In [ ]:
#This code takes the original data, the prediction of nns and the BMS, computes the rmse and mae for interpolation and extrapolation
#and saves everything into a dataframe

In [1]:
import pandas as pd
import numpy as np
import matplotlib
import matplotlib.pyplot as plt

from matplotlib.pyplot import figure
import seaborn as sns
import matplotlib.gridspec as gridspec
import ast
import sys
sys.path.append('../no_degeneracy/')
sys.path.append('../no_degeneracy/Prior/')
from mcmc import *
from parallel import *
from fit_prior import read_prior_par
from sklearn.metrics import mean_squared_error
from sklearn.metrics import root_mean_squared_error
from sklearn.metrics import mean_absolute_error

In [2]:
def clean_index(dataframe):
    dataframe.set_index('Unnamed: 0', inplace=True)
    dataframe.index.name = None
    dataframe= dataframe.reset_index(drop=True)
    return dataframe

def add_bms_pred(dataframe, bms_trace, number_param):
    VARS = ['x1',]
    x = dataframe[[c for c in VARS]].copy()
    y=dataframe.y

    if number_param==10:
        prior_par = read_prior_par('../no_degeneracy/Prior/final_prior_param_sq.named_equations.nv1.np10.2017-10-18 18:07:35.089658.dat')
    elif number_param==20:
        prior_par = read_prior_par('../no_degeneracy/Prior/final_prior_param_sq.named_equations.nv1.np20.maxs200.2024-05-10 162907.551306.dat')

    #mdl model
    minrow = bms_trace[bms_trace.H == min(bms_trace.H)].iloc[0]
    minH, minexpr, minparvals = minrow.H, minrow.expr, ast.literal_eval(minrow.parvals)

    t = Tree(
        variables=list(x.columns),
        parameters=['a%d' % i for i in range(number_param)],
        x=x, y=y,
        prior_par=prior_par,
        max_size=200,
        from_string=minexpr,
    )

    t.set_par_values(deepcopy(minparvals))

    dplot = deepcopy(dataframe)
    dplot['ybms'] = t.predict(x)
    dinterpolate=deepcopy(dplot)


    return dinterpolate

In [3]:
#Read NN and BMS data
#resolutions={'0.5x':'0.1', '1x':'0.05', '2x': '0.025', '4e-3x':'0.004' }
#resolution='1x'

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
resolution='4e-3x' #'0.5x', '1x', '2x', '4e-3'
resolutions_interp={'0.5x':'0.02', '1x':'0.01' , '2x': '0.005' , '4e-3x':'0.0008' }

resolutions={'0.5x':'0.1', '1x':'0.05' , '2x': '0.025' , '4e-3x':'0.004' }
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


functions=['tanh', 'leaky_ReLU'] #tanh, leaky_ReLU
realizations=2
N=9
sigmas=[0.0, 0.02, 0.04,0.06, 0.08, 0.1, 0.12, 0.14, 0.16, 0.18, 0.20]


runid=0
NPAR=10 #10, 20
steps=50000


rmse_nn_train=[];rmse_nn_test=[]
rmse_mdl_train=[];rmse_mdl_test=[]

mae_nn_train=[];mae_nn_test=[]
mae_mdl_train=[];mae_mdl_test=[]

n_index=[];r_index=[];sigma_index=[];function_index=[]

#Put mae and rmse of each simulation (on nn and bms) in a dataframe
for function in functions:
    for sigma in sigmas:
        for realization in range(realizations+1):
            
            #Read NN data
            #file_model='NN_no_overfit_' + function + '_sigma_' + str(sigma) + '_r_' + str(r) + '.csv'
            #file_model_hr='NN_no_overfit_' + function + '_sigma_' + str(sigma) + '_r_' + str(r) + '_res_0.01.csv'

            #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            file_model='NN_no_overfit_' + function + '_sigma_' + str(sigma) + '_r_' + str(realization) + '.csv'
            model_d='../../data/nns/' + resolution + '_resolution/approximation/' + file_model
            
            
            file_model_hr='NN_no_overfit_' + function + '_sigma_' + str(sigma) + '_r_' + str(realization) + '_res_' + \
            resolutions_interp[resolution] + '.csv'
            model_dhr='../../data/nns/' + resolution + '_resolution/inter_extrapolation/' + file_model_hr
            #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            
            #model_dhr='../data/inter_extrapolate_nns/' + file_model_hr
            dhr=pd.read_csv(model_dhr)

            #model_d='../data/1x_resolution/trained_nns/' + file_model
            d=pd.read_csv(model_d)
            

            for n in range(N+1):
                n_index.append(n);r_index.append(realization);sigma_index.append(sigma);function_index.append(function)

                #High resolution dataset
                dnhr=dhr[dhr['rep']==n]
                dnhr=dnhr[(dnhr['x1']>=-2.0) & (dnhr['x1']<=2.0)]
                dnhr=clean_index(dnhr)
                #-------------------------------------------------------------
                #train_value=1.0
                #train_border_row=dnhr[(dnhr['x1']<=1.0) & (dnhr['x1']>=0.99)] 
                #print(train_border_row)
                #train_size=train_border_row.index[0]
                #print(train_size)
                #-------------------------------------------------------------

                #Get interpolation/extrapolation border
                #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                n_points=int(len(dhr.index)/10)
                train_fraction=3/4;train_size=int(n_points*train_fraction)
                print(train_size)
                #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

                #Read BMS data
                filename='BMS_'+function+'_n_'+str(n)+'_sigma_'+str(sigma)+ '_r_' + str(realization) + '_res_'+ resolutions[resolution] +  '_trace_'+str(steps)+'_prior_'+str(NPAR)+ '.csv'
        
                #trace=pd.read_csv('../../data/MSTraces/1x_resolution/' + filename, sep=';', header=None, names=['t', 'H', 'expr', 'parvals', 'kk1', 'kk2','kk3'])
                trace_path='../../data/MSTraces/' + resolution + '_resolution/'
                trace=pd.read_csv(trace_path + filename, sep=';', header=None, names=['t', 'H', 'expr', 'parvals', 'kk1', 'kk2','kk3'])
                dinterpolate=add_bms_pred(dnhr, trace, NPAR)

                #Remove approximation points
                #-------------------------------------------------------------

                significant_figures=2
                if resolution=='4e-3x' or '2x': #It seems it is better to consider 3 for very high resolutions
                        significant_figures=3
                    
                dinterpolate=dinterpolate.round({'x1':significant_figures})
                dn=d[d['rep']==n]
                dn.set_index('Unnamed: 0', inplace=True)
                dn.index.name = None
                dn=dn.reset_index(drop=True)
                dn=dn.round({'x1':significant_figures})
                dinterpolate=dinterpolate[-dinterpolate['x1'].isin(dn['x1'].tolist() )] #cross dataframes to get only high resolution points
                #-------------------------------------------------------------

                #display(dinterpolate.loc[train_size-1])
            
                print("interpolation")
                display(dinterpolate.loc[train_size -5 : train_size - 1])
                
                print("extrapolation")
                display(dinterpolate.loc[train_size -1 : train_size + 4])
                
                #Errors
                #-----------------------------------------------------------------------------------------------------------------------
                #nns
                rmse_nn_train_i=root_mean_squared_error(dinterpolate.loc[:train_size-1]['ymodel'],dinterpolate.loc[:train_size -1]['y'])
                rmse_nn_train.append(rmse_nn_train_i)
                
                rmse_nn_test_i=root_mean_squared_error(dinterpolate.loc[train_size-1:]['ymodel'],dinterpolate.loc[train_size -1:]['y'])
                rmse_nn_test.append(rmse_nn_test_i)

                mae_nn_train_i=mean_absolute_error(dinterpolate.loc[:train_size-1]['ymodel'],dinterpolate.loc[:train_size -1]['y'])
                mae_nn_train.append(mae_nn_train_i)
            
                mae_nn_test_i=mean_absolute_error(dinterpolate.loc[train_size-1:]['ymodel'],dinterpolate.loc[train_size -1:]['y'])
                mae_nn_test.append(mae_nn_test_i)

                #bms
                try:
                    rmse_mdl_train_i=root_mean_squared_error(dinterpolate.loc[:train_size-1]['ybms'],dinterpolate.loc[:train_size-1]['y'])
                except ValueError:
                    rmse_mdl_train_i=np.inf
                rmse_mdl_train.append(rmse_mdl_train_i)

                try:
                    rmse_mdl_test_i=root_mean_squared_error(dinterpolate.loc[train_size-1:]['ybms'],dinterpolate.loc[train_size-1:]['y'])
                except ValueError:
                    rmse_mdl_test_i=np.inf
                    
                rmse_mdl_test.append(rmse_mdl_test_i)

                try:
                    mae_mdl_train_i=mean_absolute_error(dinterpolate.loc[:train_size-1]['ybms'],dinterpolate.loc[:train_size -1]['y'])
                except ValueError:
                    mae_mdl_train_i=np.inf
                    
                mae_mdl_train.append(mae_mdl_train_i)

                try:
                    mae_mdl_test_i=mean_absolute_error(dinterpolate.loc[train_size-1:]['ybms'],dinterpolate.loc[train_size -1:]['y'])
                except ValueError:
                    mae_mdl_test_i=np.inf
                
                mae_mdl_test.append(mae_mdl_test_i)
                #-----------------------------------------------------------------------------------------------------------------------              
             

              
#Save all in a dataframe      
errors_df=pd.DataFrame({'sigma':sigma_index, 'function':function_index, 'mae_nn_interp.':mae_nn_train, 'mae_nn_extrap.':mae_nn_test, 
                        'mae_mdl_interp.':mae_mdl_train, 'mae_mdl_extrap.':mae_mdl_test, 'rmse_nn_interp.':rmse_nn_train, 
                        'rmse_nn_extrap.': rmse_nn_test, 'rmse_mdl_interp.':rmse_mdl_train, 'rmse_mdl_extrap.': rmse_mdl_test, 
                        'n':n_index, 'r': r_index})
errors_df.to_csv('../../data/errors_interpolation_' + resolution + '.csv')
display(errors_df)

3750

<lambdifygenerated-27>:2: RuntimeWarning: invalid value encountered in power
  return (x1 - tan(x1*tanh(x1*(x1 + tanh(x1 + x1**x1)))))/x1
<lambdifygenerated-28>:2: RuntimeWarning: invalid value encountered in power
  return (x1 - tan(x1*tanh(x1*(x1 + tanh(x1 + x1**x1)))))/x1
<lambdifygenerated-29>:2: RuntimeWarning: invalid value encountered in power
  return (x1 - tan(x1*tanh(x1*(x1 + tanh(x1 + (2*x1)**x1)))))/x1
<lambdifygenerated-30>:2: RuntimeWarning: invalid value encountered in power
  return (x1 - tan(x1*tanh(x1*(x1 + tanh(x1 + (2*x1)**x1)))))/x1
<lambdifygenerated-31>:2: RuntimeWarning: invalid value encountered in power
  return (x1 - tan(x1*tanh(x1*(x1 + tanh(x1 + (2*x1)**x1)))))/x1
<lambdifygenerated-32>:2: RuntimeWarning: invalid value encountered in power
  return (x1 - tan(x1*tanh(x1*(x1 + tanh(x1 + (2*x1)**x1)))))/x1
<lambdifygenerated-33>:2: RuntimeWarning: invalid value encountered in power
  return (x1 - tan(x1*tanh(x1*(x1 + tanh(x1 + (x1 + x1**x1)**x1)))))/x1
<lambdifygenerated-34>:2: RuntimeWarning: invalid value encountered in power
  return (x1 - tan(x1*tanh(x1*(x1 + tanh(x1 + (x1 + x1**x1)**x1)))))/x1
<lambdifygenerated-35>:2: RuntimeWarning: invalid value encountered in power
  return (x1 - tan(x1*tanh(x1*(x1 + tanh(x1 + (x1 + abs(x1)**x1)**x1)))))/x1
<lambdifygenerated-36>:2: RuntimeWarning: invalid value encountered in power
  return (x1 - tan(x1*tanh(x1*(x1 + tanh(x1 + (x1 + abs(x1)**x1)**x1)))))/x1
<lambdifygenerated-37>:2: RuntimeWarning: invalid value encountered in power
  return (x1 - tan(x1*tanh(x1*(x1 + tanh(x1 + (x1 + 1)**x1)))))/x1
<lambdifygenerated-38>:2: RuntimeWarning: invalid value encountered in power
  return (x1 - tan(x1*tanh(x1*(x1 + tanh(x1 + (x1 + 1)**x1)))))/x1
<lambdifygenerated-39>:2: RuntimeWarning: divide by zero encountered in power
  return (x1 - tan(x1*tanh(x1*(x1 + tanh(x1 + (x1 + abs(_a6_/x1)**x1)**x1)))))/x1
<lambdifygenerated-39>:2: RuntimeWarning: invalid value encountered in power
  return (x1 - tan(x1*tanh(x1*(x1 + tanh(x1 + (x1 + abs(_a6_/x1)**x1)**x1)))))/x1
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-40>:2: RuntimeWarning: divide by zero encountered in power
  return (x1 - tan(x1*tanh(x1*(x1 + tanh(x1 + (x1 + abs(_a6_/x1)**x1)**x1)))))/x1
<lambdifygenerated-41>:2: RuntimeWarning: invalid value encountered in power
  return (x1 - tan(x1*tanh(x1*(x1 + tanh(x1 + (x1 + abs(_a6_/_a5_)**x1)**x1)))))/x1
<lambdifygenerated-42>:2: RuntimeWarning: invalid value encountered in power
  return (x1 - tan(x1*tanh(x1*(x1 + tanh(x1 + (x1 + abs(_a6_/_a5_)**x1)**x1)))))/x1
<lambdifygenerated-43>:2: RuntimeWarning: invalid value encountered in power
  return (x1 - tan(x1*tanh(x1*(x1 + tanh(x1 + (x1 + abs(_a6_/_a5_)**x1)**x1)))))/x1
<lambdifygenerated-44>:2: RuntimeWarning: invalid value encountered in power
  return (x1 - tan(x1*tanh(x1*(x1 + tanh(x1 + (x1 + abs(_a6_/_a5_)**x1)**x1)))))/x1
<lambdifygenerated-45>:2: RuntimeWarning: invalid value encountered in power
  return (x1 - tan(x1*tanh(x1*(x1 + tanh(x1 + (x1 + abs(_a6_/_a5_)**x1)**(2*x1))))))/x1
<lambdifygenerated-46>:2: RuntimeWarning: invalid value encountered in power
  return (x1 - tan(x1*tanh(x1*(x1 + tanh(x1 + (x1 + abs(_a6_/_a5_)**x1)**(2*x1))))))/x1
<lambdifygenerated-47>:2: RuntimeWarning: invalid value encountered in power
  return (x1 - tan(x1*tanh(x1*(x1 + tanh(x1 + (x1 + abs(_a6_/_a5_)**x1)**(_a5_ + x1))))))/x1
<lambdifygenerated-48>:2: RuntimeWarning: invalid value encountered in power
  return (x1 - tan(x1*tanh(x1*(x1 + tanh(x1 + (x1 + abs(_a6_/_a5_)**x1)**(_a5_ + x1))))))/x1
<lambdifygenerated-49>:2: RuntimeWarning: invalid value encountered in power
  return (x1 - tan(x1*tanh(x1*(x1 + tanh(x1 + (x1 + abs(_a6_/_a5_)**x1)**(_a5_ - x1))))))/x1
<lambdifygenerated-50>:2: RuntimeWarning: invalid value encountered in power
  return (x1 - tan(x1*tanh(x1*(x1 + tanh(x1 + (x1 + abs(_a6_/_a5_)**x1)**(_a5_ - x1))))))/x1
<lambdifygenerated-51>:2: RuntimeWarning: invalid value encountered in power
  return (x1 - tan(x1*tanh(x1*(x1 + tanh(x1 + (x1 + abs(_a6_/_a5_)**x1)**(_a5_ - _a7_))))))/x1
<lambdifygenerated-53>:2: RuntimeWarning: invalid value encountered in power
  return (x1 - tan(x1*tanh(x1*(x1 + tanh(x1 + x1*(x1 + abs(_a6_/_a5_)**x1)**(_a5_ - _a7_)/_a7_)))))/x1
<lambdifygenerated-55>:2: RuntimeWarning: invalid value encountered in power
  return (x1 - tan(x1*tanh(x1*(x1 + tanh(x1 + 2*x1*(x1 + abs(_a6_/_a5_)**x1)**(_a5_ - _a7_)/_a7_)))))/x1
<lambdifygenerated-59>:2: RuntimeWarning: invalid value encountered in power
  return (x1 - tan(x1*tanh(x1*(x1 + tanh(x1 + (-_a6_ + x1)*(x1 + abs(_a6_/_a5_)**x1)**(_a5_ - _a7_)/_a7_)))))/x1
<lambdifygenerated-63>:2: RuntimeWarning: invalid value encountered in power
  return (x1 - tan(x1*tanh(x1*(x1 + tanh(_a5_ + (-_a6_ + x1)*(x1 + abs(_a6_/_a5_)**x1)**(_a5_ - _a7_)/_a7_)))))/x1
<lambdifygenerated-65>:2: RuntimeWarning: invalid value encountered in power
  return (x1 - tan(x1*tanh(x1*(x1**2 + tanh(_a5_ + (-_a6_ + x1)*(x1 + abs(_a6_/_a5_)**x1)**(_a5_ - _a7_)/_a7_)))))/x1
<lambdifygenerated-67>:2: RuntimeWarning: invalid value encountered in power
  return (x1 - tan(x1*tanh(x1*(_a2_*x1 + tanh(_a5_ + (-_a6_ + x1)*(x1 + abs(_a6_/_a5_)**x1)**(_a5_ - _a7_)/_a7_)))))/x1
<lambdifygenerated-69>:2: RuntimeWarning: invalid value encountered in power
  return (x1 - tan(x1*tanh(x1*(_a2_*_a6_ + tanh(_a5_ + (-_a6_ + x1)*(x1 + abs(_a6_/_a5_)**x1)**(_a5_ - _a7_)/_a7_)))))/x1
<lambdifygenerated-71>:2: RuntimeWarning: invalid value encountered in power
  return (x1 - tan(x1*tanh(_a1_*(_a2_*_a6_ + tanh(_a5_ + (-_a6_ + x1)*(x1 + abs(_a6_/_a5_)**x1)**(_a5_ - _a7_)/_a7_)))))/x1
<lambdifygenerated-73>:2: RuntimeWarning: invalid value encountered in power
  return (x1 - tan(_a3_*tanh(_a1_*(_a2_*_a6_ + tanh(_a5_ + (-_a6_ + x1)*(x1 + abs(_a6_/_a5_)**x1)**(_a5_ - _a7_)/_a7_)))))/x1
<lambdifygenerated-75>:2: RuntimeWarning: invalid value encountered in power
  return (x1**2 - tan(_a3_*tanh(_a1_*(_a2_*_a6_ + tanh(_a5_ + (-_a6_ + x1)*(x1 + abs(_a6_/_a5_)**x1)**(_a5_ - _a7_)/_a7_)))))/x1
<lambdifygenerated-77>:2: RuntimeWarning: invalid value encountered in power
  return (_a4_*x1 - tan(_a3_*tanh(_a1_*(_a2_*_a6_ + tanh(_a5_ + (-_a6_ + x1)*(x1 + abs(_a6_/_a5_)**x1)**(_a5_ - _a7_)/_a7_)))))/x1
<lambdifygenerated-79>:2: RuntimeWarning: invalid value encountered in power
  return (2*_a4_*x1 - tan(_a3_*tanh(_a1_*(_a2_*_a6_ + tanh(_a5_ + (-_a6_ + x1)*(x1 + abs(_a6_/_a5_)**x1)**(_a5_ - _a7_)/_a7_)))))/x1

interpolation

<lambdifygenerated-81>:2: RuntimeWarning: invalid value encountered in sqrt
  return (_a4_*(sqrt(x1) + x1) - tan(_a3_*tanh(_a1_*(_a2_*_a6_ + tanh(_a5_ + (-_a6_ + x1)*(x1 + abs(_a6_/_a5_)**x1)**(_a5_ - _a7_)/_a7_)))))/x1
<lambdifygenerated-81>:2: RuntimeWarning: invalid value encountered in power
  return (_a4_*(sqrt(x1) + x1) - tan(_a3_*tanh(_a1_*(_a2_*_a6_ + tanh(_a5_ + (-_a6_ + x1)*(x1 + abs(_a6_/_a5_)**x1)**(_a5_ - _a7_)/_a7_)))))/x1
<lambdifygenerated-82>:2: RuntimeWarning: invalid value encountered in sqrt
  return (_a4_*(sqrt(x1) + x1) - tan(_a3_*tanh(_a1_*(_a2_*_a6_ + tanh(_a5_ + (-_a6_ + x1)*(x1 + abs(_a6_/_a5_)**x1)**(_a5_ - _a7_)/_a7_)))))/x1
<lambdifygenerated-83>:2: RuntimeWarning: invalid value encountered in sqrt
  return (_a4_*(sqrt(2)*sqrt(x1) + x1) - tan(_a3_*tanh(_a1_*(_a2_*_a6_ + tanh(_a5_ + (-_a6_ + x1)*(x1 + abs(_a6_/_a5_)**x1)**(_a5_ - _a7_)/_a7_)))))/x1
<lambdifygenerated-83>:2: RuntimeWarning: invalid value encountered in power
  return (_a4_*(sqrt(2)*sqrt(x1) + x1) - tan(_a3_*tanh(_a1_*(_a2_*_a6_ + tanh(_a5_ + (-_a6_ + x1)*(x1 + abs(_a6_/_a5_)**x1)**(_a5_ - _a7_)/_a7_)))))/x1
<lambdifygenerated-84>:2: RuntimeWarning: invalid value encountered in sqrt
  return (_a4_*(sqrt(2)*sqrt(x1) + x1) - tan(_a3_*tanh(_a1_*(_a2_*_a6_ + tanh(_a5_ + (-_a6_ + x1)*(x1 + abs(_a6_/_a5_)**x1)**(_a5_ - _a7_)/_a7_)))))/x1
<lambdifygenerated-85>:2: RuntimeWarning: invalid value encountered in sqrt
  return (_a4_*(x1 + sqrt(_a0_ + x1)) - tan(_a3_*tanh(_a1_*(_a2_*_a6_ + tanh(_a5_ + (-_a6_ + x1)*(x1 + abs(_a6_/_a5_)**x1)**(_a5_ - _a7_)/_a7_)))))/x1
<lambdifygenerated-85>:2: RuntimeWarning: invalid value encountered in power
  return (_a4_*(x1 + sqrt(_a0_ + x1)) - tan(_a3_*tanh(_a1_*(_a2_*_a6_ + tanh(_a5_ + (-_a6_ + x1)*(x1 + abs(_a6_/_a5_)**x1)**(_a5_ - _a7_)/_a7_)))))/x1
<lambdifygenerated-86>:2: RuntimeWarning: invalid value encountered in sqrt
  return (_a4_*(x1 + sqrt(_a0_ + x1)) - tan(_a3_*tanh(_a1_*(_a2_*_a6_ + tanh(_a5_ + (-_a6_ + x1)*(x1 + abs(_a6_/_a5_)**x1)**(_a5_ - _a7_)/_a7_)))))/x1
<lambdifygenerated-87>:2: RuntimeWarning: invalid value encountered in sqrt
  return (_a4_*(x1 + sqrt(_a0_ + x1)) - tan(_a3_*tanh(_a1_*(_a2_*_a6_ + tanh(_a5_ + (-_a6_ + x1)*(x1 + abs(_a6_/_a5_)**x1)**(_a5_ - _a7_)/_a7_)))))/x1
<lambdifygenerated-88>:2: RuntimeWarning: invalid value encountered in sqrt
  return (_a4_*(x1 + sqrt(_a0_ + x1)) - tan(_a3_*tanh(_a1_*(_a2_*_a6_ + tanh(_a5_ + (-_a6_ + x1)*(x1 + abs(_a6_/_a5_)**x1)**(_a5_ - _a7_)/_a7_)))))/x1
<lambdifygenerated-89>:2: RuntimeWarning: invalid value encountered in sqrt
  return (_a4_*(sqrt(_a0_ + x1) + tan(x1)) - tan(_a3_*tanh(_a1_*(_a2_*_a6_ + tanh(_a5_ + (-_a6_ + x1)*(x1 + abs(_a6_/_a5_)**x1)**(_a5_ - _a7_)/_a7_)))))/x1
<lambdifygenerated-89>:2: RuntimeWarning: invalid value encountered in power
  return (_a4_*(sqrt(_a0_ + x1) + tan(x1)) - tan(_a3_*tanh(_a1_*(_a2_*_a6_ + tanh(_a5_ + (-_a6_ + x1)*(x1 + abs(_a6_/_a5_)**x1)**(_a5_ - _a7_)/_a7_)))))/x1
<lambdifygenerated-90>:2: RuntimeWarning: invalid value encountered in sqrt
  return (_a4_*(sqrt(_a0_ + x1) + tan(x1)) - tan(_a3_*tanh(_a1_*(_a2_*_a6_ + tanh(_a5_ + (-_a6_ + x1)*(x1 + abs(_a6_/_a5_)**x1)**(_a5_ - _a7_)/_a7_)))))/x1
<lambdifygenerated-91>:2: RuntimeWarning: invalid value encountered in sqrt
  return (_a4_*(sqrt(_a0_ + x1) + tan(_a5_)) - tan(_a3_*tanh(_a1_*(_a2_*_a6_ + tanh(_a5_ + (-_a6_ + x1)*(x1 + abs(_a6_/_a5_)**x1)**(_a5_ - _a7_)/_a7_)))))/x1
<lambdifygenerated-91>:2: RuntimeWarning: invalid value encountered in power
  return (_a4_*(sqrt(_a0_ + x1) + tan(_a5_)) - tan(_a3_*tanh(_a1_*(_a2_*_a6_ + tanh(_a5_ + (-_a6_ + x1)*(x1 + abs(_a6_/_a5_)**x1)**(_a5_ - _a7_)/_a7_)))))/x1
<lambdifygenerated-92>:2: RuntimeWarning: invalid value encountered in sqrt
  return (_a4_*(sqrt(_a0_ + x1) + tan(_a5_)) - tan(_a3_*tanh(_a1_*(_a2_*_a6_ + tanh(_a5_ + (-_a6_ + x1)*(x1 + abs(_a6_/_a5_)**x1)**(_a5_ - _a7_)/_a7_)))))/x1
<lambdifygenerated-93>:2: RuntimeWarning: invalid value encountered in sqrt
  return _a4_*(sqrt(_a0_ + x1) + tan(_a5_)) - tan(_a3_*tanh(_a1_*(_a2_*_a6_ + tanh(_a5_ + (-_a6_ + x1)*(x1 + abs(_a6_/_a5_)**x1)**(_a5_ - _a7_)/_a7_))))
<lambdifygenerated-93>:2: RuntimeWarning: invalid value encountered in power
  return _a4_*(sqrt(_a0_ + x1) + tan(_a5_)) - tan(_a3_*tanh(_a1_*(_a2_*_a6_ + tanh(_a5_ + (-_a6_ + x1)*(x1 + abs(_a6_/_a5_)**x1)**(_a5_ - _a7_)/_a7_))))
<lambdifygenerated-94>:2: RuntimeWarning: invalid value encountered in sqrt
  return _a4_*(sqrt(_a0_ + x1) + tan(_a5_)) - tan(_a3_*tanh(_a1_*(_a2_*_a6_ + tanh(_a5_ + (-_a6_ + x1)*(x1 + abs(_a6_/_a5_)**x1)**(_a5_ - _a7_)/_a7_))))
<lambdifygenerated-95>:2: RuntimeWarning: invalid value encountered in sqrt
  return x1*(_a4_*(sqrt(_a0_ + x1) + tan(_a5_)) - tan(_a3_*tanh(_a1_*(_a2_*_a6_ + tanh(_a5_ + (-_a6_ + x1)*(x1 + abs(_a6_/_a5_)**x1)**(_a5_ - _a7_)/_a7_)))))/_a1_
<lambdifygenerated-95>:2: RuntimeWarning: invalid value encountered in power
  return x1*(_a4_*(sqrt(_a0_ + x1) + tan(_a5_)) - tan(_a3_*tanh(_a1_*(_a2_*_a6_ + tanh(_a5_ + (-_a6_ + x1)*(x1 + abs(_a6_/_a5_)**x1)**(_a5_ - _a7_)/_a7_)))))/_a1_
<lambdifygenerated-96>:2: RuntimeWarning: invalid value encountered in sqrt
  return x1*(_a4_*(sqrt(_a0_ + x1) + tan(_a5_)) - tan(_a3_*tanh(_a1_*(_a2_*_a6_ + tanh(_a5_ + (-_a6_ + x1)*(x1 + abs(_a6_/_a5_)**x1)**(_a5_ - _a7_)/_a7_)))))/_a1_
<lambdifygenerated-97>:2: RuntimeWarning: invalid value encountered in sqrt
  return _a7_*(_a4_*(sqrt(_a0_ + x1) + tan(_a5_)) - tan(_a3_*tanh(_a1_*(_a2_*_a6_ + tanh(_a5_ + (-_a6_ + x1)*(x1 + abs(_a6_/_a5_)**x1)**(_a5_ - _a7_)/_a7_)))))/_a1_
<lambdifygenerated-97>:2: RuntimeWarning: invalid value encountered in power
  return _a7_*(_a4_*(sqrt(_a0_ + x1) + tan(_a5_)) - tan(_a3_*tanh(_a1_*(_a2_*_a6_ + tanh(_a5_ + (-_a6_ + x1)*(x1 + abs(_a6_/_a5_)**x1)**(_a5_ - _a7_)/_a7_)))))/_a1_
<lambdifygenerated-98>:2: RuntimeWarning: invalid value encountered in sqrt
  return _a7_*(_a4_*(sqrt(_a0_ + x1) + tan(_a5_)) - tan(_a3_*tanh(_a1_*(_a2_*_a6_ + tanh(_a5_ + (-_a6_ + x1)*(x1 + abs(_a6_/_a5_)**x1)**(_a5_ - _a7_)/_a7_)))))/_a1_
<lambdifygenerated-99>:2: RuntimeWarning: invalid value encountered in sqrt
  return _a7_*(_a4_*(sqrt(_a0_ + x1) + tan(_a5_)) - tan(_a3_*tanh(_a1_*(_a2_*_a6_ + tanh(_a5_ + (-_a6_ + x1)*(x1 + abs(_a6_/_a5_)**x1)**(_a5_ - _a7_)/_a7_)))))/_a1_
<lambdifygenerated-100>:2: RuntimeWarning: invalid value encountered in sqrt
  return _a7_*(_a4_*(sqrt(_a0_ + x1) + tan(_a5_)) - tan(_a3_*tanh(_a1_*(_a2_*_a6_ + tanh(_a5_ + (-_a6_ + x1)*(x1 + abs(_a6_/_a5_)**x1)**(_a5_ - _a7_)/_a7_)))))/_a1_
<lambdifygenerated-101>:2: RuntimeWarning: invalid value encountered in sqrt
  return _a7_*(_a4_*(sqrt(_a0_ + x1) + tan(_a5_)) - tan(_a3_*tanh(_a1_*(_a2_*_a6_ + tanh(_a5_ + (-_a6_ + x1)*(x1 + abs(_a6_/_a5_)**x1)**(_a5_ - _a7_)/_a7_)))))/_a1_
<lambdifygenerated-101>:2: RuntimeWarning: invalid value encountered in power
  return _a7_*(_a4_*(sqrt(_a0_ + x1) + tan(_a5_)) - tan(_a3_*tanh(_a1_*(_a2_*_a6_ + tanh(_a5_ + (-_a6_ + x1)*(x1 + abs(_a6_/_a5_)**x1)**(_a5_ - _a7_)/_a7_)))))/_a1_
<lambdifygenerated-102>:2: RuntimeWarning: invalid value encountered in sqrt
  return _a7_*(_a4_*(sqrt(_a0_ + x1) + tan(_a5_)) - tan(_a3_*tanh(_a1_*(_a2_*_a6_ + tanh(_a5_ + (-_a6_ + x1)*(x1 + abs(_a6_/_a5_)**x1)**(_a5_ - _a7_)/_a7_)))))/_a1_

         x1         y  rep    ymodel      ybms
3745  0.997  0.987381  0.0  0.982325  0.987785
3746  0.998  0.987426  0.0  0.982335  0.987832
3747  0.998  0.987470  0.0  0.982345  0.987880
3748  0.999  0.987515  0.0  0.982355  0.987927

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.987604  0.0  0.982375  0.988022
3751  1.002  0.987648  0.0  0.982385  0.988070
3752  1.002  0.987692  0.0  0.982395  0.988117
3753  1.003  0.987737  0.0  0.982404  0.988165

3750

<lambdifygenerated-139>:2: RuntimeWarning: invalid value encountered in log
  return tan(sin(x1**2*(x1**2*(_a6_ + x1 + sinh(2*x1 + log(x1))) + x1))/x1)
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-140>:2: RuntimeWarning: invalid value encountered in log
  return tan(sin(x1**2*(x1**2*(_a6_ + x1 + sinh(2*x1 + log(x1))) + x1))/x1)
<lambdifygenerated-143>:2: RuntimeWarning: invalid value encountered in log
  return tan(sin(x1**2*(x1**2*(_a6_ + x1 + sinh(_a3_ + x1 + log(_a1_))) + x1))/x1)
<lambdifygenerated-145>:2: RuntimeWarning: invalid value encountered in log
  return tan(sin(x1**2*(x1**2*(_a6_ + x1 + sinh(_a3_ + x1**2 + log(_a1_))) + x1))/x1)
<lambdifygenerated-149>:2: RuntimeWarning: invalid value encountered in log
  return tan(sin(x1**2*(x1**2*(_a6_ + x1 + sinh(_a3_ + _a6_*x1 + log(_a1_))) + x1))/x1)
<lambdifygenerated-151>:2: RuntimeWarning: invalid value encountered in log
  return tan(sin(x1**2*(x1**2*(_a6_ + x1**2 + sinh(_a3_ + _a6_*x1 + log(_a1_))) + x1))/x1)
<lambdifygenerated-155>:2: RuntimeWarning: invalid value encountered in log
  return tan(sin(x1**2*(x1**2*(_a6_*x1 + _a6_ + sinh(_a3_ + _a6_*x1 + log(_a1_))) + x1))/x1)
<lambdifygenerated-157>:2: RuntimeWarning: invalid value encountered in log
  return tan(sin(x1**2*(_a6_*x1*(_a6_*x1 + _a6_ + sinh(_a3_ + _a6_*x1 + log(_a1_))) + x1))/x1)
<lambdifygenerated-159>:2: RuntimeWarning: invalid value encountered in log
  return tan(sin(x1**2*(2*_a6_*x1*(_a6_*x1 + _a6_ + sinh(_a3_ + _a6_*x1 + log(_a1_))) + x1))/x1)
<lambdifygenerated-161>:2: RuntimeWarning: invalid value encountered in log
  return tan(sin(x1**2*(_a6_*(x1 + 1)*(_a6_*x1 + _a6_ + sinh(_a3_ + _a6_*x1 + log(_a1_))) + x1))/x1)
<lambdifygenerated-163>:2: RuntimeWarning: invalid value encountered in log
  return tan(sin(x1**2*(_a6_*(x1 + tanh(x1)/x1)*(_a6_*x1 + _a6_ + sinh(_a3_ + _a6_*x1 + log(_a1_))) + x1))/x1)
<lambdifygenerated-165>:2: RuntimeWarning: invalid value encountered in log
  return tan(sin(x1**2*(_a6_*(x1 + tanh(x1**2)/x1)*(_a6_*x1 + _a6_ + sinh(_a3_ + _a6_*x1 + log(_a1_))) + x1))/x1)
<lambdifygenerated-167>:2: RuntimeWarning: invalid value encountered in log
  return tan(sin(x1**2*(_a6_*(x1 + tanh(2*x1**2)/x1)*(_a6_*x1 + _a6_ + sinh(_a3_ + _a6_*x1 + log(_a1_))) + x1))/x1)
<lambdifygenerated-169>:2: RuntimeWarning: invalid value encountered in log
  return tan(sin(x1**2*(_a6_*(x1 + tanh(x1*(_a4_ + x1))/x1)*(_a6_*x1 + _a6_ + sinh(_a3_ + _a6_*x1 + log(_a1_))) + x1))/x1)
<lambdifygenerated-171>:2: RuntimeWarning: invalid value encountered in log
  return tan(sin(x1**2*(_a6_*(x1 + tanh(x1*(_a4_ + x1**2))/x1)*(_a6_*x1 + _a6_ + sinh(_a3_ + _a6_*x1 + log(_a1_))) + x1))/x1)
<lambdifygenerated-173>:2: RuntimeWarning: invalid value encountered in log
  return tan(sin(x1**2*(_a6_*(x1 + tanh(x1*(_a0_*x1 + _a4_))/x1)*(_a6_*x1 + _a6_ + sinh(_a3_ + _a6_*x1 + log(_a1_))) + x1))/x1)

interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.053138  1.0  0.052363  0.048032
3746  0.998  0.053057  1.0  0.052291  0.047899
3747  0.998  0.052975  1.0  0.052220  0.047766
3748  0.999  0.052894  1.0  0.052149  0.047633

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.052733  1.0  0.052006  0.047366
3751  1.002  0.052652  1.0  0.051936  0.047233
3752  1.002  0.052571  1.0  0.051865  0.047099
3753  1.003  0.052491  1.0  0.051795  0.046966

3750

<lambdifygenerated-215>:2: RuntimeWarning: invalid value encountered in power
  return x1**2*tanh(2*x1 + x1**x1)**2 + x1
<lambdifygenerated-216>:2: RuntimeWarning: invalid value encountered in power
  return x1**2*tanh(2*x1 + x1**x1)**2 + x1
<lambdifygenerated-257>:2: RuntimeWarning: invalid value encountered in power
  return x1**2*tanh(2*x1 + (_a5_**2*(_a0_*_a7_**2/_a4_**2 + x1)**2*sin(_a1_*_a4_*(_a4_ + x1 + x1**x1))**2)**x1)**2 + x1
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-258>:2: RuntimeWarning: invalid value encountered in power
  return x1**2*tanh(2*x1 + (_a5_**2*(_a0_*_a7_**2/_a4_**2 + x1)**2*sin(_a1_*_a4_*(_a4_ + x1 + x1**x1))**2)**x1)**2 + x1
<lambdifygenerated-259>:2: RuntimeWarning: invalid value encountered in power
  return x1**2*tanh(2*x1 + (_a5_**2*(_a0_*_a7_**2/_a4_**2 + x1)**2*sin(_a1_*_a4_*(_a2_**x1 + _a4_ + x1))**2)**x1)**2 + x1

interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.277484  2.0  0.281722  0.266521
3746  0.998  0.277627  2.0  0.281909  0.266335
3747  0.998  0.277770  2.0  0.282095  0.266145
3748  0.999  0.277912  2.0  0.282279  0.265950

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.278193  2.0  0.282646  0.265547
3751  1.002  0.278333  2.0  0.282829  0.265339
3752  1.002  0.278471  2.0  0.283010  0.265127
3753  1.003  0.278610  2.0  0.283190  0.264910

3750

<lambdifygenerated-305>:2: RuntimeWarning: invalid value encountered in power
  return x1 + x1**x1
<lambdifygenerated-306>:2: RuntimeWarning: invalid value encountered in power
  return x1 + x1**x1
<lambdifygenerated-309>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (tan(x1)/x1)**x1
<lambdifygenerated-310>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (tan(x1)/x1)**x1
<lambdifygenerated-313>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (-tan(tanh(x1))/x1)**x1
<lambdifygenerated-314>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (-tan(tanh(x1))/x1)**x1
<lambdifygenerated-315>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (-tan(tanh(2*x1))/x1)**x1
<lambdifygenerated-316>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (-tan(tanh(2*x1))/x1)**x1
<lambdifygenerated-317>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (-tan(tanh(x1 + 1))/x1)**x1
<lambdifygenerated-318>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (-tan(tanh(x1 + 1))/x1)**x1
<lambdifygenerated-319>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (-tan(tanh(x1 + cos(x1)/x1))/x1)**x1
<lambdifygenerated-320>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (-tan(tanh(x1 + cos(x1)/x1))/x1)**x1
<lambdifygenerated-321>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (-tan(tanh(x1 + cos(2*x1)/x1))/x1)**x1
<lambdifygenerated-322>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (-tan(tanh(x1 + cos(2*x1)/x1))/x1)**x1
<lambdifygenerated-323>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (-tan(tanh(x1 + cos(2*x1)/x1))/x1)**x1
<lambdifygenerated-324>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (-tan(tanh(x1 + cos(2*x1)/x1))/x1)**x1
<lambdifygenerated-325>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (-tan(tanh(x1 + cos(_a1_ + x1)/x1))/x1)**x1
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-326>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (-tan(tanh(x1 + cos(_a1_ + x1)/x1))/x1)**x1
<lambdifygenerated-327>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (-tan(tanh(x1 - cos(_a1_ + x1)/x1))/x1)**x1
<lambdifygenerated-328>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (-tan(tanh(x1 - cos(_a1_ + x1)/x1))/x1)**x1
<lambdifygenerated-329>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (-tan(tanh(x1 - 1/2*cos(_a1_ + x1)/x1))/x1)**x1
<lambdifygenerated-330>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (-tan(tanh(x1 - 1/2*cos(_a1_ + x1)/x1))/x1)**x1
<lambdifygenerated-331>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (-tan(tanh(x1 + cos(_a1_ + x1)/(-_a2_ - x1)))/x1)**x1
<lambdifygenerated-332>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (-tan(tanh(x1 + cos(_a1_ + x1)/(-_a2_ - x1)))/x1)**x1
<lambdifygenerated-333>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (-tan(tanh(x1 + cos(_a1_ + x1)/(-_a2_ - x1**2)))/x1)**x1
<lambdifygenerated-334>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (-tan(tanh(x1 + cos(_a1_ + x1)/(-_a2_ - x1**2)))/x1)**x1
<lambdifygenerated-335>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (-tan(tanh(x1 + cos(_a1_ + x1)/(-_a2_ - x1)))/x1)**x1
<lambdifygenerated-336>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (-tan(tanh(x1 + cos(_a1_ + x1)/(-_a2_ - x1)))/x1)**x1
<lambdifygenerated-337>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (-tan(tanh(x1 + cos(_a1_ + x1)/(-_a2_ - x1**2)))/x1)**x1
<lambdifygenerated-338>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (-tan(tanh(x1 + cos(_a1_ + x1)/(-_a2_ - x1**2)))/x1)**x1
<lambdifygenerated-339>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (-tan(tanh(x1 + cos(_a1_ + x1)/(-_a2_ - sin(x1)**2)))/x1)**x1
<lambdifygenerated-340>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (-tan(tanh(x1 + cos(_a1_ + x1)/(-_a2_ - sin(x1)**2)))/x1)**x1
<lambdifygenerated-341>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (-tan(tanh(x1 + cos(_a1_ + x1)/(-_a2_ - sin(x1**2)**2)))/x1)**x1
<lambdifygenerated-342>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (-tan(tanh(x1 + cos(_a1_ + x1)/(-_a2_ - sin(x1**2)**2)))/x1)**x1
<lambdifygenerated-343>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (-tan(tanh(x1 + cos(_a1_ + x1)/(-_a2_ - sin(_a6_*x1)**2)))/x1)**x1
<lambdifygenerated-344>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (-tan(tanh(x1 + cos(_a1_ + x1)/(-_a2_ - sin(_a6_*x1)**2)))/x1)**x1
<lambdifygenerated-345>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (-tan(tanh(x1 + cos(_a1_ + x1)/(-_a2_ - sin(_a6_*x1)**2)))/x1)**x1
<lambdifygenerated-346>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (-tan(tanh(x1 + cos(_a1_ + x1)/(-_a2_ - sin(_a6_*x1)**2)))/x1)**x1
<lambdifygenerated-347>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (-tan(tanh(x1 + cos(_a1_ + x1)/(-_a2_ - 1/2*sin(_a6_*x1)**2)))/x1)**x1
<lambdifygenerated-348>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (-tan(tanh(x1 + cos(_a1_ + x1)/(-_a2_ - 1/2*sin(_a6_*x1)**2)))/x1)**x1
<lambdifygenerated-349>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (-tan(tanh(x1 + cos(_a1_ + x1)/(-_a2_ - x1*sin(_a6_*x1)**2/(_a5_ + x1))))/x1)**x1
<lambdifygenerated-350>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (-tan(tanh(x1 + cos(_a1_ + x1)/(-_a2_ - x1*sin(_a6_*x1)**2/(_a5_ + x1))))/x1)**x1
<lambdifygenerated-351>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (-tan(tanh(x1 + cos(_a1_ + x1)/(-_a2_ - x1*sin(_a6_*x1)**2/(_a5_ + x1))))/x1)**x1
<lambdifygenerated-352>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (-tan(tanh(x1 + cos(_a1_ + x1)/(-_a2_ - x1*sin(_a6_*x1)**2/(_a5_ + x1))))/x1)**x1
<lambdifygenerated-353>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (-tan(tanh(x1 + cos(_a1_ + x1)/(-_a2_ - x1**x1*sin(_a6_*x1)**2/(_a5_ + x1))))/x1)**x1
<lambdifygenerated-354>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (-tan(tanh(x1 + cos(_a1_ + x1)/(-_a2_ - x1**x1*sin(_a6_*x1)**2/(_a5_ + x1))))/x1)**x1
<lambdifygenerated-355>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (-tan(tanh(x1 + cos(_a1_ + x1)/(-_a2_ - _a7_**x1*sin(_a6_*x1)**2/(_a5_ + x1))))/x1)**x1
<lambdifygenerated-356>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (-tan(tanh(x1 + cos(_a1_ + x1)/(-_a2_ - _a7_**x1*sin(_a6_*x1)**2/(_a5_ + x1))))/x1)**x1
<lambdifygenerated-357>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (-tan(tanh(x1 + cos(_a1_ + x1)/(-_a2_ - _a7_**x1*sin(_a6_*x1)**2/(_a5_ + x1))))/x1)**x1
<lambdifygenerated-358>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (-tan(tanh(x1 + cos(_a1_ + x1)/(-_a2_ - _a7_**x1*sin(_a6_*x1)**2/(_a5_ + x1))))/x1)**x1
<lambdifygenerated-359>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (-tan(tanh(_a4_ + cos(_a1_ + x1)/(-_a2_ - _a7_**x1*sin(_a6_*x1)**2/(_a5_ + x1))))/x1)**x1
<lambdifygenerated-360>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (-tan(tanh(_a4_ + cos(_a1_ + x1)/(-_a2_ - _a7_**x1*sin(_a6_*x1)**2/(_a5_ + x1))))/x1)**x1
<lambdifygenerated-361>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (-tan(tanh(_a4_ + cos(_a1_ + x1)/(-_a2_ - _a7_**x1*sin(_a6_*x1)**2/(_a5_ + x1))))/_a0_)**x1
<lambdifygenerated-362>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (-tan(tanh(_a4_ + cos(_a1_ + x1)/(-_a2_ - _a7_**x1*sin(_a6_*x1)**2/(_a5_ + x1))))/_a0_)**x1
<lambdifygenerated-363>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (-tan(tanh(_a4_ + cos(_a1_ + x1)/(-_a2_ - _a7_**x1*sin(_a6_*x1)**2/(_a5_ + x1))))/_a0_)**_a3_
<lambdifygenerated-365>:2: RuntimeWarning: invalid value encountered in power
  return x1**2 + (-tan(tanh(_a4_ + cos(_a1_ + x1)/(-_a2_ - _a7_**x1*sin(_a6_*x1)**2/(_a5_ + x1))))/_a0_)**_a3_
<lambdifygenerated-367>:2: RuntimeWarning: invalid value encountered in power
  return _a4_*x1 + (-tan(tanh(_a4_ + cos(_a1_ + x1)/(-_a2_ - _a7_**x1*sin(_a6_*x1)**2/(_a5_ + x1))))/_a0_)**_a3_
<lambdifygenerated-369>:2: RuntimeWarning: invalid value encountered in power
  return _a4_ + (-tan(tanh(_a4_ + cos(_a1_ + x1)/(-_a2_ - _a7_**x1*sin(_a6_*x1)**2/(_a5_ + x1))))/_a0_)**_a3_
<lambdifygenerated-371>:2: RuntimeWarning: invalid value encountered in power
  return _a4_*sin(x1)/x1 + (-tan(tanh(_a4_ + cos(_a1_ + x1)/(-_a2_ - _a7_**x1*sin(_a6_*x1)**2/(_a5_ + x1))))/_a0_)**_a3_
<lambdifygenerated-373>:2: RuntimeWarning: invalid value encountered in power
  return _a4_*sin(x1**2)/x1 + (-tan(tanh(_a4_ + cos(_a1_ + x1)/(-_a2_ - _a7_**x1*sin(_a6_*x1)**2/(_a5_ + x1))))/_a0_)**_a3_
<lambdifygenerated-377>:2: RuntimeWarning: invalid value encountered in power
  return _a4_*sin(x1*x1**x1)/x1 + (-tan(tanh(_a4_ + cos(_a1_ + x1)/(-_a2_ - _a7_**x1*sin(_a6_*x1)**2/(_a5_ + x1))))/_a0_)**_a3_
<lambdifygenerated-378>:2: RuntimeWarning: invalid value encountered in power
  return _a4_*sin(x1*x1**x1)/x1 + (-tan(tanh(_a4_ + cos(_a1_ + x1)/(-_a2_ - _a7_**x1*sin(_a6_*x1)**2/(_a5_ + x1))))/_a0_)**_a3_
<lambdifygenerated-379>:2: RuntimeWarning: invalid value encountered in power
  return _a4_*sin(_a0_**x1*x1)/x1 + (-tan(tanh(_a4_ + cos(_a1_ + x1)/(-_a2_ - _a7_**x1*sin(_a6_*x1)**2/(_a5_ + x1))))/_a0_)**_a3_
<lambdifygenerated-383>:2: RuntimeWarning: invalid value encountered in power
  return _a4_*sin(_a0_**x1*x1)/x1**2 + (-tan(tanh(_a4_ + cos(_a1_ + x1)/(-_a2_ - _a7_**x1*sin(_a6_*x1)**2/(_a5_ + x1))))/_a0_)**_a3_
<lambdifygenerated-385>:2: RuntimeWarning: invalid value encountered in power
  return (-tan(tanh(_a4_ + cos(_a1_ + x1)/(-_a2_ - _a7_**x1*sin(_a6_*x1)**2/(_a5_ + x1))))/_a0_)**_a3_ + _a4_*sin(_a0_**x1*x1)/(_a3_*x1)
<lambdifygenerated-387>:2: RuntimeWarning: invalid value encountered in power
  return (-tan(tanh(_a4_ + cos(_a1_ + x1)/(-_a2_ - _a7_**x1*sin(_a6_*x1)**2/(_a5_ + x1))))/_a0_)**_a3_ + (1/2)*_a4_*sin(_a0_**x1*x1)/(_a3_*x1)
<lambdifygenerated-389>:2: RuntimeWarning: invalid value encountered in power
  return (-tan(tanh(_a4_ + cos(_a1_ + x1)/(-_a2_ - _a7_**x1*sin(_a6_*x1)**2/(_a5_ + x1))))/_a0_)**_a3_ + _a4_*sin(_a0_**x1*x1)/(_a3_*(_a6_ + x1))
<lambdifygenerated-395>:2: RuntimeWarning: invalid value encountered in power
  return (-tan(tanh(_a4_ + cos(_a1_ + x1)/(-_a2_ - _a7_**x1*sin(_a6_*x1)**2/(_a5_ + x1))))/_a0_)**_a3_ + _a4_*sin(_a0_**x1*x1)/(_a3_*(_a6_ + x1))

interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.306760  3.0  0.306457  0.307605
3746  0.998  0.307033  3.0  0.306721  0.307912
3747  0.998  0.307306  3.0  0.306984  0.308220
3748  0.999  0.307578  3.0  0.307247  0.308527

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.308120  3.0  0.307769  0.309141
3751  1.002  0.308390  3.0  0.308029  0.309448
3752  1.002  0.308660  3.0  0.308289  0.309755
3753  1.003  0.308928  3.0  0.308547  0.310061

3750

<lambdifygenerated-401>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1
<lambdifygenerated-402>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1
<lambdifygenerated-403>:2: RuntimeWarning: invalid value encountered in power
  return sinh(x1)**x1
<lambdifygenerated-404>:2: RuntimeWarning: invalid value encountered in power
  return sinh(x1)**x1
<lambdifygenerated-407>:2: RuntimeWarning: invalid value encountered in power
  return sinh(x1)**x1
<lambdifygenerated-408>:2: RuntimeWarning: invalid value encountered in power
  return sinh(x1)**x1
<lambdifygenerated-409>:2: RuntimeWarning: invalid value encountered in power
  return sinh(tanh(x1))**x1
<lambdifygenerated-410>:2: RuntimeWarning: invalid value encountered in power
  return sinh(tanh(x1))**x1
<lambdifygenerated-413>:2: RuntimeWarning: invalid value encountered in power
  return sinh(tanh(tan(x1)/x1))**x1
<lambdifygenerated-414>:2: RuntimeWarning: invalid value encountered in power
  return sinh(tanh(tan(x1)/x1))**x1
<lambdifygenerated-415>:2: RuntimeWarning: invalid value encountered in power
  return sinh(tanh(tan(x1**2)/x1))**x1
<lambdifygenerated-416>:2: RuntimeWarning: invalid value encountered in power
  return sinh(tanh(tan(x1**2)/x1))**x1
<lambdifygenerated-417>:2: RuntimeWarning: invalid value encountered in power
  return sinh(tanh(tan(x1**3)/x1))**x1
<lambdifygenerated-418>:2: RuntimeWarning: invalid value encountered in power
  return sinh(tanh(tan(x1**3)/x1))**x1
<lambdifygenerated-419>:2: RuntimeWarning: invalid value encountered in power
  return sinh(tanh(tan(4*x1**3)/x1))**x1
<lambdifygenerated-420>:2: RuntimeWarning: invalid value encountered in power
  return sinh(tanh(tan(4*x1**3)/x1))**x1
<lambdifygenerated-421>:2: RuntimeWarning: invalid value encountered in power
  return sinh(tanh(tan(x1*(x1 + tanh(x1))**2)/x1))**x1
<lambdifygenerated-422>:2: RuntimeWarning: invalid value encountered in power
  return sinh(tanh(tan(x1*(x1 + tanh(x1))**2)/x1))**x1
<lambdifygenerated-423>:2: RuntimeWarning: invalid value encountered in power
  return sinh(tanh(tan(x1*(x1 + tanh(2*x1))**2)/x1))**x1
<lambdifygenerated-424>:2: RuntimeWarning: invalid value encountered in power
  return sinh(tanh(tan(x1*(x1 + tanh(2*x1))**2)/x1))**x1
<lambdifygenerated-425>:2: RuntimeWarning: invalid value encountered in power
  return sinh(tanh(tan(x1*(x1 + tanh(x1**2 + x1))**2)/x1))**x1
<lambdifygenerated-426>:2: RuntimeWarning: invalid value encountered in power
  return sinh(tanh(tan(x1*(x1 + tanh(x1**2 + x1))**2)/x1))**x1
<lambdifygenerated-427>:2: RuntimeWarning: invalid value encountered in power
  return sinh(tanh(tan(x1*(x1 + tanh(x1*x1**x1 + x1))**2)/x1))**x1
<lambdifygenerated-428>:2: RuntimeWarning: invalid value encountered in power
  return sinh(tanh(tan(x1*(x1 + tanh(x1*x1**x1 + x1))**2)/x1))**x1
<lambdifygenerated-429>:2: RuntimeWarning: invalid value encountered in power
  return sinh(tanh(tan(x1*(x1 + tanh(x1*(x1**2)**x1 + x1))**2)/x1))**x1
<lambdifygenerated-430>:2: RuntimeWarning: invalid value encountered in power
  return sinh(tanh(tan(x1*(x1 + tanh(x1*(x1**2)**x1 + x1))**2)/x1))**x1
<lambdifygenerated-431>:2: RuntimeWarning: invalid value encountered in power
  return sinh(tanh(tan(x1*(x1 + tanh(x1*(x1*x1**x1)**x1 + x1))**2)/x1))**x1
<lambdifygenerated-432>:2: RuntimeWarning: invalid value encountered in power
  return sinh(tanh(tan(x1*(x1 + tanh(x1*(x1*x1**x1)**x1 + x1))**2)/x1))**x1
<lambdifygenerated-433>:2: RuntimeWarning: invalid value encountered in power
  return sinh(tanh(tan(x1*(x1 + tanh(x1*x1**x1 + x1))**2)/x1))**x1
<lambdifygenerated-434>:2: RuntimeWarning: invalid value encountered in power
  return sinh(tanh(tan(x1*(x1 + tanh(x1*x1**x1 + x1))**2)/x1))**x1
<lambdifygenerated-435>:2: RuntimeWarning: invalid value encountered in power
  return sinh(tanh(tan(x1*(x1 + tanh(x1*(x1*(_a7_/x1)**x1)**x1 + x1))**2)/x1))**x1
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-436>:2: RuntimeWarning: invalid value encountered in power
  return sinh(tanh(tan(x1*(x1 + tanh(x1*(x1*(_a7_/x1)**x1)**x1 + x1))**2)/x1))**x1
<lambdifygenerated-437>:2: RuntimeWarning: invalid value encountered in power
  return sinh(tanh(tan(x1*(x1 + tanh(x1*(_a7_**x1*x1)**x1 + x1))**2)/x1))**x1
<lambdifygenerated-438>:2: RuntimeWarning: invalid value encountered in power
  return sinh(tanh(tan(x1*(x1 + tanh(x1*(_a7_**x1*x1)**x1 + x1))**2)/x1))**x1
<lambdifygenerated-439>:2: RuntimeWarning: invalid value encountered in power
  return sinh(tanh(tan(x1*(x1 + tanh(x1*(x1*(_a7_/x1)**x1)**x1 + x1))**2)/x1))**x1
<lambdifygenerated-440>:2: RuntimeWarning: invalid value encountered in power
  return sinh(tanh(tan(x1*(x1 + tanh(x1*(x1*(_a7_/x1)**x1)**x1 + x1))**2)/x1))**x1
<lambdifygenerated-441>:2: RuntimeWarning: invalid value encountered in power
  return sinh(tanh(tan(x1*(x1 + tanh(x1*(x1*(x1/_a7_)**x1)**x1 + x1))**2)/x1))**x1
<lambdifygenerated-442>:2: RuntimeWarning: invalid value encountered in power
  return sinh(tanh(tan(x1*(x1 + tanh(x1*(x1*(x1/_a7_)**x1)**x1 + x1))**2)/x1))**x1
<lambdifygenerated-443>:2: RuntimeWarning: invalid value encountered in power
  return sinh(tanh(tan(x1*(x1 + tanh(x1*(x1*(_a0_/_a7_)**x1)**x1 + x1))**2)/x1))**x1
<lambdifygenerated-444>:2: RuntimeWarning: invalid value encountered in power
  return sinh(tanh(tan(x1*(x1 + tanh(x1*(x1*(_a0_/_a7_)**x1)**x1 + x1))**2)/x1))**x1
<lambdifygenerated-445>:2: RuntimeWarning: invalid value encountered in power
  return sinh(tanh(tan(x1*(x1 + tanh(x1*(x1*(_a0_/_a7_)**exp(x1))**x1 + x1))**2)/x1))**x1
<lambdifygenerated-446>:2: RuntimeWarning: invalid value encountered in power
  return sinh(tanh(tan(x1*(x1 + tanh(x1*(x1*(_a0_/_a7_)**exp(x1))**x1 + x1))**2)/x1))**x1
<lambdifygenerated-447>:2: RuntimeWarning: invalid value encountered in power
  return sinh(tanh(tan(x1*(x1 + tanh(x1*(x1*(_a0_/_a7_)**exp(cos(x1)))**x1 + x1))**2)/x1))**x1
<lambdifygenerated-448>:2: RuntimeWarning: invalid value encountered in power
  return sinh(tanh(tan(x1*(x1 + tanh(x1*(x1*(_a0_/_a7_)**exp(cos(x1)))**x1 + x1))**2)/x1))**x1
<lambdifygenerated-449>:2: RuntimeWarning: invalid value encountered in power
  return sinh(tanh(tan(x1*(x1 + tanh(x1*(x1*(_a0_/_a7_)**exp(cos(x1**2)))**x1 + x1))**2)/x1))**x1
<lambdifygenerated-450>:2: RuntimeWarning: invalid value encountered in power
  return sinh(tanh(tan(x1*(x1 + tanh(x1*(x1*(_a0_/_a7_)**exp(cos(x1**2)))**x1 + x1))**2)/x1))**x1
<lambdifygenerated-451>:2: RuntimeWarning: invalid value encountered in power
  return sinh(tanh(tan(x1*(x1 + tanh(x1*(x1*(_a0_/_a7_)**exp(cos(2*x1**2)))**x1 + x1))**2)/x1))**x1
<lambdifygenerated-452>:2: RuntimeWarning: invalid value encountered in power
  return sinh(tanh(tan(x1*(x1 + tanh(x1*(x1*(_a0_/_a7_)**exp(cos(2*x1**2)))**x1 + x1))**2)/x1))**x1
<lambdifygenerated-453>:2: RuntimeWarning: invalid value encountered in power
  return sinh(tanh(tan(x1*(x1 + tanh(x1*(x1*(_a0_/_a7_)**exp(cos(2*x1**2)))**x1 + x1))**2)/x1))**x1
<lambdifygenerated-454>:2: RuntimeWarning: invalid value encountered in power
  return sinh(tanh(tan(x1*(x1 + tanh(x1*(x1*(_a0_/_a7_)**exp(cos(2*x1**2)))**x1 + x1))**2)/x1))**x1
<lambdifygenerated-455>:2: RuntimeWarning: invalid value encountered in power
  return sinh(tanh(tan(x1*(x1 + tanh(x1*(x1*(_a0_/_a7_)**exp(cos(x1*(_a2_ + x1))))**x1 + x1))**2)/x1))**x1
<lambdifygenerated-456>:2: RuntimeWarning: invalid value encountered in power
  return sinh(tanh(tan(x1*(x1 + tanh(x1*(x1*(_a0_/_a7_)**exp(cos(x1*(_a2_ + x1))))**x1 + x1))**2)/x1))**x1
<lambdifygenerated-457>:2: RuntimeWarning: invalid value encountered in power
  return sinh(tanh(tan(x1*(x1 + tanh(x1*(x1*(_a0_/_a7_)**exp(cos(x1**2*(_a2_ + x1))))**x1 + x1))**2)/x1))**x1
<lambdifygenerated-458>:2: RuntimeWarning: invalid value encountered in power
  return sinh(tanh(tan(x1*(x1 + tanh(x1*(x1*(_a0_/_a7_)**exp(cos(x1**2*(_a2_ + x1))))**x1 + x1))**2)/x1))**x1
<lambdifygenerated-459>:2: RuntimeWarning: invalid value encountered in power
  return sinh(tanh(tan(x1*(x1 + tanh(x1*(x1*(_a0_/_a7_)**exp(cos(2*x1**2*(_a2_ + x1))))**x1 + x1))**2)/x1))**x1
<lambdifygenerated-460>:2: RuntimeWarning: invalid value encountered in power
  return sinh(tanh(tan(x1*(x1 + tanh(x1*(x1*(_a0_/_a7_)**exp(cos(2*x1**2*(_a2_ + x1))))**x1 + x1))**2)/x1))**x1
<lambdifygenerated-461>:2: RuntimeWarning: invalid value encountered in power
  return sinh(tanh(tan(x1*(x1 + tanh(x1*(x1*(_a0_/_a7_)**exp(cos(x1*(_a2_ + x1)*(x1 + tanh(x1)))))**x1 + x1))**2)/x1))**x1
<lambdifygenerated-462>:2: RuntimeWarning: invalid value encountered in power
  return sinh(tanh(tan(x1*(x1 + tanh(x1*(x1*(_a0_/_a7_)**exp(cos(x1*(_a2_ + x1)*(x1 + tanh(x1)))))**x1 + x1))**2)/x1))**x1
<lambdifygenerated-463>:2: RuntimeWarning: invalid value encountered in power
  return sinh(tanh(tan(x1*(x1 + tanh(x1*(x1*(_a0_/_a7_)**exp(cos(x1*(_a2_ + x1)*(x1 + tanh(exp(x1))))))**x1 + x1))**2)/x1))**x1
<lambdifygenerated-464>:2: RuntimeWarning: invalid value encountered in power
  return sinh(tanh(tan(x1*(x1 + tanh(x1*(x1*(_a0_/_a7_)**exp(cos(x1*(_a2_ + x1)*(x1 + tanh(exp(x1))))))**x1 + x1))**2)/x1))**x1
<lambdifygenerated-465>:2: RuntimeWarning: invalid value encountered in power
  return sinh(tanh(tan(x1*(x1 + tanh(x1*(x1*(_a0_/_a7_)**exp(cos(x1*(_a2_ + x1)*(x1 + tanh(exp(x1))))))**x1 + x1))**2)/x1))**x1
<lambdifygenerated-466>:2: RuntimeWarning: invalid value encountered in power
  return sinh(tanh(tan(x1*(x1 + tanh(x1*(x1*(_a0_/_a7_)**exp(cos(x1*(_a2_ + x1)*(x1 + tanh(exp(x1))))))**x1 + x1))**2)/x1))**x1
<lambdifygenerated-467>:2: RuntimeWarning: invalid value encountered in power
  return sinh(tanh(tan(x1*(x1 + tanh(x1*(x1*(_a0_/_a7_)**exp(cos(x1*(_a2_ + x1)*(_a7_ + tanh(exp(x1))))))**x1 + x1))**2)/x1))**x1
<lambdifygenerated-468>:2: RuntimeWarning: invalid value encountered in power
  return sinh(tanh(tan(x1*(x1 + tanh(x1*(x1*(_a0_/_a7_)**exp(cos(x1*(_a2_ + x1)*(_a7_ + tanh(exp(x1))))))**x1 + x1))**2)/x1))**x1
<lambdifygenerated-469>:2: RuntimeWarning: invalid value encountered in power
  return sinh(tanh(tan(x1*(x1 + tanh(x1*(x1*(_a0_/_a7_)**exp(cos(_a3_*(_a2_ + x1)*(_a7_ + tanh(exp(x1))))))**x1 + x1))**2)/x1))**x1
<lambdifygenerated-470>:2: RuntimeWarning: invalid value encountered in power
  return sinh(tanh(tan(x1*(x1 + tanh(x1*(x1*(_a0_/_a7_)**exp(cos(_a3_*(_a2_ + x1)*(_a7_ + tanh(exp(x1))))))**x1 + x1))**2)/x1))**x1
<lambdifygenerated-471>:2: RuntimeWarning: invalid value encountered in power
  return sinh(tanh(tan(x1*(x1 + tanh(x1*(x1**2*(_a0_/_a7_)**exp(cos(_a3_*(_a2_ + x1)*(_a7_ + tanh(exp(x1))))))**x1 + x1))**2)/x1))**x1
<lambdifygenerated-472>:2: RuntimeWarning: invalid value encountered in power
  return sinh(tanh(tan(x1*(x1 + tanh(x1*(x1**2*(_a0_/_a7_)**exp(cos(_a3_*(_a2_ + x1)*(_a7_ + tanh(exp(x1))))))**x1 + x1))**2)/x1))**x1
<lambdifygenerated-473>:2: RuntimeWarning: invalid value encountered in power
  return sinh(tanh(tan(x1*(x1 + tanh(x1*(_a5_**2*(_a0_/_a7_)**exp(cos(_a3_*(_a2_ + x1)*(_a7_ + tanh(exp(x1))))))**x1 + x1))**2)/x1))**x1
<lambdifygenerated-474>:2: RuntimeWarning: invalid value encountered in power
  return sinh(tanh(tan(x1*(x1 + tanh(x1*(_a5_**2*(_a0_/_a7_)**exp(cos(_a3_*(_a2_ + x1)*(_a7_ + tanh(exp(x1))))))**x1 + x1))**2)/x1))**x1
<lambdifygenerated-475>:2: RuntimeWarning: invalid value encountered in power
  return sinh(tanh(tan(x1*(x1 + tanh(x1*(_a5_**2*(_a0_/_a7_)**exp(cos(_a3_*(_a2_ + x1)*(_a7_ + tanh(exp(x1))))))**_a6_ + x1))**2)/x1))**x1
<lambdifygenerated-476>:2: RuntimeWarning: invalid value encountered in power
  return sinh(tanh(tan(x1*(x1 + tanh(x1*(_a5_**2*(_a0_/_a7_)**exp(cos(_a3_*(_a2_ + x1)*(_a7_ + tanh(exp(x1))))))**_a6_ + x1))**2)/x1))**x1
<lambdifygenerated-477>:2: RuntimeWarning: invalid value encountered in power
  return sinh(tanh(tan(x1*(x1 + tanh(2*x1*(_a5_**2*(_a0_/_a7_)**exp(cos(_a3_*(_a2_ + x1)*(_a7_ + tanh(exp(x1))))))**_a6_ + x1))**2)/x1))**x1
<lambdifygenerated-478>:2: RuntimeWarning: invalid value encountered in power
  return sinh(tanh(tan(x1*(x1 + tanh(2*x1*(_a5_**2*(_a0_/_a7_)**exp(cos(_a3_*(_a2_ + x1)*(_a7_ + tanh(exp(x1))))))**_a6_ + x1))**2)/x1))**x1
<lambdifygenerated-479>:2: RuntimeWarning: invalid value encountered in power
  return sinh(tanh(tan(x1*(x1 + tanh(2*x1*(_a5_**2*(_a0_/_a7_)**exp(cos(_a3_*(_a2_ + x1)*(_a7_ + tanh(exp(x1))))))**_a6_ + x1))**2)/x1))**x1
<lambdifygenerated-480>:2: RuntimeWarning: invalid value encountered in power
  return sinh(tanh(tan(x1*(x1 + tanh(2*x1*(_a5_**2*(_a0_/_a7_)**exp(cos(_a3_*(_a2_ + x1)*(_a7_ + tanh(exp(x1))))))**_a6_ + x1))**2)/x1))**x1
<lambdifygenerated-481>:2: RuntimeWarning: invalid value encountered in power
  return sinh(tanh(tan(x1*(x1 + tanh(x1 + (_a5_**2*(_a0_/_a7_)**exp(cos(_a3_*(_a2_ + x1)*(_a7_ + tanh(exp(x1))))))**_a6_*(_a2_ + x1)))**2)/x1))**x1
<lambdifygenerated-482>:2: RuntimeWarning: invalid value encountered in power
  return sinh(tanh(tan(x1*(x1 + tanh(x1 + (_a5_**2*(_a0_/_a7_)**exp(cos(_a3_*(_a2_ + x1)*(_a7_ + tanh(exp(x1))))))**_a6_*(_a2_ + x1)))**2)/x1))**x1
<lambdifygenerated-483>:2: RuntimeWarning: invalid value encountered in power
  return sinh(tanh(tan(x1*(x1 + tanh(x1**2 + (_a5_**2*(_a0_/_a7_)**exp(cos(_a3_*(_a2_ + x1)*(_a7_ + tanh(exp(x1))))))**_a6_*(_a2_ + x1)))**2)/x1))**x1
<lambdifygenerated-484>:2: RuntimeWarning: invalid value encountered in power
  return sinh(tanh(tan(x1*(x1 + tanh(x1**2 + (_a5_**2*(_a0_/_a7_)**exp(cos(_a3_*(_a2_ + x1)*(_a7_ + tanh(exp(x1))))))**_a6_*(_a2_ + x1)))**2)/x1))**x1
<lambdifygenerated-485>:2: RuntimeWarning: invalid value encountered in power
  return sinh(tanh(tan(x1*(x1 + tanh(_a5_*x1 + (_a5_**2*(_a0_/_a7_)**exp(cos(_a3_*(_a2_ + x1)*(_a7_ + tanh(exp(x1))))))**_a6_*(_a2_ + x1)))**2)/x1))**x1
<lambdifygenerated-486>:2: RuntimeWarning: invalid value encountered in power
  return sinh(tanh(tan(x1*(x1 + tanh(_a5_*x1 + (_a5_**2*(_a0_/_a7_)**exp(cos(_a3_*(_a2_ + x1)*(_a7_ + tanh(exp(x1))))))**_a6_*(_a2_ + x1)))**2)/x1))**x1
<lambdifygenerated-487>:2: RuntimeWarning: invalid value encountered in power
  return sinh(tanh(tan(x1*(x1 + tanh(_a5_*x1 + (_a5_**2*(_a0_/_a7_)**exp(cos(_a3_*(_a2_ + x1)*(_a7_ + tanh(exp(x1))))))**_a6_*(_a2_ + x1)))**2)/x1))**x1
<lambdifygenerated-488>:2: RuntimeWarning: invalid value encountered in power
  return sinh(tanh(tan(x1*(x1 + tanh(_a5_*x1 + (_a5_**2*(_a0_/_a7_)**exp(cos(_a3_*(_a2_ + x1)*(_a7_ + tanh(exp(x1))))))**_a6_*(_a2_ + x1)))**2)/x1))**x1
<lambdifygenerated-489>:2: RuntimeWarning: invalid value encountered in power
  return sinh(tanh(tan(x1*(_a0_ + tanh(_a5_*x1 + (_a5_**2*(_a0_/_a7_)**exp(cos(_a3_*(_a2_ + x1)*(_a7_ + tanh(exp(x1))))))**_a6_*(_a2_ + x1)))**2)/x1))**x1
<lambdifygenerated-490>:2: RuntimeWarning: invalid value encountered in power
  return sinh(tanh(tan(x1*(_a0_ + tanh(_a5_*x1 + (_a5_**2*(_a0_/_a7_)**exp(cos(_a3_*(_a2_ + x1)*(_a7_ + tanh(exp(x1))))))**_a6_*(_a2_ + x1)))**2)/x1))**x1
<lambdifygenerated-491>:2: RuntimeWarning: invalid value encountered in power
  return sinh(tanh(tan(_a1_*(_a0_ + tanh(_a5_*x1 + (_a5_**2*(_a0_/_a7_)**exp(cos(_a3_*(_a2_ + x1)*(_a7_ + tanh(exp(x1))))))**_a6_*(_a2_ + x1)))**2)/x1))**x1
<lambdifygenerated-492>:2: RuntimeWarning: invalid value encountered in power
  return sinh(tanh(tan(_a1_*(_a0_ + tanh(_a5_*x1 + (_a5_**2*(_a0_/_a7_)**exp(cos(_a3_*(_a2_ + x1)*(_a7_ + tanh(exp(x1))))))**_a6_*(_a2_ + x1)))**2)/x1))**x1
<lambdifygenerated-493>:2: RuntimeWarning: invalid value encountered in power
  return sinh(tanh(tan(_a1_*(_a0_ + tanh(_a5_*x1 + (_a5_**2*(_a0_/_a7_)**exp(cos(_a3_*(_a2_ + x1)*(_a7_ + tanh(exp(x1))))))**_a6_*(_a2_ + x1)))**2)/_a4_))**x1
<lambdifygenerated-494>:2: RuntimeWarning: invalid value encountered in power
  return sinh(tanh(tan(_a1_*(_a0_ + tanh(_a5_*x1 + (_a5_**2*(_a0_/_a7_)**exp(cos(_a3_*(_a2_ + x1)*(_a7_ + tanh(exp(x1))))))**_a6_*(_a2_ + x1)))**2)/_a4_))**x1
<lambdifygenerated-495>:2: RuntimeWarning: overflow encountered in sinh
  return sinh(_a7_*tanh(tan(_a1_*(_a0_ + tanh(_a5_*x1 + (_a5_**2*(_a0_/_a7_)**exp(cos(_a3_*(_a2_ + x1)*(_a7_ + tanh(exp(x1))))))**_a6_*(_a2_ + x1)))**2)/_a4_)/x1)**x1
<lambdifygenerated-495>:2: RuntimeWarning: invalid value encountered in power
  return sinh(_a7_*tanh(tan(_a1_*(_a0_ + tanh(_a5_*x1 + (_a5_**2*(_a0_/_a7_)**exp(cos(_a3_*(_a2_ + x1)*(_a7_ + tanh(exp(x1))))))**_a6_*(_a2_ + x1)))**2)/_a4_)/x1)**x1
<lambdifygenerated-496>:2: RuntimeWarning: overflow encountered in sinh
  return sinh(_a7_*tanh(tan(_a1_*(_a0_ + tanh(_a5_*x1 + (_a5_**2*(_a0_/_a7_)**exp(cos(_a3_*(_a2_ + x1)*(_a7_ + tanh(exp(x1))))))**_a6_*(_a2_ + x1)))**2)/_a4_)/x1)**x1
<lambdifygenerated-496>:2: RuntimeWarning: invalid value encountered in power
  return sinh(_a7_*tanh(tan(_a1_*(_a0_ + tanh(_a5_*x1 + (_a5_**2*(_a0_/_a7_)**exp(cos(_a3_*(_a2_ + x1)*(_a7_ + tanh(exp(x1))))))**_a6_*(_a2_ + x1)))**2)/_a4_)/x1)**x1
<lambdifygenerated-497>:2: RuntimeWarning: invalid value encountered in power
  return sinh(_a7_*tanh(tan(_a1_*(_a0_ + tanh(_a5_*x1 + (_a5_**2*(_a0_/_a7_)**exp(cos(_a3_*(_a2_ + x1)*(_a7_ + tanh(exp(x1))))))**_a6_*(_a2_ + x1)))**2)/_a4_)/_a0_)**x1
<lambdifygenerated-498>:2: RuntimeWarning: invalid value encountered in power
  return sinh(_a7_*tanh(tan(_a1_*(_a0_ + tanh(_a5_*x1 + (_a5_**2*(_a0_/_a7_)**exp(cos(_a3_*(_a2_ + x1)*(_a7_ + tanh(exp(x1))))))**_a6_*(_a2_ + x1)))**2)/_a4_)/_a0_)**x1
<lambdifygenerated-499>:2: RuntimeWarning: invalid value encountered in power
  return sinh(_a7_*tanh(tan(_a1_*(_a0_ + tanh(_a5_*x1 + (_a5_**2*(_a0_/_a7_)**exp(cos(_a3_*(_a2_ + x1)*(_a7_ + tanh(exp(x1))))))**_a6_*(_a2_ + x1)))**2)/_a4_)/_a0_)**_a0_
<lambdifygenerated-503>:2: RuntimeWarning: invalid value encountered in power
  return sinh(_a7_*tanh(tan(_a1_*(_a0_ + tanh(_a5_*x1 + (_a5_**2*(_a0_/_a7_)**exp(cos(_a3_*(_a2_ + x1)*(_a7_ + tanh(exp(x1))))))**_a6_*(_a2_ + x1)))**2)/_a4_)/_a0_)**_a0_

interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.965360  4.0  0.964831  0.965143
3746  0.998  0.965399  4.0  0.964858  0.965178
3747  0.998  0.965439  4.0  0.964886  0.965213
3748  0.999  0.965479  4.0  0.964914  0.965248

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.965559  4.0  0.964969  0.965318
3751  1.002  0.965598  4.0  0.964996  0.965353
3752  1.002  0.965638  4.0  0.965023  0.965388
3753  1.003  0.965678  4.0  0.965050  0.965422

3750

<lambdifygenerated-509>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1
<lambdifygenerated-510>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1
<lambdifygenerated-511>:2: RuntimeWarning: invalid value encountered in power
  return sin(x1)**x1
<lambdifygenerated-512>:2: RuntimeWarning: invalid value encountered in power
  return sin(x1)**x1
<lambdifygenerated-513>:2: RuntimeWarning: invalid value encountered in sqrt
  return sin(sqrt(x1))**x1
<lambdifygenerated-514>:2: RuntimeWarning: invalid value encountered in sqrt
  return sin(sqrt(x1))**x1
<lambdifygenerated-515>:2: RuntimeWarning: invalid value encountered in log
  return sin(sqrt(log(x1)))**x1
<lambdifygenerated-515>:2: RuntimeWarning: invalid value encountered in sqrt
  return sin(sqrt(log(x1)))**x1
<lambdifygenerated-516>:2: RuntimeWarning: invalid value encountered in log
  return sin(sqrt(log(x1)))**x1
<lambdifygenerated-516>:2: RuntimeWarning: invalid value encountered in sqrt
  return sin(sqrt(log(x1)))**x1
<lambdifygenerated-517>:2: RuntimeWarning: divide by zero encountered in power
  return 0**x1
<lambdifygenerated-518>:2: RuntimeWarning: divide by zero encountered in power
  return 0**x1
<lambdifygenerated-519>:2: RuntimeWarning: invalid value encountered in sqrt
  return sin(sqrt(log(1/sqrt(x1))))**x1
<lambdifygenerated-520>:2: RuntimeWarning: invalid value encountered in sqrt
  return sin(sqrt(log(1/sqrt(x1))))**x1
<lambdifygenerated-521>:2: RuntimeWarning: invalid value encountered in log
  return sin(sqrt(log(sqrt(x1**2)/x1)))**x1
<lambdifygenerated-522>:2: RuntimeWarning: invalid value encountered in log
  return sin(sqrt(log(sqrt(x1**2)/x1)))**x1
<lambdifygenerated-523>:2: RuntimeWarning: invalid value encountered in sqrt
  return sin(sqrt(log(sqrt(x1*cosh(x1))/x1)))**x1
<lambdifygenerated-524>:2: RuntimeWarning: invalid value encountered in sqrt
  return sin(sqrt(log(sqrt(x1*cosh(x1))/x1)))**x1
<lambdifygenerated-525>:2: RuntimeWarning: invalid value encountered in sqrt
  return sin(sqrt(log(sqrt(x1*cosh(x1**2))/x1)))**x1
<lambdifygenerated-526>:2: RuntimeWarning: invalid value encountered in sqrt
  return sin(sqrt(log(sqrt(x1*cosh(x1**2))/x1)))**x1
<lambdifygenerated-527>:2: RuntimeWarning: invalid value encountered in sqrt
  return sin(sqrt(log(sqrt(x1*cosh(2*x1**2))/x1)))**x1
<lambdifygenerated-528>:2: RuntimeWarning: invalid value encountered in sqrt
  return sin(sqrt(log(sqrt(x1*cosh(2*x1**2))/x1)))**x1
<lambdifygenerated-529>:2: RuntimeWarning: invalid value encountered in sqrt
  return sin(sqrt(log(sqrt(x1*cosh(x1*(x1 + tanh(x1))))/x1)))**x1
<lambdifygenerated-530>:2: RuntimeWarning: invalid value encountered in sqrt
  return sin(sqrt(log(sqrt(x1*cosh(x1*(x1 + tanh(x1))))/x1)))**x1
<lambdifygenerated-531>:2: RuntimeWarning: invalid value encountered in sqrt
  return sin(sqrt(log(sqrt(x1*cosh(x1*(x1 + tanh(1))))/x1)))**x1
<lambdifygenerated-532>:2: RuntimeWarning: invalid value encountered in sqrt
  return sin(sqrt(log(sqrt(x1*cosh(x1*(x1 + tanh(1))))/x1)))**x1
<lambdifygenerated-533>:2: RuntimeWarning: invalid value encountered in sqrt
  return sin(sqrt(log(sqrt(x1*cosh(x1*(x1 + tanh(2))))/x1)))**x1
<lambdifygenerated-534>:2: RuntimeWarning: invalid value encountered in sqrt
  return sin(sqrt(log(sqrt(x1*cosh(x1*(x1 + tanh(2))))/x1)))**x1
<lambdifygenerated-535>:2: RuntimeWarning: invalid value encountered in sqrt
  return sin(sqrt(log(sqrt(x1*cosh(x1*(x1 + tanh((x1 + sin(x1))/x1))))/x1)))**x1
<lambdifygenerated-536>:2: RuntimeWarning: invalid value encountered in sqrt
  return sin(sqrt(log(sqrt(x1*cosh(x1*(x1 + tanh((x1 + sin(x1))/x1))))/x1)))**x1
<lambdifygenerated-537>:2: RuntimeWarning: invalid value encountered in sqrt
  return sin(sqrt(log(sqrt(x1*cosh(x1*(x1 + tanh((x1 + sin(_a5_))/x1))))/x1)))**x1
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-538>:2: RuntimeWarning: invalid value encountered in sqrt
  return sin(sqrt(log(sqrt(x1*cosh(x1*(x1 + tanh((x1 + sin(_a5_))/x1))))/x1)))**x1
<lambdifygenerated-539>:2: RuntimeWarning: invalid value encountered in sqrt
  return sin(sqrt(log(sqrt(x1*cosh(x1*(x1 + tanh((2*x1 + sin(_a5_))/x1))))/x1)))**x1
<lambdifygenerated-540>:2: RuntimeWarning: invalid value encountered in sqrt
  return sin(sqrt(log(sqrt(x1*cosh(x1*(x1 + tanh((2*x1 + sin(_a5_))/x1))))/x1)))**x1
<lambdifygenerated-541>:2: RuntimeWarning: invalid value encountered in sqrt
  return sin(sqrt(log(sqrt(x1*cosh(x1*(x1 + tanh((2*x1 + sin(_a5_))/x1))))/x1)))**x1
<lambdifygenerated-542>:2: RuntimeWarning: invalid value encountered in sqrt
  return sin(sqrt(log(sqrt(x1*cosh(x1*(x1 + tanh((2*x1 + sin(_a5_))/x1))))/x1)))**x1
<lambdifygenerated-543>:2: RuntimeWarning: invalid value encountered in sqrt
  return sin(sqrt(log(sqrt(x1*cosh(x1*(x1 + tanh((2*x1 + sin(_a5_))/x1))))/x1)))**x1
<lambdifygenerated-544>:2: RuntimeWarning: invalid value encountered in sqrt
  return sin(sqrt(log(sqrt(x1*cosh(x1*(x1 + tanh((2*x1 + sin(_a5_))/x1))))/x1)))**x1
<lambdifygenerated-545>:2: RuntimeWarning: invalid value encountered in sqrt
  return sin(sqrt(log(sqrt(x1*cosh(x1*(x1 + tanh((2*x1 + sin(_a5_))/_a3_))))/x1)))**x1
<lambdifygenerated-546>:2: RuntimeWarning: invalid value encountered in sqrt
  return sin(sqrt(log(sqrt(x1*cosh(x1*(x1 + tanh((2*x1 + sin(_a5_))/_a3_))))/x1)))**x1
<lambdifygenerated-547>:2: RuntimeWarning: invalid value encountered in sqrt
  return sin(sqrt(log(sqrt(x1*cosh(x1*(x1**2 + tanh((2*x1 + sin(_a5_))/_a3_))))/x1)))**x1
<lambdifygenerated-548>:2: RuntimeWarning: invalid value encountered in sqrt
  return sin(sqrt(log(sqrt(x1*cosh(x1*(x1**2 + tanh((2*x1 + sin(_a5_))/_a3_))))/x1)))**x1
<lambdifygenerated-549>:2: RuntimeWarning: invalid value encountered in sqrt
  return sin(sqrt(log(sqrt(x1*cosh(x1*(tanh((2*x1 + sin(_a5_))/_a3_) + 1)))/x1)))**x1
<lambdifygenerated-550>:2: RuntimeWarning: invalid value encountered in sqrt
  return sin(sqrt(log(sqrt(x1*cosh(x1*(tanh((2*x1 + sin(_a5_))/_a3_) + 1)))/x1)))**x1
<lambdifygenerated-551>:2: RuntimeWarning: invalid value encountered in sqrt
  return sin(sqrt(log(sqrt(x1*cosh(x1*(x1**2 + tanh((2*x1 + sin(_a5_))/_a3_))))/x1)))**x1
<lambdifygenerated-552>:2: RuntimeWarning: invalid value encountered in sqrt
  return sin(sqrt(log(sqrt(x1*cosh(x1*(x1**2 + tanh((2*x1 + sin(_a5_))/_a3_))))/x1)))**x1
<lambdifygenerated-553>:2: RuntimeWarning: invalid value encountered in sqrt
  return sin(sqrt(log(sqrt(x1*cosh(x1*(_a6_**2 + tanh((2*x1 + sin(_a5_))/_a3_))))/x1)))**x1
<lambdifygenerated-554>:2: RuntimeWarning: invalid value encountered in sqrt
  return sin(sqrt(log(sqrt(x1*cosh(x1*(_a6_**2 + tanh((2*x1 + sin(_a5_))/_a3_))))/x1)))**x1
<lambdifygenerated-555>:2: RuntimeWarning: overflow encountered in cosh
  return sin(sqrt(log(sqrt(x1*cosh(x1*(_a3_**2*_a6_**2/x1**2 + tanh((2*x1 + sin(_a5_))/_a3_))))/x1)))**x1
<lambdifygenerated-555>:2: RuntimeWarning: invalid value encountered in sqrt
  return sin(sqrt(log(sqrt(x1*cosh(x1*(_a3_**2*_a6_**2/x1**2 + tanh((2*x1 + sin(_a5_))/_a3_))))/x1)))**x1
<lambdifygenerated-555>:2: RuntimeWarning: invalid value encountered in sin
  return sin(sqrt(log(sqrt(x1*cosh(x1*(_a3_**2*_a6_**2/x1**2 + tanh((2*x1 + sin(_a5_))/_a3_))))/x1)))**x1
<lambdifygenerated-555>:2: RuntimeWarning: invalid value encountered in power
  return sin(sqrt(log(sqrt(x1*cosh(x1*(_a3_**2*_a6_**2/x1**2 + tanh((2*x1 + sin(_a5_))/_a3_))))/x1)))**x1
<lambdifygenerated-556>:2: RuntimeWarning: overflow encountered in cosh
  return sin(sqrt(log(sqrt(x1*cosh(x1*(_a3_**2*_a6_**2/x1**2 + tanh((2*x1 + sin(_a5_))/_a3_))))/x1)))**x1
<lambdifygenerated-556>:2: RuntimeWarning: invalid value encountered in sqrt
  return sin(sqrt(log(sqrt(x1*cosh(x1*(_a3_**2*_a6_**2/x1**2 + tanh((2*x1 + sin(_a5_))/_a3_))))/x1)))**x1
<lambdifygenerated-556>:2: RuntimeWarning: invalid value encountered in sin
  return sin(sqrt(log(sqrt(x1*cosh(x1*(_a3_**2*_a6_**2/x1**2 + tanh((2*x1 + sin(_a5_))/_a3_))))/x1)))**x1
<lambdifygenerated-556>:2: RuntimeWarning: invalid value encountered in power
  return sin(sqrt(log(sqrt(x1*cosh(x1*(_a3_**2*_a6_**2/x1**2 + tanh((2*x1 + sin(_a5_))/_a3_))))/x1)))**x1
<lambdifygenerated-557>:2: RuntimeWarning: overflow encountered in cosh
  return sin(sqrt(log(sqrt(x1*cosh(x1*((1/4)*_a3_**2*_a6_**2/x1**2 + tanh((2*x1 + sin(_a5_))/_a3_))))/x1)))**x1
<lambdifygenerated-557>:2: RuntimeWarning: invalid value encountered in sqrt
  return sin(sqrt(log(sqrt(x1*cosh(x1*((1/4)*_a3_**2*_a6_**2/x1**2 + tanh((2*x1 + sin(_a5_))/_a3_))))/x1)))**x1
<lambdifygenerated-557>:2: RuntimeWarning: invalid value encountered in power
  return sin(sqrt(log(sqrt(x1*cosh(x1*((1/4)*_a3_**2*_a6_**2/x1**2 + tanh((2*x1 + sin(_a5_))/_a3_))))/x1)))**x1
<lambdifygenerated-558>:2: RuntimeWarning: overflow encountered in cosh
  return sin(sqrt(log(sqrt(x1*cosh(x1*((1/4)*_a3_**2*_a6_**2/x1**2 + tanh((2*x1 + sin(_a5_))/_a3_))))/x1)))**x1
<lambdifygenerated-558>:2: RuntimeWarning: invalid value encountered in sqrt
  return sin(sqrt(log(sqrt(x1*cosh(x1*((1/4)*_a3_**2*_a6_**2/x1**2 + tanh((2*x1 + sin(_a5_))/_a3_))))/x1)))**x1
<lambdifygenerated-558>:2: RuntimeWarning: invalid value encountered in power
  return sin(sqrt(log(sqrt(x1*cosh(x1*((1/4)*_a3_**2*_a6_**2/x1**2 + tanh((2*x1 + sin(_a5_))/_a3_))))/x1)))**x1
<lambdifygenerated-559>:2: RuntimeWarning: overflow encountered in cosh
  return sin(sqrt(log(sqrt(x1*cosh(x1*(_a3_**2*_a6_**2/(x1**2 + x1)**2 + tanh((2*x1 + sin(_a5_))/_a3_))))/x1)))**x1
<lambdifygenerated-559>:2: RuntimeWarning: invalid value encountered in sqrt
  return sin(sqrt(log(sqrt(x1*cosh(x1*(_a3_**2*_a6_**2/(x1**2 + x1)**2 + tanh((2*x1 + sin(_a5_))/_a3_))))/x1)))**x1
<lambdifygenerated-559>:2: RuntimeWarning: invalid value encountered in sin
  return sin(sqrt(log(sqrt(x1*cosh(x1*(_a3_**2*_a6_**2/(x1**2 + x1)**2 + tanh((2*x1 + sin(_a5_))/_a3_))))/x1)))**x1
<lambdifygenerated-559>:2: RuntimeWarning: invalid value encountered in power
  return sin(sqrt(log(sqrt(x1*cosh(x1*(_a3_**2*_a6_**2/(x1**2 + x1)**2 + tanh((2*x1 + sin(_a5_))/_a3_))))/x1)))**x1
<lambdifygenerated-560>:2: RuntimeWarning: overflow encountered in cosh
  return sin(sqrt(log(sqrt(x1*cosh(x1*(_a3_**2*_a6_**2/(x1**2 + x1)**2 + tanh((2*x1 + sin(_a5_))/_a3_))))/x1)))**x1
<lambdifygenerated-560>:2: RuntimeWarning: invalid value encountered in sqrt
  return sin(sqrt(log(sqrt(x1*cosh(x1*(_a3_**2*_a6_**2/(x1**2 + x1)**2 + tanh((2*x1 + sin(_a5_))/_a3_))))/x1)))**x1
<lambdifygenerated-560>:2: RuntimeWarning: invalid value encountered in sin
  return sin(sqrt(log(sqrt(x1*cosh(x1*(_a3_**2*_a6_**2/(x1**2 + x1)**2 + tanh((2*x1 + sin(_a5_))/_a3_))))/x1)))**x1
<lambdifygenerated-560>:2: RuntimeWarning: invalid value encountered in power
  return sin(sqrt(log(sqrt(x1*cosh(x1*(_a3_**2*_a6_**2/(x1**2 + x1)**2 + tanh((2*x1 + sin(_a5_))/_a3_))))/x1)))**x1
<lambdifygenerated-561>:2: RuntimeWarning: invalid value encountered in power
  return sin(sqrt(log(sqrt(x1*cosh(x1*(_a3_**2*_a6_**2/(x1*x1**x1 + x1)**2 + tanh((2*x1 + sin(_a5_))/_a3_))))/x1)))**x1
<lambdifygenerated-562>:2: RuntimeWarning: invalid value encountered in power
  return sin(sqrt(log(sqrt(x1*cosh(x1*(_a3_**2*_a6_**2/(x1*x1**x1 + x1)**2 + tanh((2*x1 + sin(_a5_))/_a3_))))/x1)))**x1
<lambdifygenerated-563>:2: RuntimeWarning: invalid value encountered in power
  return sin(sqrt(log(sqrt(x1*cosh(x1*(_a3_**2*_a6_**2/(x1*(2*x1)**x1 + x1)**2 + tanh((2*x1 + sin(_a5_))/_a3_))))/x1)))**x1
<lambdifygenerated-564>:2: RuntimeWarning: invalid value encountered in power
  return sin(sqrt(log(sqrt(x1*cosh(x1*(_a3_**2*_a6_**2/(x1*(2*x1)**x1 + x1)**2 + tanh((2*x1 + sin(_a5_))/_a3_))))/x1)))**x1
<lambdifygenerated-565>:2: RuntimeWarning: invalid value encountered in power
  return sin(sqrt(log(sqrt(x1*cosh(x1*(_a3_**2*_a6_**2/(x1*(_a7_ + x1)**x1 + x1)**2 + tanh((2*x1 + sin(_a5_))/_a3_))))/x1)))**x1
<lambdifygenerated-565>:2: RuntimeWarning: overflow encountered in cosh
  return sin(sqrt(log(sqrt(x1*cosh(x1*(_a3_**2*_a6_**2/(x1*(_a7_ + x1)**x1 + x1)**2 + tanh((2*x1 + sin(_a5_))/_a3_))))/x1)))**x1
<lambdifygenerated-565>:2: RuntimeWarning: invalid value encountered in sqrt
  return sin(sqrt(log(sqrt(x1*cosh(x1*(_a3_**2*_a6_**2/(x1*(_a7_ + x1)**x1 + x1)**2 + tanh((2*x1 + sin(_a5_))/_a3_))))/x1)))**x1
<lambdifygenerated-566>:2: RuntimeWarning: invalid value encountered in power
  return sin(sqrt(log(sqrt(x1*cosh(x1*(_a3_**2*_a6_**2/(x1*(_a7_ + x1)**x1 + x1)**2 + tanh((2*x1 + sin(_a5_))/_a3_))))/x1)))**x1
<lambdifygenerated-566>:2: RuntimeWarning: overflow encountered in cosh
  return sin(sqrt(log(sqrt(x1*cosh(x1*(_a3_**2*_a6_**2/(x1*(_a7_ + x1)**x1 + x1)**2 + tanh((2*x1 + sin(_a5_))/_a3_))))/x1)))**x1
<lambdifygenerated-566>:2: RuntimeWarning: invalid value encountered in sqrt
  return sin(sqrt(log(sqrt(x1*cosh(x1*(_a3_**2*_a6_**2/(x1*(_a7_ + x1)**x1 + x1)**2 + tanh((2*x1 + sin(_a5_))/_a3_))))/x1)))**x1
<lambdifygenerated-567>:2: RuntimeWarning: overflow encountered in cosh
  return sin(sqrt(log(sqrt(x1*cosh(x1*(_a3_**2*_a6_**2/(x1*(_a7_ + x1**2)**x1 + x1)**2 + tanh((2*x1 + sin(_a5_))/_a3_))))/x1)))**x1
<lambdifygenerated-567>:2: RuntimeWarning: invalid value encountered in sqrt
  return sin(sqrt(log(sqrt(x1*cosh(x1*(_a3_**2*_a6_**2/(x1*(_a7_ + x1**2)**x1 + x1)**2 + tanh((2*x1 + sin(_a5_))/_a3_))))/x1)))**x1
<lambdifygenerated-567>:2: RuntimeWarning: invalid value encountered in power
  return sin(sqrt(log(sqrt(x1*cosh(x1*(_a3_**2*_a6_**2/(x1*(_a7_ + x1**2)**x1 + x1)**2 + tanh((2*x1 + sin(_a5_))/_a3_))))/x1)))**x1
<lambdifygenerated-568>:2: RuntimeWarning: overflow encountered in cosh
  return sin(sqrt(log(sqrt(x1*cosh(x1*(_a3_**2*_a6_**2/(x1*(_a7_ + x1**2)**x1 + x1)**2 + tanh((2*x1 + sin(_a5_))/_a3_))))/x1)))**x1
<lambdifygenerated-568>:2: RuntimeWarning: invalid value encountered in sqrt
  return sin(sqrt(log(sqrt(x1*cosh(x1*(_a3_**2*_a6_**2/(x1*(_a7_ + x1**2)**x1 + x1)**2 + tanh((2*x1 + sin(_a5_))/_a3_))))/x1)))**x1
<lambdifygenerated-568>:2: RuntimeWarning: invalid value encountered in power
  return sin(sqrt(log(sqrt(x1*cosh(x1*(_a3_**2*_a6_**2/(x1*(_a7_ + x1**2)**x1 + x1)**2 + tanh((2*x1 + sin(_a5_))/_a3_))))/x1)))**x1
<lambdifygenerated-569>:2: RuntimeWarning: overflow encountered in cosh
  return sin(sqrt(log(sqrt(x1*cosh(x1*(_a3_**2*_a6_**2/(x1*(_a7_ + x1**2)**x1 + x1)**2 + tanh((2*x1 + sin(_a5_))/_a3_))))/x1)))**x1
<lambdifygenerated-569>:2: RuntimeWarning: invalid value encountered in sqrt
  return sin(sqrt(log(sqrt(x1*cosh(x1*(_a3_**2*_a6_**2/(x1*(_a7_ + x1**2)**x1 + x1)**2 + tanh((2*x1 + sin(_a5_))/_a3_))))/x1)))**x1
<lambdifygenerated-569>:2: RuntimeWarning: invalid value encountered in power
  return sin(sqrt(log(sqrt(x1*cosh(x1*(_a3_**2*_a6_**2/(x1*(_a7_ + x1**2)**x1 + x1)**2 + tanh((2*x1 + sin(_a5_))/_a3_))))/x1)))**x1
<lambdifygenerated-570>:2: RuntimeWarning: overflow encountered in cosh
  return sin(sqrt(log(sqrt(x1*cosh(x1*(_a3_**2*_a6_**2/(x1*(_a7_ + x1**2)**x1 + x1)**2 + tanh((2*x1 + sin(_a5_))/_a3_))))/x1)))**x1
<lambdifygenerated-570>:2: RuntimeWarning: invalid value encountered in sqrt
  return sin(sqrt(log(sqrt(x1*cosh(x1*(_a3_**2*_a6_**2/(x1*(_a7_ + x1**2)**x1 + x1)**2 + tanh((2*x1 + sin(_a5_))/_a3_))))/x1)))**x1
<lambdifygenerated-570>:2: RuntimeWarning: invalid value encountered in power
  return sin(sqrt(log(sqrt(x1*cosh(x1*(_a3_**2*_a6_**2/(x1*(_a7_ + x1**2)**x1 + x1)**2 + tanh((2*x1 + sin(_a5_))/_a3_))))/x1)))**x1
<lambdifygenerated-571>:2: RuntimeWarning: invalid value encountered in power
  return sin(sqrt(log(sqrt(x1*cosh(x1*(_a3_**2*_a6_**2/(x1*(_a4_*x1 + _a7_)**x1 + x1)**2 + tanh((2*x1 + sin(_a5_))/_a3_))))/x1)))**x1
<lambdifygenerated-571>:2: RuntimeWarning: overflow encountered in cosh
  return sin(sqrt(log(sqrt(x1*cosh(x1*(_a3_**2*_a6_**2/(x1*(_a4_*x1 + _a7_)**x1 + x1)**2 + tanh((2*x1 + sin(_a5_))/_a3_))))/x1)))**x1
<lambdifygenerated-571>:2: RuntimeWarning: invalid value encountered in sqrt
  return sin(sqrt(log(sqrt(x1*cosh(x1*(_a3_**2*_a6_**2/(x1*(_a4_*x1 + _a7_)**x1 + x1)**2 + tanh((2*x1 + sin(_a5_))/_a3_))))/x1)))**x1
<lambdifygenerated-572>:2: RuntimeWarning: invalid value encountered in power
  return sin(sqrt(log(sqrt(x1*cosh(x1*(_a3_**2*_a6_**2/(x1*(_a4_*x1 + _a7_)**x1 + x1)**2 + tanh((2*x1 + sin(_a5_))/_a3_))))/x1)))**x1
<lambdifygenerated-572>:2: RuntimeWarning: overflow encountered in cosh
  return sin(sqrt(log(sqrt(x1*cosh(x1*(_a3_**2*_a6_**2/(x1*(_a4_*x1 + _a7_)**x1 + x1)**2 + tanh((2*x1 + sin(_a5_))/_a3_))))/x1)))**x1
<lambdifygenerated-572>:2: RuntimeWarning: invalid value encountered in sqrt
  return sin(sqrt(log(sqrt(x1*cosh(x1*(_a3_**2*_a6_**2/(x1*(_a4_*x1 + _a7_)**x1 + x1)**2 + tanh((2*x1 + sin(_a5_))/_a3_))))/x1)))**x1
<lambdifygenerated-573>:2: RuntimeWarning: invalid value encountered in power
  return sin(sqrt(log(sqrt(x1*cosh(x1*(_a3_**2*_a6_**2/(x1*(_a4_*x1 + _a7_)**sinh(x1) + x1)**2 + tanh((2*x1 + sin(_a5_))/_a3_))))/x1)))**x1
<lambdifygenerated-573>:2: RuntimeWarning: overflow encountered in cosh
  return sin(sqrt(log(sqrt(x1*cosh(x1*(_a3_**2*_a6_**2/(x1*(_a4_*x1 + _a7_)**sinh(x1) + x1)**2 + tanh((2*x1 + sin(_a5_))/_a3_))))/x1)))**x1
<lambdifygenerated-573>:2: RuntimeWarning: invalid value encountered in sqrt
  return sin(sqrt(log(sqrt(x1*cosh(x1*(_a3_**2*_a6_**2/(x1*(_a4_*x1 + _a7_)**sinh(x1) + x1)**2 + tanh((2*x1 + sin(_a5_))/_a3_))))/x1)))**x1
<lambdifygenerated-574>:2: RuntimeWarning: invalid value encountered in power
  return sin(sqrt(log(sqrt(x1*cosh(x1*(_a3_**2*_a6_**2/(x1*(_a4_*x1 + _a7_)**sinh(x1) + x1)**2 + tanh((2*x1 + sin(_a5_))/_a3_))))/x1)))**x1
<lambdifygenerated-574>:2: RuntimeWarning: overflow encountered in cosh
  return sin(sqrt(log(sqrt(x1*cosh(x1*(_a3_**2*_a6_**2/(x1*(_a4_*x1 + _a7_)**sinh(x1) + x1)**2 + tanh((2*x1 + sin(_a5_))/_a3_))))/x1)))**x1
<lambdifygenerated-574>:2: RuntimeWarning: invalid value encountered in sqrt
  return sin(sqrt(log(sqrt(x1*cosh(x1*(_a3_**2*_a6_**2/(x1*(_a4_*x1 + _a7_)**sinh(x1) + x1)**2 + tanh((2*x1 + sin(_a5_))/_a3_))))/x1)))**x1
<lambdifygenerated-575>:2: RuntimeWarning: invalid value encountered in power
  return sin(sqrt(log(sqrt(x1*cosh(x1*(_a3_**2*_a6_**2/(x1*(_a4_*x1 + _a7_)**sinh(x1) + x1)**2 + tanh((2*x1 + sin(_a5_))/_a3_))))/x1)))**x1
<lambdifygenerated-575>:2: RuntimeWarning: overflow encountered in cosh
  return sin(sqrt(log(sqrt(x1*cosh(x1*(_a3_**2*_a6_**2/(x1*(_a4_*x1 + _a7_)**sinh(x1) + x1)**2 + tanh((2*x1 + sin(_a5_))/_a3_))))/x1)))**x1
<lambdifygenerated-575>:2: RuntimeWarning: invalid value encountered in sqrt
  return sin(sqrt(log(sqrt(x1*cosh(x1*(_a3_**2*_a6_**2/(x1*(_a4_*x1 + _a7_)**sinh(x1) + x1)**2 + tanh((2*x1 + sin(_a5_))/_a3_))))/x1)))**x1
<lambdifygenerated-576>:2: RuntimeWarning: invalid value encountered in power
  return sin(sqrt(log(sqrt(x1*cosh(x1*(_a3_**2*_a6_**2/(x1*(_a4_*x1 + _a7_)**sinh(x1) + x1)**2 + tanh((2*x1 + sin(_a5_))/_a3_))))/x1)))**x1
<lambdifygenerated-576>:2: RuntimeWarning: overflow encountered in cosh
  return sin(sqrt(log(sqrt(x1*cosh(x1*(_a3_**2*_a6_**2/(x1*(_a4_*x1 + _a7_)**sinh(x1) + x1)**2 + tanh((2*x1 + sin(_a5_))/_a3_))))/x1)))**x1
<lambdifygenerated-576>:2: RuntimeWarning: invalid value encountered in sqrt
  return sin(sqrt(log(sqrt(x1*cosh(x1*(_a3_**2*_a6_**2/(x1*(_a4_*x1 + _a7_)**sinh(x1) + x1)**2 + tanh((2*x1 + sin(_a5_))/_a3_))))/x1)))**x1
<lambdifygenerated-577>:2: RuntimeWarning: invalid value encountered in power
  return sin(sqrt(log(sqrt(x1*cosh(x1*(_a3_**2*_a6_**2/(-x1*(_a4_*x1 + _a7_)**sinh(x1) + x1)**2 + tanh((2*x1 + sin(_a5_))/_a3_))))/x1)))**x1
<lambdifygenerated-577>:2: RuntimeWarning: divide by zero encountered in divide
  return sin(sqrt(log(sqrt(x1*cosh(x1*(_a3_**2*_a6_**2/(-x1*(_a4_*x1 + _a7_)**sinh(x1) + x1)**2 + tanh((2*x1 + sin(_a5_))/_a3_))))/x1)))**x1
<lambdifygenerated-577>:2: RuntimeWarning: overflow encountered in cosh
  return sin(sqrt(log(sqrt(x1*cosh(x1*(_a3_**2*_a6_**2/(-x1*(_a4_*x1 + _a7_)**sinh(x1) + x1)**2 + tanh((2*x1 + sin(_a5_))/_a3_))))/x1)))**x1
<lambdifygenerated-577>:2: RuntimeWarning: invalid value encountered in sqrt

interpolation

<lambdifygenerated-583>:2: RuntimeWarning: invalid value encountered in power
  return sin(sqrt(log(sqrt(x1*cosh((_a3_**2*_a6_**2/(-_a0_*(_a4_*x1 + _a7_)**sinh(x1) + _a2_)**2 + tanh((2*x1 + sin(_a5_))/_a3_))*sin(x1)))/x1)))**x1
<lambdifygenerated-583>:2: RuntimeWarning: divide by zero encountered in divide
  return sin(sqrt(log(sqrt(x1*cosh((_a3_**2*_a6_**2/(-_a0_*(_a4_*x1 + _a7_)**sinh(x1) + _a2_)**2 + tanh((2*x1 + sin(_a5_))/_a3_))*sin(x1)))/x1)))**x1
<lambdifygenerated-583>:2: RuntimeWarning: overflow encountered in cosh
  return sin(sqrt(log(sqrt(x1*cosh((_a3_**2*_a6_**2/(-_a0_*(_a4_*x1 + _a7_)**sinh(x1) + _a2_)**2 + tanh((2*x1 + sin(_a5_))/_a3_))*sin(x1)))/x1)))**x1
<lambdifygenerated-583>:2: RuntimeWarning: invalid value encountered in sqrt
  return sin(sqrt(log(sqrt(x1*cosh((_a3_**2*_a6_**2/(-_a0_*(_a4_*x1 + _a7_)**sinh(x1) + _a2_)**2 + tanh((2*x1 + sin(_a5_))/_a3_))*sin(x1)))/x1)))**x1
<lambdifygenerated-583>:2: RuntimeWarning: invalid value encountered in sin
  return sin(sqrt(log(sqrt(x1*cosh((_a3_**2*_a6_**2/(-_a0_*(_a4_*x1 + _a7_)**sinh(x1) + _a2_)**2 + tanh((2*x1 + sin(_a5_))/_a3_))*sin(x1)))/x1)))**x1
<lambdifygenerated-584>:2: RuntimeWarning: invalid value encountered in power
  return sin(sqrt(log(sqrt(x1*cosh((_a3_**2*_a6_**2/(-_a0_*(_a4_*x1 + _a7_)**sinh(x1) + _a2_)**2 + tanh((2*x1 + sin(_a5_))/_a3_))*sin(x1)))/x1)))**x1
<lambdifygenerated-584>:2: RuntimeWarning: divide by zero encountered in divide
  return sin(sqrt(log(sqrt(x1*cosh((_a3_**2*_a6_**2/(-_a0_*(_a4_*x1 + _a7_)**sinh(x1) + _a2_)**2 + tanh((2*x1 + sin(_a5_))/_a3_))*sin(x1)))/x1)))**x1
<lambdifygenerated-584>:2: RuntimeWarning: overflow encountered in cosh
  return sin(sqrt(log(sqrt(x1*cosh((_a3_**2*_a6_**2/(-_a0_*(_a4_*x1 + _a7_)**sinh(x1) + _a2_)**2 + tanh((2*x1 + sin(_a5_))/_a3_))*sin(x1)))/x1)))**x1
<lambdifygenerated-584>:2: RuntimeWarning: invalid value encountered in sqrt
  return sin(sqrt(log(sqrt(x1*cosh((_a3_**2*_a6_**2/(-_a0_*(_a4_*x1 + _a7_)**sinh(x1) + _a2_)**2 + tanh((2*x1 + sin(_a5_))/_a3_))*sin(x1)))/x1)))**x1
<lambdifygenerated-584>:2: RuntimeWarning: invalid value encountered in sin
  return sin(sqrt(log(sqrt(x1*cosh((_a3_**2*_a6_**2/(-_a0_*(_a4_*x1 + _a7_)**sinh(x1) + _a2_)**2 + tanh((2*x1 + sin(_a5_))/_a3_))*sin(x1)))/x1)))**x1
<lambdifygenerated-585>:2: RuntimeWarning: invalid value encountered in power
  return sin(sqrt(log(sqrt(x1*cosh((_a3_**2*_a6_**2/(-_a0_*(_a4_*x1 + _a7_)**sinh(x1) + _a2_)**2 + tanh((2*x1 + sin(_a5_))/_a3_))*sin(_a1_)))/x1)))**x1
<lambdifygenerated-585>:2: RuntimeWarning: divide by zero encountered in divide
  return sin(sqrt(log(sqrt(x1*cosh((_a3_**2*_a6_**2/(-_a0_*(_a4_*x1 + _a7_)**sinh(x1) + _a2_)**2 + tanh((2*x1 + sin(_a5_))/_a3_))*sin(_a1_)))/x1)))**x1
<lambdifygenerated-585>:2: RuntimeWarning: overflow encountered in cosh
  return sin(sqrt(log(sqrt(x1*cosh((_a3_**2*_a6_**2/(-_a0_*(_a4_*x1 + _a7_)**sinh(x1) + _a2_)**2 + tanh((2*x1 + sin(_a5_))/_a3_))*sin(_a1_)))/x1)))**x1
<lambdifygenerated-585>:2: RuntimeWarning: invalid value encountered in sqrt
  return sin(sqrt(log(sqrt(x1*cosh((_a3_**2*_a6_**2/(-_a0_*(_a4_*x1 + _a7_)**sinh(x1) + _a2_)**2 + tanh((2*x1 + sin(_a5_))/_a3_))*sin(_a1_)))/x1)))**x1
<lambdifygenerated-585>:2: RuntimeWarning: invalid value encountered in sin
  return sin(sqrt(log(sqrt(x1*cosh((_a3_**2*_a6_**2/(-_a0_*(_a4_*x1 + _a7_)**sinh(x1) + _a2_)**2 + tanh((2*x1 + sin(_a5_))/_a3_))*sin(_a1_)))/x1)))**x1
<lambdifygenerated-586>:2: RuntimeWarning: invalid value encountered in power
  return sin(sqrt(log(sqrt(x1*cosh((_a3_**2*_a6_**2/(-_a0_*(_a4_*x1 + _a7_)**sinh(x1) + _a2_)**2 + tanh((2*x1 + sin(_a5_))/_a3_))*sin(_a1_)))/x1)))**x1
<lambdifygenerated-586>:2: RuntimeWarning: divide by zero encountered in divide
  return sin(sqrt(log(sqrt(x1*cosh((_a3_**2*_a6_**2/(-_a0_*(_a4_*x1 + _a7_)**sinh(x1) + _a2_)**2 + tanh((2*x1 + sin(_a5_))/_a3_))*sin(_a1_)))/x1)))**x1
<lambdifygenerated-586>:2: RuntimeWarning: overflow encountered in cosh
  return sin(sqrt(log(sqrt(x1*cosh((_a3_**2*_a6_**2/(-_a0_*(_a4_*x1 + _a7_)**sinh(x1) + _a2_)**2 + tanh((2*x1 + sin(_a5_))/_a3_))*sin(_a1_)))/x1)))**x1
<lambdifygenerated-586>:2: RuntimeWarning: invalid value encountered in sqrt
  return sin(sqrt(log(sqrt(x1*cosh((_a3_**2*_a6_**2/(-_a0_*(_a4_*x1 + _a7_)**sinh(x1) + _a2_)**2 + tanh((2*x1 + sin(_a5_))/_a3_))*sin(_a1_)))/x1)))**x1
<lambdifygenerated-586>:2: RuntimeWarning: invalid value encountered in sin
  return sin(sqrt(log(sqrt(x1*cosh((_a3_**2*_a6_**2/(-_a0_*(_a4_*x1 + _a7_)**sinh(x1) + _a2_)**2 + tanh((2*x1 + sin(_a5_))/_a3_))*sin(_a1_)))/x1)))**x1
<lambdifygenerated-587>:2: RuntimeWarning: invalid value encountered in power
  return sin(sqrt(log(sqrt(_a5_*cosh((_a3_**2*_a6_**2/(-_a0_*(_a4_*x1 + _a7_)**sinh(x1) + _a2_)**2 + tanh((2*x1 + sin(_a5_))/_a3_))*sin(_a1_)))/x1)))**x1
<lambdifygenerated-587>:2: RuntimeWarning: divide by zero encountered in divide
  return sin(sqrt(log(sqrt(_a5_*cosh((_a3_**2*_a6_**2/(-_a0_*(_a4_*x1 + _a7_)**sinh(x1) + _a2_)**2 + tanh((2*x1 + sin(_a5_))/_a3_))*sin(_a1_)))/x1)))**x1
<lambdifygenerated-587>:2: RuntimeWarning: overflow encountered in cosh
  return sin(sqrt(log(sqrt(_a5_*cosh((_a3_**2*_a6_**2/(-_a0_*(_a4_*x1 + _a7_)**sinh(x1) + _a2_)**2 + tanh((2*x1 + sin(_a5_))/_a3_))*sin(_a1_)))/x1)))**x1
<lambdifygenerated-587>:2: RuntimeWarning: invalid value encountered in log
  return sin(sqrt(log(sqrt(_a5_*cosh((_a3_**2*_a6_**2/(-_a0_*(_a4_*x1 + _a7_)**sinh(x1) + _a2_)**2 + tanh((2*x1 + sin(_a5_))/_a3_))*sin(_a1_)))/x1)))**x1
<lambdifygenerated-587>:2: RuntimeWarning: invalid value encountered in sqrt
  return sin(sqrt(log(sqrt(_a5_*cosh((_a3_**2*_a6_**2/(-_a0_*(_a4_*x1 + _a7_)**sinh(x1) + _a2_)**2 + tanh((2*x1 + sin(_a5_))/_a3_))*sin(_a1_)))/x1)))**x1
<lambdifygenerated-587>:2: RuntimeWarning: invalid value encountered in sin
  return sin(sqrt(log(sqrt(_a5_*cosh((_a3_**2*_a6_**2/(-_a0_*(_a4_*x1 + _a7_)**sinh(x1) + _a2_)**2 + tanh((2*x1 + sin(_a5_))/_a3_))*sin(_a1_)))/x1)))**x1
<lambdifygenerated-588>:2: RuntimeWarning: invalid value encountered in power
  return sin(sqrt(log(sqrt(_a5_*cosh((_a3_**2*_a6_**2/(-_a0_*(_a4_*x1 + _a7_)**sinh(x1) + _a2_)**2 + tanh((2*x1 + sin(_a5_))/_a3_))*sin(_a1_)))/x1)))**x1
<lambdifygenerated-588>:2: RuntimeWarning: divide by zero encountered in divide
  return sin(sqrt(log(sqrt(_a5_*cosh((_a3_**2*_a6_**2/(-_a0_*(_a4_*x1 + _a7_)**sinh(x1) + _a2_)**2 + tanh((2*x1 + sin(_a5_))/_a3_))*sin(_a1_)))/x1)))**x1
<lambdifygenerated-588>:2: RuntimeWarning: overflow encountered in cosh
  return sin(sqrt(log(sqrt(_a5_*cosh((_a3_**2*_a6_**2/(-_a0_*(_a4_*x1 + _a7_)**sinh(x1) + _a2_)**2 + tanh((2*x1 + sin(_a5_))/_a3_))*sin(_a1_)))/x1)))**x1
<lambdifygenerated-588>:2: RuntimeWarning: invalid value encountered in log
  return sin(sqrt(log(sqrt(_a5_*cosh((_a3_**2*_a6_**2/(-_a0_*(_a4_*x1 + _a7_)**sinh(x1) + _a2_)**2 + tanh((2*x1 + sin(_a5_))/_a3_))*sin(_a1_)))/x1)))**x1
<lambdifygenerated-588>:2: RuntimeWarning: invalid value encountered in sqrt
  return sin(sqrt(log(sqrt(_a5_*cosh((_a3_**2*_a6_**2/(-_a0_*(_a4_*x1 + _a7_)**sinh(x1) + _a2_)**2 + tanh((2*x1 + sin(_a5_))/_a3_))*sin(_a1_)))/x1)))**x1
<lambdifygenerated-588>:2: RuntimeWarning: invalid value encountered in sin
  return sin(sqrt(log(sqrt(_a5_*cosh((_a3_**2*_a6_**2/(-_a0_*(_a4_*x1 + _a7_)**sinh(x1) + _a2_)**2 + tanh((2*x1 + sin(_a5_))/_a3_))*sin(_a1_)))/x1)))**x1
<lambdifygenerated-589>:2: RuntimeWarning: invalid value encountered in power
  return sin(sqrt(log(sqrt(_a5_*cosh((_a3_**2*_a6_**2/(-_a0_*(_a4_*x1 + _a7_)**sinh(x1) + _a2_)**2 + tanh((2*x1 + sin(_a5_))/_a3_))*sin(_a1_)))/_a7_)))**x1
<lambdifygenerated-589>:2: RuntimeWarning: divide by zero encountered in divide
  return sin(sqrt(log(sqrt(_a5_*cosh((_a3_**2*_a6_**2/(-_a0_*(_a4_*x1 + _a7_)**sinh(x1) + _a2_)**2 + tanh((2*x1 + sin(_a5_))/_a3_))*sin(_a1_)))/_a7_)))**x1
<lambdifygenerated-589>:2: RuntimeWarning: overflow encountered in cosh
  return sin(sqrt(log(sqrt(_a5_*cosh((_a3_**2*_a6_**2/(-_a0_*(_a4_*x1 + _a7_)**sinh(x1) + _a2_)**2 + tanh((2*x1 + sin(_a5_))/_a3_))*sin(_a1_)))/_a7_)))**x1
<lambdifygenerated-589>:2: RuntimeWarning: invalid value encountered in sin
  return sin(sqrt(log(sqrt(_a5_*cosh((_a3_**2*_a6_**2/(-_a0_*(_a4_*x1 + _a7_)**sinh(x1) + _a2_)**2 + tanh((2*x1 + sin(_a5_))/_a3_))*sin(_a1_)))/_a7_)))**x1
<lambdifygenerated-590>:2: RuntimeWarning: invalid value encountered in power
  return sin(sqrt(log(sqrt(_a5_*cosh((_a3_**2*_a6_**2/(-_a0_*(_a4_*x1 + _a7_)**sinh(x1) + _a2_)**2 + tanh((2*x1 + sin(_a5_))/_a3_))*sin(_a1_)))/_a7_)))**x1
<lambdifygenerated-590>:2: RuntimeWarning: divide by zero encountered in divide
  return sin(sqrt(log(sqrt(_a5_*cosh((_a3_**2*_a6_**2/(-_a0_*(_a4_*x1 + _a7_)**sinh(x1) + _a2_)**2 + tanh((2*x1 + sin(_a5_))/_a3_))*sin(_a1_)))/_a7_)))**x1
<lambdifygenerated-590>:2: RuntimeWarning: overflow encountered in cosh
  return sin(sqrt(log(sqrt(_a5_*cosh((_a3_**2*_a6_**2/(-_a0_*(_a4_*x1 + _a7_)**sinh(x1) + _a2_)**2 + tanh((2*x1 + sin(_a5_))/_a3_))*sin(_a1_)))/_a7_)))**x1
<lambdifygenerated-590>:2: RuntimeWarning: invalid value encountered in sin
  return sin(sqrt(log(sqrt(_a5_*cosh((_a3_**2*_a6_**2/(-_a0_*(_a4_*x1 + _a7_)**sinh(x1) + _a2_)**2 + tanh((2*x1 + sin(_a5_))/_a3_))*sin(_a1_)))/_a7_)))**x1
<lambdifygenerated-591>:2: RuntimeWarning: invalid value encountered in power
  return sin(sqrt(log(sqrt(_a5_*cosh((_a3_**2*_a6_**2/(-_a0_*(_a4_*x1 + _a7_)**sinh(x1) + _a2_)**2 + tanh((2*x1 + sin(_a5_))/_a3_))*sin(_a1_)))/_a7_)))**_a1_
<lambdifygenerated-591>:2: RuntimeWarning: divide by zero encountered in divide
  return sin(sqrt(log(sqrt(_a5_*cosh((_a3_**2*_a6_**2/(-_a0_*(_a4_*x1 + _a7_)**sinh(x1) + _a2_)**2 + tanh((2*x1 + sin(_a5_))/_a3_))*sin(_a1_)))/_a7_)))**_a1_
<lambdifygenerated-591>:2: RuntimeWarning: overflow encountered in cosh
  return sin(sqrt(log(sqrt(_a5_*cosh((_a3_**2*_a6_**2/(-_a0_*(_a4_*x1 + _a7_)**sinh(x1) + _a2_)**2 + tanh((2*x1 + sin(_a5_))/_a3_))*sin(_a1_)))/_a7_)))**_a1_
<lambdifygenerated-591>:2: RuntimeWarning: invalid value encountered in sin
  return sin(sqrt(log(sqrt(_a5_*cosh((_a3_**2*_a6_**2/(-_a0_*(_a4_*x1 + _a7_)**sinh(x1) + _a2_)**2 + tanh((2*x1 + sin(_a5_))/_a3_))*sin(_a1_)))/_a7_)))**_a1_
<lambdifygenerated-592>:2: RuntimeWarning: invalid value encountered in power
  return sin(sqrt(log(sqrt(_a5_*cosh((_a3_**2*_a6_**2/(-_a0_*(_a4_*x1 + _a7_)**sinh(x1) + _a2_)**2 + tanh((2*x1 + sin(_a5_))/_a3_))*sin(_a1_)))/_a7_)))**_a1_
<lambdifygenerated-592>:2: RuntimeWarning: divide by zero encountered in divide
  return sin(sqrt(log(sqrt(_a5_*cosh((_a3_**2*_a6_**2/(-_a0_*(_a4_*x1 + _a7_)**sinh(x1) + _a2_)**2 + tanh((2*x1 + sin(_a5_))/_a3_))*sin(_a1_)))/_a7_)))**_a1_
<lambdifygenerated-592>:2: RuntimeWarning: overflow encountered in cosh
  return sin(sqrt(log(sqrt(_a5_*cosh((_a3_**2*_a6_**2/(-_a0_*(_a4_*x1 + _a7_)**sinh(x1) + _a2_)**2 + tanh((2*x1 + sin(_a5_))/_a3_))*sin(_a1_)))/_a7_)))**_a1_
<lambdifygenerated-592>:2: RuntimeWarning: invalid value encountered in sin
  return sin(sqrt(log(sqrt(_a5_*cosh((_a3_**2*_a6_**2/(-_a0_*(_a4_*x1 + _a7_)**sinh(x1) + _a2_)**2 + tanh((2*x1 + sin(_a5_))/_a3_))*sin(_a1_)))/_a7_)))**_a1_
<lambdifygenerated-593>:2: RuntimeWarning: invalid value encountered in power
  return sin(sqrt(log(sqrt(_a5_*cosh((_a3_**2*_a6_**2/(-_a0_*(_a4_*x1 + _a7_)**sinh(x1) + _a2_)**2 + tanh((2*x1 + sin(_a5_))/_a3_))*sin(_a1_)))/_a7_)))**_a1_
<lambdifygenerated-593>:2: RuntimeWarning: divide by zero encountered in divide
  return sin(sqrt(log(sqrt(_a5_*cosh((_a3_**2*_a6_**2/(-_a0_*(_a4_*x1 + _a7_)**sinh(x1) + _a2_)**2 + tanh((2*x1 + sin(_a5_))/_a3_))*sin(_a1_)))/_a7_)))**_a1_
<lambdifygenerated-593>:2: RuntimeWarning: overflow encountered in cosh
  return sin(sqrt(log(sqrt(_a5_*cosh((_a3_**2*_a6_**2/(-_a0_*(_a4_*x1 + _a7_)**sinh(x1) + _a2_)**2 + tanh((2*x1 + sin(_a5_))/_a3_))*sin(_a1_)))/_a7_)))**_a1_
<lambdifygenerated-593>:2: RuntimeWarning: invalid value encountered in sin
  return sin(sqrt(log(sqrt(_a5_*cosh((_a3_**2*_a6_**2/(-_a0_*(_a4_*x1 + _a7_)**sinh(x1) + _a2_)**2 + tanh((2*x1 + sin(_a5_))/_a3_))*sin(_a1_)))/_a7_)))**_a1_
<lambdifygenerated-594>:2: RuntimeWarning: invalid value encountered in power
  return sin(sqrt(log(sqrt(_a5_*cosh((_a3_**2*_a6_**2/(-_a0_*(_a4_*x1 + _a7_)**sinh(x1) + _a2_)**2 + tanh((2*x1 + sin(_a5_))/_a3_))*sin(_a1_)))/_a7_)))**_a1_
<lambdifygenerated-594>:2: RuntimeWarning: divide by zero encountered in divide
  return sin(sqrt(log(sqrt(_a5_*cosh((_a3_**2*_a6_**2/(-_a0_*(_a4_*x1 + _a7_)**sinh(x1) + _a2_)**2 + tanh((2*x1 + sin(_a5_))/_a3_))*sin(_a1_)))/_a7_)))**_a1_
<lambdifygenerated-594>:2: RuntimeWarning: overflow encountered in cosh
  return sin(sqrt(log(sqrt(_a5_*cosh((_a3_**2*_a6_**2/(-_a0_*(_a4_*x1 + _a7_)**sinh(x1) + _a2_)**2 + tanh((2*x1 + sin(_a5_))/_a3_))*sin(_a1_)))/_a7_)))**_a1_
<lambdifygenerated-594>:2: RuntimeWarning: invalid value encountered in sin
  return sin(sqrt(log(sqrt(_a5_*cosh((_a3_**2*_a6_**2/(-_a0_*(_a4_*x1 + _a7_)**sinh(x1) + _a2_)**2 + tanh((2*x1 + sin(_a5_))/_a3_))*sin(_a1_)))/_a7_)))**_a1_
<lambdifygenerated-595>:2: RuntimeWarning: invalid value encountered in power
  return sin(sqrt(log(sqrt(_a5_*cosh((_a3_**2*_a6_**2/(-_a0_*(_a4_*x1 + _a7_)**sinh(x1) + _a2_)**2 + tanh((2*x1 + sin(_a5_))/_a3_))*sin(_a1_)))/_a7_)))**_a1_
<lambdifygenerated-595>:2: RuntimeWarning: divide by zero encountered in divide
  return sin(sqrt(log(sqrt(_a5_*cosh((_a3_**2*_a6_**2/(-_a0_*(_a4_*x1 + _a7_)**sinh(x1) + _a2_)**2 + tanh((2*x1 + sin(_a5_))/_a3_))*sin(_a1_)))/_a7_)))**_a1_
<lambdifygenerated-595>:2: RuntimeWarning: overflow encountered in cosh
  return sin(sqrt(log(sqrt(_a5_*cosh((_a3_**2*_a6_**2/(-_a0_*(_a4_*x1 + _a7_)**sinh(x1) + _a2_)**2 + tanh((2*x1 + sin(_a5_))/_a3_))*sin(_a1_)))/_a7_)))**_a1_
<lambdifygenerated-595>:2: RuntimeWarning: invalid value encountered in sin
  return sin(sqrt(log(sqrt(_a5_*cosh((_a3_**2*_a6_**2/(-_a0_*(_a4_*x1 + _a7_)**sinh(x1) + _a2_)**2 + tanh((2*x1 + sin(_a5_))/_a3_))*sin(_a1_)))/_a7_)))**_a1_
<lambdifygenerated-596>:2: RuntimeWarning: invalid value encountered in power
  return sin(sqrt(log(sqrt(_a5_*cosh((_a3_**2*_a6_**2/(-_a0_*(_a4_*x1 + _a7_)**sinh(x1) + _a2_)**2 + tanh((2*x1 + sin(_a5_))/_a3_))*sin(_a1_)))/_a7_)))**_a1_
<lambdifygenerated-596>:2: RuntimeWarning: divide by zero encountered in divide
  return sin(sqrt(log(sqrt(_a5_*cosh((_a3_**2*_a6_**2/(-_a0_*(_a4_*x1 + _a7_)**sinh(x1) + _a2_)**2 + tanh((2*x1 + sin(_a5_))/_a3_))*sin(_a1_)))/_a7_)))**_a1_
<lambdifygenerated-596>:2: RuntimeWarning: overflow encountered in cosh
  return sin(sqrt(log(sqrt(_a5_*cosh((_a3_**2*_a6_**2/(-_a0_*(_a4_*x1 + _a7_)**sinh(x1) + _a2_)**2 + tanh((2*x1 + sin(_a5_))/_a3_))*sin(_a1_)))/_a7_)))**_a1_
<lambdifygenerated-596>:2: RuntimeWarning: invalid value encountered in sin
  return sin(sqrt(log(sqrt(_a5_*cosh((_a3_**2*_a6_**2/(-_a0_*(_a4_*x1 + _a7_)**sinh(x1) + _a2_)**2 + tanh((2*x1 + sin(_a5_))/_a3_))*sin(_a1_)))/_a7_)))**_a1_

         x1         y  rep    ymodel      ybms
3745  0.997  0.308339  5.0  0.310360  0.310721
3746  0.998  0.308354  5.0  0.310424  0.310786
3747  0.998  0.308368  5.0  0.310487  0.310851
3748  0.999  0.308382  5.0  0.310550  0.310916

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.308407  5.0  0.310675  0.311044
3751  1.002  0.308419  5.0  0.310738  0.311108
3752  1.002  0.308430  5.0  0.310800  0.311172
3753  1.003  0.308441  5.0  0.310863  0.311236

3750

<lambdifygenerated-635>:2: RuntimeWarning: invalid value encountered in power
  return (-x1*tanh(x1*(x1 + cos(_a3_*x1/cosh(_a6_ + x1**x1) - x1))) + x1)/x1**2
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-636>:2: RuntimeWarning: invalid value encountered in power
  return (-x1*tanh(x1*(x1 + cos(_a3_*x1/cosh(_a6_ + x1**x1) - x1))) + x1)/x1**2
<lambdifygenerated-639>:2: RuntimeWarning: overflow encountered in cosh
  return (-x1*tanh(x1*(x1 + cos(_a3_*x1/cosh(_a6_ + (_a5_**2)**x1) - x1))) + x1)/x1**2
<lambdifygenerated-641>:2: RuntimeWarning: overflow encountered in cosh
  return (-x1*tanh(x1*(x1 + cos(_a3_*x1/cosh(_a6_ + (_a5_**2)**(2*x1)) - x1))) + x1)/x1**2
<lambdifygenerated-643>:2: RuntimeWarning: overflow encountered in cosh
  return (-x1*tanh(x1*(x1 + cos(_a3_*x1/cosh(_a6_ + (_a5_**2)**(_a0_ + x1)) - x1))) + x1)/x1**2
<lambdifygenerated-647>:2: RuntimeWarning: overflow encountered in cosh
  return (-x1*tanh(x1*(x1 + cos(_a0_*_a3_/cosh(_a6_ + (_a5_**2)**(_a0_ + x1)) - x1))) + x1)/x1**2
<lambdifygenerated-669>:2: RuntimeWarning: overflow encountered in cosh
  return (-x1*tanh(x1*(_a6_**3 + cos(-_a0_*_a3_/cosh(_a6_ + (_a5_**2)**(_a0_ + x1)) + _a1_ + _a7_/(_a4_*(_a3_ + x1))))) + x1)/x1**2
<lambdifygenerated-670>:2: RuntimeWarning: overflow encountered in cosh
  return (-x1*tanh(x1*(_a6_**3 + cos(-_a0_*_a3_/cosh(_a6_ + (_a5_**2)**(_a0_ + x1)) + _a1_ + _a7_/(_a4_*(_a3_ + x1))))) + x1)/x1**2
<lambdifygenerated-671>:2: RuntimeWarning: overflow encountered in cosh
  return (-x1*tanh(2*x1*(_a6_**3 + cos(-_a0_*_a3_/cosh(_a6_ + (_a5_**2)**(_a0_ + x1)) + _a1_ + _a7_/(_a4_*(_a3_ + x1))))) + x1)/x1**2
<lambdifygenerated-672>:2: RuntimeWarning: overflow encountered in cosh
  return (-x1*tanh(2*x1*(_a6_**3 + cos(-_a0_*_a3_/cosh(_a6_ + (_a5_**2)**(_a0_ + x1)) + _a1_ + _a7_/(_a4_*(_a3_ + x1))))) + x1)/x1**2
<lambdifygenerated-673>:2: RuntimeWarning: overflow encountered in cosh
  return (-x1*tanh((_a4_ + x1)*(_a6_**3 + cos(-_a0_*_a3_/cosh(_a6_ + (_a5_**2)**(_a0_ + x1)) + _a1_ + _a7_/(_a4_*(_a3_ + x1))))) + x1)/x1**2
<lambdifygenerated-674>:2: RuntimeWarning: overflow encountered in cosh
  return (-x1*tanh((_a4_ + x1)*(_a6_**3 + cos(-_a0_*_a3_/cosh(_a6_ + (_a5_**2)**(_a0_ + x1)) + _a1_ + _a7_/(_a4_*(_a3_ + x1))))) + x1)/x1**2
<lambdifygenerated-675>:2: RuntimeWarning: overflow encountered in cosh
  return (-x1*tanh((_a4_ + x1)*(_a6_**3 + cos(-_a0_*_a3_/cosh(_a6_ + (_a5_**2)**(_a0_ + x1)) + _a1_ + _a7_/(_a4_*(_a3_ + x1))))) + x1)/x1**2
<lambdifygenerated-676>:2: RuntimeWarning: overflow encountered in cosh
  return (-x1*tanh((_a4_ + x1)*(_a6_**3 + cos(-_a0_*_a3_/cosh(_a6_ + (_a5_**2)**(_a0_ + x1)) + _a1_ + _a7_/(_a4_*(_a3_ + x1))))) + x1)/x1**2
<lambdifygenerated-677>:2: RuntimeWarning: overflow encountered in cosh
  return (-_a2_*tanh((_a4_ + x1)*(_a6_**3 + cos(-_a0_*_a3_/cosh(_a6_ + (_a5_**2)**(_a0_ + x1)) + _a1_ + _a7_/(_a4_*(_a3_ + x1))))) + x1)/x1**2

interpolation

<lambdifygenerated-678>:2: RuntimeWarning: overflow encountered in cosh
  return (-_a2_*tanh((_a4_ + x1)*(_a6_**3 + cos(-_a0_*_a3_/cosh(_a6_ + (_a5_**2)**(_a0_ + x1)) + _a1_ + _a7_/(_a4_*(_a3_ + x1))))) + x1)/x1**2
<lambdifygenerated-679>:2: RuntimeWarning: overflow encountered in cosh
  return (-_a2_*tanh((_a4_ + x1)*(_a6_**3 + cos(-_a0_*_a3_/cosh(_a6_ + (_a5_**2)**(_a0_ + x1)) + _a1_ + _a7_/(_a4_*(_a3_ + x1))))) + 2*x1)/x1**2
<lambdifygenerated-680>:2: RuntimeWarning: overflow encountered in cosh
  return (-_a2_*tanh((_a4_ + x1)*(_a6_**3 + cos(-_a0_*_a3_/cosh(_a6_ + (_a5_**2)**(_a0_ + x1)) + _a1_ + _a7_/(_a4_*(_a3_ + x1))))) + 2*x1)/x1**2
<lambdifygenerated-681>:2: RuntimeWarning: overflow encountered in cosh
  return (-_a2_*tanh((_a4_ + x1)*(_a6_**3 + cos(-_a0_*_a3_/cosh(_a6_ + (_a5_**2)**(_a0_ + x1)) + _a1_ + _a7_/(_a4_*(_a3_ + x1))))) + 2*x1)/x1**2
<lambdifygenerated-682>:2: RuntimeWarning: overflow encountered in cosh
  return (-_a2_*tanh((_a4_ + x1)*(_a6_**3 + cos(-_a0_*_a3_/cosh(_a6_ + (_a5_**2)**(_a0_ + x1)) + _a1_ + _a7_/(_a4_*(_a3_ + x1))))) + 2*x1)/x1**2
<lambdifygenerated-683>:2: RuntimeWarning: overflow encountered in cosh
  return (_a1_ - _a2_*tanh((_a4_ + x1)*(_a6_**3 + cos(-_a0_*_a3_/cosh(_a6_ + (_a5_**2)**(_a0_ + x1)) + _a1_ + _a7_/(_a4_*(_a3_ + x1))))) + x1)/x1**2
<lambdifygenerated-684>:2: RuntimeWarning: overflow encountered in cosh
  return (_a1_ - _a2_*tanh((_a4_ + x1)*(_a6_**3 + cos(-_a0_*_a3_/cosh(_a6_ + (_a5_**2)**(_a0_ + x1)) + _a1_ + _a7_/(_a4_*(_a3_ + x1))))) + x1)/x1**2
<lambdifygenerated-685>:2: RuntimeWarning: overflow encountered in cosh
  return (_a1_ - _a2_*tanh((_a4_ + x1)*(_a6_**3 + cos(-_a0_*_a3_/cosh(_a6_ + (_a5_**2)**(_a0_ + x1)) + _a1_ + _a7_/(_a4_*(_a3_ + x1))))) + x1)/(_a4_*x1)
<lambdifygenerated-686>:2: RuntimeWarning: overflow encountered in cosh
  return (_a1_ - _a2_*tanh((_a4_ + x1)*(_a6_**3 + cos(-_a0_*_a3_/cosh(_a6_ + (_a5_**2)**(_a0_ + x1)) + _a1_ + _a7_/(_a4_*(_a3_ + x1))))) + x1)/(_a4_*x1)
<lambdifygenerated-687>:2: RuntimeWarning: overflow encountered in cosh
  return (_a1_ - _a2_*tanh((_a4_ + x1)*(_a6_**3 + cos(-_a0_*_a3_/cosh(_a6_ + (_a5_**2)**(_a0_ + x1)) + _a1_ + _a7_/(_a4_*(_a3_ + x1))))) + x1)/_a4_**2
<lambdifygenerated-688>:2: RuntimeWarning: overflow encountered in cosh
  return (_a1_ - _a2_*tanh((_a4_ + x1)*(_a6_**3 + cos(-_a0_*_a3_/cosh(_a6_ + (_a5_**2)**(_a0_ + x1)) + _a1_ + _a7_/(_a4_*(_a3_ + x1))))) + x1)/_a4_**2
<lambdifygenerated-689>:2: RuntimeWarning: overflow encountered in cosh
  return (_a1_ - _a2_*tanh((_a4_ + x1)*(_a6_**3 + cos(-_a0_*_a3_/cosh(_a6_ + (_a5_**2)**(_a0_ + x1)) + _a1_ + _a7_/(_a4_*(_a3_ + x1))))) + x1)/_a4_**2
<lambdifygenerated-690>:2: RuntimeWarning: overflow encountered in cosh
  return (_a1_ - _a2_*tanh((_a4_ + x1)*(_a6_**3 + cos(-_a0_*_a3_/cosh(_a6_ + (_a5_**2)**(_a0_ + x1)) + _a1_ + _a7_/(_a4_*(_a3_ + x1))))) + x1)/_a4_**2
<lambdifygenerated-691>:2: RuntimeWarning: overflow encountered in cosh
  return (_a1_ - _a2_*tanh((_a4_ + x1)*(_a6_**3 + cos(-_a0_*_a3_/cosh(_a6_ + (_a5_**2)**(_a0_ + x1)) + _a1_ + _a7_/(_a4_*(_a3_ + x1))))) + x1)/_a4_**2
<lambdifygenerated-692>:2: RuntimeWarning: overflow encountered in cosh
  return (_a1_ - _a2_*tanh((_a4_ + x1)*(_a6_**3 + cos(-_a0_*_a3_/cosh(_a6_ + (_a5_**2)**(_a0_ + x1)) + _a1_ + _a7_/(_a4_*(_a3_ + x1))))) + x1)/_a4_**2

         x1         y  rep    ymodel      ybms
3745  0.997  0.215897  6.0  0.214971  0.215060
3746  0.998  0.216041  6.0  0.215103  0.215191
3747  0.998  0.216186  6.0  0.215235  0.215323
3748  0.999  0.216330  6.0  0.215366  0.215453

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.216618  6.0  0.215629  0.215714
3751  1.002  0.216762  6.0  0.215759  0.215844
3752  1.002  0.216905  6.0  0.215890  0.215974
3753  1.003  0.217048  6.0  0.216020  0.216103

3750

<lambdifygenerated-699>:2: RuntimeWarning: invalid value encountered in sqrt
  return tanh(sqrt(x1))
<lambdifygenerated-700>:2: RuntimeWarning: invalid value encountered in sqrt
  return tanh(sqrt(x1))
<lambdifygenerated-703>:2: RuntimeWarning: invalid value encountered in power
  return tanh(sqrt(x1*x1**x1))
<lambdifygenerated-704>:2: RuntimeWarning: invalid value encountered in power
  return tanh(sqrt(x1*x1**x1))
<lambdifygenerated-705>:2: RuntimeWarning: invalid value encountered in power
  return tanh(sqrt(x1*(2*x1)**x1))
<lambdifygenerated-706>:2: RuntimeWarning: invalid value encountered in power
  return tanh(sqrt(x1*(2*x1)**x1))
<lambdifygenerated-707>:2: RuntimeWarning: invalid value encountered in power
  return tanh(sqrt(x1*(x1**2 + x1)**x1))
<lambdifygenerated-707>:2: RuntimeWarning: invalid value encountered in sqrt
  return tanh(sqrt(x1*(x1**2 + x1)**x1))
<lambdifygenerated-708>:2: RuntimeWarning: invalid value encountered in power
  return tanh(sqrt(x1*(x1**2 + x1)**x1))
<lambdifygenerated-708>:2: RuntimeWarning: invalid value encountered in sqrt
  return tanh(sqrt(x1*(x1**2 + x1)**x1))
<lambdifygenerated-709>:2: RuntimeWarning: invalid value encountered in power
  return tanh(sqrt(x1*(x1*x1**x1 + x1)**x1))
<lambdifygenerated-710>:2: RuntimeWarning: invalid value encountered in power
  return tanh(sqrt(x1*(x1*x1**x1 + x1)**x1))
<lambdifygenerated-711>:2: RuntimeWarning: invalid value encountered in power
  return tanh(sqrt(x1*(x1*sinh(x1)**x1 + x1)**x1))
<lambdifygenerated-712>:2: RuntimeWarning: invalid value encountered in power
  return tanh(sqrt(x1*(x1*sinh(x1)**x1 + x1)**x1))
<lambdifygenerated-713>:2: RuntimeWarning: invalid value encountered in power
  return tanh(sqrt(x1*(x1*sinh(x1**x1)**x1 + x1)**x1))
<lambdifygenerated-714>:2: RuntimeWarning: invalid value encountered in power
  return tanh(sqrt(x1*(x1*sinh(x1**x1)**x1 + x1)**x1))
<lambdifygenerated-715>:2: RuntimeWarning: invalid value encountered in power
  return tanh(sqrt(x1*(x1*sinh(tanh(x1)**x1)**x1 + x1)**x1))
<lambdifygenerated-716>:2: RuntimeWarning: invalid value encountered in power
  return tanh(sqrt(x1*(x1*sinh(tanh(x1)**x1)**x1 + x1)**x1))
<lambdifygenerated-717>:2: RuntimeWarning: invalid value encountered in power
  return tanh(sqrt(x1*(x1*sinh(tanh(exp(x1))**x1)**x1 + x1)**x1))
<lambdifygenerated-718>:2: RuntimeWarning: invalid value encountered in power
  return tanh(sqrt(x1*(x1*sinh(tanh(exp(x1))**x1)**x1 + x1)**x1))
<lambdifygenerated-719>:2: RuntimeWarning: overflow encountered in sinh
  return tanh(sqrt(x1*(x1*sinh(tanh(exp(2*x1))**x1)**x1 + x1)**x1))
<lambdifygenerated-719>:2: RuntimeWarning: invalid value encountered in power
  return tanh(sqrt(x1*(x1*sinh(tanh(exp(2*x1))**x1)**x1 + x1)**x1))
<lambdifygenerated-720>:2: RuntimeWarning: overflow encountered in sinh
  return tanh(sqrt(x1*(x1*sinh(tanh(exp(2*x1))**x1)**x1 + x1)**x1))
<lambdifygenerated-720>:2: RuntimeWarning: invalid value encountered in power
  return tanh(sqrt(x1*(x1*sinh(tanh(exp(2*x1))**x1)**x1 + x1)**x1))
<lambdifygenerated-721>:2: RuntimeWarning: invalid value encountered in power
  return tanh(sqrt(x1*(x1*sinh(tanh(exp(x1 + 1))**x1)**x1 + x1)**x1))
<lambdifygenerated-722>:2: RuntimeWarning: invalid value encountered in power
  return tanh(sqrt(x1*(x1*sinh(tanh(exp(x1 + 1))**x1)**x1 + x1)**x1))
<lambdifygenerated-723>:2: RuntimeWarning: overflow encountered in sinh
  return tanh(sqrt(x1*(x1*sinh(tanh(exp(2*x1))**x1)**x1 + x1)**x1))
<lambdifygenerated-723>:2: RuntimeWarning: invalid value encountered in power
  return tanh(sqrt(x1*(x1*sinh(tanh(exp(2*x1))**x1)**x1 + x1)**x1))
<lambdifygenerated-724>:2: RuntimeWarning: overflow encountered in sinh
  return tanh(sqrt(x1*(x1*sinh(tanh(exp(2*x1))**x1)**x1 + x1)**x1))
<lambdifygenerated-724>:2: RuntimeWarning: invalid value encountered in power
  return tanh(sqrt(x1*(x1*sinh(tanh(exp(2*x1))**x1)**x1 + x1)**x1))
<lambdifygenerated-725>:2: RuntimeWarning: overflow encountered in sinh
  return tanh(sqrt(x1*(x1*sinh(tanh(exp(3*x1))**x1)**x1 + x1)**x1))
<lambdifygenerated-725>:2: RuntimeWarning: invalid value encountered in power
  return tanh(sqrt(x1*(x1*sinh(tanh(exp(3*x1))**x1)**x1 + x1)**x1))
<lambdifygenerated-726>:2: RuntimeWarning: overflow encountered in sinh
  return tanh(sqrt(x1*(x1*sinh(tanh(exp(3*x1))**x1)**x1 + x1)**x1))
<lambdifygenerated-726>:2: RuntimeWarning: invalid value encountered in power
  return tanh(sqrt(x1*(x1*sinh(tanh(exp(3*x1))**x1)**x1 + x1)**x1))
<lambdifygenerated-727>:2: RuntimeWarning: invalid value encountered in power
  return tanh(sqrt(x1*(x1*sinh(tanh(exp(x1**2 + 2*x1))**x1)**x1 + x1)**x1))
<lambdifygenerated-728>:2: RuntimeWarning: invalid value encountered in power
  return tanh(sqrt(x1*(x1*sinh(tanh(exp(x1**2 + 2*x1))**x1)**x1 + x1)**x1))
<lambdifygenerated-729>:2: RuntimeWarning: invalid value encountered in power
  return tanh(sqrt(x1*(x1*sinh(tanh(exp(x1**2 + 2*x1))**x1)**x1 + x1)**x1))
<lambdifygenerated-730>:2: RuntimeWarning: invalid value encountered in power
  return tanh(sqrt(x1*(x1*sinh(tanh(exp(x1**2 + 2*x1))**x1)**x1 + x1)**x1))
<lambdifygenerated-731>:2: RuntimeWarning: overflow encountered in sinh
  return tanh(sqrt(x1*(x1*sinh(tanh(exp(_a2_*x1 + 2*x1))**x1)**x1 + x1)**x1))
<lambdifygenerated-731>:2: RuntimeWarning: invalid value encountered in power
  return tanh(sqrt(x1*(x1*sinh(tanh(exp(_a2_*x1 + 2*x1))**x1)**x1 + x1)**x1))
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-732>:2: RuntimeWarning: overflow encountered in sinh
  return tanh(sqrt(x1*(x1*sinh(tanh(exp(_a2_*x1 + 2*x1))**x1)**x1 + x1)**x1))
<lambdifygenerated-732>:2: RuntimeWarning: invalid value encountered in power
  return tanh(sqrt(x1*(x1*sinh(tanh(exp(_a2_*x1 + 2*x1))**x1)**x1 + x1)**x1))
<lambdifygenerated-733>:2: RuntimeWarning: invalid value encountered in power
  return tanh(sqrt(x1*(x1*sinh(tanh(exp(_a2_*x1 + _a7_ + x1))**x1)**x1 + x1)**x1))
<lambdifygenerated-734>:2: RuntimeWarning: invalid value encountered in power
  return tanh(sqrt(x1*(x1*sinh(tanh(exp(_a2_*x1 + _a7_ + x1))**x1)**x1 + x1)**x1))
<lambdifygenerated-735>:2: RuntimeWarning: overflow encountered in exp
  return tanh(sqrt(x1*(x1*sinh(tanh(exp(_a4_*(_a2_*x1 + _a7_)/x1 + x1))**x1)**x1 + x1)**x1))
<lambdifygenerated-735>:2: RuntimeWarning: divide by zero encountered in power
  return tanh(sqrt(x1*(x1*sinh(tanh(exp(_a4_*(_a2_*x1 + _a7_)/x1 + x1))**x1)**x1 + x1)**x1))
<lambdifygenerated-735>:2: RuntimeWarning: invalid value encountered in power
  return tanh(sqrt(x1*(x1*sinh(tanh(exp(_a4_*(_a2_*x1 + _a7_)/x1 + x1))**x1)**x1 + x1)**x1))
<lambdifygenerated-736>:2: RuntimeWarning: overflow encountered in exp
  return tanh(sqrt(x1*(x1*sinh(tanh(exp(_a4_*(_a2_*x1 + _a7_)/x1 + x1))**x1)**x1 + x1)**x1))
<lambdifygenerated-736>:2: RuntimeWarning: divide by zero encountered in power
  return tanh(sqrt(x1*(x1*sinh(tanh(exp(_a4_*(_a2_*x1 + _a7_)/x1 + x1))**x1)**x1 + x1)**x1))
<lambdifygenerated-736>:2: RuntimeWarning: invalid value encountered in power
  return tanh(sqrt(x1*(x1*sinh(tanh(exp(_a4_*(_a2_*x1 + _a7_)/x1 + x1))**x1)**x1 + x1)**x1))
<lambdifygenerated-737>:2: RuntimeWarning: divide by zero encountered in power
  return tanh(sqrt(x1*(x1*sinh(tanh(exp((1/2)*_a4_*(_a2_*x1 + _a7_)/x1 + x1))**x1)**x1 + x1)**x1))
<lambdifygenerated-737>:2: RuntimeWarning: invalid value encountered in power
  return tanh(sqrt(x1*(x1*sinh(tanh(exp((1/2)*_a4_*(_a2_*x1 + _a7_)/x1 + x1))**x1)**x1 + x1)**x1))
<lambdifygenerated-738>:2: RuntimeWarning: divide by zero encountered in power
  return tanh(sqrt(x1*(x1*sinh(tanh(exp((1/2)*_a4_*(_a2_*x1 + _a7_)/x1 + x1))**x1)**x1 + x1)**x1))
<lambdifygenerated-738>:2: RuntimeWarning: invalid value encountered in power
  return tanh(sqrt(x1*(x1*sinh(tanh(exp((1/2)*_a4_*(_a2_*x1 + _a7_)/x1 + x1))**x1)**x1 + x1)**x1))
<lambdifygenerated-739>:2: RuntimeWarning: divide by zero encountered in power
  return tanh(sqrt(x1*(x1*sinh(tanh(exp(_a4_*(_a2_*x1 + _a7_)/(x1 + exp(x1)) + x1))**x1)**x1 + x1)**x1))
<lambdifygenerated-739>:2: RuntimeWarning: overflow encountered in sinh
  return tanh(sqrt(x1*(x1*sinh(tanh(exp(_a4_*(_a2_*x1 + _a7_)/(x1 + exp(x1)) + x1))**x1)**x1 + x1)**x1))
<lambdifygenerated-739>:2: RuntimeWarning: invalid value encountered in power
  return tanh(sqrt(x1*(x1*sinh(tanh(exp(_a4_*(_a2_*x1 + _a7_)/(x1 + exp(x1)) + x1))**x1)**x1 + x1)**x1))
<lambdifygenerated-740>:2: RuntimeWarning: divide by zero encountered in power
  return tanh(sqrt(x1*(x1*sinh(tanh(exp(_a4_*(_a2_*x1 + _a7_)/(x1 + exp(x1)) + x1))**x1)**x1 + x1)**x1))
<lambdifygenerated-740>:2: RuntimeWarning: overflow encountered in sinh
  return tanh(sqrt(x1*(x1*sinh(tanh(exp(_a4_*(_a2_*x1 + _a7_)/(x1 + exp(x1)) + x1))**x1)**x1 + x1)**x1))
<lambdifygenerated-740>:2: RuntimeWarning: invalid value encountered in power
  return tanh(sqrt(x1*(x1*sinh(tanh(exp(_a4_*(_a2_*x1 + _a7_)/(x1 + exp(x1)) + x1))**x1)**x1 + x1)**x1))
<lambdifygenerated-741>:2: RuntimeWarning: overflow encountered in sinh
  return tanh(sqrt(x1*(x1*sinh(tanh(exp(_a4_*(_a2_*x1 + _a7_)/(x1 + e) + x1))**x1)**x1 + x1)**x1))
<lambdifygenerated-741>:2: RuntimeWarning: invalid value encountered in power
  return tanh(sqrt(x1*(x1*sinh(tanh(exp(_a4_*(_a2_*x1 + _a7_)/(x1 + e) + x1))**x1)**x1 + x1)**x1))
<lambdifygenerated-742>:2: RuntimeWarning: overflow encountered in sinh
  return tanh(sqrt(x1*(x1*sinh(tanh(exp(_a4_*(_a2_*x1 + _a7_)/(x1 + e) + x1))**x1)**x1 + x1)**x1))
<lambdifygenerated-742>:2: RuntimeWarning: invalid value encountered in power
  return tanh(sqrt(x1*(x1*sinh(tanh(exp(_a4_*(_a2_*x1 + _a7_)/(x1 + e) + x1))**x1)**x1 + x1)**x1))
<lambdifygenerated-743>:2: RuntimeWarning: overflow encountered in exp
  return tanh(sqrt(x1*(x1*sinh(tanh(exp(_a4_*(_a2_*x1 + _a7_)/(x1 + exp(_a0_/x1)) + x1))**x1)**x1 + x1)**x1))
<lambdifygenerated-743>:2: RuntimeWarning: divide by zero encountered in power
  return tanh(sqrt(x1*(x1*sinh(tanh(exp(_a4_*(_a2_*x1 + _a7_)/(x1 + exp(_a0_/x1)) + x1))**x1)**x1 + x1)**x1))
<lambdifygenerated-743>:2: RuntimeWarning: invalid value encountered in power
  return tanh(sqrt(x1*(x1*sinh(tanh(exp(_a4_*(_a2_*x1 + _a7_)/(x1 + exp(_a0_/x1)) + x1))**x1)**x1 + x1)**x1))
<lambdifygenerated-744>:2: RuntimeWarning: overflow encountered in exp
  return tanh(sqrt(x1*(x1*sinh(tanh(exp(_a4_*(_a2_*x1 + _a7_)/(x1 + exp(_a0_/x1)) + x1))**x1)**x1 + x1)**x1))
<lambdifygenerated-744>:2: RuntimeWarning: divide by zero encountered in power
  return tanh(sqrt(x1*(x1*sinh(tanh(exp(_a4_*(_a2_*x1 + _a7_)/(x1 + exp(_a0_/x1)) + x1))**x1)**x1 + x1)**x1))
<lambdifygenerated-744>:2: RuntimeWarning: invalid value encountered in power
  return tanh(sqrt(x1*(x1*sinh(tanh(exp(_a4_*(_a2_*x1 + _a7_)/(x1 + exp(_a0_/x1)) + x1))**x1)**x1 + x1)**x1))
<lambdifygenerated-745>:2: RuntimeWarning: overflow encountered in sinh
  return tanh(sqrt(x1*(x1*sinh(tanh(exp(_a4_*(_a2_*x1 + _a7_)/(x1 + exp(_a0_/_a5_)) + x1))**x1)**x1 + x1)**x1))
<lambdifygenerated-745>:2: RuntimeWarning: invalid value encountered in power
  return tanh(sqrt(x1*(x1*sinh(tanh(exp(_a4_*(_a2_*x1 + _a7_)/(x1 + exp(_a0_/_a5_)) + x1))**x1)**x1 + x1)**x1))
<lambdifygenerated-746>:2: RuntimeWarning: overflow encountered in sinh
  return tanh(sqrt(x1*(x1*sinh(tanh(exp(_a4_*(_a2_*x1 + _a7_)/(x1 + exp(_a0_/_a5_)) + x1))**x1)**x1 + x1)**x1))
<lambdifygenerated-746>:2: RuntimeWarning: invalid value encountered in power
  return tanh(sqrt(x1*(x1*sinh(tanh(exp(_a4_*(_a2_*x1 + _a7_)/(x1 + exp(_a0_/_a5_)) + x1))**x1)**x1 + x1)**x1))
<lambdifygenerated-747>:2: RuntimeWarning: invalid value encountered in power
  return tanh(sqrt(x1*(x1*sinh(tanh(exp(_a4_*(_a2_*x1 + _a7_)/(x1**x1 + exp(_a0_/_a5_)) + x1))**x1)**x1 + x1)**x1))
<lambdifygenerated-748>:2: RuntimeWarning: invalid value encountered in power
  return tanh(sqrt(x1*(x1*sinh(tanh(exp(_a4_*(_a2_*x1 + _a7_)/(x1**x1 + exp(_a0_/_a5_)) + x1))**x1)**x1 + x1)**x1))
<lambdifygenerated-749>:2: RuntimeWarning: invalid value encountered in power
  return tanh(sqrt(x1*(x1*sinh(tanh(exp(_a4_*(_a2_*x1 + _a7_)/(_a5_**x1 + exp(_a0_/_a5_)) + x1))**x1)**x1 + x1)**x1))
<lambdifygenerated-750>:2: RuntimeWarning: invalid value encountered in power
  return tanh(sqrt(x1*(x1*sinh(tanh(exp(_a4_*(_a2_*x1 + _a7_)/(_a5_**x1 + exp(_a0_/_a5_)) + x1))**x1)**x1 + x1)**x1))
<lambdifygenerated-751>:2: RuntimeWarning: invalid value encountered in power
  return tanh(sqrt(x1*(x1*sinh(tanh(exp(_a4_*(_a2_*x1 + _a7_)/(_a5_**x1 + exp(_a0_/_a5_)) + x1))**x1)**x1 + x1)**x1))
<lambdifygenerated-752>:2: RuntimeWarning: invalid value encountered in power
  return tanh(sqrt(x1*(x1*sinh(tanh(exp(_a4_*(_a2_*x1 + _a7_)/(_a5_**x1 + exp(_a0_/_a5_)) + x1))**x1)**x1 + x1)**x1))
<lambdifygenerated-753>:2: RuntimeWarning: invalid value encountered in power
  return tanh(sqrt(x1*(x1*sinh(tanh(exp(_a4_*(_a2_*x1 + _a7_)/(_a5_**x1 + exp(_a0_/_a5_)) + cos(x1)))**x1)**x1 + x1)**x1))
<lambdifygenerated-754>:2: RuntimeWarning: invalid value encountered in power
  return tanh(sqrt(x1*(x1*sinh(tanh(exp(_a4_*(_a2_*x1 + _a7_)/(_a5_**x1 + exp(_a0_/_a5_)) + cos(x1)))**x1)**x1 + x1)**x1))
<lambdifygenerated-755>:2: RuntimeWarning: invalid value encountered in power
  return tanh(sqrt(x1*(x1*sinh(tanh(exp(_a4_*(_a2_*x1 + _a7_)/(_a5_**x1 + exp(_a0_/_a5_)) + cos(_a3_)))**x1)**x1 + x1)**x1))
<lambdifygenerated-756>:2: RuntimeWarning: invalid value encountered in power
  return tanh(sqrt(x1*(x1*sinh(tanh(exp(_a4_*(_a2_*x1 + _a7_)/(_a5_**x1 + exp(_a0_/_a5_)) + cos(_a3_)))**x1)**x1 + x1)**x1))
<lambdifygenerated-757>:2: RuntimeWarning: invalid value encountered in power
  return tanh(sqrt(x1*(x1*sinh(tanh(exp(_a4_*(_a2_*x1 + _a7_)/(_a5_**x1 + exp(_a0_/_a5_)) + cos(_a3_))))**x1 + x1)**x1))
<lambdifygenerated-758>:2: RuntimeWarning: invalid value encountered in power
  return tanh(sqrt(x1*(x1*sinh(tanh(exp(_a4_*(_a2_*x1 + _a7_)/(_a5_**x1 + exp(_a0_/_a5_)) + cos(_a3_))))**x1 + x1)**x1))
<lambdifygenerated-759>:2: RuntimeWarning: overflow encountered in power
  return tanh(sqrt(x1*(x1*sinh(tanh(exp(_a4_*(_a2_*x1 + _a7_)/(_a5_**x1 + exp(_a0_/_a5_)) + cos(_a3_)))**(_a1_/x1))**x1 + x1)**x1))
<lambdifygenerated-759>:2: RuntimeWarning: overflow encountered in sinh
  return tanh(sqrt(x1*(x1*sinh(tanh(exp(_a4_*(_a2_*x1 + _a7_)/(_a5_**x1 + exp(_a0_/_a5_)) + cos(_a3_)))**(_a1_/x1))**x1 + x1)**x1))
<lambdifygenerated-759>:2: RuntimeWarning: invalid value encountered in power
  return tanh(sqrt(x1*(x1*sinh(tanh(exp(_a4_*(_a2_*x1 + _a7_)/(_a5_**x1 + exp(_a0_/_a5_)) + cos(_a3_)))**(_a1_/x1))**x1 + x1)**x1))
<lambdifygenerated-760>:2: RuntimeWarning: overflow encountered in power
  return tanh(sqrt(x1*(x1*sinh(tanh(exp(_a4_*(_a2_*x1 + _a7_)/(_a5_**x1 + exp(_a0_/_a5_)) + cos(_a3_)))**(_a1_/x1))**x1 + x1)**x1))
<lambdifygenerated-760>:2: RuntimeWarning: overflow encountered in sinh
  return tanh(sqrt(x1*(x1*sinh(tanh(exp(_a4_*(_a2_*x1 + _a7_)/(_a5_**x1 + exp(_a0_/_a5_)) + cos(_a3_)))**(_a1_/x1))**x1 + x1)**x1))
<lambdifygenerated-760>:2: RuntimeWarning: invalid value encountered in power
  return tanh(sqrt(x1*(x1*sinh(tanh(exp(_a4_*(_a2_*x1 + _a7_)/(_a5_**x1 + exp(_a0_/_a5_)) + cos(_a3_)))**(_a1_/x1))**x1 + x1)**x1))
<lambdifygenerated-761>:2: RuntimeWarning: invalid value encountered in power
  return tanh(sqrt(x1*(x1*sinh(tanh(exp(_a4_*(_a2_*x1 + _a7_)/(_a5_**x1 + exp(_a0_/_a5_)) + cos(_a3_)))**(_a1_/_a6_))**x1 + x1)**x1))
<lambdifygenerated-762>:2: RuntimeWarning: invalid value encountered in power
  return tanh(sqrt(x1*(x1*sinh(tanh(exp(_a4_*(_a2_*x1 + _a7_)/(_a5_**x1 + exp(_a0_/_a5_)) + cos(_a3_)))**(_a1_/_a6_))**x1 + x1)**x1))
<lambdifygenerated-763>:2: RuntimeWarning: invalid value encountered in power
  return tanh(sqrt(x1*(x1*sinh(tanh(exp(_a4_*(_a2_*x1 + _a7_)/(_a5_**x1 + exp(_a0_/_a5_)) + cos(_a3_)))**(_a1_/_a6_))**_a5_ + x1)**x1))
<lambdifygenerated-764>:2: RuntimeWarning: invalid value encountered in power
  return tanh(sqrt(x1*(x1*sinh(tanh(exp(_a4_*(_a2_*x1 + _a7_)/(_a5_**x1 + exp(_a0_/_a5_)) + cos(_a3_)))**(_a1_/_a6_))**_a5_ + x1)**x1))
<lambdifygenerated-765>:2: RuntimeWarning: invalid value encountered in power
  return tanh(sqrt(x1*(x1**2*sinh(tanh(exp(_a4_*(_a2_*x1 + _a7_)/(_a5_**x1 + exp(_a0_/_a5_)) + cos(_a3_)))**(_a1_/_a6_))**_a5_ + x1)**x1))
<lambdifygenerated-765>:2: RuntimeWarning: invalid value encountered in sqrt
  return tanh(sqrt(x1*(x1**2*sinh(tanh(exp(_a4_*(_a2_*x1 + _a7_)/(_a5_**x1 + exp(_a0_/_a5_)) + cos(_a3_)))**(_a1_/_a6_))**_a5_ + x1)**x1))
<lambdifygenerated-766>:2: RuntimeWarning: invalid value encountered in power
  return tanh(sqrt(x1*(x1**2*sinh(tanh(exp(_a4_*(_a2_*x1 + _a7_)/(_a5_**x1 + exp(_a0_/_a5_)) + cos(_a3_)))**(_a1_/_a6_))**_a5_ + x1)**x1))
<lambdifygenerated-766>:2: RuntimeWarning: invalid value encountered in sqrt
  return tanh(sqrt(x1*(x1**2*sinh(tanh(exp(_a4_*(_a2_*x1 + _a7_)/(_a5_**x1 + exp(_a0_/_a5_)) + cos(_a3_)))**(_a1_/_a6_))**_a5_ + x1)**x1))
<lambdifygenerated-767>:2: RuntimeWarning: invalid value encountered in power
  return tanh(sqrt(x1*(x1**3*sinh(tanh(exp(_a4_*(_a2_*x1 + _a7_)/(_a5_**x1 + exp(_a0_/_a5_)) + cos(_a3_)))**(_a1_/_a6_))**_a5_ + x1)**x1))
<lambdifygenerated-768>:2: RuntimeWarning: invalid value encountered in power
  return tanh(sqrt(x1*(x1**3*sinh(tanh(exp(_a4_*(_a2_*x1 + _a7_)/(_a5_**x1 + exp(_a0_/_a5_)) + cos(_a3_)))**(_a1_/_a6_))**_a5_ + x1)**x1))
<lambdifygenerated-769>:2: RuntimeWarning: invalid value encountered in power
  return tanh(sqrt(x1*(_a6_*x1**2*sinh(tanh(exp(_a4_*(_a2_*x1 + _a7_)/(_a5_**x1 + exp(_a0_/_a5_)) + cos(_a3_)))**(_a1_/_a6_))**_a5_ + x1)**x1))
<lambdifygenerated-769>:2: RuntimeWarning: invalid value encountered in sqrt
  return tanh(sqrt(x1*(_a6_*x1**2*sinh(tanh(exp(_a4_*(_a2_*x1 + _a7_)/(_a5_**x1 + exp(_a0_/_a5_)) + cos(_a3_)))**(_a1_/_a6_))**_a5_ + x1)**x1))
<lambdifygenerated-770>:2: RuntimeWarning: invalid value encountered in power
  return tanh(sqrt(x1*(_a6_*x1**2*sinh(tanh(exp(_a4_*(_a2_*x1 + _a7_)/(_a5_**x1 + exp(_a0_/_a5_)) + cos(_a3_)))**(_a1_/_a6_))**_a5_ + x1)**x1))
<lambdifygenerated-770>:2: RuntimeWarning: invalid value encountered in sqrt
  return tanh(sqrt(x1*(_a6_*x1**2*sinh(tanh(exp(_a4_*(_a2_*x1 + _a7_)/(_a5_**x1 + exp(_a0_/_a5_)) + cos(_a3_)))**(_a1_/_a6_))**_a5_ + x1)**x1))
<lambdifygenerated-771>:2: RuntimeWarning: invalid value encountered in power
  return tanh(sqrt(x1*(_a6_*x1**3*sinh(tanh(exp(_a4_*(_a2_*x1 + _a7_)/(_a5_**x1 + exp(_a0_/_a5_)) + cos(_a3_)))**(_a1_/_a6_))**_a5_ + x1)**x1))
<lambdifygenerated-772>:2: RuntimeWarning: invalid value encountered in power
  return tanh(sqrt(x1*(_a6_*x1**3*sinh(tanh(exp(_a4_*(_a2_*x1 + _a7_)/(_a5_**x1 + exp(_a0_/_a5_)) + cos(_a3_)))**(_a1_/_a6_))**_a5_ + x1)**x1))
<lambdifygenerated-773>:2: RuntimeWarning: invalid value encountered in power
  return tanh(sqrt(x1*(_a5_*_a6_*x1**2*sinh(tanh(exp(_a4_*(_a2_*x1 + _a7_)/(_a5_**x1 + exp(_a0_/_a5_)) + cos(_a3_)))**(_a1_/_a6_))**_a5_ + x1)**x1))
<lambdifygenerated-773>:2: RuntimeWarning: invalid value encountered in sqrt
  return tanh(sqrt(x1*(_a5_*_a6_*x1**2*sinh(tanh(exp(_a4_*(_a2_*x1 + _a7_)/(_a5_**x1 + exp(_a0_/_a5_)) + cos(_a3_)))**(_a1_/_a6_))**_a5_ + x1)**x1))
<lambdifygenerated-774>:2: RuntimeWarning: invalid value encountered in power
  return tanh(sqrt(x1*(_a5_*_a6_*x1**2*sinh(tanh(exp(_a4_*(_a2_*x1 + _a7_)/(_a5_**x1 + exp(_a0_/_a5_)) + cos(_a3_)))**(_a1_/_a6_))**_a5_ + x1)**x1))
<lambdifygenerated-774>:2: RuntimeWarning: invalid value encountered in sqrt
  return tanh(sqrt(x1*(_a5_*_a6_*x1**2*sinh(tanh(exp(_a4_*(_a2_*x1 + _a7_)/(_a5_**x1 + exp(_a0_/_a5_)) + cos(_a3_)))**(_a1_/_a6_))**_a5_ + x1)**x1))
<lambdifygenerated-775>:2: RuntimeWarning: invalid value encountered in power
  return tanh(sqrt(x1*(_a5_*_a6_*_a7_*x1*sinh(tanh(exp(_a4_*(_a2_*x1 + _a7_)/(_a5_**x1 + exp(_a0_/_a5_)) + cos(_a3_)))**(_a1_/_a6_))**_a5_ + x1)**x1))
<lambdifygenerated-776>:2: RuntimeWarning: invalid value encountered in power

interpolation

<lambdifygenerated-793>:2: RuntimeWarning: overflow encountered in sinh
  return tanh(sqrt(_a4_*(_a3_*_a5_*_a6_*_a7_*sinh(tanh(exp(_a4_*(_a2_*x1 + _a7_)/(_a5_**x1 + exp(_a0_/_a5_)) + cos(_a3_)))**(_a1_/_a6_))**_a5_ + (_a0_ + abs(x1))/_a3_)**_a7_))
<lambdifygenerated-793>:2: RuntimeWarning: overflow encountered in exp
  return tanh(sqrt(_a4_*(_a3_*_a5_*_a6_*_a7_*sinh(tanh(exp(_a4_*(_a2_*x1 + _a7_)/(_a5_**x1 + exp(_a0_/_a5_)) + cos(_a3_)))**(_a1_/_a6_))**_a5_ + (_a0_ + abs(x1))/_a3_)**_a7_))
<lambdifygenerated-794>:2: RuntimeWarning: overflow encountered in exp
  return tanh(sqrt(_a4_*(_a3_*_a5_*_a6_*_a7_*sinh(tanh(exp(_a4_*(_a2_*x1 + _a7_)/(_a5_**x1 + exp(_a0_/_a5_)) + cos(_a3_)))**(_a1_/_a6_))**_a5_ + (_a0_ + abs(x1))/_a3_)**_a7_))
<lambdifygenerated-795>:2: RuntimeWarning: overflow encountered in exp
  return tanh(sqrt(_a4_*(_a3_*_a5_*_a6_*_a7_*sinh(tanh(exp(_a4_*(_a2_*x1 + _a7_)/(_a5_**x1 + exp(_a0_/_a5_)) + cos(_a3_)))**(_a1_/_a6_))**_a5_ + (_a0_ + abs(x1))/_a3_)**_a7_))
<lambdifygenerated-796>:2: RuntimeWarning: overflow encountered in exp
  return tanh(sqrt(_a4_*(_a3_*_a5_*_a6_*_a7_*sinh(tanh(exp(_a4_*(_a2_*x1 + _a7_)/(_a5_**x1 + exp(_a0_/_a5_)) + cos(_a3_)))**(_a1_/_a6_))**_a5_ + (_a0_ + abs(x1))/_a3_)**_a7_))
<lambdifygenerated-797>:2: RuntimeWarning: overflow encountered in exp
  return tanh(sqrt(_a4_*(_a3_*_a5_*_a6_*_a7_*sinh(tanh(exp(_a4_*(_a2_*x1 + _a7_)/(_a5_**x1 + exp(_a0_/_a5_)) + cos(_a3_)))**(_a1_/_a6_))**_a5_ + (_a0_ + abs(x1))/_a3_)**_a7_))
<lambdifygenerated-797>:2: RuntimeWarning: invalid value encountered in power
  return tanh(sqrt(_a4_*(_a3_*_a5_*_a6_*_a7_*sinh(tanh(exp(_a4_*(_a2_*x1 + _a7_)/(_a5_**x1 + exp(_a0_/_a5_)) + cos(_a3_)))**(_a1_/_a6_))**_a5_ + (_a0_ + abs(x1))/_a3_)**_a7_))
<lambdifygenerated-798>:2: RuntimeWarning: overflow encountered in exp
  return tanh(sqrt(_a4_*(_a3_*_a5_*_a6_*_a7_*sinh(tanh(exp(_a4_*(_a2_*x1 + _a7_)/(_a5_**x1 + exp(_a0_/_a5_)) + cos(_a3_)))**(_a1_/_a6_))**_a5_ + (_a0_ + abs(x1))/_a3_)**_a7_))

         x1         y  rep    ymodel      ybms
3745  0.997  0.100918  7.0  0.100488  0.100398
3746  0.998  0.100912  7.0  0.100475  0.100386
3747  0.998  0.100906  7.0  0.100463  0.100373
3748  0.999  0.100901  7.0  0.100450  0.100361

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.100890  7.0  0.100424  0.100336
3751  1.002  0.100885  7.0  0.100412  0.100324
3752  1.002  0.100880  7.0  0.100399  0.100311
3753  1.003  0.100874  7.0  0.100386  0.100299

3750

<lambdifygenerated-807>:2: RuntimeWarning: invalid value encountered in power
  return sin(x1 + x1**x1)
<lambdifygenerated-808>:2: RuntimeWarning: invalid value encountered in power
  return sin(x1 + x1**x1)
<lambdifygenerated-813>:2: RuntimeWarning: invalid value encountered in power
  return sin(x1 + (x1*tanh(x1**2))**x1)
<lambdifygenerated-814>:2: RuntimeWarning: invalid value encountered in power
  return sin(x1 + (x1*tanh(x1**2))**x1)
<lambdifygenerated-815>:2: RuntimeWarning: invalid value encountered in power
  return sin(x1 + (x1*tanh(2*x1**2))**x1)
<lambdifygenerated-816>:2: RuntimeWarning: invalid value encountered in power
  return sin(x1 + (x1*tanh(2*x1**2))**x1)
<lambdifygenerated-817>:2: RuntimeWarning: invalid value encountered in power
  return sin(x1 + (x1*tanh(3*x1**2))**x1)
<lambdifygenerated-818>:2: RuntimeWarning: invalid value encountered in power
  return sin(x1 + (x1*tanh(3*x1**2))**x1)
<lambdifygenerated-819>:2: RuntimeWarning: invalid value encountered in power
  return sin(x1 + (x1*tanh(x1*(2*x1 + x1**x1)))**x1)
<lambdifygenerated-820>:2: RuntimeWarning: invalid value encountered in power
  return sin(x1 + (x1*tanh(x1*(2*x1 + x1**x1)))**x1)
<lambdifygenerated-821>:2: RuntimeWarning: invalid value encountered in power
  return sin(x1 + (x1*tanh(x1*(2*x1 + (2*x1)**x1)))**x1)
<lambdifygenerated-822>:2: RuntimeWarning: invalid value encountered in power
  return sin(x1 + (x1*tanh(x1*(2*x1 + (2*x1)**x1)))**x1)
<lambdifygenerated-823>:2: RuntimeWarning: invalid value encountered in power
  return sin(x1 + (x1*tanh(x1*(2*x1 + (x1 + 1)**x1)))**x1)
<lambdifygenerated-824>:2: RuntimeWarning: invalid value encountered in power
  return sin(x1 + (x1*tanh(x1*(2*x1 + (x1 + 1)**x1)))**x1)
<lambdifygenerated-825>:2: RuntimeWarning: invalid value encountered in power
  return sin(x1 + (x1*tanh(x1*(2*x1 + (x1 + 2)**x1)))**x1)
<lambdifygenerated-826>:2: RuntimeWarning: invalid value encountered in power
  return sin(x1 + (x1*tanh(x1*(2*x1 + (x1 + 2)**x1)))**x1)
<lambdifygenerated-827>:2: RuntimeWarning: invalid value encountered in power
  return sin(x1 + (x1*tanh(x1*(2*x1 + (x1 + (x1**2 + x1)/x1)**x1)))**x1)
<lambdifygenerated-828>:2: RuntimeWarning: invalid value encountered in power
  return sin(x1 + (x1*tanh(x1*(2*x1 + (x1 + (x1**2 + x1)/x1)**x1)))**x1)
<lambdifygenerated-829>:2: RuntimeWarning: invalid value encountered in power
  return sin(x1 + (x1*tanh(x1*(2*x1 + (x1 + (x1*tanh(x1) + x1)/x1)**x1)))**x1)
<lambdifygenerated-830>:2: RuntimeWarning: invalid value encountered in power
  return sin(x1 + (x1*tanh(x1*(2*x1 + (x1 + (x1*tanh(x1) + x1)/x1)**x1)))**x1)
<lambdifygenerated-831>:2: RuntimeWarning: invalid value encountered in power
  return sin(x1 + (x1*tanh(x1*(2*x1 + (x1 + (x1*tanh(x1**2) + x1)/x1)**x1)))**x1)
<lambdifygenerated-832>:2: RuntimeWarning: invalid value encountered in power
  return sin(x1 + (x1*tanh(x1*(2*x1 + (x1 + (x1*tanh(x1**2) + x1)/x1)**x1)))**x1)
<lambdifygenerated-833>:2: RuntimeWarning: invalid value encountered in power
  return sin(x1 + (x1*tanh(x1*(2*x1 + (x1 + (x1*tanh(2*x1**2) + x1)/x1)**x1)))**x1)
<lambdifygenerated-834>:2: RuntimeWarning: invalid value encountered in power
  return sin(x1 + (x1*tanh(x1*(2*x1 + (x1 + (x1*tanh(2*x1**2) + x1)/x1)**x1)))**x1)
<lambdifygenerated-835>:2: RuntimeWarning: divide by zero encountered in power
  return sin(x1 + (x1*tanh(x1*(2*x1 + (x1 + (x1*tanh(x1*(_a4_ + x1)) + x1)/x1)**x1)))**x1)
<lambdifygenerated-835>:2: RuntimeWarning: invalid value encountered in power
  return sin(x1 + (x1*tanh(x1*(2*x1 + (x1 + (x1*tanh(x1*(_a4_ + x1)) + x1)/x1)**x1)))**x1)
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-836>:2: RuntimeWarning: divide by zero encountered in power
  return sin(x1 + (x1*tanh(x1*(2*x1 + (x1 + (x1*tanh(x1*(_a4_ + x1)) + x1)/x1)**x1)))**x1)
<lambdifygenerated-836>:2: RuntimeWarning: invalid value encountered in power
  return sin(x1 + (x1*tanh(x1*(2*x1 + (x1 + (x1*tanh(x1*(_a4_ + x1)) + x1)/x1)**x1)))**x1)
<lambdifygenerated-837>:2: RuntimeWarning: divide by zero encountered in power
  return sin(x1 + (x1*tanh(x1*(2*x1 + (x1 + (x1*tanh(x1*(_a4_ + x1)) + x1)/x1)**x1)))**x1)
<lambdifygenerated-837>:2: RuntimeWarning: invalid value encountered in power
  return sin(x1 + (x1*tanh(x1*(2*x1 + (x1 + (x1*tanh(x1*(_a4_ + x1)) + x1)/x1)**x1)))**x1)
<lambdifygenerated-838>:2: RuntimeWarning: divide by zero encountered in power
  return sin(x1 + (x1*tanh(x1*(2*x1 + (x1 + (x1*tanh(x1*(_a4_ + x1)) + x1)/x1)**x1)))**x1)
<lambdifygenerated-838>:2: RuntimeWarning: invalid value encountered in power
  return sin(x1 + (x1*tanh(x1*(2*x1 + (x1 + (x1*tanh(x1*(_a4_ + x1)) + x1)/x1)**x1)))**x1)
<lambdifygenerated-839>:2: RuntimeWarning: invalid value encountered in power
  return sin(x1 + (x1*tanh(x1*(2*x1 + (x1 + (x1*tanh(_a3_*(_a4_ + x1)) + x1)/x1)**x1)))**x1)
<lambdifygenerated-840>:2: RuntimeWarning: invalid value encountered in power
  return sin(x1 + (x1*tanh(x1*(2*x1 + (x1 + (x1*tanh(_a3_*(_a4_ + x1)) + x1)/x1)**x1)))**x1)
<lambdifygenerated-841>:2: RuntimeWarning: divide by zero encountered in power
  return sin(x1 + (x1*tanh(x1*(2*x1 + (x1 + (x1**2*tanh(_a3_*(_a4_ + x1)) + x1)/x1)**x1)))**x1)
<lambdifygenerated-841>:2: RuntimeWarning: invalid value encountered in power
  return sin(x1 + (x1*tanh(x1*(2*x1 + (x1 + (x1**2*tanh(_a3_*(_a4_ + x1)) + x1)/x1)**x1)))**x1)
<lambdifygenerated-842>:2: RuntimeWarning: divide by zero encountered in power
  return sin(x1 + (x1*tanh(x1*(2*x1 + (x1 + (x1**2*tanh(_a3_*(_a4_ + x1)) + x1)/x1)**x1)))**x1)
<lambdifygenerated-842>:2: RuntimeWarning: invalid value encountered in power
  return sin(x1 + (x1*tanh(x1*(2*x1 + (x1 + (x1**2*tanh(_a3_*(_a4_ + x1)) + x1)/x1)**x1)))**x1)
<lambdifygenerated-843>:2: RuntimeWarning: invalid value encountered in power
  return sin(x1 + (x1*tanh(x1*(2*x1 + (x1 + (x1*tanh(_a3_*(_a4_ + x1)) + x1)/x1)**x1)))**x1)
<lambdifygenerated-844>:2: RuntimeWarning: invalid value encountered in power
  return sin(x1 + (x1*tanh(x1*(2*x1 + (x1 + (x1*tanh(_a3_*(_a4_ + x1)) + x1)/x1)**x1)))**x1)
<lambdifygenerated-845>:2: RuntimeWarning: invalid value encountered in power
  return sin(x1 + (x1*tanh(x1*(2*x1 + (x1 + (2*x1*tanh(_a3_*(_a4_ + x1)) + x1)/x1)**x1)))**x1)
<lambdifygenerated-846>:2: RuntimeWarning: invalid value encountered in power
  return sin(x1 + (x1*tanh(x1*(2*x1 + (x1 + (2*x1*tanh(_a3_*(_a4_ + x1)) + x1)/x1)**x1)))**x1)
<lambdifygenerated-847>:2: RuntimeWarning: invalid value encountered in power
  return sin(x1 + (x1*tanh(x1*(2*x1 + (x1 + (2*x1*tanh(_a3_*(_a4_ + x1)) + x1)/x1)**x1)))**x1)
<lambdifygenerated-848>:2: RuntimeWarning: invalid value encountered in power
  return sin(x1 + (x1*tanh(x1*(2*x1 + (x1 + (2*x1*tanh(_a3_*(_a4_ + x1)) + x1)/x1)**x1)))**x1)
<lambdifygenerated-849>:2: RuntimeWarning: invalid value encountered in power
  return sin(x1 + (x1*tanh(x1*(2*x1 + (x1 + (3*x1*tanh(_a3_*(_a4_ + x1)) + x1)/x1)**x1)))**x1)
<lambdifygenerated-850>:2: RuntimeWarning: invalid value encountered in power
  return sin(x1 + (x1*tanh(x1*(2*x1 + (x1 + (3*x1*tanh(_a3_*(_a4_ + x1)) + x1)/x1)**x1)))**x1)
<lambdifygenerated-851>:2: RuntimeWarning: invalid value encountered in power
  return sin(x1 + (x1*tanh(x1*(2*x1 + (x1 + (3*x1*tanh(_a3_*(_a4_ + x1)) + x1)/x1)**x1)))**x1)
<lambdifygenerated-852>:2: RuntimeWarning: invalid value encountered in power
  return sin(x1 + (x1*tanh(x1*(2*x1 + (x1 + (3*x1*tanh(_a3_*(_a4_ + x1)) + x1)/x1)**x1)))**x1)
<lambdifygenerated-853>:2: RuntimeWarning: invalid value encountered in power
  return sin(x1 + (x1*tanh(x1*(2*x1 + (x1 + (x1 + (_a0_ + 2*x1)*tanh(_a3_*(_a4_ + x1)))/x1)**x1)))**x1)
<lambdifygenerated-854>:2: RuntimeWarning: invalid value encountered in power
  return sin(x1 + (x1*tanh(x1*(2*x1 + (x1 + (x1 + (_a0_ + 2*x1)*tanh(_a3_*(_a4_ + x1)))/x1)**x1)))**x1)
<lambdifygenerated-855>:2: RuntimeWarning: divide by zero encountered in power
  return sin(x1 + (x1*tanh(x1*(2*x1 + (x1 + (x1 + (_a0_ + 2*x1)*tanh(_a3_*(_a4_ + x1))/x1)/x1)**x1)))**x1)
<lambdifygenerated-855>:2: RuntimeWarning: invalid value encountered in power
  return sin(x1 + (x1*tanh(x1*(2*x1 + (x1 + (x1 + (_a0_ + 2*x1)*tanh(_a3_*(_a4_ + x1))/x1)/x1)**x1)))**x1)
<lambdifygenerated-856>:2: RuntimeWarning: divide by zero encountered in power
  return sin(x1 + (x1*tanh(x1*(2*x1 + (x1 + (x1 + (_a0_ + 2*x1)*tanh(_a3_*(_a4_ + x1))/x1)/x1)**x1)))**x1)
<lambdifygenerated-856>:2: RuntimeWarning: invalid value encountered in power
  return sin(x1 + (x1*tanh(x1*(2*x1 + (x1 + (x1 + (_a0_ + 2*x1)*tanh(_a3_*(_a4_ + x1))/x1)/x1)**x1)))**x1)
<lambdifygenerated-857>:2: RuntimeWarning: divide by zero encountered in power
  return sin(x1 + (x1*tanh(x1*(2*x1 + (x1 + (x1 + x1*(_a0_ + 2*x1)*tanh(_a3_*(_a4_ + x1))/_a1_**2)/x1)**x1)))**x1)
<lambdifygenerated-857>:2: RuntimeWarning: invalid value encountered in power
  return sin(x1 + (x1*tanh(x1*(2*x1 + (x1 + (x1 + x1*(_a0_ + 2*x1)*tanh(_a3_*(_a4_ + x1))/_a1_**2)/x1)**x1)))**x1)
<lambdifygenerated-858>:2: RuntimeWarning: divide by zero encountered in power
  return sin(x1 + (x1*tanh(x1*(2*x1 + (x1 + (x1 + x1*(_a0_ + 2*x1)*tanh(_a3_*(_a4_ + x1))/_a1_**2)/x1)**x1)))**x1)
<lambdifygenerated-858>:2: RuntimeWarning: invalid value encountered in power
  return sin(x1 + (x1*tanh(x1*(2*x1 + (x1 + (x1 + x1*(_a0_ + 2*x1)*tanh(_a3_*(_a4_ + x1))/_a1_**2)/x1)**x1)))**x1)
<lambdifygenerated-859>:2: RuntimeWarning: divide by zero encountered in power
  return sin(x1 + (x1*tanh(x1*(2*x1 + (x1 + (x1 + x1**3*(_a0_ + 2*x1)*tanh(_a3_*(_a4_ + x1))/_a1_**2)/x1)**x1)))**x1)
<lambdifygenerated-859>:2: RuntimeWarning: invalid value encountered in power
  return sin(x1 + (x1*tanh(x1*(2*x1 + (x1 + (x1 + x1**3*(_a0_ + 2*x1)*tanh(_a3_*(_a4_ + x1))/_a1_**2)/x1)**x1)))**x1)
<lambdifygenerated-860>:2: RuntimeWarning: divide by zero encountered in power
  return sin(x1 + (x1*tanh(x1*(2*x1 + (x1 + (x1 + x1**3*(_a0_ + 2*x1)*tanh(_a3_*(_a4_ + x1))/_a1_**2)/x1)**x1)))**x1)
<lambdifygenerated-860>:2: RuntimeWarning: invalid value encountered in power
  return sin(x1 + (x1*tanh(x1*(2*x1 + (x1 + (x1 + x1**3*(_a0_ + 2*x1)*tanh(_a3_*(_a4_ + x1))/_a1_**2)/x1)**x1)))**x1)
<lambdifygenerated-861>:2: RuntimeWarning: invalid value encountered in power
  return sin(x1 + (x1*tanh(x1*(2*x1 + (x1 + (x1 + _a3_**3*(_a0_ + 2*x1)*tanh(_a3_*(_a4_ + x1))/_a1_**2)/x1)**x1)))**x1)
<lambdifygenerated-862>:2: RuntimeWarning: invalid value encountered in power
  return sin(x1 + (x1*tanh(x1*(2*x1 + (x1 + (x1 + _a3_**3*(_a0_ + 2*x1)*tanh(_a3_*(_a4_ + x1))/_a1_**2)/x1)**x1)))**x1)
<lambdifygenerated-863>:2: RuntimeWarning: invalid value encountered in power
  return sin(x1 + (x1*tanh(x1*(2*x1 + (x1 + (_a5_ + _a3_**3*(_a0_ + 2*x1)*tanh(_a3_*(_a4_ + x1))/_a1_**2)/x1)**x1)))**x1)
<lambdifygenerated-864>:2: RuntimeWarning: invalid value encountered in power
  return sin(x1 + (x1*tanh(x1*(2*x1 + (x1 + (_a5_ + _a3_**3*(_a0_ + 2*x1)*tanh(_a3_*(_a4_ + x1))/_a1_**2)/x1)**x1)))**x1)
<lambdifygenerated-865>:2: RuntimeWarning: divide by zero encountered in power
  return sin(x1 + (x1*tanh(x1*(2*x1 + (x1 + (_a5_ + _a3_**3*(_a0_ + 2*x1)*tanh(_a3_*(_a4_ + x1))/_a1_**2)/_a6_)**x1)))**x1)
<lambdifygenerated-865>:2: RuntimeWarning: invalid value encountered in power
  return sin(x1 + (x1*tanh(x1*(2*x1 + (x1 + (_a5_ + _a3_**3*(_a0_ + 2*x1)*tanh(_a3_*(_a4_ + x1))/_a1_**2)/_a6_)**x1)))**x1)
<lambdifygenerated-866>:2: RuntimeWarning: divide by zero encountered in power
  return sin(x1 + (x1*tanh(x1*(2*x1 + (x1 + (_a5_ + _a3_**3*(_a0_ + 2*x1)*tanh(_a3_*(_a4_ + x1))/_a1_**2)/_a6_)**x1)))**x1)
<lambdifygenerated-866>:2: RuntimeWarning: invalid value encountered in power
  return sin(x1 + (x1*tanh(x1*(2*x1 + (x1 + (_a5_ + _a3_**3*(_a0_ + 2*x1)*tanh(_a3_*(_a4_ + x1))/_a1_**2)/_a6_)**x1)))**x1)
<lambdifygenerated-867>:2: RuntimeWarning: divide by zero encountered in power
  return sin(x1 + (x1*tanh(x1*(2*x1 + (x1 + (_a5_ + _a3_**3*(_a0_ + 2*x1)*tanh(_a3_*(_a4_ + x1))/_a1_**2)/_a6_)**x1)))**x1)
<lambdifygenerated-867>:2: RuntimeWarning: invalid value encountered in power
  return sin(x1 + (x1*tanh(x1*(2*x1 + (x1 + (_a5_ + _a3_**3*(_a0_ + 2*x1)*tanh(_a3_*(_a4_ + x1))/_a1_**2)/_a6_)**x1)))**x1)
<lambdifygenerated-868>:2: RuntimeWarning: divide by zero encountered in power
  return sin(x1 + (x1*tanh(x1*(2*x1 + (x1 + (_a5_ + _a3_**3*(_a0_ + 2*x1)*tanh(_a3_*(_a4_ + x1))/_a1_**2)/_a6_)**x1)))**x1)
<lambdifygenerated-868>:2: RuntimeWarning: invalid value encountered in power
  return sin(x1 + (x1*tanh(x1*(2*x1 + (x1 + (_a5_ + _a3_**3*(_a0_ + 2*x1)*tanh(_a3_*(_a4_ + x1))/_a1_**2)/_a6_)**x1)))**x1)
<lambdifygenerated-869>:2: RuntimeWarning: invalid value encountered in power
  return sin(x1 + (x1*tanh(x1*(2*x1 + (x1 + (_a5_ + _a3_**3*(_a0_ + 2*x1)*tanh(_a3_*(_a4_ + x1))/_a1_**2)/_a6_)**_a6_)))**x1)
<lambdifygenerated-870>:2: RuntimeWarning: invalid value encountered in power
  return sin(x1 + (x1*tanh(x1*(2*x1 + (x1 + (_a5_ + _a3_**3*(_a0_ + 2*x1)*tanh(_a3_*(_a4_ + x1))/_a1_**2)/_a6_)**_a6_)))**x1)
<lambdifygenerated-871>:2: RuntimeWarning: invalid value encountered in power
  return sin(x1 + (x1*tanh(x1*(_a6_ + x1 + (x1 + (_a5_ + _a3_**3*(_a0_ + 2*x1)*tanh(_a3_*(_a4_ + x1))/_a1_**2)/_a6_)**_a6_)))**x1)
<lambdifygenerated-872>:2: RuntimeWarning: invalid value encountered in power
  return sin(x1 + (x1*tanh(x1*(_a6_ + x1 + (x1 + (_a5_ + _a3_**3*(_a0_ + 2*x1)*tanh(_a3_*(_a4_ + x1))/_a1_**2)/_a6_)**_a6_)))**x1)
<lambdifygenerated-873>:2: RuntimeWarning: invalid value encountered in power
  return sin(x1 + (x1*tanh(x1*(_a6_ + (x1 + (_a5_ + _a3_**3*(_a0_ + 2*x1)*tanh(_a3_*(_a4_ + x1))/_a1_**2)/_a6_)**_a6_ + sin(x1))))**x1)
<lambdifygenerated-875>:2: RuntimeWarning: invalid value encountered in power
  return sin(x1 + (x1*tanh(x1*(_a6_ + (x1 + (_a5_ + _a3_**3*(_a0_ + 2*x1)*tanh(_a3_*(_a4_ + x1))/_a1_**2)/_a6_)**_a6_ + sin(_a5_))))**x1)
<lambdifygenerated-877>:2: RuntimeWarning: invalid value encountered in power
  return sin(x1 + (x1*tanh(_a7_*(_a6_ + (x1 + (_a5_ + _a3_**3*(_a0_ + 2*x1)*tanh(_a3_*(_a4_ + x1))/_a1_**2)/_a6_)**_a6_ + sin(_a5_))))**x1)
<lambdifygenerated-878>:2: RuntimeWarning: invalid value encountered in power
  return sin(x1 + (x1*tanh(_a7_*(_a6_ + (x1 + (_a5_ + _a3_**3*(_a0_ + 2*x1)*tanh(_a3_*(_a4_ + x1))/_a1_**2)/_a6_)**_a6_ + sin(_a5_))))**x1)
<lambdifygenerated-879>:2: RuntimeWarning: invalid value encountered in power
  return sin(x1 + (x1**x1*tanh(_a7_*(_a6_ + (x1 + (_a5_ + _a3_**3*(_a0_ + 2*x1)*tanh(_a3_*(_a4_ + x1))/_a1_**2)/_a6_)**_a6_ + sin(_a5_))))**x1)
<lambdifygenerated-880>:2: RuntimeWarning: invalid value encountered in power
  return sin(x1 + (x1**x1*tanh(_a7_*(_a6_ + (x1 + (_a5_ + _a3_**3*(_a0_ + 2*x1)*tanh(_a3_*(_a4_ + x1))/_a1_**2)/_a6_)**_a6_ + sin(_a5_))))**x1)
<lambdifygenerated-881>:2: RuntimeWarning: invalid value encountered in power
  return sin(x1 + (_a5_**x1*tanh(_a7_*(_a6_ + (x1 + (_a5_ + _a3_**3*(_a0_ + 2*x1)*tanh(_a3_*(_a4_ + x1))/_a1_**2)/_a6_)**_a6_ + sin(_a5_))))**x1)
<lambdifygenerated-883>:2: RuntimeWarning: invalid value encountered in power
  return sin(x1 + (_a5_**(2*x1)*tanh(_a7_*(_a6_ + (x1 + (_a5_ + _a3_**3*(_a0_ + 2*x1)*tanh(_a3_*(_a4_ + x1))/_a1_**2)/_a6_)**_a6_ + sin(_a5_))))**x1)
<lambdifygenerated-885>:2: RuntimeWarning: invalid value encountered in power
  return sin(x1 + (_a5_**(x1**2 + x1)*tanh(_a7_*(_a6_ + (x1 + (_a5_ + _a3_**3*(_a0_ + 2*x1)*tanh(_a3_*(_a4_ + x1))/_a1_**2)/_a6_)**_a6_ + sin(_a5_))))**x1)
<lambdifygenerated-887>:2: RuntimeWarning: invalid value encountered in power
  return sin(x1 + (_a5_**(_a1_*x1 + x1)*tanh(_a7_*(_a6_ + (x1 + (_a5_ + _a3_**3*(_a0_ + 2*x1)*tanh(_a3_*(_a4_ + x1))/_a1_**2)/_a6_)**_a6_ + sin(_a5_))))**x1)
<lambdifygenerated-889>:2: RuntimeWarning: invalid value encountered in power
  return sin(x1 + (_a5_**(_a1_*_a4_ + x1)*tanh(_a7_*(_a6_ + (x1 + (_a5_ + _a3_**3*(_a0_ + 2*x1)*tanh(_a3_*(_a4_ + x1))/_a1_**2)/_a6_)**_a6_ + sin(_a5_))))**x1)
<lambdifygenerated-893>:2: RuntimeWarning: invalid value encountered in power
  return sin(x1 + (_a5_**(_a1_*_a4_ + x1)*tanh(_a7_*(_a6_ + (x1 + (_a5_ + _a3_**3*(_a0_ + 2*x1)*tanh(_a3_*(_a4_ + x1))/_a1_**2)/_a6_)**_a6_ + sin(_a5_))))**_a3_)
<lambdifygenerated-895>:2: RuntimeWarning: invalid value encountered in power
  return sin(_a2_ + (_a5_**(_a1_*_a4_ + x1)*tanh(_a7_*(_a6_ + (x1 + (_a5_ + _a3_**3*(_a0_ + 2*x1)*tanh(_a3_*(_a4_ + x1))/_a1_**2)/_a6_)**_a6_ + sin(_a5_))))**_a3_)
<lambdifygenerated-899>:2: RuntimeWarning: invalid value encountered in power
  return sin(_a2_ + (_a5_**(_a1_*_a4_ + x1)*tanh(_a7_*(_a6_ + (x1 + (_a5_ + _a3_**3*(_a0_ + 2*x1)*tanh(_a3_*(_a4_ + x1))/_a1_**2)/_a6_)**_a6_ + sin(_a5_))))**_a3_)

interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.825595  8.0  0.825294  0.825691
3746  0.998  0.825925  8.0  0.825623  0.826023
3747  0.998  0.826254  8.0  0.825951  0.826355
3748  0.999  0.826582  8.0  0.826278  0.826686

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.827238  8.0  0.826932  0.827347
3751  1.002  0.827565  8.0  0.827258  0.827676
3752  1.002  0.827892  8.0  0.827584  0.828005
3753  1.003  0.828218  8.0  0.827909  0.828334

3750

<lambdifygenerated-907>:2: RuntimeWarning: invalid value encountered in power
  return x1*x1**x1
<lambdifygenerated-908>:2: RuntimeWarning: invalid value encountered in power
  return x1*x1**x1
<lambdifygenerated-909>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1**x1)**x1
<lambdifygenerated-910>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1**x1)**x1
<lambdifygenerated-911>:2: RuntimeWarning: invalid value encountered in power
  return x1*((2*x1)**x1)**x1
<lambdifygenerated-912>:2: RuntimeWarning: invalid value encountered in power
  return x1*((2*x1)**x1)**x1
<lambdifygenerated-913>:2: RuntimeWarning: invalid value encountered in power
  return x1*((x1**2 + x1)**x1)**x1
<lambdifygenerated-914>:2: RuntimeWarning: invalid value encountered in power
  return x1*((x1**2 + x1)**x1)**x1
<lambdifygenerated-915>:2: RuntimeWarning: invalid value encountered in power
  return x1*((x1*x1**x1 + x1)**x1)**x1
<lambdifygenerated-916>:2: RuntimeWarning: invalid value encountered in power
  return x1*((x1*x1**x1 + x1)**x1)**x1
<lambdifygenerated-917>:2: RuntimeWarning: invalid value encountered in power
  return x1*((x1*(2*x1)**x1 + x1)**x1)**x1
<lambdifygenerated-918>:2: RuntimeWarning: invalid value encountered in power
  return x1*((x1*(2*x1)**x1 + x1)**x1)**x1
<lambdifygenerated-919>:2: RuntimeWarning: invalid value encountered in power
  return x1*((x1*(3*x1)**x1 + x1)**x1)**x1
<lambdifygenerated-920>:2: RuntimeWarning: invalid value encountered in power
  return x1*((x1*(3*x1)**x1 + x1)**x1)**x1
<lambdifygenerated-921>:2: RuntimeWarning: invalid value encountered in power
  return x1*((x1*(2*x1 + tanh(x1))**x1 + x1)**x1)**x1
<lambdifygenerated-922>:2: RuntimeWarning: invalid value encountered in power
  return x1*((x1*(2*x1 + tanh(x1))**x1 + x1)**x1)**x1
<lambdifygenerated-923>:2: RuntimeWarning: invalid value encountered in power
  return x1*((x1*(2*x1 + tanh(x1**x1))**x1 + x1)**x1)**x1
<lambdifygenerated-924>:2: RuntimeWarning: invalid value encountered in power
  return x1*((x1*(2*x1 + tanh(x1**x1))**x1 + x1)**x1)**x1
<lambdifygenerated-925>:2: RuntimeWarning: invalid value encountered in power
  return x1*((x1*(2*x1 + tanh((x1**2)**x1))**x1 + x1)**x1)**x1
<lambdifygenerated-926>:2: RuntimeWarning: invalid value encountered in power
  return x1*((x1*(2*x1 + tanh((x1**2)**x1))**x1 + x1)**x1)**x1
<lambdifygenerated-927>:2: RuntimeWarning: invalid value encountered in power
  return x1*((x1*(2*x1 + tanh(exp(2*x1)**x1))**x1 + x1)**x1)**x1
<lambdifygenerated-928>:2: RuntimeWarning: invalid value encountered in power
  return x1*((x1*(2*x1 + tanh(exp(2*x1)**x1))**x1 + x1)**x1)**x1
<lambdifygenerated-929>:2: RuntimeWarning: invalid value encountered in power
  return x1*((x1*(2*x1 + tanh(exp(4*x1)**x1))**x1 + x1)**x1)**x1
<lambdifygenerated-930>:2: RuntimeWarning: invalid value encountered in power
  return x1*((x1*(2*x1 + tanh(exp(4*x1)**x1))**x1 + x1)**x1)**x1
<lambdifygenerated-931>:2: RuntimeWarning: invalid value encountered in power
  return x1*((x1*(2*x1 + tanh(exp(2*x1 + 2*cos(x1))**x1))**x1 + x1)**x1)**x1
<lambdifygenerated-932>:2: RuntimeWarning: invalid value encountered in power
  return x1*((x1*(2*x1 + tanh(exp(2*x1 + 2*cos(x1))**x1))**x1 + x1)**x1)**x1
<lambdifygenerated-933>:2: RuntimeWarning: invalid value encountered in power
  return x1*((x1*(2*x1 + tanh(exp(2*x1 + 2*cos(_a6_))**x1))**x1 + x1)**x1)**x1
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-934>:2: RuntimeWarning: invalid value encountered in power
  return x1*((x1*(2*x1 + tanh(exp(2*x1 + 2*cos(_a6_))**x1))**x1 + x1)**x1)**x1
<lambdifygenerated-935>:2: RuntimeWarning: invalid value encountered in power
  return x1*((x1*(2*x1 + tanh(exp(2*x1 + 2*cos(_a6_))**x1))**x1 + x1)**x1)**x1
<lambdifygenerated-936>:2: RuntimeWarning: invalid value encountered in power
  return x1*((x1*(2*x1 + tanh(exp(2*x1 + 2*cos(_a6_))**x1))**x1 + x1)**x1)**x1
<lambdifygenerated-937>:2: RuntimeWarning: invalid value encountered in power
  return x1*((x1*(2*x1 + tanh(exp(2*x1 + 2*cos(_a6_))**_a0_))**x1 + x1)**x1)**x1
<lambdifygenerated-938>:2: RuntimeWarning: invalid value encountered in power
  return x1*((x1*(2*x1 + tanh(exp(2*x1 + 2*cos(_a6_))**_a0_))**x1 + x1)**x1)**x1
<lambdifygenerated-939>:2: RuntimeWarning: invalid value encountered in power
  return x1*((x1*(x1 + tanh(exp(2*x1 + 2*cos(_a6_))**_a0_) + 1)**x1 + x1)**x1)**x1
<lambdifygenerated-940>:2: RuntimeWarning: invalid value encountered in power
  return x1*((x1*(x1 + tanh(exp(2*x1 + 2*cos(_a6_))**_a0_) + 1)**x1 + x1)**x1)**x1
<lambdifygenerated-941>:2: RuntimeWarning: invalid value encountered in power
  return x1*((x1*(x1 + tanh(exp(2*x1 + 2*cos(_a6_))**_a0_) + 1)**x1 + x1)**x1)**x1
<lambdifygenerated-942>:2: RuntimeWarning: invalid value encountered in power
  return x1*((x1*(x1 + tanh(exp(2*x1 + 2*cos(_a6_))**_a0_) + 1)**x1 + x1)**x1)**x1
<lambdifygenerated-943>:2: RuntimeWarning: invalid value encountered in power
  return x1*((x1*(x1 + tanh(exp(2*x1 + 2*cos(_a6_))**_a0_) + 1/2)**x1 + x1)**x1)**x1
<lambdifygenerated-944>:2: RuntimeWarning: invalid value encountered in power
  return x1*((x1*(x1 + tanh(exp(2*x1 + 2*cos(_a6_))**_a0_) + 1/2)**x1 + x1)**x1)**x1
<lambdifygenerated-945>:2: RuntimeWarning: divide by zero encountered in divide
  return x1*((x1*(x1 + x1/(x1 + abs(x1)) + tanh(exp(2*x1 + 2*cos(_a6_))**_a0_))**x1 + x1)**x1)**x1
<lambdifygenerated-945>:2: RuntimeWarning: invalid value encountered in power
  return x1*((x1*(x1 + x1/(x1 + abs(x1)) + tanh(exp(2*x1 + 2*cos(_a6_))**_a0_))**x1 + x1)**x1)**x1
<lambdifygenerated-946>:2: RuntimeWarning: divide by zero encountered in divide
  return x1*((x1*(x1 + x1/(x1 + abs(x1)) + tanh(exp(2*x1 + 2*cos(_a6_))**_a0_))**x1 + x1)**x1)**x1
<lambdifygenerated-946>:2: RuntimeWarning: invalid value encountered in power
  return x1*((x1*(x1 + x1/(x1 + abs(x1)) + tanh(exp(2*x1 + 2*cos(_a6_))**_a0_))**x1 + x1)**x1)**x1
<lambdifygenerated-947>:2: RuntimeWarning: divide by zero encountered in divide
  return x1*((x1*(x1 + x1/(x1 + abs(tanh(x1))) + tanh(exp(2*x1 + 2*cos(_a6_))**_a0_))**x1 + x1)**x1)**x1
<lambdifygenerated-947>:2: RuntimeWarning: invalid value encountered in power
  return x1*((x1*(x1 + x1/(x1 + abs(tanh(x1))) + tanh(exp(2*x1 + 2*cos(_a6_))**_a0_))**x1 + x1)**x1)**x1
<lambdifygenerated-948>:2: RuntimeWarning: divide by zero encountered in divide
  return x1*((x1*(x1 + x1/(x1 + abs(tanh(x1))) + tanh(exp(2*x1 + 2*cos(_a6_))**_a0_))**x1 + x1)**x1)**x1
<lambdifygenerated-948>:2: RuntimeWarning: invalid value encountered in power
  return x1*((x1*(x1 + x1/(x1 + abs(tanh(x1))) + tanh(exp(2*x1 + 2*cos(_a6_))**_a0_))**x1 + x1)**x1)**x1
<lambdifygenerated-949>:2: RuntimeWarning: divide by zero encountered in divide
  return x1*((x1*(x1 + x1/(x1 + abs(tanh(x1))) + tanh(exp(2*x1 + 2*cos(_a6_))**_a0_))**x1 + x1)**x1)**x1
<lambdifygenerated-949>:2: RuntimeWarning: invalid value encountered in power
  return x1*((x1*(x1 + x1/(x1 + abs(tanh(x1))) + tanh(exp(2*x1 + 2*cos(_a6_))**_a0_))**x1 + x1)**x1)**x1
<lambdifygenerated-950>:2: RuntimeWarning: divide by zero encountered in divide
  return x1*((x1*(x1 + x1/(x1 + abs(tanh(x1))) + tanh(exp(2*x1 + 2*cos(_a6_))**_a0_))**x1 + x1)**x1)**x1
<lambdifygenerated-950>:2: RuntimeWarning: invalid value encountered in power
  return x1*((x1*(x1 + x1/(x1 + abs(tanh(x1))) + tanh(exp(2*x1 + 2*cos(_a6_))**_a0_))**x1 + x1)**x1)**x1
<lambdifygenerated-951>:2: RuntimeWarning: invalid value encountered in power
  return x1*((x1*(x1 + x1/(abs(tanh(x1)) + 1) + tanh(exp(2*x1 + 2*cos(_a6_))**_a0_))**x1 + x1)**x1)**x1
<lambdifygenerated-952>:2: RuntimeWarning: invalid value encountered in power
  return x1*((x1*(x1 + x1/(abs(tanh(x1)) + 1) + tanh(exp(2*x1 + 2*cos(_a6_))**_a0_))**x1 + x1)**x1)**x1
<lambdifygenerated-953>:2: RuntimeWarning: invalid value encountered in power
  return x1*((x1*(x1 + x1/(_a2_/x1 + abs(tanh(x1))) + tanh(exp(2*x1 + 2*cos(_a6_))**_a0_))**x1 + x1)**x1)**x1
<lambdifygenerated-954>:2: RuntimeWarning: invalid value encountered in power
  return x1*((x1*(x1 + x1/(_a2_/x1 + abs(tanh(x1))) + tanh(exp(2*x1 + 2*cos(_a6_))**_a0_))**x1 + x1)**x1)**x1
<lambdifygenerated-955>:2: RuntimeWarning: invalid value encountered in power
  return x1*((x1*(x1 + x1/((1/2)*_a2_/x1 + abs(tanh(x1))) + tanh(exp(2*x1 + 2*cos(_a6_))**_a0_))**x1 + x1)**x1)**x1
<lambdifygenerated-956>:2: RuntimeWarning: invalid value encountered in power
  return x1*((x1*(x1 + x1/((1/2)*_a2_/x1 + abs(tanh(x1))) + tanh(exp(2*x1 + 2*cos(_a6_))**_a0_))**x1 + x1)**x1)**x1
<lambdifygenerated-957>:2: RuntimeWarning: invalid value encountered in power
  return x1*((x1*(x1 + x1/(_a2_/(_a7_ + x1) + abs(tanh(x1))) + tanh(exp(2*x1 + 2*cos(_a6_))**_a0_))**x1 + x1)**x1)**x1
<lambdifygenerated-958>:2: RuntimeWarning: invalid value encountered in power
  return x1*((x1*(x1 + x1/(_a2_/(_a7_ + x1) + abs(tanh(x1))) + tanh(exp(2*x1 + 2*cos(_a6_))**_a0_))**x1 + x1)**x1)**x1
<lambdifygenerated-959>:2: RuntimeWarning: invalid value encountered in power
  return x1*((x1*(x1 + x1/(_a2_/(_a7_ + sin(x1)) + abs(tanh(x1))) + tanh(exp(2*x1 + 2*cos(_a6_))**_a0_))**x1 + x1)**x1)**x1
<lambdifygenerated-960>:2: RuntimeWarning: invalid value encountered in power
  return x1*((x1*(x1 + x1/(_a2_/(_a7_ + sin(x1)) + abs(tanh(x1))) + tanh(exp(2*x1 + 2*cos(_a6_))**_a0_))**x1 + x1)**x1)**x1
<lambdifygenerated-961>:2: RuntimeWarning: invalid value encountered in power
  return x1*((x1*(x1 + x1/(_a2_/(_a7_ + sin(1)) + abs(tanh(x1))) + tanh(exp(2*x1 + 2*cos(_a6_))**_a0_))**x1 + x1)**x1)**x1
<lambdifygenerated-962>:2: RuntimeWarning: invalid value encountered in power
  return x1*((x1*(x1 + x1/(_a2_/(_a7_ + sin(1)) + abs(tanh(x1))) + tanh(exp(2*x1 + 2*cos(_a6_))**_a0_))**x1 + x1)**x1)**x1
<lambdifygenerated-963>:2: RuntimeWarning: invalid value encountered in power
  return x1*((x1*(x1 + x1/(_a2_/(_a7_ + sin(_a6_/x1)) + abs(tanh(x1))) + tanh(exp(2*x1 + 2*cos(_a6_))**_a0_))**x1 + x1)**x1)**x1
<lambdifygenerated-964>:2: RuntimeWarning: invalid value encountered in power
  return x1*((x1*(x1 + x1/(_a2_/(_a7_ + sin(_a6_/x1)) + abs(tanh(x1))) + tanh(exp(2*x1 + 2*cos(_a6_))**_a0_))**x1 + x1)**x1)**x1
<lambdifygenerated-965>:2: RuntimeWarning: invalid value encountered in power
  return x1*((x1*(x1 + x1/(_a2_/(_a7_ + sin((1/2)*_a6_/x1)) + abs(tanh(x1))) + tanh(exp(2*x1 + 2*cos(_a6_))**_a0_))**x1 + x1)**x1)**x1
<lambdifygenerated-966>:2: RuntimeWarning: invalid value encountered in power
  return x1*((x1*(x1 + x1/(_a2_/(_a7_ + sin((1/2)*_a6_/x1)) + abs(tanh(x1))) + tanh(exp(2*x1 + 2*cos(_a6_))**_a0_))**x1 + x1)**x1)**x1
<lambdifygenerated-967>:2: RuntimeWarning: invalid value encountered in power
  return x1*((x1*(x1 + x1/(_a2_/(_a7_ + sin(_a6_/(x1 + 1))) + abs(tanh(x1))) + tanh(exp(2*x1 + 2*cos(_a6_))**_a0_))**x1 + x1)**x1)**x1
<lambdifygenerated-968>:2: RuntimeWarning: invalid value encountered in power
  return x1*((x1*(x1 + x1/(_a2_/(_a7_ + sin(_a6_/(x1 + 1))) + abs(tanh(x1))) + tanh(exp(2*x1 + 2*cos(_a6_))**_a0_))**x1 + x1)**x1)**x1
<lambdifygenerated-969>:2: RuntimeWarning: invalid value encountered in power
  return x1*((x1*(x1 + x1/(_a2_/(_a7_ + sin(_a6_/(_a1_/x1 + x1))) + abs(tanh(x1))) + tanh(exp(2*x1 + 2*cos(_a6_))**_a0_))**x1 + x1)**x1)**x1
<lambdifygenerated-970>:2: RuntimeWarning: invalid value encountered in power
  return x1*((x1*(x1 + x1/(_a2_/(_a7_ + sin(_a6_/(_a1_/x1 + x1))) + abs(tanh(x1))) + tanh(exp(2*x1 + 2*cos(_a6_))**_a0_))**x1 + x1)**x1)**x1
<lambdifygenerated-971>:2: RuntimeWarning: invalid value encountered in power
  return x1*((x1*(x1 + x1/(_a2_/(_a7_ + sin(_a6_/(_a1_/x1 + x1))) + abs(tanh(x1))) + tanh(exp(2*x1 + 2*cos(_a6_))**_a0_))**x1 + x1)**x1)**x1
<lambdifygenerated-972>:2: RuntimeWarning: invalid value encountered in power
  return x1*((x1*(x1 + x1/(_a2_/(_a7_ + sin(_a6_/(_a1_/x1 + x1))) + abs(tanh(x1))) + tanh(exp(2*x1 + 2*cos(_a6_))**_a0_))**x1 + x1)**x1)**x1
<lambdifygenerated-973>:2: RuntimeWarning: invalid value encountered in power
  return x1*((x1*(x1 + x1/(_a2_/(_a7_ + sin(_a6_/(_a1_/x1 + x1))) + abs(tanh(x1))) + tanh(exp(2*x1 + 2*cos(_a6_))**_a0_))**x1 + x1)**x1)**x1
<lambdifygenerated-974>:2: RuntimeWarning: invalid value encountered in power
  return x1*((x1*(x1 + x1/(_a2_/(_a7_ + sin(_a6_/(_a1_/x1 + x1))) + abs(tanh(x1))) + tanh(exp(2*x1 + 2*cos(_a6_))**_a0_))**x1 + x1)**x1)**x1
<lambdifygenerated-975>:2: RuntimeWarning: invalid value encountered in power
  return x1*((x1*(_a0_ + x1/(_a2_/(_a7_ + sin(_a6_/(_a1_/x1 + x1))) + abs(tanh(x1))) + tanh(exp(2*x1 + 2*cos(_a6_))**_a0_))**x1 + x1)**x1)**x1
<lambdifygenerated-976>:2: RuntimeWarning: invalid value encountered in power
  return x1*((x1*(_a0_ + x1/(_a2_/(_a7_ + sin(_a6_/(_a1_/x1 + x1))) + abs(tanh(x1))) + tanh(exp(2*x1 + 2*cos(_a6_))**_a0_))**x1 + x1)**x1)**x1

interpolation

<lambdifygenerated-977>:2: RuntimeWarning: invalid value encountered in power
  return x1*((x1*(_a0_ + x1/(_a2_/(_a7_ + sin(_a6_/(_a1_/x1 + x1))) + abs(tanh(x1))) + tanh(exp(2*x1 + 2*cos(_a6_))**_a0_))**_a3_ + x1)**x1)**x1
<lambdifygenerated-978>:2: RuntimeWarning: invalid value encountered in power
  return x1*((x1*(_a0_ + x1/(_a2_/(_a7_ + sin(_a6_/(_a1_/x1 + x1))) + abs(tanh(x1))) + tanh(exp(2*x1 + 2*cos(_a6_))**_a0_))**_a3_ + x1)**x1)**x1
<lambdifygenerated-979>:2: RuntimeWarning: invalid value encountered in power
  return x1*((_a4_*(_a0_ + x1/(_a2_/(_a7_ + sin(_a6_/(_a1_/x1 + x1))) + abs(tanh(x1))) + tanh(exp(2*x1 + 2*cos(_a6_))**_a0_))**_a3_ + x1)**x1)**x1
<lambdifygenerated-980>:2: RuntimeWarning: invalid value encountered in power
  return x1*((_a4_*(_a0_ + x1/(_a2_/(_a7_ + sin(_a6_/(_a1_/x1 + x1))) + abs(tanh(x1))) + tanh(exp(2*x1 + 2*cos(_a6_))**_a0_))**_a3_ + x1)**x1)**x1
<lambdifygenerated-981>:2: RuntimeWarning: invalid value encountered in power
  return x1*((_a4_*(_a0_ + x1/(_a2_/(_a7_ + sin(_a6_/(_a1_/x1 + x1))) + abs(tanh(x1))) + tanh(exp(2*x1 + 2*cos(_a6_))**_a0_))**_a3_ + x1**2)**x1)**x1
<lambdifygenerated-983>:2: RuntimeWarning: invalid value encountered in power
  return x1*((_a4_*(_a0_ + x1/(_a2_/(_a7_ + sin(_a6_/(_a1_/x1 + x1))) + abs(tanh(x1))) + tanh(exp(2*x1 + 2*cos(_a6_))**_a0_))**_a3_ + x1*cos(x1))**x1)**x1
<lambdifygenerated-984>:2: RuntimeWarning: invalid value encountered in power
  return x1*((_a4_*(_a0_ + x1/(_a2_/(_a7_ + sin(_a6_/(_a1_/x1 + x1))) + abs(tanh(x1))) + tanh(exp(2*x1 + 2*cos(_a6_))**_a0_))**_a3_ + x1*cos(x1))**x1)**x1
<lambdifygenerated-985>:2: RuntimeWarning: invalid value encountered in power
  return x1*((_a4_*(_a0_ + x1/(_a2_/(_a7_ + sin(_a6_/(_a1_/x1 + x1))) + abs(tanh(x1))) + tanh(exp(2*x1 + 2*cos(_a6_))**_a0_))**_a3_ + x1*cos(x1))**x1)**x1
<lambdifygenerated-986>:2: RuntimeWarning: invalid value encountered in power
  return x1*((_a4_*(_a0_ + x1/(_a2_/(_a7_ + sin(_a6_/(_a1_/x1 + x1))) + abs(tanh(x1))) + tanh(exp(2*x1 + 2*cos(_a6_))**_a0_))**_a3_ + x1*cos(x1))**x1)**x1
<lambdifygenerated-987>:2: RuntimeWarning: invalid value encountered in power
  return x1*((_a1_*cos(x1) + _a4_*(_a0_ + x1/(_a2_/(_a7_ + sin(_a6_/(_a1_/x1 + x1))) + abs(tanh(x1))) + tanh(exp(2*x1 + 2*cos(_a6_))**_a0_))**_a3_)**x1)**x1
<lambdifygenerated-988>:2: RuntimeWarning: invalid value encountered in power
  return x1*((_a1_*cos(x1) + _a4_*(_a0_ + x1/(_a2_/(_a7_ + sin(_a6_/(_a1_/x1 + x1))) + abs(tanh(x1))) + tanh(exp(2*x1 + 2*cos(_a6_))**_a0_))**_a3_)**x1)**x1
<lambdifygenerated-989>:2: RuntimeWarning: invalid value encountered in power
  return x1*((_a1_*cos(x1) + _a4_*(_a0_ + x1/(_a2_/(_a7_ + sin(_a6_/(_a1_/x1 + x1))) + abs(tanh(x1))) + tanh(exp(2*x1 + 2*cos(_a6_))**_a0_))**_a3_)**_a0_)**x1
<lambdifygenerated-990>:2: RuntimeWarning: invalid value encountered in power
  return x1*((_a1_*cos(x1) + _a4_*(_a0_ + x1/(_a2_/(_a7_ + sin(_a6_/(_a1_/x1 + x1))) + abs(tanh(x1))) + tanh(exp(2*x1 + 2*cos(_a6_))**_a0_))**_a3_)**_a0_)**x1
<lambdifygenerated-991>:2: RuntimeWarning: invalid value encountered in power
  return x1*((_a1_*cos(x1) + _a4_*(_a0_ + x1/(_a2_/(_a7_ + sin(_a6_/(_a1_/x1 + x1))) + abs(tanh(x1))) + tanh(exp(2*x1 + 2*cos(_a6_))**_a0_))**_a3_)**_a0_)**_a3_
<lambdifygenerated-992>:2: RuntimeWarning: invalid value encountered in power
  return x1*((_a1_*cos(x1) + _a4_*(_a0_ + x1/(_a2_/(_a7_ + sin(_a6_/(_a1_/x1 + x1))) + abs(tanh(x1))) + tanh(exp(2*x1 + 2*cos(_a6_))**_a0_))**_a3_)**_a0_)**_a3_
<lambdifygenerated-993>:2: RuntimeWarning: invalid value encountered in power
  return _a6_*((_a1_*cos(x1) + _a4_*(_a0_ + x1/(_a2_/(_a7_ + sin(_a6_/(_a1_/x1 + x1))) + abs(tanh(x1))) + tanh(exp(2*x1 + 2*cos(_a6_))**_a0_))**_a3_)**_a0_)**_a3_
<lambdifygenerated-994>:2: RuntimeWarning: invalid value encountered in power
  return _a6_*((_a1_*cos(x1) + _a4_*(_a0_ + x1/(_a2_/(_a7_ + sin(_a6_/(_a1_/x1 + x1))) + abs(tanh(x1))) + tanh(exp(2*x1 + 2*cos(_a6_))**_a0_))**_a3_)**_a0_)**_a3_
<lambdifygenerated-995>:2: RuntimeWarning: invalid value encountered in power
  return _a6_*((_a1_*cos(x1) + _a4_*(_a0_ + x1/(_a2_/(_a7_ + sin(_a6_/(_a1_/x1 + x1))) + abs(tanh(x1))) + tanh(exp(2*x1 + 2*cos(_a6_))**_a0_))**_a3_)**_a0_)**_a3_
<lambdifygenerated-996>:2: RuntimeWarning: invalid value encountered in power
  return _a6_*((_a1_*cos(x1) + _a4_*(_a0_ + x1/(_a2_/(_a7_ + sin(_a6_/(_a1_/x1 + x1))) + abs(tanh(x1))) + tanh(exp(2*x1 + 2*cos(_a6_))**_a0_))**_a3_)**_a0_)**_a3_
<lambdifygenerated-997>:2: RuntimeWarning: invalid value encountered in power
  return _a6_*((_a1_*cos(x1) + _a4_*(_a0_ + x1/(_a2_/(_a7_ + sin(_a6_/(_a1_/x1 + x1))) + abs(tanh(x1))) + tanh(exp(2*x1 + 2*cos(_a6_))**_a0_))**_a3_)**_a0_)**_a3_
<lambdifygenerated-998>:2: RuntimeWarning: invalid value encountered in power
  return _a6_*((_a1_*cos(x1) + _a4_*(_a0_ + x1/(_a2_/(_a7_ + sin(_a6_/(_a1_/x1 + x1))) + abs(tanh(x1))) + tanh(exp(2*x1 + 2*cos(_a6_))**_a0_))**_a3_)**_a0_)**_a3_

         x1         y  rep    ymodel      ybms
3745  0.997  0.855453  9.0  0.854418  0.855301
3746  0.998  0.855554  9.0  0.854499  0.855398
3747  0.998  0.855656  9.0  0.854581  0.855495
3748  0.999  0.855757  9.0  0.854662  0.855591

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.855960  9.0  0.854825  0.855785
3751  1.002  0.856062  9.0  0.854906  0.855881
3752  1.002  0.856163  9.0  0.854987  0.855978
3753  1.003  0.856265  9.0  0.855067  0.856074

3750

<lambdifygenerated-1007>:2: RuntimeWarning: overflow encountered in sinh
  return x1 + sinh(tan(x1))
/usr/local/lib/python3.10/dist-packages/pandas/core/arraylike.py:399: RuntimeWarning: overflow encountered in square
  result = getattr(ufunc, method)(*inputs, **kwargs)
<lambdifygenerated-1008>:2: RuntimeWarning: overflow encountered in sinh
  return x1 + sinh(tan(x1))
<lambdifygenerated-1009>:2: RuntimeWarning: overflow encountered in sinh
  return x1 + sinh(tan(x1**2))
<lambdifygenerated-1010>:2: RuntimeWarning: overflow encountered in sinh
  return x1 + sinh(tan(x1**2))
<lambdifygenerated-1013>:2: RuntimeWarning: invalid value encountered in log
  return x1 + sinh(tan(log(x1)**2/x1**2))
<lambdifygenerated-1013>:2: RuntimeWarning: overflow encountered in sinh
  return x1 + sinh(tan(log(x1)**2/x1**2))
<lambdifygenerated-1014>:2: RuntimeWarning: invalid value encountered in log
  return x1 + sinh(tan(log(x1)**2/x1**2))
<lambdifygenerated-1014>:2: RuntimeWarning: overflow encountered in sinh
  return x1 + sinh(tan(log(x1)**2/x1**2))
<lambdifygenerated-1017>:2: RuntimeWarning: overflow encountered in sinh
  return x1 + sinh(tan(log(2*x1**2)**2/x1**2))
<lambdifygenerated-1018>:2: RuntimeWarning: overflow encountered in sinh
  return x1 + sinh(tan(log(2*x1**2)**2/x1**2))
<lambdifygenerated-1019>:2: RuntimeWarning: overflow encountered in sinh
  return x1 + sinh(tan(log(3*x1**2)**2/x1**2))
<lambdifygenerated-1020>:2: RuntimeWarning: overflow encountered in sinh
  return x1 + sinh(tan(log(3*x1**2)**2/x1**2))
<lambdifygenerated-1021>:2: RuntimeWarning: invalid value encountered in log
  return x1 + sinh(tan(log(x1*(2*x1 + tan(x1)))**2/x1**2))
<lambdifygenerated-1021>:2: RuntimeWarning: overflow encountered in sinh
  return x1 + sinh(tan(log(x1*(2*x1 + tan(x1)))**2/x1**2))
<lambdifygenerated-1022>:2: RuntimeWarning: invalid value encountered in log
  return x1 + sinh(tan(log(x1*(2*x1 + tan(x1)))**2/x1**2))
<lambdifygenerated-1022>:2: RuntimeWarning: overflow encountered in sinh
  return x1 + sinh(tan(log(x1*(2*x1 + tan(x1)))**2/x1**2))
<lambdifygenerated-1023>:2: RuntimeWarning: invalid value encountered in log
  return x1 + sinh(tan(log(x1*(2*x1 + tan(exp(x1))))**2/x1**2))
<lambdifygenerated-1023>:2: RuntimeWarning: overflow encountered in sinh
  return x1 + sinh(tan(log(x1*(2*x1 + tan(exp(x1))))**2/x1**2))
<lambdifygenerated-1024>:2: RuntimeWarning: invalid value encountered in log
  return x1 + sinh(tan(log(x1*(2*x1 + tan(exp(x1))))**2/x1**2))
<lambdifygenerated-1024>:2: RuntimeWarning: overflow encountered in sinh
  return x1 + sinh(tan(log(x1*(2*x1 + tan(exp(x1))))**2/x1**2))
<lambdifygenerated-1025>:2: RuntimeWarning: invalid value encountered in log
  return x1 + sinh(tan(log(x1*(2*x1 + tan(exp(2*x1))))**2/x1**2))
<lambdifygenerated-1025>:2: RuntimeWarning: overflow encountered in sinh
  return x1 + sinh(tan(log(x1*(2*x1 + tan(exp(2*x1))))**2/x1**2))
<lambdifygenerated-1026>:2: RuntimeWarning: invalid value encountered in log
  return x1 + sinh(tan(log(x1*(2*x1 + tan(exp(2*x1))))**2/x1**2))
<lambdifygenerated-1026>:2: RuntimeWarning: overflow encountered in sinh
  return x1 + sinh(tan(log(x1*(2*x1 + tan(exp(2*x1))))**2/x1**2))
<lambdifygenerated-1027>:2: RuntimeWarning: invalid value encountered in power
  return x1 + sinh(tan(log(x1*(2*x1 + tan(exp(x1 + x1**x1))))**2/x1**2))
<lambdifygenerated-1027>:2: RuntimeWarning: invalid value encountered in log
  return x1 + sinh(tan(log(x1*(2*x1 + tan(exp(x1 + x1**x1))))**2/x1**2))
<lambdifygenerated-1027>:2: RuntimeWarning: overflow encountered in sinh
  return x1 + sinh(tan(log(x1*(2*x1 + tan(exp(x1 + x1**x1))))**2/x1**2))
<lambdifygenerated-1028>:2: RuntimeWarning: invalid value encountered in power
  return x1 + sinh(tan(log(x1*(2*x1 + tan(exp(x1 + x1**x1))))**2/x1**2))
<lambdifygenerated-1028>:2: RuntimeWarning: invalid value encountered in log
  return x1 + sinh(tan(log(x1*(2*x1 + tan(exp(x1 + x1**x1))))**2/x1**2))
<lambdifygenerated-1028>:2: RuntimeWarning: overflow encountered in sinh
  return x1 + sinh(tan(log(x1*(2*x1 + tan(exp(x1 + x1**x1))))**2/x1**2))
<lambdifygenerated-1029>:2: RuntimeWarning: invalid value encountered in power
  return x1 + sinh(tan(log(x1*(2*x1 + tan(exp(x1 + tan(x1)**x1))))**2/x1**2))
<lambdifygenerated-1029>:2: RuntimeWarning: overflow encountered in exp
  return x1 + sinh(tan(log(x1*(2*x1 + tan(exp(x1 + tan(x1)**x1))))**2/x1**2))
<lambdifygenerated-1029>:2: RuntimeWarning: invalid value encountered in tan
  return x1 + sinh(tan(log(x1*(2*x1 + tan(exp(x1 + tan(x1)**x1))))**2/x1**2))
<lambdifygenerated-1029>:2: RuntimeWarning: invalid value encountered in log
  return x1 + sinh(tan(log(x1*(2*x1 + tan(exp(x1 + tan(x1)**x1))))**2/x1**2))
<lambdifygenerated-1029>:2: RuntimeWarning: overflow encountered in sinh
  return x1 + sinh(tan(log(x1*(2*x1 + tan(exp(x1 + tan(x1)**x1))))**2/x1**2))
<lambdifygenerated-1030>:2: RuntimeWarning: invalid value encountered in power
  return x1 + sinh(tan(log(x1*(2*x1 + tan(exp(x1 + tan(x1)**x1))))**2/x1**2))
<lambdifygenerated-1030>:2: RuntimeWarning: overflow encountered in exp
  return x1 + sinh(tan(log(x1*(2*x1 + tan(exp(x1 + tan(x1)**x1))))**2/x1**2))
<lambdifygenerated-1030>:2: RuntimeWarning: invalid value encountered in tan
  return x1 + sinh(tan(log(x1*(2*x1 + tan(exp(x1 + tan(x1)**x1))))**2/x1**2))
<lambdifygenerated-1030>:2: RuntimeWarning: invalid value encountered in log
  return x1 + sinh(tan(log(x1*(2*x1 + tan(exp(x1 + tan(x1)**x1))))**2/x1**2))
<lambdifygenerated-1030>:2: RuntimeWarning: overflow encountered in sinh
  return x1 + sinh(tan(log(x1*(2*x1 + tan(exp(x1 + tan(x1)**x1))))**2/x1**2))
<lambdifygenerated-1031>:2: RuntimeWarning: invalid value encountered in power
  return x1 + sinh(tan(log(x1*(2*x1 + tan(exp(x1 + tan(x1**x1)**x1))))**2/x1**2))
<lambdifygenerated-1031>:2: RuntimeWarning: overflow encountered in exp
  return x1 + sinh(tan(log(x1*(2*x1 + tan(exp(x1 + tan(x1**x1)**x1))))**2/x1**2))
<lambdifygenerated-1031>:2: RuntimeWarning: invalid value encountered in tan
  return x1 + sinh(tan(log(x1*(2*x1 + tan(exp(x1 + tan(x1**x1)**x1))))**2/x1**2))
<lambdifygenerated-1031>:2: RuntimeWarning: invalid value encountered in log
  return x1 + sinh(tan(log(x1*(2*x1 + tan(exp(x1 + tan(x1**x1)**x1))))**2/x1**2))
<lambdifygenerated-1031>:2: RuntimeWarning: overflow encountered in sinh
  return x1 + sinh(tan(log(x1*(2*x1 + tan(exp(x1 + tan(x1**x1)**x1))))**2/x1**2))
<lambdifygenerated-1032>:2: RuntimeWarning: invalid value encountered in power
  return x1 + sinh(tan(log(x1*(2*x1 + tan(exp(x1 + tan(x1**x1)**x1))))**2/x1**2))
<lambdifygenerated-1032>:2: RuntimeWarning: overflow encountered in exp
  return x1 + sinh(tan(log(x1*(2*x1 + tan(exp(x1 + tan(x1**x1)**x1))))**2/x1**2))
<lambdifygenerated-1032>:2: RuntimeWarning: invalid value encountered in tan
  return x1 + sinh(tan(log(x1*(2*x1 + tan(exp(x1 + tan(x1**x1)**x1))))**2/x1**2))
<lambdifygenerated-1032>:2: RuntimeWarning: invalid value encountered in log
  return x1 + sinh(tan(log(x1*(2*x1 + tan(exp(x1 + tan(x1**x1)**x1))))**2/x1**2))
<lambdifygenerated-1032>:2: RuntimeWarning: overflow encountered in sinh
  return x1 + sinh(tan(log(x1*(2*x1 + tan(exp(x1 + tan(x1**x1)**x1))))**2/x1**2))
<lambdifygenerated-1033>:2: RuntimeWarning: invalid value encountered in power
  return x1 + sinh(tan(log(x1*(2*x1 + tan(exp(x1 + tan((x1**x1)**x1)**x1))))**2/x1**2))
<lambdifygenerated-1033>:2: RuntimeWarning: overflow encountered in exp
  return x1 + sinh(tan(log(x1*(2*x1 + tan(exp(x1 + tan((x1**x1)**x1)**x1))))**2/x1**2))
<lambdifygenerated-1033>:2: RuntimeWarning: invalid value encountered in tan
  return x1 + sinh(tan(log(x1*(2*x1 + tan(exp(x1 + tan((x1**x1)**x1)**x1))))**2/x1**2))
<lambdifygenerated-1033>:2: RuntimeWarning: invalid value encountered in log
  return x1 + sinh(tan(log(x1*(2*x1 + tan(exp(x1 + tan((x1**x1)**x1)**x1))))**2/x1**2))
<lambdifygenerated-1033>:2: RuntimeWarning: overflow encountered in sinh
  return x1 + sinh(tan(log(x1*(2*x1 + tan(exp(x1 + tan((x1**x1)**x1)**x1))))**2/x1**2))
<lambdifygenerated-1034>:2: RuntimeWarning: invalid value encountered in power
  return x1 + sinh(tan(log(x1*(2*x1 + tan(exp(x1 + tan((x1**x1)**x1)**x1))))**2/x1**2))
<lambdifygenerated-1034>:2: RuntimeWarning: overflow encountered in exp
  return x1 + sinh(tan(log(x1*(2*x1 + tan(exp(x1 + tan((x1**x1)**x1)**x1))))**2/x1**2))
<lambdifygenerated-1034>:2: RuntimeWarning: invalid value encountered in tan
  return x1 + sinh(tan(log(x1*(2*x1 + tan(exp(x1 + tan((x1**x1)**x1)**x1))))**2/x1**2))
<lambdifygenerated-1034>:2: RuntimeWarning: invalid value encountered in log
  return x1 + sinh(tan(log(x1*(2*x1 + tan(exp(x1 + tan((x1**x1)**x1)**x1))))**2/x1**2))
<lambdifygenerated-1034>:2: RuntimeWarning: overflow encountered in sinh
  return x1 + sinh(tan(log(x1*(2*x1 + tan(exp(x1 + tan((x1**x1)**x1)**x1))))**2/x1**2))
<lambdifygenerated-1035>:2: RuntimeWarning: invalid value encountered in power
  return x1 + sinh(tan(log(x1*(2*x1 + tan(exp(x1 + tan(((x1**2)**x1)**x1)**x1))))**2/x1**2))
<lambdifygenerated-1035>:2: RuntimeWarning: overflow encountered in exp
  return x1 + sinh(tan(log(x1*(2*x1 + tan(exp(x1 + tan(((x1**2)**x1)**x1)**x1))))**2/x1**2))
<lambdifygenerated-1035>:2: RuntimeWarning: invalid value encountered in tan
  return x1 + sinh(tan(log(x1*(2*x1 + tan(exp(x1 + tan(((x1**2)**x1)**x1)**x1))))**2/x1**2))
<lambdifygenerated-1035>:2: RuntimeWarning: invalid value encountered in log
  return x1 + sinh(tan(log(x1*(2*x1 + tan(exp(x1 + tan(((x1**2)**x1)**x1)**x1))))**2/x1**2))
<lambdifygenerated-1035>:2: RuntimeWarning: overflow encountered in sinh
  return x1 + sinh(tan(log(x1*(2*x1 + tan(exp(x1 + tan(((x1**2)**x1)**x1)**x1))))**2/x1**2))
<lambdifygenerated-1036>:2: RuntimeWarning: invalid value encountered in power
  return x1 + sinh(tan(log(x1*(2*x1 + tan(exp(x1 + tan(((x1**2)**x1)**x1)**x1))))**2/x1**2))
<lambdifygenerated-1036>:2: RuntimeWarning: overflow encountered in exp
  return x1 + sinh(tan(log(x1*(2*x1 + tan(exp(x1 + tan(((x1**2)**x1)**x1)**x1))))**2/x1**2))
<lambdifygenerated-1036>:2: RuntimeWarning: invalid value encountered in tan
  return x1 + sinh(tan(log(x1*(2*x1 + tan(exp(x1 + tan(((x1**2)**x1)**x1)**x1))))**2/x1**2))
<lambdifygenerated-1036>:2: RuntimeWarning: invalid value encountered in log
  return x1 + sinh(tan(log(x1*(2*x1 + tan(exp(x1 + tan(((x1**2)**x1)**x1)**x1))))**2/x1**2))
<lambdifygenerated-1036>:2: RuntimeWarning: overflow encountered in sinh
  return x1 + sinh(tan(log(x1*(2*x1 + tan(exp(x1 + tan(((x1**2)**x1)**x1)**x1))))**2/x1**2))
<lambdifygenerated-1037>:2: RuntimeWarning: invalid value encountered in log
  return x1 + sinh(tan(log(x1*(2*x1 + tan(exp(x1 + tan(((_a3_**2)**x1)**x1)**x1))))**2/x1**2))
<lambdifygenerated-1037>:2: RuntimeWarning: overflow encountered in sinh
  return x1 + sinh(tan(log(x1*(2*x1 + tan(exp(x1 + tan(((_a3_**2)**x1)**x1)**x1))))**2/x1**2))
/usr/local/lib/python3.10/dist-packages/scipy/optimize/_minpack_py.py:1017: RuntimeWarning: overflow encountered in square
  cost = np.sum(infodict['fvec'] ** 2)
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-1038>:2: RuntimeWarning: invalid value encountered in log
  return x1 + sinh(tan(log(x1*(2*x1 + tan(exp(x1 + tan(((_a3_**2)**x1)**x1)**x1))))**2/x1**2))
<lambdifygenerated-1038>:2: RuntimeWarning: overflow encountered in sinh
  return x1 + sinh(tan(log(x1*(2*x1 + tan(exp(x1 + tan(((_a3_**2)**x1)**x1)**x1))))**2/x1**2))
<lambdifygenerated-1039>:2: RuntimeWarning: invalid value encountered in log
  return x1 + sinh(tan(log(x1*(2*x1 + tan(exp(x1 + tan(((_a3_**2)**_a7_)**x1)**x1))))**2/x1**2))
<lambdifygenerated-1039>:2: RuntimeWarning: overflow encountered in sinh
  return x1 + sinh(tan(log(x1*(2*x1 + tan(exp(x1 + tan(((_a3_**2)**_a7_)**x1)**x1))))**2/x1**2))
<lambdifygenerated-1040>:2: RuntimeWarning: invalid value encountered in log
  return x1 + sinh(tan(log(x1*(2*x1 + tan(exp(x1 + tan(((_a3_**2)**_a7_)**x1)**x1))))**2/x1**2))
<lambdifygenerated-1040>:2: RuntimeWarning: overflow encountered in sinh
  return x1 + sinh(tan(log(x1*(2*x1 + tan(exp(x1 + tan(((_a3_**2)**_a7_)**x1)**x1))))**2/x1**2))
<lambdifygenerated-1041>:2: RuntimeWarning: invalid value encountered in power
  return x1 + sinh(tan(log(x1*(2*x1 + tan(exp(x1 + tan(((_a3_**2)**_a7_)**(x1**x1))**x1))))**2/x1**2))
<lambdifygenerated-1041>:2: RuntimeWarning: invalid value encountered in log
  return x1 + sinh(tan(log(x1*(2*x1 + tan(exp(x1 + tan(((_a3_**2)**_a7_)**(x1**x1))**x1))))**2/x1**2))
<lambdifygenerated-1041>:2: RuntimeWarning: overflow encountered in sinh
  return x1 + sinh(tan(log(x1*(2*x1 + tan(exp(x1 + tan(((_a3_**2)**_a7_)**(x1**x1))**x1))))**2/x1**2))
<lambdifygenerated-1042>:2: RuntimeWarning: invalid value encountered in power
  return x1 + sinh(tan(log(x1*(2*x1 + tan(exp(x1 + tan(((_a3_**2)**_a7_)**(x1**x1))**x1))))**2/x1**2))
<lambdifygenerated-1042>:2: RuntimeWarning: invalid value encountered in log
  return x1 + sinh(tan(log(x1*(2*x1 + tan(exp(x1 + tan(((_a3_**2)**_a7_)**(x1**x1))**x1))))**2/x1**2))
<lambdifygenerated-1042>:2: RuntimeWarning: overflow encountered in sinh
  return x1 + sinh(tan(log(x1*(2*x1 + tan(exp(x1 + tan(((_a3_**2)**_a7_)**(x1**x1))**x1))))**2/x1**2))
<lambdifygenerated-1043>:2: RuntimeWarning: invalid value encountered in log
  return x1 + sinh(tan(log(x1*(2*x1 + tan(exp(x1 + tan(((_a3_**2)**_a7_)**((x1**2)**x1))**x1))))**2/x1**2))
<lambdifygenerated-1043>:2: RuntimeWarning: overflow encountered in sinh
  return x1 + sinh(tan(log(x1*(2*x1 + tan(exp(x1 + tan(((_a3_**2)**_a7_)**((x1**2)**x1))**x1))))**2/x1**2))
<lambdifygenerated-1044>:2: RuntimeWarning: invalid value encountered in log
  return x1 + sinh(tan(log(x1*(2*x1 + tan(exp(x1 + tan(((_a3_**2)**_a7_)**((x1**2)**x1))**x1))))**2/x1**2))
<lambdifygenerated-1044>:2: RuntimeWarning: overflow encountered in sinh
  return x1 + sinh(tan(log(x1*(2*x1 + tan(exp(x1 + tan(((_a3_**2)**_a7_)**((x1**2)**x1))**x1))))**2/x1**2))
<lambdifygenerated-1045>:2: RuntimeWarning: invalid value encountered in power
  return x1 + sinh(tan(log(x1*(2*x1 + tan(exp(x1 + tan(((_a3_**2)**_a7_)**((x1**3)**x1))**x1))))**2/x1**2))
<lambdifygenerated-1045>:2: RuntimeWarning: invalid value encountered in log
  return x1 + sinh(tan(log(x1*(2*x1 + tan(exp(x1 + tan(((_a3_**2)**_a7_)**((x1**3)**x1))**x1))))**2/x1**2))
<lambdifygenerated-1045>:2: RuntimeWarning: overflow encountered in sinh
  return x1 + sinh(tan(log(x1*(2*x1 + tan(exp(x1 + tan(((_a3_**2)**_a7_)**((x1**3)**x1))**x1))))**2/x1**2))
<lambdifygenerated-1046>:2: RuntimeWarning: invalid value encountered in power
  return x1 + sinh(tan(log(x1*(2*x1 + tan(exp(x1 + tan(((_a3_**2)**_a7_)**((x1**3)**x1))**x1))))**2/x1**2))
<lambdifygenerated-1046>:2: RuntimeWarning: invalid value encountered in log
  return x1 + sinh(tan(log(x1*(2*x1 + tan(exp(x1 + tan(((_a3_**2)**_a7_)**((x1**3)**x1))**x1))))**2/x1**2))
<lambdifygenerated-1046>:2: RuntimeWarning: overflow encountered in sinh
  return x1 + sinh(tan(log(x1*(2*x1 + tan(exp(x1 + tan(((_a3_**2)**_a7_)**((x1**3)**x1))**x1))))**2/x1**2))
<lambdifygenerated-1047>:2: RuntimeWarning: invalid value encountered in power
  return x1 + sinh(tan(log(x1*(2*x1 + tan(exp(x1 + tan(((_a3_**2)**_a7_)**((x1**5)**x1))**x1))))**2/x1**2))
<lambdifygenerated-1047>:2: RuntimeWarning: invalid value encountered in log
  return x1 + sinh(tan(log(x1*(2*x1 + tan(exp(x1 + tan(((_a3_**2)**_a7_)**((x1**5)**x1))**x1))))**2/x1**2))
<lambdifygenerated-1047>:2: RuntimeWarning: overflow encountered in sinh
  return x1 + sinh(tan(log(x1*(2*x1 + tan(exp(x1 + tan(((_a3_**2)**_a7_)**((x1**5)**x1))**x1))))**2/x1**2))
<lambdifygenerated-1048>:2: RuntimeWarning: invalid value encountered in power
  return x1 + sinh(tan(log(x1*(2*x1 + tan(exp(x1 + tan(((_a3_**2)**_a7_)**((x1**5)**x1))**x1))))**2/x1**2))
<lambdifygenerated-1048>:2: RuntimeWarning: invalid value encountered in log
  return x1 + sinh(tan(log(x1*(2*x1 + tan(exp(x1 + tan(((_a3_**2)**_a7_)**((x1**5)**x1))**x1))))**2/x1**2))
<lambdifygenerated-1048>:2: RuntimeWarning: overflow encountered in sinh
  return x1 + sinh(tan(log(x1*(2*x1 + tan(exp(x1 + tan(((_a3_**2)**_a7_)**((x1**5)**x1))**x1))))**2/x1**2))
<lambdifygenerated-1049>:2: RuntimeWarning: invalid value encountered in power
  return x1 + sinh(tan(log(x1*(2*x1 + tan(exp(x1 + tan(((_a3_**2)**_a7_)**((x1**3)**x1))**x1))))**2/x1**2))
<lambdifygenerated-1049>:2: RuntimeWarning: invalid value encountered in log
  return x1 + sinh(tan(log(x1*(2*x1 + tan(exp(x1 + tan(((_a3_**2)**_a7_)**((x1**3)**x1))**x1))))**2/x1**2))
<lambdifygenerated-1049>:2: RuntimeWarning: overflow encountered in sinh
  return x1 + sinh(tan(log(x1*(2*x1 + tan(exp(x1 + tan(((_a3_**2)**_a7_)**((x1**3)**x1))**x1))))**2/x1**2))
<lambdifygenerated-1050>:2: RuntimeWarning: invalid value encountered in power
  return x1 + sinh(tan(log(x1*(2*x1 + tan(exp(x1 + tan(((_a3_**2)**_a7_)**((x1**3)**x1))**x1))))**2/x1**2))
<lambdifygenerated-1050>:2: RuntimeWarning: invalid value encountered in log
  return x1 + sinh(tan(log(x1*(2*x1 + tan(exp(x1 + tan(((_a3_**2)**_a7_)**((x1**3)**x1))**x1))))**2/x1**2))
<lambdifygenerated-1050>:2: RuntimeWarning: overflow encountered in sinh
  return x1 + sinh(tan(log(x1*(2*x1 + tan(exp(x1 + tan(((_a3_**2)**_a7_)**((x1**3)**x1))**x1))))**2/x1**2))
<lambdifygenerated-1051>:2: RuntimeWarning: invalid value encountered in power
  return x1 + sinh(tan(log(x1*(2*x1 + tan(exp(x1 + tan(((_a3_**2)**_a7_)**((_a7_**2*x1)**x1))**x1))))**2/x1**2))
<lambdifygenerated-1051>:2: RuntimeWarning: invalid value encountered in log
  return x1 + sinh(tan(log(x1*(2*x1 + tan(exp(x1 + tan(((_a3_**2)**_a7_)**((_a7_**2*x1)**x1))**x1))))**2/x1**2))
<lambdifygenerated-1051>:2: RuntimeWarning: overflow encountered in sinh
  return x1 + sinh(tan(log(x1*(2*x1 + tan(exp(x1 + tan(((_a3_**2)**_a7_)**((_a7_**2*x1)**x1))**x1))))**2/x1**2))
<lambdifygenerated-1052>:2: RuntimeWarning: invalid value encountered in power
  return x1 + sinh(tan(log(x1*(2*x1 + tan(exp(x1 + tan(((_a3_**2)**_a7_)**((_a7_**2*x1)**x1))**x1))))**2/x1**2))
<lambdifygenerated-1052>:2: RuntimeWarning: invalid value encountered in log
  return x1 + sinh(tan(log(x1*(2*x1 + tan(exp(x1 + tan(((_a3_**2)**_a7_)**((_a7_**2*x1)**x1))**x1))))**2/x1**2))
<lambdifygenerated-1052>:2: RuntimeWarning: overflow encountered in sinh
  return x1 + sinh(tan(log(x1*(2*x1 + tan(exp(x1 + tan(((_a3_**2)**_a7_)**((_a7_**2*x1)**x1))**x1))))**2/x1**2))
<lambdifygenerated-1053>:2: RuntimeWarning: invalid value encountered in power
  return x1 + sinh(tan(log(x1*(2*x1 + tan(exp(x1 + tan(((_a3_**2)**_a7_)**((_a7_**2*x1**3/_a0_**2)**x1))**x1))))**2/x1**2))
<lambdifygenerated-1053>:2: RuntimeWarning: invalid value encountered in log
  return x1 + sinh(tan(log(x1*(2*x1 + tan(exp(x1 + tan(((_a3_**2)**_a7_)**((_a7_**2*x1**3/_a0_**2)**x1))**x1))))**2/x1**2))
<lambdifygenerated-1053>:2: RuntimeWarning: overflow encountered in sinh
  return x1 + sinh(tan(log(x1*(2*x1 + tan(exp(x1 + tan(((_a3_**2)**_a7_)**((_a7_**2*x1**3/_a0_**2)**x1))**x1))))**2/x1**2))
<lambdifygenerated-1054>:2: RuntimeWarning: invalid value encountered in power
  return x1 + sinh(tan(log(x1*(2*x1 + tan(exp(x1 + tan(((_a3_**2)**_a7_)**((_a7_**2*x1**3/_a0_**2)**x1))**x1))))**2/x1**2))
<lambdifygenerated-1054>:2: RuntimeWarning: invalid value encountered in log
  return x1 + sinh(tan(log(x1*(2*x1 + tan(exp(x1 + tan(((_a3_**2)**_a7_)**((_a7_**2*x1**3/_a0_**2)**x1))**x1))))**2/x1**2))
<lambdifygenerated-1054>:2: RuntimeWarning: overflow encountered in sinh
  return x1 + sinh(tan(log(x1*(2*x1 + tan(exp(x1 + tan(((_a3_**2)**_a7_)**((_a7_**2*x1**3/_a0_**2)**x1))**x1))))**2/x1**2))
<lambdifygenerated-1055>:2: RuntimeWarning: invalid value encountered in power
  return x1 + sinh(tan(log(x1*(2*x1 + tan(exp(x1 + tan(((_a3_**2)**_a7_)**((_a4_**2*_a7_**2*x1/_a0_**2)**x1))**x1))))**2/x1**2))
<lambdifygenerated-1055>:2: RuntimeWarning: invalid value encountered in log

interpolation

<lambdifygenerated-1097>:2: RuntimeWarning: overflow encountered in sinh
  return x1 + sinh(tan(log(_a5_*(2*_a5_ + x1 + tan(exp(_a1_ + tan(((_a3_**2)**_a7_)**((_a3_*_a4_**2*_a7_**2*cos(_a5_)/_a0_)**x1))**(_a6_**tanh((_a4_ + x1)/_a0_))))))**2/x1**2))
<lambdifygenerated-1098>:2: RuntimeWarning: overflow encountered in sinh
  return x1 + sinh(tan(log(_a5_*(2*_a5_ + x1 + tan(exp(_a1_ + tan(((_a3_**2)**_a7_)**((_a3_*_a4_**2*_a7_**2*cos(_a5_)/_a0_)**x1))**(_a6_**tanh((_a4_ + x1)/_a0_))))))**2/x1**2))
<lambdifygenerated-1099>:2: RuntimeWarning: overflow encountered in sinh
  return x1 + sinh(tan(log(_a5_*(2*_a5_ + x1 + tan(exp(_a1_ + tan(((_a3_**2)**_a7_)**((_a3_*_a4_**2*_a7_**2*cos(_a5_)/_a0_)**x1))**(_a6_**tanh((_a4_ + x1)/_a0_))))))**2/_a2_**2))
<lambdifygenerated-1100>:2: RuntimeWarning: overflow encountered in sinh
  return x1 + sinh(tan(log(_a5_*(2*_a5_ + x1 + tan(exp(_a1_ + tan(((_a3_**2)**_a7_)**((_a3_*_a4_**2*_a7_**2*cos(_a5_)/_a0_)**x1))**(_a6_**tanh((_a4_ + x1)/_a0_))))))**2/_a2_**2))
<lambdifygenerated-1101>:2: RuntimeWarning: overflow encountered in sinh
  return _a4_ + sinh(tan(log(_a5_*(2*_a5_ + x1 + tan(exp(_a1_ + tan(((_a3_**2)**_a7_)**((_a3_*_a4_**2*_a7_**2*cos(_a5_)/_a0_)**x1))**(_a6_**tanh((_a4_ + x1)/_a0_))))))**2/_a2_**2))
<lambdifygenerated-1102>:2: RuntimeWarning: overflow encountered in sinh
  return _a4_ + sinh(tan(log(_a5_*(2*_a5_ + x1 + tan(exp(_a1_ + tan(((_a3_**2)**_a7_)**((_a3_*_a4_**2*_a7_**2*cos(_a5_)/_a0_)**x1))**(_a6_**tanh((_a4_ + x1)/_a0_))))))**2/_a2_**2))
<lambdifygenerated-1103>:2: RuntimeWarning: overflow encountered in sinh
  return _a4_ + sinh(tan(log(_a5_*(2*_a5_ + x1 + tan(exp(_a1_ + tan(((_a3_**2)**_a7_)**((_a3_*_a4_**2*_a7_**2*cos(_a5_)/_a0_)**x1))**(_a6_**tanh((_a4_ + x1)/_a0_))))))**2/_a2_**2))
<lambdifygenerated-1104>:2: RuntimeWarning: overflow encountered in sinh
  return _a4_ + sinh(tan(log(_a5_*(2*_a5_ + x1 + tan(exp(_a1_ + tan(((_a3_**2)**_a7_)**((_a3_*_a4_**2*_a7_**2*cos(_a5_)/_a0_)**x1))**(_a6_**tanh((_a4_ + x1)/_a0_))))))**2/_a2_**2))
<lambdifygenerated-1105>:2: RuntimeWarning: overflow encountered in sinh
  return _a4_ + sinh(tan(log(_a5_*(2*_a5_ + x1 + tan(exp(_a1_ + tan(((_a3_**2)**_a7_)**((_a3_*_a4_**2*_a7_**2*cos(_a5_)/_a0_)**x1))**(_a6_**tanh((_a4_ + x1)/_a0_))))))**2/_a2_**2))
<lambdifygenerated-1106>:2: RuntimeWarning: overflow encountered in sinh
  return _a4_ + sinh(tan(log(_a5_*(2*_a5_ + x1 + tan(exp(_a1_ + tan(((_a3_**2)**_a7_)**((_a3_*_a4_**2*_a7_**2*cos(_a5_)/_a0_)**x1))**(_a6_**tanh((_a4_ + x1)/_a0_))))))**2/_a2_**2))

         x1         y  rep    ymodel      ybms
3745  0.997  0.987381  0.0  0.981852  0.985589
3746  0.998  0.987426  0.0  0.981862  0.985623
3747  0.998  0.987470  0.0  0.981871  0.985656
3748  0.999  0.987515  0.0  0.981880  0.985690

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.987604  0.0  0.981899  0.985757
3751  1.002  0.987648  0.0  0.981908  0.985791
3752  1.002  0.987692  0.0  0.981917  0.985824
3753  1.003  0.987737  0.0  0.981926  0.985858

3750

<lambdifygenerated-1111>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1
<lambdifygenerated-1112>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1
<lambdifygenerated-1113>:2: RuntimeWarning: invalid value encountered in power
  return cos(x1)**x1
<lambdifygenerated-1114>:2: RuntimeWarning: invalid value encountered in power
  return cos(x1)**x1
<lambdifygenerated-1115>:2: RuntimeWarning: invalid value encountered in power
  return cos(x1**2)**x1
<lambdifygenerated-1116>:2: RuntimeWarning: invalid value encountered in power
  return cos(x1**2)**x1
<lambdifygenerated-1117>:2: RuntimeWarning: invalid value encountered in power
  return cos(2*x1**2)**x1
<lambdifygenerated-1118>:2: RuntimeWarning: invalid value encountered in power
  return cos(2*x1**2)**x1
<lambdifygenerated-1119>:2: RuntimeWarning: invalid value encountered in power
  return cos(3*x1**2)**x1
<lambdifygenerated-1120>:2: RuntimeWarning: invalid value encountered in power
  return cos(3*x1**2)**x1
<lambdifygenerated-1121>:2: RuntimeWarning: invalid value encountered in power
  return cos(x1*(x1**2 + 2*x1))**x1
<lambdifygenerated-1122>:2: RuntimeWarning: invalid value encountered in power
  return cos(x1*(x1**2 + 2*x1))**x1
<lambdifygenerated-1123>:2: RuntimeWarning: invalid value encountered in power
  return cos(x1*(x1*tan(x1) + 2*x1))**x1
<lambdifygenerated-1124>:2: RuntimeWarning: invalid value encountered in power
  return cos(x1*(x1*tan(x1) + 2*x1))**x1
<lambdifygenerated-1125>:2: RuntimeWarning: invalid value encountered in power
  return cos(x1*(x1*tan(x1**2) + 2*x1))**x1
<lambdifygenerated-1126>:2: RuntimeWarning: invalid value encountered in power
  return cos(x1*(x1*tan(x1**2) + 2*x1))**x1
<lambdifygenerated-1127>:2: RuntimeWarning: invalid value encountered in power
  return cos(x1*(x1*tan(2*x1**2) + 2*x1))**x1
<lambdifygenerated-1128>:2: RuntimeWarning: invalid value encountered in power
  return cos(x1*(x1*tan(2*x1**2) + 2*x1))**x1
<lambdifygenerated-1129>:2: RuntimeWarning: invalid value encountered in power
  return cos(x1*(x1*tan(x1*(x1 + tanh(x1))) + 2*x1))**x1
<lambdifygenerated-1130>:2: RuntimeWarning: invalid value encountered in power
  return cos(x1*(x1*tan(x1*(x1 + tanh(x1))) + 2*x1))**x1
<lambdifygenerated-1131>:2: RuntimeWarning: invalid value encountered in power
  return cos(x1*(x1*tan(x1*(x1 + tanh(2*x1))) + 2*x1))**x1
<lambdifygenerated-1132>:2: RuntimeWarning: invalid value encountered in power
  return cos(x1*(x1*tan(x1*(x1 + tanh(2*x1))) + 2*x1))**x1
<lambdifygenerated-1133>:2: RuntimeWarning: invalid value encountered in power
  return cos(x1*(x1*tan(x1*(x1 + tanh(x1**2 + x1))) + 2*x1))**x1
<lambdifygenerated-1134>:2: RuntimeWarning: invalid value encountered in power
  return cos(x1*(x1*tan(x1*(x1 + tanh(x1**2 + x1))) + 2*x1))**x1
<lambdifygenerated-1135>:2: RuntimeWarning: invalid value encountered in power
  return cos(x1*(x1*tan(x1*(x1 + tanh(_a6_*x1 + x1))) + 2*x1))**x1
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-1136>:2: RuntimeWarning: invalid value encountered in power
  return cos(x1*(x1*tan(x1*(x1 + tanh(_a6_*x1 + x1))) + 2*x1))**x1
<lambdifygenerated-1137>:2: RuntimeWarning: invalid value encountered in power
  return cos(x1*(x1*tan(x1*(x1 + tanh(_a6_*tanh(x1) + x1))) + 2*x1))**x1
<lambdifygenerated-1138>:2: RuntimeWarning: invalid value encountered in power
  return cos(x1*(x1*tan(x1*(x1 + tanh(_a6_*tanh(x1) + x1))) + 2*x1))**x1
<lambdifygenerated-1139>:2: RuntimeWarning: invalid value encountered in power
  return cos(x1*(x1*tan(x1*(x1 + tanh(_a6_*tanh(2*x1) + x1))) + 2*x1))**x1
<lambdifygenerated-1140>:2: RuntimeWarning: invalid value encountered in power
  return cos(x1*(x1*tan(x1*(x1 + tanh(_a6_*tanh(2*x1) + x1))) + 2*x1))**x1
<lambdifygenerated-1141>:2: RuntimeWarning: invalid value encountered in power
  return cos(x1*(x1*tan(x1*(x1 + tanh(_a6_*tanh(2*x1) + x1))) + 2*x1))**x1
<lambdifygenerated-1142>:2: RuntimeWarning: invalid value encountered in power
  return cos(x1*(x1*tan(x1*(x1 + tanh(_a6_*tanh(2*x1) + x1))) + 2*x1))**x1
<lambdifygenerated-1143>:2: RuntimeWarning: invalid value encountered in power
  return cos(x1*(x1*tan(x1*(x1 + tanh(_a6_*tanh(_a0_ + x1) + x1))) + 2*x1))**x1
<lambdifygenerated-1144>:2: RuntimeWarning: invalid value encountered in power
  return cos(x1*(x1*tan(x1*(x1 + tanh(_a6_*tanh(_a0_ + x1) + x1))) + 2*x1))**x1
<lambdifygenerated-1145>:2: RuntimeWarning: invalid value encountered in power
  return cos(x1*(x1*tan(x1*(x1 + tanh(_a6_*tanh(_a0_ + x1) + x1**2))) + 2*x1))**x1
<lambdifygenerated-1146>:2: RuntimeWarning: invalid value encountered in power
  return cos(x1*(x1*tan(x1*(x1 + tanh(_a6_*tanh(_a0_ + x1) + x1**2))) + 2*x1))**x1
<lambdifygenerated-1147>:2: RuntimeWarning: invalid value encountered in power
  return cos(x1*(x1*tan(x1*(x1 + tanh(_a1_*x1 + _a6_*tanh(_a0_ + x1)))) + 2*x1))**x1
<lambdifygenerated-1148>:2: RuntimeWarning: invalid value encountered in power
  return cos(x1*(x1*tan(x1*(x1 + tanh(_a1_*x1 + _a6_*tanh(_a0_ + x1)))) + 2*x1))**x1
<lambdifygenerated-1149>:2: RuntimeWarning: invalid value encountered in power
  return cos(x1*(x1*tan(x1*(x1 + tanh(_a1_*x1**2 + _a6_*tanh(_a0_ + x1)))) + 2*x1))**x1
<lambdifygenerated-1150>:2: RuntimeWarning: invalid value encountered in power
  return cos(x1*(x1*tan(x1*(x1 + tanh(_a1_*x1**2 + _a6_*tanh(_a0_ + x1)))) + 2*x1))**x1
<lambdifygenerated-1151>:2: RuntimeWarning: invalid value encountered in power
  return cos(x1*(x1*tan(x1*(x1 + tanh(_a1_*x1*sinh(x1) + _a6_*tanh(_a0_ + x1)))) + 2*x1))**x1
<lambdifygenerated-1152>:2: RuntimeWarning: invalid value encountered in power
  return cos(x1*(x1*tan(x1*(x1 + tanh(_a1_*x1*sinh(x1) + _a6_*tanh(_a0_ + x1)))) + 2*x1))**x1
<lambdifygenerated-1153>:2: RuntimeWarning: invalid value encountered in power
  return cos(x1*(x1*tan(x1*(x1 + tanh(_a1_*x1*sinh(x1) + _a6_*tanh(_a0_ + x1)))) + 2*x1))**x1
<lambdifygenerated-1154>:2: RuntimeWarning: invalid value encountered in power
  return cos(x1*(x1*tan(x1*(x1 + tanh(_a1_*x1*sinh(x1) + _a6_*tanh(_a0_ + x1)))) + 2*x1))**x1
<lambdifygenerated-1155>:2: RuntimeWarning: invalid value encountered in power
  return cos(x1*(x1*tan(x1*(x1 + tanh(_a1_*sinh(x1)**2 + _a6_*tanh(_a0_ + x1)))) + 2*x1))**x1
<lambdifygenerated-1156>:2: RuntimeWarning: invalid value encountered in power
  return cos(x1*(x1*tan(x1*(x1 + tanh(_a1_*sinh(x1)**2 + _a6_*tanh(_a0_ + x1)))) + 2*x1))**x1
<lambdifygenerated-1157>:2: RuntimeWarning: invalid value encountered in power
  return cos(x1*(x1*tan(x1*(x1 + tanh(_a1_*sinh(x1)**2 + _a6_*tanh(_a0_ + x1)))) + 2*x1))**x1
<lambdifygenerated-1158>:2: RuntimeWarning: invalid value encountered in power
  return cos(x1*(x1*tan(x1*(x1 + tanh(_a1_*sinh(x1)**2 + _a6_*tanh(_a0_ + x1)))) + 2*x1))**x1
<lambdifygenerated-1159>:2: RuntimeWarning: invalid value encountered in log
  return cos(x1*(x1*tan(x1*(log(x1) + tanh(_a1_*sinh(x1)**2 + _a6_*tanh(_a0_ + x1)))) + 2*x1))**x1
<lambdifygenerated-1159>:2: RuntimeWarning: invalid value encountered in power
  return cos(x1*(x1*tan(x1*(log(x1) + tanh(_a1_*sinh(x1)**2 + _a6_*tanh(_a0_ + x1)))) + 2*x1))**x1
<lambdifygenerated-1160>:2: RuntimeWarning: invalid value encountered in log
  return cos(x1*(x1*tan(x1*(log(x1) + tanh(_a1_*sinh(x1)**2 + _a6_*tanh(_a0_ + x1)))) + 2*x1))**x1
<lambdifygenerated-1160>:2: RuntimeWarning: invalid value encountered in power
  return cos(x1*(x1*tan(x1*(log(x1) + tanh(_a1_*sinh(x1)**2 + _a6_*tanh(_a0_ + x1)))) + 2*x1))**x1
<lambdifygenerated-1161>:2: RuntimeWarning: invalid value encountered in power
  return cos(x1*(x1*tan(x1*(log(x1**x1) + tanh(_a1_*sinh(x1)**2 + _a6_*tanh(_a0_ + x1)))) + 2*x1))**x1
<lambdifygenerated-1162>:2: RuntimeWarning: invalid value encountered in power
  return cos(x1*(x1*tan(x1*(log(x1**x1) + tanh(_a1_*sinh(x1)**2 + _a6_*tanh(_a0_ + x1)))) + 2*x1))**x1
<lambdifygenerated-1163>:2: RuntimeWarning: invalid value encountered in power
  return cos(x1*(x1*tan(x1*(log((x1**2)**x1) + tanh(_a1_*sinh(x1)**2 + _a6_*tanh(_a0_ + x1)))) + 2*x1))**x1
<lambdifygenerated-1164>:2: RuntimeWarning: invalid value encountered in power
  return cos(x1*(x1*tan(x1*(log((x1**2)**x1) + tanh(_a1_*sinh(x1)**2 + _a6_*tanh(_a0_ + x1)))) + 2*x1))**x1
<lambdifygenerated-1165>:2: RuntimeWarning: invalid value encountered in power
  return cos(x1*(x1*tan(x1*(log((4*x1**2)**x1) + tanh(_a1_*sinh(x1)**2 + _a6_*tanh(_a0_ + x1)))) + 2*x1))**x1
<lambdifygenerated-1166>:2: RuntimeWarning: invalid value encountered in power
  return cos(x1*(x1*tan(x1*(log((4*x1**2)**x1) + tanh(_a1_*sinh(x1)**2 + _a6_*tanh(_a0_ + x1)))) + 2*x1))**x1
<lambdifygenerated-1167>:2: RuntimeWarning: invalid value encountered in power
  return cos(x1*(x1*tan(x1*(log(((x1**2 + x1)**2)**x1) + tanh(_a1_*sinh(x1)**2 + _a6_*tanh(_a0_ + x1)))) + 2*x1))**x1
<lambdifygenerated-1168>:2: RuntimeWarning: invalid value encountered in power
  return cos(x1*(x1*tan(x1*(log(((x1**2 + x1)**2)**x1) + tanh(_a1_*sinh(x1)**2 + _a6_*tanh(_a0_ + x1)))) + 2*x1))**x1
<lambdifygenerated-1169>:2: RuntimeWarning: invalid value encountered in power
  return cos(x1*(x1*tan(x1*(log(((x1**3 + x1)**2)**x1) + tanh(_a1_*sinh(x1)**2 + _a6_*tanh(_a0_ + x1)))) + 2*x1))**x1
<lambdifygenerated-1170>:2: RuntimeWarning: invalid value encountered in power
  return cos(x1*(x1*tan(x1*(log(((x1**3 + x1)**2)**x1) + tanh(_a1_*sinh(x1)**2 + _a6_*tanh(_a0_ + x1)))) + 2*x1))**x1
<lambdifygenerated-1171>:2: RuntimeWarning: invalid value encountered in power
  return cos(x1*(x1*tan(x1*(log(((_a3_*x1**2 + x1)**2)**x1) + tanh(_a1_*sinh(x1)**2 + _a6_*tanh(_a0_ + x1)))) + 2*x1))**x1
<lambdifygenerated-1172>:2: RuntimeWarning: invalid value encountered in power
  return cos(x1*(x1*tan(x1*(log(((_a3_*x1**2 + x1)**2)**x1) + tanh(_a1_*sinh(x1)**2 + _a6_*tanh(_a0_ + x1)))) + 2*x1))**x1
<lambdifygenerated-1173>:2: RuntimeWarning: invalid value encountered in power
  return cos(x1*(x1*tan(x1*(log(((_a3_*_a5_*x1 + x1)**2)**x1) + tanh(_a1_*sinh(x1)**2 + _a6_*tanh(_a0_ + x1)))) + 2*x1))**x1
<lambdifygenerated-1174>:2: RuntimeWarning: invalid value encountered in power
  return cos(x1*(x1*tan(x1*(log(((_a3_*_a5_*x1 + x1)**2)**x1) + tanh(_a1_*sinh(x1)**2 + _a6_*tanh(_a0_ + x1)))) + 2*x1))**x1
<lambdifygenerated-1175>:2: RuntimeWarning: invalid value encountered in power
  return cos(x1*(x1*tan(x1*(log(((2*_a3_*_a5_*x1 + x1)**2)**x1) + tanh(_a1_*sinh(x1)**2 + _a6_*tanh(_a0_ + x1)))) + 2*x1))**x1
<lambdifygenerated-1176>:2: RuntimeWarning: invalid value encountered in power
  return cos(x1*(x1*tan(x1*(log(((2*_a3_*_a5_*x1 + x1)**2)**x1) + tanh(_a1_*sinh(x1)**2 + _a6_*tanh(_a0_ + x1)))) + 2*x1))**x1
<lambdifygenerated-1177>:2: RuntimeWarning: invalid value encountered in power
  return cos(x1*(x1*tan(x1*(log(((2*_a3_*_a5_*x1 + x1)**2)**x1) + tanh(_a1_*sinh(x1)**2 + _a6_*tanh(_a0_ + x1)))) + 2*x1))**x1
<lambdifygenerated-1178>:2: RuntimeWarning: invalid value encountered in power
  return cos(x1*(x1*tan(x1*(log(((2*_a3_*_a5_*x1 + x1)**2)**x1) + tanh(_a1_*sinh(x1)**2 + _a6_*tanh(_a0_ + x1)))) + 2*x1))**x1
<lambdifygenerated-1179>:2: RuntimeWarning: invalid value encountered in power
  return cos(x1*(x1*tan(x1*(log(((_a3_*_a5_*(_a3_ + x1) + x1)**2)**x1) + tanh(_a1_*sinh(x1)**2 + _a6_*tanh(_a0_ + x1)))) + 2*x1))**x1
<lambdifygenerated-1180>:2: RuntimeWarning: invalid value encountered in power
  return cos(x1*(x1*tan(x1*(log(((_a3_*_a5_*(_a3_ + x1) + x1)**2)**x1) + tanh(_a1_*sinh(x1)**2 + _a6_*tanh(_a0_ + x1)))) + 2*x1))**x1
<lambdifygenerated-1181>:2: RuntimeWarning: invalid value encountered in power
  return cos(x1*(x1*tan(x1*(log(((_a1_ + _a3_*_a5_*(_a3_ + x1))**2)**x1) + tanh(_a1_*sinh(x1)**2 + _a6_*tanh(_a0_ + x1)))) + 2*x1))**x1
<lambdifygenerated-1182>:2: RuntimeWarning: invalid value encountered in power
  return cos(x1*(x1*tan(x1*(log(((_a1_ + _a3_*_a5_*(_a3_ + x1))**2)**x1) + tanh(_a1_*sinh(x1)**2 + _a6_*tanh(_a0_ + x1)))) + 2*x1))**x1
<lambdifygenerated-1183>:2: RuntimeWarning: invalid value encountered in power
  return cos(x1*(x1*tan(x1*(log(((_a1_ + _a3_*_a5_*(_a3_ + x1))**2)**_a2_) + tanh(_a1_*sinh(x1)**2 + _a6_*tanh(_a0_ + x1)))) + 2*x1))**x1
<lambdifygenerated-1184>:2: RuntimeWarning: invalid value encountered in power
  return cos(x1*(x1*tan(x1*(log(((_a1_ + _a3_*_a5_*(_a3_ + x1))**2)**_a2_) + tanh(_a1_*sinh(x1)**2 + _a6_*tanh(_a0_ + x1)))) + 2*x1))**x1
<lambdifygenerated-1185>:2: RuntimeWarning: invalid value encountered in power
  return cos(x1*(x1*tan(2*x1*(log(((_a1_ + _a3_*_a5_*(_a3_ + x1))**2)**_a2_) + tanh(_a1_*sinh(x1)**2 + _a6_*tanh(_a0_ + x1)))) + 2*x1))**x1
<lambdifygenerated-1186>:2: RuntimeWarning: invalid value encountered in power
  return cos(x1*(x1*tan(2*x1*(log(((_a1_ + _a3_*_a5_*(_a3_ + x1))**2)**_a2_) + tanh(_a1_*sinh(x1)**2 + _a6_*tanh(_a0_ + x1)))) + 2*x1))**x1
<lambdifygenerated-1187>:2: RuntimeWarning: invalid value encountered in power
  return cos(x1*(x1*tan((_a5_ + x1)*(log(((_a1_ + _a3_*_a5_*(_a3_ + x1))**2)**_a2_) + tanh(_a1_*sinh(x1)**2 + _a6_*tanh(_a0_ + x1)))) + 2*x1))**x1
<lambdifygenerated-1188>:2: RuntimeWarning: invalid value encountered in power
  return cos(x1*(x1*tan((_a5_ + x1)*(log(((_a1_ + _a3_*_a5_*(_a3_ + x1))**2)**_a2_) + tanh(_a1_*sinh(x1)**2 + _a6_*tanh(_a0_ + x1)))) + 2*x1))**x1
<lambdifygenerated-1189>:2: RuntimeWarning: invalid value encountered in power
  return cos(x1*(x1*tan((_a5_ + x1**2)*(log(((_a1_ + _a3_*_a5_*(_a3_ + x1))**2)**_a2_) + tanh(_a1_*sinh(x1)**2 + _a6_*tanh(_a0_ + x1)))) + 2*x1))**x1
<lambdifygenerated-1190>:2: RuntimeWarning: invalid value encountered in power
  return cos(x1*(x1*tan((_a5_ + x1**2)*(log(((_a1_ + _a3_*_a5_*(_a3_ + x1))**2)**_a2_) + tanh(_a1_*sinh(x1)**2 + _a6_*tanh(_a0_ + x1)))) + 2*x1))**x1
<lambdifygenerated-1191>:2: RuntimeWarning: invalid value encountered in power
  return cos(x1*(x1*tan((_a5_ + x1**2)*(log(((_a1_ + _a3_*_a5_*(_a3_ + x1))**2)**_a2_) + tanh(_a1_*sinh(x1)**2 + _a6_*tanh(_a0_ + x1)))) + 2*x1))**x1
<lambdifygenerated-1192>:2: RuntimeWarning: invalid value encountered in power
  return cos(x1*(x1*tan((_a5_ + x1**2)*(log(((_a1_ + _a3_*_a5_*(_a3_ + x1))**2)**_a2_) + tanh(_a1_*sinh(x1)**2 + _a6_*tanh(_a0_ + x1)))) + 2*x1))**x1
<lambdifygenerated-1193>:2: RuntimeWarning: invalid value encountered in power
  return cos(x1*(x1*tan((_a4_*x1 + _a5_)*(log(((_a1_ + _a3_*_a5_*(_a3_ + x1))**2)**_a2_) + tanh(_a1_*sinh(x1)**2 + _a6_*tanh(_a0_ + x1)))) + 2*x1))**x1
<lambdifygenerated-1194>:2: RuntimeWarning: invalid value encountered in power
  return cos(x1*(x1*tan((_a4_*x1 + _a5_)*(log(((_a1_ + _a3_*_a5_*(_a3_ + x1))**2)**_a2_) + tanh(_a1_*sinh(x1)**2 + _a6_*tanh(_a0_ + x1)))) + 2*x1))**x1
<lambdifygenerated-1195>:2: RuntimeWarning: invalid value encountered in power
  return cos(x1*(_a3_*tan((_a4_*x1 + _a5_)*(log(((_a1_ + _a3_*_a5_*(_a3_ + x1))**2)**_a2_) + tanh(_a1_*sinh(x1)**2 + _a6_*tanh(_a0_ + x1)))) + 2*x1))**x1
<lambdifygenerated-1196>:2: RuntimeWarning: invalid value encountered in power
  return cos(x1*(_a3_*tan((_a4_*x1 + _a5_)*(log(((_a1_ + _a3_*_a5_*(_a3_ + x1))**2)**_a2_) + tanh(_a1_*sinh(x1)**2 + _a6_*tanh(_a0_ + x1)))) + 2*x1))**x1
<lambdifygenerated-1197>:2: RuntimeWarning: invalid value encountered in power
  return cos(x1*(_a3_*tan((_a4_*x1 + _a5_)*(log(((_a1_ + _a3_*_a5_*(_a3_ + x1))**2)**_a2_) + tanh(_a1_*sinh(x1)**2 + _a6_*tanh(_a0_ + x1)))) + 2*x1))**x1
<lambdifygenerated-1198>:2: RuntimeWarning: invalid value encountered in power
  return cos(x1*(_a3_*tan((_a4_*x1 + _a5_)*(log(((_a1_ + _a3_*_a5_*(_a3_ + x1))**2)**_a2_) + tanh(_a1_*sinh(x1)**2 + _a6_*tanh(_a0_ + x1)))) + 2*x1))**x1
<lambdifygenerated-1199>:2: RuntimeWarning: invalid value encountered in power
  return cos(x1*(_a3_*tan((_a4_*x1 + _a5_)*(log(((_a1_ + _a3_*_a5_*(_a3_ + x1))**2)**_a2_) + tanh(_a1_*sinh(x1)**2 + _a6_*tanh(_a0_ + x1)))) + _a3_ + x1))**x1
<lambdifygenerated-1200>:2: RuntimeWarning: invalid value encountered in power
  return cos(x1*(_a3_*tan((_a4_*x1 + _a5_)*(log(((_a1_ + _a3_*_a5_*(_a3_ + x1))**2)**_a2_) + tanh(_a1_*sinh(x1)**2 + _a6_*tanh(_a0_ + x1)))) + _a3_ + x1))**x1
<lambdifygenerated-1201>:2: RuntimeWarning: invalid value encountered in power
  return cos(_a3_*(_a3_*tan((_a4_*x1 + _a5_)*(log(((_a1_ + _a3_*_a5_*(_a3_ + x1))**2)**_a2_) + tanh(_a1_*sinh(x1)**2 + _a6_*tanh(_a0_ + x1)))) + _a3_ + x1))**x1
<lambdifygenerated-1202>:2: RuntimeWarning: invalid value encountered in power
  return cos(_a3_*(_a3_*tan((_a4_*x1 + _a5_)*(log(((_a1_ + _a3_*_a5_*(_a3_ + x1))**2)**_a2_) + tanh(_a1_*sinh(x1)**2 + _a6_*tanh(_a0_ + x1)))) + _a3_ + x1))**x1
<lambdifygenerated-1203>:2: RuntimeWarning: invalid value encountered in power
  return cos(_a3_*(_a3_*tan((_a4_*x1 + _a5_)*(log(((_a1_ + _a3_*_a5_*(_a3_ + x1))**2)**_a2_) + tanh(_a1_*sinh(x1)**2 + _a6_*tanh(_a0_ + x1)))) + _a3_ + x1))**_a7_
<lambdifygenerated-1207>:2: RuntimeWarning: invalid value encountered in power
  return cos(_a3_*(_a3_*tan((_a4_*x1 + _a5_)*(log(((_a1_ + _a3_*_a5_*(_a3_ + x1))**2)**_a2_) + tanh(_a1_*sinh(x1)**2 + _a6_*tanh(_a0_ + x1)))) + _a3_ + x1))**_a7_

interpolation

<lambdifygenerated-1209>:2: RuntimeWarning: invalid value encountered in power
  return cos(_a3_*(_a3_*tan((_a4_*x1 + _a5_)*(log(((_a1_ + _a3_*_a5_*(_a3_ + x1))**2)**_a2_) + tanh(_a1_*sinh(x1)**2 + _a6_*tanh(_a0_ + x1)))) + _a3_ + x1))**_a7_

         x1         y  rep    ymodel      ybms
3745  0.997  0.053138  1.0  0.056325  0.052101
3746  0.998  0.053057  1.0  0.056284  0.051996
3747  0.998  0.052975  1.0  0.056243  0.051891
3748  0.999  0.052894  1.0  0.056203  0.051786

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.052733  1.0  0.056123  0.051575
3751  1.002  0.052652  1.0  0.056083  0.051470
3752  1.002  0.052571  1.0  0.056044  0.051365
3753  1.003  0.052491  1.0  0.056005  0.051259

3750

<lambdifygenerated-1245>:2: RuntimeWarning: invalid value encountered in power
  return x1*abs(x1*(x1*sin(x1*tan(sinh(x1*(x1*x1**x1 - x1))) - x1) - x1) - 2*x1)
<lambdifygenerated-1246>:2: RuntimeWarning: invalid value encountered in power
  return x1*abs(x1*(x1*sin(x1*tan(sinh(x1*(x1*x1**x1 - x1))) - x1) - x1) - 2*x1)

interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.277484  2.0  0.277532  0.267653
3746  0.998  0.277627  2.0  0.277658  0.267487
3747  0.998  0.277770  2.0  0.277782  0.267315
3748  0.999  0.277912  2.0  0.277905  0.267140

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.278193  2.0  0.278148  0.266775
3751  1.002  0.278333  2.0  0.278268  0.266585
3752  1.002  0.278471  2.0  0.278387  0.266391
3753  1.003  0.278610  2.0  0.278504  0.266193

3750

<lambdifygenerated-1327>:2: RuntimeWarning: invalid value encountered in sqrt
  return x1*cos(sqrt(x1) + x1)
<lambdifygenerated-1328>:2: RuntimeWarning: invalid value encountered in sqrt
  return x1*cos(sqrt(x1) + x1)
<lambdifygenerated-1329>:2: RuntimeWarning: invalid value encountered in power
  return x1*cos(x1 + sqrt(x1**x1))
<lambdifygenerated-1330>:2: RuntimeWarning: invalid value encountered in power
  return x1*cos(x1 + sqrt(x1**x1))
<lambdifygenerated-1331>:2: RuntimeWarning: invalid value encountered in power
  return x1*cos(x1 + sqrt(sin(x1)**x1))
<lambdifygenerated-1332>:2: RuntimeWarning: invalid value encountered in power
  return x1*cos(x1 + sqrt(sin(x1)**x1))
<lambdifygenerated-1333>:2: RuntimeWarning: invalid value encountered in power
  return x1*cos(x1 + sqrt(sin(tanh(x1))**x1))
<lambdifygenerated-1334>:2: RuntimeWarning: invalid value encountered in power
  return x1*cos(x1 + sqrt(sin(tanh(x1))**x1))
<lambdifygenerated-1337>:2: RuntimeWarning: invalid value encountered in power
  return x1*cos(x1 + sqrt(sin(tanh(x1**(2*x1)))**x1))
<lambdifygenerated-1338>:2: RuntimeWarning: invalid value encountered in power
  return x1*cos(x1 + sqrt(sin(tanh(x1**(2*x1)))**x1))
<lambdifygenerated-1341>:2: RuntimeWarning: invalid value encountered in power
  return x1*cos(x1 + sqrt(sin(tanh((x1**(-1.0))**(2*x1)))**x1))
<lambdifygenerated-1342>:2: RuntimeWarning: invalid value encountered in power
  return x1*cos(x1 + sqrt(sin(tanh((x1**(-1.0))**(2*x1)))**x1))
<lambdifygenerated-1343>:2: RuntimeWarning: invalid value encountered in power
  return x1*cos(x1 + sqrt(sin(tanh((2/x1)**(2*x1)))**x1))
<lambdifygenerated-1344>:2: RuntimeWarning: invalid value encountered in power
  return x1*cos(x1 + sqrt(sin(tanh((2/x1)**(2*x1)))**x1))
<lambdifygenerated-1345>:2: RuntimeWarning: invalid value encountered in power
  return x1*cos(x1 + sqrt(sin(tanh(((x1 + sin(x1))/x1**2)**(2*x1)))**x1))
<lambdifygenerated-1346>:2: RuntimeWarning: invalid value encountered in power
  return x1*cos(x1 + sqrt(sin(tanh(((x1 + sin(x1))/x1**2)**(2*x1)))**x1))
<lambdifygenerated-1347>:2: RuntimeWarning: invalid value encountered in power
  return x1*cos(x1 + sqrt(sin(tanh(((x1 + sin(x1**x1))/x1**2)**(2*x1)))**x1))
<lambdifygenerated-1348>:2: RuntimeWarning: invalid value encountered in power
  return x1*cos(x1 + sqrt(sin(tanh(((x1 + sin(x1**x1))/x1**2)**(2*x1)))**x1))
<lambdifygenerated-1349>:2: RuntimeWarning: invalid value encountered in power
  return x1*cos(x1 + sqrt(sin(tanh(((x1 + sin((x1**2)**x1))/x1**2)**(2*x1)))**x1))
<lambdifygenerated-1350>:2: RuntimeWarning: invalid value encountered in power
  return x1*cos(x1 + sqrt(sin(tanh(((x1 + sin((x1**2)**x1))/x1**2)**(2*x1)))**x1))
<lambdifygenerated-1351>:2: RuntimeWarning: invalid value encountered in power
  return x1*cos(x1 + sqrt(sin(tanh(((x1 + sin((x1**4)**x1))/x1**2)**(2*x1)))**x1))
<lambdifygenerated-1352>:2: RuntimeWarning: invalid value encountered in power
  return x1*cos(x1 + sqrt(sin(tanh(((x1 + sin((x1**4)**x1))/x1**2)**(2*x1)))**x1))
<lambdifygenerated-1353>:2: RuntimeWarning: invalid value encountered in power
  return x1*cos(x1 + sqrt(sin(tanh(((x1 + sin((4*x1**4)**x1))/x1**2)**(2*x1)))**x1))
<lambdifygenerated-1354>:2: RuntimeWarning: invalid value encountered in power
  return x1*cos(x1 + sqrt(sin(tanh(((x1 + sin((4*x1**4)**x1))/x1**2)**(2*x1)))**x1))
<lambdifygenerated-1355>:2: RuntimeWarning: invalid value encountered in power
  return x1*cos(x1 + sqrt(sin(tanh(((x1 + sin((x1**2*(x1 + x1**x1)**2)**x1))/x1**2)**(2*x1)))**x1))
<lambdifygenerated-1356>:2: RuntimeWarning: invalid value encountered in power
  return x1*cos(x1 + sqrt(sin(tanh(((x1 + sin((x1**2*(x1 + x1**x1)**2)**x1))/x1**2)**(2*x1)))**x1))
<lambdifygenerated-1357>:2: RuntimeWarning: invalid value encountered in power
  return x1*cos(x1 + sqrt(sin(tanh(((x1 + sin((x1**2*(x1 + (x1**2)**x1)**2)**x1))/x1**2)**(2*x1)))**x1))
<lambdifygenerated-1358>:2: RuntimeWarning: invalid value encountered in power
  return x1*cos(x1 + sqrt(sin(tanh(((x1 + sin((x1**2*(x1 + (x1**2)**x1)**2)**x1))/x1**2)**(2*x1)))**x1))
<lambdifygenerated-1359>:2: RuntimeWarning: invalid value encountered in power
  return x1*cos(x1 + sqrt(sin(tanh(((x1 + sin((x1**2*(x1 + (_a0_**2)**x1)**2)**x1))/x1**2)**(2*x1)))**x1))
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-1360>:2: RuntimeWarning: invalid value encountered in power
  return x1*cos(x1 + sqrt(sin(tanh(((x1 + sin((x1**2*(x1 + (_a0_**2)**x1)**2)**x1))/x1**2)**(2*x1)))**x1))
<lambdifygenerated-1361>:2: RuntimeWarning: invalid value encountered in power
  return x1*cos(x1 + sqrt(sin(tanh(((x1 + sin((x1**2*(x1 + (_a0_**2)**(x1**2))**2)**x1))/x1**2)**(2*x1)))**x1))
<lambdifygenerated-1362>:2: RuntimeWarning: invalid value encountered in power
  return x1*cos(x1 + sqrt(sin(tanh(((x1 + sin((x1**2*(x1 + (_a0_**2)**(x1**2))**2)**x1))/x1**2)**(2*x1)))**x1))
<lambdifygenerated-1363>:2: RuntimeWarning: invalid value encountered in power
  return x1*cos(x1 + sqrt(sin(tanh(((x1 + sin((x1**2*(x1 + (_a0_**2)**(x1*tanh(x1)))**2)**x1))/x1**2)**(2*x1)))**x1))
<lambdifygenerated-1364>:2: RuntimeWarning: invalid value encountered in power
  return x1*cos(x1 + sqrt(sin(tanh(((x1 + sin((x1**2*(x1 + (_a0_**2)**(x1*tanh(x1)))**2)**x1))/x1**2)**(2*x1)))**x1))
<lambdifygenerated-1365>:2: RuntimeWarning: invalid value encountered in power
  return x1*cos(x1 + sqrt(sin(tanh(((x1 + sin((x1**2*(x1 + (_a0_**2)**(x1*tanh(tanh(x1))))**2)**x1))/x1**2)**(2*x1)))**x1))
<lambdifygenerated-1366>:2: RuntimeWarning: invalid value encountered in power
  return x1*cos(x1 + sqrt(sin(tanh(((x1 + sin((x1**2*(x1 + (_a0_**2)**(x1*tanh(tanh(x1))))**2)**x1))/x1**2)**(2*x1)))**x1))
<lambdifygenerated-1367>:2: RuntimeWarning: invalid value encountered in power
  return x1*cos(x1 + sqrt(sin(tanh(((x1 + sin((x1**2*(x1 + (_a0_**2)**(x1*tanh(tanh(x1))))**2)**x1))/x1**2)**(2*x1)))**x1))
<lambdifygenerated-1368>:2: RuntimeWarning: invalid value encountered in power
  return x1*cos(x1 + sqrt(sin(tanh(((x1 + sin((x1**2*(x1 + (_a0_**2)**(x1*tanh(tanh(x1))))**2)**x1))/x1**2)**(2*x1)))**x1))
<lambdifygenerated-1369>:2: RuntimeWarning: invalid value encountered in power
  return x1*cos(x1 + sqrt(sin(tanh(((x1 + sin((x1**2*(x1 + (_a0_**2)**(2*x1*tanh(tanh(x1))))**2)**x1))/x1**2)**(2*x1)))**x1))
<lambdifygenerated-1370>:2: RuntimeWarning: invalid value encountered in power
  return x1*cos(x1 + sqrt(sin(tanh(((x1 + sin((x1**2*(x1 + (_a0_**2)**(2*x1*tanh(tanh(x1))))**2)**x1))/x1**2)**(2*x1)))**x1))
<lambdifygenerated-1371>:2: RuntimeWarning: invalid value encountered in power
  return x1*cos(x1 + sqrt(sin(tanh(((x1 + sin((x1**2*(x1 + (_a0_**2)**(2*x1*tanh(tanh(x1))))**2)**x1))/x1**2)**(2*x1)))**x1))
<lambdifygenerated-1372>:2: RuntimeWarning: invalid value encountered in power
  return x1*cos(x1 + sqrt(sin(tanh(((x1 + sin((x1**2*(x1 + (_a0_**2)**(2*x1*tanh(tanh(x1))))**2)**x1))/x1**2)**(2*x1)))**x1))
<lambdifygenerated-1373>:2: RuntimeWarning: invalid value encountered in power
  return x1*cos(x1 + sqrt(sin(tanh(((x1 + sin((x1**2*(x1 + (_a0_**2)**((_a5_ + x1)*tanh(tanh(x1))))**2)**x1))/x1**2)**(2*x1)))**x1))
<lambdifygenerated-1374>:2: RuntimeWarning: invalid value encountered in power
  return x1*cos(x1 + sqrt(sin(tanh(((x1 + sin((x1**2*(x1 + (_a0_**2)**((_a5_ + x1)*tanh(tanh(x1))))**2)**x1))/x1**2)**(2*x1)))**x1))
<lambdifygenerated-1375>:2: RuntimeWarning: invalid value encountered in power
  return x1*cos(x1 + sqrt(sin(tanh(((x1 + sin((x1**2*(_a6_ + (_a0_**2)**((_a5_ + x1)*tanh(tanh(x1))))**2)**x1))/x1**2)**(2*x1)))**x1))
<lambdifygenerated-1376>:2: RuntimeWarning: invalid value encountered in power
  return x1*cos(x1 + sqrt(sin(tanh(((x1 + sin((x1**2*(_a6_ + (_a0_**2)**((_a5_ + x1)*tanh(tanh(x1))))**2)**x1))/x1**2)**(2*x1)))**x1))
<lambdifygenerated-1377>:2: RuntimeWarning: invalid value encountered in power
  return x1*cos(x1 + sqrt(sin(tanh(((x1 + sin((x1**4*(_a6_ + (_a0_**2)**((_a5_ + x1)*tanh(tanh(x1))))**2)**x1))/x1**2)**(2*x1)))**x1))
<lambdifygenerated-1378>:2: RuntimeWarning: invalid value encountered in power
  return x1*cos(x1 + sqrt(sin(tanh(((x1 + sin((x1**4*(_a6_ + (_a0_**2)**((_a5_ + x1)*tanh(tanh(x1))))**2)**x1))/x1**2)**(2*x1)))**x1))
<lambdifygenerated-1379>:2: RuntimeWarning: invalid value encountered in power
  return x1*cos(x1 + sqrt(sin(tanh(((x1 + sin((_a3_**2*x1**2*(_a6_ + (_a0_**2)**((_a5_ + x1)*tanh(tanh(x1))))**2)**x1))/x1**2)**(2*x1)))**x1))
<lambdifygenerated-1380>:2: RuntimeWarning: invalid value encountered in power
  return x1*cos(x1 + sqrt(sin(tanh(((x1 + sin((_a3_**2*x1**2*(_a6_ + (_a0_**2)**((_a5_ + x1)*tanh(tanh(x1))))**2)**x1))/x1**2)**(2*x1)))**x1))
<lambdifygenerated-1381>:2: RuntimeWarning: invalid value encountered in power
  return x1*cos(x1 + sqrt(sin(tanh(((x1 + sin((4*_a3_**2*x1**2*(_a6_ + (_a0_**2)**((_a5_ + x1)*tanh(tanh(x1))))**2)**x1))/x1**2)**(2*x1)))**x1))
<lambdifygenerated-1382>:2: RuntimeWarning: invalid value encountered in power
  return x1*cos(x1 + sqrt(sin(tanh(((x1 + sin((4*_a3_**2*x1**2*(_a6_ + (_a0_**2)**((_a5_ + x1)*tanh(tanh(x1))))**2)**x1))/x1**2)**(2*x1)))**x1))
<lambdifygenerated-1383>:2: RuntimeWarning: invalid value encountered in power
  return x1*cos(x1 + sqrt(sin(tanh(((x1 + sin((4*_a3_**2*x1**2*(_a6_ + (_a0_**2)**((_a5_ + x1)*tanh(tanh(x1))))**2)**x1))/x1**2)**(2*x1)))**x1))
<lambdifygenerated-1384>:2: RuntimeWarning: invalid value encountered in power
  return x1*cos(x1 + sqrt(sin(tanh(((x1 + sin((4*_a3_**2*x1**2*(_a6_ + (_a0_**2)**((_a5_ + x1)*tanh(tanh(x1))))**2)**x1))/x1**2)**(2*x1)))**x1))
<lambdifygenerated-1385>:2: RuntimeWarning: invalid value encountered in power
  return x1*cos(x1 + sqrt(sin(tanh(((x1 + sin((_a3_**2*(_a1_ + x1)**2*(_a6_ + (_a0_**2)**((_a5_ + x1)*tanh(tanh(x1))))**2)**x1))/x1**2)**(2*x1)))**x1))
<lambdifygenerated-1386>:2: RuntimeWarning: invalid value encountered in power
  return x1*cos(x1 + sqrt(sin(tanh(((x1 + sin((_a3_**2*(_a1_ + x1)**2*(_a6_ + (_a0_**2)**((_a5_ + x1)*tanh(tanh(x1))))**2)**x1))/x1**2)**(2*x1)))**x1))
<lambdifygenerated-1387>:2: RuntimeWarning: invalid value encountered in power
  return x1*cos(x1 + sqrt(sin(tanh(((x1 + sin((_a3_**2*(_a1_ + x1)**2*(_a6_ + (_a0_**2)**((_a5_ + x1)*tanh(tanh(x1))))**2)**(x1**2)))/x1**2)**(2*x1)))**x1))
<lambdifygenerated-1388>:2: RuntimeWarning: invalid value encountered in power
  return x1*cos(x1 + sqrt(sin(tanh(((x1 + sin((_a3_**2*(_a1_ + x1)**2*(_a6_ + (_a0_**2)**((_a5_ + x1)*tanh(tanh(x1))))**2)**(x1**2)))/x1**2)**(2*x1)))**x1))
<lambdifygenerated-1389>:2: RuntimeWarning: invalid value encountered in power
  return x1*cos(x1 + sqrt(sin(tanh(((x1 + sin((_a3_**2*(_a1_ + x1)**2*(_a6_ + (_a0_**2)**((_a5_ + x1)*tanh(tanh(x1))))**2)**(x1**3)))/x1**2)**(2*x1)))**x1))
<lambdifygenerated-1390>:2: RuntimeWarning: invalid value encountered in power
  return x1*cos(x1 + sqrt(sin(tanh(((x1 + sin((_a3_**2*(_a1_ + x1)**2*(_a6_ + (_a0_**2)**((_a5_ + x1)*tanh(tanh(x1))))**2)**(x1**3)))/x1**2)**(2*x1)))**x1))
<lambdifygenerated-1391>:2: RuntimeWarning: invalid value encountered in power
  return x1*cos(x1 + sqrt(sin(tanh(((x1 + sin((_a3_**2*(_a1_ + x1)**2*(_a6_ + (_a0_**2)**((_a5_ + x1)*tanh(tanh(x1))))**2)**(_a1_**2*x1)))/x1**2)**(2*x1)))**x1))
<lambdifygenerated-1392>:2: RuntimeWarning: invalid value encountered in power
  return x1*cos(x1 + sqrt(sin(tanh(((x1 + sin((_a3_**2*(_a1_ + x1)**2*(_a6_ + (_a0_**2)**((_a5_ + x1)*tanh(tanh(x1))))**2)**(_a1_**2*x1)))/x1**2)**(2*x1)))**x1))
<lambdifygenerated-1393>:2: RuntimeWarning: invalid value encountered in power
  return x1*cos(x1 + sqrt(sin(tanh(((x1 + sin((_a3_**2*(_a1_ + x1)**2*(_a6_ + (_a0_**2)**((_a5_ + x1)*tanh(tanh(x1))))**2)**(_a1_**2*_a6_)))/x1**2)**(2*x1)))**x1))
<lambdifygenerated-1394>:2: RuntimeWarning: invalid value encountered in power
  return x1*cos(x1 + sqrt(sin(tanh(((x1 + sin((_a3_**2*(_a1_ + x1)**2*(_a6_ + (_a0_**2)**((_a5_ + x1)*tanh(tanh(x1))))**2)**(_a1_**2*_a6_)))/x1**2)**(2*x1)))**x1))
<lambdifygenerated-1397>:2: RuntimeWarning: invalid value encountered in power
  return x1*cos(x1 + sqrt(sin(tanh(((_a7_ + sin((_a3_**2*(_a1_ + x1)**2*(_a6_ + (_a0_**2)**((_a5_ + x1)*tanh(tanh(x1))))**2)**(_a1_**2*_a6_)))/(_a4_*x1))**(2*x1)))**x1))
<lambdifygenerated-1398>:2: RuntimeWarning: invalid value encountered in power
  return x1*cos(x1 + sqrt(sin(tanh(((_a7_ + sin((_a3_**2*(_a1_ + x1)**2*(_a6_ + (_a0_**2)**((_a5_ + x1)*tanh(tanh(x1))))**2)**(_a1_**2*_a6_)))/(_a4_*x1))**(2*x1)))**x1))
<lambdifygenerated-1403>:2: RuntimeWarning: invalid value encountered in power
  return x1*cos(x1 + sqrt(sin(tanh(((_a7_ + sin((_a3_**2*(_a1_ + x1)**2*(_a6_ + (_a0_**2)**((_a5_ + x1)*tanh(tanh(x1))))**2)**(_a1_**2*_a6_)))/(_a0_**4*_a4_))**(2*x1)))**x1))
<lambdifygenerated-1405>:2: RuntimeWarning: overflow encountered in power
  return x1*cos(x1 + sqrt(sin(tanh(((_a7_ + sin((_a3_**2*(_a1_ + x1)**2*(_a6_ + (_a0_**2)**((_a5_ + x1)*tanh(tanh(x1))))**2)**(_a1_**2*_a6_)))/(_a0_**4*_a4_))**(2*_a6_)))**x1))
<lambdifygenerated-1405>:2: RuntimeWarning: invalid value encountered in sin
  return x1*cos(x1 + sqrt(sin(tanh(((_a7_ + sin((_a3_**2*(_a1_ + x1)**2*(_a6_ + (_a0_**2)**((_a5_ + x1)*tanh(tanh(x1))))**2)**(_a1_**2*_a6_)))/(_a0_**4*_a4_))**(2*_a6_)))**x1))
<lambdifygenerated-1405>:2: RuntimeWarning: invalid value encountered in power
  return x1*cos(x1 + sqrt(sin(tanh(((_a7_ + sin((_a3_**2*(_a1_ + x1)**2*(_a6_ + (_a0_**2)**((_a5_ + x1)*tanh(tanh(x1))))**2)**(_a1_**2*_a6_)))/(_a0_**4*_a4_))**(2*_a6_)))**x1))

interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.306760  3.0  0.305884  0.308424
3746  0.998  0.307033  3.0  0.306127  0.308747
3747  0.998  0.307306  3.0  0.306369  0.309070
3748  0.999  0.307578  3.0  0.306609  0.309392

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.308120  3.0  0.307087  0.310038
3751  1.002  0.308390  3.0  0.307324  0.310360
3752  1.002  0.308660  3.0  0.307560  0.310682
3753  1.003  0.308928  3.0  0.307794  0.311004

3750

<lambdifygenerated-1431>:2: RuntimeWarning: invalid value encountered in power
  return abs(tan(x1*(x1 + tan(x1**x1))))
<lambdifygenerated-1432>:2: RuntimeWarning: invalid value encountered in power
  return abs(tan(x1*(x1 + tan(x1**x1))))
<lambdifygenerated-1433>:2: RuntimeWarning: invalid value encountered in power
  return abs(tan(x1*(x1 + tan(sin(x1)**x1))))
<lambdifygenerated-1434>:2: RuntimeWarning: invalid value encountered in power
  return abs(tan(x1*(x1 + tan(sin(x1)**x1))))
<lambdifygenerated-1435>:2: RuntimeWarning: invalid value encountered in sqrt
  return abs(tan(x1*(x1 + tan(sin(sqrt(x1))**x1))))
<lambdifygenerated-1436>:2: RuntimeWarning: invalid value encountered in sqrt
  return abs(tan(x1*(x1 + tan(sin(sqrt(x1))**x1))))
<lambdifygenerated-1441>:2: RuntimeWarning: invalid value encountered in sqrt
  return abs(tan(x1*(x1 + tan(sin(sqrt(tanh(x1**2)/x1))**x1))))
<lambdifygenerated-1442>:2: RuntimeWarning: invalid value encountered in sqrt
  return abs(tan(x1*(x1 + tan(sin(sqrt(tanh(x1**2)/x1))**x1))))
<lambdifygenerated-1443>:2: RuntimeWarning: invalid value encountered in power
  return abs(tan(x1*(x1 + tan(sin(sqrt(tanh(x1*x1**x1)/x1))**x1))))
<lambdifygenerated-1444>:2: RuntimeWarning: invalid value encountered in power
  return abs(tan(x1*(x1 + tan(sin(sqrt(tanh(x1*x1**x1)/x1))**x1))))
<lambdifygenerated-1445>:2: RuntimeWarning: invalid value encountered in power
  return abs(tan(x1*(x1 + tan(sin(sqrt(tanh(x1*(2*x1)**x1)/x1))**x1))))
<lambdifygenerated-1446>:2: RuntimeWarning: invalid value encountered in power
  return abs(tan(x1*(x1 + tan(sin(sqrt(tanh(x1*(2*x1)**x1)/x1))**x1))))
<lambdifygenerated-1447>:2: RuntimeWarning: invalid value encountered in power
  return abs(tan(x1*(x1 + tan(sin(sqrt(tanh(x1*(x1**2 + x1)**x1)/x1))**x1))))
<lambdifygenerated-1448>:2: RuntimeWarning: invalid value encountered in power
  return abs(tan(x1*(x1 + tan(sin(sqrt(tanh(x1*(x1**2 + x1)**x1)/x1))**x1))))
<lambdifygenerated-1449>:2: RuntimeWarning: invalid value encountered in power
  return abs(tan(x1*(x1 + tan(sin(sqrt(tanh(x1*(x1*x1**x1 + x1)**x1)/x1))**x1))))
<lambdifygenerated-1450>:2: RuntimeWarning: invalid value encountered in power
  return abs(tan(x1*(x1 + tan(sin(sqrt(tanh(x1*(x1*x1**x1 + x1)**x1)/x1))**x1))))
<lambdifygenerated-1451>:2: RuntimeWarning: invalid value encountered in power
  return abs(tan(x1*(x1 + tan(sin(sqrt(tanh(x1*(x1*tanh(x1)**x1 + x1)**x1)/x1))**x1))))
<lambdifygenerated-1452>:2: RuntimeWarning: invalid value encountered in power
  return abs(tan(x1*(x1 + tan(sin(sqrt(tanh(x1*(x1*tanh(x1)**x1 + x1)**x1)/x1))**x1))))
<lambdifygenerated-1453>:2: RuntimeWarning: invalid value encountered in power
  return abs(tan(x1*(x1 + tan(sin(sqrt(tanh(x1*(x1*tanh(x1**2)**x1 + x1)**x1)/x1))**x1))))
<lambdifygenerated-1454>:2: RuntimeWarning: invalid value encountered in power
  return abs(tan(x1*(x1 + tan(sin(sqrt(tanh(x1*(x1*tanh(x1**2)**x1 + x1)**x1)/x1))**x1))))
<lambdifygenerated-1455>:2: RuntimeWarning: invalid value encountered in power
  return abs(tan(x1*(x1 + tan(sin(sqrt(tanh(x1*(x1*tanh(x1**3)**x1 + x1)**x1)/x1))**x1))))
<lambdifygenerated-1456>:2: RuntimeWarning: invalid value encountered in power
  return abs(tan(x1*(x1 + tan(sin(sqrt(tanh(x1*(x1*tanh(x1**3)**x1 + x1)**x1)/x1))**x1))))
<lambdifygenerated-1457>:2: RuntimeWarning: invalid value encountered in power
  return abs(tan(x1*(x1 + tan(sin(sqrt(tanh(x1*(x1*tanh(_a0_*x1**2)**x1 + x1)**x1)/x1))**x1))))
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-1458>:2: RuntimeWarning: invalid value encountered in power
  return abs(tan(x1*(x1 + tan(sin(sqrt(tanh(x1*(x1*tanh(_a0_*x1**2)**x1 + x1)**x1)/x1))**x1))))
<lambdifygenerated-1459>:2: RuntimeWarning: invalid value encountered in power
  return abs(tan(x1*(x1 + tan(sin(sqrt(tanh(x1*(x1*tanh(_a0_*_a2_*x1)**x1 + x1)**x1)/x1))**x1))))
<lambdifygenerated-1460>:2: RuntimeWarning: invalid value encountered in power
  return abs(tan(x1*(x1 + tan(sin(sqrt(tanh(x1*(x1*tanh(_a0_*_a2_*x1)**x1 + x1)**x1)/x1))**x1))))
<lambdifygenerated-1461>:2: RuntimeWarning: invalid value encountered in power
  return abs(tan(x1*(x1 + tan(sin(sqrt(tanh(x1*(x1*tanh(_a0_*_a2_*x1**x1)**x1 + x1)**x1)/x1))**x1))))
<lambdifygenerated-1462>:2: RuntimeWarning: invalid value encountered in power
  return abs(tan(x1*(x1 + tan(sin(sqrt(tanh(x1*(x1*tanh(_a0_*_a2_*x1**x1)**x1 + x1)**x1)/x1))**x1))))
<lambdifygenerated-1463>:2: RuntimeWarning: invalid value encountered in power
  return abs(tan(x1*(x1 + tan(sin(sqrt(tanh(x1*(x1*tanh(_a0_*_a1_**x1*_a2_)**x1 + x1)**x1)/x1))**x1))))
<lambdifygenerated-1464>:2: RuntimeWarning: invalid value encountered in power
  return abs(tan(x1*(x1 + tan(sin(sqrt(tanh(x1*(x1*tanh(_a0_*_a1_**x1*_a2_)**x1 + x1)**x1)/x1))**x1))))
<lambdifygenerated-1465>:2: RuntimeWarning: invalid value encountered in power
  return abs(tan(x1*(x1 + tan(sin(sqrt(tanh(x1*(x1*tanh(_a0_*_a1_**tanh(x1)*_a2_)**x1 + x1)**x1)/x1))**x1))))
<lambdifygenerated-1466>:2: RuntimeWarning: invalid value encountered in power
  return abs(tan(x1*(x1 + tan(sin(sqrt(tanh(x1*(x1*tanh(_a0_*_a1_**tanh(x1)*_a2_)**x1 + x1)**x1)/x1))**x1))))
<lambdifygenerated-1467>:2: RuntimeWarning: invalid value encountered in power
  return abs(tan(x1*(x1 + tan(sin(sqrt(tanh(x1*(x1*tanh(_a0_*_a1_**tanh(x1)*_a2_)**x1 + x1)**x1)/x1))**x1))))
<lambdifygenerated-1468>:2: RuntimeWarning: invalid value encountered in power
  return abs(tan(x1*(x1 + tan(sin(sqrt(tanh(x1*(x1*tanh(_a0_*_a1_**tanh(x1)*_a2_)**x1 + x1)**x1)/x1))**x1))))
<lambdifygenerated-1469>:2: RuntimeWarning: invalid value encountered in power
  return abs(tan(x1*(x1 + tan(sin(sqrt(tanh(x1*(x1*tanh(_a0_*_a1_**tanh(x1)*_a2_)**_a4_ + x1)**x1)/x1))**x1))))
<lambdifygenerated-1470>:2: RuntimeWarning: invalid value encountered in power
  return abs(tan(x1*(x1 + tan(sin(sqrt(tanh(x1*(x1*tanh(_a0_*_a1_**tanh(x1)*_a2_)**_a4_ + x1)**x1)/x1))**x1))))
<lambdifygenerated-1471>:2: RuntimeWarning: invalid value encountered in power
  return abs(tan(x1*(x1 + tan(sin(sqrt(tanh(x1*(_a3_*tanh(_a0_*_a1_**tanh(x1)*_a2_)**_a4_ + x1)**x1)/x1))**x1))))
<lambdifygenerated-1472>:2: RuntimeWarning: invalid value encountered in power
  return abs(tan(x1*(x1 + tan(sin(sqrt(tanh(x1*(_a3_*tanh(_a0_*_a1_**tanh(x1)*_a2_)**_a4_ + x1)**x1)/x1))**x1))))
<lambdifygenerated-1473>:2: RuntimeWarning: invalid value encountered in power
  return abs(tan(x1*(x1 + tan(sin(sqrt(tanh(x1*(_a3_*tanh(_a0_*_a1_**tanh(x1)*_a2_)**_a4_ + _a6_)**x1)/x1))**x1))))
<lambdifygenerated-1475>:2: RuntimeWarning: invalid value encountered in power
  return abs(tan(x1*(x1 + tan(sin(sqrt(tanh(x1*(_a3_*tanh(_a0_*_a1_**tanh(x1)*_a2_)**_a4_ + _a6_)**(x1**2))/x1))**x1))))
<lambdifygenerated-1477>:2: RuntimeWarning: invalid value encountered in power
  return abs(tan(x1*(x1 + tan(sin(sqrt(tanh(x1*(_a3_*tanh(_a0_*_a1_**tanh(x1)*_a2_)**_a4_ + _a6_)**(_a1_*x1))/x1))**x1))))
<lambdifygenerated-1479>:2: RuntimeWarning: invalid value encountered in power
  return abs(tan(x1*(x1 + tan(sin(sqrt(tanh(x1*(_a3_*tanh(_a0_*_a1_**tanh(x1)*_a2_)**_a4_ + _a6_)**(2*_a1_*x1))/x1))**x1))))
<lambdifygenerated-1481>:2: RuntimeWarning: invalid value encountered in power
  return abs(tan(x1*(x1 + tan(sin(sqrt(tanh(x1*(_a3_*tanh(_a0_*_a1_**tanh(x1)*_a2_)**_a4_ + _a6_)**(_a1_*(_a5_ + x1)))/x1))**x1))))
<lambdifygenerated-1483>:2: RuntimeWarning: invalid value encountered in power
  return abs(tan(x1*(x1 + tan(sin(sqrt(tanh(x1*(_a3_*tanh(_a0_*_a1_**tanh(x1)*_a2_)**_a4_ + _a6_)**(_a1_*(_a5_ - x1)))/x1))**x1))))
<lambdifygenerated-1485>:2: RuntimeWarning: invalid value encountered in power
  return abs(tan(x1*(x1 + tan(sin(sqrt(tanh(x1*(_a3_*tanh(_a0_*_a1_**tanh(x1)*_a2_)**_a4_ + _a6_)**(_a1_*(_a5_ - x1**x1)))/x1))**x1))))
<lambdifygenerated-1486>:2: RuntimeWarning: invalid value encountered in power
  return abs(tan(x1*(x1 + tan(sin(sqrt(tanh(x1*(_a3_*tanh(_a0_*_a1_**tanh(x1)*_a2_)**_a4_ + _a6_)**(_a1_*(_a5_ - x1**x1)))/x1))**x1))))
<lambdifygenerated-1493>:2: RuntimeWarning: invalid value encountered in sqrt
  return abs(tan(x1*(x1 + tan(sin(sqrt(tanh(_a4_*(_a3_*tanh(_a0_*_a1_**tanh(x1)*_a2_)**_a4_ + _a6_)**(_a1_*(_a5_ - _a7_**sin(x1))))/x1))**x1))))
<lambdifygenerated-1494>:2: RuntimeWarning: invalid value encountered in sqrt
  return abs(tan(x1*(x1 + tan(sin(sqrt(tanh(_a4_*(_a3_*tanh(_a0_*_a1_**tanh(x1)*_a2_)**_a4_ + _a6_)**(_a1_*(_a5_ - _a7_**sin(x1))))/x1))**x1))))
<lambdifygenerated-1495>:2: RuntimeWarning: invalid value encountered in sqrt
  return abs(tan(x1*(x1 + tan(sin(sqrt(tanh(_a4_*(_a3_*tanh(_a0_*_a1_**tanh(x1)*_a2_)**_a4_ + _a6_)**(_a1_*(_a5_ - _a7_**sin(x1))))/cos(x1)))**x1))))
<lambdifygenerated-1496>:2: RuntimeWarning: invalid value encountered in sqrt
  return abs(tan(x1*(x1 + tan(sin(sqrt(tanh(_a4_*(_a3_*tanh(_a0_*_a1_**tanh(x1)*_a2_)**_a4_ + _a6_)**(_a1_*(_a5_ - _a7_**sin(x1))))/cos(x1)))**x1))))

interpolation

<lambdifygenerated-1515>:2: RuntimeWarning: invalid value encountered in power
  return abs(tan(_a2_*_a3_*(x1*cos(_a1_) + tan(sin(sqrt(tanh(_a4_*(_a3_*tanh(_a0_*_a1_**tanh(x1)*_a2_)**_a4_ + _a6_)**(_a1_*(_a5_ - _a7_**sin(x1))))/cos(_a2_)))**_a4_))/x1))
<lambdifygenerated-1515>:2: RuntimeWarning: invalid value encountered in sqrt
  return abs(tan(_a2_*_a3_*(x1*cos(_a1_) + tan(sin(sqrt(tanh(_a4_*(_a3_*tanh(_a0_*_a1_**tanh(x1)*_a2_)**_a4_ + _a6_)**(_a1_*(_a5_ - _a7_**sin(x1))))/cos(_a2_)))**_a4_))/x1))
<lambdifygenerated-1517>:2: RuntimeWarning: overflow encountered in power
  return abs(tan(_a2_*_a3_*(x1*cos(_a1_) + tan(sin(sqrt(tanh(_a4_*(_a3_*tanh(_a0_*_a1_**tanh(x1)*_a2_)**_a4_ + _a6_)**(_a1_*(_a5_ - _a7_**sin(x1))))/cos(_a2_)))**_a4_))/_a7_))
<lambdifygenerated-1517>:2: RuntimeWarning: invalid value encountered in power
  return abs(tan(_a2_*_a3_*(x1*cos(_a1_) + tan(sin(sqrt(tanh(_a4_*(_a3_*tanh(_a0_*_a1_**tanh(x1)*_a2_)**_a4_ + _a6_)**(_a1_*(_a5_ - _a7_**sin(x1))))/cos(_a2_)))**_a4_))/_a7_))
<lambdifygenerated-1517>:2: RuntimeWarning: overflow encountered in multiply
  return abs(tan(_a2_*_a3_*(x1*cos(_a1_) + tan(sin(sqrt(tanh(_a4_*(_a3_*tanh(_a0_*_a1_**tanh(x1)*_a2_)**_a4_ + _a6_)**(_a1_*(_a5_ - _a7_**sin(x1))))/cos(_a2_)))**_a4_))/_a7_))
<lambdifygenerated-1521>:2: RuntimeWarning: overflow encountered in power
  return abs(tan(_a2_*_a3_*(x1*cos(_a1_) + tan(sin(sqrt(tanh(_a4_*(_a3_*tanh(_a0_*_a1_**tanh(x1)*_a2_)**_a4_ + _a6_)**(_a1_*(_a5_ - _a7_**sin(x1))))/cos(_a2_)))**_a4_))/_a7_))
<lambdifygenerated-1521>:2: RuntimeWarning: invalid value encountered in power
  return abs(tan(_a2_*_a3_*(x1*cos(_a1_) + tan(sin(sqrt(tanh(_a4_*(_a3_*tanh(_a0_*_a1_**tanh(x1)*_a2_)**_a4_ + _a6_)**(_a1_*(_a5_ - _a7_**sin(x1))))/cos(_a2_)))**_a4_))/_a7_))
<lambdifygenerated-1521>:2: RuntimeWarning: overflow encountered in multiply
  return abs(tan(_a2_*_a3_*(x1*cos(_a1_) + tan(sin(sqrt(tanh(_a4_*(_a3_*tanh(_a0_*_a1_**tanh(x1)*_a2_)**_a4_ + _a6_)**(_a1_*(_a5_ - _a7_**sin(x1))))/cos(_a2_)))**_a4_))/_a7_))

         x1         y  rep    ymodel      ybms
3745  0.997  0.965360  4.0  0.965902  0.965541
3746  0.998  0.965399  4.0  0.965949  0.965583
3747  0.998  0.965439  4.0  0.965997  0.965625
3748  0.999  0.965479  4.0  0.966044  0.965667

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.965559  4.0  0.966139  0.965752
3751  1.002  0.965598  4.0  0.966187  0.965794
3752  1.002  0.965638  4.0  0.966234  0.965836
3753  1.003  0.965678  4.0  0.966282  0.965878

3750

<lambdifygenerated-1527>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1
<lambdifygenerated-1528>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1
<lambdifygenerated-1529>:2: RuntimeWarning: invalid value encountered in power
  return tan(x1)**x1
<lambdifygenerated-1530>:2: RuntimeWarning: invalid value encountered in power
  return tan(x1)**x1
<lambdifygenerated-1533>:2: RuntimeWarning: invalid value encountered in power
  return tan(exp(x1)/x1)**x1
<lambdifygenerated-1534>:2: RuntimeWarning: invalid value encountered in power
  return tan(exp(x1)/x1)**x1
<lambdifygenerated-1535>:2: RuntimeWarning: overflow encountered in exp
  return tan(exp(tan(x1))/x1)**x1
<lambdifygenerated-1535>:2: RuntimeWarning: invalid value encountered in tan
  return tan(exp(tan(x1))/x1)**x1
<lambdifygenerated-1535>:2: RuntimeWarning: divide by zero encountered in power
  return tan(exp(tan(x1))/x1)**x1
<lambdifygenerated-1535>:2: RuntimeWarning: invalid value encountered in power
  return tan(exp(tan(x1))/x1)**x1
<lambdifygenerated-1536>:2: RuntimeWarning: overflow encountered in exp
  return tan(exp(tan(x1))/x1)**x1
<lambdifygenerated-1536>:2: RuntimeWarning: invalid value encountered in tan
  return tan(exp(tan(x1))/x1)**x1
<lambdifygenerated-1536>:2: RuntimeWarning: divide by zero encountered in power
  return tan(exp(tan(x1))/x1)**x1
<lambdifygenerated-1536>:2: RuntimeWarning: invalid value encountered in power
  return tan(exp(tan(x1))/x1)**x1
<lambdifygenerated-1537>:2: RuntimeWarning: invalid value encountered in power
  return tan(exp(tan(x1**x1))/x1)**x1
<lambdifygenerated-1537>:2: RuntimeWarning: overflow encountered in exp
  return tan(exp(tan(x1**x1))/x1)**x1
<lambdifygenerated-1537>:2: RuntimeWarning: invalid value encountered in tan
  return tan(exp(tan(x1**x1))/x1)**x1
<lambdifygenerated-1538>:2: RuntimeWarning: invalid value encountered in power
  return tan(exp(tan(x1**x1))/x1)**x1
<lambdifygenerated-1538>:2: RuntimeWarning: overflow encountered in exp
  return tan(exp(tan(x1**x1))/x1)**x1
<lambdifygenerated-1538>:2: RuntimeWarning: invalid value encountered in tan
  return tan(exp(tan(x1**x1))/x1)**x1
<lambdifygenerated-1539>:2: RuntimeWarning: invalid value encountered in power
  return tan(exp(tan((2*x1)**x1))/x1)**x1
<lambdifygenerated-1539>:2: RuntimeWarning: overflow encountered in exp
  return tan(exp(tan((2*x1)**x1))/x1)**x1
<lambdifygenerated-1539>:2: RuntimeWarning: invalid value encountered in tan
  return tan(exp(tan((2*x1)**x1))/x1)**x1
<lambdifygenerated-1540>:2: RuntimeWarning: invalid value encountered in power
  return tan(exp(tan((2*x1)**x1))/x1)**x1
<lambdifygenerated-1540>:2: RuntimeWarning: overflow encountered in exp
  return tan(exp(tan((2*x1)**x1))/x1)**x1
<lambdifygenerated-1540>:2: RuntimeWarning: invalid value encountered in tan
  return tan(exp(tan((2*x1)**x1))/x1)**x1
<lambdifygenerated-1541>:2: RuntimeWarning: invalid value encountered in power
  return tan(exp(tan((x1**2 + x1)**x1))/x1)**x1
<lambdifygenerated-1541>:2: RuntimeWarning: overflow encountered in exp
  return tan(exp(tan((x1**2 + x1)**x1))/x1)**x1
<lambdifygenerated-1541>:2: RuntimeWarning: invalid value encountered in tan
  return tan(exp(tan((x1**2 + x1)**x1))/x1)**x1
<lambdifygenerated-1541>:2: RuntimeWarning: divide by zero encountered in power
  return tan(exp(tan((x1**2 + x1)**x1))/x1)**x1
<lambdifygenerated-1542>:2: RuntimeWarning: invalid value encountered in power
  return tan(exp(tan((x1**2 + x1)**x1))/x1)**x1
<lambdifygenerated-1542>:2: RuntimeWarning: overflow encountered in exp
  return tan(exp(tan((x1**2 + x1)**x1))/x1)**x1
<lambdifygenerated-1542>:2: RuntimeWarning: invalid value encountered in tan
  return tan(exp(tan((x1**2 + x1)**x1))/x1)**x1
<lambdifygenerated-1542>:2: RuntimeWarning: divide by zero encountered in power
  return tan(exp(tan((x1**2 + x1)**x1))/x1)**x1
<lambdifygenerated-1543>:2: RuntimeWarning: invalid value encountered in power
  return tan(exp(tan((2*x1)**x1))/x1)**x1
<lambdifygenerated-1543>:2: RuntimeWarning: overflow encountered in exp
  return tan(exp(tan((2*x1)**x1))/x1)**x1
<lambdifygenerated-1543>:2: RuntimeWarning: invalid value encountered in tan
  return tan(exp(tan((2*x1)**x1))/x1)**x1
<lambdifygenerated-1544>:2: RuntimeWarning: invalid value encountered in power
  return tan(exp(tan((2*x1)**x1))/x1)**x1
<lambdifygenerated-1544>:2: RuntimeWarning: overflow encountered in exp
  return tan(exp(tan((2*x1)**x1))/x1)**x1
<lambdifygenerated-1544>:2: RuntimeWarning: invalid value encountered in tan
  return tan(exp(tan((2*x1)**x1))/x1)**x1
<lambdifygenerated-1545>:2: RuntimeWarning: invalid value encountered in power
  return tan(exp(tan((x1 + x1**x1)**x1))/x1)**x1
<lambdifygenerated-1545>:2: RuntimeWarning: overflow encountered in exp
  return tan(exp(tan((x1 + x1**x1)**x1))/x1)**x1
<lambdifygenerated-1545>:2: RuntimeWarning: invalid value encountered in tan
  return tan(exp(tan((x1 + x1**x1)**x1))/x1)**x1
<lambdifygenerated-1546>:2: RuntimeWarning: invalid value encountered in power
  return tan(exp(tan((x1 + x1**x1)**x1))/x1)**x1
<lambdifygenerated-1546>:2: RuntimeWarning: overflow encountered in exp
  return tan(exp(tan((x1 + x1**x1)**x1))/x1)**x1
<lambdifygenerated-1546>:2: RuntimeWarning: invalid value encountered in tan
  return tan(exp(tan((x1 + x1**x1)**x1))/x1)**x1
<lambdifygenerated-1547>:2: RuntimeWarning: invalid value encountered in power
  return tan(exp(tan((x1 + (2*x1)**x1)**x1))/x1)**x1
<lambdifygenerated-1547>:2: RuntimeWarning: overflow encountered in exp
  return tan(exp(tan((x1 + (2*x1)**x1)**x1))/x1)**x1
<lambdifygenerated-1547>:2: RuntimeWarning: invalid value encountered in tan
  return tan(exp(tan((x1 + (2*x1)**x1)**x1))/x1)**x1
<lambdifygenerated-1548>:2: RuntimeWarning: invalid value encountered in power
  return tan(exp(tan((x1 + (2*x1)**x1)**x1))/x1)**x1
<lambdifygenerated-1548>:2: RuntimeWarning: overflow encountered in exp
  return tan(exp(tan((x1 + (2*x1)**x1)**x1))/x1)**x1
<lambdifygenerated-1548>:2: RuntimeWarning: invalid value encountered in tan
  return tan(exp(tan((x1 + (2*x1)**x1)**x1))/x1)**x1
<lambdifygenerated-1549>:2: RuntimeWarning: invalid value encountered in power
  return tan(exp(tan((x1 + (x1 + 1)**x1)**x1))/x1)**x1
<lambdifygenerated-1549>:2: RuntimeWarning: overflow encountered in exp
  return tan(exp(tan((x1 + (x1 + 1)**x1)**x1))/x1)**x1
<lambdifygenerated-1549>:2: RuntimeWarning: invalid value encountered in tan
  return tan(exp(tan((x1 + (x1 + 1)**x1)**x1))/x1)**x1
<lambdifygenerated-1550>:2: RuntimeWarning: invalid value encountered in power
  return tan(exp(tan((x1 + (x1 + 1)**x1)**x1))/x1)**x1
<lambdifygenerated-1550>:2: RuntimeWarning: overflow encountered in exp
  return tan(exp(tan((x1 + (x1 + 1)**x1)**x1))/x1)**x1
<lambdifygenerated-1550>:2: RuntimeWarning: invalid value encountered in tan
  return tan(exp(tan((x1 + (x1 + 1)**x1)**x1))/x1)**x1
<lambdifygenerated-1551>:2: RuntimeWarning: invalid value encountered in power
  return tan(exp(tan((x1 + (x1 + x1**(-1.0))**x1)**x1))/x1)**x1
<lambdifygenerated-1551>:2: RuntimeWarning: overflow encountered in exp
  return tan(exp(tan((x1 + (x1 + x1**(-1.0))**x1)**x1))/x1)**x1
<lambdifygenerated-1551>:2: RuntimeWarning: invalid value encountered in tan
  return tan(exp(tan((x1 + (x1 + x1**(-1.0))**x1)**x1))/x1)**x1
<lambdifygenerated-1552>:2: RuntimeWarning: invalid value encountered in power
  return tan(exp(tan((x1 + (x1 + x1**(-1.0))**x1)**x1))/x1)**x1
<lambdifygenerated-1552>:2: RuntimeWarning: overflow encountered in exp
  return tan(exp(tan((x1 + (x1 + x1**(-1.0))**x1)**x1))/x1)**x1
<lambdifygenerated-1552>:2: RuntimeWarning: invalid value encountered in tan
  return tan(exp(tan((x1 + (x1 + x1**(-1.0))**x1)**x1))/x1)**x1
<lambdifygenerated-1553>:2: RuntimeWarning: invalid value encountered in power
  return tan(exp(tan((x1 + (x1 + cos(x1)/x1**2)**x1)**x1))/x1)**x1
<lambdifygenerated-1553>:2: RuntimeWarning: overflow encountered in exp
  return tan(exp(tan((x1 + (x1 + cos(x1)/x1**2)**x1)**x1))/x1)**x1
<lambdifygenerated-1553>:2: RuntimeWarning: invalid value encountered in tan
  return tan(exp(tan((x1 + (x1 + cos(x1)/x1**2)**x1)**x1))/x1)**x1
<lambdifygenerated-1553>:2: RuntimeWarning: divide by zero encountered in power
  return tan(exp(tan((x1 + (x1 + cos(x1)/x1**2)**x1)**x1))/x1)**x1
<lambdifygenerated-1554>:2: RuntimeWarning: invalid value encountered in power
  return tan(exp(tan((x1 + (x1 + cos(x1)/x1**2)**x1)**x1))/x1)**x1
<lambdifygenerated-1554>:2: RuntimeWarning: overflow encountered in exp
  return tan(exp(tan((x1 + (x1 + cos(x1)/x1**2)**x1)**x1))/x1)**x1
<lambdifygenerated-1554>:2: RuntimeWarning: invalid value encountered in tan
  return tan(exp(tan((x1 + (x1 + cos(x1)/x1**2)**x1)**x1))/x1)**x1
<lambdifygenerated-1554>:2: RuntimeWarning: divide by zero encountered in power
  return tan(exp(tan((x1 + (x1 + cos(x1)/x1**2)**x1)**x1))/x1)**x1
<lambdifygenerated-1555>:2: RuntimeWarning: invalid value encountered in power
  return tan(exp(tan((x1 + (x1 + cos(x1**x1)/x1**2)**x1)**x1))/x1)**x1
<lambdifygenerated-1555>:2: RuntimeWarning: overflow encountered in exp
  return tan(exp(tan((x1 + (x1 + cos(x1**x1)/x1**2)**x1)**x1))/x1)**x1
<lambdifygenerated-1555>:2: RuntimeWarning: invalid value encountered in tan
  return tan(exp(tan((x1 + (x1 + cos(x1**x1)/x1**2)**x1)**x1))/x1)**x1
<lambdifygenerated-1556>:2: RuntimeWarning: invalid value encountered in power
  return tan(exp(tan((x1 + (x1 + cos(x1**x1)/x1**2)**x1)**x1))/x1)**x1
<lambdifygenerated-1556>:2: RuntimeWarning: overflow encountered in exp
  return tan(exp(tan((x1 + (x1 + cos(x1**x1)/x1**2)**x1)**x1))/x1)**x1
<lambdifygenerated-1556>:2: RuntimeWarning: invalid value encountered in tan
  return tan(exp(tan((x1 + (x1 + cos(x1**x1)/x1**2)**x1)**x1))/x1)**x1
<lambdifygenerated-1557>:2: RuntimeWarning: invalid value encountered in power
  return tan(exp(tan((x1 + (x1 + cos(_a6_**x1)/x1**2)**x1)**x1))/x1)**x1
<lambdifygenerated-1557>:2: RuntimeWarning: overflow encountered in exp
  return tan(exp(tan((x1 + (x1 + cos(_a6_**x1)/x1**2)**x1)**x1))/x1)**x1
<lambdifygenerated-1557>:2: RuntimeWarning: invalid value encountered in tan
  return tan(exp(tan((x1 + (x1 + cos(_a6_**x1)/x1**2)**x1)**x1))/x1)**x1
<lambdifygenerated-1557>:2: RuntimeWarning: divide by zero encountered in power
  return tan(exp(tan((x1 + (x1 + cos(_a6_**x1)/x1**2)**x1)**x1))/x1)**x1
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-1558>:2: RuntimeWarning: invalid value encountered in power
  return tan(exp(tan((x1 + (x1 + cos(_a6_**x1)/x1**2)**x1)**x1))/x1)**x1
<lambdifygenerated-1558>:2: RuntimeWarning: overflow encountered in exp
  return tan(exp(tan((x1 + (x1 + cos(_a6_**x1)/x1**2)**x1)**x1))/x1)**x1
<lambdifygenerated-1558>:2: RuntimeWarning: invalid value encountered in tan
  return tan(exp(tan((x1 + (x1 + cos(_a6_**x1)/x1**2)**x1)**x1))/x1)**x1
<lambdifygenerated-1558>:2: RuntimeWarning: divide by zero encountered in power
  return tan(exp(tan((x1 + (x1 + cos(_a6_**x1)/x1**2)**x1)**x1))/x1)**x1
<lambdifygenerated-1559>:2: RuntimeWarning: invalid value encountered in power
  return tan(exp(tan((x1 + (x1 + cos(_a6_**tanh(x1))/x1**2)**x1)**x1))/x1)**x1
<lambdifygenerated-1559>:2: RuntimeWarning: overflow encountered in exp
  return tan(exp(tan((x1 + (x1 + cos(_a6_**tanh(x1))/x1**2)**x1)**x1))/x1)**x1
<lambdifygenerated-1559>:2: RuntimeWarning: invalid value encountered in tan
  return tan(exp(tan((x1 + (x1 + cos(_a6_**tanh(x1))/x1**2)**x1)**x1))/x1)**x1
<lambdifygenerated-1559>:2: RuntimeWarning: divide by zero encountered in power
  return tan(exp(tan((x1 + (x1 + cos(_a6_**tanh(x1))/x1**2)**x1)**x1))/x1)**x1
<lambdifygenerated-1560>:2: RuntimeWarning: invalid value encountered in power
  return tan(exp(tan((x1 + (x1 + cos(_a6_**tanh(x1))/x1**2)**x1)**x1))/x1)**x1
<lambdifygenerated-1560>:2: RuntimeWarning: overflow encountered in exp
  return tan(exp(tan((x1 + (x1 + cos(_a6_**tanh(x1))/x1**2)**x1)**x1))/x1)**x1
<lambdifygenerated-1560>:2: RuntimeWarning: invalid value encountered in tan
  return tan(exp(tan((x1 + (x1 + cos(_a6_**tanh(x1))/x1**2)**x1)**x1))/x1)**x1
<lambdifygenerated-1560>:2: RuntimeWarning: divide by zero encountered in power
  return tan(exp(tan((x1 + (x1 + cos(_a6_**tanh(x1))/x1**2)**x1)**x1))/x1)**x1
<lambdifygenerated-1561>:2: RuntimeWarning: invalid value encountered in power
  return tan(exp(tan((x1 + (x1 + cos(_a6_**tanh(x1**2))/x1**2)**x1)**x1))/x1)**x1
<lambdifygenerated-1561>:2: RuntimeWarning: overflow encountered in exp
  return tan(exp(tan((x1 + (x1 + cos(_a6_**tanh(x1**2))/x1**2)**x1)**x1))/x1)**x1
<lambdifygenerated-1561>:2: RuntimeWarning: invalid value encountered in tan
  return tan(exp(tan((x1 + (x1 + cos(_a6_**tanh(x1**2))/x1**2)**x1)**x1))/x1)**x1
<lambdifygenerated-1561>:2: RuntimeWarning: divide by zero encountered in power
  return tan(exp(tan((x1 + (x1 + cos(_a6_**tanh(x1**2))/x1**2)**x1)**x1))/x1)**x1
<lambdifygenerated-1562>:2: RuntimeWarning: invalid value encountered in power
  return tan(exp(tan((x1 + (x1 + cos(_a6_**tanh(x1**2))/x1**2)**x1)**x1))/x1)**x1
<lambdifygenerated-1562>:2: RuntimeWarning: overflow encountered in exp
  return tan(exp(tan((x1 + (x1 + cos(_a6_**tanh(x1**2))/x1**2)**x1)**x1))/x1)**x1
<lambdifygenerated-1562>:2: RuntimeWarning: invalid value encountered in tan
  return tan(exp(tan((x1 + (x1 + cos(_a6_**tanh(x1**2))/x1**2)**x1)**x1))/x1)**x1
<lambdifygenerated-1562>:2: RuntimeWarning: divide by zero encountered in power
  return tan(exp(tan((x1 + (x1 + cos(_a6_**tanh(x1**2))/x1**2)**x1)**x1))/x1)**x1
<lambdifygenerated-1563>:2: RuntimeWarning: invalid value encountered in power
  return tan(exp(tan((x1 + (x1 + cos(_a6_**tanh(x1*tanh(x1)))/x1**2)**x1)**x1))/x1)**x1
<lambdifygenerated-1563>:2: RuntimeWarning: overflow encountered in exp
  return tan(exp(tan((x1 + (x1 + cos(_a6_**tanh(x1*tanh(x1)))/x1**2)**x1)**x1))/x1)**x1
<lambdifygenerated-1563>:2: RuntimeWarning: invalid value encountered in tan
  return tan(exp(tan((x1 + (x1 + cos(_a6_**tanh(x1*tanh(x1)))/x1**2)**x1)**x1))/x1)**x1
<lambdifygenerated-1563>:2: RuntimeWarning: divide by zero encountered in power
  return tan(exp(tan((x1 + (x1 + cos(_a6_**tanh(x1*tanh(x1)))/x1**2)**x1)**x1))/x1)**x1
<lambdifygenerated-1564>:2: RuntimeWarning: invalid value encountered in power
  return tan(exp(tan((x1 + (x1 + cos(_a6_**tanh(x1*tanh(x1)))/x1**2)**x1)**x1))/x1)**x1
<lambdifygenerated-1564>:2: RuntimeWarning: overflow encountered in exp
  return tan(exp(tan((x1 + (x1 + cos(_a6_**tanh(x1*tanh(x1)))/x1**2)**x1)**x1))/x1)**x1
<lambdifygenerated-1564>:2: RuntimeWarning: invalid value encountered in tan
  return tan(exp(tan((x1 + (x1 + cos(_a6_**tanh(x1*tanh(x1)))/x1**2)**x1)**x1))/x1)**x1
<lambdifygenerated-1564>:2: RuntimeWarning: divide by zero encountered in power
  return tan(exp(tan((x1 + (x1 + cos(_a6_**tanh(x1*tanh(x1)))/x1**2)**x1)**x1))/x1)**x1
<lambdifygenerated-1565>:2: RuntimeWarning: invalid value encountered in power
  return tan(exp(tan((x1 + (x1 + cos(_a6_**tanh(x1*tanh(tanh(x1))))/x1**2)**x1)**x1))/x1)**x1
<lambdifygenerated-1565>:2: RuntimeWarning: overflow encountered in exp
  return tan(exp(tan((x1 + (x1 + cos(_a6_**tanh(x1*tanh(tanh(x1))))/x1**2)**x1)**x1))/x1)**x1
<lambdifygenerated-1565>:2: RuntimeWarning: invalid value encountered in tan
  return tan(exp(tan((x1 + (x1 + cos(_a6_**tanh(x1*tanh(tanh(x1))))/x1**2)**x1)**x1))/x1)**x1
<lambdifygenerated-1565>:2: RuntimeWarning: divide by zero encountered in power
  return tan(exp(tan((x1 + (x1 + cos(_a6_**tanh(x1*tanh(tanh(x1))))/x1**2)**x1)**x1))/x1)**x1
<lambdifygenerated-1566>:2: RuntimeWarning: invalid value encountered in power
  return tan(exp(tan((x1 + (x1 + cos(_a6_**tanh(x1*tanh(tanh(x1))))/x1**2)**x1)**x1))/x1)**x1
<lambdifygenerated-1566>:2: RuntimeWarning: overflow encountered in exp
  return tan(exp(tan((x1 + (x1 + cos(_a6_**tanh(x1*tanh(tanh(x1))))/x1**2)**x1)**x1))/x1)**x1
<lambdifygenerated-1566>:2: RuntimeWarning: invalid value encountered in tan
  return tan(exp(tan((x1 + (x1 + cos(_a6_**tanh(x1*tanh(tanh(x1))))/x1**2)**x1)**x1))/x1)**x1
<lambdifygenerated-1566>:2: RuntimeWarning: divide by zero encountered in power
  return tan(exp(tan((x1 + (x1 + cos(_a6_**tanh(x1*tanh(tanh(x1))))/x1**2)**x1)**x1))/x1)**x1
<lambdifygenerated-1567>:2: RuntimeWarning: invalid value encountered in power
  return tan(exp(tan((x1 + (x1 + cos(_a6_**tanh(x1*tanh(tanh(x1))))/x1**2)**x1)**x1))/x1)**x1
<lambdifygenerated-1567>:2: RuntimeWarning: overflow encountered in exp
  return tan(exp(tan((x1 + (x1 + cos(_a6_**tanh(x1*tanh(tanh(x1))))/x1**2)**x1)**x1))/x1)**x1
<lambdifygenerated-1567>:2: RuntimeWarning: invalid value encountered in tan
  return tan(exp(tan((x1 + (x1 + cos(_a6_**tanh(x1*tanh(tanh(x1))))/x1**2)**x1)**x1))/x1)**x1
<lambdifygenerated-1567>:2: RuntimeWarning: divide by zero encountered in power
  return tan(exp(tan((x1 + (x1 + cos(_a6_**tanh(x1*tanh(tanh(x1))))/x1**2)**x1)**x1))/x1)**x1
<lambdifygenerated-1568>:2: RuntimeWarning: invalid value encountered in power
  return tan(exp(tan((x1 + (x1 + cos(_a6_**tanh(x1*tanh(tanh(x1))))/x1**2)**x1)**x1))/x1)**x1
<lambdifygenerated-1568>:2: RuntimeWarning: overflow encountered in exp
  return tan(exp(tan((x1 + (x1 + cos(_a6_**tanh(x1*tanh(tanh(x1))))/x1**2)**x1)**x1))/x1)**x1
<lambdifygenerated-1568>:2: RuntimeWarning: invalid value encountered in tan
  return tan(exp(tan((x1 + (x1 + cos(_a6_**tanh(x1*tanh(tanh(x1))))/x1**2)**x1)**x1))/x1)**x1
<lambdifygenerated-1568>:2: RuntimeWarning: divide by zero encountered in power
  return tan(exp(tan((x1 + (x1 + cos(_a6_**tanh(x1*tanh(tanh(x1))))/x1**2)**x1)**x1))/x1)**x1
<lambdifygenerated-1569>:2: RuntimeWarning: invalid value encountered in power
  return tan(exp(tan((x1 + (x1 + cos(_a6_**tanh(_a1_*tanh(tanh(x1))))/x1**2)**x1)**x1))/x1)**x1
<lambdifygenerated-1569>:2: RuntimeWarning: overflow encountered in exp
  return tan(exp(tan((x1 + (x1 + cos(_a6_**tanh(_a1_*tanh(tanh(x1))))/x1**2)**x1)**x1))/x1)**x1
<lambdifygenerated-1569>:2: RuntimeWarning: invalid value encountered in tan
  return tan(exp(tan((x1 + (x1 + cos(_a6_**tanh(_a1_*tanh(tanh(x1))))/x1**2)**x1)**x1))/x1)**x1
<lambdifygenerated-1569>:2: RuntimeWarning: divide by zero encountered in power
  return tan(exp(tan((x1 + (x1 + cos(_a6_**tanh(_a1_*tanh(tanh(x1))))/x1**2)**x1)**x1))/x1)**x1
<lambdifygenerated-1570>:2: RuntimeWarning: invalid value encountered in power
  return tan(exp(tan((x1 + (x1 + cos(_a6_**tanh(_a1_*tanh(tanh(x1))))/x1**2)**x1)**x1))/x1)**x1
<lambdifygenerated-1570>:2: RuntimeWarning: overflow encountered in exp
  return tan(exp(tan((x1 + (x1 + cos(_a6_**tanh(_a1_*tanh(tanh(x1))))/x1**2)**x1)**x1))/x1)**x1
<lambdifygenerated-1570>:2: RuntimeWarning: invalid value encountered in tan
  return tan(exp(tan((x1 + (x1 + cos(_a6_**tanh(_a1_*tanh(tanh(x1))))/x1**2)**x1)**x1))/x1)**x1
<lambdifygenerated-1570>:2: RuntimeWarning: divide by zero encountered in power
  return tan(exp(tan((x1 + (x1 + cos(_a6_**tanh(_a1_*tanh(tanh(x1))))/x1**2)**x1)**x1))/x1)**x1
<lambdifygenerated-1571>:2: RuntimeWarning: invalid value encountered in power
  return tan(exp(tan((x1 + (x1 + cos(_a6_**tanh(_a1_*tanh(tanh(x1))))/(_a7_*x1))**x1)**x1))/x1)**x1
<lambdifygenerated-1571>:2: RuntimeWarning: overflow encountered in exp
  return tan(exp(tan((x1 + (x1 + cos(_a6_**tanh(_a1_*tanh(tanh(x1))))/(_a7_*x1))**x1)**x1))/x1)**x1
<lambdifygenerated-1571>:2: RuntimeWarning: invalid value encountered in tan
  return tan(exp(tan((x1 + (x1 + cos(_a6_**tanh(_a1_*tanh(tanh(x1))))/(_a7_*x1))**x1)**x1))/x1)**x1
<lambdifygenerated-1572>:2: RuntimeWarning: invalid value encountered in power
  return tan(exp(tan((x1 + (x1 + cos(_a6_**tanh(_a1_*tanh(tanh(x1))))/(_a7_*x1))**x1)**x1))/x1)**x1
<lambdifygenerated-1572>:2: RuntimeWarning: overflow encountered in exp

interpolation

<lambdifygenerated-1589>:2: RuntimeWarning: invalid value encountered in power
  return tan(exp(tan((x1 + x1*(_a3_*cosh(x1) + cos(_a6_**tanh(_a1_*tanh(tanh(x1))))/(_a0_*_a7_))**(_a4_ + x1)/_a1_)**x1))/x1)**x1
<lambdifygenerated-1589>:2: RuntimeWarning: overflow encountered in exp
  return tan(exp(tan((x1 + x1*(_a3_*cosh(x1) + cos(_a6_**tanh(_a1_*tanh(tanh(x1))))/(_a0_*_a7_))**(_a4_ + x1)/_a1_)**x1))/x1)**x1
<lambdifygenerated-1589>:2: RuntimeWarning: invalid value encountered in tan
  return tan(exp(tan((x1 + x1*(_a3_*cosh(x1) + cos(_a6_**tanh(_a1_*tanh(tanh(x1))))/(_a0_*_a7_))**(_a4_ + x1)/_a1_)**x1))/x1)**x1
<lambdifygenerated-1590>:2: RuntimeWarning: invalid value encountered in power
  return tan(exp(tan((x1 + x1*(_a3_*cosh(x1) + cos(_a6_**tanh(_a1_*tanh(tanh(x1))))/(_a0_*_a7_))**(_a4_ + x1)/_a1_)**x1))/x1)**x1
<lambdifygenerated-1590>:2: RuntimeWarning: overflow encountered in exp
  return tan(exp(tan((x1 + x1*(_a3_*cosh(x1) + cos(_a6_**tanh(_a1_*tanh(tanh(x1))))/(_a0_*_a7_))**(_a4_ + x1)/_a1_)**x1))/x1)**x1
<lambdifygenerated-1590>:2: RuntimeWarning: invalid value encountered in tan
  return tan(exp(tan((x1 + x1*(_a3_*cosh(x1) + cos(_a6_**tanh(_a1_*tanh(tanh(x1))))/(_a0_*_a7_))**(_a4_ + x1)/_a1_)**x1))/x1)**x1
<lambdifygenerated-1591>:2: RuntimeWarning: invalid value encountered in power
  return tan(exp(tan((_a0_*(_a3_*cosh(x1) + cos(_a6_**tanh(_a1_*tanh(tanh(x1))))/(_a0_*_a7_))**(_a4_ + x1)/_a1_ + x1)**x1))/x1)**x1
<lambdifygenerated-1591>:2: RuntimeWarning: overflow encountered in exp
  return tan(exp(tan((_a0_*(_a3_*cosh(x1) + cos(_a6_**tanh(_a1_*tanh(tanh(x1))))/(_a0_*_a7_))**(_a4_ + x1)/_a1_ + x1)**x1))/x1)**x1
<lambdifygenerated-1591>:2: RuntimeWarning: invalid value encountered in tan
  return tan(exp(tan((_a0_*(_a3_*cosh(x1) + cos(_a6_**tanh(_a1_*tanh(tanh(x1))))/(_a0_*_a7_))**(_a4_ + x1)/_a1_ + x1)**x1))/x1)**x1
<lambdifygenerated-1591>:2: RuntimeWarning: divide by zero encountered in power
  return tan(exp(tan((_a0_*(_a3_*cosh(x1) + cos(_a6_**tanh(_a1_*tanh(tanh(x1))))/(_a0_*_a7_))**(_a4_ + x1)/_a1_ + x1)**x1))/x1)**x1
<lambdifygenerated-1592>:2: RuntimeWarning: invalid value encountered in power
  return tan(exp(tan((_a0_*(_a3_*cosh(x1) + cos(_a6_**tanh(_a1_*tanh(tanh(x1))))/(_a0_*_a7_))**(_a4_ + x1)/_a1_ + x1)**x1))/x1)**x1
<lambdifygenerated-1592>:2: RuntimeWarning: overflow encountered in exp
  return tan(exp(tan((_a0_*(_a3_*cosh(x1) + cos(_a6_**tanh(_a1_*tanh(tanh(x1))))/(_a0_*_a7_))**(_a4_ + x1)/_a1_ + x1)**x1))/x1)**x1
<lambdifygenerated-1592>:2: RuntimeWarning: invalid value encountered in tan
  return tan(exp(tan((_a0_*(_a3_*cosh(x1) + cos(_a6_**tanh(_a1_*tanh(tanh(x1))))/(_a0_*_a7_))**(_a4_ + x1)/_a1_ + x1)**x1))/x1)**x1
<lambdifygenerated-1592>:2: RuntimeWarning: divide by zero encountered in power
  return tan(exp(tan((_a0_*(_a3_*cosh(x1) + cos(_a6_**tanh(_a1_*tanh(tanh(x1))))/(_a0_*_a7_))**(_a4_ + x1)/_a1_ + x1)**x1))/x1)**x1
<lambdifygenerated-1593>:2: RuntimeWarning: overflow encountered in exp
  return tan(exp(tan((_a0_*(_a3_*cosh(x1) + cos(_a6_**tanh(_a1_*tanh(tanh(x1))))/(_a0_*_a7_))**(_a4_ + x1)/_a1_ + _a5_)**x1))/x1)**x1
<lambdifygenerated-1593>:2: RuntimeWarning: invalid value encountered in tan
  return tan(exp(tan((_a0_*(_a3_*cosh(x1) + cos(_a6_**tanh(_a1_*tanh(tanh(x1))))/(_a0_*_a7_))**(_a4_ + x1)/_a1_ + _a5_)**x1))/x1)**x1
<lambdifygenerated-1593>:2: RuntimeWarning: invalid value encountered in power
  return tan(exp(tan((_a0_*(_a3_*cosh(x1) + cos(_a6_**tanh(_a1_*tanh(tanh(x1))))/(_a0_*_a7_))**(_a4_ + x1)/_a1_ + _a5_)**x1))/x1)**x1
<lambdifygenerated-1594>:2: RuntimeWarning: overflow encountered in exp
  return tan(exp(tan((_a0_*(_a3_*cosh(x1) + cos(_a6_**tanh(_a1_*tanh(tanh(x1))))/(_a0_*_a7_))**(_a4_ + x1)/_a1_ + _a5_)**x1))/x1)**x1
<lambdifygenerated-1594>:2: RuntimeWarning: invalid value encountered in tan
  return tan(exp(tan((_a0_*(_a3_*cosh(x1) + cos(_a6_**tanh(_a1_*tanh(tanh(x1))))/(_a0_*_a7_))**(_a4_ + x1)/_a1_ + _a5_)**x1))/x1)**x1
<lambdifygenerated-1594>:2: RuntimeWarning: invalid value encountered in power
  return tan(exp(tan((_a0_*(_a3_*cosh(x1) + cos(_a6_**tanh(_a1_*tanh(tanh(x1))))/(_a0_*_a7_))**(_a4_ + x1)/_a1_ + _a5_)**x1))/x1)**x1
<lambdifygenerated-1595>:2: RuntimeWarning: overflow encountered in exp
  return tan(exp(tan((_a0_*(_a3_*cosh(x1) + cos(_a6_**tanh(_a1_*tanh(tanh(x1))))/(_a0_*_a7_))**(_a4_ + x1)/_a1_ + _a5_)**(x1**2)))/x1)**x1
<lambdifygenerated-1595>:2: RuntimeWarning: invalid value encountered in tan
  return tan(exp(tan((_a0_*(_a3_*cosh(x1) + cos(_a6_**tanh(_a1_*tanh(tanh(x1))))/(_a0_*_a7_))**(_a4_ + x1)/_a1_ + _a5_)**(x1**2)))/x1)**x1
<lambdifygenerated-1595>:2: RuntimeWarning: divide by zero encountered in power
  return tan(exp(tan((_a0_*(_a3_*cosh(x1) + cos(_a6_**tanh(_a1_*tanh(tanh(x1))))/(_a0_*_a7_))**(_a4_ + x1)/_a1_ + _a5_)**(x1**2)))/x1)**x1
<lambdifygenerated-1595>:2: RuntimeWarning: invalid value encountered in power
  return tan(exp(tan((_a0_*(_a3_*cosh(x1) + cos(_a6_**tanh(_a1_*tanh(tanh(x1))))/(_a0_*_a7_))**(_a4_ + x1)/_a1_ + _a5_)**(x1**2)))/x1)**x1
<lambdifygenerated-1596>:2: RuntimeWarning: overflow encountered in exp
  return tan(exp(tan((_a0_*(_a3_*cosh(x1) + cos(_a6_**tanh(_a1_*tanh(tanh(x1))))/(_a0_*_a7_))**(_a4_ + x1)/_a1_ + _a5_)**(x1**2)))/x1)**x1
<lambdifygenerated-1596>:2: RuntimeWarning: invalid value encountered in tan
  return tan(exp(tan((_a0_*(_a3_*cosh(x1) + cos(_a6_**tanh(_a1_*tanh(tanh(x1))))/(_a0_*_a7_))**(_a4_ + x1)/_a1_ + _a5_)**(x1**2)))/x1)**x1
<lambdifygenerated-1596>:2: RuntimeWarning: divide by zero encountered in power
  return tan(exp(tan((_a0_*(_a3_*cosh(x1) + cos(_a6_**tanh(_a1_*tanh(tanh(x1))))/(_a0_*_a7_))**(_a4_ + x1)/_a1_ + _a5_)**(x1**2)))/x1)**x1
<lambdifygenerated-1596>:2: RuntimeWarning: invalid value encountered in power
  return tan(exp(tan((_a0_*(_a3_*cosh(x1) + cos(_a6_**tanh(_a1_*tanh(tanh(x1))))/(_a0_*_a7_))**(_a4_ + x1)/_a1_ + _a5_)**(x1**2)))/x1)**x1
<lambdifygenerated-1597>:2: RuntimeWarning: divide by zero encountered in power
  return tan(exp(tan((_a0_*(_a3_*cosh(x1) + cos(_a6_**tanh(_a1_*tanh(tanh(x1))))/(_a0_*_a7_))**(_a4_ + x1)/_a1_ + _a5_)**(x1**4)))/x1)**x1
<lambdifygenerated-1597>:2: RuntimeWarning: invalid value encountered in power
  return tan(exp(tan((_a0_*(_a3_*cosh(x1) + cos(_a6_**tanh(_a1_*tanh(tanh(x1))))/(_a0_*_a7_))**(_a4_ + x1)/_a1_ + _a5_)**(x1**4)))/x1)**x1
<lambdifygenerated-1597>:2: RuntimeWarning: overflow encountered in exp
  return tan(exp(tan((_a0_*(_a3_*cosh(x1) + cos(_a6_**tanh(_a1_*tanh(tanh(x1))))/(_a0_*_a7_))**(_a4_ + x1)/_a1_ + _a5_)**(x1**4)))/x1)**x1
<lambdifygenerated-1597>:2: RuntimeWarning: invalid value encountered in tan
  return tan(exp(tan((_a0_*(_a3_*cosh(x1) + cos(_a6_**tanh(_a1_*tanh(tanh(x1))))/(_a0_*_a7_))**(_a4_ + x1)/_a1_ + _a5_)**(x1**4)))/x1)**x1
<lambdifygenerated-1598>:2: RuntimeWarning: divide by zero encountered in power
  return tan(exp(tan((_a0_*(_a3_*cosh(x1) + cos(_a6_**tanh(_a1_*tanh(tanh(x1))))/(_a0_*_a7_))**(_a4_ + x1)/_a1_ + _a5_)**(x1**4)))/x1)**x1
<lambdifygenerated-1598>:2: RuntimeWarning: invalid value encountered in power
  return tan(exp(tan((_a0_*(_a3_*cosh(x1) + cos(_a6_**tanh(_a1_*tanh(tanh(x1))))/(_a0_*_a7_))**(_a4_ + x1)/_a1_ + _a5_)**(x1**4)))/x1)**x1
<lambdifygenerated-1599>:2: RuntimeWarning: overflow encountered in exp
  return tan(exp(tan((_a0_*(_a3_*cosh(x1) + cos(_a6_**tanh(_a1_*tanh(tanh(x1))))/(_a0_*_a7_))**(_a4_ + x1)/_a1_ + _a5_)**(_a6_**2*x1**2)))/x1)**x1
<lambdifygenerated-1599>:2: RuntimeWarning: invalid value encountered in tan
  return tan(exp(tan((_a0_*(_a3_*cosh(x1) + cos(_a6_**tanh(_a1_*tanh(tanh(x1))))/(_a0_*_a7_))**(_a4_ + x1)/_a1_ + _a5_)**(_a6_**2*x1**2)))/x1)**x1
<lambdifygenerated-1599>:2: RuntimeWarning: divide by zero encountered in power
  return tan(exp(tan((_a0_*(_a3_*cosh(x1) + cos(_a6_**tanh(_a1_*tanh(tanh(x1))))/(_a0_*_a7_))**(_a4_ + x1)/_a1_ + _a5_)**(_a6_**2*x1**2)))/x1)**x1
<lambdifygenerated-1599>:2: RuntimeWarning: invalid value encountered in power
  return tan(exp(tan((_a0_*(_a3_*cosh(x1) + cos(_a6_**tanh(_a1_*tanh(tanh(x1))))/(_a0_*_a7_))**(_a4_ + x1)/_a1_ + _a5_)**(_a6_**2*x1**2)))/x1)**x1
<lambdifygenerated-1600>:2: RuntimeWarning: overflow encountered in exp
  return tan(exp(tan((_a0_*(_a3_*cosh(x1) + cos(_a6_**tanh(_a1_*tanh(tanh(x1))))/(_a0_*_a7_))**(_a4_ + x1)/_a1_ + _a5_)**(_a6_**2*x1**2)))/x1)**x1
<lambdifygenerated-1600>:2: RuntimeWarning: invalid value encountered in tan
  return tan(exp(tan((_a0_*(_a3_*cosh(x1) + cos(_a6_**tanh(_a1_*tanh(tanh(x1))))/(_a0_*_a7_))**(_a4_ + x1)/_a1_ + _a5_)**(_a6_**2*x1**2)))/x1)**x1
<lambdifygenerated-1600>:2: RuntimeWarning: divide by zero encountered in power
  return tan(exp(tan((_a0_*(_a3_*cosh(x1) + cos(_a6_**tanh(_a1_*tanh(tanh(x1))))/(_a0_*_a7_))**(_a4_ + x1)/_a1_ + _a5_)**(_a6_**2*x1**2)))/x1)**x1
<lambdifygenerated-1600>:2: RuntimeWarning: invalid value encountered in power
  return tan(exp(tan((_a0_*(_a3_*cosh(x1) + cos(_a6_**tanh(_a1_*tanh(tanh(x1))))/(_a0_*_a7_))**(_a4_ + x1)/_a1_ + _a5_)**(_a6_**2*x1**2)))/x1)**x1
<lambdifygenerated-1601>:2: RuntimeWarning: overflow encountered in exp
  return tan(exp(tan((_a0_*(_a3_*cosh(x1) + cos(_a6_**tanh(_a1_*tanh(tanh(x1))))/(_a0_*_a7_))**(_a4_ + x1)/_a1_ + _a5_)**(_a6_**2*_a7_**2)))/x1)**x1
<lambdifygenerated-1601>:2: RuntimeWarning: invalid value encountered in tan
  return tan(exp(tan((_a0_*(_a3_*cosh(x1) + cos(_a6_**tanh(_a1_*tanh(tanh(x1))))/(_a0_*_a7_))**(_a4_ + x1)/_a1_ + _a5_)**(_a6_**2*_a7_**2)))/x1)**x1
<lambdifygenerated-1601>:2: RuntimeWarning: divide by zero encountered in power
  return tan(exp(tan((_a0_*(_a3_*cosh(x1) + cos(_a6_**tanh(_a1_*tanh(tanh(x1))))/(_a0_*_a7_))**(_a4_ + x1)/_a1_ + _a5_)**(_a6_**2*_a7_**2)))/x1)**x1
<lambdifygenerated-1601>:2: RuntimeWarning: invalid value encountered in power
  return tan(exp(tan((_a0_*(_a3_*cosh(x1) + cos(_a6_**tanh(_a1_*tanh(tanh(x1))))/(_a0_*_a7_))**(_a4_ + x1)/_a1_ + _a5_)**(_a6_**2*_a7_**2)))/x1)**x1
<lambdifygenerated-1602>:2: RuntimeWarning: overflow encountered in exp
  return tan(exp(tan((_a0_*(_a3_*cosh(x1) + cos(_a6_**tanh(_a1_*tanh(tanh(x1))))/(_a0_*_a7_))**(_a4_ + x1)/_a1_ + _a5_)**(_a6_**2*_a7_**2)))/x1)**x1
<lambdifygenerated-1602>:2: RuntimeWarning: invalid value encountered in tan
  return tan(exp(tan((_a0_*(_a3_*cosh(x1) + cos(_a6_**tanh(_a1_*tanh(tanh(x1))))/(_a0_*_a7_))**(_a4_ + x1)/_a1_ + _a5_)**(_a6_**2*_a7_**2)))/x1)**x1
<lambdifygenerated-1602>:2: RuntimeWarning: divide by zero encountered in power
  return tan(exp(tan((_a0_*(_a3_*cosh(x1) + cos(_a6_**tanh(_a1_*tanh(tanh(x1))))/(_a0_*_a7_))**(_a4_ + x1)/_a1_ + _a5_)**(_a6_**2*_a7_**2)))/x1)**x1
<lambdifygenerated-1602>:2: RuntimeWarning: invalid value encountered in power
  return tan(exp(tan((_a0_*(_a3_*cosh(x1) + cos(_a6_**tanh(_a1_*tanh(tanh(x1))))/(_a0_*_a7_))**(_a4_ + x1)/_a1_ + _a5_)**(_a6_**2*_a7_**2)))/x1)**x1
<lambdifygenerated-1603>:2: RuntimeWarning: overflow encountered in exp
  return tan(exp(tan((_a0_*(_a3_*cosh(x1) + cos(_a6_**tanh(_a1_*tanh(tanh(x1))))/(_a0_*_a7_))**(_a4_ + x1)/_a1_ + _a5_)**(_a6_**2*_a7_**2)))/x1**2)**x1
<lambdifygenerated-1603>:2: RuntimeWarning: invalid value encountered in tan
  return tan(exp(tan((_a0_*(_a3_*cosh(x1) + cos(_a6_**tanh(_a1_*tanh(tanh(x1))))/(_a0_*_a7_))**(_a4_ + x1)/_a1_ + _a5_)**(_a6_**2*_a7_**2)))/x1**2)**x1
<lambdifygenerated-1603>:2: RuntimeWarning: divide by zero encountered in power
  return tan(exp(tan((_a0_*(_a3_*cosh(x1) + cos(_a6_**tanh(_a1_*tanh(tanh(x1))))/(_a0_*_a7_))**(_a4_ + x1)/_a1_ + _a5_)**(_a6_**2*_a7_**2)))/x1**2)**x1
<lambdifygenerated-1603>:2: RuntimeWarning: overflow encountered in power
  return tan(exp(tan((_a0_*(_a3_*cosh(x1) + cos(_a6_**tanh(_a1_*tanh(tanh(x1))))/(_a0_*_a7_))**(_a4_ + x1)/_a1_ + _a5_)**(_a6_**2*_a7_**2)))/x1**2)**x1
<lambdifygenerated-1603>:2: RuntimeWarning: invalid value encountered in power
  return tan(exp(tan((_a0_*(_a3_*cosh(x1) + cos(_a6_**tanh(_a1_*tanh(tanh(x1))))/(_a0_*_a7_))**(_a4_ + x1)/_a1_ + _a5_)**(_a6_**2*_a7_**2)))/x1**2)**x1
/usr/local/lib/python3.10/dist-packages/scipy/optimize/_minpack_py.py:1017: RuntimeWarning: overflow encountered in square
  cost = np.sum(infodict['fvec'] ** 2)
/usr/local/lib/python3.10/dist-packages/pandas/core/arraylike.py:399: RuntimeWarning: overflow encountered in square
  result = getattr(ufunc, method)(*inputs, **kwargs)
<lambdifygenerated-1604>:2: RuntimeWarning: overflow encountered in exp
  return tan(exp(tan((_a0_*(_a3_*cosh(x1) + cos(_a6_**tanh(_a1_*tanh(tanh(x1))))/(_a0_*_a7_))**(_a4_ + x1)/_a1_ + _a5_)**(_a6_**2*_a7_**2)))/x1**2)**x1
<lambdifygenerated-1604>:2: RuntimeWarning: invalid value encountered in tan
  return tan(exp(tan((_a0_*(_a3_*cosh(x1) + cos(_a6_**tanh(_a1_*tanh(tanh(x1))))/(_a0_*_a7_))**(_a4_ + x1)/_a1_ + _a5_)**(_a6_**2*_a7_**2)))/x1**2)**x1
<lambdifygenerated-1604>:2: RuntimeWarning: divide by zero encountered in power
  return tan(exp(tan((_a0_*(_a3_*cosh(x1) + cos(_a6_**tanh(_a1_*tanh(tanh(x1))))/(_a0_*_a7_))**(_a4_ + x1)/_a1_ + _a5_)**(_a6_**2*_a7_**2)))/x1**2)**x1
<lambdifygenerated-1604>:2: RuntimeWarning: overflow encountered in power
  return tan(exp(tan((_a0_*(_a3_*cosh(x1) + cos(_a6_**tanh(_a1_*tanh(tanh(x1))))/(_a0_*_a7_))**(_a4_ + x1)/_a1_ + _a5_)**(_a6_**2*_a7_**2)))/x1**2)**x1
<lambdifygenerated-1604>:2: RuntimeWarning: invalid value encountered in power
  return tan(exp(tan((_a0_*(_a3_*cosh(x1) + cos(_a6_**tanh(_a1_*tanh(tanh(x1))))/(_a0_*_a7_))**(_a4_ + x1)/_a1_ + _a5_)**(_a6_**2*_a7_**2)))/x1**2)**x1
<lambdifygenerated-1605>:2: RuntimeWarning: overflow encountered in exp
  return tan(exp(tan((_a0_*(_a3_*cosh(x1) + cos(_a6_**tanh(_a1_*tanh(tanh(x1))))/(_a0_*_a7_))**(_a4_ + x1)/_a1_ + _a5_)**(_a6_**2*_a7_**2)))/(_a2_*x1))**x1
<lambdifygenerated-1605>:2: RuntimeWarning: invalid value encountered in tan
  return tan(exp(tan((_a0_*(_a3_*cosh(x1) + cos(_a6_**tanh(_a1_*tanh(tanh(x1))))/(_a0_*_a7_))**(_a4_ + x1)/_a1_ + _a5_)**(_a6_**2*_a7_**2)))/(_a2_*x1))**x1
<lambdifygenerated-1605>:2: RuntimeWarning: divide by zero encountered in power
  return tan(exp(tan((_a0_*(_a3_*cosh(x1) + cos(_a6_**tanh(_a1_*tanh(tanh(x1))))/(_a0_*_a7_))**(_a4_ + x1)/_a1_ + _a5_)**(_a6_**2*_a7_**2)))/(_a2_*x1))**x1
<lambdifygenerated-1605>:2: RuntimeWarning: invalid value encountered in power
  return tan(exp(tan((_a0_*(_a3_*cosh(x1) + cos(_a6_**tanh(_a1_*tanh(tanh(x1))))/(_a0_*_a7_))**(_a4_ + x1)/_a1_ + _a5_)**(_a6_**2*_a7_**2)))/(_a2_*x1))**x1
<lambdifygenerated-1606>:2: RuntimeWarning: overflow encountered in exp
  return tan(exp(tan((_a0_*(_a3_*cosh(x1) + cos(_a6_**tanh(_a1_*tanh(tanh(x1))))/(_a0_*_a7_))**(_a4_ + x1)/_a1_ + _a5_)**(_a6_**2*_a7_**2)))/(_a2_*x1))**x1
<lambdifygenerated-1606>:2: RuntimeWarning: invalid value encountered in tan
  return tan(exp(tan((_a0_*(_a3_*cosh(x1) + cos(_a6_**tanh(_a1_*tanh(tanh(x1))))/(_a0_*_a7_))**(_a4_ + x1)/_a1_ + _a5_)**(_a6_**2*_a7_**2)))/(_a2_*x1))**x1
<lambdifygenerated-1606>:2: RuntimeWarning: divide by zero encountered in power
  return tan(exp(tan((_a0_*(_a3_*cosh(x1) + cos(_a6_**tanh(_a1_*tanh(tanh(x1))))/(_a0_*_a7_))**(_a4_ + x1)/_a1_ + _a5_)**(_a6_**2*_a7_**2)))/(_a2_*x1))**x1
<lambdifygenerated-1606>:2: RuntimeWarning: invalid value encountered in power
  return tan(exp(tan((_a0_*(_a3_*cosh(x1) + cos(_a6_**tanh(_a1_*tanh(tanh(x1))))/(_a0_*_a7_))**(_a4_ + x1)/_a1_ + _a5_)**(_a6_**2*_a7_**2)))/(_a2_*x1))**x1
<lambdifygenerated-1607>:2: RuntimeWarning: overflow encountered in exp
  return tan(exp(tan((_a0_*(_a3_*cosh(x1) + cos(_a6_**tanh(_a1_*tanh(tanh(x1))))/(_a0_*_a7_))**(_a4_ + x1)/_a1_ + _a5_)**(_a6_**2*_a7_**2)))/(_a2_*_a7_))**x1
<lambdifygenerated-1607>:2: RuntimeWarning: invalid value encountered in tan
  return tan(exp(tan((_a0_*(_a3_*cosh(x1) + cos(_a6_**tanh(_a1_*tanh(tanh(x1))))/(_a0_*_a7_))**(_a4_ + x1)/_a1_ + _a5_)**(_a6_**2*_a7_**2)))/(_a2_*_a7_))**x1
<lambdifygenerated-1607>:2: RuntimeWarning: divide by zero encountered in power
  return tan(exp(tan((_a0_*(_a3_*cosh(x1) + cos(_a6_**tanh(_a1_*tanh(tanh(x1))))/(_a0_*_a7_))**(_a4_ + x1)/_a1_ + _a5_)**(_a6_**2*_a7_**2)))/(_a2_*_a7_))**x1
<lambdifygenerated-1607>:2: RuntimeWarning: overflow encountered in power
  return tan(exp(tan((_a0_*(_a3_*cosh(x1) + cos(_a6_**tanh(_a1_*tanh(tanh(x1))))/(_a0_*_a7_))**(_a4_ + x1)/_a1_ + _a5_)**(_a6_**2*_a7_**2)))/(_a2_*_a7_))**x1
<lambdifygenerated-1607>:2: RuntimeWarning: invalid value encountered in power
  return tan(exp(tan((_a0_*(_a3_*cosh(x1) + cos(_a6_**tanh(_a1_*tanh(tanh(x1))))/(_a0_*_a7_))**(_a4_ + x1)/_a1_ + _a5_)**(_a6_**2*_a7_**2)))/(_a2_*_a7_))**x1
<lambdifygenerated-1608>:2: RuntimeWarning: overflow encountered in exp
  return tan(exp(tan((_a0_*(_a3_*cosh(x1) + cos(_a6_**tanh(_a1_*tanh(tanh(x1))))/(_a0_*_a7_))**(_a4_ + x1)/_a1_ + _a5_)**(_a6_**2*_a7_**2)))/(_a2_*_a7_))**x1
<lambdifygenerated-1608>:2: RuntimeWarning: invalid value encountered in tan
  return tan(exp(tan((_a0_*(_a3_*cosh(x1) + cos(_a6_**tanh(_a1_*tanh(tanh(x1))))/(_a0_*_a7_))**(_a4_ + x1)/_a1_ + _a5_)**(_a6_**2*_a7_**2)))/(_a2_*_a7_))**x1
<lambdifygenerated-1608>:2: RuntimeWarning: divide by zero encountered in power
  return tan(exp(tan((_a0_*(_a3_*cosh(x1) + cos(_a6_**tanh(_a1_*tanh(tanh(x1))))/(_a0_*_a7_))**(_a4_ + x1)/_a1_ + _a5_)**(_a6_**2*_a7_**2)))/(_a2_*_a7_))**x1
<lambdifygenerated-1608>:2: RuntimeWarning: overflow encountered in power
  return tan(exp(tan((_a0_*(_a3_*cosh(x1) + cos(_a6_**tanh(_a1_*tanh(tanh(x1))))/(_a0_*_a7_))**(_a4_ + x1)/_a1_ + _a5_)**(_a6_**2*_a7_**2)))/(_a2_*_a7_))**x1
<lambdifygenerated-1608>:2: RuntimeWarning: invalid value encountered in power
  return tan(exp(tan((_a0_*(_a3_*cosh(x1) + cos(_a6_**tanh(_a1_*tanh(tanh(x1))))/(_a0_*_a7_))**(_a4_ + x1)/_a1_ + _a5_)**(_a6_**2*_a7_**2)))/(_a2_*_a7_))**x1
<lambdifygenerated-1609>:2: RuntimeWarning: overflow encountered in exp
  return tan(exp(tan((_a0_*(_a3_*cosh(x1) + cos(_a6_**tanh(_a1_*tanh(tanh(x1))))/(_a0_*_a7_))**(_a4_ + x1)/_a1_ + _a5_)**(_a6_**2*_a7_**2)))/(_a2_*_a7_))**_a6_
<lambdifygenerated-1609>:2: RuntimeWarning: invalid value encountered in tan
  return tan(exp(tan((_a0_*(_a3_*cosh(x1) + cos(_a6_**tanh(_a1_*tanh(tanh(x1))))/(_a0_*_a7_))**(_a4_ + x1)/_a1_ + _a5_)**(_a6_**2*_a7_**2)))/(_a2_*_a7_))**_a6_
<lambdifygenerated-1609>:2: RuntimeWarning: invalid value encountered in power
  return tan(exp(tan((_a0_*(_a3_*cosh(x1) + cos(_a6_**tanh(_a1_*tanh(tanh(x1))))/(_a0_*_a7_))**(_a4_ + x1)/_a1_ + _a5_)**(_a6_**2*_a7_**2)))/(_a2_*_a7_))**_a6_
<lambdifygenerated-1610>:2: RuntimeWarning: overflow encountered in exp
  return tan(exp(tan((_a0_*(_a3_*cosh(x1) + cos(_a6_**tanh(_a1_*tanh(tanh(x1))))/(_a0_*_a7_))**(_a4_ + x1)/_a1_ + _a5_)**(_a6_**2*_a7_**2)))/(_a2_*_a7_))**_a6_
<lambdifygenerated-1610>:2: RuntimeWarning: invalid value encountered in tan
  return tan(exp(tan((_a0_*(_a3_*cosh(x1) + cos(_a6_**tanh(_a1_*tanh(tanh(x1))))/(_a0_*_a7_))**(_a4_ + x1)/_a1_ + _a5_)**(_a6_**2*_a7_**2)))/(_a2_*_a7_))**_a6_
<lambdifygenerated-1611>:2: RuntimeWarning: overflow encountered in exp
  return tan(exp(tan((_a0_*(_a3_*cosh(x1) + cos(_a6_**tanh(_a1_*tanh(tanh(x1))))/(_a0_*_a7_))**(_a4_ + x1)/_a1_ + _a5_)**(_a6_**2*_a7_**2)))/(_a2_*_a7_))**_a6_
<lambdifygenerated-1611>:2: RuntimeWarning: invalid value encountered in tan
  return tan(exp(tan((_a0_*(_a3_*cosh(x1) + cos(_a6_**tanh(_a1_*tanh(tanh(x1))))/(_a0_*_a7_))**(_a4_ + x1)/_a1_ + _a5_)**(_a6_**2*_a7_**2)))/(_a2_*_a7_))**_a6_
<lambdifygenerated-1612>:2: RuntimeWarning: overflow encountered in exp
  return tan(exp(tan((_a0_*(_a3_*cosh(x1) + cos(_a6_**tanh(_a1_*tanh(tanh(x1))))/(_a0_*_a7_))**(_a4_ + x1)/_a1_ + _a5_)**(_a6_**2*_a7_**2)))/(_a2_*_a7_))**_a6_
<lambdifygenerated-1612>:2: RuntimeWarning: invalid value encountered in tan
  return tan(exp(tan((_a0_*(_a3_*cosh(x1) + cos(_a6_**tanh(_a1_*tanh(tanh(x1))))/(_a0_*_a7_))**(_a4_ + x1)/_a1_ + _a5_)**(_a6_**2*_a7_**2)))/(_a2_*_a7_))**_a6_
<lambdifygenerated-1613>:2: RuntimeWarning: overflow encountered in exp
  return tan(exp(tan((_a0_*(_a3_*cosh(x1) + cos(_a6_**tanh(_a1_*tanh(tanh(x1))))/(_a0_*_a7_))**(_a4_ + x1)/_a1_ + _a5_)**(_a6_**2*_a7_**2)))/(_a2_*_a7_))**_a6_

         x1         y  rep    ymodel      ybms
3745  0.997  0.308339  5.0  0.310494  0.308817
3746  0.998  0.308354  5.0  0.310565  0.308847
3747  0.998  0.308368  5.0  0.310635  0.308876
3748  0.999  0.308382  5.0  0.310705  0.308905

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.308407  5.0  0.310846  0.308961
3751  1.002  0.308419  5.0  0.310916  0.308989
3752  1.002  0.308430  5.0  0.310986  0.309016
3753  1.003  0.308441  5.0  0.311055  0.309043

3750

<lambdifygenerated-1623>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1
<lambdifygenerated-1624>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1
<lambdifygenerated-1629>:2: RuntimeWarning: invalid value encountered in power
  return (sinh(x1**x1)/x1)**x1
<lambdifygenerated-1630>:2: RuntimeWarning: invalid value encountered in power
  return (sinh(x1**x1)/x1)**x1
<lambdifygenerated-1631>:2: RuntimeWarning: invalid value encountered in power
  return (sinh(tanh(x1)**x1)/x1)**x1
<lambdifygenerated-1632>:2: RuntimeWarning: invalid value encountered in power
  return (sinh(tanh(x1)**x1)/x1)**x1
<lambdifygenerated-1633>:2: RuntimeWarning: invalid value encountered in power
  return (sinh(tanh(x1**2)**x1)/x1)**x1
<lambdifygenerated-1634>:2: RuntimeWarning: invalid value encountered in power
  return (sinh(tanh(x1**2)**x1)/x1)**x1
<lambdifygenerated-1635>:2: RuntimeWarning: invalid value encountered in power
  return (sinh(tanh(x1**3)**x1)/x1)**x1
<lambdifygenerated-1636>:2: RuntimeWarning: invalid value encountered in power
  return (sinh(tanh(x1**3)**x1)/x1)**x1
<lambdifygenerated-1637>:2: RuntimeWarning: invalid value encountered in power
  return (sinh(tanh(x1**2*sin(x1))**x1)/x1)**x1
<lambdifygenerated-1638>:2: RuntimeWarning: invalid value encountered in power
  return (sinh(tanh(x1**2*sin(x1))**x1)/x1)**x1
<lambdifygenerated-1639>:2: RuntimeWarning: invalid value encountered in power
  return (sinh(tanh(x1**2*sin(x1**2))**x1)/x1)**x1
<lambdifygenerated-1639>:2: RuntimeWarning: overflow encountered in sinh
  return (sinh(tanh(x1**2*sin(x1**2))**x1)/x1)**x1
<lambdifygenerated-1640>:2: RuntimeWarning: invalid value encountered in power
  return (sinh(tanh(x1**2*sin(x1**2))**x1)/x1)**x1
<lambdifygenerated-1640>:2: RuntimeWarning: overflow encountered in sinh
  return (sinh(tanh(x1**2*sin(x1**2))**x1)/x1)**x1
<lambdifygenerated-1641>:2: RuntimeWarning: invalid value encountered in power
  return (sinh(tanh(x1**2*sin(x1**3))**x1)/x1)**x1
<lambdifygenerated-1641>:2: RuntimeWarning: overflow encountered in sinh
  return (sinh(tanh(x1**2*sin(x1**3))**x1)/x1)**x1
<lambdifygenerated-1642>:2: RuntimeWarning: invalid value encountered in power
  return (sinh(tanh(x1**2*sin(x1**3))**x1)/x1)**x1
<lambdifygenerated-1642>:2: RuntimeWarning: overflow encountered in sinh
  return (sinh(tanh(x1**2*sin(x1**3))**x1)/x1)**x1
<lambdifygenerated-1643>:2: RuntimeWarning: invalid value encountered in power
  return (sinh(tanh(x1**2*sin(4*x1**3))**x1)/x1)**x1
<lambdifygenerated-1643>:2: RuntimeWarning: overflow encountered in sinh
  return (sinh(tanh(x1**2*sin(4*x1**3))**x1)/x1)**x1
<lambdifygenerated-1644>:2: RuntimeWarning: invalid value encountered in power
  return (sinh(tanh(x1**2*sin(4*x1**3))**x1)/x1)**x1
<lambdifygenerated-1644>:2: RuntimeWarning: overflow encountered in sinh
  return (sinh(tanh(x1**2*sin(4*x1**3))**x1)/x1)**x1
<lambdifygenerated-1645>:2: RuntimeWarning: invalid value encountered in power
  return (sinh(tanh(x1**2*sin(x1*(x1 + x1**x1)**2))**x1)/x1)**x1
<lambdifygenerated-1646>:2: RuntimeWarning: invalid value encountered in power
  return (sinh(tanh(x1**2*sin(x1*(x1 + x1**x1)**2))**x1)/x1)**x1
<lambdifygenerated-1647>:2: RuntimeWarning: invalid value encountered in power
  return (sinh(tanh(x1**2*sin(x1*(x1 + tanh(x1)**x1)**2))**x1)/x1)**x1
<lambdifygenerated-1648>:2: RuntimeWarning: invalid value encountered in power
  return (sinh(tanh(x1**2*sin(x1*(x1 + tanh(x1)**x1)**2))**x1)/x1)**x1
<lambdifygenerated-1649>:2: RuntimeWarning: invalid value encountered in power
  return (sinh(tanh(x1**2*sin(x1*(x1 + tanh(x1**2)**x1)**2))**x1)/x1)**x1
<lambdifygenerated-1650>:2: RuntimeWarning: invalid value encountered in power
  return (sinh(tanh(x1**2*sin(x1*(x1 + tanh(x1**2)**x1)**2))**x1)/x1)**x1
<lambdifygenerated-1651>:2: RuntimeWarning: invalid value encountered in power
  return (sinh(tanh(x1**2*sin(x1*(x1 + tanh(2*x1**2)**x1)**2))**x1)/x1)**x1
<lambdifygenerated-1652>:2: RuntimeWarning: invalid value encountered in power
  return (sinh(tanh(x1**2*sin(x1*(x1 + tanh(2*x1**2)**x1)**2))**x1)/x1)**x1
<lambdifygenerated-1653>:2: RuntimeWarning: invalid value encountered in power
  return (sinh(tanh(x1**2*sin(x1*(x1 + tanh(2*x1**2)**x1)**2))**x1)/x1)**x1
<lambdifygenerated-1654>:2: RuntimeWarning: invalid value encountered in power
  return (sinh(tanh(x1**2*sin(x1*(x1 + tanh(2*x1**2)**x1)**2))**x1)/x1)**x1
<lambdifygenerated-1655>:2: RuntimeWarning: invalid value encountered in power
  return (sinh(tanh(x1**2*sin(x1*(x1 + tanh(x1*(x1**2 + x1))**x1)**2))**x1)/x1)**x1
<lambdifygenerated-1656>:2: RuntimeWarning: invalid value encountered in power
  return (sinh(tanh(x1**2*sin(x1*(x1 + tanh(x1*(x1**2 + x1))**x1)**2))**x1)/x1)**x1
<lambdifygenerated-1657>:2: RuntimeWarning: invalid value encountered in power
  return (sinh(tanh(x1**2*sin(x1*(x1 + tanh(x1*(_a0_*x1 + x1))**x1)**2))**x1)/x1)**x1
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-1658>:2: RuntimeWarning: invalid value encountered in power
  return (sinh(tanh(x1**2*sin(x1*(x1 + tanh(x1*(_a0_*x1 + x1))**x1)**2))**x1)/x1)**x1
<lambdifygenerated-1659>:2: RuntimeWarning: invalid value encountered in power
  return (sinh(tanh(x1**2*sin(x1*(x1 + tanh(x1*(_a0_*x1**2 + x1))**x1)**2))**x1)/x1)**x1
<lambdifygenerated-1660>:2: RuntimeWarning: invalid value encountered in power
  return (sinh(tanh(x1**2*sin(x1*(x1 + tanh(x1*(_a0_*x1**2 + x1))**x1)**2))**x1)/x1)**x1
<lambdifygenerated-1661>:2: RuntimeWarning: invalid value encountered in power
  return (sinh(tanh(x1**2*sin(x1*(x1 + tanh(x1*(_a0_*_a7_**2 + x1))**x1)**2))**x1)/x1)**x1
<lambdifygenerated-1662>:2: RuntimeWarning: invalid value encountered in power
  return (sinh(tanh(x1**2*sin(x1*(x1 + tanh(x1*(_a0_*_a7_**2 + x1))**x1)**2))**x1)/x1)**x1
<lambdifygenerated-1663>:2: RuntimeWarning: invalid value encountered in power
  return (sinh(tanh(x1**2*sin(x1*(x1 + tanh(_a4_*(_a0_*_a7_**2 + x1))**x1)**2))**x1)/x1)**x1
<lambdifygenerated-1664>:2: RuntimeWarning: invalid value encountered in power
  return (sinh(tanh(x1**2*sin(x1*(x1 + tanh(_a4_*(_a0_*_a7_**2 + x1))**x1)**2))**x1)/x1)**x1
<lambdifygenerated-1665>:2: RuntimeWarning: invalid value encountered in power
  return (sinh(tanh(x1**2*sin(x1*(x1 + tanh(_a4_*(_a0_*_a7_**2 + x1)))**2))**x1)/x1)**x1
<lambdifygenerated-1665>:2: RuntimeWarning: overflow encountered in sinh
  return (sinh(tanh(x1**2*sin(x1*(x1 + tanh(_a4_*(_a0_*_a7_**2 + x1)))**2))**x1)/x1)**x1
<lambdifygenerated-1666>:2: RuntimeWarning: invalid value encountered in power
  return (sinh(tanh(x1**2*sin(x1*(x1 + tanh(_a4_*(_a0_*_a7_**2 + x1)))**2))**x1)/x1)**x1
<lambdifygenerated-1666>:2: RuntimeWarning: overflow encountered in sinh
  return (sinh(tanh(x1**2*sin(x1*(x1 + tanh(_a4_*(_a0_*_a7_**2 + x1)))**2))**x1)/x1)**x1
<lambdifygenerated-1667>:2: RuntimeWarning: overflow encountered in power
  return (sinh(tanh(x1**2*sin(x1*(x1 + tanh(_a4_*(_a0_*_a7_**2 + x1))**(_a2_/x1))**2))**x1)/x1)**x1
<lambdifygenerated-1667>:2: RuntimeWarning: invalid value encountered in power
  return (sinh(tanh(x1**2*sin(x1*(x1 + tanh(_a4_*(_a0_*_a7_**2 + x1))**(_a2_/x1))**2))**x1)/x1)**x1
<lambdifygenerated-1667>:2: RuntimeWarning: invalid value encountered in sin
  return (sinh(tanh(x1**2*sin(x1*(x1 + tanh(_a4_*(_a0_*_a7_**2 + x1))**(_a2_/x1))**2))**x1)/x1)**x1
<lambdifygenerated-1668>:2: RuntimeWarning: overflow encountered in power
  return (sinh(tanh(x1**2*sin(x1*(x1 + tanh(_a4_*(_a0_*_a7_**2 + x1))**(_a2_/x1))**2))**x1)/x1)**x1
<lambdifygenerated-1668>:2: RuntimeWarning: invalid value encountered in power
  return (sinh(tanh(x1**2*sin(x1*(x1 + tanh(_a4_*(_a0_*_a7_**2 + x1))**(_a2_/x1))**2))**x1)/x1)**x1
<lambdifygenerated-1668>:2: RuntimeWarning: invalid value encountered in sin
  return (sinh(tanh(x1**2*sin(x1*(x1 + tanh(_a4_*(_a0_*_a7_**2 + x1))**(_a2_/x1))**2))**x1)/x1)**x1
<lambdifygenerated-1669>:2: RuntimeWarning: invalid value encountered in power
  return (sinh(tanh(x1**2*sin(x1*(x1 + tanh(_a4_*(_a0_*_a7_**2 + x1))**(_a2_/x1**2))**2))**x1)/x1)**x1
<lambdifygenerated-1670>:2: RuntimeWarning: invalid value encountered in power
  return (sinh(tanh(x1**2*sin(x1*(x1 + tanh(_a4_*(_a0_*_a7_**2 + x1))**(_a2_/x1**2))**2))**x1)/x1)**x1
<lambdifygenerated-1671>:2: RuntimeWarning: invalid value encountered in power
  return (sinh(tanh(x1**2*sin(x1*(x1 + tanh(_a4_*(_a0_*_a7_**2 + x1))**((1/2)*_a2_/x1**2))**2))**x1)/x1)**x1
<lambdifygenerated-1672>:2: RuntimeWarning: invalid value encountered in power
  return (sinh(tanh(x1**2*sin(x1*(x1 + tanh(_a4_*(_a0_*_a7_**2 + x1))**((1/2)*_a2_/x1**2))**2))**x1)/x1)**x1
<lambdifygenerated-1673>:2: RuntimeWarning: overflow encountered in power
  return (sinh(tanh(x1**2*sin(x1*(x1 + tanh(_a4_*(_a0_*_a7_**2 + x1))**(_a2_/(x1*(x1 + 1))))**2))**x1)/x1)**x1
<lambdifygenerated-1673>:2: RuntimeWarning: invalid value encountered in power
  return (sinh(tanh(x1**2*sin(x1*(x1 + tanh(_a4_*(_a0_*_a7_**2 + x1))**(_a2_/(x1*(x1 + 1))))**2))**x1)/x1)**x1
<lambdifygenerated-1673>:2: RuntimeWarning: overflow encountered in square
  return (sinh(tanh(x1**2*sin(x1*(x1 + tanh(_a4_*(_a0_*_a7_**2 + x1))**(_a2_/(x1*(x1 + 1))))**2))**x1)/x1)**x1
<lambdifygenerated-1673>:2: RuntimeWarning: invalid value encountered in sin
  return (sinh(tanh(x1**2*sin(x1*(x1 + tanh(_a4_*(_a0_*_a7_**2 + x1))**(_a2_/(x1*(x1 + 1))))**2))**x1)/x1)**x1
<lambdifygenerated-1673>:2: RuntimeWarning: overflow encountered in sinh
  return (sinh(tanh(x1**2*sin(x1*(x1 + tanh(_a4_*(_a0_*_a7_**2 + x1))**(_a2_/(x1*(x1 + 1))))**2))**x1)/x1)**x1
<lambdifygenerated-1674>:2: RuntimeWarning: overflow encountered in power
  return (sinh(tanh(x1**2*sin(x1*(x1 + tanh(_a4_*(_a0_*_a7_**2 + x1))**(_a2_/(x1*(x1 + 1))))**2))**x1)/x1)**x1
<lambdifygenerated-1674>:2: RuntimeWarning: invalid value encountered in power
  return (sinh(tanh(x1**2*sin(x1*(x1 + tanh(_a4_*(_a0_*_a7_**2 + x1))**(_a2_/(x1*(x1 + 1))))**2))**x1)/x1)**x1
<lambdifygenerated-1674>:2: RuntimeWarning: overflow encountered in square
  return (sinh(tanh(x1**2*sin(x1*(x1 + tanh(_a4_*(_a0_*_a7_**2 + x1))**(_a2_/(x1*(x1 + 1))))**2))**x1)/x1)**x1
<lambdifygenerated-1674>:2: RuntimeWarning: invalid value encountered in sin
  return (sinh(tanh(x1**2*sin(x1*(x1 + tanh(_a4_*(_a0_*_a7_**2 + x1))**(_a2_/(x1*(x1 + 1))))**2))**x1)/x1)**x1
<lambdifygenerated-1674>:2: RuntimeWarning: overflow encountered in sinh
  return (sinh(tanh(x1**2*sin(x1*(x1 + tanh(_a4_*(_a0_*_a7_**2 + x1))**(_a2_/(x1*(x1 + 1))))**2))**x1)/x1)**x1
<lambdifygenerated-1675>:2: RuntimeWarning: invalid value encountered in power
  return (sinh(tanh(x1**2*sin(x1*(x1 + tanh(_a4_*(_a0_*_a7_**2 + x1))**(_a2_/(x1*(_a6_/x1 + x1))))**2))**x1)/x1)**x1
<lambdifygenerated-1676>:2: RuntimeWarning: invalid value encountered in power
  return (sinh(tanh(x1**2*sin(x1*(x1 + tanh(_a4_*(_a0_*_a7_**2 + x1))**(_a2_/(x1*(_a6_/x1 + x1))))**2))**x1)/x1)**x1
<lambdifygenerated-1677>:2: RuntimeWarning: overflow encountered in power
  return (sinh(tanh(x1**2*sin(x1*(x1 + tanh(_a4_*(_a0_*_a7_**2 + x1))**(_a2_/(x1*(x1 + _a6_/_a1_))))**2))**x1)/x1)**x1
<lambdifygenerated-1677>:2: RuntimeWarning: invalid value encountered in power
  return (sinh(tanh(x1**2*sin(x1*(x1 + tanh(_a4_*(_a0_*_a7_**2 + x1))**(_a2_/(x1*(x1 + _a6_/_a1_))))**2))**x1)/x1)**x1
<lambdifygenerated-1677>:2: RuntimeWarning: overflow encountered in square
  return (sinh(tanh(x1**2*sin(x1*(x1 + tanh(_a4_*(_a0_*_a7_**2 + x1))**(_a2_/(x1*(x1 + _a6_/_a1_))))**2))**x1)/x1)**x1
<lambdifygenerated-1677>:2: RuntimeWarning: invalid value encountered in sin
  return (sinh(tanh(x1**2*sin(x1*(x1 + tanh(_a4_*(_a0_*_a7_**2 + x1))**(_a2_/(x1*(x1 + _a6_/_a1_))))**2))**x1)/x1)**x1
<lambdifygenerated-1677>:2: RuntimeWarning: overflow encountered in sinh
  return (sinh(tanh(x1**2*sin(x1*(x1 + tanh(_a4_*(_a0_*_a7_**2 + x1))**(_a2_/(x1*(x1 + _a6_/_a1_))))**2))**x1)/x1)**x1
<lambdifygenerated-1678>:2: RuntimeWarning: overflow encountered in power
  return (sinh(tanh(x1**2*sin(x1*(x1 + tanh(_a4_*(_a0_*_a7_**2 + x1))**(_a2_/(x1*(x1 + _a6_/_a1_))))**2))**x1)/x1)**x1
<lambdifygenerated-1678>:2: RuntimeWarning: invalid value encountered in power
  return (sinh(tanh(x1**2*sin(x1*(x1 + tanh(_a4_*(_a0_*_a7_**2 + x1))**(_a2_/(x1*(x1 + _a6_/_a1_))))**2))**x1)/x1)**x1
<lambdifygenerated-1678>:2: RuntimeWarning: overflow encountered in square
  return (sinh(tanh(x1**2*sin(x1*(x1 + tanh(_a4_*(_a0_*_a7_**2 + x1))**(_a2_/(x1*(x1 + _a6_/_a1_))))**2))**x1)/x1)**x1
<lambdifygenerated-1678>:2: RuntimeWarning: invalid value encountered in sin
  return (sinh(tanh(x1**2*sin(x1*(x1 + tanh(_a4_*(_a0_*_a7_**2 + x1))**(_a2_/(x1*(x1 + _a6_/_a1_))))**2))**x1)/x1)**x1
<lambdifygenerated-1678>:2: RuntimeWarning: overflow encountered in sinh
  return (sinh(tanh(x1**2*sin(x1*(x1 + tanh(_a4_*(_a0_*_a7_**2 + x1))**(_a2_/(x1*(x1 + _a6_/_a1_))))**2))**x1)/x1)**x1
<lambdifygenerated-1679>:2: RuntimeWarning: overflow encountered in power
  return (sinh(tanh(x1**2*sin(x1*(x1 + tanh(_a4_*(_a0_*_a7_**2 + x1))**(_a2_/(x1*(x1**2 + _a6_/_a1_))))**2))**x1)/x1)**x1
<lambdifygenerated-1679>:2: RuntimeWarning: invalid value encountered in power
  return (sinh(tanh(x1**2*sin(x1*(x1 + tanh(_a4_*(_a0_*_a7_**2 + x1))**(_a2_/(x1*(x1**2 + _a6_/_a1_))))**2))**x1)/x1)**x1
<lambdifygenerated-1679>:2: RuntimeWarning: invalid value encountered in sin
  return (sinh(tanh(x1**2*sin(x1*(x1 + tanh(_a4_*(_a0_*_a7_**2 + x1))**(_a2_/(x1*(x1**2 + _a6_/_a1_))))**2))**x1)/x1)**x1
<lambdifygenerated-1680>:2: RuntimeWarning: overflow encountered in power
  return (sinh(tanh(x1**2*sin(x1*(x1 + tanh(_a4_*(_a0_*_a7_**2 + x1))**(_a2_/(x1*(x1**2 + _a6_/_a1_))))**2))**x1)/x1)**x1
<lambdifygenerated-1680>:2: RuntimeWarning: invalid value encountered in power
  return (sinh(tanh(x1**2*sin(x1*(x1 + tanh(_a4_*(_a0_*_a7_**2 + x1))**(_a2_/(x1*(x1**2 + _a6_/_a1_))))**2))**x1)/x1)**x1
<lambdifygenerated-1680>:2: RuntimeWarning: invalid value encountered in sin
  return (sinh(tanh(x1**2*sin(x1*(x1 + tanh(_a4_*(_a0_*_a7_**2 + x1))**(_a2_/(x1*(x1**2 + _a6_/_a1_))))**2))**x1)/x1)**x1
<lambdifygenerated-1681>:2: RuntimeWarning: overflow encountered in power
  return (sinh(tanh(x1**2*sin(x1*(x1 + tanh(_a4_*(_a0_*_a7_**2 + x1))**(_a2_/(x1*(2*x1**2 + _a6_/_a1_))))**2))**x1)/x1)**x1
<lambdifygenerated-1681>:2: RuntimeWarning: invalid value encountered in power
  return (sinh(tanh(x1**2*sin(x1*(x1 + tanh(_a4_*(_a0_*_a7_**2 + x1))**(_a2_/(x1*(2*x1**2 + _a6_/_a1_))))**2))**x1)/x1)**x1
<lambdifygenerated-1681>:2: RuntimeWarning: invalid value encountered in sin
  return (sinh(tanh(x1**2*sin(x1*(x1 + tanh(_a4_*(_a0_*_a7_**2 + x1))**(_a2_/(x1*(2*x1**2 + _a6_/_a1_))))**2))**x1)/x1)**x1
<lambdifygenerated-1682>:2: RuntimeWarning: overflow encountered in power
  return (sinh(tanh(x1**2*sin(x1*(x1 + tanh(_a4_*(_a0_*_a7_**2 + x1))**(_a2_/(x1*(2*x1**2 + _a6_/_a1_))))**2))**x1)/x1)**x1
<lambdifygenerated-1682>:2: RuntimeWarning: invalid value encountered in power
  return (sinh(tanh(x1**2*sin(x1*(x1 + tanh(_a4_*(_a0_*_a7_**2 + x1))**(_a2_/(x1*(2*x1**2 + _a6_/_a1_))))**2))**x1)/x1)**x1
<lambdifygenerated-1682>:2: RuntimeWarning: invalid value encountered in sin
  return (sinh(tanh(x1**2*sin(x1*(x1 + tanh(_a4_*(_a0_*_a7_**2 + x1))**(_a2_/(x1*(2*x1**2 + _a6_/_a1_))))**2))**x1)/x1)**x1
<lambdifygenerated-1683>:2: RuntimeWarning: overflow encountered in power
  return (sinh(tanh(x1**2*sin(x1*(x1 + tanh(_a4_*(_a0_*_a7_**2 + x1))**(_a2_/(x1*(2*x1**2 + _a6_/_a1_))))**2))**x1)/x1)**x1
<lambdifygenerated-1683>:2: RuntimeWarning: invalid value encountered in power
  return (sinh(tanh(x1**2*sin(x1*(x1 + tanh(_a4_*(_a0_*_a7_**2 + x1))**(_a2_/(x1*(2*x1**2 + _a6_/_a1_))))**2))**x1)/x1)**x1
<lambdifygenerated-1683>:2: RuntimeWarning: invalid value encountered in sin
  return (sinh(tanh(x1**2*sin(x1*(x1 + tanh(_a4_*(_a0_*_a7_**2 + x1))**(_a2_/(x1*(2*x1**2 + _a6_/_a1_))))**2))**x1)/x1)**x1
<lambdifygenerated-1684>:2: RuntimeWarning: overflow encountered in power
  return (sinh(tanh(x1**2*sin(x1*(x1 + tanh(_a4_*(_a0_*_a7_**2 + x1))**(_a2_/(x1*(2*x1**2 + _a6_/_a1_))))**2))**x1)/x1)**x1
<lambdifygenerated-1684>:2: RuntimeWarning: invalid value encountered in power
  return (sinh(tanh(x1**2*sin(x1*(x1 + tanh(_a4_*(_a0_*_a7_**2 + x1))**(_a2_/(x1*(2*x1**2 + _a6_/_a1_))))**2))**x1)/x1)**x1
<lambdifygenerated-1684>:2: RuntimeWarning: invalid value encountered in sin
  return (sinh(tanh(x1**2*sin(x1*(x1 + tanh(_a4_*(_a0_*_a7_**2 + x1))**(_a2_/(x1*(2*x1**2 + _a6_/_a1_))))**2))**x1)/x1)**x1
<lambdifygenerated-1685>:2: RuntimeWarning: overflow encountered in power
  return (sinh(tanh(x1**2*sin(x1*(x1 + tanh(_a4_*(_a0_*_a7_**2 + x1))**(_a2_/(x1*(x1*(_a0_ + x1) + _a6_/_a1_))))**2))**x1)/x1)**x1
<lambdifygenerated-1685>:2: RuntimeWarning: invalid value encountered in power
  return (sinh(tanh(x1**2*sin(x1*(x1 + tanh(_a4_*(_a0_*_a7_**2 + x1))**(_a2_/(x1*(x1*(_a0_ + x1) + _a6_/_a1_))))**2))**x1)/x1)**x1
<lambdifygenerated-1685>:2: RuntimeWarning: invalid value encountered in sin
  return (sinh(tanh(x1**2*sin(x1*(x1 + tanh(_a4_*(_a0_*_a7_**2 + x1))**(_a2_/(x1*(x1*(_a0_ + x1) + _a6_/_a1_))))**2))**x1)/x1)**x1
<lambdifygenerated-1686>:2: RuntimeWarning: overflow encountered in power
  return (sinh(tanh(x1**2*sin(x1*(x1 + tanh(_a4_*(_a0_*_a7_**2 + x1))**(_a2_/(x1*(x1*(_a0_ + x1) + _a6_/_a1_))))**2))**x1)/x1)**x1
<lambdifygenerated-1686>:2: RuntimeWarning: invalid value encountered in power
  return (sinh(tanh(x1**2*sin(x1*(x1 + tanh(_a4_*(_a0_*_a7_**2 + x1))**(_a2_/(x1*(x1*(_a0_ + x1) + _a6_/_a1_))))**2))**x1)/x1)**x1
<lambdifygenerated-1686>:2: RuntimeWarning: invalid value encountered in sin
  return (sinh(tanh(x1**2*sin(x1*(x1 + tanh(_a4_*(_a0_*_a7_**2 + x1))**(_a2_/(x1*(x1*(_a0_ + x1) + _a6_/_a1_))))**2))**x1)/x1)**x1
<lambdifygenerated-1687>:2: RuntimeWarning: overflow encountered in power
  return (sinh(tanh(x1**2*sin(x1*(x1 + tanh(_a4_*(_a0_*_a7_**2 + x1))**(_a2_/(x1*(_a0_ + x1 + _a6_/_a1_))))**2))**x1)/x1)**x1
<lambdifygenerated-1687>:2: RuntimeWarning: invalid value encountered in power
  return (sinh(tanh(x1**2*sin(x1*(x1 + tanh(_a4_*(_a0_*_a7_**2 + x1))**(_a2_/(x1*(_a0_ + x1 + _a6_/_a1_))))**2))**x1)/x1)**x1
<lambdifygenerated-1687>:2: RuntimeWarning: invalid value encountered in sin
  return (sinh(tanh(x1**2*sin(x1*(x1 + tanh(_a4_*(_a0_*_a7_**2 + x1))**(_a2_/(x1*(_a0_ + x1 + _a6_/_a1_))))**2))**x1)/x1)**x1
<lambdifygenerated-1688>:2: RuntimeWarning: overflow encountered in power
  return (sinh(tanh(x1**2*sin(x1*(x1 + tanh(_a4_*(_a0_*_a7_**2 + x1))**(_a2_/(x1*(_a0_ + x1 + _a6_/_a1_))))**2))**x1)/x1)**x1
<lambdifygenerated-1688>:2: RuntimeWarning: invalid value encountered in power
  return (sinh(tanh(x1**2*sin(x1*(x1 + tanh(_a4_*(_a0_*_a7_**2 + x1))**(_a2_/(x1*(_a0_ + x1 + _a6_/_a1_))))**2))**x1)/x1)**x1
<lambdifygenerated-1688>:2: RuntimeWarning: invalid value encountered in sin
  return (sinh(tanh(x1**2*sin(x1*(x1 + tanh(_a4_*(_a0_*_a7_**2 + x1))**(_a2_/(x1*(_a0_ + x1 + _a6_/_a1_))))**2))**x1)/x1)**x1
<lambdifygenerated-1689>:2: RuntimeWarning: overflow encountered in power
  return (sinh(tanh(x1**2*sin(x1*(x1 + tanh(_a4_*(_a0_*_a7_**2 + x1))**(_a2_/(x1*(_a0_ + x1 + _a6_/_a1_))))**2))**x1)/x1)**x1
<lambdifygenerated-1689>:2: RuntimeWarning: invalid value encountered in power
  return (sinh(tanh(x1**2*sin(x1*(x1 + tanh(_a4_*(_a0_*_a7_**2 + x1))**(_a2_/(x1*(_a0_ + x1 + _a6_/_a1_))))**2))**x1)/x1)**x1
<lambdifygenerated-1689>:2: RuntimeWarning: invalid value encountered in sin
  return (sinh(tanh(x1**2*sin(x1*(x1 + tanh(_a4_*(_a0_*_a7_**2 + x1))**(_a2_/(x1*(_a0_ + x1 + _a6_/_a1_))))**2))**x1)/x1)**x1
<lambdifygenerated-1690>:2: RuntimeWarning: overflow encountered in power
  return (sinh(tanh(x1**2*sin(x1*(x1 + tanh(_a4_*(_a0_*_a7_**2 + x1))**(_a2_/(x1*(_a0_ + x1 + _a6_/_a1_))))**2))**x1)/x1)**x1
<lambdifygenerated-1690>:2: RuntimeWarning: invalid value encountered in power

interpolation

<lambdifygenerated-1706>:2: RuntimeWarning: invalid value encountered in power
  return (sinh(tanh(_a2_*_a4_*sin(_a5_*(_a3_ + tanh(_a4_*(_a0_*_a7_**2 + x1))**(_a2_/(_a5_*(_a6_/_a1_ + x1*(_a0_ + x1)/_a1_))))**2))**tan(_a5_))/x1)**x1
<lambdifygenerated-1707>:2: RuntimeWarning: invalid value encountered in power
  return (sinh(tanh(_a2_*_a4_*sin(_a5_*(_a3_ + tanh(_a4_*(_a0_*_a7_**2 + x1))**(_a2_/(_a5_*(_a6_/_a1_ + x1*(_a0_ + x1)/_a1_))))**2))**tan(_a5_))/_a7_)**x1
<lambdifygenerated-1708>:2: RuntimeWarning: invalid value encountered in power
  return (sinh(tanh(_a2_*_a4_*sin(_a5_*(_a3_ + tanh(_a4_*(_a0_*_a7_**2 + x1))**(_a2_/(_a5_*(_a6_/_a1_ + x1*(_a0_ + x1)/_a1_))))**2))**tan(_a5_))/_a7_)**x1
<lambdifygenerated-1709>:2: RuntimeWarning: invalid value encountered in power
  return (sinh(tanh(_a2_*_a4_*sin(_a5_*(_a3_ + tanh(_a4_*(_a0_*_a7_**2 + x1))**(_a2_/(_a5_*(_a6_/_a1_ + x1*(_a0_ + x1)/_a1_))))**2))**tan(_a5_))/_a7_)**_a7_
<lambdifygenerated-1710>:2: RuntimeWarning: invalid value encountered in power
  return (sinh(tanh(_a2_*_a4_*sin(_a5_*(_a3_ + tanh(_a4_*(_a0_*_a7_**2 + x1))**(_a2_/(_a5_*(_a6_/_a1_ + x1*(_a0_ + x1)/_a1_))))**2))**tan(_a5_))/_a7_)**_a7_
<lambdifygenerated-1711>:2: RuntimeWarning: invalid value encountered in power
  return x1*(sinh(tanh(_a2_*_a4_*sin(_a5_*(_a3_ + tanh(_a4_*(_a0_*_a7_**2 + x1))**(_a2_/(_a5_*(_a6_/_a1_ + x1*(_a0_ + x1)/_a1_))))**2))**tan(_a5_))/_a7_)**_a7_/_a4_
<lambdifygenerated-1712>:2: RuntimeWarning: invalid value encountered in power
  return x1*(sinh(tanh(_a2_*_a4_*sin(_a5_*(_a3_ + tanh(_a4_*(_a0_*_a7_**2 + x1))**(_a2_/(_a5_*(_a6_/_a1_ + x1*(_a0_ + x1)/_a1_))))**2))**tan(_a5_))/_a7_)**_a7_/_a4_
<lambdifygenerated-1713>:2: RuntimeWarning: invalid value encountered in power
  return _a7_*(sinh(tanh(_a2_*_a4_*sin(_a5_*(_a3_ + tanh(_a4_*(_a0_*_a7_**2 + x1))**(_a2_/(_a5_*(_a6_/_a1_ + x1*(_a0_ + x1)/_a1_))))**2))**tan(_a5_))/_a7_)**_a7_/_a4_
<lambdifygenerated-1714>:2: RuntimeWarning: invalid value encountered in power
  return _a7_*(sinh(tanh(_a2_*_a4_*sin(_a5_*(_a3_ + tanh(_a4_*(_a0_*_a7_**2 + x1))**(_a2_/(_a5_*(_a6_/_a1_ + x1*(_a0_ + x1)/_a1_))))**2))**tan(_a5_))/_a7_)**_a7_/_a4_
<lambdifygenerated-1715>:2: RuntimeWarning: invalid value encountered in power
  return _a7_*(sinh(tanh(_a2_*_a4_*sin(_a5_*(_a3_ + tanh(_a4_*(_a0_*_a7_**2 + x1))**(_a2_/(_a5_*(_a6_/_a1_ + x1*(_a0_ + x1)/_a1_))))**2))**tan(_a5_))/_a7_)**_a7_/_a4_
<lambdifygenerated-1716>:2: RuntimeWarning: invalid value encountered in power
  return _a7_*(sinh(tanh(_a2_*_a4_*sin(_a5_*(_a3_ + tanh(_a4_*(_a0_*_a7_**2 + x1))**(_a2_/(_a5_*(_a6_/_a1_ + x1*(_a0_ + x1)/_a1_))))**2))**tan(_a5_))/_a7_)**_a7_/_a4_
<lambdifygenerated-1717>:2: RuntimeWarning: invalid value encountered in power
  return _a7_*(sinh(tanh(_a2_*_a4_*sin(_a5_*(_a3_ + tanh(_a4_*(_a0_*_a7_**2 + x1))**(_a2_/(_a5_*(_a6_/_a1_ + x1*(_a0_ + x1)/_a1_))))**2))**tan(_a5_))/_a7_)**_a7_/_a4_
<lambdifygenerated-1718>:2: RuntimeWarning: invalid value encountered in power
  return _a7_*(sinh(tanh(_a2_*_a4_*sin(_a5_*(_a3_ + tanh(_a4_*(_a0_*_a7_**2 + x1))**(_a2_/(_a5_*(_a6_/_a1_ + x1*(_a0_ + x1)/_a1_))))**2))**tan(_a5_))/_a7_)**_a7_/_a4_

         x1         y  rep    ymodel      ybms
3745  0.997  0.215897  6.0  0.215308  0.216198
3746  0.998  0.216041  6.0  0.215445  0.216343
3747  0.998  0.216186  6.0  0.215581  0.216488
3748  0.999  0.216330  6.0  0.215716  0.216632

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.216618  6.0  0.215987  0.216921
3751  1.002  0.216762  6.0  0.216123  0.217065
3752  1.002  0.216905  6.0  0.216257  0.217209
3753  1.003  0.217048  6.0  0.216392  0.217353

3750

<lambdifygenerated-1739>:2: RuntimeWarning: overflow encountered in sinh
  return tanh(abs(sinh(sinh(exp(x1)))))/x1**2
<lambdifygenerated-1740>:2: RuntimeWarning: overflow encountered in sinh
  return tanh(abs(sinh(sinh(exp(x1)))))/x1**2
<lambdifygenerated-1741>:2: RuntimeWarning: overflow encountered in sinh
  return tanh(abs(sinh(sinh(exp(2*x1)))))/x1**2
<lambdifygenerated-1742>:2: RuntimeWarning: overflow encountered in sinh
  return tanh(abs(sinh(sinh(exp(2*x1)))))/x1**2
<lambdifygenerated-1743>:2: RuntimeWarning: overflow encountered in sinh
  return tanh(abs(sinh(sinh(exp(x1**2 + x1)))))/x1**2
<lambdifygenerated-1744>:2: RuntimeWarning: overflow encountered in sinh
  return tanh(abs(sinh(sinh(exp(x1**2 + x1)))))/x1**2
<lambdifygenerated-1745>:2: RuntimeWarning: overflow encountered in sinh
  return tanh(abs(sinh(sinh(exp(x1*tanh(x1) + x1)))))/x1**2
<lambdifygenerated-1746>:2: RuntimeWarning: overflow encountered in sinh
  return tanh(abs(sinh(sinh(exp(x1*tanh(x1) + x1)))))/x1**2
<lambdifygenerated-1747>:2: RuntimeWarning: overflow encountered in sinh
  return tanh(abs(sinh(sinh(exp(x1*tanh(sin(x1)) + x1)))))/x1**2
<lambdifygenerated-1748>:2: RuntimeWarning: overflow encountered in sinh
  return tanh(abs(sinh(sinh(exp(x1*tanh(sin(x1)) + x1)))))/x1**2
<lambdifygenerated-1753>:2: RuntimeWarning: invalid value encountered in power
  return tanh(abs(sinh(sinh(exp(x1*tanh(sin(x1*x1**x1 + x1)) + x1)))))/x1**2
<lambdifygenerated-1753>:2: RuntimeWarning: overflow encountered in sinh
  return tanh(abs(sinh(sinh(exp(x1*tanh(sin(x1*x1**x1 + x1)) + x1)))))/x1**2
<lambdifygenerated-1754>:2: RuntimeWarning: invalid value encountered in power
  return tanh(abs(sinh(sinh(exp(x1*tanh(sin(x1*x1**x1 + x1)) + x1)))))/x1**2
<lambdifygenerated-1754>:2: RuntimeWarning: overflow encountered in sinh
  return tanh(abs(sinh(sinh(exp(x1*tanh(sin(x1*x1**x1 + x1)) + x1)))))/x1**2
<lambdifygenerated-1755>:2: RuntimeWarning: invalid value encountered in power
  return tanh(abs(sinh(sinh(exp(x1*tanh(sin(x1*(2*x1)**x1 + x1)) + x1)))))/x1**2
<lambdifygenerated-1755>:2: RuntimeWarning: overflow encountered in sinh
  return tanh(abs(sinh(sinh(exp(x1*tanh(sin(x1*(2*x1)**x1 + x1)) + x1)))))/x1**2
<lambdifygenerated-1756>:2: RuntimeWarning: invalid value encountered in power
  return tanh(abs(sinh(sinh(exp(x1*tanh(sin(x1*(2*x1)**x1 + x1)) + x1)))))/x1**2
<lambdifygenerated-1756>:2: RuntimeWarning: overflow encountered in sinh
  return tanh(abs(sinh(sinh(exp(x1*tanh(sin(x1*(2*x1)**x1 + x1)) + x1)))))/x1**2
<lambdifygenerated-1757>:2: RuntimeWarning: invalid value encountered in power
  return tanh(abs(sinh(sinh(exp(x1*tanh(sin(x1*(_a1_ + x1)**x1 + x1)) + x1)))))/x1**2
<lambdifygenerated-1757>:2: RuntimeWarning: overflow encountered in sinh
  return tanh(abs(sinh(sinh(exp(x1*tanh(sin(x1*(_a1_ + x1)**x1 + x1)) + x1)))))/x1**2
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-1758>:2: RuntimeWarning: invalid value encountered in power
  return tanh(abs(sinh(sinh(exp(x1*tanh(sin(x1*(_a1_ + x1)**x1 + x1)) + x1)))))/x1**2
<lambdifygenerated-1758>:2: RuntimeWarning: overflow encountered in sinh
  return tanh(abs(sinh(sinh(exp(x1*tanh(sin(x1*(_a1_ + x1)**x1 + x1)) + x1)))))/x1**2
<lambdifygenerated-1759>:2: RuntimeWarning: invalid value encountered in power
  return tanh(abs(sinh(sinh(exp(x1*tanh(sin(x1*(_a1_ + x1**x1)**x1 + x1)) + x1)))))/x1**2
<lambdifygenerated-1759>:2: RuntimeWarning: overflow encountered in sinh
  return tanh(abs(sinh(sinh(exp(x1*tanh(sin(x1*(_a1_ + x1**x1)**x1 + x1)) + x1)))))/x1**2
<lambdifygenerated-1760>:2: RuntimeWarning: invalid value encountered in power
  return tanh(abs(sinh(sinh(exp(x1*tanh(sin(x1*(_a1_ + x1**x1)**x1 + x1)) + x1)))))/x1**2
<lambdifygenerated-1760>:2: RuntimeWarning: overflow encountered in sinh
  return tanh(abs(sinh(sinh(exp(x1*tanh(sin(x1*(_a1_ + x1**x1)**x1 + x1)) + x1)))))/x1**2
<lambdifygenerated-1761>:2: RuntimeWarning: invalid value encountered in power
  return tanh(abs(sinh(sinh(exp(x1*tanh(sin(x1*(_a1_ + cos(x1)**x1)**x1 + x1)) + x1)))))/x1**2
<lambdifygenerated-1762>:2: RuntimeWarning: invalid value encountered in power
  return tanh(abs(sinh(sinh(exp(x1*tanh(sin(x1*(_a1_ + cos(x1)**x1)**x1 + x1)) + x1)))))/x1**2
<lambdifygenerated-1763>:2: RuntimeWarning: invalid value encountered in power
  return tanh(abs(sinh(sinh(exp(x1*tanh(sin(x1*(_a1_ + cos(1)**x1)**x1 + x1)) + x1)))))/x1**2
<lambdifygenerated-1765>:2: RuntimeWarning: invalid value encountered in power
  return tanh(abs(sinh(sinh(exp(x1*tanh(sin(x1*(_a1_ + cos(_a4_/x1)**x1)**x1 + x1)) + x1)))))/x1**2
<lambdifygenerated-1765>:2: RuntimeWarning: overflow encountered in sinh
  return tanh(abs(sinh(sinh(exp(x1*tanh(sin(x1*(_a1_ + cos(_a4_/x1)**x1)**x1 + x1)) + x1)))))/x1**2
<lambdifygenerated-1766>:2: RuntimeWarning: invalid value encountered in power
  return tanh(abs(sinh(sinh(exp(x1*tanh(sin(x1*(_a1_ + cos(_a4_/x1)**x1)**x1 + x1)) + x1)))))/x1**2
<lambdifygenerated-1766>:2: RuntimeWarning: overflow encountered in sinh
  return tanh(abs(sinh(sinh(exp(x1*tanh(sin(x1*(_a1_ + cos(_a4_/x1)**x1)**x1 + x1)) + x1)))))/x1**2
<lambdifygenerated-1767>:2: RuntimeWarning: invalid value encountered in power
  return tanh(abs(sinh(sinh(exp(x1*tanh(sin(x1*(_a1_ + cos(_a4_/_a0_)**x1)**x1 + x1)) + x1)))))/x1**2
<lambdifygenerated-1769>:2: RuntimeWarning: overflow encountered in sinh
  return tanh(abs(sinh(sinh(exp(x1*tanh(sin(x1*(_a1_ + cos(_a4_/_a0_)**(x1**2))**x1 + x1)) + x1)))))/x1**2
<lambdifygenerated-1771>:2: RuntimeWarning: overflow encountered in sinh
  return tanh(abs(sinh(sinh(exp(x1*tanh(sin(x1*(_a1_ + cos(_a4_/_a0_)**(4*x1**2))**x1 + x1)) + x1)))))/x1**2
<lambdifygenerated-1773>:2: RuntimeWarning: overflow encountered in sinh
  return tanh(abs(sinh(sinh(exp(x1*tanh(sin(x1*(_a1_ + cos(_a4_/_a0_)**((x1 + tan(x1))**2))**x1 + x1)) + x1)))))/x1**2
<lambdifygenerated-1774>:2: RuntimeWarning: overflow encountered in sinh
  return tanh(abs(sinh(sinh(exp(x1*tanh(sin(x1*(_a1_ + cos(_a4_/_a0_)**((x1 + tan(x1))**2))**x1 + x1)) + x1)))))/x1**2
<lambdifygenerated-1775>:2: RuntimeWarning: overflow encountered in sinh
  return tanh(abs(sinh(sinh(exp(x1*tanh(sin(x1*(_a1_ + cos(_a4_/_a0_)**((x1 + tan(x1))**2))**x1 + x1)) + x1)))))/x1**2
<lambdifygenerated-1776>:2: RuntimeWarning: overflow encountered in sinh
  return tanh(abs(sinh(sinh(exp(x1*tanh(sin(x1*(_a1_ + cos(_a4_/_a0_)**((x1 + tan(x1))**2))**x1 + x1)) + x1)))))/x1**2
<lambdifygenerated-1777>:2: RuntimeWarning: invalid value encountered in power
  return tanh(abs(sinh(sinh(exp(x1*tanh(sin(x1*(_a1_ + cos(_a4_/_a0_)**((_a0_ + tan(x1))**2))**x1 + x1)) + x1)))))/x1**2
<lambdifygenerated-1779>:2: RuntimeWarning: invalid value encountered in power
  return tanh(abs(sinh(sinh(exp(x1*tanh(sin(x1*(_a1_ + cos(_a4_/_a0_)**((_a0_ + tan(x1))**2))**(x1**x1) + x1)) + x1)))))/x1**2
<lambdifygenerated-1779>:2: RuntimeWarning: overflow encountered in sinh
  return tanh(abs(sinh(sinh(exp(x1*tanh(sin(x1*(_a1_ + cos(_a4_/_a0_)**((_a0_ + tan(x1))**2))**(x1**x1) + x1)) + x1)))))/x1**2
<lambdifygenerated-1780>:2: RuntimeWarning: invalid value encountered in power
  return tanh(abs(sinh(sinh(exp(x1*tanh(sin(x1*(_a1_ + cos(_a4_/_a0_)**((_a0_ + tan(x1))**2))**(x1**x1) + x1)) + x1)))))/x1**2
<lambdifygenerated-1780>:2: RuntimeWarning: overflow encountered in sinh
  return tanh(abs(sinh(sinh(exp(x1*tanh(sin(x1*(_a1_ + cos(_a4_/_a0_)**((_a0_ + tan(x1))**2))**(x1**x1) + x1)) + x1)))))/x1**2
<lambdifygenerated-1781>:2: RuntimeWarning: overflow encountered in sinh
  return tanh(abs(sinh(sinh(exp(x1*tanh(sin(x1*(_a1_ + cos(_a4_/_a0_)**((_a0_ + tan(x1))**2))**((x1**2)**x1) + x1)) + x1)))))/x1**2
<lambdifygenerated-1781>:2: RuntimeWarning: invalid value encountered in power
  return tanh(abs(sinh(sinh(exp(x1*tanh(sin(x1*(_a1_ + cos(_a4_/_a0_)**((_a0_ + tan(x1))**2))**((x1**2)**x1) + x1)) + x1)))))/x1**2
<lambdifygenerated-1782>:2: RuntimeWarning: overflow encountered in sinh
  return tanh(abs(sinh(sinh(exp(x1*tanh(sin(x1*(_a1_ + cos(_a4_/_a0_)**((_a0_ + tan(x1))**2))**((x1**2)**x1) + x1)) + x1)))))/x1**2
<lambdifygenerated-1783>:2: RuntimeWarning: invalid value encountered in power
  return tanh(abs(sinh(sinh(exp(x1*tanh(sin(x1*(_a1_ + cos(_a4_/_a0_)**((_a0_ + tan(x1))**2))**((_a4_*x1)**x1) + x1)) + x1)))))/x1**2
<lambdifygenerated-1783>:2: RuntimeWarning: overflow encountered in sinh
  return tanh(abs(sinh(sinh(exp(x1*tanh(sin(x1*(_a1_ + cos(_a4_/_a0_)**((_a0_ + tan(x1))**2))**((_a4_*x1)**x1) + x1)) + x1)))))/x1**2
<lambdifygenerated-1784>:2: RuntimeWarning: invalid value encountered in power
  return tanh(abs(sinh(sinh(exp(x1*tanh(sin(x1*(_a1_ + cos(_a4_/_a0_)**((_a0_ + tan(x1))**2))**((_a4_*x1)**x1) + x1)) + x1)))))/x1**2
<lambdifygenerated-1784>:2: RuntimeWarning: overflow encountered in sinh
  return tanh(abs(sinh(sinh(exp(x1*tanh(sin(x1*(_a1_ + cos(_a4_/_a0_)**((_a0_ + tan(x1))**2))**((_a4_*x1)**x1) + x1)) + x1)))))/x1**2
<lambdifygenerated-1785>:2: RuntimeWarning: invalid value encountered in power
  return tanh(abs(sinh(sinh(exp(x1*tanh(sin(x1*(_a1_ + cos(_a4_/_a0_)**((_a0_ + tan(x1))**2))**((_a4_*_a6_)**x1) + x1)) + x1)))))/x1**2
<lambdifygenerated-1789>:2: RuntimeWarning: overflow encountered in sinh
  return tanh(abs(sinh(sinh(exp(x1*tanh(sin(_a5_*(_a1_ + cos(_a4_/_a0_)**((_a0_ + tan(x1))**2))**((_a4_*_a6_)**x1) + x1)) + x1)))))/x1**2
<lambdifygenerated-1789>:2: RuntimeWarning: overflow encountered in power
  return tanh(abs(sinh(sinh(exp(x1*tanh(sin(_a5_*(_a1_ + cos(_a4_/_a0_)**((_a0_ + tan(x1))**2))**((_a4_*_a6_)**x1) + x1)) + x1)))))/x1**2
<lambdifygenerated-1789>:2: RuntimeWarning: invalid value encountered in sin
  return tanh(abs(sinh(sinh(exp(x1*tanh(sin(_a5_*(_a1_ + cos(_a4_/_a0_)**((_a0_ + tan(x1))**2))**((_a4_*_a6_)**x1) + x1)) + x1)))))/x1**2
<lambdifygenerated-1790>:2: RuntimeWarning: overflow encountered in sinh
  return tanh(abs(sinh(sinh(exp(x1*tanh(sin(_a5_*(_a1_ + cos(_a4_/_a0_)**((_a0_ + tan(x1))**2))**((_a4_*_a6_)**x1) + x1)) + x1)))))/x1**2
<lambdifygenerated-1791>:2: RuntimeWarning: invalid value encountered in power
  return tanh(abs(sinh(sinh(exp(x1*tanh(sin(_a5_*(_a1_ + cos(_a4_/_a0_)**((_a0_ + tan(x1))**2))**((_a4_*_a6_)**x1) + x1**2)) + x1)))))/x1**2
<lambdifygenerated-1793>:2: RuntimeWarning: overflow encountered in sinh
  return tanh(abs(sinh(sinh(exp(x1*tanh(sin(_a5_*(_a1_ + cos(_a4_/_a0_)**((_a0_ + tan(x1))**2))**((_a4_*_a6_)**x1) + 2*x1**2)) + x1)))))/x1**2
<lambdifygenerated-1793>:2: RuntimeWarning: invalid value encountered in power
  return tanh(abs(sinh(sinh(exp(x1*tanh(sin(_a5_*(_a1_ + cos(_a4_/_a0_)**((_a0_ + tan(x1))**2))**((_a4_*_a6_)**x1) + 2*x1**2)) + x1)))))/x1**2
<lambdifygenerated-1794>:2: RuntimeWarning: overflow encountered in sinh
  return tanh(abs(sinh(sinh(exp(x1*tanh(sin(_a5_*(_a1_ + cos(_a4_/_a0_)**((_a0_ + tan(x1))**2))**((_a4_*_a6_)**x1) + 2*x1**2)) + x1)))))/x1**2
<lambdifygenerated-1795>:2: RuntimeWarning: overflow encountered in sinh
  return tanh(abs(sinh(sinh(exp(x1*tanh(sin(_a5_*(_a1_ + cos(_a4_/_a0_)**((_a0_ + tan(x1))**2))**((_a4_*_a6_)**x1) + x1*(x1 + sin(x1)))) + x1)))))/x1**2
<lambdifygenerated-1795>:2: RuntimeWarning: invalid value encountered in power
  return tanh(abs(sinh(sinh(exp(x1*tanh(sin(_a5_*(_a1_ + cos(_a4_/_a0_)**((_a0_ + tan(x1))**2))**((_a4_*_a6_)**x1) + x1*(x1 + sin(x1)))) + x1)))))/x1**2
<lambdifygenerated-1796>:2: RuntimeWarning: overflow encountered in sinh
  return tanh(abs(sinh(sinh(exp(x1*tanh(sin(_a5_*(_a1_ + cos(_a4_/_a0_)**((_a0_ + tan(x1))**2))**((_a4_*_a6_)**x1) + x1*(x1 + sin(x1)))) + x1)))))/x1**2
<lambdifygenerated-1797>:2: RuntimeWarning: invalid value encountered in power
  return tanh(abs(sinh(sinh(exp(x1*tanh(sin(_a5_*(_a1_ + cos(_a4_/_a0_)**((_a0_ + tan(x1))**2))**((_a4_*_a6_)**x1) + x1*(x1 + sin(x1**2)))) + x1)))))/x1**2
<lambdifygenerated-1799>:2: RuntimeWarning: overflow encountered in sinh
  return tanh(abs(sinh(sinh(exp(x1*tanh(sin(_a5_*(_a1_ + cos(_a4_/_a0_)**((_a0_ + tan(x1))**2))**((_a4_*_a6_)**x1) + x1*(x1 + sin(2*x1**2)))) + x1)))))/x1**2
<lambdifygenerated-1799>:2: RuntimeWarning: invalid value encountered in power
  return tanh(abs(sinh(sinh(exp(x1*tanh(sin(_a5_*(_a1_ + cos(_a4_/_a0_)**((_a0_ + tan(x1))**2))**((_a4_*_a6_)**x1) + x1*(x1 + sin(2*x1**2)))) + x1)))))/x1**2
<lambdifygenerated-1800>:2: RuntimeWarning: overflow encountered in sinh
  return tanh(abs(sinh(sinh(exp(x1*tanh(sin(_a5_*(_a1_ + cos(_a4_/_a0_)**((_a0_ + tan(x1))**2))**((_a4_*_a6_)**x1) + x1*(x1 + sin(2*x1**2)))) + x1)))))/x1**2
<lambdifygenerated-1801>:2: RuntimeWarning: overflow encountered in sinh
  return tanh(abs(sinh(sinh(exp(x1*tanh(sin(_a5_*(_a1_ + cos(_a4_/_a0_)**((_a0_ + tan(x1))**2))**((_a4_*_a6_)**x1) + x1*(x1 + sin(2*x1**2)))) + x1)))))/x1**2
<lambdifygenerated-1802>:2: RuntimeWarning: overflow encountered in sinh
  return tanh(abs(sinh(sinh(exp(x1*tanh(sin(_a5_*(_a1_ + cos(_a4_/_a0_)**((_a0_ + tan(x1))**2))**((_a4_*_a6_)**x1) + x1*(x1 + sin(2*x1**2)))) + x1)))))/x1**2
<lambdifygenerated-1803>:2: RuntimeWarning: overflow encountered in sinh
  return tanh(abs(sinh(sinh(exp(x1*tanh(sin(_a5_*(_a1_ + cos(_a4_/_a0_)**((_a0_ + tan(x1))**2))**((_a4_*_a6_)**x1) + x1*(x1 + sin(x1*(_a3_ + x1))))) + x1)))))/x1**2
<lambdifygenerated-1803>:2: RuntimeWarning: invalid value encountered in power
  return tanh(abs(sinh(sinh(exp(x1*tanh(sin(_a5_*(_a1_ + cos(_a4_/_a0_)**((_a0_ + tan(x1))**2))**((_a4_*_a6_)**x1) + x1*(x1 + sin(x1*(_a3_ + x1))))) + x1)))))/x1**2
<lambdifygenerated-1804>:2: RuntimeWarning: overflow encountered in sinh
  return tanh(abs(sinh(sinh(exp(x1*tanh(sin(_a5_*(_a1_ + cos(_a4_/_a0_)**((_a0_ + tan(x1))**2))**((_a4_*_a6_)**x1) + x1*(x1 + sin(x1*(_a3_ + x1))))) + x1)))))/x1**2
<lambdifygenerated-1805>:2: RuntimeWarning: invalid value encountered in power
  return tanh(abs(sinh(sinh(exp(x1*tanh(sin(_a5_*(_a1_ + cos(_a4_/_a0_)**((_a0_ + tan(x1))**2))**((_a4_*_a6_)**x1) + x1*(x1 + sin(_a7_*(_a3_ + x1))))) + x1)))))/x1**2
<lambdifygenerated-1809>:2: RuntimeWarning: invalid value encountered in power
  return tanh(abs(sinh(sinh(exp(x1*tanh(sin(_a4_*(x1 + sin(_a7_*(_a3_ + x1))) + _a5_*(_a1_ + cos(_a4_/_a0_)**((_a0_ + tan(x1))**2))**((_a4_*_a6_)**x1))) + x1)))))/x1**2
<lambdifygenerated-1811>:2: RuntimeWarning: invalid value encountered in power
  return tanh(abs(sinh(sinh(exp(_a6_*tanh(sin(_a4_*(x1 + sin(_a7_*(_a3_ + x1))) + _a5_*(_a1_ + cos(_a4_/_a0_)**((_a0_ + tan(x1))**2))**((_a4_*_a6_)**x1))) + x1)))))/x1**2
<lambdifygenerated-1811>:2: RuntimeWarning: overflow encountered in sinh
  return tanh(abs(sinh(sinh(exp(_a6_*tanh(sin(_a4_*(x1 + sin(_a7_*(_a3_ + x1))) + _a5_*(_a1_ + cos(_a4_/_a0_)**((_a0_ + tan(x1))**2))**((_a4_*_a6_)**x1))) + x1)))))/x1**2
<lambdifygenerated-1813>:2: RuntimeWarning: invalid value encountered in power
  return tanh(abs(sinh(sinh(exp(_a2_ + _a6_*tanh(sin(_a4_*(x1 + sin(_a7_*(_a3_ + x1))) + _a5_*(_a1_ + cos(_a4_/_a0_)**((_a0_ + tan(x1))**2))**((_a4_*_a6_)**x1))))))))/x1**2
<lambdifygenerated-1815>:2: RuntimeWarning: invalid value encountered in power
  return tanh(abs(_a1_*sinh(sinh(exp(_a2_ + _a6_*tanh(sin(_a4_*(x1 + sin(_a7_*(_a3_ + x1))) + _a5_*(_a1_ + cos(_a4_/_a0_)**((_a0_ + tan(x1))**2))**((_a4_*_a6_)**x1))))))/x1))/x1**2
<lambdifygenerated-1817>:2: RuntimeWarning: invalid value encountered in power
  return tanh(abs(_a1_*sinh(sinh(exp(_a2_ + _a6_*tanh(sin(_a4_*(x1 + sin(_a7_*(_a3_ + x1))) + _a5_*(_a1_ + cos(_a4_/_a0_)**((_a0_ + tan(x1))**2))**((_a4_*_a6_)**x1))))))/_a6_))/x1**2
<lambdifygenerated-1819>:2: RuntimeWarning: invalid value encountered in power
  return tanh(abs(_a1_*sinh(sinh(exp(_a2_ + _a6_*tanh(sin(_a4_*(x1 + sin(_a7_*(_a3_ + x1))) + _a5_*(_a1_ + cos(_a4_/_a0_)**((_a0_ + tan(x1))**2))**((_a4_*_a6_)**x1))))))/_a6_))/(_a4_*x1)
<lambdifygenerated-1821>:2: RuntimeWarning: invalid value encountered in power
  return tanh(abs(_a1_*sinh(sinh(exp(_a2_ + _a6_*tanh(sin(_a4_*(x1 + sin(_a7_*(_a3_ + x1))) + _a5_*(_a1_ + cos(_a4_/_a0_)**((_a0_ + tan(x1))**2))**((_a4_*_a6_)**x1))))))/_a6_))/_a4_**2
<lambdifygenerated-1821>:2: RuntimeWarning: overflow encountered in sinh
  return tanh(abs(_a1_*sinh(sinh(exp(_a2_ + _a6_*tanh(sin(_a4_*(x1 + sin(_a7_*(_a3_ + x1))) + _a5_*(_a1_ + cos(_a4_/_a0_)**((_a0_ + tan(x1))**2))**((_a4_*_a6_)**x1))))))/_a6_))/_a4_**2
<lambdifygenerated-1825>:2: RuntimeWarning: invalid value encountered in power
  return tanh(abs(_a1_*sinh(sinh(exp(_a2_ + _a6_*tanh(sin(_a4_*(x1 + sin(_a7_*(_a3_ + x1))) + _a5_*(_a1_ + cos(_a4_/_a0_)**((_a0_ + tan(x1))**2))**((_a4_*_a6_)**x1))))))/_a6_))/_a4_**2
<lambdifygenerated-1825>:2: RuntimeWarning: overflow encountered in sinh
  return tanh(abs(_a1_*sinh(sinh(exp(_a2_ + _a6_*tanh(sin(_a4_*(x1 + sin(_a7_*(_a3_ + x1))) + _a5_*(_a1_ + cos(_a4_/_a0_)**((_a0_ + tan(x1))**2))**((_a4_*_a6_)**x1))))))/_a6_))/_a4_**2

interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.100918  7.0  0.100272  0.100924
3746  0.998  0.100912  7.0  0.100258  0.100919
3747  0.998  0.100906  7.0  0.100245  0.100914
3748  0.999  0.100901  7.0  0.100231  0.100909

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.100890  7.0  0.100203  0.100900
3751  1.002  0.100885  7.0  0.100189  0.100895
3752  1.002  0.100880  7.0  0.100175  0.100891
3753  1.003  0.100874  7.0  0.100161  0.100886

3750

<lambdifygenerated-1833>:2: RuntimeWarning: invalid value encountered in power
  return x1*x1**x1
<lambdifygenerated-1834>:2: RuntimeWarning: invalid value encountered in power
  return x1*x1**x1
<lambdifygenerated-1835>:2: RuntimeWarning: invalid value encountered in power
  return x1*(2*x1)**x1
<lambdifygenerated-1836>:2: RuntimeWarning: invalid value encountered in power
  return x1*(2*x1)**x1
<lambdifygenerated-1837>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1 + x1**x1)**x1
<lambdifygenerated-1838>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1 + x1**x1)**x1
<lambdifygenerated-1839>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1 + (2*x1)**x1)**x1
<lambdifygenerated-1840>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1 + (2*x1)**x1)**x1
<lambdifygenerated-1841>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1 + (x1**2 + x1)**x1)**x1
<lambdifygenerated-1842>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1 + (x1**2 + x1)**x1)**x1
<lambdifygenerated-1843>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1 + (x1**3 + x1)**x1)**x1
<lambdifygenerated-1844>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1 + (x1**3 + x1)**x1)**x1
<lambdifygenerated-1845>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1 + (x1**2*tanh(x1) + x1)**x1)**x1
<lambdifygenerated-1846>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1 + (x1**2*tanh(x1) + x1)**x1)**x1
<lambdifygenerated-1847>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1 + (x1**2*tanh(x1**3) + x1)**x1)**x1
<lambdifygenerated-1848>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1 + (x1**2*tanh(x1**3) + x1)**x1)**x1
<lambdifygenerated-1849>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1 + (x1**2*tanh(8*x1**3) + x1)**x1)**x1
<lambdifygenerated-1850>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1 + (x1**2*tanh(8*x1**3) + x1)**x1)**x1
<lambdifygenerated-1851>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1 + (x1**2*tanh((_a5_ + x1)**3) + x1)**x1)**x1
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-1852>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1 + (x1**2*tanh((_a5_ + x1)**3) + x1)**x1)**x1
<lambdifygenerated-1853>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1 + (x1**2*tanh((_a5_ + x1**2)**3) + x1)**x1)**x1
<lambdifygenerated-1854>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1 + (x1**2*tanh((_a5_ + x1**2)**3) + x1)**x1)**x1
<lambdifygenerated-1855>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1 + (x1**2*tanh((_a5_ + x1**2)**3) + x1)**x1)**x1
<lambdifygenerated-1856>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1 + (x1**2*tanh((_a5_ + x1**2)**3) + x1)**x1)**x1
<lambdifygenerated-1857>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1 + (x1**2*tanh((_a5_ + x1**3)**3) + x1)**x1)**x1
<lambdifygenerated-1858>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1 + (x1**2*tanh((_a5_ + x1**3)**3) + x1)**x1)**x1
<lambdifygenerated-1859>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1 + (x1**2*tanh((_a5_ + _a7_*x1**2)**3) + x1)**x1)**x1
<lambdifygenerated-1860>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1 + (x1**2*tanh((_a5_ + _a7_*x1**2)**3) + x1)**x1)**x1
<lambdifygenerated-1861>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1 + (x1**2*tanh((_a5_ + _a7_*x1*cosh(x1))**3) + x1)**x1)**x1
<lambdifygenerated-1862>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1 + (x1**2*tanh((_a5_ + _a7_*x1*cosh(x1))**3) + x1)**x1)**x1
<lambdifygenerated-1863>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1 + (x1**2*tanh((_a5_ + _a7_*x1*cosh(x1**x1))**3) + x1)**x1)**x1
<lambdifygenerated-1864>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1 + (x1**2*tanh((_a5_ + _a7_*x1*cosh(x1**x1))**3) + x1)**x1)**x1
<lambdifygenerated-1865>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1 + (x1**2*tanh((_a5_ + _a7_*x1*cosh(_a0_**x1))**3) + x1)**x1)**x1
<lambdifygenerated-1866>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1 + (x1**2*tanh((_a5_ + _a7_*x1*cosh(_a0_**x1))**3) + x1)**x1)**x1
<lambdifygenerated-1867>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1 + (x1**2*tanh((_a5_ + _a7_*x1*cosh(_a0_**cos(x1)))**3) + x1)**x1)**x1
<lambdifygenerated-1868>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1 + (x1**2*tanh((_a5_ + _a7_*x1*cosh(_a0_**cos(x1)))**3) + x1)**x1)**x1
<lambdifygenerated-1869>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1 + (x1**2*tanh((_a5_ + _a7_*x1*cosh(_a0_**cos(1)))**3) + x1)**x1)**x1
<lambdifygenerated-1870>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1 + (x1**2*tanh((_a5_ + _a7_*x1*cosh(_a0_**cos(1)))**3) + x1)**x1)**x1
<lambdifygenerated-1871>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1 + (x1**2*tanh((_a5_ + _a7_*x1*cosh(_a0_**cos(1)))**3) + x1)**x1)**x1
<lambdifygenerated-1872>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1 + (x1**2*tanh((_a5_ + _a7_*x1*cosh(_a0_**cos(1)))**3) + x1)**x1)**x1
<lambdifygenerated-1873>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1 + (x1**2*tanh((_a5_ + _a7_*x1*cosh(_a0_**cos(x1/_a1_)))**3) + x1)**x1)**x1
<lambdifygenerated-1874>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1 + (x1**2*tanh((_a5_ + _a7_*x1*cosh(_a0_**cos(x1/_a1_)))**3) + x1)**x1)**x1
<lambdifygenerated-1875>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1 + (2*x1**2*tanh((_a5_ + _a7_*x1*cosh(_a0_**cos(x1/_a1_)))**3) + x1)**x1)**x1
<lambdifygenerated-1876>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1 + (2*x1**2*tanh((_a5_ + _a7_*x1*cosh(_a0_**cos(x1/_a1_)))**3) + x1)**x1)**x1
<lambdifygenerated-1877>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1 + (x1*(x1 + x1**x1)*tanh((_a5_ + _a7_*x1*cosh(_a0_**cos(x1/_a1_)))**3) + x1)**x1)**x1
<lambdifygenerated-1878>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1 + (x1*(x1 + x1**x1)*tanh((_a5_ + _a7_*x1*cosh(_a0_**cos(x1/_a1_)))**3) + x1)**x1)**x1
<lambdifygenerated-1879>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1 + (x1*(x1 + (x1**2)**x1)*tanh((_a5_ + _a7_*x1*cosh(_a0_**cos(x1/_a1_)))**3) + x1)**x1)**x1
<lambdifygenerated-1880>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1 + (x1*(x1 + (x1**2)**x1)*tanh((_a5_ + _a7_*x1*cosh(_a0_**cos(x1/_a1_)))**3) + x1)**x1)**x1
<lambdifygenerated-1881>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1 + (x1*(x1 + (_a7_*x1)**x1)*tanh((_a5_ + _a7_*x1*cosh(_a0_**cos(x1/_a1_)))**3) + x1)**x1)**x1
<lambdifygenerated-1882>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1 + (x1*(x1 + (_a7_*x1)**x1)*tanh((_a5_ + _a7_*x1*cosh(_a0_**cos(x1/_a1_)))**3) + x1)**x1)**x1
<lambdifygenerated-1883>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1 + (x1*(x1 + (_a4_*_a7_)**x1)*tanh((_a5_ + _a7_*x1*cosh(_a0_**cos(x1/_a1_)))**3) + x1)**x1)**x1
<lambdifygenerated-1884>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1 + (x1*(x1 + (_a4_*_a7_)**x1)*tanh((_a5_ + _a7_*x1*cosh(_a0_**cos(x1/_a1_)))**3) + x1)**x1)**x1
<lambdifygenerated-1885>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1 + (x1*(x1 + (_a4_*_a7_)**_a4_)*tanh((_a5_ + _a7_*x1*cosh(_a0_**cos(x1/_a1_)))**3) + x1)**x1)**x1
<lambdifygenerated-1886>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1 + (x1*(x1 + (_a4_*_a7_)**_a4_)*tanh((_a5_ + _a7_*x1*cosh(_a0_**cos(x1/_a1_)))**3) + x1)**x1)**x1
<lambdifygenerated-1887>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1 + (x1*((_a4_*_a7_)**_a4_ + tanh(x1))*tanh((_a5_ + _a7_*x1*cosh(_a0_**cos(x1/_a1_)))**3) + x1)**x1)**x1
<lambdifygenerated-1888>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1 + (x1*((_a4_*_a7_)**_a4_ + tanh(x1))*tanh((_a5_ + _a7_*x1*cosh(_a0_**cos(x1/_a1_)))**3) + x1)**x1)**x1
<lambdifygenerated-1889>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1 + (x1*((_a4_*_a7_)**_a4_ + tanh(x1))*tanh((_a5_ + _a7_*x1*cosh(_a0_**cos(x1/_a1_)))**3) + x1)**x1)**x1
<lambdifygenerated-1890>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1 + (x1*((_a4_*_a7_)**_a4_ + tanh(x1))*tanh((_a5_ + _a7_*x1*cosh(_a0_**cos(x1/_a1_)))**3) + x1)**x1)**x1
<lambdifygenerated-1891>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1 + (2*x1*((_a4_*_a7_)**_a4_ + tanh(x1))*tanh((_a5_ + _a7_*x1*cosh(_a0_**cos(x1/_a1_)))**3) + x1)**x1)**x1
<lambdifygenerated-1892>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1 + (2*x1*((_a4_*_a7_)**_a4_ + tanh(x1))*tanh((_a5_ + _a7_*x1*cosh(_a0_**cos(x1/_a1_)))**3) + x1)**x1)**x1
<lambdifygenerated-1893>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1 + (x1 + (_a6_ + x1)*((_a4_*_a7_)**_a4_ + tanh(x1))*tanh((_a5_ + _a7_*x1*cosh(_a0_**cos(x1/_a1_)))**3))**x1)**x1
<lambdifygenerated-1894>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1 + (x1 + (_a6_ + x1)*((_a4_*_a7_)**_a4_ + tanh(x1))*tanh((_a5_ + _a7_*x1*cosh(_a0_**cos(x1/_a1_)))**3))**x1)**x1
<lambdifygenerated-1895>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1 + (x1 + (_a6_ + x1**2)*((_a4_*_a7_)**_a4_ + tanh(x1))*tanh((_a5_ + _a7_*x1*cosh(_a0_**cos(x1/_a1_)))**3))**x1)**x1
<lambdifygenerated-1896>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1 + (x1 + (_a6_ + x1**2)*((_a4_*_a7_)**_a4_ + tanh(x1))*tanh((_a5_ + _a7_*x1*cosh(_a0_**cos(x1/_a1_)))**3))**x1)**x1
<lambdifygenerated-1897>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1 + (x1 + (_a6_ + x1**2)*((_a4_*_a7_)**_a4_ + tanh(x1))*tanh((_a5_ + _a7_*x1*cosh(_a0_**cos(x1/_a1_)))**3))**x1)**x1
<lambdifygenerated-1898>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1 + (x1 + (_a6_ + x1**2)*((_a4_*_a7_)**_a4_ + tanh(x1))*tanh((_a5_ + _a7_*x1*cosh(_a0_**cos(x1/_a1_)))**3))**x1)**x1
<lambdifygenerated-1899>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1 + (x1 + (_a2_*x1 + _a6_)*((_a4_*_a7_)**_a4_ + tanh(x1))*tanh((_a5_ + _a7_*x1*cosh(_a0_**cos(x1/_a1_)))**3))**x1)**x1
<lambdifygenerated-1900>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1 + (x1 + (_a2_*x1 + _a6_)*((_a4_*_a7_)**_a4_ + tanh(x1))*tanh((_a5_ + _a7_*x1*cosh(_a0_**cos(x1/_a1_)))**3))**x1)**x1
<lambdifygenerated-1901>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1 + (x1**2 + (_a2_*x1 + _a6_)*((_a4_*_a7_)**_a4_ + tanh(x1))*tanh((_a5_ + _a7_*x1*cosh(_a0_**cos(x1/_a1_)))**3))**x1)**x1
<lambdifygenerated-1902>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1 + (x1**2 + (_a2_*x1 + _a6_)*((_a4_*_a7_)**_a4_ + tanh(x1))*tanh((_a5_ + _a7_*x1*cosh(_a0_**cos(x1/_a1_)))**3))**x1)**x1
<lambdifygenerated-1903>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1 + (_a3_*x1 + (_a2_*x1 + _a6_)*((_a4_*_a7_)**_a4_ + tanh(x1))*tanh((_a5_ + _a7_*x1*cosh(_a0_**cos(x1/_a1_)))**3))**x1)**x1
<lambdifygenerated-1904>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1 + (_a3_*x1 + (_a2_*x1 + _a6_)*((_a4_*_a7_)**_a4_ + tanh(x1))*tanh((_a5_ + _a7_*x1*cosh(_a0_**cos(x1/_a1_)))**3))**x1)**x1
<lambdifygenerated-1905>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1 + (_a3_ + (_a2_*x1 + _a6_)*((_a4_*_a7_)**_a4_ + tanh(x1))*tanh((_a5_ + _a7_*x1*cosh(_a0_**cos(x1/_a1_)))**3))**x1)**x1
<lambdifygenerated-1906>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1 + (_a3_ + (_a2_*x1 + _a6_)*((_a4_*_a7_)**_a4_ + tanh(x1))*tanh((_a5_ + _a7_*x1*cosh(_a0_**cos(x1/_a1_)))**3))**x1)**x1
<lambdifygenerated-1907>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1 + (_a3_*x1 + (_a2_*x1 + _a6_)*((_a4_*_a7_)**_a4_ + tanh(x1))*tanh((_a5_ + _a7_*x1*cosh(_a0_**cos(x1/_a1_)))**3))**x1)**x1
<lambdifygenerated-1908>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1 + (_a3_*x1 + (_a2_*x1 + _a6_)*((_a4_*_a7_)**_a4_ + tanh(x1))*tanh((_a5_ + _a7_*x1*cosh(_a0_**cos(x1/_a1_)))**3))**x1)**x1
<lambdifygenerated-1909>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1 + (_a3_*_a6_ + (_a2_*x1 + _a6_)*((_a4_*_a7_)**_a4_ + tanh(x1))*tanh((_a5_ + _a7_*x1*cosh(_a0_**cos(x1/_a1_)))**3))**x1)**x1
<lambdifygenerated-1910>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1 + (_a3_*_a6_ + (_a2_*x1 + _a6_)*((_a4_*_a7_)**_a4_ + tanh(x1))*tanh((_a5_ + _a7_*x1*cosh(_a0_**cos(x1/_a1_)))**3))**x1)**x1
<lambdifygenerated-1911>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1 + (_a3_**2*_a6_/x1 + (_a2_*x1 + _a6_)*((_a4_*_a7_)**_a4_ + tanh(x1))*tanh((_a5_ + _a7_*x1*cosh(_a0_**cos(x1/_a1_)))**3))**x1)**x1
<lambdifygenerated-1912>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1 + (_a3_**2*_a6_/x1 + (_a2_*x1 + _a6_)*((_a4_*_a7_)**_a4_ + tanh(x1))*tanh((_a5_ + _a7_*x1*cosh(_a0_**cos(x1/_a1_)))**3))**x1)**x1
<lambdifygenerated-1913>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1 + (_a3_**2*_a6_/_a4_ + (_a2_*x1 + _a6_)*((_a4_*_a7_)**_a4_ + tanh(x1))*tanh((_a5_ + _a7_*x1*cosh(_a0_**cos(x1/_a1_)))**3))**x1)**x1
<lambdifygenerated-1914>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1 + (_a3_**2*_a6_/_a4_ + (_a2_*x1 + _a6_)*((_a4_*_a7_)**_a4_ + tanh(x1))*tanh((_a5_ + _a7_*x1*cosh(_a0_**cos(x1/_a1_)))**3))**x1)**x1
<lambdifygenerated-1915>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1 + (_a3_**2*_a6_/_a4_ + (_a2_*x1 + _a6_)*((_a4_*_a7_)**_a4_ + tanh(x1))*tanh((_a5_ + _a7_*x1*cosh(_a0_**cos(x1/_a1_)))**3))**exp(x1))**x1
<lambdifygenerated-1916>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1 + (_a3_**2*_a6_/_a4_ + (_a2_*x1 + _a6_)*((_a4_*_a7_)**_a4_ + tanh(x1))*tanh((_a5_ + _a7_*x1*cosh(_a0_**cos(x1/_a1_)))**3))**exp(x1))**x1
<lambdifygenerated-1917>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1 + (_a3_**2*_a6_/_a4_ + (_a2_*x1 + _a6_)*((_a4_*_a7_)**_a4_ + tanh(x1))*tanh((_a5_ + _a7_*x1*cosh(_a0_**cos(x1/_a1_)))**3))**exp(_a3_))**x1
<lambdifygenerated-1918>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1 + (_a3_**2*_a6_/_a4_ + (_a2_*x1 + _a6_)*((_a4_*_a7_)**_a4_ + tanh(x1))*tanh((_a5_ + _a7_*x1*cosh(_a0_**cos(x1/_a1_)))**3))**exp(_a3_))**x1
<lambdifygenerated-1919>:2: RuntimeWarning: invalid value encountered in scalar power
  return x1*(_a3_ + (_a3_**2*_a6_/_a4_ + (_a2_*x1 + _a6_)*((_a4_*_a7_)**_a4_ + tanh(x1))*tanh((_a5_ + _a7_*x1*cosh(_a0_**cos(x1/_a1_)))**3))**exp(_a3_))**x1
<lambdifygenerated-1919>:2: RuntimeWarning: invalid value encountered in power
  return x1*(_a3_ + (_a3_**2*_a6_/_a4_ + (_a2_*x1 + _a6_)*((_a4_*_a7_)**_a4_ + tanh(x1))*tanh((_a5_ + _a7_*x1*cosh(_a0_**cos(x1/_a1_)))**3))**exp(_a3_))**x1

interpolation

<lambdifygenerated-1921>:2: RuntimeWarning: invalid value encountered in power
  return x1*(_a3_ + (_a3_**2*_a6_/_a4_ + (_a2_*x1 + _a6_)*((_a4_*_a7_)**_a4_ + tanh(x1))*tanh((_a5_ + _a7_*x1*cosh(_a0_**cos(x1/_a1_)))**3))**exp(_a3_))**_a0_
<lambdifygenerated-1923>:2: RuntimeWarning: invalid value encountered in scalar power
  return -x1*(_a3_ + (_a3_**2*_a6_/_a4_ + (_a2_*x1 + _a6_)*((_a4_*_a7_)**_a4_ + tanh(x1))*tanh((_a5_ + _a7_*x1*cosh(_a0_**cos(x1/_a1_)))**3))**exp(_a3_))**_a0_
<lambdifygenerated-1923>:2: RuntimeWarning: invalid value encountered in power
  return -x1*(_a3_ + (_a3_**2*_a6_/_a4_ + (_a2_*x1 + _a6_)*((_a4_*_a7_)**_a4_ + tanh(x1))*tanh((_a5_ + _a7_*x1*cosh(_a0_**cos(x1/_a1_)))**3))**exp(_a3_))**_a0_
<lambdifygenerated-1925>:2: RuntimeWarning: invalid value encountered in scalar power
  return -_a3_*(_a3_ + (_a3_**2*_a6_/_a4_ + (_a2_*x1 + _a6_)*((_a4_*_a7_)**_a4_ + tanh(x1))*tanh((_a5_ + _a7_*x1*cosh(_a0_**cos(x1/_a1_)))**3))**exp(_a3_))**_a0_
<lambdifygenerated-1925>:2: RuntimeWarning: invalid value encountered in power
  return -_a3_*(_a3_ + (_a3_**2*_a6_/_a4_ + (_a2_*x1 + _a6_)*((_a4_*_a7_)**_a4_ + tanh(x1))*tanh((_a5_ + _a7_*x1*cosh(_a0_**cos(x1/_a1_)))**3))**exp(_a3_))**_a0_
<lambdifygenerated-1929>:2: RuntimeWarning: invalid value encountered in scalar power
  return -_a3_*(_a3_ + (_a3_**2*_a6_/_a4_ + (_a2_*x1 + _a6_)*((_a4_*_a7_)**_a4_ + tanh(x1))*tanh((_a5_ + _a7_*x1*cosh(_a0_**cos(x1/_a1_)))**3))**exp(_a3_))**_a0_
<lambdifygenerated-1929>:2: RuntimeWarning: invalid value encountered in power
  return -_a3_*(_a3_ + (_a3_**2*_a6_/_a4_ + (_a2_*x1 + _a6_)*((_a4_*_a7_)**_a4_ + tanh(x1))*tanh((_a5_ + _a7_*x1*cosh(_a0_**cos(x1/_a1_)))**3))**exp(_a3_))**_a0_

         x1         y  rep    ymodel      ybms
3745  0.997  0.825595  8.0  0.825622  0.825950
3746  0.998  0.825925  8.0  0.825952  0.826288
3747  0.998  0.826254  8.0  0.826282  0.826625
3748  0.999  0.826582  8.0  0.826612  0.826962

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.827238  8.0  0.827270  0.827634
3751  1.002  0.827565  8.0  0.827598  0.827969
3752  1.002  0.827892  8.0  0.827925  0.828304
3753  1.003  0.828218  8.0  0.828252  0.828638

3750

<lambdifygenerated-1937>:2: RuntimeWarning: invalid value encountered in power
  return x1 + x1**x1
<lambdifygenerated-1938>:2: RuntimeWarning: invalid value encountered in power
  return x1 + x1**x1
<lambdifygenerated-1939>:2: RuntimeWarning: invalid value encountered in power
  return x1 + tanh(x1)**x1
<lambdifygenerated-1940>:2: RuntimeWarning: invalid value encountered in power
  return x1 + tanh(x1)**x1
<lambdifygenerated-1945>:2: RuntimeWarning: invalid value encountered in power
  return x1 + tanh(x1*sinh(x1**2))**x1
<lambdifygenerated-1946>:2: RuntimeWarning: invalid value encountered in power
  return x1 + tanh(x1*sinh(x1**2))**x1
<lambdifygenerated-1947>:2: RuntimeWarning: invalid value encountered in power
  return x1 + tanh(x1*sinh(2*x1**2))**x1
<lambdifygenerated-1948>:2: RuntimeWarning: invalid value encountered in power
  return x1 + tanh(x1*sinh(2*x1**2))**x1
<lambdifygenerated-1949>:2: RuntimeWarning: invalid value encountered in power
  return x1 + tanh(x1*sinh(x1*(x1 + x1**x1)))**x1
<lambdifygenerated-1950>:2: RuntimeWarning: invalid value encountered in power
  return x1 + tanh(x1*sinh(x1*(x1 + x1**x1)))**x1
<lambdifygenerated-1951>:2: RuntimeWarning: invalid value encountered in power
  return x1 + tanh(x1*sinh(x1*(x1 + tanh(x1)**x1)))**x1
<lambdifygenerated-1952>:2: RuntimeWarning: invalid value encountered in power
  return x1 + tanh(x1*sinh(x1*(x1 + tanh(x1)**x1)))**x1
<lambdifygenerated-1953>:2: RuntimeWarning: invalid value encountered in power
  return x1 + tanh(x1*sinh(x1*(x1 + tanh(2*x1)**x1)))**x1
<lambdifygenerated-1954>:2: RuntimeWarning: invalid value encountered in power
  return x1 + tanh(x1*sinh(x1*(x1 + tanh(2*x1)**x1)))**x1
<lambdifygenerated-1955>:2: RuntimeWarning: invalid value encountered in power
  return x1 + tanh(x1*sinh(x1*(x1 + tanh(x1**2 + x1)**x1)))**x1
<lambdifygenerated-1955>:2: RuntimeWarning: overflow encountered in sinh
  return x1 + tanh(x1*sinh(x1*(x1 + tanh(x1**2 + x1)**x1)))**x1
<lambdifygenerated-1956>:2: RuntimeWarning: invalid value encountered in power
  return x1 + tanh(x1*sinh(x1*(x1 + tanh(x1**2 + x1)**x1)))**x1
<lambdifygenerated-1956>:2: RuntimeWarning: overflow encountered in sinh
  return x1 + tanh(x1*sinh(x1*(x1 + tanh(x1**2 + x1)**x1)))**x1
<lambdifygenerated-1957>:2: RuntimeWarning: invalid value encountered in power
  return x1 + tanh(x1*sinh(x1*(x1 + tanh(2*x1**2 + x1)**x1)))**x1
<lambdifygenerated-1957>:2: RuntimeWarning: overflow encountered in sinh
  return x1 + tanh(x1*sinh(x1*(x1 + tanh(2*x1**2 + x1)**x1)))**x1
<lambdifygenerated-1958>:2: RuntimeWarning: invalid value encountered in power
  return x1 + tanh(x1*sinh(x1*(x1 + tanh(2*x1**2 + x1)**x1)))**x1
<lambdifygenerated-1958>:2: RuntimeWarning: overflow encountered in sinh
  return x1 + tanh(x1*sinh(x1*(x1 + tanh(2*x1**2 + x1)**x1)))**x1
<lambdifygenerated-1959>:2: RuntimeWarning: invalid value encountered in power
  return x1 + tanh(x1*sinh(x1*(x1 + tanh(x1*(x1**3 + x1) + x1)**x1)))**x1
<lambdifygenerated-1960>:2: RuntimeWarning: invalid value encountered in power
  return x1 + tanh(x1*sinh(x1*(x1 + tanh(x1*(x1**3 + x1) + x1)**x1)))**x1
<lambdifygenerated-1961>:2: RuntimeWarning: invalid value encountered in power
  return x1 + tanh(x1*sinh(x1*(x1 + tanh(x1*(x1 + sin(x1)**3) + x1)**x1)))**x1
<lambdifygenerated-1962>:2: RuntimeWarning: invalid value encountered in power
  return x1 + tanh(x1*sinh(x1*(x1 + tanh(x1*(x1 + sin(x1)**3) + x1)**x1)))**x1
<lambdifygenerated-1963>:2: RuntimeWarning: invalid value encountered in power
  return x1 + tanh(x1*sinh(x1*(x1 + tanh(x1*(x1 + sin(x1**2)**3) + x1)**x1)))**x1
<lambdifygenerated-1963>:2: RuntimeWarning: overflow encountered in sinh
  return x1 + tanh(x1*sinh(x1*(x1 + tanh(x1*(x1 + sin(x1**2)**3) + x1)**x1)))**x1
<lambdifygenerated-1964>:2: RuntimeWarning: invalid value encountered in power
  return x1 + tanh(x1*sinh(x1*(x1 + tanh(x1*(x1 + sin(x1**2)**3) + x1)**x1)))**x1
<lambdifygenerated-1964>:2: RuntimeWarning: overflow encountered in sinh
  return x1 + tanh(x1*sinh(x1*(x1 + tanh(x1*(x1 + sin(x1**2)**3) + x1)**x1)))**x1
<lambdifygenerated-1965>:2: RuntimeWarning: invalid value encountered in power
  return x1 + tanh(x1*sinh(x1*(x1 + tanh(x1*(x1 + sin(2*x1**2)**3) + x1)**x1)))**x1
<lambdifygenerated-1965>:2: RuntimeWarning: overflow encountered in sinh
  return x1 + tanh(x1*sinh(x1*(x1 + tanh(x1*(x1 + sin(2*x1**2)**3) + x1)**x1)))**x1
<lambdifygenerated-1966>:2: RuntimeWarning: invalid value encountered in power
  return x1 + tanh(x1*sinh(x1*(x1 + tanh(x1*(x1 + sin(2*x1**2)**3) + x1)**x1)))**x1
<lambdifygenerated-1966>:2: RuntimeWarning: overflow encountered in sinh
  return x1 + tanh(x1*sinh(x1*(x1 + tanh(x1*(x1 + sin(2*x1**2)**3) + x1)**x1)))**x1
<lambdifygenerated-1967>:2: RuntimeWarning: invalid value encountered in power
  return x1 + tanh(x1*sinh(x1*(x1 + tanh(x1*(x1 + sin(x1*(x1 + exp(x1)))**3) + x1)**x1)))**x1
<lambdifygenerated-1967>:2: RuntimeWarning: overflow encountered in sinh
  return x1 + tanh(x1*sinh(x1*(x1 + tanh(x1*(x1 + sin(x1*(x1 + exp(x1)))**3) + x1)**x1)))**x1
<lambdifygenerated-1968>:2: RuntimeWarning: invalid value encountered in power
  return x1 + tanh(x1*sinh(x1*(x1 + tanh(x1*(x1 + sin(x1*(x1 + exp(x1)))**3) + x1)**x1)))**x1
<lambdifygenerated-1968>:2: RuntimeWarning: overflow encountered in sinh
  return x1 + tanh(x1*sinh(x1*(x1 + tanh(x1*(x1 + sin(x1*(x1 + exp(x1)))**3) + x1)**x1)))**x1
<lambdifygenerated-1969>:2: RuntimeWarning: invalid value encountered in power
  return x1 + tanh(x1*sinh(x1*(x1 + tanh(x1*(x1 + sin(x1*(x1 + exp(x1**x1)))**3) + x1)**x1)))**x1
<lambdifygenerated-1970>:2: RuntimeWarning: invalid value encountered in power
  return x1 + tanh(x1*sinh(x1*(x1 + tanh(x1*(x1 + sin(x1*(x1 + exp(x1**x1)))**3) + x1)**x1)))**x1
<lambdifygenerated-1971>:2: RuntimeWarning: invalid value encountered in power
  return x1 + tanh(x1*sinh(x1*(x1 + tanh(x1*(x1 + sin(x1*(x1 + exp(tan(x1)**x1)))**3) + x1)**x1)))**x1
<lambdifygenerated-1971>:2: RuntimeWarning: overflow encountered in exp
  return x1 + tanh(x1*sinh(x1*(x1 + tanh(x1*(x1 + sin(x1*(x1 + exp(tan(x1)**x1)))**3) + x1)**x1)))**x1
<lambdifygenerated-1971>:2: RuntimeWarning: invalid value encountered in sin
  return x1 + tanh(x1*sinh(x1*(x1 + tanh(x1*(x1 + sin(x1*(x1 + exp(tan(x1)**x1)))**3) + x1)**x1)))**x1
<lambdifygenerated-1971>:2: RuntimeWarning: overflow encountered in sinh
  return x1 + tanh(x1*sinh(x1*(x1 + tanh(x1*(x1 + sin(x1*(x1 + exp(tan(x1)**x1)))**3) + x1)**x1)))**x1
<lambdifygenerated-1972>:2: RuntimeWarning: invalid value encountered in power
  return x1 + tanh(x1*sinh(x1*(x1 + tanh(x1*(x1 + sin(x1*(x1 + exp(tan(x1)**x1)))**3) + x1)**x1)))**x1
<lambdifygenerated-1972>:2: RuntimeWarning: overflow encountered in exp
  return x1 + tanh(x1*sinh(x1*(x1 + tanh(x1*(x1 + sin(x1*(x1 + exp(tan(x1)**x1)))**3) + x1)**x1)))**x1
<lambdifygenerated-1972>:2: RuntimeWarning: invalid value encountered in sin
  return x1 + tanh(x1*sinh(x1*(x1 + tanh(x1*(x1 + sin(x1*(x1 + exp(tan(x1)**x1)))**3) + x1)**x1)))**x1
<lambdifygenerated-1972>:2: RuntimeWarning: overflow encountered in sinh
  return x1 + tanh(x1*sinh(x1*(x1 + tanh(x1*(x1 + sin(x1*(x1 + exp(tan(x1)**x1)))**3) + x1)**x1)))**x1
<lambdifygenerated-1973>:2: RuntimeWarning: invalid value encountered in power
  return x1 + tanh(x1*sinh(x1*(x1 + tanh(x1*(x1 + sin(x1*(x1 + exp(tan(_a3_)**x1)))**3) + x1)**x1)))**x1
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-1974>:2: RuntimeWarning: invalid value encountered in power
  return x1 + tanh(x1*sinh(x1*(x1 + tanh(x1*(x1 + sin(x1*(x1 + exp(tan(_a3_)**x1)))**3) + x1)**x1)))**x1
<lambdifygenerated-1975>:2: RuntimeWarning: invalid value encountered in power
  return x1 + tanh(x1*sinh(x1*(x1 + tanh(x1*(x1 + sin(x1*(x1 + exp(tan(_a3_)**(2*x1))))**3) + x1)**x1)))**x1
<lambdifygenerated-1975>:2: RuntimeWarning: overflow encountered in sinh
  return x1 + tanh(x1*sinh(x1*(x1 + tanh(x1*(x1 + sin(x1*(x1 + exp(tan(_a3_)**(2*x1))))**3) + x1)**x1)))**x1
<lambdifygenerated-1976>:2: RuntimeWarning: invalid value encountered in power
  return x1 + tanh(x1*sinh(x1*(x1 + tanh(x1*(x1 + sin(x1*(x1 + exp(tan(_a3_)**(2*x1))))**3) + x1)**x1)))**x1
<lambdifygenerated-1976>:2: RuntimeWarning: overflow encountered in sinh
  return x1 + tanh(x1*sinh(x1*(x1 + tanh(x1*(x1 + sin(x1*(x1 + exp(tan(_a3_)**(2*x1))))**3) + x1)**x1)))**x1
<lambdifygenerated-1977>:2: RuntimeWarning: invalid value encountered in power
  return x1 + tanh(x1*sinh(x1*(x1 + tanh(x1*(x1 + sin(x1*(x1 + exp(tan(_a3_)**(x1**2 + x1))))**3) + x1)**x1)))**x1
<lambdifygenerated-1977>:2: RuntimeWarning: overflow encountered in sinh
  return x1 + tanh(x1*sinh(x1*(x1 + tanh(x1*(x1 + sin(x1*(x1 + exp(tan(_a3_)**(x1**2 + x1))))**3) + x1)**x1)))**x1
<lambdifygenerated-1978>:2: RuntimeWarning: invalid value encountered in power
  return x1 + tanh(x1*sinh(x1*(x1 + tanh(x1*(x1 + sin(x1*(x1 + exp(tan(_a3_)**(x1**2 + x1))))**3) + x1)**x1)))**x1
<lambdifygenerated-1978>:2: RuntimeWarning: overflow encountered in sinh
  return x1 + tanh(x1*sinh(x1*(x1 + tanh(x1*(x1 + sin(x1*(x1 + exp(tan(_a3_)**(x1**2 + x1))))**3) + x1)**x1)))**x1
<lambdifygenerated-1979>:2: RuntimeWarning: invalid value encountered in power
  return x1 + tanh(x1*sinh(x1*(x1 + tanh(x1*(x1 + sin(x1*(x1 + exp(tan(_a3_)**(_a2_*x1 + x1))))**3) + x1)**x1)))**x1
<lambdifygenerated-1979>:2: RuntimeWarning: overflow encountered in sinh
  return x1 + tanh(x1*sinh(x1*(x1 + tanh(x1*(x1 + sin(x1*(x1 + exp(tan(_a3_)**(_a2_*x1 + x1))))**3) + x1)**x1)))**x1
<lambdifygenerated-1980>:2: RuntimeWarning: invalid value encountered in power
  return x1 + tanh(x1*sinh(x1*(x1 + tanh(x1*(x1 + sin(x1*(x1 + exp(tan(_a3_)**(_a2_*x1 + x1))))**3) + x1)**x1)))**x1
<lambdifygenerated-1980>:2: RuntimeWarning: overflow encountered in sinh
  return x1 + tanh(x1*sinh(x1*(x1 + tanh(x1*(x1 + sin(x1*(x1 + exp(tan(_a3_)**(_a2_*x1 + x1))))**3) + x1)**x1)))**x1
<lambdifygenerated-1981>:2: RuntimeWarning: invalid value encountered in power
  return x1 + tanh(x1*sinh(x1*(x1 + tanh(x1*(x1 + sin(x1*(x1 + exp(tan(_a3_)**(_a2_*x1 + x1))))**3) + x1)**x1)))**x1
<lambdifygenerated-1981>:2: RuntimeWarning: overflow encountered in sinh
  return x1 + tanh(x1*sinh(x1*(x1 + tanh(x1*(x1 + sin(x1*(x1 + exp(tan(_a3_)**(_a2_*x1 + x1))))**3) + x1)**x1)))**x1
<lambdifygenerated-1982>:2: RuntimeWarning: invalid value encountered in power
  return x1 + tanh(x1*sinh(x1*(x1 + tanh(x1*(x1 + sin(x1*(x1 + exp(tan(_a3_)**(_a2_*x1 + x1))))**3) + x1)**x1)))**x1
<lambdifygenerated-1982>:2: RuntimeWarning: overflow encountered in sinh
  return x1 + tanh(x1*sinh(x1*(x1 + tanh(x1*(x1 + sin(x1*(x1 + exp(tan(_a3_)**(_a2_*x1 + x1))))**3) + x1)**x1)))**x1
<lambdifygenerated-1983>:2: RuntimeWarning: invalid value encountered in power
  return x1 + tanh(x1*sinh(x1*(x1 + tanh(x1*(x1 + sin(x1*(x1 + exp(tan(_a3_)**(_a2_*x1 + cos(x1)))))**3) + x1)**x1)))**x1
<lambdifygenerated-1984>:2: RuntimeWarning: invalid value encountered in power
  return x1 + tanh(x1*sinh(x1*(x1 + tanh(x1*(x1 + sin(x1*(x1 + exp(tan(_a3_)**(_a2_*x1 + cos(x1)))))**3) + x1)**x1)))**x1
<lambdifygenerated-1985>:2: RuntimeWarning: invalid value encountered in power
  return x1 + tanh(x1*sinh(x1*(x1 + tanh(x1*(x1 + sin(x1*(x1 + exp(tan(_a3_)**(_a2_*x1 + cos(1)))))**3) + x1)**x1)))**x1
<lambdifygenerated-1986>:2: RuntimeWarning: invalid value encountered in power
  return x1 + tanh(x1*sinh(x1*(x1 + tanh(x1*(x1 + sin(x1*(x1 + exp(tan(_a3_)**(_a2_*x1 + cos(1)))))**3) + x1)**x1)))**x1
<lambdifygenerated-1987>:2: RuntimeWarning: invalid value encountered in power
  return x1 + tanh(x1*sinh(x1*(x1 + tanh(x1*(x1 + sin(x1*(x1 + exp(tan(_a3_)**(_a2_*x1 + cos(1)))))**3) + x1)**x1)))**x1
<lambdifygenerated-1988>:2: RuntimeWarning: invalid value encountered in power
  return x1 + tanh(x1*sinh(x1*(x1 + tanh(x1*(x1 + sin(x1*(x1 + exp(tan(_a3_)**(_a2_*x1 + cos(1)))))**3) + x1)**x1)))**x1
<lambdifygenerated-1989>:2: RuntimeWarning: invalid value encountered in power
  return x1 + tanh(x1*sinh(x1*(x1 + tanh(x1*(x1 + sin(x1*(x1 + exp(tan(_a3_)**(_a2_*x1 + cos(x1/cos(x1))))))**3) + x1)**x1)))**x1
<lambdifygenerated-1990>:2: RuntimeWarning: invalid value encountered in power
  return x1 + tanh(x1*sinh(x1*(x1 + tanh(x1*(x1 + sin(x1*(x1 + exp(tan(_a3_)**(_a2_*x1 + cos(x1/cos(x1))))))**3) + x1)**x1)))**x1
<lambdifygenerated-1991>:2: RuntimeWarning: invalid value encountered in power
  return x1 + tanh(x1*sinh(x1*(x1 + tanh(x1*(x1 + sin(x1*(x1 + exp(tan(_a3_)**(_a2_*x1 + cos(x1/cos(x1**2))))))**3) + x1)**x1)))**x1
<lambdifygenerated-1992>:2: RuntimeWarning: invalid value encountered in power
  return x1 + tanh(x1*sinh(x1*(x1 + tanh(x1*(x1 + sin(x1*(x1 + exp(tan(_a3_)**(_a2_*x1 + cos(x1/cos(x1**2))))))**3) + x1)**x1)))**x1
<lambdifygenerated-1993>:2: RuntimeWarning: invalid value encountered in power
  return x1 + tanh(x1*sinh(x1*(x1 + tanh(x1*(x1 + sin(x1*(x1 + exp(tan(_a3_)**(_a2_*x1 + cos(x1/cos(_a3_*x1))))))**3) + x1)**x1)))**x1
<lambdifygenerated-1994>:2: RuntimeWarning: invalid value encountered in power
  return x1 + tanh(x1*sinh(x1*(x1 + tanh(x1*(x1 + sin(x1*(x1 + exp(tan(_a3_)**(_a2_*x1 + cos(x1/cos(_a3_*x1))))))**3) + x1)**x1)))**x1
<lambdifygenerated-1995>:2: RuntimeWarning: invalid value encountered in power
  return x1 + tanh(x1*sinh(x1*(x1 + tanh(x1*(x1 + sin(x1*(x1 + exp(tan(_a3_)**(_a2_*x1 + cos(x1/cos(_a3_*x1**2))))))**3) + x1)**x1)))**x1
<lambdifygenerated-1996>:2: RuntimeWarning: invalid value encountered in power
  return x1 + tanh(x1*sinh(x1*(x1 + tanh(x1*(x1 + sin(x1*(x1 + exp(tan(_a3_)**(_a2_*x1 + cos(x1/cos(_a3_*x1**2))))))**3) + x1)**x1)))**x1
<lambdifygenerated-1997>:2: RuntimeWarning: invalid value encountered in power
  return x1 + tanh(x1*sinh(x1*(x1 + tanh(x1*(x1 + sin(x1*(x1 + exp(tan(_a3_)**(_a2_*x1 + cos(x1/cos(_a1_**2*_a3_))))))**3) + x1)**x1)))**x1
<lambdifygenerated-1998>:2: RuntimeWarning: invalid value encountered in power
  return x1 + tanh(x1*sinh(x1*(x1 + tanh(x1*(x1 + sin(x1*(x1 + exp(tan(_a3_)**(_a2_*x1 + cos(x1/cos(_a1_**2*_a3_))))))**3) + x1)**x1)))**x1
<lambdifygenerated-1999>:2: RuntimeWarning: invalid value encountered in power
  return x1 + tanh(x1*sinh(x1*(x1 + tanh(x1*(x1 + sin(x1*(x1**2 + exp(tan(_a3_)**(_a2_*x1 + cos(x1/cos(_a1_**2*_a3_))))))**3) + x1)**x1)))**x1
<lambdifygenerated-1999>:2: RuntimeWarning: overflow encountered in sinh
  return x1 + tanh(x1*sinh(x1*(x1 + tanh(x1*(x1 + sin(x1*(x1**2 + exp(tan(_a3_)**(_a2_*x1 + cos(x1/cos(_a1_**2*_a3_))))))**3) + x1)**x1)))**x1
<lambdifygenerated-2000>:2: RuntimeWarning: invalid value encountered in power
  return x1 + tanh(x1*sinh(x1*(x1 + tanh(x1*(x1 + sin(x1*(x1**2 + exp(tan(_a3_)**(_a2_*x1 + cos(x1/cos(_a1_**2*_a3_))))))**3) + x1)**x1)))**x1
<lambdifygenerated-2000>:2: RuntimeWarning: overflow encountered in sinh
  return x1 + tanh(x1*sinh(x1*(x1 + tanh(x1*(x1 + sin(x1*(x1**2 + exp(tan(_a3_)**(_a2_*x1 + cos(x1/cos(_a1_**2*_a3_))))))**3) + x1)**x1)))**x1
<lambdifygenerated-2001>:2: RuntimeWarning: invalid value encountered in power
  return x1 + tanh(x1*sinh(x1*(x1 + tanh(x1*(x1 + sin(x1*(_a4_*x1 + exp(tan(_a3_)**(_a2_*x1 + cos(x1/cos(_a1_**2*_a3_))))))**3) + x1)**x1)))**x1
<lambdifygenerated-2002>:2: RuntimeWarning: invalid value encountered in power
  return x1 + tanh(x1*sinh(x1*(x1 + tanh(x1*(x1 + sin(x1*(_a4_*x1 + exp(tan(_a3_)**(_a2_*x1 + cos(x1/cos(_a1_**2*_a3_))))))**3) + x1)**x1)))**x1
<lambdifygenerated-2003>:2: RuntimeWarning: invalid value encountered in power
  return x1 + tanh(x1*sinh(x1*(x1 + tanh(x1*(x1 + sin(x1*(_a1_*_a4_ + exp(tan(_a3_)**(_a2_*x1 + cos(x1/cos(_a1_**2*_a3_))))))**3) + x1)**x1)))**x1
<lambdifygenerated-2003>:2: RuntimeWarning: overflow encountered in sinh
  return x1 + tanh(x1*sinh(x1*(x1 + tanh(x1*(x1 + sin(x1*(_a1_*_a4_ + exp(tan(_a3_)**(_a2_*x1 + cos(x1/cos(_a1_**2*_a3_))))))**3) + x1)**x1)))**x1
<lambdifygenerated-2004>:2: RuntimeWarning: invalid value encountered in power
  return x1 + tanh(x1*sinh(x1*(x1 + tanh(x1*(x1 + sin(x1*(_a1_*_a4_ + exp(tan(_a3_)**(_a2_*x1 + cos(x1/cos(_a1_**2*_a3_))))))**3) + x1)**x1)))**x1
<lambdifygenerated-2004>:2: RuntimeWarning: overflow encountered in sinh
  return x1 + tanh(x1*sinh(x1*(x1 + tanh(x1*(x1 + sin(x1*(_a1_*_a4_ + exp(tan(_a3_)**(_a2_*x1 + cos(x1/cos(_a1_**2*_a3_))))))**3) + x1)**x1)))**x1
<lambdifygenerated-2005>:2: RuntimeWarning: invalid value encountered in power
  return x1 + tanh(x1*sinh(x1*(x1 + tanh(x1*(x1 + sin(_a0_*(_a1_*_a4_ + exp(tan(_a3_)**(_a2_*x1 + cos(x1/cos(_a1_**2*_a3_))))))**3) + x1)**x1)))**x1
<lambdifygenerated-2005>:2: RuntimeWarning: overflow encountered in sinh
  return x1 + tanh(x1*sinh(x1*(x1 + tanh(x1*(x1 + sin(_a0_*(_a1_*_a4_ + exp(tan(_a3_)**(_a2_*x1 + cos(x1/cos(_a1_**2*_a3_))))))**3) + x1)**x1)))**x1
<lambdifygenerated-2006>:2: RuntimeWarning: invalid value encountered in power
  return x1 + tanh(x1*sinh(x1*(x1 + tanh(x1*(x1 + sin(_a0_*(_a1_*_a4_ + exp(tan(_a3_)**(_a2_*x1 + cos(x1/cos(_a1_**2*_a3_))))))**3) + x1)**x1)))**x1
<lambdifygenerated-2006>:2: RuntimeWarning: overflow encountered in sinh
  return x1 + tanh(x1*sinh(x1*(x1 + tanh(x1*(x1 + sin(_a0_*(_a1_*_a4_ + exp(tan(_a3_)**(_a2_*x1 + cos(x1/cos(_a1_**2*_a3_))))))**3) + x1)**x1)))**x1
<lambdifygenerated-2007>:2: RuntimeWarning: invalid value encountered in power
  return x1 + tanh(x1*sinh(x1*(x1 + tanh(x1*(_a6_ + sin(_a0_*(_a1_*_a4_ + exp(tan(_a3_)**(_a2_*x1 + cos(x1/cos(_a1_**2*_a3_))))))**3) + x1)**x1)))**x1
<lambdifygenerated-2008>:2: RuntimeWarning: invalid value encountered in power
  return x1 + tanh(x1*sinh(x1*(x1 + tanh(x1*(_a6_ + sin(_a0_*(_a1_*_a4_ + exp(tan(_a3_)**(_a2_*x1 + cos(x1/cos(_a1_**2*_a3_))))))**3) + x1)**x1)))**x1
<lambdifygenerated-2009>:2: RuntimeWarning: invalid value encountered in power
  return x1 + tanh(x1*sinh(x1*(x1 + tanh(_a5_*(_a6_ + sin(_a0_*(_a1_*_a4_ + exp(tan(_a3_)**(_a2_*x1 + cos(x1/cos(_a1_**2*_a3_))))))**3) + x1)**x1)))**x1
<lambdifygenerated-2009>:2: RuntimeWarning: overflow encountered in sinh
  return x1 + tanh(x1*sinh(x1*(x1 + tanh(_a5_*(_a6_ + sin(_a0_*(_a1_*_a4_ + exp(tan(_a3_)**(_a2_*x1 + cos(x1/cos(_a1_**2*_a3_))))))**3) + x1)**x1)))**x1
<lambdifygenerated-2010>:2: RuntimeWarning: invalid value encountered in power
  return x1 + tanh(x1*sinh(x1*(x1 + tanh(_a5_*(_a6_ + sin(_a0_*(_a1_*_a4_ + exp(tan(_a3_)**(_a2_*x1 + cos(x1/cos(_a1_**2*_a3_))))))**3) + x1)**x1)))**x1
<lambdifygenerated-2010>:2: RuntimeWarning: overflow encountered in sinh
  return x1 + tanh(x1*sinh(x1*(x1 + tanh(_a5_*(_a6_ + sin(_a0_*(_a1_*_a4_ + exp(tan(_a3_)**(_a2_*x1 + cos(x1/cos(_a1_**2*_a3_))))))**3) + x1)**x1)))**x1
<lambdifygenerated-2011>:2: RuntimeWarning: invalid value encountered in power
  return x1 + tanh(x1*sinh(x1*(x1 + tanh(_a2_ + _a5_*(_a6_ + sin(_a0_*(_a1_*_a4_ + exp(tan(_a3_)**(_a2_*x1 + cos(x1/cos(_a1_**2*_a3_))))))**3))**x1)))**x1
<lambdifygenerated-2012>:2: RuntimeWarning: invalid value encountered in power
  return x1 + tanh(x1*sinh(x1*(x1 + tanh(_a2_ + _a5_*(_a6_ + sin(_a0_*(_a1_*_a4_ + exp(tan(_a3_)**(_a2_*x1 + cos(x1/cos(_a1_**2*_a3_))))))**3))**x1)))**x1
<lambdifygenerated-2013>:2: RuntimeWarning: invalid value encountered in power
  return x1 + tanh(x1*sinh(x1*(x1 + tanh(_a2_ + _a5_*(_a6_ + sin(_a0_*(_a1_*_a4_ + exp(tan(_a3_)**(_a2_*x1 + cos(x1/cos(_a1_**2*_a3_))))))**3))**_a4_)))**x1
<lambdifygenerated-2014>:2: RuntimeWarning: invalid value encountered in power
  return x1 + tanh(x1*sinh(x1*(x1 + tanh(_a2_ + _a5_*(_a6_ + sin(_a0_*(_a1_*_a4_ + exp(tan(_a3_)**(_a2_*x1 + cos(x1/cos(_a1_**2*_a3_))))))**3))**_a4_)))**x1
<lambdifygenerated-2015>:2: RuntimeWarning: overflow encountered in exp
  return x1 + tanh(x1*sinh(x1*(tanh(_a2_ + _a5_*(_a6_ + sin(_a0_*(_a1_*_a4_ + exp(tan(_a3_)**(_a2_*x1 + cos(x1/cos(_a1_**2*_a3_))))))**3))**_a4_ + 1)))**x1
<lambdifygenerated-2015>:2: RuntimeWarning: overflow encountered in multiply

interpolation

<lambdifygenerated-2029>:2: RuntimeWarning: overflow encountered in sinh
  return x1 + tanh(_a0_*_a5_*sinh(_a4_*(tanh(_a2_ + _a5_*(_a6_ + sin(_a0_*(_a1_*_a4_ + exp(tan(_a3_)**(_a2_*x1 + cos(x1/cos(_a1_**2*_a3_))))))**3))**_a4_ + _a6_/_a3_)))**tan(x1)
<lambdifygenerated-2030>:2: RuntimeWarning: overflow encountered in sinh
  return x1 + tanh(_a0_*_a5_*sinh(_a4_*(tanh(_a2_ + _a5_*(_a6_ + sin(_a0_*(_a1_*_a4_ + exp(tan(_a3_)**(_a2_*x1 + cos(x1/cos(_a1_**2*_a3_))))))**3))**_a4_ + _a6_/_a3_)))**tan(x1)
<lambdifygenerated-2031>:2: RuntimeWarning: overflow encountered in sinh
  return x1 + tanh(_a0_*_a5_*sinh(_a4_*(tanh(_a2_ + _a5_*(_a6_ + sin(_a0_*(_a1_*_a4_ + exp(tan(_a3_)**(_a2_*x1 + cos(x1/cos(_a1_**2*_a3_))))))**3))**_a4_ + _a6_/_a3_)))**tan(_a5_)
<lambdifygenerated-2032>:2: RuntimeWarning: overflow encountered in sinh
  return x1 + tanh(_a0_*_a5_*sinh(_a4_*(tanh(_a2_ + _a5_*(_a6_ + sin(_a0_*(_a1_*_a4_ + exp(tan(_a3_)**(_a2_*x1 + cos(x1/cos(_a1_**2*_a3_))))))**3))**_a4_ + _a6_/_a3_)))**tan(_a5_)
<lambdifygenerated-2033>:2: RuntimeWarning: overflow encountered in sinh
  return _a7_ + tanh(_a0_*_a5_*sinh(_a4_*(tanh(_a2_ + _a5_*(_a6_ + sin(_a0_*(_a1_*_a4_ + exp(tan(_a3_)**(_a2_*x1 + cos(x1/cos(_a1_**2*_a3_))))))**3))**_a4_ + _a6_/_a3_)))**tan(_a5_)
<lambdifygenerated-2034>:2: RuntimeWarning: overflow encountered in sinh
  return _a7_ + tanh(_a0_*_a5_*sinh(_a4_*(tanh(_a2_ + _a5_*(_a6_ + sin(_a0_*(_a1_*_a4_ + exp(tan(_a3_)**(_a2_*x1 + cos(x1/cos(_a1_**2*_a3_))))))**3))**_a4_ + _a6_/_a3_)))**tan(_a5_)
<lambdifygenerated-2035>:2: RuntimeWarning: overflow encountered in sinh
  return _a7_ + tanh(_a0_*_a5_*sinh(_a4_*(tanh(_a2_ + _a5_*(_a6_ + sin(_a0_*(_a1_*_a4_ + exp(tan(_a3_)**(_a2_*x1 + cos(x1/cos(_a1_**2*_a3_))))))**3))**_a4_ + _a6_/_a3_)))**tan(_a5_)
<lambdifygenerated-2036>:2: RuntimeWarning: overflow encountered in sinh
  return _a7_ + tanh(_a0_*_a5_*sinh(_a4_*(tanh(_a2_ + _a5_*(_a6_ + sin(_a0_*(_a1_*_a4_ + exp(tan(_a3_)**(_a2_*x1 + cos(x1/cos(_a1_**2*_a3_))))))**3))**_a4_ + _a6_/_a3_)))**tan(_a5_)
<lambdifygenerated-2037>:2: RuntimeWarning: overflow encountered in sinh
  return _a7_ + tanh(_a0_*_a5_*sinh(_a4_*(tanh(_a2_ + _a5_*(_a6_ + sin(_a0_*(_a1_*_a4_ + exp(tan(_a3_)**(_a2_*x1 + cos(x1/cos(_a1_**2*_a3_))))))**3))**_a4_ + _a6_/_a3_)))**tan(_a5_)
<lambdifygenerated-2038>:2: RuntimeWarning: overflow encountered in sinh
  return _a7_ + tanh(_a0_*_a5_*sinh(_a4_*(tanh(_a2_ + _a5_*(_a6_ + sin(_a0_*(_a1_*_a4_ + exp(tan(_a3_)**(_a2_*x1 + cos(x1/cos(_a1_**2*_a3_))))))**3))**_a4_ + _a6_/_a3_)))**tan(_a5_)

         x1         y  rep    ymodel    ybms
3745  0.997  0.855453  9.0  0.854028  0.8554
3746  0.998  0.855554  9.0  0.854107  0.8555
3747  0.998  0.855656  9.0  0.854186  0.8556
3748  0.999  0.855757  9.0  0.854265  0.8557

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.855960  9.0  0.854422  0.855899
3751  1.002  0.856062  9.0  0.854501  0.855999
3752  1.002  0.856163  9.0  0.854579  0.856098
3753  1.003  0.856265  9.0  0.854657  0.856198

3750

<lambdifygenerated-2043>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1
<lambdifygenerated-2044>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1
<lambdifygenerated-2045>:2: RuntimeWarning: invalid value encountered in power
  return tanh(x1)**x1
<lambdifygenerated-2046>:2: RuntimeWarning: invalid value encountered in power
  return tanh(x1)**x1
<lambdifygenerated-2047>:2: RuntimeWarning: invalid value encountered in power
  return tanh(2*x1)**x1
<lambdifygenerated-2048>:2: RuntimeWarning: invalid value encountered in power
  return tanh(2*x1)**x1
<lambdifygenerated-2049>:2: RuntimeWarning: invalid value encountered in power
  return tanh(x1 + x1**x1)**x1
<lambdifygenerated-2050>:2: RuntimeWarning: invalid value encountered in power
  return tanh(x1 + x1**x1)**x1
<lambdifygenerated-2051>:2: RuntimeWarning: invalid value encountered in power
  return tanh(x1 + tanh(x1)**x1)**x1
<lambdifygenerated-2052>:2: RuntimeWarning: invalid value encountered in power
  return tanh(x1 + tanh(x1)**x1)**x1
<lambdifygenerated-2053>:2: RuntimeWarning: invalid value encountered in power
  return tanh(x1 + tanh(x1**2)**x1)**x1
<lambdifygenerated-2054>:2: RuntimeWarning: invalid value encountered in power
  return tanh(x1 + tanh(x1**2)**x1)**x1
<lambdifygenerated-2055>:2: RuntimeWarning: invalid value encountered in power
  return tanh(x1 + tanh(x1)**x1)**x1
<lambdifygenerated-2056>:2: RuntimeWarning: invalid value encountered in power
  return tanh(x1 + tanh(x1)**x1)**x1
<lambdifygenerated-2057>:2: RuntimeWarning: invalid value encountered in power
  return tanh(x1 + tanh(x1**2)**x1)**x1
<lambdifygenerated-2058>:2: RuntimeWarning: invalid value encountered in power
  return tanh(x1 + tanh(x1**2)**x1)**x1
<lambdifygenerated-2059>:2: RuntimeWarning: invalid value encountered in power
  return tanh(x1 + tanh(sin(x1)**2)**x1)**x1
<lambdifygenerated-2060>:2: RuntimeWarning: invalid value encountered in power
  return tanh(x1 + tanh(sin(x1)**2)**x1)**x1
<lambdifygenerated-2067>:2: RuntimeWarning: invalid value encountered in power
  return tanh(x1 + tanh(sin(x1)**2)**x1)**x1
<lambdifygenerated-2068>:2: RuntimeWarning: invalid value encountered in power
  return tanh(x1 + tanh(sin(x1)**2)**x1)**x1
<lambdifygenerated-2069>:2: RuntimeWarning: invalid value encountered in power
  return tanh(x1 + tanh(sin(x1 + (x1 - tanh(x1))/x1)**2)**x1)**x1
<lambdifygenerated-2070>:2: RuntimeWarning: invalid value encountered in power
  return tanh(x1 + tanh(sin(x1 + (x1 - tanh(x1))/x1)**2)**x1)**x1
<lambdifygenerated-2077>:2: RuntimeWarning: invalid value encountered in power
  return tanh(x1 + tanh(sin(x1 + (x1 - tanh(x1/(_a5_ + x1)))/x1)**2)**x1)**x1
<lambdifygenerated-2079>:2: RuntimeWarning: invalid value encountered in power
  return tanh(x1 + tanh(sin(x1 + (x1 - tanh(x1/(_a5_ + 1)))/x1)**2)**x1)**x1
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-2080>:2: RuntimeWarning: invalid value encountered in power
  return tanh(x1 + tanh(sin(x1 + (x1 - tanh(x1/(_a5_ + 1)))/x1)**2)**x1)**x1
<lambdifygenerated-2081>:2: RuntimeWarning: invalid value encountered in power
  return tanh(x1 + tanh(sin(x1 + (x1 - tanh(x1/(_a2_/x1 + _a5_)))/x1)**2)**x1)**x1
<lambdifygenerated-2082>:2: RuntimeWarning: invalid value encountered in power
  return tanh(x1 + tanh(sin(x1 + (x1 - tanh(x1/(_a2_/x1 + _a5_)))/x1)**2)**x1)**x1
<lambdifygenerated-2083>:2: RuntimeWarning: invalid value encountered in power
  return tanh(x1 + tanh(sin(x1 + (x1 - tanh(x1/(_a2_/x1 + _a5_)))/x1)**2)**x1)**x1
<lambdifygenerated-2084>:2: RuntimeWarning: invalid value encountered in power
  return tanh(x1 + tanh(sin(x1 + (x1 - tanh(x1/(_a2_/x1 + _a5_)))/x1)**2)**x1)**x1
<lambdifygenerated-2087>:2: RuntimeWarning: invalid value encountered in power
  return tanh(x1 + tanh(sin(x1 + (_a1_ - tanh(x1/(_a2_/x1 + _a5_)))/cos(x1))**2)**x1)**x1
<lambdifygenerated-2088>:2: RuntimeWarning: invalid value encountered in power
  return tanh(x1 + tanh(sin(x1 + (_a1_ - tanh(x1/(_a2_/x1 + _a5_)))/cos(x1))**2)**x1)**x1
<lambdifygenerated-2089>:2: RuntimeWarning: invalid value encountered in power
  return tanh(x1 + tanh(sin(x1 + (_a1_ - tanh(x1/(_a2_/x1 + _a5_)))/cos(_a1_))**2)**x1)**x1
<lambdifygenerated-2091>:2: RuntimeWarning: invalid value encountered in power
  return tanh(x1 + tanh(sin(_a0_ + (_a1_ - tanh(x1/(_a2_/x1 + _a5_)))/cos(_a1_))**2)**x1)**x1
<lambdifygenerated-2093>:2: RuntimeWarning: invalid value encountered in power
  return tanh(x1 + tanh(x1*sin(_a0_ + (_a1_ - tanh(x1/(_a2_/x1 + _a5_)))/cos(_a1_))**2/_a7_)**x1)**x1
<lambdifygenerated-2094>:2: RuntimeWarning: invalid value encountered in power
  return tanh(x1 + tanh(x1*sin(_a0_ + (_a1_ - tanh(x1/(_a2_/x1 + _a5_)))/cos(_a1_))**2/_a7_)**x1)**x1
<lambdifygenerated-2095>:2: RuntimeWarning: invalid value encountered in power
  return tanh(x1 + tanh(x1**x1*sin(_a0_ + (_a1_ - tanh(x1/(_a2_/x1 + _a5_)))/cos(_a1_))**2/_a7_)**x1)**x1
<lambdifygenerated-2096>:2: RuntimeWarning: invalid value encountered in power
  return tanh(x1 + tanh(x1**x1*sin(_a0_ + (_a1_ - tanh(x1/(_a2_/x1 + _a5_)))/cos(_a1_))**2/_a7_)**x1)**x1
<lambdifygenerated-2097>:2: RuntimeWarning: invalid value encountered in power
  return tanh(x1 + tanh(_a1_**x1*sin(_a0_ + (_a1_ - tanh(x1/(_a2_/x1 + _a5_)))/cos(_a1_))**2/_a7_)**x1)**x1
<lambdifygenerated-2098>:2: RuntimeWarning: invalid value encountered in power
  return tanh(x1 + tanh(_a1_**x1*sin(_a0_ + (_a1_ - tanh(x1/(_a2_/x1 + _a5_)))/cos(_a1_))**2/_a7_)**x1)**x1
<lambdifygenerated-2099>:2: RuntimeWarning: invalid value encountered in power
  return tanh(x1 + tanh(_a1_**x1*sin(_a0_ + (_a1_ - tanh(x1/(_a2_/x1 + _a5_)))/cos(_a1_))**2/_a7_)**x1)**x1
<lambdifygenerated-2100>:2: RuntimeWarning: invalid value encountered in power
  return tanh(x1 + tanh(_a1_**x1*sin(_a0_ + (_a1_ - tanh(x1/(_a2_/x1 + _a5_)))/cos(_a1_))**2/_a7_)**x1)**x1
<lambdifygenerated-2101>:2: RuntimeWarning: invalid value encountered in power
  return tanh(x1 + tanh(_a1_**x1*sin(_a0_ + (_a1_ - tanh(x1/(_a2_/x1 + _a5_)))/cos(_a1_))**2/_a7_)**_a4_)**x1
<lambdifygenerated-2102>:2: RuntimeWarning: invalid value encountered in power
  return tanh(x1 + tanh(_a1_**x1*sin(_a0_ + (_a1_ - tanh(x1/(_a2_/x1 + _a5_)))/cos(_a1_))**2/_a7_)**_a4_)**x1
<lambdifygenerated-2103>:2: RuntimeWarning: invalid value encountered in power
  return tanh(_a6_ + tanh(_a1_**x1*sin(_a0_ + (_a1_ - tanh(x1/(_a2_/x1 + _a5_)))/cos(_a1_))**2/_a7_)**_a4_)**x1
<lambdifygenerated-2104>:2: RuntimeWarning: invalid value encountered in power
  return tanh(_a6_ + tanh(_a1_**x1*sin(_a0_ + (_a1_ - tanh(x1/(_a2_/x1 + _a5_)))/cos(_a1_))**2/_a7_)**_a4_)**x1
<lambdifygenerated-2105>:2: RuntimeWarning: invalid value encountered in power
  return tanh(_a6_ + tanh(_a1_**x1*sin(_a0_ + (_a1_ - tanh(x1/(_a2_/x1 + _a5_)))/cos(_a1_))**2/_a7_)**_a4_)**(2*x1)
<lambdifygenerated-2106>:2: RuntimeWarning: invalid value encountered in power
  return tanh(_a6_ + tanh(_a1_**x1*sin(_a0_ + (_a1_ - tanh(x1/(_a2_/x1 + _a5_)))/cos(_a1_))**2/_a7_)**_a4_)**(2*x1)
<lambdifygenerated-2107>:2: RuntimeWarning: invalid value encountered in power
  return tanh(_a6_ + tanh(_a1_**x1*sin(_a0_ + (_a1_ - tanh(x1/(_a2_/x1 + _a5_)))/cos(_a1_))**2/_a7_)**_a4_)**(3*x1)
<lambdifygenerated-2108>:2: RuntimeWarning: invalid value encountered in power
  return tanh(_a6_ + tanh(_a1_**x1*sin(_a0_ + (_a1_ - tanh(x1/(_a2_/x1 + _a5_)))/cos(_a1_))**2/_a7_)**_a4_)**(3*x1)
<lambdifygenerated-2109>:2: RuntimeWarning: invalid value encountered in power
  return tanh(_a6_ + tanh(_a1_**x1*sin(_a0_ + (_a1_ - tanh(x1/(_a2_/x1 + _a5_)))/cos(_a1_))**2/_a7_)**_a4_)**(2*x1 + x1**x1)
<lambdifygenerated-2110>:2: RuntimeWarning: invalid value encountered in power
  return tanh(_a6_ + tanh(_a1_**x1*sin(_a0_ + (_a1_ - tanh(x1/(_a2_/x1 + _a5_)))/cos(_a1_))**2/_a7_)**_a4_)**(2*x1 + x1**x1)
<lambdifygenerated-2111>:2: RuntimeWarning: invalid value encountered in power
  return tanh(_a6_ + tanh(_a1_**x1*sin(_a0_ + (_a1_ - tanh(x1/(_a2_/x1 + _a5_)))/cos(_a1_))**2/_a7_)**_a4_)**(_a7_**x1 + 2*x1)
<lambdifygenerated-2112>:2: RuntimeWarning: invalid value encountered in power
  return tanh(_a6_ + tanh(_a1_**x1*sin(_a0_ + (_a1_ - tanh(x1/(_a2_/x1 + _a5_)))/cos(_a1_))**2/_a7_)**_a4_)**(_a7_**x1 + 2*x1)
<lambdifygenerated-2113>:2: RuntimeWarning: invalid value encountered in power
  return tanh(_a6_ + tanh(_a1_**x1*sin(_a0_ + (_a1_ - tanh(x1/(_a2_/x1 + _a5_)))/cos(_a1_))**2/_a7_)**_a4_)**(_a7_**(x1**x1) + 2*x1)
<lambdifygenerated-2114>:2: RuntimeWarning: invalid value encountered in power
  return tanh(_a6_ + tanh(_a1_**x1*sin(_a0_ + (_a1_ - tanh(x1/(_a2_/x1 + _a5_)))/cos(_a1_))**2/_a7_)**_a4_)**(_a7_**(x1**x1) + 2*x1)
<lambdifygenerated-2115>:2: RuntimeWarning: invalid value encountered in power
  return tanh(_a6_ + tanh(_a1_**x1*sin(_a0_ + (_a1_ - tanh(x1/(_a2_/x1 + _a5_)))/cos(_a1_))**2/_a7_)**_a4_)**(_a7_**(_a3_**x1) + 2*x1)
<lambdifygenerated-2116>:2: RuntimeWarning: invalid value encountered in power
  return tanh(_a6_ + tanh(_a1_**x1*sin(_a0_ + (_a1_ - tanh(x1/(_a2_/x1 + _a5_)))/cos(_a1_))**2/_a7_)**_a4_)**(_a7_**(_a3_**x1) + 2*x1)
<lambdifygenerated-2117>:2: RuntimeWarning: invalid value encountered in power
  return tanh(_a6_ + tanh(_a1_**x1*sin(_a0_ + (_a1_ - tanh(x1/(_a2_/x1 + _a5_)))/cos(_a1_))**2/_a7_)**_a4_)**(_a7_**(_a3_**(x1**2)) + 2*x1)
<lambdifygenerated-2118>:2: RuntimeWarning: invalid value encountered in power
  return tanh(_a6_ + tanh(_a1_**x1*sin(_a0_ + (_a1_ - tanh(x1/(_a2_/x1 + _a5_)))/cos(_a1_))**2/_a7_)**_a4_)**(_a7_**(_a3_**(x1**2)) + 2*x1)

interpolation

<lambdifygenerated-2119>:2: RuntimeWarning: invalid value encountered in power
  return tanh(_a6_ + tanh(_a1_**x1*sin(_a0_ + (_a1_ - tanh(x1/(_a2_/x1 + _a5_)))/cos(_a1_))**2/_a7_)**_a4_)**(_a7_**(_a3_**(x1*tanh(x1))) + 2*x1)
<lambdifygenerated-2120>:2: RuntimeWarning: invalid value encountered in power
  return tanh(_a6_ + tanh(_a1_**x1*sin(_a0_ + (_a1_ - tanh(x1/(_a2_/x1 + _a5_)))/cos(_a1_))**2/_a7_)**_a4_)**(_a7_**(_a3_**(x1*tanh(x1))) + 2*x1)
<lambdifygenerated-2121>:2: RuntimeWarning: invalid value encountered in power
  return tanh(_a6_ + tanh(_a1_**x1*sin(_a0_ + (_a1_ - tanh(x1/(_a2_/x1 + _a5_)))/cos(_a1_))**2/_a7_)**_a4_)**(_a7_**(_a3_**(x1*tanh(x1))) + 2*x1)
<lambdifygenerated-2122>:2: RuntimeWarning: invalid value encountered in power
  return tanh(_a6_ + tanh(_a1_**x1*sin(_a0_ + (_a1_ - tanh(x1/(_a2_/x1 + _a5_)))/cos(_a1_))**2/_a7_)**_a4_)**(_a7_**(_a3_**(x1*tanh(x1))) + 2*x1)
<lambdifygenerated-2123>:2: RuntimeWarning: invalid value encountered in power
  return tanh(_a6_ + tanh(_a1_**x1*sin(_a0_ + (_a1_ - tanh(x1/(_a2_/x1 + _a5_)))/cos(_a1_))**2/_a7_)**_a4_)**(_a7_**(_a3_**(_a5_*tanh(x1))) + 2*x1)
<lambdifygenerated-2124>:2: RuntimeWarning: invalid value encountered in power
  return tanh(_a6_ + tanh(_a1_**x1*sin(_a0_ + (_a1_ - tanh(x1/(_a2_/x1 + _a5_)))/cos(_a1_))**2/_a7_)**_a4_)**(_a7_**(_a3_**(_a5_*tanh(x1))) + 2*x1)
<lambdifygenerated-2125>:2: RuntimeWarning: invalid value encountered in power
  return tanh(_a6_ + tanh(_a1_**x1*sin(_a0_ + (_a1_ - tanh(x1/(_a2_/x1 + _a5_)))/cos(_a1_))**2/_a7_)**_a4_)**(_a7_**(_a3_**(_a5_*tanh(x1))) + x1 + cosh(x1))
<lambdifygenerated-2126>:2: RuntimeWarning: invalid value encountered in power
  return tanh(_a6_ + tanh(_a1_**x1*sin(_a0_ + (_a1_ - tanh(x1/(_a2_/x1 + _a5_)))/cos(_a1_))**2/_a7_)**_a4_)**(_a7_**(_a3_**(_a5_*tanh(x1))) + x1 + cosh(x1))
<lambdifygenerated-2127>:2: RuntimeWarning: invalid value encountered in power
  return tanh(_a6_ + tanh(_a1_**x1*sin(_a0_ + (_a1_ - tanh(x1/(_a2_/x1 + _a5_)))/cos(_a1_))**2/_a7_)**_a4_)**(_a7_**(_a3_**(_a5_*tanh(x1))) + x1 + cosh(x1))
<lambdifygenerated-2128>:2: RuntimeWarning: invalid value encountered in power
  return tanh(_a6_ + tanh(_a1_**x1*sin(_a0_ + (_a1_ - tanh(x1/(_a2_/x1 + _a5_)))/cos(_a1_))**2/_a7_)**_a4_)**(_a7_**(_a3_**(_a5_*tanh(x1))) + x1 + cosh(x1))
<lambdifygenerated-2129>:2: RuntimeWarning: invalid value encountered in power
  return tanh(_a6_ + tanh(_a1_**x1*sin(_a0_ + (_a1_ - tanh(x1/(_a2_/x1 + _a5_)))/cos(_a1_))**2/_a7_)**_a4_)**(_a7_**(_a3_**(_a5_*tanh(x1))) + x1**2 + cosh(x1))
<lambdifygenerated-2130>:2: RuntimeWarning: invalid value encountered in power
  return tanh(_a6_ + tanh(_a1_**x1*sin(_a0_ + (_a1_ - tanh(x1/(_a2_/x1 + _a5_)))/cos(_a1_))**2/_a7_)**_a4_)**(_a7_**(_a3_**(_a5_*tanh(x1))) + x1**2 + cosh(x1))
<lambdifygenerated-2131>:2: RuntimeWarning: invalid value encountered in power
  return tanh(_a6_ + tanh(_a1_**x1*sin(_a0_ + (_a1_ - tanh(x1/(_a2_/x1 + _a5_)))/cos(_a1_))**2/_a7_)**_a4_)**(_a7_**(_a3_**(_a5_*tanh(x1))) + x1**2 + cosh(x1))
<lambdifygenerated-2132>:2: RuntimeWarning: invalid value encountered in power
  return tanh(_a6_ + tanh(_a1_**x1*sin(_a0_ + (_a1_ - tanh(x1/(_a2_/x1 + _a5_)))/cos(_a1_))**2/_a7_)**_a4_)**(_a7_**(_a3_**(_a5_*tanh(x1))) + x1**2 + cosh(x1))
<lambdifygenerated-2133>:2: RuntimeWarning: invalid value encountered in power
  return tanh(_a6_ + tanh(_a1_**x1*sin(_a0_ + (_a1_ - tanh(x1/(_a2_/x1 + _a5_)))/cos(_a1_))**2/_a7_)**_a4_)**(_a0_*x1 + _a7_**(_a3_**(_a5_*tanh(x1))) + cosh(x1))
<lambdifygenerated-2134>:2: RuntimeWarning: invalid value encountered in power
  return tanh(_a6_ + tanh(_a1_**x1*sin(_a0_ + (_a1_ - tanh(x1/(_a2_/x1 + _a5_)))/cos(_a1_))**2/_a7_)**_a4_)**(_a0_*x1 + _a7_**(_a3_**(_a5_*tanh(x1))) + cosh(x1))
<lambdifygenerated-2135>:2: RuntimeWarning: invalid value encountered in power
  return tanh(_a6_ + tanh(_a1_**x1*sin(_a0_ + (_a1_ - tanh(x1/(_a2_/x1 + _a5_)))/cos(_a1_))**2/_a7_)**_a4_)**(_a0_*x1 + _a7_**(_a3_**(_a5_*tanh(x1))) + cosh(x1))
<lambdifygenerated-2136>:2: RuntimeWarning: invalid value encountered in power
  return tanh(_a6_ + tanh(_a1_**x1*sin(_a0_ + (_a1_ - tanh(x1/(_a2_/x1 + _a5_)))/cos(_a1_))**2/_a7_)**_a4_)**(_a0_*x1 + _a7_**(_a3_**(_a5_*tanh(x1))) + cosh(x1))
<lambdifygenerated-2137>:2: RuntimeWarning: invalid value encountered in power
  return tanh(_a6_ + tanh(_a1_**x1*sin(_a0_ + (_a1_ - tanh(x1/(_a2_/x1 + _a5_)))/cos(_a1_))**2/_a7_)**_a4_)**(_a0_*x1 + _a7_**(_a3_**(_a5_*tanh(x1))) + cosh(x1))
<lambdifygenerated-2138>:2: RuntimeWarning: invalid value encountered in power
  return tanh(_a6_ + tanh(_a1_**x1*sin(_a0_ + (_a1_ - tanh(x1/(_a2_/x1 + _a5_)))/cos(_a1_))**2/_a7_)**_a4_)**(_a0_*x1 + _a7_**(_a3_**(_a5_*tanh(x1))) + cosh(x1))

         x1         y  rep    ymodel      ybms
3745  0.997  0.987381  0.0  0.980139  0.987439
3746  0.998  0.987426  0.0  0.980137  0.987479
3747  0.998  0.987470  0.0  0.980135  0.987519
3748  0.999  0.987515  0.0  0.980133  0.987560

extrapolation

         x1         y  rep    ymodel     ybms
3750  1.001  0.987604  0.0  0.980128  0.98764
3751  1.002  0.987648  0.0  0.980126  0.98768
3752  1.002  0.987692  0.0  0.980124  0.98772
3753  1.003  0.987737  0.0  0.980121  0.98776

3750

<lambdifygenerated-2153>:2: RuntimeWarning: invalid value encountered in power
  return x1*sin(x1*(x1 + tan(x1**x1)))
<lambdifygenerated-2154>:2: RuntimeWarning: invalid value encountered in power
  return x1*sin(x1*(x1 + tan(x1**x1)))
<lambdifygenerated-2159>:2: RuntimeWarning: invalid value encountered in power
  return x1*sin(x1*(x1 + tan((x1*(x1 + cos(x1)))**x1)))
<lambdifygenerated-2160>:2: RuntimeWarning: invalid value encountered in power
  return x1*sin(x1*(x1 + tan((x1*(x1 + cos(x1)))**x1)))
<lambdifygenerated-2161>:2: RuntimeWarning: invalid value encountered in power
  return x1*sin(x1*(x1 + tan((x1*(x1 + cos(2*x1)))**x1)))
<lambdifygenerated-2162>:2: RuntimeWarning: invalid value encountered in power
  return x1*sin(x1*(x1 + tan((x1*(x1 + cos(2*x1)))**x1)))
<lambdifygenerated-2163>:2: RuntimeWarning: invalid value encountered in power
  return x1*sin(x1*(x1 + tan((x1*(x1 + cos(_a5_ + x1)))**x1)))
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-2164>:2: RuntimeWarning: invalid value encountered in power
  return x1*sin(x1*(x1 + tan((x1*(x1 + cos(_a5_ + x1)))**x1)))
<lambdifygenerated-2165>:2: RuntimeWarning: invalid value encountered in power
  return x1*sin(x1*(x1 + tan((x1*(x1 + cos(_a5_ + x1**2)))**x1)))
<lambdifygenerated-2166>:2: RuntimeWarning: invalid value encountered in power
  return x1*sin(x1*(x1 + tan((x1*(x1 + cos(_a5_ + x1**2)))**x1)))
<lambdifygenerated-2167>:2: RuntimeWarning: invalid value encountered in power
  return x1*sin(x1*(x1 + tan((x1*(x1 + cos(_a2_*x1 + _a5_)))**x1)))
<lambdifygenerated-2168>:2: RuntimeWarning: invalid value encountered in power
  return x1*sin(x1*(x1 + tan((x1*(x1 + cos(_a2_*x1 + _a5_)))**x1)))
<lambdifygenerated-2169>:2: RuntimeWarning: invalid value encountered in power
  return x1*sin(x1*(x1 + tan((x1*(x1 + cos(_a2_*sin(x1) + _a5_)))**x1)))
<lambdifygenerated-2170>:2: RuntimeWarning: invalid value encountered in power
  return x1*sin(x1*(x1 + tan((x1*(x1 + cos(_a2_*sin(x1) + _a5_)))**x1)))
<lambdifygenerated-2171>:2: RuntimeWarning: invalid value encountered in power
  return x1*sin(x1*(x1 + tan((x1*(x1 + cos(_a2_*sin(x1) + _a5_)))**x1)))
<lambdifygenerated-2172>:2: RuntimeWarning: invalid value encountered in power
  return x1*sin(x1*(x1 + tan((x1*(x1 + cos(_a2_*sin(x1) + _a5_)))**x1)))
<lambdifygenerated-2173>:2: RuntimeWarning: invalid value encountered in power
  return x1*sin(x1*(x1 + tan((x1*(2*x1 + cos(_a2_*sin(x1) + _a5_)))**x1)))
<lambdifygenerated-2174>:2: RuntimeWarning: invalid value encountered in power
  return x1*sin(x1*(x1 + tan((x1*(2*x1 + cos(_a2_*sin(x1) + _a5_)))**x1)))
<lambdifygenerated-2175>:2: RuntimeWarning: invalid value encountered in power
  return x1*sin(x1*(x1 + tan((x1*(_a3_ + x1 + cos(_a2_*sin(x1) + _a5_)))**x1)))
<lambdifygenerated-2176>:2: RuntimeWarning: invalid value encountered in power
  return x1*sin(x1*(x1 + tan((x1*(_a3_ + x1 + cos(_a2_*sin(x1) + _a5_)))**x1)))
<lambdifygenerated-2177>:2: RuntimeWarning: invalid value encountered in power
  return x1*sin(x1*(x1 + tan((x1*(_a3_ + x1**2 + cos(_a2_*sin(x1) + _a5_)))**x1)))
<lambdifygenerated-2178>:2: RuntimeWarning: invalid value encountered in power
  return x1*sin(x1*(x1 + tan((x1*(_a3_ + x1**2 + cos(_a2_*sin(x1) + _a5_)))**x1)))
<lambdifygenerated-2179>:2: RuntimeWarning: invalid value encountered in power
  return x1*sin(x1*(x1 + tan((x1*(_a3_ + x1**3 + cos(_a2_*sin(x1) + _a5_)))**x1)))
<lambdifygenerated-2180>:2: RuntimeWarning: invalid value encountered in power
  return x1*sin(x1*(x1 + tan((x1*(_a3_ + x1**3 + cos(_a2_*sin(x1) + _a5_)))**x1)))
<lambdifygenerated-2181>:2: RuntimeWarning: invalid value encountered in power
  return x1*sin(x1*(x1 + tan((x1*(_a3_ + _a4_*x1**2 + cos(_a2_*sin(x1) + _a5_)))**x1)))
<lambdifygenerated-2182>:2: RuntimeWarning: invalid value encountered in power
  return x1*sin(x1*(x1 + tan((x1*(_a3_ + _a4_*x1**2 + cos(_a2_*sin(x1) + _a5_)))**x1)))
<lambdifygenerated-2183>:2: RuntimeWarning: invalid value encountered in power
  return x1*sin(x1*(x1 + tan((x1*(_a3_ + _a4_*x1**3 + cos(_a2_*sin(x1) + _a5_)))**x1)))
<lambdifygenerated-2184>:2: RuntimeWarning: invalid value encountered in power
  return x1*sin(x1*(x1 + tan((x1*(_a3_ + _a4_*x1**3 + cos(_a2_*sin(x1) + _a5_)))**x1)))
<lambdifygenerated-2185>:2: RuntimeWarning: invalid value encountered in power
  return x1*sin(x1*(x1 + tan((x1*(_a3_ + 2*_a4_*x1**3 + cos(_a2_*sin(x1) + _a5_)))**x1)))
<lambdifygenerated-2186>:2: RuntimeWarning: invalid value encountered in power
  return x1*sin(x1*(x1 + tan((x1*(_a3_ + 2*_a4_*x1**3 + cos(_a2_*sin(x1) + _a5_)))**x1)))
<lambdifygenerated-2187>:2: RuntimeWarning: invalid value encountered in power
  return x1*sin(x1*(x1 + tan((x1*(_a3_ + _a4_*x1**2*(x1 + cos(x1)) + cos(_a2_*sin(x1) + _a5_)))**x1)))
<lambdifygenerated-2188>:2: RuntimeWarning: invalid value encountered in power
  return x1*sin(x1*(x1 + tan((x1*(_a3_ + _a4_*x1**2*(x1 + cos(x1)) + cos(_a2_*sin(x1) + _a5_)))**x1)))
<lambdifygenerated-2189>:2: RuntimeWarning: invalid value encountered in power
  return x1*sin(x1*(x1 + tan((x1*(_a3_ + _a4_*x1**2*(x1 + cos(x1)) + cos(_a2_*sin(x1) + _a5_)))**x1)))
<lambdifygenerated-2190>:2: RuntimeWarning: invalid value encountered in power
  return x1*sin(x1*(x1 + tan((x1*(_a3_ + _a4_*x1**2*(x1 + cos(x1)) + cos(_a2_*sin(x1) + _a5_)))**x1)))
<lambdifygenerated-2191>:2: RuntimeWarning: invalid value encountered in power
  return x1*sin(x1*(x1 + tan((x1*(_a3_ + _a4_*x1**2*(_a4_ + cos(x1)) + cos(_a2_*sin(x1) + _a5_)))**x1)))
<lambdifygenerated-2192>:2: RuntimeWarning: invalid value encountered in power
  return x1*sin(x1*(x1 + tan((x1*(_a3_ + _a4_*x1**2*(_a4_ + cos(x1)) + cos(_a2_*sin(x1) + _a5_)))**x1)))
<lambdifygenerated-2193>:2: RuntimeWarning: invalid value encountered in power
  return x1*sin(x1*(x1 + tan((x1*(_a3_ + _a4_*x1**3*(_a4_ + cos(x1)) + cos(_a2_*sin(x1) + _a5_)))**x1)))
<lambdifygenerated-2194>:2: RuntimeWarning: invalid value encountered in power
  return x1*sin(x1*(x1 + tan((x1*(_a3_ + _a4_*x1**3*(_a4_ + cos(x1)) + cos(_a2_*sin(x1) + _a5_)))**x1)))
<lambdifygenerated-2195>:2: RuntimeWarning: invalid value encountered in power
  return x1*sin(x1*(x1 + tan((x1*(_a3_ + _a4_*_a5_*x1**2*(_a4_ + cos(x1)) + cos(_a2_*sin(x1) + _a5_)))**x1)))
<lambdifygenerated-2196>:2: RuntimeWarning: invalid value encountered in power
  return x1*sin(x1*(x1 + tan((x1*(_a3_ + _a4_*_a5_*x1**2*(_a4_ + cos(x1)) + cos(_a2_*sin(x1) + _a5_)))**x1)))
<lambdifygenerated-2197>:2: RuntimeWarning: invalid value encountered in power
  return x1*sin(x1*(x1 + tan((x1*(_a3_ + _a4_*_a5_*x1**3*(_a4_ + cos(x1)) + cos(_a2_*sin(x1) + _a5_)))**x1)))
<lambdifygenerated-2198>:2: RuntimeWarning: invalid value encountered in power
  return x1*sin(x1*(x1 + tan((x1*(_a3_ + _a4_*_a5_*x1**3*(_a4_ + cos(x1)) + cos(_a2_*sin(x1) + _a5_)))**x1)))
<lambdifygenerated-2199>:2: RuntimeWarning: invalid value encountered in power
  return x1*sin(x1*(x1 + tan((x1*(_a1_*_a4_*_a5_*x1**2*(_a4_ + cos(x1)) + _a3_ + cos(_a2_*sin(x1) + _a5_)))**x1)))
<lambdifygenerated-2200>:2: RuntimeWarning: invalid value encountered in power
  return x1*sin(x1*(x1 + tan((x1*(_a1_*_a4_*_a5_*x1**2*(_a4_ + cos(x1)) + _a3_ + cos(_a2_*sin(x1) + _a5_)))**x1)))
<lambdifygenerated-2201>:2: RuntimeWarning: invalid value encountered in power
  return x1*sin(x1*(x1 + tan((x1*(_a1_*_a4_*_a5_*x1*(_a4_ + cos(x1)) + _a3_ + cos(_a2_*sin(x1) + _a5_)))**x1)))
<lambdifygenerated-2202>:2: RuntimeWarning: invalid value encountered in power
  return x1*sin(x1*(x1 + tan((x1*(_a1_*_a4_*_a5_*x1*(_a4_ + cos(x1)) + _a3_ + cos(_a2_*sin(x1) + _a5_)))**x1)))
<lambdifygenerated-2203>:2: RuntimeWarning: invalid value encountered in power
  return x1*sin(x1*(x1 + tan((x1*(_a1_*_a4_*_a5_*_a6_*(_a4_ + cos(x1)) + _a3_ + cos(_a2_*sin(x1) + _a5_)))**x1)))
<lambdifygenerated-2204>:2: RuntimeWarning: invalid value encountered in power
  return x1*sin(x1*(x1 + tan((x1*(_a1_*_a4_*_a5_*_a6_*(_a4_ + cos(x1)) + _a3_ + cos(_a2_*sin(x1) + _a5_)))**x1)))
<lambdifygenerated-2205>:2: RuntimeWarning: invalid value encountered in power
  return x1*sin(x1*(x1 + tan((x1*((1/2)*_a1_*_a4_*_a5_*_a6_*(_a4_ + cos(x1)) + _a3_ + cos(_a2_*sin(x1) + _a5_)))**x1)))
<lambdifygenerated-2206>:2: RuntimeWarning: invalid value encountered in power
  return x1*sin(x1*(x1 + tan((x1*((1/2)*_a1_*_a4_*_a5_*_a6_*(_a4_ + cos(x1)) + _a3_ + cos(_a2_*sin(x1) + _a5_)))**x1)))
<lambdifygenerated-2207>:2: RuntimeWarning: invalid value encountered in power
  return x1*sin(x1*(x1 + tan((x1*((1/2)*_a1_*_a4_*_a5_*_a6_*(_a4_ + cos(x1)) + _a3_ + cos(_a2_*sin(x1) + _a5_)))**x1)))
<lambdifygenerated-2208>:2: RuntimeWarning: invalid value encountered in power
  return x1*sin(x1*(x1 + tan((x1*((1/2)*_a1_*_a4_*_a5_*_a6_*(_a4_ + cos(x1)) + _a3_ + cos(_a2_*sin(x1) + _a5_)))**x1)))
<lambdifygenerated-2209>:2: RuntimeWarning: invalid value encountered in power
  return x1*sin(x1*(x1 + tan((x1*(_a1_*_a4_*_a5_*_a6_*x1*(_a4_ + cos(x1))/(_a2_ + x1) + _a3_ + cos(_a2_*sin(x1) + _a5_)))**x1)))
<lambdifygenerated-2210>:2: RuntimeWarning: invalid value encountered in power
  return x1*sin(x1*(x1 + tan((x1*(_a1_*_a4_*_a5_*_a6_*x1*(_a4_ + cos(x1))/(_a2_ + x1) + _a3_ + cos(_a2_*sin(x1) + _a5_)))**x1)))
<lambdifygenerated-2211>:2: RuntimeWarning: invalid value encountered in power
  return x1*sin(x1*(x1 + tan((x1*(2*_a1_*_a4_*_a5_*_a6_*x1*(_a4_ + cos(x1))/(_a2_ + x1) + _a3_ + cos(_a2_*sin(x1) + _a5_)))**x1)))
<lambdifygenerated-2212>:2: RuntimeWarning: invalid value encountered in power
  return x1*sin(x1*(x1 + tan((x1*(2*_a1_*_a4_*_a5_*_a6_*x1*(_a4_ + cos(x1))/(_a2_ + x1) + _a3_ + cos(_a2_*sin(x1) + _a5_)))**x1)))
<lambdifygenerated-2213>:2: RuntimeWarning: invalid value encountered in power
  return x1*sin(x1*(x1 + tan((x1*(_a1_*_a4_*_a5_*_a6_*(_a4_ + cos(x1))*(_a7_ + x1)/(_a2_ + x1) + _a3_ + cos(_a2_*sin(x1) + _a5_)))**x1)))
<lambdifygenerated-2214>:2: RuntimeWarning: invalid value encountered in power
  return x1*sin(x1*(x1 + tan((x1*(_a1_*_a4_*_a5_*_a6_*(_a4_ + cos(x1))*(_a7_ + x1)/(_a2_ + x1) + _a3_ + cos(_a2_*sin(x1) + _a5_)))**x1)))
<lambdifygenerated-2215>:2: RuntimeWarning: invalid value encountered in power
  return x1*sin(x1*(x1 + tan((x1*(_a1_*_a4_*_a5_*_a6_*(_a4_ + cos(x1))*(_a7_ + x1)/(_a2_ + x1) + _a3_ + cos(_a2_*sin(x1) + _a5_)))**x1)))
<lambdifygenerated-2216>:2: RuntimeWarning: invalid value encountered in power
  return x1*sin(x1*(x1 + tan((x1*(_a1_*_a4_*_a5_*_a6_*(_a4_ + cos(x1))*(_a7_ + x1)/(_a2_ + x1) + _a3_ + cos(_a2_*sin(x1) + _a5_)))**x1)))
<lambdifygenerated-2217>:2: RuntimeWarning: invalid value encountered in power
  return x1*sin(x1*(x1 + tan((_a6_*(_a1_*_a4_*_a5_*_a6_*(_a4_ + cos(x1))*(_a7_ + x1)/(_a2_ + x1) + _a3_ + cos(_a2_*sin(x1) + _a5_)))**x1)))

interpolation

<lambdifygenerated-2221>:2: RuntimeWarning: invalid value encountered in power
  return x1*sin(x1*(_a5_ + tan((_a6_*(_a1_*_a4_*_a5_*_a6_*(_a4_ + cos(x1))*(_a7_ + x1)/(_a2_ + x1) + _a3_ + cos(_a2_*sin(x1) + _a5_)))**_a1_)))
<lambdifygenerated-2223>:2: RuntimeWarning: invalid value encountered in power
  return x1*sin(_a7_*(_a5_ + tan((_a6_*(_a1_*_a4_*_a5_*_a6_*(_a4_ + cos(x1))*(_a7_ + x1)/(_a2_ + x1) + _a3_ + cos(_a2_*sin(x1) + _a5_)))**_a1_)))
<lambdifygenerated-2225>:2: RuntimeWarning: invalid value encountered in power
  return _a0_*sin(_a7_*(_a5_ + tan((_a6_*(_a1_*_a4_*_a5_*_a6_*(_a4_ + cos(x1))*(_a7_ + x1)/(_a2_ + x1) + _a3_ + cos(_a2_*sin(x1) + _a5_)))**_a1_)))
<lambdifygenerated-2229>:2: RuntimeWarning: invalid value encountered in power
  return _a0_*sin(_a7_*(_a5_ + tan((_a6_*(_a1_*_a4_*_a5_*_a6_*(_a4_ + cos(x1))*(_a7_ + x1)/(_a2_ + x1) + _a3_ + cos(_a2_*sin(x1) + _a5_)))**_a1_)))
<lambdifygenerated-2231>:2: RuntimeWarning: invalid value encountered in power
  return _a0_*sin(_a7_*(_a5_ + tan((_a6_*(_a1_*_a4_*_a5_*_a6_*(_a4_ + cos(x1))*(_a7_ + x1)/(_a2_ + x1) + _a3_ + cos(_a2_*sin(x1) + _a5_)))**_a1_)))

         x1         y  rep    ymodel      ybms
3745  0.997  0.053138  1.0  0.053707  0.047522
3746  0.998  0.053057  1.0  0.053646  0.047289
3747  0.998  0.052975  1.0  0.053585  0.047055
3748  0.999  0.052894  1.0  0.053524  0.046819

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.052733  1.0  0.053403  0.046342
3751  1.002  0.052652  1.0  0.053342  0.046101
3752  1.002  0.052571  1.0  0.053282  0.045858
3753  1.003  0.052491  1.0  0.053222  0.045614

3750

<lambdifygenerated-2235>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1
<lambdifygenerated-2236>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1
<lambdifygenerated-2241>:2: RuntimeWarning: invalid value encountered in power
  return ((x1**2 + x1)/x1)**x1
<lambdifygenerated-2242>:2: RuntimeWarning: invalid value encountered in power
  return ((x1**2 + x1)/x1)**x1
<lambdifygenerated-2243>:2: RuntimeWarning: invalid value encountered in power
  return ((2*x1**2 + x1)/x1)**x1
<lambdifygenerated-2244>:2: RuntimeWarning: invalid value encountered in power
  return ((2*x1**2 + x1)/x1)**x1
<lambdifygenerated-2245>:2: RuntimeWarning: invalid value encountered in power
  return ((x1*(x1 + x1**x1) + x1)/x1)**x1
<lambdifygenerated-2246>:2: RuntimeWarning: invalid value encountered in power
  return ((x1*(x1 + x1**x1) + x1)/x1)**x1
<lambdifygenerated-2247>:2: RuntimeWarning: invalid value encountered in power
  return ((x1*(_a0_**x1 + x1) + x1)/x1)**x1
<lambdifygenerated-2253>:2: RuntimeWarning: invalid value encountered in power
  return ((x1*(_a0_**x1 + _a4_*x1) + x1)/x1)**x1
<lambdifygenerated-2255>:2: RuntimeWarning: invalid value encountered in power
  return ((x1*(_a0_**x1 + _a4_*tanh(x1)) + x1)/x1)**x1
<lambdifygenerated-2257>:2: RuntimeWarning: invalid value encountered in power
  return ((x1*(_a0_**x1 + _a4_*tanh(x1**2)) + x1)/x1)**x1
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-2258>:2: RuntimeWarning: invalid value encountered in power
  return ((x1*(_a0_**x1 + _a4_*tanh(x1**2)) + x1)/x1)**x1
<lambdifygenerated-2259>:2: RuntimeWarning: invalid value encountered in power
  return ((x1*(_a0_**x1 + _a4_*tanh(2*x1**2)) + x1)/x1)**x1
<lambdifygenerated-2260>:2: RuntimeWarning: invalid value encountered in power
  return ((x1*(_a0_**x1 + _a4_*tanh(2*x1**2)) + x1)/x1)**x1
<lambdifygenerated-2261>:2: RuntimeWarning: invalid value encountered in power
  return ((x1*(_a0_**x1 + _a4_*tanh(x1*(x1 + x1**x1))) + x1)/x1)**x1
<lambdifygenerated-2262>:2: RuntimeWarning: invalid value encountered in power
  return ((x1*(_a0_**x1 + _a4_*tanh(x1*(x1 + x1**x1))) + x1)/x1)**x1
<lambdifygenerated-2263>:2: RuntimeWarning: invalid value encountered in power
  return ((x1*(_a0_**x1 + _a4_*tanh(x1*(_a5_**x1 + x1))) + x1)/x1)**x1
<lambdifygenerated-2264>:2: RuntimeWarning: invalid value encountered in power
  return ((x1*(_a0_**x1 + _a4_*tanh(x1*(_a5_**x1 + x1))) + x1)/x1)**x1
<lambdifygenerated-2265>:2: RuntimeWarning: invalid value encountered in power
  return ((x1*(_a0_**x1 + _a4_*tanh(x1*(_a5_**(2*x1) + x1))) + x1)/x1)**x1
<lambdifygenerated-2266>:2: RuntimeWarning: invalid value encountered in power
  return ((x1*(_a0_**x1 + _a4_*tanh(x1*(_a5_**(2*x1) + x1))) + x1)/x1)**x1
<lambdifygenerated-2267>:2: RuntimeWarning: invalid value encountered in power
  return ((x1*(_a0_**x1 + _a4_*tanh(x1*(_a5_**(x1 + sin(x1)) + x1))) + x1)/x1)**x1
<lambdifygenerated-2268>:2: RuntimeWarning: invalid value encountered in power
  return ((x1*(_a0_**x1 + _a4_*tanh(x1*(_a5_**(x1 + sin(x1)) + x1))) + x1)/x1)**x1
<lambdifygenerated-2269>:2: RuntimeWarning: invalid value encountered in power
  return ((x1*(_a0_**x1 + _a4_*tanh(x1*(_a5_**(x1 + sin(x1)) + x1))) + x1)/x1)**x1
<lambdifygenerated-2270>:2: RuntimeWarning: invalid value encountered in power
  return ((x1*(_a0_**x1 + _a4_*tanh(x1*(_a5_**(x1 + sin(x1)) + x1))) + x1)/x1)**x1
<lambdifygenerated-2271>:2: RuntimeWarning: invalid value encountered in power
  return ((x1*(_a0_**x1 + _a4_*tanh(x1*(_a5_**(_a2_ + sin(x1)) + x1))) + x1)/x1)**x1
<lambdifygenerated-2272>:2: RuntimeWarning: invalid value encountered in power
  return ((x1*(_a0_**x1 + _a4_*tanh(x1*(_a5_**(_a2_ + sin(x1)) + x1))) + x1)/x1)**x1
<lambdifygenerated-2273>:2: RuntimeWarning: invalid value encountered in power
  return ((x1*(_a0_**x1 + _a4_*tanh(x1*(_a3_ + _a5_**(_a2_ + sin(x1))))) + x1)/x1)**x1
<lambdifygenerated-2274>:2: RuntimeWarning: invalid value encountered in power
  return ((x1*(_a0_**x1 + _a4_*tanh(x1*(_a3_ + _a5_**(_a2_ + sin(x1))))) + x1)/x1)**x1
<lambdifygenerated-2275>:2: RuntimeWarning: invalid value encountered in power
  return ((x1*(_a0_**x1 + _a4_*tanh(x1**2*(_a3_ + _a5_**(_a2_ + sin(x1))))) + x1)/x1)**x1
<lambdifygenerated-2276>:2: RuntimeWarning: invalid value encountered in power
  return ((x1*(_a0_**x1 + _a4_*tanh(x1**2*(_a3_ + _a5_**(_a2_ + sin(x1))))) + x1)/x1)**x1
<lambdifygenerated-2277>:2: RuntimeWarning: invalid value encountered in power
  return ((x1*(_a0_**x1 + _a4_*tanh(2*x1**2*(_a3_ + _a5_**(_a2_ + sin(x1))))) + x1)/x1)**x1
<lambdifygenerated-2278>:2: RuntimeWarning: invalid value encountered in power
  return ((x1*(_a0_**x1 + _a4_*tanh(2*x1**2*(_a3_ + _a5_**(_a2_ + sin(x1))))) + x1)/x1)**x1
<lambdifygenerated-2279>:2: RuntimeWarning: invalid value encountered in power
  return ((x1*(_a0_**x1 + _a4_*tanh(x1*(_a3_ + _a5_**(_a2_ + sin(x1)))*(x1 + 1))) + x1)/x1)**x1
<lambdifygenerated-2280>:2: RuntimeWarning: invalid value encountered in power
  return ((x1*(_a0_**x1 + _a4_*tanh(x1*(_a3_ + _a5_**(_a2_ + sin(x1)))*(x1 + 1))) + x1)/x1)**x1
<lambdifygenerated-2281>:2: RuntimeWarning: invalid value encountered in power
  return ((x1*(_a0_**x1 + _a4_*tanh(x1*(_a3_ + _a5_**(_a2_ + sin(x1)))*(x1 + 1))) + x1)/x1)**x1
<lambdifygenerated-2282>:2: RuntimeWarning: invalid value encountered in power
  return ((x1*(_a0_**x1 + _a4_*tanh(x1*(_a3_ + _a5_**(_a2_ + sin(x1)))*(x1 + 1))) + x1)/x1)**x1
<lambdifygenerated-2283>:2: RuntimeWarning: invalid value encountered in power
  return ((x1*(_a0_**x1 + _a4_*tanh(x1*(_a3_ + _a5_**(_a2_ + sin(x1)))*(x1 + x1/_a7_))) + x1)/x1)**x1
<lambdifygenerated-2284>:2: RuntimeWarning: invalid value encountered in power
  return ((x1*(_a0_**x1 + _a4_*tanh(x1*(_a3_ + _a5_**(_a2_ + sin(x1)))*(x1 + x1/_a7_))) + x1)/x1)**x1
<lambdifygenerated-2285>:2: RuntimeWarning: invalid value encountered in power
  return ((x1*(_a0_**x1 + _a4_*tanh(x1*(_a3_ + _a5_**(_a2_ + sin(x1)))*(_a6_ + x1/_a7_))) + x1)/x1)**x1
<lambdifygenerated-2286>:2: RuntimeWarning: invalid value encountered in power
  return ((x1*(_a0_**x1 + _a4_*tanh(x1*(_a3_ + _a5_**(_a2_ + sin(x1)))*(_a6_ + x1/_a7_))) + x1)/x1)**x1
<lambdifygenerated-2287>:2: RuntimeWarning: invalid value encountered in power
  return ((x1*(_a0_**x1 + _a4_*tanh(x1*(_a3_ + _a5_**(_a2_ + sin(x1)))*(_a6_ + x1/_a7_))) + x1)/x1)**x1
<lambdifygenerated-2288>:2: RuntimeWarning: invalid value encountered in power
  return ((x1*(_a0_**x1 + _a4_*tanh(x1*(_a3_ + _a5_**(_a2_ + sin(x1)))*(_a6_ + x1/_a7_))) + x1)/x1)**x1
<lambdifygenerated-2289>:2: RuntimeWarning: invalid value encountered in power
  return ((2*x1*(_a0_**x1 + _a4_*tanh(x1*(_a3_ + _a5_**(_a2_ + sin(x1)))*(_a6_ + x1/_a7_))) + x1)/x1)**x1
<lambdifygenerated-2290>:2: RuntimeWarning: invalid value encountered in power
  return ((2*x1*(_a0_**x1 + _a4_*tanh(x1*(_a3_ + _a5_**(_a2_ + sin(x1)))*(_a6_ + x1/_a7_))) + x1)/x1)**x1
<lambdifygenerated-2291>:2: RuntimeWarning: invalid value encountered in power
  return ((2*x1*(_a0_**x1 + _a4_*tanh(x1*(_a3_ + _a5_**(_a2_ + sin(x1)))*(_a6_ + x1/_a7_))) + x1)/x1)**x1
<lambdifygenerated-2292>:2: RuntimeWarning: invalid value encountered in power
  return ((2*x1*(_a0_**x1 + _a4_*tanh(x1*(_a3_ + _a5_**(_a2_ + sin(x1)))*(_a6_ + x1/_a7_))) + x1)/x1)**x1
<lambdifygenerated-2293>:2: RuntimeWarning: invalid value encountered in power
  return ((x1 + (_a0_**x1 + _a4_*tanh(x1*(_a3_ + _a5_**(_a2_ + sin(x1)))*(_a6_ + x1/_a7_)))*(x1**2 + x1))/x1)**x1
<lambdifygenerated-2294>:2: RuntimeWarning: invalid value encountered in power
  return ((x1 + (_a0_**x1 + _a4_*tanh(x1*(_a3_ + _a5_**(_a2_ + sin(x1)))*(_a6_ + x1/_a7_)))*(x1**2 + x1))/x1)**x1
<lambdifygenerated-2295>:2: RuntimeWarning: invalid value encountered in power
  return ((x1 + (_a0_**x1 + _a4_*tanh(x1*(_a3_ + _a5_**(_a2_ + sin(x1)))*(_a6_ + x1/_a7_)))*(_a3_*x1 + x1))/x1)**x1
<lambdifygenerated-2296>:2: RuntimeWarning: invalid value encountered in power
  return ((x1 + (_a0_**x1 + _a4_*tanh(x1*(_a3_ + _a5_**(_a2_ + sin(x1)))*(_a6_ + x1/_a7_)))*(_a3_*x1 + x1))/x1)**x1
<lambdifygenerated-2297>:2: RuntimeWarning: invalid value encountered in power
  return ((x1 + (_a0_**x1 + _a4_*tanh(x1*(_a3_ + _a5_**(_a2_ + sin(x1)))*(_a6_ + x1/_a7_)))*(2*_a3_*x1 + x1))/x1)**x1
<lambdifygenerated-2298>:2: RuntimeWarning: invalid value encountered in power
  return ((x1 + (_a0_**x1 + _a4_*tanh(x1*(_a3_ + _a5_**(_a2_ + sin(x1)))*(_a6_ + x1/_a7_)))*(2*_a3_*x1 + x1))/x1)**x1
<lambdifygenerated-2299>:2: RuntimeWarning: invalid value encountered in power
  return ((x1 + (_a0_**x1 + _a4_*tanh(x1*(_a3_ + _a5_**(_a2_ + sin(x1)))*(_a6_ + x1/_a7_)))*(_a3_*(_a7_ + x1) + x1))/x1)**x1
<lambdifygenerated-2300>:2: RuntimeWarning: invalid value encountered in power
  return ((x1 + (_a0_**x1 + _a4_*tanh(x1*(_a3_ + _a5_**(_a2_ + sin(x1)))*(_a6_ + x1/_a7_)))*(_a3_*(_a7_ + x1) + x1))/x1)**x1
<lambdifygenerated-2301>:2: RuntimeWarning: invalid value encountered in power
  return ((x1 + (_a0_**x1 + _a4_*tanh(x1*(_a3_ + _a5_**(_a2_ + sin(x1)))*(_a6_ + x1/_a7_)))*(_a3_*(_a7_ + x1) + x1))/x1)**x1
<lambdifygenerated-2302>:2: RuntimeWarning: invalid value encountered in power
  return ((x1 + (_a0_**x1 + _a4_*tanh(x1*(_a3_ + _a5_**(_a2_ + sin(x1)))*(_a6_ + x1/_a7_)))*(_a3_*(_a7_ + x1) + x1))/x1)**x1
<lambdifygenerated-2303>:2: RuntimeWarning: invalid value encountered in power
  return ((x1**2 + (_a0_**x1 + _a4_*tanh(x1*(_a3_ + _a5_**(_a2_ + sin(x1)))*(_a6_ + x1/_a7_)))*(_a3_*(_a7_ + x1) + x1))/x1)**x1
<lambdifygenerated-2304>:2: RuntimeWarning: invalid value encountered in power
  return ((x1**2 + (_a0_**x1 + _a4_*tanh(x1*(_a3_ + _a5_**(_a2_ + sin(x1)))*(_a6_ + x1/_a7_)))*(_a3_*(_a7_ + x1) + x1))/x1)**x1
<lambdifygenerated-2305>:2: RuntimeWarning: invalid value encountered in power
  return ((_a1_*x1 + (_a0_**x1 + _a4_*tanh(x1*(_a3_ + _a5_**(_a2_ + sin(x1)))*(_a6_ + x1/_a7_)))*(_a3_*(_a7_ + x1) + x1))/x1)**x1
<lambdifygenerated-2306>:2: RuntimeWarning: invalid value encountered in power
  return ((_a1_*x1 + (_a0_**x1 + _a4_*tanh(x1*(_a3_ + _a5_**(_a2_ + sin(x1)))*(_a6_ + x1/_a7_)))*(_a3_*(_a7_ + x1) + x1))/x1)**x1
<lambdifygenerated-2307>:2: RuntimeWarning: invalid value encountered in power
  return ((_a1_**2 + (_a0_**x1 + _a4_*tanh(x1*(_a3_ + _a5_**(_a2_ + sin(x1)))*(_a6_ + x1/_a7_)))*(_a3_*(_a7_ + x1) + x1))/x1)**x1
<lambdifygenerated-2308>:2: RuntimeWarning: invalid value encountered in power
  return ((_a1_**2 + (_a0_**x1 + _a4_*tanh(x1*(_a3_ + _a5_**(_a2_ + sin(x1)))*(_a6_ + x1/_a7_)))*(_a3_*(_a7_ + x1) + x1))/x1)**x1
<lambdifygenerated-2309>:2: RuntimeWarning: invalid value encountered in power
  return ((1/2)*(_a1_**2 + (_a0_**x1 + _a4_*tanh(x1*(_a3_ + _a5_**(_a2_ + sin(x1)))*(_a6_ + x1/_a7_)))*(_a3_*(_a7_ + x1) + x1))/x1)**x1
<lambdifygenerated-2310>:2: RuntimeWarning: invalid value encountered in power
  return ((1/2)*(_a1_**2 + (_a0_**x1 + _a4_*tanh(x1*(_a3_ + _a5_**(_a2_ + sin(x1)))*(_a6_ + x1/_a7_)))*(_a3_*(_a7_ + x1) + x1))/x1)**x1
<lambdifygenerated-2311>:2: RuntimeWarning: invalid value encountered in power
  return ((_a1_**2 + (_a0_**x1 + _a4_*tanh(x1*(_a3_ + _a5_**(_a2_ + sin(x1)))*(_a6_ + x1/_a7_)))*(_a3_*(_a7_ + x1) + x1))/(x1 + fac(x1)))**x1
<lambdifygenerated-2312>:2: RuntimeWarning: invalid value encountered in power
  return ((_a1_**2 + (_a0_**x1 + _a4_*tanh(x1*(_a3_ + _a5_**(_a2_ + sin(x1)))*(_a6_ + x1/_a7_)))*(_a3_*(_a7_ + x1) + x1))/(x1 + fac(x1)))**x1
<lambdifygenerated-2313>:2: RuntimeWarning: invalid value encountered in power
  return ((_a1_**2 + (_a0_**x1 + _a4_*tanh(x1*(_a3_ + _a5_**(_a2_ + sin(x1)))*(_a6_ + x1/_a7_)))*(_a3_*(_a7_ + x1) + x1))/(x1 + fac(fac(x1))))**x1
<lambdifygenerated-2314>:2: RuntimeWarning: invalid value encountered in power
  return ((_a1_**2 + (_a0_**x1 + _a4_*tanh(x1*(_a3_ + _a5_**(_a2_ + sin(x1)))*(_a6_ + x1/_a7_)))*(_a3_*(_a7_ + x1) + x1))/(x1 + fac(fac(x1))))**x1
<lambdifygenerated-2315>:2: RuntimeWarning: invalid value encountered in power
  return ((_a1_**2 + (_a0_**x1 + _a4_*tanh(x1*(_a3_ + _a5_**(_a2_ + sin(x1)))*(_a6_ + x1/_a7_)))*(_a3_*(_a7_ + x1) + x1))/(x1 + fac(fac(_a7_))))**x1
<lambdifygenerated-2316>:2: RuntimeWarning: invalid value encountered in power
  return ((_a1_**2 + (_a0_**x1 + _a4_*tanh(x1*(_a3_ + _a5_**(_a2_ + sin(x1)))*(_a6_ + x1/_a7_)))*(_a3_*(_a7_ + x1) + x1))/(x1 + fac(fac(_a7_))))**x1
<lambdifygenerated-2317>:2: RuntimeWarning: invalid value encountered in power
  return ((_a1_**2 + (_a0_**x1 + _a4_*tanh(x1*(_a3_ + _a5_**(_a2_ + sin(x1)))*(_a6_ + x1/_a7_)))*(_a3_*(_a7_ + x1) + x1))/(_a3_ + fac(fac(_a7_))))**x1
<lambdifygenerated-2318>:2: RuntimeWarning: invalid value encountered in power
  return ((_a1_**2 + (_a0_**x1 + _a4_*tanh(x1*(_a3_ + _a5_**(_a2_ + sin(x1)))*(_a6_ + x1/_a7_)))*(_a3_*(_a7_ + x1) + x1))/(_a3_ + fac(fac(_a7_))))**x1
<lambdifygenerated-2319>:2: RuntimeWarning: invalid value encountered in power
  return ((_a1_**2 + (_a0_**x1 + _a4_*tanh(x1*(_a3_ + _a5_**(_a2_ + sin(x1)))*(_a6_ + x1/_a7_)))*(_a3_*(_a7_ + x1) + x1))/(_a3_ + fac(fac(_a7_))))**_a7_
<lambdifygenerated-2323>:2: RuntimeWarning: invalid value encountered in power
  return ((_a1_**2 + (_a0_**x1 + _a4_*tanh(x1*(_a3_ + _a5_**(_a2_ + sin(x1)))*(_a6_ + x1/_a7_)))*(_a3_*(_a7_ + x1) + x1))/(_a3_ + fac(fac(_a7_))))**_a7_

interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.277484  2.0  0.283143  0.283259
3746  0.998  0.277627  2.0  0.283342  0.283580
3747  0.998  0.277770  2.0  0.283540  0.283902
3748  0.999  0.277912  2.0  0.283736  0.284225

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.278193  2.0  0.284127  0.284876
3751  1.002  0.278333  2.0  0.284321  0.285204
3752  1.002  0.278471  2.0  0.284514  0.285532
3753  1.003  0.278610  2.0  0.284707  0.285862

3750

<lambdifygenerated-2335>:2: RuntimeWarning: invalid value encountered in log
  return (x1 + tanh(log(x1)))/x1
<lambdifygenerated-2336>:2: RuntimeWarning: invalid value encountered in log
  return (x1 + tanh(log(x1)))/x1
<lambdifygenerated-2341>:2: RuntimeWarning: invalid value encountered in log
  return (x1 + tanh(log(sin(2*x1)/x1)))/x1
<lambdifygenerated-2342>:2: RuntimeWarning: invalid value encountered in log
  return (x1 + tanh(log(sin(2*x1)/x1)))/x1
<lambdifygenerated-2343>:2: RuntimeWarning: invalid value encountered in log
  return (x1 + tanh(log(sin(x1**2 + x1)/x1)))/x1
<lambdifygenerated-2344>:2: RuntimeWarning: invalid value encountered in log
  return (x1 + tanh(log(sin(x1**2 + x1)/x1)))/x1
<lambdifygenerated-2345>:2: RuntimeWarning: invalid value encountered in power
  return (x1 + tanh(log(sin(x1**(3/2) + x1)/x1)))/x1
<lambdifygenerated-2345>:2: RuntimeWarning: invalid value encountered in log
  return (x1 + tanh(log(sin(x1**(3/2) + x1)/x1)))/x1
<lambdifygenerated-2346>:2: RuntimeWarning: invalid value encountered in power
  return (x1 + tanh(log(sin(x1**(3/2) + x1)/x1)))/x1
<lambdifygenerated-2346>:2: RuntimeWarning: invalid value encountered in log
  return (x1 + tanh(log(sin(x1**(3/2) + x1)/x1)))/x1
<lambdifygenerated-2347>:2: RuntimeWarning: invalid value encountered in power
  return (x1 + tanh(log(sin(sqrt(2)*x1**(3/2) + x1)/x1)))/x1
<lambdifygenerated-2347>:2: RuntimeWarning: invalid value encountered in log
  return (x1 + tanh(log(sin(sqrt(2)*x1**(3/2) + x1)/x1)))/x1
<lambdifygenerated-2348>:2: RuntimeWarning: invalid value encountered in power
  return (x1 + tanh(log(sin(sqrt(2)*x1**(3/2) + x1)/x1)))/x1
<lambdifygenerated-2348>:2: RuntimeWarning: invalid value encountered in log
  return (x1 + tanh(log(sin(sqrt(2)*x1**(3/2) + x1)/x1)))/x1
<lambdifygenerated-2349>:2: RuntimeWarning: invalid value encountered in power
  return (x1 + tanh(log(sin(x1*sqrt(x1 + x1**x1) + x1)/x1)))/x1
<lambdifygenerated-2349>:2: RuntimeWarning: invalid value encountered in log
  return (x1 + tanh(log(sin(x1*sqrt(x1 + x1**x1) + x1)/x1)))/x1
<lambdifygenerated-2350>:2: RuntimeWarning: invalid value encountered in power
  return (x1 + tanh(log(sin(x1*sqrt(x1 + x1**x1) + x1)/x1)))/x1
<lambdifygenerated-2350>:2: RuntimeWarning: invalid value encountered in log
  return (x1 + tanh(log(sin(x1*sqrt(x1 + x1**x1) + x1)/x1)))/x1
<lambdifygenerated-2351>:2: RuntimeWarning: invalid value encountered in power
  return (x1 + tanh(log(sin(x1*sqrt(x1 + x1**((1/2)*x1)) + x1)/x1)))/x1
<lambdifygenerated-2351>:2: RuntimeWarning: invalid value encountered in log
  return (x1 + tanh(log(sin(x1*sqrt(x1 + x1**((1/2)*x1)) + x1)/x1)))/x1
<lambdifygenerated-2352>:2: RuntimeWarning: invalid value encountered in power
  return (x1 + tanh(log(sin(x1*sqrt(x1 + x1**((1/2)*x1)) + x1)/x1)))/x1
<lambdifygenerated-2352>:2: RuntimeWarning: invalid value encountered in log
  return (x1 + tanh(log(sin(x1*sqrt(x1 + x1**((1/2)*x1)) + x1)/x1)))/x1
<lambdifygenerated-2353>:2: RuntimeWarning: invalid value encountered in sqrt
  return (x1 + tanh(log(sin(x1*sqrt(x1 + (sqrt(2)*sqrt(x1))**x1) + x1)/x1)))/x1
<lambdifygenerated-2353>:2: RuntimeWarning: invalid value encountered in log
  return (x1 + tanh(log(sin(x1*sqrt(x1 + (sqrt(2)*sqrt(x1))**x1) + x1)/x1)))/x1
<lambdifygenerated-2354>:2: RuntimeWarning: invalid value encountered in sqrt
  return (x1 + tanh(log(sin(x1*sqrt(x1 + (sqrt(2)*sqrt(x1))**x1) + x1)/x1)))/x1
<lambdifygenerated-2354>:2: RuntimeWarning: invalid value encountered in log
  return (x1 + tanh(log(sin(x1*sqrt(x1 + (sqrt(2)*sqrt(x1))**x1) + x1)/x1)))/x1
<lambdifygenerated-2355>:2: RuntimeWarning: invalid value encountered in power
  return (x1 + tanh(log(sin(x1*sqrt(x1 + (x1 + x1**x1)**((1/2)*x1)) + x1)/x1)))/x1
<lambdifygenerated-2355>:2: RuntimeWarning: invalid value encountered in log
  return (x1 + tanh(log(sin(x1*sqrt(x1 + (x1 + x1**x1)**((1/2)*x1)) + x1)/x1)))/x1
<lambdifygenerated-2356>:2: RuntimeWarning: invalid value encountered in power
  return (x1 + tanh(log(sin(x1*sqrt(x1 + (x1 + x1**x1)**((1/2)*x1)) + x1)/x1)))/x1
<lambdifygenerated-2356>:2: RuntimeWarning: invalid value encountered in log
  return (x1 + tanh(log(sin(x1*sqrt(x1 + (x1 + x1**x1)**((1/2)*x1)) + x1)/x1)))/x1
<lambdifygenerated-2357>:2: RuntimeWarning: invalid value encountered in power
  return (x1 + tanh(log(sin(x1*sqrt(x1 + (x1 + (x1**2)**x1)**((1/2)*x1)) + x1)/x1)))/x1
<lambdifygenerated-2357>:2: RuntimeWarning: invalid value encountered in log
  return (x1 + tanh(log(sin(x1*sqrt(x1 + (x1 + (x1**2)**x1)**((1/2)*x1)) + x1)/x1)))/x1
<lambdifygenerated-2358>:2: RuntimeWarning: invalid value encountered in power
  return (x1 + tanh(log(sin(x1*sqrt(x1 + (x1 + (x1**2)**x1)**((1/2)*x1)) + x1)/x1)))/x1
<lambdifygenerated-2358>:2: RuntimeWarning: invalid value encountered in log
  return (x1 + tanh(log(sin(x1*sqrt(x1 + (x1 + (x1**2)**x1)**((1/2)*x1)) + x1)/x1)))/x1
<lambdifygenerated-2359>:2: RuntimeWarning: invalid value encountered in power
  return (x1 + tanh(log(sin(x1*sqrt(x1 + (x1 + (4*x1**2)**x1)**((1/2)*x1)) + x1)/x1)))/x1
<lambdifygenerated-2359>:2: RuntimeWarning: invalid value encountered in log
  return (x1 + tanh(log(sin(x1*sqrt(x1 + (x1 + (4*x1**2)**x1)**((1/2)*x1)) + x1)/x1)))/x1
<lambdifygenerated-2360>:2: RuntimeWarning: invalid value encountered in power
  return (x1 + tanh(log(sin(x1*sqrt(x1 + (x1 + (4*x1**2)**x1)**((1/2)*x1)) + x1)/x1)))/x1
<lambdifygenerated-2360>:2: RuntimeWarning: invalid value encountered in log
  return (x1 + tanh(log(sin(x1*sqrt(x1 + (x1 + (4*x1**2)**x1)**((1/2)*x1)) + x1)/x1)))/x1
<lambdifygenerated-2361>:2: RuntimeWarning: invalid value encountered in power
  return (x1 + tanh(log(sin(x1*sqrt(x1 + (x1 + ((x1 + 1)**2)**x1)**((1/2)*x1)) + x1)/x1)))/x1
<lambdifygenerated-2361>:2: RuntimeWarning: invalid value encountered in sqrt
  return (x1 + tanh(log(sin(x1*sqrt(x1 + (x1 + ((x1 + 1)**2)**x1)**((1/2)*x1)) + x1)/x1)))/x1
<lambdifygenerated-2361>:2: RuntimeWarning: invalid value encountered in log
  return (x1 + tanh(log(sin(x1*sqrt(x1 + (x1 + ((x1 + 1)**2)**x1)**((1/2)*x1)) + x1)/x1)))/x1
<lambdifygenerated-2362>:2: RuntimeWarning: invalid value encountered in power
  return (x1 + tanh(log(sin(x1*sqrt(x1 + (x1 + ((x1 + 1)**2)**x1)**((1/2)*x1)) + x1)/x1)))/x1
<lambdifygenerated-2362>:2: RuntimeWarning: invalid value encountered in sqrt
  return (x1 + tanh(log(sin(x1*sqrt(x1 + (x1 + ((x1 + 1)**2)**x1)**((1/2)*x1)) + x1)/x1)))/x1
<lambdifygenerated-2362>:2: RuntimeWarning: invalid value encountered in log
  return (x1 + tanh(log(sin(x1*sqrt(x1 + (x1 + ((x1 + 1)**2)**x1)**((1/2)*x1)) + x1)/x1)))/x1
<lambdifygenerated-2363>:2: RuntimeWarning: invalid value encountered in power
  return (x1 + tanh(log(sin(x1*sqrt(x1 + (x1 + ((_a7_/x1 + x1)**2)**x1)**((1/2)*x1)) + x1)/x1)))/x1
<lambdifygenerated-2363>:2: RuntimeWarning: invalid value encountered in log
  return (x1 + tanh(log(sin(x1*sqrt(x1 + (x1 + ((_a7_/x1 + x1)**2)**x1)**((1/2)*x1)) + x1)/x1)))/x1
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-2364>:2: RuntimeWarning: invalid value encountered in power
  return (x1 + tanh(log(sin(x1*sqrt(x1 + (x1 + ((_a7_/x1 + x1)**2)**x1)**((1/2)*x1)) + x1)/x1)))/x1
<lambdifygenerated-2364>:2: RuntimeWarning: invalid value encountered in log
  return (x1 + tanh(log(sin(x1*sqrt(x1 + (x1 + ((_a7_/x1 + x1)**2)**x1)**((1/2)*x1)) + x1)/x1)))/x1
<lambdifygenerated-2365>:2: RuntimeWarning: invalid value encountered in power
  return (x1 + tanh(log(sin(x1*sqrt(x1 + (x1 + ((_a7_/x1**2 + x1)**2)**x1)**((1/2)*x1)) + x1)/x1)))/x1
<lambdifygenerated-2365>:2: RuntimeWarning: invalid value encountered in sqrt
  return (x1 + tanh(log(sin(x1*sqrt(x1 + (x1 + ((_a7_/x1**2 + x1)**2)**x1)**((1/2)*x1)) + x1)/x1)))/x1
<lambdifygenerated-2365>:2: RuntimeWarning: invalid value encountered in log
  return (x1 + tanh(log(sin(x1*sqrt(x1 + (x1 + ((_a7_/x1**2 + x1)**2)**x1)**((1/2)*x1)) + x1)/x1)))/x1
<lambdifygenerated-2366>:2: RuntimeWarning: invalid value encountered in power
  return (x1 + tanh(log(sin(x1*sqrt(x1 + (x1 + ((_a7_/x1**2 + x1)**2)**x1)**((1/2)*x1)) + x1)/x1)))/x1
<lambdifygenerated-2366>:2: RuntimeWarning: invalid value encountered in sqrt
  return (x1 + tanh(log(sin(x1*sqrt(x1 + (x1 + ((_a7_/x1**2 + x1)**2)**x1)**((1/2)*x1)) + x1)/x1)))/x1
<lambdifygenerated-2366>:2: RuntimeWarning: invalid value encountered in log
  return (x1 + tanh(log(sin(x1*sqrt(x1 + (x1 + ((_a7_/x1**2 + x1)**2)**x1)**((1/2)*x1)) + x1)/x1)))/x1
<lambdifygenerated-2367>:2: RuntimeWarning: invalid value encountered in power
  return (x1 + tanh(log(sin(x1*sqrt(x1 + (x1 + ((_a7_/x1**4 + x1)**2)**x1)**((1/2)*x1)) + x1)/x1)))/x1
<lambdifygenerated-2367>:2: RuntimeWarning: invalid value encountered in sqrt
  return (x1 + tanh(log(sin(x1*sqrt(x1 + (x1 + ((_a7_/x1**4 + x1)**2)**x1)**((1/2)*x1)) + x1)/x1)))/x1
<lambdifygenerated-2367>:2: RuntimeWarning: invalid value encountered in log
  return (x1 + tanh(log(sin(x1*sqrt(x1 + (x1 + ((_a7_/x1**4 + x1)**2)**x1)**((1/2)*x1)) + x1)/x1)))/x1
<lambdifygenerated-2368>:2: RuntimeWarning: invalid value encountered in power
  return (x1 + tanh(log(sin(x1*sqrt(x1 + (x1 + ((_a7_/x1**4 + x1)**2)**x1)**((1/2)*x1)) + x1)/x1)))/x1
<lambdifygenerated-2368>:2: RuntimeWarning: invalid value encountered in sqrt
  return (x1 + tanh(log(sin(x1*sqrt(x1 + (x1 + ((_a7_/x1**4 + x1)**2)**x1)**((1/2)*x1)) + x1)/x1)))/x1
<lambdifygenerated-2368>:2: RuntimeWarning: invalid value encountered in log
  return (x1 + tanh(log(sin(x1*sqrt(x1 + (x1 + ((_a7_/x1**4 + x1)**2)**x1)**((1/2)*x1)) + x1)/x1)))/x1
<lambdifygenerated-2369>:2: RuntimeWarning: invalid value encountered in power
  return (x1 + tanh(log(sin(x1*sqrt(x1 + (x1 + ((x1 + _a7_/(_a0_**2*x1**2))**2)**x1)**((1/2)*x1)) + x1)/x1)))/x1
<lambdifygenerated-2369>:2: RuntimeWarning: invalid value encountered in sqrt
  return (x1 + tanh(log(sin(x1*sqrt(x1 + (x1 + ((x1 + _a7_/(_a0_**2*x1**2))**2)**x1)**((1/2)*x1)) + x1)/x1)))/x1
<lambdifygenerated-2369>:2: RuntimeWarning: invalid value encountered in log
  return (x1 + tanh(log(sin(x1*sqrt(x1 + (x1 + ((x1 + _a7_/(_a0_**2*x1**2))**2)**x1)**((1/2)*x1)) + x1)/x1)))/x1
<lambdifygenerated-2370>:2: RuntimeWarning: invalid value encountered in power
  return (x1 + tanh(log(sin(x1*sqrt(x1 + (x1 + ((x1 + _a7_/(_a0_**2*x1**2))**2)**x1)**((1/2)*x1)) + x1)/x1)))/x1
<lambdifygenerated-2370>:2: RuntimeWarning: invalid value encountered in sqrt
  return (x1 + tanh(log(sin(x1*sqrt(x1 + (x1 + ((x1 + _a7_/(_a0_**2*x1**2))**2)**x1)**((1/2)*x1)) + x1)/x1)))/x1
<lambdifygenerated-2370>:2: RuntimeWarning: invalid value encountered in log
  return (x1 + tanh(log(sin(x1*sqrt(x1 + (x1 + ((x1 + _a7_/(_a0_**2*x1**2))**2)**x1)**((1/2)*x1)) + x1)/x1)))/x1
<lambdifygenerated-2371>:2: RuntimeWarning: invalid value encountered in power
  return (x1 + tanh(log(sin(x1*sqrt(x1 + (x1 + ((x1 + _a7_/(_a0_**2*x1**4))**2)**x1)**((1/2)*x1)) + x1)/x1)))/x1
<lambdifygenerated-2371>:2: RuntimeWarning: invalid value encountered in sqrt
  return (x1 + tanh(log(sin(x1*sqrt(x1 + (x1 + ((x1 + _a7_/(_a0_**2*x1**4))**2)**x1)**((1/2)*x1)) + x1)/x1)))/x1
<lambdifygenerated-2371>:2: RuntimeWarning: invalid value encountered in log
  return (x1 + tanh(log(sin(x1*sqrt(x1 + (x1 + ((x1 + _a7_/(_a0_**2*x1**4))**2)**x1)**((1/2)*x1)) + x1)/x1)))/x1
<lambdifygenerated-2372>:2: RuntimeWarning: invalid value encountered in power
  return (x1 + tanh(log(sin(x1*sqrt(x1 + (x1 + ((x1 + _a7_/(_a0_**2*x1**4))**2)**x1)**((1/2)*x1)) + x1)/x1)))/x1
<lambdifygenerated-2372>:2: RuntimeWarning: invalid value encountered in sqrt
  return (x1 + tanh(log(sin(x1*sqrt(x1 + (x1 + ((x1 + _a7_/(_a0_**2*x1**4))**2)**x1)**((1/2)*x1)) + x1)/x1)))/x1
<lambdifygenerated-2372>:2: RuntimeWarning: invalid value encountered in log
  return (x1 + tanh(log(sin(x1*sqrt(x1 + (x1 + ((x1 + _a7_/(_a0_**2*x1**4))**2)**x1)**((1/2)*x1)) + x1)/x1)))/x1
<lambdifygenerated-2373>:2: RuntimeWarning: invalid value encountered in power
  return (x1 + tanh(log(sin(x1*sqrt(x1 + (x1 + ((x1 + _a7_/(_a0_**2*_a2_**2*x1**2))**2)**x1)**((1/2)*x1)) + x1)/x1)))/x1
<lambdifygenerated-2373>:2: RuntimeWarning: invalid value encountered in sqrt
  return (x1 + tanh(log(sin(x1*sqrt(x1 + (x1 + ((x1 + _a7_/(_a0_**2*_a2_**2*x1**2))**2)**x1)**((1/2)*x1)) + x1)/x1)))/x1
<lambdifygenerated-2373>:2: RuntimeWarning: invalid value encountered in log
  return (x1 + tanh(log(sin(x1*sqrt(x1 + (x1 + ((x1 + _a7_/(_a0_**2*_a2_**2*x1**2))**2)**x1)**((1/2)*x1)) + x1)/x1)))/x1
<lambdifygenerated-2374>:2: RuntimeWarning: invalid value encountered in power
  return (x1 + tanh(log(sin(x1*sqrt(x1 + (x1 + ((x1 + _a7_/(_a0_**2*_a2_**2*x1**2))**2)**x1)**((1/2)*x1)) + x1)/x1)))/x1
<lambdifygenerated-2374>:2: RuntimeWarning: invalid value encountered in sqrt
  return (x1 + tanh(log(sin(x1*sqrt(x1 + (x1 + ((x1 + _a7_/(_a0_**2*_a2_**2*x1**2))**2)**x1)**((1/2)*x1)) + x1)/x1)))/x1
<lambdifygenerated-2374>:2: RuntimeWarning: invalid value encountered in log
  return (x1 + tanh(log(sin(x1*sqrt(x1 + (x1 + ((x1 + _a7_/(_a0_**2*_a2_**2*x1**2))**2)**x1)**((1/2)*x1)) + x1)/x1)))/x1
<lambdifygenerated-2375>:2: RuntimeWarning: invalid value encountered in power
  return (x1 + tanh(log(sin(x1*sqrt(x1 + (x1 + ((x1 + 1/(_a0_**2*_a2_**2*_a7_))**2)**x1)**((1/2)*x1)) + x1)/x1)))/x1
<lambdifygenerated-2375>:2: RuntimeWarning: invalid value encountered in sqrt
  return (x1 + tanh(log(sin(x1*sqrt(x1 + (x1 + ((x1 + 1/(_a0_**2*_a2_**2*_a7_))**2)**x1)**((1/2)*x1)) + x1)/x1)))/x1
<lambdifygenerated-2375>:2: RuntimeWarning: invalid value encountered in log
  return (x1 + tanh(log(sin(x1*sqrt(x1 + (x1 + ((x1 + 1/(_a0_**2*_a2_**2*_a7_))**2)**x1)**((1/2)*x1)) + x1)/x1)))/x1
<lambdifygenerated-2376>:2: RuntimeWarning: invalid value encountered in power
  return (x1 + tanh(log(sin(x1*sqrt(x1 + (x1 + ((x1 + 1/(_a0_**2*_a2_**2*_a7_))**2)**x1)**((1/2)*x1)) + x1)/x1)))/x1
<lambdifygenerated-2376>:2: RuntimeWarning: invalid value encountered in sqrt
  return (x1 + tanh(log(sin(x1*sqrt(x1 + (x1 + ((x1 + 1/(_a0_**2*_a2_**2*_a7_))**2)**x1)**((1/2)*x1)) + x1)/x1)))/x1
<lambdifygenerated-2376>:2: RuntimeWarning: invalid value encountered in log
  return (x1 + tanh(log(sin(x1*sqrt(x1 + (x1 + ((x1 + 1/(_a0_**2*_a2_**2*_a7_))**2)**x1)**((1/2)*x1)) + x1)/x1)))/x1
<lambdifygenerated-2377>:2: RuntimeWarning: invalid value encountered in power
  return (x1 + tanh(log(sin(x1*sqrt(x1 + (x1 + ((x1 + 1/(_a0_**2*_a2_**2*_a7_))**2)**x1)**((1/2)*x1)) + x1)/x1)))/x1
<lambdifygenerated-2377>:2: RuntimeWarning: invalid value encountered in sqrt
  return (x1 + tanh(log(sin(x1*sqrt(x1 + (x1 + ((x1 + 1/(_a0_**2*_a2_**2*_a7_))**2)**x1)**((1/2)*x1)) + x1)/x1)))/x1
<lambdifygenerated-2377>:2: RuntimeWarning: invalid value encountered in log
  return (x1 + tanh(log(sin(x1*sqrt(x1 + (x1 + ((x1 + 1/(_a0_**2*_a2_**2*_a7_))**2)**x1)**((1/2)*x1)) + x1)/x1)))/x1
<lambdifygenerated-2378>:2: RuntimeWarning: invalid value encountered in power
  return (x1 + tanh(log(sin(x1*sqrt(x1 + (x1 + ((x1 + 1/(_a0_**2*_a2_**2*_a7_))**2)**x1)**((1/2)*x1)) + x1)/x1)))/x1
<lambdifygenerated-2378>:2: RuntimeWarning: invalid value encountered in sqrt
  return (x1 + tanh(log(sin(x1*sqrt(x1 + (x1 + ((x1 + 1/(_a0_**2*_a2_**2*_a7_))**2)**x1)**((1/2)*x1)) + x1)/x1)))/x1
<lambdifygenerated-2378>:2: RuntimeWarning: invalid value encountered in log
  return (x1 + tanh(log(sin(x1*sqrt(x1 + (x1 + ((x1 + 1/(_a0_**2*_a2_**2*_a7_))**2)**x1)**((1/2)*x1)) + x1)/x1)))/x1
<lambdifygenerated-2379>:2: RuntimeWarning: invalid value encountered in power
  return (x1 + tanh(log(sin(x1*sqrt(x1 + (x1 + ((x1 + 1/(_a0_**2*_a2_**2*_a7_))**2)**_a3_)**((1/2)*x1)) + x1)/x1)))/x1
<lambdifygenerated-2379>:2: RuntimeWarning: invalid value encountered in log
  return (x1 + tanh(log(sin(x1*sqrt(x1 + (x1 + ((x1 + 1/(_a0_**2*_a2_**2*_a7_))**2)**_a3_)**((1/2)*x1)) + x1)/x1)))/x1
<lambdifygenerated-2380>:2: RuntimeWarning: invalid value encountered in power
  return (x1 + tanh(log(sin(x1*sqrt(x1 + (x1 + ((x1 + 1/(_a0_**2*_a2_**2*_a7_))**2)**_a3_)**((1/2)*x1)) + x1)/x1)))/x1
<lambdifygenerated-2380>:2: RuntimeWarning: invalid value encountered in log
  return (x1 + tanh(log(sin(x1*sqrt(x1 + (x1 + ((x1 + 1/(_a0_**2*_a2_**2*_a7_))**2)**_a3_)**((1/2)*x1)) + x1)/x1)))/x1
<lambdifygenerated-2381>:2: RuntimeWarning: invalid value encountered in sqrt
  return (x1 + tanh(log(sin(x1*sqrt(x1 + (x1**2 + ((x1 + 1/(_a0_**2*_a2_**2*_a7_))**2)**_a3_)**((1/2)*x1)) + x1)/x1)))/x1
<lambdifygenerated-2381>:2: RuntimeWarning: invalid value encountered in log
  return (x1 + tanh(log(sin(x1*sqrt(x1 + (x1**2 + ((x1 + 1/(_a0_**2*_a2_**2*_a7_))**2)**_a3_)**((1/2)*x1)) + x1)/x1)))/x1
<lambdifygenerated-2382>:2: RuntimeWarning: invalid value encountered in sqrt
  return (x1 + tanh(log(sin(x1*sqrt(x1 + (x1**2 + ((x1 + 1/(_a0_**2*_a2_**2*_a7_))**2)**_a3_)**((1/2)*x1)) + x1)/x1)))/x1
<lambdifygenerated-2382>:2: RuntimeWarning: invalid value encountered in log
  return (x1 + tanh(log(sin(x1*sqrt(x1 + (x1**2 + ((x1 + 1/(_a0_**2*_a2_**2*_a7_))**2)**_a3_)**((1/2)*x1)) + x1)/x1)))/x1
<lambdifygenerated-2383>:2: RuntimeWarning: invalid value encountered in sqrt
  return (x1 + tanh(log(sin(x1*sqrt(x1 + (x1**2 + ((x1 + 1/(_a0_**2*_a2_**2*_a7_))**2)**_a3_)**((1/2)*x1)) + x1)/x1)))/x1
<lambdifygenerated-2383>:2: RuntimeWarning: invalid value encountered in log
  return (x1 + tanh(log(sin(x1*sqrt(x1 + (x1**2 + ((x1 + 1/(_a0_**2*_a2_**2*_a7_))**2)**_a3_)**((1/2)*x1)) + x1)/x1)))/x1
<lambdifygenerated-2384>:2: RuntimeWarning: invalid value encountered in sqrt
  return (x1 + tanh(log(sin(x1*sqrt(x1 + (x1**2 + ((x1 + 1/(_a0_**2*_a2_**2*_a7_))**2)**_a3_)**((1/2)*x1)) + x1)/x1)))/x1
<lambdifygenerated-2384>:2: RuntimeWarning: invalid value encountered in log
  return (x1 + tanh(log(sin(x1*sqrt(x1 + (x1**2 + ((x1 + 1/(_a0_**2*_a2_**2*_a7_))**2)**_a3_)**((1/2)*x1)) + x1)/x1)))/x1
<lambdifygenerated-2385>:2: RuntimeWarning: invalid value encountered in power
  return (x1 + tanh(log(sin(x1*sqrt(x1 + (x1*x1**x1 + ((x1 + 1/(_a0_**2*_a2_**2*_a7_))**2)**_a3_)**((1/2)*x1)) + x1)/x1)))/x1
<lambdifygenerated-2385>:2: RuntimeWarning: invalid value encountered in log
  return (x1 + tanh(log(sin(x1*sqrt(x1 + (x1*x1**x1 + ((x1 + 1/(_a0_**2*_a2_**2*_a7_))**2)**_a3_)**((1/2)*x1)) + x1)/x1)))/x1
<lambdifygenerated-2386>:2: RuntimeWarning: invalid value encountered in power
  return (x1 + tanh(log(sin(x1*sqrt(x1 + (x1*x1**x1 + ((x1 + 1/(_a0_**2*_a2_**2*_a7_))**2)**_a3_)**((1/2)*x1)) + x1)/x1)))/x1
<lambdifygenerated-2386>:2: RuntimeWarning: invalid value encountered in log
  return (x1 + tanh(log(sin(x1*sqrt(x1 + (x1*x1**x1 + ((x1 + 1/(_a0_**2*_a2_**2*_a7_))**2)**_a3_)**((1/2)*x1)) + x1)/x1)))/x1
<lambdifygenerated-2387>:2: RuntimeWarning: invalid value encountered in power
  return (x1 + tanh(log(sin(x1*sqrt(x1 + (x1*sin(x1)**x1 + ((x1 + 1/(_a0_**2*_a2_**2*_a7_))**2)**_a3_)**((1/2)*x1)) + x1)/x1)))/x1
<lambdifygenerated-2387>:2: RuntimeWarning: invalid value encountered in log
  return (x1 + tanh(log(sin(x1*sqrt(x1 + (x1*sin(x1)**x1 + ((x1 + 1/(_a0_**2*_a2_**2*_a7_))**2)**_a3_)**((1/2)*x1)) + x1)/x1)))/x1
<lambdifygenerated-2388>:2: RuntimeWarning: invalid value encountered in power
  return (x1 + tanh(log(sin(x1*sqrt(x1 + (x1*sin(x1)**x1 + ((x1 + 1/(_a0_**2*_a2_**2*_a7_))**2)**_a3_)**((1/2)*x1)) + x1)/x1)))/x1
<lambdifygenerated-2388>:2: RuntimeWarning: invalid value encountered in log
  return (x1 + tanh(log(sin(x1*sqrt(x1 + (x1*sin(x1)**x1 + ((x1 + 1/(_a0_**2*_a2_**2*_a7_))**2)**_a3_)**((1/2)*x1)) + x1)/x1)))/x1
<lambdifygenerated-2389>:2: RuntimeWarning: invalid value encountered in power
  return (x1 + tanh(log(sin(x1*sqrt(x1 + (x1*sin(_a1_)**x1 + ((x1 + 1/(_a0_**2*_a2_**2*_a7_))**2)**_a3_)**((1/2)*x1)) + x1)/x1)))/x1
<lambdifygenerated-2389>:2: RuntimeWarning: invalid value encountered in log
  return (x1 + tanh(log(sin(x1*sqrt(x1 + (x1*sin(_a1_)**x1 + ((x1 + 1/(_a0_**2*_a2_**2*_a7_))**2)**_a3_)**((1/2)*x1)) + x1)/x1)))/x1

interpolation

<lambdifygenerated-2424>:2: RuntimeWarning: invalid value encountered in power
  return (_a6_ + tanh(log(sin(_a0_ + _a5_*sqrt(_a2_ + (x1*sin(_a1_)**x1 + ((x1 + 1/(_a0_**2*_a2_**2*_a7_))**2)**_a3_)**((1/2)*_a1_*_a2_*_a4_**(_a6_*x1))))/_a7_)))/_a2_
<lambdifygenerated-2425>:2: RuntimeWarning: invalid value encountered in power
  return (_a6_ + tanh(log(sin(_a0_ + _a5_*sqrt(_a2_ + (x1*sin(_a1_)**x1 + ((x1 + 1/(_a0_**2*_a2_**2*_a7_))**2)**_a3_)**((1/2)*_a1_*_a2_*_a4_**(_a6_*x1))))/_a7_)))/_a2_
<lambdifygenerated-2426>:2: RuntimeWarning: invalid value encountered in power
  return (_a6_ + tanh(log(sin(_a0_ + _a5_*sqrt(_a2_ + (x1*sin(_a1_)**x1 + ((x1 + 1/(_a0_**2*_a2_**2*_a7_))**2)**_a3_)**((1/2)*_a1_*_a2_*_a4_**(_a6_*x1))))/_a7_)))/_a2_

         x1         y  rep    ymodel      ybms
3745  0.997  0.306760  3.0  0.305741  0.307473
3746  0.998  0.307033  3.0  0.305995  0.307770
3747  0.998  0.307306  3.0  0.306248  0.308067
3748  0.999  0.307578  3.0  0.306500  0.308364

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.308120  3.0  0.307003  0.308956
3751  1.002  0.308390  3.0  0.307253  0.309251
3752  1.002  0.308660  3.0  0.307502  0.309546
3753  1.003  0.308928  3.0  0.307750  0.309841

3750

<lambdifygenerated-2431>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1
<lambdifygenerated-2432>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1
<lambdifygenerated-2433>:2: RuntimeWarning: invalid value encountered in power
  return tanh(x1)**x1
<lambdifygenerated-2434>:2: RuntimeWarning: invalid value encountered in power
  return tanh(x1)**x1
<lambdifygenerated-2447>:2: RuntimeWarning: divide by zero encountered in power
  return 0**x1
<lambdifygenerated-2448>:2: RuntimeWarning: divide by zero encountered in power
  return 0**x1
<lambdifygenerated-2449>:2: RuntimeWarning: divide by zero encountered in power
  return tanh(abs(tan(x1 - tanh(x1))/x1))**x1
<lambdifygenerated-2450>:2: RuntimeWarning: divide by zero encountered in power
  return tanh(abs(tan(x1 - tanh(x1))/x1))**x1

interpolation

/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-2519>:2: RuntimeWarning: invalid value encountered in power
  return tanh(abs(_a6_*(_a1_ + _a3_*x1**3)*tan(_a3_*_a7_*tanh(_a4_**2*(_a6_ + tanh(x1)))/(_a1_*(_a5_ + cosh(sin(x1**2/_a2_))) + _a7_) - _a5_)/_a3_))**(x1**x1)
<lambdifygenerated-2520>:2: RuntimeWarning: invalid value encountered in power
  return tanh(abs(_a6_*(_a1_ + _a3_*x1**3)*tan(_a3_*_a7_*tanh(_a4_**2*(_a6_ + tanh(x1)))/(_a1_*(_a5_ + cosh(sin(x1**2/_a2_))) + _a7_) - _a5_)/_a3_))**(x1**x1)

         x1         y  rep    ymodel      ybms
3745  0.997  0.965360  4.0  0.965420  0.965375
3746  0.998  0.965399  4.0  0.965457  0.965415
3747  0.998  0.965439  4.0  0.965494  0.965454
3748  0.999  0.965479  4.0  0.965531  0.965494

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.965559  4.0  0.965604  0.965573
3751  1.002  0.965598  4.0  0.965641  0.965612
3752  1.002  0.965638  4.0  0.965677  0.965651
3753  1.003  0.965678  4.0  0.965713  0.965691

3750

<lambdifygenerated-2547>:2: RuntimeWarning: invalid value encountered in power
  return tan(tan(tan(x1*x1**x1)))/x1**2
<lambdifygenerated-2548>:2: RuntimeWarning: invalid value encountered in power
  return tan(tan(tan(x1*x1**x1)))/x1**2
<lambdifygenerated-2549>:2: RuntimeWarning: invalid value encountered in power
  return tan(tan(tan(x1*sinh(x1)**x1)))/x1**2
<lambdifygenerated-2550>:2: RuntimeWarning: invalid value encountered in power
  return tan(tan(tan(x1*sinh(x1)**x1)))/x1**2
<lambdifygenerated-2551>:2: RuntimeWarning: invalid value encountered in power
  return tan(tan(tan(x1*sinh(tanh(x1))**x1)))/x1**2
<lambdifygenerated-2552>:2: RuntimeWarning: invalid value encountered in power
  return tan(tan(tan(x1*sinh(tanh(x1))**x1)))/x1**2
<lambdifygenerated-2557>:2: RuntimeWarning: invalid value encountered in power
  return tan(tan(tan(x1*sinh(tanh(x1*x1**(3*x1)))**x1)))/x1**2
<lambdifygenerated-2558>:2: RuntimeWarning: invalid value encountered in power
  return tan(tan(tan(x1*sinh(tanh(x1*x1**(3*x1)))**x1)))/x1**2
<lambdifygenerated-2559>:2: RuntimeWarning: invalid value encountered in power
  return tan(tan(tan(x1*sinh(tanh(x1))**x1)))/x1**2
<lambdifygenerated-2560>:2: RuntimeWarning: invalid value encountered in power
  return tan(tan(tan(x1*sinh(tanh(x1))**x1)))/x1**2
<lambdifygenerated-2561>:2: RuntimeWarning: invalid value encountered in power
  return tan(tan(tan(x1*sinh(tanh(x1*(x1**2)**(3*x1)))**x1)))/x1**2
<lambdifygenerated-2562>:2: RuntimeWarning: invalid value encountered in power
  return tan(tan(tan(x1*sinh(tanh(x1*(x1**2)**(3*x1)))**x1)))/x1**2
<lambdifygenerated-2563>:2: RuntimeWarning: invalid value encountered in power
  return tan(tan(tan(x1*sinh(tanh(x1*(tanh(x1)**3/x1)**(3*x1)))**x1)))/x1**2
<lambdifygenerated-2564>:2: RuntimeWarning: invalid value encountered in power
  return tan(tan(tan(x1*sinh(tanh(x1*(tanh(x1)**3/x1)**(3*x1)))**x1)))/x1**2
<lambdifygenerated-2565>:2: RuntimeWarning: invalid value encountered in power
  return tan(tan(tan(x1*sinh(tanh(x1*(tanh(x1**2)**3/x1)**(3*x1)))**x1)))/x1**2
<lambdifygenerated-2566>:2: RuntimeWarning: invalid value encountered in power
  return tan(tan(tan(x1*sinh(tanh(x1*(tanh(x1**2)**3/x1)**(3*x1)))**x1)))/x1**2
<lambdifygenerated-2567>:2: RuntimeWarning: invalid value encountered in power
  return tan(tan(tan(x1*sinh(tanh(x1*(tanh(2*x1**2)**3/x1)**(3*x1)))**x1)))/x1**2
<lambdifygenerated-2568>:2: RuntimeWarning: invalid value encountered in power
  return tan(tan(tan(x1*sinh(tanh(x1*(tanh(2*x1**2)**3/x1)**(3*x1)))**x1)))/x1**2
<lambdifygenerated-2569>:2: RuntimeWarning: invalid value encountered in power
  return tan(tan(tan(x1*sinh(tanh(x1*(tanh(x1*(x1**3 + x1))**3/x1)**(3*x1)))**x1)))/x1**2
<lambdifygenerated-2570>:2: RuntimeWarning: invalid value encountered in power
  return tan(tan(tan(x1*sinh(tanh(x1*(tanh(x1*(x1**3 + x1))**3/x1)**(3*x1)))**x1)))/x1**2
<lambdifygenerated-2571>:2: RuntimeWarning: invalid value encountered in power
  return tan(tan(tan(x1*sinh(tanh(x1*(tanh(x1*(x1 + sin(x1)**3))**3/x1)**(3*x1)))**x1)))/x1**2
<lambdifygenerated-2572>:2: RuntimeWarning: invalid value encountered in power
  return tan(tan(tan(x1*sinh(tanh(x1*(tanh(x1*(x1 + sin(x1)**3))**3/x1)**(3*x1)))**x1)))/x1**2
<lambdifygenerated-2573>:2: RuntimeWarning: invalid value encountered in power
  return tan(tan(tan(x1*sinh(tanh(x1*(tanh(x1*(x1 + sin(2*x1)**3))**3/x1)**(3*x1)))**x1)))/x1**2
<lambdifygenerated-2574>:2: RuntimeWarning: invalid value encountered in power
  return tan(tan(tan(x1*sinh(tanh(x1*(tanh(x1*(x1 + sin(2*x1)**3))**3/x1)**(3*x1)))**x1)))/x1**2
<lambdifygenerated-2575>:2: RuntimeWarning: invalid value encountered in power
  return tan(tan(tan(x1*sinh(tanh(x1*(tanh(x1*(x1 + sin(_a0_ + x1)**3))**3/x1)**(3*x1)))**x1)))/x1**2
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-2576>:2: RuntimeWarning: invalid value encountered in power
  return tan(tan(tan(x1*sinh(tanh(x1*(tanh(x1*(x1 + sin(_a0_ + x1)**3))**3/x1)**(3*x1)))**x1)))/x1**2
<lambdifygenerated-2577>:2: RuntimeWarning: invalid value encountered in power
  return tan(tan(tan(x1*sinh(tanh(x1*(tanh(x1*(x1 + sin(_a0_ + x1**2)**3))**3/x1)**(3*x1)))**x1)))/x1**2
<lambdifygenerated-2578>:2: RuntimeWarning: invalid value encountered in power
  return tan(tan(tan(x1*sinh(tanh(x1*(tanh(x1*(x1 + sin(_a0_ + x1**2)**3))**3/x1)**(3*x1)))**x1)))/x1**2
<lambdifygenerated-2579>:2: RuntimeWarning: invalid value encountered in power
  return tan(tan(tan(x1*sinh(tanh(x1*(tanh(x1*(x1 + sin(_a0_ + x1**2)**3))**3/x1)**(3*x1)))**x1)))/x1**2
<lambdifygenerated-2580>:2: RuntimeWarning: invalid value encountered in power
  return tan(tan(tan(x1*sinh(tanh(x1*(tanh(x1*(x1 + sin(_a0_ + x1**2)**3))**3/x1)**(3*x1)))**x1)))/x1**2
<lambdifygenerated-2581>:2: RuntimeWarning: invalid value encountered in log
  return tan(tan(tan(x1*sinh(tanh(x1*(tanh(x1*(x1 + sin(_a0_ + x1*log(x1))**3))**3/x1)**(3*x1)))**x1)))/x1**2
<lambdifygenerated-2582>:2: RuntimeWarning: invalid value encountered in log
  return tan(tan(tan(x1*sinh(tanh(x1*(tanh(x1*(x1 + sin(_a0_ + x1*log(x1))**3))**3/x1)**(3*x1)))**x1)))/x1**2
<lambdifygenerated-2583>:2: RuntimeWarning: invalid value encountered in power
  return tan(tan(tan(x1*sinh(tanh(x1*(tanh(x1*(x1 + sin(_a0_ + x1*log(_a7_))**3))**3/x1)**(3*x1)))**x1)))/x1**2
<lambdifygenerated-2584>:2: RuntimeWarning: invalid value encountered in power
  return tan(tan(tan(x1*sinh(tanh(x1*(tanh(x1*(x1 + sin(_a0_ + x1*log(_a7_))**3))**3/x1)**(3*x1)))**x1)))/x1**2
<lambdifygenerated-2585>:2: RuntimeWarning: invalid value encountered in power
  return tan(tan(tan(x1*sinh(tanh(x1*(tanh(x1*(_a7_ + sin(_a0_ + x1*log(_a7_))**3))**3/x1)**(3*x1)))**x1)))/x1**2
<lambdifygenerated-2586>:2: RuntimeWarning: invalid value encountered in power
  return tan(tan(tan(x1*sinh(tanh(x1*(tanh(x1*(_a7_ + sin(_a0_ + x1*log(_a7_))**3))**3/x1)**(3*x1)))**x1)))/x1**2
<lambdifygenerated-2587>:2: RuntimeWarning: invalid value encountered in power
  return tan(tan(tan(x1*sinh(tanh(x1*(tanh(_a6_*(_a7_ + sin(_a0_ + x1*log(_a7_))**3))**3/x1)**(3*x1)))**x1)))/x1**2
<lambdifygenerated-2588>:2: RuntimeWarning: invalid value encountered in power
  return tan(tan(tan(x1*sinh(tanh(x1*(tanh(_a6_*(_a7_ + sin(_a0_ + x1*log(_a7_))**3))**3/x1)**(3*x1)))**x1)))/x1**2
<lambdifygenerated-2589>:2: RuntimeWarning: invalid value encountered in power
  return tan(tan(tan(x1*sinh(tanh(x1*(tanh(_a6_*(_a7_ + sin(_a0_ + x1*log(_a7_))**3))**3/_a4_)**(3*x1)))**x1)))/x1**2
<lambdifygenerated-2590>:2: RuntimeWarning: invalid value encountered in power
  return tan(tan(tan(x1*sinh(tanh(x1*(tanh(_a6_*(_a7_ + sin(_a0_ + x1*log(_a7_))**3))**3/_a4_)**(3*x1)))**x1)))/x1**2
<lambdifygenerated-2591>:2: RuntimeWarning: invalid value encountered in power
  return tan(tan(tan(x1*sinh(tanh(x1*(tanh(_a6_*(_a7_ + sin(_a0_ + x1*log(_a7_))**3))**3/_a4_)**(3*x1**2)))**x1)))/x1**2
<lambdifygenerated-2592>:2: RuntimeWarning: invalid value encountered in power
  return tan(tan(tan(x1*sinh(tanh(x1*(tanh(_a6_*(_a7_ + sin(_a0_ + x1*log(_a7_))**3))**3/_a4_)**(3*x1**2)))**x1)))/x1**2
<lambdifygenerated-2593>:2: RuntimeWarning: invalid value encountered in power
  return tan(tan(tan(x1*sinh(tanh(x1*(tanh(_a6_*(_a7_ + sin(_a0_ + x1*log(_a7_))**3))**3/_a4_)**(3*x1)))**x1)))/x1**2
<lambdifygenerated-2594>:2: RuntimeWarning: invalid value encountered in power
  return tan(tan(tan(x1*sinh(tanh(x1*(tanh(_a6_*(_a7_ + sin(_a0_ + x1*log(_a7_))**3))**3/_a4_)**(3*x1)))**x1)))/x1**2
<lambdifygenerated-2595>:2: RuntimeWarning: invalid value encountered in power
  return tan(tan(tan(x1*sinh(tanh(x1*(tanh(_a6_*(_a7_ + sin(_a0_ + x1*log(_a7_))**3))**3/_a4_)**(-3*x1)))**x1)))/x1**2
<lambdifygenerated-2596>:2: RuntimeWarning: invalid value encountered in power
  return tan(tan(tan(x1*sinh(tanh(x1*(tanh(_a6_*(_a7_ + sin(_a0_ + x1*log(_a7_))**3))**3/_a4_)**(-3*x1)))**x1)))/x1**2
<lambdifygenerated-2597>:2: RuntimeWarning: invalid value encountered in power
  return tan(tan(tan(x1*sinh(tanh(x1*(tanh(_a6_*(_a7_ + sin(_a0_ + x1*log(_a7_))**3))**3/_a4_)**(-6*x1)))**x1)))/x1**2
<lambdifygenerated-2598>:2: RuntimeWarning: invalid value encountered in power
  return tan(tan(tan(x1*sinh(tanh(x1*(tanh(_a6_*(_a7_ + sin(_a0_ + x1*log(_a7_))**3))**3/_a4_)**(-6*x1)))**x1)))/x1**2
<lambdifygenerated-2599>:2: RuntimeWarning: invalid value encountered in power
  return tan(tan(tan(x1*sinh(tanh(x1*(tanh(_a6_*(_a7_ + sin(_a0_ + x1*log(_a7_))**3))**3/_a4_)**(-3*x1 - 3*x1**x1)))**x1)))/x1**2
<lambdifygenerated-2600>:2: RuntimeWarning: invalid value encountered in power
  return tan(tan(tan(x1*sinh(tanh(x1*(tanh(_a6_*(_a7_ + sin(_a0_ + x1*log(_a7_))**3))**3/_a4_)**(-3*x1 - 3*x1**x1)))**x1)))/x1**2
<lambdifygenerated-2601>:2: RuntimeWarning: invalid value encountered in power
  return tan(tan(tan(x1*sinh(tanh(x1*(tanh(_a6_*(_a7_ + sin(_a0_ + x1*log(_a7_))**3))**3/_a4_)**(-3*x1 - 3*(x1**2)**x1)))**x1)))/x1**2
<lambdifygenerated-2602>:2: RuntimeWarning: invalid value encountered in power
  return tan(tan(tan(x1*sinh(tanh(x1*(tanh(_a6_*(_a7_ + sin(_a0_ + x1*log(_a7_))**3))**3/_a4_)**(-3*x1 - 3*(x1**2)**x1)))**x1)))/x1**2
<lambdifygenerated-2603>:2: RuntimeWarning: invalid value encountered in power
  return tan(tan(tan(x1*sinh(tanh(x1*(tanh(_a6_*(_a7_ + sin(_a0_ + x1*log(_a7_))**3))**3/_a4_)**(-3*x1 - 3*(_a7_*x1)**x1)))**x1)))/x1**2
<lambdifygenerated-2604>:2: RuntimeWarning: invalid value encountered in power
  return tan(tan(tan(x1*sinh(tanh(x1*(tanh(_a6_*(_a7_ + sin(_a0_ + x1*log(_a7_))**3))**3/_a4_)**(-3*x1 - 3*(_a7_*x1)**x1)))**x1)))/x1**2
<lambdifygenerated-2605>:2: RuntimeWarning: invalid value encountered in power
  return tan(tan(tan(x1*sinh(tanh(x1*(tanh(_a6_*(_a7_ + sin(_a0_ + x1*log(_a7_))**3))**3/_a4_)**(-3*x1 - 3*(_a7_**2)**x1)))**x1)))/x1**2
<lambdifygenerated-2606>:2: RuntimeWarning: invalid value encountered in power
  return tan(tan(tan(x1*sinh(tanh(x1*(tanh(_a6_*(_a7_ + sin(_a0_ + x1*log(_a7_))**3))**3/_a4_)**(-3*x1 - 3*(_a7_**2)**x1)))**x1)))/x1**2
<lambdifygenerated-2607>:2: RuntimeWarning: invalid value encountered in power
  return tan(tan(tan(x1*sinh(tanh(x1*(tanh(_a6_*(_a7_ + sin(_a0_ + x1*log(_a7_))**3))**3/_a4_)**(-3*x1 - 3*(_a7_**2)**x1)))**x1)))/x1**2
<lambdifygenerated-2608>:2: RuntimeWarning: invalid value encountered in power
  return tan(tan(tan(x1*sinh(tanh(x1*(tanh(_a6_*(_a7_ + sin(_a0_ + x1*log(_a7_))**3))**3/_a4_)**(-3*x1 - 3*(_a7_**2)**x1)))**x1)))/x1**2
<lambdifygenerated-2609>:2: RuntimeWarning: invalid value encountered in power
  return tan(tan(tan(x1*sinh(tanh(x1*(tanh(_a6_*(_a7_ + sin(_a0_ + x1*log(_a7_))**3))**3/_a4_)**(3*x1 - 3*(_a7_**2)**x1)))**x1)))/x1**2
<lambdifygenerated-2610>:2: RuntimeWarning: invalid value encountered in power
  return tan(tan(tan(x1*sinh(tanh(x1*(tanh(_a6_*(_a7_ + sin(_a0_ + x1*log(_a7_))**3))**3/_a4_)**(3*x1 - 3*(_a7_**2)**x1)))**x1)))/x1**2
<lambdifygenerated-2611>:2: RuntimeWarning: invalid value encountered in power
  return tan(tan(tan(x1*sinh(tanh(x1*(tanh(_a6_*(_a7_ + sin(_a0_ + x1*log(_a7_))**3))**3/_a4_)**(3*x1**2 - 3*(_a7_**2)**x1)))**x1)))/x1**2
<lambdifygenerated-2612>:2: RuntimeWarning: invalid value encountered in power
  return tan(tan(tan(x1*sinh(tanh(x1*(tanh(_a6_*(_a7_ + sin(_a0_ + x1*log(_a7_))**3))**3/_a4_)**(3*x1**2 - 3*(_a7_**2)**x1)))**x1)))/x1**2
<lambdifygenerated-2613>:2: RuntimeWarning: invalid value encountered in power
  return tan(tan(tan(x1*sinh(tanh(x1*(tanh(_a6_*(_a7_ + sin(_a0_ + x1*log(_a7_))**3))**3/_a4_)**(-3*(_a7_**2)**x1 + 3*cos(x1)**2)))**x1)))/x1**2
<lambdifygenerated-2614>:2: RuntimeWarning: invalid value encountered in power
  return tan(tan(tan(x1*sinh(tanh(x1*(tanh(_a6_*(_a7_ + sin(_a0_ + x1*log(_a7_))**3))**3/_a4_)**(-3*(_a7_**2)**x1 + 3*cos(x1)**2)))**x1)))/x1**2
<lambdifygenerated-2615>:2: RuntimeWarning: invalid value encountered in power
  return tan(tan(tan(x1*sinh(tanh(x1*(tanh(_a6_*(_a7_ + sin(_a0_ + x1*log(_a7_))**3))**3/_a4_)**(-3*(_a7_**2)**x1 + 3*cos(_a4_)**2)))**x1)))/x1**2
<lambdifygenerated-2616>:2: RuntimeWarning: invalid value encountered in power
  return tan(tan(tan(x1*sinh(tanh(x1*(tanh(_a6_*(_a7_ + sin(_a0_ + x1*log(_a7_))**3))**3/_a4_)**(-3*(_a7_**2)**x1 + 3*cos(_a4_)**2)))**x1)))/x1**2
<lambdifygenerated-2617>:2: RuntimeWarning: invalid value encountered in power
  return tan(tan(tan(x1*sinh(tanh(x1*(tanh(_a6_*(_a7_ + sin(_a0_ + x1*log(_a7_))**3))**3/_a4_)**(3*x1*(-(_a7_**2)**x1 + cos(_a4_)**2)/_a3_)))**x1)))/x1**2
<lambdifygenerated-2618>:2: RuntimeWarning: invalid value encountered in power
  return tan(tan(tan(x1*sinh(tanh(x1*(tanh(_a6_*(_a7_ + sin(_a0_ + x1*log(_a7_))**3))**3/_a4_)**(3*x1*(-(_a7_**2)**x1 + cos(_a4_)**2)/_a3_)))**x1)))/x1**2
<lambdifygenerated-2619>:2: RuntimeWarning: invalid value encountered in power
  return tan(tan(tan(x1*sinh(tanh(x1*(tanh(_a6_*(_a7_ + sin(_a0_ + x1*log(_a7_))**3))**3/_a4_)**(3*x1**2*(-(_a7_**2)**x1 + cos(_a4_)**2)/_a3_)))**x1)))/x1**2
<lambdifygenerated-2620>:2: RuntimeWarning: invalid value encountered in power
  return tan(tan(tan(x1*sinh(tanh(x1*(tanh(_a6_*(_a7_ + sin(_a0_ + x1*log(_a7_))**3))**3/_a4_)**(3*x1**2*(-(_a7_**2)**x1 + cos(_a4_)**2)/_a3_)))**x1)))/x1**2
<lambdifygenerated-2621>:2: RuntimeWarning: invalid value encountered in power
  return tan(tan(tan(x1*sinh(tanh(x1*(tanh(_a6_*(_a7_ + sin(_a0_ + x1*log(_a7_))**3))**3/_a4_)**(3*_a1_*x1*(-(_a7_**2)**x1 + cos(_a4_)**2)/_a3_)))**x1)))/x1**2
<lambdifygenerated-2622>:2: RuntimeWarning: invalid value encountered in power
  return tan(tan(tan(x1*sinh(tanh(x1*(tanh(_a6_*(_a7_ + sin(_a0_ + x1*log(_a7_))**3))**3/_a4_)**(3*_a1_*x1*(-(_a7_**2)**x1 + cos(_a4_)**2)/_a3_)))**x1)))/x1**2
<lambdifygenerated-2623>:2: RuntimeWarning: invalid value encountered in power
  return tan(tan(tan(x1*sinh(tanh(x1*(tanh(_a6_*(_a7_ + sin(_a0_ + x1*log(_a7_))**3))**3/_a4_)**(3*_a1_*_a2_*(-(_a7_**2)**x1 + cos(_a4_)**2)/_a3_)))**x1)))/x1**2
<lambdifygenerated-2624>:2: RuntimeWarning: invalid value encountered in power
  return tan(tan(tan(x1*sinh(tanh(x1*(tanh(_a6_*(_a7_ + sin(_a0_ + x1*log(_a7_))**3))**3/_a4_)**(3*_a1_*_a2_*(-(_a7_**2)**x1 + cos(_a4_)**2)/_a3_)))**x1)))/x1**2
<lambdifygenerated-2627>:2: RuntimeWarning: invalid value encountered in power
  return tan(tan(tan(x1*sinh(tanh(_a1_*(tanh(_a6_*(_a7_ + sin(_a0_ + x1*log(_a7_))**3))**3/_a4_)**(3*_a1_*_a2_*(-(_a7_**2)**x1 + cos(_a4_)**2)/_a3_)))**_a5_)))/x1**2
<lambdifygenerated-2627>:2: RuntimeWarning: invalid value encountered in log
  return tan(tan(tan(x1*sinh(tanh(_a1_*(tanh(_a6_*(_a7_ + sin(_a0_ + x1*log(_a7_))**3))**3/_a4_)**(3*_a1_*_a2_*(-(_a7_**2)**x1 + cos(_a4_)**2)/_a3_)))**_a5_)))/x1**2
<lambdifygenerated-2629>:2: RuntimeWarning: invalid value encountered in power
  return tan(tan(tan(_a2_*sinh(tanh(_a1_*(tanh(_a6_*(_a7_ + sin(_a0_ + x1*log(_a7_))**3))**3/_a4_)**(3*_a1_*_a2_*(-(_a7_**2)**x1 + cos(_a4_)**2)/_a3_)))**_a5_)))/x1**2
<lambdifygenerated-2629>:2: RuntimeWarning: overflow encountered in power
  return tan(tan(tan(_a2_*sinh(tanh(_a1_*(tanh(_a6_*(_a7_ + sin(_a0_ + x1*log(_a7_))**3))**3/_a4_)**(3*_a1_*_a2_*(-(_a7_**2)**x1 + cos(_a4_)**2)/_a3_)))**_a5_)))/x1**2
<lambdifygenerated-2629>:2: RuntimeWarning: invalid value encountered in log
  return tan(tan(tan(_a2_*sinh(tanh(_a1_*(tanh(_a6_*(_a7_ + sin(_a0_ + x1*log(_a7_))**3))**3/_a4_)**(3*_a1_*_a2_*(-(_a7_**2)**x1 + cos(_a4_)**2)/_a3_)))**_a5_)))/x1**2
<lambdifygenerated-2631>:2: RuntimeWarning: invalid value encountered in log
  return tan(tan(tan(_a2_*sinh(tanh(_a1_*(tanh(_a6_*(_a7_ + sin(_a0_ + x1*log(_a7_))**3))**3/_a4_)**(3*_a1_*_a2_*(-(_a7_**2)**x1 + cos(_a4_)**2)/_a3_)))**_a5_)))/(_a7_*x1)
<lambdifygenerated-2631>:2: RuntimeWarning: invalid value encountered in power
  return tan(tan(tan(_a2_*sinh(tanh(_a1_*(tanh(_a6_*(_a7_ + sin(_a0_ + x1*log(_a7_))**3))**3/_a4_)**(3*_a1_*_a2_*(-(_a7_**2)**x1 + cos(_a4_)**2)/_a3_)))**_a5_)))/(_a7_*x1)

interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.308339  5.0  0.308567  0.308313
3746  0.998  0.308354  5.0  0.308602  0.308325
3747  0.998  0.308368  5.0  0.308638  0.308335
3748  0.999  0.308382  5.0  0.308673  0.308345

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.308407  5.0  0.308742  0.308363
3751  1.002  0.308419  5.0  0.308777  0.308371
3752  1.002  0.308430  5.0  0.308811  0.308378
3753  1.003  0.308441  5.0  0.308845  0.308385

3750

/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-2665>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1 + tanh(_a6_ + cos((_a4_ + _a5_)*(x1 + x1**x1))))
<lambdifygenerated-2666>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1 + tanh(_a6_ + cos((_a4_ + _a5_)*(x1 + x1**x1))))

interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.215897  6.0  0.214248  0.215813
3746  0.998  0.216041  6.0  0.214369  0.215956
3747  0.998  0.216186  6.0  0.214491  0.216099
3748  0.999  0.216330  6.0  0.214612  0.216242

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.216618  6.0  0.214853  0.216527
3751  1.002  0.216762  6.0  0.214973  0.216669
3752  1.002  0.216905  6.0  0.215093  0.216811
3753  1.003  0.217048  6.0  0.215213  0.216952

3750

<lambdifygenerated-2723>:2: RuntimeWarning: invalid value encountered in power
  return -x1*tanh(tanh(x1*x1**x1))
<lambdifygenerated-2724>:2: RuntimeWarning: invalid value encountered in power
  return -x1*tanh(tanh(x1*x1**x1))
<lambdifygenerated-2727>:2: RuntimeWarning: invalid value encountered in power
  return -x1*tanh(tanh(x1*(cosh(x1)/x1)**x1))
<lambdifygenerated-2728>:2: RuntimeWarning: invalid value encountered in power
  return -x1*tanh(tanh(x1*(cosh(x1)/x1)**x1))
<lambdifygenerated-2729>:2: RuntimeWarning: invalid value encountered in power
  return -x1*tanh(tanh(x1*(cosh(2*x1)/x1)**x1))
<lambdifygenerated-2730>:2: RuntimeWarning: invalid value encountered in power
  return -x1*tanh(tanh(x1*(cosh(2*x1)/x1)**x1))
<lambdifygenerated-2731>:2: RuntimeWarning: invalid value encountered in power
  return -x1*tanh(tanh(x1*(cosh(x1**2 + x1)/x1)**x1))
<lambdifygenerated-2732>:2: RuntimeWarning: invalid value encountered in power
  return -x1*tanh(tanh(x1*(cosh(x1**2 + x1)/x1)**x1))
<lambdifygenerated-2733>:2: RuntimeWarning: invalid value encountered in power
  return -x1*tanh(tanh(x1*(cosh(2*x1)/x1)**x1))
<lambdifygenerated-2734>:2: RuntimeWarning: invalid value encountered in power
  return -x1*tanh(tanh(x1*(cosh(2*x1)/x1)**x1))
<lambdifygenerated-2735>:2: RuntimeWarning: invalid value encountered in power
  return -x1*tanh(tanh(x1*(cosh(3*x1)/x1)**x1))
<lambdifygenerated-2736>:2: RuntimeWarning: invalid value encountered in power
  return -x1*tanh(tanh(x1*(cosh(3*x1)/x1)**x1))
<lambdifygenerated-2737>:2: RuntimeWarning: invalid value encountered in power
  return -x1*tanh(tanh(x1*(cosh(_a4_ + 2*x1)/x1)**x1))
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-2738>:2: RuntimeWarning: invalid value encountered in power
  return -x1*tanh(tanh(x1*(cosh(_a4_ + 2*x1)/x1)**x1))
<lambdifygenerated-2739>:2: RuntimeWarning: invalid value encountered in power
  return -x1*tanh(tanh(x1*(cosh(_a4_ + x1 + x1**x1)/x1)**x1))
<lambdifygenerated-2740>:2: RuntimeWarning: invalid value encountered in power
  return -x1*tanh(tanh(x1*(cosh(_a4_ + x1 + x1**x1)/x1)**x1))
<lambdifygenerated-2741>:2: RuntimeWarning: invalid value encountered in power
  return -x1*tanh(tanh(x1*(cosh(_a0_**x1 + _a4_ + x1)/x1)**x1))
<lambdifygenerated-2742>:2: RuntimeWarning: invalid value encountered in power
  return -x1*tanh(tanh(x1*(cosh(_a0_**x1 + _a4_ + x1)/x1)**x1))
<lambdifygenerated-2743>:2: RuntimeWarning: invalid value encountered in power
  return -x1*tanh(tanh(x1*(cosh(_a0_**sinh(x1) + _a4_ + x1)/x1)**x1))
<lambdifygenerated-2744>:2: RuntimeWarning: invalid value encountered in power
  return -x1*tanh(tanh(x1*(cosh(_a0_**sinh(x1) + _a4_ + x1)/x1)**x1))
<lambdifygenerated-2745>:2: RuntimeWarning: invalid value encountered in power
  return -x1*tanh(tanh(x1*(cosh(_a0_**sinh(x1) + _a4_ + x1)/x1)**x1))
<lambdifygenerated-2746>:2: RuntimeWarning: invalid value encountered in power
  return -x1*tanh(tanh(x1*(cosh(_a0_**sinh(x1) + _a4_ + x1)/x1)**x1))
<lambdifygenerated-2747>:2: RuntimeWarning: invalid value encountered in power
  return -x1*tanh(tanh(x1*(cosh((1/2)*_a0_**sinh(x1) + (1/2)*_a4_ + x1)/x1)**x1))
<lambdifygenerated-2748>:2: RuntimeWarning: invalid value encountered in power
  return -x1*tanh(tanh(x1*(cosh((1/2)*_a0_**sinh(x1) + (1/2)*_a4_ + x1)/x1)**x1))
<lambdifygenerated-2749>:2: RuntimeWarning: invalid value encountered in power
  return -x1*tanh(tanh(x1*(cosh(x1*(_a0_**sinh(x1) + _a4_)/(x1 + cosh(x1)) + x1)/x1)**x1))
<lambdifygenerated-2750>:2: RuntimeWarning: invalid value encountered in power
  return -x1*tanh(tanh(x1*(cosh(x1*(_a0_**sinh(x1) + _a4_)/(x1 + cosh(x1)) + x1)/x1)**x1))
<lambdifygenerated-2751>:2: RuntimeWarning: invalid value encountered in power
  return -x1*tanh(tanh(x1*(cosh(x1*(_a0_**sinh(x1) + _a4_)/(x1 + cosh(x1**2)) + x1)/x1)**x1))
<lambdifygenerated-2752>:2: RuntimeWarning: invalid value encountered in power
  return -x1*tanh(tanh(x1*(cosh(x1*(_a0_**sinh(x1) + _a4_)/(x1 + cosh(x1**2)) + x1)/x1)**x1))
<lambdifygenerated-2753>:2: RuntimeWarning: invalid value encountered in power
  return -x1*tanh(tanh(x1*(cosh(x1*(_a0_**sinh(x1) + _a4_)/(x1 + cosh(_a5_*x1)) + x1)/x1)**x1))
<lambdifygenerated-2754>:2: RuntimeWarning: invalid value encountered in power
  return -x1*tanh(tanh(x1*(cosh(x1*(_a0_**sinh(x1) + _a4_)/(x1 + cosh(_a5_*x1)) + x1)/x1)**x1))
<lambdifygenerated-2755>:2: RuntimeWarning: invalid value encountered in power
  return -x1*tanh(tanh(x1*(cosh(x1*(_a0_**sinh(x1) + _a4_)/(x1 + cosh(_a5_*x1)) + x1)/x1)**x1))
<lambdifygenerated-2756>:2: RuntimeWarning: invalid value encountered in power
  return -x1*tanh(tanh(x1*(cosh(x1*(_a0_**sinh(x1) + _a4_)/(x1 + cosh(_a5_*x1)) + x1)/x1)**x1))
<lambdifygenerated-2757>:2: RuntimeWarning: invalid value encountered in power
  return -x1*tanh(tanh(x1*(cosh(x1*(_a0_**sinh(x1) + _a4_)/(x1**2 + cosh(_a5_*x1)) + x1)/x1)**x1))
<lambdifygenerated-2758>:2: RuntimeWarning: invalid value encountered in power
  return -x1*tanh(tanh(x1*(cosh(x1*(_a0_**sinh(x1) + _a4_)/(x1**2 + cosh(_a5_*x1)) + x1)/x1)**x1))
<lambdifygenerated-2759>:2: RuntimeWarning: invalid value encountered in power
  return -x1*tanh(tanh(x1*(cosh(x1*(_a0_**sinh(x1) + _a4_)/(x1**2 + cosh(_a5_*x1)) + x1)/x1)**x1))
<lambdifygenerated-2760>:2: RuntimeWarning: invalid value encountered in power
  return -x1*tanh(tanh(x1*(cosh(x1*(_a0_**sinh(x1) + _a4_)/(x1**2 + cosh(_a5_*x1)) + x1)/x1)**x1))
<lambdifygenerated-2761>:2: RuntimeWarning: invalid value encountered in power
  return -x1*tanh(tanh(x1*(cosh(x1*(_a0_**sinh(x1) + _a4_)/(_a2_*x1 + cosh(_a5_*x1)) + x1)/x1)**x1))
<lambdifygenerated-2762>:2: RuntimeWarning: invalid value encountered in power
  return -x1*tanh(tanh(x1*(cosh(x1*(_a0_**sinh(x1) + _a4_)/(_a2_*x1 + cosh(_a5_*x1)) + x1)/x1)**x1))
<lambdifygenerated-2763>:2: RuntimeWarning: invalid value encountered in power
  return -x1*tanh(tanh(x1*(cosh(2*x1*(_a0_**sinh(x1) + _a4_)/(_a2_*x1 + cosh(_a5_*x1)) + x1)/x1)**x1))
<lambdifygenerated-2764>:2: RuntimeWarning: invalid value encountered in power
  return -x1*tanh(tanh(x1*(cosh(2*x1*(_a0_**sinh(x1) + _a4_)/(_a2_*x1 + cosh(_a5_*x1)) + x1)/x1)**x1))
<lambdifygenerated-2765>:2: RuntimeWarning: invalid value encountered in power
  return -x1*tanh(tanh(x1*(cosh(x1 + (_a0_**sinh(x1) + _a4_)*(x1**2 + x1)/(_a2_*x1 + cosh(_a5_*x1)))/x1)**x1))
<lambdifygenerated-2766>:2: RuntimeWarning: invalid value encountered in power
  return -x1*tanh(tanh(x1*(cosh(x1 + (_a0_**sinh(x1) + _a4_)*(x1**2 + x1)/(_a2_*x1 + cosh(_a5_*x1)))/x1)**x1))
<lambdifygenerated-2767>:2: RuntimeWarning: invalid value encountered in power
  return -x1*tanh(tanh(x1*(cosh(x1 + (_a0_**sinh(x1) + _a4_)*(2*x1**2 + x1)/(_a2_*x1 + cosh(_a5_*x1)))/x1)**x1))
<lambdifygenerated-2768>:2: RuntimeWarning: invalid value encountered in power
  return -x1*tanh(tanh(x1*(cosh(x1 + (_a0_**sinh(x1) + _a4_)*(2*x1**2 + x1)/(_a2_*x1 + cosh(_a5_*x1)))/x1)**x1))
<lambdifygenerated-2769>:2: RuntimeWarning: invalid value encountered in power
  return -x1*tanh(tanh(x1*(cosh(x1 + (_a0_**sinh(x1) + _a4_)*(2*x1**2 + x1)/(_a2_*x1 + cosh(_a5_*x1)))/x1)**x1))
<lambdifygenerated-2770>:2: RuntimeWarning: invalid value encountered in power
  return -x1*tanh(tanh(x1*(cosh(x1 + (_a0_**sinh(x1) + _a4_)*(2*x1**2 + x1)/(_a2_*x1 + cosh(_a5_*x1)))/x1)**x1))
<lambdifygenerated-2771>:2: RuntimeWarning: invalid value encountered in power
  return -x1*tanh(tanh(x1*(cosh(x1 + (_a0_**sinh(x1) + _a4_)*(x1*(_a7_ + x1) + x1)/(_a2_*x1 + cosh(_a5_*x1)))/x1)**x1))
<lambdifygenerated-2772>:2: RuntimeWarning: invalid value encountered in power
  return -x1*tanh(tanh(x1*(cosh(x1 + (_a0_**sinh(x1) + _a4_)*(x1*(_a7_ + x1) + x1)/(_a2_*x1 + cosh(_a5_*x1)))/x1)**x1))
<lambdifygenerated-2773>:2: RuntimeWarning: invalid value encountered in power
  return -x1*tanh(tanh(x1*(cosh(x1 + (_a0_**sinh(x1) + _a4_)*(x1*(_a7_ + x1) + x1)/(_a2_*x1 + cosh(_a5_*x1)))/x1)**x1))
<lambdifygenerated-2774>:2: RuntimeWarning: invalid value encountered in power
  return -x1*tanh(tanh(x1*(cosh(x1 + (_a0_**sinh(x1) + _a4_)*(x1*(_a7_ + x1) + x1)/(_a2_*x1 + cosh(_a5_*x1)))/x1)**x1))
<lambdifygenerated-2775>:2: RuntimeWarning: invalid value encountered in power
  return -x1*tanh(tanh(x1*(cosh(x1 + (_a0_**sinh(x1) + _a4_)*(_a2_ + x1*(_a7_ + x1))/(_a2_*x1 + cosh(_a5_*x1)))/x1)**x1))
<lambdifygenerated-2776>:2: RuntimeWarning: invalid value encountered in power
  return -x1*tanh(tanh(x1*(cosh(x1 + (_a0_**sinh(x1) + _a4_)*(_a2_ + x1*(_a7_ + x1))/(_a2_*x1 + cosh(_a5_*x1)))/x1)**x1))
<lambdifygenerated-2777>:2: RuntimeWarning: invalid value encountered in power
  return -x1*tanh(tanh(x1*(cosh(x1**2 + (_a0_**sinh(x1) + _a4_)*(_a2_ + x1*(_a7_ + x1))/(_a2_*x1 + cosh(_a5_*x1)))/x1)**x1))
<lambdifygenerated-2778>:2: RuntimeWarning: invalid value encountered in power
  return -x1*tanh(tanh(x1*(cosh(x1**2 + (_a0_**sinh(x1) + _a4_)*(_a2_ + x1*(_a7_ + x1))/(_a2_*x1 + cosh(_a5_*x1)))/x1)**x1))
<lambdifygenerated-2779>:2: RuntimeWarning: invalid value encountered in power
  return -x1*tanh(tanh(x1*(cosh(_a0_*x1 + (_a0_**sinh(x1) + _a4_)*(_a2_ + x1*(_a7_ + x1))/(_a2_*x1 + cosh(_a5_*x1)))/x1)**x1))
<lambdifygenerated-2780>:2: RuntimeWarning: invalid value encountered in power
  return -x1*tanh(tanh(x1*(cosh(_a0_*x1 + (_a0_**sinh(x1) + _a4_)*(_a2_ + x1*(_a7_ + x1))/(_a2_*x1 + cosh(_a5_*x1)))/x1)**x1))
<lambdifygenerated-2781>:2: RuntimeWarning: invalid value encountered in power
  return -x1*tanh(tanh(x1*(cosh(_a0_*_a1_ + (_a0_**sinh(x1) + _a4_)*(_a2_ + x1*(_a7_ + x1))/(_a2_*x1 + cosh(_a5_*x1)))/x1)**x1))
<lambdifygenerated-2782>:2: RuntimeWarning: invalid value encountered in power
  return -x1*tanh(tanh(x1*(cosh(_a0_*_a1_ + (_a0_**sinh(x1) + _a4_)*(_a2_ + x1*(_a7_ + x1))/(_a2_*x1 + cosh(_a5_*x1)))/x1)**x1))
<lambdifygenerated-2783>:2: RuntimeWarning: invalid value encountered in power
  return -x1*tanh(tanh(x1*(cosh(_a0_*_a1_ + (_a0_**sinh(x1) + _a4_)*(_a2_ + x1*(_a7_ + x1))/(_a2_*x1 + cosh(_a5_*x1)))/_a7_)**x1))
<lambdifygenerated-2783>:2: RuntimeWarning: overflow encountered in cosh
  return -x1*tanh(tanh(x1*(cosh(_a0_*_a1_ + (_a0_**sinh(x1) + _a4_)*(_a2_ + x1*(_a7_ + x1))/(_a2_*x1 + cosh(_a5_*x1)))/_a7_)**x1))
<lambdifygenerated-2783>:2: RuntimeWarning: overflow encountered in power
  return -x1*tanh(tanh(x1*(cosh(_a0_*_a1_ + (_a0_**sinh(x1) + _a4_)*(_a2_ + x1*(_a7_ + x1))/(_a2_*x1 + cosh(_a5_*x1)))/_a7_)**x1))
<lambdifygenerated-2783>:2: RuntimeWarning: overflow encountered in multiply
  return -x1*tanh(tanh(x1*(cosh(_a0_*_a1_ + (_a0_**sinh(x1) + _a4_)*(_a2_ + x1*(_a7_ + x1))/(_a2_*x1 + cosh(_a5_*x1)))/_a7_)**x1))
<lambdifygenerated-2783>:2: RuntimeWarning: overflow encountered in divide
  return -x1*tanh(tanh(x1*(cosh(_a0_*_a1_ + (_a0_**sinh(x1) + _a4_)*(_a2_ + x1*(_a7_ + x1))/(_a2_*x1 + cosh(_a5_*x1)))/_a7_)**x1))
<lambdifygenerated-2785>:2: RuntimeWarning: overflow encountered in cosh
  return -x1*tanh(tanh(x1*(cosh(_a0_*_a1_ + (_a0_**sinh(x1) + _a4_)*(_a2_ + x1*(_a7_ + x1))/(_a2_*x1 + cosh(_a5_*x1)))/_a7_)**_a1_))
<lambdifygenerated-2785>:2: RuntimeWarning: invalid value encountered in power
  return -x1*tanh(tanh(x1*(cosh(_a0_*_a1_ + (_a0_**sinh(x1) + _a4_)*(_a2_ + x1*(_a7_ + x1))/(_a2_*x1 + cosh(_a5_*x1)))/_a7_)**_a1_))
<lambdifygenerated-2785>:2: RuntimeWarning: overflow encountered in power
  return -x1*tanh(tanh(x1*(cosh(_a0_*_a1_ + (_a0_**sinh(x1) + _a4_)*(_a2_ + x1*(_a7_ + x1))/(_a2_*x1 + cosh(_a5_*x1)))/_a7_)**_a1_))
<lambdifygenerated-2787>:2: RuntimeWarning: invalid value encountered in power
  return -x1*tanh(tanh(_a6_*(cosh(_a0_*_a1_ + (_a0_**sinh(x1) + _a4_)*(_a2_ + x1*(_a7_ + x1))/(_a2_*x1 + cosh(_a5_*x1)))/_a7_)**_a1_))
<lambdifygenerated-2787>:2: RuntimeWarning: overflow encountered in cosh
  return -x1*tanh(tanh(_a6_*(cosh(_a0_*_a1_ + (_a0_**sinh(x1) + _a4_)*(_a2_ + x1*(_a7_ + x1))/(_a2_*x1 + cosh(_a5_*x1)))/_a7_)**_a1_))
<lambdifygenerated-2787>:2: RuntimeWarning: overflow encountered in power
  return -x1*tanh(tanh(_a6_*(cosh(_a0_*_a1_ + (_a0_**sinh(x1) + _a4_)*(_a2_ + x1*(_a7_ + x1))/(_a2_*x1 + cosh(_a5_*x1)))/_a7_)**_a1_))
<lambdifygenerated-2787>:2: RuntimeWarning: overflow encountered in multiply
  return -x1*tanh(tanh(_a6_*(cosh(_a0_*_a1_ + (_a0_**sinh(x1) + _a4_)*(_a2_ + x1*(_a7_ + x1))/(_a2_*x1 + cosh(_a5_*x1)))/_a7_)**_a1_))

interpolation

<lambdifygenerated-2789>:2: RuntimeWarning: overflow encountered in cosh
  return -_a3_*tanh(tanh(_a6_*(cosh(_a0_*_a1_ + (_a0_**sinh(x1) + _a4_)*(_a2_ + x1*(_a7_ + x1))/(_a2_*x1 + cosh(_a5_*x1)))/_a7_)**_a1_))
<lambdifygenerated-2789>:2: RuntimeWarning: overflow encountered in power
  return -_a3_*tanh(tanh(_a6_*(cosh(_a0_*_a1_ + (_a0_**sinh(x1) + _a4_)*(_a2_ + x1*(_a7_ + x1))/(_a2_*x1 + cosh(_a5_*x1)))/_a7_)**_a1_))
<lambdifygenerated-2789>:2: RuntimeWarning: invalid value encountered in power
  return -_a3_*tanh(tanh(_a6_*(cosh(_a0_*_a1_ + (_a0_**sinh(x1) + _a4_)*(_a2_ + x1*(_a7_ + x1))/(_a2_*x1 + cosh(_a5_*x1)))/_a7_)**_a1_))
<lambdifygenerated-2793>:2: RuntimeWarning: invalid value encountered in power
  return -_a3_*tanh(tanh(_a6_*(cosh(_a0_*_a1_ + (_a0_**sinh(x1) + _a4_)*(_a2_ + x1*(_a7_ + x1))/(_a2_*x1 + cosh(_a5_*x1)))/_a7_)**_a1_))

         x1         y  rep    ymodel      ybms
3745  0.997  0.100918  7.0  0.101084  0.101181
3746  0.998  0.100912  7.0  0.101083  0.101183
3747  0.998  0.100906  7.0  0.101081  0.101185
3748  0.999  0.100901  7.0  0.101080  0.101187

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.100890  7.0  0.101078  0.101191
3751  1.002  0.100885  7.0  0.101077  0.101194
3752  1.002  0.100880  7.0  0.101076  0.101197
3753  1.003  0.100874  7.0  0.101075  0.101200

3750

<lambdifygenerated-2807>:2: RuntimeWarning: invalid value encountered in power
  return -x1*(x1 + x1**x1) + x1
<lambdifygenerated-2808>:2: RuntimeWarning: invalid value encountered in power
  return -x1*(x1 + x1**x1) + x1
<lambdifygenerated-2809>:2: RuntimeWarning: invalid value encountered in power
  return -x1*(x1 + (2*x1)**x1) + x1
<lambdifygenerated-2810>:2: RuntimeWarning: invalid value encountered in power
  return -x1*(x1 + (2*x1)**x1) + x1
<lambdifygenerated-2811>:2: RuntimeWarning: divide by zero encountered in power
  return -x1*(0**x1 + x1) + x1
<lambdifygenerated-2812>:2: RuntimeWarning: divide by zero encountered in power
  return -x1*(0**x1 + x1) + x1
<lambdifygenerated-2813>:2: RuntimeWarning: invalid value encountered in power
  return -x1*(x1 + (-x1**2 + x1)**x1) + x1
<lambdifygenerated-2814>:2: RuntimeWarning: invalid value encountered in power
  return -x1*(x1 + (-x1**2 + x1)**x1) + x1
<lambdifygenerated-2815>:2: RuntimeWarning: invalid value encountered in power
  return -x1*(x1 + (-x1*exp(x1) + x1)**x1) + x1
<lambdifygenerated-2816>:2: RuntimeWarning: invalid value encountered in power
  return -x1*(x1 + (-x1*exp(x1) + x1)**x1) + x1
<lambdifygenerated-2817>:2: RuntimeWarning: divide by zero encountered in power
  return -x1*(x1 + (-x1*exp(x1**2) + x1)**x1) + x1
<lambdifygenerated-2817>:2: RuntimeWarning: invalid value encountered in power
  return -x1*(x1 + (-x1*exp(x1**2) + x1)**x1) + x1
<lambdifygenerated-2818>:2: RuntimeWarning: divide by zero encountered in power
  return -x1*(x1 + (-x1*exp(x1**2) + x1)**x1) + x1
<lambdifygenerated-2818>:2: RuntimeWarning: invalid value encountered in power
  return -x1*(x1 + (-x1*exp(x1**2) + x1)**x1) + x1
<lambdifygenerated-2819>:2: RuntimeWarning: invalid value encountered in power
  return -x1*(x1 + (-x1*exp(x1*x1**x1) + x1)**x1) + x1
<lambdifygenerated-2820>:2: RuntimeWarning: invalid value encountered in power
  return -x1*(x1 + (-x1*exp(x1*x1**x1) + x1)**x1) + x1
<lambdifygenerated-2821>:2: RuntimeWarning: invalid value encountered in power
  return -x1*(x1 + (-x1*exp(_a6_**x1*x1) + x1)**x1) + x1
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-2822>:2: RuntimeWarning: invalid value encountered in power
  return -x1*(x1 + (-x1*exp(_a6_**x1*x1) + x1)**x1) + x1
<lambdifygenerated-2823>:2: RuntimeWarning: invalid value encountered in power
  return -x1*(x1 + (-x1*exp(_a6_**tanh(x1)*x1) + x1)**x1) + x1
<lambdifygenerated-2824>:2: RuntimeWarning: invalid value encountered in power
  return -x1*(x1 + (-x1*exp(_a6_**tanh(x1)*x1) + x1)**x1) + x1
<lambdifygenerated-2825>:2: RuntimeWarning: invalid value encountered in power
  return -x1*(x1 + (-x1*exp(_a6_**tanh(x1**2)*x1) + x1)**x1) + x1
<lambdifygenerated-2826>:2: RuntimeWarning: invalid value encountered in power
  return -x1*(x1 + (-x1*exp(_a6_**tanh(x1**2)*x1) + x1)**x1) + x1
<lambdifygenerated-2827>:2: RuntimeWarning: invalid value encountered in power
  return -x1*(x1 + (-x1*exp(_a6_**tanh(2*x1**2)*x1) + x1)**x1) + x1
<lambdifygenerated-2828>:2: RuntimeWarning: invalid value encountered in power
  return -x1*(x1 + (-x1*exp(_a6_**tanh(2*x1**2)*x1) + x1)**x1) + x1
<lambdifygenerated-2829>:2: RuntimeWarning: invalid value encountered in power
  return -x1*(x1 + (-x1*exp(_a6_**tanh(2*x1**2)*x1) + x1)**x1) + x1
<lambdifygenerated-2830>:2: RuntimeWarning: invalid value encountered in power
  return -x1*(x1 + (-x1*exp(_a6_**tanh(2*x1**2)*x1) + x1)**x1) + x1
<lambdifygenerated-2831>:2: RuntimeWarning: invalid value encountered in power
  return -x1*(x1 + (-x1*exp(_a6_**tanh(x1*(_a4_ + x1))*x1) + x1)**x1) + x1
<lambdifygenerated-2832>:2: RuntimeWarning: invalid value encountered in power
  return -x1*(x1 + (-x1*exp(_a6_**tanh(x1*(_a4_ + x1))*x1) + x1)**x1) + x1
<lambdifygenerated-2833>:2: RuntimeWarning: invalid value encountered in power
  return -x1*(x1 + (-x1*exp(_a6_**tanh(_a2_*(_a4_ + x1))*x1) + x1)**x1) + x1
<lambdifygenerated-2834>:2: RuntimeWarning: invalid value encountered in power
  return -x1*(x1 + (-x1*exp(_a6_**tanh(_a2_*(_a4_ + x1))*x1) + x1)**x1) + x1
<lambdifygenerated-2835>:2: RuntimeWarning: invalid value encountered in power
  return -x1*(x1 + (-x1*exp(2*_a6_**tanh(_a2_*(_a4_ + x1))*x1) + x1)**x1) + x1
<lambdifygenerated-2836>:2: RuntimeWarning: invalid value encountered in power
  return -x1*(x1 + (-x1*exp(2*_a6_**tanh(_a2_*(_a4_ + x1))*x1) + x1)**x1) + x1
<lambdifygenerated-2837>:2: RuntimeWarning: invalid value encountered in power
  return -x1*(x1 + (-x1*exp(_a6_**tanh(_a2_*(_a4_ + x1))*(x1**2 + x1)) + x1)**x1) + x1
<lambdifygenerated-2838>:2: RuntimeWarning: invalid value encountered in power
  return -x1*(x1 + (-x1*exp(_a6_**tanh(_a2_*(_a4_ + x1))*(x1**2 + x1)) + x1)**x1) + x1
<lambdifygenerated-2839>:2: RuntimeWarning: invalid value encountered in power
  return -x1*(x1 + (-x1*exp(_a6_**tanh(_a2_*(_a4_ + x1))*(_a0_*x1 + x1)) + x1)**x1) + x1
<lambdifygenerated-2840>:2: RuntimeWarning: invalid value encountered in power
  return -x1*(x1 + (-x1*exp(_a6_**tanh(_a2_*(_a4_ + x1))*(_a0_*x1 + x1)) + x1)**x1) + x1
<lambdifygenerated-2841>:2: RuntimeWarning: invalid value encountered in power
  return -x1*(x1 + (-x1*exp(_a6_**tanh(_a2_*(_a4_ + x1))*(_a0_*x1 + x1)) + x1)**x1) + x1
<lambdifygenerated-2842>:2: RuntimeWarning: invalid value encountered in power
  return -x1*(x1 + (-x1*exp(_a6_**tanh(_a2_*(_a4_ + x1))*(_a0_*x1 + x1)) + x1)**x1) + x1
<lambdifygenerated-2843>:2: RuntimeWarning: invalid value encountered in power
  return -x1*(x1 + (-x1*exp(_a6_**tanh(_a2_*(_a4_ + x1))*(_a0_*x1 + cos(x1))) + x1)**x1) + x1
<lambdifygenerated-2844>:2: RuntimeWarning: invalid value encountered in power
  return -x1*(x1 + (-x1*exp(_a6_**tanh(_a2_*(_a4_ + x1))*(_a0_*x1 + cos(x1))) + x1)**x1) + x1
<lambdifygenerated-2845>:2: RuntimeWarning: invalid value encountered in power
  return -x1*(x1 + (-x1*exp(_a6_**tanh(_a2_*(_a4_ + x1))*(_a0_*x1 + cos(2*x1))) + x1)**x1) + x1
<lambdifygenerated-2846>:2: RuntimeWarning: invalid value encountered in power
  return -x1*(x1 + (-x1*exp(_a6_**tanh(_a2_*(_a4_ + x1))*(_a0_*x1 + cos(2*x1))) + x1)**x1) + x1
<lambdifygenerated-2847>:2: RuntimeWarning: invalid value encountered in power
  return -x1*(x1 + (-x1*exp(_a6_**tanh(_a2_*(_a4_ + x1))*(_a0_*x1 + cos(_a3_ + x1))) + x1)**x1) + x1
<lambdifygenerated-2848>:2: RuntimeWarning: invalid value encountered in power
  return -x1*(x1 + (-x1*exp(_a6_**tanh(_a2_*(_a4_ + x1))*(_a0_*x1 + cos(_a3_ + x1))) + x1)**x1) + x1
<lambdifygenerated-2849>:2: RuntimeWarning: invalid value encountered in power
  return -x1*(x1 + (-x1*exp(_a6_**tanh(_a2_*(_a4_ + x1))*(_a0_*x1 + cos(_a3_ + x1**2))) + x1)**x1) + x1
<lambdifygenerated-2850>:2: RuntimeWarning: invalid value encountered in power
  return -x1*(x1 + (-x1*exp(_a6_**tanh(_a2_*(_a4_ + x1))*(_a0_*x1 + cos(_a3_ + x1**2))) + x1)**x1) + x1
<lambdifygenerated-2851>:2: RuntimeWarning: invalid value encountered in power
  return -x1*(x1 + (-x1*exp(_a6_**tanh(_a2_*(_a4_ + x1))*(_a0_*x1 + cos(_a3_ + x1*tanh(x1)))) + x1)**x1) + x1
<lambdifygenerated-2852>:2: RuntimeWarning: invalid value encountered in power
  return -x1*(x1 + (-x1*exp(_a6_**tanh(_a2_*(_a4_ + x1))*(_a0_*x1 + cos(_a3_ + x1*tanh(x1)))) + x1)**x1) + x1
<lambdifygenerated-2853>:2: RuntimeWarning: invalid value encountered in power
  return -x1*(x1 + (-x1*exp(_a6_**tanh(_a2_*(_a4_ + x1))*(_a0_*x1 + cos(_a3_ + x1*tanh(x1)))) + x1)**x1) + x1
<lambdifygenerated-2854>:2: RuntimeWarning: invalid value encountered in power
  return -x1*(x1 + (-x1*exp(_a6_**tanh(_a2_*(_a4_ + x1))*(_a0_*x1 + cos(_a3_ + x1*tanh(x1)))) + x1)**x1) + x1
<lambdifygenerated-2855>:2: RuntimeWarning: invalid value encountered in power
  return -x1*(x1 + (-x1*exp(_a6_**tanh(_a2_*(_a4_ + x1))*(_a0_*x1 + cos(_a3_ + _a5_*tanh(x1)))) + x1)**x1) + x1
<lambdifygenerated-2856>:2: RuntimeWarning: invalid value encountered in power
  return -x1*(x1 + (-x1*exp(_a6_**tanh(_a2_*(_a4_ + x1))*(_a0_*x1 + cos(_a3_ + _a5_*tanh(x1)))) + x1)**x1) + x1
<lambdifygenerated-2857>:2: RuntimeWarning: invalid value encountered in power
  return -x1*(x1 + (-_a4_*exp(_a6_**tanh(_a2_*(_a4_ + x1))*(_a0_*x1 + cos(_a3_ + _a5_*tanh(x1)))) + x1)**x1) + x1
<lambdifygenerated-2858>:2: RuntimeWarning: invalid value encountered in power
  return -x1*(x1 + (-_a4_*exp(_a6_**tanh(_a2_*(_a4_ + x1))*(_a0_*x1 + cos(_a3_ + _a5_*tanh(x1)))) + x1)**x1) + x1
<lambdifygenerated-2859>:2: RuntimeWarning: invalid value encountered in power
  return -x1*(x1 + (-_a4_*exp(_a6_**tanh(_a2_*(_a4_ + x1))*(_a0_*x1 + cos(_a3_ + _a5_*tanh(x1)))) + 2*x1)**x1) + x1
<lambdifygenerated-2860>:2: RuntimeWarning: invalid value encountered in power
  return -x1*(x1 + (-_a4_*exp(_a6_**tanh(_a2_*(_a4_ + x1))*(_a0_*x1 + cos(_a3_ + _a5_*tanh(x1)))) + 2*x1)**x1) + x1
<lambdifygenerated-2861>:2: RuntimeWarning: invalid value encountered in power
  return -x1*(x1 + (-_a4_*exp(_a6_**tanh(_a2_*(_a4_ + x1))*(_a0_*x1 + cos(_a3_ + _a5_*tanh(x1)))) + x1 + 1)**x1) + x1
<lambdifygenerated-2862>:2: RuntimeWarning: invalid value encountered in power
  return -x1*(x1 + (-_a4_*exp(_a6_**tanh(_a2_*(_a4_ + x1))*(_a0_*x1 + cos(_a3_ + _a5_*tanh(x1)))) + x1 + 1)**x1) + x1
<lambdifygenerated-2863>:2: RuntimeWarning: invalid value encountered in power
  return -x1*(x1 + (_a1_/x1 - _a4_*exp(_a6_**tanh(_a2_*(_a4_ + x1))*(_a0_*x1 + cos(_a3_ + _a5_*tanh(x1)))) + x1)**x1) + x1
<lambdifygenerated-2864>:2: RuntimeWarning: invalid value encountered in power
  return -x1*(x1 + (_a1_/x1 - _a4_*exp(_a6_**tanh(_a2_*(_a4_ + x1))*(_a0_*x1 + cos(_a3_ + _a5_*tanh(x1)))) + x1)**x1) + x1
<lambdifygenerated-2865>:2: RuntimeWarning: invalid value encountered in power
  return -x1*(x1 + (_a1_/tanh(x1) - _a4_*exp(_a6_**tanh(_a2_*(_a4_ + x1))*(_a0_*x1 + cos(_a3_ + _a5_*tanh(x1)))) + x1)**x1) + x1
<lambdifygenerated-2866>:2: RuntimeWarning: invalid value encountered in power
  return -x1*(x1 + (_a1_/tanh(x1) - _a4_*exp(_a6_**tanh(_a2_*(_a4_ + x1))*(_a0_*x1 + cos(_a3_ + _a5_*tanh(x1)))) + x1)**x1) + x1
<lambdifygenerated-2867>:2: RuntimeWarning: invalid value encountered in power
  return -x1*(x1 + (_a1_/tanh(_a0_) - _a4_*exp(_a6_**tanh(_a2_*(_a4_ + x1))*(_a0_*x1 + cos(_a3_ + _a5_*tanh(x1)))) + x1)**x1) + x1
<lambdifygenerated-2868>:2: RuntimeWarning: invalid value encountered in power
  return -x1*(x1 + (_a1_/tanh(_a0_) - _a4_*exp(_a6_**tanh(_a2_*(_a4_ + x1))*(_a0_*x1 + cos(_a3_ + _a5_*tanh(x1)))) + x1)**x1) + x1
<lambdifygenerated-2869>:2: RuntimeWarning: invalid value encountered in power
  return -x1*(x1 + (_a1_/tanh(_a0_) - _a4_*exp(_a6_**tanh(_a2_*(_a4_ + x1))*(_a0_*x1 + cos(_a3_ + _a5_*tanh(x1)))) + x1**2)**x1) + x1
<lambdifygenerated-2870>:2: RuntimeWarning: invalid value encountered in power
  return -x1*(x1 + (_a1_/tanh(_a0_) - _a4_*exp(_a6_**tanh(_a2_*(_a4_ + x1))*(_a0_*x1 + cos(_a3_ + _a5_*tanh(x1)))) + x1**2)**x1) + x1
<lambdifygenerated-2871>:2: RuntimeWarning: invalid value encountered in power
  return -x1*(x1 + (_a1_/tanh(_a0_) - _a4_*exp(_a6_**tanh(_a2_*(_a4_ + x1))*(_a0_*x1 + cos(_a3_ + _a5_*tanh(x1)))) + _a7_*x1)**x1) + x1
<lambdifygenerated-2872>:2: RuntimeWarning: invalid value encountered in power
  return -x1*(x1 + (_a1_/tanh(_a0_) - _a4_*exp(_a6_**tanh(_a2_*(_a4_ + x1))*(_a0_*x1 + cos(_a3_ + _a5_*tanh(x1)))) + _a7_*x1)**x1) + x1
<lambdifygenerated-2873>:2: RuntimeWarning: invalid value encountered in power
  return -x1*(x1 + (_a1_/tanh(_a0_) - _a4_*exp(_a6_**tanh(_a2_*(_a4_ + x1))*(_a0_*x1 + cos(_a3_ + _a5_*tanh(x1)))) + _a7_*x1)**x1) + x1
<lambdifygenerated-2874>:2: RuntimeWarning: invalid value encountered in power
  return -x1*(x1 + (_a1_/tanh(_a0_) - _a4_*exp(_a6_**tanh(_a2_*(_a4_ + x1))*(_a0_*x1 + cos(_a3_ + _a5_*tanh(x1)))) + _a7_*x1)**x1) + x1

interpolation

<lambdifygenerated-2879>:2: RuntimeWarning: invalid value encountered in power
  return -x1*(x1 + (_a1_/tanh(_a0_) - _a4_*exp(_a6_**tanh(_a2_*(_a4_ + x1))*(_a0_*x1 + cos(_a3_ + _a5_*tanh(x1)))) + _a7_*x1)**((_a1_ + x1)/x1)) + x1
<lambdifygenerated-2880>:2: RuntimeWarning: invalid value encountered in power
  return -x1*(x1 + (_a1_/tanh(_a0_) - _a4_*exp(_a6_**tanh(_a2_*(_a4_ + x1))*(_a0_*x1 + cos(_a3_ + _a5_*tanh(x1)))) + _a7_*x1)**((_a1_ + x1)/x1)) + x1
<lambdifygenerated-2881>:2: RuntimeWarning: overflow encountered in power
  return -x1*(x1 + (_a1_/tanh(_a0_) - _a4_*exp(_a6_**tanh(_a2_*(_a4_ + x1))*(_a0_*x1 + cos(_a3_ + _a5_*tanh(x1)))) + _a7_*x1)**((_a1_ + _a2_)/x1)) + x1
<lambdifygenerated-2881>:2: RuntimeWarning: invalid value encountered in power
  return -x1*(x1 + (_a1_/tanh(_a0_) - _a4_*exp(_a6_**tanh(_a2_*(_a4_ + x1))*(_a0_*x1 + cos(_a3_ + _a5_*tanh(x1)))) + _a7_*x1)**((_a1_ + _a2_)/x1)) + x1
/usr/local/lib/python3.10/dist-packages/scipy/optimize/_minpack_py.py:1017: RuntimeWarning: overflow encountered in square
  cost = np.sum(infodict['fvec'] ** 2)
/usr/local/lib/python3.10/dist-packages/pandas/core/arraylike.py:399: RuntimeWarning: overflow encountered in square
  result = getattr(ufunc, method)(*inputs, **kwargs)
<lambdifygenerated-2882>:2: RuntimeWarning: overflow encountered in power
  return -x1*(x1 + (_a1_/tanh(_a0_) - _a4_*exp(_a6_**tanh(_a2_*(_a4_ + x1))*(_a0_*x1 + cos(_a3_ + _a5_*tanh(x1)))) + _a7_*x1)**((_a1_ + _a2_)/x1)) + x1
<lambdifygenerated-2882>:2: RuntimeWarning: invalid value encountered in power
  return -x1*(x1 + (_a1_/tanh(_a0_) - _a4_*exp(_a6_**tanh(_a2_*(_a4_ + x1))*(_a0_*x1 + cos(_a3_ + _a5_*tanh(x1)))) + _a7_*x1)**((_a1_ + _a2_)/x1)) + x1
<lambdifygenerated-2883>:2: RuntimeWarning: invalid value encountered in power
  return -x1*(x1 + (_a1_/tanh(_a0_) - _a4_*exp(_a6_**tanh(_a2_*(_a4_ + x1))*(_a0_*x1 + cos(_a3_ + _a5_*tanh(x1)))) + _a7_*x1)**((_a1_ + _a2_)/_a0_)) + x1
<lambdifygenerated-2884>:2: RuntimeWarning: invalid value encountered in power
  return -x1*(x1 + (_a1_/tanh(_a0_) - _a4_*exp(_a6_**tanh(_a2_*(_a4_ + x1))*(_a0_*x1 + cos(_a3_ + _a5_*tanh(x1)))) + _a7_*x1)**((_a1_ + _a2_)/_a0_)) + x1
<lambdifygenerated-2885>:2: RuntimeWarning: invalid value encountered in power
  return -x1*(x1**2 + (_a1_/tanh(_a0_) - _a4_*exp(_a6_**tanh(_a2_*(_a4_ + x1))*(_a0_*x1 + cos(_a3_ + _a5_*tanh(x1)))) + _a7_*x1)**((_a1_ + _a2_)/_a0_)) + x1
<lambdifygenerated-2886>:2: RuntimeWarning: invalid value encountered in power
  return -x1*(x1**2 + (_a1_/tanh(_a0_) - _a4_*exp(_a6_**tanh(_a2_*(_a4_ + x1))*(_a0_*x1 + cos(_a3_ + _a5_*tanh(x1)))) + _a7_*x1)**((_a1_ + _a2_)/_a0_)) + x1
<lambdifygenerated-2887>:2: RuntimeWarning: invalid value encountered in power
  return -x1*(x1**3 + (_a1_/tanh(_a0_) - _a4_*exp(_a6_**tanh(_a2_*(_a4_ + x1))*(_a0_*x1 + cos(_a3_ + _a5_*tanh(x1)))) + _a7_*x1)**((_a1_ + _a2_)/_a0_)) + x1
<lambdifygenerated-2888>:2: RuntimeWarning: invalid value encountered in power
  return -x1*(x1**3 + (_a1_/tanh(_a0_) - _a4_*exp(_a6_**tanh(_a2_*(_a4_ + x1))*(_a0_*x1 + cos(_a3_ + _a5_*tanh(x1)))) + _a7_*x1)**((_a1_ + _a2_)/_a0_)) + x1
<lambdifygenerated-2889>:2: RuntimeWarning: invalid value encountered in power
  return -x1*(x1**3 + (_a1_/tanh(_a0_) - _a4_*exp(_a6_**tanh(_a2_*(_a4_ + x1))*(_a0_*x1 + cos(_a3_ + _a5_*tanh(x1)))) + _a7_*x1)**((_a1_ + _a2_)/_a0_)) + x1
<lambdifygenerated-2890>:2: RuntimeWarning: invalid value encountered in power
  return -x1*(x1**3 + (_a1_/tanh(_a0_) - _a4_*exp(_a6_**tanh(_a2_*(_a4_ + x1))*(_a0_*x1 + cos(_a3_ + _a5_*tanh(x1)))) + _a7_*x1)**((_a1_ + _a2_)/_a0_)) + x1
<lambdifygenerated-2891>:2: RuntimeWarning: invalid value encountered in power
  return -x1*(_a1_*x1**2 + (_a1_/tanh(_a0_) - _a4_*exp(_a6_**tanh(_a2_*(_a4_ + x1))*(_a0_*x1 + cos(_a3_ + _a5_*tanh(x1)))) + _a7_*x1)**((_a1_ + _a2_)/_a0_)) + x1
<lambdifygenerated-2892>:2: RuntimeWarning: invalid value encountered in power
  return -x1*(_a1_*x1**2 + (_a1_/tanh(_a0_) - _a4_*exp(_a6_**tanh(_a2_*(_a4_ + x1))*(_a0_*x1 + cos(_a3_ + _a5_*tanh(x1)))) + _a7_*x1)**((_a1_ + _a2_)/_a0_)) + x1
<lambdifygenerated-2893>:2: RuntimeWarning: invalid value encountered in power
  return -x1*(_a1_**2*x1 + (_a1_/tanh(_a0_) - _a4_*exp(_a6_**tanh(_a2_*(_a4_ + x1))*(_a0_*x1 + cos(_a3_ + _a5_*tanh(x1)))) + _a7_*x1)**((_a1_ + _a2_)/_a0_)) + x1
<lambdifygenerated-2894>:2: RuntimeWarning: invalid value encountered in power
  return -x1*(_a1_**2*x1 + (_a1_/tanh(_a0_) - _a4_*exp(_a6_**tanh(_a2_*(_a4_ + x1))*(_a0_*x1 + cos(_a3_ + _a5_*tanh(x1)))) + _a7_*x1)**((_a1_ + _a2_)/_a0_)) + x1
<lambdifygenerated-2895>:2: RuntimeWarning: invalid value encountered in power
  return -_a7_*(_a1_**2*x1 + (_a1_/tanh(_a0_) - _a4_*exp(_a6_**tanh(_a2_*(_a4_ + x1))*(_a0_*x1 + cos(_a3_ + _a5_*tanh(x1)))) + _a7_*x1)**((_a1_ + _a2_)/_a0_)) + x1
<lambdifygenerated-2896>:2: RuntimeWarning: invalid value encountered in power
  return -_a7_*(_a1_**2*x1 + (_a1_/tanh(_a0_) - _a4_*exp(_a6_**tanh(_a2_*(_a4_ + x1))*(_a0_*x1 + cos(_a3_ + _a5_*tanh(x1)))) + _a7_*x1)**((_a1_ + _a2_)/_a0_)) + x1
<lambdifygenerated-2897>:2: RuntimeWarning: invalid value encountered in power
  return -_a7_*(_a1_**2*x1 + (_a1_/tanh(_a0_) - _a4_*exp(_a6_**tanh(_a2_*(_a4_ + x1))*(_a0_*x1 + cos(_a3_ + _a5_*tanh(x1)))) + _a7_*x1)**((_a1_ + _a2_)/_a0_)) + _a7_
<lambdifygenerated-2898>:2: RuntimeWarning: invalid value encountered in power
  return -_a7_*(_a1_**2*x1 + (_a1_/tanh(_a0_) - _a4_*exp(_a6_**tanh(_a2_*(_a4_ + x1))*(_a0_*x1 + cos(_a3_ + _a5_*tanh(x1)))) + _a7_*x1)**((_a1_ + _a2_)/_a0_)) + _a7_
<lambdifygenerated-2899>:2: RuntimeWarning: invalid value encountered in power
  return -_a7_*(_a1_**2*x1 + (_a1_/tanh(_a0_) - _a4_*exp(_a6_**tanh(_a2_*(_a4_ + x1))*(_a0_*x1 + cos(_a3_ + _a5_*tanh(x1)))) + _a7_*x1)**((_a1_ + _a2_)/_a0_)) + _a7_
<lambdifygenerated-2900>:2: RuntimeWarning: invalid value encountered in power
  return -_a7_*(_a1_**2*x1 + (_a1_/tanh(_a0_) - _a4_*exp(_a6_**tanh(_a2_*(_a4_ + x1))*(_a0_*x1 + cos(_a3_ + _a5_*tanh(x1)))) + _a7_*x1)**((_a1_ + _a2_)/_a0_)) + _a7_
<lambdifygenerated-2901>:2: RuntimeWarning: invalid value encountered in power
  return -_a7_*(_a1_**2*x1 + (_a1_/tanh(_a0_) - _a4_*exp(_a6_**tanh(_a2_*(_a4_ + x1))*(_a0_*x1 + cos(_a3_ + _a5_*tanh(x1)))) + _a7_*x1)**((_a1_ + _a2_)/_a0_)) + _a7_
<lambdifygenerated-2902>:2: RuntimeWarning: invalid value encountered in power
  return -_a7_*(_a1_**2*x1 + (_a1_/tanh(_a0_) - _a4_*exp(_a6_**tanh(_a2_*(_a4_ + x1))*(_a0_*x1 + cos(_a3_ + _a5_*tanh(x1)))) + _a7_*x1)**((_a1_ + _a2_)/_a0_)) + _a7_

         x1         y  rep    ymodel      ybms
3745  0.997  0.825595  8.0  0.823169  0.825741
3746  0.998  0.825925  8.0  0.823472  0.826073
3747  0.998  0.826254  8.0  0.823774  0.826405
3748  0.999  0.826582  8.0  0.824076  0.826737

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.827238  8.0  0.824677  0.827398
3751  1.002  0.827565  8.0  0.824977  0.827728
3752  1.002  0.827892  8.0  0.825276  0.828058
3753  1.003  0.828218  8.0  0.825575  0.828387

3750

<lambdifygenerated-2915>:2: RuntimeWarning: invalid value encountered in log
  return tan(tan(x1*(x1 + log(x1))))
<lambdifygenerated-2916>:2: RuntimeWarning: invalid value encountered in log
  return tan(tan(x1*(x1 + log(x1))))
<lambdifygenerated-2917>:2: RuntimeWarning: invalid value encountered in log
  return tan(tan(x1*(x1 + log(2*x1))))
<lambdifygenerated-2918>:2: RuntimeWarning: invalid value encountered in log
  return tan(tan(x1*(x1 + log(2*x1))))
<lambdifygenerated-2919>:2: RuntimeWarning: invalid value encountered in log
  return tan(tan(x1*(x1 + log(x1 + sin(x1)))))
<lambdifygenerated-2920>:2: RuntimeWarning: invalid value encountered in log
  return tan(tan(x1*(x1 + log(x1 + sin(x1)))))
<lambdifygenerated-2921>:2: RuntimeWarning: invalid value encountered in log
  return tan(tan(x1*(x1 + log(x1 + sin(2*x1)))))
<lambdifygenerated-2922>:2: RuntimeWarning: invalid value encountered in log
  return tan(tan(x1*(x1 + log(x1 + sin(2*x1)))))
<lambdifygenerated-2923>:2: RuntimeWarning: invalid value encountered in log
  return tan(tan(x1*(x1 + log(x1 + sin(x1 + tanh(x1))))))
<lambdifygenerated-2924>:2: RuntimeWarning: invalid value encountered in log
  return tan(tan(x1*(x1 + log(x1 + sin(x1 + tanh(x1))))))
<lambdifygenerated-2925>:2: RuntimeWarning: invalid value encountered in log
  return tan(tan(x1*(x1 + log(x1 + sin(x1 + tanh(2*x1))))))
<lambdifygenerated-2926>:2: RuntimeWarning: invalid value encountered in log
  return tan(tan(x1*(x1 + log(x1 + sin(x1 + tanh(2*x1))))))
<lambdifygenerated-2927>:2: RuntimeWarning: invalid value encountered in log
  return tan(tan(x1*(x1 + log(x1 + sin(x1 + tanh(x1**2 + x1))))))
<lambdifygenerated-2928>:2: RuntimeWarning: invalid value encountered in log
  return tan(tan(x1*(x1 + log(x1 + sin(x1 + tanh(x1**2 + x1))))))
<lambdifygenerated-2929>:2: RuntimeWarning: invalid value encountered in log
  return tan(tan(x1*(x1 + log(x1 + sin(x1 + tanh(2*x1**2 + x1))))))
<lambdifygenerated-2930>:2: RuntimeWarning: invalid value encountered in log
  return tan(tan(x1*(x1 + log(x1 + sin(x1 + tanh(2*x1**2 + x1))))))
<lambdifygenerated-2931>:2: RuntimeWarning: invalid value encountered in power
  return tan(tan(x1*(x1 + log(x1 + sin(x1 + tanh(x1*(x1 + x1**x1) + x1))))))
<lambdifygenerated-2932>:2: RuntimeWarning: invalid value encountered in power
  return tan(tan(x1*(x1 + log(x1 + sin(x1 + tanh(x1*(x1 + x1**x1) + x1))))))
<lambdifygenerated-2933>:2: RuntimeWarning: invalid value encountered in log
  return tan(tan(x1*(x1 + log(x1 + sin(x1 + tanh(x1*(x1 + (x1**2)**x1) + x1))))))
<lambdifygenerated-2934>:2: RuntimeWarning: invalid value encountered in log
  return tan(tan(x1*(x1 + log(x1 + sin(x1 + tanh(x1*(x1 + (x1**2)**x1) + x1))))))
<lambdifygenerated-2935>:2: RuntimeWarning: invalid value encountered in log
  return tan(tan(x1*(x1 + log(x1 + sin(x1 + tanh(x1*(x1 + (tanh(x1)**2)**x1) + x1))))))
<lambdifygenerated-2936>:2: RuntimeWarning: invalid value encountered in log
  return tan(tan(x1*(x1 + log(x1 + sin(x1 + tanh(x1*(x1 + (tanh(x1)**2)**x1) + x1))))))
<lambdifygenerated-2937>:2: RuntimeWarning: invalid value encountered in log
  return tan(tan(x1*(x1 + log(x1 + sin(x1 + tanh(x1*(x1 + (tanh(sinh(x1))**2)**x1) + x1))))))
<lambdifygenerated-2938>:2: RuntimeWarning: invalid value encountered in log
  return tan(tan(x1*(x1 + log(x1 + sin(x1 + tanh(x1*(x1 + (tanh(sinh(x1))**2)**x1) + x1))))))
<lambdifygenerated-2939>:2: RuntimeWarning: invalid value encountered in log
  return tan(tan(x1*(x1 + log(x1 + sin(x1 + tanh(x1*(x1 + (tanh(sinh(x1**3))**2)**x1) + x1))))))
<lambdifygenerated-2940>:2: RuntimeWarning: invalid value encountered in log
  return tan(tan(x1*(x1 + log(x1 + sin(x1 + tanh(x1*(x1 + (tanh(sinh(x1**3))**2)**x1) + x1))))))
<lambdifygenerated-2941>:2: RuntimeWarning: invalid value encountered in power
  return tan(tan(x1*(x1 + log(x1 + sin(x1 + tanh(x1*(x1 + (tanh(sinh(x1**(3*x1)))**2)**x1) + x1))))))
<lambdifygenerated-2942>:2: RuntimeWarning: invalid value encountered in power
  return tan(tan(x1*(x1 + log(x1 + sin(x1 + tanh(x1*(x1 + (tanh(sinh(x1**(3*x1)))**2)**x1) + x1))))))
<lambdifygenerated-2943>:2: RuntimeWarning: overflow encountered in sinh
  return tan(tan(x1*(x1 + log(x1 + sin(x1 + tanh(x1*(x1 + (tanh(sinh(exp(x1)**(3*x1)))**2)**x1) + x1))))))
<lambdifygenerated-2943>:2: RuntimeWarning: invalid value encountered in log
  return tan(tan(x1*(x1 + log(x1 + sin(x1 + tanh(x1*(x1 + (tanh(sinh(exp(x1)**(3*x1)))**2)**x1) + x1))))))
<lambdifygenerated-2944>:2: RuntimeWarning: overflow encountered in sinh
  return tan(tan(x1*(x1 + log(x1 + sin(x1 + tanh(x1*(x1 + (tanh(sinh(exp(x1)**(3*x1)))**2)**x1) + x1))))))
<lambdifygenerated-2944>:2: RuntimeWarning: invalid value encountered in log
  return tan(tan(x1*(x1 + log(x1 + sin(x1 + tanh(x1*(x1 + (tanh(sinh(exp(x1)**(3*x1)))**2)**x1) + x1))))))
<lambdifygenerated-2945>:2: RuntimeWarning: overflow encountered in sinh
  return tan(tan(x1*(x1 + log(x1 + sin(x1 + tanh(x1*(x1 + (tanh(sinh(exp(x1)**(3*x1)))**2)**x1) + x1))))))
<lambdifygenerated-2945>:2: RuntimeWarning: invalid value encountered in log
  return tan(tan(x1*(x1 + log(x1 + sin(x1 + tanh(x1*(x1 + (tanh(sinh(exp(x1)**(3*x1)))**2)**x1) + x1))))))
<lambdifygenerated-2946>:2: RuntimeWarning: overflow encountered in sinh
  return tan(tan(x1*(x1 + log(x1 + sin(x1 + tanh(x1*(x1 + (tanh(sinh(exp(x1)**(3*x1)))**2)**x1) + x1))))))
<lambdifygenerated-2946>:2: RuntimeWarning: invalid value encountered in log
  return tan(tan(x1*(x1 + log(x1 + sin(x1 + tanh(x1*(x1 + (tanh(sinh(exp(x1)**(3*x1)))**2)**x1) + x1))))))
<lambdifygenerated-2947>:2: RuntimeWarning: invalid value encountered in log
  return tan(tan(x1*(x1 + log(x1 + sin(x1 + tanh(x1*(x1 + (tanh(sinh(exp(x1)**(3*_a0_)))**2)**x1) + x1))))))
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-2948>:2: RuntimeWarning: invalid value encountered in log
  return tan(tan(x1*(x1 + log(x1 + sin(x1 + tanh(x1*(x1 + (tanh(sinh(exp(x1)**(3*_a0_)))**2)**x1) + x1))))))
<lambdifygenerated-2949>:2: RuntimeWarning: invalid value encountered in log
  return tan(tan(x1*(x1 + log(x1 + sin(x1 + tanh(x1*(x1 + (tanh(sinh(exp(x1)**(3*_a0_)))**2)**(2*x1)) + x1))))))
<lambdifygenerated-2950>:2: RuntimeWarning: invalid value encountered in log
  return tan(tan(x1*(x1 + log(x1 + sin(x1 + tanh(x1*(x1 + (tanh(sinh(exp(x1)**(3*_a0_)))**2)**(2*x1)) + x1))))))
<lambdifygenerated-2951>:2: RuntimeWarning: invalid value encountered in log
  return tan(tan(x1*(x1 + log(x1 + sin(x1 + tanh(x1*(x1 + (tanh(sinh(exp(x1)**(3*_a0_)))**2)**(_a0_ + x1)) + x1))))))
<lambdifygenerated-2952>:2: RuntimeWarning: invalid value encountered in log
  return tan(tan(x1*(x1 + log(x1 + sin(x1 + tanh(x1*(x1 + (tanh(sinh(exp(x1)**(3*_a0_)))**2)**(_a0_ + x1)) + x1))))))
<lambdifygenerated-2953>:2: RuntimeWarning: invalid value encountered in power
  return tan(tan(x1*(x1 + log(x1 + sin(x1 + tanh(x1*(x1 + (tanh(sinh(exp(x1)**(3*_a0_)))**2)**(_a0_ + x1**x1)) + x1))))))
<lambdifygenerated-2954>:2: RuntimeWarning: invalid value encountered in power
  return tan(tan(x1*(x1 + log(x1 + sin(x1 + tanh(x1*(x1 + (tanh(sinh(exp(x1)**(3*_a0_)))**2)**(_a0_ + x1**x1)) + x1))))))
<lambdifygenerated-2955>:2: RuntimeWarning: invalid value encountered in log
  return tan(tan(x1*(x1 + log(x1 + sin(x1 + tanh(x1*(x1 + (tanh(sinh(exp(x1)**(3*_a0_)))**2)**(_a0_ + _a1_**x1)) + x1))))))
<lambdifygenerated-2956>:2: RuntimeWarning: invalid value encountered in log
  return tan(tan(x1*(x1 + log(x1 + sin(x1 + tanh(x1*(x1 + (tanh(sinh(exp(x1)**(3*_a0_)))**2)**(_a0_ + _a1_**x1)) + x1))))))
<lambdifygenerated-2957>:2: RuntimeWarning: invalid value encountered in log
  return tan(tan(x1*(x1 + log(x1 + sin(x1 + tanh(x1*(x1 + (tanh(sinh(exp(x1)**(3*_a0_)))**2)**(_a0_ + _a1_**x1)) + x1))))))
<lambdifygenerated-2958>:2: RuntimeWarning: invalid value encountered in log
  return tan(tan(x1*(x1 + log(x1 + sin(x1 + tanh(x1*(x1 + (tanh(sinh(exp(x1)**(3*_a0_)))**2)**(_a0_ + _a1_**x1)) + x1))))))
<lambdifygenerated-2959>:2: RuntimeWarning: invalid value encountered in power
  return tan(tan(x1*(x1 + log(x1 + sin(x1 + tanh(x1*(x1**x1 + (tanh(sinh(exp(x1)**(3*_a0_)))**2)**(_a0_ + _a1_**x1)) + x1))))))
<lambdifygenerated-2960>:2: RuntimeWarning: invalid value encountered in power
  return tan(tan(x1*(x1 + log(x1 + sin(x1 + tanh(x1*(x1**x1 + (tanh(sinh(exp(x1)**(3*_a0_)))**2)**(_a0_ + _a1_**x1)) + x1))))))
<lambdifygenerated-2961>:2: RuntimeWarning: invalid value encountered in log
  return tan(tan(x1*(x1 + log(x1 + sin(x1 + tanh(x1*((tanh(sinh(exp(x1)**(3*_a0_)))**2)**(_a0_ + _a1_**x1) + 1) + x1))))))
<lambdifygenerated-2962>:2: RuntimeWarning: invalid value encountered in log
  return tan(tan(x1*(x1 + log(x1 + sin(x1 + tanh(x1*((tanh(sinh(exp(x1)**(3*_a0_)))**2)**(_a0_ + _a1_**x1) + 1) + x1))))))
<lambdifygenerated-2963>:2: RuntimeWarning: invalid value encountered in power
  return tan(tan(x1*(x1 + log(x1 + sin(x1 + tanh(x1*((tanh(sinh(exp(x1)**(3*_a0_)))**2)**(_a0_ + _a1_**x1) + x1**(-1/2*x1)) + x1))))))
<lambdifygenerated-2964>:2: RuntimeWarning: invalid value encountered in power
  return tan(tan(x1*(x1 + log(x1 + sin(x1 + tanh(x1*((tanh(sinh(exp(x1)**(3*_a0_)))**2)**(_a0_ + _a1_**x1) + x1**(-1/2*x1)) + x1))))))
<lambdifygenerated-2965>:2: RuntimeWarning: invalid value encountered in sqrt
  return tan(tan(x1*(x1 + log(x1 + sin(x1 + tanh(x1*((sqrt(2)/sqrt(x1))**x1 + (tanh(sinh(exp(x1)**(3*_a0_)))**2)**(_a0_ + _a1_**x1)) + x1))))))
<lambdifygenerated-2966>:2: RuntimeWarning: invalid value encountered in sqrt
  return tan(tan(x1*(x1 + log(x1 + sin(x1 + tanh(x1*((sqrt(2)/sqrt(x1))**x1 + (tanh(sinh(exp(x1)**(3*_a0_)))**2)**(_a0_ + _a1_**x1)) + x1))))))
<lambdifygenerated-2967>:2: RuntimeWarning: invalid value encountered in sqrt
  return tan(tan(x1*(x1 + log(x1 + sin(x1 + tanh(x1*((sqrt(x1**2 + x1)/x1)**x1 + (tanh(sinh(exp(x1)**(3*_a0_)))**2)**(_a0_ + _a1_**x1)) + x1))))))
<lambdifygenerated-2967>:2: RuntimeWarning: invalid value encountered in power
  return tan(tan(x1*(x1 + log(x1 + sin(x1 + tanh(x1*((sqrt(x1**2 + x1)/x1)**x1 + (tanh(sinh(exp(x1)**(3*_a0_)))**2)**(_a0_ + _a1_**x1)) + x1))))))
<lambdifygenerated-2968>:2: RuntimeWarning: invalid value encountered in sqrt
  return tan(tan(x1*(x1 + log(x1 + sin(x1 + tanh(x1*((sqrt(x1**2 + x1)/x1)**x1 + (tanh(sinh(exp(x1)**(3*_a0_)))**2)**(_a0_ + _a1_**x1)) + x1))))))
<lambdifygenerated-2968>:2: RuntimeWarning: invalid value encountered in power
  return tan(tan(x1*(x1 + log(x1 + sin(x1 + tanh(x1*((sqrt(x1**2 + x1)/x1)**x1 + (tanh(sinh(exp(x1)**(3*_a0_)))**2)**(_a0_ + _a1_**x1)) + x1))))))
<lambdifygenerated-2969>:2: RuntimeWarning: invalid value encountered in sqrt
  return tan(tan(x1*(x1 + log(x1 + sin(x1 + tanh(x1*((sqrt(_a3_*x1 + x1)/x1)**x1 + (tanh(sinh(exp(x1)**(3*_a0_)))**2)**(_a0_ + _a1_**x1)) + x1))))))
<lambdifygenerated-2970>:2: RuntimeWarning: invalid value encountered in sqrt
  return tan(tan(x1*(x1 + log(x1 + sin(x1 + tanh(x1*((sqrt(_a3_*x1 + x1)/x1)**x1 + (tanh(sinh(exp(x1)**(3*_a0_)))**2)**(_a0_ + _a1_**x1)) + x1))))))
<lambdifygenerated-2971>:2: RuntimeWarning: invalid value encountered in sqrt
  return tan(tan(x1*(x1 + log(x1 + sin(x1 + tanh(x1*((sqrt(_a1_*_a3_ + x1)/x1)**x1 + (tanh(sinh(exp(x1)**(3*_a0_)))**2)**(_a0_ + _a1_**x1)) + x1))))))
<lambdifygenerated-2971>:2: RuntimeWarning: invalid value encountered in power
  return tan(tan(x1*(x1 + log(x1 + sin(x1 + tanh(x1*((sqrt(_a1_*_a3_ + x1)/x1)**x1 + (tanh(sinh(exp(x1)**(3*_a0_)))**2)**(_a0_ + _a1_**x1)) + x1))))))
<lambdifygenerated-2972>:2: RuntimeWarning: invalid value encountered in sqrt
  return tan(tan(x1*(x1 + log(x1 + sin(x1 + tanh(x1*((sqrt(_a1_*_a3_ + x1)/x1)**x1 + (tanh(sinh(exp(x1)**(3*_a0_)))**2)**(_a0_ + _a1_**x1)) + x1))))))
<lambdifygenerated-2972>:2: RuntimeWarning: invalid value encountered in power
  return tan(tan(x1*(x1 + log(x1 + sin(x1 + tanh(x1*((sqrt(_a1_*_a3_ + x1)/x1)**x1 + (tanh(sinh(exp(x1)**(3*_a0_)))**2)**(_a0_ + _a1_**x1)) + x1))))))
<lambdifygenerated-2973>:2: RuntimeWarning: invalid value encountered in sqrt
  return tan(tan(x1*(x1 + log(x1 + sin(x1 + tanh(x1*((sqrt(_a1_*_a3_ + x1)/x1)**x1 + (tanh(sinh(exp(x1)**(3*_a0_)))**2)**(_a0_ + _a1_**x1)) + x1))))))
<lambdifygenerated-2973>:2: RuntimeWarning: invalid value encountered in power
  return tan(tan(x1*(x1 + log(x1 + sin(x1 + tanh(x1*((sqrt(_a1_*_a3_ + x1)/x1)**x1 + (tanh(sinh(exp(x1)**(3*_a0_)))**2)**(_a0_ + _a1_**x1)) + x1))))))
<lambdifygenerated-2974>:2: RuntimeWarning: invalid value encountered in sqrt
  return tan(tan(x1*(x1 + log(x1 + sin(x1 + tanh(x1*((sqrt(_a1_*_a3_ + x1)/x1)**x1 + (tanh(sinh(exp(x1)**(3*_a0_)))**2)**(_a0_ + _a1_**x1)) + x1))))))
<lambdifygenerated-2974>:2: RuntimeWarning: invalid value encountered in power
  return tan(tan(x1*(x1 + log(x1 + sin(x1 + tanh(x1*((sqrt(_a1_*_a3_ + x1)/x1)**x1 + (tanh(sinh(exp(x1)**(3*_a0_)))**2)**(_a0_ + _a1_**x1)) + x1))))))
<lambdifygenerated-2975>:2: RuntimeWarning: invalid value encountered in sqrt
  return tan(tan(x1*(x1 + log(x1 + sin(x1 + tanh(x1*((sqrt(_a1_*_a3_ + x1)/x1**2)**x1 + (tanh(sinh(exp(x1)**(3*_a0_)))**2)**(_a0_ + _a1_**x1)) + x1))))))
<lambdifygenerated-2975>:2: RuntimeWarning: invalid value encountered in log
  return tan(tan(x1*(x1 + log(x1 + sin(x1 + tanh(x1*((sqrt(_a1_*_a3_ + x1)/x1**2)**x1 + (tanh(sinh(exp(x1)**(3*_a0_)))**2)**(_a0_ + _a1_**x1)) + x1))))))
<lambdifygenerated-2976>:2: RuntimeWarning: invalid value encountered in sqrt
  return tan(tan(x1*(x1 + log(x1 + sin(x1 + tanh(x1*((sqrt(_a1_*_a3_ + x1)/x1**2)**x1 + (tanh(sinh(exp(x1)**(3*_a0_)))**2)**(_a0_ + _a1_**x1)) + x1))))))
<lambdifygenerated-2976>:2: RuntimeWarning: invalid value encountered in log
  return tan(tan(x1*(x1 + log(x1 + sin(x1 + tanh(x1*((sqrt(_a1_*_a3_ + x1)/x1**2)**x1 + (tanh(sinh(exp(x1)**(3*_a0_)))**2)**(_a0_ + _a1_**x1)) + x1))))))
<lambdifygenerated-2977>:2: RuntimeWarning: invalid value encountered in sqrt
  return tan(tan(x1*(x1 + log(x1 + sin(x1 + tanh(x1*((sqrt(_a1_*_a3_ + x1)/_a2_**2)**x1 + (tanh(sinh(exp(x1)**(3*_a0_)))**2)**(_a0_ + _a1_**x1)) + x1))))))
<lambdifygenerated-2977>:2: RuntimeWarning: invalid value encountered in log
  return tan(tan(x1*(x1 + log(x1 + sin(x1 + tanh(x1*((sqrt(_a1_*_a3_ + x1)/_a2_**2)**x1 + (tanh(sinh(exp(x1)**(3*_a0_)))**2)**(_a0_ + _a1_**x1)) + x1))))))
<lambdifygenerated-2978>:2: RuntimeWarning: invalid value encountered in sqrt
  return tan(tan(x1*(x1 + log(x1 + sin(x1 + tanh(x1*((sqrt(_a1_*_a3_ + x1)/_a2_**2)**x1 + (tanh(sinh(exp(x1)**(3*_a0_)))**2)**(_a0_ + _a1_**x1)) + x1))))))
<lambdifygenerated-2978>:2: RuntimeWarning: invalid value encountered in log
  return tan(tan(x1*(x1 + log(x1 + sin(x1 + tanh(x1*((sqrt(_a1_*_a3_ + x1)/_a2_**2)**x1 + (tanh(sinh(exp(x1)**(3*_a0_)))**2)**(_a0_ + _a1_**x1)) + x1))))))
<lambdifygenerated-2979>:2: RuntimeWarning: invalid value encountered in sqrt
  return tan(tan(x1*(x1 + log(x1 + sin(x1 + tanh(x1*((sqrt(_a1_*_a3_ + x1)/_a2_**2)**abs(x1) + (tanh(sinh(exp(x1)**(3*_a0_)))**2)**(_a0_ + _a1_**x1)) + x1))))))
<lambdifygenerated-2979>:2: RuntimeWarning: invalid value encountered in log
  return tan(tan(x1*(x1 + log(x1 + sin(x1 + tanh(x1*((sqrt(_a1_*_a3_ + x1)/_a2_**2)**abs(x1) + (tanh(sinh(exp(x1)**(3*_a0_)))**2)**(_a0_ + _a1_**x1)) + x1))))))
<lambdifygenerated-2980>:2: RuntimeWarning: invalid value encountered in sqrt
  return tan(tan(x1*(x1 + log(x1 + sin(x1 + tanh(x1*((sqrt(_a1_*_a3_ + x1)/_a2_**2)**abs(x1) + (tanh(sinh(exp(x1)**(3*_a0_)))**2)**(_a0_ + _a1_**x1)) + x1))))))
<lambdifygenerated-2980>:2: RuntimeWarning: invalid value encountered in log
  return tan(tan(x1*(x1 + log(x1 + sin(x1 + tanh(x1*((sqrt(_a1_*_a3_ + x1)/_a2_**2)**abs(x1) + (tanh(sinh(exp(x1)**(3*_a0_)))**2)**(_a0_ + _a1_**x1)) + x1))))))
<lambdifygenerated-2981>:2: RuntimeWarning: invalid value encountered in sqrt
  return tan(tan(x1*(x1 + log(x1 + sin(x1 + tanh(x1*((sqrt(_a1_*_a3_ + x1)/_a2_**2)**abs(x1**x1) + (tanh(sinh(exp(x1)**(3*_a0_)))**2)**(_a0_ + _a1_**x1)) + x1))))))
<lambdifygenerated-2981>:2: RuntimeWarning: invalid value encountered in power
  return tan(tan(x1*(x1 + log(x1 + sin(x1 + tanh(x1*((sqrt(_a1_*_a3_ + x1)/_a2_**2)**abs(x1**x1) + (tanh(sinh(exp(x1)**(3*_a0_)))**2)**(_a0_ + _a1_**x1)) + x1))))))
<lambdifygenerated-2982>:2: RuntimeWarning: invalid value encountered in sqrt
  return tan(tan(x1*(x1 + log(x1 + sin(x1 + tanh(x1*((sqrt(_a1_*_a3_ + x1)/_a2_**2)**abs(x1**x1) + (tanh(sinh(exp(x1)**(3*_a0_)))**2)**(_a0_ + _a1_**x1)) + x1))))))
<lambdifygenerated-2982>:2: RuntimeWarning: invalid value encountered in power
  return tan(tan(x1*(x1 + log(x1 + sin(x1 + tanh(x1*((sqrt(_a1_*_a3_ + x1)/_a2_**2)**abs(x1**x1) + (tanh(sinh(exp(x1)**(3*_a0_)))**2)**(_a0_ + _a1_**x1)) + x1))))))
<lambdifygenerated-2983>:2: RuntimeWarning: invalid value encountered in sqrt
  return tan(tan(x1*(x1 + log(x1 + sin(x1 + tanh(x1*((sqrt(_a1_*_a3_ + x1)/_a2_**2)**abs(_a5_**x1) + (tanh(sinh(exp(x1)**(3*_a0_)))**2)**(_a0_ + _a1_**x1)) + x1))))))
<lambdifygenerated-2983>:2: RuntimeWarning: invalid value encountered in log
  return tan(tan(x1*(x1 + log(x1 + sin(x1 + tanh(x1*((sqrt(_a1_*_a3_ + x1)/_a2_**2)**abs(_a5_**x1) + (tanh(sinh(exp(x1)**(3*_a0_)))**2)**(_a0_ + _a1_**x1)) + x1))))))
<lambdifygenerated-2984>:2: RuntimeWarning: invalid value encountered in sqrt
  return tan(tan(x1*(x1 + log(x1 + sin(x1 + tanh(x1*((sqrt(_a1_*_a3_ + x1)/_a2_**2)**abs(_a5_**x1) + (tanh(sinh(exp(x1)**(3*_a0_)))**2)**(_a0_ + _a1_**x1)) + x1))))))
<lambdifygenerated-2984>:2: RuntimeWarning: invalid value encountered in log
  return tan(tan(x1*(x1 + log(x1 + sin(x1 + tanh(x1*((sqrt(_a1_*_a3_ + x1)/_a2_**2)**abs(_a5_**x1) + (tanh(sinh(exp(x1)**(3*_a0_)))**2)**(_a0_ + _a1_**x1)) + x1))))))
<lambdifygenerated-2985>:2: RuntimeWarning: invalid value encountered in sqrt
  return tan(tan(x1*(x1 + log(x1 + sin(x1 + tanh(x1*((sqrt(_a1_*_a3_ + x1)/_a2_**2)**(abs(_a5_**x1)**(-1.0)) + (tanh(sinh(exp(x1)**(3*_a0_)))**2)**(_a0_ + _a1_**x1)) + x1))))))
<lambdifygenerated-2985>:2: RuntimeWarning: invalid value encountered in log
  return tan(tan(x1*(x1 + log(x1 + sin(x1 + tanh(x1*((sqrt(_a1_*_a3_ + x1)/_a2_**2)**(abs(_a5_**x1)**(-1.0)) + (tanh(sinh(exp(x1)**(3*_a0_)))**2)**(_a0_ + _a1_**x1)) + x1))))))
<lambdifygenerated-2986>:2: RuntimeWarning: invalid value encountered in sqrt
  return tan(tan(x1*(x1 + log(x1 + sin(x1 + tanh(x1*((sqrt(_a1_*_a3_ + x1)/_a2_**2)**(abs(_a5_**x1)**(-1.0)) + (tanh(sinh(exp(x1)**(3*_a0_)))**2)**(_a0_ + _a1_**x1)) + x1))))))
<lambdifygenerated-2986>:2: RuntimeWarning: invalid value encountered in log
  return tan(tan(x1*(x1 + log(x1 + sin(x1 + tanh(x1*((sqrt(_a1_*_a3_ + x1)/_a2_**2)**(abs(_a5_**x1)**(-1.0)) + (tanh(sinh(exp(x1)**(3*_a0_)))**2)**(_a0_ + _a1_**x1)) + x1))))))
<lambdifygenerated-2987>:2: RuntimeWarning: invalid value encountered in sqrt
  return tan(tan(x1*(x1 + log(x1 + sin(x1 + tanh(x1*((sqrt(_a1_*_a3_ + x1)/_a2_**2)**(abs(_a5_**_a5_)**(-1.0)) + (tanh(sinh(exp(x1)**(3*_a0_)))**2)**(_a0_ + _a1_**x1)) + x1))))))
<lambdifygenerated-2987>:2: RuntimeWarning: invalid value encountered in log
  return tan(tan(x1*(x1 + log(x1 + sin(x1 + tanh(x1*((sqrt(_a1_*_a3_ + x1)/_a2_**2)**(abs(_a5_**_a5_)**(-1.0)) + (tanh(sinh(exp(x1)**(3*_a0_)))**2)**(_a0_ + _a1_**x1)) + x1))))))
<lambdifygenerated-2988>:2: RuntimeWarning: invalid value encountered in sqrt
  return tan(tan(x1*(x1 + log(x1 + sin(x1 + tanh(x1*((sqrt(_a1_*_a3_ + x1)/_a2_**2)**(abs(_a5_**_a5_)**(-1.0)) + (tanh(sinh(exp(x1)**(3*_a0_)))**2)**(_a0_ + _a1_**x1)) + x1))))))
<lambdifygenerated-2988>:2: RuntimeWarning: invalid value encountered in log
  return tan(tan(x1*(x1 + log(x1 + sin(x1 + tanh(x1*((sqrt(_a1_*_a3_ + x1)/_a2_**2)**(abs(_a5_**_a5_)**(-1.0)) + (tanh(sinh(exp(x1)**(3*_a0_)))**2)**(_a0_ + _a1_**x1)) + x1))))))
<lambdifygenerated-2989>:2: RuntimeWarning: invalid value encountered in sqrt

interpolation

<lambdifygenerated-3005>:2: RuntimeWarning: invalid value encountered in sqrt
  return tan(tan(_a7_*(_a4_ + log(_a6_ + sin(_a3_ + tanh(_a0_*_a4_ + _a5_*((sqrt(_a1_*_a3_ + x1)/_a2_**2)**(abs(_a5_**_a5_)**(-1.0)) + (tanh(sinh(exp(x1)**(3*_a0_)))**2)**(_a0_ + _a1_**x1))))))))
<lambdifygenerated-3006>:2: RuntimeWarning: invalid value encountered in sqrt
  return tan(tan(_a7_*(_a4_ + log(_a6_ + sin(_a3_ + tanh(_a0_*_a4_ + _a5_*((sqrt(_a1_*_a3_ + x1)/_a2_**2)**(abs(_a5_**_a5_)**(-1.0)) + (tanh(sinh(exp(x1)**(3*_a0_)))**2)**(_a0_ + _a1_**x1))))))))
<lambdifygenerated-3007>:2: RuntimeWarning: invalid value encountered in sqrt
  return tan(tan(_a7_*(_a4_ + log(_a6_ + sin(_a3_ + tanh(_a0_*_a4_ + _a5_*((sqrt(_a1_*_a3_ + x1)/_a2_**2)**(abs(_a5_**_a5_)**(-1.0)) + (tanh(sinh(exp(x1)**(3*_a0_)))**2)**(_a0_ + _a1_**x1))))))))
<lambdifygenerated-3008>:2: RuntimeWarning: invalid value encountered in sqrt
  return tan(tan(_a7_*(_a4_ + log(_a6_ + sin(_a3_ + tanh(_a0_*_a4_ + _a5_*((sqrt(_a1_*_a3_ + x1)/_a2_**2)**(abs(_a5_**_a5_)**(-1.0)) + (tanh(sinh(exp(x1)**(3*_a0_)))**2)**(_a0_ + _a1_**x1))))))))

         x1         y  rep    ymodel      ybms
3745  0.997  0.855453  9.0  0.853062  0.855245
3746  0.998  0.855554  9.0  0.853135  0.855340
3747  0.998  0.855656  9.0  0.853207  0.855436
3748  0.999  0.855757  9.0  0.853280  0.855531

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.855960  9.0  0.853424  0.855721
3751  1.002  0.856062  9.0  0.853495  0.855816
3752  1.002  0.856163  9.0  0.853567  0.855911
3753  1.003  0.856265  9.0  0.853639  0.856006

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.987381  0.0  0.984444  0.978600
3746  0.998  0.987426  0.0  0.984449  0.978604
3747  0.998  0.987470  0.0  0.984455  0.978609
3748  0.999  0.987515  0.0  0.984460  0.978613

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.987604  0.0  0.984470  0.978622
3751  1.002  0.987648  0.0  0.984475  0.978627
3752  1.002  0.987692  0.0  0.984480  0.978631
3753  1.003  0.987737  0.0  0.984485  0.978636

3750

/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-3089>:2: RuntimeWarning: overflow encountered in sinh
  return x1*(x1*(2*x1 - tanh(sinh(_a0_ + _a6_*x1/_a0_))) + x1)
<lambdifygenerated-3090>:2: RuntimeWarning: overflow encountered in sinh
  return x1*(x1*(2*x1 - tanh(sinh(_a0_ + _a6_*x1/_a0_))) + x1)
<lambdifygenerated-3091>:2: RuntimeWarning: overflow encountered in sinh
  return x1*(x1*(_a7_ + x1 - tanh(sinh(_a0_ + _a6_*x1/_a0_))) + x1)
<lambdifygenerated-3092>:2: RuntimeWarning: overflow encountered in sinh
  return x1*(x1*(_a7_ + x1 - tanh(sinh(_a0_ + _a6_*x1/_a0_))) + x1)
<lambdifygenerated-3093>:2: RuntimeWarning: overflow encountered in sinh
  return x1*(x1*(_a7_ + x1**2 - tanh(sinh(_a0_ + _a6_*x1/_a0_))) + x1)
<lambdifygenerated-3094>:2: RuntimeWarning: overflow encountered in sinh
  return x1*(x1*(_a7_ + x1**2 - tanh(sinh(_a0_ + _a6_*x1/_a0_))) + x1)
<lambdifygenerated-3095>:2: RuntimeWarning: overflow encountered in sinh
  return x1*(x1*(_a7_ + 2*x1**2 - tanh(sinh(_a0_ + _a6_*x1/_a0_))) + x1)
<lambdifygenerated-3096>:2: RuntimeWarning: overflow encountered in sinh
  return x1*(x1*(_a7_ + 2*x1**2 - tanh(sinh(_a0_ + _a6_*x1/_a0_))) + x1)
<lambdifygenerated-3097>:2: RuntimeWarning: overflow encountered in sinh
  return x1*(x1*(_a7_ + x1*(_a5_ + x1) - tanh(sinh(_a0_ + _a6_*x1/_a0_))) + x1)
<lambdifygenerated-3098>:2: RuntimeWarning: overflow encountered in sinh
  return x1*(x1*(_a7_ + x1*(_a5_ + x1) - tanh(sinh(_a0_ + _a6_*x1/_a0_))) + x1)
<lambdifygenerated-3099>:2: RuntimeWarning: overflow encountered in sinh
  return x1*(x1*(_a7_ + x1*(_a5_ + x1**2) - tanh(sinh(_a0_ + _a6_*x1/_a0_))) + x1)
<lambdifygenerated-3100>:2: RuntimeWarning: overflow encountered in sinh
  return x1*(x1*(_a7_ + x1*(_a5_ + x1**2) - tanh(sinh(_a0_ + _a6_*x1/_a0_))) + x1)
<lambdifygenerated-3101>:2: RuntimeWarning: overflow encountered in sinh
  return x1*(x1*(_a7_ + x1*(_a0_*x1 + _a5_) - tanh(sinh(_a0_ + _a6_*x1/_a0_))) + x1)
<lambdifygenerated-3102>:2: RuntimeWarning: overflow encountered in sinh
  return x1*(x1*(_a7_ + x1*(_a0_*x1 + _a5_) - tanh(sinh(_a0_ + _a6_*x1/_a0_))) + x1)
<lambdifygenerated-3103>:2: RuntimeWarning: overflow encountered in sinh
  return x1*(x1*(_a7_ + x1*(_a0_*x1 + _a5_) - tanh(sinh(_a0_ + _a6_*x1/_a0_))) + x1)
<lambdifygenerated-3104>:2: RuntimeWarning: overflow encountered in sinh
  return x1*(x1*(_a7_ + x1*(_a0_*x1 + _a5_) - tanh(sinh(_a0_ + _a6_*x1/_a0_))) + x1)
<lambdifygenerated-3105>:2: RuntimeWarning: overflow encountered in sinh
  return x1*(x1*(_a7_ + (_a0_*x1 + _a5_)*exp(x1) - tanh(sinh(_a0_ + _a6_*x1/_a0_))) + x1)
<lambdifygenerated-3106>:2: RuntimeWarning: overflow encountered in sinh
  return x1*(x1*(_a7_ + (_a0_*x1 + _a5_)*exp(x1) - tanh(sinh(_a0_ + _a6_*x1/_a0_))) + x1)
<lambdifygenerated-3107>:2: RuntimeWarning: overflow encountered in sinh
  return x1*(x1*(_a7_ + (_a0_*x1 + _a5_)*exp(cos(x1)) - tanh(sinh(_a0_ + _a6_*x1/_a0_))) + x1)
<lambdifygenerated-3108>:2: RuntimeWarning: overflow encountered in sinh
  return x1*(x1*(_a7_ + (_a0_*x1 + _a5_)*exp(cos(x1)) - tanh(sinh(_a0_ + _a6_*x1/_a0_))) + x1)
<lambdifygenerated-3109>:2: RuntimeWarning: overflow encountered in sinh
  return x1*(x1*(_a7_ + (_a0_*x1 + _a5_)*exp(cos(x1**2)) - tanh(sinh(_a0_ + _a6_*x1/_a0_))) + x1)
<lambdifygenerated-3110>:2: RuntimeWarning: overflow encountered in sinh
  return x1*(x1*(_a7_ + (_a0_*x1 + _a5_)*exp(cos(x1**2)) - tanh(sinh(_a0_ + _a6_*x1/_a0_))) + x1)
<lambdifygenerated-3111>:2: RuntimeWarning: overflow encountered in sinh
  return x1*(x1*(_a7_ + (_a0_*x1 + _a5_)*exp(cos(_a6_*x1)) - tanh(sinh(_a0_ + _a6_*x1/_a0_))) + x1)
<lambdifygenerated-3112>:2: RuntimeWarning: overflow encountered in sinh
  return x1*(x1*(_a7_ + (_a0_*x1 + _a5_)*exp(cos(_a6_*x1)) - tanh(sinh(_a0_ + _a6_*x1/_a0_))) + x1)
<lambdifygenerated-3113>:2: RuntimeWarning: overflow encountered in sinh
  return x1*(x1*(_a7_ + (_a0_*x1 + _a5_)*exp(cos(_a6_*x1)) - tanh(sinh(_a0_ + _a6_*x1/_a0_))) + x1)
<lambdifygenerated-3114>:2: RuntimeWarning: overflow encountered in sinh
  return x1*(x1*(_a7_ + (_a0_*x1 + _a5_)*exp(cos(_a6_*x1)) - tanh(sinh(_a0_ + _a6_*x1/_a0_))) + x1)
<lambdifygenerated-3115>:2: RuntimeWarning: overflow encountered in sinh
  return x1*(_a6_*(_a7_ + (_a0_*x1 + _a5_)*exp(cos(_a6_*x1)) - tanh(sinh(_a0_ + _a6_*x1/_a0_))) + x1)
<lambdifygenerated-3116>:2: RuntimeWarning: overflow encountered in sinh
  return x1*(_a6_*(_a7_ + (_a0_*x1 + _a5_)*exp(cos(_a6_*x1)) - tanh(sinh(_a0_ + _a6_*x1/_a0_))) + x1)
<lambdifygenerated-3117>:2: RuntimeWarning: overflow encountered in sinh
  return x1*(_a6_*(_a7_ + (_a0_*x1 + _a5_)*exp(cos(_a6_*x1)) - tanh(sinh(_a0_ + _a6_*x1/_a0_))) + x1)
<lambdifygenerated-3118>:2: RuntimeWarning: overflow encountered in sinh
  return x1*(_a6_*(_a7_ + (_a0_*x1 + _a5_)*exp(cos(_a6_*x1)) - tanh(sinh(_a0_ + _a6_*x1/_a0_))) + x1)
<lambdifygenerated-3119>:2: RuntimeWarning: overflow encountered in sinh
  return _a3_*(_a6_*(_a7_ + (_a0_*x1 + _a5_)*exp(cos(_a6_*x1)) - tanh(sinh(_a0_ + _a6_*x1/_a0_))) + x1)
<lambdifygenerated-3120>:2: RuntimeWarning: overflow encountered in sinh
  return _a3_*(_a6_*(_a7_ + (_a0_*x1 + _a5_)*exp(cos(_a6_*x1)) - tanh(sinh(_a0_ + _a6_*x1/_a0_))) + x1)
<lambdifygenerated-3121>:2: RuntimeWarning: overflow encountered in sinh
  return _a3_*(_a6_*(_a7_ + (_a0_*x1 + _a5_)*exp(cos(_a6_*x1)) - tanh(sinh(_a0_ + _a6_*x1/_a0_))) + x1)
<lambdifygenerated-3122>:2: RuntimeWarning: overflow encountered in sinh
  return _a3_*(_a6_*(_a7_ + (_a0_*x1 + _a5_)*exp(cos(_a6_*x1)) - tanh(sinh(_a0_ + _a6_*x1/_a0_))) + x1)
<lambdifygenerated-3123>:2: RuntimeWarning: overflow encountered in sinh
  return _a3_*(_a6_*(_a7_ + (_a0_*x1 + _a5_)*exp(cos(_a6_*x1)) - tanh(sinh(_a0_ + _a6_*x1/_a0_))) + x1)

interpolation

<lambdifygenerated-3124>:2: RuntimeWarning: overflow encountered in sinh
  return _a3_*(_a6_*(_a7_ + (_a0_*x1 + _a5_)*exp(cos(_a6_*x1)) - tanh(sinh(_a0_ + _a6_*x1/_a0_))) + x1)

         x1         y  rep    ymodel      ybms
3745  0.997  0.053138  1.0  0.060177  0.052929
3746  0.998  0.053057  1.0  0.060167  0.052860
3747  0.998  0.052975  1.0  0.060158  0.052791
3748  0.999  0.052894  1.0  0.060148  0.052723

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.052733  1.0  0.060131  0.052585
3751  1.002  0.052652  1.0  0.060122  0.052516
3752  1.002  0.052571  1.0  0.060113  0.052447
3753  1.003  0.052491  1.0  0.060105  0.052378

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.277484  2.0  0.289434  0.285578
3746  0.998  0.277627  2.0  0.289672  0.285637
3747  0.998  0.277770  2.0  0.289910  0.285693
3748  0.999  0.277912  2.0  0.290147  0.285744

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.278193  2.0  0.290617  0.285835
3751  1.002  0.278333  2.0  0.290851  0.285875
3752  1.002  0.278471  2.0  0.291084  0.285910
3753  1.003  0.278610  2.0  0.291316  0.285941

3750
interpolation

<lambdifygenerated-3177>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1 + x1**x1)
<lambdifygenerated-3178>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1 + x1**x1)
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(

         x1         y  rep    ymodel      ybms
3745  0.997  0.306760  3.0  0.307664  0.308968
3746  0.998  0.307033  3.0  0.307891  0.309193
3747  0.998  0.307306  3.0  0.308118  0.309417
3748  0.999  0.307578  3.0  0.308344  0.309640

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.308120  3.0  0.308793  0.310081
3751  1.002  0.308390  3.0  0.309017  0.310300
3752  1.002  0.308660  3.0  0.309240  0.310517
3753  1.003  0.308928  3.0  0.309463  0.310733

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.965360  4.0  0.964809  0.951098
3746  0.998  0.965399  4.0  0.964831  0.951098
3747  0.998  0.965439  4.0  0.964854  0.951098
3748  0.999  0.965479  4.0  0.964876  0.951098

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.965559  4.0  0.964921  0.951098
3751  1.002  0.965598  4.0  0.964943  0.951098
3752  1.002  0.965638  4.0  0.964966  0.951098
3753  1.003  0.965678  4.0  0.964988  0.951099

3750
interpolation

<lambdifygenerated-3245>:2: RuntimeWarning: overflow encountered in exp
  return x1*exp(tanh(x1 + exp(x1))/x1)
/usr/local/lib/python3.10/dist-packages/pandas/core/arraylike.py:399: RuntimeWarning: overflow encountered in square
  result = getattr(ufunc, method)(*inputs, **kwargs)
<lambdifygenerated-3246>:2: RuntimeWarning: overflow encountered in exp
  return x1*exp(tanh(x1 + exp(x1))/x1)
<lambdifygenerated-3247>:2: RuntimeWarning: overflow encountered in exp
  return x1*exp(tanh(x1 + exp(x1**2))/x1)
<lambdifygenerated-3248>:2: RuntimeWarning: overflow encountered in exp
  return x1*exp(tanh(x1 + exp(x1**2))/x1)
<lambdifygenerated-3249>:2: RuntimeWarning: overflow encountered in exp
  return x1*exp(tanh(x1 + exp(x1**2))/x1)
<lambdifygenerated-3250>:2: RuntimeWarning: overflow encountered in exp
  return x1*exp(tanh(x1 + exp(x1**2))/x1)
<lambdifygenerated-3251>:2: RuntimeWarning: overflow encountered in exp
  return x1*exp(tanh(x1 + exp(_a3_*x1))/x1)
/usr/local/lib/python3.10/dist-packages/scipy/optimize/_minpack_py.py:1017: RuntimeWarning: overflow encountered in square
  cost = np.sum(infodict['fvec'] ** 2)
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-3252>:2: RuntimeWarning: overflow encountered in exp
  return x1*exp(tanh(x1 + exp(_a3_*x1))/x1)
<lambdifygenerated-3253>:2: RuntimeWarning: overflow encountered in exp
  return x1*exp(tanh(_a1_ + exp(_a3_*x1))/x1)
<lambdifygenerated-3254>:2: RuntimeWarning: overflow encountered in exp
  return x1*exp(tanh(_a1_ + exp(_a3_*x1))/x1)
<lambdifygenerated-3257>:2: RuntimeWarning: overflow encountered in exp
  return _a0_*exp(tanh(_a1_ + exp(_a3_*x1))/_a5_)
<lambdifygenerated-3258>:2: RuntimeWarning: overflow encountered in exp
  return _a0_*exp(tanh(_a1_ + exp(_a3_*x1))/_a5_)
<lambdifygenerated-3259>:2: RuntimeWarning: overflow encountered in exp
  return _a0_*exp(tanh(_a1_ + exp(_a3_*x1))/_a5_)
<lambdifygenerated-3260>:2: RuntimeWarning: overflow encountered in exp
  return _a0_*exp(tanh(_a1_ + exp(_a3_*x1))/_a5_)
<lambdifygenerated-3261>:2: RuntimeWarning: overflow encountered in exp
  return _a0_*exp(tanh(_a1_ + exp(_a3_*x1))/_a5_)
<lambdifygenerated-3262>:2: RuntimeWarning: overflow encountered in exp
  return _a0_*exp(tanh(_a1_ + exp(_a3_*x1))/_a5_)

         x1         y  rep    ymodel      ybms
3745  0.997  0.308339  5.0  0.308862  0.295856
3746  0.998  0.308354  5.0  0.308922  0.295856
3747  0.998  0.308368  5.0  0.308983  0.295856
3748  0.999  0.308382  5.0  0.309043  0.295856

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.308407  5.0  0.309165  0.295856
3751  1.002  0.308419  5.0  0.309225  0.295856
3752  1.002  0.308430  5.0  0.309286  0.295856
3753  1.003  0.308441  5.0  0.309346  0.295856

3750

/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(

interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.215897  6.0  0.213959  0.212630
3746  0.998  0.216041  6.0  0.214080  0.212719
3747  0.998  0.216186  6.0  0.214200  0.212808
3748  0.999  0.216330  6.0  0.214321  0.212897

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.216618  6.0  0.214561  0.213074
3751  1.002  0.216762  6.0  0.214680  0.213162
3752  1.002  0.216905  6.0  0.214800  0.213249
3753  1.003  0.217048  6.0  0.214919  0.213336

3750
interpolation

/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-3347>:2: RuntimeWarning: invalid value encountered in power
  return _a3_/(_a6_*(x1 + sin(x1 + x1**x1*(_a0_ + x1))))
<lambdifygenerated-3348>:2: RuntimeWarning: invalid value encountered in power
  return _a3_/(_a6_*(x1 + sin(x1 + x1**x1*(_a0_ + x1))))

         x1         y  rep    ymodel      ybms
3745  0.997  0.100918  7.0  0.114389  0.106350
3746  0.998  0.100912  7.0  0.114400  0.106346
3747  0.998  0.100906  7.0  0.114412  0.106342
3748  0.999  0.100901  7.0  0.114423  0.106337

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.100890  7.0  0.114445  0.106329
3751  1.002  0.100885  7.0  0.114456  0.106324
3752  1.002  0.100880  7.0  0.114468  0.106320
3753  1.003  0.100874  7.0  0.114479  0.106316

3750
interpolation

/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(

         x1         y  rep    ymodel      ybms
3745  0.997  0.825595  8.0  0.824475  0.814260
3746  0.998  0.825925  8.0  0.824806  0.814496
3747  0.998  0.826254  8.0  0.825136  0.814732
3748  0.999  0.826582  8.0  0.825466  0.814967

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.827238  8.0  0.826125  0.815435
3751  1.002  0.827565  8.0  0.826453  0.815668
3752  1.002  0.827892  8.0  0.826781  0.815900
3753  1.003  0.828218  8.0  0.827109  0.816131

3750
interpolation

<lambdifygenerated-3401>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1
<lambdifygenerated-3402>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1
<lambdifygenerated-3403>:2: RuntimeWarning: invalid value encountered in power
  return (2*x1)**x1
<lambdifygenerated-3404>:2: RuntimeWarning: invalid value encountered in power
  return (2*x1)**x1
<lambdifygenerated-3405>:2: RuntimeWarning: invalid value encountered in power
  return (x1**2 + x1)**x1
<lambdifygenerated-3406>:2: RuntimeWarning: invalid value encountered in power
  return (x1**2 + x1)**x1
<lambdifygenerated-3407>:2: RuntimeWarning: invalid value encountered in power
  return (x1*x1**x1 + x1)**x1
<lambdifygenerated-3408>:2: RuntimeWarning: invalid value encountered in power
  return (x1*x1**x1 + x1)**x1
<lambdifygenerated-3409>:2: RuntimeWarning: invalid value encountered in power
  return (x1*(x1**2)**x1 + x1)**x1
<lambdifygenerated-3410>:2: RuntimeWarning: invalid value encountered in power
  return (x1*(x1**2)**x1 + x1)**x1
<lambdifygenerated-3411>:2: RuntimeWarning: invalid value encountered in power
  return (x1*(_a1_*x1)**x1 + x1)**x1
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-3412>:2: RuntimeWarning: invalid value encountered in power
  return (x1*(_a1_*x1)**x1 + x1)**x1
<lambdifygenerated-3413>:2: RuntimeWarning: invalid value encountered in power
  return (x1*(_a1_*_a2_)**x1 + x1)**x1
<lambdifygenerated-3414>:2: RuntimeWarning: invalid value encountered in power
  return (x1*(_a1_*_a2_)**x1 + x1)**x1
<lambdifygenerated-3415>:2: RuntimeWarning: invalid value encountered in power
  return (x1*(_a1_*_a2_)**x1 + x1)**x1
<lambdifygenerated-3416>:2: RuntimeWarning: invalid value encountered in power
  return (x1*(_a1_*_a2_)**x1 + x1)**x1
<lambdifygenerated-3417>:2: RuntimeWarning: invalid value encountered in power
  return (_a5_*(_a1_*_a2_)**x1 + x1)**x1
<lambdifygenerated-3418>:2: RuntimeWarning: invalid value encountered in power
  return (_a5_*(_a1_*_a2_)**x1 + x1)**x1
<lambdifygenerated-3419>:2: RuntimeWarning: invalid value encountered in power
  return (_a2_ + _a5_*(_a1_*_a2_)**x1)**x1
<lambdifygenerated-3421>:2: RuntimeWarning: invalid value encountered in power
  return (_a2_ + _a5_*(_a1_*_a2_)**x1)**_a3_
<lambdifygenerated-3425>:2: RuntimeWarning: invalid value encountered in power
  return (_a2_ + _a5_*(_a1_*_a2_)**x1)**_a3_

         x1         y  rep    ymodel      ybms
3745  0.997  0.855453  9.0  0.856026  0.852366
3746  0.998  0.855554  9.0  0.856109  0.852427
3747  0.998  0.855656  9.0  0.856191  0.852488
3748  0.999  0.855757  9.0  0.856273  0.852549

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.855960  9.0  0.856437  0.852670
3751  1.002  0.856062  9.0  0.856519  0.852731
3752  1.002  0.856163  9.0  0.856601  0.852791
3753  1.003  0.856265  9.0  0.856682  0.852851

3750

<lambdifygenerated-3437>:2: RuntimeWarning: invalid value encountered in power
  return x1 + tanh(x1 + x1**x1)
<lambdifygenerated-3438>:2: RuntimeWarning: invalid value encountered in power
  return x1 + tanh(x1 + x1**x1)
<lambdifygenerated-3439>:2: RuntimeWarning: invalid value encountered in power
  return x1 + tanh(x1 + (x1**x1)**x1)
<lambdifygenerated-3440>:2: RuntimeWarning: invalid value encountered in power
  return x1 + tanh(x1 + (x1**x1)**x1)
<lambdifygenerated-3445>:2: RuntimeWarning: invalid value encountered in power
  return x1 + tanh(x1 + (_a1_**x1)**(2*x1))
<lambdifygenerated-3447>:2: RuntimeWarning: invalid value encountered in power
  return x1 + tanh(x1 + (_a1_**x1)**(_a3_ + x1))
<lambdifygenerated-3449>:2: RuntimeWarning: invalid value encountered in power
  return x1 + tanh(x1 + (_a1_**x1)**(_a3_ + 2*x1))
<lambdifygenerated-3451>:2: RuntimeWarning: invalid value encountered in power
  return x1 + tanh(x1 + (_a1_**x1)**(_a3_ + _a6_ + x1))
<lambdifygenerated-3451>:2: RuntimeWarning: overflow encountered in power
  return x1 + tanh(x1 + (_a1_**x1)**(_a3_ + _a6_ + x1))
<lambdifygenerated-3453>:2: RuntimeWarning: invalid value encountered in power
  return x1 + tanh(x1 + (_a1_**x1)**(_a3_ + _a6_ + sin(x1)))
<lambdifygenerated-3453>:2: RuntimeWarning: overflow encountered in power
  return x1 + tanh(x1 + (_a1_**x1)**(_a3_ + _a6_ + sin(x1)))
<lambdifygenerated-3455>:2: RuntimeWarning: invalid value encountered in power
  return x1 + tanh(x1 + (_a1_**x1)**(_a3_ + _a6_ + sin(2*x1)))
<lambdifygenerated-3455>:2: RuntimeWarning: overflow encountered in power
  return x1 + tanh(x1 + (_a1_**x1)**(_a3_ + _a6_ + sin(2*x1)))
<lambdifygenerated-3459>:2: RuntimeWarning: invalid value encountered in power
  return x1 + tanh(x1 + (_a1_**x1)**(_a3_ + _a6_ + sin(_a1_ + x1)))
<lambdifygenerated-3459>:2: RuntimeWarning: overflow encountered in power
  return x1 + tanh(x1 + (_a1_**x1)**(_a3_ + _a6_ + sin(_a1_ + x1)))
<lambdifygenerated-3461>:2: RuntimeWarning: overflow encountered in power
  return x1 + tanh(_a4_ + (_a1_**x1)**(_a3_ + _a6_ + sin(_a1_ + x1)))

interpolation

<lambdifygenerated-3463>:2: RuntimeWarning: overflow encountered in power
  return 2*x1 + tanh(_a4_ + (_a1_**x1)**(_a3_ + _a6_ + sin(_a1_ + x1)))
<lambdifygenerated-3465>:2: RuntimeWarning: overflow encountered in power
  return _a7_ + x1 + tanh(_a4_ + (_a1_**x1)**(_a3_ + _a6_ + sin(_a1_ + x1)))
<lambdifygenerated-3467>:2: RuntimeWarning: invalid value encountered in power
  return _a7_ + x1**2 + tanh(_a4_ + (_a1_**x1)**(_a3_ + _a6_ + sin(_a1_ + x1)))
<lambdifygenerated-3471>:2: RuntimeWarning: invalid value encountered in power
  return _a6_*x1 + _a7_ + tanh(_a4_ + (_a1_**x1)**(_a3_ + _a6_ + sin(_a1_ + x1)))

         x1         y  rep    ymodel      ybms
3745  0.997  0.987381  0.0  0.982248  0.995595
3746  0.998  0.987426  0.0  0.982263  0.995664
3747  0.998  0.987470  0.0  0.982277  0.995732
3748  0.999  0.987515  0.0  0.982292  0.995801

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.987604  0.0  0.982320  0.995938
3751  1.002  0.987648  0.0  0.982335  0.996006
3752  1.002  0.987692  0.0  0.982349  0.996075
3753  1.003  0.987737  0.0  0.982363  0.996143

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.053138  1.0  0.055881  0.037558
3746  0.998  0.053057  1.0  0.055827  0.037271
3747  0.998  0.052975  1.0  0.055774  0.036984
3748  0.999  0.052894  1.0  0.055721  0.036695

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.052733  1.0  0.055616  0.036114
3751  1.002  0.052652  1.0  0.055563  0.035821
3752  1.002  0.052571  1.0  0.055511  0.035528
3753  1.003  0.052491  1.0  0.055459  0.035233

3750

<lambdifygenerated-3561>:2: RuntimeWarning: invalid value encountered in power
  return -x1**3*(-x1 - cos(x1*(x1 + x1**x1) + x1)) + x1
<lambdifygenerated-3562>:2: RuntimeWarning: invalid value encountered in power
  return -x1**3*(-x1 - cos(x1*(x1 + x1**x1) + x1)) + x1

interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.277484  2.0  0.287902  0.278167
3746  0.998  0.277627  2.0  0.288149  0.277995
3747  0.998  0.277770  2.0  0.288395  0.277816
3748  0.999  0.277912  2.0  0.288641  0.277631

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.278193  2.0  0.289130  0.277242
3751  1.002  0.278333  2.0  0.289373  0.277038
3752  1.002  0.278471  2.0  0.289615  0.276827
3753  1.003  0.278610  2.0  0.289856  0.276610

3750

<lambdifygenerated-3595>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1
<lambdifygenerated-3596>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(

interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.306760  3.0  0.299006  0.296521
3746  0.998  0.307033  3.0  0.299256  0.296782
3747  0.998  0.307306  3.0  0.299505  0.297042
3748  0.999  0.307578  3.0  0.299754  0.297301

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.308120  3.0  0.300250  0.297819
3751  1.002  0.308390  3.0  0.300496  0.298077
3752  1.002  0.308660  3.0  0.300743  0.298335
3753  1.003  0.308928  3.0  0.300988  0.298592

3750
interpolation

<lambdifygenerated-3633>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1/x1
<lambdifygenerated-3634>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1/x1
<lambdifygenerated-3641>:2: RuntimeWarning: invalid value encountered in power
  return _a0_**x1/(x1 + x1**x1)
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-3642>:2: RuntimeWarning: invalid value encountered in power
  return _a0_**x1/(x1 + x1**x1)
<lambdifygenerated-3645>:2: RuntimeWarning: invalid value encountered in power
  return _a0_**x1/(x1 + (_a4_*x1)**x1)
<lambdifygenerated-3646>:2: RuntimeWarning: invalid value encountered in power
  return _a0_**x1/(x1 + (_a4_*x1)**x1)
<lambdifygenerated-3651>:2: RuntimeWarning: invalid value encountered in power
  return _a0_**x1/(_a2_ + (_a4_**2)**x1)

         x1         y  rep    ymodel      ybms
3745  0.997  0.965360  4.0  0.955444  0.958901
3746  0.998  0.965399  4.0  0.955435  0.958924
3747  0.998  0.965439  4.0  0.955426  0.958946
3748  0.999  0.965479  4.0  0.955416  0.958969

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.965559  4.0  0.955397  0.959014
3751  1.002  0.965598  4.0  0.955388  0.959036
3752  1.002  0.965638  4.0  0.955378  0.959059
3753  1.003  0.965678  4.0  0.955369  0.959081

3750

<lambdifygenerated-3671>:2: RuntimeWarning: invalid value encountered in power
  return x1*tanh(_a1_ + x1**x1) + x1
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-3672>:2: RuntimeWarning: invalid value encountered in power
  return x1*tanh(_a1_ + x1**x1) + x1
<lambdifygenerated-3677>:2: RuntimeWarning: invalid value encountered in power
  return _a0_*tanh(_a1_ + _a5_**x1) + x1

interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.308339  5.0  0.311198  0.297063
3746  0.998  0.308354  5.0  0.311255  0.297063
3747  0.998  0.308368  5.0  0.311312  0.297063
3748  0.999  0.308382  5.0  0.311369  0.297063

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.308407  5.0  0.311481  0.297063
3751  1.002  0.308419  5.0  0.311537  0.297063
3752  1.002  0.308430  5.0  0.311592  0.297063
3753  1.003  0.308441  5.0  0.311648  0.297063

3750
interpolation

<lambdifygenerated-3691>:2: RuntimeWarning: invalid value encountered in log
  return log(x1)/x1
<lambdifygenerated-3692>:2: RuntimeWarning: invalid value encountered in log
  return log(x1)/x1
<lambdifygenerated-3693>:2: RuntimeWarning: invalid value encountered in log
  return log(2*x1)/x1
<lambdifygenerated-3694>:2: RuntimeWarning: invalid value encountered in log
  return log(2*x1)/x1
<lambdifygenerated-3695>:2: RuntimeWarning: invalid value encountered in log
  return log(x1 + tanh(x1))/x1
<lambdifygenerated-3696>:2: RuntimeWarning: invalid value encountered in log
  return log(x1 + tanh(x1))/x1
<lambdifygenerated-3697>:2: RuntimeWarning: invalid value encountered in log
  return log(x1 + tanh(x1**2))/x1
<lambdifygenerated-3698>:2: RuntimeWarning: invalid value encountered in log
  return log(x1 + tanh(x1**2))/x1
<lambdifygenerated-3699>:2: RuntimeWarning: invalid value encountered in log
  return log(x1 + tanh(_a0_*x1))/x1
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-3700>:2: RuntimeWarning: invalid value encountered in log
  return log(x1 + tanh(_a0_*x1))/x1
<lambdifygenerated-3701>:2: RuntimeWarning: invalid value encountered in log
  return log(x1 + tanh(2*_a0_*x1))/x1
<lambdifygenerated-3702>:2: RuntimeWarning: invalid value encountered in log
  return log(x1 + tanh(2*_a0_*x1))/x1
<lambdifygenerated-3703>:2: RuntimeWarning: invalid value encountered in log
  return log(x1 + tanh(_a0_*(_a7_ + x1)))/x1
<lambdifygenerated-3704>:2: RuntimeWarning: invalid value encountered in log
  return log(x1 + tanh(_a0_*(_a7_ + x1)))/x1
<lambdifygenerated-3705>:2: RuntimeWarning: invalid value encountered in log
  return log(x1 + tanh(_a0_*(_a7_ + x1)))/x1
<lambdifygenerated-3706>:2: RuntimeWarning: invalid value encountered in log
  return log(x1 + tanh(_a0_*(_a7_ + x1)))/x1
<lambdifygenerated-3707>:2: RuntimeWarning: invalid value encountered in log
  return log(2*x1 + tanh(_a0_*(_a7_ + x1)))/x1
<lambdifygenerated-3708>:2: RuntimeWarning: invalid value encountered in log
  return log(2*x1 + tanh(_a0_*(_a7_ + x1)))/x1
<lambdifygenerated-3709>:2: RuntimeWarning: invalid value encountered in power
  return log(x1 + x1**x1 + tanh(_a0_*(_a7_ + x1)))/x1
<lambdifygenerated-3710>:2: RuntimeWarning: invalid value encountered in power
  return log(x1 + x1**x1 + tanh(_a0_*(_a7_ + x1)))/x1
<lambdifygenerated-3711>:2: RuntimeWarning: invalid value encountered in log
  return log(_a4_**x1 + x1 + tanh(_a0_*(_a7_ + x1)))/x1
<lambdifygenerated-3712>:2: RuntimeWarning: invalid value encountered in log
  return log(_a4_**x1 + x1 + tanh(_a0_*(_a7_ + x1)))/x1
<lambdifygenerated-3713>:2: RuntimeWarning: invalid value encountered in log
  return log(_a4_**x1 + x1 + tanh(_a0_*(_a7_ + x1)))/x1
<lambdifygenerated-3714>:2: RuntimeWarning: invalid value encountered in log
  return log(_a4_**x1 + x1 + tanh(_a0_*(_a7_ + x1)))/x1
<lambdifygenerated-3715>:2: RuntimeWarning: invalid value encountered in log
  return log(_a4_**x1 + _a5_ + tanh(_a0_*(_a7_ + x1)))/x1
<lambdifygenerated-3717>:2: RuntimeWarning: invalid value encountered in log
  return log(_a4_**x1 + _a5_ + tanh(_a0_*(_a7_ + x1)))/_a1_

         x1         y  rep    ymodel      ybms
3745  0.997  0.215897  6.0  0.214945  0.227000
3746  0.998  0.216041  6.0  0.215071  0.227234
3747  0.998  0.216186  6.0  0.215196  0.227467
3748  0.999  0.216330  6.0  0.215322  0.227701

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.216618  6.0  0.215572  0.228168
3751  1.002  0.216762  6.0  0.215696  0.228401
3752  1.002  0.216905  6.0  0.215821  0.228635
3753  1.003  0.217048  6.0  0.215945  0.228868

3750
interpolation

<lambdifygenerated-3745>:2: RuntimeWarning: overflow encountered in exp
  return exp(x1 + x1**3*(_a1_ + x1)/_a4_)
/usr/local/lib/python3.10/dist-packages/scipy/optimize/_minpack_py.py:1017: RuntimeWarning: overflow encountered in square
  cost = np.sum(infodict['fvec'] ** 2)
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
/usr/local/lib/python3.10/dist-packages/pandas/core/arraylike.py:399: RuntimeWarning: overflow encountered in square
  result = getattr(ufunc, method)(*inputs, **kwargs)
<lambdifygenerated-3746>:2: RuntimeWarning: overflow encountered in exp
  return exp(x1 + x1**3*(_a1_ + x1)/_a4_)
<lambdifygenerated-3747>:2: RuntimeWarning: overflow encountered in exp
  return exp(x1**2 + x1**3*(_a1_ + x1)/_a4_)
<lambdifygenerated-3748>:2: RuntimeWarning: overflow encountered in exp
  return exp(x1**2 + x1**3*(_a1_ + x1)/_a4_)
<lambdifygenerated-3749>:2: RuntimeWarning: overflow encountered in exp
  return exp(_a4_*x1 + x1**3*(_a1_ + x1)/_a4_)
<lambdifygenerated-3750>:2: RuntimeWarning: overflow encountered in exp
  return exp(_a4_*x1 + x1**3*(_a1_ + x1)/_a4_)
<lambdifygenerated-3751>:2: RuntimeWarning: overflow encountered in exp
  return exp(_a4_*exp(x1) + x1**3*(_a1_ + x1)/_a4_)
<lambdifygenerated-3752>:2: RuntimeWarning: overflow encountered in exp
  return exp(_a4_*exp(x1) + x1**3*(_a1_ + x1)/_a4_)
<lambdifygenerated-3753>:2: RuntimeWarning: overflow encountered in exp
  return exp(_a4_*exp(x1) + x1**3*(_a1_ + x1)/_a4_)
<lambdifygenerated-3754>:2: RuntimeWarning: overflow encountered in exp
  return exp(_a4_*exp(x1) + x1**3*(_a1_ + x1)/_a4_)
<lambdifygenerated-3755>:2: RuntimeWarning: overflow encountered in exp
  return exp(_a4_*exp(x1) + x1**3*(_a1_ + x1)/_a4_)
<lambdifygenerated-3756>:2: RuntimeWarning: overflow encountered in exp
  return exp(_a4_*exp(x1) + x1**3*(_a1_ + x1)/_a4_)
<lambdifygenerated-3757>:2: RuntimeWarning: overflow encountered in exp
  return exp(_a4_*exp(x1) + x1**3*(_a1_ + x1)/_a4_)
<lambdifygenerated-3758>:2: RuntimeWarning: overflow encountered in exp
  return exp(_a4_*exp(x1) + x1**3*(_a1_ + x1)/_a4_)

         x1         y  rep    ymodel      ybms
3745  0.997  0.100918  7.0  0.104080  0.100865
3746  0.998  0.100912  7.0  0.104085  0.100880
3747  0.998  0.100906  7.0  0.104090  0.100895
3748  0.999  0.100901  7.0  0.104096  0.100911

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.100890  7.0  0.104106  0.100942
3751  1.002  0.100885  7.0  0.104111  0.100958
3752  1.002  0.100880  7.0  0.104117  0.100974
3753  1.003  0.100874  7.0  0.104122  0.100990

3750
interpolation

<lambdifygenerated-3769>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1 + x1**x1) + x1
<lambdifygenerated-3770>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1 + x1**x1) + x1
<lambdifygenerated-3775>:2: RuntimeWarning: invalid value encountered in power
  return x1*(_a5_**tanh(x1**2) + x1) + x1
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-3787>:2: RuntimeWarning: invalid value encountered in power
  return x1*(_a5_**tanh(_a1_*x1/(_a4_ + x1)) + x1) + x1
<lambdifygenerated-3788>:2: RuntimeWarning: invalid value encountered in power
  return x1*(_a5_**tanh(_a1_*x1/(_a4_ + x1)) + x1) + x1
<lambdifygenerated-3789>:2: RuntimeWarning: invalid value encountered in power
  return x1*(_a5_**tanh(_a1_*x1/(_a4_ + x1)) + cos(x1)) + x1
<lambdifygenerated-3790>:2: RuntimeWarning: invalid value encountered in power
  return x1*(_a5_**tanh(_a1_*x1/(_a4_ + x1)) + cos(x1)) + x1
<lambdifygenerated-3791>:2: RuntimeWarning: invalid value encountered in power
  return x1*(_a5_**tanh(_a1_*x1/(_a4_ + x1)) + cos(x1)) + x1
<lambdifygenerated-3792>:2: RuntimeWarning: invalid value encountered in power
  return x1*(_a5_**tanh(_a1_*x1/(_a4_ + x1)) + cos(x1)) + x1
<lambdifygenerated-3793>:2: RuntimeWarning: invalid value encountered in power
  return _a5_*(_a5_**tanh(_a1_*x1/(_a4_ + x1)) + cos(x1)) + x1
<lambdifygenerated-3794>:2: RuntimeWarning: invalid value encountered in power
  return _a5_*(_a5_**tanh(_a1_*x1/(_a4_ + x1)) + cos(x1)) + x1
<lambdifygenerated-3795>:2: RuntimeWarning: invalid value encountered in power
  return _a5_*(_a5_**tanh(_a1_*x1/(_a4_ + x1)) + cos(x1)) + _a5_
<lambdifygenerated-3796>:2: RuntimeWarning: invalid value encountered in power
  return _a5_*(_a5_**tanh(_a1_*x1/(_a4_ + x1)) + cos(x1)) + _a5_
<lambdifygenerated-3797>:2: RuntimeWarning: invalid value encountered in power
  return _a5_*(_a5_**tanh(_a1_*x1/(_a4_ + x1)) + cos(x1)) + _a5_
<lambdifygenerated-3798>:2: RuntimeWarning: invalid value encountered in power
  return _a5_*(_a5_**tanh(_a1_*x1/(_a4_ + x1)) + cos(x1)) + _a5_
<lambdifygenerated-3799>:2: RuntimeWarning: invalid value encountered in power
  return _a5_*(_a5_**tanh(_a1_*x1/(_a4_ + x1)) + cos(x1)) + _a5_
<lambdifygenerated-3800>:2: RuntimeWarning: invalid value encountered in power
  return _a5_*(_a5_**tanh(_a1_*x1/(_a4_ + x1)) + cos(x1)) + _a5_

         x1         y  rep    ymodel      ybms
3745  0.997  0.825595  8.0  0.828214  0.825756
3746  0.998  0.825925  8.0  0.828539  0.826073
3747  0.998  0.826254  8.0  0.828863  0.826389
3748  0.999  0.826582  8.0  0.829186  0.826705

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.827238  8.0  0.829832  0.827335
3751  1.002  0.827565  8.0  0.830153  0.827649
3752  1.002  0.827892  8.0  0.830475  0.827962
3753  1.003  0.828218  8.0  0.830795  0.828275

3750
interpolation

<lambdifygenerated-3809>:2: RuntimeWarning: invalid value encountered in power
  return _a1_*x1**x1
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-3810>:2: RuntimeWarning: invalid value encountered in power
  return _a1_*x1**x1
<lambdifygenerated-3811>:2: RuntimeWarning: invalid value encountered in power
  return _a1_*(2*x1)**x1
<lambdifygenerated-3812>:2: RuntimeWarning: invalid value encountered in power
  return _a1_*(2*x1)**x1
<lambdifygenerated-3813>:2: RuntimeWarning: invalid value encountered in power
  return _a1_*(x1 + x1**x1)**x1
<lambdifygenerated-3814>:2: RuntimeWarning: invalid value encountered in power
  return _a1_*(x1 + x1**x1)**x1
<lambdifygenerated-3819>:2: RuntimeWarning: invalid value encountered in power
  return _a1_*(x1 + exp(x1)**_a6_)**x1
<lambdifygenerated-3820>:2: RuntimeWarning: invalid value encountered in power
  return _a1_*(x1 + exp(x1)**_a6_)**x1
<lambdifygenerated-3823>:2: RuntimeWarning: invalid value encountered in power
  return _a1_*(_a3_ + exp(x1)**_a6_)**_a5_

         x1         y  rep    ymodel      ybms
3745  0.997  0.855453  9.0  0.856657  0.849371
3746  0.998  0.855554  9.0  0.856741  0.849422
3747  0.998  0.855656  9.0  0.856825  0.849472
3748  0.999  0.855757  9.0  0.856909  0.849522

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.855960  9.0  0.857077  0.849623
3751  1.002  0.856062  9.0  0.857160  0.849673
3752  1.002  0.856163  9.0  0.857244  0.849722
3753  1.003  0.856265  9.0  0.857327  0.849772

3750

<lambdifygenerated-3843>:2: RuntimeWarning: invalid value encountered in power
  return x1*tanh(x1*x1**x1 + x1) + x1
<lambdifygenerated-3844>:2: RuntimeWarning: invalid value encountered in power
  return x1*tanh(x1*x1**x1 + x1) + x1
<lambdifygenerated-3845>:2: RuntimeWarning: invalid value encountered in power
  return x1*tanh(_a7_**x1*x1 + x1) + x1
<lambdifygenerated-3851>:2: RuntimeWarning: invalid value encountered in power
  return x1*tanh(_a7_**(x1**2*cos(x1)**2)*x1 + x1) + x1
<lambdifygenerated-3855>:2: RuntimeWarning: invalid value encountered in power
  return x1*tanh(_a7_**(4*x1**2*cos(x1)**2)*x1 + x1) + x1
<lambdifygenerated-3861>:2: RuntimeWarning: invalid value encountered in power
  return x1*tanh(_a0_*_a7_**((_a5_ + x1)**2*cos(x1)**2) + x1) + x1

interpolation

<lambdifygenerated-3867>:2: RuntimeWarning: invalid value encountered in power
  return x1*tanh(_a0_*_a7_**((_a5_ + x1)**2*cos(x1)**2) + _a1_*x1) + x1
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(

         x1         y  rep    ymodel      ybms
3745  0.997  0.987381  0.0  0.982380  0.986542
3746  0.998  0.987426  0.0  0.982403  0.986555
3747  0.998  0.987470  0.0  0.982425  0.986568
3748  0.999  0.987515  0.0  0.982448  0.986581

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.987604  0.0  0.982493  0.986606
3751  1.002  0.987648  0.0  0.982516  0.986619
3752  1.002  0.987692  0.0  0.982538  0.986632
3753  1.003  0.987737  0.0  0.982560  0.986645

3750

<lambdifygenerated-3915>:2: RuntimeWarning: invalid value encountered in power
  return x1**2*sin(x1*(x1 + (_a2_*x1 + tanh(_a3_*x1))**2*sin(x1**x1)**2)) + x1
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-3916>:2: RuntimeWarning: invalid value encountered in power
  return x1**2*sin(x1*(x1 + (_a2_*x1 + tanh(_a3_*x1))**2*sin(x1**x1)**2)) + x1
<lambdifygenerated-3925>:2: RuntimeWarning: invalid value encountered in log
  return x1**2*sin(x1*(x1 + (_a2_*x1 + tanh(_a3_*x1))**2*sin(_a2_**sin(x1*log(x1)))**2)) + x1
<lambdifygenerated-3926>:2: RuntimeWarning: invalid value encountered in log
  return x1**2*sin(x1*(x1 + (_a2_*x1 + tanh(_a3_*x1))**2*sin(_a2_**sin(x1*log(x1)))**2)) + x1
<lambdifygenerated-3931>:2: RuntimeWarning: invalid value encountered in power
  return x1**2*sin(_a7_*(_a0_ + (_a2_*x1 + tanh(_a3_*x1))**2*sin(_a2_**sin(x1*log(_a0_)))**2)) + x1
<lambdifygenerated-3933>:2: RuntimeWarning: invalid value encountered in power
  return 2*x1**2*sin(_a7_*(_a0_ + (_a2_*x1 + tanh(_a3_*x1))**2*sin(_a2_**sin(x1*log(_a0_)))**2)) + x1
<lambdifygenerated-3935>:2: RuntimeWarning: invalid value encountered in power
  return x1*(_a6_ + x1)*sin(_a7_*(_a0_ + (_a2_*x1 + tanh(_a3_*x1))**2*sin(_a2_**sin(x1*log(_a0_)))**2)) + x1
<lambdifygenerated-3943>:2: RuntimeWarning: invalid value encountered in log
  return _a3_*(_a2_*x1 + _a6_)*sin(_a7_*(_a0_ + (_a2_*x1 + tanh(_a3_*x1))**2*sin(_a2_**sin(x1*log(_a0_)))**2)) + x1

interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.053138  1.0  0.057057  0.058591
3746  0.998  0.053057  1.0  0.057058  0.058625
3747  0.998  0.052975  1.0  0.057059  0.058659
3748  0.999  0.052894  1.0  0.057061  0.058694

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.052733  1.0  0.057065  0.058765
3751  1.002  0.052652  1.0  0.057068  0.058801
3752  1.002  0.052571  1.0  0.057070  0.058838
3753  1.003  0.052491  1.0  0.057074  0.058876

3750

/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(

interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.277484  2.0  0.281834  0.258777
3746  0.998  0.277627  2.0  0.282052  0.258600
3747  0.998  0.277770  2.0  0.282271  0.258420
3748  0.999  0.277912  2.0  0.282488  0.258236

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.278193  2.0  0.282919  0.257856
3751  1.002  0.278333  2.0  0.283133  0.257661
3752  1.002  0.278471  2.0  0.283347  0.257462
3753  1.003  0.278610  2.0  0.283560  0.257259

3750
interpolation

<lambdifygenerated-4005>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1/x1
<lambdifygenerated-4006>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1/x1
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(

         x1         y  rep    ymodel      ybms
3745  0.997  0.306760  3.0  0.311699  0.307930
3746  0.998  0.307033  3.0  0.312018  0.308214
3747  0.998  0.307306  3.0  0.312337  0.308497
3748  0.999  0.307578  3.0  0.312654  0.308779

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.308120  3.0  0.313288  0.309342
3751  1.002  0.308390  3.0  0.313604  0.309622
3752  1.002  0.308660  3.0  0.313919  0.309902
3753  1.003  0.308928  3.0  0.314234  0.310181

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.965360  4.0  0.966899  0.949523
3746  0.998  0.965399  4.0  0.966952  0.949523
3747  0.998  0.965439  4.0  0.967006  0.949523
3748  0.999  0.965479  4.0  0.967059  0.949523

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.965559  4.0  0.967166  0.949523
3751  1.002  0.965598  4.0  0.967219  0.949523
3752  1.002  0.965638  4.0  0.967272  0.949523
3753  1.003  0.965678  4.0  0.967326  0.949523

3750

<lambdifygenerated-4069>:2: RuntimeWarning: invalid value encountered in power
  return x1*tanh(x1 + x1**x1) + x1
<lambdifygenerated-4070>:2: RuntimeWarning: invalid value encountered in power
  return x1*tanh(x1 + x1**x1) + x1
<lambdifygenerated-4077>:2: RuntimeWarning: invalid value encountered in power
  return _a4_*tanh(_a0_ + _a6_**x1) + x1

interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.308339  5.0  0.304939  0.292757
3746  0.998  0.308354  5.0  0.304976  0.292757
3747  0.998  0.308368  5.0  0.305013  0.292757
3748  0.999  0.308382  5.0  0.305049  0.292757

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.308407  5.0  0.305122  0.292757
3751  1.002  0.308419  5.0  0.305158  0.292757
3752  1.002  0.308430  5.0  0.305194  0.292757
3753  1.003  0.308441  5.0  0.305229  0.292757

3750
interpolation

/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(

         x1         y  rep    ymodel      ybms
3745  0.997  0.215897  6.0  0.213215  0.208560
3746  0.998  0.216041  6.0  0.213312  0.208676
3747  0.998  0.216186  6.0  0.213409  0.208792
3748  0.999  0.216330  6.0  0.213506  0.208908

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.216618  6.0  0.213698  0.209139
3751  1.002  0.216762  6.0  0.213793  0.209254
3752  1.002  0.216905  6.0  0.213888  0.209369
3753  1.003  0.217048  6.0  0.213983  0.209484

3750

<lambdifygenerated-4131>:2: RuntimeWarning: invalid value encountered in power
  return -x1*x1**x1
<lambdifygenerated-4132>:2: RuntimeWarning: invalid value encountered in power
  return -x1*x1**x1
<lambdifygenerated-4133>:2: RuntimeWarning: invalid value encountered in power
  return -x1*(x1**x1)**x1
<lambdifygenerated-4134>:2: RuntimeWarning: invalid value encountered in power
  return -x1*(x1**x1)**x1
<lambdifygenerated-4135>:2: RuntimeWarning: invalid value encountered in power
  return -x1*(_a5_**x1)**x1
<lambdifygenerated-4137>:2: RuntimeWarning: invalid value encountered in power
  return -x1*(_a5_**(x1**3))**x1
<lambdifygenerated-4137>:2: RuntimeWarning: overflow encountered in power
  return -x1*(_a5_**(x1**3))**x1
<lambdifygenerated-4138>:2: RuntimeWarning: overflow encountered in power
  return -x1*(_a5_**(x1**3))**x1
<lambdifygenerated-4139>:2: RuntimeWarning: overflow encountered in power
  return -x1*(_a5_**(8*x1**3))**x1
<lambdifygenerated-4140>:2: RuntimeWarning: overflow encountered in power
  return -x1*(_a5_**(8*x1**3))**x1
<lambdifygenerated-4141>:2: RuntimeWarning: overflow encountered in power
  return -x1*(_a5_**(8*x1**3))**x1
<lambdifygenerated-4142>:2: RuntimeWarning: overflow encountered in power
  return -x1*(_a5_**(8*x1**3))**x1
<lambdifygenerated-4143>:2: RuntimeWarning: invalid value encountered in power
  return -x1*(_a5_**((_a2_ + x1)**3))**x1
<lambdifygenerated-4143>:2: RuntimeWarning: overflow encountered in power
  return -x1*(_a5_**((_a2_ + x1)**3))**x1
<lambdifygenerated-4144>:2: RuntimeWarning: overflow encountered in power
  return -x1*(_a5_**((_a2_ + x1)**3))**x1
<lambdifygenerated-4145>:2: RuntimeWarning: overflow encountered in power
  return -x1*(_a5_**((_a2_ + x1)**3))**(2*x1)
<lambdifygenerated-4149>:2: RuntimeWarning: invalid value encountered in power
  return -x1*(_a5_**((_a2_ + x1)**3))**(_a4_ + x1)
<lambdifygenerated-4149>:2: RuntimeWarning: overflow encountered in power
  return -x1*(_a5_**((_a2_ + x1)**3))**(_a4_ + x1)
<lambdifygenerated-4150>:2: RuntimeWarning: overflow encountered in power
  return -x1*(_a5_**((_a2_ + x1)**3))**(_a4_ + x1)
<lambdifygenerated-4151>:2: RuntimeWarning: overflow encountered in power
  return -_a7_*(_a5_**((_a2_ + x1)**3))**(_a4_ + x1)
<lambdifygenerated-4151>:2: RuntimeWarning: invalid value encountered in power
  return -_a7_*(_a5_**((_a2_ + x1)**3))**(_a4_ + x1)
<lambdifygenerated-4155>:2: RuntimeWarning: overflow encountered in power
  return -_a7_*(_a5_**((_a2_ + x1)**3))**(_a4_ + x1)

interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.100918  7.0  0.092021  0.096232
3746  0.998  0.100912  7.0  0.091999  0.096229
3747  0.998  0.100906  7.0  0.091976  0.096227
3748  0.999  0.100901  7.0  0.091954  0.096224

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.100890  7.0  0.091910  0.096220
3751  1.002  0.100885  7.0  0.091887  0.096218
3752  1.002  0.100880  7.0  0.091865  0.096216
3753  1.003  0.100874  7.0  0.091843  0.096214

3750
interpolation

/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(

         x1         y  rep    ymodel      ybms
3745  0.997  0.825595  8.0  0.829612  0.838041
3746  0.998  0.825925  8.0  0.829936  0.838435
3747  0.998  0.826254  8.0  0.830260  0.838829
3748  0.999  0.826582  8.0  0.830583  0.839222

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.827238  8.0  0.831227  0.840006
3751  1.002  0.827565  8.0  0.831548  0.840398
3752  1.002  0.827892  8.0  0.831869  0.840789
3753  1.003  0.828218  8.0  0.832189  0.841180

3750
interpolation

<lambdifygenerated-4201>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1
<lambdifygenerated-4202>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1
<lambdifygenerated-4205>:2: RuntimeWarning: invalid value encountered in power
  return (x1*exp(x1))**x1
<lambdifygenerated-4206>:2: RuntimeWarning: invalid value encountered in power
  return (x1*exp(x1))**x1
<lambdifygenerated-4207>:2: RuntimeWarning: invalid value encountered in power
  return (x1*exp(_a5_))**x1
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-4208>:2: RuntimeWarning: invalid value encountered in power
  return (x1*exp(_a5_))**x1
<lambdifygenerated-4209>:2: RuntimeWarning: invalid value encountered in power
  return (2*x1*exp(_a5_))**x1
<lambdifygenerated-4210>:2: RuntimeWarning: invalid value encountered in power
  return (2*x1*exp(_a5_))**x1
<lambdifygenerated-4211>:2: RuntimeWarning: invalid value encountered in power
  return ((_a0_ + x1)*exp(_a5_))**x1
<lambdifygenerated-4212>:2: RuntimeWarning: invalid value encountered in power
  return ((_a0_ + x1)*exp(_a5_))**x1
<lambdifygenerated-4213>:2: RuntimeWarning: invalid value encountered in power
  return ((_a0_ + x1**x1)*exp(_a5_))**x1
<lambdifygenerated-4214>:2: RuntimeWarning: invalid value encountered in power
  return ((_a0_ + x1**x1)*exp(_a5_))**x1
<lambdifygenerated-4215>:2: RuntimeWarning: invalid value encountered in power
  return ((_a0_ + _a7_**x1)*exp(_a5_))**x1
<lambdifygenerated-4219>:2: RuntimeWarning: invalid value encountered in power
  return ((_a0_ + _a7_**x1)*exp(_a5_))**_a3_
<lambdifygenerated-4223>:2: RuntimeWarning: overflow encountered in exp
  return ((_a0_ + _a7_**x1)*exp(_a5_))**_a3_
<lambdifygenerated-4223>:2: RuntimeWarning: invalid value encountered in power
  return ((_a0_ + _a7_**x1)*exp(_a5_))**_a3_

         x1         y  rep    ymodel      ybms
3745  0.997  0.855453  9.0  0.853636  0.850777
3746  0.998  0.855554  9.0  0.853711  0.850835
3747  0.998  0.855656  9.0  0.853786  0.850892
3748  0.999  0.855757  9.0  0.853861  0.850949

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.855960  9.0  0.854010  0.851062
3751  1.002  0.856062  9.0  0.854084  0.851119
3752  1.002  0.856163  9.0  0.854159  0.851175
3753  1.003  0.856265  9.0  0.854233  0.851231

3750
interpolation

         x1         y  rep    ymodel     ybms
3745  0.997  0.987381  0.0  0.973266  0.97907
3746  0.998  0.987426  0.0  0.973205  0.97907
3747  0.998  0.987470  0.0  0.973143  0.97907
3748  0.999  0.987515  0.0  0.973081  0.97907

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.987604  0.0  0.972957  0.979071
3751  1.002  0.987648  0.0  0.972895  0.979071
3752  1.002  0.987692  0.0  0.972833  0.979071
3753  1.003  0.987737  0.0  0.972770  0.979071

3750
interpolation

<lambdifygenerated-4319>:2: RuntimeWarning: overflow encountered in sinh
  return (_a6_*sin(_a0_*(_a3_*x1 + _a3_) + abs(_a3_ + sinh(_a1_*x1 + _a2_))) + x1)**2/x1**2
<lambdifygenerated-4319>:2: RuntimeWarning: invalid value encountered in sin
  return (_a6_*sin(_a0_*(_a3_*x1 + _a3_) + abs(_a3_ + sinh(_a1_*x1 + _a2_))) + x1)**2/x1**2
<lambdifygenerated-4321>:2: RuntimeWarning: invalid value encountered in power
  return (_a6_*sin(_a0_*(_a3_*x1 + _a3_) + abs(_a3_ + sinh(_a1_*x1 + _a2_))) + x1**x1)**2/x1**2
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-4322>:2: RuntimeWarning: invalid value encountered in power
  return (_a6_*sin(_a0_*(_a3_*x1 + _a3_) + abs(_a3_ + sinh(_a1_*x1 + _a2_))) + x1**x1)**2/x1**2
<lambdifygenerated-4323>:2: RuntimeWarning: overflow encountered in sinh
  return (_a6_*sin(_a0_*(_a3_*x1 + _a3_) + abs(_a3_ + sinh(_a1_*x1 + _a2_))) + _a7_**x1)**2/x1**2
<lambdifygenerated-4323>:2: RuntimeWarning: invalid value encountered in sin
  return (_a6_*sin(_a0_*(_a3_*x1 + _a3_) + abs(_a3_ + sinh(_a1_*x1 + _a2_))) + _a7_**x1)**2/x1**2
<lambdifygenerated-4323>:2: RuntimeWarning: invalid value encountered in power
  return (_a6_*sin(_a0_*(_a3_*x1 + _a3_) + abs(_a3_ + sinh(_a1_*x1 + _a2_))) + _a7_**x1)**2/x1**2

         x1         y  rep    ymodel      ybms
3745  0.997  0.053138  1.0  0.080919  0.084852
3746  0.998  0.053057  1.0  0.081017  0.085061
3747  0.998  0.052975  1.0  0.081115  0.085272
3748  0.999  0.052894  1.0  0.081213  0.085483

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.052733  1.0  0.081410  0.085910
3751  1.002  0.052652  1.0  0.081509  0.086125
3752  1.002  0.052571  1.0  0.081609  0.086341
3753  1.003  0.052491  1.0  0.081708  0.086558

3750

<lambdifygenerated-4351>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1 + cos(_a0_*x1**(-x1)))**3 + x1
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-4352>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1 + cos(_a0_*x1**(-x1)))**3 + x1

interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.277484  2.0  0.310363  0.310866
3746  0.998  0.277627  2.0  0.310776  0.311341
3747  0.998  0.277770  2.0  0.311188  0.311816
3748  0.999  0.277912  2.0  0.311599  0.312289

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.278193  2.0  0.312419  0.313233
3751  1.002  0.278333  2.0  0.312827  0.313704
3752  1.002  0.278471  2.0  0.313234  0.314173
3753  1.003  0.278610  2.0  0.313641  0.314641

3750
interpolation

<lambdifygenerated-4375>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1
<lambdifygenerated-4376>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1

         x1         y  rep    ymodel      ybms
3745  0.997  0.306760  3.0  0.295778  0.329025
3746  0.998  0.307033  3.0  0.296018  0.329619
3747  0.998  0.307306  3.0  0.296258  0.330214
3748  0.999  0.307578  3.0  0.296496  0.330810

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.308120  3.0  0.296972  0.332004
3751  1.002  0.308390  3.0  0.297210  0.332602
3752  1.002  0.308660  3.0  0.297446  0.333200
3753  1.003  0.308928  3.0  0.297683  0.333800

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.965360  4.0  0.957049  0.945001
3746  0.998  0.965399  4.0  0.957066  0.945001
3747  0.998  0.965439  4.0  0.957082  0.945001
3748  0.999  0.965479  4.0  0.957099  0.945001

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.965559  4.0  0.957132  0.945001
3751  1.002  0.965598  4.0  0.957148  0.945001
3752  1.002  0.965638  4.0  0.957165  0.945001
3753  1.003  0.965678  4.0  0.957181  0.945001

3750
interpolation

<lambdifygenerated-4427>:2: RuntimeWarning: invalid value encountered in power
  return x1*x1**x1 + x1
<lambdifygenerated-4428>:2: RuntimeWarning: invalid value encountered in power
  return x1*x1**x1 + x1
<lambdifygenerated-4431>:2: RuntimeWarning: invalid value encountered in power
  return _a4_**(x1**x1)*x1 + x1
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-4432>:2: RuntimeWarning: invalid value encountered in power
  return _a4_**(x1**x1)*x1 + x1
<lambdifygenerated-4433>:2: RuntimeWarning: invalid value encountered in power
  return _a4_**(_a3_**x1)*x1 + x1

         x1         y  rep    ymodel     ybms
3745  0.997  0.308339  5.0  0.304555  0.29526
3746  0.998  0.308354  5.0  0.304613  0.29526
3747  0.998  0.308368  5.0  0.304671  0.29526
3748  0.999  0.308382  5.0  0.304729  0.29526

extrapolation

         x1         y  rep    ymodel     ybms
3750  1.001  0.308407  5.0  0.304845  0.29526
3751  1.002  0.308419  5.0  0.304903  0.29526
3752  1.002  0.308430  5.0  0.304962  0.29526
3753  1.003  0.308441  5.0  0.305020  0.29526

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.215897  6.0  0.216814  0.231552
3746  0.998  0.216041  6.0  0.216971  0.231808
3747  0.998  0.216186  6.0  0.217128  0.232065
3748  0.999  0.216330  6.0  0.217285  0.232321

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.216618  6.0  0.217598  0.232834
3751  1.002  0.216762  6.0  0.217754  0.233091
3752  1.002  0.216905  6.0  0.217911  0.233347
3753  1.003  0.217048  6.0  0.218066  0.233604

3750
interpolation

<lambdifygenerated-4491>:2: RuntimeWarning: invalid value encountered in power
  return _a3_*x1**x1
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-4492>:2: RuntimeWarning: invalid value encountered in power
  return _a3_*x1**x1
<lambdifygenerated-4507>:2: RuntimeWarning: invalid value encountered in log
  return _a3_*((_a0_ + x1)**2)**(x1*(x1 + log(x1)))
<lambdifygenerated-4508>:2: RuntimeWarning: invalid value encountered in log
  return _a3_*((_a0_ + x1)**2)**(x1*(x1 + log(x1)))

         x1         y  rep    ymodel      ybms
3745  0.997  0.100918  7.0  0.125188  0.103802
3746  0.998  0.100912  7.0  0.125241  0.103865
3747  0.998  0.100906  7.0  0.125295  0.103928
3748  0.999  0.100901  7.0  0.125348  0.103991

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.100890  7.0  0.125455  0.104119
3751  1.002  0.100885  7.0  0.125508  0.104183
3752  1.002  0.100880  7.0  0.125561  0.104248
3753  1.003  0.100874  7.0  0.125615  0.104313

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.825595  8.0  0.812031  0.864709
3746  0.998  0.825925  8.0  0.812334  0.865301
3747  0.998  0.826254  8.0  0.812637  0.865893
3748  0.999  0.826582  8.0  0.812939  0.866485

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.827238  8.0  0.813541  0.867669
3751  1.002  0.827565  8.0  0.813842  0.868261
3752  1.002  0.827892  8.0  0.814142  0.868853
3753  1.003  0.828218  8.0  0.814442  0.869445

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.855453  9.0  0.861995  0.860690
3746  0.998  0.855554  9.0  0.862119  0.860783
3747  0.998  0.855656  9.0  0.862242  0.860877
3748  0.999  0.855757  9.0  0.862366  0.860971

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.855960  9.0  0.862612  0.861157
3751  1.002  0.856062  9.0  0.862735  0.861250
3752  1.002  0.856163  9.0  0.862858  0.861342
3753  1.003  0.856265  9.0  0.862980  0.861435

3750
interpolation

<lambdifygenerated-4595>:2: RuntimeWarning: invalid value encountered in power
  return x1**2*(_a0_ + x1**x1 + cos(_a1_ + x1))**2
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-4596>:2: RuntimeWarning: invalid value encountered in power
  return x1**2*(_a0_ + x1**x1 + cos(_a1_ + x1))**2
<lambdifygenerated-4597>:2: RuntimeWarning: invalid value encountered in power
  return x1**2*(_a0_ + (2*x1)**x1 + cos(_a1_ + x1))**2
<lambdifygenerated-4598>:2: RuntimeWarning: invalid value encountered in power
  return x1**2*(_a0_ + (2*x1)**x1 + cos(_a1_ + x1))**2
<lambdifygenerated-4599>:2: RuntimeWarning: invalid value encountered in power
  return x1**2*(_a0_ + (x1**2 + x1)**x1 + cos(_a1_ + x1))**2
<lambdifygenerated-4600>:2: RuntimeWarning: invalid value encountered in power
  return x1**2*(_a0_ + (x1**2 + x1)**x1 + cos(_a1_ + x1))**2
<lambdifygenerated-4601>:2: RuntimeWarning: invalid value encountered in power
  return x1**2*(_a0_ + (4*x1**2 + x1)**x1 + cos(_a1_ + x1))**2
<lambdifygenerated-4602>:2: RuntimeWarning: invalid value encountered in power
  return x1**2*(_a0_ + (4*x1**2 + x1)**x1 + cos(_a1_ + x1))**2
<lambdifygenerated-4603>:2: RuntimeWarning: invalid value encountered in power
  return x1**2*(_a0_ + (4*x1**2 + x1)**x1 + cos(_a1_ + x1))**2
<lambdifygenerated-4604>:2: RuntimeWarning: invalid value encountered in power
  return x1**2*(_a0_ + (4*x1**2 + x1)**x1 + cos(_a1_ + x1))**2
<lambdifygenerated-4605>:2: RuntimeWarning: invalid value encountered in power
  return x1**2*(_a0_ + (x1 + (_a3_ + x1)**2)**x1 + cos(_a1_ + x1))**2
<lambdifygenerated-4606>:2: RuntimeWarning: invalid value encountered in power
  return x1**2*(_a0_ + (x1 + (_a3_ + x1)**2)**x1 + cos(_a1_ + x1))**2
<lambdifygenerated-4607>:2: RuntimeWarning: invalid value encountered in power
  return x1**2*(_a0_ + (_a2_ + (_a3_ + x1)**2)**x1 + cos(_a1_ + x1))**2
<lambdifygenerated-4609>:2: RuntimeWarning: invalid value encountered in power
  return x1**2*(_a0_ + (_a2_ + (_a3_ + x1)**2)**_a6_ + cos(_a1_ + x1))**2
<lambdifygenerated-4611>:2: RuntimeWarning: invalid value encountered in power
  return _a4_**2*(_a0_ + (_a2_ + (_a3_ + x1)**2)**_a6_ + cos(_a1_ + x1))**2

         x1         y  rep    ymodel      ybms
3745  0.997  0.987381  0.0  0.977234  0.959722
3746  0.998  0.987426  0.0  0.977228  0.959586
3747  0.998  0.987470  0.0  0.977222  0.959450
3748  0.999  0.987515  0.0  0.977217  0.959313

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.987604  0.0  0.977205  0.959037
3751  1.002  0.987648  0.0  0.977199  0.958899
3752  1.002  0.987692  0.0  0.977193  0.958760
3753  1.003  0.987737  0.0  0.977186  0.958621

3750
interpolation

/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(

         x1         y  rep    ymodel      ybms
3745  0.997  0.053138  1.0  0.064721  0.044254
3746  0.998  0.053057  1.0  0.064722  0.044150
3747  0.998  0.052975  1.0  0.064723  0.044047
3748  0.999  0.052894  1.0  0.064725  0.043944

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.052733  1.0  0.064729  0.043739
3751  1.002  0.052652  1.0  0.064731  0.043637
3752  1.002  0.052571  1.0  0.064733  0.043535
3753  1.003  0.052491  1.0  0.064736  0.043434

3750
interpolation

<lambdifygenerated-4705>:2: RuntimeWarning: invalid value encountered in power
  return (x1**x1 + tan(_a0_*cos(_a3_*(_a2_ + x1)*(_a4_ + x1))))/x1
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-4706>:2: RuntimeWarning: invalid value encountered in power
  return (x1**x1 + tan(_a0_*cos(_a3_*(_a2_ + x1)*(_a4_ + x1))))/x1
<lambdifygenerated-4707>:2: RuntimeWarning: invalid value encountered in power
  return (_a0_**x1 + tan(_a0_*cos(_a3_*(_a2_ + x1)*(_a4_ + x1))))/x1
<lambdifygenerated-4708>:2: RuntimeWarning: invalid value encountered in power
  return (_a0_**x1 + tan(_a0_*cos(_a3_*(_a2_ + x1)*(_a4_ + x1))))/x1
<lambdifygenerated-4709>:2: RuntimeWarning: invalid value encountered in power
  return (_a0_**x1 + tan(_a0_*cos(_a3_*(_a2_ + x1)*(_a4_ + x1))))/x1
<lambdifygenerated-4710>:2: RuntimeWarning: invalid value encountered in power
  return (_a0_**x1 + tan(_a0_*cos(_a3_*(_a2_ + x1)*(_a4_ + x1))))/x1
<lambdifygenerated-4711>:2: RuntimeWarning: invalid value encountered in power
  return (_a0_**x1 + tan(_a0_*cos(_a3_*(_a2_ + x1)*(_a4_ + x1))))/_a1_
<lambdifygenerated-4712>:2: RuntimeWarning: invalid value encountered in power
  return (_a0_**x1 + tan(_a0_*cos(_a3_*(_a2_ + x1)*(_a4_ + x1))))/_a1_
<lambdifygenerated-4713>:2: RuntimeWarning: invalid value encountered in power
  return (_a0_**x1 + tan(_a0_*cos(_a3_*(_a2_ + x1)*(_a4_ + x1))))/_a1_
<lambdifygenerated-4714>:2: RuntimeWarning: invalid value encountered in power
  return (_a0_**x1 + tan(_a0_*cos(_a3_*(_a2_ + x1)*(_a4_ + x1))))/_a1_
<lambdifygenerated-4715>:2: RuntimeWarning: invalid value encountered in power
  return (_a0_**x1 + tan(_a0_*cos(_a3_*(_a2_ + x1)*(_a4_ + x1))))/_a1_
<lambdifygenerated-4716>:2: RuntimeWarning: invalid value encountered in power
  return (_a0_**x1 + tan(_a0_*cos(_a3_*(_a2_ + x1)*(_a4_ + x1))))/_a1_

         x1         y  rep    ymodel      ybms
3745  0.997  0.277484  2.0  0.290940  0.333575
3746  0.998  0.277627  2.0  0.291376  0.334163
3747  0.998  0.277770  2.0  0.291812  0.334749
3748  0.999  0.277912  2.0  0.292246  0.335333

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.278193  2.0  0.293112  0.336496
3751  1.002  0.278333  2.0  0.293544  0.337074
3752  1.002  0.278471  2.0  0.293975  0.337650
3753  1.003  0.278610  2.0  0.294405  0.338223

3750
interpolation

<lambdifygenerated-4723>:2: RuntimeWarning: invalid value encountered in power
  return x1*x1**x1
<lambdifygenerated-4724>:2: RuntimeWarning: invalid value encountered in power
  return x1*x1**x1
<lambdifygenerated-4725>:2: RuntimeWarning: invalid value encountered in power
  return -x1*x1**x1
<lambdifygenerated-4726>:2: RuntimeWarning: invalid value encountered in power
  return -x1*x1**x1
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-4743>:2: RuntimeWarning: overflow encountered in power
  return -x1*(_a2_**2/x1**2)**(x1*(_a1_ + exp(x1)))
/usr/local/lib/python3.10/dist-packages/scipy/optimize/_minpack_py.py:1017: RuntimeWarning: overflow encountered in square
  cost = np.sum(infodict['fvec'] ** 2)
/usr/local/lib/python3.10/dist-packages/pandas/core/arraylike.py:399: RuntimeWarning: overflow encountered in square
  result = getattr(ufunc, method)(*inputs, **kwargs)
<lambdifygenerated-4744>:2: RuntimeWarning: overflow encountered in power
  return -x1*(_a2_**2/x1**2)**(x1*(_a1_ + exp(x1)))

         x1         y  rep    ymodel      ybms
3745  0.997  0.306760  3.0  0.299917  0.298931
3746  0.998  0.307033  3.0  0.300057  0.298976
3747  0.998  0.307306  3.0  0.300196  0.299019
3748  0.999  0.307578  3.0  0.300334  0.299059

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.308120  3.0  0.300609  0.299135
3751  1.002  0.308390  3.0  0.300745  0.299171
3752  1.002  0.308660  3.0  0.300881  0.299204
3753  1.003  0.308928  3.0  0.301016  0.299235

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.965360  4.0  0.959798  0.946274
3746  0.998  0.965399  4.0  0.959841  0.946274
3747  0.998  0.965439  4.0  0.959885  0.946274
3748  0.999  0.965479  4.0  0.959929  0.946274

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.965559  4.0  0.960016  0.946274
3751  1.002  0.965598  4.0  0.960060  0.946275
3752  1.002  0.965638  4.0  0.960103  0.946275
3753  1.003  0.965678  4.0  0.960147  0.946275

3750
interpolation

<lambdifygenerated-4785>:2: RuntimeWarning: invalid value encountered in power
  return x1*x1**x1 + x1
<lambdifygenerated-4786>:2: RuntimeWarning: invalid value encountered in power
  return x1*x1**x1 + x1
<lambdifygenerated-4789>:2: RuntimeWarning: invalid value encountered in power
  return _a3_**(x1**x1)*x1 + x1
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-4790>:2: RuntimeWarning: invalid value encountered in power
  return _a3_**(x1**x1)*x1 + x1
<lambdifygenerated-4791>:2: RuntimeWarning: invalid value encountered in power
  return _a3_**(_a7_**x1)*x1 + x1

         x1         y  rep    ymodel      ybms
3745  0.997  0.308339  5.0  0.274083  0.292705
3746  0.998  0.308354  5.0  0.274043  0.292705
3747  0.998  0.308368  5.0  0.274003  0.292705
3748  0.999  0.308382  5.0  0.273963  0.292705

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.308407  5.0  0.273883  0.292705
3751  1.002  0.308419  5.0  0.273843  0.292705
3752  1.002  0.308430  5.0  0.273803  0.292705
3753  1.003  0.308441  5.0  0.273764  0.292705

3750

<lambdifygenerated-4815>:2: RuntimeWarning: overflow encountered in exp
  return x1 + exp((_a4_ + x1)/x1)
/usr/local/lib/python3.10/dist-packages/scipy/optimize/_minpack_py.py:1017: RuntimeWarning: overflow encountered in square
  cost = np.sum(infodict['fvec'] ** 2)
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
/usr/local/lib/python3.10/dist-packages/pandas/core/arraylike.py:399: RuntimeWarning: overflow encountered in square
  result = getattr(ufunc, method)(*inputs, **kwargs)
<lambdifygenerated-4816>:2: RuntimeWarning: overflow encountered in exp
  return x1 + exp((_a4_ + x1)/x1)
<lambdifygenerated-4817>:2: RuntimeWarning: overflow encountered in exp
  return x1 + exp((_a4_ + x1**2)/x1)
<lambdifygenerated-4818>:2: RuntimeWarning: overflow encountered in exp
  return x1 + exp((_a4_ + x1**2)/x1)
<lambdifygenerated-4819>:2: RuntimeWarning: overflow encountered in exp
  return x1 + exp((_a4_ + x1**2)/x1)
<lambdifygenerated-4820>:2: RuntimeWarning: overflow encountered in exp
  return x1 + exp((_a4_ + x1**2)/x1)
<lambdifygenerated-4821>:2: RuntimeWarning: overflow encountered in exp
  return x1 + exp((_a4_ + _a6_*x1)/x1)
<lambdifygenerated-4822>:2: RuntimeWarning: overflow encountered in exp
  return x1 + exp((_a4_ + _a6_*x1)/x1)
<lambdifygenerated-4825>:2: RuntimeWarning: overflow encountered in exp
  return x1 + exp((_a4_ + _a6_*x1)/(_a0_ + x1))
<lambdifygenerated-4826>:2: RuntimeWarning: overflow encountered in exp
  return x1 + exp((_a4_ + _a6_*x1)/(_a0_ + x1))
<lambdifygenerated-4827>:2: RuntimeWarning: overflow encountered in exp
  return x1 + exp((_a4_ + _a6_*x1)/(_a0_ + sin(x1)))
<lambdifygenerated-4828>:2: RuntimeWarning: overflow encountered in exp
  return x1 + exp((_a4_ + _a6_*x1)/(_a0_ + sin(x1)))
<lambdifygenerated-4829>:2: RuntimeWarning: overflow encountered in exp
  return x1 + exp((_a4_ + _a6_*x1)/(_a0_ + sin(2*x1)))
<lambdifygenerated-4830>:2: RuntimeWarning: overflow encountered in exp
  return x1 + exp((_a4_ + _a6_*x1)/(_a0_ + sin(2*x1)))
<lambdifygenerated-4831>:2: RuntimeWarning: overflow encountered in exp
  return x1 + exp((_a4_ + _a6_*x1)/(_a0_ + sin(2*x1)))
<lambdifygenerated-4832>:2: RuntimeWarning: overflow encountered in exp
  return x1 + exp((_a4_ + _a6_*x1)/(_a0_ + sin(2*x1)))
<lambdifygenerated-4833>:2: RuntimeWarning: overflow encountered in exp
  return x1 + exp((_a4_ + _a6_*x1)/(_a0_ + sin(_a7_ + x1)))
<lambdifygenerated-4835>:2: RuntimeWarning: overflow encountered in exp
  return _a2_ + exp((_a4_ + _a6_*x1)/(_a0_ + sin(_a7_ + x1)))

interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.215897  6.0  0.217482  0.205393
3746  0.998  0.216041  6.0  0.217664  0.205529
3747  0.998  0.216186  6.0  0.217846  0.205666
3748  0.999  0.216330  6.0  0.218028  0.205803

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.216618  6.0  0.218392  0.206075
3751  1.002  0.216762  6.0  0.218573  0.206211
3752  1.002  0.216905  6.0  0.218755  0.206347
3753  1.003  0.217048  6.0  0.218936  0.206483

3750
interpolation

<lambdifygenerated-4863>:2: RuntimeWarning: overflow encountered in exp
  return exp(_a3_*x1*exp(-x1)*cos(x1) + x1)
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-4864>:2: RuntimeWarning: overflow encountered in exp
  return exp(_a3_*x1*exp(-x1)*cos(x1) + x1)
<lambdifygenerated-4865>:2: RuntimeWarning: overflow encountered in exp
  return exp(_a3_*x1*exp(-x1)*cos(2*x1) + x1)
<lambdifygenerated-4866>:2: RuntimeWarning: overflow encountered in exp
  return exp(_a3_*x1*exp(-x1)*cos(2*x1) + x1)
<lambdifygenerated-4867>:2: RuntimeWarning: overflow encountered in exp
  return exp(_a3_*x1*exp(-x1)*cos(_a7_ + x1) + x1)
<lambdifygenerated-4868>:2: RuntimeWarning: overflow encountered in exp
  return exp(_a3_*x1*exp(-x1)*cos(_a7_ + x1) + x1)
<lambdifygenerated-4869>:2: RuntimeWarning: overflow encountered in exp
  return exp(_a3_*x1*exp(-x1)*cos(_a7_ + x1) + x1)
<lambdifygenerated-4870>:2: RuntimeWarning: overflow encountered in exp
  return exp(_a3_*x1*exp(-x1)*cos(_a7_ + x1) + x1)
<lambdifygenerated-4871>:2: RuntimeWarning: overflow encountered in exp
  return exp(_a2_ + _a3_*x1*exp(-x1)*cos(_a7_ + x1))
<lambdifygenerated-4872>:2: RuntimeWarning: overflow encountered in exp
  return exp(_a2_ + _a3_*x1*exp(-x1)*cos(_a7_ + x1))
<lambdifygenerated-4873>:2: RuntimeWarning: overflow encountered in exp
  return exp(_a2_ + _a3_*x1*exp(-x1)*cos(_a7_ + x1))
<lambdifygenerated-4874>:2: RuntimeWarning: overflow encountered in exp
  return exp(_a2_ + _a3_*x1*exp(-x1)*cos(_a7_ + x1))
<lambdifygenerated-4875>:2: RuntimeWarning: overflow encountered in exp
  return exp(_a2_ + _a3_*x1*exp(-x1)*cos(_a7_ + x1))
<lambdifygenerated-4876>:2: RuntimeWarning: overflow encountered in exp
  return exp(_a2_ + _a3_*x1*exp(-x1)*cos(_a7_ + x1))

         x1         y  rep    ymodel      ybms
3745  0.997  0.100918  7.0  0.101363  0.094392
3746  0.998  0.100912  7.0  0.101370  0.094397
3747  0.998  0.100906  7.0  0.101377  0.094402
3748  0.999  0.100901  7.0  0.101384  0.094407

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.100890  7.0  0.101399  0.094417
3751  1.002  0.100885  7.0  0.101406  0.094423
3752  1.002  0.100880  7.0  0.101414  0.094428
3753  1.003  0.100874  7.0  0.101421  0.094434

3750

<lambdifygenerated-4889>:2: RuntimeWarning: invalid value encountered in power
  return x1*(_a2_ + x1 + x1**x1)
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-4890>:2: RuntimeWarning: invalid value encountered in power
  return x1*(_a2_ + x1 + x1**x1)
<lambdifygenerated-4899>:2: RuntimeWarning: invalid value encountered in power
  return x1*(_a0_**tanh(_a5_*x1) + _a2_ + x1)
<lambdifygenerated-4903>:2: RuntimeWarning: invalid value encountered in power
  return _a4_*(_a0_**tanh(_a5_*x1) + _a2_ + x1)

interpolation

<lambdifygenerated-4907>:2: RuntimeWarning: invalid value encountered in power
  return _a4_*(_a0_**tanh(_a5_*x1) + _a2_ + x1)

         x1         y  rep    ymodel      ybms
3745  0.997  0.825595  8.0  0.812878  0.799763
3746  0.998  0.825925  8.0  0.813204  0.799992
3747  0.998  0.826254  8.0  0.813529  0.800222
3748  0.999  0.826582  8.0  0.813853  0.800450

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.827238  8.0  0.814501  0.800906
3751  1.002  0.827565  8.0  0.814825  0.801133
3752  1.002  0.827892  8.0  0.815147  0.801359
3753  1.003  0.828218  8.0  0.815470  0.801585

3750
interpolation

<lambdifygenerated-4921>:2: RuntimeWarning: invalid value encountered in power
  return sin(tanh(_a7_*x1**x1))
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-4922>:2: RuntimeWarning: invalid value encountered in power
  return sin(tanh(_a7_*x1**x1))

         x1         y  rep    ymodel      ybms
3745  0.997  0.855453  9.0  0.858870  0.840748
3746  0.998  0.855554  9.0  0.858959  0.840757
3747  0.998  0.855656  9.0  0.859049  0.840765
3748  0.999  0.855757  9.0  0.859138  0.840773

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.855960  9.0  0.859316  0.840789
3751  1.002  0.856062  9.0  0.859405  0.840797
3752  1.002  0.856163  9.0  0.859493  0.840805
3753  1.003  0.856265  9.0  0.859582  0.840813

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.987381  0.0  0.965228  0.973018
3746  0.998  0.987426  0.0  0.965196  0.973020
3747  0.998  0.987470  0.0  0.965163  0.973023
3748  0.999  0.987515  0.0  0.965130  0.973025

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.987604  0.0  0.965065  0.973031
3751  1.002  0.987648  0.0  0.965033  0.973033
3752  1.002  0.987692  0.0  0.965000  0.973036
3753  1.003  0.987737  0.0  0.964967  0.973038

3750
interpolation

/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(

         x1         y  rep    ymodel      ybms
3745  0.997  0.053138  1.0  0.051667  0.044964
3746  0.998  0.053057  1.0  0.051575  0.044735
3747  0.998  0.052975  1.0  0.051483  0.044506
3748  0.999  0.052894  1.0  0.051391  0.044276

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.052733  1.0  0.051209  0.043816
3751  1.002  0.052652  1.0  0.051117  0.043586
3752  1.002  0.052571  1.0  0.051027  0.043355
3753  1.003  0.052491  1.0  0.050936  0.043124

3750
interpolation

<lambdifygenerated-5033>:2: RuntimeWarning: invalid value encountered in log
  return x1*log(x1)
<lambdifygenerated-5034>:2: RuntimeWarning: invalid value encountered in log
  return x1*log(x1)
<lambdifygenerated-5037>:2: RuntimeWarning: invalid value encountered in log
  return x1*log(x1**3)
<lambdifygenerated-5038>:2: RuntimeWarning: invalid value encountered in log
  return x1*log(x1**3)
<lambdifygenerated-5039>:2: RuntimeWarning: invalid value encountered in log
  return x1*log(4*x1**3)
<lambdifygenerated-5040>:2: RuntimeWarning: invalid value encountered in log
  return x1*log(4*x1**3)
<lambdifygenerated-5041>:2: RuntimeWarning: invalid value encountered in log
  return x1*log(x1*(x1**2 + x1)**2)
<lambdifygenerated-5042>:2: RuntimeWarning: invalid value encountered in log
  return x1*log(x1*(x1**2 + x1)**2)
<lambdifygenerated-5043>:2: RuntimeWarning: invalid value encountered in log
  return x1*log(x1*(x1**4 + x1)**2)
<lambdifygenerated-5044>:2: RuntimeWarning: invalid value encountered in log
  return x1*log(x1*(x1**4 + x1)**2)
<lambdifygenerated-5045>:2: RuntimeWarning: invalid value encountered in log
  return x1*log(x1*(x1*cos(x1)**3 + x1)**2)
<lambdifygenerated-5046>:2: RuntimeWarning: invalid value encountered in log
  return x1*log(x1*(x1*cos(x1)**3 + x1)**2)
<lambdifygenerated-5047>:2: RuntimeWarning: invalid value encountered in log
  return x1*log(x1*(x1*cos(2*x1)**3 + x1)**2)
<lambdifygenerated-5048>:2: RuntimeWarning: invalid value encountered in log
  return x1*log(x1*(x1*cos(2*x1)**3 + x1)**2)
<lambdifygenerated-5049>:2: RuntimeWarning: invalid value encountered in log
  return x1*log(x1*(x1*cos(x1**2 + x1)**3 + x1)**2)
<lambdifygenerated-5050>:2: RuntimeWarning: invalid value encountered in log
  return x1*log(x1*(x1*cos(x1**2 + x1)**3 + x1)**2)
<lambdifygenerated-5051>:2: RuntimeWarning: invalid value encountered in log
  return x1*log(x1*(x1*cos(x1**2 + x1)**3 + x1)**2)
<lambdifygenerated-5052>:2: RuntimeWarning: invalid value encountered in log
  return x1*log(x1*(x1*cos(x1**2 + x1)**3 + x1)**2)
<lambdifygenerated-5053>:2: RuntimeWarning: invalid value encountered in log
  return x1*log(x1*(x1*cos(_a7_*x1 + x1)**3 + x1)**2)
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-5054>:2: RuntimeWarning: invalid value encountered in log
  return x1*log(x1*(x1*cos(_a7_*x1 + x1)**3 + x1)**2)
<lambdifygenerated-5055>:2: RuntimeWarning: invalid value encountered in log
  return x1*log(x1*(x1*cos(_a6_ + _a7_*x1)**3 + x1)**2)
<lambdifygenerated-5056>:2: RuntimeWarning: invalid value encountered in log
  return x1*log(x1*(x1*cos(_a6_ + _a7_*x1)**3 + x1)**2)
<lambdifygenerated-5057>:2: RuntimeWarning: invalid value encountered in log
  return x1*log(x1*(_a0_*cos(_a6_ + _a7_*x1)**3 + x1)**2)
<lambdifygenerated-5058>:2: RuntimeWarning: invalid value encountered in log
  return x1*log(x1*(_a0_*cos(_a6_ + _a7_*x1)**3 + x1)**2)
<lambdifygenerated-5059>:2: RuntimeWarning: invalid value encountered in log
  return x1*log(x1*(_a0_*cos(_a6_ + _a7_*x1)**3 + _a2_)**2)
<lambdifygenerated-5060>:2: RuntimeWarning: invalid value encountered in log
  return x1*log(x1*(_a0_*cos(_a6_ + _a7_*x1)**3 + _a2_)**2)
<lambdifygenerated-5061>:2: RuntimeWarning: invalid value encountered in log
  return x1*log(_a6_*(_a0_*cos(_a6_ + _a7_*x1)**3 + _a2_)**2)

         x1         y  rep    ymodel      ybms
3745  0.997  0.277484  2.0  0.303488  0.318558
3746  0.998  0.277627  2.0  0.303921  0.319068
3747  0.998  0.277770  2.0  0.304353  0.319578
3748  0.999  0.277912  2.0  0.304784  0.320087

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.278193  2.0  0.305644  0.321103
3751  1.002  0.278333  2.0  0.306073  0.321610
3752  1.002  0.278471  2.0  0.306502  0.322116
3753  1.003  0.278610  2.0  0.306929  0.322622

3750
interpolation

<lambdifygenerated-5073>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1
<lambdifygenerated-5074>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1

         x1         y  rep    ymodel      ybms
3745  0.997  0.306760  3.0  0.308872  0.328709
3746  0.998  0.307033  3.0  0.309193  0.329314
3747  0.998  0.307306  3.0  0.309513  0.329920
3748  0.999  0.307578  3.0  0.309833  0.330527

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.308120  3.0  0.310472  0.331743
3751  1.002  0.308390  3.0  0.310790  0.332353
3752  1.002  0.308660  3.0  0.311108  0.332963
3753  1.003  0.308928  3.0  0.311426  0.333573

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.965360  4.0  0.979332  0.951632
3746  0.998  0.965399  4.0  0.979383  0.951632
3747  0.998  0.965439  4.0  0.979433  0.951632
3748  0.999  0.965479  4.0  0.979484  0.951632

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.965559  4.0  0.979585  0.951632
3751  1.002  0.965598  4.0  0.979635  0.951632
3752  1.002  0.965638  4.0  0.979685  0.951632
3753  1.003  0.965678  4.0  0.979736  0.951632

3750

<lambdifygenerated-5133>:2: RuntimeWarning: invalid value encountered in power
  return x1*(-_a1_ - tanh(x1 + x1**x1))
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-5134>:2: RuntimeWarning: invalid value encountered in power
  return x1*(-_a1_ - tanh(x1 + x1**x1))
<lambdifygenerated-5135>:2: RuntimeWarning: invalid value encountered in power
  return x1*(-_a1_ - tanh(_a0_**x1 + x1))
<lambdifygenerated-5135>:2: RuntimeWarning: overflow encountered in power
  return x1*(-_a1_ - tanh(_a0_**x1 + x1))
<lambdifygenerated-5136>:2: RuntimeWarning: overflow encountered in power
  return x1*(-_a1_ - tanh(_a0_**x1 + x1))
<lambdifygenerated-5137>:2: RuntimeWarning: overflow encountered in power
  return x1*(-_a1_ - tanh(_a0_**x1 + x1))
<lambdifygenerated-5138>:2: RuntimeWarning: overflow encountered in power
  return x1*(-_a1_ - tanh(_a0_**x1 + x1))
<lambdifygenerated-5139>:2: RuntimeWarning: overflow encountered in power
  return x1*(-_a1_ - tanh(_a0_**x1 + _a6_))
<lambdifygenerated-5139>:2: RuntimeWarning: invalid value encountered in power
  return x1*(-_a1_ - tanh(_a0_**x1 + _a6_))
<lambdifygenerated-5140>:2: RuntimeWarning: overflow encountered in power
  return x1*(-_a1_ - tanh(_a0_**x1 + _a6_))
<lambdifygenerated-5141>:2: RuntimeWarning: overflow encountered in power
  return _a3_*(-_a1_ - tanh(_a0_**x1 + _a6_))
<lambdifygenerated-5141>:2: RuntimeWarning: invalid value encountered in power
  return _a3_*(-_a1_ - tanh(_a0_**x1 + _a6_))

interpolation

<lambdifygenerated-5142>:2: RuntimeWarning: overflow encountered in power
  return _a3_*(-_a1_ - tanh(_a0_**x1 + _a6_))
<lambdifygenerated-5143>:2: RuntimeWarning: overflow encountered in power
  return _a3_*(-_a1_ - tanh(_a0_**x1 + _a6_))
<lambdifygenerated-5144>:2: RuntimeWarning: overflow encountered in power
  return _a3_*(-_a1_ - tanh(_a0_**x1 + _a6_))
<lambdifygenerated-5145>:2: RuntimeWarning: overflow encountered in power
  return _a3_*(-_a1_ - tanh(_a0_**x1 + _a6_))
<lambdifygenerated-5146>:2: RuntimeWarning: overflow encountered in power
  return _a3_*(-_a1_ - tanh(_a0_**x1 + _a6_))

         x1         y  rep    ymodel      ybms
3745  0.997  0.308339  5.0  0.303243  0.295486
3746  0.998  0.308354  5.0  0.303292  0.295486
3747  0.998  0.308368  5.0  0.303342  0.295486
3748  0.999  0.308382  5.0  0.303391  0.295486

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.308407  5.0  0.303491  0.295486
3751  1.002  0.308419  5.0  0.303541  0.295486
3752  1.002  0.308430  5.0  0.303590  0.295486
3753  1.003  0.308441  5.0  0.303640  0.295486

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.215897  6.0  0.208974  0.212207
3746  0.998  0.216041  6.0  0.209116  0.212381
3747  0.998  0.216186  6.0  0.209258  0.212556
3748  0.999  0.216330  6.0  0.209399  0.212731

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.216618  6.0  0.209682  0.213081
3751  1.002  0.216762  6.0  0.209824  0.213255
3752  1.002  0.216905  6.0  0.209965  0.213430
3753  1.003  0.217048  6.0  0.210106  0.213605

3750

<lambdifygenerated-5205>:2: RuntimeWarning: invalid value encountered in power
  return x1**2*exp(2*x1*(2*x1 + x1**x1))
<lambdifygenerated-5206>:2: RuntimeWarning: invalid value encountered in power
  return x1**2*exp(2*x1*(2*x1 + x1**x1))
<lambdifygenerated-5207>:2: RuntimeWarning: invalid value encountered in power
  return x1**2*exp(2*x1*(_a3_**x1 + 2*x1))
<lambdifygenerated-5211>:2: RuntimeWarning: invalid value encountered in power
  return x1**2*exp(2*x1*(_a1_ + _a3_**x1 + x1))
<lambdifygenerated-5215>:2: RuntimeWarning: invalid value encountered in power
  return _a7_**2*exp(2*x1*(_a1_ + _a3_**x1 + x1))
<lambdifygenerated-5219>:2: RuntimeWarning: invalid value encountered in power
  return _a7_**2*exp(2*x1*(_a1_ + _a3_**x1 + x1))

interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.100918  7.0  0.094199  0.101919
3746  0.998  0.100912  7.0  0.094178  0.101957
3747  0.998  0.100906  7.0  0.094157  0.101995
3748  0.999  0.100901  7.0  0.094136  0.102033

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.100890  7.0  0.094094  0.102110
3751  1.002  0.100885  7.0  0.094074  0.102149
3752  1.002  0.100880  7.0  0.094053  0.102188
3753  1.003  0.100874  7.0  0.094032  0.102227

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.825595  8.0  0.832673  0.822337
3746  0.998  0.825925  8.0  0.833030  0.822594
3747  0.998  0.826254  8.0  0.833387  0.822850
3748  0.999  0.826582  8.0  0.833742  0.823106

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.827238  8.0  0.834452  0.823614
3751  1.002  0.827565  8.0  0.834806  0.823867
3752  1.002  0.827892  8.0  0.835160  0.824119
3753  1.003  0.828218  8.0  0.835513  0.824371

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.855453  9.0  0.853419  0.861487
3746  0.998  0.855554  9.0  0.853514  0.861584
3747  0.998  0.855656  9.0  0.853609  0.861680
3748  0.999  0.855757  9.0  0.853703  0.861777

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.855960  9.0  0.853892  0.861969
3751  1.002  0.856062  9.0  0.853986  0.862065
3752  1.002  0.856163  9.0  0.854080  0.862160
3753  1.003  0.856265  9.0  0.854174  0.862255

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.987381  0.0  0.985157  0.999653
3746  0.998  0.987426  0.0  0.985123  0.999657
3747  0.998  0.987470  0.0  0.985089  0.999661
3748  0.999  0.987515  0.0  0.985055  0.999666

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.987604  0.0  0.984987  0.999674
3751  1.002  0.987648  0.0  0.984953  0.999679
3752  1.002  0.987692  0.0  0.984919  0.999683
3753  1.003  0.987737  0.0  0.984884  0.999687

3750

<lambdifygenerated-5347>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1*(x1 + x1**x1) + (_a6_ - x1 - cos(_a7_*x1))**2)
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-5348>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1*(x1 + x1**x1) + (_a6_ - x1 - cos(_a7_*x1))**2)
<lambdifygenerated-5349>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1*(_a5_**x1 + x1) + (_a6_ - x1 - cos(_a7_*x1))**2)

interpolation

<lambdifygenerated-5357>:2: RuntimeWarning: invalid value encountered in power
  return _a0_*(_a3_*(_a4_ + _a5_**x1) + (_a6_ - x1 - cos(_a7_*x1))**2)

         x1         y  rep    ymodel      ybms
3745  0.997  0.053138  1.0  0.052254  0.067087
3746  0.998  0.053057  1.0  0.052263  0.067273
3747  0.998  0.052975  1.0  0.052272  0.067461
3748  0.999  0.052894  1.0  0.052282  0.067650

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.052733  1.0  0.052302  0.068033
3751  1.002  0.052652  1.0  0.052313  0.068226
3752  1.002  0.052571  1.0  0.052325  0.068422
3753  1.003  0.052491  1.0  0.052336  0.068618

3750

<lambdifygenerated-5373>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1 - x1**x1)
<lambdifygenerated-5374>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1 - x1**x1)
<lambdifygenerated-5375>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1 - (2*x1)**x1)
<lambdifygenerated-5376>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1 - (2*x1)**x1)
<lambdifygenerated-5377>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1 - (x1**3 + x1)**x1)
<lambdifygenerated-5378>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1 - (x1**3 + x1)**x1)
<lambdifygenerated-5379>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1 - (x1 + cos(x1)**3)**x1)
<lambdifygenerated-5380>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1 - (x1 + cos(x1)**3)**x1)
<lambdifygenerated-5381>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1 - (x1 + cos(2*x1)**3)**x1)
<lambdifygenerated-5382>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1 - (x1 + cos(2*x1)**3)**x1)
<lambdifygenerated-5383>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1 - (x1 + cos(_a5_ + x1)**3)**x1)
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-5384>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1 - (x1 + cos(_a5_ + x1)**3)**x1)
<lambdifygenerated-5385>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1 - (x1 + cos(_a5_ + x1**2)**3)**x1)
<lambdifygenerated-5386>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1 - (x1 + cos(_a5_ + x1**2)**3)**x1)
<lambdifygenerated-5387>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1 - (x1 + cos(_a4_*x1 + _a5_)**3)**x1)
<lambdifygenerated-5388>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1 - (x1 + cos(_a4_*x1 + _a5_)**3)**x1)
<lambdifygenerated-5389>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1 - (x1 + cos(_a4_*x1 + _a5_)**3)**x1)
<lambdifygenerated-5390>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1 - (x1 + cos(_a4_*x1 + _a5_)**3)**x1)
<lambdifygenerated-5391>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1 - (_a4_ + cos(_a4_*x1 + _a5_)**3)**x1)

interpolation

<lambdifygenerated-5397>:2: RuntimeWarning: invalid value encountered in power
  return _a2_*(_a3_ - (_a4_ + cos(_a4_*x1 + _a5_)**3)**_a3_)

         x1         y  rep    ymodel      ybms
3745  0.997  0.277484  2.0  0.287504  0.305616
3746  0.998  0.277627  2.0  0.287882  0.306103
3747  0.998  0.277770  2.0  0.288259  0.306590
3748  0.999  0.277912  2.0  0.288636  0.307077

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.278193  2.0  0.289387  0.308049
3751  1.002  0.278333  2.0  0.289761  0.308534
3752  1.002  0.278471  2.0  0.290135  0.309019
3753  1.003  0.278610  2.0  0.290508  0.309503

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.306760  3.0  0.318261  0.362495
3746  0.998  0.307033  3.0  0.318639  0.363276
3747  0.998  0.307306  3.0  0.319017  0.364059
3748  0.999  0.307578  3.0  0.319394  0.364843

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.308120  3.0  0.320148  0.366415
3751  1.002  0.308390  3.0  0.320524  0.367202
3752  1.002  0.308660  3.0  0.320900  0.367991
3753  1.003  0.308928  3.0  0.321276  0.368782

3750
interpolation

<lambdifygenerated-5437>:2: RuntimeWarning: invalid value encountered in power
  return _a1_/(_a2_ + x1**x1)
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-5438>:2: RuntimeWarning: invalid value encountered in power
  return _a1_/(_a2_ + x1**x1)
<lambdifygenerated-5439>:2: RuntimeWarning: invalid value encountered in power
  return _a1_/(_a2_ + _a6_**x1)

         x1         y  rep    ymodel      ybms
3745  0.997  0.965360  4.0  0.970841  0.945124
3746  0.998  0.965399  4.0  0.970975  0.945124
3747  0.998  0.965439  4.0  0.971109  0.945124
3748  0.999  0.965479  4.0  0.971243  0.945124

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.965559  4.0  0.971511  0.945124
3751  1.002  0.965598  4.0  0.971645  0.945124
3752  1.002  0.965638  4.0  0.971779  0.945124
3753  1.003  0.965678  4.0  0.971913  0.945124

3750
interpolation

<lambdifygenerated-5455>:2: RuntimeWarning: invalid value encountered in power
  return x1*x1**x1 + x1
<lambdifygenerated-5456>:2: RuntimeWarning: invalid value encountered in power
  return x1*x1**x1 + x1
<lambdifygenerated-5459>:2: RuntimeWarning: invalid value encountered in power
  return _a3_**(x1**x1)*x1 + x1
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-5460>:2: RuntimeWarning: invalid value encountered in power
  return _a3_**(x1**x1)*x1 + x1
<lambdifygenerated-5461>:2: RuntimeWarning: invalid value encountered in power
  return _a3_**(_a6_**x1)*x1 + x1

         x1         y  rep    ymodel      ybms
3745  0.997  0.308339  5.0  0.299479  0.293434
3746  0.998  0.308354  5.0  0.299548  0.293434
3747  0.998  0.308368  5.0  0.299617  0.293434
3748  0.999  0.308382  5.0  0.299686  0.293434

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.308407  5.0  0.299825  0.293434
3751  1.002  0.308419  5.0  0.299894  0.293434
3752  1.002  0.308430  5.0  0.299963  0.293434
3753  1.003  0.308441  5.0  0.300033  0.293434

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.215897  6.0  0.209869  0.171119
3746  0.998  0.216041  6.0  0.209984  0.170855
3747  0.998  0.216186  6.0  0.210099  0.170589
3748  0.999  0.216330  6.0  0.210214  0.170322

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.216618  6.0  0.210444  0.169781
3751  1.002  0.216762  6.0  0.210558  0.169508
3752  1.002  0.216905  6.0  0.210673  0.169233
3753  1.003  0.217048  6.0  0.210787  0.168956

3750
interpolation

/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-5523>:2: RuntimeWarning: invalid value encountered in power
  return _a7_**2*x1**(-x1)
<lambdifygenerated-5524>:2: RuntimeWarning: invalid value encountered in power
  return _a7_**2*x1**(-x1)
<lambdifygenerated-5525>:2: RuntimeWarning: invalid value encountered in power
  return _a7_**2*_a7_**(-x1)
<lambdifygenerated-5526>:2: RuntimeWarning: invalid value encountered in power
  return _a7_**2*_a7_**(-x1)
<lambdifygenerated-5527>:2: RuntimeWarning: invalid value encountered in power
  return _a7_**2*_a7_**(-x1**2)
<lambdifygenerated-5528>:2: RuntimeWarning: invalid value encountered in power
  return _a7_**2*_a7_**(-x1**2)
<lambdifygenerated-5529>:2: RuntimeWarning: invalid value encountered in power
  return _a7_**2*_a7_**(x1**2)
<lambdifygenerated-5530>:2: RuntimeWarning: invalid value encountered in power
  return _a7_**2*_a7_**(x1**2)
<lambdifygenerated-5531>:2: RuntimeWarning: invalid value encountered in power
  return _a7_**2*_a7_**(4*x1**2)
<lambdifygenerated-5532>:2: RuntimeWarning: invalid value encountered in power
  return _a7_**2*_a7_**(4*x1**2)
<lambdifygenerated-5533>:2: RuntimeWarning: invalid value encountered in power
  return _a7_**2*_a7_**((x1**2 + x1)**2)
<lambdifygenerated-5534>:2: RuntimeWarning: invalid value encountered in power
  return _a7_**2*_a7_**((x1**2 + x1)**2)
<lambdifygenerated-5535>:2: RuntimeWarning: invalid value encountered in power
  return _a7_**2*_a7_**((x1**2 + x1)**2)
<lambdifygenerated-5536>:2: RuntimeWarning: invalid value encountered in power
  return _a7_**2*_a7_**((x1**2 + x1)**2)
<lambdifygenerated-5537>:2: RuntimeWarning: invalid value encountered in power
  return _a7_**2*_a7_**((2*x1**2 + x1)**2)
<lambdifygenerated-5538>:2: RuntimeWarning: invalid value encountered in power
  return _a7_**2*_a7_**((2*x1**2 + x1)**2)
<lambdifygenerated-5539>:2: RuntimeWarning: invalid value encountered in power
  return _a7_**2*_a7_**((x1*(_a6_ + x1) + x1)**2)
<lambdifygenerated-5540>:2: RuntimeWarning: invalid value encountered in power
  return _a7_**2*_a7_**((x1*(_a6_ + x1) + x1)**2)
<lambdifygenerated-5541>:2: RuntimeWarning: invalid value encountered in power
  return _a7_**2*_a7_**((x1*(_a6_ + x1) + x1)**2)
<lambdifygenerated-5542>:2: RuntimeWarning: invalid value encountered in power
  return _a7_**2*_a7_**((x1*(_a6_ + x1) + x1)**2)
<lambdifygenerated-5543>:2: RuntimeWarning: invalid value encountered in power
  return _a7_**2*_a7_**((_a3_ + x1*(_a6_ + x1))**2)
<lambdifygenerated-5544>:2: RuntimeWarning: invalid value encountered in power
  return _a7_**2*_a7_**((_a3_ + x1*(_a6_ + x1))**2)
<lambdifygenerated-5545>:2: RuntimeWarning: invalid value encountered in power
  return _a7_**2*_a7_**((_a3_ + x1*(_a6_ + x1))**2)
<lambdifygenerated-5546>:2: RuntimeWarning: invalid value encountered in power
  return _a7_**2*_a7_**((_a3_ + x1*(_a6_ + x1))**2)
<lambdifygenerated-5547>:2: RuntimeWarning: invalid value encountered in power
  return _a7_**2*_a7_**((_a3_ + x1*(_a6_ + x1))**2)
<lambdifygenerated-5548>:2: RuntimeWarning: invalid value encountered in power
  return _a7_**2*_a7_**((_a3_ + x1*(_a6_ + x1))**2)

         x1         y  rep    ymodel      ybms
3745  0.997  0.100918  7.0  0.106718  0.097881
3746  0.998  0.100912  7.0  0.106732  0.097917
3747  0.998  0.100906  7.0  0.106745  0.097953
3748  0.999  0.100901  7.0  0.106759  0.097990

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.100890  7.0  0.106787  0.098064
3751  1.002  0.100885  7.0  0.106800  0.098102
3752  1.002  0.100880  7.0  0.106814  0.098139
3753  1.003  0.100874  7.0  0.106828  0.098177

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.825595  8.0  0.822055  0.859884
3746  0.998  0.825925  8.0  0.822405  0.860489
3747  0.998  0.826254  8.0  0.822755  0.861094
3748  0.999  0.826582  8.0  0.823104  0.861699

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.827238  8.0  0.823801  0.862910
3751  1.002  0.827565  8.0  0.824149  0.863515
3752  1.002  0.827892  8.0  0.824496  0.864120
3753  1.003  0.828218  8.0  0.824843  0.864725

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.855453  9.0  0.851221  0.858716
3746  0.998  0.855554  9.0  0.851319  0.858802
3747  0.998  0.855656  9.0  0.851417  0.858887
3748  0.999  0.855757  9.0  0.851515  0.858972

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.855960  9.0  0.851710  0.859141
3751  1.002  0.856062  9.0  0.851808  0.859226
3752  1.002  0.856163  9.0  0.851905  0.859310
3753  1.003  0.856265  9.0  0.852002  0.859394

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.987381  0.0  0.993989  0.999972
3746  0.998  0.987426  0.0  0.994001  0.999972
3747  0.998  0.987470  0.0  0.994014  0.999973
3748  0.999  0.987515  0.0  0.994026  0.999974

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.987604  0.0  0.994051  0.999975
3751  1.002  0.987648  0.0  0.994063  0.999976
3752  1.002  0.987692  0.0  0.994075  0.999977
3753  1.003  0.987737  0.0  0.994087  0.999977

3750

/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-5665>:2: RuntimeWarning: invalid value encountered in power
  return x1*x1**x1*(_a6_ + cos(_a0_*(_a0_ + tanh(x1/_a3_))))
<lambdifygenerated-5666>:2: RuntimeWarning: invalid value encountered in power
  return x1*x1**x1*(_a6_ + cos(_a0_*(_a0_ + tanh(x1/_a3_))))
<lambdifygenerated-5669>:2: RuntimeWarning: invalid value encountered in power
  return _a3_**(x1**2)*x1*(_a6_ + cos(_a0_*(_a0_ + tanh(x1/_a3_))))

interpolation

<lambdifygenerated-5673>:2: RuntimeWarning: invalid value encountered in power
  return _a3_**(_a6_*x1)*x1*(_a6_ + cos(_a0_*(_a0_ + tanh(x1/_a3_))))
<lambdifygenerated-5675>:2: RuntimeWarning: invalid value encountered in power
  return _a3_**(_a6_*x1)*_a5_*(_a6_ + cos(_a0_*(_a0_ + tanh(x1/_a3_))))
<lambdifygenerated-5679>:2: RuntimeWarning: overflow encountered in power
  return _a3_**(_a6_*x1)*_a5_*(_a6_ + cos(_a0_*(_a0_ + tanh(x1/_a3_))))
<lambdifygenerated-5679>:2: RuntimeWarning: overflow encountered in multiply
  return _a3_**(_a6_*x1)*_a5_*(_a6_ + cos(_a0_*(_a0_ + tanh(x1/_a3_))))

         x1         y  rep    ymodel      ybms
3745  0.997  0.053138  1.0  0.045405  0.064089
3746  0.998  0.053057  1.0  0.045286  0.064022
3747  0.998  0.052975  1.0  0.045167  0.063956
3748  0.999  0.052894  1.0  0.045048  0.063890

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.052733  1.0  0.044810  0.063758
3751  1.002  0.052652  1.0  0.044692  0.063693
3752  1.002  0.052571  1.0  0.044573  0.063627
3753  1.003  0.052491  1.0  0.044455  0.063562

3750

<lambdifygenerated-5689>:2: RuntimeWarning: invalid value encountered in power
  return (x1 + x1**x1)**2
<lambdifygenerated-5690>:2: RuntimeWarning: invalid value encountered in power
  return (x1 + x1**x1)**2
<lambdifygenerated-5693>:2: RuntimeWarning: invalid value encountered in power
  return (x1 + x1**x1)**2
<lambdifygenerated-5694>:2: RuntimeWarning: invalid value encountered in power
  return (x1 + x1**x1)**2
<lambdifygenerated-5695>:2: RuntimeWarning: invalid value encountered in power
  return (x1 + (tanh(x1)**2/x1)**x1)**2
<lambdifygenerated-5696>:2: RuntimeWarning: invalid value encountered in power
  return (x1 + (tanh(x1)**2/x1)**x1)**2
<lambdifygenerated-5697>:2: RuntimeWarning: invalid value encountered in power
  return (x1 + (tanh(2*x1)**2/x1)**x1)**2
<lambdifygenerated-5698>:2: RuntimeWarning: invalid value encountered in power
  return (x1 + (tanh(2*x1)**2/x1)**x1)**2
<lambdifygenerated-5699>:2: RuntimeWarning: invalid value encountered in power
  return (x1 + (tanh(2*x1)**2/x1)**x1)**2
<lambdifygenerated-5700>:2: RuntimeWarning: invalid value encountered in power
  return (x1 + (tanh(2*x1)**2/x1)**x1)**2
<lambdifygenerated-5701>:2: RuntimeWarning: invalid value encountered in power
  return (x1 + (tanh(_a6_ + x1)**2/x1)**x1)**2
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-5702>:2: RuntimeWarning: invalid value encountered in power
  return (x1 + (tanh(_a6_ + x1)**2/x1)**x1)**2

interpolation

<lambdifygenerated-5713>:2: RuntimeWarning: invalid value encountered in power
  return (-_a5_ + (tanh(_a6_ + x1)**2/_a3_)**(_a2_ + x1))**2

         x1         y  rep    ymodel      ybms
3745  0.997  0.277484  2.0  0.299598  0.283094
3746  0.998  0.277627  2.0  0.299939  0.283072
3747  0.998  0.277770  2.0  0.300278  0.283047
3748  0.999  0.277912  2.0  0.300617  0.283021

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.278193  2.0  0.301293  0.282962
3751  1.002  0.278333  2.0  0.301629  0.282929
3752  1.002  0.278471  2.0  0.301965  0.282896
3753  1.003  0.278610  2.0  0.302300  0.282860

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.306760  3.0  0.312472  0.341073
3746  0.998  0.307033  3.0  0.312698  0.341660
3747  0.998  0.307306  3.0  0.312923  0.342248
3748  0.999  0.307578  3.0  0.313148  0.342836

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.308120  3.0  0.313595  0.344015
3751  1.002  0.308390  3.0  0.313818  0.344605
3752  1.002  0.308660  3.0  0.314040  0.345196
3753  1.003  0.308928  3.0  0.314262  0.345787

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.965360  4.0  0.967411  0.949436
3746  0.998  0.965399  4.0  0.967460  0.949436
3747  0.998  0.965439  4.0  0.967509  0.949436
3748  0.999  0.965479  4.0  0.967557  0.949436

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.965559  4.0  0.967654  0.949436
3751  1.002  0.965598  4.0  0.967702  0.949436
3752  1.002  0.965638  4.0  0.967750  0.949436
3753  1.003  0.965678  4.0  0.967798  0.949436

3750
interpolation

<lambdifygenerated-5775>:2: RuntimeWarning: invalid value encountered in power
  return x1 + x1**x1
<lambdifygenerated-5776>:2: RuntimeWarning: invalid value encountered in power
  return x1 + x1**x1
<lambdifygenerated-5777>:2: RuntimeWarning: invalid value encountered in power
  return _a4_**x1 + x1
<lambdifygenerated-5783>:2: RuntimeWarning: invalid value encountered in power
  return _a4_**(_a2_*x1 + x1) + x1
<lambdifygenerated-5785>:2: RuntimeWarning: invalid value encountered in power
  return _a4_**(_a2_*x1**x1 + x1) + x1
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-5786>:2: RuntimeWarning: invalid value encountered in power
  return _a4_**(_a2_*x1**x1 + x1) + x1
<lambdifygenerated-5787>:2: RuntimeWarning: invalid value encountered in power
  return _a4_**(_a2_*_a2_**x1 + x1) + x1
<lambdifygenerated-5788>:2: RuntimeWarning: invalid value encountered in power
  return _a4_**(_a2_*_a2_**x1 + x1) + x1
<lambdifygenerated-5789>:2: RuntimeWarning: invalid value encountered in power
  return _a4_**(_a2_*_a2_**x1 + x1) + x1
<lambdifygenerated-5790>:2: RuntimeWarning: invalid value encountered in power
  return _a4_**(_a2_*_a2_**x1 + x1) + x1
<lambdifygenerated-5791>:2: RuntimeWarning: invalid value encountered in power
  return _a4_**(_a2_*_a2_**x1 + _a2_) + x1
<lambdifygenerated-5792>:2: RuntimeWarning: invalid value encountered in power
  return _a4_**(_a2_*_a2_**x1 + _a2_) + x1
<lambdifygenerated-5793>:2: RuntimeWarning: invalid value encountered in power
  return _a4_**(_a2_*_a2_**x1 + _a2_) + _a7_
<lambdifygenerated-5794>:2: RuntimeWarning: invalid value encountered in power
  return _a4_**(_a2_*_a2_**x1 + _a2_) + _a7_
<lambdifygenerated-5795>:2: RuntimeWarning: invalid value encountered in power
  return _a4_**(_a2_*_a2_**x1 + _a2_) + _a7_
<lambdifygenerated-5796>:2: RuntimeWarning: invalid value encountered in power
  return _a4_**(_a2_*_a2_**x1 + _a2_) + _a7_
<lambdifygenerated-5797>:2: RuntimeWarning: invalid value encountered in power
  return _a4_**(_a2_*_a2_**x1 + _a2_) + _a7_
<lambdifygenerated-5798>:2: RuntimeWarning: invalid value encountered in power
  return _a4_**(_a2_*_a2_**x1 + _a2_) + _a7_

         x1         y  rep    ymodel     ybms
3745  0.997  0.308339  5.0  0.317353  0.29009
3746  0.998  0.308354  5.0  0.317481  0.29009
3747  0.998  0.308368  5.0  0.317610  0.29009
3748  0.999  0.308382  5.0  0.317738  0.29009

extrapolation

         x1         y  rep    ymodel     ybms
3750  1.001  0.308407  5.0  0.317995  0.29009
3751  1.002  0.308419  5.0  0.318123  0.29009
3752  1.002  0.308430  5.0  0.318251  0.29009
3753  1.003  0.308441  5.0  0.318380  0.29009

3750
interpolation

<lambdifygenerated-5817>:2: RuntimeWarning: invalid value encountered in power
  return tanh(2*x1 + cos(_a6_ + x1*x1**x1))
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-5818>:2: RuntimeWarning: invalid value encountered in power
  return tanh(2*x1 + cos(_a6_ + x1*x1**x1))
<lambdifygenerated-5819>:2: RuntimeWarning: invalid value encountered in power
  return tanh(2*x1 + cos(_a6_ + _a6_**x1*x1))
<lambdifygenerated-5820>:2: RuntimeWarning: invalid value encountered in power
  return tanh(2*x1 + cos(_a6_ + _a6_**x1*x1))
<lambdifygenerated-5821>:2: RuntimeWarning: invalid value encountered in power
  return tanh(2*x1 + cos(_a6_ + _a6_**x1*x1))
<lambdifygenerated-5822>:2: RuntimeWarning: invalid value encountered in power
  return tanh(2*x1 + cos(_a6_ + _a6_**x1*x1))
<lambdifygenerated-5823>:2: RuntimeWarning: invalid value encountered in power
  return tanh(2*x1 + cos(_a6_ + _a6_**x1*_a7_))
<lambdifygenerated-5824>:2: RuntimeWarning: invalid value encountered in power
  return tanh(2*x1 + cos(_a6_ + _a6_**x1*_a7_))
<lambdifygenerated-5825>:2: RuntimeWarning: invalid value encountered in power
  return tanh(x1**2 + x1 + cos(_a6_ + _a6_**x1*_a7_))
<lambdifygenerated-5826>:2: RuntimeWarning: invalid value encountered in power
  return tanh(x1**2 + x1 + cos(_a6_ + _a6_**x1*_a7_))
<lambdifygenerated-5827>:2: RuntimeWarning: invalid value encountered in power
  return tanh(_a0_*x1 + x1 + cos(_a6_ + _a6_**x1*_a7_))
<lambdifygenerated-5828>:2: RuntimeWarning: invalid value encountered in power
  return tanh(_a0_*x1 + x1 + cos(_a6_ + _a6_**x1*_a7_))
<lambdifygenerated-5829>:2: RuntimeWarning: invalid value encountered in power
  return tanh(_a0_*x1 + x1 + cos(_a6_ + _a6_**x1*_a7_))
<lambdifygenerated-5830>:2: RuntimeWarning: invalid value encountered in power
  return tanh(_a0_*x1 + x1 + cos(_a6_ + _a6_**x1*_a7_))
<lambdifygenerated-5831>:2: RuntimeWarning: invalid value encountered in power
  return tanh(_a0_*x1 + _a1_ + cos(_a6_ + _a6_**x1*_a7_))
<lambdifygenerated-5832>:2: RuntimeWarning: invalid value encountered in power
  return tanh(_a0_*x1 + _a1_ + cos(_a6_ + _a6_**x1*_a7_))
<lambdifygenerated-5833>:2: RuntimeWarning: invalid value encountered in power
  return tanh(_a0_*x1 + _a1_ + cos(_a6_ + _a6_**x1*_a7_))
<lambdifygenerated-5834>:2: RuntimeWarning: invalid value encountered in power
  return tanh(_a0_*x1 + _a1_ + cos(_a6_ + _a6_**x1*_a7_))
<lambdifygenerated-5835>:2: RuntimeWarning: invalid value encountered in power
  return tanh(_a0_*x1 + _a1_ + cos(_a6_ + _a6_**x1*_a7_))
<lambdifygenerated-5836>:2: RuntimeWarning: invalid value encountered in power
  return tanh(_a0_*x1 + _a1_ + cos(_a6_ + _a6_**x1*_a7_))

         x1         y  rep    ymodel      ybms
3745  0.997  0.215897  6.0  0.221668  0.206906
3746  0.998  0.216041  6.0  0.221817  0.206919
3747  0.998  0.216186  6.0  0.221967  0.206931
3748  0.999  0.216330  6.0  0.222116  0.206943

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.216618  6.0  0.222416  0.206964
3751  1.002  0.216762  6.0  0.222566  0.206974
3752  1.002  0.216905  6.0  0.222716  0.206984
3753  1.003  0.217048  6.0  0.222866  0.206992

3750
interpolation

<lambdifygenerated-5843>:2: RuntimeWarning: invalid value encountered in power
  return x1*x1**x1
<lambdifygenerated-5844>:2: RuntimeWarning: invalid value encountered in power
  return x1*x1**x1

         x1         y  rep    ymodel      ybms
3745  0.997  0.100918  7.0  0.103832  0.103731
3746  0.998  0.100912  7.0  0.103858  0.103853
3747  0.998  0.100906  7.0  0.103885  0.103975
3748  0.999  0.100901  7.0  0.103911  0.104098

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.100890  7.0  0.103964  0.104346
3751  1.002  0.100885  7.0  0.103991  0.104472
3752  1.002  0.100880  7.0  0.104018  0.104598
3753  1.003  0.100874  7.0  0.104044  0.104724

3750
interpolation

<lambdifygenerated-5877>:2: RuntimeWarning: invalid value encountered in power
  return x1 + x1**x1
<lambdifygenerated-5878>:2: RuntimeWarning: invalid value encountered in power
  return x1 + x1**x1
<lambdifygenerated-5887>:2: RuntimeWarning: invalid value encountered in power
  return _a0_**exp(_a5_*x1) + x1
<lambdifygenerated-5889>:2: RuntimeWarning: invalid value encountered in power
  return _a0_**exp(_a5_*x1) + x1**2
<lambdifygenerated-5891>:2: RuntimeWarning: overflow encountered in exp
  return _a0_**exp(_a5_*x1) + _a2_*x1
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-5892>:2: RuntimeWarning: overflow encountered in exp
  return _a0_**exp(_a5_*x1) + _a2_*x1
<lambdifygenerated-5893>:2: RuntimeWarning: overflow encountered in exp
  return _a0_**exp(_a5_*x1) + 2*_a2_*x1
<lambdifygenerated-5894>:2: RuntimeWarning: overflow encountered in exp
  return _a0_**exp(_a5_*x1) + 2*_a2_*x1
<lambdifygenerated-5895>:2: RuntimeWarning: overflow encountered in exp
  return _a0_**exp(_a5_*x1) + _a2_*(_a6_ + x1)
<lambdifygenerated-5896>:2: RuntimeWarning: overflow encountered in exp
  return _a0_**exp(_a5_*x1) + _a2_*(_a6_ + x1)
<lambdifygenerated-5897>:2: RuntimeWarning: overflow encountered in exp
  return _a0_**exp(_a5_*x1) + _a2_*(_a6_ + x1**3)
<lambdifygenerated-5898>:2: RuntimeWarning: overflow encountered in exp
  return _a0_**exp(_a5_*x1) + _a2_*(_a6_ + x1**3)
<lambdifygenerated-5899>:2: RuntimeWarning: overflow encountered in exp
  return _a0_**exp(_a5_*x1) + _a2_*(_a6_ + x1**3)
<lambdifygenerated-5900>:2: RuntimeWarning: overflow encountered in exp
  return _a0_**exp(_a5_*x1) + _a2_*(_a6_ + x1**3)
<lambdifygenerated-5901>:2: RuntimeWarning: overflow encountered in exp
  return _a0_**exp(_a5_*x1) + _a2_*(_a6_ + x1**3)
<lambdifygenerated-5902>:2: RuntimeWarning: overflow encountered in exp
  return _a0_**exp(_a5_*x1) + _a2_*(_a6_ + x1**3)
<lambdifygenerated-5903>:2: RuntimeWarning: overflow encountered in exp
  return _a0_**exp(_a5_*x1) + _a2_*(_a6_ + x1**3)
<lambdifygenerated-5904>:2: RuntimeWarning: overflow encountered in exp
  return _a0_**exp(_a5_*x1) + _a2_*(_a6_ + x1**3)

         x1         y  rep    ymodel      ybms
3745  0.997  0.825595  8.0  0.831066  0.851422
3746  0.998  0.825925  8.0  0.831430  0.851850
3747  0.998  0.826254  8.0  0.831793  0.852278
3748  0.999  0.826582  8.0  0.832156  0.852706

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.827238  8.0  0.832880  0.853559
3751  1.002  0.827565  8.0  0.833242  0.853985
3752  1.002  0.827892  8.0  0.833602  0.854410
3753  1.003  0.828218  8.0  0.833963  0.854835

3750
interpolation

<lambdifygenerated-5911>:2: RuntimeWarning: invalid value encountered in power
  return x1*x1**x1
<lambdifygenerated-5912>:2: RuntimeWarning: invalid value encountered in power
  return x1*x1**x1

         x1         y  rep    ymodel      ybms
3745  0.997  0.855453  9.0  0.837633  0.821712
3746  0.998  0.855554  9.0  0.837684  0.821585
3747  0.998  0.855656  9.0  0.837735  0.821458
3748  0.999  0.855757  9.0  0.837786  0.821330

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.855960  9.0  0.837888  0.821071
3751  1.002  0.856062  9.0  0.837939  0.820940
3752  1.002  0.856163  9.0  0.837990  0.820809
3753  1.003  0.856265  9.0  0.838040  0.820676

3750
interpolation

<lambdifygenerated-5939>:2: RuntimeWarning: invalid value encountered in power
  return sin(x1 + x1**x1)
<lambdifygenerated-5940>:2: RuntimeWarning: invalid value encountered in power
  return sin(x1 + x1**x1)
<lambdifygenerated-5941>:2: RuntimeWarning: invalid value encountered in power
  return sin(x1 + (2*x1)**x1)
<lambdifygenerated-5942>:2: RuntimeWarning: invalid value encountered in power
  return sin(x1 + (2*x1)**x1)
<lambdifygenerated-5943>:2: RuntimeWarning: invalid value encountered in power
  return sin(x1 + (x1**2 + x1)**x1)
<lambdifygenerated-5944>:2: RuntimeWarning: invalid value encountered in power
  return sin(x1 + (x1**2 + x1)**x1)
<lambdifygenerated-5945>:2: RuntimeWarning: invalid value encountered in power
  return sin(x1 + (4*x1**2 + x1)**x1)
<lambdifygenerated-5946>:2: RuntimeWarning: invalid value encountered in power
  return sin(x1 + (4*x1**2 + x1)**x1)
<lambdifygenerated-5947>:2: RuntimeWarning: invalid value encountered in power
  return sin(x1 + (x1 + (_a0_ + x1)**2)**x1)
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-5948>:2: RuntimeWarning: invalid value encountered in power
  return sin(x1 + (x1 + (_a0_ + x1)**2)**x1)
<lambdifygenerated-5949>:2: RuntimeWarning: invalid value encountered in power
  return sin(x1 + (x1 + (_a0_ + x1)**2)**x1)
<lambdifygenerated-5950>:2: RuntimeWarning: invalid value encountered in power
  return sin(x1 + (x1 + (_a0_ + x1)**2)**x1)
<lambdifygenerated-5965>:2: RuntimeWarning: invalid value encountered in power
  return sin(_a0_*sin(x1) + _a0_ + (_a5_ + (_a0_ + x1)**2)**(-_a2_))

         x1         y  rep    ymodel      ybms
3745  0.997  0.987381  0.0  0.984961  0.998245
3746  0.998  0.987426  0.0  0.984975  0.998266
3747  0.998  0.987470  0.0  0.984989  0.998286
3748  0.999  0.987515  0.0  0.985003  0.998307

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.987604  0.0  0.985031  0.998347
3751  1.002  0.987648  0.0  0.985045  0.998367
3752  1.002  0.987692  0.0  0.985059  0.998386
3753  1.003  0.987737  0.0  0.985072  0.998406

3750
interpolation

/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(

         x1         y  rep    ymodel      ybms
3745  0.997  0.053138  1.0  0.058087  0.092139
3746  0.998  0.053057  1.0  0.058033  0.092228
3747  0.998  0.052975  1.0  0.057979  0.092318
3748  0.999  0.052894  1.0  0.057925  0.092408

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.052733  1.0  0.057819  0.092588
3751  1.002  0.052652  1.0  0.057765  0.092679
3752  1.002  0.052571  1.0  0.057713  0.092770
3753  1.003  0.052491  1.0  0.057660  0.092862

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.277484  2.0  0.307143  0.269625
3746  0.998  0.277627  2.0  0.307561  0.269243
3747  0.998  0.277770  2.0  0.307977  0.268853
3748  0.999  0.277912  2.0  0.308393  0.268455

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.278193  2.0  0.309220  0.267634
3751  1.002  0.278333  2.0  0.309632  0.267211
3752  1.002  0.278471  2.0  0.310043  0.266780
3753  1.003  0.278610  2.0  0.310453  0.266340

3750
interpolation

<lambdifygenerated-6067>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1
<lambdifygenerated-6068>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1

         x1         y  rep    ymodel      ybms
3745  0.997  0.306760  3.0  0.288617  0.327481
3746  0.998  0.307033  3.0  0.288755  0.328063
3747  0.998  0.307306  3.0  0.288893  0.328646
3748  0.999  0.307578  3.0  0.289030  0.329229

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.308120  3.0  0.289301  0.330399
3751  1.002  0.308390  3.0  0.289436  0.330984
3752  1.002  0.308660  3.0  0.289571  0.331571
3753  1.003  0.308928  3.0  0.289704  0.332158

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.965360  4.0  0.939931  0.945651
3746  0.998  0.965399  4.0  0.939925  0.945651
3747  0.998  0.965439  4.0  0.939920  0.945651
3748  0.999  0.965479  4.0  0.939914  0.945651

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.965559  4.0  0.939902  0.945651
3751  1.002  0.965598  4.0  0.939896  0.945651
3752  1.002  0.965638  4.0  0.939890  0.945651
3753  1.003  0.965678  4.0  0.939885  0.945651

3750

<lambdifygenerated-6119>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1 + x1**x1)
<lambdifygenerated-6120>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1 + x1**x1)
<lambdifygenerated-6123>:2: RuntimeWarning: invalid value encountered in power
  return x1*(_a2_**(x1**x1) + x1)
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-6124>:2: RuntimeWarning: invalid value encountered in power
  return x1*(_a2_**(x1**x1) + x1)
<lambdifygenerated-6125>:2: RuntimeWarning: invalid value encountered in power
  return x1*(_a2_**(_a3_**x1) + x1)

interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.308339  5.0  0.292749  0.293702
3746  0.998  0.308354  5.0  0.292727  0.293702
3747  0.998  0.308368  5.0  0.292704  0.293702
3748  0.999  0.308382  5.0  0.292681  0.293702

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.308407  5.0  0.292636  0.293702
3751  1.002  0.308419  5.0  0.292614  0.293702
3752  1.002  0.308430  5.0  0.292591  0.293702
3753  1.003  0.308441  5.0  0.292569  0.293702

3750
interpolation

<lambdifygenerated-6153>:2: RuntimeWarning: invalid value encountered in power
  return -sin(_a1_/(x1*x1**x1 + x1))
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-6154>:2: RuntimeWarning: invalid value encountered in power
  return -sin(_a1_/(x1*x1**x1 + x1))

         x1         y  rep    ymodel      ybms
3745  0.997  0.215897  6.0  0.212518  0.266679
3746  0.998  0.216041  6.0  0.212556  0.267242
3747  0.998  0.216186  6.0  0.212595  0.267807
3748  0.999  0.216330  6.0  0.212633  0.268373

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.216618  6.0  0.212709  0.269509
3751  1.002  0.216762  6.0  0.212746  0.270080
3752  1.002  0.216905  6.0  0.212783  0.270652
3753  1.003  0.217048  6.0  0.212819  0.271225

3750
interpolation

<lambdifygenerated-6179>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1
<lambdifygenerated-6180>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1
<lambdifygenerated-6181>:2: RuntimeWarning: invalid value encountered in power
  return (2*x1)**x1
<lambdifygenerated-6182>:2: RuntimeWarning: invalid value encountered in power
  return (2*x1)**x1
<lambdifygenerated-6183>:2: RuntimeWarning: invalid value encountered in power
  return (x1**2 + x1)**x1
<lambdifygenerated-6184>:2: RuntimeWarning: invalid value encountered in power
  return (x1**2 + x1)**x1
<lambdifygenerated-6185>:2: RuntimeWarning: invalid value encountered in power
  return (4*x1**2 + x1)**x1
<lambdifygenerated-6186>:2: RuntimeWarning: invalid value encountered in power
  return (4*x1**2 + x1)**x1
<lambdifygenerated-6187>:2: RuntimeWarning: invalid value encountered in power
  return (x1 + (_a3_ + x1)**2)**x1
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-6188>:2: RuntimeWarning: invalid value encountered in power
  return (x1 + (_a3_ + x1)**2)**x1
<lambdifygenerated-6189>:2: RuntimeWarning: invalid value encountered in power
  return (x1 + (_a3_ + x1**x1)**2)**x1
<lambdifygenerated-6190>:2: RuntimeWarning: invalid value encountered in power
  return (x1 + (_a3_ + x1**x1)**2)**x1
<lambdifygenerated-6191>:2: RuntimeWarning: invalid value encountered in power
  return (x1 + (_a3_ + (2*x1)**x1)**2)**x1
<lambdifygenerated-6192>:2: RuntimeWarning: invalid value encountered in power
  return (x1 + (_a3_ + (2*x1)**x1)**2)**x1
<lambdifygenerated-6193>:2: RuntimeWarning: invalid value encountered in power
  return (x1 + (_a3_ + (_a3_ + x1)**x1)**2)**x1
<lambdifygenerated-6194>:2: RuntimeWarning: invalid value encountered in power
  return (x1 + (_a3_ + (_a3_ + x1)**x1)**2)**x1
<lambdifygenerated-6195>:2: RuntimeWarning: invalid value encountered in power
  return (x1 + (_a3_ + (_a3_ + _a5_)**x1)**2)**x1
<lambdifygenerated-6196>:2: RuntimeWarning: invalid value encountered in power
  return (x1 + (_a3_ + (_a3_ + _a5_)**x1)**2)**x1
<lambdifygenerated-6197>:2: RuntimeWarning: invalid value encountered in power
  return (x1 + (_a3_ + (_a3_ + _a5_)**x1)**2)**x1
<lambdifygenerated-6198>:2: RuntimeWarning: invalid value encountered in power
  return (x1 + (_a3_ + (_a3_ + _a5_)**x1)**2)**x1
<lambdifygenerated-6199>:2: RuntimeWarning: invalid value encountered in power
  return (_a5_ + (_a3_ + (_a3_ + _a5_)**x1)**2)**x1
<lambdifygenerated-6201>:2: RuntimeWarning: invalid value encountered in power
  return (_a5_ + (_a3_ + (_a3_ + _a5_)**x1)**2)**_a3_
<lambdifygenerated-6205>:2: RuntimeWarning: invalid value encountered in power
  return (_a5_ + (_a3_ + (_a3_ + _a5_)**x1)**2)**_a3_

         x1         y  rep    ymodel      ybms
3745  0.997  0.100918  7.0  0.109395  0.097464
3746  0.998  0.100912  7.0  0.109449  0.097431
3747  0.998  0.100906  7.0  0.109502  0.097398
3748  0.999  0.100901  7.0  0.109556  0.097365

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.100890  7.0  0.109665  0.097299
3751  1.002  0.100885  7.0  0.109720  0.097267
3752  1.002  0.100880  7.0  0.109775  0.097234
3753  1.003  0.100874  7.0  0.109830  0.097201

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.825595  8.0  0.832512  0.869321
3746  0.998  0.825925  8.0  0.832849  0.869927
3747  0.998  0.826254  8.0  0.833186  0.870533
3748  0.999  0.826582  8.0  0.833522  0.871139

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.827238  8.0  0.834193  0.872351
3751  1.002  0.827565  8.0  0.834527  0.872956
3752  1.002  0.827892  8.0  0.834861  0.873562
3753  1.003  0.828218  8.0  0.835194  0.874168

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.855453  9.0  0.853324  0.868231
3746  0.998  0.855554  9.0  0.853395  0.868327
3747  0.998  0.855656  9.0  0.853466  0.868423
3748  0.999  0.855757  9.0  0.853537  0.868519

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.855960  9.0  0.853678  0.868711
3751  1.002  0.856062  9.0  0.853749  0.868806
3752  1.002  0.856163  9.0  0.853819  0.868901
3753  1.003  0.856265  9.0  0.853889  0.868996

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.987381  0.0  0.984315  0.981396
3746  0.998  0.987426  0.0  0.984348  0.981412
3747  0.998  0.987470  0.0  0.984380  0.981428
3748  0.999  0.987515  0.0  0.984413  0.981443

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.987604  0.0  0.984477  0.981474
3751  1.002  0.987648  0.0  0.984510  0.981489
3752  1.002  0.987692  0.0  0.984542  0.981505
3753  1.003  0.987737  0.0  0.984574  0.981520

3750
interpolation

<lambdifygenerated-6299>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1
<lambdifygenerated-6300>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1
<lambdifygenerated-6301>:2: RuntimeWarning: invalid value encountered in power
  return (2*x1)**x1
<lambdifygenerated-6302>:2: RuntimeWarning: invalid value encountered in power
  return (2*x1)**x1
<lambdifygenerated-6303>:2: RuntimeWarning: invalid value encountered in power
  return (x1**2 + x1)**x1
<lambdifygenerated-6304>:2: RuntimeWarning: invalid value encountered in power
  return (x1**2 + x1)**x1
<lambdifygenerated-6305>:2: RuntimeWarning: invalid value encountered in power
  return (x1**4 + x1)**x1
<lambdifygenerated-6306>:2: RuntimeWarning: invalid value encountered in power
  return (x1**4 + x1)**x1
<lambdifygenerated-6307>:2: RuntimeWarning: invalid value encountered in power
  return (8*x1**4 + x1)**x1
<lambdifygenerated-6308>:2: RuntimeWarning: invalid value encountered in power
  return (8*x1**4 + x1)**x1
<lambdifygenerated-6309>:2: RuntimeWarning: invalid value encountered in power
  return (x1*(x1 + exp(x1))**3 + x1)**x1
<lambdifygenerated-6310>:2: RuntimeWarning: invalid value encountered in power
  return (x1*(x1 + exp(x1))**3 + x1)**x1
<lambdifygenerated-6311>:2: RuntimeWarning: invalid value encountered in power
  return (x1*(x1 + exp(x1**2))**3 + x1)**x1
<lambdifygenerated-6312>:2: RuntimeWarning: invalid value encountered in power
  return (x1*(x1 + exp(x1**2))**3 + x1)**x1
<lambdifygenerated-6313>:2: RuntimeWarning: invalid value encountered in power
  return (x1*(x1 + exp(-x1**2))**3 + x1)**x1
<lambdifygenerated-6314>:2: RuntimeWarning: invalid value encountered in power
  return (x1*(x1 + exp(-x1**2))**3 + x1)**x1
<lambdifygenerated-6315>:2: RuntimeWarning: invalid value encountered in power
  return (x1*(x1 + exp(-2*x1**2))**3 + x1)**x1
<lambdifygenerated-6316>:2: RuntimeWarning: invalid value encountered in power
  return (x1*(x1 + exp(-2*x1**2))**3 + x1)**x1
<lambdifygenerated-6317>:2: RuntimeWarning: invalid value encountered in power
  return (x1*(x1 + exp(-2*x1**2))**3 + x1)**x1
<lambdifygenerated-6318>:2: RuntimeWarning: invalid value encountered in power
  return (x1*(x1 + exp(-2*x1**2))**3 + x1)**x1
<lambdifygenerated-6319>:2: RuntimeWarning: invalid value encountered in power
  return (x1*(x1 + exp(x1*(-_a7_ - x1)))**3 + x1)**x1
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-6320>:2: RuntimeWarning: invalid value encountered in power
  return (x1*(x1 + exp(x1*(-_a7_ - x1)))**3 + x1)**x1
<lambdifygenerated-6321>:2: RuntimeWarning: invalid value encountered in power
  return (x1*(x1 + exp(x1*(-_a7_ - x1)))**3 + x1)**x1
<lambdifygenerated-6322>:2: RuntimeWarning: invalid value encountered in power
  return (x1*(x1 + exp(x1*(-_a7_ - x1)))**3 + x1)**x1
<lambdifygenerated-6323>:2: RuntimeWarning: invalid value encountered in power
  return (x1*(_a3_ + exp(x1*(-_a7_ - x1)))**3 + x1)**x1
<lambdifygenerated-6324>:2: RuntimeWarning: invalid value encountered in power
  return (x1*(_a3_ + exp(x1*(-_a7_ - x1)))**3 + x1)**x1
<lambdifygenerated-6325>:2: RuntimeWarning: invalid value encountered in power
  return (2*x1*(_a3_ + exp(x1*(-_a7_ - x1)))**3 + x1)**x1
<lambdifygenerated-6326>:2: RuntimeWarning: invalid value encountered in power
  return (2*x1*(_a3_ + exp(x1*(-_a7_ - x1)))**3 + x1)**x1
<lambdifygenerated-6327>:2: RuntimeWarning: invalid value encountered in power
  return (2*x1*(_a3_ + exp(x1*(-_a7_ - x1)))**3 + x1)**x1
<lambdifygenerated-6328>:2: RuntimeWarning: invalid value encountered in power
  return (2*x1*(_a3_ + exp(x1*(-_a7_ - x1)))**3 + x1)**x1
<lambdifygenerated-6329>:2: RuntimeWarning: invalid value encountered in power
  return (x1 + (_a3_ + exp(x1*(-_a7_ - x1)))**3*(_a7_ + x1))**x1
<lambdifygenerated-6330>:2: RuntimeWarning: invalid value encountered in power
  return (x1 + (_a3_ + exp(x1*(-_a7_ - x1)))**3*(_a7_ + x1))**x1
<lambdifygenerated-6331>:2: RuntimeWarning: invalid value encountered in power
  return (_a1_ + (_a3_ + exp(x1*(-_a7_ - x1)))**3*(_a7_ + x1))**x1
<lambdifygenerated-6332>:2: RuntimeWarning: invalid value encountered in power
  return (_a1_ + (_a3_ + exp(x1*(-_a7_ - x1)))**3*(_a7_ + x1))**x1
<lambdifygenerated-6333>:2: RuntimeWarning: invalid value encountered in power
  return (_a1_ + (_a3_ + exp(x1*(-_a7_ - x1)))**3*(_a7_ + x1))**(2*x1)
<lambdifygenerated-6334>:2: RuntimeWarning: invalid value encountered in power
  return (_a1_ + (_a3_ + exp(x1*(-_a7_ - x1)))**3*(_a7_ + x1))**(2*x1)
<lambdifygenerated-6335>:2: RuntimeWarning: invalid value encountered in power
  return (_a1_ + (_a3_ + exp(x1*(-_a7_ - x1)))**3*(_a7_ + x1))**(_a2_ + x1)
<lambdifygenerated-6336>:2: RuntimeWarning: invalid value encountered in power
  return (_a1_ + (_a3_ + exp(x1*(-_a7_ - x1)))**3*(_a7_ + x1))**(_a2_ + x1)
<lambdifygenerated-6337>:2: RuntimeWarning: invalid value encountered in power
  return (_a1_ + (_a3_ + exp(x1*(-_a7_ - x1)))**3*(_a7_ + x1))**(_a2_ + x1)
<lambdifygenerated-6338>:2: RuntimeWarning: invalid value encountered in power
  return (_a1_ + (_a3_ + exp(x1*(-_a7_ - x1)))**3*(_a7_ + x1))**(_a2_ + x1)
<lambdifygenerated-6339>:2: RuntimeWarning: invalid value encountered in power
  return (_a1_ + (_a3_ + exp(x1*(-_a7_ - x1)))**3*(_a7_ + x1))**(_a2_ + x1)
<lambdifygenerated-6340>:2: RuntimeWarning: invalid value encountered in power
  return (_a1_ + (_a3_ + exp(x1*(-_a7_ - x1)))**3*(_a7_ + x1))**(_a2_ + x1)
<lambdifygenerated-6341>:2: RuntimeWarning: invalid value encountered in power
  return (_a1_ + (_a3_ + exp(x1*(-_a7_ - x1)))**3*(_a7_ + x1))**(_a2_ + x1)
<lambdifygenerated-6342>:2: RuntimeWarning: invalid value encountered in power
  return (_a1_ + (_a3_ + exp(x1*(-_a7_ - x1)))**3*(_a7_ + x1))**(_a2_ + x1)

         x1         y  rep    ymodel      ybms
3745  0.997  0.053138  1.0  0.049299  0.065501
3746  0.998  0.053057  1.0  0.049254  0.065448
3747  0.998  0.052975  1.0  0.049209  0.065395
3748  0.999  0.052894  1.0  0.049164  0.065343

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.052733  1.0  0.049075  0.065238
3751  1.002  0.052652  1.0  0.049030  0.065186
3752  1.002  0.052571  1.0  0.048986  0.065134
3753  1.003  0.052491  1.0  0.048942  0.065082

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.277484  2.0  0.231485  0.252481
3746  0.998  0.277627  2.0  0.231261  0.252304
3747  0.998  0.277770  2.0  0.231035  0.252122
3748  0.999  0.277912  2.0  0.230807  0.251937

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.278193  2.0  0.230347  0.251552
3751  1.002  0.278333  2.0  0.230114  0.251353
3752  1.002  0.278471  2.0  0.229879  0.251150
3753  1.003  0.278610  2.0  0.229643  0.250943

3750
interpolation

<lambdifygenerated-6387>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1
<lambdifygenerated-6388>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1
<lambdifygenerated-6393>:2: RuntimeWarning: overflow encountered in power
  return _a1_**(_a2_/x1)
/usr/local/lib/python3.10/dist-packages/scipy/optimize/_minpack_py.py:1017: RuntimeWarning: overflow encountered in square
  cost = np.sum(infodict['fvec'] ** 2)
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
/usr/local/lib/python3.10/dist-packages/pandas/core/arraylike.py:399: RuntimeWarning: overflow encountered in square
  result = getattr(ufunc, method)(*inputs, **kwargs)
<lambdifygenerated-6394>:2: RuntimeWarning: overflow encountered in power
  return _a1_**(_a2_/x1)
<lambdifygenerated-6395>:2: RuntimeWarning: overflow encountered in power
  return _a1_**(_a2_/x1**2)
<lambdifygenerated-6397>:2: RuntimeWarning: overflow encountered in power
  return _a1_**((1/4)*_a2_/x1**2)
<lambdifygenerated-6399>:2: RuntimeWarning: invalid value encountered in power
  return _a1_**(_a2_/(_a2_ + x1)**2)

         x1         y  rep    ymodel      ybms
3745  0.997  0.306760  3.0  0.311823  0.316936
3746  0.998  0.307033  3.0  0.312095  0.317329
3747  0.998  0.307306  3.0  0.312365  0.317721
3748  0.999  0.307578  3.0  0.312634  0.318114

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.308120  3.0  0.313169  0.318899
3751  1.002  0.308390  3.0  0.313434  0.319291
3752  1.002  0.308660  3.0  0.313698  0.319683
3753  1.003  0.308928  3.0  0.313960  0.320075

3750
interpolation

         x1         y  rep   ymodel     ybms
3745  0.997  0.965360  4.0  0.98742  0.94885
3746  0.998  0.965399  4.0  0.98747  0.94885
3747  0.998  0.965439  4.0  0.98752  0.94885
3748  0.999  0.965479  4.0  0.98757  0.94885

extrapolation

         x1         y  rep    ymodel     ybms
3750  1.001  0.965559  4.0  0.987667  0.94885
3751  1.002  0.965598  4.0  0.987715  0.94885
3752  1.002  0.965638  4.0  0.987763  0.94885
3753  1.003  0.965678  4.0  0.987810  0.94885

3750
interpolation

<lambdifygenerated-6441>:2: RuntimeWarning: invalid value encountered in power
  return x1*x1**x1 + x1
<lambdifygenerated-6442>:2: RuntimeWarning: invalid value encountered in power
  return x1*x1**x1 + x1
<lambdifygenerated-6445>:2: RuntimeWarning: invalid value encountered in power
  return _a1_**(x1**x1)*x1 + x1
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-6446>:2: RuntimeWarning: invalid value encountered in power
  return _a1_**(x1**x1)*x1 + x1
<lambdifygenerated-6447>:2: RuntimeWarning: invalid value encountered in power
  return _a1_**(_a7_**x1)*x1 + x1

         x1         y  rep    ymodel      ybms
3745  0.997  0.308339  5.0  0.275653  0.297884
3746  0.998  0.308354  5.0  0.274885  0.297884
3747  0.998  0.308368  5.0  0.274110  0.297884
3748  0.999  0.308382  5.0  0.273327  0.297884

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.308407  5.0  0.271739  0.297884
3751  1.002  0.308419  5.0  0.270934  0.297884
3752  1.002  0.308430  5.0  0.270122  0.297884
3753  1.003  0.308441  5.0  0.269302  0.297884

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.215897  6.0  0.179943  0.239656
3746  0.998  0.216041  6.0  0.179577  0.239934
3747  0.998  0.216186  6.0  0.179205  0.240212
3748  0.999  0.216330  6.0  0.178827  0.240489

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.216618  6.0  0.178052  0.241044
3751  1.002  0.216762  6.0  0.177655  0.241321
3752  1.002  0.216905  6.0  0.177252  0.241598
3753  1.003  0.217048  6.0  0.176843  0.241874

3750

<lambdifygenerated-6497>:2: RuntimeWarning: invalid value encountered in power
  return x1*x1**(2*x1)
<lambdifygenerated-6498>:2: RuntimeWarning: invalid value encountered in power
  return x1*x1**(2*x1)
<lambdifygenerated-6507>:2: RuntimeWarning: invalid value encountered in power
  return x1*exp(_a1_ + x1)**(2*x1**x1)
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-6508>:2: RuntimeWarning: invalid value encountered in power
  return x1*exp(_a1_ + x1)**(2*x1**x1)
<lambdifygenerated-6513>:2: RuntimeWarning: overflow encountered in power
  return _a5_*exp(_a1_ + x1)**(2*_a0_**x1)
<lambdifygenerated-6513>:2: RuntimeWarning: overflow encountered in multiply
  return _a5_*exp(_a1_ + x1)**(2*_a0_**x1)
<lambdifygenerated-6517>:2: RuntimeWarning: overflow encountered in power
  return _a5_*exp(_a1_ + x1)**(2*_a0_**x1)
<lambdifygenerated-6517>:2: RuntimeWarning: overflow encountered in multiply
  return _a5_*exp(_a1_ + x1)**(2*_a0_**x1)

interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.100918  7.0  0.058944  0.070728
3746  0.998  0.100912  7.0  0.058630  0.070678
3747  0.998  0.100906  7.0  0.058315  0.070628
3748  0.999  0.100901  7.0  0.057999  0.070578

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.100890  7.0  0.057361  0.070479
3751  1.002  0.100885  7.0  0.057040  0.070430
3752  1.002  0.100880  7.0  0.056717  0.070380
3753  1.003  0.100874  7.0  0.056393  0.070331

3750
interpolation

<lambdifygenerated-6525>:2: RuntimeWarning: invalid value encountered in power
  return x1 + x1**x1
<lambdifygenerated-6526>:2: RuntimeWarning: invalid value encountered in power
  return x1 + x1**x1
<lambdifygenerated-6529>:2: RuntimeWarning: invalid value encountered in power
  return _a6_**(x1**x1) + x1
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-6530>:2: RuntimeWarning: invalid value encountered in power
  return _a6_**(x1**x1) + x1
<lambdifygenerated-6535>:2: RuntimeWarning: invalid value encountered in power
  return _a6_ + _a6_**(_a5_**x1)

         x1         y  rep    ymodel      ybms
3745  0.997  0.825595  8.0  0.823857  0.831594
3746  0.998  0.825925  8.0  0.824117  0.831974
3747  0.998  0.826254  8.0  0.824376  0.832353
3748  0.999  0.826582  8.0  0.824634  0.832732

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.827238  8.0  0.825147  0.833488
3751  1.002  0.827565  8.0  0.825402  0.833866
3752  1.002  0.827892  8.0  0.825656  0.834242
3753  1.003  0.828218  8.0  0.825910  0.834619

3750
interpolation

<lambdifygenerated-6551>:2: RuntimeWarning: invalid value encountered in power
  return x1*tanh(x1**x1)**2
<lambdifygenerated-6552>:2: RuntimeWarning: invalid value encountered in power
  return x1*tanh(x1**x1)**2
<lambdifygenerated-6557>:2: RuntimeWarning: invalid value encountered in power
  return _a6_*tanh(_a0_**x1)**2

         x1         y  rep    ymodel      ybms
3745  0.997  0.855453  9.0  0.847963  0.817676
3746  0.998  0.855554  9.0  0.848105  0.817689
3747  0.998  0.855656  9.0  0.848246  0.817703
3748  0.999  0.855757  9.0  0.848388  0.817716

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.855960  9.0  0.848669  0.817742
3751  1.002  0.856062  9.0  0.848809  0.817755
3752  1.002  0.856163  9.0  0.848948  0.817768
3753  1.003  0.856265  9.0  0.849088  0.817781

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.987381  0.0  0.996029  0.985134
3746  0.998  0.987426  0.0  0.996058  0.985137
3747  0.998  0.987470  0.0  0.996087  0.985140
3748  0.999  0.987515  0.0  0.996115  0.985143

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.987604  0.0  0.996172  0.985149
3751  1.002  0.987648  0.0  0.996200  0.985152
3752  1.002  0.987692  0.0  0.996228  0.985155
3753  1.003  0.987737  0.0  0.996256  0.985158

3750

<lambdifygenerated-6617>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (-_a4_/(x1 + x1**x1) + x1)**2
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-6618>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (-_a4_/(x1 + x1**x1) + x1)**2
<lambdifygenerated-6623>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (-_a4_/(_a5_**x1 + x1**2) + x1)**2
<lambdifygenerated-6625>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (-_a4_/(_a5_**x1 + 4*x1**2) + x1)**2
<lambdifygenerated-6627>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (-_a4_/(_a5_**x1 + (_a1_ + x1)**2) + x1)**2
<lambdifygenerated-6627>:2: RuntimeWarning: overflow encountered in power
  return x1 + (-_a4_/(_a5_**x1 + (_a1_ + x1)**2) + x1)**2
<lambdifygenerated-6631>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (-_a4_/(_a5_**x1 + (_a1_ + x1)**2) + _a7_)**2
<lambdifygenerated-6633>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1 + (-_a4_/(_a5_**x1 + (_a1_ + x1)**2) + _a7_)**2
<lambdifygenerated-6634>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1 + (-_a4_/(_a5_**x1 + (_a1_ + x1)**2) + _a7_)**2

interpolation

<lambdifygenerated-6641>:2: RuntimeWarning: invalid value encountered in power
  return _a7_**(_a4_ + x1) + (-_a4_/(_a5_**x1 + (_a1_ + x1)**2) + _a7_)**2

         x1         y  rep    ymodel      ybms
3745  0.997  0.053138  1.0  0.046071  0.040063
3746  0.998  0.053057  1.0  0.045928  0.039966
3747  0.998  0.052975  1.0  0.045785  0.039869
3748  0.999  0.052894  1.0  0.045643  0.039773

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.052733  1.0  0.045358  0.039581
3751  1.002  0.052652  1.0  0.045216  0.039485
3752  1.002  0.052571  1.0  0.045074  0.039390
3753  1.003  0.052491  1.0  0.044933  0.039295

3750
interpolation

<lambdifygenerated-6663>:2: RuntimeWarning: invalid value encountered in power
  return x1*x1**x1*(_a0_ + x1) + x1
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-6664>:2: RuntimeWarning: invalid value encountered in power
  return x1*x1**x1*(_a0_ + x1) + x1
<lambdifygenerated-6673>:2: RuntimeWarning: invalid value encountered in power
  return _a2_**cos(x1*(x1 + x1**x1))*x1*(_a0_ + x1) + x1
<lambdifygenerated-6674>:2: RuntimeWarning: invalid value encountered in power
  return _a2_**cos(x1*(x1 + x1**x1))*x1*(_a0_ + x1) + x1
<lambdifygenerated-6675>:2: RuntimeWarning: invalid value encountered in power
  return _a2_**cos(x1*(_a0_**x1 + x1))*x1*(_a0_ + x1) + x1
<lambdifygenerated-6676>:2: RuntimeWarning: invalid value encountered in power
  return _a2_**cos(x1*(_a0_**x1 + x1))*x1*(_a0_ + x1) + x1
<lambdifygenerated-6677>:2: RuntimeWarning: invalid value encountered in power
  return _a2_**cos(x1*(_a0_**x1 + x1))*x1*(_a0_ + x1) + x1
<lambdifygenerated-6678>:2: RuntimeWarning: invalid value encountered in power
  return _a2_**cos(x1*(_a0_**x1 + x1))*x1*(_a0_ + x1) + x1
<lambdifygenerated-6679>:2: RuntimeWarning: invalid value encountered in power
  return _a2_**cos(x1*(_a0_**x1 + x1))*x1*(_a0_ + x1) + x1
<lambdifygenerated-6680>:2: RuntimeWarning: invalid value encountered in power
  return _a2_**cos(x1*(_a0_**x1 + x1))*x1*(_a0_ + x1) + x1
<lambdifygenerated-6681>:2: RuntimeWarning: invalid value encountered in power
  return _a2_**cos(_a0_*(_a0_**x1 + x1))*x1*(_a0_ + x1) + x1
<lambdifygenerated-6682>:2: RuntimeWarning: invalid value encountered in power
  return _a2_**cos(_a0_*(_a0_**x1 + x1))*x1*(_a0_ + x1) + x1
<lambdifygenerated-6683>:2: RuntimeWarning: invalid value encountered in power
  return _a1_*_a2_**cos(_a0_*(_a0_**x1 + x1))*(_a0_ + x1) + x1
<lambdifygenerated-6684>:2: RuntimeWarning: invalid value encountered in power
  return _a1_*_a2_**cos(_a0_*(_a0_**x1 + x1))*(_a0_ + x1) + x1
<lambdifygenerated-6685>:2: RuntimeWarning: invalid value encountered in power
  return _a1_*_a2_**cos(_a0_*(_a0_**x1 + x1))*(_a0_ + x1) + _a4_
<lambdifygenerated-6686>:2: RuntimeWarning: invalid value encountered in power
  return _a1_*_a2_**cos(_a0_*(_a0_**x1 + x1))*(_a0_ + x1) + _a4_
<lambdifygenerated-6687>:2: RuntimeWarning: invalid value encountered in power
  return _a1_*_a2_**cos(_a0_*(_a0_**x1 + x1))*(_a0_ + x1) + _a4_
<lambdifygenerated-6688>:2: RuntimeWarning: invalid value encountered in power
  return _a1_*_a2_**cos(_a0_*(_a0_**x1 + x1))*(_a0_ + x1) + _a4_
<lambdifygenerated-6689>:2: RuntimeWarning: invalid value encountered in power
  return _a1_*_a2_**cos(_a0_*(_a0_**x1 + x1))*(_a0_ + x1) + _a4_
<lambdifygenerated-6690>:2: RuntimeWarning: invalid value encountered in power
  return _a1_*_a2_**cos(_a0_*(_a0_**x1 + x1))*(_a0_ + x1) + _a4_

         x1         y  rep    ymodel      ybms
3745  0.997  0.277484  2.0  0.317988  0.298986
3746  0.998  0.277627  2.0  0.318377  0.299295
3747  0.998  0.277770  2.0  0.318765  0.299603
3748  0.999  0.277912  2.0  0.319153  0.299909

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.278193  2.0  0.319925  0.300517
3751  1.002  0.278333  2.0  0.320310  0.300819
3752  1.002  0.278471  2.0  0.320695  0.301119
3753  1.003  0.278610  2.0  0.321078  0.301417

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.306760  3.0  0.319522  0.353790
3746  0.998  0.307033  3.0  0.319853  0.354553
3747  0.998  0.307306  3.0  0.320183  0.355316
3748  0.999  0.307578  3.0  0.320512  0.356081

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.308120  3.0  0.321168  0.357613
3751  1.002  0.308390  3.0  0.321495  0.358382
3752  1.002  0.308660  3.0  0.321822  0.359151
3753  1.003  0.308928  3.0  0.322147  0.359922

3750
interpolation

<lambdifygenerated-6717>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1
<lambdifygenerated-6718>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1
<lambdifygenerated-6721>:2: RuntimeWarning: invalid value encountered in power
  return _a1_**(x1**x1)
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-6722>:2: RuntimeWarning: invalid value encountered in power
  return _a1_**(x1**x1)

         x1         y  rep    ymodel      ybms
3745  0.997  0.965360  4.0  0.945724  0.970462
3746  0.998  0.965399  4.0  0.945701  0.970488
3747  0.998  0.965439  4.0  0.945677  0.970514
3748  0.999  0.965479  4.0  0.945654  0.970539

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.965559  4.0  0.945608  0.970591
3751  1.002  0.965598  4.0  0.945584  0.970617
3752  1.002  0.965638  4.0  0.945561  0.970642
3753  1.003  0.965678  4.0  0.945538  0.970668

3750

<lambdifygenerated-6751>:2: RuntimeWarning: invalid value encountered in power
  return _a7_*exp(x1*x1**x1) + x1
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-6752>:2: RuntimeWarning: invalid value encountered in power
  return _a7_*exp(x1*x1**x1) + x1
<lambdifygenerated-6753>:2: RuntimeWarning: invalid value encountered in power
  return _a7_*exp(_a3_**x1*x1) + x1
<lambdifygenerated-6757>:2: RuntimeWarning: invalid value encountered in power
  return _a7_*exp(_a2_*_a3_**x1) + x1
<lambdifygenerated-6759>:2: RuntimeWarning: invalid value encountered in power
  return _a6_ + _a7_*exp(_a2_*_a3_**x1)
<lambdifygenerated-6763>:2: RuntimeWarning: invalid value encountered in power
  return _a6_ + _a7_*exp(_a2_*_a3_**x1)

interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.308339  5.0  0.270127  0.292683
3746  0.998  0.308354  5.0  0.270077  0.292683
3747  0.998  0.308368  5.0  0.270027  0.292683
3748  0.999  0.308382  5.0  0.269977  0.292683

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.308407  5.0  0.269877  0.292683
3751  1.002  0.308419  5.0  0.269828  0.292683
3752  1.002  0.308430  5.0  0.269778  0.292683
3753  1.003  0.308441  5.0  0.269729  0.292683

3750
interpolation

<lambdifygenerated-6777>:2: RuntimeWarning: invalid value encountered in power
  return x1*tanh((x1 + x1**x1)**2)
<lambdifygenerated-6778>:2: RuntimeWarning: invalid value encountered in power
  return x1*tanh((x1 + x1**x1)**2)

         x1         y  rep    ymodel      ybms
3745  0.997  0.215897  6.0  0.200137  0.245385
3746  0.998  0.216041  6.0  0.200232  0.245658
3747  0.998  0.216186  6.0  0.200328  0.245931
3748  0.999  0.216330  6.0  0.200423  0.246204

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.216618  6.0  0.200613  0.246749
3751  1.002  0.216762  6.0  0.200707  0.247022
3752  1.002  0.216905  6.0  0.200802  0.247294
3753  1.003  0.217048  6.0  0.200896  0.247567

3750
interpolation

<lambdifygenerated-6813>:2: RuntimeWarning: invalid value encountered in power
  return _a2_/(_a3_*(_a5_ + x1) + x1*x1**x1)
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-6814>:2: RuntimeWarning: invalid value encountered in power
  return _a2_/(_a3_*(_a5_ + x1) + x1*x1**x1)
<lambdifygenerated-6815>:2: RuntimeWarning: invalid value encountered in power
  return _a2_/(_a3_*(_a5_ + x1) + _a3_**x1*x1)
<lambdifygenerated-6816>:2: RuntimeWarning: invalid value encountered in power
  return _a2_/(_a3_*(_a5_ + x1) + _a3_**x1*x1)
<lambdifygenerated-6817>:2: RuntimeWarning: invalid value encountered in power
  return _a2_/(_a3_*(_a5_ + x1) + _a3_**x1*x1)
<lambdifygenerated-6818>:2: RuntimeWarning: invalid value encountered in power
  return _a2_/(_a3_*(_a5_ + x1) + _a3_**x1*x1)
<lambdifygenerated-6819>:2: RuntimeWarning: invalid value encountered in power
  return _a2_/(_a3_*(_a5_ + x1) + _a3_**x1*_a4_)
<lambdifygenerated-6820>:2: RuntimeWarning: invalid value encountered in power
  return _a2_/(_a3_*(_a5_ + x1) + _a3_**x1*_a4_)
<lambdifygenerated-6821>:2: RuntimeWarning: invalid value encountered in power
  return _a2_/(_a3_*(_a5_ + x1) + _a3_**x1*_a4_)
<lambdifygenerated-6822>:2: RuntimeWarning: invalid value encountered in power
  return _a2_/(_a3_*(_a5_ + x1) + _a3_**x1*_a4_)
<lambdifygenerated-6823>:2: RuntimeWarning: invalid value encountered in power
  return _a2_/(_a3_*(_a5_ + x1) + _a3_**x1*_a4_)
<lambdifygenerated-6824>:2: RuntimeWarning: invalid value encountered in power
  return _a2_/(_a3_*(_a5_ + x1) + _a3_**x1*_a4_)

         x1         y  rep    ymodel      ybms
3745  0.997  0.100918  7.0  0.114279  0.089491
3746  0.998  0.100912  7.0  0.114305  0.089447
3747  0.998  0.100906  7.0  0.114332  0.089403
3748  0.999  0.100901  7.0  0.114358  0.089359

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.100890  7.0  0.114411  0.089272
3751  1.002  0.100885  7.0  0.114437  0.089228
3752  1.002  0.100880  7.0  0.114464  0.089184
3753  1.003  0.100874  7.0  0.114490  0.089141

3750
interpolation

/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(

         x1         y  rep    ymodel      ybms
3745  0.997  0.825595  8.0  0.813149  0.825182
3746  0.998  0.825925  8.0  0.813397  0.825472
3747  0.998  0.826254  8.0  0.813644  0.825761
3748  0.999  0.826582  8.0  0.813891  0.826050

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.827238  8.0  0.814384  0.826625
3751  1.002  0.827565  8.0  0.814629  0.826912
3752  1.002  0.827892  8.0  0.814874  0.827198
3753  1.003  0.828218  8.0  0.815118  0.827483

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.855453  9.0  0.849745  0.869986
3746  0.998  0.855554  9.0  0.849814  0.870096
3747  0.998  0.855656  9.0  0.849884  0.870206
3748  0.999  0.855757  9.0  0.849953  0.870316

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.855960  9.0  0.850092  0.870536
3751  1.002  0.856062  9.0  0.850161  0.870645
3752  1.002  0.856163  9.0  0.850229  0.870754
3753  1.003  0.856265  9.0  0.850298  0.870863

3750
interpolation

<lambdifygenerated-6885>:2: RuntimeWarning: invalid value encountered in power
  return exp(x1*x1**x1)
<lambdifygenerated-6886>:2: RuntimeWarning: invalid value encountered in power
  return exp(x1*x1**x1)
<lambdifygenerated-6895>:2: RuntimeWarning: invalid value encountered in power
  return exp(_a4_**exp(x1*(_a0_ + x1))*x1)
<lambdifygenerated-6899>:2: RuntimeWarning: overflow encountered in exp
  return exp(_a4_**exp(x1*(_a0_ + x1**2 + x1))*x1)

         x1         y  rep    ymodel  ybms
3745  0.997  0.987381  0.0  0.983373   1.0
3746  0.998  0.987426  0.0  0.983386   1.0
3747  0.998  0.987470  0.0  0.983399   1.0
3748  0.999  0.987515  0.0  0.983412   1.0

extrapolation

         x1         y  rep    ymodel  ybms
3750  1.001  0.987604  0.0  0.983438   1.0
3751  1.002  0.987648  0.0  0.983451   1.0
3752  1.002  0.987692  0.0  0.983464   1.0
3753  1.003  0.987737  0.0  0.983477   1.0

3750
interpolation

/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(

         x1         y  rep    ymodel      ybms
3745  0.997  0.053138  1.0  0.052063  0.035107
3746  0.998  0.053057  1.0  0.052070  0.035079
3747  0.998  0.052975  1.0  0.052077  0.035052
3748  0.999  0.052894  1.0  0.052084  0.035025

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.052733  1.0  0.052100  0.034973
3751  1.002  0.052652  1.0  0.052108  0.034947
3752  1.002  0.052571  1.0  0.052117  0.034922
3753  1.003  0.052491  1.0  0.052126  0.034897

3750
interpolation

<lambdifygenerated-6975>:2: RuntimeWarning: invalid value encountered in power
  return x1*cos(x1*x1**x1 + x1)
<lambdifygenerated-6976>:2: RuntimeWarning: invalid value encountered in power
  return x1*cos(x1*x1**x1 + x1)

         x1         y  rep    ymodel      ybms
3745  0.997  0.277484  2.0  0.284750  0.285378
3746  0.998  0.277627  2.0  0.285007  0.285259
3747  0.998  0.277770  2.0  0.285263  0.285133
3748  0.999  0.277912  2.0  0.285519  0.285000

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.278193  2.0  0.286027  0.284714
3751  1.002  0.278333  2.0  0.286280  0.284559
3752  1.002  0.278471  2.0  0.286532  0.284398
3753  1.003  0.278610  2.0  0.286784  0.284230

3750
interpolation

<lambdifygenerated-7007>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1
<lambdifygenerated-7008>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1

         x1         y  rep    ymodel      ybms
3745  0.997  0.306760  3.0  0.300129  0.333404
3746  0.998  0.307033  3.0  0.300335  0.333991
3747  0.998  0.307306  3.0  0.300540  0.334579
3748  0.999  0.307578  3.0  0.300744  0.335167

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.308120  3.0  0.301152  0.336346
3751  1.002  0.308390  3.0  0.301356  0.336937
3752  1.002  0.308660  3.0  0.301558  0.337528
3753  1.003  0.308928  3.0  0.301761  0.338120

3750
interpolation

<lambdifygenerated-7041>:2: RuntimeWarning: invalid value encountered in power
  return _a5_/(_a5_*x1**x1 + x1)
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-7042>:2: RuntimeWarning: invalid value encountered in power
  return _a5_/(_a5_*x1**x1 + x1)
<lambdifygenerated-7047>:2: RuntimeWarning: invalid value encountered in power
  return _a5_/(_a0_ + _a0_**x1*_a5_)
<lambdifygenerated-7051>:2: RuntimeWarning: invalid value encountered in power
  return _a5_/(_a0_ + _a0_**x1*_a5_)

         x1         y  rep    ymodel      ybms
3745  0.997  0.965360  4.0  0.954581  0.948958
3746  0.998  0.965399  4.0  0.954600  0.948958
3747  0.998  0.965439  4.0  0.954620  0.948958
3748  0.999  0.965479  4.0  0.954640  0.948958

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.965559  4.0  0.954679  0.948958
3751  1.002  0.965598  4.0  0.954698  0.948958
3752  1.002  0.965638  4.0  0.954718  0.948959
3753  1.003  0.965678  4.0  0.954737  0.948959

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.308339  5.0  0.309136  0.357121
3746  0.998  0.308354  5.0  0.309373  0.357840
3747  0.998  0.308368  5.0  0.309609  0.358562
3748  0.999  0.308382  5.0  0.309846  0.359286

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.308407  5.0  0.310321  0.360741
3751  1.002  0.308419  5.0  0.310559  0.361472
3752  1.002  0.308430  5.0  0.310798  0.362205
3753  1.003  0.308441  5.0  0.311036  0.362940

3750

<lambdifygenerated-7083>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1
<lambdifygenerated-7084>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1

interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.215897  6.0  0.208897  0.212850
3746  0.998  0.216041  6.0  0.209006  0.212996
3747  0.998  0.216186  6.0  0.209115  0.213142
3748  0.999  0.216330  6.0  0.209224  0.213288

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.216618  6.0  0.209442  0.213580
3751  1.002  0.216762  6.0  0.209550  0.213725
3752  1.002  0.216905  6.0  0.209659  0.213871
3753  1.003  0.217048  6.0  0.209767  0.214016

3750
interpolation

<lambdifygenerated-7121>:2: RuntimeWarning: invalid value encountered in power
  return _a1_*x1**x1
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-7122>:2: RuntimeWarning: invalid value encountered in power
  return _a1_*x1**x1
<lambdifygenerated-7129>:2: RuntimeWarning: invalid value encountered in power
  return _a1_*_a2_**((x1 + x1**x1)**2)
<lambdifygenerated-7130>:2: RuntimeWarning: invalid value encountered in power
  return _a1_*_a2_**((x1 + x1**x1)**2)
<lambdifygenerated-7135>:2: RuntimeWarning: invalid value encountered in power
  return _a1_*_a2_**((_a0_ + _a1_**x1)**2)

         x1         y  rep    ymodel      ybms
3745  0.997  0.100918  7.0  0.174714  0.075812
3746  0.998  0.100912  7.0  0.176264  0.075762
3747  0.998  0.100906  7.0  0.177824  0.075712
3748  0.999  0.100901  7.0  0.179396  0.075661

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.100890  7.0  0.182575  0.075561
3751  1.002  0.100885  7.0  0.184181  0.075511
3752  1.002  0.100880  7.0  0.185798  0.075461
3753  1.003  0.100874  7.0  0.187426  0.075412

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.825595  8.0  0.878343  0.857094
3746  0.998  0.825925  8.0  0.880036  0.857685
3747  0.998  0.826254  8.0  0.881737  0.858276
3748  0.999  0.826582  8.0  0.883446  0.858866

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.827238  8.0  0.886888  0.860048
3751  1.002  0.827565  8.0  0.888620  0.860638
3752  1.002  0.827892  8.0  0.890361  0.861229
3753  1.003  0.828218  8.0  0.892108  0.861820

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.855453  9.0  0.925065  0.871606
3746  0.998  0.855554  9.0  0.926567  0.871717
3747  0.998  0.855656  9.0  0.928076  0.871827
3748  0.999  0.855757  9.0  0.929592  0.871937

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.855960  9.0  0.932644  0.872157
3751  1.002  0.856062  9.0  0.934180  0.872267
3752  1.002  0.856163  9.0  0.935722  0.872376
3753  1.003  0.856265  9.0  0.937270  0.872485

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.987381  0.0  0.957712  0.999378
3746  0.998  0.987426  0.0  0.957640  0.999381
3747  0.998  0.987470  0.0  0.957569  0.999383
3748  0.999  0.987515  0.0  0.957497  0.999386

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.987604  0.0  0.957354  0.999391
3751  1.002  0.987648  0.0  0.957282  0.999393
3752  1.002  0.987692  0.0  0.957211  0.999395
3753  1.003  0.987737  0.0  0.957139  0.999398

3750
interpolation

<lambdifygenerated-7241>:2: RuntimeWarning: invalid value encountered in power
  return exp(x1*(x1 + x1**x1))
<lambdifygenerated-7242>:2: RuntimeWarning: invalid value encountered in power
  return exp(x1*(x1 + x1**x1))
<lambdifygenerated-7243>:2: RuntimeWarning: invalid value encountered in power
  return exp(x1*(_a2_**x1 + x1))
<lambdifygenerated-7245>:2: RuntimeWarning: invalid value encountered in power
  return exp(x1*(_a2_**tanh(x1) + x1))
<lambdifygenerated-7247>:2: RuntimeWarning: invalid value encountered in power
  return exp(x1*(_a2_**tanh(x1**2) + x1))
<lambdifygenerated-7249>:2: RuntimeWarning: invalid value encountered in power
  return exp(x1*(_a2_**tanh(2*x1**2) + x1))
<lambdifygenerated-7255>:2: RuntimeWarning: invalid value encountered in power
  return exp(x1*(_a2_**tanh(x1**2*(_a4_ + x1)) + x1))
<lambdifygenerated-7257>:2: RuntimeWarning: invalid value encountered in power
  return exp(x1*(_a2_**tanh(_a6_*x1*(_a4_ + x1)) + x1))
<lambdifygenerated-7257>:2: RuntimeWarning: overflow encountered in exp
  return exp(x1*(_a2_**tanh(_a6_*x1*(_a4_ + x1)) + x1))
<lambdifygenerated-7261>:2: RuntimeWarning: overflow encountered in exp
  return exp(_a1_*(_a2_**tanh(_a6_*x1*(_a4_ + x1)) + x1))
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-7262>:2: RuntimeWarning: overflow encountered in exp
  return exp(_a1_*(_a2_**tanh(_a6_*x1*(_a4_ + x1)) + x1))
<lambdifygenerated-7263>:2: RuntimeWarning: overflow encountered in exp
  return exp(_a1_*(_a2_**tanh(_a6_*x1*(_a4_ + x1)) + x1))
<lambdifygenerated-7264>:2: RuntimeWarning: overflow encountered in exp
  return exp(_a1_*(_a2_**tanh(_a6_*x1*(_a4_ + x1)) + x1))
<lambdifygenerated-7265>:2: RuntimeWarning: overflow encountered in exp
  return exp(_a1_*(_a2_**tanh(_a6_*x1*(_a4_ + x1)) + x1))
<lambdifygenerated-7266>:2: RuntimeWarning: overflow encountered in exp
  return exp(_a1_*(_a2_**tanh(_a6_*x1*(_a4_ + x1)) + x1))

         x1         y  rep    ymodel      ybms
3745  0.997  0.053138  1.0  0.017661  0.041750
3746  0.998  0.053057  1.0  0.017438  0.041709
3747  0.998  0.052975  1.0  0.017215  0.041669
3748  0.999  0.052894  1.0  0.016993  0.041629

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.052733  1.0  0.016548  0.041548
3751  1.002  0.052652  1.0  0.016326  0.041509
3752  1.002  0.052571  1.0  0.016104  0.041469
3753  1.003  0.052491  1.0  0.015882  0.041429

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.277484  2.0  0.306271  0.396883
3746  0.998  0.277627  2.0  0.306709  0.398201
3747  0.998  0.277770  2.0  0.307146  0.399522
3748  0.999  0.277912  2.0  0.307582  0.400845

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.278193  2.0  0.308452  0.403496
3751  1.002  0.278333  2.0  0.308886  0.404825
3752  1.002  0.278471  2.0  0.309320  0.406157
3753  1.003  0.278610  2.0  0.309753  0.407490

3750
interpolation

<lambdifygenerated-7305>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1
<lambdifygenerated-7306>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1

         x1         y  rep    ymodel      ybms
3745  0.997  0.306760  3.0  0.314057  0.336940
3746  0.998  0.307033  3.0  0.314342  0.337556
3747  0.998  0.307306  3.0  0.314626  0.338174
3748  0.999  0.307578  3.0  0.314909  0.338792

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.308120  3.0  0.315474  0.340030
3751  1.002  0.308390  3.0  0.315756  0.340650
3752  1.002  0.308660  3.0  0.316037  0.341272
3753  1.003  0.308928  3.0  0.316317  0.341894

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.965360  4.0  0.893986  0.937059
3746  0.998  0.965399  4.0  0.893474  0.937059
3747  0.998  0.965439  4.0  0.892961  0.937059
3748  0.999  0.965479  4.0  0.892446  0.937059

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.965559  4.0  0.891411  0.937059
3751  1.002  0.965598  4.0  0.890892  0.937059
3752  1.002  0.965638  4.0  0.890371  0.937059
3753  1.003  0.965678  4.0  0.889849  0.937059

3750

<lambdifygenerated-7357>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1 + x1**x1)
<lambdifygenerated-7358>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1 + x1**x1)
<lambdifygenerated-7361>:2: RuntimeWarning: invalid value encountered in power
  return x1*(_a2_**(x1**x1) + x1)
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-7362>:2: RuntimeWarning: invalid value encountered in power
  return x1*(_a2_**(x1**x1) + x1)
<lambdifygenerated-7363>:2: RuntimeWarning: invalid value encountered in power
  return x1*(_a2_**(_a3_**x1) + x1)

interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.308339  5.0  0.298860  0.283113
3746  0.998  0.308354  5.0  0.298552  0.283113
3747  0.998  0.308368  5.0  0.298240  0.283113
3748  0.999  0.308382  5.0  0.297925  0.283113

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.308407  5.0  0.297285  0.283113
3751  1.002  0.308419  5.0  0.296961  0.283113
3752  1.002  0.308430  5.0  0.296632  0.283113
3753  1.003  0.308441  5.0  0.296301  0.283113

3750

<lambdifygenerated-7391>:2: RuntimeWarning: invalid value encountered in power
  return x1*tanh(_a2_**2*(x1 + x1**x1)**2)
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-7392>:2: RuntimeWarning: invalid value encountered in power
  return x1*tanh(_a2_**2*(x1 + x1**x1)**2)

interpolation

<lambdifygenerated-7399>:2: RuntimeWarning: invalid value encountered in power
  return _a2_*tanh(_a2_**2*(_a1_ + _a4_**x1)**2)

         x1         y  rep    ymodel      ybms
3745  0.997  0.215897  6.0  0.247978  0.248777
3746  0.998  0.216041  6.0  0.248102  0.249046
3747  0.998  0.216186  6.0  0.248222  0.249315
3748  0.999  0.216330  6.0  0.248338  0.249584

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.216618  6.0  0.248559  0.250122
3751  1.002  0.216762  6.0  0.248663  0.250391
3752  1.002  0.216905  6.0  0.248763  0.250659
3753  1.003  0.217048  6.0  0.248860  0.250928

3750
interpolation

<lambdifygenerated-7411>:2: RuntimeWarning: invalid value encountered in power
  return x1*x1**x1
<lambdifygenerated-7412>:2: RuntimeWarning: invalid value encountered in power
  return x1*x1**x1

         x1         y  rep    ymodel      ybms
3745  0.997  0.100918  7.0  0.109442  0.083658
3746  0.998  0.100912  7.0  0.109659  0.083676
3747  0.998  0.100906  7.0  0.109876  0.083694
3748  0.999  0.100901  7.0  0.110092  0.083712

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.100890  7.0  0.110524  0.083750
3751  1.002  0.100885  7.0  0.110740  0.083769
3752  1.002  0.100880  7.0  0.110955  0.083789
3753  1.003  0.100874  7.0  0.111170  0.083808

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.825595  8.0  0.872139  0.874529
3746  0.998  0.825925  8.0  0.872776  0.875131
3747  0.998  0.826254  8.0  0.873415  0.875733
3748  0.999  0.826582  8.0  0.874054  0.876335

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.827238  8.0  0.875335  0.877540
3751  1.002  0.827565  8.0  0.875977  0.878142
3752  1.002  0.827892  8.0  0.876620  0.878744
3753  1.003  0.828218  8.0  0.877264  0.879346

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.855453  9.0  0.925196  0.869547
3746  0.998  0.855554  9.0  0.927270  0.869654
3747  0.998  0.855656  9.0  0.929374  0.869761
3748  0.999  0.855757  9.0  0.931508  0.869868

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.855960  9.0  0.935870  0.870081
3751  1.002  0.856062  9.0  0.938097  0.870187
3752  1.002  0.856163  9.0  0.940355  0.870293
3753  1.003  0.856265  9.0  0.942644  0.870399

3750
interpolation

<lambdifygenerated-7499>:2: RuntimeWarning: invalid value encountered in power
  return x1**2*tanh(x1**x1/x1)
<lambdifygenerated-7500>:2: RuntimeWarning: invalid value encountered in power
  return x1**2*tanh(x1**x1/x1)
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(

         x1         y  rep    ymodel      ybms
3745  0.997  0.987381  0.0  1.002279  1.026648
3746  0.998  0.987426  0.0  1.002320  1.026815
3747  0.998  0.987470  0.0  1.002361  1.026981
3748  0.999  0.987515  0.0  1.002401  1.027148

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.987604  0.0  1.002483  1.027481
3751  1.002  0.987648  0.0  1.002523  1.027648
3752  1.002  0.987692  0.0  1.002563  1.027815
3753  1.003  0.987737  0.0  1.002603  1.027982

3750
interpolation

/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(

         x1         y  rep    ymodel      ybms
3745  0.997  0.053138  1.0  0.044696  0.086810
3746  0.998  0.053057  1.0  0.044554  0.086901
3747  0.998  0.052975  1.0  0.044412  0.086993
3748  0.999  0.052894  1.0  0.044271  0.087086

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.052733  1.0  0.043988  0.087272
3751  1.002  0.052652  1.0  0.043848  0.087366
3752  1.002  0.052571  1.0  0.043707  0.087460
3753  1.003  0.052491  1.0  0.043567  0.087554

3750
interpolation

<lambdifygenerated-7587>:2: RuntimeWarning: invalid value encountered in power
  return _a1_*sin(x1*(_a6_ + x1)) + x1**x1
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-7588>:2: RuntimeWarning: invalid value encountered in power
  return _a1_*sin(x1*(_a6_ + x1)) + x1**x1

         x1         y  rep    ymodel      ybms
3745  0.997  0.277484  2.0  0.326366  0.324071
3746  0.998  0.277627  2.0  0.326776  0.324413
3747  0.998  0.277770  2.0  0.327186  0.324752
3748  0.999  0.277912  2.0  0.327595  0.325089

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.278193  2.0  0.328410  0.325753
3751  1.002  0.278333  2.0  0.328816  0.326082
3752  1.002  0.278471  2.0  0.329221  0.326407
3753  1.003  0.278610  2.0  0.329625  0.326730

3750
interpolation

<lambdifygenerated-7605>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1
<lambdifygenerated-7606>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1

         x1         y  rep    ymodel      ybms
3745  0.997  0.306760  3.0  0.265859  0.312554
3746  0.998  0.307033  3.0  0.265965  0.313116
3747  0.998  0.307306  3.0  0.266071  0.313680
3748  0.999  0.307578  3.0  0.266175  0.314244

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.308120  3.0  0.266382  0.315374
3751  1.002  0.308390  3.0  0.266484  0.315940
3752  1.002  0.308660  3.0  0.266586  0.316507
3753  1.003  0.308928  3.0  0.266686  0.317074

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.965360  4.0  0.895545  0.948216
3746  0.998  0.965399  4.0  0.895002  0.948216
3747  0.998  0.965439  4.0  0.894459  0.948216
3748  0.999  0.965479  4.0  0.893914  0.948216

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.965559  4.0  0.892824  0.948216
3751  1.002  0.965598  4.0  0.892278  0.948216
3752  1.002  0.965638  4.0  0.891732  0.948217
3753  1.003  0.965678  4.0  0.891185  0.948217

3750

<lambdifygenerated-7659>:2: RuntimeWarning: invalid value encountered in power
  return x1**2*x1**(2*x1) + x1
<lambdifygenerated-7660>:2: RuntimeWarning: invalid value encountered in power
  return x1**2*x1**(2*x1) + x1
<lambdifygenerated-7663>:2: RuntimeWarning: invalid value encountered in power
  return _a4_**(2*x1**x1)*x1**2 + x1
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-7664>:2: RuntimeWarning: invalid value encountered in power
  return _a4_**(2*x1**x1)*x1**2 + x1

interpolation

<lambdifygenerated-7671>:2: RuntimeWarning: invalid value encountered in power
  return _a3_ + _a4_**2*_a4_**(2*_a2_**x1)

         x1         y  rep    ymodel      ybms
3745  0.997  0.308339  5.0  0.277295  0.289619
3746  0.998  0.308354  5.0  0.276720  0.289619
3747  0.998  0.308368  5.0  0.276143  0.289619
3748  0.999  0.308382  5.0  0.275564  0.289619

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.308407  5.0  0.274400  0.289619
3751  1.002  0.308419  5.0  0.273815  0.289619
3752  1.002  0.308430  5.0  0.273228  0.289619
3753  1.003  0.308441  5.0  0.272639  0.289619

3750
interpolation

<lambdifygenerated-7693>:2: RuntimeWarning: invalid value encountered in power
  return x1*tanh((-_a7_ + x1**x1)**2)
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-7694>:2: RuntimeWarning: invalid value encountered in power
  return x1*tanh((-_a7_ + x1**x1)**2)

         x1         y  rep    ymodel      ybms
3745  0.997  0.215897  6.0  0.182064  0.237235
3746  0.998  0.216041  6.0  0.181805  0.237503
3747  0.998  0.216186  6.0  0.181545  0.237770
3748  0.999  0.216330  6.0  0.181286  0.238038

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.216618  6.0  0.180767  0.238572
3751  1.002  0.216762  6.0  0.180507  0.238839
3752  1.002  0.216905  6.0  0.180248  0.239106
3753  1.003  0.217048  6.0  0.179989  0.239373

3750
interpolation

/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(

         x1         y  rep    ymodel      ybms
3745  0.997  0.100918  7.0  0.044857  0.065126
3746  0.998  0.100912  7.0  0.044765  0.065065
3747  0.998  0.100906  7.0  0.044674  0.065005
3748  0.999  0.100901  7.0  0.044582  0.064945

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.100890  7.0  0.044402  0.064826
3751  1.002  0.100885  7.0  0.044312  0.064766
3752  1.002  0.100880  7.0  0.044223  0.064706
3753  1.003  0.100874  7.0  0.044134  0.064647

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.825595  8.0  0.713650  0.842607
3746  0.998  0.825925  8.0  0.713648  0.843180
3747  0.998  0.826254  8.0  0.713645  0.843754
3748  0.999  0.826582  8.0  0.713643  0.844328

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.827238  8.0  0.713638  0.845475
3751  1.002  0.827565  8.0  0.713635  0.846049
3752  1.002  0.827892  8.0  0.713633  0.846623
3753  1.003  0.828218  8.0  0.713630  0.847196

3750
interpolation

<lambdifygenerated-7775>:2: RuntimeWarning: invalid value encountered in power
  return x1*x1**x1
<lambdifygenerated-7776>:2: RuntimeWarning: invalid value encountered in power
  return x1*x1**x1

         x1         y  rep    ymodel      ybms
3745  0.997  0.855453  9.0  0.839954  0.825628
3746  0.998  0.855554  9.0  0.840435  0.825504
3747  0.998  0.855656  9.0  0.840918  0.825379
3748  0.999  0.855757  9.0  0.841402  0.825253

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.855960  9.0  0.842375  0.824999
3751  1.002  0.856062  9.0  0.842863  0.824871
3752  1.002  0.856163  9.0  0.843353  0.824743
3753  1.003  0.856265  9.0  0.843845  0.824613

3750
interpolation

/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(

         x1         y  rep    ymodel      ybms
3745  0.997  0.987381  0.0  1.009079  1.009246
3746  0.998  0.987426  0.0  1.009212  1.009404
3747  0.998  0.987470  0.0  1.009345  1.009562
3748  0.999  0.987515  0.0  1.009478  1.009720

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.987604  0.0  1.009743  1.010037
3751  1.002  0.987648  0.0  1.009876  1.010195
3752  1.002  0.987692  0.0  1.010009  1.010353
3753  1.003  0.987737  0.0  1.010141  1.010511

3750
interpolation

<lambdifygenerated-7857>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1**x1 + exp(x1**2*(_a2_ + _a3_/x1))/_a7_)
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-7858>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1**x1 + exp(x1**2*(_a2_ + _a3_/x1))/_a7_)

         x1         y  rep    ymodel      ybms
3745  0.997  0.053138  1.0  0.054445  0.040785
3746  0.998  0.053057  1.0  0.054396  0.040743
3747  0.998  0.052975  1.0  0.054347  0.040701
3748  0.999  0.052894  1.0  0.054299  0.040660

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.052733  1.0  0.054202  0.040577
3751  1.002  0.052652  1.0  0.054155  0.040535
3752  1.002  0.052571  1.0  0.054107  0.040494
3753  1.003  0.052491  1.0  0.054060  0.040453

3750

<lambdifygenerated-7879>:2: RuntimeWarning: invalid value encountered in power
  return x1**2*x1**x1 + x1
<lambdifygenerated-7880>:2: RuntimeWarning: invalid value encountered in power
  return x1**2*x1**x1 + x1

interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.277484  2.0  0.301872  0.286385
3746  0.998  0.277627  2.0  0.302468  0.286821
3747  0.998  0.277770  2.0  0.303065  0.287256
3748  0.999  0.277912  2.0  0.303660  0.287690

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.278193  2.0  0.304851  0.288556
3751  1.002  0.278333  2.0  0.305446  0.288988
3752  1.002  0.278471  2.0  0.306040  0.289418
3753  1.003  0.278610  2.0  0.306634  0.289849

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.306760  3.0  0.315771  0.383523
3746  0.998  0.307033  3.0  0.316102  0.384478
3747  0.998  0.307306  3.0  0.316431  0.385435
3748  0.999  0.307578  3.0  0.316760  0.386395

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.308120  3.0  0.317417  0.388324
3751  1.002  0.308390  3.0  0.317744  0.389293
3752  1.002  0.308660  3.0  0.318071  0.390264
3753  1.003  0.308928  3.0  0.318397  0.391238

3750
interpolation

<lambdifygenerated-7935>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1
<lambdifygenerated-7936>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1
<lambdifygenerated-7937>:2: RuntimeWarning: invalid value encountered in power
  return (2*x1)**x1
<lambdifygenerated-7938>:2: RuntimeWarning: invalid value encountered in power
  return (2*x1)**x1
<lambdifygenerated-7939>:2: RuntimeWarning: invalid value encountered in power
  return (_a5_ + x1)**x1
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-7940>:2: RuntimeWarning: invalid value encountered in power
  return (_a5_ + x1)**x1
<lambdifygenerated-7941>:2: RuntimeWarning: invalid value encountered in power
  return (_a5_ + x1**x1)**x1
<lambdifygenerated-7942>:2: RuntimeWarning: invalid value encountered in power
  return (_a5_ + x1**x1)**x1
<lambdifygenerated-7943>:2: RuntimeWarning: invalid value encountered in power
  return (_a5_ + (x1**2)**x1)**x1
<lambdifygenerated-7945>:2: RuntimeWarning: overflow encountered in power
  return (_a5_ + (_a0_**2)**x1)**x1
<lambdifygenerated-7946>:2: RuntimeWarning: overflow encountered in power
  return (_a5_ + (_a0_**2)**x1)**x1
<lambdifygenerated-7947>:2: RuntimeWarning: overflow encountered in power
  return (_a5_ + (_a0_**2)**x1)**x1
<lambdifygenerated-7948>:2: RuntimeWarning: overflow encountered in power
  return (_a5_ + (_a0_**2)**x1)**x1
<lambdifygenerated-7949>:2: RuntimeWarning: overflow encountered in power
  return (_a5_ + (_a0_**2)**x1)**(-x1)
/usr/local/lib/python3.10/dist-packages/scipy/optimize/_minpack_py.py:1017: RuntimeWarning: overflow encountered in square
  cost = np.sum(infodict['fvec'] ** 2)
/usr/local/lib/python3.10/dist-packages/pandas/core/arraylike.py:399: RuntimeWarning: overflow encountered in square
  result = getattr(ufunc, method)(*inputs, **kwargs)
<lambdifygenerated-7950>:2: RuntimeWarning: overflow encountered in power
  return (_a5_ + (_a0_**2)**x1)**(-x1)
<lambdifygenerated-7951>:2: RuntimeWarning: overflow encountered in power
  return (_a5_ + (_a0_**2)**x1)**(-_a5_)
<lambdifygenerated-7952>:2: RuntimeWarning: overflow encountered in power
  return (_a5_ + (_a0_**2)**x1)**(-_a5_)
<lambdifygenerated-7953>:2: RuntimeWarning: overflow encountered in power
  return (_a5_ + (_a0_**2)**x1)**(-_a5_)
<lambdifygenerated-7954>:2: RuntimeWarning: overflow encountered in power
  return (_a5_ + (_a0_**2)**x1)**(-_a5_)
<lambdifygenerated-7955>:2: RuntimeWarning: overflow encountered in power
  return (_a5_ + (_a0_**2)**x1)**(-_a5_)
<lambdifygenerated-7956>:2: RuntimeWarning: overflow encountered in power
  return (_a5_ + (_a0_**2)**x1)**(-_a5_)

         x1         y  rep    ymodel      ybms
3745  0.997  0.965360  4.0  0.957644  0.951413
3746  0.998  0.965399  4.0  0.957625  0.951413
3747  0.998  0.965439  4.0  0.957607  0.951413
3748  0.999  0.965479  4.0  0.957588  0.951413

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.965559  4.0  0.957551  0.951413
3751  1.002  0.965598  4.0  0.957532  0.951413
3752  1.002  0.965638  4.0  0.957513  0.951414
3753  1.003  0.965678  4.0  0.957494  0.951414

3750

<lambdifygenerated-7965>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1 + x1**x1)
<lambdifygenerated-7966>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1 + x1**x1)
<lambdifygenerated-7969>:2: RuntimeWarning: invalid value encountered in power
  return x1*(_a5_**(x1**x1) + x1)
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-7970>:2: RuntimeWarning: invalid value encountered in power
  return x1*(_a5_**(x1**x1) + x1)
<lambdifygenerated-7971>:2: RuntimeWarning: invalid value encountered in power
  return x1*(_a5_**(_a3_**x1) + x1)

interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.308339  5.0  0.306020  0.306775
3746  0.998  0.308354  5.0  0.305910  0.306775
3747  0.998  0.308368  5.0  0.305800  0.306775
3748  0.999  0.308382  5.0  0.305689  0.306775

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.308407  5.0  0.305467  0.306775
3751  1.002  0.308419  5.0  0.305355  0.306775
3752  1.002  0.308430  5.0  0.305244  0.306775
3753  1.003  0.308441  5.0  0.305132  0.306775

3750
interpolation

<lambdifygenerated-7995>:2: RuntimeWarning: invalid value encountered in power
  return cos(_a1_*x1**x1)**2
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-7996>:2: RuntimeWarning: invalid value encountered in power
  return cos(_a1_*x1**x1)**2
<lambdifygenerated-8001>:2: RuntimeWarning: invalid value encountered in power
  return cos(_a1_*_a2_**(x1*x1**x1))**2
<lambdifygenerated-8002>:2: RuntimeWarning: invalid value encountered in power
  return cos(_a1_*_a2_**(x1*x1**x1))**2
<lambdifygenerated-8007>:2: RuntimeWarning: overflow encountered in power
  return cos(_a1_*_a2_**(_a0_*_a2_**x1))**2
<lambdifygenerated-8007>:2: RuntimeWarning: overflow encountered in multiply
  return cos(_a1_*_a2_**(_a0_*_a2_**x1))**2
<lambdifygenerated-8007>:2: RuntimeWarning: invalid value encountered in cos
  return cos(_a1_*_a2_**(_a0_*_a2_**x1))**2

         x1         y  rep    ymodel      ybms
3745  0.997  0.215897  6.0  0.205342  0.215668
3746  0.998  0.216041  6.0  0.205390  0.215788
3747  0.998  0.216186  6.0  0.205437  0.215908
3748  0.999  0.216330  6.0  0.205485  0.216028

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.216618  6.0  0.205579  0.216268
3751  1.002  0.216762  6.0  0.205626  0.216387
3752  1.002  0.216905  6.0  0.205673  0.216506
3753  1.003  0.217048  6.0  0.205720  0.216625

3750
interpolation

<lambdifygenerated-8037>:2: RuntimeWarning: overflow encountered in exp
  return exp(_a4_*abs(_a2_ + x1) + x1/_a2_)

         x1         y  rep    ymodel      ybms
3745  0.997  0.100918  7.0  0.088403  0.076707
3746  0.998  0.100912  7.0  0.088392  0.076644
3747  0.998  0.100906  7.0  0.088382  0.076582
3748  0.999  0.100901  7.0  0.088371  0.076519

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.100890  7.0  0.088351  0.076394
3751  1.002  0.100885  7.0  0.088341  0.076331
3752  1.002  0.100880  7.0  0.088331  0.076269
3753  1.003  0.100874  7.0  0.088321  0.076206

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.825595  8.0  0.799410  0.863318
3746  0.998  0.825925  8.0  0.799466  0.863915
3747  0.998  0.826254  8.0  0.799522  0.864511
3748  0.999  0.826582  8.0  0.799577  0.865107

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.827238  8.0  0.799684  0.866300
3751  1.002  0.827565  8.0  0.799736  0.866897
3752  1.002  0.827892  8.0  0.799788  0.867493
3753  1.003  0.828218  8.0  0.799838  0.868089

3750
interpolation

<lambdifygenerated-8081>:2: RuntimeWarning: invalid value encountered in power
  return _a5_/(x1 + x1**x1)
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-8082>:2: RuntimeWarning: invalid value encountered in power
  return _a5_/(x1 + x1**x1)
<lambdifygenerated-8087>:2: RuntimeWarning: invalid value encountered in power
  return _a5_/(_a6_**x1 + _a7_)

         x1         y  rep    ymodel      ybms
3745  0.997  0.855453  9.0  0.854746  0.870416
3746  0.998  0.855554  9.0  0.854795  0.870542
3747  0.998  0.855656  9.0  0.854843  0.870668
3748  0.999  0.855757  9.0  0.854891  0.870794

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.855960  9.0  0.854985  0.871045
3751  1.002  0.856062  9.0  0.855032  0.871170
3752  1.002  0.856163  9.0  0.855078  0.871294
3753  1.003  0.856265  9.0  0.855123  0.871419

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.987381  0.0  0.980275  0.999146
3746  0.998  0.987426  0.0  0.980251  0.999152
3747  0.998  0.987470  0.0  0.980226  0.999157
3748  0.999  0.987515  0.0  0.980200  0.999162

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.987604  0.0  0.980150  0.999173
3751  1.002  0.987648  0.0  0.980125  0.999178
3752  1.002  0.987692  0.0  0.980099  0.999183
3753  1.003  0.987737  0.0  0.980073  0.999188

3750

<lambdifygenerated-8133>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1
<lambdifygenerated-8134>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1

interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.053138  1.0  0.038155  0.082737
3746  0.998  0.053057  1.0  0.038050  0.083336
3747  0.998  0.052975  1.0  0.037946  0.083925
3748  0.999  0.052894  1.0  0.037841  0.084504

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.052733  1.0  0.037633  0.085635
3751  1.002  0.052652  1.0  0.037530  0.086188
3752  1.002  0.052571  1.0  0.037426  0.086732
3753  1.003  0.052491  1.0  0.037323  0.087268

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.277484  2.0  0.325111  0.332788
3746  0.998  0.277627  2.0  0.325662  0.333366
3747  0.998  0.277770  2.0  0.326212  0.333943
3748  0.999  0.277912  2.0  0.326762  0.334520

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.278193  2.0  0.327859  0.335671
3751  1.002  0.278333  2.0  0.328406  0.336245
3752  1.002  0.278471  2.0  0.328954  0.336819
3753  1.003  0.278610  2.0  0.329500  0.337391

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.306760  3.0  0.255103  0.325023
3746  0.998  0.307033  3.0  0.255186  0.325739
3747  0.998  0.307306  3.0  0.255269  0.326455
3748  0.999  0.307578  3.0  0.255351  0.327173

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.308120  3.0  0.255514  0.328612
3751  1.002  0.308390  3.0  0.255595  0.329333
3752  1.002  0.308660  3.0  0.255675  0.330056
3753  1.003  0.308928  3.0  0.255755  0.330780

3750

<lambdifygenerated-8237>:2: RuntimeWarning: invalid value encountered in power
  return x1*x1**x1
<lambdifygenerated-8238>:2: RuntimeWarning: invalid value encountered in power
  return x1*x1**x1

interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.965360  4.0  0.963228  0.956125
3746  0.998  0.965399  4.0  0.963234  0.956126
3747  0.998  0.965439  4.0  0.963240  0.956127
3748  0.999  0.965479  4.0  0.963246  0.956127

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.965559  4.0  0.963258  0.956129
3751  1.002  0.965598  4.0  0.963263  0.956129
3752  1.002  0.965638  4.0  0.963269  0.956130
3753  1.003  0.965678  4.0  0.963275  0.956131

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.308339  5.0  0.291272  0.297128
3746  0.998  0.308354  5.0  0.291287  0.297388
3747  0.998  0.308368  5.0  0.291301  0.297650
3748  0.999  0.308382  5.0  0.291316  0.297912

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.308407  5.0  0.291346  0.298441
3751  1.002  0.308419  5.0  0.291361  0.298707
3752  1.002  0.308430  5.0  0.291376  0.298974
3753  1.003  0.308441  5.0  0.291392  0.299242

3750
interpolation

<lambdifygenerated-8291>:2: RuntimeWarning: invalid value encountered in power
  return tanh(_a3_*x1**(-x1) + x1)**2
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-8292>:2: RuntimeWarning: invalid value encountered in power
  return tanh(_a3_*x1**(-x1) + x1)**2
<lambdifygenerated-8293>:2: RuntimeWarning: invalid value encountered in power
  return tanh(x1 + _a1_**(-x1)*_a3_)**2

         x1         y  rep    ymodel      ybms
3745  0.997  0.215897  6.0  0.205369  0.201854
3746  0.998  0.216041  6.0  0.205436  0.201995
3747  0.998  0.216186  6.0  0.205503  0.202135
3748  0.999  0.216330  6.0  0.205570  0.202276

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.216618  6.0  0.205703  0.202556
3751  1.002  0.216762  6.0  0.205770  0.202696
3752  1.002  0.216905  6.0  0.205836  0.202835
3753  1.003  0.217048  6.0  0.205903  0.202975

3750
interpolation

<lambdifygenerated-8311>:2: RuntimeWarning: invalid value encountered in power
  return x1**2*x1**(2*x1)
<lambdifygenerated-8312>:2: RuntimeWarning: invalid value encountered in power
  return x1**2*x1**(2*x1)
<lambdifygenerated-8315>:2: RuntimeWarning: invalid value encountered in power
  return x1**2*(_a7_*x1)**(2*x1)
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-8316>:2: RuntimeWarning: invalid value encountered in power
  return x1**2*(_a7_*x1)**(2*x1)
<lambdifygenerated-8321>:2: RuntimeWarning: invalid value encountered in power
  return x1**2*(_a7_*exp(x1))**(2*x1**x1)
<lambdifygenerated-8322>:2: RuntimeWarning: invalid value encountered in power
  return x1**2*(_a7_*exp(x1))**(2*x1**x1)

         x1         y  rep    ymodel      ybms
3745  0.997  0.100918  7.0  0.094396  0.075350
3746  0.998  0.100912  7.0  0.094387  0.075298
3747  0.998  0.100906  7.0  0.094379  0.075246
3748  0.999  0.100901  7.0  0.094371  0.075194

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.100890  7.0  0.094354  0.075091
3751  1.002  0.100885  7.0  0.094346  0.075039
3752  1.002  0.100880  7.0  0.094337  0.074987
3753  1.003  0.100874  7.0  0.094329  0.074936

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.825595  8.0  0.821792  0.876701
3746  0.998  0.825925  8.0  0.822009  0.877306
3747  0.998  0.826254  8.0  0.822225  0.877911
3748  0.999  0.826582  8.0  0.822440  0.878516

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.827238  8.0  0.822869  0.879726
3751  1.002  0.827565  8.0  0.823083  0.880331
3752  1.002  0.827892  8.0  0.823296  0.880935
3753  1.003  0.828218  8.0  0.823508  0.881540

3750
interpolation

<lambdifygenerated-8373>:2: RuntimeWarning: invalid value encountered in power
  return _a3_/(_a3_ + x1**x1)
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-8374>:2: RuntimeWarning: invalid value encountered in power
  return _a3_/(_a3_ + x1**x1)

         x1         y  rep    ymodel      ybms
3745  0.997  0.855453  9.0  0.871046  0.908238
3746  0.998  0.855554  9.0  0.871167  0.908407
3747  0.998  0.855656  9.0  0.871288  0.908575
3748  0.999  0.855757  9.0  0.871408  0.908744

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.855960  9.0  0.871649  0.909079
3751  1.002  0.856062  9.0  0.871769  0.909247
3752  1.002  0.856163  9.0  0.871889  0.909414
3753  1.003  0.856265  9.0  0.872009  0.909581

3750

<lambdifygenerated-8393>:2: RuntimeWarning: invalid value encountered in power
  return tanh(x1**x1)/x1
<lambdifygenerated-8394>:2: RuntimeWarning: invalid value encountered in power
  return tanh(x1**x1)/x1
<lambdifygenerated-8395>:2: RuntimeWarning: overflow encountered in power
  return tanh(_a0_**x1)/x1
/usr/local/lib/python3.10/dist-packages/scipy/optimize/_minpack_py.py:497: RuntimeWarning: overflow encountered in matmul
  cov_x = invR @ invR.T
<lambdifygenerated-8396>:2: RuntimeWarning: overflow encountered in power
  return tanh(_a0_**x1)/x1
<lambdifygenerated-8397>:2: RuntimeWarning: overflow encountered in power
  return tanh(_a0_**x1)/x1
<lambdifygenerated-8398>:2: RuntimeWarning: overflow encountered in power
  return tanh(_a0_**x1)/x1
<lambdifygenerated-8399>:2: RuntimeWarning: overflow encountered in power
  return tanh(_a0_**x1)/fac(x1)
<lambdifygenerated-8399>:2: RuntimeWarning: divide by zero encountered in divide
  return tanh(_a0_**x1)/fac(x1)
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-8400>:2: RuntimeWarning: overflow encountered in power
  return tanh(_a0_**x1)/fac(x1)
<lambdifygenerated-8400>:2: RuntimeWarning: divide by zero encountered in divide
  return tanh(_a0_**x1)/fac(x1)
<lambdifygenerated-8401>:2: RuntimeWarning: overflow encountered in power
  return tanh(_a0_**x1)/fac(x1**2)
<lambdifygenerated-8401>:2: RuntimeWarning: invalid value encountered in power
  return tanh(_a0_**x1)/fac(x1**2)

interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.987381  0.0  0.986315  0.941473
3746  0.998  0.987426  0.0  0.986396  0.940933
3747  0.998  0.987470  0.0  0.986476  0.940392
3748  0.999  0.987515  0.0  0.986557  0.939849

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.987604  0.0  0.986718  0.938757
3751  1.002  0.987648  0.0  0.986798  0.938209
3752  1.002  0.987692  0.0  0.986878  0.937658
3753  1.003  0.987737  0.0  0.986958  0.937106

3750
interpolation

<lambdifygenerated-8421>:2: RuntimeWarning: invalid value encountered in power
  return _a7_*x1**(-x1) + x1
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-8422>:2: RuntimeWarning: invalid value encountered in power
  return _a7_*x1**(-x1) + x1
<lambdifygenerated-8423>:2: RuntimeWarning: invalid value encountered in power
  return _a7_*(x1**x1)**(-x1) + x1
<lambdifygenerated-8424>:2: RuntimeWarning: invalid value encountered in power
  return _a7_*(x1**x1)**(-x1) + x1
<lambdifygenerated-8425>:2: RuntimeWarning: invalid value encountered in power
  return _a7_*(_a7_**x1)**(-x1) + x1
<lambdifygenerated-8426>:2: RuntimeWarning: invalid value encountered in power
  return _a7_*(_a7_**x1)**(-x1) + x1
<lambdifygenerated-8427>:2: RuntimeWarning: invalid value encountered in power
  return _a7_*(_a7_**(x1**x1))**(-x1) + x1
<lambdifygenerated-8428>:2: RuntimeWarning: invalid value encountered in power
  return _a7_*(_a7_**(x1**x1))**(-x1) + x1
<lambdifygenerated-8429>:2: RuntimeWarning: invalid value encountered in power
  return _a7_*(_a7_**(_a5_**x1))**(-x1) + x1
<lambdifygenerated-8430>:2: RuntimeWarning: invalid value encountered in power
  return _a7_*(_a7_**(_a5_**x1))**(-x1) + x1
<lambdifygenerated-8431>:2: RuntimeWarning: invalid value encountered in power
  return _a7_*(_a7_**(_a5_**x1))**(-x1) + x1
<lambdifygenerated-8432>:2: RuntimeWarning: invalid value encountered in power
  return _a7_*(_a7_**(_a5_**x1))**(-x1) + x1
<lambdifygenerated-8433>:2: RuntimeWarning: invalid value encountered in power
  return _a7_*(_a7_**(_a5_**x1))**(-x1) + x1
<lambdifygenerated-8434>:2: RuntimeWarning: invalid value encountered in power
  return _a7_*(_a7_**(_a5_**x1))**(-x1) + x1
<lambdifygenerated-8435>:2: RuntimeWarning: invalid value encountered in power
  return _a7_*(_a7_**(_a5_**x1))**(-x1) + 2*x1
<lambdifygenerated-8436>:2: RuntimeWarning: invalid value encountered in power
  return _a7_*(_a7_**(_a5_**x1))**(-x1) + 2*x1
<lambdifygenerated-8437>:2: RuntimeWarning: invalid value encountered in power
  return _a1_ + _a7_*(_a7_**(_a5_**x1))**(-x1) + x1
<lambdifygenerated-8438>:2: RuntimeWarning: invalid value encountered in power
  return _a1_ + _a7_*(_a7_**(_a5_**x1))**(-x1) + x1
<lambdifygenerated-8439>:2: RuntimeWarning: invalid value encountered in power
  return _a1_ + _a7_*(_a7_**(_a5_**x1))**(-x1) + x1**2
<lambdifygenerated-8440>:2: RuntimeWarning: invalid value encountered in power
  return _a1_ + _a7_*(_a7_**(_a5_**x1))**(-x1) + x1**2
<lambdifygenerated-8441>:2: RuntimeWarning: invalid value encountered in power
  return _a1_ + _a5_*x1 + _a7_*(_a7_**(_a5_**x1))**(-x1)
<lambdifygenerated-8442>:2: RuntimeWarning: invalid value encountered in power
  return _a1_ + _a5_*x1 + _a7_*(_a7_**(_a5_**x1))**(-x1)
<lambdifygenerated-8443>:2: RuntimeWarning: invalid value encountered in power
  return _a1_ + _a5_*x1**2 + _a7_*(_a7_**(_a5_**x1))**(-x1)
<lambdifygenerated-8444>:2: RuntimeWarning: invalid value encountered in power
  return _a1_ + _a5_*x1**2 + _a7_*(_a7_**(_a5_**x1))**(-x1)
<lambdifygenerated-8445>:2: RuntimeWarning: invalid value encountered in power
  return _a1_ + _a5_*x1**2 + _a7_*(_a7_**(_a5_**x1))**(-x1)
<lambdifygenerated-8446>:2: RuntimeWarning: invalid value encountered in power
  return _a1_ + _a5_*x1**2 + _a7_*(_a7_**(_a5_**x1))**(-x1)
<lambdifygenerated-8447>:2: RuntimeWarning: invalid value encountered in power
  return _a1_ + _a5_*_a6_*x1 + _a7_*(_a7_**(_a5_**x1))**(-x1)
<lambdifygenerated-8448>:2: RuntimeWarning: invalid value encountered in power
  return _a1_ + _a5_*_a6_*x1 + _a7_*(_a7_**(_a5_**x1))**(-x1)
<lambdifygenerated-8449>:2: RuntimeWarning: invalid value encountered in power
  return _a1_ + _a5_*_a6_*x1 + _a7_*(_a7_**(_a5_**x1))**(-x1)
<lambdifygenerated-8450>:2: RuntimeWarning: invalid value encountered in power
  return _a1_ + _a5_*_a6_*x1 + _a7_*(_a7_**(_a5_**x1))**(-x1)
<lambdifygenerated-8451>:2: RuntimeWarning: invalid value encountered in power
  return _a1_ + _a5_*_a6_*x1 + _a7_*(_a7_**(_a5_**x1))**(-x1)
<lambdifygenerated-8452>:2: RuntimeWarning: invalid value encountered in power
  return _a1_ + _a5_*_a6_*x1 + _a7_*(_a7_**(_a5_**x1))**(-x1)

         x1         y  rep    ymodel      ybms
3745  0.997  0.053138  1.0  0.002416 -0.002229
3746  0.998  0.053057  1.0  0.002180 -0.002553
3747  0.998  0.052975  1.0  0.001944 -0.002877
3748  0.999  0.052894  1.0  0.001708 -0.003200

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.052733  1.0  0.001237 -0.003848
3751  1.002  0.052652  1.0  0.001002 -0.004171
3752  1.002  0.052571  1.0  0.000767 -0.004495
3753  1.003  0.052491  1.0  0.000532 -0.004819

3750
interpolation

/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(

         x1         y  rep    ymodel      ybms
3745  0.997  0.277484  2.0  0.347787  0.294249
3746  0.998  0.277627  2.0  0.348440  0.294630
3747  0.998  0.277770  2.0  0.349092  0.295011
3748  0.999  0.277912  2.0  0.349745  0.295392

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.278193  2.0  0.351049  0.296152
3751  1.002  0.278333  2.0  0.351702  0.296532
3752  1.002  0.278471  2.0  0.352353  0.296912
3753  1.003  0.278610  2.0  0.353005  0.297291

<lambdifygenerated-8479>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1
<lambdifygenerated-8480>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.306760  3.0  0.363609  0.378711
3746  0.998  0.307033  3.0  0.363969  0.379380
3747  0.998  0.307306  3.0  0.364328  0.380050
3748  0.999  0.307578  3.0  0.364687  0.380721

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.308120  3.0  0.365403  0.382065
3751  1.002  0.308390  3.0  0.365761  0.382738
3752  1.002  0.308660  3.0  0.366118  0.383413
3753  1.003  0.308928  3.0  0.366475  0.384088

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.965360  4.0  0.951789  0.951781
3746  0.998  0.965399  4.0  0.951741  0.951781
3747  0.998  0.965439  4.0  0.951693  0.951781
3748  0.999  0.965479  4.0  0.951644  0.951781

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.965559  4.0  0.951548  0.951781
3751  1.002  0.965598  4.0  0.951500  0.951781
3752  1.002  0.965638  4.0  0.951451  0.951781
3753  1.003  0.965678  4.0  0.951403  0.951781

3750
interpolation

<lambdifygenerated-8531>:2: RuntimeWarning: invalid value encountered in power
  return x1*x1**x1 + x1
<lambdifygenerated-8532>:2: RuntimeWarning: invalid value encountered in power
  return x1*x1**x1 + x1
<lambdifygenerated-8535>:2: RuntimeWarning: invalid value encountered in power
  return _a3_**exp(x1)*x1 + x1
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-8541>:2: RuntimeWarning: invalid value encountered in power
  return _a3_**exp(x1/_a1_)*x1 + x1
<lambdifygenerated-8545>:2: RuntimeWarning: overflow encountered in power
  return _a1_ + _a2_*_a3_**exp(x1/_a1_)

         x1         y  rep    ymodel      ybms
3745  0.997  0.308339  5.0  0.300486  0.269467
3746  0.998  0.308354  5.0  0.300508  0.269467
3747  0.998  0.308368  5.0  0.300530  0.269467
3748  0.999  0.308382  5.0  0.300551  0.269467

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.308407  5.0  0.300594  0.269467
3751  1.002  0.308419  5.0  0.300616  0.269467
3752  1.002  0.308430  5.0  0.300637  0.269467
3753  1.003  0.308441  5.0  0.300658  0.269467

3750
interpolation

<lambdifygenerated-8561>:2: RuntimeWarning: invalid value encountered in power
  return tanh(x1 + x1**x1)**2
<lambdifygenerated-8562>:2: RuntimeWarning: invalid value encountered in power
  return tanh(x1 + x1**x1)**2
<lambdifygenerated-8565>:2: RuntimeWarning: invalid value encountered in power
  return tanh(_a3_**(2*x1) + x1)**2
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(

         x1         y  rep    ymodel      ybms
3745  0.997  0.215897  6.0  0.186770  0.211402
3746  0.998  0.216041  6.0  0.186817  0.211535
3747  0.998  0.216186  6.0  0.186863  0.211668
3748  0.999  0.216330  6.0  0.186909  0.211800

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.216618  6.0  0.187002  0.212064
3751  1.002  0.216762  6.0  0.187048  0.212196
3752  1.002  0.216905  6.0  0.187093  0.212328
3753  1.003  0.217048  6.0  0.187139  0.212460

3750
interpolation

<lambdifygenerated-8583>:2: RuntimeWarning: invalid value encountered in power
  return x1*x1**x1
<lambdifygenerated-8584>:2: RuntimeWarning: invalid value encountered in power
  return x1*x1**x1
<lambdifygenerated-8587>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1**3)**x1
<lambdifygenerated-8588>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1**3)**x1
<lambdifygenerated-8589>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1*exp(2*x1))**x1
<lambdifygenerated-8590>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1*exp(2*x1))**x1
<lambdifygenerated-8591>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1*exp(2*x1))**x1
<lambdifygenerated-8592>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1*exp(2*x1))**x1
<lambdifygenerated-8595>:2: RuntimeWarning: invalid value encountered in power
  return x1*(_a4_*exp(2*x1))**(x1**x1)
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-8596>:2: RuntimeWarning: invalid value encountered in power
  return x1*(_a4_*exp(2*x1))**(x1**x1)
<lambdifygenerated-8597>:2: RuntimeWarning: invalid value encountered in power
  return x1*(_a4_*exp(2*x1))**(_a3_**x1)

         x1         y  rep    ymodel      ybms
3745  0.997  0.100918  7.0  0.048171  0.073273
3746  0.998  0.100912  7.0  0.048047  0.073222
3747  0.998  0.100906  7.0  0.047923  0.073171
3748  0.999  0.100901  7.0  0.047799  0.073120

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.100890  7.0  0.047552  0.073019
3751  1.002  0.100885  7.0  0.047429  0.072969
3752  1.002  0.100880  7.0  0.047306  0.072918
3753  1.003  0.100874  7.0  0.047183  0.072868

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.825595  8.0  0.750519  0.858454
3746  0.998  0.825925  8.0  0.750670  0.859037
3747  0.998  0.826254  8.0  0.750821  0.859620
3748  0.999  0.826582  8.0  0.750971  0.860203

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.827238  8.0  0.751270  0.861369
3751  1.002  0.827565  8.0  0.751420  0.861952
3752  1.002  0.827892  8.0  0.751568  0.862535
3753  1.003  0.828218  8.0  0.751717  0.863118

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.855453  9.0  0.871902  0.871609
3746  0.998  0.855554  9.0  0.871998  0.871733
3747  0.998  0.855656  9.0  0.872093  0.871855
3748  0.999  0.855757  9.0  0.872188  0.871978

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.855960  9.0  0.872377  0.872223
3751  1.002  0.856062  9.0  0.872471  0.872345
3752  1.002  0.856163  9.0  0.872564  0.872467
3753  1.003  0.856265  9.0  0.872658  0.872588

3750
interpolation

/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(

         x1         y  rep    ymodel      ybms
3745  0.997  0.987381  0.0  0.945067  0.899276
3746  0.998  0.987426  0.0  0.944914  0.898621
3747  0.998  0.987470  0.0  0.944760  0.897964
3748  0.999  0.987515  0.0  0.944606  0.897305

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.987604  0.0  0.944296  0.895981
3751  1.002  0.987648  0.0  0.944141  0.895316
3752  1.002  0.987692  0.0  0.943985  0.894649
3753  1.003  0.987737  0.0  0.943829  0.893979

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.053138  1.0  0.036241  0.068635
3746  0.998  0.053057  1.0  0.036160  0.068840
3747  0.998  0.052975  1.0  0.036079  0.069046
3748  0.999  0.052894  1.0  0.035998  0.069254

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.052733  1.0  0.035837  0.069674
3751  1.002  0.052652  1.0  0.035757  0.069885
3752  1.002  0.052571  1.0  0.035678  0.070098
3753  1.003  0.052491  1.0  0.035598  0.070313

3750
interpolation

/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(

         x1         y  rep    ymodel      ybms
3745  0.997  0.277484  2.0  0.334605  0.303568
3746  0.998  0.277627  2.0  0.335205  0.303702
3747  0.998  0.277770  2.0  0.335805  0.303831
3748  0.999  0.277912  2.0  0.336404  0.303956

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.278193  2.0  0.337599  0.304192
3751  1.002  0.278333  2.0  0.338195  0.304304
3752  1.002  0.278471  2.0  0.338790  0.304410
3753  1.003  0.278610  2.0  0.339384  0.304512

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.306760  3.0  0.301632  0.367147
3746  0.998  0.307033  3.0  0.301880  0.367941
3747  0.998  0.307306  3.0  0.302127  0.368736
3748  0.999  0.307578  3.0  0.302374  0.369533

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.308120  3.0  0.302867  0.371130
3751  1.002  0.308390  3.0  0.303113  0.371931
3752  1.002  0.308660  3.0  0.303358  0.372733
3753  1.003  0.308928  3.0  0.303604  0.373536

3750
interpolation

<lambdifygenerated-8791>:2: RuntimeWarning: invalid value encountered in power
  return _a1_/(x1 + x1**x1)
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-8792>:2: RuntimeWarning: invalid value encountered in power
  return _a1_/(x1 + x1**x1)

         x1         y  rep    ymodel      ybms
3745  0.997  0.965360  4.0  0.993197  0.960096
3746  0.998  0.965399  4.0  0.993287  0.960096
3747  0.998  0.965439  4.0  0.993377  0.960096
3748  0.999  0.965479  4.0  0.993468  0.960097

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.965559  4.0  0.993648  0.960097
3751  1.002  0.965598  4.0  0.993738  0.960097
3752  1.002  0.965638  4.0  0.993828  0.960097
3753  1.003  0.965678  4.0  0.993918  0.960097

3750
interpolation

<lambdifygenerated-8813>:2: RuntimeWarning: invalid value encountered in power
  return x1*x1**x1 + x1
<lambdifygenerated-8814>:2: RuntimeWarning: invalid value encountered in power
  return x1*x1**x1 + x1
<lambdifygenerated-8817>:2: RuntimeWarning: invalid value encountered in power
  return _a0_**(x1**x1)*x1 + x1
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-8818>:2: RuntimeWarning: invalid value encountered in power
  return _a0_**(x1**x1)*x1 + x1
<lambdifygenerated-8819>:2: RuntimeWarning: invalid value encountered in power
  return _a0_**(_a2_**x1)*x1 + x1

         x1         y  rep    ymodel      ybms
3745  0.997  0.308339  5.0  0.294359  0.291967
3746  0.998  0.308354  5.0  0.294356  0.291967
3747  0.998  0.308368  5.0  0.294352  0.291967
3748  0.999  0.308382  5.0  0.294349  0.291967

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.308407  5.0  0.294342  0.291967
3751  1.002  0.308419  5.0  0.294338  0.291967
3752  1.002  0.308430  5.0  0.294334  0.291967
3753  1.003  0.308441  5.0  0.294331  0.291967

3750
interpolation

<lambdifygenerated-8835>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1
<lambdifygenerated-8836>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1

         x1         y  rep    ymodel      ybms
3745  0.997  0.215897  6.0  0.231807  0.300932
3746  0.998  0.216041  6.0  0.232005  0.301725
3747  0.998  0.216186  6.0  0.232202  0.302521
3748  0.999  0.216330  6.0  0.232399  0.303318

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.216618  6.0  0.232792  0.304918
3751  1.002  0.216762  6.0  0.232989  0.305720
3752  1.002  0.216905  6.0  0.233185  0.306524
3753  1.003  0.217048  6.0  0.233381  0.307330

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.100918  7.0  0.093467  0.069572
3746  0.998  0.100912  7.0  0.093496  0.069553
3747  0.998  0.100906  7.0  0.093525  0.069533
3748  0.999  0.100901  7.0  0.093553  0.069514

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.100890  7.0  0.093610  0.069475
3751  1.002  0.100885  7.0  0.093639  0.069456
3752  1.002  0.100880  7.0  0.093667  0.069437
3753  1.003  0.100874  7.0  0.093696  0.069419

3750
interpolation

<lambdifygenerated-8893>:2: RuntimeWarning: invalid value encountered in power
  return x1 + x1**x1
<lambdifygenerated-8894>:2: RuntimeWarning: invalid value encountered in power
  return x1 + x1**x1
<lambdifygenerated-8903>:2: RuntimeWarning: invalid value encountered in power
  return _a7_**exp(_a3_*x1) + x1
<lambdifygenerated-8905>:2: RuntimeWarning: invalid value encountered in power
  return _a7_ + _a7_**exp(_a3_*x1)

         x1         y  rep    ymodel      ybms
3745  0.997  0.825595  8.0  0.798993  0.826799
3746  0.998  0.825925  8.0  0.799291  0.827180
3747  0.998  0.826254  8.0  0.799589  0.827561
3748  0.999  0.826582  8.0  0.799887  0.827941

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.827238  8.0  0.800481  0.828700
3751  1.002  0.827565  8.0  0.800778  0.829078
3752  1.002  0.827892  8.0  0.801074  0.829457
3753  1.003  0.828218  8.0  0.801370  0.829834

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.855453  9.0  0.882960  0.908448
3746  0.998  0.855554  9.0  0.883118  0.908618
3747  0.998  0.855656  9.0  0.883277  0.908787
3748  0.999  0.855757  9.0  0.883435  0.908956

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.855960  9.0  0.883751  0.909293
3751  1.002  0.856062  9.0  0.883908  0.909461
3752  1.002  0.856163  9.0  0.884066  0.909629
3753  1.003  0.856265  9.0  0.884223  0.909796

3750
interpolation

/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-8955>:2: RuntimeWarning: invalid value encountered in power
  return (_a0_ + x1)/(_a3_*(_a5_ + x1**x1))
<lambdifygenerated-8956>:2: RuntimeWarning: invalid value encountered in power
  return (_a0_ + x1)/(_a3_*(_a5_ + x1**x1))

         x1         y  rep    ymodel      ybms
3745  0.997  0.987381  0.0  1.047162  1.020623
3746  0.998  0.987426  0.0  1.047336  1.020785
3747  0.998  0.987470  0.0  1.047509  1.020947
3748  0.999  0.987515  0.0  1.047683  1.021109

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.987604  0.0  1.048030  1.021433
3751  1.002  0.987648  0.0  1.048203  1.021595
3752  1.002  0.987692  0.0  1.048377  1.021756
3753  1.003  0.987737  0.0  1.048550  1.021918

3750
interpolation

/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(

         x1         y  rep    ymodel      ybms
3745  0.997  0.053138  1.0  0.108327  0.115241
3746  0.998  0.053057  1.0  0.108370  0.115337
3747  0.998  0.052975  1.0  0.108413  0.115434
3748  0.999  0.052894  1.0  0.108455  0.115531

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.052733  1.0  0.108541  0.115725
3751  1.002  0.052652  1.0  0.108584  0.115823
3752  1.002  0.052571  1.0  0.108627  0.115922
3753  1.003  0.052491  1.0  0.108670  0.116020

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.277484  2.0  0.288313  0.321223
3746  0.998  0.277627  2.0  0.288636  0.321850
3747  0.998  0.277770  2.0  0.288957  0.322477
3748  0.999  0.277912  2.0  0.289278  0.323104

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.278193  2.0  0.289917  0.324360
3751  1.002  0.278333  2.0  0.290235  0.324988
3752  1.002  0.278471  2.0  0.290552  0.325617
3753  1.003  0.278610  2.0  0.290869  0.326246

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.306760  3.0  0.320361  0.373204
3746  0.998  0.307033  3.0  0.320601  0.374000
3747  0.998  0.307306  3.0  0.320841  0.374796
3748  0.999  0.307578  3.0  0.321081  0.375594

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.308120  3.0  0.321558  0.377194
3751  1.002  0.308390  3.0  0.321796  0.377996
3752  1.002  0.308660  3.0  0.322034  0.378799
3753  1.003  0.308928  3.0  0.322271  0.379604

3750
interpolation

<lambdifygenerated-9073>:2: RuntimeWarning: invalid value encountered in power
  return x1*tanh(x1*x1**x1)**2
<lambdifygenerated-9074>:2: RuntimeWarning: invalid value encountered in power
  return x1*tanh(x1*x1**x1)**2
<lambdifygenerated-9075>:2: RuntimeWarning: overflow encountered in multiply
  return x1*tanh(_a1_**x1*x1)**2
<lambdifygenerated-9075>:2: RuntimeWarning: overflow encountered in power
  return x1*tanh(_a1_**x1*x1)**2
/usr/local/lib/python3.10/dist-packages/scipy/optimize/_minpack_py.py:497: RuntimeWarning: overflow encountered in matmul
  cov_x = invR @ invR.T
<lambdifygenerated-9076>:2: RuntimeWarning: overflow encountered in power
  return x1*tanh(_a1_**x1*x1)**2
<lambdifygenerated-9076>:2: RuntimeWarning: overflow encountered in multiply
  return x1*tanh(_a1_**x1*x1)**2
<lambdifygenerated-9077>:2: RuntimeWarning: overflow encountered in power
  return x1*tanh(_a1_**x1*x1)**2
<lambdifygenerated-9077>:2: RuntimeWarning: overflow encountered in multiply
  return x1*tanh(_a1_**x1*x1)**2
<lambdifygenerated-9078>:2: RuntimeWarning: overflow encountered in power
  return x1*tanh(_a1_**x1*x1)**2
<lambdifygenerated-9078>:2: RuntimeWarning: overflow encountered in multiply
  return x1*tanh(_a1_**x1*x1)**2
<lambdifygenerated-9079>:2: RuntimeWarning: overflow encountered in power
  return x1*tanh(_a1_**x1*_a6_)**2
<lambdifygenerated-9079>:2: RuntimeWarning: overflow encountered in multiply
  return x1*tanh(_a1_**x1*_a6_)**2
<lambdifygenerated-9080>:2: RuntimeWarning: overflow encountered in power
  return x1*tanh(_a1_**x1*_a6_)**2
<lambdifygenerated-9081>:2: RuntimeWarning: overflow encountered in power
  return _a6_*tanh(_a1_**x1*_a6_)**2
<lambdifygenerated-9081>:2: RuntimeWarning: invalid value encountered in power
  return _a6_*tanh(_a1_**x1*_a6_)**2

         x1         y  rep    ymodel      ybms
3745  0.997  0.965360  4.0  0.945807  0.932198
3746  0.998  0.965399  4.0  0.945762  0.932198
3747  0.998  0.965439  4.0  0.945717  0.932198
3748  0.999  0.965479  4.0  0.945671  0.932198

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.965559  4.0  0.945579  0.932198
3751  1.002  0.965598  4.0  0.945533  0.932198
3752  1.002  0.965638  4.0  0.945487  0.932198
3753  1.003  0.965678  4.0  0.945440  0.932198

3750

<lambdifygenerated-9099>:2: RuntimeWarning: invalid value encountered in power
  return x1 + exp(x1*(x1 + x1**x1))
<lambdifygenerated-9100>:2: RuntimeWarning: invalid value encountered in power
  return x1 + exp(x1*(x1 + x1**x1))
<lambdifygenerated-9101>:2: RuntimeWarning: invalid value encountered in power
  return x1 + exp(x1*(_a2_**x1 + x1))
<lambdifygenerated-9107>:2: RuntimeWarning: overflow encountered in exp
  return x1 + exp(_a3_*(_a1_ + _a2_**x1))
<lambdifygenerated-9107>:2: RuntimeWarning: invalid value encountered in power
  return x1 + exp(_a3_*(_a1_ + _a2_**x1))
<lambdifygenerated-9109>:2: RuntimeWarning: overflow encountered in exp
  return _a0_ + exp(_a3_*(_a1_ + _a2_**x1))
<lambdifygenerated-9113>:2: RuntimeWarning: overflow encountered in exp
  return _a0_ + exp(_a3_*(_a1_ + _a2_**x1))

interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.308339  5.0  0.328018  0.294225
3746  0.998  0.308354  5.0  0.327990  0.294225
3747  0.998  0.308368  5.0  0.327961  0.294225
3748  0.999  0.308382  5.0  0.327930  0.294225

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.308407  5.0  0.327864  0.294225
3751  1.002  0.308419  5.0  0.327828  0.294225
3752  1.002  0.308430  5.0  0.327791  0.294225
3753  1.003  0.308441  5.0  0.327753  0.294225

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.215897  6.0  0.248599  0.202260
3746  0.998  0.216041  6.0  0.248848  0.202439
3747  0.998  0.216186  6.0  0.249096  0.202618
3748  0.999  0.216330  6.0  0.249344  0.202797

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.216618  6.0  0.249838  0.203155
3751  1.002  0.216762  6.0  0.250085  0.203334
3752  1.002  0.216905  6.0  0.250331  0.203512
3753  1.003  0.217048  6.0  0.250576  0.203691

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.100918  7.0  0.113963  0.088324
3746  0.998  0.100912  7.0  0.114037  0.088275
3747  0.998  0.100906  7.0  0.114110  0.088226
3748  0.999  0.100901  7.0  0.114183  0.088176

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.100890  7.0  0.114330  0.088078
3751  1.002  0.100885  7.0  0.114403  0.088029
3752  1.002  0.100880  7.0  0.114476  0.087980
3753  1.003  0.100874  7.0  0.114550  0.087931

3750
interpolation

<lambdifygenerated-9185>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1 + x1**x1) + x1
<lambdifygenerated-9186>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1 + x1**x1) + x1

         x1         y  rep    ymodel      ybms
3745  0.997  0.825595  8.0  0.867608  0.865958
3746  0.998  0.825925  8.0  0.868077  0.866523
3747  0.998  0.826254  8.0  0.868545  0.867088
3748  0.999  0.826582  8.0  0.869012  0.867652

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.827238  8.0  0.869945  0.868782
3751  1.002  0.827565  8.0  0.870411  0.869346
3752  1.002  0.827892  8.0  0.870876  0.869911
3753  1.003  0.828218  8.0  0.871340  0.870475

3750
interpolation

<lambdifygenerated-9217>:2: RuntimeWarning: invalid value encountered in power
  return _a6_/(_a5_ + x1*x1**x1)
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-9218>:2: RuntimeWarning: invalid value encountered in power
  return _a6_/(_a5_ + x1*x1**x1)
<lambdifygenerated-9219>:2: RuntimeWarning: invalid value encountered in power
  return _a6_/(_a5_ + _a6_**x1*x1)
<lambdifygenerated-9223>:2: RuntimeWarning: invalid value encountered in power
  return _a6_/(_a5_ + _a6_*_a6_**x1)

         x1         y  rep    ymodel      ybms
3745  0.997  0.855453  9.0  0.820225  0.865541
3746  0.998  0.855554  9.0  0.819980  0.865627
3747  0.998  0.855656  9.0  0.819734  0.865713
3748  0.999  0.855757  9.0  0.819487  0.865799

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.855960  9.0  0.818988  0.865971
3751  1.002  0.856062  9.0  0.818737  0.866056
3752  1.002  0.856163  9.0  0.818485  0.866142
3753  1.003  0.856265  9.0  0.818231  0.866227

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.987381  0.0  1.028617  0.940276
3746  0.998  0.987426  0.0  1.028733  0.939659
3747  0.998  0.987470  0.0  1.028849  0.939041
3748  0.999  0.987515  0.0  1.028965  0.938420

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.987604  0.0  1.029197  0.937173
3751  1.002  0.987648  0.0  1.029312  0.936546
3752  1.002  0.987692  0.0  1.029428  0.935917
3753  1.003  0.987737  0.0  1.029544  0.935287

3750
interpolation

<lambdifygenerated-9265>:2: RuntimeWarning: invalid value encountered in power
  return abs(x1*x1**x1 + x1)
<lambdifygenerated-9266>:2: RuntimeWarning: invalid value encountered in power
  return abs(x1*x1**x1 + x1)

         x1         y  rep    ymodel      ybms
3745  0.997  0.053138  1.0  0.031228  0.113718
3746  0.998  0.053057  1.0  0.031126  0.114233
3747  0.998  0.052975  1.0  0.031023  0.114749
3748  0.999  0.052894  1.0  0.030922  0.115265

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.052733  1.0  0.030719  0.116296
3751  1.002  0.052652  1.0  0.030618  0.116811
3752  1.002  0.052571  1.0  0.030517  0.117326
3753  1.003  0.052491  1.0  0.030416  0.117841

3750
interpolation

<lambdifygenerated-9299>:2: RuntimeWarning: invalid value encountered in power
  return x1*x1**x1 + x1
<lambdifygenerated-9300>:2: RuntimeWarning: invalid value encountered in power
  return x1*x1**x1 + x1
<lambdifygenerated-9303>:2: RuntimeWarning: invalid value encountered in power
  return _a2_**(x1**x1)*x1 + x1
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-9304>:2: RuntimeWarning: invalid value encountered in power
  return _a2_**(x1**x1)*x1 + x1
<lambdifygenerated-9305>:2: RuntimeWarning: invalid value encountered in power
  return _a2_**(_a3_**x1)*x1 + x1
<lambdifygenerated-9309>:2: RuntimeWarning: invalid value encountered in power
  return _a0_*_a2_**(_a3_**x1) + x1
<lambdifygenerated-9311>:2: RuntimeWarning: invalid value encountered in power
  return _a0_*_a2_**(_a3_**x1) + 2*x1
<lambdifygenerated-9313>:2: RuntimeWarning: invalid value encountered in power
  return _a0_*_a2_**(_a3_**x1) + x1 + cos(x1)
<lambdifygenerated-9315>:2: RuntimeWarning: invalid value encountered in power
  return _a0_*_a2_**(_a3_**x1) + x1 + cos(2*x1)
<lambdifygenerated-9319>:2: RuntimeWarning: invalid value encountered in power
  return _a0_*_a2_**(_a3_**x1) + x1 + cos(_a3_ + x1)
<lambdifygenerated-9321>:2: RuntimeWarning: invalid value encountered in power
  return _a0_*_a2_**(_a3_**x1) + _a6_ + cos(_a3_ + x1)
<lambdifygenerated-9325>:2: RuntimeWarning: invalid value encountered in power
  return _a0_*_a2_**(_a3_**x1) + _a6_ + cos(_a3_ + x1)

         x1         y  rep    ymodel      ybms
3745  0.997  0.277484  2.0  0.240492  0.313886
3746  0.998  0.277627  2.0  0.240381  0.314409
3747  0.998  0.277770  2.0  0.240270  0.314932
3748  0.999  0.277912  2.0  0.240157  0.315453

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.278193  2.0  0.239930  0.316496
3751  1.002  0.278333  2.0  0.239815  0.317016
3752  1.002  0.278471  2.0  0.239699  0.317536
3753  1.003  0.278610  2.0  0.239582  0.318056

3750
interpolation

<lambdifygenerated-9331>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1
<lambdifygenerated-9332>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1

         x1         y  rep    ymodel      ybms
3745  0.997  0.306760  3.0  0.299915  0.314670
3746  0.998  0.307033  3.0  0.300198  0.315203
3747  0.998  0.307306  3.0  0.300479  0.315738
3748  0.999  0.307578  3.0  0.300759  0.316273

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.308120  3.0  0.301313  0.317344
3751  1.002  0.308390  3.0  0.301587  0.317881
3752  1.002  0.308660  3.0  0.301860  0.318418
3753  1.003  0.308928  3.0  0.302131  0.318956

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.965360  4.0  0.968885  0.955970
3746  0.998  0.965399  4.0  0.968921  0.955970
3747  0.998  0.965439  4.0  0.968957  0.955971
3748  0.999  0.965479  4.0  0.968994  0.955971

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.965559  4.0  0.969066  0.955971
3751  1.002  0.965598  4.0  0.969102  0.955971
3752  1.002  0.965638  4.0  0.969138  0.955971
3753  1.003  0.965678  4.0  0.969174  0.955971

3750

<lambdifygenerated-9383>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1 + x1**x1)
<lambdifygenerated-9384>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1 + x1**x1)
<lambdifygenerated-9387>:2: RuntimeWarning: invalid value encountered in power
  return x1*(_a2_**(x1**x1) + x1)
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-9388>:2: RuntimeWarning: invalid value encountered in power
  return x1*(_a2_**(x1**x1) + x1)
<lambdifygenerated-9389>:2: RuntimeWarning: invalid value encountered in power
  return x1*(_a2_**(_a5_**x1) + x1)

interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.308339  5.0  0.294262  0.280756
3746  0.998  0.308354  5.0  0.294169  0.280756
3747  0.998  0.308368  5.0  0.294076  0.280756
3748  0.999  0.308382  5.0  0.293983  0.280756

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.308407  5.0  0.293798  0.280756
3751  1.002  0.308419  5.0  0.293705  0.280756
3752  1.002  0.308430  5.0  0.293612  0.280756
3753  1.003  0.308441  5.0  0.293520  0.280756

3750
interpolation

<lambdifygenerated-9419>:2: RuntimeWarning: overflow encountered in square
  return tanh((x1 + exp(-_a2_*x1))**2)
<lambdifygenerated-9419>:2: RuntimeWarning: overflow encountered in exp
  return tanh((x1 + exp(-_a2_*x1))**2)
<lambdifygenerated-9420>:2: RuntimeWarning: overflow encountered in exp
  return tanh((x1 + exp(-_a2_*x1))**2)
<lambdifygenerated-9420>:2: RuntimeWarning: overflow encountered in square
  return tanh((x1 + exp(-_a2_*x1))**2)
<lambdifygenerated-9421>:2: RuntimeWarning: overflow encountered in exp
  return tanh((_a3_ + exp(-_a2_*x1))**2)
<lambdifygenerated-9421>:2: RuntimeWarning: overflow encountered in square
  return tanh((_a3_ + exp(-_a2_*x1))**2)
<lambdifygenerated-9422>:2: RuntimeWarning: overflow encountered in exp
  return tanh((_a3_ + exp(-_a2_*x1))**2)
<lambdifygenerated-9422>:2: RuntimeWarning: overflow encountered in square
  return tanh((_a3_ + exp(-_a2_*x1))**2)
<lambdifygenerated-9423>:2: RuntimeWarning: overflow encountered in exp
  return tanh((_a3_ + exp(-_a2_*x1))**2)
<lambdifygenerated-9423>:2: RuntimeWarning: overflow encountered in square
  return tanh((_a3_ + exp(-_a2_*x1))**2)
<lambdifygenerated-9424>:2: RuntimeWarning: overflow encountered in exp
  return tanh((_a3_ + exp(-_a2_*x1))**2)
<lambdifygenerated-9424>:2: RuntimeWarning: overflow encountered in square
  return tanh((_a3_ + exp(-_a2_*x1))**2)
<lambdifygenerated-9425>:2: RuntimeWarning: overflow encountered in exp
  return tanh((_a3_ + exp(-_a2_*x1))**2)
<lambdifygenerated-9425>:2: RuntimeWarning: overflow encountered in square
  return tanh((_a3_ + exp(-_a2_*x1))**2)
<lambdifygenerated-9426>:2: RuntimeWarning: overflow encountered in exp
  return tanh((_a3_ + exp(-_a2_*x1))**2)
<lambdifygenerated-9426>:2: RuntimeWarning: overflow encountered in square
  return tanh((_a3_ + exp(-_a2_*x1))**2)

         x1         y  rep    ymodel      ybms
3745  0.997  0.215897  6.0  0.240902  0.249807
3746  0.998  0.216041  6.0  0.240956  0.250086
3747  0.998  0.216186  6.0  0.241010  0.250365
3748  0.999  0.216330  6.0  0.241063  0.250644

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.216618  6.0  0.241170  0.251201
3751  1.002  0.216762  6.0  0.241223  0.251479
3752  1.002  0.216905  6.0  0.241276  0.251758
3753  1.003  0.217048  6.0  0.241329  0.252036

3750
interpolation

<lambdifygenerated-9433>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1/x1
<lambdifygenerated-9434>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1/x1

         x1         y  rep    ymodel      ybms
3745  0.997  0.100918  7.0  0.089722  0.042781
3746  0.998  0.100912  7.0  0.089469  0.042691
3747  0.998  0.100906  7.0  0.089215  0.042601
3748  0.999  0.100901  7.0  0.088962  0.042511

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.100890  7.0  0.088455  0.042332
3751  1.002  0.100885  7.0  0.088201  0.042242
3752  1.002  0.100880  7.0  0.087947  0.042153
3753  1.003  0.100874  7.0  0.087693  0.042064

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.825595  8.0  0.707827  0.858463
3746  0.998  0.825925  8.0  0.707275  0.859046
3747  0.998  0.826254  8.0  0.706722  0.859629
3748  0.999  0.826582  8.0  0.706168  0.860212

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.827238  8.0  0.705055  0.861378
3751  1.002  0.827565  8.0  0.704497  0.861961
3752  1.002  0.827892  8.0  0.703938  0.862545
3753  1.003  0.828218  8.0  0.703377  0.863128

3750
interpolation

<lambdifygenerated-9487>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1
<lambdifygenerated-9488>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1
<lambdifygenerated-9491>:2: RuntimeWarning: invalid value encountered in power
  return _a7_**(x1**x1)
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-9492>:2: RuntimeWarning: invalid value encountered in power
  return _a7_**(x1**x1)

         x1         y  rep    ymodel      ybms
3745  0.997  0.855453  9.0  0.790307  0.846189
3746  0.998  0.855554  9.0  0.790110  0.846360
3747  0.998  0.855656  9.0  0.789913  0.846532
3748  0.999  0.855757  9.0  0.789715  0.846704

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.855960  9.0  0.789319  0.847046
3751  1.002  0.856062  9.0  0.789120  0.847217
3752  1.002  0.856163  9.0  0.788922  0.847388
3753  1.003  0.856265  9.0  0.788723  0.847558

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.987381  0.0  1.027787  0.968399
3746  0.998  0.987426  0.0  1.027948  0.968401
3747  0.998  0.987470  0.0  1.028110  0.968402
3748  0.999  0.987515  0.0  1.028271  0.968404

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.987604  0.0  1.028593  0.968406
3751  1.002  0.987648  0.0  1.028754  0.968407
3752  1.002  0.987692  0.0  1.028915  0.968409
3753  1.003  0.987737  0.0  1.029076  0.968410

3750
interpolation

/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(

         x1         y  rep    ymodel      ybms
3745  0.997  0.053138  1.0  0.018860 -0.105450
3746  0.998  0.053057  1.0  0.018746 -0.106766
3747  0.998  0.052975  1.0  0.018632 -0.108086
3748  0.999  0.052894  1.0  0.018519 -0.109408

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.052733  1.0  0.018292 -0.112061
3751  1.002  0.052652  1.0  0.018180 -0.113392
3752  1.002  0.052571  1.0  0.018067 -0.114725
3753  1.003  0.052491  1.0  0.017955 -0.116061

3750
interpolation

<lambdifygenerated-9583>:2: RuntimeWarning: invalid value encountered in power
  return x1*cos(x1 + x1**x1)
<lambdifygenerated-9584>:2: RuntimeWarning: invalid value encountered in power
  return x1*cos(x1 + x1**x1)
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(

         x1         y  rep    ymodel      ybms
3745  0.997  0.277484  2.0  0.350999  0.286912
3746  0.998  0.277627  2.0  0.351507  0.285666
3747  0.998  0.277770  2.0  0.352014  0.284401
3748  0.999  0.277912  2.0  0.352520  0.283117

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.278193  2.0  0.353529  0.280489
3751  1.002  0.278333  2.0  0.354032  0.279146
3752  1.002  0.278471  2.0  0.354534  0.277784
3753  1.003  0.278610  2.0  0.355035  0.276401

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.306760  3.0  0.308956  0.359096
3746  0.998  0.307033  3.0  0.309100  0.359863
3747  0.998  0.307306  3.0  0.309244  0.360632
3748  0.999  0.307578  3.0  0.309387  0.361402

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.308120  3.0  0.309671  0.362945
3751  1.002  0.308390  3.0  0.309812  0.363719
3752  1.002  0.308660  3.0  0.309952  0.364494
3753  1.003  0.308928  3.0  0.310092  0.365270

3750
interpolation

<lambdifygenerated-9635>:2: RuntimeWarning: invalid value encountered in power
  return exp(x1*x1**x1)
<lambdifygenerated-9636>:2: RuntimeWarning: invalid value encountered in power
  return exp(x1*x1**x1)
<lambdifygenerated-9637>:2: RuntimeWarning: invalid value encountered in power
  return exp(_a2_**x1*x1)
<lambdifygenerated-9639>:2: RuntimeWarning: overflow encountered in exp
  return exp(_a2_**(-x1)*x1)
/usr/local/lib/python3.10/dist-packages/scipy/optimize/_minpack_py.py:1017: RuntimeWarning: overflow encountered in square
  cost = np.sum(infodict['fvec'] ** 2)
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
/usr/local/lib/python3.10/dist-packages/pandas/core/arraylike.py:399: RuntimeWarning: overflow encountered in square
  result = getattr(ufunc, method)(*inputs, **kwargs)
<lambdifygenerated-9640>:2: RuntimeWarning: overflow encountered in exp
  return exp(_a2_**(-x1)*x1)
<lambdifygenerated-9641>:2: RuntimeWarning: overflow encountered in exp
  return exp(_a2_**(-x1)*x1)
<lambdifygenerated-9642>:2: RuntimeWarning: overflow encountered in exp
  return exp(_a2_**(-x1)*x1)
<lambdifygenerated-9643>:2: RuntimeWarning: overflow encountered in exp
  return exp(_a2_**(-x1)*_a7_)
<lambdifygenerated-9644>:2: RuntimeWarning: overflow encountered in exp
  return exp(_a2_**(-x1)*_a7_)
<lambdifygenerated-9645>:2: RuntimeWarning: overflow encountered in exp
  return exp(_a2_**(-x1)*_a7_)
<lambdifygenerated-9646>:2: RuntimeWarning: overflow encountered in exp
  return exp(_a2_**(-x1)*_a7_)
<lambdifygenerated-9647>:2: RuntimeWarning: overflow encountered in exp
  return exp(_a2_**(-x1)*_a7_)
<lambdifygenerated-9648>:2: RuntimeWarning: overflow encountered in exp
  return exp(_a2_**(-x1)*_a7_)

         x1         y  rep    ymodel      ybms
3745  0.997  0.965360  4.0  0.981833  0.999584
3746  0.998  0.965399  4.0  0.981849  0.999586
3747  0.998  0.965439  4.0  0.981864  0.999588
3748  0.999  0.965479  4.0  0.981879  0.999591

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.965559  4.0  0.981910  0.999596
3751  1.002  0.965598  4.0  0.981925  0.999598
3752  1.002  0.965638  4.0  0.981940  0.999601
3753  1.003  0.965678  4.0  0.981955  0.999603

3750
interpolation

<lambdifygenerated-9659>:2: RuntimeWarning: invalid value encountered in power
  return _a5_*x1**x1 + x1
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-9660>:2: RuntimeWarning: invalid value encountered in power
  return _a5_*x1**x1 + x1
<lambdifygenerated-9661>:2: RuntimeWarning: invalid value encountered in power
  return _a5_*_a5_**x1 + x1
<lambdifygenerated-9662>:2: RuntimeWarning: invalid value encountered in power
  return _a5_*_a5_**x1 + x1
<lambdifygenerated-9663>:2: RuntimeWarning: invalid value encountered in power
  return _a5_*_a5_**(x1**2) + x1
<lambdifygenerated-9664>:2: RuntimeWarning: invalid value encountered in power
  return _a5_*_a5_**(x1**2) + x1
<lambdifygenerated-9665>:2: RuntimeWarning: invalid value encountered in power
  return _a5_*_a5_**(x1**4) + x1
<lambdifygenerated-9666>:2: RuntimeWarning: invalid value encountered in power
  return _a5_*_a5_**(x1**4) + x1
<lambdifygenerated-9667>:2: RuntimeWarning: invalid value encountered in power
  return _a5_*_a5_**exp(4*x1) + x1
<lambdifygenerated-9668>:2: RuntimeWarning: invalid value encountered in power
  return _a5_*_a5_**exp(4*x1) + x1
<lambdifygenerated-9669>:2: RuntimeWarning: invalid value encountered in power
  return _a5_*_a5_**exp(4*x1) + x1
<lambdifygenerated-9670>:2: RuntimeWarning: invalid value encountered in power
  return _a5_*_a5_**exp(4*x1) + x1
<lambdifygenerated-9671>:2: RuntimeWarning: invalid value encountered in power
  return _a5_*_a5_**exp(4*x1) + _a6_
<lambdifygenerated-9672>:2: RuntimeWarning: invalid value encountered in power
  return _a5_*_a5_**exp(4*x1) + _a6_
<lambdifygenerated-9673>:2: RuntimeWarning: invalid value encountered in power
  return _a5_*_a5_**exp(4*x1) + _a6_
<lambdifygenerated-9674>:2: RuntimeWarning: invalid value encountered in power
  return _a5_*_a5_**exp(4*x1) + _a6_
<lambdifygenerated-9675>:2: RuntimeWarning: invalid value encountered in power
  return _a5_*_a5_**exp(4*x1) + _a6_
<lambdifygenerated-9676>:2: RuntimeWarning: invalid value encountered in power
  return _a5_*_a5_**exp(4*x1) + _a6_

         x1         y  rep    ymodel     ybms
3745  0.997  0.308339  5.0  0.321363  0.29969
3746  0.998  0.308354  5.0  0.321427  0.29969
3747  0.998  0.308368  5.0  0.321491  0.29969
3748  0.999  0.308382  5.0  0.321556  0.29969

extrapolation

         x1         y  rep    ymodel     ybms
3750  1.001  0.308407  5.0  0.321684  0.29969
3751  1.002  0.308419  5.0  0.321748  0.29969
3752  1.002  0.308430  5.0  0.321811  0.29969
3753  1.003  0.308441  5.0  0.321875  0.29969

3750
interpolation

<lambdifygenerated-9691>:2: RuntimeWarning: invalid value encountered in power
  return tanh(_a3_ + x1*x1**x1)**2
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-9692>:2: RuntimeWarning: invalid value encountered in power
  return tanh(_a3_ + x1*x1**x1)**2
<lambdifygenerated-9697>:2: RuntimeWarning: invalid value encountered in power
  return tanh(_a3_ + _a6_**x1*_a7_)**2

         x1         y  rep    ymodel      ybms
3745  0.997  0.215897  6.0  0.169242  0.184869
3746  0.998  0.216041  6.0  0.169266  0.184989
3747  0.998  0.216186  6.0  0.169289  0.185110
3748  0.999  0.216330  6.0  0.169311  0.185230

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.216618  6.0  0.169357  0.185471
3751  1.002  0.216762  6.0  0.169380  0.185590
3752  1.002  0.216905  6.0  0.169402  0.185710
3753  1.003  0.217048  6.0  0.169425  0.185830

3750
interpolation

<lambdifygenerated-9719>:2: RuntimeWarning: invalid value encountered in power
  return x1*exp(x1**x1*(_a5_ + x1))
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-9720>:2: RuntimeWarning: invalid value encountered in power
  return x1*exp(x1**x1*(_a5_ + x1))

         x1         y  rep    ymodel      ybms
3745  0.997  0.100918  7.0  0.116173  0.105907
3746  0.998  0.100912  7.0  0.116180  0.105880
3747  0.998  0.100906  7.0  0.116188  0.105853
3748  0.999  0.100901  7.0  0.116195  0.105826

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.100890  7.0  0.116209  0.105773
3751  1.002  0.100885  7.0  0.116217  0.105746
3752  1.002  0.100880  7.0  0.116224  0.105720
3753  1.003  0.100874  7.0  0.116231  0.105693

3750
interpolation

<lambdifygenerated-9737>:2: RuntimeWarning: invalid value encountered in power
  return x1 + x1**x1
<lambdifygenerated-9738>:2: RuntimeWarning: invalid value encountered in power
  return x1 + x1**x1
<lambdifygenerated-9741>:2: RuntimeWarning: invalid value encountered in power
  return _a1_**(x1**x1) + x1
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-9742>:2: RuntimeWarning: invalid value encountered in power
  return _a1_**(x1**x1) + x1
<lambdifygenerated-9747>:2: RuntimeWarning: invalid value encountered in power
  return _a1_ + _a1_**(_a6_**x1)

         x1         y  rep    ymodel      ybms
3745  0.997  0.825595  8.0  0.819780  0.816284
3746  0.998  0.825925  8.0  0.820024  0.816670
3747  0.998  0.826254  8.0  0.820267  0.817055
3748  0.999  0.826582  8.0  0.820509  0.817440

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.827238  8.0  0.820991  0.818208
3751  1.002  0.827565  8.0  0.821231  0.818592
3752  1.002  0.827892  8.0  0.821470  0.818975
3753  1.003  0.828218  8.0  0.821709  0.819357

3750
interpolation

<lambdifygenerated-9759>:2: RuntimeWarning: invalid value encountered in power
  return x1*x1**x1
<lambdifygenerated-9760>:2: RuntimeWarning: invalid value encountered in power
  return x1*x1**x1
<lambdifygenerated-9761>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1**x1)**x1
<lambdifygenerated-9762>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1**x1)**x1

         x1         y  rep    ymodel      ybms
3745  0.997  0.855453  9.0  0.842644  0.823483
3746  0.998  0.855554  9.0  0.842681  0.823357
3747  0.998  0.855656  9.0  0.842717  0.823231
3748  0.999  0.855757  9.0  0.842753  0.823104

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.855960  9.0  0.842825  0.822847
3751  1.002  0.856062  9.0  0.842861  0.822718
3752  1.002  0.856163  9.0  0.842896  0.822587
3753  1.003  0.856265  9.0  0.842932  0.822456

3750
interpolation

<lambdifygenerated-9789>:2: RuntimeWarning: divide by zero encountered in divide
  return _a7_*x1/fac(x1)
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-9790>:2: RuntimeWarning: divide by zero encountered in divide
  return _a7_*x1/fac(x1)

         x1         y  rep    ymodel      ybms
3745  0.997  0.987381  0.0  1.036115  0.995445
3746  0.998  0.987426  0.0  1.036199  0.994974
3747  0.998  0.987470  0.0  1.036283  0.994502
3748  0.999  0.987515  0.0  1.036368  0.994027

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.987604  0.0  1.036536  0.993072
3751  1.002  0.987648  0.0  1.036619  0.992592
3752  1.002  0.987692  0.0  1.036703  0.992109
3753  1.003  0.987737  0.0  1.036787  0.991625

3750

<lambdifygenerated-9815>:2: RuntimeWarning: invalid value encountered in power
  return x1*x1**(2*x1)
<lambdifygenerated-9816>:2: RuntimeWarning: invalid value encountered in power
  return x1*x1**(2*x1)
<lambdifygenerated-9817>:2: RuntimeWarning: invalid value encountered in power
  return x1*(2*x1)**(2*x1)
<lambdifygenerated-9818>:2: RuntimeWarning: invalid value encountered in power
  return x1*(2*x1)**(2*x1)
<lambdifygenerated-9819>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1 + 1)**(2*x1)
<lambdifygenerated-9820>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1 + 1)**(2*x1)
<lambdifygenerated-9821>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1 + x1**x1/x1)**(2*x1)
<lambdifygenerated-9822>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1 + x1**x1/x1)**(2*x1)
<lambdifygenerated-9823>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1 + (x1**2)**x1/x1)**(2*x1)
<lambdifygenerated-9824>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1 + (x1**2)**x1/x1)**(2*x1)
<lambdifygenerated-9825>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1 + (_a2_*x1)**x1/x1)**(2*x1)
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-9826>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1 + (_a2_*x1)**x1/x1)**(2*x1)
<lambdifygenerated-9827>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1 + (_a2_*_a4_)**x1/x1)**(2*x1)
<lambdifygenerated-9828>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1 + (_a2_*_a4_)**x1/x1)**(2*x1)
<lambdifygenerated-9829>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1 + (_a2_*_a4_)**(x1**2)/x1)**(2*x1)
<lambdifygenerated-9830>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1 + (_a2_*_a4_)**(x1**2)/x1)**(2*x1)
<lambdifygenerated-9831>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1 + (_a2_*_a4_)**(x1**2)/x1)**(2*x1)
<lambdifygenerated-9832>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1 + (_a2_*_a4_)**(x1**2)/x1)**(2*x1)
<lambdifygenerated-9833>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1 + (_a2_*_a4_)**(x1**2)/_a2_)**(2*x1)
<lambdifygenerated-9834>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1 + (_a2_*_a4_)**(x1**2)/_a2_)**(2*x1)
<lambdifygenerated-9835>:2: RuntimeWarning: invalid value encountered in power
  return x1*(_a2_ + (_a2_*_a4_)**(x1**2)/_a2_)**(2*x1)
<lambdifygenerated-9837>:2: RuntimeWarning: invalid value encountered in power
  return x1*(_a2_ + (_a2_*_a4_)**(x1**2)/_a2_)**(4*x1)
<lambdifygenerated-9839>:2: RuntimeWarning: invalid value encountered in power
  return x1*(_a2_ + (_a2_*_a4_)**(x1**2)/_a2_)**(2*_a7_ + 2*x1)

interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.053138  1.0  0.029108  0.043548
3746  0.998  0.053057  1.0  0.028847  0.043506
3747  0.998  0.052975  1.0  0.028586  0.043463
3748  0.999  0.052894  1.0  0.028325  0.043421

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.052733  1.0  0.027804  0.043337
3751  1.002  0.052652  1.0  0.027544  0.043295
3752  1.002  0.052571  1.0  0.027285  0.043253
3753  1.003  0.052491  1.0  0.027025  0.043211

3750
interpolation

/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(

         x1         y  rep    ymodel      ybms
3745  0.997  0.277484  2.0  0.266588  0.274615
3746  0.998  0.277627  2.0  0.266754  0.275012
3747  0.998  0.277770  2.0  0.266919  0.275410
3748  0.999  0.277912  2.0  0.267083  0.275807

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.278193  2.0  0.267408  0.276601
3751  1.002  0.278333  2.0  0.267569  0.276997
3752  1.002  0.278471  2.0  0.267730  0.277393
3753  1.003  0.278610  2.0  0.267889  0.277789

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.306760  3.0  0.330050  0.308374
3746  0.998  0.307033  3.0  0.330262  0.308745
3747  0.998  0.307306  3.0  0.330474  0.309116
3748  0.999  0.307578  3.0  0.330685  0.309488

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.308120  3.0  0.331106  0.310231
3751  1.002  0.308390  3.0  0.331316  0.310604
3752  1.002  0.308660  3.0  0.331525  0.310976
3753  1.003  0.308928  3.0  0.331734  0.311348

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.965360  4.0  0.978126  0.968823
3746  0.998  0.965399  4.0  0.978214  0.968823
3747  0.998  0.965439  4.0  0.978302  0.968823
3748  0.999  0.965479  4.0  0.978391  0.968823

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.965559  4.0  0.978568  0.968823
3751  1.002  0.965598  4.0  0.978656  0.968823
3752  1.002  0.965638  4.0  0.978744  0.968823
3753  1.003  0.965678  4.0  0.978833  0.968823

3750
interpolation

<lambdifygenerated-9925>:2: RuntimeWarning: invalid value encountered in power
  return tanh(x1**x1)
<lambdifygenerated-9926>:2: RuntimeWarning: invalid value encountered in power
  return tanh(x1**x1)

         x1         y  rep    ymodel      ybms
3745  0.997  0.308339  5.0  0.274331  0.194309
3746  0.998  0.308354  5.0  0.274331  0.194150
3747  0.998  0.308368  5.0  0.274331  0.193992
3748  0.999  0.308382  5.0  0.274330  0.193833

extrapolation

         x1         y  rep   ymodel      ybms
3750  1.001  0.308407  5.0  0.27433  0.193517
3751  1.002  0.308419  5.0  0.27433  0.193360
3752  1.002  0.308430  5.0  0.27433  0.193203
3753  1.003  0.308441  5.0  0.27433  0.193046

3750
interpolation

<lambdifygenerated-9951>:2: RuntimeWarning: invalid value encountered in power
  return tanh(x1**2*(_a7_ + x1**x1)**2)
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-9952>:2: RuntimeWarning: invalid value encountered in power
  return tanh(x1**2*(_a7_ + x1**x1)**2)

         x1         y  rep    ymodel      ybms
3745  0.997  0.215897  6.0  0.227542  0.215498
3746  0.998  0.216041  6.0  0.227862  0.215718
3747  0.998  0.216186  6.0  0.228183  0.215937
3748  0.999  0.216330  6.0  0.228504  0.216156

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.216618  6.0  0.229144  0.216594
3751  1.002  0.216762  6.0  0.229464  0.216813
3752  1.002  0.216905  6.0  0.229785  0.217032
3753  1.003  0.217048  6.0  0.230105  0.217251

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.100918  7.0  0.146247  0.181958
3746  0.998  0.100912  7.0  0.146554  0.182451
3747  0.998  0.100906  7.0  0.146861  0.182945
3748  0.999  0.100901  7.0  0.147169  0.183442

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.100890  7.0  0.147787  0.184444
3751  1.002  0.100885  7.0  0.148097  0.184948
3752  1.002  0.100880  7.0  0.148408  0.185455
3753  1.003  0.100874  7.0  0.148720  0.185964

3750
interpolation

<lambdifygenerated-10003>:2: RuntimeWarning: invalid value encountered in power
  return _a2_ + x1**x1
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-10004>:2: RuntimeWarning: invalid value encountered in power
  return _a2_ + x1**x1
<lambdifygenerated-10007>:2: RuntimeWarning: invalid value encountered in power
  return _a2_ + _a2_**(x1**x1)
<lambdifygenerated-10008>:2: RuntimeWarning: invalid value encountered in power
  return _a2_ + _a2_**(x1**x1)
<lambdifygenerated-10011>:2: RuntimeWarning: invalid value encountered in power
  return _a2_ + _a2_**((_a2_*x1)**x1)
<lambdifygenerated-10012>:2: RuntimeWarning: invalid value encountered in power
  return _a2_ + _a2_**((_a2_*x1)**x1)

         x1         y  rep    ymodel      ybms
3745  0.997  0.825595  8.0  0.985697  0.851463
3746  0.998  0.825925  8.0  0.986590  0.851833
3747  0.998  0.826254  8.0  0.987483  0.852203
3748  0.999  0.826582  8.0  0.988376  0.852572

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.827238  8.0  0.990164  0.853308
3751  1.002  0.827565  8.0  0.991058  0.853675
3752  1.002  0.827892  8.0  0.991952  0.854041
3753  1.003  0.828218  8.0  0.992846  0.854407

3750
interpolation

<lambdifygenerated-10031>:2: RuntimeWarning: invalid value encountered in power
  return _a7_/(x1 + x1**x1)
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-10032>:2: RuntimeWarning: invalid value encountered in power
  return _a7_/(x1 + x1**x1)
<lambdifygenerated-10033>:2: RuntimeWarning: invalid value encountered in power
  return _a7_/(_a7_**x1 + x1)
<lambdifygenerated-10034>:2: RuntimeWarning: invalid value encountered in power
  return _a7_/(_a7_**x1 + x1)
<lambdifygenerated-10035>:2: RuntimeWarning: invalid value encountered in power
  return _a7_/(_a7_**(x1**2) + x1)
<lambdifygenerated-10036>:2: RuntimeWarning: invalid value encountered in power
  return _a7_/(_a7_**(x1**2) + x1)
<lambdifygenerated-10037>:2: RuntimeWarning: invalid value encountered in power
  return _a7_/(_a7_**(x1**2) + x1)
<lambdifygenerated-10038>:2: RuntimeWarning: invalid value encountered in power
  return _a7_/(_a7_**(x1**2) + x1)
<lambdifygenerated-10039>:2: RuntimeWarning: invalid value encountered in power
  return _a7_/(_a7_**(_a5_*x1) + x1)
<lambdifygenerated-10040>:2: RuntimeWarning: invalid value encountered in power
  return _a7_/(_a7_**(_a5_*x1) + x1)
<lambdifygenerated-10041>:2: RuntimeWarning: invalid value encountered in power
  return _a7_/(_a7_ + _a7_**(_a5_*x1))
<lambdifygenerated-10042>:2: RuntimeWarning: invalid value encountered in power
  return _a7_/(_a7_ + _a7_**(_a5_*x1))
<lambdifygenerated-10043>:2: RuntimeWarning: invalid value encountered in power
  return _a7_/(_a7_ + _a7_**(_a5_*x1))
<lambdifygenerated-10044>:2: RuntimeWarning: invalid value encountered in power
  return _a7_/(_a7_ + _a7_**(_a5_*x1))
<lambdifygenerated-10045>:2: RuntimeWarning: invalid value encountered in power
  return _a7_/(_a7_ + _a7_**(_a5_*x1))
<lambdifygenerated-10046>:2: RuntimeWarning: invalid value encountered in power
  return _a7_/(_a7_ + _a7_**(_a5_*x1))

         x1         y  rep    ymodel      ybms
3745  0.997  0.855453  9.0  0.899646  0.893286
3746  0.998  0.855554  9.0  0.900050  0.893463
3747  0.998  0.855656  9.0  0.900456  0.893640
3748  0.999  0.855757  9.0  0.900862  0.893816

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.855960  9.0  0.901676  0.894169
3751  1.002  0.856062  9.0  0.902084  0.894345
3752  1.002  0.856163  9.0  0.902493  0.894521
3753  1.003  0.856265  9.0  0.902902  0.894696

3750
interpolation

<lambdifygenerated-10051>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1
<lambdifygenerated-10052>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1
<lambdifygenerated-10055>:2: RuntimeWarning: invalid value encountered in power
  return _a7_**(x1**x1)
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-10056>:2: RuntimeWarning: invalid value encountered in power
  return _a7_**(x1**x1)
<lambdifygenerated-10057>:2: RuntimeWarning: invalid value encountered in power
  return _a7_**(_a2_**x1)

         x1         y  rep    ymodel      ybms
3745  0.997  0.987381  0.0  0.994618  0.969280
3746  0.998  0.987426  0.0  0.994593  0.969319
3747  0.998  0.987470  0.0  0.994568  0.969358
3748  0.999  0.987515  0.0  0.994543  0.969397

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.987604  0.0  0.994492  0.969474
3751  1.002  0.987648  0.0  0.994466  0.969512
3752  1.002  0.987692  0.0  0.994441  0.969551
3753  1.003  0.987737  0.0  0.994415  0.969589

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.053138  1.0  0.068789  0.066508
3746  0.998  0.053057  1.0  0.068783  0.066508
3747  0.998  0.052975  1.0  0.068777  0.066509
3748  0.999  0.052894  1.0  0.068771  0.066511

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.052733  1.0  0.068760  0.066515
3751  1.002  0.052652  1.0  0.068755  0.066518
3752  1.002  0.052571  1.0  0.068750  0.066521
3753  1.003  0.052491  1.0  0.068746  0.066525

3750
interpolation

<lambdifygenerated-10111>:2: RuntimeWarning: invalid value encountered in log
  return x1*abs(tanh(x1 + log(x1)))
<lambdifygenerated-10112>:2: RuntimeWarning: invalid value encountered in log
  return x1*abs(tanh(x1 + log(x1)))

         x1         y  rep    ymodel      ybms
3745  0.997  0.277484  2.0  0.243531  0.299131
3746  0.998  0.277627  2.0  0.243804  0.299514
3747  0.998  0.277770  2.0  0.244077  0.299897
3748  0.999  0.277912  2.0  0.244350  0.300280

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.278193  2.0  0.244896  0.301044
3751  1.002  0.278333  2.0  0.245168  0.301426
3752  1.002  0.278471  2.0  0.245440  0.301807
3753  1.003  0.278610  2.0  0.245712  0.302189

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.306760  3.0  0.278986  0.345620
3746  0.998  0.307033  3.0  0.279150  0.346372
3747  0.998  0.307306  3.0  0.279314  0.347125
3748  0.999  0.307578  3.0  0.279477  0.347879

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.308120  3.0  0.279803  0.349392
3751  1.002  0.308390  3.0  0.279965  0.350150
3752  1.002  0.308660  3.0  0.280126  0.350909
3753  1.003  0.308928  3.0  0.280287  0.351670

3750
interpolation

<lambdifygenerated-10149>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1
<lambdifygenerated-10150>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1
<lambdifygenerated-10153>:2: RuntimeWarning: invalid value encountered in power
  return _a2_**(x1**x1)
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-10154>:2: RuntimeWarning: invalid value encountered in power
  return _a2_**(x1**x1)
<lambdifygenerated-10157>:2: RuntimeWarning: invalid value encountered in power
  return _a2_**((_a7_*x1)**x1)
<lambdifygenerated-10158>:2: RuntimeWarning: invalid value encountered in power
  return _a2_**((_a7_*x1)**x1)

         x1         y  rep    ymodel      ybms
3745  0.997  0.965360  4.0  0.949742  0.999477
3746  0.998  0.965399  4.0  0.949718  0.999480
3747  0.998  0.965439  4.0  0.949695  0.999483
3748  0.999  0.965479  4.0  0.949671  0.999486

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.965559  4.0  0.949624  0.999492
3751  1.002  0.965598  4.0  0.949601  0.999495
3752  1.002  0.965638  4.0  0.949577  0.999498
3753  1.003  0.965678  4.0  0.949554  0.999501

3750
interpolation

<lambdifygenerated-10175>:2: RuntimeWarning: invalid value encountered in power
  return sin(x1 + x1**x1)
<lambdifygenerated-10176>:2: RuntimeWarning: invalid value encountered in power
  return sin(x1 + x1**x1)
<lambdifygenerated-10179>:2: RuntimeWarning: invalid value encountered in power
  return sin(_a4_**(x1**x1) + x1)
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-10180>:2: RuntimeWarning: invalid value encountered in power
  return sin(_a4_**(x1**x1) + x1)

         x1         y  rep    ymodel      ybms
3745  0.997  0.308339  5.0  0.264894  0.319905
3746  0.998  0.308354  5.0  0.264839  0.319905
3747  0.998  0.308368  5.0  0.264784  0.319905
3748  0.999  0.308382  5.0  0.264729  0.319905

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.308407  5.0  0.264619  0.319905
3751  1.002  0.308419  5.0  0.264564  0.319905
3752  1.002  0.308430  5.0  0.264510  0.319905
3753  1.003  0.308441  5.0  0.264456  0.319905

3750

<lambdifygenerated-10199>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1 + x1**x1)
<lambdifygenerated-10200>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1 + x1**x1)
<lambdifygenerated-10203>:2: RuntimeWarning: invalid value encountered in power
  return x1*(_a7_**(x1**x1) + x1)
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-10204>:2: RuntimeWarning: invalid value encountered in power
  return x1*(_a7_**(x1**x1) + x1)
<lambdifygenerated-10205>:2: RuntimeWarning: invalid value encountered in power
  return x1*(_a7_**((x1**2)**x1) + x1)
<lambdifygenerated-10207>:2: RuntimeWarning: invalid value encountered in power
  return x1*(_a7_**((_a3_**2)**x1) + x1)
<lambdifygenerated-10211>:2: RuntimeWarning: invalid value encountered in power
  return x1*(_a7_**((_a3_**2)**x1) + x1**2)
<lambdifygenerated-10215>:2: RuntimeWarning: invalid value encountered in power
  return x1*(_a5_*x1 + _a7_**((_a3_**2)**x1))

interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.215897  6.0  0.249772  0.191494
3746  0.998  0.216041  6.0  0.250038  0.191648
3747  0.998  0.216186  6.0  0.250303  0.191802
3748  0.999  0.216330  6.0  0.250569  0.191955

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.216618  6.0  0.251098  0.192263
3751  1.002  0.216762  6.0  0.251362  0.192416
3752  1.002  0.216905  6.0  0.251626  0.192570
3753  1.003  0.217048  6.0  0.251890  0.192724

3750
interpolation

<lambdifygenerated-10229>:2: RuntimeWarning: invalid value encountered in power
  return x1*x1**x1
<lambdifygenerated-10230>:2: RuntimeWarning: invalid value encountered in power
  return x1*x1**x1
<lambdifygenerated-10233>:2: RuntimeWarning: invalid value encountered in power
  return x1*(_a4_*x1)**x1
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-10234>:2: RuntimeWarning: invalid value encountered in power
  return x1*(_a4_*x1)**x1
<lambdifygenerated-10239>:2: RuntimeWarning: invalid value encountered in power
  return x1*(_a4_*exp(x1))**(x1**x1)
<lambdifygenerated-10240>:2: RuntimeWarning: invalid value encountered in power
  return x1*(_a4_*exp(x1))**(x1**x1)
<lambdifygenerated-10241>:2: RuntimeWarning: invalid value encountered in power
  return x1*(_a4_*exp(x1))**(_a6_**x1)

         x1         y  rep    ymodel      ybms
3745  0.997  0.100918  7.0  0.142412  0.108367
3746  0.998  0.100912  7.0  0.142644  0.108340
3747  0.998  0.100906  7.0  0.142876  0.108313
3748  0.999  0.100901  7.0  0.143109  0.108286

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.100890  7.0  0.143577  0.108232
3751  1.002  0.100885  7.0  0.143812  0.108205
3752  1.002  0.100880  7.0  0.144049  0.108178
3753  1.003  0.100874  7.0  0.144286  0.108152

3750
interpolation

<lambdifygenerated-10259>:2: RuntimeWarning: invalid value encountered in power
  return _a0_ + x1**x1
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-10260>:2: RuntimeWarning: invalid value encountered in power
  return _a0_ + x1**x1
<lambdifygenerated-10263>:2: RuntimeWarning: invalid value encountered in power
  return _a0_ + _a4_**(x1**x1)
<lambdifygenerated-10264>:2: RuntimeWarning: invalid value encountered in power
  return _a0_ + _a4_**(x1**x1)
<lambdifygenerated-10265>:2: RuntimeWarning: invalid value encountered in power
  return _a0_ + _a4_**(_a0_**x1)
<lambdifygenerated-10266>:2: RuntimeWarning: invalid value encountered in power
  return _a0_ + _a4_**(_a0_**x1)
<lambdifygenerated-10267>:2: RuntimeWarning: invalid value encountered in power
  return _a0_ + _a4_**(_a0_**x1)
<lambdifygenerated-10268>:2: RuntimeWarning: invalid value encountered in power
  return _a0_ + _a4_**(_a0_**x1)
<lambdifygenerated-10269>:2: RuntimeWarning: invalid value encountered in power
  return _a0_ + _a4_**(_a0_**x1)
<lambdifygenerated-10270>:2: RuntimeWarning: invalid value encountered in power
  return _a0_ + _a4_**(_a0_**x1)
<lambdifygenerated-10271>:2: RuntimeWarning: invalid value encountered in power
  return _a0_ + _a4_**(_a0_**x1)
<lambdifygenerated-10272>:2: RuntimeWarning: invalid value encountered in power
  return _a0_ + _a4_**(_a0_**x1)

         x1         y  rep    ymodel      ybms
3745  0.997  0.825595  8.0  0.829655  0.864389
3746  0.998  0.825925  8.0  0.830051  0.864775
3747  0.998  0.826254  8.0  0.830447  0.865161
3748  0.999  0.826582  8.0  0.830843  0.865547

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.827238  8.0  0.831635  0.866316
3751  1.002  0.827565  8.0  0.832030  0.866699
3752  1.002  0.827892  8.0  0.832425  0.867082
3753  1.003  0.828218  8.0  0.832820  0.867464

3750
interpolation

<lambdifygenerated-10277>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1
<lambdifygenerated-10278>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1
<lambdifygenerated-10281>:2: RuntimeWarning: invalid value encountered in power
  return _a1_**(x1**x1)
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-10282>:2: RuntimeWarning: invalid value encountered in power
  return _a1_**(x1**x1)
<lambdifygenerated-10283>:2: RuntimeWarning: invalid value encountered in power
  return _a1_**(_a6_**x1)

         x1         y  rep    ymodel      ybms
3745  0.997  0.855453  9.0  0.868048  0.869156
3746  0.998  0.855554  9.0  0.868335  0.869319
3747  0.998  0.855656  9.0  0.868622  0.869482
3748  0.999  0.855757  9.0  0.868910  0.869644

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.855960  9.0  0.869484  0.869968
3751  1.002  0.856062  9.0  0.869771  0.870130
3752  1.002  0.856163  9.0  0.870059  0.870291
3753  1.003  0.856265  9.0  0.870346  0.870453

3750
interpolation

<lambdifygenerated-10295>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1
<lambdifygenerated-10296>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1
<lambdifygenerated-10299>:2: RuntimeWarning: invalid value encountered in power
  return _a6_**(x1**x1)
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-10300>:2: RuntimeWarning: invalid value encountered in power
  return _a6_**(x1**x1)
<lambdifygenerated-10301>:2: RuntimeWarning: invalid value encountered in power
  return _a6_**(_a4_**x1)

         x1         y  rep    ymodel      ybms
3745  0.997  0.987381  0.0  0.991512  0.967433
3746  0.998  0.987426  0.0  0.991513  0.967474
3747  0.998  0.987470  0.0  0.991514  0.967514
3748  0.999  0.987515  0.0  0.991514  0.967555

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.987604  0.0  0.991515  0.967635
3751  1.002  0.987648  0.0  0.991515  0.967676
3752  1.002  0.987692  0.0  0.991515  0.967716
3753  1.003  0.987737  0.0  0.991515  0.967756

3750
interpolation

<lambdifygenerated-10317>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1 + x1**x1)
<lambdifygenerated-10318>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1 + x1**x1)

         x1         y  rep    ymodel      ybms
3745  0.997  0.053138  1.0  0.097317  0.078472
3746  0.998  0.053057  1.0  0.097287  0.078330
3747  0.998  0.052975  1.0  0.097258  0.078188
3748  0.999  0.052894  1.0  0.097229  0.078046

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.052733  1.0  0.097172  0.077762
3751  1.002  0.052652  1.0  0.097144  0.077620
3752  1.002  0.052571  1.0  0.097116  0.077478
3753  1.003  0.052491  1.0  0.097088  0.077336

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.277484  2.0  0.290526  0.214456
3746  0.998  0.277627  2.0  0.291121  0.214429
3747  0.998  0.277770  2.0  0.291716  0.214399
3748  0.999  0.277912  2.0  0.292311  0.214366

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.278193  2.0  0.293501  0.214292
3751  1.002  0.278333  2.0  0.294096  0.214251
3752  1.002  0.278471  2.0  0.294691  0.214206
3753  1.003  0.278610  2.0  0.295286  0.214159

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.306760  3.0  0.244532  0.358220
3746  0.998  0.307033  3.0  0.244757  0.359082
3747  0.998  0.307306  3.0  0.244982  0.359947
3748  0.999  0.307578  3.0  0.245206  0.360813

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.308120  3.0  0.245653  0.362549
3751  1.002  0.308390  3.0  0.245877  0.363419
3752  1.002  0.308660  3.0  0.246099  0.364291
3753  1.003  0.308928  3.0  0.246322  0.365164

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.965360  4.0  0.950354  0.952266
3746  0.998  0.965399  4.0  0.950357  0.952266
3747  0.998  0.965439  4.0  0.950361  0.952266
3748  0.999  0.965479  4.0  0.950364  0.952266

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.965559  4.0  0.950371  0.952266
3751  1.002  0.965598  4.0  0.950375  0.952266
3752  1.002  0.965638  4.0  0.950378  0.952266
3753  1.003  0.965678  4.0  0.950382  0.952266

3750
interpolation

<lambdifygenerated-10435>:2: RuntimeWarning: invalid value encountered in power
  return tanh(x1**x1)
<lambdifygenerated-10436>:2: RuntimeWarning: invalid value encountered in power
  return tanh(x1**x1)
<lambdifygenerated-10439>:2: RuntimeWarning: invalid value encountered in power
  return tanh((x1*exp(x1))**x1)
<lambdifygenerated-10440>:2: RuntimeWarning: invalid value encountered in power
  return tanh((x1*exp(x1))**x1)
<lambdifygenerated-10441>:2: RuntimeWarning: invalid value encountered in power
  return tanh((x1*exp(x1))**x1)
<lambdifygenerated-10442>:2: RuntimeWarning: invalid value encountered in power
  return tanh((x1*exp(x1))**x1)
<lambdifygenerated-10443>:2: RuntimeWarning: invalid value encountered in power
  return tanh((_a7_*exp(x1))**x1)

         x1         y  rep    ymodel      ybms
3745  0.997  0.308339  5.0  0.368921  0.242489
3746  0.998  0.308354  5.0  0.368946  0.242413
3747  0.998  0.308368  5.0  0.368971  0.242339
3748  0.999  0.308382  5.0  0.368996  0.242264

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.308407  5.0  0.369047  0.242116
3751  1.002  0.308419  5.0  0.369072  0.242042
3752  1.002  0.308430  5.0  0.369097  0.241969
3753  1.003  0.308441  5.0  0.369123  0.241896

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.215897  6.0  0.232772  0.243417
3746  0.998  0.216041  6.0  0.232918  0.243467
3747  0.998  0.216186  6.0  0.233063  0.243515
3748  0.999  0.216330  6.0  0.233209  0.243563

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.216618  6.0  0.233498  0.243653
3751  1.002  0.216762  6.0  0.233642  0.243697
3752  1.002  0.216905  6.0  0.233787  0.243739
3753  1.003  0.217048  6.0  0.233930  0.243780

3750
interpolation

<lambdifygenerated-10487>:2: RuntimeWarning: invalid value encountered in power
  return x1*x1**x1
<lambdifygenerated-10488>:2: RuntimeWarning: invalid value encountered in power
  return x1*x1**x1

         x1         y  rep    ymodel      ybms
3745  0.997  0.100918  7.0  0.151588  0.062166
3746  0.998  0.100912  7.0  0.151668  0.061261
3747  0.998  0.100906  7.0  0.151748  0.060347
3748  0.999  0.100901  7.0  0.151829  0.059424

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.100890  7.0  0.151989  0.057549
3751  1.002  0.100885  7.0  0.152069  0.056598
3752  1.002  0.100880  7.0  0.152149  0.055636
3753  1.003  0.100874  7.0  0.152229  0.054665

3750
interpolation

<lambdifygenerated-10515>:2: RuntimeWarning: invalid value encountered in power
  return x1*x1**x1
<lambdifygenerated-10516>:2: RuntimeWarning: invalid value encountered in power
  return x1*x1**x1

         x1         y  rep    ymodel      ybms
3745  0.997  0.825595  8.0  0.892354  0.922894
3746  0.998  0.825925  8.0  0.893054  0.923673
3747  0.998  0.826254  8.0  0.893754  0.924452
3748  0.999  0.826582  8.0  0.894454  0.925230

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.827238  8.0  0.895852  0.926786
3751  1.002  0.827565  8.0  0.896551  0.927564
3752  1.002  0.827892  8.0  0.897250  0.928341
3753  1.003  0.828218  8.0  0.897948  0.929118

<lambdifygenerated-10533>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1
<lambdifygenerated-10534>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1

3750
interpolation

<lambdifygenerated-10537>:2: RuntimeWarning: invalid value encountered in power
  return _a1_**(x1**x1)
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-10538>:2: RuntimeWarning: invalid value encountered in power
  return _a1_**(x1**x1)
<lambdifygenerated-10539>:2: RuntimeWarning: invalid value encountered in power
  return _a1_**(-x1**x1)
<lambdifygenerated-10540>:2: RuntimeWarning: invalid value encountered in power
  return _a1_**(-x1**x1)
<lambdifygenerated-10541>:2: RuntimeWarning: invalid value encountered in power
  return _a1_**(-_a4_**x1)

         x1         y  rep    ymodel      ybms
3745  0.997  0.855453  9.0  0.912353  0.869893
3746  0.998  0.855554  9.0  0.912843  0.870056
3747  0.998  0.855656  9.0  0.913334  0.870219
3748  0.999  0.855757  9.0  0.913826  0.870382

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.855960  9.0  0.914811  0.870707
3751  1.002  0.856062  9.0  0.915304  0.870869
3752  1.002  0.856163  9.0  0.915798  0.871031
3753  1.003  0.856265  9.0  0.916293  0.871192

3750
interpolation

<lambdifygenerated-10553>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1
<lambdifygenerated-10554>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1
<lambdifygenerated-10557>:2: RuntimeWarning: invalid value encountered in power
  return _a6_**(x1**x1)
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-10558>:2: RuntimeWarning: invalid value encountered in power
  return _a6_**(x1**x1)

         x1         y  rep    ymodel      ybms
3745  0.997  0.987381  0.0  1.001458  0.966975
3746  0.998  0.987426  0.0  1.001535  0.967016
3747  0.998  0.987470  0.0  1.001612  0.967057
3748  0.999  0.987515  0.0  1.001688  0.967098

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.987604  0.0  1.001841  0.967179
3751  1.002  0.987648  0.0  1.001918  0.967220
3752  1.002  0.987692  0.0  1.001994  0.967261
3753  1.003  0.987737  0.0  1.002070  0.967302

3750
interpolation

/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(

         x1         y  rep    ymodel      ybms
3745  0.997  0.053138  1.0  0.100750  0.024101
3746  0.998  0.053057  1.0  0.100608  0.023631
3747  0.998  0.052975  1.0  0.100466  0.023160
3748  0.999  0.052894  1.0  0.100324  0.022689

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.052733  1.0  0.100042  0.021747
3751  1.002  0.052652  1.0  0.099901  0.021275
3752  1.002  0.052571  1.0  0.099760  0.020804
3753  1.003  0.052491  1.0  0.099619  0.020331

3750
interpolation

/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(

         x1         y  rep    ymodel      ybms
3745  0.997  0.277484  2.0  0.308693  0.417432
3746  0.998  0.277627  2.0  0.309334  0.418478
3747  0.998  0.277770  2.0  0.309974  0.419523
3748  0.999  0.277912  2.0  0.310615  0.420566

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.278193  2.0  0.311895  0.422649
3751  1.002  0.278333  2.0  0.312535  0.423688
3752  1.002  0.278471  2.0  0.313175  0.424726
3753  1.003  0.278610  2.0  0.313815  0.425763

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.306760  3.0  0.390063  0.313949
3746  0.998  0.307033  3.0  0.390501  0.314327
3747  0.998  0.307306  3.0  0.390939  0.314705
3748  0.999  0.307578  3.0  0.391375  0.315083

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.308120  3.0  0.392248  0.315840
3751  1.002  0.308390  3.0  0.392683  0.316219
3752  1.002  0.308660  3.0  0.393117  0.316598
3753  1.003  0.308928  3.0  0.393551  0.316977

3750
interpolation

<lambdifygenerated-10645>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1
<lambdifygenerated-10646>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1
<lambdifygenerated-10649>:2: RuntimeWarning: invalid value encountered in power
  return _a5_**(x1**x1)
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-10650>:2: RuntimeWarning: invalid value encountered in power
  return _a5_**(x1**x1)

         x1         y  rep    ymodel      ybms
3745  0.997  0.965360  4.0  0.957719  0.999655
3746  0.998  0.965399  4.0  0.957720  0.999657
3747  0.998  0.965439  4.0  0.957721  0.999660
3748  0.999  0.965479  4.0  0.957722  0.999662

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.965559  4.0  0.957725  0.999666
3751  1.002  0.965598  4.0  0.957726  0.999668
3752  1.002  0.965638  4.0  0.957727  0.999670
3753  1.003  0.965678  4.0  0.957728  0.999672

3750

<lambdifygenerated-10669>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1 + x1**x1)
<lambdifygenerated-10670>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1 + x1**x1)
<lambdifygenerated-10673>:2: RuntimeWarning: invalid value encountered in power
  return x1*(_a6_**(x1**x1) + x1)
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-10674>:2: RuntimeWarning: invalid value encountered in power
  return x1*(_a6_**(x1**x1) + x1)
<lambdifygenerated-10675>:2: RuntimeWarning: invalid value encountered in power
  return x1*(_a6_**(_a7_**x1) + x1)

interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.308339  5.0  0.295370  0.309079
3746  0.998  0.308354  5.0  0.295385  0.309079
3747  0.998  0.308368  5.0  0.295399  0.309079
3748  0.999  0.308382  5.0  0.295414  0.309079

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.308407  5.0  0.295443  0.309079
3751  1.002  0.308419  5.0  0.295457  0.309079
3752  1.002  0.308430  5.0  0.295472  0.309079
3753  1.003  0.308441  5.0  0.295486  0.309079

3750
interpolation

/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(

         x1         y  rep    ymodel      ybms
3745  0.997  0.215897  6.0  0.124807  0.197735
3746  0.998  0.216041  6.0  0.124735  0.197761
3747  0.998  0.216186  6.0  0.124662  0.197788
3748  0.999  0.216330  6.0  0.124589  0.197814

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.216618  6.0  0.124443  0.197866
3751  1.002  0.216762  6.0  0.124370  0.197892
3752  1.002  0.216905  6.0  0.124296  0.197918
3753  1.003  0.217048  6.0  0.124222  0.197943

3750
interpolation

<lambdifygenerated-10727>:2: RuntimeWarning: invalid value encountered in power
  return _a4_*x1**x1
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-10728>:2: RuntimeWarning: invalid value encountered in power
  return _a4_*x1**x1

         x1         y  rep    ymodel      ybms
3745  0.997  0.100918  7.0  0.145004  0.087883
3746  0.998  0.100912  7.0  0.145023  0.087820
3747  0.998  0.100906  7.0  0.145042  0.087757
3748  0.999  0.100901  7.0  0.145060  0.087694

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.100890  7.0  0.145097  0.087568
3751  1.002  0.100885  7.0  0.145116  0.087506
3752  1.002  0.100880  7.0  0.145134  0.087443
3753  1.003  0.100874  7.0  0.145152  0.087381

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.825595  8.0  0.714535  0.853586
3746  0.998  0.825925  8.0  0.714367  0.854216
3747  0.998  0.826254  8.0  0.714198  0.854846
3748  0.999  0.826582  8.0  0.714027  0.855475

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.827238  8.0  0.713682  0.856735
3751  1.002  0.827565  8.0  0.713507  0.857364
3752  1.002  0.827892  8.0  0.713331  0.857994
3753  1.003  0.828218  8.0  0.713153  0.858624

3750
interpolation

<lambdifygenerated-10781>:2: RuntimeWarning: invalid value encountered in power
  return _a7_/(x1 + x1**x1)
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-10782>:2: RuntimeWarning: invalid value encountered in power
  return _a7_/(x1 + x1**x1)
<lambdifygenerated-10787>:2: RuntimeWarning: invalid value encountered in power
  return _a7_/(_a6_**x1 + _a7_)

         x1         y  rep    ymodel      ybms
3745  0.997  0.855453  9.0  0.844941  0.909931
3746  0.998  0.855554  9.0  0.844880  0.910101
3747  0.998  0.855656  9.0  0.844819  0.910271
3748  0.999  0.855757  9.0  0.844757  0.910441

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.855960  9.0  0.844632  0.910780
3751  1.002  0.856062  9.0  0.844570  0.910948
3752  1.002  0.856163  9.0  0.844506  0.911117
3753  1.003  0.856265  9.0  0.844443  0.911285

3750
interpolation

<lambdifygenerated-10797>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1
<lambdifygenerated-10798>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1
<lambdifygenerated-10801>:2: RuntimeWarning: invalid value encountered in power
  return _a2_**(x1**x1)
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-10802>:2: RuntimeWarning: invalid value encountered in power
  return _a2_**(x1**x1)

         x1         y  rep    ymodel      ybms
3745  0.997  0.987381  0.0  0.992476  0.968891
3746  0.998  0.987426  0.0  0.992553  0.968931
3747  0.998  0.987470  0.0  0.992630  0.968971
3748  0.999  0.987515  0.0  0.992706  0.969011

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.987604  0.0  0.992859  0.969090
3751  1.002  0.987648  0.0  0.992936  0.969129
3752  1.002  0.987692  0.0  0.993012  0.969169
3753  1.003  0.987737  0.0  0.993089  0.969208

3750
interpolation

<lambdifygenerated-10823>:2: RuntimeWarning: invalid value encountered in power
  return 2*x1 + tanh(x1**x1)
<lambdifygenerated-10824>:2: RuntimeWarning: invalid value encountered in power
  return 2*x1 + tanh(x1**x1)
<lambdifygenerated-10825>:2: RuntimeWarning: invalid value encountered in power
  return 2*x1 + tanh(_a4_**x1)

         x1         y  rep    ymodel      ybms
3745  0.997  0.053138  1.0 -0.013869 -0.014148
3746  0.998  0.053057  1.0 -0.014285 -0.014606
3747  0.998  0.052975  1.0 -0.014701 -0.015065
3748  0.999  0.052894  1.0 -0.015117 -0.015523

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.052733  1.0 -0.015949 -0.016440
3751  1.002  0.052652  1.0 -0.016365 -0.016898
3752  1.002  0.052571  1.0 -0.016781 -0.017356
3753  1.003  0.052491  1.0 -0.017197 -0.017815

3750
interpolation

<lambdifygenerated-10845>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1
<lambdifygenerated-10846>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1
<lambdifygenerated-10853>:2: RuntimeWarning: invalid value encountered in power
  return _a2_**(_a2_ + x1**x1)
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-10854>:2: RuntimeWarning: invalid value encountered in power
  return _a2_**(_a2_ + x1**x1)

         x1         y  rep    ymodel      ybms
3745  0.997  0.277484  2.0  0.284279  0.295134
3746  0.998  0.277627  2.0  0.284777  0.295589
3747  0.998  0.277770  2.0  0.285274  0.296042
3748  0.999  0.277912  2.0  0.285771  0.296495

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.278193  2.0  0.286764  0.297399
3751  1.002  0.278333  2.0  0.287260  0.297850
3752  1.002  0.278471  2.0  0.287755  0.298300
3753  1.003  0.278610  2.0  0.288250  0.298749

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.306760  3.0  0.305839  0.275694
3746  0.998  0.307033  3.0  0.306234  0.276025
3747  0.998  0.307306  3.0  0.306629  0.276357
3748  0.999  0.307578  3.0  0.307023  0.276690

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.308120  3.0  0.307807  0.277354
3751  1.002  0.308390  3.0  0.308198  0.277687
3752  1.002  0.308660  3.0  0.308589  0.278020
3753  1.003  0.308928  3.0  0.308978  0.278353

3750
interpolation

<lambdifygenerated-10895>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1
<lambdifygenerated-10896>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1

         x1         y  rep    ymodel      ybms
3745  0.997  0.965360  4.0  0.977677  0.999689
3746  0.998  0.965399  4.0  0.977710  0.999691
3747  0.998  0.965439  4.0  0.977742  0.999693
3748  0.999  0.965479  4.0  0.977775  0.999695

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.965559  4.0  0.977840  0.999699
3751  1.002  0.965598  4.0  0.977873  0.999701
3752  1.002  0.965638  4.0  0.977905  0.999703
3753  1.003  0.965678  4.0  0.977938  0.999704

3750
interpolation

<lambdifygenerated-10919>:2: RuntimeWarning: invalid value encountered in power
  return x1*x1**x1 + x1
<lambdifygenerated-10920>:2: RuntimeWarning: invalid value encountered in power
  return x1*x1**x1 + x1
<lambdifygenerated-10923>:2: RuntimeWarning: invalid value encountered in power
  return _a0_**(x1**x1)*x1 + x1
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-10924>:2: RuntimeWarning: invalid value encountered in power
  return _a0_**(x1**x1)*x1 + x1
<lambdifygenerated-10925>:2: RuntimeWarning: invalid value encountered in power
  return _a0_**(_a3_**x1)*x1 + x1

         x1         y  rep    ymodel      ybms
3745  0.997  0.308339  5.0  0.341620  0.301144
3746  0.998  0.308354  5.0  0.341698  0.301144
3747  0.998  0.308368  5.0  0.341775  0.301144
3748  0.999  0.308382  5.0  0.341852  0.301144

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.308407  5.0  0.342005  0.301144
3751  1.002  0.308419  5.0  0.342081  0.301144
3752  1.002  0.308430  5.0  0.342157  0.301144
3753  1.003  0.308441  5.0  0.342233  0.301144

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.215897  6.0  0.227105  0.234433
3746  0.998  0.216041  6.0  0.227291  0.234712
3747  0.998  0.216186  6.0  0.227478  0.234990
3748  0.999  0.216330  6.0  0.227663  0.235268

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.216618  6.0  0.228032  0.235824
3751  1.002  0.216762  6.0  0.228216  0.236102
3752  1.002  0.216905  6.0  0.228400  0.236379
3753  1.003  0.217048  6.0  0.228583  0.236657

3750
interpolation

<lambdifygenerated-10971>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1/x1
<lambdifygenerated-10972>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1/x1
<lambdifygenerated-10983>:2: RuntimeWarning: overflow encountered in power
  return ((_a2_ + x1)**2)**(_a0_/x1)/x1
/usr/local/lib/python3.10/dist-packages/scipy/optimize/_minpack_py.py:1017: RuntimeWarning: overflow encountered in square
  cost = np.sum(infodict['fvec'] ** 2)
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
/usr/local/lib/python3.10/dist-packages/pandas/core/arraylike.py:399: RuntimeWarning: overflow encountered in square
  result = getattr(ufunc, method)(*inputs, **kwargs)
<lambdifygenerated-10984>:2: RuntimeWarning: overflow encountered in power
  return ((_a2_ + x1)**2)**(_a0_/x1)/x1
<lambdifygenerated-10985>:2: RuntimeWarning: invalid value encountered in power
  return ((_a2_ + x1)**2)**(_a0_*x1**(-x1))/x1
<lambdifygenerated-10986>:2: RuntimeWarning: invalid value encountered in power
  return ((_a2_ + x1)**2)**(_a0_*x1**(-x1))/x1

         x1         y  rep    ymodel      ybms
3745  0.997  0.100918  7.0  0.131238  0.100435
3746  0.998  0.100912  7.0  0.131351  0.100411
3747  0.998  0.100906  7.0  0.131464  0.100386
3748  0.999  0.100901  7.0  0.131576  0.100361

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.100890  7.0  0.131801  0.100312
3751  1.002  0.100885  7.0  0.131914  0.100288
3752  1.002  0.100880  7.0  0.132026  0.100263
3753  1.003  0.100874  7.0  0.132139  0.100239

3750
interpolation

<lambdifygenerated-11001>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1
<lambdifygenerated-11002>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1
<lambdifygenerated-11007>:2: RuntimeWarning: invalid value encountered in power
  return _a5_**tanh(x1**x1)
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-11008>:2: RuntimeWarning: invalid value encountered in power
  return _a5_**tanh(x1**x1)

         x1         y  rep    ymodel      ybms
3745  0.997  0.825595  8.0  0.793197  0.842715
3746  0.998  0.825925  8.0  0.793432  0.843037
3747  0.998  0.826254  8.0  0.793666  0.843359
3748  0.999  0.826582  8.0  0.793899  0.843680

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.827238  8.0  0.794366  0.844321
3751  1.002  0.827565  8.0  0.794598  0.844641
3752  1.002  0.827892  8.0  0.794830  0.844959
3753  1.003  0.828218  8.0  0.795062  0.845278

<lambdifygenerated-11021>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1
<lambdifygenerated-11022>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1

3750
interpolation

<lambdifygenerated-11027>:2: RuntimeWarning: invalid value encountered in power
  return _a6_**(x1**(2*x1))
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-11028>:2: RuntimeWarning: invalid value encountered in power
  return _a6_**(x1**(2*x1))

         x1         y  rep    ymodel      ybms
3745  0.997  0.855453  9.0  0.838664  0.847750
3746  0.998  0.855554  9.0  0.838748  0.847923
3747  0.998  0.855656  9.0  0.838832  0.848097
3748  0.999  0.855757  9.0  0.838915  0.848270

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.855960  9.0  0.839082  0.848617
3751  1.002  0.856062  9.0  0.839165  0.848790
3752  1.002  0.856163  9.0  0.839248  0.848962
3753  1.003  0.856265  9.0  0.839331  0.849135

3750
interpolation

<lambdifygenerated-11049>:2: RuntimeWarning: invalid value encountered in power
  return tanh(x1**(-x1)*exp(x1))
<lambdifygenerated-11050>:2: RuntimeWarning: invalid value encountered in power
  return tanh(x1**(-x1)*exp(x1))

         x1         y  rep    ymodel      ybms
3745  0.997  0.987381  0.0  0.995023  0.999651
3746  0.998  0.987426  0.0  0.995063  0.999651
3747  0.998  0.987470  0.0  0.995104  0.999651
3748  0.999  0.987515  0.0  0.995145  0.999651

extrapolation

         x1         y  rep    ymodel     ybms
3750  1.001  0.987604  0.0  0.995226  0.99965
3751  1.002  0.987648  0.0  0.995267  0.99965
3752  1.002  0.987692  0.0  0.995307  0.99965
3753  1.003  0.987737  0.0  0.995347  0.99965

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.053138  1.0  0.044836  0.162251
3746  0.998  0.053057  1.0  0.044696  0.162629
3747  0.998  0.052975  1.0  0.044557  0.163008
3748  0.999  0.052894  1.0  0.044418  0.163386

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.052733  1.0  0.044141  0.164143
3751  1.002  0.052652  1.0  0.044003  0.164521
3752  1.002  0.052571  1.0  0.043865  0.164899
3753  1.003  0.052491  1.0  0.043727  0.165278

3750
interpolation

<lambdifygenerated-11111>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1/x1
<lambdifygenerated-11112>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1/x1
<lambdifygenerated-11123>:2: RuntimeWarning: invalid value encountered in power
  return (_a5_**4*cos(x1**x1)**4)**x1/x1
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-11124>:2: RuntimeWarning: invalid value encountered in power
  return (_a5_**4*cos(x1**x1)**4)**x1/x1

         x1         y  rep    ymodel      ybms
3745  0.997  0.277484  2.0  0.318368  0.148258
3746  0.998  0.277627  2.0  0.318972  0.147468
3747  0.998  0.277770  2.0  0.319575  0.146671
3748  0.999  0.277912  2.0  0.320178  0.145869

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.278193  2.0  0.321384  0.144249
3751  1.002  0.278333  2.0  0.321987  0.143431
3752  1.002  0.278471  2.0  0.322590  0.142608
3753  1.003  0.278610  2.0  0.323192  0.141780

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.306760  3.0  0.338737  0.421010
3746  0.998  0.307033  3.0  0.339039  0.421895
3747  0.998  0.307306  3.0  0.339340  0.422780
3748  0.999  0.307578  3.0  0.339641  0.423667

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.308120  3.0  0.340242  0.425445
3751  1.002  0.308390  3.0  0.340542  0.426336
3752  1.002  0.308660  3.0  0.340841  0.427229
3753  1.003  0.308928  3.0  0.341140  0.428123

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.965360  4.0  0.935868  0.925811
3746  0.998  0.965399  4.0  0.935935  0.925811
3747  0.998  0.965439  4.0  0.936003  0.925811
3748  0.999  0.965479  4.0  0.936070  0.925812

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.965559  4.0  0.936205  0.925812
3751  1.002  0.965598  4.0  0.936273  0.925812
3752  1.002  0.965638  4.0  0.936340  0.925812
3753  1.003  0.965678  4.0  0.936407  0.925812

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.308339  5.0  0.293313  0.299096
3746  0.998  0.308354  5.0  0.293431  0.299319
3747  0.998  0.308368  5.0  0.293548  0.299544
3748  0.999  0.308382  5.0  0.293666  0.299770

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.308407  5.0  0.293901  0.300225
3751  1.002  0.308419  5.0  0.294019  0.300454
3752  1.002  0.308430  5.0  0.294137  0.300684
3753  1.003  0.308441  5.0  0.294255  0.300916

3750

<lambdifygenerated-11217>:2: RuntimeWarning: invalid value encountered in power
  return tanh((x1 + x1**x1)**2)
<lambdifygenerated-11218>:2: RuntimeWarning: invalid value encountered in power
  return tanh((x1 + x1**x1)**2)
<lambdifygenerated-11219>:2: RuntimeWarning: overflow encountered in square
  return tanh((_a5_**x1 + x1)**2)
<lambdifygenerated-11219>:2: RuntimeWarning: overflow encountered in power
  return tanh((_a5_**x1 + x1)**2)
/usr/local/lib/python3.10/dist-packages/scipy/optimize/_minpack_py.py:497: RuntimeWarning: overflow encountered in matmul
  cov_x = invR @ invR.T
<lambdifygenerated-11220>:2: RuntimeWarning: overflow encountered in power
  return tanh((_a5_**x1 + x1)**2)
<lambdifygenerated-11220>:2: RuntimeWarning: overflow encountered in square
  return tanh((_a5_**x1 + x1)**2)
<lambdifygenerated-11221>:2: RuntimeWarning: overflow encountered in power
  return tanh((_a5_**x1 + x1)**2)
<lambdifygenerated-11221>:2: RuntimeWarning: overflow encountered in square
  return tanh((_a5_**x1 + x1)**2)
<lambdifygenerated-11222>:2: RuntimeWarning: overflow encountered in power
  return tanh((_a5_**x1 + x1)**2)
<lambdifygenerated-11222>:2: RuntimeWarning: overflow encountered in square
  return tanh((_a5_**x1 + x1)**2)
<lambdifygenerated-11223>:2: RuntimeWarning: overflow encountered in power
  return tanh((_a5_**x1 + _a6_)**2)
<lambdifygenerated-11223>:2: RuntimeWarning: overflow encountered in square
  return tanh((_a5_**x1 + _a6_)**2)

interpolation

/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(

         x1         y  rep    ymodel      ybms
3745  0.997  0.215897  6.0  0.225590  0.254025
3746  0.998  0.216041  6.0  0.225844  0.254305
3747  0.998  0.216186  6.0  0.226098  0.254586
3748  0.999  0.216330  6.0  0.226352  0.254866

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.216618  6.0  0.226862  0.255426
3751  1.002  0.216762  6.0  0.227117  0.255705
3752  1.002  0.216905  6.0  0.227373  0.255985
3753  1.003  0.217048  6.0  0.227628  0.256264

3750

<lambdifygenerated-11235>:2: RuntimeWarning: invalid value encountered in power
  return x1*x1**x1
<lambdifygenerated-11236>:2: RuntimeWarning: invalid value encountered in power
  return x1*x1**x1
<lambdifygenerated-11239>:2: RuntimeWarning: invalid value encountered in power
  return _a1_**(x1**2)*x1
<lambdifygenerated-11241>:2: RuntimeWarning: invalid value encountered in power
  return _a1_**(4*x1**2)*x1

interpolation

<lambdifygenerated-11243>:2: RuntimeWarning: invalid value encountered in power
  return _a1_**((_a2_ + x1)**2)*x1
<lambdifygenerated-11247>:2: RuntimeWarning: invalid value encountered in power
  return _a1_**((_a2_ + x1)**2)*_a2_
<lambdifygenerated-11251>:2: RuntimeWarning: invalid value encountered in power
  return _a1_**((_a2_ + x1)**2)*_a2_

         x1         y  rep    ymodel      ybms
3745  0.997  0.100918  7.0  0.098757  0.008368
3746  0.998  0.100912  7.0  0.099066  0.008331
3747  0.998  0.100906  7.0  0.099376  0.008294
3748  0.999  0.100901  7.0  0.099687  0.008258

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.100890  7.0  0.100313  0.008185
3751  1.002  0.100885  7.0  0.100628  0.008149
3752  1.002  0.100880  7.0  0.100944  0.008113
3753  1.003  0.100874  7.0  0.101261  0.008077

3750
interpolation

<lambdifygenerated-11263>:2: RuntimeWarning: invalid value encountered in power
  return x1*(2*x1 + x1**x1)
<lambdifygenerated-11264>:2: RuntimeWarning: invalid value encountered in power
  return x1*(2*x1 + x1**x1)

         x1         y  rep    ymodel      ybms
3745  0.997  0.825595  8.0  0.732029  0.843418
3746  0.998  0.825925  8.0  0.732449  0.843949
3747  0.998  0.826254  8.0  0.732869  0.844480
3748  0.999  0.826582  8.0  0.733289  0.845011

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.827238  8.0  0.734129  0.846073
3751  1.002  0.827565  8.0  0.734549  0.846604
3752  1.002  0.827892  8.0  0.734969  0.847134
3753  1.003  0.828218  8.0  0.735388  0.847665

3750
interpolation

<lambdifygenerated-11291>:2: RuntimeWarning: invalid value encountered in power
  return _a0_/(x1 + x1**x1)
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-11292>:2: RuntimeWarning: invalid value encountered in power
  return _a0_/(x1 + x1**x1)
<lambdifygenerated-11297>:2: RuntimeWarning: invalid value encountered in power
  return _a0_/(_a0_ + _a5_**x1)

         x1         y  rep    ymodel      ybms
3745  0.997  0.855453  9.0  0.832798  0.931168
3746  0.998  0.855554  9.0  0.832169  0.931312
3747  0.998  0.855656  9.0  0.831535  0.931455
3748  0.999  0.855757  9.0  0.830895  0.931597

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.855960  9.0  0.829600  0.931882
3751  1.002  0.856062  9.0  0.828944  0.932023
3752  1.002  0.856163  9.0  0.828283  0.932165
3753  1.003  0.856265  9.0  0.827617  0.932306

3750
interpolation

<lambdifygenerated-11307>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1
<lambdifygenerated-11308>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1
<lambdifygenerated-11311>:2: RuntimeWarning: invalid value encountered in power
  return _a5_**(x1**x1)
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-11312>:2: RuntimeWarning: invalid value encountered in power
  return _a5_**(x1**x1)
<lambdifygenerated-11313>:2: RuntimeWarning: invalid value encountered in power
  return _a5_**(_a1_**x1)

         x1         y  rep    ymodel      ybms
3745  0.997  0.987381  0.0  0.888682  0.974461
3746  0.998  0.987426  0.0  0.888164  0.974495
3747  0.998  0.987470  0.0  0.887645  0.974529
3748  0.999  0.987515  0.0  0.887126  0.974563

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.987604  0.0  0.886083  0.974630
3751  1.002  0.987648  0.0  0.885560  0.974664
3752  1.002  0.987692  0.0  0.885036  0.974697
3753  1.003  0.987737  0.0  0.884510  0.974731

3750

<lambdifygenerated-11325>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1
<lambdifygenerated-11326>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1

interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.053138  1.0  0.012433  0.057021
3746  0.998  0.053057  1.0  0.012168  0.057517
3747  0.998  0.052975  1.0  0.011903  0.058011
3748  0.999  0.052894  1.0  0.011638  0.058502

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.052733  1.0  0.011109  0.059477
3751  1.002  0.052652  1.0  0.010844  0.059960
3752  1.002  0.052571  1.0  0.010580  0.060441
3753  1.003  0.052491  1.0  0.010316  0.060920

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.277484  2.0  0.405506  0.408037
3746  0.998  0.277627  2.0  0.406334  0.408930
3747  0.998  0.277770  2.0  0.407162  0.409824
3748  0.999  0.277912  2.0  0.407989  0.410719

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.278193  2.0  0.409642  0.412510
3751  1.002  0.278333  2.0  0.410468  0.413407
3752  1.002  0.278471  2.0  0.411293  0.414304
3753  1.003  0.278610  2.0  0.412118  0.415203

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.306760  3.0  0.298288  0.416592
3746  0.998  0.307033  3.0  0.298499  0.417596
3747  0.998  0.307306  3.0  0.298708  0.418601
3748  0.999  0.307578  3.0  0.298918  0.419608

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.308120  3.0  0.299335  0.421627
3751  1.002  0.308390  3.0  0.299543  0.422639
3752  1.002  0.308660  3.0  0.299750  0.423653
3753  1.003  0.308928  3.0  0.299957  0.424668

3750
interpolation

         x1         y  rep    ymodel     ybms
3745  0.997  0.965360  4.0  0.979090  0.95508
3746  0.998  0.965399  4.0  0.979070  0.95508
3747  0.998  0.965439  4.0  0.979049  0.95508
3748  0.999  0.965479  4.0  0.979029  0.95508

extrapolation

         x1         y  rep    ymodel     ybms
3750  1.001  0.965559  4.0  0.978988  0.95508
3751  1.002  0.965598  4.0  0.978967  0.95508
3752  1.002  0.965638  4.0  0.978946  0.95508
3753  1.003  0.965678  4.0  0.978926  0.95508

3750
interpolation

<lambdifygenerated-11437>:2: RuntimeWarning: invalid value encountered in power
  return x1*x1**x1 + x1
<lambdifygenerated-11438>:2: RuntimeWarning: invalid value encountered in power
  return x1*x1**x1 + x1
<lambdifygenerated-11441>:2: RuntimeWarning: invalid value encountered in power
  return _a1_**(x1**x1)*x1 + x1
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-11442>:2: RuntimeWarning: invalid value encountered in power
  return _a1_**(x1**x1)*x1 + x1
<lambdifygenerated-11443>:2: RuntimeWarning: invalid value encountered in power
  return _a1_**(_a0_**x1)*x1 + x1

         x1         y  rep    ymodel      ybms
3745  0.997  0.308339  5.0  0.304052  0.291855
3746  0.998  0.308354  5.0  0.304055  0.291855
3747  0.998  0.308368  5.0  0.304058  0.291855
3748  0.999  0.308382  5.0  0.304061  0.291855

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.308407  5.0  0.304067  0.291855
3751  1.002  0.308419  5.0  0.304069  0.291855
3752  1.002  0.308430  5.0  0.304072  0.291855
3753  1.003  0.308441  5.0  0.304075  0.291855

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.215897  6.0  0.196562  0.255641
3746  0.998  0.216041  6.0  0.196604  0.255910
3747  0.998  0.216186  6.0  0.196646  0.256179
3748  0.999  0.216330  6.0  0.196687  0.256447

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.216618  6.0  0.196770  0.256984
3751  1.002  0.216762  6.0  0.196812  0.257252
3752  1.002  0.216905  6.0  0.196853  0.257520
3753  1.003  0.217048  6.0  0.196894  0.257787

3750

<lambdifygenerated-11487>:2: RuntimeWarning: invalid value encountered in power
  return x1*x1**x1
<lambdifygenerated-11488>:2: RuntimeWarning: invalid value encountered in power
  return x1*x1**x1
<lambdifygenerated-11491>:2: RuntimeWarning: invalid value encountered in power
  return _a1_**(x1**2)*x1
<lambdifygenerated-11493>:2: RuntimeWarning: invalid value encountered in power
  return _a1_**(4*x1**2)*x1

interpolation

<lambdifygenerated-11497>:2: RuntimeWarning: invalid value encountered in power
  return _a1_**((_a3_ + x1)**2)*x1
<lambdifygenerated-11499>:2: RuntimeWarning: invalid value encountered in power
  return _a1_**((_a3_ + x1)**2)*_a3_
<lambdifygenerated-11503>:2: RuntimeWarning: invalid value encountered in power
  return _a1_**((_a3_ + x1)**2)*_a3_

         x1         y  rep    ymodel      ybms
3745  0.997  0.100918  7.0  0.134688  0.005270
3746  0.998  0.100912  7.0  0.134868  0.005244
3747  0.998  0.100906  7.0  0.135049  0.005218
3748  0.999  0.100901  7.0  0.135229  0.005192

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.100890  7.0  0.135590  0.005141
3751  1.002  0.100885  7.0  0.135770  0.005115
3752  1.002  0.100880  7.0  0.135951  0.005089
3753  1.003  0.100874  7.0  0.136131  0.005064

3750
interpolation

<lambdifygenerated-11511>:2: RuntimeWarning: invalid value encountered in power
  return x1 + x1**x1
<lambdifygenerated-11512>:2: RuntimeWarning: invalid value encountered in power
  return x1 + x1**x1
<lambdifygenerated-11515>:2: RuntimeWarning: invalid value encountered in power
  return _a1_**(x1**x1) + x1
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-11516>:2: RuntimeWarning: invalid value encountered in power
  return _a1_**(x1**x1) + x1
<lambdifygenerated-11521>:2: RuntimeWarning: invalid value encountered in power
  return _a1_ + _a1_**(_a3_**x1)

         x1         y  rep    ymodel      ybms
3745  0.997  0.825595  8.0  0.836140  0.830713
3746  0.998  0.825925  8.0  0.836664  0.831092
3747  0.998  0.826254  8.0  0.837187  0.831470
3748  0.999  0.826582  8.0  0.837710  0.831848

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.827238  8.0  0.838756  0.832602
3751  1.002  0.827565  8.0  0.839279  0.832979
3752  1.002  0.827892  8.0  0.839801  0.833355
3753  1.003  0.828218  8.0  0.840323  0.833730

3750
interpolation

<lambdifygenerated-11531>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1
<lambdifygenerated-11532>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1
<lambdifygenerated-11535>:2: RuntimeWarning: invalid value encountered in power
  return _a0_**(x1**x1)
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-11536>:2: RuntimeWarning: invalid value encountered in power
  return _a0_**(x1**x1)
<lambdifygenerated-11537>:2: RuntimeWarning: invalid value encountered in power
  return _a0_**(_a3_**x1)

         x1         y  rep    ymodel      ybms
3745  0.997  0.855453  9.0  0.864587  0.863523
3746  0.998  0.855554  9.0  0.864744  0.863689
3747  0.998  0.855656  9.0  0.864902  0.863855
3748  0.999  0.855757  9.0  0.865059  0.864021

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.855960  9.0  0.865373  0.864353
3751  1.002  0.856062  9.0  0.865530  0.864518
3752  1.002  0.856163  9.0  0.865687  0.864683
3753  1.003  0.856265  9.0  0.865844  0.864848

3750
interpolation

<lambdifygenerated-11549>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1
<lambdifygenerated-11550>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1
<lambdifygenerated-11553>:2: RuntimeWarning: invalid value encountered in power
  return _a3_**(x1**x1)
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-11554>:2: RuntimeWarning: invalid value encountered in power
  return _a3_**(x1**x1)
<lambdifygenerated-11555>:2: RuntimeWarning: invalid value encountered in power
  return _a3_**(-x1**x1)
<lambdifygenerated-11556>:2: RuntimeWarning: invalid value encountered in power
  return _a3_**(-x1**x1)
<lambdifygenerated-11557>:2: RuntimeWarning: invalid value encountered in power
  return _a3_**(-_a1_**x1)

         x1         y  rep    ymodel      ybms
3745  0.997  0.987381  0.0  1.028264  0.955696
3746  0.998  0.987426  0.0  1.028408  0.955744
3747  0.998  0.987470  0.0  1.028553  0.955793
3748  0.999  0.987515  0.0  1.028697  0.955841

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.987604  0.0  1.028985  0.955937
3751  1.002  0.987648  0.0  1.029129  0.955985
3752  1.002  0.987692  0.0  1.029272  0.956033
3753  1.003  0.987737  0.0  1.029416  0.956081

3750
interpolation

<lambdifygenerated-11573>:2: RuntimeWarning: invalid value encountered in power
  return x1**(3/2) + x1
<lambdifygenerated-11574>:2: RuntimeWarning: invalid value encountered in power
  return x1**(3/2) + x1
<lambdifygenerated-11579>:2: RuntimeWarning: invalid value encountered in power
  return x1*sqrt((x1 + x1**x1)**2) + x1
<lambdifygenerated-11580>:2: RuntimeWarning: invalid value encountered in power
  return x1*sqrt((x1 + x1**x1)**2) + x1
<lambdifygenerated-11593>:2: RuntimeWarning: overflow encountered in square
  return _a0_*sqrt((_a2_ + ((_a7_ + x1)**2)**_a0_)**2) + x1
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(

         x1         y  rep    ymodel      ybms
3745  0.997  0.053138  1.0  0.035747  0.185202
3746  0.998  0.053057  1.0  0.035577  0.185550
3747  0.998  0.052975  1.0  0.035406  0.185897
3748  0.999  0.052894  1.0  0.035236  0.186245

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.052733  1.0  0.034896  0.186940
3751  1.002  0.052652  1.0  0.034727  0.187287
3752  1.002  0.052571  1.0  0.034557  0.187635
3753  1.003  0.052491  1.0  0.034388  0.187982

3750
interpolation

<lambdifygenerated-11607>:2: RuntimeWarning: invalid value encountered in power
  return x1 + x1**x1
<lambdifygenerated-11608>:2: RuntimeWarning: invalid value encountered in power
  return x1 + x1**x1

         x1         y  rep    ymodel      ybms
3745  0.997  0.277484  2.0  0.239858  0.275113
3746  0.998  0.277627  2.0  0.240362  0.275449
3747  0.998  0.277770  2.0  0.240865  0.275784
3748  0.999  0.277912  2.0  0.241369  0.276118

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.278193  2.0  0.242377  0.276786
3751  1.002  0.278333  2.0  0.242880  0.277119
3752  1.002  0.278471  2.0  0.243384  0.277452
3753  1.003  0.278610  2.0  0.243887  0.277784

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.306760  3.0  0.314890  0.279489
3746  0.998  0.307033  3.0  0.315312  0.279825
3747  0.998  0.307306  3.0  0.315734  0.280162
3748  0.999  0.307578  3.0  0.316155  0.280498

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.308120  3.0  0.316995  0.281172
3751  1.002  0.308390  3.0  0.317415  0.281510
3752  1.002  0.308660  3.0  0.317834  0.281847
3753  1.003  0.308928  3.0  0.318252  0.282185

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.965360  4.0  0.969378  0.940415
3746  0.998  0.965399  4.0  0.969676  0.940415
3747  0.998  0.965439  4.0  0.969976  0.940415
3748  0.999  0.965479  4.0  0.970276  0.940415

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.965559  4.0  0.970878  0.940415
3751  1.002  0.965598  4.0  0.971180  0.940415
3752  1.002  0.965638  4.0  0.971483  0.940415
3753  1.003  0.965678  4.0  0.971787  0.940415

3750
interpolation

<lambdifygenerated-11679>:2: RuntimeWarning: invalid value encountered in power
  return x1*x1**x1 + x1
<lambdifygenerated-11680>:2: RuntimeWarning: invalid value encountered in power
  return x1*x1**x1 + x1
<lambdifygenerated-11683>:2: RuntimeWarning: invalid value encountered in power
  return _a6_**(x1**x1)*x1 + x1
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-11684>:2: RuntimeWarning: invalid value encountered in power
  return _a6_**(x1**x1)*x1 + x1
<lambdifygenerated-11685>:2: RuntimeWarning: invalid value encountered in power
  return _a6_**(_a5_**x1)*x1 + x1

         x1         y  rep    ymodel     ybms
3745  0.997  0.308339  5.0  0.327513  0.28965
3746  0.998  0.308354  5.0  0.327561  0.28965
3747  0.998  0.308368  5.0  0.327609  0.28965
3748  0.999  0.308382  5.0  0.327656  0.28965

extrapolation

         x1         y  rep    ymodel     ybms
3750  1.001  0.308407  5.0  0.327750  0.28965
3751  1.002  0.308419  5.0  0.327797  0.28965
3752  1.002  0.308430  5.0  0.327844  0.28965
3753  1.003  0.308441  5.0  0.327890  0.28965

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.215897  6.0  0.186615  0.191626
3746  0.998  0.216041  6.0  0.186606  0.191627
3747  0.998  0.216186  6.0  0.186596  0.191627
3748  0.999  0.216330  6.0  0.186585  0.191628

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.216618  6.0  0.186560  0.191628
3751  1.002  0.216762  6.0  0.186547  0.191627
3752  1.002  0.216905  6.0  0.186533  0.191627
3753  1.003  0.217048  6.0  0.186518  0.191626

3750

<lambdifygenerated-11735>:2: RuntimeWarning: invalid value encountered in power
  return x1*exp(x1*(x1 + x1**x1))
<lambdifygenerated-11736>:2: RuntimeWarning: invalid value encountered in power
  return x1*exp(x1*(x1 + x1**x1))
<lambdifygenerated-11737>:2: RuntimeWarning: invalid value encountered in power
  return x1*exp(x1*(_a1_**x1 + x1))
<lambdifygenerated-11741>:2: RuntimeWarning: invalid value encountered in power
  return x1*exp(x1*(_a1_**x1 + _a7_))
<lambdifygenerated-11741>:2: RuntimeWarning: overflow encountered in multiply
  return x1*exp(x1*(_a1_**x1 + _a7_))
<lambdifygenerated-11741>:2: RuntimeWarning: overflow encountered in power
  return x1*exp(x1*(_a1_**x1 + _a7_))

interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.100918  7.0  0.059700  0.035053
3746  0.998  0.100912  7.0  0.059486  0.034988
3747  0.998  0.100906  7.0  0.059271  0.034922
3748  0.999  0.100901  7.0  0.059055  0.034857

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.100890  7.0  0.058622  0.034727
3751  1.002  0.100885  7.0  0.058404  0.034662
3752  1.002  0.100880  7.0  0.058186  0.034597
3753  1.003  0.100874  7.0  0.057967  0.034532

3750
interpolation

<lambdifygenerated-11755>:2: RuntimeWarning: invalid value encountered in power
  return x1*x1**x1
<lambdifygenerated-11756>:2: RuntimeWarning: invalid value encountered in power
  return x1*x1**x1

         x1         y  rep    ymodel      ybms
3745  0.997  0.825595  8.0  0.788205  0.897280
3746  0.998  0.825925  8.0  0.788550  0.898327
3747  0.998  0.826254  8.0  0.788894  0.899375
3748  0.999  0.826582  8.0  0.789239  0.900425

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.827238  8.0  0.789927  0.902527
3751  1.002  0.827565  8.0  0.790271  0.903580
3752  1.002  0.827892  8.0  0.790614  0.904634
3753  1.003  0.828218  8.0  0.790958  0.905690

3750

<lambdifygenerated-11773>:2: RuntimeWarning: invalid value encountered in power
  return x1*x1**x1
<lambdifygenerated-11774>:2: RuntimeWarning: invalid value encountered in power
  return x1*x1**x1
<lambdifygenerated-11777>:2: RuntimeWarning: invalid value encountered in power
  return _a6_**(x1**x1)*x1
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-11778>:2: RuntimeWarning: invalid value encountered in power
  return _a6_**(x1**x1)*x1

interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.855453  9.0  0.873330  0.961120
3746  0.998  0.855554  9.0  0.873399  0.961432
3747  0.998  0.855656  9.0  0.873469  0.961743
3748  0.999  0.855757  9.0  0.873538  0.962054

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.855960  9.0  0.873675  0.962676
3751  1.002  0.856062  9.0  0.873744  0.962987
3752  1.002  0.856163  9.0  0.873812  0.963297
3753  1.003  0.856265  9.0  0.873880  0.963607

3750
interpolation

<lambdifygenerated-11793>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1
<lambdifygenerated-11794>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1
<lambdifygenerated-11797>:2: RuntimeWarning: invalid value encountered in power
  return _a4_**(x1**x1)
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-11798>:2: RuntimeWarning: invalid value encountered in power
  return _a4_**(x1**x1)
<lambdifygenerated-11799>:2: RuntimeWarning: invalid value encountered in power
  return _a4_**(_a2_**x1)

         x1         y  rep    ymodel      ybms
3745  0.997  0.987381  0.0  1.044846  0.966620
3746  0.998  0.987426  0.0  1.044991  0.966661
3747  0.998  0.987470  0.0  1.045135  0.966702
3748  0.999  0.987515  0.0  1.045280  0.966743

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.987604  0.0  1.045568  0.966825
3751  1.002  0.987648  0.0  1.045713  0.966865
3752  1.002  0.987692  0.0  1.045857  0.966906
3753  1.003  0.987737  0.0  1.046001  0.966947

3750

<lambdifygenerated-11823>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (_a4_ + x1)*(x1 + x1**x1)
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-11824>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (_a4_ + x1)*(x1 + x1**x1)

interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.053138  1.0  0.015435  0.019861
3746  0.998  0.053057  1.0  0.015188  0.019484
3747  0.998  0.052975  1.0  0.014941  0.019107
3748  0.999  0.052894  1.0  0.014694  0.018730

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.052733  1.0  0.014202  0.017977
3751  1.002  0.052652  1.0  0.013956  0.017599
3752  1.002  0.052571  1.0  0.013710  0.017222
3753  1.003  0.052491  1.0  0.013465  0.016845

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.277484  2.0  0.209953  0.377549
3746  0.998  0.277627  2.0  0.210285  0.378773
3747  0.998  0.277770  2.0  0.210617  0.379996
3748  0.999  0.277912  2.0  0.210949  0.381219

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.278193  2.0  0.211613  0.383661
3751  1.002  0.278333  2.0  0.211945  0.384882
3752  1.002  0.278471  2.0  0.212277  0.386101
3753  1.003  0.278610  2.0  0.212608  0.387320

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.306760  3.0  0.308668  0.286582
3746  0.998  0.307033  3.0  0.309132  0.286927
3747  0.998  0.307306  3.0  0.309597  0.287272
3748  0.999  0.307578  3.0  0.310061  0.287617

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.308120  3.0  0.310989  0.288308
3751  1.002  0.308390  3.0  0.311453  0.288654
3752  1.002  0.308660  3.0  0.311917  0.289000
3753  1.003  0.308928  3.0  0.312380  0.289346

3750
interpolation

<lambdifygenerated-11891>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1
<lambdifygenerated-11892>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1
<lambdifygenerated-11893>:2: RuntimeWarning: invalid value encountered in power
  return sin(x1)**x1
<lambdifygenerated-11894>:2: RuntimeWarning: invalid value encountered in power
  return sin(x1)**x1
<lambdifygenerated-11897>:2: RuntimeWarning: invalid value encountered in power
  return sin(_a4_)**exp(x1)
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-11899>:2: RuntimeWarning: invalid value encountered in power
  return sin(_a4_)**exp(x1**2)
<lambdifygenerated-11901>:2: RuntimeWarning: invalid value encountered in power
  return sin(_a4_)**exp(_a4_*x1)
<lambdifygenerated-11907>:2: RuntimeWarning: invalid value encountered in power
  return sin(_a4_)**exp(_a4_*x1)

         x1         y  rep    ymodel      ybms
3745  0.997  0.965360  4.0  0.949413  0.997798
3746  0.998  0.965399  4.0  0.949336  0.997808
3747  0.998  0.965439  4.0  0.949260  0.997818
3748  0.999  0.965479  4.0  0.949184  0.997828

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.965559  4.0  0.949032  0.997848
3751  1.002  0.965598  4.0  0.948957  0.997858
3752  1.002  0.965638  4.0  0.948881  0.997868
3753  1.003  0.965678  4.0  0.948806  0.997878

3750
interpolation

<lambdifygenerated-11915>:2: RuntimeWarning: invalid value encountered in power
  return tanh(x1**x1)
<lambdifygenerated-11916>:2: RuntimeWarning: invalid value encountered in power
  return tanh(x1**x1)

         x1         y  rep    ymodel      ybms
3745  0.997  0.308339  5.0  0.275186  0.178897
3746  0.998  0.308354  5.0  0.275119  0.178656
3747  0.998  0.308368  5.0  0.275052  0.178417
3748  0.999  0.308382  5.0  0.274985  0.178177

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.308407  5.0  0.274852  0.177699
3751  1.002  0.308419  5.0  0.274786  0.177461
3752  1.002  0.308430  5.0  0.274720  0.177222
3753  1.003  0.308441  5.0  0.274654  0.176984

3750

<lambdifygenerated-11929>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1
<lambdifygenerated-11930>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1

interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.215897  6.0  0.223638  0.247034
3746  0.998  0.216041  6.0  0.223909  0.247782
3747  0.998  0.216186  6.0  0.224180  0.248531
3748  0.999  0.216330  6.0  0.224452  0.249283

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.216618  6.0  0.224995  0.250793
3751  1.002  0.216762  6.0  0.225267  0.251550
3752  1.002  0.216905  6.0  0.225539  0.252310
3753  1.003  0.217048  6.0  0.225811  0.253072

3750
interpolation

<lambdifygenerated-11977>:2: RuntimeWarning: overflow encountered in exp
  return _a3_/(x1 + exp(x1**2*(_a1_ + x1)**2))

         x1         y  rep    ymodel      ybms
3745  0.997  0.100918  7.0  0.130448  0.108919
3746  0.998  0.100912  7.0  0.130339  0.108812
3747  0.998  0.100906  7.0  0.130230  0.108706
3748  0.999  0.100901  7.0  0.130121  0.108599

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.100890  7.0  0.129903  0.108385
3751  1.002  0.100885  7.0  0.129794  0.108278
3752  1.002  0.100880  7.0  0.129685  0.108171
3753  1.003  0.100874  7.0  0.129575  0.108063

<lambdifygenerated-11987>:2: RuntimeWarning: invalid value encountered in power
  return sin(x1 + x1**x1)
<lambdifygenerated-11988>:2: RuntimeWarning: invalid value encountered in power
  return sin(x1 + x1**x1)
<lambdifygenerated-11991>:2: RuntimeWarning: invalid value encountered in power
  return sin(_a2_**(x1**x1) + x1)
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-11992>:2: RuntimeWarning: invalid value encountered in power
  return sin(_a2_**(x1**x1) + x1)

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.825595  8.0  0.728821  0.783091
3746  0.998  0.825925  8.0  0.728655  0.783296
3747  0.998  0.826254  8.0  0.728487  0.783500
3748  0.999  0.826582  8.0  0.728318  0.783704

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.827238  8.0  0.727977  0.784111
3751  1.002  0.827565  8.0  0.727804  0.784314
3752  1.002  0.827892  8.0  0.727630  0.784516
3753  1.003  0.828218  8.0  0.727455  0.784718

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.855453  9.0  0.881232  0.925864
3746  0.998  0.855554  9.0  0.881161  0.926018
3747  0.998  0.855656  9.0  0.881090  0.926172
3748  0.999  0.855757  9.0  0.881018  0.926325

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.855960  9.0  0.880873  0.926631
3751  1.002  0.856062  9.0  0.880800  0.926784
3752  1.002  0.856163  9.0  0.880726  0.926936
3753  1.003  0.856265  9.0  0.880652  0.927088

3750
interpolation

<lambdifygenerated-12097>:2: RuntimeWarning: invalid value encountered in power
  return abs(x1 + exp(x1**(2*x1)*tanh(_a2_*x1*cos((_a3_ + x1)*(_a0_/x1 + _a1_)) + _a4_ + (_a5_ + _a6_)*sin(_a0_*x1))**2/_a3_**2))
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-12098>:2: RuntimeWarning: invalid value encountered in power
  return abs(x1 + exp(x1**(2*x1)*tanh(_a2_*x1*cos((_a3_ + x1)*(_a0_/x1 + _a1_)) + _a4_ + (_a5_ + _a6_)*sin(_a0_*x1))**2/_a3_**2))
<lambdifygenerated-12099>:2: RuntimeWarning: invalid value encountered in power
  return abs(x1 + exp(_a6_**(2*x1)*tanh(_a2_*x1*cos((_a3_ + x1)*(_a0_/x1 + _a1_)) + _a4_ + (_a5_ + _a6_)*sin(_a0_*x1))**2/_a3_**2))
<lambdifygenerated-12100>:2: RuntimeWarning: invalid value encountered in power
  return abs(x1 + exp(_a6_**(2*x1)*tanh(_a2_*x1*cos((_a3_ + x1)*(_a0_/x1 + _a1_)) + _a4_ + (_a5_ + _a6_)*sin(_a0_*x1))**2/_a3_**2))
<lambdifygenerated-12101>:2: RuntimeWarning: invalid value encountered in power
  return abs(x1 + exp(_a6_**(2*x1)*tanh(_a2_*x1*cos((_a3_ + x1)*(_a0_/x1 + _a1_)) + _a4_ + (_a5_ + _a6_)*sin(_a0_*x1))**2/_a3_**2))
<lambdifygenerated-12102>:2: RuntimeWarning: invalid value encountered in power
  return abs(x1 + exp(_a6_**(2*x1)*tanh(_a2_*x1*cos((_a3_ + x1)*(_a0_/x1 + _a1_)) + _a4_ + (_a5_ + _a6_)*sin(_a0_*x1))**2/_a3_**2))
<lambdifygenerated-12103>:2: RuntimeWarning: invalid value encountered in power
  return abs(_a7_ + exp(_a6_**(2*x1)*tanh(_a2_*x1*cos((_a3_ + x1)*(_a0_/x1 + _a1_)) + _a4_ + (_a5_ + _a6_)*sin(_a0_*x1))**2/_a3_**2))
<lambdifygenerated-12104>:2: RuntimeWarning: invalid value encountered in power
  return abs(_a7_ + exp(_a6_**(2*x1)*tanh(_a2_*x1*cos((_a3_ + x1)*(_a0_/x1 + _a1_)) + _a4_ + (_a5_ + _a6_)*sin(_a0_*x1))**2/_a3_**2))
<lambdifygenerated-12105>:2: RuntimeWarning: invalid value encountered in power
  return abs(_a7_ + exp(_a6_**(2*x1)*tanh(_a2_*x1*cos((_a3_ + x1)*(_a0_/x1 + _a1_)) + _a4_ + (_a5_ + _a6_)*sin(_a0_*x1))**2/_a3_**2))
<lambdifygenerated-12106>:2: RuntimeWarning: invalid value encountered in power
  return abs(_a7_ + exp(_a6_**(2*x1)*tanh(_a2_*x1*cos((_a3_ + x1)*(_a0_/x1 + _a1_)) + _a4_ + (_a5_ + _a6_)*sin(_a0_*x1))**2/_a3_**2))
<lambdifygenerated-12107>:2: RuntimeWarning: invalid value encountered in power
  return abs(_a7_ + exp(_a6_**(2*x1)*tanh(_a2_*x1*cos((_a3_ + x1)*(_a0_/x1 + _a1_)) + _a4_ + (_a5_ + _a6_)*sin(_a0_*x1))**2/_a3_**2))
<lambdifygenerated-12108>:2: RuntimeWarning: invalid value encountered in power
  return abs(_a7_ + exp(_a6_**(2*x1)*tanh(_a2_*x1*cos((_a3_ + x1)*(_a0_/x1 + _a1_)) + _a4_ + (_a5_ + _a6_)*sin(_a0_*x1))**2/_a3_**2))

         x1         y  rep    ymodel      ybms
3745  0.997  0.360683  0.0  0.357868  0.362100
3746  0.998  0.360826  0.0  0.357995  0.362261
3747  0.998  0.360969  0.0  0.358122  0.362423
3748  0.999  0.361111  0.0  0.358249  0.362584

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.361396  0.0  0.358503  0.362907
3751  1.002  0.361539  0.0  0.358630  0.363069
3752  1.002  0.361681  0.0  0.358757  0.363230
3753  1.003  0.361824  0.0  0.358884  0.363392

3750

<lambdifygenerated-12161>:2: RuntimeWarning: overflow encountered in square
  return x1 + (_a3_*(_a1_*(_a0_ + x1*(_a2_ + x1)) + cosh(_a6_*x1))/cosh(x1*(_a5_*x1 + x1)) + x1)**2
<lambdifygenerated-12167>:2: RuntimeWarning: overflow encountered in square
  return x1 + (_a3_*(_a1_*(_a0_ + x1*(_a2_ + x1)) + cosh(_a6_*x1))/cosh(x1*(_a5_*x1 + _a7_*x1)) + x1)**2
<lambdifygenerated-12169>:2: RuntimeWarning: overflow encountered in square
  return x1 + (_a3_*(_a1_*(_a0_ + x1*(_a2_ + x1)) + cosh(_a6_*x1))/cosh(x1*(_a4_*_a7_ + _a5_*x1)) + x1)**2
<lambdifygenerated-12171>:2: RuntimeWarning: overflow encountered in square
  return x1 + (_a3_*(_a1_*(_a0_ + x1*(_a2_ + x1)) + cosh(_a6_*x1))/cosh(x1**2*(_a4_*_a7_ + _a5_*x1)) + x1)**2
<lambdifygenerated-12177>:2: RuntimeWarning: overflow encountered in square
  return x1 + (_a3_*(_a1_*(_a0_ + x1*(_a2_ + x1)) + cosh(_a6_*x1))/cosh(x1*(_a4_*_a7_ + _a5_*x1)*cos(_a5_/x1)) + x1)**2
<lambdifygenerated-12181>:2: RuntimeWarning: overflow encountered in cosh
  return x1 + (_a3_*(_a1_*(_a0_ + x1*(_a2_ + x1)) + cosh(_a6_*x1))/cosh((_a4_*_a7_ + _a5_*x1)*cos(_a5_/x1)) + x1)**2
<lambdifygenerated-12181>:2: RuntimeWarning: overflow encountered in multiply
  return x1 + (_a3_*(_a1_*(_a0_ + x1*(_a2_ + x1)) + cosh(_a6_*x1))/cosh((_a4_*_a7_ + _a5_*x1)*cos(_a5_/x1)) + x1)**2
<lambdifygenerated-12181>:2: RuntimeWarning: invalid value encountered in divide
  return x1 + (_a3_*(_a1_*(_a0_ + x1*(_a2_ + x1)) + cosh(_a6_*x1))/cosh((_a4_*_a7_ + _a5_*x1)*cos(_a5_/x1)) + x1)**2
<lambdifygenerated-12181>:2: RuntimeWarning: overflow encountered in square
  return x1 + (_a3_*(_a1_*(_a0_ + x1*(_a2_ + x1)) + cosh(_a6_*x1))/cosh((_a4_*_a7_ + _a5_*x1)*cos(_a5_/x1)) + x1)**2
<lambdifygenerated-12185>:2: RuntimeWarning: overflow encountered in square
  return x1 + (_a3_*(_a1_*(_a0_ + x1*(_a2_ + x1)) + cosh(_a6_*x1))/cosh(x1*(_a4_*_a7_ + _a5_*x1)*cos(_a5_/x1)/_a7_) + x1)**2

interpolation

/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(

         x1         y  rep    ymodel      ybms
3745  0.997  0.875844  1.0  0.893601  0.888678
3746  0.998  0.875274  1.0  0.893481  0.888510
3747  0.998  0.874704  1.0  0.893360  0.888342
3748  0.999  0.874135  1.0  0.893239  0.888173

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.872995  1.0  0.892997  0.887834
3751  1.002  0.872426  1.0  0.892876  0.887664
3752  1.002  0.871856  1.0  0.892755  0.887493
3753  1.003  0.871287  1.0  0.892634  0.887322

3750

/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-12223>:2: RuntimeWarning: invalid value encountered in power
  return x1 + cos(x1 + sin(_a5_ - _a7_*x1*x1**(-x1)))/x1
<lambdifygenerated-12224>:2: RuntimeWarning: invalid value encountered in power
  return x1 + cos(x1 + sin(_a5_ - _a7_*x1*x1**(-x1)))/x1
<lambdifygenerated-12227>:2: RuntimeWarning: invalid value encountered in power
  return x1 + cos(x1 + sin(_a5_ - _a5_**(-tanh(x1))*_a7_*x1))/x1
<lambdifygenerated-12229>:2: RuntimeWarning: invalid value encountered in scalar power
  return x1 + cos(x1 + sin(_a5_ - _a5_**(-tanh(1))*_a7_*x1))/x1
<lambdifygenerated-12231>:2: RuntimeWarning: invalid value encountered in scalar power
  return x1 + cos(x1 + sin(_a5_ - _a5_**(-tanh(2))*_a7_*x1))/x1
<lambdifygenerated-12233>:2: RuntimeWarning: invalid value encountered in power
  return x1 + cos(x1 + sin(_a5_ - _a5_**(-tanh((x1 + sin(x1))/x1))*_a7_*x1))/x1
<lambdifygenerated-12235>:2: RuntimeWarning: invalid value encountered in power
  return x1 + cos(x1 + sin(_a5_ - _a5_**(-tanh((x1 + sin(x1**2))/x1))*_a7_*x1))/x1
<lambdifygenerated-12239>:2: RuntimeWarning: invalid value encountered in power
  return x1 + cos(x1 + sin(_a5_ - _a5_**(-tanh((x1 + sin(2*x1**2))/x1))*_a7_*x1))/x1
<lambdifygenerated-12241>:2: RuntimeWarning: invalid value encountered in power
  return x1 + cos(x1 + sin(_a5_ - _a5_**(-tanh((x1 + sin(x1*(_a1_ + x1)))/x1))*_a7_*x1))/x1
<lambdifygenerated-12245>:2: RuntimeWarning: invalid value encountered in power
  return x1 + cos(x1 + sin(_a5_ - _a5_**(-tanh((x1**x1 + sin(x1*(_a1_ + x1)))/x1))*_a7_*x1))/x1
<lambdifygenerated-12246>:2: RuntimeWarning: invalid value encountered in power
  return x1 + cos(x1 + sin(_a5_ - _a5_**(-tanh((x1**x1 + sin(x1*(_a1_ + x1)))/x1))*_a7_*x1))/x1
<lambdifygenerated-12247>:2: RuntimeWarning: invalid value encountered in power
  return x1 + cos(x1 + sin(_a5_ - _a5_**(-tanh(((x1**2)**x1 + sin(x1*(_a1_ + x1)))/x1))*_a7_*x1))/x1
<lambdifygenerated-12249>:2: RuntimeWarning: invalid value encountered in power
  return x1 + cos(x1 + sin(_a5_ - _a5_**(-tanh((sin(x1*(_a1_ + x1)) + 1)/x1))*_a7_*x1))/x1
<lambdifygenerated-12251>:2: RuntimeWarning: invalid value encountered in power
  return x1 + cos(x1 + sin(_a5_ - _a5_**(-tanh(((_a3_**2/x1**2)**x1 + sin(x1*(_a1_ + x1)))/x1))*_a7_*x1))/x1
<lambdifygenerated-12253>:2: RuntimeWarning: invalid value encountered in power
  return x1 + cos(x1 + sin(_a5_ - _a5_**(-tanh((((1/4)*_a3_**2/x1**2)**x1 + sin(x1*(_a1_ + x1)))/x1))*_a7_*x1))/x1
<lambdifygenerated-12257>:2: RuntimeWarning: invalid value encountered in power
  return x1 + cos(x1 + sin(_a5_ - _a5_**(-tanh(((_a3_**2/(_a0_ + x1)**2)**x1 + sin(x1*(_a1_ + x1)))/x1))*_a7_*x1))/x1
<lambdifygenerated-12259>:2: RuntimeWarning: invalid value encountered in power
  return x1 + cos(x1 + sin(_a5_ - _a5_**(-tanh((sin(x1*(_a1_ + x1)) + (_a3_**2/(_a0_ + x1)**2)**(-x1))/x1))*_a7_*x1))/x1
<lambdifygenerated-12261>:2: RuntimeWarning: overflow encountered in power
  return x1 + cos(x1 + sin(_a5_ - _a5_**(-tanh((sin(x1*(_a1_ + x1)) + (_a3_**2/(_a0_ + x1)**2)**(-_a7_))/x1))*_a7_*x1))/x1
<lambdifygenerated-12261>:2: RuntimeWarning: invalid value encountered in power
  return x1 + cos(x1 + sin(_a5_ - _a5_**(-tanh((sin(x1*(_a1_ + x1)) + (_a3_**2/(_a0_ + x1)**2)**(-_a7_))/x1))*_a7_*x1))/x1
<lambdifygenerated-12261>:2: RuntimeWarning: overflow encountered in divide
  return x1 + cos(x1 + sin(_a5_ - _a5_**(-tanh((sin(x1*(_a1_ + x1)) + (_a3_**2/(_a0_ + x1)**2)**(-_a7_))/x1))*_a7_*x1))/x1
<lambdifygenerated-12263>:2: RuntimeWarning: overflow encountered in power
  return x1 + cos(x1 + sin(_a5_ - _a5_**(-tanh((sin(x1*(_a1_ + x1)) + (_a3_**2/(_a0_ + x1)**2)**(-_a7_))/x1**2))*_a7_*x1))/x1
<lambdifygenerated-12263>:2: RuntimeWarning: overflow encountered in divide
  return x1 + cos(x1 + sin(_a5_ - _a5_**(-tanh((sin(x1*(_a1_ + x1)) + (_a3_**2/(_a0_ + x1)**2)**(-_a7_))/x1**2))*_a7_*x1))/x1
<lambdifygenerated-12263>:2: RuntimeWarning: invalid value encountered in power
  return x1 + cos(x1 + sin(_a5_ - _a5_**(-tanh((sin(x1*(_a1_ + x1)) + (_a3_**2/(_a0_ + x1)**2)**(-_a7_))/x1**2))*_a7_*x1))/x1
<lambdifygenerated-12267>:2: RuntimeWarning: overflow encountered in power
  return x1 + cos(x1 + sin(_a5_ - _a5_**(-tanh((sin(x1*(_a1_ + x1)) + (_a3_**2/(_a0_ + x1)**2)**(-_a7_))/(_a3_*x1)))*_a7_*x1))/x1
<lambdifygenerated-12267>:2: RuntimeWarning: invalid value encountered in power
  return x1 + cos(x1 + sin(_a5_ - _a5_**(-tanh((sin(x1*(_a1_ + x1)) + (_a3_**2/(_a0_ + x1)**2)**(-_a7_))/(_a3_*x1)))*_a7_*x1))/x1
<lambdifygenerated-12267>:2: RuntimeWarning: overflow encountered in divide
  return x1 + cos(x1 + sin(_a5_ - _a5_**(-tanh((sin(x1*(_a1_ + x1)) + (_a3_**2/(_a0_ + x1)**2)**(-_a7_))/(_a3_*x1)))*_a7_*x1))/x1
<lambdifygenerated-12269>:2: RuntimeWarning: overflow encountered in power
  return x1 + cos(2*x1 + sin(_a5_ - _a5_**(-tanh((sin(x1*(_a1_ + x1)) + (_a3_**2/(_a0_ + x1)**2)**(-_a7_))/(_a3_*x1)))*_a7_*x1))/x1
<lambdifygenerated-12269>:2: RuntimeWarning: invalid value encountered in power
  return x1 + cos(2*x1 + sin(_a5_ - _a5_**(-tanh((sin(x1*(_a1_ + x1)) + (_a3_**2/(_a0_ + x1)**2)**(-_a7_))/(_a3_*x1)))*_a7_*x1))/x1
<lambdifygenerated-12269>:2: RuntimeWarning: overflow encountered in divide
  return x1 + cos(2*x1 + sin(_a5_ - _a5_**(-tanh((sin(x1*(_a1_ + x1)) + (_a3_**2/(_a0_ + x1)**2)**(-_a7_))/(_a3_*x1)))*_a7_*x1))/x1

interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.997734  2.0  0.988172  0.991235
3746  0.998  0.997761  2.0  0.988108  0.991200
3747  0.998  0.997787  2.0  0.988044  0.991164
3748  0.999  0.997814  2.0  0.987980  0.991129

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.997867  2.0  0.987850  0.991058
3751  1.002  0.997894  2.0  0.987785  0.991022
3752  1.002  0.997921  2.0  0.987719  0.990986
3753  1.003  0.997948  2.0  0.987654  0.990950

3750
interpolation

<lambdifygenerated-12379>:2: RuntimeWarning: overflow encountered in cosh
  return cos(_a2_*exp(tanh(_a4_ + _a7_*x1 + sin(_a0_)*cos((_a1_ + _a3_*cosh(_a1_*x1**2) + _a6_)*tanh(_a3_*x1/(_a4_*_a5_)))*tan(_a6_*x1/_a0_)**2)) + x1)**2/x1
<lambdifygenerated-12379>:2: RuntimeWarning: overflow encountered in multiply
  return cos(_a2_*exp(tanh(_a4_ + _a7_*x1 + sin(_a0_)*cos((_a1_ + _a3_*cosh(_a1_*x1**2) + _a6_)*tanh(_a3_*x1/(_a4_*_a5_)))*tan(_a6_*x1/_a0_)**2)) + x1)**2/x1
<lambdifygenerated-12379>:2: RuntimeWarning: invalid value encountered in cos
  return cos(_a2_*exp(tanh(_a4_ + _a7_*x1 + sin(_a0_)*cos((_a1_ + _a3_*cosh(_a1_*x1**2) + _a6_)*tanh(_a3_*x1/(_a4_*_a5_)))*tan(_a6_*x1/_a0_)**2)) + x1)**2/x1
<lambdifygenerated-12383>:2: RuntimeWarning: invalid value encountered in sqrt
  return cos(_a2_*exp(tanh(_a4_ + _a7_*x1 + sin(_a0_)*cos((_a1_ + _a3_*cosh(_a1_*x1**2) + _a6_)*tanh(_a3_*x1/(_a4_*_a5_)))*tan(_a6_*x1/_a0_)**2)) + _a5_)**2/sqrt(x1)
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-12384>:2: RuntimeWarning: invalid value encountered in sqrt
  return cos(_a2_*exp(tanh(_a4_ + _a7_*x1 + sin(_a0_)*cos((_a1_ + _a3_*cosh(_a1_*x1**2) + _a6_)*tanh(_a3_*x1/(_a4_*_a5_)))*tan(_a6_*x1/_a0_)**2)) + _a5_)**2/sqrt(x1)
<lambdifygenerated-12385>:2: RuntimeWarning: invalid value encountered in sqrt
  return cos(_a2_*exp(tanh(_a4_ + _a7_*x1 + sin(_a0_)*cos((_a1_ + _a3_*cosh(_a1_*x1**2) + _a6_)*tanh(_a3_*x1/(_a4_*_a5_)))*tan(_a6_*x1/_a0_)**2)) + _a5_)**2/sqrt(_a7_)
<lambdifygenerated-12386>:2: RuntimeWarning: invalid value encountered in sqrt
  return cos(_a2_*exp(tanh(_a4_ + _a7_*x1 + sin(_a0_)*cos((_a1_ + _a3_*cosh(_a1_*x1**2) + _a6_)*tanh(_a3_*x1/(_a4_*_a5_)))*tan(_a6_*x1/_a0_)**2)) + _a5_)**2/sqrt(_a7_)
<lambdifygenerated-12387>:2: RuntimeWarning: invalid value encountered in sqrt
  return cos(_a2_*exp(tanh(_a4_ + _a7_*x1 + sin(_a0_)*cos((_a1_ + _a3_*cosh(_a1_*x1**2) + _a6_)*tanh(_a3_*x1/(_a4_*_a5_)))*tan(_a6_*x1/_a0_)**2)) + _a5_)**2/sqrt(_a7_)
<lambdifygenerated-12388>:2: RuntimeWarning: invalid value encountered in sqrt
  return cos(_a2_*exp(tanh(_a4_ + _a7_*x1 + sin(_a0_)*cos((_a1_ + _a3_*cosh(_a1_*x1**2) + _a6_)*tanh(_a3_*x1/(_a4_*_a5_)))*tan(_a6_*x1/_a0_)**2)) + _a5_)**2/sqrt(_a7_)
<lambdifygenerated-12389>:2: RuntimeWarning: invalid value encountered in sqrt
  return cos(_a2_*exp(tanh(_a4_ + _a7_*x1 + sin(_a0_)*cos((_a1_ + _a3_*cosh(_a1_*x1**2) + _a6_)*tanh(_a3_*x1/(_a4_*_a5_)))*tan(_a6_*x1/_a0_)**2)) + _a5_)**2/sqrt(_a7_)
<lambdifygenerated-12390>:2: RuntimeWarning: invalid value encountered in sqrt
  return cos(_a2_*exp(tanh(_a4_ + _a7_*x1 + sin(_a0_)*cos((_a1_ + _a3_*cosh(_a1_*x1**2) + _a6_)*tanh(_a3_*x1/(_a4_*_a5_)))*tan(_a6_*x1/_a0_)**2)) + _a5_)**2/sqrt(_a7_)

         x1         y  rep    ymodel      ybms
3745  0.997  0.689029  3.0  0.682103  0.687794
3746  0.998  0.688777  3.0  0.681721  0.687475
3747  0.998  0.688525  3.0  0.681338  0.687156
3748  0.999  0.688273  3.0  0.680956  0.686838

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.687768  3.0  0.680191  0.686203
3751  1.002  0.687516  3.0  0.679809  0.685887
3752  1.002  0.687264  3.0  0.679427  0.685572
3753  1.003  0.687012  3.0  0.679045  0.685257

3750

<lambdifygenerated-12397>:2: RuntimeWarning: invalid value encountered in power
  return x1 + x1**x1
<lambdifygenerated-12398>:2: RuntimeWarning: invalid value encountered in power
  return x1 + x1**x1
<lambdifygenerated-12399>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (2*x1)**x1
<lambdifygenerated-12400>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (2*x1)**x1
<lambdifygenerated-12401>:2: RuntimeWarning: divide by zero encountered in power
  return 0**x1 + x1
<lambdifygenerated-12402>:2: RuntimeWarning: divide by zero encountered in power
  return 0**x1 + x1
<lambdifygenerated-12403>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (-x1**2 + x1)**x1
<lambdifygenerated-12404>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (-x1**2 + x1)**x1
<lambdifygenerated-12405>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (-x1**3 + x1)**x1
<lambdifygenerated-12406>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (-x1**3 + x1)**x1
<lambdifygenerated-12407>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (-2*x1**3 + x1)**x1
<lambdifygenerated-12408>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (-2*x1**3 + x1)**x1
<lambdifygenerated-12409>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (-x1**2*(x1 + 1) + x1)**x1
<lambdifygenerated-12410>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (-x1**2*(x1 + 1) + x1)**x1
<lambdifygenerated-12411>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (-2*x1**3 + x1)**x1
<lambdifygenerated-12412>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (-2*x1**3 + x1)**x1
<lambdifygenerated-12413>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (-3*x1**3 + x1)**x1
<lambdifygenerated-12414>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (-3*x1**3 + x1)**x1
<lambdifygenerated-12415>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (-x1**2*(2*x1 + exp(x1)) + x1)**x1
<lambdifygenerated-12416>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (-x1**2*(2*x1 + exp(x1)) + x1)**x1
<lambdifygenerated-12417>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (-x1**2*(2*x1 + exp(x1)) + x1)**x1
<lambdifygenerated-12418>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (-x1**2*(2*x1 + exp(x1)) + x1)**x1
<lambdifygenerated-12419>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (-x1**2*(_a0_ + x1 + exp(x1)) + x1)**x1
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-12420>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (-x1**2*(_a0_ + x1 + exp(x1)) + x1)**x1
<lambdifygenerated-12421>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (-x1**2*(2*_a0_ + x1 + 2*exp(x1)) + x1)**x1
<lambdifygenerated-12422>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (-x1**2*(2*_a0_ + x1 + 2*exp(x1)) + x1)**x1
<lambdifygenerated-12423>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (-x1**2*(x1 + (_a0_ + exp(x1))*(x1 + exp(x1))/x1) + x1)**x1
<lambdifygenerated-12424>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (-x1**2*(x1 + (_a0_ + exp(x1))*(x1 + exp(x1))/x1) + x1)**x1
<lambdifygenerated-12425>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (-x1**2*(x1 + (_a0_ + exp(x1))*(x1 + exp(x1))/x1) + x1)**x1
<lambdifygenerated-12426>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (-x1**2*(x1 + (_a0_ + exp(x1))*(x1 + exp(x1))/x1) + x1)**x1
<lambdifygenerated-12427>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (-x1**2*(x1 + (_a0_ + exp(x1))*(x1**2 + exp(x1))/x1) + x1)**x1
<lambdifygenerated-12428>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (-x1**2*(x1 + (_a0_ + exp(x1))*(x1**2 + exp(x1))/x1) + x1)**x1
<lambdifygenerated-12429>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (-x1**2*(x1 + (_a0_ + exp(x1))*(_a7_*x1 + exp(x1))/x1) + x1)**x1
<lambdifygenerated-12430>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (-x1**2*(x1 + (_a0_ + exp(x1))*(_a7_*x1 + exp(x1))/x1) + x1)**x1
<lambdifygenerated-12431>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (-x1**2*(x1 + (_a0_ + exp(x1))*(_a7_*abs(x1) + exp(x1))/x1) + x1)**x1
<lambdifygenerated-12432>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (-x1**2*(x1 + (_a0_ + exp(x1))*(_a7_*abs(x1) + exp(x1))/x1) + x1)**x1
<lambdifygenerated-12433>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (-x1**2*(x1 + (_a0_ + exp(x1))*(_a7_*abs(x1) + exp(x1))/x1) + x1)**x1
<lambdifygenerated-12434>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (-x1**2*(x1 + (_a0_ + exp(x1))*(_a7_*abs(x1) + exp(x1))/x1) + x1)**x1
<lambdifygenerated-12435>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (-x1**2*(x1 + (_a0_ + exp(x1))*(_a7_*abs(x1) + exp(x1))/_a4_) + x1)**x1
<lambdifygenerated-12436>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (-x1**2*(x1 + (_a0_ + exp(x1))*(_a7_*abs(x1) + exp(x1))/_a4_) + x1)**x1
<lambdifygenerated-12437>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (-x1**2*(_a1_ + (_a0_ + exp(x1))*(_a7_*abs(x1) + exp(x1))/_a4_) + x1)**x1
<lambdifygenerated-12438>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (-x1**2*(_a1_ + (_a0_ + exp(x1))*(_a7_*abs(x1) + exp(x1))/_a4_) + x1)**x1
<lambdifygenerated-12439>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (-2*x1**2*(_a1_ + (_a0_ + exp(x1))*(_a7_*abs(x1) + exp(x1))/_a4_) + x1)**x1
<lambdifygenerated-12440>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (-2*x1**2*(_a1_ + (_a0_ + exp(x1))*(_a7_*abs(x1) + exp(x1))/_a4_) + x1)**x1
<lambdifygenerated-12441>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (-x1*(_a1_ + (_a0_ + exp(x1))*(_a7_*abs(x1) + exp(x1))/_a4_)*(_a4_ + x1) + x1)**x1
<lambdifygenerated-12442>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (-x1*(_a1_ + (_a0_ + exp(x1))*(_a7_*abs(x1) + exp(x1))/_a4_)*(_a4_ + x1) + x1)**x1
<lambdifygenerated-12443>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (-x1*(_a1_ + (_a0_ + exp(x1))*(_a7_*abs(x1) + exp(x1))/_a4_)*(_a4_ + x1**3) + x1)**x1
<lambdifygenerated-12444>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (-x1*(_a1_ + (_a0_ + exp(x1))*(_a7_*abs(x1) + exp(x1))/_a4_)*(_a4_ + x1**3) + x1)**x1
<lambdifygenerated-12445>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (-x1*(_a1_ + (_a0_ + exp(x1))*(_a7_*abs(x1) + exp(x1))/_a4_)*(_a4_ + x1**3) + x1)**x1
<lambdifygenerated-12446>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (-x1*(_a1_ + (_a0_ + exp(x1))*(_a7_*abs(x1) + exp(x1))/_a4_)*(_a4_ + x1**3) + x1)**x1
<lambdifygenerated-12447>:2: RuntimeWarning: invalid value encountered in log
  return x1 + (x1 - (_a1_ + (_a0_ + exp(x1))*(_a7_*abs(x1) + exp(x1))/_a4_)*(_a4_ + x1**3)*log(x1))**x1
<lambdifygenerated-12447>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (x1 - (_a1_ + (_a0_ + exp(x1))*(_a7_*abs(x1) + exp(x1))/_a4_)*(_a4_ + x1**3)*log(x1))**x1
<lambdifygenerated-12448>:2: RuntimeWarning: invalid value encountered in log
  return x1 + (x1 - (_a1_ + (_a0_ + exp(x1))*(_a7_*abs(x1) + exp(x1))/_a4_)*(_a4_ + x1**3)*log(x1))**x1
<lambdifygenerated-12448>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (x1 - (_a1_ + (_a0_ + exp(x1))*(_a7_*abs(x1) + exp(x1))/_a4_)*(_a4_ + x1**3)*log(x1))**x1
<lambdifygenerated-12449>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (x1 - (_a1_ + (_a0_ + exp(x1))*(_a7_*abs(x1) + exp(x1))/_a4_)*(_a4_ + x1**3)*log(_a3_))**x1
<lambdifygenerated-12450>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (x1 - (_a1_ + (_a0_ + exp(x1))*(_a7_*abs(x1) + exp(x1))/_a4_)*(_a4_ + x1**3)*log(_a3_))**x1
<lambdifygenerated-12451>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (_a3_ - (_a1_ + (_a0_ + exp(x1))*(_a7_*abs(x1) + exp(x1))/_a4_)*(_a4_ + x1**3)*log(_a3_))**x1
<lambdifygenerated-12453>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (_a3_ - (_a1_ + (_a0_ + exp(x1))*(_a7_*abs(x1) + exp(x1))/_a4_)*(_a4_ + x1**3)*log(_a3_))**(2*x1)
<lambdifygenerated-12455>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (_a3_ - (_a1_ + (_a0_ + exp(x1))*(_a7_*abs(x1) + exp(x1))/_a4_)*(_a4_ + x1**3)*log(_a3_))**(_a7_ + x1)
<lambdifygenerated-12457>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (_a3_ - (_a1_ + (_a0_ + exp(x1))*(_a7_*abs(x1) + exp(x1))/_a4_)*(_a4_ + x1**3)*log(_a3_))**(_a7_ + x1**2)
<lambdifygenerated-12459>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (_a3_ - (_a1_ + (_a0_ + exp(x1))*(_a7_*abs(x1) + exp(x1))/_a4_)*(_a4_ + x1**3)*log(_a3_))**(_a5_*x1 + _a7_)

interpolation

<lambdifygenerated-12461>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (_a3_ - (_a1_ + (_a0_ + exp(x1))*(_a7_*abs(x1) + exp(x1))/_a4_)*(_a4_ + x1**3)*log(_a3_))**(_a5_*cos(x1) + _a7_)
<lambdifygenerated-12463>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (_a3_ - (_a1_ + (_a0_ + exp(x1))*(_a7_*abs(x1) + exp(x1))/_a4_)*(_a4_ + x1**3)*log(_a3_))**(_a5_*cos(x1**2) + _a7_)
<lambdifygenerated-12467>:2: RuntimeWarning: invalid value encountered in power
  return _a6_ + (_a3_ - (_a1_ + (_a0_ + exp(x1))*(_a7_*abs(x1) + exp(x1))/_a4_)*(_a4_ + x1**3)*log(_a3_))**(_a5_*cos(x1**2) + _a7_)
<lambdifygenerated-12471>:2: RuntimeWarning: invalid value encountered in power
  return _a6_ + (_a3_ - (_a1_ + (_a0_ + exp(x1))*(_a7_*abs(x1) + exp(x1))/_a4_)*(_a4_ + x1**3)*log(_a3_))**(_a5_*cos(x1**2) + _a7_)
<lambdifygenerated-12473>:2: RuntimeWarning: invalid value encountered in power
  return _a6_ + (_a3_ - (_a1_ + (_a0_ + exp(x1))*(_a7_*abs(x1) + exp(x1))/_a4_)*(_a4_ + x1**3)*log(_a3_))**(_a5_*cos(x1**2) + _a7_)

         x1         y  rep    ymodel      ybms
3745  0.997  0.661298  4.0  0.663945  0.667482
3746  0.998  0.661485  4.0  0.664194  0.667830
3747  0.998  0.661672  4.0  0.664445  0.668179
3748  0.999  0.661858  4.0  0.664695  0.668529

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.662232  4.0  0.665197  0.669234
3751  1.002  0.662419  4.0  0.665449  0.669589
3752  1.002  0.662605  4.0  0.665701  0.669945
3753  1.003  0.662792  4.0  0.665953  0.670303

3750

<lambdifygenerated-12515>:2: RuntimeWarning: invalid value encountered in power
  return x1**2*cos(x1 + sin(_a4_*(_a6_ + x1))*cos(x1*(2*x1 + x1**x1))/_a0_) + x1
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-12516>:2: RuntimeWarning: invalid value encountered in power
  return x1**2*cos(x1 + sin(_a4_*(_a6_ + x1))*cos(x1*(2*x1 + x1**x1))/_a0_) + x1
<lambdifygenerated-12517>:2: RuntimeWarning: invalid value encountered in power
  return x1**2*cos(x1 + sin(_a4_*(_a6_ + x1))*cos(x1*(_a1_**x1 + 2*x1))/_a0_) + x1
<lambdifygenerated-12519>:2: RuntimeWarning: invalid value encountered in power
  return x1**2*cos(x1 + sin(_a4_*(_a6_ + x1))*cos(x1*(_a1_**cos(x1) + 2*x1))/_a0_) + x1
<lambdifygenerated-12523>:2: RuntimeWarning: invalid value encountered in power
  return x1**2*cos(x1 + sin(_a4_*(_a6_ + x1))*cos(x1*(_a1_**cos(x1) + _a5_ + x1))/_a0_) + x1
<lambdifygenerated-12529>:2: RuntimeWarning: invalid value encountered in power
  return x1**2*cos(x1**(3/2) + sin(_a4_*(_a6_ + x1))*cos(_a6_*(_a1_**cos(x1) + _a5_ + x1))/_a0_) + x1
<lambdifygenerated-12530>:2: RuntimeWarning: invalid value encountered in power
  return x1**2*cos(x1**(3/2) + sin(_a4_*(_a6_ + x1))*cos(_a6_*(_a1_**cos(x1) + _a5_ + x1))/_a0_) + x1
<lambdifygenerated-12531>:2: RuntimeWarning: invalid value encountered in sqrt
  return x1**2*cos(sqrt(_a3_)*x1 + sin(_a4_*(_a6_ + x1))*cos(_a6_*(_a1_**cos(x1) + _a5_ + x1))/_a0_) + x1
<lambdifygenerated-12535>:2: RuntimeWarning: invalid value encountered in power
  return x1**2*cos(sqrt(_a3_)*(x1 + x1**x1) + sin(_a4_*(_a6_ + x1))*cos(_a6_*(_a1_**cos(x1) + _a5_ + x1))/_a0_) + x1
<lambdifygenerated-12536>:2: RuntimeWarning: invalid value encountered in power
  return x1**2*cos(sqrt(_a3_)*(x1 + x1**x1) + sin(_a4_*(_a6_ + x1))*cos(_a6_*(_a1_**cos(x1) + _a5_ + x1))/_a0_) + x1
<lambdifygenerated-12545>:2: RuntimeWarning: invalid value encountered in sqrt
  return x1**2*cos(sqrt(_a3_)*(_a0_*x1 + _a5_**tanh(x1)) + sin(_a4_*(_a6_ + x1))*cos(_a6_*(_a1_**cos(x1) + _a5_ + x1))/_a0_) + x1
<lambdifygenerated-12551>:2: RuntimeWarning: invalid value encountered in power
  return x1**2*x1**x1*cos(sqrt(_a3_)*(_a0_**2 + _a5_**tanh(x1)) + sin(_a4_*(_a6_ + x1))*cos(_a6_*(_a1_**cos(x1) + _a5_ + x1))/_a0_) + x1
<lambdifygenerated-12552>:2: RuntimeWarning: invalid value encountered in power
  return x1**2*x1**x1*cos(sqrt(_a3_)*(_a0_**2 + _a5_**tanh(x1)) + sin(_a4_*(_a6_ + x1))*cos(_a6_*(_a1_**cos(x1) + _a5_ + x1))/_a0_) + x1
<lambdifygenerated-12553>:2: RuntimeWarning: invalid value encountered in sqrt
  return _a1_**x1*x1**2*cos(sqrt(_a3_)*(_a0_**2 + _a5_**tanh(x1)) + sin(_a4_*(_a6_ + x1))*cos(_a6_*(_a1_**cos(x1) + _a5_ + x1))/_a0_) + x1
<lambdifygenerated-12557>:2: RuntimeWarning: invalid value encountered in sqrt
  return _a1_**x1*_a3_*x1*cos(sqrt(_a3_)*(_a0_**2 + _a5_**tanh(x1)) + sin(_a4_*(_a6_ + x1))*cos(_a6_*(_a1_**cos(x1) + _a5_ + x1))/_a0_) + x1
<lambdifygenerated-12559>:2: RuntimeWarning: invalid value encountered in power
  return _a1_**x1*_a2_*_a3_*cos(sqrt(_a3_)*(_a0_**2 + _a5_**tanh(x1)) + sin(_a4_*(_a6_ + x1))*cos(_a6_*(_a1_**cos(x1) + _a5_ + x1))/_a0_) + x1
<lambdifygenerated-12559>:2: RuntimeWarning: invalid value encountered in sqrt
  return _a1_**x1*_a2_*_a3_*cos(sqrt(_a3_)*(_a0_**2 + _a5_**tanh(x1)) + sin(_a4_*(_a6_ + x1))*cos(_a6_*(_a1_**cos(x1) + _a5_ + x1))/_a0_) + x1
<lambdifygenerated-12561>:2: RuntimeWarning: invalid value encountered in sqrt
  return _a1_**x1*_a2_*_a3_*cos(sqrt(_a3_)*(_a0_**2 + _a5_**tanh(x1)) + sin(_a4_*(_a6_ + x1))*cos(_a6_*(_a1_**cos(x1) + _a5_ + x1))/_a0_) + _a7_

interpolation

<lambdifygenerated-12565>:2: RuntimeWarning: invalid value encountered in sqrt
  return _a1_**x1*_a2_*_a3_*cos(sqrt(_a3_)*(_a0_**2 + _a5_**tanh(x1)) + sin(_a4_*(_a6_ + x1))*cos(_a6_*(_a1_**cos(x1) + _a5_ + x1))/_a0_) + _a7_

         x1         y  rep    ymodel      ybms
3745  0.997  0.956369  5.0  0.957027  0.956306
3746  0.998  0.956259  5.0  0.956942  0.956207
3747  0.998  0.956150  5.0  0.956857  0.956108
3748  0.999  0.956040  5.0  0.956772  0.956009

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.955822  5.0  0.956604  0.955814
3751  1.002  0.955712  5.0  0.956521  0.955716
3752  1.002  0.955603  5.0  0.956438  0.955619
3753  1.003  0.955493  5.0  0.956356  0.955522

3750

<lambdifygenerated-12573>:2: RuntimeWarning: invalid value encountered in power
  return x1 + x1**x1
<lambdifygenerated-12574>:2: RuntimeWarning: invalid value encountered in power
  return x1 + x1**x1
<lambdifygenerated-12583>:2: RuntimeWarning: invalid value encountered in power
  return x1 + ((4*x1**2 + 2*x1)/x1)**x1
<lambdifygenerated-12584>:2: RuntimeWarning: invalid value encountered in power
  return x1 + ((4*x1**2 + 2*x1)/x1)**x1
<lambdifygenerated-12587>:2: RuntimeWarning: invalid value encountered in power
  return x1 + ((2*x1 + (x1**3 + x1)**2)/x1)**x1
<lambdifygenerated-12588>:2: RuntimeWarning: invalid value encountered in power
  return x1 + ((2*x1 + (x1**3 + x1)**2)/x1)**x1
<lambdifygenerated-12589>:2: RuntimeWarning: invalid value encountered in power
  return x1 + ((2*x1 + (x1**2*x1**x1 + x1)**2)/x1)**x1
<lambdifygenerated-12590>:2: RuntimeWarning: invalid value encountered in power
  return x1 + ((2*x1 + (x1**2*x1**x1 + x1)**2)/x1)**x1
<lambdifygenerated-12599>:2: RuntimeWarning: invalid value encountered in power
  return x1 + ((2*x1 + (x1**2*cosh(x1**2*exp(x1**x1))**x1 + x1)**2)/x1)**x1
<lambdifygenerated-12599>:2: RuntimeWarning: overflow encountered in square
  return x1 + ((2*x1 + (x1**2*cosh(x1**2*exp(x1**x1))**x1 + x1)**2)/x1)**x1
<lambdifygenerated-12599>:2: RuntimeWarning: overflow encountered in power
  return x1 + ((2*x1 + (x1**2*cosh(x1**2*exp(x1**x1))**x1 + x1)**2)/x1)**x1
/usr/local/lib/python3.10/dist-packages/pandas/core/arraylike.py:399: RuntimeWarning: overflow encountered in square
  result = getattr(ufunc, method)(*inputs, **kwargs)
<lambdifygenerated-12600>:2: RuntimeWarning: invalid value encountered in power
  return x1 + ((2*x1 + (x1**2*cosh(x1**2*exp(x1**x1))**x1 + x1)**2)/x1)**x1
<lambdifygenerated-12600>:2: RuntimeWarning: overflow encountered in square
  return x1 + ((2*x1 + (x1**2*cosh(x1**2*exp(x1**x1))**x1 + x1)**2)/x1)**x1
<lambdifygenerated-12600>:2: RuntimeWarning: overflow encountered in power
  return x1 + ((2*x1 + (x1**2*cosh(x1**2*exp(x1**x1))**x1 + x1)**2)/x1)**x1
<lambdifygenerated-12601>:2: RuntimeWarning: invalid value encountered in log
  return x1 + ((2*x1 + (x1**2*cosh(x1**2*exp(log(x1)**x1))**x1 + x1)**2)/x1)**x1
<lambdifygenerated-12601>:2: RuntimeWarning: invalid value encountered in power
  return x1 + ((2*x1 + (x1**2*cosh(x1**2*exp(log(x1)**x1))**x1 + x1)**2)/x1)**x1
<lambdifygenerated-12602>:2: RuntimeWarning: invalid value encountered in log
  return x1 + ((2*x1 + (x1**2*cosh(x1**2*exp(log(x1)**x1))**x1 + x1)**2)/x1)**x1
<lambdifygenerated-12602>:2: RuntimeWarning: invalid value encountered in power
  return x1 + ((2*x1 + (x1**2*cosh(x1**2*exp(log(x1)**x1))**x1 + x1)**2)/x1)**x1
<lambdifygenerated-12603>:2: RuntimeWarning: divide by zero encountered in power
  return x1 + ((2*x1 + (x1**2*cosh(x1**2*exp(log(_a0_)**x1))**x1 + x1)**2)/x1)**x1
<lambdifygenerated-12603>:2: RuntimeWarning: overflow encountered in exp
  return x1 + ((2*x1 + (x1**2*cosh(x1**2*exp(log(_a0_)**x1))**x1 + x1)**2)/x1)**x1
<lambdifygenerated-12603>:2: RuntimeWarning: overflow encountered in cosh
  return x1 + ((2*x1 + (x1**2*cosh(x1**2*exp(log(_a0_)**x1))**x1 + x1)**2)/x1)**x1
<lambdifygenerated-12603>:2: RuntimeWarning: invalid value encountered in log
  return x1 + ((2*x1 + (x1**2*cosh(x1**2*exp(log(_a0_)**x1))**x1 + x1)**2)/x1)**x1
<lambdifygenerated-12603>:2: RuntimeWarning: divide by zero encountered in log
  return x1 + ((2*x1 + (x1**2*cosh(x1**2*exp(log(_a0_)**x1))**x1 + x1)**2)/x1)**x1
<lambdifygenerated-12603>:2: RuntimeWarning: invalid value encountered in power
  return x1 + ((2*x1 + (x1**2*cosh(x1**2*exp(log(_a0_)**x1))**x1 + x1)**2)/x1)**x1
<lambdifygenerated-12604>:2: RuntimeWarning: divide by zero encountered in power
  return x1 + ((2*x1 + (x1**2*cosh(x1**2*exp(log(_a0_)**x1))**x1 + x1)**2)/x1)**x1
<lambdifygenerated-12605>:2: RuntimeWarning: divide by zero encountered in power
  return x1 + ((2*x1 + (x1**2*cosh(x1**2*exp(log(_a0_)**x1))**x1 + x1)**2)/x1)**x1
<lambdifygenerated-12606>:2: RuntimeWarning: divide by zero encountered in power
  return x1 + ((2*x1 + (x1**2*cosh(x1**2*exp(log(_a0_)**x1))**x1 + x1)**2)/x1)**x1
<lambdifygenerated-12607>:2: RuntimeWarning: divide by zero encountered in power
  return x1 + ((2*x1 + (x1**2*cosh(2*x1**2*exp(log(_a0_)**x1))**x1 + x1)**2)/x1)**x1
<lambdifygenerated-12607>:2: RuntimeWarning: overflow encountered in exp
  return x1 + ((2*x1 + (x1**2*cosh(2*x1**2*exp(log(_a0_)**x1))**x1 + x1)**2)/x1)**x1
<lambdifygenerated-12607>:2: RuntimeWarning: overflow encountered in cosh
  return x1 + ((2*x1 + (x1**2*cosh(2*x1**2*exp(log(_a0_)**x1))**x1 + x1)**2)/x1)**x1
<lambdifygenerated-12607>:2: RuntimeWarning: invalid value encountered in log
  return x1 + ((2*x1 + (x1**2*cosh(2*x1**2*exp(log(_a0_)**x1))**x1 + x1)**2)/x1)**x1
<lambdifygenerated-12607>:2: RuntimeWarning: invalid value encountered in power
  return x1 + ((2*x1 + (x1**2*cosh(2*x1**2*exp(log(_a0_)**x1))**x1 + x1)**2)/x1)**x1
<lambdifygenerated-12608>:2: RuntimeWarning: divide by zero encountered in power
  return x1 + ((2*x1 + (x1**2*cosh(2*x1**2*exp(log(_a0_)**x1))**x1 + x1)**2)/x1)**x1
<lambdifygenerated-12609>:2: RuntimeWarning: divide by zero encountered in power
  return x1 + ((2*x1 + (x1**2*cosh(x1*(_a1_ + x1)*exp(log(_a0_)**x1))**x1 + x1)**2)/x1)**x1
<lambdifygenerated-12609>:2: RuntimeWarning: overflow encountered in exp
  return x1 + ((2*x1 + (x1**2*cosh(x1*(_a1_ + x1)*exp(log(_a0_)**x1))**x1 + x1)**2)/x1)**x1
<lambdifygenerated-12609>:2: RuntimeWarning: overflow encountered in cosh
  return x1 + ((2*x1 + (x1**2*cosh(x1*(_a1_ + x1)*exp(log(_a0_)**x1))**x1 + x1)**2)/x1)**x1
<lambdifygenerated-12609>:2: RuntimeWarning: invalid value encountered in log
  return x1 + ((2*x1 + (x1**2*cosh(x1*(_a1_ + x1)*exp(log(_a0_)**x1))**x1 + x1)**2)/x1)**x1
<lambdifygenerated-12610>:2: RuntimeWarning: divide by zero encountered in power
  return x1 + ((2*x1 + (x1**2*cosh(x1*(_a1_ + x1)*exp(log(_a0_)**x1))**x1 + x1)**2)/x1)**x1
<lambdifygenerated-12611>:2: RuntimeWarning: divide by zero encountered in power
  return x1 + ((2*x1 + (x1**2*cosh(x1*(_a1_ + x1)*exp(log(_a0_)**x1))**x1 + x1)**2)/x1)**x1
<lambdifygenerated-12612>:2: RuntimeWarning: divide by zero encountered in power
  return x1 + ((2*x1 + (x1**2*cosh(x1*(_a1_ + x1)*exp(log(_a0_)**x1))**x1 + x1)**2)/x1)**x1
<lambdifygenerated-12613>:2: RuntimeWarning: divide by zero encountered in power
  return x1 + ((2*x1 + (x1**2*cosh(2*x1*(_a1_ + x1)*exp(log(_a0_)**x1))**x1 + x1)**2)/x1)**x1
<lambdifygenerated-12613>:2: RuntimeWarning: overflow encountered in exp
  return x1 + ((2*x1 + (x1**2*cosh(2*x1*(_a1_ + x1)*exp(log(_a0_)**x1))**x1 + x1)**2)/x1)**x1
<lambdifygenerated-12613>:2: RuntimeWarning: overflow encountered in cosh
  return x1 + ((2*x1 + (x1**2*cosh(2*x1*(_a1_ + x1)*exp(log(_a0_)**x1))**x1 + x1)**2)/x1)**x1
<lambdifygenerated-12613>:2: RuntimeWarning: invalid value encountered in log
  return x1 + ((2*x1 + (x1**2*cosh(2*x1*(_a1_ + x1)*exp(log(_a0_)**x1))**x1 + x1)**2)/x1)**x1
<lambdifygenerated-12613>:2: RuntimeWarning: invalid value encountered in power
  return x1 + ((2*x1 + (x1**2*cosh(2*x1*(_a1_ + x1)*exp(log(_a0_)**x1))**x1 + x1)**2)/x1)**x1
<lambdifygenerated-12614>:2: RuntimeWarning: divide by zero encountered in power
  return x1 + ((2*x1 + (x1**2*cosh(2*x1*(_a1_ + x1)*exp(log(_a0_)**x1))**x1 + x1)**2)/x1)**x1
<lambdifygenerated-12615>:2: RuntimeWarning: divide by zero encountered in power
  return x1 + ((2*x1 + (x1**2*cosh((_a1_ + x1)*(x1**2 + x1)*exp(log(_a0_)**x1))**x1 + x1)**2)/x1)**x1
<lambdifygenerated-12615>:2: RuntimeWarning: overflow encountered in exp
  return x1 + ((2*x1 + (x1**2*cosh((_a1_ + x1)*(x1**2 + x1)*exp(log(_a0_)**x1))**x1 + x1)**2)/x1)**x1
<lambdifygenerated-12615>:2: RuntimeWarning: overflow encountered in cosh
  return x1 + ((2*x1 + (x1**2*cosh((_a1_ + x1)*(x1**2 + x1)*exp(log(_a0_)**x1))**x1 + x1)**2)/x1)**x1
<lambdifygenerated-12615>:2: RuntimeWarning: invalid value encountered in log
  return x1 + ((2*x1 + (x1**2*cosh((_a1_ + x1)*(x1**2 + x1)*exp(log(_a0_)**x1))**x1 + x1)**2)/x1)**x1
<lambdifygenerated-12615>:2: RuntimeWarning: invalid value encountered in power
  return x1 + ((2*x1 + (x1**2*cosh((_a1_ + x1)*(x1**2 + x1)*exp(log(_a0_)**x1))**x1 + x1)**2)/x1)**x1
<lambdifygenerated-12616>:2: RuntimeWarning: divide by zero encountered in power
  return x1 + ((2*x1 + (x1**2*cosh((_a1_ + x1)*(x1**2 + x1)*exp(log(_a0_)**x1))**x1 + x1)**2)/x1)**x1
<lambdifygenerated-12617>:2: RuntimeWarning: divide by zero encountered in power
  return x1 + ((2*x1 + (x1**2*cosh((_a1_ + x1)*(_a7_*x1 + x1)*exp(log(_a0_)**x1))**x1 + x1)**2)/x1)**x1
<lambdifygenerated-12617>:2: RuntimeWarning: overflow encountered in exp
  return x1 + ((2*x1 + (x1**2*cosh((_a1_ + x1)*(_a7_*x1 + x1)*exp(log(_a0_)**x1))**x1 + x1)**2)/x1)**x1
<lambdifygenerated-12617>:2: RuntimeWarning: overflow encountered in cosh
  return x1 + ((2*x1 + (x1**2*cosh((_a1_ + x1)*(_a7_*x1 + x1)*exp(log(_a0_)**x1))**x1 + x1)**2)/x1)**x1
<lambdifygenerated-12617>:2: RuntimeWarning: invalid value encountered in log
  return x1 + ((2*x1 + (x1**2*cosh((_a1_ + x1)*(_a7_*x1 + x1)*exp(log(_a0_)**x1))**x1 + x1)**2)/x1)**x1
<lambdifygenerated-12618>:2: RuntimeWarning: divide by zero encountered in power
  return x1 + ((2*x1 + (x1**2*cosh((_a1_ + x1)*(_a7_*x1 + x1)*exp(log(_a0_)**x1))**x1 + x1)**2)/x1)**x1
<lambdifygenerated-12619>:2: RuntimeWarning: divide by zero encountered in power
  return x1 + ((2*x1 + (x1**2*cosh((_a1_ + x1)*(_a7_*x1**2 + x1)*exp(log(_a0_)**x1))**x1 + x1)**2)/x1)**x1
<lambdifygenerated-12619>:2: RuntimeWarning: overflow encountered in exp
  return x1 + ((2*x1 + (x1**2*cosh((_a1_ + x1)*(_a7_*x1**2 + x1)*exp(log(_a0_)**x1))**x1 + x1)**2)/x1)**x1
<lambdifygenerated-12619>:2: RuntimeWarning: overflow encountered in cosh
  return x1 + ((2*x1 + (x1**2*cosh((_a1_ + x1)*(_a7_*x1**2 + x1)*exp(log(_a0_)**x1))**x1 + x1)**2)/x1)**x1
<lambdifygenerated-12619>:2: RuntimeWarning: overflow encountered in power
  return x1 + ((2*x1 + (x1**2*cosh((_a1_ + x1)*(_a7_*x1**2 + x1)*exp(log(_a0_)**x1))**x1 + x1)**2)/x1)**x1
<lambdifygenerated-12619>:2: RuntimeWarning: overflow encountered in square
  return x1 + ((2*x1 + (x1**2*cosh((_a1_ + x1)*(_a7_*x1**2 + x1)*exp(log(_a0_)**x1))**x1 + x1)**2)/x1)**x1
<lambdifygenerated-12619>:2: RuntimeWarning: invalid value encountered in log
  return x1 + ((2*x1 + (x1**2*cosh((_a1_ + x1)*(_a7_*x1**2 + x1)*exp(log(_a0_)**x1))**x1 + x1)**2)/x1)**x1
<lambdifygenerated-12620>:2: RuntimeWarning: divide by zero encountered in power
  return x1 + ((2*x1 + (x1**2*cosh((_a1_ + x1)*(_a7_*x1**2 + x1)*exp(log(_a0_)**x1))**x1 + x1)**2)/x1)**x1
<lambdifygenerated-12621>:2: RuntimeWarning: divide by zero encountered in power
  return x1 + ((2*x1 + (x1**2*cosh((_a1_ + x1)*(_a7_*x1**2 + x1)*exp(log(_a0_)**x1))**x1 + x1)**2)/x1)**x1
<lambdifygenerated-12622>:2: RuntimeWarning: divide by zero encountered in power
  return x1 + ((2*x1 + (x1**2*cosh((_a1_ + x1)*(_a7_*x1**2 + x1)*exp(log(_a0_)**x1))**x1 + x1)**2)/x1)**x1
<lambdifygenerated-12623>:2: RuntimeWarning: divide by zero encountered in power
  return x1 + ((2*x1 + (x1**2*cosh((_a1_ + x1)*(_a7_*x1**3 + x1)*exp(log(_a0_)**x1))**x1 + x1)**2)/x1)**x1
<lambdifygenerated-12623>:2: RuntimeWarning: overflow encountered in exp
  return x1 + ((2*x1 + (x1**2*cosh((_a1_ + x1)*(_a7_*x1**3 + x1)*exp(log(_a0_)**x1))**x1 + x1)**2)/x1)**x1
<lambdifygenerated-12623>:2: RuntimeWarning: overflow encountered in cosh
  return x1 + ((2*x1 + (x1**2*cosh((_a1_ + x1)*(_a7_*x1**3 + x1)*exp(log(_a0_)**x1))**x1 + x1)**2)/x1)**x1
<lambdifygenerated-12623>:2: RuntimeWarning: overflow encountered in power
  return x1 + ((2*x1 + (x1**2*cosh((_a1_ + x1)*(_a7_*x1**3 + x1)*exp(log(_a0_)**x1))**x1 + x1)**2)/x1)**x1
<lambdifygenerated-12623>:2: RuntimeWarning: overflow encountered in square
  return x1 + ((2*x1 + (x1**2*cosh((_a1_ + x1)*(_a7_*x1**3 + x1)*exp(log(_a0_)**x1))**x1 + x1)**2)/x1)**x1
<lambdifygenerated-12623>:2: RuntimeWarning: invalid value encountered in log
  return x1 + ((2*x1 + (x1**2*cosh((_a1_ + x1)*(_a7_*x1**3 + x1)*exp(log(_a0_)**x1))**x1 + x1)**2)/x1)**x1
<lambdifygenerated-12623>:2: RuntimeWarning: invalid value encountered in power
  return x1 + ((2*x1 + (x1**2*cosh((_a1_ + x1)*(_a7_*x1**3 + x1)*exp(log(_a0_)**x1))**x1 + x1)**2)/x1)**x1
<lambdifygenerated-12624>:2: RuntimeWarning: divide by zero encountered in power
  return x1 + ((2*x1 + (x1**2*cosh((_a1_ + x1)*(_a7_*x1**3 + x1)*exp(log(_a0_)**x1))**x1 + x1)**2)/x1)**x1
<lambdifygenerated-12625>:2: RuntimeWarning: divide by zero encountered in power
  return x1 + ((2*x1 + (x1**2*cosh((_a1_ + x1)*(_a7_*x1**3 + x1)*exp(log(_a0_)**x1))**x1 + x1)**2)/x1)**x1
<lambdifygenerated-12626>:2: RuntimeWarning: divide by zero encountered in power
  return x1 + ((2*x1 + (x1**2*cosh((_a1_ + x1)*(_a7_*x1**3 + x1)*exp(log(_a0_)**x1))**x1 + x1)**2)/x1)**x1
<lambdifygenerated-12627>:2: RuntimeWarning: divide by zero encountered in power
  return x1 + ((2*x1 + (x1**2*cosh((_a1_ + x1)*(_a5_*_a7_*x1**2 + x1)*exp(log(_a0_)**x1))**x1 + x1)**2)/x1)**x1
<lambdifygenerated-12627>:2: RuntimeWarning: overflow encountered in exp
  return x1 + ((2*x1 + (x1**2*cosh((_a1_ + x1)*(_a5_*_a7_*x1**2 + x1)*exp(log(_a0_)**x1))**x1 + x1)**2)/x1)**x1
<lambdifygenerated-12627>:2: RuntimeWarning: overflow encountered in cosh
  return x1 + ((2*x1 + (x1**2*cosh((_a1_ + x1)*(_a5_*_a7_*x1**2 + x1)*exp(log(_a0_)**x1))**x1 + x1)**2)/x1)**x1
<lambdifygenerated-12627>:2: RuntimeWarning: overflow encountered in square
  return x1 + ((2*x1 + (x1**2*cosh((_a1_ + x1)*(_a5_*_a7_*x1**2 + x1)*exp(log(_a0_)**x1))**x1 + x1)**2)/x1)**x1
<lambdifygenerated-12627>:2: RuntimeWarning: overflow encountered in divide
  return x1 + ((2*x1 + (x1**2*cosh((_a1_ + x1)*(_a5_*_a7_*x1**2 + x1)*exp(log(_a0_)**x1))**x1 + x1)**2)/x1)**x1
<lambdifygenerated-12627>:2: RuntimeWarning: overflow encountered in power
  return x1 + ((2*x1 + (x1**2*cosh((_a1_ + x1)*(_a5_*_a7_*x1**2 + x1)*exp(log(_a0_)**x1))**x1 + x1)**2)/x1)**x1
<lambdifygenerated-12627>:2: RuntimeWarning: overflow encountered in multiply
  return x1 + ((2*x1 + (x1**2*cosh((_a1_ + x1)*(_a5_*_a7_*x1**2 + x1)*exp(log(_a0_)**x1))**x1 + x1)**2)/x1)**x1
<lambdifygenerated-12627>:2: RuntimeWarning: invalid value encountered in log
  return x1 + ((2*x1 + (x1**2*cosh((_a1_ + x1)*(_a5_*_a7_*x1**2 + x1)*exp(log(_a0_)**x1))**x1 + x1)**2)/x1)**x1
<lambdifygenerated-12628>:2: RuntimeWarning: divide by zero encountered in power
  return x1 + ((2*x1 + (x1**2*cosh((_a1_ + x1)*(_a5_*_a7_*x1**2 + x1)*exp(log(_a0_)**x1))**x1 + x1)**2)/x1)**x1
<lambdifygenerated-12629>:2: RuntimeWarning: divide by zero encountered in power
  return x1 + ((2*x1 + (x1**2*cosh((_a1_ + x1)*(_a5_*_a7_*x1**2 + _a5_)*exp(log(_a0_)**x1))**x1 + x1)**2)/x1)**x1
<lambdifygenerated-12629>:2: RuntimeWarning: overflow encountered in exp
  return x1 + ((2*x1 + (x1**2*cosh((_a1_ + x1)*(_a5_*_a7_*x1**2 + _a5_)*exp(log(_a0_)**x1))**x1 + x1)**2)/x1)**x1
<lambdifygenerated-12629>:2: RuntimeWarning: overflow encountered in cosh
  return x1 + ((2*x1 + (x1**2*cosh((_a1_ + x1)*(_a5_*_a7_*x1**2 + _a5_)*exp(log(_a0_)**x1))**x1 + x1)**2)/x1)**x1
<lambdifygenerated-12629>:2: RuntimeWarning: invalid value encountered in power
  return x1 + ((2*x1 + (x1**2*cosh((_a1_ + x1)*(_a5_*_a7_*x1**2 + _a5_)*exp(log(_a0_)**x1))**x1 + x1)**2)/x1)**x1
<lambdifygenerated-12629>:2: RuntimeWarning: overflow encountered in power
  return x1 + ((2*x1 + (x1**2*cosh((_a1_ + x1)*(_a5_*_a7_*x1**2 + _a5_)*exp(log(_a0_)**x1))**x1 + x1)**2)/x1)**x1
<lambdifygenerated-12629>:2: RuntimeWarning: overflow encountered in square
  return x1 + ((2*x1 + (x1**2*cosh((_a1_ + x1)*(_a5_*_a7_*x1**2 + _a5_)*exp(log(_a0_)**x1))**x1 + x1)**2)/x1)**x1
<lambdifygenerated-12629>:2: RuntimeWarning: invalid value encountered in log
  return x1 + ((2*x1 + (x1**2*cosh((_a1_ + x1)*(_a5_*_a7_*x1**2 + _a5_)*exp(log(_a0_)**x1))**x1 + x1)**2)/x1)**x1
<lambdifygenerated-12630>:2: RuntimeWarning: divide by zero encountered in power
  return x1 + ((2*x1 + (x1**2*cosh((_a1_ + x1)*(_a5_*_a7_*x1**2 + _a5_)*exp(log(_a0_)**x1))**x1 + x1)**2)/x1)**x1
<lambdifygenerated-12631>:2: RuntimeWarning: divide by zero encountered in power
  return x1 + ((2*x1 + (x1**2*cosh((_a1_ + x1)*(_a5_*_a7_*x1**2 + _a5_)*exp(log(_a0_)**x1))**_a4_ + x1)**2)/x1)**x1
<lambdifygenerated-12631>:2: RuntimeWarning: overflow encountered in exp
  return x1 + ((2*x1 + (x1**2*cosh((_a1_ + x1)*(_a5_*_a7_*x1**2 + _a5_)*exp(log(_a0_)**x1))**_a4_ + x1)**2)/x1)**x1
<lambdifygenerated-12631>:2: RuntimeWarning: overflow encountered in cosh
  return x1 + ((2*x1 + (x1**2*cosh((_a1_ + x1)*(_a5_*_a7_*x1**2 + _a5_)*exp(log(_a0_)**x1))**_a4_ + x1)**2)/x1)**x1
<lambdifygenerated-12631>:2: RuntimeWarning: overflow encountered in square
  return x1 + ((2*x1 + (x1**2*cosh((_a1_ + x1)*(_a5_*_a7_*x1**2 + _a5_)*exp(log(_a0_)**x1))**_a4_ + x1)**2)/x1)**x1
<lambdifygenerated-12631>:2: RuntimeWarning: invalid value encountered in power
  return x1 + ((2*x1 + (x1**2*cosh((_a1_ + x1)*(_a5_*_a7_*x1**2 + _a5_)*exp(log(_a0_)**x1))**_a4_ + x1)**2)/x1)**x1
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-12632>:2: RuntimeWarning: divide by zero encountered in power
  return x1 + ((2*x1 + (x1**2*cosh((_a1_ + x1)*(_a5_*_a7_*x1**2 + _a5_)*exp(log(_a0_)**x1))**_a4_ + x1)**2)/x1)**x1
<lambdifygenerated-12633>:2: RuntimeWarning: divide by zero encountered in power
  return x1 + ((2*x1 + (_a6_*x1*cosh((_a1_ + x1)*(_a5_*_a7_*x1**2 + _a5_)*exp(log(_a0_)**x1))**_a4_ + x1)**2)/x1)**x1
<lambdifygenerated-12633>:2: RuntimeWarning: overflow encountered in exp
  return x1 + ((2*x1 + (_a6_*x1*cosh((_a1_ + x1)*(_a5_*_a7_*x1**2 + _a5_)*exp(log(_a0_)**x1))**_a4_ + x1)**2)/x1)**x1
<lambdifygenerated-12633>:2: RuntimeWarning: overflow encountered in cosh
  return x1 + ((2*x1 + (_a6_*x1*cosh((_a1_ + x1)*(_a5_*_a7_*x1**2 + _a5_)*exp(log(_a0_)**x1))**_a4_ + x1)**2)/x1)**x1
<lambdifygenerated-12633>:2: RuntimeWarning: overflow encountered in square
  return x1 + ((2*x1 + (_a6_*x1*cosh((_a1_ + x1)*(_a5_*_a7_*x1**2 + _a5_)*exp(log(_a0_)**x1))**_a4_ + x1)**2)/x1)**x1
<lambdifygenerated-12633>:2: RuntimeWarning: invalid value encountered in power
  return x1 + ((2*x1 + (_a6_*x1*cosh((_a1_ + x1)*(_a5_*_a7_*x1**2 + _a5_)*exp(log(_a0_)**x1))**_a4_ + x1)**2)/x1)**x1
<lambdifygenerated-12634>:2: RuntimeWarning: divide by zero encountered in power
  return x1 + ((2*x1 + (_a6_*x1*cosh((_a1_ + x1)*(_a5_*_a7_*x1**2 + _a5_)*exp(log(_a0_)**x1))**_a4_ + x1)**2)/x1)**x1
<lambdifygenerated-12635>:2: RuntimeWarning: divide by zero encountered in power
  return x1 + ((2*x1 + (_a6_*cosh((_a1_ + x1)*(_a5_*_a7_*x1**2 + _a5_)*exp(log(_a0_)**x1))**_a4_ + x1)**2)/x1)**x1
<lambdifygenerated-12635>:2: RuntimeWarning: overflow encountered in exp
  return x1 + ((2*x1 + (_a6_*cosh((_a1_ + x1)*(_a5_*_a7_*x1**2 + _a5_)*exp(log(_a0_)**x1))**_a4_ + x1)**2)/x1)**x1
<lambdifygenerated-12635>:2: RuntimeWarning: overflow encountered in cosh
  return x1 + ((2*x1 + (_a6_*cosh((_a1_ + x1)*(_a5_*_a7_*x1**2 + _a5_)*exp(log(_a0_)**x1))**_a4_ + x1)**2)/x1)**x1
<lambdifygenerated-12635>:2: RuntimeWarning: overflow encountered in square
  return x1 + ((2*x1 + (_a6_*cosh((_a1_ + x1)*(_a5_*_a7_*x1**2 + _a5_)*exp(log(_a0_)**x1))**_a4_ + x1)**2)/x1)**x1
<lambdifygenerated-12635>:2: RuntimeWarning: invalid value encountered in power
  return x1 + ((2*x1 + (_a6_*cosh((_a1_ + x1)*(_a5_*_a7_*x1**2 + _a5_)*exp(log(_a0_)**x1))**_a4_ + x1)**2)/x1)**x1
<lambdifygenerated-12636>:2: RuntimeWarning: divide by zero encountered in power
  return x1 + ((2*x1 + (_a6_*cosh((_a1_ + x1)*(_a5_*_a7_*x1**2 + _a5_)*exp(log(_a0_)**x1))**_a4_ + x1)**2)/x1)**x1
<lambdifygenerated-12637>:2: RuntimeWarning: divide by zero encountered in power
  return x1 + ((2*x1 + (_a1_*_a6_*cosh((_a1_ + x1)*(_a5_*_a7_*x1**2 + _a5_)*exp(log(_a0_)**x1))**_a4_/x1 + x1)**2)/x1)**x1

interpolation

<lambdifygenerated-12640>:2: RuntimeWarning: divide by zero encountered in power
  return x1 + ((2*x1 + (_a1_*_a6_*cosh((_a1_ + x1)*(_a5_*_a7_*x1**2 + _a5_)*exp(log(_a0_)**x1))**_a4_/_a5_ + x1)**2)/x1)**x1
<lambdifygenerated-12641>:2: RuntimeWarning: divide by zero encountered in power
  return x1 + ((2*x1 + (_a1_*_a6_*cosh((_a1_ + x1)*(_a5_*_a7_*x1**2 + _a5_)*exp(log(_a0_)**x1))**_a4_/_a5_ + x1**2)**2)/x1)**x1
<lambdifygenerated-12641>:2: RuntimeWarning: overflow encountered in exp
  return x1 + ((2*x1 + (_a1_*_a6_*cosh((_a1_ + x1)*(_a5_*_a7_*x1**2 + _a5_)*exp(log(_a0_)**x1))**_a4_/_a5_ + x1**2)**2)/x1)**x1
<lambdifygenerated-12641>:2: RuntimeWarning: overflow encountered in cosh
  return x1 + ((2*x1 + (_a1_*_a6_*cosh((_a1_ + x1)*(_a5_*_a7_*x1**2 + _a5_)*exp(log(_a0_)**x1))**_a4_/_a5_ + x1**2)**2)/x1)**x1
<lambdifygenerated-12641>:2: RuntimeWarning: overflow encountered in square
  return x1 + ((2*x1 + (_a1_*_a6_*cosh((_a1_ + x1)*(_a5_*_a7_*x1**2 + _a5_)*exp(log(_a0_)**x1))**_a4_/_a5_ + x1**2)**2)/x1)**x1
<lambdifygenerated-12641>:2: RuntimeWarning: invalid value encountered in power
  return x1 + ((2*x1 + (_a1_*_a6_*cosh((_a1_ + x1)*(_a5_*_a7_*x1**2 + _a5_)*exp(log(_a0_)**x1))**_a4_/_a5_ + x1**2)**2)/x1)**x1
<lambdifygenerated-12642>:2: RuntimeWarning: divide by zero encountered in power
  return x1 + ((2*x1 + (_a1_*_a6_*cosh((_a1_ + x1)*(_a5_*_a7_*x1**2 + _a5_)*exp(log(_a0_)**x1))**_a4_/_a5_ + x1**2)**2)/x1)**x1
<lambdifygenerated-12643>:2: RuntimeWarning: divide by zero encountered in power
  return x1 + ((2*x1 + (_a1_*_a6_*cosh((_a1_ + x1)*(_a5_*_a7_*x1**2 + _a5_)*exp(log(_a0_)**x1))**_a4_/_a5_ + _a6_*x1)**2)/x1)**x1
<lambdifygenerated-12643>:2: RuntimeWarning: overflow encountered in exp
  return x1 + ((2*x1 + (_a1_*_a6_*cosh((_a1_ + x1)*(_a5_*_a7_*x1**2 + _a5_)*exp(log(_a0_)**x1))**_a4_/_a5_ + _a6_*x1)**2)/x1)**x1
<lambdifygenerated-12643>:2: RuntimeWarning: overflow encountered in cosh
  return x1 + ((2*x1 + (_a1_*_a6_*cosh((_a1_ + x1)*(_a5_*_a7_*x1**2 + _a5_)*exp(log(_a0_)**x1))**_a4_/_a5_ + _a6_*x1)**2)/x1)**x1
<lambdifygenerated-12643>:2: RuntimeWarning: overflow encountered in square
  return x1 + ((2*x1 + (_a1_*_a6_*cosh((_a1_ + x1)*(_a5_*_a7_*x1**2 + _a5_)*exp(log(_a0_)**x1))**_a4_/_a5_ + _a6_*x1)**2)/x1)**x1
<lambdifygenerated-12643>:2: RuntimeWarning: invalid value encountered in power
  return x1 + ((2*x1 + (_a1_*_a6_*cosh((_a1_ + x1)*(_a5_*_a7_*x1**2 + _a5_)*exp(log(_a0_)**x1))**_a4_/_a5_ + _a6_*x1)**2)/x1)**x1
<lambdifygenerated-12644>:2: RuntimeWarning: divide by zero encountered in power
  return x1 + ((2*x1 + (_a1_*_a6_*cosh((_a1_ + x1)*(_a5_*_a7_*x1**2 + _a5_)*exp(log(_a0_)**x1))**_a4_/_a5_ + _a6_*x1)**2)/x1)**x1
<lambdifygenerated-12645>:2: RuntimeWarning: divide by zero encountered in power
  return x1 + ((2*x1 + (_a1_*_a6_*cosh((_a1_ + x1)*(_a5_*_a7_*x1**2 + _a5_)*exp(log(_a0_)**x1))**_a4_/_a5_ + _a3_*_a6_)**2)/x1)**x1
<lambdifygenerated-12645>:2: RuntimeWarning: overflow encountered in exp
  return x1 + ((2*x1 + (_a1_*_a6_*cosh((_a1_ + x1)*(_a5_*_a7_*x1**2 + _a5_)*exp(log(_a0_)**x1))**_a4_/_a5_ + _a3_*_a6_)**2)/x1)**x1
<lambdifygenerated-12645>:2: RuntimeWarning: overflow encountered in cosh
  return x1 + ((2*x1 + (_a1_*_a6_*cosh((_a1_ + x1)*(_a5_*_a7_*x1**2 + _a5_)*exp(log(_a0_)**x1))**_a4_/_a5_ + _a3_*_a6_)**2)/x1)**x1
<lambdifygenerated-12645>:2: RuntimeWarning: overflow encountered in square
  return x1 + ((2*x1 + (_a1_*_a6_*cosh((_a1_ + x1)*(_a5_*_a7_*x1**2 + _a5_)*exp(log(_a0_)**x1))**_a4_/_a5_ + _a3_*_a6_)**2)/x1)**x1
<lambdifygenerated-12645>:2: RuntimeWarning: invalid value encountered in power
  return x1 + ((2*x1 + (_a1_*_a6_*cosh((_a1_ + x1)*(_a5_*_a7_*x1**2 + _a5_)*exp(log(_a0_)**x1))**_a4_/_a5_ + _a3_*_a6_)**2)/x1)**x1
<lambdifygenerated-12646>:2: RuntimeWarning: divide by zero encountered in power
  return x1 + ((2*x1 + (_a1_*_a6_*cosh((_a1_ + x1)*(_a5_*_a7_*x1**2 + _a5_)*exp(log(_a0_)**x1))**_a4_/_a5_ + _a3_*_a6_)**2)/x1)**x1
<lambdifygenerated-12647>:2: RuntimeWarning: divide by zero encountered in power
  return x1 + ((_a3_ + x1 + (_a1_*_a6_*cosh((_a1_ + x1)*(_a5_*_a7_*x1**2 + _a5_)*exp(log(_a0_)**x1))**_a4_/_a5_ + _a3_*_a6_)**2)/x1)**x1
<lambdifygenerated-12647>:2: RuntimeWarning: overflow encountered in exp
  return x1 + ((_a3_ + x1 + (_a1_*_a6_*cosh((_a1_ + x1)*(_a5_*_a7_*x1**2 + _a5_)*exp(log(_a0_)**x1))**_a4_/_a5_ + _a3_*_a6_)**2)/x1)**x1
<lambdifygenerated-12647>:2: RuntimeWarning: overflow encountered in cosh
  return x1 + ((_a3_ + x1 + (_a1_*_a6_*cosh((_a1_ + x1)*(_a5_*_a7_*x1**2 + _a5_)*exp(log(_a0_)**x1))**_a4_/_a5_ + _a3_*_a6_)**2)/x1)**x1
<lambdifygenerated-12647>:2: RuntimeWarning: overflow encountered in square
  return x1 + ((_a3_ + x1 + (_a1_*_a6_*cosh((_a1_ + x1)*(_a5_*_a7_*x1**2 + _a5_)*exp(log(_a0_)**x1))**_a4_/_a5_ + _a3_*_a6_)**2)/x1)**x1
<lambdifygenerated-12647>:2: RuntimeWarning: invalid value encountered in power
  return x1 + ((_a3_ + x1 + (_a1_*_a6_*cosh((_a1_ + x1)*(_a5_*_a7_*x1**2 + _a5_)*exp(log(_a0_)**x1))**_a4_/_a5_ + _a3_*_a6_)**2)/x1)**x1
<lambdifygenerated-12648>:2: RuntimeWarning: divide by zero encountered in power
  return x1 + ((_a3_ + x1 + (_a1_*_a6_*cosh((_a1_ + x1)*(_a5_*_a7_*x1**2 + _a5_)*exp(log(_a0_)**x1))**_a4_/_a5_ + _a3_*_a6_)**2)/x1)**x1
<lambdifygenerated-12649>:2: RuntimeWarning: invalid value encountered in power
  return x1 + ((_a3_ + x1**x1 + (_a1_*_a6_*cosh((_a1_ + x1)*(_a5_*_a7_*x1**2 + _a5_)*exp(log(_a0_)**x1))**_a4_/_a5_ + _a3_*_a6_)**2)/x1)**x1
<lambdifygenerated-12649>:2: RuntimeWarning: divide by zero encountered in power
  return x1 + ((_a3_ + x1**x1 + (_a1_*_a6_*cosh((_a1_ + x1)*(_a5_*_a7_*x1**2 + _a5_)*exp(log(_a0_)**x1))**_a4_/_a5_ + _a3_*_a6_)**2)/x1)**x1
<lambdifygenerated-12649>:2: RuntimeWarning: overflow encountered in exp
  return x1 + ((_a3_ + x1**x1 + (_a1_*_a6_*cosh((_a1_ + x1)*(_a5_*_a7_*x1**2 + _a5_)*exp(log(_a0_)**x1))**_a4_/_a5_ + _a3_*_a6_)**2)/x1)**x1
<lambdifygenerated-12649>:2: RuntimeWarning: overflow encountered in cosh
  return x1 + ((_a3_ + x1**x1 + (_a1_*_a6_*cosh((_a1_ + x1)*(_a5_*_a7_*x1**2 + _a5_)*exp(log(_a0_)**x1))**_a4_/_a5_ + _a3_*_a6_)**2)/x1)**x1
<lambdifygenerated-12649>:2: RuntimeWarning: overflow encountered in square
  return x1 + ((_a3_ + x1**x1 + (_a1_*_a6_*cosh((_a1_ + x1)*(_a5_*_a7_*x1**2 + _a5_)*exp(log(_a0_)**x1))**_a4_/_a5_ + _a3_*_a6_)**2)/x1)**x1
<lambdifygenerated-12650>:2: RuntimeWarning: invalid value encountered in power
  return x1 + ((_a3_ + x1**x1 + (_a1_*_a6_*cosh((_a1_ + x1)*(_a5_*_a7_*x1**2 + _a5_)*exp(log(_a0_)**x1))**_a4_/_a5_ + _a3_*_a6_)**2)/x1)**x1
<lambdifygenerated-12650>:2: RuntimeWarning: divide by zero encountered in power
  return x1 + ((_a3_ + x1**x1 + (_a1_*_a6_*cosh((_a1_ + x1)*(_a5_*_a7_*x1**2 + _a5_)*exp(log(_a0_)**x1))**_a4_/_a5_ + _a3_*_a6_)**2)/x1)**x1
<lambdifygenerated-12651>:2: RuntimeWarning: divide by zero encountered in power
  return x1 + ((_a2_**x1 + _a3_ + (_a1_*_a6_*cosh((_a1_ + x1)*(_a5_*_a7_*x1**2 + _a5_)*exp(log(_a0_)**x1))**_a4_/_a5_ + _a3_*_a6_)**2)/x1)**x1
<lambdifygenerated-12651>:2: RuntimeWarning: overflow encountered in exp
  return x1 + ((_a2_**x1 + _a3_ + (_a1_*_a6_*cosh((_a1_ + x1)*(_a5_*_a7_*x1**2 + _a5_)*exp(log(_a0_)**x1))**_a4_/_a5_ + _a3_*_a6_)**2)/x1)**x1
<lambdifygenerated-12651>:2: RuntimeWarning: overflow encountered in cosh
  return x1 + ((_a2_**x1 + _a3_ + (_a1_*_a6_*cosh((_a1_ + x1)*(_a5_*_a7_*x1**2 + _a5_)*exp(log(_a0_)**x1))**_a4_/_a5_ + _a3_*_a6_)**2)/x1)**x1
<lambdifygenerated-12651>:2: RuntimeWarning: overflow encountered in square
  return x1 + ((_a2_**x1 + _a3_ + (_a1_*_a6_*cosh((_a1_ + x1)*(_a5_*_a7_*x1**2 + _a5_)*exp(log(_a0_)**x1))**_a4_/_a5_ + _a3_*_a6_)**2)/x1)**x1
<lambdifygenerated-12651>:2: RuntimeWarning: invalid value encountered in power
  return x1 + ((_a2_**x1 + _a3_ + (_a1_*_a6_*cosh((_a1_ + x1)*(_a5_*_a7_*x1**2 + _a5_)*exp(log(_a0_)**x1))**_a4_/_a5_ + _a3_*_a6_)**2)/x1)**x1
<lambdifygenerated-12652>:2: RuntimeWarning: divide by zero encountered in power
  return x1 + ((_a2_**x1 + _a3_ + (_a1_*_a6_*cosh((_a1_ + x1)*(_a5_*_a7_*x1**2 + _a5_)*exp(log(_a0_)**x1))**_a4_/_a5_ + _a3_*_a6_)**2)/x1)**x1
<lambdifygenerated-12653>:2: RuntimeWarning: divide by zero encountered in power
  return x1 + ((_a2_**x1 + _a3_ + (_a1_*_a6_*cosh((_a1_ + x1)*(_a5_*_a7_*x1**2 + _a5_)*exp(log(_a0_)**x1))**_a4_/_a5_ + _a3_*_a6_)**2)/x1)**x1
<lambdifygenerated-12654>:2: RuntimeWarning: divide by zero encountered in power
  return x1 + ((_a2_**x1 + _a3_ + (_a1_*_a6_*cosh((_a1_ + x1)*(_a5_*_a7_*x1**2 + _a5_)*exp(log(_a0_)**x1))**_a4_/_a5_ + _a3_*_a6_)**2)/x1)**x1
<lambdifygenerated-12655>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (x1**(-x1)*(_a2_**x1 + _a3_ + (_a1_*_a6_*cosh((_a1_ + x1)*(_a5_*_a7_*x1**2 + _a5_)*exp(log(_a0_)**x1))**_a4_/_a5_ + _a3_*_a6_)**2))**x1
<lambdifygenerated-12655>:2: RuntimeWarning: divide by zero encountered in power
  return x1 + (x1**(-x1)*(_a2_**x1 + _a3_ + (_a1_*_a6_*cosh((_a1_ + x1)*(_a5_*_a7_*x1**2 + _a5_)*exp(log(_a0_)**x1))**_a4_/_a5_ + _a3_*_a6_)**2))**x1
<lambdifygenerated-12655>:2: RuntimeWarning: overflow encountered in exp
  return x1 + (x1**(-x1)*(_a2_**x1 + _a3_ + (_a1_*_a6_*cosh((_a1_ + x1)*(_a5_*_a7_*x1**2 + _a5_)*exp(log(_a0_)**x1))**_a4_/_a5_ + _a3_*_a6_)**2))**x1
<lambdifygenerated-12655>:2: RuntimeWarning: overflow encountered in cosh
  return x1 + (x1**(-x1)*(_a2_**x1 + _a3_ + (_a1_*_a6_*cosh((_a1_ + x1)*(_a5_*_a7_*x1**2 + _a5_)*exp(log(_a0_)**x1))**_a4_/_a5_ + _a3_*_a6_)**2))**x1
<lambdifygenerated-12655>:2: RuntimeWarning: overflow encountered in square
  return x1 + (x1**(-x1)*(_a2_**x1 + _a3_ + (_a1_*_a6_*cosh((_a1_ + x1)*(_a5_*_a7_*x1**2 + _a5_)*exp(log(_a0_)**x1))**_a4_/_a5_ + _a3_*_a6_)**2))**x1
<lambdifygenerated-12656>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (x1**(-x1)*(_a2_**x1 + _a3_ + (_a1_*_a6_*cosh((_a1_ + x1)*(_a5_*_a7_*x1**2 + _a5_)*exp(log(_a0_)**x1))**_a4_/_a5_ + _a3_*_a6_)**2))**x1
<lambdifygenerated-12656>:2: RuntimeWarning: divide by zero encountered in power
  return x1 + (x1**(-x1)*(_a2_**x1 + _a3_ + (_a1_*_a6_*cosh((_a1_ + x1)*(_a5_*_a7_*x1**2 + _a5_)*exp(log(_a0_)**x1))**_a4_/_a5_ + _a3_*_a6_)**2))**x1
<lambdifygenerated-12657>:2: RuntimeWarning: divide by zero encountered in power
  return x1 + (_a1_**(-x1)*(_a2_**x1 + _a3_ + (_a1_*_a6_*cosh((_a1_ + x1)*(_a5_*_a7_*x1**2 + _a5_)*exp(log(_a0_)**x1))**_a4_/_a5_ + _a3_*_a6_)**2))**x1
<lambdifygenerated-12657>:2: RuntimeWarning: overflow encountered in exp
  return x1 + (_a1_**(-x1)*(_a2_**x1 + _a3_ + (_a1_*_a6_*cosh((_a1_ + x1)*(_a5_*_a7_*x1**2 + _a5_)*exp(log(_a0_)**x1))**_a4_/_a5_ + _a3_*_a6_)**2))**x1
<lambdifygenerated-12657>:2: RuntimeWarning: overflow encountered in cosh
  return x1 + (_a1_**(-x1)*(_a2_**x1 + _a3_ + (_a1_*_a6_*cosh((_a1_ + x1)*(_a5_*_a7_*x1**2 + _a5_)*exp(log(_a0_)**x1))**_a4_/_a5_ + _a3_*_a6_)**2))**x1
<lambdifygenerated-12657>:2: RuntimeWarning: overflow encountered in square
  return x1 + (_a1_**(-x1)*(_a2_**x1 + _a3_ + (_a1_*_a6_*cosh((_a1_ + x1)*(_a5_*_a7_*x1**2 + _a5_)*exp(log(_a0_)**x1))**_a4_/_a5_ + _a3_*_a6_)**2))**x1
<lambdifygenerated-12657>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (_a1_**(-x1)*(_a2_**x1 + _a3_ + (_a1_*_a6_*cosh((_a1_ + x1)*(_a5_*_a7_*x1**2 + _a5_)*exp(log(_a0_)**x1))**_a4_/_a5_ + _a3_*_a6_)**2))**x1
<lambdifygenerated-12657>:2: RuntimeWarning: invalid value encountered in log
  return x1 + (_a1_**(-x1)*(_a2_**x1 + _a3_ + (_a1_*_a6_*cosh((_a1_ + x1)*(_a5_*_a7_*x1**2 + _a5_)*exp(log(_a0_)**x1))**_a4_/_a5_ + _a3_*_a6_)**2))**x1
<lambdifygenerated-12658>:2: RuntimeWarning: divide by zero encountered in power
  return x1 + (_a1_**(-x1)*(_a2_**x1 + _a3_ + (_a1_*_a6_*cosh((_a1_ + x1)*(_a5_*_a7_*x1**2 + _a5_)*exp(log(_a0_)**x1))**_a4_/_a5_ + _a3_*_a6_)**2))**x1
<lambdifygenerated-12659>:2: RuntimeWarning: divide by zero encountered in power
  return x1 + (_a1_**(-_a0_)*(_a2_**x1 + _a3_ + (_a1_*_a6_*cosh((_a1_ + x1)*(_a5_*_a7_*x1**2 + _a5_)*exp(log(_a0_)**x1))**_a4_/_a5_ + _a3_*_a6_)**2))**x1
<lambdifygenerated-12659>:2: RuntimeWarning: overflow encountered in exp
  return x1 + (_a1_**(-_a0_)*(_a2_**x1 + _a3_ + (_a1_*_a6_*cosh((_a1_ + x1)*(_a5_*_a7_*x1**2 + _a5_)*exp(log(_a0_)**x1))**_a4_/_a5_ + _a3_*_a6_)**2))**x1
<lambdifygenerated-12659>:2: RuntimeWarning: overflow encountered in cosh
  return x1 + (_a1_**(-_a0_)*(_a2_**x1 + _a3_ + (_a1_*_a6_*cosh((_a1_ + x1)*(_a5_*_a7_*x1**2 + _a5_)*exp(log(_a0_)**x1))**_a4_/_a5_ + _a3_*_a6_)**2))**x1
<lambdifygenerated-12659>:2: RuntimeWarning: overflow encountered in square
  return x1 + (_a1_**(-_a0_)*(_a2_**x1 + _a3_ + (_a1_*_a6_*cosh((_a1_ + x1)*(_a5_*_a7_*x1**2 + _a5_)*exp(log(_a0_)**x1))**_a4_/_a5_ + _a3_*_a6_)**2))**x1
<lambdifygenerated-12659>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (_a1_**(-_a0_)*(_a2_**x1 + _a3_ + (_a1_*_a6_*cosh((_a1_ + x1)*(_a5_*_a7_*x1**2 + _a5_)*exp(log(_a0_)**x1))**_a4_/_a5_ + _a3_*_a6_)**2))**x1
<lambdifygenerated-12659>:2: RuntimeWarning: invalid value encountered in log
  return x1 + (_a1_**(-_a0_)*(_a2_**x1 + _a3_ + (_a1_*_a6_*cosh((_a1_ + x1)*(_a5_*_a7_*x1**2 + _a5_)*exp(log(_a0_)**x1))**_a4_/_a5_ + _a3_*_a6_)**2))**x1
<lambdifygenerated-12659>:2: RuntimeWarning: overflow encountered in multiply
  return x1 + (_a1_**(-_a0_)*(_a2_**x1 + _a3_ + (_a1_*_a6_*cosh((_a1_ + x1)*(_a5_*_a7_*x1**2 + _a5_)*exp(log(_a0_)**x1))**_a4_/_a5_ + _a3_*_a6_)**2))**x1
<lambdifygenerated-12660>:2: RuntimeWarning: divide by zero encountered in power
  return x1 + (_a1_**(-_a0_)*(_a2_**x1 + _a3_ + (_a1_*_a6_*cosh((_a1_ + x1)*(_a5_*_a7_*x1**2 + _a5_)*exp(log(_a0_)**x1))**_a4_/_a5_ + _a3_*_a6_)**2))**x1
<lambdifygenerated-12661>:2: RuntimeWarning: divide by zero encountered in power
  return x1 + (_a1_**(-_a0_)*(_a2_**x1 + _a3_ + (_a1_*_a6_*cosh((_a1_ + x1)*(_a5_*_a7_*x1**2 + _a5_)*exp(log(_a0_)**x1))**_a4_/_a5_ + _a3_*_a6_)**2))**_a6_
<lambdifygenerated-12661>:2: RuntimeWarning: overflow encountered in exp
  return x1 + (_a1_**(-_a0_)*(_a2_**x1 + _a3_ + (_a1_*_a6_*cosh((_a1_ + x1)*(_a5_*_a7_*x1**2 + _a5_)*exp(log(_a0_)**x1))**_a4_/_a5_ + _a3_*_a6_)**2))**_a6_
<lambdifygenerated-12661>:2: RuntimeWarning: overflow encountered in cosh
  return x1 + (_a1_**(-_a0_)*(_a2_**x1 + _a3_ + (_a1_*_a6_*cosh((_a1_ + x1)*(_a5_*_a7_*x1**2 + _a5_)*exp(log(_a0_)**x1))**_a4_/_a5_ + _a3_*_a6_)**2))**_a6_
<lambdifygenerated-12661>:2: RuntimeWarning: overflow encountered in square
  return x1 + (_a1_**(-_a0_)*(_a2_**x1 + _a3_ + (_a1_*_a6_*cosh((_a1_ + x1)*(_a5_*_a7_*x1**2 + _a5_)*exp(log(_a0_)**x1))**_a4_/_a5_ + _a3_*_a6_)**2))**_a6_
<lambdifygenerated-12662>:2: RuntimeWarning: divide by zero encountered in power
  return x1 + (_a1_**(-_a0_)*(_a2_**x1 + _a3_ + (_a1_*_a6_*cosh((_a1_ + x1)*(_a5_*_a7_*x1**2 + _a5_)*exp(log(_a0_)**x1))**_a4_/_a5_ + _a3_*_a6_)**2))**_a6_
<lambdifygenerated-12663>:2: RuntimeWarning: divide by zero encountered in power
  return (_a1_**(-_a0_)*(_a2_**x1 + _a3_ + (_a1_*_a6_*cosh((_a1_ + x1)*(_a5_*_a7_*x1**2 + _a5_)*exp(log(_a0_)**x1))**_a4_/_a5_ + _a3_*_a6_)**2))**_a6_ + sin(x1)
<lambdifygenerated-12663>:2: RuntimeWarning: overflow encountered in exp
  return (_a1_**(-_a0_)*(_a2_**x1 + _a3_ + (_a1_*_a6_*cosh((_a1_ + x1)*(_a5_*_a7_*x1**2 + _a5_)*exp(log(_a0_)**x1))**_a4_/_a5_ + _a3_*_a6_)**2))**_a6_ + sin(x1)
<lambdifygenerated-12663>:2: RuntimeWarning: overflow encountered in cosh
  return (_a1_**(-_a0_)*(_a2_**x1 + _a3_ + (_a1_*_a6_*cosh((_a1_ + x1)*(_a5_*_a7_*x1**2 + _a5_)*exp(log(_a0_)**x1))**_a4_/_a5_ + _a3_*_a6_)**2))**_a6_ + sin(x1)
<lambdifygenerated-12663>:2: RuntimeWarning: overflow encountered in square
  return (_a1_**(-_a0_)*(_a2_**x1 + _a3_ + (_a1_*_a6_*cosh((_a1_ + x1)*(_a5_*_a7_*x1**2 + _a5_)*exp(log(_a0_)**x1))**_a4_/_a5_ + _a3_*_a6_)**2))**_a6_ + sin(x1)
<lambdifygenerated-12664>:2: RuntimeWarning: divide by zero encountered in power
  return (_a1_**(-_a0_)*(_a2_**x1 + _a3_ + (_a1_*_a6_*cosh((_a1_ + x1)*(_a5_*_a7_*x1**2 + _a5_)*exp(log(_a0_)**x1))**_a4_/_a5_ + _a3_*_a6_)**2))**_a6_ + sin(x1)
<lambdifygenerated-12665>:2: RuntimeWarning: divide by zero encountered in power
  return (_a1_**(-_a0_)*(_a2_**x1 + _a3_ + (_a1_*_a6_*cosh((_a1_ + x1)*(_a5_*_a7_*x1**2 + _a5_)*exp(log(_a0_)**x1))**_a4_/_a5_ + _a3_*_a6_)**2))**_a6_ + sin(_a4_)
<lambdifygenerated-12665>:2: RuntimeWarning: overflow encountered in exp
  return (_a1_**(-_a0_)*(_a2_**x1 + _a3_ + (_a1_*_a6_*cosh((_a1_ + x1)*(_a5_*_a7_*x1**2 + _a5_)*exp(log(_a0_)**x1))**_a4_/_a5_ + _a3_*_a6_)**2))**_a6_ + sin(_a4_)
<lambdifygenerated-12665>:2: RuntimeWarning: overflow encountered in cosh
  return (_a1_**(-_a0_)*(_a2_**x1 + _a3_ + (_a1_*_a6_*cosh((_a1_ + x1)*(_a5_*_a7_*x1**2 + _a5_)*exp(log(_a0_)**x1))**_a4_/_a5_ + _a3_*_a6_)**2))**_a6_ + sin(_a4_)
<lambdifygenerated-12665>:2: RuntimeWarning: overflow encountered in square
  return (_a1_**(-_a0_)*(_a2_**x1 + _a3_ + (_a1_*_a6_*cosh((_a1_ + x1)*(_a5_*_a7_*x1**2 + _a5_)*exp(log(_a0_)**x1))**_a4_/_a5_ + _a3_*_a6_)**2))**_a6_ + sin(_a4_)
<lambdifygenerated-12666>:2: RuntimeWarning: divide by zero encountered in power
  return (_a1_**(-_a0_)*(_a2_**x1 + _a3_ + (_a1_*_a6_*cosh((_a1_ + x1)*(_a5_*_a7_*x1**2 + _a5_)*exp(log(_a0_)**x1))**_a4_/_a5_ + _a3_*_a6_)**2))**_a6_ + sin(_a4_)
<lambdifygenerated-12667>:2: RuntimeWarning: divide by zero encountered in power
  return (_a1_**(-_a0_)*(_a2_**x1 + _a3_ + (_a1_*_a6_*cosh((_a1_ + x1)*(_a5_*_a7_*x1**2 + _a5_)*exp(log(_a0_)**x1))**_a4_/_a5_ + _a3_*_a6_)**2))**_a6_ + sin(_a4_)
<lambdifygenerated-12668>:2: RuntimeWarning: divide by zero encountered in power
  return (_a1_**(-_a0_)*(_a2_**x1 + _a3_ + (_a1_*_a6_*cosh((_a1_ + x1)*(_a5_*_a7_*x1**2 + _a5_)*exp(log(_a0_)**x1))**_a4_/_a5_ + _a3_*_a6_)**2))**_a6_ + sin(_a4_)
<lambdifygenerated-12669>:2: RuntimeWarning: divide by zero encountered in power
  return (_a1_**(-_a0_)*(_a2_**x1 + _a3_ + (_a1_*_a6_*cosh((_a1_ + x1)*(_a5_*_a7_*x1**2 + _a5_)*exp(log(_a0_)**x1))**_a4_/_a5_ + _a3_*_a6_)**2))**_a6_ + sin(_a4_)
<lambdifygenerated-12669>:2: RuntimeWarning: overflow encountered in exp
  return (_a1_**(-_a0_)*(_a2_**x1 + _a3_ + (_a1_*_a6_*cosh((_a1_ + x1)*(_a5_*_a7_*x1**2 + _a5_)*exp(log(_a0_)**x1))**_a4_/_a5_ + _a3_*_a6_)**2))**_a6_ + sin(_a4_)
<lambdifygenerated-12669>:2: RuntimeWarning: overflow encountered in cosh
  return (_a1_**(-_a0_)*(_a2_**x1 + _a3_ + (_a1_*_a6_*cosh((_a1_ + x1)*(_a5_*_a7_*x1**2 + _a5_)*exp(log(_a0_)**x1))**_a4_/_a5_ + _a3_*_a6_)**2))**_a6_ + sin(_a4_)
<lambdifygenerated-12669>:2: RuntimeWarning: overflow encountered in square
  return (_a1_**(-_a0_)*(_a2_**x1 + _a3_ + (_a1_*_a6_*cosh((_a1_ + x1)*(_a5_*_a7_*x1**2 + _a5_)*exp(log(_a0_)**x1))**_a4_/_a5_ + _a3_*_a6_)**2))**_a6_ + sin(_a4_)
<lambdifygenerated-12670>:2: RuntimeWarning: divide by zero encountered in power
  return (_a1_**(-_a0_)*(_a2_**x1 + _a3_ + (_a1_*_a6_*cosh((_a1_ + x1)*(_a5_*_a7_*x1**2 + _a5_)*exp(log(_a0_)**x1))**_a4_/_a5_ + _a3_*_a6_)**2))**_a6_ + sin(_a4_)

         x1         y  rep    ymodel      ybms
3745  0.997  0.428260  6.0  0.422174  0.427749
3746  0.998  0.428367  6.0  0.422220  0.427890
3747  0.998  0.428474  6.0  0.422265  0.428032
3748  0.999  0.428581  6.0  0.422311  0.428175

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.428794  6.0  0.422403  0.428465
3751  1.002  0.428901  6.0  0.422449  0.428612
3752  1.002  0.429008  6.0  0.422495  0.428759
3753  1.003  0.429115  6.0  0.422541  0.428908

3750

<lambdifygenerated-12677>:2: RuntimeWarning: invalid value encountered in sqrt
  return sqrt(x1) + x1
<lambdifygenerated-12678>:2: RuntimeWarning: invalid value encountered in sqrt
  return sqrt(x1) + x1
<lambdifygenerated-12727>:2: RuntimeWarning: invalid value encountered in power
  return x1 + sqrt(abs(x1*(x1 + cosh(x1 + sin(_a0_*_a3_*x1*(x1 + x1**x1)*sin(_a1_*_a3_*x1 + _a1_))/x1))))
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-12728>:2: RuntimeWarning: invalid value encountered in power
  return x1 + sqrt(abs(x1*(x1 + cosh(x1 + sin(_a0_*_a3_*x1*(x1 + x1**x1)*sin(_a1_*_a3_*x1 + _a1_))/x1))))
<lambdifygenerated-12729>:2: RuntimeWarning: invalid value encountered in power
  return x1 + sqrt(abs(x1*(x1 + cosh(x1 + sin(_a0_*_a3_*x1*(x1 + (2*x1)**x1)*sin(_a1_*_a3_*x1 + _a1_))/x1))))
<lambdifygenerated-12730>:2: RuntimeWarning: invalid value encountered in power
  return x1 + sqrt(abs(x1*(x1 + cosh(x1 + sin(_a0_*_a3_*x1*(x1 + (2*x1)**x1)*sin(_a1_*_a3_*x1 + _a1_))/x1))))
<lambdifygenerated-12731>:2: RuntimeWarning: invalid value encountered in power
  return x1 + sqrt(abs(x1*(x1 + cosh(x1 + sin(_a0_*_a3_*x1*(x1 + (x1 + 1)**x1)*sin(_a1_*_a3_*x1 + _a1_))/x1))))
<lambdifygenerated-12732>:2: RuntimeWarning: invalid value encountered in power
  return x1 + sqrt(abs(x1*(x1 + cosh(x1 + sin(_a0_*_a3_*x1*(x1 + (x1 + 1)**x1)*sin(_a1_*_a3_*x1 + _a1_))/x1))))
<lambdifygenerated-12733>:2: RuntimeWarning: invalid value encountered in power
  return x1 + sqrt(abs(x1*(x1 + cosh(x1 + sin(_a0_*_a3_*x1*(x1 + (_a2_/x1 + x1)**x1)*sin(_a1_*_a3_*x1 + _a1_))/x1))))
<lambdifygenerated-12734>:2: RuntimeWarning: invalid value encountered in power
  return x1 + sqrt(abs(x1*(x1 + cosh(x1 + sin(_a0_*_a3_*x1*(x1 + (_a2_/x1 + x1)**x1)*sin(_a1_*_a3_*x1 + _a1_))/x1))))
<lambdifygenerated-12735>:2: RuntimeWarning: invalid value encountered in power
  return x1 + sqrt(abs(x1*(x1 + cosh(x1 + sin(_a0_*_a3_*x1*(x1 + (_a2_/x1**2 + x1)**x1)*sin(_a1_*_a3_*x1 + _a1_))/x1))))
<lambdifygenerated-12736>:2: RuntimeWarning: invalid value encountered in power
  return x1 + sqrt(abs(x1*(x1 + cosh(x1 + sin(_a0_*_a3_*x1*(x1 + (_a2_/x1**2 + x1)**x1)*sin(_a1_*_a3_*x1 + _a1_))/x1))))
<lambdifygenerated-12737>:2: RuntimeWarning: invalid value encountered in power
  return x1 + sqrt(abs(x1*(x1 + cosh(x1 + sin(_a0_*_a3_*x1*(x1 + (_a2_/sinh(x1)**2 + x1)**x1)*sin(_a1_*_a3_*x1 + _a1_))/x1))))
<lambdifygenerated-12738>:2: RuntimeWarning: invalid value encountered in power
  return x1 + sqrt(abs(x1*(x1 + cosh(x1 + sin(_a0_*_a3_*x1*(x1 + (_a2_/sinh(x1)**2 + x1)**x1)*sin(_a1_*_a3_*x1 + _a1_))/x1))))
<lambdifygenerated-12739>:2: RuntimeWarning: invalid value encountered in power
  return x1 + sqrt(abs(x1*(x1 + cosh(x1 + sin(_a0_*_a3_*x1*(x1 + (_a2_/sinh(x1**2)**2 + x1)**x1)*sin(_a1_*_a3_*x1 + _a1_))/x1))))
<lambdifygenerated-12740>:2: RuntimeWarning: invalid value encountered in power
  return x1 + sqrt(abs(x1*(x1 + cosh(x1 + sin(_a0_*_a3_*x1*(x1 + (_a2_/sinh(x1**2)**2 + x1)**x1)*sin(_a1_*_a3_*x1 + _a1_))/x1))))
<lambdifygenerated-12741>:2: RuntimeWarning: invalid value encountered in power
  return x1 + sqrt(abs(x1*(x1 + cosh(x1 + sin(_a0_*_a3_*x1*(x1 + (_a2_/sinh(x1**2)**2 + x1)**x1)*sin(_a1_*_a3_*x1 + _a1_))/x1))))
<lambdifygenerated-12742>:2: RuntimeWarning: invalid value encountered in power
  return x1 + sqrt(abs(x1*(x1 + cosh(x1 + sin(_a0_*_a3_*x1*(x1 + (_a2_/sinh(x1**2)**2 + x1)**x1)*sin(_a1_*_a3_*x1 + _a1_))/x1))))
<lambdifygenerated-12743>:2: RuntimeWarning: invalid value encountered in power
  return x1 + sqrt(abs(x1*(x1 + cosh(x1 + sin(_a0_*_a3_*x1*(x1 + (_a2_/sinh(_a1_*x1)**2 + x1)**x1)*sin(_a1_*_a3_*x1 + _a1_))/x1))))
<lambdifygenerated-12744>:2: RuntimeWarning: invalid value encountered in power
  return x1 + sqrt(abs(x1*(x1 + cosh(x1 + sin(_a0_*_a3_*x1*(x1 + (_a2_/sinh(_a1_*x1)**2 + x1)**x1)*sin(_a1_*_a3_*x1 + _a1_))/x1))))
<lambdifygenerated-12745>:2: RuntimeWarning: invalid value encountered in power
  return x1 + sqrt(abs(x1*(x1 + cosh(x1 + sin(_a0_*_a3_*x1*(x1 + (_a0_ + _a2_/sinh(_a1_*x1)**2)**x1)*sin(_a1_*_a3_*x1 + _a1_))/x1))))
<lambdifygenerated-12746>:2: RuntimeWarning: invalid value encountered in power
  return x1 + sqrt(abs(x1*(x1 + cosh(x1 + sin(_a0_*_a3_*x1*(x1 + (_a0_ + _a2_/sinh(_a1_*x1)**2)**x1)*sin(_a1_*_a3_*x1 + _a1_))/x1))))
<lambdifygenerated-12747>:2: RuntimeWarning: invalid value encountered in power
  return x1 + sqrt(abs(x1*(x1 + cosh(x1 + sin(_a0_*_a3_*x1*(x1 + (_a0_ + _a2_/sinh(_a1_*x1)**2)**x1)*sin(_a1_*_a3_*x1 + _a1_))/x1))))
<lambdifygenerated-12748>:2: RuntimeWarning: invalid value encountered in power
  return x1 + sqrt(abs(x1*(x1 + cosh(x1 + sin(_a0_*_a3_*x1*(x1 + (_a0_ + _a2_/sinh(_a1_*x1)**2)**x1)*sin(_a1_*_a3_*x1 + _a1_))/x1))))
<lambdifygenerated-12749>:2: RuntimeWarning: invalid value encountered in power
  return x1 + sqrt(abs(x1*(x1 + cosh(x1 + sin(_a0_*_a3_*x1*(_a7_ + (_a0_ + _a2_/sinh(_a1_*x1)**2)**x1)*sin(_a1_*_a3_*x1 + _a1_))/x1))))
<lambdifygenerated-12750>:2: RuntimeWarning: invalid value encountered in power
  return x1 + sqrt(abs(x1*(x1 + cosh(x1 + sin(_a0_*_a3_*x1*(_a7_ + (_a0_ + _a2_/sinh(_a1_*x1)**2)**x1)*sin(_a1_*_a3_*x1 + _a1_))/x1))))
<lambdifygenerated-12751>:2: RuntimeWarning: invalid value encountered in power
  return x1 + sqrt(abs(x1*(x1 + cosh(x1 + sin(_a0_*_a3_*_a5_*(_a7_ + (_a0_ + _a2_/sinh(_a1_*x1)**2)**x1)*sin(_a1_*_a3_*x1 + _a1_))/x1))))
<lambdifygenerated-12751>:2: RuntimeWarning: overflow encountered in cosh
  return x1 + sqrt(abs(x1*(x1 + cosh(x1 + sin(_a0_*_a3_*_a5_*(_a7_ + (_a0_ + _a2_/sinh(_a1_*x1)**2)**x1)*sin(_a1_*_a3_*x1 + _a1_))/x1))))
<lambdifygenerated-12752>:2: RuntimeWarning: invalid value encountered in power
  return x1 + sqrt(abs(x1*(x1 + cosh(x1 + sin(_a0_*_a3_*_a5_*(_a7_ + (_a0_ + _a2_/sinh(_a1_*x1)**2)**x1)*sin(_a1_*_a3_*x1 + _a1_))/x1))))
<lambdifygenerated-12752>:2: RuntimeWarning: overflow encountered in cosh
  return x1 + sqrt(abs(x1*(x1 + cosh(x1 + sin(_a0_*_a3_*_a5_*(_a7_ + (_a0_ + _a2_/sinh(_a1_*x1)**2)**x1)*sin(_a1_*_a3_*x1 + _a1_))/x1))))
<lambdifygenerated-12753>:2: RuntimeWarning: invalid value encountered in power
  return x1 + sqrt(abs(x1*(x1 + cosh(x1 + sin(_a0_*_a3_*_a5_*(_a7_ + (_a0_ + _a2_/sinh(_a1_*x1)**2)**x1)*sin(_a1_*_a3_*x1 + _a1_))/_a7_))))
<lambdifygenerated-12754>:2: RuntimeWarning: invalid value encountered in power
  return x1 + sqrt(abs(x1*(x1 + cosh(x1 + sin(_a0_*_a3_*_a5_*(_a7_ + (_a0_ + _a2_/sinh(_a1_*x1)**2)**x1)*sin(_a1_*_a3_*x1 + _a1_))/_a7_))))
<lambdifygenerated-12755>:2: RuntimeWarning: invalid value encountered in power
  return x1 + sqrt(abs(x1*(x1 + cosh(x1**2 + sin(_a0_*_a3_*_a5_*(_a7_ + (_a0_ + _a2_/sinh(_a1_*x1)**2)**x1)*sin(_a1_*_a3_*x1 + _a1_))/_a7_))))
<lambdifygenerated-12756>:2: RuntimeWarning: invalid value encountered in power
  return x1 + sqrt(abs(x1*(x1 + cosh(x1**2 + sin(_a0_*_a3_*_a5_*(_a7_ + (_a0_ + _a2_/sinh(_a1_*x1)**2)**x1)*sin(_a1_*_a3_*x1 + _a1_))/_a7_))))
<lambdifygenerated-12757>:2: RuntimeWarning: invalid value encountered in power
  return x1 + sqrt(abs(x1*(x1 + cosh(2*x1**2 + sin(_a0_*_a3_*_a5_*(_a7_ + (_a0_ + _a2_/sinh(_a1_*x1)**2)**x1)*sin(_a1_*_a3_*x1 + _a1_))/_a7_))))
<lambdifygenerated-12758>:2: RuntimeWarning: invalid value encountered in power
  return x1 + sqrt(abs(x1*(x1 + cosh(2*x1**2 + sin(_a0_*_a3_*_a5_*(_a7_ + (_a0_ + _a2_/sinh(_a1_*x1)**2)**x1)*sin(_a1_*_a3_*x1 + _a1_))/_a7_))))
<lambdifygenerated-12759>:2: RuntimeWarning: invalid value encountered in power
  return x1 + sqrt(abs(x1*(x1 + cosh(2*x1**2 + sin(_a0_*_a3_*_a5_*(_a7_ + (_a0_ + _a2_/sinh(_a1_*x1)**2)**x1)*sin(_a1_*_a3_*x1 + _a1_))/_a7_))))
<lambdifygenerated-12760>:2: RuntimeWarning: invalid value encountered in power
  return x1 + sqrt(abs(x1*(x1 + cosh(2*x1**2 + sin(_a0_*_a3_*_a5_*(_a7_ + (_a0_ + _a2_/sinh(_a1_*x1)**2)**x1)*sin(_a1_*_a3_*x1 + _a1_))/_a7_))))
<lambdifygenerated-12761>:2: RuntimeWarning: invalid value encountered in power
  return x1 + sqrt(abs(x1*(x1 + cosh(x1*(_a4_ + x1) + sin(_a0_*_a3_*_a5_*(_a7_ + (_a0_ + _a2_/sinh(_a1_*x1)**2)**x1)*sin(_a1_*_a3_*x1 + _a1_))/_a7_))))
<lambdifygenerated-12762>:2: RuntimeWarning: invalid value encountered in power
  return x1 + sqrt(abs(x1*(x1 + cosh(x1*(_a4_ + x1) + sin(_a0_*_a3_*_a5_*(_a7_ + (_a0_ + _a2_/sinh(_a1_*x1)**2)**x1)*sin(_a1_*_a3_*x1 + _a1_))/_a7_))))
<lambdifygenerated-12763>:2: RuntimeWarning: invalid value encountered in power
  return x1 + sqrt(abs(x1*(x1 + cosh(_a0_*(_a4_ + x1) + sin(_a0_*_a3_*_a5_*(_a7_ + (_a0_ + _a2_/sinh(_a1_*x1)**2)**x1)*sin(_a1_*_a3_*x1 + _a1_))/_a7_))))
<lambdifygenerated-12764>:2: RuntimeWarning: invalid value encountered in power
  return x1 + sqrt(abs(x1*(x1 + cosh(_a0_*(_a4_ + x1) + sin(_a0_*_a3_*_a5_*(_a7_ + (_a0_ + _a2_/sinh(_a1_*x1)**2)**x1)*sin(_a1_*_a3_*x1 + _a1_))/_a7_))))

interpolation

<lambdifygenerated-12765>:2: RuntimeWarning: invalid value encountered in power
  return x1 + sqrt(abs(x1*(x1 - cosh(_a0_*(_a4_ + x1) + sin(_a0_*_a3_*_a5_*(_a7_ + (_a0_ + _a2_/sinh(_a1_*x1)**2)**x1)*sin(_a1_*_a3_*x1 + _a1_))/_a7_))))
<lambdifygenerated-12766>:2: RuntimeWarning: invalid value encountered in power
  return x1 + sqrt(abs(x1*(x1 - cosh(_a0_*(_a4_ + x1) + sin(_a0_*_a3_*_a5_*(_a7_ + (_a0_ + _a2_/sinh(_a1_*x1)**2)**x1)*sin(_a1_*_a3_*x1 + _a1_))/_a7_))))
<lambdifygenerated-12767>:2: RuntimeWarning: invalid value encountered in power
  return x1 + sqrt(abs(x1*(_a6_ - cosh(_a0_*(_a4_ + x1) + sin(_a0_*_a3_*_a5_*(_a7_ + (_a0_ + _a2_/sinh(_a1_*x1)**2)**x1)*sin(_a1_*_a3_*x1 + _a1_))/_a7_))))
<lambdifygenerated-12768>:2: RuntimeWarning: invalid value encountered in power
  return x1 + sqrt(abs(x1*(_a6_ - cosh(_a0_*(_a4_ + x1) + sin(_a0_*_a3_*_a5_*(_a7_ + (_a0_ + _a2_/sinh(_a1_*x1)**2)**x1)*sin(_a1_*_a3_*x1 + _a1_))/_a7_))))
<lambdifygenerated-12769>:2: RuntimeWarning: invalid value encountered in power
  return x1 + sqrt(abs(_a0_*(_a6_ - cosh(_a0_*(_a4_ + x1) + sin(_a0_*_a3_*_a5_*(_a7_ + (_a0_ + _a2_/sinh(_a1_*x1)**2)**x1)*sin(_a1_*_a3_*x1 + _a1_))/_a7_))))
<lambdifygenerated-12770>:2: RuntimeWarning: invalid value encountered in power
  return x1 + sqrt(abs(_a0_*(_a6_ - cosh(_a0_*(_a4_ + x1) + sin(_a0_*_a3_*_a5_*(_a7_ + (_a0_ + _a2_/sinh(_a1_*x1)**2)**x1)*sin(_a1_*_a3_*x1 + _a1_))/_a7_))))
<lambdifygenerated-12771>:2: RuntimeWarning: invalid value encountered in power
  return sin(x1) + sqrt(abs(_a0_*(_a6_ - cosh(_a0_*(_a4_ + x1) + sin(_a0_*_a3_*_a5_*(_a7_ + (_a0_ + _a2_/sinh(_a1_*x1)**2)**x1)*sin(_a1_*_a3_*x1 + _a1_))/_a7_))))
<lambdifygenerated-12772>:2: RuntimeWarning: invalid value encountered in power
  return sin(x1) + sqrt(abs(_a0_*(_a6_ - cosh(_a0_*(_a4_ + x1) + sin(_a0_*_a3_*_a5_*(_a7_ + (_a0_ + _a2_/sinh(_a1_*x1)**2)**x1)*sin(_a1_*_a3_*x1 + _a1_))/_a7_))))
<lambdifygenerated-12773>:2: RuntimeWarning: invalid value encountered in power
  return sin(_a5_) + sqrt(abs(_a0_*(_a6_ - cosh(_a0_*(_a4_ + x1) + sin(_a0_*_a3_*_a5_*(_a7_ + (_a0_ + _a2_/sinh(_a1_*x1)**2)**x1)*sin(_a1_*_a3_*x1 + _a1_))/_a7_))))
<lambdifygenerated-12774>:2: RuntimeWarning: invalid value encountered in power
  return sin(_a5_) + sqrt(abs(_a0_*(_a6_ - cosh(_a0_*(_a4_ + x1) + sin(_a0_*_a3_*_a5_*(_a7_ + (_a0_ + _a2_/sinh(_a1_*x1)**2)**x1)*sin(_a1_*_a3_*x1 + _a1_))/_a7_))))
<lambdifygenerated-12775>:2: RuntimeWarning: invalid value encountered in power
  return sin(_a5_) + sqrt(abs(_a0_*(_a6_ - cosh(_a0_*(_a4_ + x1) + sin(_a0_*_a3_*_a5_*(_a7_ + (_a0_ + _a2_/sinh(_a1_*x1)**2)**x1)*sin(_a1_*_a3_*x1 + _a1_))/_a7_))))
<lambdifygenerated-12776>:2: RuntimeWarning: invalid value encountered in power
  return sin(_a5_) + sqrt(abs(_a0_*(_a6_ - cosh(_a0_*(_a4_ + x1) + sin(_a0_*_a3_*_a5_*(_a7_ + (_a0_ + _a2_/sinh(_a1_*x1)**2)**x1)*sin(_a1_*_a3_*x1 + _a1_))/_a7_))))
<lambdifygenerated-12777>:2: RuntimeWarning: invalid value encountered in power
  return sin(_a5_) + sqrt(abs(_a0_*(_a6_ - cosh(_a0_*(_a4_ + x1) + sin(_a0_*_a3_*_a5_*(_a7_ + (_a0_ + _a2_/sinh(_a1_*x1)**2)**x1)*sin(_a1_*_a3_*x1 + _a1_))/_a7_))))
<lambdifygenerated-12778>:2: RuntimeWarning: invalid value encountered in power
  return sin(_a5_) + sqrt(abs(_a0_*(_a6_ - cosh(_a0_*(_a4_ + x1) + sin(_a0_*_a3_*_a5_*(_a7_ + (_a0_ + _a2_/sinh(_a1_*x1)**2)**x1)*sin(_a1_*_a3_*x1 + _a1_))/_a7_))))

         x1         y  rep    ymodel      ybms
3745  0.997  0.173654  7.0  0.177910  0.176867
3746  0.998  0.173884  7.0  0.178192  0.177107
3747  0.998  0.174114  7.0  0.178474  0.177348
3748  0.999  0.174344  7.0  0.178756  0.177589

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.174804  7.0  0.179321  0.178069
3751  1.002  0.175034  7.0  0.179604  0.178309
3752  1.002  0.175264  7.0  0.179887  0.178549
3753  1.003  0.175494  7.0  0.180170  0.178788

3750
interpolation

/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-12819>:2: RuntimeWarning: overflow encountered in exp
  return x1**4*(x1*sin(_a1_*exp(-_a4_*_a5_*x1/(x1**2 + x1))) + x1)**2 + 2*x1
<lambdifygenerated-12819>:2: RuntimeWarning: invalid value encountered in sin
  return x1**4*(x1*sin(_a1_*exp(-_a4_*_a5_*x1/(x1**2 + x1))) + x1)**2 + 2*x1
<lambdifygenerated-12820>:2: RuntimeWarning: overflow encountered in exp
  return x1**4*(x1*sin(_a1_*exp(-_a4_*_a5_*x1/(x1**2 + x1))) + x1)**2 + 2*x1
<lambdifygenerated-12820>:2: RuntimeWarning: invalid value encountered in sin
  return x1**4*(x1*sin(_a1_*exp(-_a4_*_a5_*x1/(x1**2 + x1))) + x1)**2 + 2*x1
<lambdifygenerated-12821>:2: RuntimeWarning: overflow encountered in exp
  return x1**4*(x1*sin(_a1_*exp(-_a4_*_a5_*x1/(x1**2 + x1))) + x1)**2 + 2*x1
<lambdifygenerated-12821>:2: RuntimeWarning: invalid value encountered in sin
  return x1**4*(x1*sin(_a1_*exp(-_a4_*_a5_*x1/(x1**2 + x1))) + x1)**2 + 2*x1
<lambdifygenerated-12822>:2: RuntimeWarning: overflow encountered in exp
  return x1**4*(x1*sin(_a1_*exp(-_a4_*_a5_*x1/(x1**2 + x1))) + x1)**2 + 2*x1
<lambdifygenerated-12822>:2: RuntimeWarning: invalid value encountered in sin
  return x1**4*(x1*sin(_a1_*exp(-_a4_*_a5_*x1/(x1**2 + x1))) + x1)**2 + 2*x1
<lambdifygenerated-12825>:2: RuntimeWarning: overflow encountered in exp
  return x1**4*(x1*sin(_a1_*exp(-_a1_*_a4_*_a5_/(_a4_ + x1**2))) + x1)**2 + 2*x1
<lambdifygenerated-12825>:2: RuntimeWarning: invalid value encountered in sin
  return x1**4*(x1*sin(_a1_*exp(-_a1_*_a4_*_a5_/(_a4_ + x1**2))) + x1)**2 + 2*x1
<lambdifygenerated-12826>:2: RuntimeWarning: overflow encountered in exp
  return x1**4*(x1*sin(_a1_*exp(-_a1_*_a4_*_a5_/(_a4_ + x1**2))) + x1)**2 + 2*x1
<lambdifygenerated-12826>:2: RuntimeWarning: invalid value encountered in sin
  return x1**4*(x1*sin(_a1_*exp(-_a1_*_a4_*_a5_/(_a4_ + x1**2))) + x1)**2 + 2*x1
<lambdifygenerated-12827>:2: RuntimeWarning: overflow encountered in exp
  return x1**4*(2*x1*sin(_a1_*exp(-_a1_*_a4_*_a5_/(_a4_ + x1**2))) + x1)**2 + 2*x1
<lambdifygenerated-12827>:2: RuntimeWarning: invalid value encountered in sin
  return x1**4*(2*x1*sin(_a1_*exp(-_a1_*_a4_*_a5_/(_a4_ + x1**2))) + x1)**2 + 2*x1
<lambdifygenerated-12828>:2: RuntimeWarning: overflow encountered in exp
  return x1**4*(2*x1*sin(_a1_*exp(-_a1_*_a4_*_a5_/(_a4_ + x1**2))) + x1)**2 + 2*x1
<lambdifygenerated-12828>:2: RuntimeWarning: invalid value encountered in sin
  return x1**4*(2*x1*sin(_a1_*exp(-_a1_*_a4_*_a5_/(_a4_ + x1**2))) + x1)**2 + 2*x1
<lambdifygenerated-12829>:2: RuntimeWarning: overflow encountered in exp
  return x1**4*(3*x1*sin(_a1_*exp(-_a1_*_a4_*_a5_/(_a4_ + x1**2))) + x1)**2 + 2*x1
<lambdifygenerated-12829>:2: RuntimeWarning: invalid value encountered in sin
  return x1**4*(3*x1*sin(_a1_*exp(-_a1_*_a4_*_a5_/(_a4_ + x1**2))) + x1)**2 + 2*x1
<lambdifygenerated-12830>:2: RuntimeWarning: overflow encountered in exp
  return x1**4*(3*x1*sin(_a1_*exp(-_a1_*_a4_*_a5_/(_a4_ + x1**2))) + x1)**2 + 2*x1
<lambdifygenerated-12830>:2: RuntimeWarning: invalid value encountered in sin
  return x1**4*(3*x1*sin(_a1_*exp(-_a1_*_a4_*_a5_/(_a4_ + x1**2))) + x1)**2 + 2*x1
<lambdifygenerated-12831>:2: RuntimeWarning: overflow encountered in exp
  return x1**4*(x1 + (_a0_ + 2*x1)*sin(_a1_*exp(-_a1_*_a4_*_a5_/(_a4_ + x1**2))))**2 + 2*x1
<lambdifygenerated-12831>:2: RuntimeWarning: invalid value encountered in sin
  return x1**4*(x1 + (_a0_ + 2*x1)*sin(_a1_*exp(-_a1_*_a4_*_a5_/(_a4_ + x1**2))))**2 + 2*x1
<lambdifygenerated-12832>:2: RuntimeWarning: overflow encountered in exp
  return x1**4*(x1 + (_a0_ + 2*x1)*sin(_a1_*exp(-_a1_*_a4_*_a5_/(_a4_ + x1**2))))**2 + 2*x1
<lambdifygenerated-12832>:2: RuntimeWarning: invalid value encountered in sin
  return x1**4*(x1 + (_a0_ + 2*x1)*sin(_a1_*exp(-_a1_*_a4_*_a5_/(_a4_ + x1**2))))**2 + 2*x1
<lambdifygenerated-12833>:2: RuntimeWarning: overflow encountered in exp
  return x1**4*(x1 + (_a0_ + 2*x1)*sin(_a1_*exp(-_a1_*_a4_*_a5_/(_a4_ + x1**2))))**2 + 2*x1
<lambdifygenerated-12833>:2: RuntimeWarning: invalid value encountered in sin
  return x1**4*(x1 + (_a0_ + 2*x1)*sin(_a1_*exp(-_a1_*_a4_*_a5_/(_a4_ + x1**2))))**2 + 2*x1
<lambdifygenerated-12834>:2: RuntimeWarning: overflow encountered in exp
  return x1**4*(x1 + (_a0_ + 2*x1)*sin(_a1_*exp(-_a1_*_a4_*_a5_/(_a4_ + x1**2))))**2 + 2*x1
<lambdifygenerated-12834>:2: RuntimeWarning: invalid value encountered in sin
  return x1**4*(x1 + (_a0_ + 2*x1)*sin(_a1_*exp(-_a1_*_a4_*_a5_/(_a4_ + x1**2))))**2 + 2*x1
<lambdifygenerated-12835>:2: RuntimeWarning: overflow encountered in exp
  return x1**4*(x1 + (_a0_ + 3*x1)*sin(_a1_*exp(-_a1_*_a4_*_a5_/(_a4_ + x1**2))))**2 + 2*x1
<lambdifygenerated-12835>:2: RuntimeWarning: invalid value encountered in sin
  return x1**4*(x1 + (_a0_ + 3*x1)*sin(_a1_*exp(-_a1_*_a4_*_a5_/(_a4_ + x1**2))))**2 + 2*x1
<lambdifygenerated-12836>:2: RuntimeWarning: overflow encountered in exp
  return x1**4*(x1 + (_a0_ + 3*x1)*sin(_a1_*exp(-_a1_*_a4_*_a5_/(_a4_ + x1**2))))**2 + 2*x1
<lambdifygenerated-12836>:2: RuntimeWarning: invalid value encountered in sin
  return x1**4*(x1 + (_a0_ + 3*x1)*sin(_a1_*exp(-_a1_*_a4_*_a5_/(_a4_ + x1**2))))**2 + 2*x1
<lambdifygenerated-12837>:2: RuntimeWarning: overflow encountered in exp
  return x1**4*(x1 + (_a0_ + _a1_ + 2*x1)*sin(_a1_*exp(-_a1_*_a4_*_a5_/(_a4_ + x1**2))))**2 + 2*x1
<lambdifygenerated-12837>:2: RuntimeWarning: invalid value encountered in sin
  return x1**4*(x1 + (_a0_ + _a1_ + 2*x1)*sin(_a1_*exp(-_a1_*_a4_*_a5_/(_a4_ + x1**2))))**2 + 2*x1
<lambdifygenerated-12838>:2: RuntimeWarning: overflow encountered in exp
  return x1**4*(x1 + (_a0_ + _a1_ + 2*x1)*sin(_a1_*exp(-_a1_*_a4_*_a5_/(_a4_ + x1**2))))**2 + 2*x1
<lambdifygenerated-12838>:2: RuntimeWarning: invalid value encountered in sin
  return x1**4*(x1 + (_a0_ + _a1_ + 2*x1)*sin(_a1_*exp(-_a1_*_a4_*_a5_/(_a4_ + x1**2))))**2 + 2*x1
<lambdifygenerated-12839>:2: RuntimeWarning: overflow encountered in exp
  return x1**4*(x1 + (_a0_ + _a1_)*sin(_a1_*exp(-_a1_*_a4_*_a5_/(_a4_ + x1**2))))**2 + 2*x1
<lambdifygenerated-12839>:2: RuntimeWarning: invalid value encountered in sin
  return x1**4*(x1 + (_a0_ + _a1_)*sin(_a1_*exp(-_a1_*_a4_*_a5_/(_a4_ + x1**2))))**2 + 2*x1
<lambdifygenerated-12840>:2: RuntimeWarning: overflow encountered in exp
  return x1**4*(x1 + (_a0_ + _a1_)*sin(_a1_*exp(-_a1_*_a4_*_a5_/(_a4_ + x1**2))))**2 + 2*x1
<lambdifygenerated-12840>:2: RuntimeWarning: invalid value encountered in sin
  return x1**4*(x1 + (_a0_ + _a1_)*sin(_a1_*exp(-_a1_*_a4_*_a5_/(_a4_ + x1**2))))**2 + 2*x1
<lambdifygenerated-12841>:2: RuntimeWarning: overflow encountered in exp
  return x1**4*(x1 + (_a0_ + _a1_ - _a7_ + x1)*sin(_a1_*exp(-_a1_*_a4_*_a5_/(_a4_ + x1**2))))**2 + 2*x1
<lambdifygenerated-12841>:2: RuntimeWarning: invalid value encountered in sin
  return x1**4*(x1 + (_a0_ + _a1_ - _a7_ + x1)*sin(_a1_*exp(-_a1_*_a4_*_a5_/(_a4_ + x1**2))))**2 + 2*x1
<lambdifygenerated-12842>:2: RuntimeWarning: overflow encountered in exp
  return x1**4*(x1 + (_a0_ + _a1_ - _a7_ + x1)*sin(_a1_*exp(-_a1_*_a4_*_a5_/(_a4_ + x1**2))))**2 + 2*x1
<lambdifygenerated-12842>:2: RuntimeWarning: invalid value encountered in sin
  return x1**4*(x1 + (_a0_ + _a1_ - _a7_ + x1)*sin(_a1_*exp(-_a1_*_a4_*_a5_/(_a4_ + x1**2))))**2 + 2*x1
<lambdifygenerated-12843>:2: RuntimeWarning: overflow encountered in exp
  return x1**4*(_a4_ + (_a0_ + _a1_ - _a7_ + x1)*sin(_a1_*exp(-_a1_*_a4_*_a5_/(_a4_ + x1**2))))**2 + 2*x1
<lambdifygenerated-12843>:2: RuntimeWarning: invalid value encountered in sin
  return x1**4*(_a4_ + (_a0_ + _a1_ - _a7_ + x1)*sin(_a1_*exp(-_a1_*_a4_*_a5_/(_a4_ + x1**2))))**2 + 2*x1
<lambdifygenerated-12844>:2: RuntimeWarning: overflow encountered in exp
  return x1**4*(_a4_ + (_a0_ + _a1_ - _a7_ + x1)*sin(_a1_*exp(-_a1_*_a4_*_a5_/(_a4_ + x1**2))))**2 + 2*x1
<lambdifygenerated-12844>:2: RuntimeWarning: invalid value encountered in sin
  return x1**4*(_a4_ + (_a0_ + _a1_ - _a7_ + x1)*sin(_a1_*exp(-_a1_*_a4_*_a5_/(_a4_ + x1**2))))**2 + 2*x1
<lambdifygenerated-12845>:2: RuntimeWarning: invalid value encountered in power
  return x1**2*x1**(2*x1)*(_a4_ + (_a0_ + _a1_ - _a7_ + x1)*sin(_a1_*exp(-_a1_*_a4_*_a5_/(_a4_ + x1**2))))**2 + 2*x1
<lambdifygenerated-12845>:2: RuntimeWarning: overflow encountered in exp
  return x1**2*x1**(2*x1)*(_a4_ + (_a0_ + _a1_ - _a7_ + x1)*sin(_a1_*exp(-_a1_*_a4_*_a5_/(_a4_ + x1**2))))**2 + 2*x1
<lambdifygenerated-12845>:2: RuntimeWarning: invalid value encountered in sin
  return x1**2*x1**(2*x1)*(_a4_ + (_a0_ + _a1_ - _a7_ + x1)*sin(_a1_*exp(-_a1_*_a4_*_a5_/(_a4_ + x1**2))))**2 + 2*x1
<lambdifygenerated-12846>:2: RuntimeWarning: invalid value encountered in power
  return x1**2*x1**(2*x1)*(_a4_ + (_a0_ + _a1_ - _a7_ + x1)*sin(_a1_*exp(-_a1_*_a4_*_a5_/(_a4_ + x1**2))))**2 + 2*x1
<lambdifygenerated-12846>:2: RuntimeWarning: overflow encountered in exp
  return x1**2*x1**(2*x1)*(_a4_ + (_a0_ + _a1_ - _a7_ + x1)*sin(_a1_*exp(-_a1_*_a4_*_a5_/(_a4_ + x1**2))))**2 + 2*x1
<lambdifygenerated-12846>:2: RuntimeWarning: invalid value encountered in sin
  return x1**2*x1**(2*x1)*(_a4_ + (_a0_ + _a1_ - _a7_ + x1)*sin(_a1_*exp(-_a1_*_a4_*_a5_/(_a4_ + x1**2))))**2 + 2*x1
<lambdifygenerated-12847>:2: RuntimeWarning: overflow encountered in exp
  return _a6_**(2*x1)*x1**2*(_a4_ + (_a0_ + _a1_ - _a7_ + x1)*sin(_a1_*exp(-_a1_*_a4_*_a5_/(_a4_ + x1**2))))**2 + 2*x1
<lambdifygenerated-12847>:2: RuntimeWarning: invalid value encountered in sin
  return _a6_**(2*x1)*x1**2*(_a4_ + (_a0_ + _a1_ - _a7_ + x1)*sin(_a1_*exp(-_a1_*_a4_*_a5_/(_a4_ + x1**2))))**2 + 2*x1
<lambdifygenerated-12848>:2: RuntimeWarning: overflow encountered in exp
  return _a6_**(2*x1)*x1**2*(_a4_ + (_a0_ + _a1_ - _a7_ + x1)*sin(_a1_*exp(-_a1_*_a4_*_a5_/(_a4_ + x1**2))))**2 + 2*x1
<lambdifygenerated-12848>:2: RuntimeWarning: invalid value encountered in sin
  return _a6_**(2*x1)*x1**2*(_a4_ + (_a0_ + _a1_ - _a7_ + x1)*sin(_a1_*exp(-_a1_*_a4_*_a5_/(_a4_ + x1**2))))**2 + 2*x1
<lambdifygenerated-12849>:2: RuntimeWarning: overflow encountered in exp
  return _a6_**(2*x1)*x1**2*(_a4_ + (_a0_ + _a1_ - _a7_ + x1)*sin(_a1_*exp(-_a1_*_a4_*_a5_/(_a4_ + x1**2))))**2 + 2*x1
<lambdifygenerated-12849>:2: RuntimeWarning: invalid value encountered in sin
  return _a6_**(2*x1)*x1**2*(_a4_ + (_a0_ + _a1_ - _a7_ + x1)*sin(_a1_*exp(-_a1_*_a4_*_a5_/(_a4_ + x1**2))))**2 + 2*x1
<lambdifygenerated-12850>:2: RuntimeWarning: overflow encountered in exp
  return _a6_**(2*x1)*x1**2*(_a4_ + (_a0_ + _a1_ - _a7_ + x1)*sin(_a1_*exp(-_a1_*_a4_*_a5_/(_a4_ + x1**2))))**2 + 2*x1
<lambdifygenerated-12850>:2: RuntimeWarning: invalid value encountered in sin
  return _a6_**(2*x1)*x1**2*(_a4_ + (_a0_ + _a1_ - _a7_ + x1)*sin(_a1_*exp(-_a1_*_a4_*_a5_/(_a4_ + x1**2))))**2 + 2*x1
<lambdifygenerated-12851>:2: RuntimeWarning: overflow encountered in exp
  return _a3_**2*_a6_**(2*x1)*(_a4_ + (_a0_ + _a1_ - _a7_ + x1)*sin(_a1_*exp(-_a1_*_a4_*_a5_/(_a4_ + x1**2))))**2 + 2*x1
<lambdifygenerated-12851>:2: RuntimeWarning: invalid value encountered in sin
  return _a3_**2*_a6_**(2*x1)*(_a4_ + (_a0_ + _a1_ - _a7_ + x1)*sin(_a1_*exp(-_a1_*_a4_*_a5_/(_a4_ + x1**2))))**2 + 2*x1
<lambdifygenerated-12852>:2: RuntimeWarning: overflow encountered in exp
  return _a3_**2*_a6_**(2*x1)*(_a4_ + (_a0_ + _a1_ - _a7_ + x1)*sin(_a1_*exp(-_a1_*_a4_*_a5_/(_a4_ + x1**2))))**2 + 2*x1
<lambdifygenerated-12852>:2: RuntimeWarning: invalid value encountered in sin
  return _a3_**2*_a6_**(2*x1)*(_a4_ + (_a0_ + _a1_ - _a7_ + x1)*sin(_a1_*exp(-_a1_*_a4_*_a5_/(_a4_ + x1**2))))**2 + 2*x1
<lambdifygenerated-12853>:2: RuntimeWarning: overflow encountered in exp
  return _a2_ + _a3_**2*_a6_**(2*x1)*(_a4_ + (_a0_ + _a1_ - _a7_ + x1)*sin(_a1_*exp(-_a1_*_a4_*_a5_/(_a4_ + x1**2))))**2 + x1
<lambdifygenerated-12853>:2: RuntimeWarning: invalid value encountered in sin
  return _a2_ + _a3_**2*_a6_**(2*x1)*(_a4_ + (_a0_ + _a1_ - _a7_ + x1)*sin(_a1_*exp(-_a1_*_a4_*_a5_/(_a4_ + x1**2))))**2 + x1
<lambdifygenerated-12854>:2: RuntimeWarning: overflow encountered in exp
  return _a2_ + _a3_**2*_a6_**(2*x1)*(_a4_ + (_a0_ + _a1_ - _a7_ + x1)*sin(_a1_*exp(-_a1_*_a4_*_a5_/(_a4_ + x1**2))))**2 + x1
<lambdifygenerated-12854>:2: RuntimeWarning: invalid value encountered in sin
  return _a2_ + _a3_**2*_a6_**(2*x1)*(_a4_ + (_a0_ + _a1_ - _a7_ + x1)*sin(_a1_*exp(-_a1_*_a4_*_a5_/(_a4_ + x1**2))))**2 + x1
<lambdifygenerated-12855>:2: RuntimeWarning: overflow encountered in exp
  return _a2_ + _a3_**2*_a6_**(2*x1)*(_a4_ + (_a0_ + _a1_ - _a7_ + x1)*sin(_a1_*exp(-_a1_*_a4_*_a5_/(_a4_ + x1**2))))**2 + x1**2
<lambdifygenerated-12855>:2: RuntimeWarning: invalid value encountered in sin
  return _a2_ + _a3_**2*_a6_**(2*x1)*(_a4_ + (_a0_ + _a1_ - _a7_ + x1)*sin(_a1_*exp(-_a1_*_a4_*_a5_/(_a4_ + x1**2))))**2 + x1**2
<lambdifygenerated-12856>:2: RuntimeWarning: overflow encountered in exp
  return _a2_ + _a3_**2*_a6_**(2*x1)*(_a4_ + (_a0_ + _a1_ - _a7_ + x1)*sin(_a1_*exp(-_a1_*_a4_*_a5_/(_a4_ + x1**2))))**2 + x1**2
<lambdifygenerated-12856>:2: RuntimeWarning: invalid value encountered in sin
  return _a2_ + _a3_**2*_a6_**(2*x1)*(_a4_ + (_a0_ + _a1_ - _a7_ + x1)*sin(_a1_*exp(-_a1_*_a4_*_a5_/(_a4_ + x1**2))))**2 + x1**2
<lambdifygenerated-12857>:2: RuntimeWarning: overflow encountered in exp
  return _a2_ + _a3_**2*_a6_**(2*x1)*(_a4_ + (_a0_ + _a1_ - _a7_ + x1)*sin(_a1_*exp(-_a1_*_a4_*_a5_/(_a4_ + x1**2))))**2 + x1**2
<lambdifygenerated-12857>:2: RuntimeWarning: invalid value encountered in sin
  return _a2_ + _a3_**2*_a6_**(2*x1)*(_a4_ + (_a0_ + _a1_ - _a7_ + x1)*sin(_a1_*exp(-_a1_*_a4_*_a5_/(_a4_ + x1**2))))**2 + x1**2
<lambdifygenerated-12858>:2: RuntimeWarning: overflow encountered in exp
  return _a2_ + _a3_**2*_a6_**(2*x1)*(_a4_ + (_a0_ + _a1_ - _a7_ + x1)*sin(_a1_*exp(-_a1_*_a4_*_a5_/(_a4_ + x1**2))))**2 + x1**2
<lambdifygenerated-12858>:2: RuntimeWarning: invalid value encountered in sin
  return _a2_ + _a3_**2*_a6_**(2*x1)*(_a4_ + (_a0_ + _a1_ - _a7_ + x1)*sin(_a1_*exp(-_a1_*_a4_*_a5_/(_a4_ + x1**2))))**2 + x1**2
<lambdifygenerated-12859>:2: RuntimeWarning: overflow encountered in exp
  return _a2_ + _a3_**2*_a6_**(2*x1)*(_a4_ + (_a0_ + _a1_ - _a7_ + x1)*sin(_a1_*exp(-_a1_*_a4_*_a5_/(_a4_ + x1**2))))**2 + _a7_*x1
<lambdifygenerated-12859>:2: RuntimeWarning: invalid value encountered in sin
  return _a2_ + _a3_**2*_a6_**(2*x1)*(_a4_ + (_a0_ + _a1_ - _a7_ + x1)*sin(_a1_*exp(-_a1_*_a4_*_a5_/(_a4_ + x1**2))))**2 + _a7_*x1
<lambdifygenerated-12860>:2: RuntimeWarning: overflow encountered in exp
  return _a2_ + _a3_**2*_a6_**(2*x1)*(_a4_ + (_a0_ + _a1_ - _a7_ + x1)*sin(_a1_*exp(-_a1_*_a4_*_a5_/(_a4_ + x1**2))))**2 + _a7_*x1
<lambdifygenerated-12860>:2: RuntimeWarning: invalid value encountered in sin
  return _a2_ + _a3_**2*_a6_**(2*x1)*(_a4_ + (_a0_ + _a1_ - _a7_ + x1)*sin(_a1_*exp(-_a1_*_a4_*_a5_/(_a4_ + x1**2))))**2 + _a7_*x1
<lambdifygenerated-12861>:2: RuntimeWarning: overflow encountered in exp
  return _a2_ + _a3_**2*_a6_**(2*x1)*(_a4_ + (_a0_ + _a1_ - _a7_ + x1)*sin(_a1_*exp(-_a1_*_a4_*_a5_/(_a4_ + x1**2))))**2 + _a7_*x1
<lambdifygenerated-12861>:2: RuntimeWarning: invalid value encountered in sin
  return _a2_ + _a3_**2*_a6_**(2*x1)*(_a4_ + (_a0_ + _a1_ - _a7_ + x1)*sin(_a1_*exp(-_a1_*_a4_*_a5_/(_a4_ + x1**2))))**2 + _a7_*x1
<lambdifygenerated-12862>:2: RuntimeWarning: overflow encountered in exp
  return _a2_ + _a3_**2*_a6_**(2*x1)*(_a4_ + (_a0_ + _a1_ - _a7_ + x1)*sin(_a1_*exp(-_a1_*_a4_*_a5_/(_a4_ + x1**2))))**2 + _a7_*x1
<lambdifygenerated-12862>:2: RuntimeWarning: invalid value encountered in sin
  return _a2_ + _a3_**2*_a6_**(2*x1)*(_a4_ + (_a0_ + _a1_ - _a7_ + x1)*sin(_a1_*exp(-_a1_*_a4_*_a5_/(_a4_ + x1**2))))**2 + _a7_*x1
<lambdifygenerated-12863>:2: RuntimeWarning: overflow encountered in exp
  return _a2_ + _a3_**2*_a6_**(2*x1)*(_a4_ + (_a0_ + _a1_ - _a7_ + x1)*sin(_a1_*exp(-_a1_*_a4_*_a5_/(_a4_ + x1**2))))**2 + _a7_*x1
<lambdifygenerated-12863>:2: RuntimeWarning: invalid value encountered in sin
  return _a2_ + _a3_**2*_a6_**(2*x1)*(_a4_ + (_a0_ + _a1_ - _a7_ + x1)*sin(_a1_*exp(-_a1_*_a4_*_a5_/(_a4_ + x1**2))))**2 + _a7_*x1
<lambdifygenerated-12864>:2: RuntimeWarning: overflow encountered in exp
  return _a2_ + _a3_**2*_a6_**(2*x1)*(_a4_ + (_a0_ + _a1_ - _a7_ + x1)*sin(_a1_*exp(-_a1_*_a4_*_a5_/(_a4_ + x1**2))))**2 + _a7_*x1
<lambdifygenerated-12864>:2: RuntimeWarning: invalid value encountered in sin
  return _a2_ + _a3_**2*_a6_**(2*x1)*(_a4_ + (_a0_ + _a1_ - _a7_ + x1)*sin(_a1_*exp(-_a1_*_a4_*_a5_/(_a4_ + x1**2))))**2 + _a7_*x1

         x1         y  rep    ymodel      ybms
3745  0.997  0.261188  8.0  0.261484  0.265149
3746  0.998  0.261362  8.0  0.261718  0.265472
3747  0.998  0.261535  8.0  0.261952  0.265795
3748  0.999  0.261709  8.0  0.262186  0.266119

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.262056  8.0  0.262652  0.266768
3751  1.002  0.262229  8.0  0.262885  0.267093
3752  1.002  0.262402  8.0  0.263118  0.267419
3753  1.003  0.262576  8.0  0.263351  0.267745

3750

<lambdifygenerated-12889>:2: RuntimeWarning: invalid value encountered in sqrt
  return x1*(x1*sin(x1*(x1 + exp(2*x1 + sin(sqrt(x1))))) + x1)
<lambdifygenerated-12890>:2: RuntimeWarning: invalid value encountered in sqrt
  return x1*(x1*sin(x1*(x1 + exp(2*x1 + sin(sqrt(x1))))) + x1)
<lambdifygenerated-12899>:2: RuntimeWarning: overflow encountered in exp
  return x1*(x1*sin(x1*(x1 + exp(2*x1 + sin(sqrt(exp(x1 + sinh(1)/x1)))))) + x1)
<lambdifygenerated-12899>:2: RuntimeWarning: invalid value encountered in sin
  return x1*(x1*sin(x1*(x1 + exp(2*x1 + sin(sqrt(exp(x1 + sinh(1)/x1)))))) + x1)
<lambdifygenerated-12900>:2: RuntimeWarning: overflow encountered in exp
  return x1*(x1*sin(x1*(x1 + exp(2*x1 + sin(sqrt(exp(x1 + sinh(1)/x1)))))) + x1)
<lambdifygenerated-12900>:2: RuntimeWarning: invalid value encountered in sin
  return x1*(x1*sin(x1*(x1 + exp(2*x1 + sin(sqrt(exp(x1 + sinh(1)/x1)))))) + x1)
<lambdifygenerated-12901>:2: RuntimeWarning: overflow encountered in sinh
  return x1*(x1*sin(x1*(x1 + exp(2*x1 + sin(sqrt(exp(x1 + sinh(x1**(-1.0))/x1)))))) + x1)
<lambdifygenerated-12901>:2: RuntimeWarning: overflow encountered in exp
  return x1*(x1*sin(x1*(x1 + exp(2*x1 + sin(sqrt(exp(x1 + sinh(x1**(-1.0))/x1)))))) + x1)
<lambdifygenerated-12901>:2: RuntimeWarning: invalid value encountered in sin
  return x1*(x1*sin(x1*(x1 + exp(2*x1 + sin(sqrt(exp(x1 + sinh(x1**(-1.0))/x1)))))) + x1)
<lambdifygenerated-12902>:2: RuntimeWarning: overflow encountered in sinh
  return x1*(x1*sin(x1*(x1 + exp(2*x1 + sin(sqrt(exp(x1 + sinh(x1**(-1.0))/x1)))))) + x1)
<lambdifygenerated-12902>:2: RuntimeWarning: overflow encountered in exp
  return x1*(x1*sin(x1*(x1 + exp(2*x1 + sin(sqrt(exp(x1 + sinh(x1**(-1.0))/x1)))))) + x1)
<lambdifygenerated-12902>:2: RuntimeWarning: invalid value encountered in sin
  return x1*(x1*sin(x1*(x1 + exp(2*x1 + sin(sqrt(exp(x1 + sinh(x1**(-1.0))/x1)))))) + x1)
<lambdifygenerated-12903>:2: RuntimeWarning: overflow encountered in sinh
  return x1*(x1*sin(x1*(x1 + exp(2*x1 + sin(sqrt(exp(x1 + sinh(2/x1)/x1)))))) + x1)
<lambdifygenerated-12903>:2: RuntimeWarning: overflow encountered in exp
  return x1*(x1*sin(x1*(x1 + exp(2*x1 + sin(sqrt(exp(x1 + sinh(2/x1)/x1)))))) + x1)
<lambdifygenerated-12903>:2: RuntimeWarning: invalid value encountered in sin
  return x1*(x1*sin(x1*(x1 + exp(2*x1 + sin(sqrt(exp(x1 + sinh(2/x1)/x1)))))) + x1)
<lambdifygenerated-12904>:2: RuntimeWarning: overflow encountered in sinh
  return x1*(x1*sin(x1*(x1 + exp(2*x1 + sin(sqrt(exp(x1 + sinh(2/x1)/x1)))))) + x1)
<lambdifygenerated-12904>:2: RuntimeWarning: overflow encountered in exp
  return x1*(x1*sin(x1*(x1 + exp(2*x1 + sin(sqrt(exp(x1 + sinh(2/x1)/x1)))))) + x1)
<lambdifygenerated-12904>:2: RuntimeWarning: invalid value encountered in sin
  return x1*(x1*sin(x1*(x1 + exp(2*x1 + sin(sqrt(exp(x1 + sinh(2/x1)/x1)))))) + x1)
<lambdifygenerated-12905>:2: RuntimeWarning: overflow encountered in sinh
  return x1*(x1*sin(x1*(x1 + exp(2*x1 + sin(sqrt(exp(x1 + sinh((_a2_ + x1)/x1**2)/x1)))))) + x1)
<lambdifygenerated-12905>:2: RuntimeWarning: overflow encountered in exp
  return x1*(x1*sin(x1*(x1 + exp(2*x1 + sin(sqrt(exp(x1 + sinh((_a2_ + x1)/x1**2)/x1)))))) + x1)
<lambdifygenerated-12905>:2: RuntimeWarning: invalid value encountered in sin
  return x1*(x1*sin(x1*(x1 + exp(2*x1 + sin(sqrt(exp(x1 + sinh((_a2_ + x1)/x1**2)/x1)))))) + x1)
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-12906>:2: RuntimeWarning: overflow encountered in sinh
  return x1*(x1*sin(x1*(x1 + exp(2*x1 + sin(sqrt(exp(x1 + sinh((_a2_ + x1)/x1**2)/x1)))))) + x1)
<lambdifygenerated-12906>:2: RuntimeWarning: overflow encountered in exp
  return x1*(x1*sin(x1*(x1 + exp(2*x1 + sin(sqrt(exp(x1 + sinh((_a2_ + x1)/x1**2)/x1)))))) + x1)
<lambdifygenerated-12906>:2: RuntimeWarning: invalid value encountered in sin
  return x1*(x1*sin(x1*(x1 + exp(2*x1 + sin(sqrt(exp(x1 + sinh((_a2_ + x1)/x1**2)/x1)))))) + x1)
<lambdifygenerated-12907>:2: RuntimeWarning: overflow encountered in sinh
  return x1*(x1*sin(x1*(x1 + exp(2*x1 + sin(sqrt(exp(x1 + sinh((_a2_ + 2*x1)/x1**2)/x1)))))) + x1)
<lambdifygenerated-12907>:2: RuntimeWarning: overflow encountered in exp
  return x1*(x1*sin(x1*(x1 + exp(2*x1 + sin(sqrt(exp(x1 + sinh((_a2_ + 2*x1)/x1**2)/x1)))))) + x1)
<lambdifygenerated-12907>:2: RuntimeWarning: invalid value encountered in sin
  return x1*(x1*sin(x1*(x1 + exp(2*x1 + sin(sqrt(exp(x1 + sinh((_a2_ + 2*x1)/x1**2)/x1)))))) + x1)
<lambdifygenerated-12908>:2: RuntimeWarning: overflow encountered in sinh
  return x1*(x1*sin(x1*(x1 + exp(2*x1 + sin(sqrt(exp(x1 + sinh((_a2_ + 2*x1)/x1**2)/x1)))))) + x1)
<lambdifygenerated-12908>:2: RuntimeWarning: overflow encountered in exp
  return x1*(x1*sin(x1*(x1 + exp(2*x1 + sin(sqrt(exp(x1 + sinh((_a2_ + 2*x1)/x1**2)/x1)))))) + x1)
<lambdifygenerated-12908>:2: RuntimeWarning: invalid value encountered in sin
  return x1*(x1*sin(x1*(x1 + exp(2*x1 + sin(sqrt(exp(x1 + sinh((_a2_ + 2*x1)/x1**2)/x1)))))) + x1)
<lambdifygenerated-12909>:2: RuntimeWarning: overflow encountered in sinh
  return x1*(x1*sin(x1*(x1 + exp(2*x1 + sin(sqrt(exp(x1 + sinh((_a2_ + _a7_ + x1)/x1**2)/x1)))))) + x1)
<lambdifygenerated-12909>:2: RuntimeWarning: overflow encountered in exp
  return x1*(x1*sin(x1*(x1 + exp(2*x1 + sin(sqrt(exp(x1 + sinh((_a2_ + _a7_ + x1)/x1**2)/x1)))))) + x1)
<lambdifygenerated-12909>:2: RuntimeWarning: invalid value encountered in sin
  return x1*(x1*sin(x1*(x1 + exp(2*x1 + sin(sqrt(exp(x1 + sinh((_a2_ + _a7_ + x1)/x1**2)/x1)))))) + x1)
<lambdifygenerated-12910>:2: RuntimeWarning: overflow encountered in sinh
  return x1*(x1*sin(x1*(x1 + exp(2*x1 + sin(sqrt(exp(x1 + sinh((_a2_ + _a7_ + x1)/x1**2)/x1)))))) + x1)
<lambdifygenerated-12910>:2: RuntimeWarning: overflow encountered in exp
  return x1*(x1*sin(x1*(x1 + exp(2*x1 + sin(sqrt(exp(x1 + sinh((_a2_ + _a7_ + x1)/x1**2)/x1)))))) + x1)
<lambdifygenerated-12910>:2: RuntimeWarning: invalid value encountered in sin
  return x1*(x1*sin(x1*(x1 + exp(2*x1 + sin(sqrt(exp(x1 + sinh((_a2_ + _a7_ + x1)/x1**2)/x1)))))) + x1)
<lambdifygenerated-12911>:2: RuntimeWarning: overflow encountered in sinh
  return x1*(x1*sin(x1*(x1 + exp(2*x1 + sin(sqrt(exp(x1 + sinh((_a2_ + _a7_ + x1)/x1**2)/x1)))))) + x1)
<lambdifygenerated-12911>:2: RuntimeWarning: overflow encountered in exp
  return x1*(x1*sin(x1*(x1 + exp(2*x1 + sin(sqrt(exp(x1 + sinh((_a2_ + _a7_ + x1)/x1**2)/x1)))))) + x1)
<lambdifygenerated-12911>:2: RuntimeWarning: invalid value encountered in sin
  return x1*(x1*sin(x1*(x1 + exp(2*x1 + sin(sqrt(exp(x1 + sinh((_a2_ + _a7_ + x1)/x1**2)/x1)))))) + x1)
<lambdifygenerated-12912>:2: RuntimeWarning: overflow encountered in sinh
  return x1*(x1*sin(x1*(x1 + exp(2*x1 + sin(sqrt(exp(x1 + sinh((_a2_ + _a7_ + x1)/x1**2)/x1)))))) + x1)
<lambdifygenerated-12912>:2: RuntimeWarning: overflow encountered in exp
  return x1*(x1*sin(x1*(x1 + exp(2*x1 + sin(sqrt(exp(x1 + sinh((_a2_ + _a7_ + x1)/x1**2)/x1)))))) + x1)
<lambdifygenerated-12912>:2: RuntimeWarning: invalid value encountered in sin
  return x1*(x1*sin(x1*(x1 + exp(2*x1 + sin(sqrt(exp(x1 + sinh((_a2_ + _a7_ + x1)/x1**2)/x1)))))) + x1)
<lambdifygenerated-12913>:2: RuntimeWarning: overflow encountered in sinh
  return x1*(x1*sin(x1*(x1 + exp(2*x1 + sin(sqrt(exp(x1 + sinh((_a2_ + _a7_ + x1)/(_a3_*x1))/x1)))))) + x1)
<lambdifygenerated-12913>:2: RuntimeWarning: overflow encountered in exp
  return x1*(x1*sin(x1*(x1 + exp(2*x1 + sin(sqrt(exp(x1 + sinh((_a2_ + _a7_ + x1)/(_a3_*x1))/x1)))))) + x1)
<lambdifygenerated-12913>:2: RuntimeWarning: invalid value encountered in sin
  return x1*(x1*sin(x1*(x1 + exp(2*x1 + sin(sqrt(exp(x1 + sinh((_a2_ + _a7_ + x1)/(_a3_*x1))/x1)))))) + x1)
<lambdifygenerated-12914>:2: RuntimeWarning: overflow encountered in sinh
  return x1*(x1*sin(x1*(x1 + exp(2*x1 + sin(sqrt(exp(x1 + sinh((_a2_ + _a7_ + x1)/(_a3_*x1))/x1)))))) + x1)
<lambdifygenerated-12914>:2: RuntimeWarning: overflow encountered in exp
  return x1*(x1*sin(x1*(x1 + exp(2*x1 + sin(sqrt(exp(x1 + sinh((_a2_ + _a7_ + x1)/(_a3_*x1))/x1)))))) + x1)
<lambdifygenerated-12914>:2: RuntimeWarning: invalid value encountered in sin
  return x1*(x1*sin(x1*(x1 + exp(2*x1 + sin(sqrt(exp(x1 + sinh((_a2_ + _a7_ + x1)/(_a3_*x1))/x1)))))) + x1)
<lambdifygenerated-12915>:2: RuntimeWarning: overflow encountered in exp
  return x1*(x1*sin(x1*(x1 + exp(2*x1 + sin(sqrt(exp(x1 + sinh((_a2_ + _a7_ + x1)/(_a3_*_a7_))/x1)))))) + x1)
<lambdifygenerated-12915>:2: RuntimeWarning: invalid value encountered in sin
  return x1*(x1*sin(x1*(x1 + exp(2*x1 + sin(sqrt(exp(x1 + sinh((_a2_ + _a7_ + x1)/(_a3_*_a7_))/x1)))))) + x1)
<lambdifygenerated-12916>:2: RuntimeWarning: overflow encountered in exp
  return x1*(x1*sin(x1*(x1 + exp(2*x1 + sin(sqrt(exp(x1 + sinh((_a2_ + _a7_ + x1)/(_a3_*_a7_))/x1)))))) + x1)
<lambdifygenerated-12916>:2: RuntimeWarning: invalid value encountered in sin
  return x1*(x1*sin(x1*(x1 + exp(2*x1 + sin(sqrt(exp(x1 + sinh((_a2_ + _a7_ + x1)/(_a3_*_a7_))/x1)))))) + x1)
<lambdifygenerated-12917>:2: RuntimeWarning: overflow encountered in exp
  return x1*(x1*sin(x1*(x1 + exp(2*x1 + sin(sqrt(exp(x1 - sinh((_a2_ + _a7_ + x1)/(_a3_*_a7_))/x1)))))) + x1)
<lambdifygenerated-12917>:2: RuntimeWarning: invalid value encountered in sin
  return x1*(x1*sin(x1*(x1 + exp(2*x1 + sin(sqrt(exp(x1 - sinh((_a2_ + _a7_ + x1)/(_a3_*_a7_))/x1)))))) + x1)
<lambdifygenerated-12918>:2: RuntimeWarning: overflow encountered in exp
  return x1*(x1*sin(x1*(x1 + exp(2*x1 + sin(sqrt(exp(x1 - sinh((_a2_ + _a7_ + x1)/(_a3_*_a7_))/x1)))))) + x1)
<lambdifygenerated-12918>:2: RuntimeWarning: invalid value encountered in sin
  return x1*(x1*sin(x1*(x1 + exp(2*x1 + sin(sqrt(exp(x1 - sinh((_a2_ + _a7_ + x1)/(_a3_*_a7_))/x1)))))) + x1)
<lambdifygenerated-12919>:2: RuntimeWarning: overflow encountered in exp
  return x1*(x1*sin(x1*(x1 + exp(2*x1 + sin(sqrt(exp(x1 - 1/2*sinh((_a2_ + _a7_ + x1)/(_a3_*_a7_))/x1)))))) + x1)
<lambdifygenerated-12919>:2: RuntimeWarning: invalid value encountered in sin
  return x1*(x1*sin(x1*(x1 + exp(2*x1 + sin(sqrt(exp(x1 - 1/2*sinh((_a2_ + _a7_ + x1)/(_a3_*_a7_))/x1)))))) + x1)
<lambdifygenerated-12920>:2: RuntimeWarning: overflow encountered in exp
  return x1*(x1*sin(x1*(x1 + exp(2*x1 + sin(sqrt(exp(x1 - 1/2*sinh((_a2_ + _a7_ + x1)/(_a3_*_a7_))/x1)))))) + x1)
<lambdifygenerated-12920>:2: RuntimeWarning: invalid value encountered in sin
  return x1*(x1*sin(x1*(x1 + exp(2*x1 + sin(sqrt(exp(x1 - 1/2*sinh((_a2_ + _a7_ + x1)/(_a3_*_a7_))/x1)))))) + x1)
<lambdifygenerated-12921>:2: RuntimeWarning: overflow encountered in exp
  return x1*(x1*sin(x1*(x1 + exp(2*x1 + sin(sqrt(exp(x1 + sinh((_a2_ + _a7_ + x1)/(_a3_*_a7_))/(-_a4_ - x1))))))) + x1)
<lambdifygenerated-12921>:2: RuntimeWarning: invalid value encountered in sin
  return x1*(x1*sin(x1*(x1 + exp(2*x1 + sin(sqrt(exp(x1 + sinh((_a2_ + _a7_ + x1)/(_a3_*_a7_))/(-_a4_ - x1))))))) + x1)
<lambdifygenerated-12922>:2: RuntimeWarning: overflow encountered in exp
  return x1*(x1*sin(x1*(x1 + exp(2*x1 + sin(sqrt(exp(x1 + sinh((_a2_ + _a7_ + x1)/(_a3_*_a7_))/(-_a4_ - x1))))))) + x1)
<lambdifygenerated-12922>:2: RuntimeWarning: invalid value encountered in sin
  return x1*(x1*sin(x1*(x1 + exp(2*x1 + sin(sqrt(exp(x1 + sinh((_a2_ + _a7_ + x1)/(_a3_*_a7_))/(-_a4_ - x1))))))) + x1)

interpolation

<lambdifygenerated-12929>:2: RuntimeWarning: overflow encountered in exp
  return x1*(x1*sin(x1*(x1 + exp(2*x1 + sin(sqrt(exp(_a4_ + x1 + sinh((_a2_ + _a7_ + x1)/(_a3_*_a7_))/(-_a4_ - _a6_))))))) + x1)
<lambdifygenerated-12929>:2: RuntimeWarning: invalid value encountered in sin
  return x1*(x1*sin(x1*(x1 + exp(2*x1 + sin(sqrt(exp(_a4_ + x1 + sinh((_a2_ + _a7_ + x1)/(_a3_*_a7_))/(-_a4_ - _a6_))))))) + x1)
<lambdifygenerated-12930>:2: RuntimeWarning: overflow encountered in exp
  return x1*(x1*sin(x1*(x1 + exp(2*x1 + sin(sqrt(exp(_a4_ + x1 + sinh((_a2_ + _a7_ + x1)/(_a3_*_a7_))/(-_a4_ - _a6_))))))) + x1)
<lambdifygenerated-12930>:2: RuntimeWarning: invalid value encountered in sin
  return x1*(x1*sin(x1*(x1 + exp(2*x1 + sin(sqrt(exp(_a4_ + x1 + sinh((_a2_ + _a7_ + x1)/(_a3_*_a7_))/(-_a4_ - _a6_))))))) + x1)
<lambdifygenerated-12931>:2: RuntimeWarning: overflow encountered in exp
  return x1*(x1*sin(x1*(x1 + exp(_a5_ + x1 + sin(sqrt(exp(_a4_ + x1 + sinh((_a2_ + _a7_ + x1)/(_a3_*_a7_))/(-_a4_ - _a6_))))))) + x1)
<lambdifygenerated-12931>:2: RuntimeWarning: invalid value encountered in sin
  return x1*(x1*sin(x1*(x1 + exp(_a5_ + x1 + sin(sqrt(exp(_a4_ + x1 + sinh((_a2_ + _a7_ + x1)/(_a3_*_a7_))/(-_a4_ - _a6_))))))) + x1)
<lambdifygenerated-12932>:2: RuntimeWarning: overflow encountered in exp
  return x1*(x1*sin(x1*(x1 + exp(_a5_ + x1 + sin(sqrt(exp(_a4_ + x1 + sinh((_a2_ + _a7_ + x1)/(_a3_*_a7_))/(-_a4_ - _a6_))))))) + x1)
<lambdifygenerated-12932>:2: RuntimeWarning: invalid value encountered in sin
  return x1*(x1*sin(x1*(x1 + exp(_a5_ + x1 + sin(sqrt(exp(_a4_ + x1 + sinh((_a2_ + _a7_ + x1)/(_a3_*_a7_))/(-_a4_ - _a6_))))))) + x1)
<lambdifygenerated-12933>:2: RuntimeWarning: overflow encountered in exp
  return x1*(x1*sin(x1*(x1 + exp(_a5_ + x1**2 + sin(sqrt(exp(_a4_ + x1 + sinh((_a2_ + _a7_ + x1)/(_a3_*_a7_))/(-_a4_ - _a6_))))))) + x1)
<lambdifygenerated-12933>:2: RuntimeWarning: invalid value encountered in sin
  return x1*(x1*sin(x1*(x1 + exp(_a5_ + x1**2 + sin(sqrt(exp(_a4_ + x1 + sinh((_a2_ + _a7_ + x1)/(_a3_*_a7_))/(-_a4_ - _a6_))))))) + x1)
<lambdifygenerated-12934>:2: RuntimeWarning: overflow encountered in exp
  return x1*(x1*sin(x1*(x1 + exp(_a5_ + x1**2 + sin(sqrt(exp(_a4_ + x1 + sinh((_a2_ + _a7_ + x1)/(_a3_*_a7_))/(-_a4_ - _a6_))))))) + x1)
<lambdifygenerated-12934>:2: RuntimeWarning: invalid value encountered in sin
  return x1*(x1*sin(x1*(x1 + exp(_a5_ + x1**2 + sin(sqrt(exp(_a4_ + x1 + sinh((_a2_ + _a7_ + x1)/(_a3_*_a7_))/(-_a4_ - _a6_))))))) + x1)
<lambdifygenerated-12935>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1*sin(x1*(x1 + exp(_a5_ + x1*x1**x1 + sin(sqrt(exp(_a4_ + x1 + sinh((_a2_ + _a7_ + x1)/(_a3_*_a7_))/(-_a4_ - _a6_))))))) + x1)
<lambdifygenerated-12935>:2: RuntimeWarning: overflow encountered in exp
  return x1*(x1*sin(x1*(x1 + exp(_a5_ + x1*x1**x1 + sin(sqrt(exp(_a4_ + x1 + sinh((_a2_ + _a7_ + x1)/(_a3_*_a7_))/(-_a4_ - _a6_))))))) + x1)
<lambdifygenerated-12935>:2: RuntimeWarning: invalid value encountered in sin
  return x1*(x1*sin(x1*(x1 + exp(_a5_ + x1*x1**x1 + sin(sqrt(exp(_a4_ + x1 + sinh((_a2_ + _a7_ + x1)/(_a3_*_a7_))/(-_a4_ - _a6_))))))) + x1)
<lambdifygenerated-12936>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1*sin(x1*(x1 + exp(_a5_ + x1*x1**x1 + sin(sqrt(exp(_a4_ + x1 + sinh((_a2_ + _a7_ + x1)/(_a3_*_a7_))/(-_a4_ - _a6_))))))) + x1)
<lambdifygenerated-12936>:2: RuntimeWarning: overflow encountered in exp
  return x1*(x1*sin(x1*(x1 + exp(_a5_ + x1*x1**x1 + sin(sqrt(exp(_a4_ + x1 + sinh((_a2_ + _a7_ + x1)/(_a3_*_a7_))/(-_a4_ - _a6_))))))) + x1)
<lambdifygenerated-12936>:2: RuntimeWarning: invalid value encountered in sin
  return x1*(x1*sin(x1*(x1 + exp(_a5_ + x1*x1**x1 + sin(sqrt(exp(_a4_ + x1 + sinh((_a2_ + _a7_ + x1)/(_a3_*_a7_))/(-_a4_ - _a6_))))))) + x1)
<lambdifygenerated-12937>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1*sin(x1*(x1 + exp(_a3_**x1*x1 + _a5_ + sin(sqrt(exp(_a4_ + x1 + sinh((_a2_ + _a7_ + x1)/(_a3_*_a7_))/(-_a4_ - _a6_))))))) + x1)
<lambdifygenerated-12937>:2: RuntimeWarning: overflow encountered in exp
  return x1*(x1*sin(x1*(x1 + exp(_a3_**x1*x1 + _a5_ + sin(sqrt(exp(_a4_ + x1 + sinh((_a2_ + _a7_ + x1)/(_a3_*_a7_))/(-_a4_ - _a6_))))))) + x1)
<lambdifygenerated-12937>:2: RuntimeWarning: invalid value encountered in sin
  return x1*(x1*sin(x1*(x1 + exp(_a3_**x1*x1 + _a5_ + sin(sqrt(exp(_a4_ + x1 + sinh((_a2_ + _a7_ + x1)/(_a3_*_a7_))/(-_a4_ - _a6_))))))) + x1)
<lambdifygenerated-12938>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1*sin(x1*(x1 + exp(_a3_**x1*x1 + _a5_ + sin(sqrt(exp(_a4_ + x1 + sinh((_a2_ + _a7_ + x1)/(_a3_*_a7_))/(-_a4_ - _a6_))))))) + x1)
<lambdifygenerated-12938>:2: RuntimeWarning: overflow encountered in exp
  return x1*(x1*sin(x1*(x1 + exp(_a3_**x1*x1 + _a5_ + sin(sqrt(exp(_a4_ + x1 + sinh((_a2_ + _a7_ + x1)/(_a3_*_a7_))/(-_a4_ - _a6_))))))) + x1)
<lambdifygenerated-12938>:2: RuntimeWarning: invalid value encountered in sin
  return x1*(x1*sin(x1*(x1 + exp(_a3_**x1*x1 + _a5_ + sin(sqrt(exp(_a4_ + x1 + sinh((_a2_ + _a7_ + x1)/(_a3_*_a7_))/(-_a4_ - _a6_))))))) + x1)
<lambdifygenerated-12939>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1*sin(x1*(x1 + exp(_a3_**abs(x1)*x1 + _a5_ + sin(sqrt(exp(_a4_ + x1 + sinh((_a2_ + _a7_ + x1)/(_a3_*_a7_))/(-_a4_ - _a6_))))))) + x1)
<lambdifygenerated-12939>:2: RuntimeWarning: overflow encountered in exp
  return x1*(x1*sin(x1*(x1 + exp(_a3_**abs(x1)*x1 + _a5_ + sin(sqrt(exp(_a4_ + x1 + sinh((_a2_ + _a7_ + x1)/(_a3_*_a7_))/(-_a4_ - _a6_))))))) + x1)
<lambdifygenerated-12939>:2: RuntimeWarning: invalid value encountered in sin
  return x1*(x1*sin(x1*(x1 + exp(_a3_**abs(x1)*x1 + _a5_ + sin(sqrt(exp(_a4_ + x1 + sinh((_a2_ + _a7_ + x1)/(_a3_*_a7_))/(-_a4_ - _a6_))))))) + x1)
<lambdifygenerated-12940>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1*sin(x1*(x1 + exp(_a3_**abs(x1)*x1 + _a5_ + sin(sqrt(exp(_a4_ + x1 + sinh((_a2_ + _a7_ + x1)/(_a3_*_a7_))/(-_a4_ - _a6_))))))) + x1)
<lambdifygenerated-12940>:2: RuntimeWarning: overflow encountered in exp
  return x1*(x1*sin(x1*(x1 + exp(_a3_**abs(x1)*x1 + _a5_ + sin(sqrt(exp(_a4_ + x1 + sinh((_a2_ + _a7_ + x1)/(_a3_*_a7_))/(-_a4_ - _a6_))))))) + x1)
<lambdifygenerated-12940>:2: RuntimeWarning: invalid value encountered in sin
  return x1*(x1*sin(x1*(x1 + exp(_a3_**abs(x1)*x1 + _a5_ + sin(sqrt(exp(_a4_ + x1 + sinh((_a2_ + _a7_ + x1)/(_a3_*_a7_))/(-_a4_ - _a6_))))))) + x1)
<lambdifygenerated-12941>:2: RuntimeWarning: overflow encountered in exp
  return x1*(x1*sin(x1*(x1 + exp(_a3_*x1 + _a5_ + sin(sqrt(exp(_a4_ + x1 + sinh((_a2_ + _a7_ + x1)/(_a3_*_a7_))/(-_a4_ - _a6_))))))) + x1)
<lambdifygenerated-12941>:2: RuntimeWarning: invalid value encountered in sin
  return x1*(x1*sin(x1*(x1 + exp(_a3_*x1 + _a5_ + sin(sqrt(exp(_a4_ + x1 + sinh((_a2_ + _a7_ + x1)/(_a3_*_a7_))/(-_a4_ - _a6_))))))) + x1)
<lambdifygenerated-12942>:2: RuntimeWarning: overflow encountered in exp
  return x1*(x1*sin(x1*(x1 + exp(_a3_*x1 + _a5_ + sin(sqrt(exp(_a4_ + x1 + sinh((_a2_ + _a7_ + x1)/(_a3_*_a7_))/(-_a4_ - _a6_))))))) + x1)
<lambdifygenerated-12942>:2: RuntimeWarning: invalid value encountered in sin
  return x1*(x1*sin(x1*(x1 + exp(_a3_*x1 + _a5_ + sin(sqrt(exp(_a4_ + x1 + sinh((_a2_ + _a7_ + x1)/(_a3_*_a7_))/(-_a4_ - _a6_))))))) + x1)
<lambdifygenerated-12943>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1*sin(x1*(x1 + exp(_a3_**abs(_a1_/x1)*x1 + _a5_ + sin(sqrt(exp(_a4_ + x1 + sinh((_a2_ + _a7_ + x1)/(_a3_*_a7_))/(-_a4_ - _a6_))))))) + x1)
<lambdifygenerated-12943>:2: RuntimeWarning: overflow encountered in exp
  return x1*(x1*sin(x1*(x1 + exp(_a3_**abs(_a1_/x1)*x1 + _a5_ + sin(sqrt(exp(_a4_ + x1 + sinh((_a2_ + _a7_ + x1)/(_a3_*_a7_))/(-_a4_ - _a6_))))))) + x1)
<lambdifygenerated-12943>:2: RuntimeWarning: invalid value encountered in sin
  return x1*(x1*sin(x1*(x1 + exp(_a3_**abs(_a1_/x1)*x1 + _a5_ + sin(sqrt(exp(_a4_ + x1 + sinh((_a2_ + _a7_ + x1)/(_a3_*_a7_))/(-_a4_ - _a6_))))))) + x1)
<lambdifygenerated-12944>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1*sin(x1*(x1 + exp(_a3_**abs(_a1_/x1)*x1 + _a5_ + sin(sqrt(exp(_a4_ + x1 + sinh((_a2_ + _a7_ + x1)/(_a3_*_a7_))/(-_a4_ - _a6_))))))) + x1)
<lambdifygenerated-12944>:2: RuntimeWarning: overflow encountered in exp
  return x1*(x1*sin(x1*(x1 + exp(_a3_**abs(_a1_/x1)*x1 + _a5_ + sin(sqrt(exp(_a4_ + x1 + sinh((_a2_ + _a7_ + x1)/(_a3_*_a7_))/(-_a4_ - _a6_))))))) + x1)
<lambdifygenerated-12944>:2: RuntimeWarning: invalid value encountered in sin
  return x1*(x1*sin(x1*(x1 + exp(_a3_**abs(_a1_/x1)*x1 + _a5_ + sin(sqrt(exp(_a4_ + x1 + sinh((_a2_ + _a7_ + x1)/(_a3_*_a7_))/(-_a4_ - _a6_))))))) + x1)
<lambdifygenerated-12945>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1*sin(x1*(x1 + exp(_a3_**abs(_a1_/x1)*x1 + _a5_ + sin(sqrt(exp(_a4_ + x1 + sinh((_a2_ + _a7_ + x1)/(_a3_*_a7_))/(-_a4_ - _a6_))))))) + x1)
<lambdifygenerated-12945>:2: RuntimeWarning: overflow encountered in exp
  return x1*(x1*sin(x1*(x1 + exp(_a3_**abs(_a1_/x1)*x1 + _a5_ + sin(sqrt(exp(_a4_ + x1 + sinh((_a2_ + _a7_ + x1)/(_a3_*_a7_))/(-_a4_ - _a6_))))))) + x1)
<lambdifygenerated-12945>:2: RuntimeWarning: invalid value encountered in sin
  return x1*(x1*sin(x1*(x1 + exp(_a3_**abs(_a1_/x1)*x1 + _a5_ + sin(sqrt(exp(_a4_ + x1 + sinh((_a2_ + _a7_ + x1)/(_a3_*_a7_))/(-_a4_ - _a6_))))))) + x1)
<lambdifygenerated-12946>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1*sin(x1*(x1 + exp(_a3_**abs(_a1_/x1)*x1 + _a5_ + sin(sqrt(exp(_a4_ + x1 + sinh((_a2_ + _a7_ + x1)/(_a3_*_a7_))/(-_a4_ - _a6_))))))) + x1)
<lambdifygenerated-12946>:2: RuntimeWarning: overflow encountered in exp
  return x1*(x1*sin(x1*(x1 + exp(_a3_**abs(_a1_/x1)*x1 + _a5_ + sin(sqrt(exp(_a4_ + x1 + sinh((_a2_ + _a7_ + x1)/(_a3_*_a7_))/(-_a4_ - _a6_))))))) + x1)
<lambdifygenerated-12946>:2: RuntimeWarning: invalid value encountered in sin
  return x1*(x1*sin(x1*(x1 + exp(_a3_**abs(_a1_/x1)*x1 + _a5_ + sin(sqrt(exp(_a4_ + x1 + sinh((_a2_ + _a7_ + x1)/(_a3_*_a7_))/(-_a4_ - _a6_))))))) + x1)
<lambdifygenerated-12947>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1*sin(x1*(x1 + exp(_a0_*_a3_**abs(_a1_/x1) + _a5_ + sin(sqrt(exp(_a4_ + x1 + sinh((_a2_ + _a7_ + x1)/(_a3_*_a7_))/(-_a4_ - _a6_))))))) + x1)
<lambdifygenerated-12947>:2: RuntimeWarning: overflow encountered in exp
  return x1*(x1*sin(x1*(x1 + exp(_a0_*_a3_**abs(_a1_/x1) + _a5_ + sin(sqrt(exp(_a4_ + x1 + sinh((_a2_ + _a7_ + x1)/(_a3_*_a7_))/(-_a4_ - _a6_))))))) + x1)
<lambdifygenerated-12947>:2: RuntimeWarning: invalid value encountered in sin
  return x1*(x1*sin(x1*(x1 + exp(_a0_*_a3_**abs(_a1_/x1) + _a5_ + sin(sqrt(exp(_a4_ + x1 + sinh((_a2_ + _a7_ + x1)/(_a3_*_a7_))/(-_a4_ - _a6_))))))) + x1)
<lambdifygenerated-12948>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1*sin(x1*(x1 + exp(_a0_*_a3_**abs(_a1_/x1) + _a5_ + sin(sqrt(exp(_a4_ + x1 + sinh((_a2_ + _a7_ + x1)/(_a3_*_a7_))/(-_a4_ - _a6_))))))) + x1)
<lambdifygenerated-12948>:2: RuntimeWarning: overflow encountered in exp
  return x1*(x1*sin(x1*(x1 + exp(_a0_*_a3_**abs(_a1_/x1) + _a5_ + sin(sqrt(exp(_a4_ + x1 + sinh((_a2_ + _a7_ + x1)/(_a3_*_a7_))/(-_a4_ - _a6_))))))) + x1)
<lambdifygenerated-12948>:2: RuntimeWarning: invalid value encountered in sin
  return x1*(x1*sin(x1*(x1 + exp(_a0_*_a3_**abs(_a1_/x1) + _a5_ + sin(sqrt(exp(_a4_ + x1 + sinh((_a2_ + _a7_ + x1)/(_a3_*_a7_))/(-_a4_ - _a6_))))))) + x1)
<lambdifygenerated-12949>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1*sin(x1*(exp(_a0_*_a3_**abs(_a1_/x1) + _a5_ + sin(sqrt(exp(_a4_ + x1 + sinh((_a2_ + _a7_ + x1)/(_a3_*_a7_))/(-_a4_ - _a6_))))) + cos(x1))) + x1)
<lambdifygenerated-12949>:2: RuntimeWarning: overflow encountered in exp
  return x1*(x1*sin(x1*(exp(_a0_*_a3_**abs(_a1_/x1) + _a5_ + sin(sqrt(exp(_a4_ + x1 + sinh((_a2_ + _a7_ + x1)/(_a3_*_a7_))/(-_a4_ - _a6_))))) + cos(x1))) + x1)
<lambdifygenerated-12949>:2: RuntimeWarning: invalid value encountered in sin
  return x1*(x1*sin(x1*(exp(_a0_*_a3_**abs(_a1_/x1) + _a5_ + sin(sqrt(exp(_a4_ + x1 + sinh((_a2_ + _a7_ + x1)/(_a3_*_a7_))/(-_a4_ - _a6_))))) + cos(x1))) + x1)
<lambdifygenerated-12950>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1*sin(x1*(exp(_a0_*_a3_**abs(_a1_/x1) + _a5_ + sin(sqrt(exp(_a4_ + x1 + sinh((_a2_ + _a7_ + x1)/(_a3_*_a7_))/(-_a4_ - _a6_))))) + cos(x1))) + x1)
<lambdifygenerated-12950>:2: RuntimeWarning: overflow encountered in exp
  return x1*(x1*sin(x1*(exp(_a0_*_a3_**abs(_a1_/x1) + _a5_ + sin(sqrt(exp(_a4_ + x1 + sinh((_a2_ + _a7_ + x1)/(_a3_*_a7_))/(-_a4_ - _a6_))))) + cos(x1))) + x1)
<lambdifygenerated-12950>:2: RuntimeWarning: invalid value encountered in sin
  return x1*(x1*sin(x1*(exp(_a0_*_a3_**abs(_a1_/x1) + _a5_ + sin(sqrt(exp(_a4_ + x1 + sinh((_a2_ + _a7_ + x1)/(_a3_*_a7_))/(-_a4_ - _a6_))))) + cos(x1))) + x1)
<lambdifygenerated-12951>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1*sin(x1*(exp(_a0_*_a3_**abs(_a1_/x1) + _a5_ + sin(sqrt(exp(_a4_ + x1 + sinh((_a2_ + _a7_ + x1)/(_a3_*_a7_))/(-_a4_ - _a6_))))) + cos(x1))) + x1)
<lambdifygenerated-12951>:2: RuntimeWarning: overflow encountered in exp
  return x1*(x1*sin(x1*(exp(_a0_*_a3_**abs(_a1_/x1) + _a5_ + sin(sqrt(exp(_a4_ + x1 + sinh((_a2_ + _a7_ + x1)/(_a3_*_a7_))/(-_a4_ - _a6_))))) + cos(x1))) + x1)
<lambdifygenerated-12951>:2: RuntimeWarning: invalid value encountered in sin
  return x1*(x1*sin(x1*(exp(_a0_*_a3_**abs(_a1_/x1) + _a5_ + sin(sqrt(exp(_a4_ + x1 + sinh((_a2_ + _a7_ + x1)/(_a3_*_a7_))/(-_a4_ - _a6_))))) + cos(x1))) + x1)
<lambdifygenerated-12952>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1*sin(x1*(exp(_a0_*_a3_**abs(_a1_/x1) + _a5_ + sin(sqrt(exp(_a4_ + x1 + sinh((_a2_ + _a7_ + x1)/(_a3_*_a7_))/(-_a4_ - _a6_))))) + cos(x1))) + x1)
<lambdifygenerated-12952>:2: RuntimeWarning: overflow encountered in exp
  return x1*(x1*sin(x1*(exp(_a0_*_a3_**abs(_a1_/x1) + _a5_ + sin(sqrt(exp(_a4_ + x1 + sinh((_a2_ + _a7_ + x1)/(_a3_*_a7_))/(-_a4_ - _a6_))))) + cos(x1))) + x1)
<lambdifygenerated-12952>:2: RuntimeWarning: invalid value encountered in sin
  return x1*(x1*sin(x1*(exp(_a0_*_a3_**abs(_a1_/x1) + _a5_ + sin(sqrt(exp(_a4_ + x1 + sinh((_a2_ + _a7_ + x1)/(_a3_*_a7_))/(-_a4_ - _a6_))))) + cos(x1))) + x1)
<lambdifygenerated-12953>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1*sin(_a6_*(exp(_a0_*_a3_**abs(_a1_/x1) + _a5_ + sin(sqrt(exp(_a4_ + x1 + sinh((_a2_ + _a7_ + x1)/(_a3_*_a7_))/(-_a4_ - _a6_))))) + cos(x1))) + x1)
<lambdifygenerated-12953>:2: RuntimeWarning: overflow encountered in exp
  return x1*(x1*sin(_a6_*(exp(_a0_*_a3_**abs(_a1_/x1) + _a5_ + sin(sqrt(exp(_a4_ + x1 + sinh((_a2_ + _a7_ + x1)/(_a3_*_a7_))/(-_a4_ - _a6_))))) + cos(x1))) + x1)
<lambdifygenerated-12953>:2: RuntimeWarning: invalid value encountered in sin
  return x1*(x1*sin(_a6_*(exp(_a0_*_a3_**abs(_a1_/x1) + _a5_ + sin(sqrt(exp(_a4_ + x1 + sinh((_a2_ + _a7_ + x1)/(_a3_*_a7_))/(-_a4_ - _a6_))))) + cos(x1))) + x1)
<lambdifygenerated-12954>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1*sin(_a6_*(exp(_a0_*_a3_**abs(_a1_/x1) + _a5_ + sin(sqrt(exp(_a4_ + x1 + sinh((_a2_ + _a7_ + x1)/(_a3_*_a7_))/(-_a4_ - _a6_))))) + cos(x1))) + x1)
<lambdifygenerated-12954>:2: RuntimeWarning: overflow encountered in exp
  return x1*(x1*sin(_a6_*(exp(_a0_*_a3_**abs(_a1_/x1) + _a5_ + sin(sqrt(exp(_a4_ + x1 + sinh((_a2_ + _a7_ + x1)/(_a3_*_a7_))/(-_a4_ - _a6_))))) + cos(x1))) + x1)
<lambdifygenerated-12954>:2: RuntimeWarning: invalid value encountered in sin
  return x1*(x1*sin(_a6_*(exp(_a0_*_a3_**abs(_a1_/x1) + _a5_ + sin(sqrt(exp(_a4_ + x1 + sinh((_a2_ + _a7_ + x1)/(_a3_*_a7_))/(-_a4_ - _a6_))))) + cos(x1))) + x1)
<lambdifygenerated-12955>:2: RuntimeWarning: invalid value encountered in power
  return x1*(_a7_*sin(_a6_*(exp(_a0_*_a3_**abs(_a1_/x1) + _a5_ + sin(sqrt(exp(_a4_ + x1 + sinh((_a2_ + _a7_ + x1)/(_a3_*_a7_))/(-_a4_ - _a6_))))) + cos(x1))) + x1)
<lambdifygenerated-12955>:2: RuntimeWarning: overflow encountered in exp
  return x1*(_a7_*sin(_a6_*(exp(_a0_*_a3_**abs(_a1_/x1) + _a5_ + sin(sqrt(exp(_a4_ + x1 + sinh((_a2_ + _a7_ + x1)/(_a3_*_a7_))/(-_a4_ - _a6_))))) + cos(x1))) + x1)
<lambdifygenerated-12955>:2: RuntimeWarning: invalid value encountered in sin
  return x1*(_a7_*sin(_a6_*(exp(_a0_*_a3_**abs(_a1_/x1) + _a5_ + sin(sqrt(exp(_a4_ + x1 + sinh((_a2_ + _a7_ + x1)/(_a3_*_a7_))/(-_a4_ - _a6_))))) + cos(x1))) + x1)
<lambdifygenerated-12956>:2: RuntimeWarning: invalid value encountered in power
  return x1*(_a7_*sin(_a6_*(exp(_a0_*_a3_**abs(_a1_/x1) + _a5_ + sin(sqrt(exp(_a4_ + x1 + sinh((_a2_ + _a7_ + x1)/(_a3_*_a7_))/(-_a4_ - _a6_))))) + cos(x1))) + x1)
<lambdifygenerated-12956>:2: RuntimeWarning: overflow encountered in exp
  return x1*(_a7_*sin(_a6_*(exp(_a0_*_a3_**abs(_a1_/x1) + _a5_ + sin(sqrt(exp(_a4_ + x1 + sinh((_a2_ + _a7_ + x1)/(_a3_*_a7_))/(-_a4_ - _a6_))))) + cos(x1))) + x1)
<lambdifygenerated-12956>:2: RuntimeWarning: invalid value encountered in sin
  return x1*(_a7_*sin(_a6_*(exp(_a0_*_a3_**abs(_a1_/x1) + _a5_ + sin(sqrt(exp(_a4_ + x1 + sinh((_a2_ + _a7_ + x1)/(_a3_*_a7_))/(-_a4_ - _a6_))))) + cos(x1))) + x1)
<lambdifygenerated-12957>:2: RuntimeWarning: invalid value encountered in power
  return x1*(_a6_ + _a7_*sin(_a6_*(exp(_a0_*_a3_**abs(_a1_/x1) + _a5_ + sin(sqrt(exp(_a4_ + x1 + sinh((_a2_ + _a7_ + x1)/(_a3_*_a7_))/(-_a4_ - _a6_))))) + cos(x1))))
<lambdifygenerated-12957>:2: RuntimeWarning: overflow encountered in exp
  return x1*(_a6_ + _a7_*sin(_a6_*(exp(_a0_*_a3_**abs(_a1_/x1) + _a5_ + sin(sqrt(exp(_a4_ + x1 + sinh((_a2_ + _a7_ + x1)/(_a3_*_a7_))/(-_a4_ - _a6_))))) + cos(x1))))
<lambdifygenerated-12957>:2: RuntimeWarning: invalid value encountered in sin
  return x1*(_a6_ + _a7_*sin(_a6_*(exp(_a0_*_a3_**abs(_a1_/x1) + _a5_ + sin(sqrt(exp(_a4_ + x1 + sinh((_a2_ + _a7_ + x1)/(_a3_*_a7_))/(-_a4_ - _a6_))))) + cos(x1))))
<lambdifygenerated-12958>:2: RuntimeWarning: invalid value encountered in power
  return x1*(_a6_ + _a7_*sin(_a6_*(exp(_a0_*_a3_**abs(_a1_/x1) + _a5_ + sin(sqrt(exp(_a4_ + x1 + sinh((_a2_ + _a7_ + x1)/(_a3_*_a7_))/(-_a4_ - _a6_))))) + cos(x1))))
<lambdifygenerated-12958>:2: RuntimeWarning: overflow encountered in exp
  return x1*(_a6_ + _a7_*sin(_a6_*(exp(_a0_*_a3_**abs(_a1_/x1) + _a5_ + sin(sqrt(exp(_a4_ + x1 + sinh((_a2_ + _a7_ + x1)/(_a3_*_a7_))/(-_a4_ - _a6_))))) + cos(x1))))
<lambdifygenerated-12958>:2: RuntimeWarning: invalid value encountered in sin
  return x1*(_a6_ + _a7_*sin(_a6_*(exp(_a0_*_a3_**abs(_a1_/x1) + _a5_ + sin(sqrt(exp(_a4_ + x1 + sinh((_a2_ + _a7_ + x1)/(_a3_*_a7_))/(-_a4_ - _a6_))))) + cos(x1))))
<lambdifygenerated-12959>:2: RuntimeWarning: invalid value encountered in power
  return _a0_*(_a6_ + _a7_*sin(_a6_*(exp(_a0_*_a3_**abs(_a1_/x1) + _a5_ + sin(sqrt(exp(_a4_ + x1 + sinh((_a2_ + _a7_ + x1)/(_a3_*_a7_))/(-_a4_ - _a6_))))) + cos(x1))))
<lambdifygenerated-12959>:2: RuntimeWarning: overflow encountered in exp
  return _a0_*(_a6_ + _a7_*sin(_a6_*(exp(_a0_*_a3_**abs(_a1_/x1) + _a5_ + sin(sqrt(exp(_a4_ + x1 + sinh((_a2_ + _a7_ + x1)/(_a3_*_a7_))/(-_a4_ - _a6_))))) + cos(x1))))
<lambdifygenerated-12959>:2: RuntimeWarning: invalid value encountered in sin
  return _a0_*(_a6_ + _a7_*sin(_a6_*(exp(_a0_*_a3_**abs(_a1_/x1) + _a5_ + sin(sqrt(exp(_a4_ + x1 + sinh((_a2_ + _a7_ + x1)/(_a3_*_a7_))/(-_a4_ - _a6_))))) + cos(x1))))
<lambdifygenerated-12960>:2: RuntimeWarning: invalid value encountered in power
  return _a0_*(_a6_ + _a7_*sin(_a6_*(exp(_a0_*_a3_**abs(_a1_/x1) + _a5_ + sin(sqrt(exp(_a4_ + x1 + sinh((_a2_ + _a7_ + x1)/(_a3_*_a7_))/(-_a4_ - _a6_))))) + cos(x1))))
<lambdifygenerated-12960>:2: RuntimeWarning: overflow encountered in exp
  return _a0_*(_a6_ + _a7_*sin(_a6_*(exp(_a0_*_a3_**abs(_a1_/x1) + _a5_ + sin(sqrt(exp(_a4_ + x1 + sinh((_a2_ + _a7_ + x1)/(_a3_*_a7_))/(-_a4_ - _a6_))))) + cos(x1))))
<lambdifygenerated-12960>:2: RuntimeWarning: invalid value encountered in sin

         x1        y  rep    ymodel      ybms
3745  0.997  0.64259  9.0  0.645736  0.639796
3746  0.998  0.64247  9.0  0.645617  0.639613
3747  0.998  0.64235  9.0  0.645498  0.639430
3748  0.999  0.64223  9.0  0.645380  0.639247

extrapolation

         x1        y  rep    ymodel      ybms
3750  1.001  0.64199  9.0  0.645143  0.638880
3751  1.002  0.64187  9.0  0.645025  0.638697
3752  1.002  0.64175  9.0  0.644907  0.638513
3753  1.003  0.64163  9.0  0.644789  0.638329

3750

<lambdifygenerated-12977>:2: RuntimeWarning: invalid value encountered in power
  return abs(x1 + sinh(x1**x1)/x1)
<lambdifygenerated-12978>:2: RuntimeWarning: invalid value encountered in power
  return abs(x1 + sinh(x1**x1)/x1)
<lambdifygenerated-12983>:2: RuntimeWarning: divide by zero encountered in power
  return abs(x1 + sinh(((x1 + abs(x1))**2)**x1)/x1)
<lambdifygenerated-12984>:2: RuntimeWarning: divide by zero encountered in power
  return abs(x1 + sinh(((x1 + abs(x1))**2)**x1)/x1)
<lambdifygenerated-12985>:2: RuntimeWarning: overflow encountered in sinh
  return abs(x1 + sinh(((x1 + abs(x1**2))**2)**x1)/x1)
/usr/local/lib/python3.10/dist-packages/pandas/core/arraylike.py:399: RuntimeWarning: overflow encountered in square
  result = getattr(ufunc, method)(*inputs, **kwargs)
<lambdifygenerated-12986>:2: RuntimeWarning: overflow encountered in sinh
  return abs(x1 + sinh(((x1 + abs(x1**2))**2)**x1)/x1)
<lambdifygenerated-12987>:2: RuntimeWarning: invalid value encountered in power
  return abs(x1 + sinh(((x1 + abs(x1*x1**x1))**2)**x1)/x1)
<lambdifygenerated-12987>:2: RuntimeWarning: overflow encountered in sinh
  return abs(x1 + sinh(((x1 + abs(x1*x1**x1))**2)**x1)/x1)
<lambdifygenerated-12988>:2: RuntimeWarning: invalid value encountered in power
  return abs(x1 + sinh(((x1 + abs(x1*x1**x1))**2)**x1)/x1)
<lambdifygenerated-12988>:2: RuntimeWarning: overflow encountered in sinh
  return abs(x1 + sinh(((x1 + abs(x1*x1**x1))**2)**x1)/x1)
<lambdifygenerated-12989>:2: RuntimeWarning: invalid value encountered in power
  return abs(x1 + sinh(((x1 + abs(x1*(2*x1)**x1))**2)**x1)/x1)
<lambdifygenerated-12989>:2: RuntimeWarning: overflow encountered in sinh
  return abs(x1 + sinh(((x1 + abs(x1*(2*x1)**x1))**2)**x1)/x1)
<lambdifygenerated-12990>:2: RuntimeWarning: invalid value encountered in power
  return abs(x1 + sinh(((x1 + abs(x1*(2*x1)**x1))**2)**x1)/x1)
<lambdifygenerated-12990>:2: RuntimeWarning: overflow encountered in sinh
  return abs(x1 + sinh(((x1 + abs(x1*(2*x1)**x1))**2)**x1)/x1)
<lambdifygenerated-12991>:2: RuntimeWarning: invalid value encountered in power
  return abs(x1 + sinh(((x1 + abs(x1*(x1**2 + x1)**x1))**2)**x1)/x1)
<lambdifygenerated-12991>:2: RuntimeWarning: overflow encountered in sinh
  return abs(x1 + sinh(((x1 + abs(x1*(x1**2 + x1)**x1))**2)**x1)/x1)
<lambdifygenerated-12992>:2: RuntimeWarning: invalid value encountered in power
  return abs(x1 + sinh(((x1 + abs(x1*(x1**2 + x1)**x1))**2)**x1)/x1)
<lambdifygenerated-12992>:2: RuntimeWarning: overflow encountered in sinh
  return abs(x1 + sinh(((x1 + abs(x1*(x1**2 + x1)**x1))**2)**x1)/x1)
<lambdifygenerated-12993>:2: RuntimeWarning: invalid value encountered in power
  return abs(x1 + sinh(((x1 + abs(x1*(x1 + cos(x1)**2)**x1))**2)**x1)/x1)
<lambdifygenerated-12993>:2: RuntimeWarning: divide by zero encountered in power
  return abs(x1 + sinh(((x1 + abs(x1*(x1 + cos(x1)**2)**x1))**2)**x1)/x1)
<lambdifygenerated-12993>:2: RuntimeWarning: overflow encountered in sinh
  return abs(x1 + sinh(((x1 + abs(x1*(x1 + cos(x1)**2)**x1))**2)**x1)/x1)
<lambdifygenerated-12994>:2: RuntimeWarning: invalid value encountered in power
  return abs(x1 + sinh(((x1 + abs(x1*(x1 + cos(x1)**2)**x1))**2)**x1)/x1)
<lambdifygenerated-12994>:2: RuntimeWarning: divide by zero encountered in power
  return abs(x1 + sinh(((x1 + abs(x1*(x1 + cos(x1)**2)**x1))**2)**x1)/x1)
<lambdifygenerated-12994>:2: RuntimeWarning: overflow encountered in sinh
  return abs(x1 + sinh(((x1 + abs(x1*(x1 + cos(x1)**2)**x1))**2)**x1)/x1)
<lambdifygenerated-12995>:2: RuntimeWarning: invalid value encountered in power
  return abs(x1 + sinh(((x1 + abs(x1*(x1 + cos(2*x1)**2)**x1))**2)**x1)/x1)
<lambdifygenerated-12995>:2: RuntimeWarning: divide by zero encountered in power
  return abs(x1 + sinh(((x1 + abs(x1*(x1 + cos(2*x1)**2)**x1))**2)**x1)/x1)
<lambdifygenerated-12995>:2: RuntimeWarning: overflow encountered in sinh
  return abs(x1 + sinh(((x1 + abs(x1*(x1 + cos(2*x1)**2)**x1))**2)**x1)/x1)
<lambdifygenerated-12996>:2: RuntimeWarning: invalid value encountered in power
  return abs(x1 + sinh(((x1 + abs(x1*(x1 + cos(2*x1)**2)**x1))**2)**x1)/x1)
<lambdifygenerated-12996>:2: RuntimeWarning: divide by zero encountered in power
  return abs(x1 + sinh(((x1 + abs(x1*(x1 + cos(2*x1)**2)**x1))**2)**x1)/x1)
<lambdifygenerated-12996>:2: RuntimeWarning: overflow encountered in sinh
  return abs(x1 + sinh(((x1 + abs(x1*(x1 + cos(2*x1)**2)**x1))**2)**x1)/x1)
<lambdifygenerated-12997>:2: RuntimeWarning: invalid value encountered in power
  return abs(x1 + sinh(((x1 + abs(x1*(x1 + cos(2*x1)**2)**x1))**2)**x1)/x1)
<lambdifygenerated-12997>:2: RuntimeWarning: divide by zero encountered in power
  return abs(x1 + sinh(((x1 + abs(x1*(x1 + cos(2*x1)**2)**x1))**2)**x1)/x1)
<lambdifygenerated-12997>:2: RuntimeWarning: overflow encountered in sinh
  return abs(x1 + sinh(((x1 + abs(x1*(x1 + cos(2*x1)**2)**x1))**2)**x1)/x1)
<lambdifygenerated-12998>:2: RuntimeWarning: invalid value encountered in power
  return abs(x1 + sinh(((x1 + abs(x1*(x1 + cos(2*x1)**2)**x1))**2)**x1)/x1)
<lambdifygenerated-12998>:2: RuntimeWarning: divide by zero encountered in power
  return abs(x1 + sinh(((x1 + abs(x1*(x1 + cos(2*x1)**2)**x1))**2)**x1)/x1)
<lambdifygenerated-12998>:2: RuntimeWarning: overflow encountered in sinh
  return abs(x1 + sinh(((x1 + abs(x1*(x1 + cos(2*x1)**2)**x1))**2)**x1)/x1)
<lambdifygenerated-12999>:2: RuntimeWarning: invalid value encountered in power
  return abs(x1 + sinh(((x1 + abs(x1*(x1 + cos(_a1_ + x1)**2)**x1))**2)**x1)/x1)
<lambdifygenerated-12999>:2: RuntimeWarning: overflow encountered in sinh
  return abs(x1 + sinh(((x1 + abs(x1*(x1 + cos(_a1_ + x1)**2)**x1))**2)**x1)/x1)
/usr/local/lib/python3.10/dist-packages/scipy/optimize/_minpack_py.py:1017: RuntimeWarning: overflow encountered in square
  cost = np.sum(infodict['fvec'] ** 2)
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-13000>:2: RuntimeWarning: invalid value encountered in power
  return abs(x1 + sinh(((x1 + abs(x1*(x1 + cos(_a1_ + x1)**2)**x1))**2)**x1)/x1)
<lambdifygenerated-13000>:2: RuntimeWarning: overflow encountered in sinh
  return abs(x1 + sinh(((x1 + abs(x1*(x1 + cos(_a1_ + x1)**2)**x1))**2)**x1)/x1)
<lambdifygenerated-13001>:2: RuntimeWarning: invalid value encountered in power
  return abs(x1 + sinh(((x1 + abs(x1*(x1**x1 + cos(_a1_ + x1)**2)**x1))**2)**x1)/x1)
<lambdifygenerated-13001>:2: RuntimeWarning: overflow encountered in sinh
  return abs(x1 + sinh(((x1 + abs(x1*(x1**x1 + cos(_a1_ + x1)**2)**x1))**2)**x1)/x1)
<lambdifygenerated-13002>:2: RuntimeWarning: invalid value encountered in power
  return abs(x1 + sinh(((x1 + abs(x1*(x1**x1 + cos(_a1_ + x1)**2)**x1))**2)**x1)/x1)
<lambdifygenerated-13002>:2: RuntimeWarning: overflow encountered in sinh
  return abs(x1 + sinh(((x1 + abs(x1*(x1**x1 + cos(_a1_ + x1)**2)**x1))**2)**x1)/x1)
<lambdifygenerated-13003>:2: RuntimeWarning: overflow encountered in sinh
  return abs(x1 + sinh(((x1 + abs(x1*((x1**2)**x1 + cos(_a1_ + x1)**2)**x1))**2)**x1)/x1)
<lambdifygenerated-13004>:2: RuntimeWarning: overflow encountered in sinh
  return abs(x1 + sinh(((x1 + abs(x1*((x1**2)**x1 + cos(_a1_ + x1)**2)**x1))**2)**x1)/x1)
<lambdifygenerated-13005>:2: RuntimeWarning: invalid value encountered in power
  return abs(x1 + sinh(((x1 + abs(x1*((x1**3)**x1 + cos(_a1_ + x1)**2)**x1))**2)**x1)/x1)
<lambdifygenerated-13005>:2: RuntimeWarning: overflow encountered in sinh
  return abs(x1 + sinh(((x1 + abs(x1*((x1**3)**x1 + cos(_a1_ + x1)**2)**x1))**2)**x1)/x1)
<lambdifygenerated-13006>:2: RuntimeWarning: invalid value encountered in power
  return abs(x1 + sinh(((x1 + abs(x1*((x1**3)**x1 + cos(_a1_ + x1)**2)**x1))**2)**x1)/x1)
<lambdifygenerated-13006>:2: RuntimeWarning: overflow encountered in sinh
  return abs(x1 + sinh(((x1 + abs(x1*((x1**3)**x1 + cos(_a1_ + x1)**2)**x1))**2)**x1)/x1)
<lambdifygenerated-13007>:2: RuntimeWarning: invalid value encountered in power
  return abs(x1 + sinh(((x1 + abs(x1*((_a4_**2*x1)**x1 + cos(_a1_ + x1)**2)**x1))**2)**x1)/x1)
<lambdifygenerated-13007>:2: RuntimeWarning: overflow encountered in sinh
  return abs(x1 + sinh(((x1 + abs(x1*((_a4_**2*x1)**x1 + cos(_a1_ + x1)**2)**x1))**2)**x1)/x1)
<lambdifygenerated-13008>:2: RuntimeWarning: invalid value encountered in power
  return abs(x1 + sinh(((x1 + abs(x1*((_a4_**2*x1)**x1 + cos(_a1_ + x1)**2)**x1))**2)**x1)/x1)
<lambdifygenerated-13008>:2: RuntimeWarning: overflow encountered in sinh
  return abs(x1 + sinh(((x1 + abs(x1*((_a4_**2*x1)**x1 + cos(_a1_ + x1)**2)**x1))**2)**x1)/x1)
<lambdifygenerated-13009>:2: RuntimeWarning: overflow encountered in sinh
  return abs(x1 + sinh(((x1 + abs(x1*((_a1_*_a4_**2)**x1 + cos(_a1_ + x1)**2)**x1))**2)**x1)/x1)
<lambdifygenerated-13010>:2: RuntimeWarning: overflow encountered in sinh
  return abs(x1 + sinh(((x1 + abs(x1*((_a1_*_a4_**2)**x1 + cos(_a1_ + x1)**2)**x1))**2)**x1)/x1)
<lambdifygenerated-13011>:2: RuntimeWarning: overflow encountered in sinh
  return abs(x1 + sinh(((x1 + abs(x1*((_a1_*_a4_**2)**x1 + cos(_a1_ + x1)**2)**x1))**2)**x1)/x1)
<lambdifygenerated-13012>:2: RuntimeWarning: overflow encountered in sinh
  return abs(x1 + sinh(((x1 + abs(x1*((_a1_*_a4_**2)**x1 + cos(_a1_ + x1)**2)**x1))**2)**x1)/x1)
<lambdifygenerated-13013>:2: RuntimeWarning: overflow encountered in sinh
  return abs(x1 + sinh(((x1 + abs(x1*((_a1_*_a4_**2)**x1 + cos(_a1_ + x1)**2)**(2*x1)))**2)**x1)/x1)
<lambdifygenerated-13014>:2: RuntimeWarning: overflow encountered in sinh
  return abs(x1 + sinh(((x1 + abs(x1*((_a1_*_a4_**2)**x1 + cos(_a1_ + x1)**2)**(2*x1)))**2)**x1)/x1)
<lambdifygenerated-13015>:2: RuntimeWarning: overflow encountered in sinh
  return abs(x1 + sinh(((x1 + abs(x1*((_a1_*_a4_**2)**x1 + cos(_a1_ + x1)**2)**(x1**3 + x1)))**2)**x1)/x1)
<lambdifygenerated-13016>:2: RuntimeWarning: overflow encountered in sinh
  return abs(x1 + sinh(((x1 + abs(x1*((_a1_*_a4_**2)**x1 + cos(_a1_ + x1)**2)**(x1**3 + x1)))**2)**x1)/x1)
<lambdifygenerated-13017>:2: RuntimeWarning: overflow encountered in sinh
  return abs(x1 + sinh(((x1 + abs(x1*((_a1_*_a4_**2)**x1 + cos(_a1_ + x1)**2)**(x1**3 + x1)))**2)**x1)/x1)
<lambdifygenerated-13018>:2: RuntimeWarning: overflow encountered in sinh
  return abs(x1 + sinh(((x1 + abs(x1*((_a1_*_a4_**2)**x1 + cos(_a1_ + x1)**2)**(x1**3 + x1)))**2)**x1)/x1)
<lambdifygenerated-13019>:2: RuntimeWarning: overflow encountered in sinh
  return abs(x1 + sinh(((x1 + abs(x1*((_a1_*_a4_**2)**x1 + cos(_a1_ + x1)**2)**(_a3_ + x1**3)))**2)**x1)/x1)
<lambdifygenerated-13020>:2: RuntimeWarning: overflow encountered in sinh
  return abs(x1 + sinh(((x1 + abs(x1*((_a1_*_a4_**2)**x1 + cos(_a1_ + x1)**2)**(_a3_ + x1**3)))**2)**x1)/x1)
<lambdifygenerated-13021>:2: RuntimeWarning: overflow encountered in sinh
  return abs(x1 + sinh(((x1 + abs(x1**2*((_a1_*_a4_**2)**x1 + cos(_a1_ + x1)**2)**(_a3_ + x1**3)))**2)**x1)/x1)
<lambdifygenerated-13022>:2: RuntimeWarning: overflow encountered in sinh
  return abs(x1 + sinh(((x1 + abs(x1**2*((_a1_*_a4_**2)**x1 + cos(_a1_ + x1)**2)**(_a3_ + x1**3)))**2)**x1)/x1)
<lambdifygenerated-13023>:2: RuntimeWarning: overflow encountered in sinh
  return abs(x1 + sinh(((x1 + 2*abs(x1**2*((_a1_*_a4_**2)**x1 + cos(_a1_ + x1)**2)**(_a3_ + x1**3)))**2)**x1)/x1)
<lambdifygenerated-13024>:2: RuntimeWarning: overflow encountered in sinh
  return abs(x1 + sinh(((x1 + 2*abs(x1**2*((_a1_*_a4_**2)**x1 + cos(_a1_ + x1)**2)**(_a3_ + x1**3)))**2)**x1)/x1)
<lambdifygenerated-13025>:2: RuntimeWarning: overflow encountered in sinh
  return abs(x1 + sinh(((x1 + abs(x1*(_a6_ + x1)*((_a1_*_a4_**2)**x1 + cos(_a1_ + x1)**2)**(_a3_ + x1**3)))**2)**x1)/x1)
<lambdifygenerated-13026>:2: RuntimeWarning: overflow encountered in sinh
  return abs(x1 + sinh(((x1 + abs(x1*(_a6_ + x1)*((_a1_*_a4_**2)**x1 + cos(_a1_ + x1)**2)**(_a3_ + x1**3)))**2)**x1)/x1)
<lambdifygenerated-13027>:2: RuntimeWarning: overflow encountered in sinh
  return abs(x1 + sinh(((x1 + abs(x1*(_a6_ + x1)*((_a1_*_a4_**2)**x1 + cos(_a1_ + x1)**2)**(_a3_ + x1**3)))**2)**x1)/x1)
<lambdifygenerated-13028>:2: RuntimeWarning: overflow encountered in sinh
  return abs(x1 + sinh(((x1 + abs(x1*(_a6_ + x1)*((_a1_*_a4_**2)**x1 + cos(_a1_ + x1)**2)**(_a3_ + x1**3)))**2)**x1)/x1)
<lambdifygenerated-13029>:2: RuntimeWarning: overflow encountered in sinh
  return abs(x1 + sinh(((x1 + abs(_a0_*(_a6_ + x1)*((_a1_*_a4_**2)**x1 + cos(_a1_ + x1)**2)**(_a3_ + x1**3)))**2)**x1)/x1)
<lambdifygenerated-13030>:2: RuntimeWarning: overflow encountered in sinh
  return abs(x1 + sinh(((x1 + abs(_a0_*(_a6_ + x1)*((_a1_*_a4_**2)**x1 + cos(_a1_ + x1)**2)**(_a3_ + x1**3)))**2)**x1)/x1)
<lambdifygenerated-13031>:2: RuntimeWarning: overflow encountered in sinh
  return abs(x1 + sinh(((_a4_ + abs(_a0_*(_a6_ + x1)*((_a1_*_a4_**2)**x1 + cos(_a1_ + x1)**2)**(_a3_ + x1**3)))**2)**x1)/x1)
<lambdifygenerated-13032>:2: RuntimeWarning: overflow encountered in sinh
  return abs(x1 + sinh(((_a4_ + abs(_a0_*(_a6_ + x1)*((_a1_*_a4_**2)**x1 + cos(_a1_ + x1)**2)**(_a3_ + x1**3)))**2)**x1)/x1)
<lambdifygenerated-13033>:2: RuntimeWarning: overflow encountered in sinh
  return abs(x1 + sinh(((_a4_ + abs(_a0_*(_a6_ + x1)*((_a1_*_a4_**2)**x1 + cos(_a1_ + x1)**2)**(_a3_ + x1**3)))**2)**(x1**2))/x1)
<lambdifygenerated-13034>:2: RuntimeWarning: overflow encountered in sinh
  return abs(x1 + sinh(((_a4_ + abs(_a0_*(_a6_ + x1)*((_a1_*_a4_**2)**x1 + cos(_a1_ + x1)**2)**(_a3_ + x1**3)))**2)**(x1**2))/x1)
<lambdifygenerated-13035>:2: RuntimeWarning: invalid value encountered in power
  return abs(x1 + sinh(((_a4_ + abs(_a0_*(_a6_ + x1)*((_a1_*_a4_**2)**x1 + cos(_a1_ + x1)**2)**(_a3_ + x1**3)))**2)**(cos(x1)**2))/x1)
<lambdifygenerated-13037>:2: RuntimeWarning: invalid value encountered in power
  return abs(x1 + sinh(((_a4_ + abs(_a0_*(_a6_ + x1)*((_a1_*_a4_**2)**x1 + cos(_a1_ + x1)**2)**(_a3_ + x1**3)))**2)**(cos(_a0_)**2))/x1)
<lambdifygenerated-13039>:2: RuntimeWarning: invalid value encountered in power
  return abs(x1 + sinh(((_a4_ + abs(_a0_*(_a6_ + x1)*((_a1_*_a4_**2)**x1 + cos(_a1_ + x1)**2)**(_a3_ + x1**3)))**2)**(cos(_a0_)**2))/_a0_)
<lambdifygenerated-13039>:2: RuntimeWarning: overflow encountered in power
  return abs(x1 + sinh(((_a4_ + abs(_a0_*(_a6_ + x1)*((_a1_*_a4_**2)**x1 + cos(_a1_ + x1)**2)**(_a3_ + x1**3)))**2)**(cos(_a0_)**2))/_a0_)
<lambdifygenerated-13040>:2: RuntimeWarning: overflow encountered in power
  return abs(x1 + sinh(((_a4_ + abs(_a0_*(_a6_ + x1)*((_a1_*_a4_**2)**x1 + cos(_a1_ + x1)**2)**(_a3_ + x1**3)))**2)**(cos(_a0_)**2))/_a0_)
<lambdifygenerated-13041>:2: RuntimeWarning: overflow encountered in power
  return abs(_a5_ + sinh(((_a4_ + abs(_a0_*(_a6_ + x1)*((_a1_*_a4_**2)**x1 + cos(_a1_ + x1)**2)**(_a3_ + x1**3)))**2)**(cos(_a0_)**2))/_a0_)

interpolation

<lambdifygenerated-13042>:2: RuntimeWarning: overflow encountered in power
  return abs(_a5_ + sinh(((_a4_ + abs(_a0_*(_a6_ + x1)*((_a1_*_a4_**2)**x1 + cos(_a1_ + x1)**2)**(_a3_ + x1**3)))**2)**(cos(_a0_)**2))/_a0_)
<lambdifygenerated-13043>:2: RuntimeWarning: overflow encountered in power
  return abs(_a5_ + sinh(((_a4_ + abs(_a0_*(_a6_ + x1)*((_a1_*_a4_**2)**x1 + cos(_a1_ + x1)**2)**(_a3_ + x1**3)))**2)**(cos(_a0_)**2))/_a0_)
<lambdifygenerated-13044>:2: RuntimeWarning: overflow encountered in power
  return abs(_a5_ + sinh(((_a4_ + abs(_a0_*(_a6_ + x1)*((_a1_*_a4_**2)**x1 + cos(_a1_ + x1)**2)**(_a3_ + x1**3)))**2)**(cos(_a0_)**2))/_a0_)
<lambdifygenerated-13045>:2: RuntimeWarning: overflow encountered in power
  return abs(_a5_ + sinh(((_a4_ + abs(_a0_*(_a6_ + x1)*((_a1_*_a4_**2)**x1 + cos(_a1_ + x1)**2)**(_a3_ + x1**3)))**2)**(cos(_a0_)**2))/_a0_)
<lambdifygenerated-13046>:2: RuntimeWarning: overflow encountered in power
  return abs(_a5_ + sinh(((_a4_ + abs(_a0_*(_a6_ + x1)*((_a1_*_a4_**2)**x1 + cos(_a1_ + x1)**2)**(_a3_ + x1**3)))**2)**(cos(_a0_)**2))/_a0_)

         x1         y  rep    ymodel      ybms
3745  0.997  0.360683  0.0  0.356903  0.359728
3746  0.998  0.360826  0.0  0.357024  0.359839
3747  0.998  0.360969  0.0  0.357144  0.359950
3748  0.999  0.361111  0.0  0.357265  0.360060

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.361396  0.0  0.357505  0.360279
3751  1.002  0.361539  0.0  0.357626  0.360388
3752  1.002  0.361681  0.0  0.357746  0.360496
3753  1.003  0.361824  0.0  0.357866  0.360604

3750

<lambdifygenerated-13053>:2: RuntimeWarning: invalid value encountered in power
  return x1 + x1**x1
<lambdifygenerated-13054>:2: RuntimeWarning: invalid value encountered in power
  return x1 + x1**x1
<lambdifygenerated-13059>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (x1*(x1**2 + x1))**x1
<lambdifygenerated-13060>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (x1*(x1**2 + x1))**x1
<lambdifygenerated-13063>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (x1*(_a5_*x1**2 + x1))**x1
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-13064>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (x1*(_a5_*x1**2 + x1))**x1
<lambdifygenerated-13065>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (x1*(4*_a5_*x1**2 + x1))**x1
<lambdifygenerated-13066>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (x1*(4*_a5_*x1**2 + x1))**x1
<lambdifygenerated-13067>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (x1*(_a5_*(x1 + sin(x1))**2 + x1))**x1
<lambdifygenerated-13068>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (x1*(_a5_*(x1 + sin(x1))**2 + x1))**x1
<lambdifygenerated-13069>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (x1*(_a5_*(x1 + sin(x1))**2 + x1))**x1
<lambdifygenerated-13070>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (x1*(_a5_*(x1 + sin(x1))**2 + x1))**x1
<lambdifygenerated-13071>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (x1*(_a5_*(sin(x1) + tanh(x1))**2 + x1))**x1
<lambdifygenerated-13072>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (x1*(_a5_*(sin(x1) + tanh(x1))**2 + x1))**x1
<lambdifygenerated-13073>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (x1*(_a5_*(sin(x1) + tanh(2*x1))**2 + x1))**x1
<lambdifygenerated-13074>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (x1*(_a5_*(sin(x1) + tanh(2*x1))**2 + x1))**x1
<lambdifygenerated-13075>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (x1*(_a5_*(sin(x1) + tanh(x1 + 1))**2 + x1))**x1
<lambdifygenerated-13076>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (x1*(_a5_*(sin(x1) + tanh(x1 + 1))**2 + x1))**x1
<lambdifygenerated-13077>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (x1*(_a5_*(sin(x1) + tanh(x1 + sinh(x1)/x1))**2 + x1))**x1
<lambdifygenerated-13078>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (x1*(_a5_*(sin(x1) + tanh(x1 + sinh(x1)/x1))**2 + x1))**x1
<lambdifygenerated-13079>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (x1*(_a5_*(sin(x1) + tanh(x1 + sinh(x1)/x1))**2 + x1))**x1
<lambdifygenerated-13080>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (x1*(_a5_*(sin(x1) + tanh(x1 + sinh(x1)/x1))**2 + x1))**x1
<lambdifygenerated-13081>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (x1*(_a5_*(sin(x1) + tanh(x1 + sinh(x1)/_a2_))**2 + x1))**x1
<lambdifygenerated-13082>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (x1*(_a5_*(sin(x1) + tanh(x1 + sinh(x1)/_a2_))**2 + x1))**x1
<lambdifygenerated-13083>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (x1*(_a5_*(sin(x1) - tanh(x1 - sinh(x1)/_a2_))**2 + x1))**x1
<lambdifygenerated-13084>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (x1*(_a5_*(sin(x1) - tanh(x1 - sinh(x1)/_a2_))**2 + x1))**x1
<lambdifygenerated-13085>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (x1*(_a5_*(sin(x1) - tanh(2*x1 - sinh(x1)/_a2_))**2 + x1))**x1
<lambdifygenerated-13087>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (x1*(_a5_*(sin(x1) - tanh(_a4_ + x1 - sinh(x1)/_a2_))**2 + x1))**x1
<lambdifygenerated-13088>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (x1*(_a5_*(sin(x1) - tanh(_a4_ + x1 - sinh(x1)/_a2_))**2 + x1))**x1
<lambdifygenerated-13089>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (x1*(_a5_*(sin(x1) - tanh(_a4_ + abs(x1) - sinh(x1)/_a2_))**2 + x1))**x1
<lambdifygenerated-13090>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (x1*(_a5_*(sin(x1) - tanh(_a4_ + abs(x1) - sinh(x1)/_a2_))**2 + x1))**x1
<lambdifygenerated-13091>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (x1*(_a5_*(sin(x1) - tanh(_a4_ + 2*abs(x1) - sinh(x1)/_a2_))**2 + x1))**x1
<lambdifygenerated-13092>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (x1*(_a5_*(sin(x1) - tanh(_a4_ + 2*abs(x1) - sinh(x1)/_a2_))**2 + x1))**x1
<lambdifygenerated-13093>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (x1*(_a5_*(sin(x1) - tanh(_a4_ + abs(x1**2 + x1) - sinh(x1)/_a2_))**2 + x1))**x1
<lambdifygenerated-13094>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (x1*(_a5_*(sin(x1) - tanh(_a4_ + abs(x1**2 + x1) - sinh(x1)/_a2_))**2 + x1))**x1
<lambdifygenerated-13095>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (x1*(_a5_*(sin(x1) - tanh(_a4_ + abs(x1**2 + x1) - sinh(x1)/_a2_))**2 + x1))**x1
<lambdifygenerated-13096>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (x1*(_a5_*(sin(x1) - tanh(_a4_ + abs(x1**2 + x1) - sinh(x1)/_a2_))**2 + x1))**x1
<lambdifygenerated-13097>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (x1*(_a5_*(sin(x1) - tanh(_a4_ + abs(_a6_*x1 + x1) - sinh(x1)/_a2_))**2 + x1))**x1
<lambdifygenerated-13098>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (x1*(_a5_*(sin(x1) - tanh(_a4_ + abs(_a6_*x1 + x1) - sinh(x1)/_a2_))**2 + x1))**x1
<lambdifygenerated-13099>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (x1*(_a5_*(sin(x1) - tanh(_a4_ + abs(_a0_ + _a6_*x1) - sinh(x1)/_a2_))**2 + x1))**x1
<lambdifygenerated-13100>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (x1*(_a5_*(sin(x1) - tanh(_a4_ + abs(_a0_ + _a6_*x1) - sinh(x1)/_a2_))**2 + x1))**x1
<lambdifygenerated-13101>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (x1*(_a5_*(sin(x1) - tanh(_a4_ + abs(_a0_ + _a6_*x1) - sinh(x1)/_a2_))**2 - x1))**x1
<lambdifygenerated-13102>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (x1*(_a5_*(sin(x1) - tanh(_a4_ + abs(_a0_ + _a6_*x1) - sinh(x1)/_a2_))**2 - x1))**x1
<lambdifygenerated-13103>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (x1*(_a5_*(sin(x1) - tanh(_a4_ + abs(_a0_ + _a6_*x1) - sinh(x1)/_a2_))**2 - x1**x1))**x1
<lambdifygenerated-13104>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (x1*(_a5_*(sin(x1) - tanh(_a4_ + abs(_a0_ + _a6_*x1) - sinh(x1)/_a2_))**2 - x1**x1))**x1
<lambdifygenerated-13105>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (x1*(_a5_*(sin(x1) - tanh(_a4_ + abs(_a0_ + _a6_*x1) - sinh(x1)/_a2_))**2 - (x1**2)**x1))**x1
<lambdifygenerated-13106>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (x1*(_a5_*(sin(x1) - tanh(_a4_ + abs(_a0_ + _a6_*x1) - sinh(x1)/_a2_))**2 - (x1**2)**x1))**x1
<lambdifygenerated-13107>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (x1*(_a5_*(sin(x1) - tanh(_a4_ + abs(_a0_ + _a6_*x1) - sinh(x1)/_a2_))**2 - (_a3_**2)**x1))**x1
<lambdifygenerated-13108>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (x1*(_a5_*(sin(x1) - tanh(_a4_ + abs(_a0_ + _a6_*x1) - sinh(x1)/_a2_))**2 - (_a3_**2)**x1))**x1
<lambdifygenerated-13109>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (x1*(_a5_*(sin(x1) - tanh(_a4_ + abs(_a0_ + _a6_*x1) - sinh(x1)/_a2_))**2 - (_a3_**2)**x1))**x1
<lambdifygenerated-13110>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (x1*(_a5_*(sin(x1) - tanh(_a4_ + abs(_a0_ + _a6_*x1) - sinh(x1)/_a2_))**2 - (_a3_**2)**x1))**x1
<lambdifygenerated-13111>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (_a2_*(_a5_*(sin(x1) - tanh(_a4_ + abs(_a0_ + _a6_*x1) - sinh(x1)/_a2_))**2 - (_a3_**2)**x1))**x1
<lambdifygenerated-13112>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (_a2_*(_a5_*(sin(x1) - tanh(_a4_ + abs(_a0_ + _a6_*x1) - sinh(x1)/_a2_))**2 - (_a3_**2)**x1))**x1
<lambdifygenerated-13113>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (_a2_*(_a5_*(sin(x1) - tanh(_a4_ + abs(_a0_ + _a6_*x1) - sinh(x1)/_a2_))**2 - (_a3_**2)**x1))**(x1**2)
<lambdifygenerated-13114>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (_a2_*(_a5_*(sin(x1) - tanh(_a4_ + abs(_a0_ + _a6_*x1) - sinh(x1)/_a2_))**2 - (_a3_**2)**x1))**(x1**2)
<lambdifygenerated-13115>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (_a2_*(_a5_*(sin(x1) - tanh(_a4_ + abs(_a0_ + _a6_*x1) - sinh(x1)/_a2_))**2 - (_a3_**2)**x1))**(_a1_**2)
<lambdifygenerated-13117>:2: RuntimeWarning: invalid value encountered in power
  return _a3_ + (_a2_*(_a5_*(sin(x1) - tanh(_a4_ + abs(_a0_ + _a6_*x1) - sinh(x1)/_a2_))**2 - (_a3_**2)**x1))**(_a1_**2)
<lambdifygenerated-13121>:2: RuntimeWarning: invalid value encountered in power
  return _a3_ + (_a2_*(_a5_*(sin(x1) - tanh(_a4_ + abs(_a0_ + _a6_*x1) - sinh(x1)/_a2_))**2 - (_a3_**2)**x1))**(_a1_**2)

interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.875844  1.0  0.896273  0.896010
3746  0.998  0.875274  1.0  0.896169  0.895875
3747  0.998  0.874704  1.0  0.896066  0.895739
3748  0.999  0.874135  1.0  0.895962  0.895604

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.872995  1.0  0.895754  0.895332
3751  1.002  0.872426  1.0  0.895651  0.895196
3752  1.002  0.871856  1.0  0.895547  0.895059
3753  1.003  0.871287  1.0  0.895443  0.894923

3750
interpolation

<lambdifygenerated-13199>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1 + sinh(x1*sin((_a3_ + x1*x1**x1)*(_a5_ + cos(_a0_*x1 + _a1_ + _a2_*sin(_a0_*x1*(_a1_**2*_a4_ + x1)) + _a2_))/_a1_)))
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-13200>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1 + sinh(x1*sin((_a3_ + x1*x1**x1)*(_a5_ + cos(_a0_*x1 + _a1_ + _a2_*sin(_a0_*x1*(_a1_**2*_a4_ + x1)) + _a2_))/_a1_)))

         x1         y  rep    ymodel      ybms
3745  0.997  0.997734  2.0  0.992378  0.992268
3746  0.998  0.997761  2.0  0.992347  0.992200
3747  0.998  0.997787  2.0  0.992315  0.992130
3748  0.999  0.997814  2.0  0.992284  0.992058

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.997867  2.0  0.992221  0.991908
3751  1.002  0.997894  2.0  0.992189  0.991830
3752  1.002  0.997921  2.0  0.992157  0.991751
3753  1.003  0.997948  2.0  0.992125  0.991669

3750

<lambdifygenerated-13239>:2: RuntimeWarning: overflow encountered in exp
  return x1**3*cos(x1 + exp(x1*(x1 + tan(x1))))**3
<lambdifygenerated-13239>:2: RuntimeWarning: invalid value encountered in cos
  return x1**3*cos(x1 + exp(x1*(x1 + tan(x1))))**3
<lambdifygenerated-13240>:2: RuntimeWarning: overflow encountered in exp
  return x1**3*cos(x1 + exp(x1*(x1 + tan(x1))))**3
<lambdifygenerated-13240>:2: RuntimeWarning: invalid value encountered in cos
  return x1**3*cos(x1 + exp(x1*(x1 + tan(x1))))**3
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(

interpolation

<lambdifygenerated-13295>:2: RuntimeWarning: overflow encountered in exp
  return x1**3*cos(x1 + exp(x1*(_a7_/(_a3_ + 2*x1) + tan(sin(_a2_*(_a1_ + x1) + tanh(_a2_*_a5_*(_a1_*_a5_ + _a2_ + _a5_ + _a6_ + x1)))))))**3
<lambdifygenerated-13295>:2: RuntimeWarning: invalid value encountered in cos
  return x1**3*cos(x1 + exp(x1*(_a7_/(_a3_ + 2*x1) + tan(sin(_a2_*(_a1_ + x1) + tanh(_a2_*_a5_*(_a1_*_a5_ + _a2_ + _a5_ + _a6_ + x1)))))))**3
<lambdifygenerated-13296>:2: RuntimeWarning: overflow encountered in exp
  return x1**3*cos(x1 + exp(x1*(_a7_/(_a3_ + 2*x1) + tan(sin(_a2_*(_a1_ + x1) + tanh(_a2_*_a5_*(_a1_*_a5_ + _a2_ + _a5_ + _a6_ + x1)))))))**3
<lambdifygenerated-13296>:2: RuntimeWarning: invalid value encountered in cos
  return x1**3*cos(x1 + exp(x1*(_a7_/(_a3_ + 2*x1) + tan(sin(_a2_*(_a1_ + x1) + tanh(_a2_*_a5_*(_a1_*_a5_ + _a2_ + _a5_ + _a6_ + x1)))))))**3
<lambdifygenerated-13297>:2: RuntimeWarning: overflow encountered in exp
  return x1**3*cos(x1 + exp(x1*(_a7_/(_a3_ + x1 + sin(x1)) + tan(sin(_a2_*(_a1_ + x1) + tanh(_a2_*_a5_*(_a1_*_a5_ + _a2_ + _a5_ + _a6_ + x1)))))))**3
<lambdifygenerated-13297>:2: RuntimeWarning: invalid value encountered in cos
  return x1**3*cos(x1 + exp(x1*(_a7_/(_a3_ + x1 + sin(x1)) + tan(sin(_a2_*(_a1_ + x1) + tanh(_a2_*_a5_*(_a1_*_a5_ + _a2_ + _a5_ + _a6_ + x1)))))))**3
<lambdifygenerated-13298>:2: RuntimeWarning: overflow encountered in exp
  return x1**3*cos(x1 + exp(x1*(_a7_/(_a3_ + x1 + sin(x1)) + tan(sin(_a2_*(_a1_ + x1) + tanh(_a2_*_a5_*(_a1_*_a5_ + _a2_ + _a5_ + _a6_ + x1)))))))**3
<lambdifygenerated-13298>:2: RuntimeWarning: invalid value encountered in cos
  return x1**3*cos(x1 + exp(x1*(_a7_/(_a3_ + x1 + sin(x1)) + tan(sin(_a2_*(_a1_ + x1) + tanh(_a2_*_a5_*(_a1_*_a5_ + _a2_ + _a5_ + _a6_ + x1)))))))**3
<lambdifygenerated-13299>:2: RuntimeWarning: overflow encountered in exp
  return x1**3*cos(x1 + exp(x1*(_a7_/(_a3_ + x1 + sin(x1)) + tan(sin(_a2_*(_a1_ + x1) + tanh(_a2_*_a5_*(_a1_*_a5_ + _a2_ + _a5_ + _a6_ + x1)))))))**3
<lambdifygenerated-13299>:2: RuntimeWarning: invalid value encountered in cos
  return x1**3*cos(x1 + exp(x1*(_a7_/(_a3_ + x1 + sin(x1)) + tan(sin(_a2_*(_a1_ + x1) + tanh(_a2_*_a5_*(_a1_*_a5_ + _a2_ + _a5_ + _a6_ + x1)))))))**3
<lambdifygenerated-13300>:2: RuntimeWarning: overflow encountered in exp
  return x1**3*cos(x1 + exp(x1*(_a7_/(_a3_ + x1 + sin(x1)) + tan(sin(_a2_*(_a1_ + x1) + tanh(_a2_*_a5_*(_a1_*_a5_ + _a2_ + _a5_ + _a6_ + x1)))))))**3
<lambdifygenerated-13300>:2: RuntimeWarning: invalid value encountered in cos
  return x1**3*cos(x1 + exp(x1*(_a7_/(_a3_ + x1 + sin(x1)) + tan(sin(_a2_*(_a1_ + x1) + tanh(_a2_*_a5_*(_a1_*_a5_ + _a2_ + _a5_ + _a6_ + x1)))))))**3
<lambdifygenerated-13301>:2: RuntimeWarning: overflow encountered in exp
  return x1**3*cos(x1 + exp(x1*(_a7_/(_a3_ + _a4_ + sin(x1)) + tan(sin(_a2_*(_a1_ + x1) + tanh(_a2_*_a5_*(_a1_*_a5_ + _a2_ + _a5_ + _a6_ + x1)))))))**3
<lambdifygenerated-13301>:2: RuntimeWarning: invalid value encountered in cos
  return x1**3*cos(x1 + exp(x1*(_a7_/(_a3_ + _a4_ + sin(x1)) + tan(sin(_a2_*(_a1_ + x1) + tanh(_a2_*_a5_*(_a1_*_a5_ + _a2_ + _a5_ + _a6_ + x1)))))))**3
<lambdifygenerated-13303>:2: RuntimeWarning: overflow encountered in exp
  return x1**3*cos(x1 + exp(_a3_*(_a7_/(_a3_ + _a4_ + sin(x1)) + tan(sin(_a2_*(_a1_ + x1) + tanh(_a2_*_a5_*(_a1_*_a5_ + _a2_ + _a5_ + _a6_ + x1)))))))**3
<lambdifygenerated-13303>:2: RuntimeWarning: invalid value encountered in cos
  return x1**3*cos(x1 + exp(_a3_*(_a7_/(_a3_ + _a4_ + sin(x1)) + tan(sin(_a2_*(_a1_ + x1) + tanh(_a2_*_a5_*(_a1_*_a5_ + _a2_ + _a5_ + _a6_ + x1)))))))**3
<lambdifygenerated-13304>:2: RuntimeWarning: overflow encountered in exp
  return x1**3*cos(x1 + exp(_a3_*(_a7_/(_a3_ + _a4_ + sin(x1)) + tan(sin(_a2_*(_a1_ + x1) + tanh(_a2_*_a5_*(_a1_*_a5_ + _a2_ + _a5_ + _a6_ + x1)))))))**3
<lambdifygenerated-13304>:2: RuntimeWarning: invalid value encountered in cos
  return x1**3*cos(x1 + exp(_a3_*(_a7_/(_a3_ + _a4_ + sin(x1)) + tan(sin(_a2_*(_a1_ + x1) + tanh(_a2_*_a5_*(_a1_*_a5_ + _a2_ + _a5_ + _a6_ + x1)))))))**3
<lambdifygenerated-13305>:2: RuntimeWarning: overflow encountered in exp
  return x1**3*cos(_a1_ + exp(_a3_*(_a7_/(_a3_ + _a4_ + sin(x1)) + tan(sin(_a2_*(_a1_ + x1) + tanh(_a2_*_a5_*(_a1_*_a5_ + _a2_ + _a5_ + _a6_ + x1)))))))**3
<lambdifygenerated-13305>:2: RuntimeWarning: invalid value encountered in cos
  return x1**3*cos(_a1_ + exp(_a3_*(_a7_/(_a3_ + _a4_ + sin(x1)) + tan(sin(_a2_*(_a1_ + x1) + tanh(_a2_*_a5_*(_a1_*_a5_ + _a2_ + _a5_ + _a6_ + x1)))))))**3
<lambdifygenerated-13306>:2: RuntimeWarning: overflow encountered in exp
  return x1**3*cos(_a1_ + exp(_a3_*(_a7_/(_a3_ + _a4_ + sin(x1)) + tan(sin(_a2_*(_a1_ + x1) + tanh(_a2_*_a5_*(_a1_*_a5_ + _a2_ + _a5_ + _a6_ + x1)))))))**3
<lambdifygenerated-13306>:2: RuntimeWarning: invalid value encountered in cos
  return x1**3*cos(_a1_ + exp(_a3_*(_a7_/(_a3_ + _a4_ + sin(x1)) + tan(sin(_a2_*(_a1_ + x1) + tanh(_a2_*_a5_*(_a1_*_a5_ + _a2_ + _a5_ + _a6_ + x1)))))))**3
<lambdifygenerated-13307>:2: RuntimeWarning: overflow encountered in exp
  return _a0_**3*cos(_a1_ + exp(_a3_*(_a7_/(_a3_ + _a4_ + sin(x1)) + tan(sin(_a2_*(_a1_ + x1) + tanh(_a2_*_a5_*(_a1_*_a5_ + _a2_ + _a5_ + _a6_ + x1)))))))**3
<lambdifygenerated-13307>:2: RuntimeWarning: invalid value encountered in cos
  return _a0_**3*cos(_a1_ + exp(_a3_*(_a7_/(_a3_ + _a4_ + sin(x1)) + tan(sin(_a2_*(_a1_ + x1) + tanh(_a2_*_a5_*(_a1_*_a5_ + _a2_ + _a5_ + _a6_ + x1)))))))**3
<lambdifygenerated-13308>:2: RuntimeWarning: overflow encountered in exp
  return _a0_**3*cos(_a1_ + exp(_a3_*(_a7_/(_a3_ + _a4_ + sin(x1)) + tan(sin(_a2_*(_a1_ + x1) + tanh(_a2_*_a5_*(_a1_*_a5_ + _a2_ + _a5_ + _a6_ + x1)))))))**3
<lambdifygenerated-13308>:2: RuntimeWarning: invalid value encountered in cos
  return _a0_**3*cos(_a1_ + exp(_a3_*(_a7_/(_a3_ + _a4_ + sin(x1)) + tan(sin(_a2_*(_a1_ + x1) + tanh(_a2_*_a5_*(_a1_*_a5_ + _a2_ + _a5_ + _a6_ + x1)))))))**3
<lambdifygenerated-13309>:2: RuntimeWarning: overflow encountered in exp
  return _a0_**3*cos(_a1_ + exp(_a3_*(_a7_/(_a3_ + _a4_ + sin(x1)) + tan(sin(_a2_*(_a1_ + x1) + tanh(_a2_*_a5_*(_a1_*_a5_ + _a2_ + _a5_ + _a6_ + x1)))))))**3
<lambdifygenerated-13309>:2: RuntimeWarning: invalid value encountered in cos
  return _a0_**3*cos(_a1_ + exp(_a3_*(_a7_/(_a3_ + _a4_ + sin(x1)) + tan(sin(_a2_*(_a1_ + x1) + tanh(_a2_*_a5_*(_a1_*_a5_ + _a2_ + _a5_ + _a6_ + x1)))))))**3
<lambdifygenerated-13310>:2: RuntimeWarning: overflow encountered in exp
  return _a0_**3*cos(_a1_ + exp(_a3_*(_a7_/(_a3_ + _a4_ + sin(x1)) + tan(sin(_a2_*(_a1_ + x1) + tanh(_a2_*_a5_*(_a1_*_a5_ + _a2_ + _a5_ + _a6_ + x1)))))))**3
<lambdifygenerated-13310>:2: RuntimeWarning: invalid value encountered in cos
  return _a0_**3*cos(_a1_ + exp(_a3_*(_a7_/(_a3_ + _a4_ + sin(x1)) + tan(sin(_a2_*(_a1_ + x1) + tanh(_a2_*_a5_*(_a1_*_a5_ + _a2_ + _a5_ + _a6_ + x1)))))))**3
<lambdifygenerated-13311>:2: RuntimeWarning: overflow encountered in exp
  return _a0_**3*cos(_a1_ + exp(_a3_*(_a7_/(_a3_ + _a4_ + sin(x1)) + tan(sin(_a2_*(_a1_ + x1) + tanh(_a2_*_a5_*(_a1_*_a5_ + _a2_ + _a5_ + _a6_ + x1)))))))**3
<lambdifygenerated-13311>:2: RuntimeWarning: invalid value encountered in cos
  return _a0_**3*cos(_a1_ + exp(_a3_*(_a7_/(_a3_ + _a4_ + sin(x1)) + tan(sin(_a2_*(_a1_ + x1) + tanh(_a2_*_a5_*(_a1_*_a5_ + _a2_ + _a5_ + _a6_ + x1)))))))**3
<lambdifygenerated-13312>:2: RuntimeWarning: overflow encountered in exp
  return _a0_**3*cos(_a1_ + exp(_a3_*(_a7_/(_a3_ + _a4_ + sin(x1)) + tan(sin(_a2_*(_a1_ + x1) + tanh(_a2_*_a5_*(_a1_*_a5_ + _a2_ + _a5_ + _a6_ + x1)))))))**3
<lambdifygenerated-13312>:2: RuntimeWarning: invalid value encountered in cos
  return _a0_**3*cos(_a1_ + exp(_a3_*(_a7_/(_a3_ + _a4_ + sin(x1)) + tan(sin(_a2_*(_a1_ + x1) + tanh(_a2_*_a5_*(_a1_*_a5_ + _a2_ + _a5_ + _a6_ + x1)))))))**3

         x1         y  rep    ymodel      ybms
3745  0.997  0.689029  3.0  0.684438  0.687315
3746  0.998  0.688777  3.0  0.684083  0.686972
3747  0.998  0.688525  3.0  0.683727  0.686629
3748  0.999  0.688273  3.0  0.683372  0.686287

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.687768  3.0  0.682661  0.685602
3751  1.002  0.687516  3.0  0.682306  0.685260
3752  1.002  0.687264  3.0  0.681951  0.684917
3753  1.003  0.687012  3.0  0.681596  0.684575

3750

<lambdifygenerated-13317>:2: RuntimeWarning: invalid value encountered in sqrt
  return sqrt(x1)
<lambdifygenerated-13318>:2: RuntimeWarning: invalid value encountered in sqrt
  return sqrt(x1)
<lambdifygenerated-13319>:2: RuntimeWarning: invalid value encountered in sqrt
  return sqrt(2)*sqrt(x1)
<lambdifygenerated-13320>:2: RuntimeWarning: invalid value encountered in sqrt
  return sqrt(2)*sqrt(x1)
<lambdifygenerated-13321>:2: RuntimeWarning: invalid value encountered in sqrt
  return sqrt(x1**2 + x1)
<lambdifygenerated-13322>:2: RuntimeWarning: invalid value encountered in sqrt
  return sqrt(x1**2 + x1)
<lambdifygenerated-13323>:2: RuntimeWarning: invalid value encountered in sqrt
  return sqrt(2*x1**2 + x1)
<lambdifygenerated-13324>:2: RuntimeWarning: invalid value encountered in sqrt
  return sqrt(2*x1**2 + x1)
<lambdifygenerated-13325>:2: RuntimeWarning: invalid value encountered in log
  return sqrt(x1*(x1 + log(x1)) + x1)
<lambdifygenerated-13325>:2: RuntimeWarning: invalid value encountered in sqrt
  return sqrt(x1*(x1 + log(x1)) + x1)
<lambdifygenerated-13326>:2: RuntimeWarning: invalid value encountered in log
  return sqrt(x1*(x1 + log(x1)) + x1)
<lambdifygenerated-13326>:2: RuntimeWarning: invalid value encountered in sqrt
  return sqrt(x1*(x1 + log(x1)) + x1)
<lambdifygenerated-13327>:2: RuntimeWarning: invalid value encountered in log
  return sqrt(x1*(x1 + log(2*x1)) + x1)
<lambdifygenerated-13327>:2: RuntimeWarning: invalid value encountered in sqrt
  return sqrt(x1*(x1 + log(2*x1)) + x1)
<lambdifygenerated-13328>:2: RuntimeWarning: invalid value encountered in log
  return sqrt(x1*(x1 + log(2*x1)) + x1)
<lambdifygenerated-13328>:2: RuntimeWarning: invalid value encountered in sqrt
  return sqrt(x1*(x1 + log(2*x1)) + x1)
<lambdifygenerated-13329>:2: RuntimeWarning: invalid value encountered in log
  return sqrt(x1*(x1 + log(x1 + 1)) + x1)
<lambdifygenerated-13329>:2: RuntimeWarning: invalid value encountered in sqrt
  return sqrt(x1*(x1 + log(x1 + 1)) + x1)
<lambdifygenerated-13330>:2: RuntimeWarning: invalid value encountered in log
  return sqrt(x1*(x1 + log(x1 + 1)) + x1)
<lambdifygenerated-13330>:2: RuntimeWarning: invalid value encountered in sqrt
  return sqrt(x1*(x1 + log(x1 + 1)) + x1)
<lambdifygenerated-13331>:2: RuntimeWarning: invalid value encountered in log
  return sqrt(x1*(x1 + log(x1 + tanh(x1)/x1)) + x1)
<lambdifygenerated-13331>:2: RuntimeWarning: invalid value encountered in sqrt
  return sqrt(x1*(x1 + log(x1 + tanh(x1)/x1)) + x1)
<lambdifygenerated-13332>:2: RuntimeWarning: invalid value encountered in log
  return sqrt(x1*(x1 + log(x1 + tanh(x1)/x1)) + x1)
<lambdifygenerated-13332>:2: RuntimeWarning: invalid value encountered in sqrt
  return sqrt(x1*(x1 + log(x1 + tanh(x1)/x1)) + x1)
<lambdifygenerated-13333>:2: RuntimeWarning: invalid value encountered in log
  return sqrt(x1*(x1 + log(x1 + tanh(x1**2)/x1)) + x1)
<lambdifygenerated-13333>:2: RuntimeWarning: invalid value encountered in sqrt
  return sqrt(x1*(x1 + log(x1 + tanh(x1**2)/x1)) + x1)
<lambdifygenerated-13334>:2: RuntimeWarning: invalid value encountered in log
  return sqrt(x1*(x1 + log(x1 + tanh(x1**2)/x1)) + x1)
<lambdifygenerated-13334>:2: RuntimeWarning: invalid value encountered in sqrt
  return sqrt(x1*(x1 + log(x1 + tanh(x1**2)/x1)) + x1)
<lambdifygenerated-13335>:2: RuntimeWarning: invalid value encountered in log
  return sqrt(x1*(x1 + log(x1 + tanh(2*x1**2)/x1)) + x1)
<lambdifygenerated-13335>:2: RuntimeWarning: invalid value encountered in sqrt
  return sqrt(x1*(x1 + log(x1 + tanh(2*x1**2)/x1)) + x1)
<lambdifygenerated-13336>:2: RuntimeWarning: invalid value encountered in log
  return sqrt(x1*(x1 + log(x1 + tanh(2*x1**2)/x1)) + x1)
<lambdifygenerated-13336>:2: RuntimeWarning: invalid value encountered in sqrt
  return sqrt(x1*(x1 + log(x1 + tanh(2*x1**2)/x1)) + x1)
<lambdifygenerated-13337>:2: RuntimeWarning: invalid value encountered in log
  return sqrt(x1*(x1 + log(x1 + tanh(x1*(_a0_ + x1))/x1)) + x1)
<lambdifygenerated-13337>:2: RuntimeWarning: invalid value encountered in sqrt
  return sqrt(x1*(x1 + log(x1 + tanh(x1*(_a0_ + x1))/x1)) + x1)
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-13338>:2: RuntimeWarning: invalid value encountered in log
  return sqrt(x1*(x1 + log(x1 + tanh(x1*(_a0_ + x1))/x1)) + x1)
<lambdifygenerated-13338>:2: RuntimeWarning: invalid value encountered in sqrt
  return sqrt(x1*(x1 + log(x1 + tanh(x1*(_a0_ + x1))/x1)) + x1)
<lambdifygenerated-13339>:2: RuntimeWarning: invalid value encountered in log
  return sqrt(x1*(x1 + log(x1 + tanh(x1*(_a0_ + x1**2))/x1)) + x1)
<lambdifygenerated-13339>:2: RuntimeWarning: invalid value encountered in sqrt
  return sqrt(x1*(x1 + log(x1 + tanh(x1*(_a0_ + x1**2))/x1)) + x1)
<lambdifygenerated-13340>:2: RuntimeWarning: invalid value encountered in log
  return sqrt(x1*(x1 + log(x1 + tanh(x1*(_a0_ + x1**2))/x1)) + x1)
<lambdifygenerated-13340>:2: RuntimeWarning: invalid value encountered in sqrt
  return sqrt(x1*(x1 + log(x1 + tanh(x1*(_a0_ + x1**2))/x1)) + x1)
<lambdifygenerated-13341>:2: RuntimeWarning: invalid value encountered in log
  return sqrt(x1*(x1 + log(x1 + tanh(x1*(_a0_ + x1**4))/x1)) + x1)
<lambdifygenerated-13341>:2: RuntimeWarning: invalid value encountered in sqrt
  return sqrt(x1*(x1 + log(x1 + tanh(x1*(_a0_ + x1**4))/x1)) + x1)
<lambdifygenerated-13342>:2: RuntimeWarning: invalid value encountered in log
  return sqrt(x1*(x1 + log(x1 + tanh(x1*(_a0_ + x1**4))/x1)) + x1)
<lambdifygenerated-13342>:2: RuntimeWarning: invalid value encountered in sqrt
  return sqrt(x1*(x1 + log(x1 + tanh(x1*(_a0_ + x1**4))/x1)) + x1)
<lambdifygenerated-13343>:2: RuntimeWarning: invalid value encountered in log
  return sqrt(x1*(x1 + log(x1 + tanh(x1*(_a0_ + _a2_**2*x1**2))/x1)) + x1)
<lambdifygenerated-13343>:2: RuntimeWarning: invalid value encountered in sqrt
  return sqrt(x1*(x1 + log(x1 + tanh(x1*(_a0_ + _a2_**2*x1**2))/x1)) + x1)
<lambdifygenerated-13344>:2: RuntimeWarning: invalid value encountered in log
  return sqrt(x1*(x1 + log(x1 + tanh(x1*(_a0_ + _a2_**2*x1**2))/x1)) + x1)
<lambdifygenerated-13344>:2: RuntimeWarning: invalid value encountered in sqrt
  return sqrt(x1*(x1 + log(x1 + tanh(x1*(_a0_ + _a2_**2*x1**2))/x1)) + x1)
<lambdifygenerated-13345>:2: RuntimeWarning: invalid value encountered in log
  return sqrt(x1*(x1 + log(x1 + tanh(x1*(_a0_ + _a2_**2*x1**2))/x1)) + x1)
<lambdifygenerated-13345>:2: RuntimeWarning: invalid value encountered in sqrt
  return sqrt(x1*(x1 + log(x1 + tanh(x1*(_a0_ + _a2_**2*x1**2))/x1)) + x1)
<lambdifygenerated-13346>:2: RuntimeWarning: invalid value encountered in log
  return sqrt(x1*(x1 + log(x1 + tanh(x1*(_a0_ + _a2_**2*x1**2))/x1)) + x1)
<lambdifygenerated-13346>:2: RuntimeWarning: invalid value encountered in sqrt
  return sqrt(x1*(x1 + log(x1 + tanh(x1*(_a0_ + _a2_**2*x1**2))/x1)) + x1)
<lambdifygenerated-13347>:2: RuntimeWarning: invalid value encountered in log
  return sqrt(x1*(x1 + log(x1 + tanh(x1**2*(_a0_ + _a2_**2*x1**2))/x1)) + x1)
<lambdifygenerated-13347>:2: RuntimeWarning: invalid value encountered in sqrt
  return sqrt(x1*(x1 + log(x1 + tanh(x1**2*(_a0_ + _a2_**2*x1**2))/x1)) + x1)
<lambdifygenerated-13348>:2: RuntimeWarning: invalid value encountered in log
  return sqrt(x1*(x1 + log(x1 + tanh(x1**2*(_a0_ + _a2_**2*x1**2))/x1)) + x1)
<lambdifygenerated-13348>:2: RuntimeWarning: invalid value encountered in sqrt
  return sqrt(x1*(x1 + log(x1 + tanh(x1**2*(_a0_ + _a2_**2*x1**2))/x1)) + x1)
<lambdifygenerated-13349>:2: RuntimeWarning: invalid value encountered in log
  return sqrt(x1*(x1 + log(x1 + tanh(4*x1**2*(_a0_ + _a2_**2*x1**2))/x1)) + x1)
<lambdifygenerated-13349>:2: RuntimeWarning: invalid value encountered in sqrt
  return sqrt(x1*(x1 + log(x1 + tanh(4*x1**2*(_a0_ + _a2_**2*x1**2))/x1)) + x1)
<lambdifygenerated-13350>:2: RuntimeWarning: invalid value encountered in log
  return sqrt(x1*(x1 + log(x1 + tanh(4*x1**2*(_a0_ + _a2_**2*x1**2))/x1)) + x1)
<lambdifygenerated-13350>:2: RuntimeWarning: invalid value encountered in sqrt
  return sqrt(x1*(x1 + log(x1 + tanh(4*x1**2*(_a0_ + _a2_**2*x1**2))/x1)) + x1)
<lambdifygenerated-13351>:2: RuntimeWarning: invalid value encountered in log
  return sqrt(x1*(x1 + log(x1 + tanh((_a0_ + _a2_**2*x1**2)*(x1**2 + x1)**2)/x1)) + x1)
<lambdifygenerated-13351>:2: RuntimeWarning: invalid value encountered in sqrt
  return sqrt(x1*(x1 + log(x1 + tanh((_a0_ + _a2_**2*x1**2)*(x1**2 + x1)**2)/x1)) + x1)
<lambdifygenerated-13352>:2: RuntimeWarning: invalid value encountered in log
  return sqrt(x1*(x1 + log(x1 + tanh((_a0_ + _a2_**2*x1**2)*(x1**2 + x1)**2)/x1)) + x1)
<lambdifygenerated-13352>:2: RuntimeWarning: invalid value encountered in sqrt
  return sqrt(x1*(x1 + log(x1 + tanh((_a0_ + _a2_**2*x1**2)*(x1**2 + x1)**2)/x1)) + x1)
<lambdifygenerated-13353>:2: RuntimeWarning: invalid value encountered in log
  return sqrt(x1*(x1 + log(x1 + tanh((_a0_ + _a2_**2*x1**2)*(_a3_*x1 + x1)**2)/x1)) + x1)
<lambdifygenerated-13353>:2: RuntimeWarning: invalid value encountered in sqrt
  return sqrt(x1*(x1 + log(x1 + tanh((_a0_ + _a2_**2*x1**2)*(_a3_*x1 + x1)**2)/x1)) + x1)
<lambdifygenerated-13354>:2: RuntimeWarning: invalid value encountered in log
  return sqrt(x1*(x1 + log(x1 + tanh((_a0_ + _a2_**2*x1**2)*(_a3_*x1 + x1)**2)/x1)) + x1)
<lambdifygenerated-13354>:2: RuntimeWarning: invalid value encountered in sqrt
  return sqrt(x1*(x1 + log(x1 + tanh((_a0_ + _a2_**2*x1**2)*(_a3_*x1 + x1)**2)/x1)) + x1)
<lambdifygenerated-13355>:2: RuntimeWarning: invalid value encountered in log
  return sqrt(x1*(x1 + log(x1 + tanh((_a0_ + _a2_**2*x1**2)*(_a3_*sin(x1) + x1)**2)/x1)) + x1)
<lambdifygenerated-13355>:2: RuntimeWarning: invalid value encountered in sqrt
  return sqrt(x1*(x1 + log(x1 + tanh((_a0_ + _a2_**2*x1**2)*(_a3_*sin(x1) + x1)**2)/x1)) + x1)
<lambdifygenerated-13356>:2: RuntimeWarning: invalid value encountered in log
  return sqrt(x1*(x1 + log(x1 + tanh((_a0_ + _a2_**2*x1**2)*(_a3_*sin(x1) + x1)**2)/x1)) + x1)
<lambdifygenerated-13356>:2: RuntimeWarning: invalid value encountered in sqrt
  return sqrt(x1*(x1 + log(x1 + tanh((_a0_ + _a2_**2*x1**2)*(_a3_*sin(x1) + x1)**2)/x1)) + x1)
<lambdifygenerated-13357>:2: RuntimeWarning: invalid value encountered in log
  return sqrt(x1*(x1 + log(x1 + tanh((_a0_ + _a2_**2*x1**2)*(_a3_*sin(x1**2) + x1)**2)/x1)) + x1)
<lambdifygenerated-13357>:2: RuntimeWarning: invalid value encountered in sqrt
  return sqrt(x1*(x1 + log(x1 + tanh((_a0_ + _a2_**2*x1**2)*(_a3_*sin(x1**2) + x1)**2)/x1)) + x1)
<lambdifygenerated-13358>:2: RuntimeWarning: invalid value encountered in log
  return sqrt(x1*(x1 + log(x1 + tanh((_a0_ + _a2_**2*x1**2)*(_a3_*sin(x1**2) + x1)**2)/x1)) + x1)
<lambdifygenerated-13358>:2: RuntimeWarning: invalid value encountered in sqrt
  return sqrt(x1*(x1 + log(x1 + tanh((_a0_ + _a2_**2*x1**2)*(_a3_*sin(x1**2) + x1)**2)/x1)) + x1)
<lambdifygenerated-13359>:2: RuntimeWarning: invalid value encountered in log
  return sqrt(x1*(x1 + log(x1 + tanh((_a0_ + _a2_**2*x1**2)*(_a3_*sin(_a0_*x1) + x1)**2)/x1)) + x1)
<lambdifygenerated-13359>:2: RuntimeWarning: invalid value encountered in sqrt
  return sqrt(x1*(x1 + log(x1 + tanh((_a0_ + _a2_**2*x1**2)*(_a3_*sin(_a0_*x1) + x1)**2)/x1)) + x1)
<lambdifygenerated-13360>:2: RuntimeWarning: invalid value encountered in log
  return sqrt(x1*(x1 + log(x1 + tanh((_a0_ + _a2_**2*x1**2)*(_a3_*sin(_a0_*x1) + x1)**2)/x1)) + x1)
<lambdifygenerated-13360>:2: RuntimeWarning: invalid value encountered in sqrt
  return sqrt(x1*(x1 + log(x1 + tanh((_a0_ + _a2_**2*x1**2)*(_a3_*sin(_a0_*x1) + x1)**2)/x1)) + x1)
<lambdifygenerated-13361>:2: RuntimeWarning: invalid value encountered in log
  return sqrt(x1*(x1 + log(x1 + tanh((_a0_ + _a2_**2*x1**2)*(_a3_*sin(_a0_*x1) + x1)**2)/x1)) + x1)
<lambdifygenerated-13361>:2: RuntimeWarning: invalid value encountered in sqrt
  return sqrt(x1*(x1 + log(x1 + tanh((_a0_ + _a2_**2*x1**2)*(_a3_*sin(_a0_*x1) + x1)**2)/x1)) + x1)
<lambdifygenerated-13362>:2: RuntimeWarning: invalid value encountered in log
  return sqrt(x1*(x1 + log(x1 + tanh((_a0_ + _a2_**2*x1**2)*(_a3_*sin(_a0_*x1) + x1)**2)/x1)) + x1)
<lambdifygenerated-13362>:2: RuntimeWarning: invalid value encountered in sqrt
  return sqrt(x1*(x1 + log(x1 + tanh((_a0_ + _a2_**2*x1**2)*(_a3_*sin(_a0_*x1) + x1)**2)/x1)) + x1)
<lambdifygenerated-13363>:2: RuntimeWarning: invalid value encountered in log
  return sqrt(x1*(x1 + log(x1 + tanh((_a0_ + _a2_**2*x1**2)*(_a3_*sin(_a0_*x1) + _a6_)**2)/x1)) + x1)
<lambdifygenerated-13364>:2: RuntimeWarning: invalid value encountered in log
  return sqrt(x1*(x1 + log(x1 + tanh((_a0_ + _a2_**2*x1**2)*(_a3_*sin(_a0_*x1) + _a6_)**2)/x1)) + x1)
<lambdifygenerated-13365>:2: RuntimeWarning: invalid value encountered in log
  return sqrt(x1*(x1 + log(x1 + (1/2)*tanh((_a0_ + _a2_**2*x1**2)*(_a3_*sin(_a0_*x1) + _a6_)**2)/x1)) + x1)
<lambdifygenerated-13366>:2: RuntimeWarning: invalid value encountered in log
  return sqrt(x1*(x1 + log(x1 + (1/2)*tanh((_a0_ + _a2_**2*x1**2)*(_a3_*sin(_a0_*x1) + _a6_)**2)/x1)) + x1)
<lambdifygenerated-13367>:2: RuntimeWarning: invalid value encountered in log
  return sqrt(x1*(x1 + log(x1 + tanh((_a0_ + _a2_**2*x1**2)*(_a3_*sin(_a0_*x1) + _a6_)**2)/(x1 + 1))) + x1)
<lambdifygenerated-13367>:2: RuntimeWarning: invalid value encountered in sqrt
  return sqrt(x1*(x1 + log(x1 + tanh((_a0_ + _a2_**2*x1**2)*(_a3_*sin(_a0_*x1) + _a6_)**2)/(x1 + 1))) + x1)
<lambdifygenerated-13368>:2: RuntimeWarning: invalid value encountered in log
  return sqrt(x1*(x1 + log(x1 + tanh((_a0_ + _a2_**2*x1**2)*(_a3_*sin(_a0_*x1) + _a6_)**2)/(x1 + 1))) + x1)
<lambdifygenerated-13368>:2: RuntimeWarning: invalid value encountered in sqrt
  return sqrt(x1*(x1 + log(x1 + tanh((_a0_ + _a2_**2*x1**2)*(_a3_*sin(_a0_*x1) + _a6_)**2)/(x1 + 1))) + x1)
<lambdifygenerated-13369>:2: RuntimeWarning: invalid value encountered in log
  return sqrt(x1*(x1 + log(x1 + (1/2)*tanh((_a0_ + _a2_**2*x1**2)*(_a3_*sin(_a0_*x1) + _a6_)**2)/x1)) + x1)
<lambdifygenerated-13370>:2: RuntimeWarning: invalid value encountered in log
  return sqrt(x1*(x1 + log(x1 + (1/2)*tanh((_a0_ + _a2_**2*x1**2)*(_a3_*sin(_a0_*x1) + _a6_)**2)/x1)) + x1)
<lambdifygenerated-13371>:2: RuntimeWarning: invalid value encountered in log
  return sqrt(x1*(x1 + log(x1 + tanh((_a0_ + _a2_**2*x1**2)*(_a3_*sin(_a0_*x1) + _a6_)**2)/(_a5_ + x1))) + x1)
<lambdifygenerated-13371>:2: RuntimeWarning: invalid value encountered in sqrt
  return sqrt(x1*(x1 + log(x1 + tanh((_a0_ + _a2_**2*x1**2)*(_a3_*sin(_a0_*x1) + _a6_)**2)/(_a5_ + x1))) + x1)
<lambdifygenerated-13372>:2: RuntimeWarning: invalid value encountered in log
  return sqrt(x1*(x1 + log(x1 + tanh((_a0_ + _a2_**2*x1**2)*(_a3_*sin(_a0_*x1) + _a6_)**2)/(_a5_ + x1))) + x1)
<lambdifygenerated-13372>:2: RuntimeWarning: invalid value encountered in sqrt
  return sqrt(x1*(x1 + log(x1 + tanh((_a0_ + _a2_**2*x1**2)*(_a3_*sin(_a0_*x1) + _a6_)**2)/(_a5_ + x1))) + x1)
<lambdifygenerated-13373>:2: RuntimeWarning: invalid value encountered in log
  return sqrt(x1*(x1 + log(x1 + tanh((_a0_ + _a2_**2*x1**2)*(_a3_*sin(_a0_*x1) + _a6_)**2)/(_a5_*cos(x1)/x1 + x1))) + x1)
<lambdifygenerated-13373>:2: RuntimeWarning: invalid value encountered in sqrt
  return sqrt(x1*(x1 + log(x1 + tanh((_a0_ + _a2_**2*x1**2)*(_a3_*sin(_a0_*x1) + _a6_)**2)/(_a5_*cos(x1)/x1 + x1))) + x1)
<lambdifygenerated-13374>:2: RuntimeWarning: invalid value encountered in log
  return sqrt(x1*(x1 + log(x1 + tanh((_a0_ + _a2_**2*x1**2)*(_a3_*sin(_a0_*x1) + _a6_)**2)/(_a5_*cos(x1)/x1 + x1))) + x1)
<lambdifygenerated-13374>:2: RuntimeWarning: invalid value encountered in sqrt
  return sqrt(x1*(x1 + log(x1 + tanh((_a0_ + _a2_**2*x1**2)*(_a3_*sin(_a0_*x1) + _a6_)**2)/(_a5_*cos(x1)/x1 + x1))) + x1)
<lambdifygenerated-13375>:2: RuntimeWarning: invalid value encountered in log
  return sqrt(x1*(x1 + log(x1 + tanh((_a0_ + _a2_**2*x1**2)*(_a3_*sin(_a0_*x1) + _a6_)**2)/(_a5_*cos(x1)/x1 + x1))) + x1)
<lambdifygenerated-13375>:2: RuntimeWarning: invalid value encountered in sqrt
  return sqrt(x1*(x1 + log(x1 + tanh((_a0_ + _a2_**2*x1**2)*(_a3_*sin(_a0_*x1) + _a6_)**2)/(_a5_*cos(x1)/x1 + x1))) + x1)
<lambdifygenerated-13376>:2: RuntimeWarning: invalid value encountered in log
  return sqrt(x1*(x1 + log(x1 + tanh((_a0_ + _a2_**2*x1**2)*(_a3_*sin(_a0_*x1) + _a6_)**2)/(_a5_*cos(x1)/x1 + x1))) + x1)
<lambdifygenerated-13376>:2: RuntimeWarning: invalid value encountered in sqrt
  return sqrt(x1*(x1 + log(x1 + tanh((_a0_ + _a2_**2*x1**2)*(_a3_*sin(_a0_*x1) + _a6_)**2)/(_a5_*cos(x1)/x1 + x1))) + x1)
<lambdifygenerated-13377>:2: RuntimeWarning: invalid value encountered in log
  return sqrt(x1*(x1 + log(x1 + tanh((_a0_ + _a2_**2*x1**2)*(_a3_*sin(_a0_*x1) + _a6_)**2)/((1/2)*_a5_*cos(x1)/x1 + x1))) + x1)
<lambdifygenerated-13377>:2: RuntimeWarning: invalid value encountered in sqrt
  return sqrt(x1*(x1 + log(x1 + tanh((_a0_ + _a2_**2*x1**2)*(_a3_*sin(_a0_*x1) + _a6_)**2)/((1/2)*_a5_*cos(x1)/x1 + x1))) + x1)
<lambdifygenerated-13378>:2: RuntimeWarning: invalid value encountered in log
  return sqrt(x1*(x1 + log(x1 + tanh((_a0_ + _a2_**2*x1**2)*(_a3_*sin(_a0_*x1) + _a6_)**2)/((1/2)*_a5_*cos(x1)/x1 + x1))) + x1)
<lambdifygenerated-13378>:2: RuntimeWarning: invalid value encountered in sqrt
  return sqrt(x1*(x1 + log(x1 + tanh((_a0_ + _a2_**2*x1**2)*(_a3_*sin(_a0_*x1) + _a6_)**2)/((1/2)*_a5_*cos(x1)/x1 + x1))) + x1)
<lambdifygenerated-13379>:2: RuntimeWarning: invalid value encountered in log
  return sqrt(x1*(x1 + log(x1 + tanh((_a0_ + _a2_**2*x1**2)*(_a3_*sin(_a0_*x1) + _a6_)**2)/(_a5_*cos(x1)/(_a5_ + x1) + x1))) + x1)
<lambdifygenerated-13379>:2: RuntimeWarning: invalid value encountered in sqrt
  return sqrt(x1*(x1 + log(x1 + tanh((_a0_ + _a2_**2*x1**2)*(_a3_*sin(_a0_*x1) + _a6_)**2)/(_a5_*cos(x1)/(_a5_ + x1) + x1))) + x1)
<lambdifygenerated-13380>:2: RuntimeWarning: invalid value encountered in log
  return sqrt(x1*(x1 + log(x1 + tanh((_a0_ + _a2_**2*x1**2)*(_a3_*sin(_a0_*x1) + _a6_)**2)/(_a5_*cos(x1)/(_a5_ + x1) + x1))) + x1)
<lambdifygenerated-13380>:2: RuntimeWarning: invalid value encountered in sqrt
  return sqrt(x1*(x1 + log(x1 + tanh((_a0_ + _a2_**2*x1**2)*(_a3_*sin(_a0_*x1) + _a6_)**2)/(_a5_*cos(x1)/(_a5_ + x1) + x1))) + x1)
<lambdifygenerated-13381>:2: RuntimeWarning: invalid value encountered in log
  return sqrt(x1*(x1 + log(x1 + tanh((_a0_ + _a2_**2*x1**2)*(_a3_*sin(_a0_*x1) + _a6_)**2)/(_a5_*cos(x1)/(_a0_ + _a5_) + x1))) + x1)
<lambdifygenerated-13381>:2: RuntimeWarning: invalid value encountered in sqrt
  return sqrt(x1*(x1 + log(x1 + tanh((_a0_ + _a2_**2*x1**2)*(_a3_*sin(_a0_*x1) + _a6_)**2)/(_a5_*cos(x1)/(_a0_ + _a5_) + x1))) + x1)
<lambdifygenerated-13382>:2: RuntimeWarning: invalid value encountered in log
  return sqrt(x1*(x1 + log(x1 + tanh((_a0_ + _a2_**2*x1**2)*(_a3_*sin(_a0_*x1) + _a6_)**2)/(_a5_*cos(x1)/(_a0_ + _a5_) + x1))) + x1)
<lambdifygenerated-13382>:2: RuntimeWarning: invalid value encountered in sqrt
  return sqrt(x1*(x1 + log(x1 + tanh((_a0_ + _a2_**2*x1**2)*(_a3_*sin(_a0_*x1) + _a6_)**2)/(_a5_*cos(x1)/(_a0_ + _a5_) + x1))) + x1)
<lambdifygenerated-13383>:2: RuntimeWarning: invalid value encountered in log
  return sqrt(x1*(x1 + log(x1 + tanh((_a0_ + _a2_**2*x1**2)*(_a3_*sin(_a0_*x1) + _a6_)**2)/(_a4_ + _a5_*cos(x1)/(_a0_ + _a5_)))) + x1)
<lambdifygenerated-13383>:2: RuntimeWarning: invalid value encountered in sqrt
  return sqrt(x1*(x1 + log(x1 + tanh((_a0_ + _a2_**2*x1**2)*(_a3_*sin(_a0_*x1) + _a6_)**2)/(_a4_ + _a5_*cos(x1)/(_a0_ + _a5_)))) + x1)
<lambdifygenerated-13384>:2: RuntimeWarning: invalid value encountered in log
  return sqrt(x1*(x1 + log(x1 + tanh((_a0_ + _a2_**2*x1**2)*(_a3_*sin(_a0_*x1) + _a6_)**2)/(_a4_ + _a5_*cos(x1)/(_a0_ + _a5_)))) + x1)
<lambdifygenerated-13384>:2: RuntimeWarning: invalid value encountered in sqrt

interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.661298  4.0  0.664972  0.661121
3746  0.998  0.661485  4.0  0.665241  0.661323
3747  0.998  0.661672  4.0  0.665511  0.661525
3748  0.999  0.661858  4.0  0.665781  0.661727

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.662232  4.0  0.666322  0.662131
3751  1.002  0.662419  4.0  0.666594  0.662333
3752  1.002  0.662605  4.0  0.666866  0.662534
3753  1.003  0.662792  4.0  0.667138  0.662736

3750

/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-13453>:2: RuntimeWarning: overflow encountered in exp
  return x1*(x1 + cos(_a1_ + (-_a5_ + cos(x1))*exp(_a2_*_a5_ + _a2_ + x1)))
<lambdifygenerated-13453>:2: RuntimeWarning: invalid value encountered in cos
  return x1*(x1 + cos(_a1_ + (-_a5_ + cos(x1))*exp(_a2_*_a5_ + _a2_ + x1)))

interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.956369  5.0  0.956122  0.950913
3746  0.998  0.956259  5.0  0.956008  0.950697
3747  0.998  0.956150  5.0  0.955895  0.950480
3748  0.999  0.956040  5.0  0.955782  0.950262

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.955822  5.0  0.955556  0.949823
3751  1.002  0.955712  5.0  0.955443  0.949603
3752  1.002  0.955603  5.0  0.955330  0.949382
3753  1.003  0.955493  5.0  0.955218  0.949160

3750

<lambdifygenerated-13537>:2: RuntimeWarning: invalid value encountered in power
  return sin(2*x1 + abs(x1 + tan(x1 + exp(x1*(x1 + x1**x1)))))
<lambdifygenerated-13538>:2: RuntimeWarning: invalid value encountered in power
  return sin(2*x1 + abs(x1 + tan(x1 + exp(x1*(x1 + x1**x1)))))
<lambdifygenerated-13539>:2: RuntimeWarning: invalid value encountered in power
  return sin(2*x1 + abs(x1 + tan(x1 + exp(x1*(x1 + tanh(x1)**x1)))))
<lambdifygenerated-13540>:2: RuntimeWarning: invalid value encountered in power
  return sin(2*x1 + abs(x1 + tan(x1 + exp(x1*(x1 + tanh(x1)**x1)))))
<lambdifygenerated-13541>:2: RuntimeWarning: invalid value encountered in power
  return sin(2*x1 + abs(x1 + tan(x1 + exp(x1*(x1 + (-tanh(x1))**x1)))))
<lambdifygenerated-13542>:2: RuntimeWarning: invalid value encountered in power
  return sin(2*x1 + abs(x1 + tan(x1 + exp(x1*(x1 + (-tanh(x1))**x1)))))
<lambdifygenerated-13543>:2: RuntimeWarning: invalid value encountered in power
  return sin(2*x1 + abs(x1 + tan(x1 + exp(x1*(x1 + (-tanh(1))**x1)))))
<lambdifygenerated-13544>:2: RuntimeWarning: invalid value encountered in power
  return sin(2*x1 + abs(x1 + tan(x1 + exp(x1*(x1 + (-tanh(1))**x1)))))
<lambdifygenerated-13545>:2: RuntimeWarning: invalid value encountered in power
  return sin(2*x1 + abs(x1 + tan(x1 + exp(x1*(x1 + (-tanh(x1))**x1)))))
<lambdifygenerated-13546>:2: RuntimeWarning: invalid value encountered in power
  return sin(2*x1 + abs(x1 + tan(x1 + exp(x1*(x1 + (-tanh(x1))**x1)))))
<lambdifygenerated-13547>:2: RuntimeWarning: invalid value encountered in power
  return sin(2*x1 + abs(x1 + tan(x1 + exp(x1*(x1 + (-tanh(x1**x1))**x1)))))
<lambdifygenerated-13548>:2: RuntimeWarning: invalid value encountered in power
  return sin(2*x1 + abs(x1 + tan(x1 + exp(x1*(x1 + (-tanh(x1**x1))**x1)))))
<lambdifygenerated-13549>:2: RuntimeWarning: invalid value encountered in power
  return sin(2*x1 + abs(x1 + tan(x1 + exp(x1*(x1 + (-tanh(_a3_**x1))**x1)))))
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-13550>:2: RuntimeWarning: invalid value encountered in power
  return sin(2*x1 + abs(x1 + tan(x1 + exp(x1*(x1 + (-tanh(_a3_**x1))**x1)))))
<lambdifygenerated-13551>:2: RuntimeWarning: invalid value encountered in power
  return sin(2*x1 + abs(x1 + tan(x1 + exp(x1*(x1 + (-tanh(_a3_**x1))**x1)))))
<lambdifygenerated-13552>:2: RuntimeWarning: invalid value encountered in power
  return sin(2*x1 + abs(x1 + tan(x1 + exp(x1*(x1 + (-tanh(_a3_**x1))**x1)))))
<lambdifygenerated-13553>:2: RuntimeWarning: invalid value encountered in power
  return sin(2*x1 + abs(x1 + tan(x1 + exp(x1*(x1 + (-tanh(_a3_**x1*x1))**x1)))))
<lambdifygenerated-13554>:2: RuntimeWarning: invalid value encountered in power
  return sin(2*x1 + abs(x1 + tan(x1 + exp(x1*(x1 + (-tanh(_a3_**x1*x1))**x1)))))
<lambdifygenerated-13555>:2: RuntimeWarning: invalid value encountered in power
  return sin(2*x1 + abs(x1 + tan(x1 + exp(x1*(x1 + (-tanh(_a1_**2*_a3_**x1/x1))**x1)))))
<lambdifygenerated-13556>:2: RuntimeWarning: invalid value encountered in power
  return sin(2*x1 + abs(x1 + tan(x1 + exp(x1*(x1 + (-tanh(_a1_**2*_a3_**x1/x1))**x1)))))
<lambdifygenerated-13557>:2: RuntimeWarning: invalid value encountered in power
  return sin(2*x1 + abs(x1 + tan(x1 + exp(x1*(x1 + (-tanh((1/2)*_a1_**2*_a3_**x1/x1))**x1)))))
<lambdifygenerated-13558>:2: RuntimeWarning: invalid value encountered in power
  return sin(2*x1 + abs(x1 + tan(x1 + exp(x1*(x1 + (-tanh((1/2)*_a1_**2*_a3_**x1/x1))**x1)))))
<lambdifygenerated-13559>:2: RuntimeWarning: invalid value encountered in power
  return sin(2*x1 + abs(x1 + tan(x1 + exp(x1*(x1 + (-tanh(_a1_**2*_a3_**x1/(_a1_ + x1)))**x1)))))
<lambdifygenerated-13560>:2: RuntimeWarning: invalid value encountered in power
  return sin(2*x1 + abs(x1 + tan(x1 + exp(x1*(x1 + (-tanh(_a1_**2*_a3_**x1/(_a1_ + x1)))**x1)))))
<lambdifygenerated-13561>:2: RuntimeWarning: invalid value encountered in power
  return sin(2*x1 + abs(x1 + tan(x1 + exp(x1*(x1 + (-tanh(_a1_**2*_a3_**x1/(_a1_ + x1**2)))**x1)))))
<lambdifygenerated-13562>:2: RuntimeWarning: invalid value encountered in power
  return sin(2*x1 + abs(x1 + tan(x1 + exp(x1*(x1 + (-tanh(_a1_**2*_a3_**x1/(_a1_ + x1**2)))**x1)))))
<lambdifygenerated-13563>:2: RuntimeWarning: invalid value encountered in power
  return sin(2*x1 + abs(x1 + tan(x1 + exp(x1*(x1 + (-tanh(_a1_**2*_a3_**x1/(_a1_ + 2*x1**2)))**x1)))))
<lambdifygenerated-13564>:2: RuntimeWarning: invalid value encountered in power
  return sin(2*x1 + abs(x1 + tan(x1 + exp(x1*(x1 + (-tanh(_a1_**2*_a3_**x1/(_a1_ + 2*x1**2)))**x1)))))
<lambdifygenerated-13565>:2: RuntimeWarning: invalid value encountered in power
  return sin(2*x1 + abs(x1 + tan(x1 + exp(x1*(x1 + (-tanh(_a1_**2*_a3_**x1/(_a1_ + x1*(_a2_ + x1))))**x1)))))
<lambdifygenerated-13566>:2: RuntimeWarning: invalid value encountered in power
  return sin(2*x1 + abs(x1 + tan(x1 + exp(x1*(x1 + (-tanh(_a1_**2*_a3_**x1/(_a1_ + x1*(_a2_ + x1))))**x1)))))
<lambdifygenerated-13567>:2: RuntimeWarning: invalid value encountered in power
  return sin(2*x1 + abs(x1 + tan(x1 + exp(x1*(x1 + (-tanh(_a1_**2*_a3_**x1/(_a1_ + x1*(_a2_ + _a6_))))**x1)))))
<lambdifygenerated-13568>:2: RuntimeWarning: invalid value encountered in power
  return sin(2*x1 + abs(x1 + tan(x1 + exp(x1*(x1 + (-tanh(_a1_**2*_a3_**x1/(_a1_ + x1*(_a2_ + _a6_))))**x1)))))
<lambdifygenerated-13569>:2: RuntimeWarning: invalid value encountered in power
  return sin(2*x1 + abs(x1 + tan(x1 + exp(x1*(x1 + (-tanh(_a1_**2*_a3_**x1/(_a1_ + x1**2*(_a2_ + _a6_))))**x1)))))
<lambdifygenerated-13570>:2: RuntimeWarning: invalid value encountered in power
  return sin(2*x1 + abs(x1 + tan(x1 + exp(x1*(x1 + (-tanh(_a1_**2*_a3_**x1/(_a1_ + x1**2*(_a2_ + _a6_))))**x1)))))
<lambdifygenerated-13571>:2: RuntimeWarning: invalid value encountered in power
  return sin(2*x1 + abs(x1 + tan(x1 + exp(x1*(x1 + (-tanh(_a1_**2*_a3_**x1/(_a1_ + x1*(_a2_ + _a6_))))**x1)))))
<lambdifygenerated-13572>:2: RuntimeWarning: invalid value encountered in power
  return sin(2*x1 + abs(x1 + tan(x1 + exp(x1*(x1 + (-tanh(_a1_**2*_a3_**x1/(_a1_ + x1*(_a2_ + _a6_))))**x1)))))
<lambdifygenerated-13573>:2: RuntimeWarning: invalid value encountered in power
  return sin(2*x1 + abs(x1 + tan(x1 + exp(x1*(x1 + (-tanh(_a1_**2*_a3_**x1/(_a1_ + (_a2_ + _a6_)*tanh(x1))))**x1)))))
<lambdifygenerated-13574>:2: RuntimeWarning: invalid value encountered in power
  return sin(2*x1 + abs(x1 + tan(x1 + exp(x1*(x1 + (-tanh(_a1_**2*_a3_**x1/(_a1_ + (_a2_ + _a6_)*tanh(x1))))**x1)))))
<lambdifygenerated-13575>:2: RuntimeWarning: invalid value encountered in power
  return sin(2*x1 + abs(x1 + tan(x1 + exp(x1*(x1 + (-tanh(_a1_**2*_a3_**x1/(_a1_ + (_a2_ + _a6_)*tanh(x1))))**x1)))))
<lambdifygenerated-13576>:2: RuntimeWarning: invalid value encountered in power
  return sin(2*x1 + abs(x1 + tan(x1 + exp(x1*(x1 + (-tanh(_a1_**2*_a3_**x1/(_a1_ + (_a2_ + _a6_)*tanh(x1))))**x1)))))
<lambdifygenerated-13577>:2: RuntimeWarning: invalid value encountered in power
  return sin(2*x1 + abs(x1 + tan(x1 + exp(x1*(x1 + (-tanh(_a1_**2*_a3_**x1/(_a1_ + x1*(_a2_ + _a6_)*tanh(x1)/_a3_)))**x1)))))
<lambdifygenerated-13578>:2: RuntimeWarning: invalid value encountered in power
  return sin(2*x1 + abs(x1 + tan(x1 + exp(x1*(x1 + (-tanh(_a1_**2*_a3_**x1/(_a1_ + x1*(_a2_ + _a6_)*tanh(x1)/_a3_)))**x1)))))
<lambdifygenerated-13579>:2: RuntimeWarning: invalid value encountered in power
  return sin(2*x1 + abs(x1 + tan(x1 + exp(x1*(x1 + (-tanh(_a1_**2*_a3_**x1/(_a1_ + x1*(_a2_ + _a6_)*tanh(x1)/_a3_)))**x1)))))
<lambdifygenerated-13580>:2: RuntimeWarning: invalid value encountered in power
  return sin(2*x1 + abs(x1 + tan(x1 + exp(x1*(x1 + (-tanh(_a1_**2*_a3_**x1/(_a1_ + x1*(_a2_ + _a6_)*tanh(x1)/_a3_)))**x1)))))
<lambdifygenerated-13581>:2: RuntimeWarning: invalid value encountered in power
  return sin(2*x1 + abs(x1 + tan(x1 + exp(x1*(x1 + (-tanh(_a1_**2*_a3_**x1/(_a1_ + x1*(_a2_ + _a6_)*tanh(x1)/_a3_)))**(2*x1))))))
<lambdifygenerated-13582>:2: RuntimeWarning: invalid value encountered in power
  return sin(2*x1 + abs(x1 + tan(x1 + exp(x1*(x1 + (-tanh(_a1_**2*_a3_**x1/(_a1_ + x1*(_a2_ + _a6_)*tanh(x1)/_a3_)))**(2*x1))))))
<lambdifygenerated-13583>:2: RuntimeWarning: invalid value encountered in power
  return sin(2*x1 + abs(x1 + tan(x1 + exp(x1*(x1 + (-tanh(_a1_**2*_a3_**x1/(_a1_ + x1*(_a2_ + _a6_)*tanh(x1)/_a3_)))**(_a4_ + x1))))))
<lambdifygenerated-13584>:2: RuntimeWarning: invalid value encountered in power
  return sin(2*x1 + abs(x1 + tan(x1 + exp(x1*(x1 + (-tanh(_a1_**2*_a3_**x1/(_a1_ + x1*(_a2_ + _a6_)*tanh(x1)/_a3_)))**(_a4_ + x1))))))
<lambdifygenerated-13585>:2: RuntimeWarning: invalid value encountered in power
  return sin(2*x1 + abs(x1 + tan(x1 + exp(x1*(x1 + (-tanh(_a1_**2*_a3_**x1/(_a1_ + x1*(_a2_ + _a6_)*tanh(x1)/_a3_)))**(_a0_ + _a4_))))))
<lambdifygenerated-13587>:2: RuntimeWarning: invalid value encountered in power
  return sin(2*x1 + abs(x1 + tan(x1 + exp(x1*(2*x1 + (-tanh(_a1_**2*_a3_**x1/(_a1_ + x1*(_a2_ + _a6_)*tanh(x1)/_a3_)))**(_a0_ + _a4_))))))
<lambdifygenerated-13589>:2: RuntimeWarning: invalid value encountered in power
  return sin(2*x1 + abs(x1 + tan(x1 + exp(x1*(_a7_ + x1 + (-tanh(_a1_**2*_a3_**x1/(_a1_ + x1*(_a2_ + _a6_)*tanh(x1)/_a3_)))**(_a0_ + _a4_))))))
<lambdifygenerated-13591>:2: RuntimeWarning: invalid value encountered in power
  return sin(2*x1 + abs(x1 + tan(x1 + exp(x1*(2*_a7_ + (-tanh(_a1_**2*_a3_**x1/(_a1_ + x1*(_a2_ + _a6_)*tanh(x1)/_a3_)))**(_a0_ + _a4_))))))
<lambdifygenerated-13593>:2: RuntimeWarning: invalid value encountered in power
  return sin(2*x1 + abs(x1 + tan(x1 + exp(_a1_*(2*_a7_ + (-tanh(_a1_**2*_a3_**x1/(_a1_ + x1*(_a2_ + _a6_)*tanh(x1)/_a3_)))**(_a0_ + _a4_))))))
<lambdifygenerated-13595>:2: RuntimeWarning: invalid value encountered in power
  return sin(2*x1 + abs(x1 + tan(x1**2 + exp(_a1_*(2*_a7_ + (-tanh(_a1_**2*_a3_**x1/(_a1_ + x1*(_a2_ + _a6_)*tanh(x1)/_a3_)))**(_a0_ + _a4_))))))
<lambdifygenerated-13599>:2: RuntimeWarning: invalid value encountered in power
  return sin(2*x1 + abs(x1 + tan(_a5_*x1 + exp(_a1_*(2*_a7_ + (-tanh(_a1_**2*_a3_**x1/(_a1_ + x1*(_a2_ + _a6_)*tanh(x1)/_a3_)))**(_a0_ + _a4_))))))
<lambdifygenerated-13601>:2: RuntimeWarning: invalid value encountered in power
  return sin(2*x1 + abs(_a6_ + tan(_a5_*x1 + exp(_a1_*(2*_a7_ + (-tanh(_a1_**2*_a3_**x1/(_a1_ + x1*(_a2_ + _a6_)*tanh(x1)/_a3_)))**(_a0_ + _a4_))))))
<lambdifygenerated-13603>:2: RuntimeWarning: invalid value encountered in power
  return sin(x1**3 + x1 + abs(_a6_ + tan(_a5_*x1 + exp(_a1_*(2*_a7_ + (-tanh(_a1_**2*_a3_**x1/(_a1_ + x1*(_a2_ + _a6_)*tanh(x1)/_a3_)))**(_a0_ + _a4_))))))
<lambdifygenerated-13605>:2: RuntimeWarning: invalid value encountered in power
  return sin(x1**6 + x1 + abs(_a6_ + tan(_a5_*x1 + exp(_a1_*(2*_a7_ + (-tanh(_a1_**2*_a3_**x1/(_a1_ + x1*(_a2_ + _a6_)*tanh(x1)/_a3_)))**(_a0_ + _a4_))))))
<lambdifygenerated-13607>:2: RuntimeWarning: invalid value encountered in power
  return sin(_a2_**3*x1**3 + x1 + abs(_a6_ + tan(_a5_*x1 + exp(_a1_*(2*_a7_ + (-tanh(_a1_**2*_a3_**x1/(_a1_ + x1*(_a2_ + _a6_)*tanh(x1)/_a3_)))**(_a0_ + _a4_))))))
<lambdifygenerated-13609>:2: RuntimeWarning: invalid value encountered in power
  return sin(_a2_**3*x1**6 + x1 + abs(_a6_ + tan(_a5_*x1 + exp(_a1_*(2*_a7_ + (-tanh(_a1_**2*_a3_**x1/(_a1_ + x1*(_a2_ + _a6_)*tanh(x1)/_a3_)))**(_a0_ + _a4_))))))
<lambdifygenerated-13613>:2: RuntimeWarning: invalid value encountered in power
  return sin(_a2_**6*x1**3 + x1 + abs(_a6_ + tan(_a5_*x1 + exp(_a1_*(2*_a7_ + (-tanh(_a1_**2*_a3_**x1/(_a1_ + x1*(_a2_ + _a6_)*tanh(x1)/_a3_)))**(_a0_ + _a4_))))))
<lambdifygenerated-13615>:2: RuntimeWarning: invalid value encountered in power
  return sin(_a2_**6*x1**3 + _a7_ + abs(_a6_ + tan(_a5_*x1 + exp(_a1_*(2*_a7_ + (-tanh(_a1_**2*_a3_**x1/(_a1_ + x1*(_a2_ + _a6_)*tanh(x1)/_a3_)))**(_a0_ + _a4_))))))
<lambdifygenerated-13619>:2: RuntimeWarning: invalid value encountered in power
  return sin(_a2_**6*x1**3 + _a7_ + abs(_a6_ + tan(_a5_*x1 + exp(_a1_*(2*_a7_ + (-tanh(_a1_**2*_a3_**x1/(_a1_ + x1*(_a2_ + _a6_)*tanh(x1)/_a3_)))**(_a0_ + _a4_))))))

interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.428260  6.0  0.425197  0.422745
3746  0.998  0.428367  6.0  0.425268  0.422790
3747  0.998  0.428474  6.0  0.425338  0.422834
3748  0.999  0.428581  6.0  0.425409  0.422879

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.428794  6.0  0.425551  0.422968
3751  1.002  0.428901  6.0  0.425622  0.423013
3752  1.002  0.429008  6.0  0.425693  0.423058
3753  1.003  0.429115  6.0  0.425765  0.423103

3750

<lambdifygenerated-13655>:2: RuntimeWarning: invalid value encountered in power
  return x1*tan(x1*(x1*(x1 + cos(x1*(x1*(2*x1 + x1**x1) + x1)))**3 + x1) + x1) + x1
<lambdifygenerated-13656>:2: RuntimeWarning: invalid value encountered in power
  return x1*tan(x1*(x1*(x1 + cos(x1*(x1*(2*x1 + x1**x1) + x1)))**3 + x1) + x1) + x1
<lambdifygenerated-13657>:2: RuntimeWarning: divide by zero encountered in power
  return x1*tan(x1*(x1*(x1 + cos(x1*(x1*(2*x1 + fac(x1)**x1) + x1)))**3 + x1) + x1) + x1
<lambdifygenerated-13657>:2: RuntimeWarning: invalid value encountered in cos
  return x1*tan(x1*(x1*(x1 + cos(x1*(x1*(2*x1 + fac(x1)**x1) + x1)))**3 + x1) + x1) + x1
<lambdifygenerated-13658>:2: RuntimeWarning: divide by zero encountered in power
  return x1*tan(x1*(x1*(x1 + cos(x1*(x1*(2*x1 + fac(x1)**x1) + x1)))**3 + x1) + x1) + x1
<lambdifygenerated-13658>:2: RuntimeWarning: invalid value encountered in cos
  return x1*tan(x1*(x1*(x1 + cos(x1*(x1*(2*x1 + fac(x1)**x1) + x1)))**3 + x1) + x1) + x1
<lambdifygenerated-13659>:2: RuntimeWarning: divide by zero encountered in power
  return x1*tan(x1*(x1*(x1 + cos(x1*(x1*(2*x1 + fac(x1)**x1) + x1)))**3 + x1) + x1) + x1
<lambdifygenerated-13659>:2: RuntimeWarning: invalid value encountered in cos
  return x1*tan(x1*(x1*(x1 + cos(x1*(x1*(2*x1 + fac(x1)**x1) + x1)))**3 + x1) + x1) + x1
<lambdifygenerated-13660>:2: RuntimeWarning: divide by zero encountered in power
  return x1*tan(x1*(x1*(x1 + cos(x1*(x1*(2*x1 + fac(x1)**x1) + x1)))**3 + x1) + x1) + x1
<lambdifygenerated-13660>:2: RuntimeWarning: invalid value encountered in cos
  return x1*tan(x1*(x1*(x1 + cos(x1*(x1*(2*x1 + fac(x1)**x1) + x1)))**3 + x1) + x1) + x1
<lambdifygenerated-13663>:2: RuntimeWarning: divide by zero encountered in power
  return x1*tan(x1*(x1*(x1 + cos(x1*(x1*(2*x1 + fac(x1)**(_a7_*x1)) + x1)))**3 + x1) + x1) + x1
<lambdifygenerated-13663>:2: RuntimeWarning: invalid value encountered in cos
  return x1*tan(x1*(x1*(x1 + cos(x1*(x1*(2*x1 + fac(x1)**(_a7_*x1)) + x1)))**3 + x1) + x1) + x1
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-13664>:2: RuntimeWarning: divide by zero encountered in power
  return x1*tan(x1*(x1*(x1 + cos(x1*(x1*(2*x1 + fac(x1)**(_a7_*x1)) + x1)))**3 + x1) + x1) + x1
<lambdifygenerated-13664>:2: RuntimeWarning: invalid value encountered in cos
  return x1*tan(x1*(x1*(x1 + cos(x1*(x1*(2*x1 + fac(x1)**(_a7_*x1)) + x1)))**3 + x1) + x1) + x1
<lambdifygenerated-13665>:2: RuntimeWarning: divide by zero encountered in power
  return x1*tan(x1*(x1*(x1 + cos(x1*(x1*(2*x1 + fac(x1)**(_a0_*_a7_)) + x1)))**3 + x1) + x1) + x1
<lambdifygenerated-13665>:2: RuntimeWarning: overflow encountered in power
  return x1*tan(x1*(x1*(x1 + cos(x1*(x1*(2*x1 + fac(x1)**(_a0_*_a7_)) + x1)))**3 + x1) + x1) + x1
<lambdifygenerated-13665>:2: RuntimeWarning: invalid value encountered in cos
  return x1*tan(x1*(x1*(x1 + cos(x1*(x1*(2*x1 + fac(x1)**(_a0_*_a7_)) + x1)))**3 + x1) + x1) + x1
<lambdifygenerated-13667>:2: RuntimeWarning: divide by zero encountered in power
  return x1*tan(x1*(x1*(x1 + cos(x1*(x1*(_a2_ + x1 + fac(x1)**(_a0_*_a7_)) + x1)))**3 + x1) + x1) + x1
<lambdifygenerated-13667>:2: RuntimeWarning: overflow encountered in power
  return x1*tan(x1*(x1*(x1 + cos(x1*(x1*(_a2_ + x1 + fac(x1)**(_a0_*_a7_)) + x1)))**3 + x1) + x1) + x1
<lambdifygenerated-13667>:2: RuntimeWarning: invalid value encountered in cos
  return x1*tan(x1*(x1*(x1 + cos(x1*(x1*(_a2_ + x1 + fac(x1)**(_a0_*_a7_)) + x1)))**3 + x1) + x1) + x1
<lambdifygenerated-13669>:2: RuntimeWarning: divide by zero encountered in power
  return x1*tan(x1*(x1*(x1 + cos(x1*(x1*(2*_a2_ + fac(x1)**(_a0_*_a7_)) + x1)))**3 + x1) + x1) + x1
<lambdifygenerated-13669>:2: RuntimeWarning: overflow encountered in power
  return x1*tan(x1*(x1*(x1 + cos(x1*(x1*(2*_a2_ + fac(x1)**(_a0_*_a7_)) + x1)))**3 + x1) + x1) + x1
<lambdifygenerated-13669>:2: RuntimeWarning: invalid value encountered in cos
  return x1*tan(x1*(x1*(x1 + cos(x1*(x1*(2*_a2_ + fac(x1)**(_a0_*_a7_)) + x1)))**3 + x1) + x1) + x1
<lambdifygenerated-13671>:2: RuntimeWarning: divide by zero encountered in power
  return x1*tan(x1*(x1*(x1 + cos(x1*(2*x1*(2*_a2_ + fac(x1)**(_a0_*_a7_)) + x1)))**3 + x1) + x1) + x1
<lambdifygenerated-13671>:2: RuntimeWarning: overflow encountered in power
  return x1*tan(x1*(x1*(x1 + cos(x1*(2*x1*(2*_a2_ + fac(x1)**(_a0_*_a7_)) + x1)))**3 + x1) + x1) + x1
<lambdifygenerated-13671>:2: RuntimeWarning: invalid value encountered in cos
  return x1*tan(x1*(x1*(x1 + cos(x1*(2*x1*(2*_a2_ + fac(x1)**(_a0_*_a7_)) + x1)))**3 + x1) + x1) + x1
<lambdifygenerated-13671>:2: RuntimeWarning: overflow encountered in multiply
  return x1*tan(x1*(x1*(x1 + cos(x1*(2*x1*(2*_a2_ + fac(x1)**(_a0_*_a7_)) + x1)))**3 + x1) + x1) + x1
<lambdifygenerated-13673>:2: RuntimeWarning: divide by zero encountered in power
  return x1*tan(x1*(x1*(x1 + cos(x1*(x1 + (2*_a2_ + fac(x1)**(_a0_*_a7_))*(_a5_ + x1))))**3 + x1) + x1) + x1
<lambdifygenerated-13673>:2: RuntimeWarning: overflow encountered in power
  return x1*tan(x1*(x1*(x1 + cos(x1*(x1 + (2*_a2_ + fac(x1)**(_a0_*_a7_))*(_a5_ + x1))))**3 + x1) + x1) + x1
<lambdifygenerated-13673>:2: RuntimeWarning: invalid value encountered in cos
  return x1*tan(x1*(x1*(x1 + cos(x1*(x1 + (2*_a2_ + fac(x1)**(_a0_*_a7_))*(_a5_ + x1))))**3 + x1) + x1) + x1
<lambdifygenerated-13677>:2: RuntimeWarning: divide by zero encountered in power
  return x1*tan(x1*(x1*(x1 + cos(x1*(_a1_ + (2*_a2_ + fac(x1)**(_a0_*_a7_))*(_a5_ + x1))))**3 + x1) + x1) + x1
<lambdifygenerated-13677>:2: RuntimeWarning: overflow encountered in power
  return x1*tan(x1*(x1*(x1 + cos(x1*(_a1_ + (2*_a2_ + fac(x1)**(_a0_*_a7_))*(_a5_ + x1))))**3 + x1) + x1) + x1
<lambdifygenerated-13677>:2: RuntimeWarning: invalid value encountered in cos
  return x1*tan(x1*(x1*(x1 + cos(x1*(_a1_ + (2*_a2_ + fac(x1)**(_a0_*_a7_))*(_a5_ + x1))))**3 + x1) + x1) + x1
<lambdifygenerated-13679>:2: RuntimeWarning: divide by zero encountered in power
  return x1*tan(x1*(x1*(x1 + cos(_a2_*(_a1_ + (2*_a2_ + fac(x1)**(_a0_*_a7_))*(_a5_ + x1))))**3 + x1) + x1) + x1
<lambdifygenerated-13679>:2: RuntimeWarning: overflow encountered in power
  return x1*tan(x1*(x1*(x1 + cos(_a2_*(_a1_ + (2*_a2_ + fac(x1)**(_a0_*_a7_))*(_a5_ + x1))))**3 + x1) + x1) + x1
<lambdifygenerated-13679>:2: RuntimeWarning: invalid value encountered in cos
  return x1*tan(x1*(x1*(x1 + cos(_a2_*(_a1_ + (2*_a2_ + fac(x1)**(_a0_*_a7_))*(_a5_ + x1))))**3 + x1) + x1) + x1
<lambdifygenerated-13679>:2: RuntimeWarning: overflow encountered in multiply
  return x1*tan(x1*(x1*(x1 + cos(_a2_*(_a1_ + (2*_a2_ + fac(x1)**(_a0_*_a7_))*(_a5_ + x1))))**3 + x1) + x1) + x1
<lambdifygenerated-13689>:2: RuntimeWarning: divide by zero encountered in power
  return x1*tan(x1*(_a0_*_a3_*(_a0_ + cos(_a2_*(_a1_ + (2*_a2_ + fac(x1)**(_a0_*_a7_))*(_a5_ + x1))))**3 + _a6_) + x1) + x1
<lambdifygenerated-13689>:2: RuntimeWarning: invalid value encountered in cos
  return x1*tan(x1*(_a0_*_a3_*(_a0_ + cos(_a2_*(_a1_ + (2*_a2_ + fac(x1)**(_a0_*_a7_))*(_a5_ + x1))))**3 + _a6_) + x1) + x1
<lambdifygenerated-13691>:2: RuntimeWarning: divide by zero encountered in power
  return x1*tan(_a0_*_a3_*(_a0_ + cos(_a2_*(_a1_ + (2*_a2_ + fac(x1)**(_a0_*_a7_))*(_a5_ + x1))))**3 + _a6_ + x1) + x1
<lambdifygenerated-13691>:2: RuntimeWarning: invalid value encountered in cos
  return x1*tan(_a0_*_a3_*(_a0_ + cos(_a2_*(_a1_ + (2*_a2_ + fac(x1)**(_a0_*_a7_))*(_a5_ + x1))))**3 + _a6_ + x1) + x1
<lambdifygenerated-13693>:2: RuntimeWarning: divide by zero encountered in power
  return x1*tan(_a5_*(_a0_*_a3_*(_a0_ + cos(_a2_*(_a1_ + (2*_a2_ + fac(x1)**(_a0_*_a7_))*(_a5_ + x1))))**3 + _a6_)/x1 + x1) + x1
<lambdifygenerated-13693>:2: RuntimeWarning: invalid value encountered in cos
  return x1*tan(_a5_*(_a0_*_a3_*(_a0_ + cos(_a2_*(_a1_ + (2*_a2_ + fac(x1)**(_a0_*_a7_))*(_a5_ + x1))))**3 + _a6_)/x1 + x1) + x1
<lambdifygenerated-13695>:2: RuntimeWarning: divide by zero encountered in power
  return x1*tan(_a5_*(_a0_*_a3_*(_a0_ + cos(_a2_*(_a1_ + (2*_a2_ + fac(x1)**(_a0_*_a7_))*(_a5_ + x1))))**3 + _a6_) + x1) + x1
<lambdifygenerated-13695>:2: RuntimeWarning: invalid value encountered in cos
  return x1*tan(_a5_*(_a0_*_a3_*(_a0_ + cos(_a2_*(_a1_ + (2*_a2_ + fac(x1)**(_a0_*_a7_))*(_a5_ + x1))))**3 + _a6_) + x1) + x1
<lambdifygenerated-13699>:2: RuntimeWarning: invalid value encountered in power
  return x1*tan(x1 + _a5_*x1**x1*(_a0_*_a3_*(_a0_ + cos(_a2_*(_a1_ + (2*_a2_ + fac(x1)**(_a0_*_a7_))*(_a5_ + x1))))**3 + _a6_)/_a4_) + x1
<lambdifygenerated-13700>:2: RuntimeWarning: invalid value encountered in power
  return x1*tan(x1 + _a5_*x1**x1*(_a0_*_a3_*(_a0_ + cos(_a2_*(_a1_ + (2*_a2_ + fac(x1)**(_a0_*_a7_))*(_a5_ + x1))))**3 + _a6_)/_a4_) + x1
<lambdifygenerated-13701>:2: RuntimeWarning: invalid value encountered in power
  return x1*tan(x1 + _a5_*(_a0_*_a3_*(_a0_ + cos(_a2_*(_a1_ + (2*_a2_ + fac(x1)**(_a0_*_a7_))*(_a5_ + x1))))**3 + _a6_)*tanh(x1)**x1/_a4_) + x1
<lambdifygenerated-13702>:2: RuntimeWarning: invalid value encountered in power
  return x1*tan(x1 + _a5_*(_a0_*_a3_*(_a0_ + cos(_a2_*(_a1_ + (2*_a2_ + fac(x1)**(_a0_*_a7_))*(_a5_ + x1))))**3 + _a6_)*tanh(x1)**x1/_a4_) + x1
<lambdifygenerated-13703>:2: RuntimeWarning: invalid value encountered in power
  return x1*tan(x1 + _a5_*(_a0_*_a3_*(_a0_ + cos(_a2_*(_a1_ + (2*_a2_ + fac(x1)**(_a0_*_a7_))*(_a5_ + x1))))**3 + _a6_)*tanh(x1**x1)**x1/_a4_) + x1
<lambdifygenerated-13704>:2: RuntimeWarning: invalid value encountered in power
  return x1*tan(x1 + _a5_*(_a0_*_a3_*(_a0_ + cos(_a2_*(_a1_ + (2*_a2_ + fac(x1)**(_a0_*_a7_))*(_a5_ + x1))))**3 + _a6_)*tanh(x1**x1)**x1/_a4_) + x1

interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.173654  7.0  0.179574  0.176985
3746  0.998  0.173884  7.0  0.179867  0.177287
3747  0.998  0.174114  7.0  0.180161  0.177589
3748  0.999  0.174344  7.0  0.180455  0.177892

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.174804  7.0  0.181043  0.178501
3751  1.002  0.175034  7.0  0.181337  0.178806
3752  1.002  0.175264  7.0  0.181631  0.179112
3753  1.003  0.175494  7.0  0.181926  0.179419

3750

<lambdifygenerated-13745>:2: RuntimeWarning: overflow encountered in exp
  return x1 + exp(x1 + (_a0_ + x1)/x1)
/usr/local/lib/python3.10/dist-packages/scipy/optimize/_minpack_py.py:1017: RuntimeWarning: overflow encountered in square
  cost = np.sum(infodict['fvec'] ** 2)
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
/usr/local/lib/python3.10/dist-packages/pandas/core/arraylike.py:399: RuntimeWarning: overflow encountered in square
  result = getattr(ufunc, method)(*inputs, **kwargs)
<lambdifygenerated-13746>:2: RuntimeWarning: overflow encountered in exp
  return x1 + exp(x1 + (_a0_ + x1)/x1)
<lambdifygenerated-13757>:2: RuntimeWarning: overflow encountered in exp
  return x1 + exp(x1 + (_a0_*(_a6_ + x1)/cosh(_a6_*x1) + x1)/x1)
<lambdifygenerated-13758>:2: RuntimeWarning: overflow encountered in exp
  return x1 + exp(x1 + (_a0_*(_a6_ + x1)/cosh(_a6_*x1) + x1)/x1)
<lambdifygenerated-13759>:2: RuntimeWarning: overflow encountered in exp
  return x1 + exp(x1 + (_a0_*(_a6_ + x1)/cosh(_a6_*x1) + x1)/x1)
<lambdifygenerated-13760>:2: RuntimeWarning: overflow encountered in exp
  return x1 + exp(x1 + (_a0_*(_a6_ + x1)/cosh(_a6_*x1) + x1)/x1)
<lambdifygenerated-13761>:2: RuntimeWarning: overflow encountered in exp
  return x1 + exp(x1 + (_a0_*(_a6_ + x1)/cosh(_a6_*x1) + cos(x1))/x1)
<lambdifygenerated-13762>:2: RuntimeWarning: overflow encountered in exp
  return x1 + exp(x1 + (_a0_*(_a6_ + x1)/cosh(_a6_*x1) + cos(x1))/x1)
<lambdifygenerated-13763>:2: RuntimeWarning: overflow encountered in exp
  return x1 + exp(x1 + (_a0_*(_a6_ + x1)/cosh(_a6_*x1) + cos(2*x1))/x1)
<lambdifygenerated-13764>:2: RuntimeWarning: overflow encountered in exp
  return x1 + exp(x1 + (_a0_*(_a6_ + x1)/cosh(_a6_*x1) + cos(2*x1))/x1)
<lambdifygenerated-13765>:2: RuntimeWarning: overflow encountered in exp
  return x1 + exp(x1 + (_a0_*(_a6_ + x1)/cosh(_a6_*x1) + cos(x1 + cosh(x1)))/x1)
<lambdifygenerated-13766>:2: RuntimeWarning: overflow encountered in exp
  return x1 + exp(x1 + (_a0_*(_a6_ + x1)/cosh(_a6_*x1) + cos(x1 + cosh(x1)))/x1)
<lambdifygenerated-13767>:2: RuntimeWarning: overflow encountered in exp
  return x1 + exp(x1 + (_a0_*(_a6_ + x1)/cosh(_a6_*x1) + cos(x1 + cosh(2*x1)))/x1)
<lambdifygenerated-13768>:2: RuntimeWarning: overflow encountered in exp
  return x1 + exp(x1 + (_a0_*(_a6_ + x1)/cosh(_a6_*x1) + cos(x1 + cosh(2*x1)))/x1)
<lambdifygenerated-13769>:2: RuntimeWarning: overflow encountered in exp
  return x1 + exp(x1 + (_a0_*(_a6_ + x1)/cosh(_a6_*x1) + cos(x1 + cosh(_a0_ + x1)))/x1)
<lambdifygenerated-13770>:2: RuntimeWarning: overflow encountered in exp
  return x1 + exp(x1 + (_a0_*(_a6_ + x1)/cosh(_a6_*x1) + cos(x1 + cosh(_a0_ + x1)))/x1)
<lambdifygenerated-13771>:2: RuntimeWarning: overflow encountered in exp
  return x1 + exp(x1 + (_a0_*(_a6_ + x1)/cosh(_a6_*x1) + cos(x1 + cosh(_a0_ + tanh(x1))))/x1)
<lambdifygenerated-13772>:2: RuntimeWarning: overflow encountered in exp
  return x1 + exp(x1 + (_a0_*(_a6_ + x1)/cosh(_a6_*x1) + cos(x1 + cosh(_a0_ + tanh(x1))))/x1)
<lambdifygenerated-13773>:2: RuntimeWarning: overflow encountered in exp
  return x1 + exp(x1 + (_a0_*(_a6_ + x1)/cosh(_a6_*x1) + cos(x1 + cosh(_a0_ + tanh(x1**2))))/x1)
<lambdifygenerated-13774>:2: RuntimeWarning: overflow encountered in exp
  return x1 + exp(x1 + (_a0_*(_a6_ + x1)/cosh(_a6_*x1) + cos(x1 + cosh(_a0_ + tanh(x1**2))))/x1)
<lambdifygenerated-13775>:2: RuntimeWarning: overflow encountered in exp
  return x1 + exp(x1 + (_a0_*(_a6_ + x1)/cosh(_a6_*x1) + cos(x1 + cosh(_a0_ + tanh(x1**2))))/x1)
<lambdifygenerated-13776>:2: RuntimeWarning: overflow encountered in exp
  return x1 + exp(x1 + (_a0_*(_a6_ + x1)/cosh(_a6_*x1) + cos(x1 + cosh(_a0_ + tanh(x1**2))))/x1)
<lambdifygenerated-13777>:2: RuntimeWarning: overflow encountered in exp
  return x1 + exp(x1 + (_a0_*(_a6_ + x1)/cosh(_a6_*x1) + cos(x1 + cosh(_a0_ + tanh(x1**3))))/x1)
<lambdifygenerated-13778>:2: RuntimeWarning: overflow encountered in exp
  return x1 + exp(x1 + (_a0_*(_a6_ + x1)/cosh(_a6_*x1) + cos(x1 + cosh(_a0_ + tanh(x1**3))))/x1)
<lambdifygenerated-13779>:2: RuntimeWarning: overflow encountered in exp
  return x1 + exp(x1 + (_a0_*(_a6_ + x1)/cosh(_a6_*x1) + cos(x1 + cosh(_a0_ + tanh(x1**4))))/x1)
<lambdifygenerated-13780>:2: RuntimeWarning: overflow encountered in exp
  return x1 + exp(x1 + (_a0_*(_a6_ + x1)/cosh(_a6_*x1) + cos(x1 + cosh(_a0_ + tanh(x1**4))))/x1)
<lambdifygenerated-13781>:2: RuntimeWarning: overflow encountered in exp
  return x1 + exp(x1 + (_a0_*(_a6_ + x1)/cosh(_a6_*x1) + cos(x1 + cosh(_a0_ + tanh(_a7_*x1**3))))/x1)
<lambdifygenerated-13782>:2: RuntimeWarning: overflow encountered in exp
  return x1 + exp(x1 + (_a0_*(_a6_ + x1)/cosh(_a6_*x1) + cos(x1 + cosh(_a0_ + tanh(_a7_*x1**3))))/x1)
<lambdifygenerated-13783>:2: RuntimeWarning: overflow encountered in exp
  return x1 + exp(x1 + (_a0_*(_a6_ + x1)/cosh(_a6_*x1) + cos(x1 + cosh(_a0_ + tanh(_a1_*_a7_*x1**2))))/x1)
<lambdifygenerated-13784>:2: RuntimeWarning: overflow encountered in exp
  return x1 + exp(x1 + (_a0_*(_a6_ + x1)/cosh(_a6_*x1) + cos(x1 + cosh(_a0_ + tanh(_a1_*_a7_*x1**2))))/x1)
<lambdifygenerated-13785>:2: RuntimeWarning: overflow encountered in exp
  return x1 + exp(x1 + (_a0_*(_a6_ + x1)/cosh(_a6_*x1) + cos(x1 + cosh(_a0_ + tanh(_a1_*_a4_*_a7_*x1))))/x1)
<lambdifygenerated-13786>:2: RuntimeWarning: overflow encountered in exp
  return x1 + exp(x1 + (_a0_*(_a6_ + x1)/cosh(_a6_*x1) + cos(x1 + cosh(_a0_ + tanh(_a1_*_a4_*_a7_*x1))))/x1)
<lambdifygenerated-13787>:2: RuntimeWarning: overflow encountered in exp
  return x1 + exp(x1 + (_a0_*(_a6_ + x1)/cosh(_a6_*x1) + cos(2*x1 + cosh(_a0_ + tanh(_a1_*_a4_*_a7_*x1))))/x1)
<lambdifygenerated-13788>:2: RuntimeWarning: overflow encountered in exp
  return x1 + exp(x1 + (_a0_*(_a6_ + x1)/cosh(_a6_*x1) + cos(2*x1 + cosh(_a0_ + tanh(_a1_*_a4_*_a7_*x1))))/x1)
<lambdifygenerated-13789>:2: RuntimeWarning: overflow encountered in exp
  return x1 + exp(x1 + (_a0_*(_a6_ + x1)/cosh(_a6_*x1) + cos(x1 + fac(x1) + cosh(_a0_ + tanh(_a1_*_a4_*_a7_*x1))))/x1)
<lambdifygenerated-13790>:2: RuntimeWarning: overflow encountered in exp
  return x1 + exp(x1 + (_a0_*(_a6_ + x1)/cosh(_a6_*x1) + cos(x1 + fac(x1) + cosh(_a0_ + tanh(_a1_*_a4_*_a7_*x1))))/x1)
<lambdifygenerated-13791>:2: RuntimeWarning: overflow encountered in exp
  return x1 + exp(x1 + (_a0_*(_a6_ + x1)/cosh(_a6_*x1) + cos(x1 + fac(2*x1) + cosh(_a0_ + tanh(_a1_*_a4_*_a7_*x1))))/x1)
<lambdifygenerated-13792>:2: RuntimeWarning: overflow encountered in exp
  return x1 + exp(x1 + (_a0_*(_a6_ + x1)/cosh(_a6_*x1) + cos(x1 + fac(2*x1) + cosh(_a0_ + tanh(_a1_*_a4_*_a7_*x1))))/x1)
<lambdifygenerated-13793>:2: RuntimeWarning: overflow encountered in exp
  return x1 + exp(x1 + (_a0_*(_a6_ + x1)/cosh(_a6_*x1) + cos(x1 + fac(2*x1) + cosh(_a0_ + tanh(_a1_*_a4_*_a7_*x1))))/x1)
<lambdifygenerated-13794>:2: RuntimeWarning: overflow encountered in exp
  return x1 + exp(x1 + (_a0_*(_a6_ + x1)/cosh(_a6_*x1) + cos(x1 + fac(2*x1) + cosh(_a0_ + tanh(_a1_*_a4_*_a7_*x1))))/x1)
<lambdifygenerated-13795>:2: RuntimeWarning: overflow encountered in exp
  return x1 + exp(x1 + (_a0_*(_a6_ + x1)/cosh(_a6_*x1) + cos(x1 + fac(0) + cosh(_a0_ + tanh(_a1_*_a4_*_a7_*x1))))/x1)
<lambdifygenerated-13796>:2: RuntimeWarning: overflow encountered in exp
  return x1 + exp(x1 + (_a0_*(_a6_ + x1)/cosh(_a6_*x1) + cos(x1 + fac(0) + cosh(_a0_ + tanh(_a1_*_a4_*_a7_*x1))))/x1)
<lambdifygenerated-13797>:2: RuntimeWarning: overflow encountered in exp
  return x1 + exp(x1 + (_a0_*(_a6_ + x1)/cosh(_a6_*x1) + cos(x1 + fac(-_a2_ + x1) + cosh(_a0_ + tanh(_a1_*_a4_*_a7_*x1))))/x1)
<lambdifygenerated-13798>:2: RuntimeWarning: overflow encountered in exp
  return x1 + exp(x1 + (_a0_*(_a6_ + x1)/cosh(_a6_*x1) + cos(x1 + fac(-_a2_ + x1) + cosh(_a0_ + tanh(_a1_*_a4_*_a7_*x1))))/x1)
<lambdifygenerated-13799>:2: RuntimeWarning: overflow encountered in exp
  return x1 + exp(x1 + (_a0_*(_a6_ + x1)/cosh(_a6_*x1) + cos(x1**2 + fac(-_a2_ + x1) + cosh(_a0_ + tanh(_a1_*_a4_*_a7_*x1))))/x1)
<lambdifygenerated-13800>:2: RuntimeWarning: overflow encountered in exp
  return x1 + exp(x1 + (_a0_*(_a6_ + x1)/cosh(_a6_*x1) + cos(x1**2 + fac(-_a2_ + x1) + cosh(_a0_ + tanh(_a1_*_a4_*_a7_*x1))))/x1)
<lambdifygenerated-13801>:2: RuntimeWarning: overflow encountered in exp
  return x1 + exp(x1 + (_a0_*(_a6_ + x1)/cosh(_a6_*x1) + cos(x1**3 + fac(-_a2_ + x1) + cosh(_a0_ + tanh(_a1_*_a4_*_a7_*x1))))/x1)
<lambdifygenerated-13802>:2: RuntimeWarning: overflow encountered in exp
  return x1 + exp(x1 + (_a0_*(_a6_ + x1)/cosh(_a6_*x1) + cos(x1**3 + fac(-_a2_ + x1) + cosh(_a0_ + tanh(_a1_*_a4_*_a7_*x1))))/x1)
<lambdifygenerated-13803>:2: RuntimeWarning: overflow encountered in exp
  return x1 + exp(x1 + (_a0_*(_a6_ + x1)/cosh(_a6_*x1) + cos(_a5_*x1**2 + fac(-_a2_ + x1) + cosh(_a0_ + tanh(_a1_*_a4_*_a7_*x1))))/x1)
<lambdifygenerated-13804>:2: RuntimeWarning: overflow encountered in exp
  return x1 + exp(x1 + (_a0_*(_a6_ + x1)/cosh(_a6_*x1) + cos(_a5_*x1**2 + fac(-_a2_ + x1) + cosh(_a0_ + tanh(_a1_*_a4_*_a7_*x1))))/x1)
<lambdifygenerated-13805>:2: RuntimeWarning: overflow encountered in exp
  return x1 + exp(x1 + (_a0_*(_a6_ + x1)/cosh(_a6_*x1) + cos(_a5_*x1 + fac(-_a2_ + x1) + cosh(_a0_ + tanh(_a1_*_a4_*_a7_*x1))))/x1)

interpolation

<lambdifygenerated-13806>:2: RuntimeWarning: overflow encountered in exp
  return x1 + exp(x1 + (_a0_*(_a6_ + x1)/cosh(_a6_*x1) + cos(_a5_*x1 + fac(-_a2_ + x1) + cosh(_a0_ + tanh(_a1_*_a4_*_a7_*x1))))/x1)
<lambdifygenerated-13807>:2: RuntimeWarning: overflow encountered in exp
  return x1 + exp(x1 + (_a0_*(_a6_ + x1)/cosh(_a6_*x1) + cos(_a4_*_a5_ + fac(-_a2_ + x1) + cosh(_a0_ + tanh(_a1_*_a4_*_a7_*x1))))/x1)
<lambdifygenerated-13808>:2: RuntimeWarning: overflow encountered in exp
  return x1 + exp(x1 + (_a0_*(_a6_ + x1)/cosh(_a6_*x1) + cos(_a4_*_a5_ + fac(-_a2_ + x1) + cosh(_a0_ + tanh(_a1_*_a4_*_a7_*x1))))/x1)
<lambdifygenerated-13809>:2: RuntimeWarning: overflow encountered in exp
  return x1 + exp(x1 + (_a0_*(_a6_ + x1)/cosh(_a6_*x1) + cos(_a4_*_a5_*x1/_a7_ + fac(-_a2_ + x1) + cosh(_a0_ + tanh(_a1_*_a4_*_a7_*x1))))/x1)
<lambdifygenerated-13810>:2: RuntimeWarning: overflow encountered in exp
  return x1 + exp(x1 + (_a0_*(_a6_ + x1)/cosh(_a6_*x1) + cos(_a4_*_a5_*x1/_a7_ + fac(-_a2_ + x1) + cosh(_a0_ + tanh(_a1_*_a4_*_a7_*x1))))/x1)
<lambdifygenerated-13811>:2: RuntimeWarning: overflow encountered in exp
  return x1 + exp(x1 + (_a0_*(_a6_ + x1)/cosh(_a6_*x1) + cos(_a4_*_a5_*x1/_a7_ + fac(-_a2_ + x1) + cosh(_a0_ + tanh(_a1_*_a4_*_a7_*x1))))/x1)
<lambdifygenerated-13812>:2: RuntimeWarning: overflow encountered in exp
  return x1 + exp(x1 + (_a0_*(_a6_ + x1)/cosh(_a6_*x1) + cos(_a4_*_a5_*x1/_a7_ + fac(-_a2_ + x1) + cosh(_a0_ + tanh(_a1_*_a4_*_a7_*x1))))/x1)
<lambdifygenerated-13815>:2: RuntimeWarning: overflow encountered in exp
  return x1 + exp(x1 + (_a0_*(_a6_ + x1)/cosh(_a6_*x1) + cos(_a4_*_a5_*x1/_a7_ + fac(-_a2_ + x1) + cosh(_a0_ + tanh(_a1_*_a4_*_a7_*x1))))*exp(-2*x1))
<lambdifygenerated-13816>:2: RuntimeWarning: overflow encountered in exp
  return x1 + exp(x1 + (_a0_*(_a6_ + x1)/cosh(_a6_*x1) + cos(_a4_*_a5_*x1/_a7_ + fac(-_a2_ + x1) + cosh(_a0_ + tanh(_a1_*_a4_*_a7_*x1))))*exp(-2*x1))
<lambdifygenerated-13817>:2: RuntimeWarning: overflow encountered in exp
  return x1 + exp(x1 + (_a0_*(_a6_ + x1)/cosh(_a6_*x1) + cos(_a4_*_a5_*x1/_a7_ + fac(-_a2_ + x1) + cosh(_a0_ + tanh(_a1_*_a4_*_a7_*x1))))*exp(-4*x1))
<lambdifygenerated-13818>:2: RuntimeWarning: overflow encountered in exp
  return x1 + exp(x1 + (_a0_*(_a6_ + x1)/cosh(_a6_*x1) + cos(_a4_*_a5_*x1/_a7_ + fac(-_a2_ + x1) + cosh(_a0_ + tanh(_a1_*_a4_*_a7_*x1))))*exp(-4*x1))
<lambdifygenerated-13819>:2: RuntimeWarning: invalid value encountered in power
  return x1 + exp(x1 + (_a0_*(_a6_ + x1)/cosh(_a6_*x1) + cos(_a4_*_a5_*x1/_a7_ + fac(-_a2_ + x1) + cosh(_a0_ + tanh(_a1_*_a4_*_a7_*x1))))*exp(-2*x1 - 2*x1**x1))
<lambdifygenerated-13820>:2: RuntimeWarning: invalid value encountered in power
  return x1 + exp(x1 + (_a0_*(_a6_ + x1)/cosh(_a6_*x1) + cos(_a4_*_a5_*x1/_a7_ + fac(-_a2_ + x1) + cosh(_a0_ + tanh(_a1_*_a4_*_a7_*x1))))*exp(-2*x1 - 2*x1**x1))
<lambdifygenerated-13821>:2: RuntimeWarning: overflow encountered in exp
  return x1 + exp(x1 + (_a0_*(_a6_ + x1)/cosh(_a6_*x1) + cos(_a4_*_a5_*x1/_a7_ + fac(-_a2_ + x1) + cosh(_a0_ + tanh(_a1_*_a4_*_a7_*x1))))*exp(-2*_a3_**x1 - 2*x1))
<lambdifygenerated-13822>:2: RuntimeWarning: overflow encountered in exp
  return x1 + exp(x1 + (_a0_*(_a6_ + x1)/cosh(_a6_*x1) + cos(_a4_*_a5_*x1/_a7_ + fac(-_a2_ + x1) + cosh(_a0_ + tanh(_a1_*_a4_*_a7_*x1))))*exp(-2*_a3_**x1 - 2*x1))
<lambdifygenerated-13823>:2: RuntimeWarning: overflow encountered in exp
  return x1 + exp(x1 + (_a0_*(_a6_ + x1)/cosh(_a6_*x1) + cos(_a4_*_a5_*x1/_a7_ + fac(-_a2_ + x1) + cosh(_a0_ + tanh(_a1_*_a4_*_a7_*x1))))*exp(-2*_a3_**x1 - 2*x1))
<lambdifygenerated-13824>:2: RuntimeWarning: overflow encountered in exp
  return x1 + exp(x1 + (_a0_*(_a6_ + x1)/cosh(_a6_*x1) + cos(_a4_*_a5_*x1/_a7_ + fac(-_a2_ + x1) + cosh(_a0_ + tanh(_a1_*_a4_*_a7_*x1))))*exp(-2*_a3_**x1 - 2*x1))
<lambdifygenerated-13825>:2: RuntimeWarning: overflow encountered in exp
  return x1 + exp(x1 + (_a0_*(_a6_ + x1)/cosh(_a6_*x1) + cos(_a4_*_a5_*x1/_a7_ + fac(-_a2_ + x1) + cosh(_a0_ + tanh(_a1_*_a4_*_a7_*x1))))*exp(-2*_a1_ - 2*_a3_**x1))
<lambdifygenerated-13826>:2: RuntimeWarning: overflow encountered in exp
  return x1 + exp(x1 + (_a0_*(_a6_ + x1)/cosh(_a6_*x1) + cos(_a4_*_a5_*x1/_a7_ + fac(-_a2_ + x1) + cosh(_a0_ + tanh(_a1_*_a4_*_a7_*x1))))*exp(-2*_a1_ - 2*_a3_**x1))
<lambdifygenerated-13827>:2: RuntimeWarning: overflow encountered in exp
  return x1 + exp(_a2_ + (_a0_*(_a6_ + x1)/cosh(_a6_*x1) + cos(_a4_*_a5_*x1/_a7_ + fac(-_a2_ + x1) + cosh(_a0_ + tanh(_a1_*_a4_*_a7_*x1))))*exp(-2*_a1_ - 2*_a3_**x1))
<lambdifygenerated-13828>:2: RuntimeWarning: overflow encountered in exp
  return x1 + exp(_a2_ + (_a0_*(_a6_ + x1)/cosh(_a6_*x1) + cos(_a4_*_a5_*x1/_a7_ + fac(-_a2_ + x1) + cosh(_a0_ + tanh(_a1_*_a4_*_a7_*x1))))*exp(-2*_a1_ - 2*_a3_**x1))
<lambdifygenerated-13829>:2: RuntimeWarning: overflow encountered in exp
  return _a4_ + exp(_a2_ + (_a0_*(_a6_ + x1)/cosh(_a6_*x1) + cos(_a4_*_a5_*x1/_a7_ + fac(-_a2_ + x1) + cosh(_a0_ + tanh(_a1_*_a4_*_a7_*x1))))*exp(-2*_a1_ - 2*_a3_**x1))
<lambdifygenerated-13830>:2: RuntimeWarning: overflow encountered in exp
  return _a4_ + exp(_a2_ + (_a0_*(_a6_ + x1)/cosh(_a6_*x1) + cos(_a4_*_a5_*x1/_a7_ + fac(-_a2_ + x1) + cosh(_a0_ + tanh(_a1_*_a4_*_a7_*x1))))*exp(-2*_a1_ - 2*_a3_**x1))
<lambdifygenerated-13831>:2: RuntimeWarning: overflow encountered in exp
  return _a4_ + exp(_a2_ + (_a0_*(_a6_ + x1)/cosh(_a6_*x1) + cos(_a4_*_a5_*x1/_a7_ + fac(-_a2_ + x1) + cosh(_a0_ + tanh(_a1_*_a4_*_a7_*x1))))*exp(-2*_a1_ - 2*_a3_**x1))
<lambdifygenerated-13832>:2: RuntimeWarning: overflow encountered in exp
  return _a4_ + exp(_a2_ + (_a0_*(_a6_ + x1)/cosh(_a6_*x1) + cos(_a4_*_a5_*x1/_a7_ + fac(-_a2_ + x1) + cosh(_a0_ + tanh(_a1_*_a4_*_a7_*x1))))*exp(-2*_a1_ - 2*_a3_**x1))
<lambdifygenerated-13833>:2: RuntimeWarning: overflow encountered in exp
  return _a4_ + exp(_a2_ + (_a0_*(_a6_ + x1)/cosh(_a6_*x1) + cos(_a4_*_a5_*x1/_a7_ + fac(-_a2_ + x1) + cosh(_a0_ + tanh(_a1_*_a4_*_a7_*x1))))*exp(-2*_a1_ - 2*_a3_**x1))
<lambdifygenerated-13834>:2: RuntimeWarning: overflow encountered in exp
  return _a4_ + exp(_a2_ + (_a0_*(_a6_ + x1)/cosh(_a6_*x1) + cos(_a4_*_a5_*x1/_a7_ + fac(-_a2_ + x1) + cosh(_a0_ + tanh(_a1_*_a4_*_a7_*x1))))*exp(-2*_a1_ - 2*_a3_**x1))

         x1         y  rep    ymodel      ybms
3745  0.997  0.261188  8.0  0.259516  0.254691
3746  0.998  0.261362  8.0  0.259739  0.254834
3747  0.998  0.261535  8.0  0.259961  0.254976
3748  0.999  0.261709  8.0  0.260183  0.255117

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.262056  8.0  0.260627  0.255398
3751  1.002  0.262229  8.0  0.260849  0.255538
3752  1.002  0.262402  8.0  0.261070  0.255677
3753  1.003  0.262576  8.0  0.261291  0.255815

3750

<lambdifygenerated-13877>:2: RuntimeWarning: invalid value encountered in power
  return x1*cos(2*x1 + tan(x1 + sin(_a2_ + _a3_*(_a4_ + x1)/(_a2_*(_a0_ + x1**x1)))))
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-13878>:2: RuntimeWarning: invalid value encountered in power
  return x1*cos(2*x1 + tan(x1 + sin(_a2_ + _a3_*(_a4_ + x1)/(_a2_*(_a0_ + x1**x1)))))
<lambdifygenerated-13885>:2: RuntimeWarning: invalid value encountered in power
  return x1*cos(2*x1 + tan(x1**x1 + sin(_a2_ + _a3_*(_a4_ + x1)/(_a2_*(_a0_ + (_a5_**2)**x1)))))
<lambdifygenerated-13886>:2: RuntimeWarning: invalid value encountered in power
  return x1*cos(2*x1 + tan(x1**x1 + sin(_a2_ + _a3_*(_a4_ + x1)/(_a2_*(_a0_ + (_a5_**2)**x1)))))
<lambdifygenerated-13895>:2: RuntimeWarning: invalid value encountered in power
  return x1*cos(2*x1 + tan(_a0_**(abs(x1)/_a0_) + sin(_a2_ + _a3_*(_a4_ + x1)/(_a2_*(_a0_ + (_a5_**2)**x1)))))
<lambdifygenerated-13895>:2: RuntimeWarning: overflow encountered in multiply
  return x1*cos(2*x1 + tan(_a0_**(abs(x1)/_a0_) + sin(_a2_ + _a3_*(_a4_ + x1)/(_a2_*(_a0_ + (_a5_**2)**x1)))))
<lambdifygenerated-13895>:2: RuntimeWarning: overflow encountered in power
  return x1*cos(2*x1 + tan(_a0_**(abs(x1)/_a0_) + sin(_a2_ + _a3_*(_a4_ + x1)/(_a2_*(_a0_ + (_a5_**2)**x1)))))

interpolation

<lambdifygenerated-13896>:2: RuntimeWarning: overflow encountered in power
  return x1*cos(2*x1 + tan(_a0_**(abs(x1)/_a0_) + sin(_a2_ + _a3_*(_a4_ + x1)/(_a2_*(_a0_ + (_a5_**2)**x1)))))
<lambdifygenerated-13896>:2: RuntimeWarning: overflow encountered in multiply
  return x1*cos(2*x1 + tan(_a0_**(abs(x1)/_a0_) + sin(_a2_ + _a3_*(_a4_ + x1)/(_a2_*(_a0_ + (_a5_**2)**x1)))))
<lambdifygenerated-13897>:2: RuntimeWarning: overflow encountered in power
  return x1*cos(_a7_ + x1 + tan(_a0_**(abs(x1)/_a0_) + sin(_a2_ + _a3_*(_a4_ + x1)/(_a2_*(_a0_ + (_a5_**2)**x1)))))
<lambdifygenerated-13897>:2: RuntimeWarning: overflow encountered in multiply
  return x1*cos(_a7_ + x1 + tan(_a0_**(abs(x1)/_a0_) + sin(_a2_ + _a3_*(_a4_ + x1)/(_a2_*(_a0_ + (_a5_**2)**x1)))))
<lambdifygenerated-13898>:2: RuntimeWarning: overflow encountered in multiply
  return x1*cos(_a7_ + x1 + tan(_a0_**(abs(x1)/_a0_) + sin(_a2_ + _a3_*(_a4_ + x1)/(_a2_*(_a0_ + (_a5_**2)**x1)))))
<lambdifygenerated-13899>:2: RuntimeWarning: overflow encountered in multiply
  return x1*cos(_a3_ + _a7_ + tan(_a0_**(abs(x1)/_a0_) + sin(_a2_ + _a3_*(_a4_ + x1)/(_a2_*(_a0_ + (_a5_**2)**x1)))))

         x1        y  rep    ymodel      ybms
3745  0.997  0.64259  9.0  0.647224  0.638641
3746  0.998  0.64247  9.0  0.647116  0.638452
3747  0.998  0.64235  9.0  0.647008  0.638262
3748  0.999  0.64223  9.0  0.646901  0.638072

extrapolation

         x1        y  rep    ymodel      ybms
3750  1.001  0.64199  9.0  0.646686  0.637691
3751  1.002  0.64187  9.0  0.646578  0.637501
3752  1.002  0.64175  9.0  0.646471  0.637311
3753  1.003  0.64163  9.0  0.646364  0.637120

3750

/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-13955>:2: RuntimeWarning: overflow encountered in sinh
  return x1**3*(2*x1 + exp(x1*tanh(_a0_*_a1_*sinh(_a2_*_a3_*x1) + x1) + x1))**2
<lambdifygenerated-13955>:2: RuntimeWarning: overflow encountered in multiply
  return x1**3*(2*x1 + exp(x1*tanh(_a0_*_a1_*sinh(_a2_*_a3_*x1) + x1) + x1))**2
<lambdifygenerated-13957>:2: RuntimeWarning: overflow encountered in sinh
  return x1**3*(2*x1 + exp(x1*tanh(_a0_*_a1_*_a5_*sinh(_a2_*_a3_*x1)/x1 + x1) + x1))**2
<lambdifygenerated-13957>:2: RuntimeWarning: overflow encountered in multiply
  return x1**3*(2*x1 + exp(x1*tanh(_a0_*_a1_*_a5_*sinh(_a2_*_a3_*x1)/x1 + x1) + x1))**2
<lambdifygenerated-13957>:2: RuntimeWarning: overflow encountered in divide
  return x1**3*(2*x1 + exp(x1*tanh(_a0_*_a1_*_a5_*sinh(_a2_*_a3_*x1)/x1 + x1) + x1))**2
<lambdifygenerated-13958>:2: RuntimeWarning: overflow encountered in sinh
  return x1**3*(2*x1 + exp(x1*tanh(_a0_*_a1_*_a5_*sinh(_a2_*_a3_*x1)/x1 + x1) + x1))**2
<lambdifygenerated-13958>:2: RuntimeWarning: overflow encountered in multiply
  return x1**3*(2*x1 + exp(x1*tanh(_a0_*_a1_*_a5_*sinh(_a2_*_a3_*x1)/x1 + x1) + x1))**2
<lambdifygenerated-13958>:2: RuntimeWarning: overflow encountered in divide
  return x1**3*(2*x1 + exp(x1*tanh(_a0_*_a1_*_a5_*sinh(_a2_*_a3_*x1)/x1 + x1) + x1))**2
<lambdifygenerated-13959>:2: RuntimeWarning: overflow encountered in sinh
  return x1**3*(2*x1 + exp(x1*tanh(_a0_*_a1_*_a5_*sinh(_a2_*_a3_*x1)/_a7_ + x1) + x1))**2
<lambdifygenerated-13959>:2: RuntimeWarning: overflow encountered in multiply
  return x1**3*(2*x1 + exp(x1*tanh(_a0_*_a1_*_a5_*sinh(_a2_*_a3_*x1)/_a7_ + x1) + x1))**2
<lambdifygenerated-13960>:2: RuntimeWarning: overflow encountered in sinh
  return x1**3*(2*x1 + exp(x1*tanh(_a0_*_a1_*_a5_*sinh(_a2_*_a3_*x1)/_a7_ + x1) + x1))**2
<lambdifygenerated-13960>:2: RuntimeWarning: overflow encountered in multiply
  return x1**3*(2*x1 + exp(x1*tanh(_a0_*_a1_*_a5_*sinh(_a2_*_a3_*x1)/_a7_ + x1) + x1))**2
<lambdifygenerated-13961>:2: RuntimeWarning: overflow encountered in sinh
  return x1**3*(2*x1 + exp(x1*tanh(_a0_*_a1_*_a5_*sinh(_a2_*_a3_*x1)/_a7_ + _a4_) + x1))**2
<lambdifygenerated-13961>:2: RuntimeWarning: overflow encountered in multiply
  return x1**3*(2*x1 + exp(x1*tanh(_a0_*_a1_*_a5_*sinh(_a2_*_a3_*x1)/_a7_ + _a4_) + x1))**2
<lambdifygenerated-13962>:2: RuntimeWarning: overflow encountered in sinh
  return x1**3*(2*x1 + exp(x1*tanh(_a0_*_a1_*_a5_*sinh(_a2_*_a3_*x1)/_a7_ + _a4_) + x1))**2
<lambdifygenerated-13962>:2: RuntimeWarning: overflow encountered in multiply
  return x1**3*(2*x1 + exp(x1*tanh(_a0_*_a1_*_a5_*sinh(_a2_*_a3_*x1)/_a7_ + _a4_) + x1))**2
<lambdifygenerated-13963>:2: RuntimeWarning: overflow encountered in sinh
  return x1**3*(2*x1 + exp(_a0_*tanh(_a0_*_a1_*_a5_*sinh(_a2_*_a3_*x1)/_a7_ + _a4_) + x1))**2
<lambdifygenerated-13963>:2: RuntimeWarning: overflow encountered in multiply
  return x1**3*(2*x1 + exp(_a0_*tanh(_a0_*_a1_*_a5_*sinh(_a2_*_a3_*x1)/_a7_ + _a4_) + x1))**2
<lambdifygenerated-13964>:2: RuntimeWarning: overflow encountered in sinh
  return x1**3*(2*x1 + exp(_a0_*tanh(_a0_*_a1_*_a5_*sinh(_a2_*_a3_*x1)/_a7_ + _a4_) + x1))**2
<lambdifygenerated-13965>:2: RuntimeWarning: overflow encountered in sinh
  return x1**3*(2*x1 + exp(_a0_*tanh(_a0_*_a1_*_a5_*sinh(_a2_*_a3_*x1)/_a7_ + _a4_) + _a2_))**2
<lambdifygenerated-13966>:2: RuntimeWarning: overflow encountered in sinh
  return x1**3*(2*x1 + exp(_a0_*tanh(_a0_*_a1_*_a5_*sinh(_a2_*_a3_*x1)/_a7_ + _a4_) + _a2_))**2
<lambdifygenerated-13967>:2: RuntimeWarning: overflow encountered in sinh
  return x1**3*(x1 + exp(_a0_*tanh(_a0_*_a1_*_a5_*sinh(_a2_*_a3_*x1)/_a7_ + _a4_) + _a2_) + 1)**2
<lambdifygenerated-13968>:2: RuntimeWarning: overflow encountered in sinh
  return x1**3*(x1 + exp(_a0_*tanh(_a0_*_a1_*_a5_*sinh(_a2_*_a3_*x1)/_a7_ + _a4_) + _a2_) + 1)**2
<lambdifygenerated-13969>:2: RuntimeWarning: overflow encountered in sinh
  return x1**3*(_a6_/x1 + x1 + exp(_a0_*tanh(_a0_*_a1_*_a5_*sinh(_a2_*_a3_*x1)/_a7_ + _a4_) + _a2_))**2
<lambdifygenerated-13970>:2: RuntimeWarning: overflow encountered in sinh
  return x1**3*(_a6_/x1 + x1 + exp(_a0_*tanh(_a0_*_a1_*_a5_*sinh(_a2_*_a3_*x1)/_a7_ + _a4_) + _a2_))**2
<lambdifygenerated-13971>:2: RuntimeWarning: invalid value encountered in power
  return x1**3*(_a6_*x1**(-x1) + x1 + exp(_a0_*tanh(_a0_*_a1_*_a5_*sinh(_a2_*_a3_*x1)/_a7_ + _a4_) + _a2_))**2
<lambdifygenerated-13971>:2: RuntimeWarning: overflow encountered in sinh
  return x1**3*(_a6_*x1**(-x1) + x1 + exp(_a0_*tanh(_a0_*_a1_*_a5_*sinh(_a2_*_a3_*x1)/_a7_ + _a4_) + _a2_))**2
<lambdifygenerated-13972>:2: RuntimeWarning: invalid value encountered in power
  return x1**3*(_a6_*x1**(-x1) + x1 + exp(_a0_*tanh(_a0_*_a1_*_a5_*sinh(_a2_*_a3_*x1)/_a7_ + _a4_) + _a2_))**2
<lambdifygenerated-13972>:2: RuntimeWarning: overflow encountered in sinh
  return x1**3*(_a6_*x1**(-x1) + x1 + exp(_a0_*tanh(_a0_*_a1_*_a5_*sinh(_a2_*_a3_*x1)/_a7_ + _a4_) + _a2_))**2
<lambdifygenerated-13973>:2: RuntimeWarning: invalid value encountered in log
  return x1**3*(_a6_*log(x1)**(-x1) + x1 + exp(_a0_*tanh(_a0_*_a1_*_a5_*sinh(_a2_*_a3_*x1)/_a7_ + _a4_) + _a2_))**2
<lambdifygenerated-13973>:2: RuntimeWarning: invalid value encountered in power
  return x1**3*(_a6_*log(x1)**(-x1) + x1 + exp(_a0_*tanh(_a0_*_a1_*_a5_*sinh(_a2_*_a3_*x1)/_a7_ + _a4_) + _a2_))**2
<lambdifygenerated-13973>:2: RuntimeWarning: overflow encountered in sinh
  return x1**3*(_a6_*log(x1)**(-x1) + x1 + exp(_a0_*tanh(_a0_*_a1_*_a5_*sinh(_a2_*_a3_*x1)/_a7_ + _a4_) + _a2_))**2
<lambdifygenerated-13974>:2: RuntimeWarning: invalid value encountered in log
  return x1**3*(_a6_*log(x1)**(-x1) + x1 + exp(_a0_*tanh(_a0_*_a1_*_a5_*sinh(_a2_*_a3_*x1)/_a7_ + _a4_) + _a2_))**2
<lambdifygenerated-13974>:2: RuntimeWarning: invalid value encountered in power
  return x1**3*(_a6_*log(x1)**(-x1) + x1 + exp(_a0_*tanh(_a0_*_a1_*_a5_*sinh(_a2_*_a3_*x1)/_a7_ + _a4_) + _a2_))**2
<lambdifygenerated-13974>:2: RuntimeWarning: overflow encountered in sinh
  return x1**3*(_a6_*log(x1)**(-x1) + x1 + exp(_a0_*tanh(_a0_*_a1_*_a5_*sinh(_a2_*_a3_*x1)/_a7_ + _a4_) + _a2_))**2
<lambdifygenerated-13975>:2: RuntimeWarning: overflow encountered in sinh
  return x1**3*(_a6_*log(_a4_)**(-x1) + x1 + exp(_a0_*tanh(_a0_*_a1_*_a5_*sinh(_a2_*_a3_*x1)/_a7_ + _a4_) + _a2_))**2
<lambdifygenerated-13976>:2: RuntimeWarning: overflow encountered in sinh
  return x1**3*(_a6_*log(_a4_)**(-x1) + x1 + exp(_a0_*tanh(_a0_*_a1_*_a5_*sinh(_a2_*_a3_*x1)/_a7_ + _a4_) + _a2_))**2
<lambdifygenerated-13977>:2: RuntimeWarning: overflow encountered in sinh
  return x1**3*(_a6_/log(_a4_) + x1 + exp(_a0_*tanh(_a0_*_a1_*_a5_*sinh(_a2_*_a3_*x1)/_a7_ + _a4_) + _a2_))**2
<lambdifygenerated-13978>:2: RuntimeWarning: overflow encountered in sinh
  return x1**3*(_a6_/log(_a4_) + x1 + exp(_a0_*tanh(_a0_*_a1_*_a5_*sinh(_a2_*_a3_*x1)/_a7_ + _a4_) + _a2_))**2
<lambdifygenerated-13979>:2: RuntimeWarning: overflow encountered in power
  return x1**3*(_a6_*log(_a4_)**(-cos(x1)/x1) + x1 + exp(_a0_*tanh(_a0_*_a1_*_a5_*sinh(_a2_*_a3_*x1)/_a7_ + _a4_) + _a2_))**2
<lambdifygenerated-13979>:2: RuntimeWarning: overflow encountered in sinh
  return x1**3*(_a6_*log(_a4_)**(-cos(x1)/x1) + x1 + exp(_a0_*tanh(_a0_*_a1_*_a5_*sinh(_a2_*_a3_*x1)/_a7_ + _a4_) + _a2_))**2
<lambdifygenerated-13979>:2: RuntimeWarning: overflow encountered in square
  return x1**3*(_a6_*log(_a4_)**(-cos(x1)/x1) + x1 + exp(_a0_*tanh(_a0_*_a1_*_a5_*sinh(_a2_*_a3_*x1)/_a7_ + _a4_) + _a2_))**2
/usr/local/lib/python3.10/dist-packages/scipy/optimize/_minpack_py.py:1017: RuntimeWarning: overflow encountered in square
  cost = np.sum(infodict['fvec'] ** 2)
/usr/local/lib/python3.10/dist-packages/pandas/core/arraylike.py:399: RuntimeWarning: overflow encountered in square
  result = getattr(ufunc, method)(*inputs, **kwargs)
<lambdifygenerated-13980>:2: RuntimeWarning: overflow encountered in power
  return x1**3*(_a6_*log(_a4_)**(-cos(x1)/x1) + x1 + exp(_a0_*tanh(_a0_*_a1_*_a5_*sinh(_a2_*_a3_*x1)/_a7_ + _a4_) + _a2_))**2
<lambdifygenerated-13980>:2: RuntimeWarning: overflow encountered in sinh
  return x1**3*(_a6_*log(_a4_)**(-cos(x1)/x1) + x1 + exp(_a0_*tanh(_a0_*_a1_*_a5_*sinh(_a2_*_a3_*x1)/_a7_ + _a4_) + _a2_))**2
<lambdifygenerated-13980>:2: RuntimeWarning: overflow encountered in square
  return x1**3*(_a6_*log(_a4_)**(-cos(x1)/x1) + x1 + exp(_a0_*tanh(_a0_*_a1_*_a5_*sinh(_a2_*_a3_*x1)/_a7_ + _a4_) + _a2_))**2
<lambdifygenerated-13981>:2: RuntimeWarning: overflow encountered in power
  return x1**3*(_a6_*log(_a4_)**(-cos(x1**2)/x1) + x1 + exp(_a0_*tanh(_a0_*_a1_*_a5_*sinh(_a2_*_a3_*x1)/_a7_ + _a4_) + _a2_))**2
<lambdifygenerated-13981>:2: RuntimeWarning: overflow encountered in sinh
  return x1**3*(_a6_*log(_a4_)**(-cos(x1**2)/x1) + x1 + exp(_a0_*tanh(_a0_*_a1_*_a5_*sinh(_a2_*_a3_*x1)/_a7_ + _a4_) + _a2_))**2
<lambdifygenerated-13981>:2: RuntimeWarning: overflow encountered in square
  return x1**3*(_a6_*log(_a4_)**(-cos(x1**2)/x1) + x1 + exp(_a0_*tanh(_a0_*_a1_*_a5_*sinh(_a2_*_a3_*x1)/_a7_ + _a4_) + _a2_))**2
<lambdifygenerated-13982>:2: RuntimeWarning: overflow encountered in power
  return x1**3*(_a6_*log(_a4_)**(-cos(x1**2)/x1) + x1 + exp(_a0_*tanh(_a0_*_a1_*_a5_*sinh(_a2_*_a3_*x1)/_a7_ + _a4_) + _a2_))**2
<lambdifygenerated-13982>:2: RuntimeWarning: overflow encountered in sinh
  return x1**3*(_a6_*log(_a4_)**(-cos(x1**2)/x1) + x1 + exp(_a0_*tanh(_a0_*_a1_*_a5_*sinh(_a2_*_a3_*x1)/_a7_ + _a4_) + _a2_))**2
<lambdifygenerated-13982>:2: RuntimeWarning: overflow encountered in square
  return x1**3*(_a6_*log(_a4_)**(-cos(x1**2)/x1) + x1 + exp(_a0_*tanh(_a0_*_a1_*_a5_*sinh(_a2_*_a3_*x1)/_a7_ + _a4_) + _a2_))**2
<lambdifygenerated-13983>:2: RuntimeWarning: overflow encountered in power
  return x1**3*(_a6_*log(_a4_)**(-cos(_a4_*x1)/x1) + x1 + exp(_a0_*tanh(_a0_*_a1_*_a5_*sinh(_a2_*_a3_*x1)/_a7_ + _a4_) + _a2_))**2
<lambdifygenerated-13983>:2: RuntimeWarning: overflow encountered in sinh
  return x1**3*(_a6_*log(_a4_)**(-cos(_a4_*x1)/x1) + x1 + exp(_a0_*tanh(_a0_*_a1_*_a5_*sinh(_a2_*_a3_*x1)/_a7_ + _a4_) + _a2_))**2
<lambdifygenerated-13983>:2: RuntimeWarning: overflow encountered in square
  return x1**3*(_a6_*log(_a4_)**(-cos(_a4_*x1)/x1) + x1 + exp(_a0_*tanh(_a0_*_a1_*_a5_*sinh(_a2_*_a3_*x1)/_a7_ + _a4_) + _a2_))**2
<lambdifygenerated-13984>:2: RuntimeWarning: overflow encountered in power
  return x1**3*(_a6_*log(_a4_)**(-cos(_a4_*x1)/x1) + x1 + exp(_a0_*tanh(_a0_*_a1_*_a5_*sinh(_a2_*_a3_*x1)/_a7_ + _a4_) + _a2_))**2
<lambdifygenerated-13984>:2: RuntimeWarning: overflow encountered in sinh
  return x1**3*(_a6_*log(_a4_)**(-cos(_a4_*x1)/x1) + x1 + exp(_a0_*tanh(_a0_*_a1_*_a5_*sinh(_a2_*_a3_*x1)/_a7_ + _a4_) + _a2_))**2
<lambdifygenerated-13984>:2: RuntimeWarning: overflow encountered in square
  return x1**3*(_a6_*log(_a4_)**(-cos(_a4_*x1)/x1) + x1 + exp(_a0_*tanh(_a0_*_a1_*_a5_*sinh(_a2_*_a3_*x1)/_a7_ + _a4_) + _a2_))**2
<lambdifygenerated-13985>:2: RuntimeWarning: overflow encountered in power
  return x1**3*(_a6_*log(_a4_)**(-cos(2*_a4_*x1)/x1) + x1 + exp(_a0_*tanh(_a0_*_a1_*_a5_*sinh(_a2_*_a3_*x1)/_a7_ + _a4_) + _a2_))**2
<lambdifygenerated-13985>:2: RuntimeWarning: overflow encountered in sinh
  return x1**3*(_a6_*log(_a4_)**(-cos(2*_a4_*x1)/x1) + x1 + exp(_a0_*tanh(_a0_*_a1_*_a5_*sinh(_a2_*_a3_*x1)/_a7_ + _a4_) + _a2_))**2
<lambdifygenerated-13985>:2: RuntimeWarning: overflow encountered in square
  return x1**3*(_a6_*log(_a4_)**(-cos(2*_a4_*x1)/x1) + x1 + exp(_a0_*tanh(_a0_*_a1_*_a5_*sinh(_a2_*_a3_*x1)/_a7_ + _a4_) + _a2_))**2
<lambdifygenerated-13986>:2: RuntimeWarning: overflow encountered in power
  return x1**3*(_a6_*log(_a4_)**(-cos(2*_a4_*x1)/x1) + x1 + exp(_a0_*tanh(_a0_*_a1_*_a5_*sinh(_a2_*_a3_*x1)/_a7_ + _a4_) + _a2_))**2
<lambdifygenerated-13986>:2: RuntimeWarning: overflow encountered in sinh
  return x1**3*(_a6_*log(_a4_)**(-cos(2*_a4_*x1)/x1) + x1 + exp(_a0_*tanh(_a0_*_a1_*_a5_*sinh(_a2_*_a3_*x1)/_a7_ + _a4_) + _a2_))**2
<lambdifygenerated-13986>:2: RuntimeWarning: overflow encountered in square
  return x1**3*(_a6_*log(_a4_)**(-cos(2*_a4_*x1)/x1) + x1 + exp(_a0_*tanh(_a0_*_a1_*_a5_*sinh(_a2_*_a3_*x1)/_a7_ + _a4_) + _a2_))**2
<lambdifygenerated-13987>:2: RuntimeWarning: overflow encountered in power
  return x1**3*(_a6_*log(_a4_)**(-cos(_a4_*(_a4_ + x1))/x1) + x1 + exp(_a0_*tanh(_a0_*_a1_*_a5_*sinh(_a2_*_a3_*x1)/_a7_ + _a4_) + _a2_))**2
<lambdifygenerated-13987>:2: RuntimeWarning: overflow encountered in sinh
  return x1**3*(_a6_*log(_a4_)**(-cos(_a4_*(_a4_ + x1))/x1) + x1 + exp(_a0_*tanh(_a0_*_a1_*_a5_*sinh(_a2_*_a3_*x1)/_a7_ + _a4_) + _a2_))**2
<lambdifygenerated-13987>:2: RuntimeWarning: overflow encountered in square
  return x1**3*(_a6_*log(_a4_)**(-cos(_a4_*(_a4_ + x1))/x1) + x1 + exp(_a0_*tanh(_a0_*_a1_*_a5_*sinh(_a2_*_a3_*x1)/_a7_ + _a4_) + _a2_))**2
<lambdifygenerated-13988>:2: RuntimeWarning: overflow encountered in power
  return x1**3*(_a6_*log(_a4_)**(-cos(_a4_*(_a4_ + x1))/x1) + x1 + exp(_a0_*tanh(_a0_*_a1_*_a5_*sinh(_a2_*_a3_*x1)/_a7_ + _a4_) + _a2_))**2
<lambdifygenerated-13988>:2: RuntimeWarning: overflow encountered in sinh
  return x1**3*(_a6_*log(_a4_)**(-cos(_a4_*(_a4_ + x1))/x1) + x1 + exp(_a0_*tanh(_a0_*_a1_*_a5_*sinh(_a2_*_a3_*x1)/_a7_ + _a4_) + _a2_))**2
<lambdifygenerated-13988>:2: RuntimeWarning: overflow encountered in square
  return x1**3*(_a6_*log(_a4_)**(-cos(_a4_*(_a4_ + x1))/x1) + x1 + exp(_a0_*tanh(_a0_*_a1_*_a5_*sinh(_a2_*_a3_*x1)/_a7_ + _a4_) + _a2_))**2
<lambdifygenerated-13989>:2: RuntimeWarning: overflow encountered in power
  return x1**3*(_a6_*log(_a4_)**(-cos(_a4_*(_a4_ + x1))/x1) + x1 + exp(_a0_*tanh(_a0_*_a1_*_a5_*sinh(_a2_*_a3_*x1)/_a7_ + _a4_) + _a2_))**2
<lambdifygenerated-13989>:2: RuntimeWarning: overflow encountered in sinh
  return x1**3*(_a6_*log(_a4_)**(-cos(_a4_*(_a4_ + x1))/x1) + x1 + exp(_a0_*tanh(_a0_*_a1_*_a5_*sinh(_a2_*_a3_*x1)/_a7_ + _a4_) + _a2_))**2
<lambdifygenerated-13989>:2: RuntimeWarning: overflow encountered in square
  return x1**3*(_a6_*log(_a4_)**(-cos(_a4_*(_a4_ + x1))/x1) + x1 + exp(_a0_*tanh(_a0_*_a1_*_a5_*sinh(_a2_*_a3_*x1)/_a7_ + _a4_) + _a2_))**2
<lambdifygenerated-13990>:2: RuntimeWarning: overflow encountered in power
  return x1**3*(_a6_*log(_a4_)**(-cos(_a4_*(_a4_ + x1))/x1) + x1 + exp(_a0_*tanh(_a0_*_a1_*_a5_*sinh(_a2_*_a3_*x1)/_a7_ + _a4_) + _a2_))**2
<lambdifygenerated-13990>:2: RuntimeWarning: overflow encountered in sinh
  return x1**3*(_a6_*log(_a4_)**(-cos(_a4_*(_a4_ + x1))/x1) + x1 + exp(_a0_*tanh(_a0_*_a1_*_a5_*sinh(_a2_*_a3_*x1)/_a7_ + _a4_) + _a2_))**2
<lambdifygenerated-13990>:2: RuntimeWarning: overflow encountered in square
  return x1**3*(_a6_*log(_a4_)**(-cos(_a4_*(_a4_ + x1))/x1) + x1 + exp(_a0_*tanh(_a0_*_a1_*_a5_*sinh(_a2_*_a3_*x1)/_a7_ + _a4_) + _a2_))**2
<lambdifygenerated-13991>:2: RuntimeWarning: overflow encountered in sinh
  return x1**3*(_a6_*log(_a4_)**(-cos(_a4_*(_a4_ + x1))/_a5_) + x1 + exp(_a0_*tanh(_a0_*_a1_*_a5_*sinh(_a2_*_a3_*x1)/_a7_ + _a4_) + _a2_))**2
<lambdifygenerated-13992>:2: RuntimeWarning: overflow encountered in sinh
  return x1**3*(_a6_*log(_a4_)**(-cos(_a4_*(_a4_ + x1))/_a5_) + x1 + exp(_a0_*tanh(_a0_*_a1_*_a5_*sinh(_a2_*_a3_*x1)/_a7_ + _a4_) + _a2_))**2
<lambdifygenerated-13993>:2: RuntimeWarning: overflow encountered in sinh
  return x1**3*(_a6_*log(_a4_)**(-cos(_a4_*(_a4_ + x1))/_a5_) + _a7_ + exp(_a0_*tanh(_a0_*_a1_*_a5_*sinh(_a2_*_a3_*x1)/_a7_ + _a4_) + _a2_))**2

interpolation

<lambdifygenerated-13994>:2: RuntimeWarning: overflow encountered in sinh
  return x1**3*(_a6_*log(_a4_)**(-cos(_a4_*(_a4_ + x1))/_a5_) + _a7_ + exp(_a0_*tanh(_a0_*_a1_*_a5_*sinh(_a2_*_a3_*x1)/_a7_ + _a4_) + _a2_))**2
<lambdifygenerated-13995>:2: RuntimeWarning: overflow encountered in sinh
  return x1**7*(_a6_*log(_a4_)**(-cos(_a4_*(_a4_ + x1))/_a5_) + _a7_ + exp(_a0_*tanh(_a0_*_a1_*_a5_*sinh(_a2_*_a3_*x1)/_a7_ + _a4_) + _a2_))**2
<lambdifygenerated-13996>:2: RuntimeWarning: overflow encountered in sinh
  return x1**7*(_a6_*log(_a4_)**(-cos(_a4_*(_a4_ + x1))/_a5_) + _a7_ + exp(_a0_*tanh(_a0_*_a1_*_a5_*sinh(_a2_*_a3_*x1)/_a7_ + _a4_) + _a2_))**2
<lambdifygenerated-13997>:2: RuntimeWarning: overflow encountered in sinh
  return x1**13*(_a6_*log(_a4_)**(-cos(_a4_*(_a4_ + x1))/_a5_) + _a7_ + exp(_a0_*tanh(_a0_*_a1_*_a5_*sinh(_a2_*_a3_*x1)/_a7_ + _a4_) + _a2_))**2
<lambdifygenerated-13998>:2: RuntimeWarning: overflow encountered in sinh
  return x1**13*(_a6_*log(_a4_)**(-cos(_a4_*(_a4_ + x1))/_a5_) + _a7_ + exp(_a0_*tanh(_a0_*_a1_*_a5_*sinh(_a2_*_a3_*x1)/_a7_ + _a4_) + _a2_))**2
<lambdifygenerated-13999>:2: RuntimeWarning: overflow encountered in sinh
  return x1**25*(_a6_*log(_a4_)**(-cos(_a4_*(_a4_ + x1))/_a5_) + _a7_ + exp(_a0_*tanh(_a0_*_a1_*_a5_*sinh(_a2_*_a3_*x1)/_a7_ + _a4_) + _a2_))**2
<lambdifygenerated-14000>:2: RuntimeWarning: overflow encountered in sinh
  return x1**25*(_a6_*log(_a4_)**(-cos(_a4_*(_a4_ + x1))/_a5_) + _a7_ + exp(_a0_*tanh(_a0_*_a1_*_a5_*sinh(_a2_*_a3_*x1)/_a7_ + _a4_) + _a2_))**2
<lambdifygenerated-14001>:2: RuntimeWarning: overflow encountered in sinh
  return 16777216*x1**25*(_a6_*log(_a4_)**(-cos(_a4_*(_a4_ + x1))/_a5_) + _a7_ + exp(_a0_*tanh(_a0_*_a1_*_a5_*sinh(_a2_*_a3_*x1)/_a7_ + _a4_) + _a2_))**2
<lambdifygenerated-14002>:2: RuntimeWarning: overflow encountered in sinh
  return 16777216*x1**25*(_a6_*log(_a4_)**(-cos(_a4_*(_a4_ + x1))/_a5_) + _a7_ + exp(_a0_*tanh(_a0_*_a1_*_a5_*sinh(_a2_*_a3_*x1)/_a7_ + _a4_) + _a2_))**2
<lambdifygenerated-14003>:2: RuntimeWarning: overflow encountered in power
  return x1*(_a2_ + x1)**24*(_a6_*log(_a4_)**(-cos(_a4_*(_a4_ + x1))/_a5_) + _a7_ + exp(_a0_*tanh(_a0_*_a1_*_a5_*sinh(_a2_*_a3_*x1)/_a7_ + _a4_) + _a2_))**2
<lambdifygenerated-14003>:2: RuntimeWarning: overflow encountered in sinh
  return x1*(_a2_ + x1)**24*(_a6_*log(_a4_)**(-cos(_a4_*(_a4_ + x1))/_a5_) + _a7_ + exp(_a0_*tanh(_a0_*_a1_*_a5_*sinh(_a2_*_a3_*x1)/_a7_ + _a4_) + _a2_))**2
<lambdifygenerated-14004>:2: RuntimeWarning: overflow encountered in power
  return x1*(_a2_ + x1)**24*(_a6_*log(_a4_)**(-cos(_a4_*(_a4_ + x1))/_a5_) + _a7_ + exp(_a0_*tanh(_a0_*_a1_*_a5_*sinh(_a2_*_a3_*x1)/_a7_ + _a4_) + _a2_))**2
<lambdifygenerated-14004>:2: RuntimeWarning: overflow encountered in sinh
  return x1*(_a2_ + x1)**24*(_a6_*log(_a4_)**(-cos(_a4_*(_a4_ + x1))/_a5_) + _a7_ + exp(_a0_*tanh(_a0_*_a1_*_a5_*sinh(_a2_*_a3_*x1)/_a7_ + _a4_) + _a2_))**2
<lambdifygenerated-14005>:2: RuntimeWarning: overflow encountered in power
  return x1*(_a2_ + x1)**24*(_a6_*log(_a4_)**(-cos(_a4_*(_a4_ + x1))/_a5_) + _a7_ + exp(_a0_*tanh(_a0_*_a1_*_a5_*sinh(_a2_*_a3_*x1)/_a7_ + _a4_) + _a2_))**2
<lambdifygenerated-14005>:2: RuntimeWarning: overflow encountered in sinh
  return x1*(_a2_ + x1)**24*(_a6_*log(_a4_)**(-cos(_a4_*(_a4_ + x1))/_a5_) + _a7_ + exp(_a0_*tanh(_a0_*_a1_*_a5_*sinh(_a2_*_a3_*x1)/_a7_ + _a4_) + _a2_))**2
<lambdifygenerated-14006>:2: RuntimeWarning: overflow encountered in power
  return x1*(_a2_ + x1)**24*(_a6_*log(_a4_)**(-cos(_a4_*(_a4_ + x1))/_a5_) + _a7_ + exp(_a0_*tanh(_a0_*_a1_*_a5_*sinh(_a2_*_a3_*x1)/_a7_ + _a4_) + _a2_))**2
<lambdifygenerated-14006>:2: RuntimeWarning: overflow encountered in sinh
  return x1*(_a2_ + x1)**24*(_a6_*log(_a4_)**(-cos(_a4_*(_a4_ + x1))/_a5_) + _a7_ + exp(_a0_*tanh(_a0_*_a1_*_a5_*sinh(_a2_*_a3_*x1)/_a7_ + _a4_) + _a2_))**2
<lambdifygenerated-14007>:2: RuntimeWarning: overflow encountered in power
  return _a2_**2*(_a2_ + x1)**24*(_a6_*log(_a4_)**(-cos(_a4_*(_a4_ + x1))/_a5_) + _a7_ + exp(_a0_*tanh(_a0_*_a1_*_a5_*sinh(_a2_*_a3_*x1)/_a7_ + _a4_) + _a2_))**2/x1
<lambdifygenerated-14007>:2: RuntimeWarning: overflow encountered in sinh
  return _a2_**2*(_a2_ + x1)**24*(_a6_*log(_a4_)**(-cos(_a4_*(_a4_ + x1))/_a5_) + _a7_ + exp(_a0_*tanh(_a0_*_a1_*_a5_*sinh(_a2_*_a3_*x1)/_a7_ + _a4_) + _a2_))**2/x1
<lambdifygenerated-14008>:2: RuntimeWarning: overflow encountered in power
  return _a2_**2*(_a2_ + x1)**24*(_a6_*log(_a4_)**(-cos(_a4_*(_a4_ + x1))/_a5_) + _a7_ + exp(_a0_*tanh(_a0_*_a1_*_a5_*sinh(_a2_*_a3_*x1)/_a7_ + _a4_) + _a2_))**2/x1
<lambdifygenerated-14008>:2: RuntimeWarning: overflow encountered in sinh
  return _a2_**2*(_a2_ + x1)**24*(_a6_*log(_a4_)**(-cos(_a4_*(_a4_ + x1))/_a5_) + _a7_ + exp(_a0_*tanh(_a0_*_a1_*_a5_*sinh(_a2_*_a3_*x1)/_a7_ + _a4_) + _a2_))**2/x1
<lambdifygenerated-14009>:2: RuntimeWarning: overflow encountered in power
  return _a2_**2*(_a2_ + x1)**24*(_a6_*log(_a4_)**(-cos(_a4_*(_a4_ + x1))/_a5_) + _a7_ + exp(_a0_*tanh(_a0_*_a1_*_a5_*sinh(_a2_*_a3_*x1)/_a7_ + _a4_) + _a2_))**2/_a5_
<lambdifygenerated-14009>:2: RuntimeWarning: overflow encountered in sinh
  return _a2_**2*(_a2_ + x1)**24*(_a6_*log(_a4_)**(-cos(_a4_*(_a4_ + x1))/_a5_) + _a7_ + exp(_a0_*tanh(_a0_*_a1_*_a5_*sinh(_a2_*_a3_*x1)/_a7_ + _a4_) + _a2_))**2/_a5_
<lambdifygenerated-14010>:2: RuntimeWarning: overflow encountered in power
  return _a2_**2*(_a2_ + x1)**24*(_a6_*log(_a4_)**(-cos(_a4_*(_a4_ + x1))/_a5_) + _a7_ + exp(_a0_*tanh(_a0_*_a1_*_a5_*sinh(_a2_*_a3_*x1)/_a7_ + _a4_) + _a2_))**2/_a5_
<lambdifygenerated-14010>:2: RuntimeWarning: overflow encountered in sinh
  return _a2_**2*(_a2_ + x1)**24*(_a6_*log(_a4_)**(-cos(_a4_*(_a4_ + x1))/_a5_) + _a7_ + exp(_a0_*tanh(_a0_*_a1_*_a5_*sinh(_a2_*_a3_*x1)/_a7_ + _a4_) + _a2_))**2/_a5_
<lambdifygenerated-14011>:2: RuntimeWarning: overflow encountered in power
  return _a2_**2*(_a2_ + x1)**24*(_a6_*log(_a4_)**(-cos(_a4_*(_a4_ + x1))/_a5_) + _a7_ + exp(_a0_*tanh(_a0_*_a1_*_a5_*sinh(_a2_*_a3_*x1)/_a7_ + _a4_) + _a2_))**2/_a5_
<lambdifygenerated-14011>:2: RuntimeWarning: overflow encountered in sinh
  return _a2_**2*(_a2_ + x1)**24*(_a6_*log(_a4_)**(-cos(_a4_*(_a4_ + x1))/_a5_) + _a7_ + exp(_a0_*tanh(_a0_*_a1_*_a5_*sinh(_a2_*_a3_*x1)/_a7_ + _a4_) + _a2_))**2/_a5_
<lambdifygenerated-14012>:2: RuntimeWarning: overflow encountered in power
  return _a2_**2*(_a2_ + x1)**24*(_a6_*log(_a4_)**(-cos(_a4_*(_a4_ + x1))/_a5_) + _a7_ + exp(_a0_*tanh(_a0_*_a1_*_a5_*sinh(_a2_*_a3_*x1)/_a7_ + _a4_) + _a2_))**2/_a5_
<lambdifygenerated-14012>:2: RuntimeWarning: overflow encountered in sinh
  return _a2_**2*(_a2_ + x1)**24*(_a6_*log(_a4_)**(-cos(_a4_*(_a4_ + x1))/_a5_) + _a7_ + exp(_a0_*tanh(_a0_*_a1_*_a5_*sinh(_a2_*_a3_*x1)/_a7_ + _a4_) + _a2_))**2/_a5_
<lambdifygenerated-14013>:2: RuntimeWarning: overflow encountered in power
  return _a2_**2*(_a2_ + x1)**24*(_a6_*log(_a4_)**(-cos(_a4_*(_a4_ + x1))/_a5_) + _a7_ + exp(_a0_*tanh(_a0_*_a1_*_a5_*sinh(_a2_*_a3_*x1)/_a7_ + _a4_) + _a2_))**2/_a5_
<lambdifygenerated-14013>:2: RuntimeWarning: overflow encountered in sinh
  return _a2_**2*(_a2_ + x1)**24*(_a6_*log(_a4_)**(-cos(_a4_*(_a4_ + x1))/_a5_) + _a7_ + exp(_a0_*tanh(_a0_*_a1_*_a5_*sinh(_a2_*_a3_*x1)/_a7_ + _a4_) + _a2_))**2/_a5_
<lambdifygenerated-14014>:2: RuntimeWarning: overflow encountered in power
  return _a2_**2*(_a2_ + x1)**24*(_a6_*log(_a4_)**(-cos(_a4_*(_a4_ + x1))/_a5_) + _a7_ + exp(_a0_*tanh(_a0_*_a1_*_a5_*sinh(_a2_*_a3_*x1)/_a7_ + _a4_) + _a2_))**2/_a5_
<lambdifygenerated-14014>:2: RuntimeWarning: overflow encountered in sinh
  return _a2_**2*(_a2_ + x1)**24*(_a6_*log(_a4_)**(-cos(_a4_*(_a4_ + x1))/_a5_) + _a7_ + exp(_a0_*tanh(_a0_*_a1_*_a5_*sinh(_a2_*_a3_*x1)/_a7_ + _a4_) + _a2_))**2/_a5_

         x1         y  rep    ymodel      ybms
3745  0.997  0.360683  0.0  0.357358  0.360991
3746  0.998  0.360826  0.0  0.357483  0.361131
3747  0.998  0.360969  0.0  0.357608  0.361272
3748  0.999  0.361111  0.0  0.357734  0.361412

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.361396  0.0  0.357984  0.361692
3751  1.002  0.361539  0.0  0.358110  0.361832
3752  1.002  0.361681  0.0  0.358235  0.361972
3753  1.003  0.361824  0.0  0.358360  0.362112

3750

<lambdifygenerated-14021>:2: RuntimeWarning: invalid value encountered in log
  return log(x1)/x1
<lambdifygenerated-14022>:2: RuntimeWarning: invalid value encountered in log
  return log(x1)/x1
<lambdifygenerated-14027>:2: RuntimeWarning: invalid value encountered in power
  return log(x1*(x1 + x1**x1))/x1
<lambdifygenerated-14028>:2: RuntimeWarning: invalid value encountered in power
  return log(x1*(x1 + x1**x1))/x1
<lambdifygenerated-14029>:2: RuntimeWarning: invalid value encountered in power
  return log(x1*(x1 + (x1**x1)**x1))/x1
<lambdifygenerated-14030>:2: RuntimeWarning: invalid value encountered in power
  return log(x1*(x1 + (x1**x1)**x1))/x1
<lambdifygenerated-14031>:2: RuntimeWarning: invalid value encountered in log
  return log(x1*(x1 + (_a0_**x1)**x1))/x1
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-14032>:2: RuntimeWarning: invalid value encountered in log
  return log(x1*(x1 + (_a0_**x1)**x1))/x1
<lambdifygenerated-14033>:2: RuntimeWarning: invalid value encountered in log
  return log(x1*(x1 + (_a0_**(2*x1))**x1))/x1
<lambdifygenerated-14034>:2: RuntimeWarning: invalid value encountered in log
  return log(x1*(x1 + (_a0_**(2*x1))**x1))/x1
<lambdifygenerated-14035>:2: RuntimeWarning: invalid value encountered in log
  return log(x1*(x1 + (_a0_**(x1 + cos(x1)))**x1))/x1
<lambdifygenerated-14036>:2: RuntimeWarning: invalid value encountered in log
  return log(x1*(x1 + (_a0_**(x1 + cos(x1)))**x1))/x1
<lambdifygenerated-14037>:2: RuntimeWarning: invalid value encountered in log
  return log(x1*(x1 + (_a0_**(x1 + cos(_a4_)))**x1))/x1
<lambdifygenerated-14038>:2: RuntimeWarning: invalid value encountered in log
  return log(x1*(x1 + (_a0_**(x1 + cos(_a4_)))**x1))/x1
<lambdifygenerated-14039>:2: RuntimeWarning: invalid value encountered in log
  return log(x1*(x1 + (_a0_**(cos(_a4_) + sinh(x1)))**x1))/x1
<lambdifygenerated-14040>:2: RuntimeWarning: invalid value encountered in log
  return log(x1*(x1 + (_a0_**(cos(_a4_) + sinh(x1)))**x1))/x1
<lambdifygenerated-14041>:2: RuntimeWarning: invalid value encountered in log
  return log(x1*(x1 + (_a0_**(cos(_a4_) + sinh(x1)))**x1))/x1
<lambdifygenerated-14042>:2: RuntimeWarning: invalid value encountered in log
  return log(x1*(x1 + (_a0_**(cos(_a4_) + sinh(x1)))**x1))/x1
<lambdifygenerated-14043>:2: RuntimeWarning: invalid value encountered in log
  return log(x1*(x1 + (_a0_**(cos(_a4_) + sinh(x1)))**x1))/x1
<lambdifygenerated-14044>:2: RuntimeWarning: invalid value encountered in log
  return log(x1*(x1 + (_a0_**(cos(_a4_) + sinh(x1)))**x1))/x1
<lambdifygenerated-14045>:2: RuntimeWarning: invalid value encountered in log
  return log(x1*((_a0_**(cos(_a4_) + sinh(x1)))**x1 + abs(x1)))/x1
<lambdifygenerated-14046>:2: RuntimeWarning: invalid value encountered in log
  return log(x1*((_a0_**(cos(_a4_) + sinh(x1)))**x1 + abs(x1)))/x1
<lambdifygenerated-14047>:2: RuntimeWarning: invalid value encountered in log
  return log(x1*((_a0_**(cos(_a4_) + sinh(x1)))**x1 + abs(sin(x1))))/x1
<lambdifygenerated-14048>:2: RuntimeWarning: invalid value encountered in log
  return log(x1*((_a0_**(cos(_a4_) + sinh(x1)))**x1 + abs(sin(x1))))/x1
<lambdifygenerated-14049>:2: RuntimeWarning: invalid value encountered in log
  return log(x1*((_a0_**(cos(_a4_) + sinh(x1)))**x1 + abs(sin(x1**2))))/x1
<lambdifygenerated-14050>:2: RuntimeWarning: invalid value encountered in log
  return log(x1*((_a0_**(cos(_a4_) + sinh(x1)))**x1 + abs(sin(x1**2))))/x1
<lambdifygenerated-14051>:2: RuntimeWarning: invalid value encountered in log
  return log(x1*((_a0_**(cos(_a4_) + sinh(x1)))**x1 + abs(sin(x1*tan(x1)))))/x1
<lambdifygenerated-14052>:2: RuntimeWarning: invalid value encountered in log
  return log(x1*((_a0_**(cos(_a4_) + sinh(x1)))**x1 + abs(sin(x1*tan(x1)))))/x1
<lambdifygenerated-14053>:2: RuntimeWarning: invalid value encountered in log
  return log(x1*((_a0_**(cos(_a4_) + sinh(x1)))**x1 + abs(sin(x1*tan(_a6_)))))/x1
<lambdifygenerated-14054>:2: RuntimeWarning: invalid value encountered in log
  return log(x1*((_a0_**(cos(_a4_) + sinh(x1)))**x1 + abs(sin(x1*tan(_a6_)))))/x1
<lambdifygenerated-14055>:2: RuntimeWarning: invalid value encountered in log
  return log(x1*((_a0_**(cos(_a4_) + sinh(x1)))**x1 + abs(sin(2*x1*tan(_a6_)))))/x1
<lambdifygenerated-14056>:2: RuntimeWarning: invalid value encountered in log
  return log(x1*((_a0_**(cos(_a4_) + sinh(x1)))**x1 + abs(sin(2*x1*tan(_a6_)))))/x1
<lambdifygenerated-14057>:2: RuntimeWarning: invalid value encountered in log
  return log(x1*((_a0_**(cos(_a4_) + sinh(x1)))**x1 + abs(sin((x1**2 + x1)*tan(_a6_)))))/x1
<lambdifygenerated-14058>:2: RuntimeWarning: invalid value encountered in log
  return log(x1*((_a0_**(cos(_a4_) + sinh(x1)))**x1 + abs(sin((x1**2 + x1)*tan(_a6_)))))/x1
<lambdifygenerated-14059>:2: RuntimeWarning: invalid value encountered in log
  return log(x1*((_a0_**(cos(_a4_) + sinh(x1)))**x1 + abs(sin((_a3_*x1 + x1)*tan(_a6_)))))/x1
<lambdifygenerated-14060>:2: RuntimeWarning: invalid value encountered in log
  return log(x1*((_a0_**(cos(_a4_) + sinh(x1)))**x1 + abs(sin((_a3_*x1 + x1)*tan(_a6_)))))/x1
<lambdifygenerated-14061>:2: RuntimeWarning: invalid value encountered in log
  return log(x1*((_a0_**(cos(_a4_) + sinh(x1)))**x1 + abs(sin((_a2_*_a3_ + x1)*tan(_a6_)))))/x1
<lambdifygenerated-14062>:2: RuntimeWarning: invalid value encountered in log
  return log(x1*((_a0_**(cos(_a4_) + sinh(x1)))**x1 + abs(sin((_a2_*_a3_ + x1)*tan(_a6_)))))/x1
<lambdifygenerated-14063>:2: RuntimeWarning: invalid value encountered in log
  return log(x1*((_a0_**(cos(_a4_) + sinh(x1)))**x1 + abs(sin((_a2_*_a3_ + x1)*tan(_a6_)))))/x1
<lambdifygenerated-14064>:2: RuntimeWarning: invalid value encountered in log
  return log(x1*((_a0_**(cos(_a4_) + sinh(x1)))**x1 + abs(sin((_a2_*_a3_ + x1)*tan(_a6_)))))/x1
<lambdifygenerated-14071>:2: RuntimeWarning: invalid value encountered in power
  return log(_a1_*((_a0_**(cos(_a4_) + sinh(x1)))**x1 + abs(sin((_a2_*_a3_ + x1)*tan(_a6_)))))/(_a3_*x1 + x1)
<lambdifygenerated-14073>:2: RuntimeWarning: invalid value encountered in power
  return log(_a1_*((_a0_**(cos(_a4_) + sinh(x1)))**x1 + abs(sin((_a2_*_a3_ + x1)*tan(_a6_)))))/(_a3_*sin(x1) + x1)
<lambdifygenerated-14075>:2: RuntimeWarning: invalid value encountered in power
  return log(_a1_*((_a0_**(cos(_a4_) + sinh(x1)))**x1 + abs(sin((_a2_*_a3_ + x1)*tan(_a6_)))))/(_a3_*sin(x1**2) + x1)
<lambdifygenerated-14077>:2: RuntimeWarning: invalid value encountered in power
  return log(_a1_*((_a0_**(cos(_a4_) + sinh(x1)))**x1 + abs(sin((_a2_*_a3_ + x1)*tan(_a6_)))))/(_a3_*sin(2*x1**2) + x1)
<lambdifygenerated-14083>:2: RuntimeWarning: invalid value encountered in power
  return log(_a1_*((_a0_**(cos(_a4_) + sinh(x1)))**x1 + abs(sin((_a2_*_a3_ + x1)*tan(_a6_)))))/(_a3_*sin((_a5_ + x1)*cos(x1)) + x1)
<lambdifygenerated-14085>:2: RuntimeWarning: invalid value encountered in power
  return log(_a1_*((_a0_**(cos(_a4_) + sinh(x1)))**x1 + abs(sin((_a2_*_a3_ + x1)*tan(_a6_)))))/(_a3_*sin((_a5_ + x1)*cos(x1**2)) + x1)
<lambdifygenerated-14087>:2: RuntimeWarning: invalid value encountered in power
  return log(_a1_*((_a0_**(cos(_a4_) + sinh(x1)))**x1 + abs(sin((_a2_*_a3_ + x1)*tan(_a6_)))))/(_a3_*sin((_a5_ + x1)*cos(_a7_*x1)) + x1)
<lambdifygenerated-14091>:2: RuntimeWarning: invalid value encountered in power
  return log(_a1_*((_a0_**(cos(_a4_) + sinh(x1)))**x1 + abs(sin((_a2_*_a3_ + x1)*tan(_a6_)))))/(_a3_*sin((_a5_ + x1)*cos(_a7_*x1)) + 1)
<lambdifygenerated-14091>:2: RuntimeWarning: invalid value encountered in log
  return log(_a1_*((_a0_**(cos(_a4_) + sinh(x1)))**x1 + abs(sin((_a2_*_a3_ + x1)*tan(_a6_)))))/(_a3_*sin((_a5_ + x1)*cos(_a7_*x1)) + 1)
<lambdifygenerated-14093>:2: RuntimeWarning: invalid value encountered in power
  return log(_a1_*((_a0_**(cos(_a4_) + sinh(x1)))**x1 + abs(sin((_a2_*_a3_ + x1)*tan(_a6_)))))/(_a3_*sin((_a5_ + x1)*cos(_a7_*x1)) + x1**(-1.0))
<lambdifygenerated-14095>:2: RuntimeWarning: invalid value encountered in power
  return log(_a1_*((_a0_**(cos(_a4_) + sinh(x1)))**x1 + abs(sin((_a2_*_a3_ + x1)*tan(_a6_)))))/(_a3_*sin((_a5_ + x1)*cos(_a7_*x1)) + 1)
<lambdifygenerated-14097>:2: RuntimeWarning: invalid value encountered in power
  return log(_a1_*((_a0_**(cos(_a4_) + sinh(x1)))**x1 + abs(sin((_a2_*_a3_ + x1)*tan(_a6_)))))/(_a3_*sin((_a5_ + x1)*cos(_a7_*x1)) + _a4_**2/x1**2)
<lambdifygenerated-14099>:2: RuntimeWarning: invalid value encountered in power
  return log(_a1_*((_a0_**(cos(_a4_) + sinh(x1)))**x1 + abs(sin((_a2_*_a3_ + x1)*tan(_a6_)))))/(_a3_*sin((_a5_ + x1)*cos(_a7_*x1)) + _a4_**2/(_a2_*x1))
<lambdifygenerated-14101>:2: RuntimeWarning: invalid value encountered in power
  return log(_a1_*((_a0_**(cos(_a4_) + sinh(x1)))**x1 + abs(sin((_a2_*_a3_ + x1)*tan(_a6_)))))/(_a3_*sin((_a5_ + x1)*cos(_a7_*x1)) - _a4_**2/(_a2_*x1))
<lambdifygenerated-14103>:2: RuntimeWarning: invalid value encountered in power
  return log(_a1_*((_a0_**(cos(_a4_) + sinh(x1)))**x1 + abs(sin((_a2_*_a3_ + x1)*tan(_a6_)))))/(_a3_*sin((_a5_ + x1)*cos(_a7_*x1)) - _a4_/_a2_)
<lambdifygenerated-14107>:2: RuntimeWarning: invalid value encountered in power
  return log(_a1_*((_a0_**(cos(_a4_) + sinh(x1)))**x1 + abs(sin((_a2_*_a3_ + x1)*tan(_a6_)))))/(_a3_*sin((_a5_ + x1)*cos(_a7_*x1)) - _a4_/_a2_)

interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.875844  1.0  0.897224  0.873098
3746  0.998  0.875274  1.0  0.897122  0.872073
3747  0.998  0.874704  1.0  0.897021  0.871000
3748  0.999  0.874135  1.0  0.896919  0.869876

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.872995  1.0  0.896716  0.867454
3751  1.002  0.872426  1.0  0.896614  0.866144
3752  1.002  0.871856  1.0  0.896512  0.864758
3753  1.003  0.871287  1.0  0.896411  0.863288

3750

<lambdifygenerated-14117>:2: RuntimeWarning: invalid value encountered in power
  return exp(x1 + x1**x1)
<lambdifygenerated-14118>:2: RuntimeWarning: invalid value encountered in power
  return exp(x1 + x1**x1)
<lambdifygenerated-14121>:2: RuntimeWarning: invalid value encountered in power
  return exp(x1 + x1**x1)
<lambdifygenerated-14122>:2: RuntimeWarning: invalid value encountered in power
  return exp(x1 + x1**x1)
<lambdifygenerated-14125>:2: RuntimeWarning: invalid value encountered in power
  return exp(x1 + (x1**(2*x1))**x1)
<lambdifygenerated-14126>:2: RuntimeWarning: invalid value encountered in power
  return exp(x1 + (x1**(2*x1))**x1)
<lambdifygenerated-14127>:2: RuntimeWarning: invalid value encountered in power
  return exp(x1 + ((2*x1)**(2*x1))**x1)
<lambdifygenerated-14127>:2: RuntimeWarning: overflow encountered in exp
  return exp(x1 + ((2*x1)**(2*x1))**x1)
/usr/local/lib/python3.10/dist-packages/pandas/core/arraylike.py:399: RuntimeWarning: overflow encountered in square
  result = getattr(ufunc, method)(*inputs, **kwargs)
<lambdifygenerated-14128>:2: RuntimeWarning: invalid value encountered in power
  return exp(x1 + ((2*x1)**(2*x1))**x1)
<lambdifygenerated-14128>:2: RuntimeWarning: overflow encountered in exp
  return exp(x1 + ((2*x1)**(2*x1))**x1)
<lambdifygenerated-14129>:2: RuntimeWarning: invalid value encountered in power
  return exp(x1 + ((3*x1)**(2*x1))**x1)
<lambdifygenerated-14129>:2: RuntimeWarning: overflow encountered in exp
  return exp(x1 + ((3*x1)**(2*x1))**x1)
<lambdifygenerated-14130>:2: RuntimeWarning: invalid value encountered in power
  return exp(x1 + ((3*x1)**(2*x1))**x1)
<lambdifygenerated-14130>:2: RuntimeWarning: overflow encountered in exp
  return exp(x1 + ((3*x1)**(2*x1))**x1)
<lambdifygenerated-14131>:2: RuntimeWarning: invalid value encountered in power
  return exp(x1 + ((x1**2 + 2*x1)**(2*x1))**x1)
<lambdifygenerated-14131>:2: RuntimeWarning: overflow encountered in exp
  return exp(x1 + ((x1**2 + 2*x1)**(2*x1))**x1)
<lambdifygenerated-14132>:2: RuntimeWarning: invalid value encountered in power
  return exp(x1 + ((x1**2 + 2*x1)**(2*x1))**x1)
<lambdifygenerated-14132>:2: RuntimeWarning: overflow encountered in exp
  return exp(x1 + ((x1**2 + 2*x1)**(2*x1))**x1)
<lambdifygenerated-14133>:2: RuntimeWarning: invalid value encountered in power
  return exp(x1 + ((x1*x1**x1 + 2*x1)**(2*x1))**x1)
<lambdifygenerated-14133>:2: RuntimeWarning: overflow encountered in exp
  return exp(x1 + ((x1*x1**x1 + 2*x1)**(2*x1))**x1)
<lambdifygenerated-14134>:2: RuntimeWarning: invalid value encountered in power
  return exp(x1 + ((x1*x1**x1 + 2*x1)**(2*x1))**x1)
<lambdifygenerated-14134>:2: RuntimeWarning: overflow encountered in exp
  return exp(x1 + ((x1*x1**x1 + 2*x1)**(2*x1))**x1)
<lambdifygenerated-14135>:2: RuntimeWarning: invalid value encountered in power
  return exp(x1 + ((_a3_**x1*x1 + 2*x1)**(2*x1))**x1)
<lambdifygenerated-14135>:2: RuntimeWarning: overflow encountered in exp
  return exp(x1 + ((_a3_**x1*x1 + 2*x1)**(2*x1))**x1)
/usr/local/lib/python3.10/dist-packages/scipy/optimize/_minpack_py.py:1017: RuntimeWarning: overflow encountered in square
  cost = np.sum(infodict['fvec'] ** 2)
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-14136>:2: RuntimeWarning: invalid value encountered in power
  return exp(x1 + ((_a3_**x1*x1 + 2*x1)**(2*x1))**x1)
<lambdifygenerated-14136>:2: RuntimeWarning: overflow encountered in exp
  return exp(x1 + ((_a3_**x1*x1 + 2*x1)**(2*x1))**x1)
<lambdifygenerated-14137>:2: RuntimeWarning: invalid value encountered in power
  return exp(x1 + ((_a3_**cos(x1)*x1 + 2*x1)**(2*x1))**x1)
<lambdifygenerated-14137>:2: RuntimeWarning: overflow encountered in exp
  return exp(x1 + ((_a3_**cos(x1)*x1 + 2*x1)**(2*x1))**x1)
<lambdifygenerated-14138>:2: RuntimeWarning: invalid value encountered in power
  return exp(x1 + ((_a3_**cos(x1)*x1 + 2*x1)**(2*x1))**x1)
<lambdifygenerated-14138>:2: RuntimeWarning: overflow encountered in exp
  return exp(x1 + ((_a3_**cos(x1)*x1 + 2*x1)**(2*x1))**x1)
<lambdifygenerated-14139>:2: RuntimeWarning: invalid value encountered in power
  return exp(x1 + ((_a3_**cos(2*x1)*x1 + 2*x1)**(2*x1))**x1)
<lambdifygenerated-14139>:2: RuntimeWarning: overflow encountered in exp
  return exp(x1 + ((_a3_**cos(2*x1)*x1 + 2*x1)**(2*x1))**x1)
<lambdifygenerated-14140>:2: RuntimeWarning: invalid value encountered in power
  return exp(x1 + ((_a3_**cos(2*x1)*x1 + 2*x1)**(2*x1))**x1)
<lambdifygenerated-14140>:2: RuntimeWarning: overflow encountered in exp
  return exp(x1 + ((_a3_**cos(2*x1)*x1 + 2*x1)**(2*x1))**x1)
<lambdifygenerated-14141>:2: RuntimeWarning: invalid value encountered in power
  return exp(x1 + ((_a3_**cos(_a6_ + x1)*x1 + 2*x1)**(2*x1))**x1)
<lambdifygenerated-14141>:2: RuntimeWarning: overflow encountered in exp
  return exp(x1 + ((_a3_**cos(_a6_ + x1)*x1 + 2*x1)**(2*x1))**x1)
<lambdifygenerated-14142>:2: RuntimeWarning: invalid value encountered in power
  return exp(x1 + ((_a3_**cos(_a6_ + x1)*x1 + 2*x1)**(2*x1))**x1)
<lambdifygenerated-14142>:2: RuntimeWarning: overflow encountered in exp
  return exp(x1 + ((_a3_**cos(_a6_ + x1)*x1 + 2*x1)**(2*x1))**x1)
<lambdifygenerated-14143>:2: RuntimeWarning: invalid value encountered in power
  return exp(x1 + ((_a3_**cos(_a6_ + 2*x1)*x1 + 2*x1)**(2*x1))**x1)
<lambdifygenerated-14143>:2: RuntimeWarning: overflow encountered in exp
  return exp(x1 + ((_a3_**cos(_a6_ + 2*x1)*x1 + 2*x1)**(2*x1))**x1)
<lambdifygenerated-14144>:2: RuntimeWarning: invalid value encountered in power
  return exp(x1 + ((_a3_**cos(_a6_ + 2*x1)*x1 + 2*x1)**(2*x1))**x1)
<lambdifygenerated-14144>:2: RuntimeWarning: overflow encountered in exp
  return exp(x1 + ((_a3_**cos(_a6_ + 2*x1)*x1 + 2*x1)**(2*x1))**x1)
<lambdifygenerated-14145>:2: RuntimeWarning: invalid value encountered in power
  return exp(x1 + ((_a3_**cos(_a3_ + _a6_ + x1)*x1 + 2*x1)**(2*x1))**x1)
<lambdifygenerated-14145>:2: RuntimeWarning: overflow encountered in exp
  return exp(x1 + ((_a3_**cos(_a3_ + _a6_ + x1)*x1 + 2*x1)**(2*x1))**x1)
<lambdifygenerated-14146>:2: RuntimeWarning: invalid value encountered in power
  return exp(x1 + ((_a3_**cos(_a3_ + _a6_ + x1)*x1 + 2*x1)**(2*x1))**x1)
<lambdifygenerated-14146>:2: RuntimeWarning: overflow encountered in exp
  return exp(x1 + ((_a3_**cos(_a3_ + _a6_ + x1)*x1 + 2*x1)**(2*x1))**x1)
<lambdifygenerated-14147>:2: RuntimeWarning: invalid value encountered in power
  return exp(x1 + ((_a3_**cos(_a3_ + _a6_ + 1)*x1 + 2*x1)**(2*x1))**x1)
<lambdifygenerated-14147>:2: RuntimeWarning: overflow encountered in exp
  return exp(x1 + ((_a3_**cos(_a3_ + _a6_ + 1)*x1 + 2*x1)**(2*x1))**x1)
<lambdifygenerated-14148>:2: RuntimeWarning: invalid value encountered in power
  return exp(x1 + ((_a3_**cos(_a3_ + _a6_ + 1)*x1 + 2*x1)**(2*x1))**x1)
<lambdifygenerated-14148>:2: RuntimeWarning: overflow encountered in exp
  return exp(x1 + ((_a3_**cos(_a3_ + _a6_ + 1)*x1 + 2*x1)**(2*x1))**x1)
<lambdifygenerated-14149>:2: RuntimeWarning: invalid value encountered in power
  return exp(x1 + ((_a3_**cos(_a3_ + _a6_ + x1)*x1 + 2*x1)**(2*x1))**x1)
<lambdifygenerated-14149>:2: RuntimeWarning: overflow encountered in exp
  return exp(x1 + ((_a3_**cos(_a3_ + _a6_ + x1)*x1 + 2*x1)**(2*x1))**x1)
<lambdifygenerated-14150>:2: RuntimeWarning: invalid value encountered in power
  return exp(x1 + ((_a3_**cos(_a3_ + _a6_ + x1)*x1 + 2*x1)**(2*x1))**x1)
<lambdifygenerated-14150>:2: RuntimeWarning: overflow encountered in exp
  return exp(x1 + ((_a3_**cos(_a3_ + _a6_ + x1)*x1 + 2*x1)**(2*x1))**x1)
<lambdifygenerated-14151>:2: RuntimeWarning: invalid value encountered in power
  return exp(x1 + ((_a3_**cos(_a2_ + _a3_ + _a6_)*x1 + 2*x1)**(2*x1))**x1)
<lambdifygenerated-14151>:2: RuntimeWarning: overflow encountered in exp
  return exp(x1 + ((_a3_**cos(_a2_ + _a3_ + _a6_)*x1 + 2*x1)**(2*x1))**x1)
<lambdifygenerated-14152>:2: RuntimeWarning: invalid value encountered in power
  return exp(x1 + ((_a3_**cos(_a2_ + _a3_ + _a6_)*x1 + 2*x1)**(2*x1))**x1)
<lambdifygenerated-14152>:2: RuntimeWarning: overflow encountered in exp
  return exp(x1 + ((_a3_**cos(_a2_ + _a3_ + _a6_)*x1 + 2*x1)**(2*x1))**x1)
<lambdifygenerated-14153>:2: RuntimeWarning: invalid value encountered in power
  return exp(x1 + ((_a3_**cos(_a2_*x1 + _a3_ + _a6_)*x1 + 2*x1)**(2*x1))**x1)
<lambdifygenerated-14153>:2: RuntimeWarning: overflow encountered in exp
  return exp(x1 + ((_a3_**cos(_a2_*x1 + _a3_ + _a6_)*x1 + 2*x1)**(2*x1))**x1)
<lambdifygenerated-14154>:2: RuntimeWarning: invalid value encountered in power
  return exp(x1 + ((_a3_**cos(_a2_*x1 + _a3_ + _a6_)*x1 + 2*x1)**(2*x1))**x1)
<lambdifygenerated-14154>:2: RuntimeWarning: overflow encountered in exp
  return exp(x1 + ((_a3_**cos(_a2_*x1 + _a3_ + _a6_)*x1 + 2*x1)**(2*x1))**x1)
<lambdifygenerated-14155>:2: RuntimeWarning: invalid value encountered in power
  return exp(x1 + ((_a3_**cos(2*_a2_*x1 + _a3_ + _a6_)*x1 + 2*x1)**(2*x1))**x1)
<lambdifygenerated-14155>:2: RuntimeWarning: overflow encountered in exp
  return exp(x1 + ((_a3_**cos(2*_a2_*x1 + _a3_ + _a6_)*x1 + 2*x1)**(2*x1))**x1)
<lambdifygenerated-14156>:2: RuntimeWarning: invalid value encountered in power
  return exp(x1 + ((_a3_**cos(2*_a2_*x1 + _a3_ + _a6_)*x1 + 2*x1)**(2*x1))**x1)
<lambdifygenerated-14156>:2: RuntimeWarning: overflow encountered in exp
  return exp(x1 + ((_a3_**cos(2*_a2_*x1 + _a3_ + _a6_)*x1 + 2*x1)**(2*x1))**x1)
<lambdifygenerated-14157>:2: RuntimeWarning: invalid value encountered in power
  return exp(x1 + ((_a3_**cos(_a2_*(_a0_ + x1) + _a3_ + _a6_)*x1 + 2*x1)**(2*x1))**x1)
<lambdifygenerated-14157>:2: RuntimeWarning: overflow encountered in exp
  return exp(x1 + ((_a3_**cos(_a2_*(_a0_ + x1) + _a3_ + _a6_)*x1 + 2*x1)**(2*x1))**x1)
<lambdifygenerated-14158>:2: RuntimeWarning: invalid value encountered in power
  return exp(x1 + ((_a3_**cos(_a2_*(_a0_ + x1) + _a3_ + _a6_)*x1 + 2*x1)**(2*x1))**x1)
<lambdifygenerated-14158>:2: RuntimeWarning: overflow encountered in exp
  return exp(x1 + ((_a3_**cos(_a2_*(_a0_ + x1) + _a3_ + _a6_)*x1 + 2*x1)**(2*x1))**x1)
<lambdifygenerated-14159>:2: RuntimeWarning: invalid value encountered in power
  return exp(x1 + ((_a3_**cos(_a2_*(_a0_ + x1) + _a3_ + _a6_)*x1 + 2*x1)**(2*x1))**x1)
<lambdifygenerated-14159>:2: RuntimeWarning: overflow encountered in exp
  return exp(x1 + ((_a3_**cos(_a2_*(_a0_ + x1) + _a3_ + _a6_)*x1 + 2*x1)**(2*x1))**x1)
<lambdifygenerated-14160>:2: RuntimeWarning: invalid value encountered in power
  return exp(x1 + ((_a3_**cos(_a2_*(_a0_ + x1) + _a3_ + _a6_)*x1 + 2*x1)**(2*x1))**x1)
<lambdifygenerated-14160>:2: RuntimeWarning: overflow encountered in exp
  return exp(x1 + ((_a3_**cos(_a2_*(_a0_ + x1) + _a3_ + _a6_)*x1 + 2*x1)**(2*x1))**x1)
<lambdifygenerated-14161>:2: RuntimeWarning: invalid value encountered in power
  return exp(x1 + ((_a3_**cos(_a2_*(_a0_ + x1) + _a3_ + _a6_)*x1 + 2*x1)**(2*x1))**x1)
<lambdifygenerated-14161>:2: RuntimeWarning: overflow encountered in exp
  return exp(x1 + ((_a3_**cos(_a2_*(_a0_ + x1) + _a3_ + _a6_)*x1 + 2*x1)**(2*x1))**x1)
<lambdifygenerated-14162>:2: RuntimeWarning: invalid value encountered in power
  return exp(x1 + ((_a3_**cos(_a2_*(_a0_ + x1) + _a3_ + _a6_)*x1 + 2*x1)**(2*x1))**x1)
<lambdifygenerated-14162>:2: RuntimeWarning: overflow encountered in exp
  return exp(x1 + ((_a3_**cos(_a2_*(_a0_ + x1) + _a3_ + _a6_)*x1 + 2*x1)**(2*x1))**x1)
<lambdifygenerated-14163>:2: RuntimeWarning: invalid value encountered in power
  return exp(x1 + ((_a3_**cos(_a3_ + _a6_ + x1*(_a0_ + x1))*x1 + 2*x1)**(2*x1))**x1)
<lambdifygenerated-14163>:2: RuntimeWarning: overflow encountered in exp
  return exp(x1 + ((_a3_**cos(_a3_ + _a6_ + x1*(_a0_ + x1))*x1 + 2*x1)**(2*x1))**x1)
<lambdifygenerated-14164>:2: RuntimeWarning: invalid value encountered in power
  return exp(x1 + ((_a3_**cos(_a3_ + _a6_ + x1*(_a0_ + x1))*x1 + 2*x1)**(2*x1))**x1)
<lambdifygenerated-14164>:2: RuntimeWarning: overflow encountered in exp
  return exp(x1 + ((_a3_**cos(_a3_ + _a6_ + x1*(_a0_ + x1))*x1 + 2*x1)**(2*x1))**x1)
<lambdifygenerated-14165>:2: RuntimeWarning: invalid value encountered in power
  return exp(x1 + ((_a3_**cos(_a3_ + _a6_ + x1*(_a0_ + x1))*_a6_ + 2*x1)**(2*x1))**x1)
<lambdifygenerated-14165>:2: RuntimeWarning: overflow encountered in exp
  return exp(x1 + ((_a3_**cos(_a3_ + _a6_ + x1*(_a0_ + x1))*_a6_ + 2*x1)**(2*x1))**x1)
<lambdifygenerated-14166>:2: RuntimeWarning: invalid value encountered in power
  return exp(x1 + ((_a3_**cos(_a3_ + _a6_ + x1*(_a0_ + x1))*_a6_ + 2*x1)**(2*x1))**x1)
<lambdifygenerated-14166>:2: RuntimeWarning: overflow encountered in exp
  return exp(x1 + ((_a3_**cos(_a3_ + _a6_ + x1*(_a0_ + x1))*_a6_ + 2*x1)**(2*x1))**x1)
<lambdifygenerated-14167>:2: RuntimeWarning: overflow encountered in exp
  return exp(x1 + ((_a3_**cos(_a3_ + _a6_ + x1*(_a0_ + x1))*_a6_ + x1**2 + x1)**(2*x1))**x1)
<lambdifygenerated-14168>:2: RuntimeWarning: overflow encountered in exp
  return exp(x1 + ((_a3_**cos(_a3_ + _a6_ + x1*(_a0_ + x1))*_a6_ + x1**2 + x1)**(2*x1))**x1)
<lambdifygenerated-14169>:2: RuntimeWarning: invalid value encountered in power
  return exp(x1 + ((_a2_*x1 + _a3_**cos(_a3_ + _a6_ + x1*(_a0_ + x1))*_a6_ + x1)**(2*x1))**x1)
<lambdifygenerated-14169>:2: RuntimeWarning: overflow encountered in exp
  return exp(x1 + ((_a2_*x1 + _a3_**cos(_a3_ + _a6_ + x1*(_a0_ + x1))*_a6_ + x1)**(2*x1))**x1)
<lambdifygenerated-14170>:2: RuntimeWarning: invalid value encountered in power
  return exp(x1 + ((_a2_*x1 + _a3_**cos(_a3_ + _a6_ + x1*(_a0_ + x1))*_a6_ + x1)**(2*x1))**x1)
<lambdifygenerated-14170>:2: RuntimeWarning: overflow encountered in exp
  return exp(x1 + ((_a2_*x1 + _a3_**cos(_a3_ + _a6_ + x1*(_a0_ + x1))*_a6_ + x1)**(2*x1))**x1)
<lambdifygenerated-14171>:2: RuntimeWarning: invalid value encountered in power
  return exp(x1 + ((2*_a2_*x1 + _a3_**cos(_a3_ + _a6_ + x1*(_a0_ + x1))*_a6_ + x1)**(2*x1))**x1)
<lambdifygenerated-14171>:2: RuntimeWarning: overflow encountered in exp
  return exp(x1 + ((2*_a2_*x1 + _a3_**cos(_a3_ + _a6_ + x1*(_a0_ + x1))*_a6_ + x1)**(2*x1))**x1)
<lambdifygenerated-14172>:2: RuntimeWarning: invalid value encountered in power
  return exp(x1 + ((2*_a2_*x1 + _a3_**cos(_a3_ + _a6_ + x1*(_a0_ + x1))*_a6_ + x1)**(2*x1))**x1)
<lambdifygenerated-14172>:2: RuntimeWarning: overflow encountered in exp
  return exp(x1 + ((2*_a2_*x1 + _a3_**cos(_a3_ + _a6_ + x1*(_a0_ + x1))*_a6_ + x1)**(2*x1))**x1)
<lambdifygenerated-14173>:2: RuntimeWarning: invalid value encountered in power
  return exp(x1 + ((2*_a2_*x1 + _a3_**cos(_a3_ + _a6_ + x1*(_a0_ + x1))*_a6_ + x1)**(2*x1))**x1)
<lambdifygenerated-14173>:2: RuntimeWarning: overflow encountered in exp
  return exp(x1 + ((2*_a2_*x1 + _a3_**cos(_a3_ + _a6_ + x1*(_a0_ + x1))*_a6_ + x1)**(2*x1))**x1)
<lambdifygenerated-14174>:2: RuntimeWarning: invalid value encountered in power
  return exp(x1 + ((2*_a2_*x1 + _a3_**cos(_a3_ + _a6_ + x1*(_a0_ + x1))*_a6_ + x1)**(2*x1))**x1)
<lambdifygenerated-14174>:2: RuntimeWarning: overflow encountered in exp
  return exp(x1 + ((2*_a2_*x1 + _a3_**cos(_a3_ + _a6_ + x1*(_a0_ + x1))*_a6_ + x1)**(2*x1))**x1)
<lambdifygenerated-14175>:2: RuntimeWarning: invalid value encountered in power
  return exp(x1 + ((_a2_*(_a5_ + x1) + _a3_**cos(_a3_ + _a6_ + x1*(_a0_ + x1))*_a6_ + x1)**(2*x1))**x1)
<lambdifygenerated-14175>:2: RuntimeWarning: overflow encountered in exp
  return exp(x1 + ((_a2_*(_a5_ + x1) + _a3_**cos(_a3_ + _a6_ + x1*(_a0_ + x1))*_a6_ + x1)**(2*x1))**x1)
<lambdifygenerated-14176>:2: RuntimeWarning: invalid value encountered in power
  return exp(x1 + ((_a2_*(_a5_ + x1) + _a3_**cos(_a3_ + _a6_ + x1*(_a0_ + x1))*_a6_ + x1)**(2*x1))**x1)
<lambdifygenerated-14176>:2: RuntimeWarning: overflow encountered in exp
  return exp(x1 + ((_a2_*(_a5_ + x1) + _a3_**cos(_a3_ + _a6_ + x1*(_a0_ + x1))*_a6_ + x1)**(2*x1))**x1)
<lambdifygenerated-14177>:2: RuntimeWarning: overflow encountered in exp
  return exp(x1 + ((_a2_*(_a5_ + x1) + _a3_**cos(_a3_ + _a6_ + x1*(_a0_ + x1))*_a6_ + x1**2)**(2*x1))**x1)
<lambdifygenerated-14178>:2: RuntimeWarning: overflow encountered in exp
  return exp(x1 + ((_a2_*(_a5_ + x1) + _a3_**cos(_a3_ + _a6_ + x1*(_a0_ + x1))*_a6_ + x1**2)**(2*x1))**x1)
<lambdifygenerated-14179>:2: RuntimeWarning: invalid value encountered in power
  return exp(x1 + ((_a2_*(_a5_ + x1) + _a3_**cos(_a3_ + _a6_ + x1*(_a0_ + x1))*_a6_ + _a4_*x1)**(2*x1))**x1)
<lambdifygenerated-14179>:2: RuntimeWarning: overflow encountered in exp
  return exp(x1 + ((_a2_*(_a5_ + x1) + _a3_**cos(_a3_ + _a6_ + x1*(_a0_ + x1))*_a6_ + _a4_*x1)**(2*x1))**x1)
<lambdifygenerated-14180>:2: RuntimeWarning: invalid value encountered in power
  return exp(x1 + ((_a2_*(_a5_ + x1) + _a3_**cos(_a3_ + _a6_ + x1*(_a0_ + x1))*_a6_ + _a4_*x1)**(2*x1))**x1)
<lambdifygenerated-14180>:2: RuntimeWarning: overflow encountered in exp
  return exp(x1 + ((_a2_*(_a5_ + x1) + _a3_**cos(_a3_ + _a6_ + x1*(_a0_ + x1))*_a6_ + _a4_*x1)**(2*x1))**x1)
<lambdifygenerated-14181>:2: RuntimeWarning: overflow encountered in exp
  return exp(x1 + ((_a2_*_a4_ + _a2_*(_a5_ + x1) + _a3_**cos(_a3_ + _a6_ + x1*(_a0_ + x1))*_a6_)**(2*x1))**x1)
<lambdifygenerated-14182>:2: RuntimeWarning: overflow encountered in exp
  return exp(x1 + ((_a2_*_a4_ + _a2_*(_a5_ + x1) + _a3_**cos(_a3_ + _a6_ + x1*(_a0_ + x1))*_a6_)**(2*x1))**x1)
<lambdifygenerated-14183>:2: RuntimeWarning: overflow encountered in exp
  return exp(x1 + ((_a2_*_a4_ + _a2_*(_a5_ + x1) + _a3_**cos(_a3_ + _a6_ + x1*(_a0_ + x1))*_a6_)**(4*x1))**x1)
<lambdifygenerated-14184>:2: RuntimeWarning: overflow encountered in exp
  return exp(x1 + ((_a2_*_a4_ + _a2_*(_a5_ + x1) + _a3_**cos(_a3_ + _a6_ + x1*(_a0_ + x1))*_a6_)**(4*x1))**x1)
<lambdifygenerated-14185>:2: RuntimeWarning: invalid value encountered in power
  return exp(x1 + ((_a2_*_a4_ + _a2_*(_a5_ + x1) + _a3_**cos(_a3_ + _a6_ + x1*(_a0_ + x1))*_a6_)**(2*x1 + 2*x1**x1))**x1)
<lambdifygenerated-14185>:2: RuntimeWarning: overflow encountered in exp
  return exp(x1 + ((_a2_*_a4_ + _a2_*(_a5_ + x1) + _a3_**cos(_a3_ + _a6_ + x1*(_a0_ + x1))*_a6_)**(2*x1 + 2*x1**x1))**x1)
<lambdifygenerated-14186>:2: RuntimeWarning: invalid value encountered in power
  return exp(x1 + ((_a2_*_a4_ + _a2_*(_a5_ + x1) + _a3_**cos(_a3_ + _a6_ + x1*(_a0_ + x1))*_a6_)**(2*x1 + 2*x1**x1))**x1)
<lambdifygenerated-14186>:2: RuntimeWarning: overflow encountered in exp
  return exp(x1 + ((_a2_*_a4_ + _a2_*(_a5_ + x1) + _a3_**cos(_a3_ + _a6_ + x1*(_a0_ + x1))*_a6_)**(2*x1 + 2*x1**x1))**x1)
<lambdifygenerated-14187>:2: RuntimeWarning: overflow encountered in exp
  return exp(x1 + ((_a2_*_a4_ + _a2_*(_a5_ + x1) + _a3_**cos(_a3_ + _a6_ + x1*(_a0_ + x1))*_a6_)**(2*_a4_**x1 + 2*x1))**x1)
<lambdifygenerated-14188>:2: RuntimeWarning: overflow encountered in exp
  return exp(x1 + ((_a2_*_a4_ + _a2_*(_a5_ + x1) + _a3_**cos(_a3_ + _a6_ + x1*(_a0_ + x1))*_a6_)**(2*_a4_**x1 + 2*x1))**x1)
<lambdifygenerated-14189>:2: RuntimeWarning: overflow encountered in exp
  return exp(x1 + ((_a2_*_a4_ + _a2_*(_a5_ + x1) + _a3_**cos(_a3_ + _a6_ + x1*(_a0_ + x1))*_a6_)**(2*_a4_**x1 + 2*x1))**x1)
<lambdifygenerated-14190>:2: RuntimeWarning: overflow encountered in exp
  return exp(x1 + ((_a2_*_a4_ + _a2_*(_a5_ + x1) + _a3_**cos(_a3_ + _a6_ + x1*(_a0_ + x1))*_a6_)**(2*_a4_**x1 + 2*x1))**x1)
<lambdifygenerated-14191>:2: RuntimeWarning: overflow encountered in exp
  return exp(x1 + ((_a2_*_a4_ + _a2_*(_a5_ + x1) + _a3_**cos(_a3_ + _a6_ + x1*(_a0_ + x1))*_a6_)**(2*_a4_**x1 + 2*_a5_))**x1)
<lambdifygenerated-14192>:2: RuntimeWarning: overflow encountered in exp
  return exp(x1 + ((_a2_*_a4_ + _a2_*(_a5_ + x1) + _a3_**cos(_a3_ + _a6_ + x1*(_a0_ + x1))*_a6_)**(2*_a4_**x1 + 2*_a5_))**x1)
<lambdifygenerated-14193>:2: RuntimeWarning: invalid value encountered in power
  return exp(x1 + (_a7_*(_a2_*_a4_ + _a2_*(_a5_ + x1) + _a3_**cos(_a3_ + _a6_ + x1*(_a0_ + x1))*_a6_)**(2*_a4_**x1 + 2*_a5_)/x1)**x1)

interpolation

<lambdifygenerated-14199>:2: RuntimeWarning: invalid value encountered in power
  return exp(_a1_ + (_a7_*(_a2_*_a4_ + _a2_*(_a5_ + x1) + _a3_**cos(_a3_ + _a6_ + x1*(_a0_ + x1))*_a6_)**(2*_a4_**x1 + 2*_a5_)/_a3_)**_a4_)

         x1         y  rep    ymodel      ybms
3745  0.997  0.997734  2.0  1.003144  1.006761
3746  0.998  0.997761  2.0  1.003173  1.006942
3747  0.998  0.997787  2.0  1.003203  1.007125
3748  0.999  0.997814  2.0  1.003232  1.007309

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.997867  2.0  1.003291  1.007679
3751  1.002  0.997894  2.0  1.003321  1.007866
3752  1.002  0.997921  2.0  1.003350  1.008054
3753  1.003  0.997948  2.0  1.003379  1.008242

3750

<lambdifygenerated-14217>:2: RuntimeWarning: invalid value encountered in power
  return x1*cos(x1**x1/x1) + x1
<lambdifygenerated-14218>:2: RuntimeWarning: invalid value encountered in power
  return x1*cos(x1**x1/x1) + x1
<lambdifygenerated-14225>:2: RuntimeWarning: overflow encountered in power
  return x1*cos(_a5_**(_a7_*x1)/x1) + x1
<lambdifygenerated-14225>:2: RuntimeWarning: invalid value encountered in cos
  return x1*cos(_a5_**(_a7_*x1)/x1) + x1
<lambdifygenerated-14231>:2: RuntimeWarning: invalid value encountered in power
  return x1*cos(_a5_**(_a7_*x1)/(x1 + tanh(x1**x1))) + x1
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-14232>:2: RuntimeWarning: invalid value encountered in power
  return x1*cos(_a5_**(_a7_*x1)/(x1 + tanh(x1**x1))) + x1
<lambdifygenerated-14269>:2: RuntimeWarning: overflow encountered in power
  return x1*cos(_a5_**(_a7_*x1)/(x1 + tanh(_a5_**(_a0_*_a4_*x1**2*tanh(_a1_*_a4_/x1 + _a1_*x1/_a7_))))) + x1
<lambdifygenerated-14270>:2: RuntimeWarning: overflow encountered in power
  return x1*cos(_a5_**(_a7_*x1)/(x1 + tanh(_a5_**(_a0_*_a4_*x1**2*tanh(_a1_*_a4_/x1 + _a1_*x1/_a7_))))) + x1
<lambdifygenerated-14271>:2: RuntimeWarning: overflow encountered in power
  return x1*cos(_a5_**(_a7_*x1)/(x1 + tanh(_a5_**(2*_a0_*_a4_*x1**2*tanh(_a1_*_a4_/x1 + _a1_*x1/_a7_))))) + x1
<lambdifygenerated-14272>:2: RuntimeWarning: overflow encountered in power
  return x1*cos(_a5_**(_a7_*x1)/(x1 + tanh(_a5_**(2*_a0_*_a4_*x1**2*tanh(_a1_*_a4_/x1 + _a1_*x1/_a7_))))) + x1
<lambdifygenerated-14273>:2: RuntimeWarning: overflow encountered in power
  return x1*cos(_a5_**(_a7_*x1)/(x1 + tanh(_a5_**(2*_a0_*_a4_*x1**2*tanh(_a1_*_a4_/x1 + _a1_*x1/_a7_))))) + x1
<lambdifygenerated-14274>:2: RuntimeWarning: overflow encountered in power
  return x1*cos(_a5_**(_a7_*x1)/(x1 + tanh(_a5_**(2*_a0_*_a4_*x1**2*tanh(_a1_*_a4_/x1 + _a1_*x1/_a7_))))) + x1
<lambdifygenerated-14275>:2: RuntimeWarning: overflow encountered in power
  return x1*cos(_a5_**(_a7_*x1)/(x1 + tanh(_a5_**(_a0_*_a4_*x1*(x1**2 + x1)*tanh(_a1_*_a4_/x1 + _a1_*x1/_a7_))))) + x1
<lambdifygenerated-14276>:2: RuntimeWarning: overflow encountered in power
  return x1*cos(_a5_**(_a7_*x1)/(x1 + tanh(_a5_**(_a0_*_a4_*x1*(x1**2 + x1)*tanh(_a1_*_a4_/x1 + _a1_*x1/_a7_))))) + x1
<lambdifygenerated-14277>:2: RuntimeWarning: overflow encountered in power
  return x1*cos(_a5_**(_a7_*x1)/(x1 + tanh(_a5_**(_a0_*_a4_*x1*(_a4_*x1 + x1)*tanh(_a1_*_a4_/x1 + _a1_*x1/_a7_))))) + x1
<lambdifygenerated-14278>:2: RuntimeWarning: overflow encountered in power
  return x1*cos(_a5_**(_a7_*x1)/(x1 + tanh(_a5_**(_a0_*_a4_*x1*(_a4_*x1 + x1)*tanh(_a1_*_a4_/x1 + _a1_*x1/_a7_))))) + x1
<lambdifygenerated-14283>:2: RuntimeWarning: overflow encountered in power
  return x1*cos(_a5_**(_a7_*x1)/(x1 + tanh(_a5_**(_a0_*_a4_*x1**6*(_a3_*_a4_ + x1)*tanh(_a1_*_a4_/x1 + _a1_*x1/_a7_))))) + x1
<lambdifygenerated-14284>:2: RuntimeWarning: overflow encountered in power
  return x1*cos(_a5_**(_a7_*x1)/(x1 + tanh(_a5_**(_a0_*_a4_*x1**6*(_a3_*_a4_ + x1)*tanh(_a1_*_a4_/x1 + _a1_*x1/_a7_))))) + x1
<lambdifygenerated-14285>:2: RuntimeWarning: overflow encountered in power
  return x1*cos(_a5_**(_a7_*x1)/(x1 + tanh(_a5_**(_a0_*_a4_*x1**6*(_a3_*_a4_ + x1)*tanh(_a1_*_a4_/x1 + _a1_*x1/_a7_))))) + x1
<lambdifygenerated-14286>:2: RuntimeWarning: overflow encountered in power
  return x1*cos(_a5_**(_a7_*x1)/(x1 + tanh(_a5_**(_a0_*_a4_*x1**6*(_a3_*_a4_ + x1)*tanh(_a1_*_a4_/x1 + _a1_*x1/_a7_))))) + x1

interpolation

<lambdifygenerated-14299>:2: RuntimeWarning: overflow encountered in power
  return _a2_*cos(_a5_**(_a7_*x1)/(_a6_ + x1 + tanh(_a5_**(_a0_*_a4_*_a6_**3*x1**3*(_a3_*_a4_ + x1)*tanh(_a1_*_a4_/x1 + _a1_*x1/_a7_))))) - _a3_
<lambdifygenerated-14300>:2: RuntimeWarning: overflow encountered in power
  return _a2_*cos(_a5_**(_a7_*x1)/(_a6_ + x1 + tanh(_a5_**(_a0_*_a4_*_a6_**3*x1**3*(_a3_*_a4_ + x1)*tanh(_a1_*_a4_/x1 + _a1_*x1/_a7_))))) - _a3_
<lambdifygenerated-14301>:2: RuntimeWarning: overflow encountered in power
  return _a2_*cos(_a5_**(_a7_*x1)/(_a6_ + x1 + tanh(_a5_**(_a0_*_a4_*_a6_**3*x1**3*(_a3_*_a4_ + x1)*tanh(_a1_*_a4_/x1 + _a1_*x1/_a7_))))) - _a3_
<lambdifygenerated-14302>:2: RuntimeWarning: overflow encountered in power
  return _a2_*cos(_a5_**(_a7_*x1)/(_a6_ + x1 + tanh(_a5_**(_a0_*_a4_*_a6_**3*x1**3*(_a3_*_a4_ + x1)*tanh(_a1_*_a4_/x1 + _a1_*x1/_a7_))))) - _a3_
<lambdifygenerated-14303>:2: RuntimeWarning: overflow encountered in power
  return _a2_*cos(_a5_**(_a7_*x1)/(_a6_ + x1 + tanh(_a5_**(_a0_*_a4_*_a6_**3*x1**3*(_a3_*_a4_ + x1)*tanh(_a1_*_a4_/x1 + _a1_*x1/_a7_))))) - _a3_
<lambdifygenerated-14304>:2: RuntimeWarning: overflow encountered in power
  return _a2_*cos(_a5_**(_a7_*x1)/(_a6_ + x1 + tanh(_a5_**(_a0_*_a4_*_a6_**3*x1**3*(_a3_*_a4_ + x1)*tanh(_a1_*_a4_/x1 + _a1_*x1/_a7_))))) - _a3_

         x1         y  rep    ymodel      ybms
3745  0.997  0.689029  3.0  0.681004  0.686060
3746  0.998  0.688777  3.0  0.680613  0.685683
3747  0.998  0.688525  3.0  0.680222  0.685306
3748  0.999  0.688273  3.0  0.679830  0.684929

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.687768  3.0  0.679048  0.684173
3751  1.002  0.687516  3.0  0.678657  0.683795
3752  1.002  0.687264  3.0  0.678265  0.683416
3753  1.003  0.687012  3.0  0.677874  0.683036

3750

<lambdifygenerated-14309>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1
<lambdifygenerated-14310>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1
<lambdifygenerated-14313>:2: RuntimeWarning: invalid value encountered in power
  return (x1*exp(x1))**x1
<lambdifygenerated-14314>:2: RuntimeWarning: invalid value encountered in power
  return (x1*exp(x1))**x1
<lambdifygenerated-14315>:2: RuntimeWarning: invalid value encountered in power
  return (e*x1)**x1
<lambdifygenerated-14316>:2: RuntimeWarning: invalid value encountered in power
  return (e*x1)**x1
<lambdifygenerated-14317>:2: RuntimeWarning: invalid value encountered in sqrt
  return (x1*exp(1/sqrt(x1)))**x1
<lambdifygenerated-14318>:2: RuntimeWarning: invalid value encountered in sqrt
  return (x1*exp(1/sqrt(x1)))**x1
<lambdifygenerated-14319>:2: RuntimeWarning: invalid value encountered in power
  return (x1*exp(sqrt(x1**x1)/x1))**x1
<lambdifygenerated-14319>:2: RuntimeWarning: overflow encountered in exp
  return (x1*exp(sqrt(x1**x1)/x1))**x1
<lambdifygenerated-14320>:2: RuntimeWarning: invalid value encountered in power
  return (x1*exp(sqrt(x1**x1)/x1))**x1
<lambdifygenerated-14320>:2: RuntimeWarning: overflow encountered in exp
  return (x1*exp(sqrt(x1**x1)/x1))**x1
<lambdifygenerated-14321>:2: RuntimeWarning: overflow encountered in exp
  return (x1*exp(sqrt((x1**2)**x1)/x1))**x1
<lambdifygenerated-14321>:2: RuntimeWarning: divide by zero encountered in power
  return (x1*exp(sqrt((x1**2)**x1)/x1))**x1
<lambdifygenerated-14321>:2: RuntimeWarning: invalid value encountered in power
  return (x1*exp(sqrt((x1**2)**x1)/x1))**x1
<lambdifygenerated-14322>:2: RuntimeWarning: overflow encountered in exp
  return (x1*exp(sqrt((x1**2)**x1)/x1))**x1
<lambdifygenerated-14322>:2: RuntimeWarning: divide by zero encountered in power
  return (x1*exp(sqrt((x1**2)**x1)/x1))**x1
<lambdifygenerated-14322>:2: RuntimeWarning: invalid value encountered in power
  return (x1*exp(sqrt((x1**2)**x1)/x1))**x1
<lambdifygenerated-14323>:2: RuntimeWarning: overflow encountered in exp
  return (x1*exp(sqrt((x1**4)**x1)/x1))**x1
<lambdifygenerated-14323>:2: RuntimeWarning: divide by zero encountered in power
  return (x1*exp(sqrt((x1**4)**x1)/x1))**x1
<lambdifygenerated-14323>:2: RuntimeWarning: invalid value encountered in power
  return (x1*exp(sqrt((x1**4)**x1)/x1))**x1
<lambdifygenerated-14324>:2: RuntimeWarning: overflow encountered in exp
  return (x1*exp(sqrt((x1**4)**x1)/x1))**x1
<lambdifygenerated-14324>:2: RuntimeWarning: divide by zero encountered in power
  return (x1*exp(sqrt((x1**4)**x1)/x1))**x1
<lambdifygenerated-14324>:2: RuntimeWarning: invalid value encountered in power
  return (x1*exp(sqrt((x1**4)**x1)/x1))**x1
<lambdifygenerated-14325>:2: RuntimeWarning: overflow encountered in exp
  return (x1*exp(sqrt((x1**6)**x1)/x1))**x1
<lambdifygenerated-14325>:2: RuntimeWarning: divide by zero encountered in power
  return (x1*exp(sqrt((x1**6)**x1)/x1))**x1
<lambdifygenerated-14325>:2: RuntimeWarning: invalid value encountered in power
  return (x1*exp(sqrt((x1**6)**x1)/x1))**x1
<lambdifygenerated-14326>:2: RuntimeWarning: overflow encountered in exp
  return (x1*exp(sqrt((x1**6)**x1)/x1))**x1
<lambdifygenerated-14326>:2: RuntimeWarning: divide by zero encountered in power
  return (x1*exp(sqrt((x1**6)**x1)/x1))**x1
<lambdifygenerated-14326>:2: RuntimeWarning: invalid value encountered in power
  return (x1*exp(sqrt((x1**6)**x1)/x1))**x1
<lambdifygenerated-14327>:2: RuntimeWarning: overflow encountered in exp
  return (x1*exp(sqrt((16*x1**6)**x1)/x1))**x1
<lambdifygenerated-14327>:2: RuntimeWarning: divide by zero encountered in power
  return (x1*exp(sqrt((16*x1**6)**x1)/x1))**x1
<lambdifygenerated-14327>:2: RuntimeWarning: overflow encountered in power
  return (x1*exp(sqrt((16*x1**6)**x1)/x1))**x1
<lambdifygenerated-14327>:2: RuntimeWarning: invalid value encountered in power
  return (x1*exp(sqrt((16*x1**6)**x1)/x1))**x1
/usr/local/lib/python3.10/dist-packages/pandas/core/arraylike.py:399: RuntimeWarning: overflow encountered in square
  result = getattr(ufunc, method)(*inputs, **kwargs)
<lambdifygenerated-14328>:2: RuntimeWarning: overflow encountered in exp
  return (x1*exp(sqrt((16*x1**6)**x1)/x1))**x1
<lambdifygenerated-14328>:2: RuntimeWarning: divide by zero encountered in power
  return (x1*exp(sqrt((16*x1**6)**x1)/x1))**x1
<lambdifygenerated-14328>:2: RuntimeWarning: overflow encountered in power
  return (x1*exp(sqrt((16*x1**6)**x1)/x1))**x1
<lambdifygenerated-14328>:2: RuntimeWarning: invalid value encountered in power
  return (x1*exp(sqrt((16*x1**6)**x1)/x1))**x1
<lambdifygenerated-14329>:2: RuntimeWarning: overflow encountered in exp
  return (x1*exp(sqrt((x1**2*(x1 + sin(x1))**4)**x1)/x1))**x1
<lambdifygenerated-14329>:2: RuntimeWarning: divide by zero encountered in power
  return (x1*exp(sqrt((x1**2*(x1 + sin(x1))**4)**x1)/x1))**x1
<lambdifygenerated-14329>:2: RuntimeWarning: invalid value encountered in power
  return (x1*exp(sqrt((x1**2*(x1 + sin(x1))**4)**x1)/x1))**x1
<lambdifygenerated-14330>:2: RuntimeWarning: overflow encountered in exp
  return (x1*exp(sqrt((x1**2*(x1 + sin(x1))**4)**x1)/x1))**x1
<lambdifygenerated-14330>:2: RuntimeWarning: divide by zero encountered in power
  return (x1*exp(sqrt((x1**2*(x1 + sin(x1))**4)**x1)/x1))**x1
<lambdifygenerated-14330>:2: RuntimeWarning: invalid value encountered in power
  return (x1*exp(sqrt((x1**2*(x1 + sin(x1))**4)**x1)/x1))**x1
<lambdifygenerated-14331>:2: RuntimeWarning: overflow encountered in exp
  return (x1*exp(sqrt((x1**2*(x1 + sin(1))**4)**x1)/x1))**x1
<lambdifygenerated-14331>:2: RuntimeWarning: divide by zero encountered in power
  return (x1*exp(sqrt((x1**2*(x1 + sin(1))**4)**x1)/x1))**x1
<lambdifygenerated-14331>:2: RuntimeWarning: invalid value encountered in power
  return (x1*exp(sqrt((x1**2*(x1 + sin(1))**4)**x1)/x1))**x1
<lambdifygenerated-14332>:2: RuntimeWarning: overflow encountered in exp
  return (x1*exp(sqrt((x1**2*(x1 + sin(1))**4)**x1)/x1))**x1
<lambdifygenerated-14332>:2: RuntimeWarning: divide by zero encountered in power
  return (x1*exp(sqrt((x1**2*(x1 + sin(1))**4)**x1)/x1))**x1
<lambdifygenerated-14332>:2: RuntimeWarning: invalid value encountered in power
  return (x1*exp(sqrt((x1**2*(x1 + sin(1))**4)**x1)/x1))**x1
<lambdifygenerated-14333>:2: RuntimeWarning: overflow encountered in exp
  return (x1*exp(sqrt((x1**2*(x1 + sin(x1))**4)**x1)/x1))**x1
<lambdifygenerated-14333>:2: RuntimeWarning: divide by zero encountered in power
  return (x1*exp(sqrt((x1**2*(x1 + sin(x1))**4)**x1)/x1))**x1
<lambdifygenerated-14333>:2: RuntimeWarning: invalid value encountered in power
  return (x1*exp(sqrt((x1**2*(x1 + sin(x1))**4)**x1)/x1))**x1
<lambdifygenerated-14334>:2: RuntimeWarning: overflow encountered in exp
  return (x1*exp(sqrt((x1**2*(x1 + sin(x1))**4)**x1)/x1))**x1
<lambdifygenerated-14334>:2: RuntimeWarning: divide by zero encountered in power
  return (x1*exp(sqrt((x1**2*(x1 + sin(x1))**4)**x1)/x1))**x1
<lambdifygenerated-14334>:2: RuntimeWarning: invalid value encountered in power
  return (x1*exp(sqrt((x1**2*(x1 + sin(x1))**4)**x1)/x1))**x1
<lambdifygenerated-14335>:2: RuntimeWarning: overflow encountered in exp
  return (x1*exp(sqrt((x1**2*(x1 + sin(x1))**4)**x1)/x1))**x1
<lambdifygenerated-14335>:2: RuntimeWarning: divide by zero encountered in power
  return (x1*exp(sqrt((x1**2*(x1 + sin(x1))**4)**x1)/x1))**x1
<lambdifygenerated-14335>:2: RuntimeWarning: invalid value encountered in power
  return (x1*exp(sqrt((x1**2*(x1 + sin(x1))**4)**x1)/x1))**x1
<lambdifygenerated-14336>:2: RuntimeWarning: overflow encountered in exp
  return (x1*exp(sqrt((x1**2*(x1 + sin(x1))**4)**x1)/x1))**x1
<lambdifygenerated-14336>:2: RuntimeWarning: divide by zero encountered in power
  return (x1*exp(sqrt((x1**2*(x1 + sin(x1))**4)**x1)/x1))**x1
<lambdifygenerated-14336>:2: RuntimeWarning: invalid value encountered in power
  return (x1*exp(sqrt((x1**2*(x1 + sin(x1))**4)**x1)/x1))**x1
<lambdifygenerated-14337>:2: RuntimeWarning: overflow encountered in exp
  return (x1*exp(sqrt((x1**2*(x1 + sin(_a6_))**4)**x1)/x1))**x1
<lambdifygenerated-14337>:2: RuntimeWarning: divide by zero encountered in power
  return (x1*exp(sqrt((x1**2*(x1 + sin(_a6_))**4)**x1)/x1))**x1
<lambdifygenerated-14337>:2: RuntimeWarning: invalid value encountered in power
  return (x1*exp(sqrt((x1**2*(x1 + sin(_a6_))**4)**x1)/x1))**x1
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-14338>:2: RuntimeWarning: overflow encountered in exp
  return (x1*exp(sqrt((x1**2*(x1 + sin(_a6_))**4)**x1)/x1))**x1
<lambdifygenerated-14338>:2: RuntimeWarning: divide by zero encountered in power
  return (x1*exp(sqrt((x1**2*(x1 + sin(_a6_))**4)**x1)/x1))**x1
<lambdifygenerated-14338>:2: RuntimeWarning: invalid value encountered in power
  return (x1*exp(sqrt((x1**2*(x1 + sin(_a6_))**4)**x1)/x1))**x1
<lambdifygenerated-14339>:2: RuntimeWarning: overflow encountered in exp
  return (x1*exp(sqrt((x1**2*(x1 + sin(_a6_*x1/_a7_))**4)**x1)/x1))**x1
<lambdifygenerated-14339>:2: RuntimeWarning: divide by zero encountered in power
  return (x1*exp(sqrt((x1**2*(x1 + sin(_a6_*x1/_a7_))**4)**x1)/x1))**x1
<lambdifygenerated-14339>:2: RuntimeWarning: invalid value encountered in power
  return (x1*exp(sqrt((x1**2*(x1 + sin(_a6_*x1/_a7_))**4)**x1)/x1))**x1
<lambdifygenerated-14340>:2: RuntimeWarning: overflow encountered in exp
  return (x1*exp(sqrt((x1**2*(x1 + sin(_a6_*x1/_a7_))**4)**x1)/x1))**x1
<lambdifygenerated-14340>:2: RuntimeWarning: divide by zero encountered in power
  return (x1*exp(sqrt((x1**2*(x1 + sin(_a6_*x1/_a7_))**4)**x1)/x1))**x1
<lambdifygenerated-14340>:2: RuntimeWarning: invalid value encountered in power
  return (x1*exp(sqrt((x1**2*(x1 + sin(_a6_*x1/_a7_))**4)**x1)/x1))**x1
<lambdifygenerated-14341>:2: RuntimeWarning: overflow encountered in exp
  return (x1*exp(sqrt((x1**2*(2*x1 + sin(_a6_*x1/_a7_))**4)**x1)/x1))**x1
<lambdifygenerated-14341>:2: RuntimeWarning: divide by zero encountered in power
  return (x1*exp(sqrt((x1**2*(2*x1 + sin(_a6_*x1/_a7_))**4)**x1)/x1))**x1
<lambdifygenerated-14341>:2: RuntimeWarning: overflow encountered in power
  return (x1*exp(sqrt((x1**2*(2*x1 + sin(_a6_*x1/_a7_))**4)**x1)/x1))**x1
<lambdifygenerated-14341>:2: RuntimeWarning: invalid value encountered in power
  return (x1*exp(sqrt((x1**2*(2*x1 + sin(_a6_*x1/_a7_))**4)**x1)/x1))**x1
/usr/local/lib/python3.10/dist-packages/scipy/optimize/_minpack_py.py:1017: RuntimeWarning: overflow encountered in square
  cost = np.sum(infodict['fvec'] ** 2)
<lambdifygenerated-14342>:2: RuntimeWarning: overflow encountered in exp
  return (x1*exp(sqrt((x1**2*(2*x1 + sin(_a6_*x1/_a7_))**4)**x1)/x1))**x1
<lambdifygenerated-14342>:2: RuntimeWarning: divide by zero encountered in power
  return (x1*exp(sqrt((x1**2*(2*x1 + sin(_a6_*x1/_a7_))**4)**x1)/x1))**x1
<lambdifygenerated-14342>:2: RuntimeWarning: overflow encountered in power
  return (x1*exp(sqrt((x1**2*(2*x1 + sin(_a6_*x1/_a7_))**4)**x1)/x1))**x1
<lambdifygenerated-14342>:2: RuntimeWarning: invalid value encountered in power
  return (x1*exp(sqrt((x1**2*(2*x1 + sin(_a6_*x1/_a7_))**4)**x1)/x1))**x1
<lambdifygenerated-14343>:2: RuntimeWarning: overflow encountered in exp
  return (x1*exp(sqrt((x1**2*(x1**2 + x1 + sin(_a6_*x1/_a7_))**4)**x1)/x1))**x1
<lambdifygenerated-14343>:2: RuntimeWarning: divide by zero encountered in power
  return (x1*exp(sqrt((x1**2*(x1**2 + x1 + sin(_a6_*x1/_a7_))**4)**x1)/x1))**x1
<lambdifygenerated-14343>:2: RuntimeWarning: overflow encountered in power
  return (x1*exp(sqrt((x1**2*(x1**2 + x1 + sin(_a6_*x1/_a7_))**4)**x1)/x1))**x1
<lambdifygenerated-14343>:2: RuntimeWarning: invalid value encountered in power
  return (x1*exp(sqrt((x1**2*(x1**2 + x1 + sin(_a6_*x1/_a7_))**4)**x1)/x1))**x1
<lambdifygenerated-14344>:2: RuntimeWarning: overflow encountered in exp
  return (x1*exp(sqrt((x1**2*(x1**2 + x1 + sin(_a6_*x1/_a7_))**4)**x1)/x1))**x1
<lambdifygenerated-14344>:2: RuntimeWarning: divide by zero encountered in power
  return (x1*exp(sqrt((x1**2*(x1**2 + x1 + sin(_a6_*x1/_a7_))**4)**x1)/x1))**x1
<lambdifygenerated-14344>:2: RuntimeWarning: overflow encountered in power
  return (x1*exp(sqrt((x1**2*(x1**2 + x1 + sin(_a6_*x1/_a7_))**4)**x1)/x1))**x1
<lambdifygenerated-14344>:2: RuntimeWarning: invalid value encountered in power
  return (x1*exp(sqrt((x1**2*(x1**2 + x1 + sin(_a6_*x1/_a7_))**4)**x1)/x1))**x1
<lambdifygenerated-14345>:2: RuntimeWarning: overflow encountered in exp
  return (x1*exp(sqrt((x1**2*(x1*tan(x1) + x1 + sin(_a6_*x1/_a7_))**4)**x1)/x1))**x1
<lambdifygenerated-14345>:2: RuntimeWarning: divide by zero encountered in power
  return (x1*exp(sqrt((x1**2*(x1*tan(x1) + x1 + sin(_a6_*x1/_a7_))**4)**x1)/x1))**x1
<lambdifygenerated-14345>:2: RuntimeWarning: overflow encountered in power
  return (x1*exp(sqrt((x1**2*(x1*tan(x1) + x1 + sin(_a6_*x1/_a7_))**4)**x1)/x1))**x1
<lambdifygenerated-14345>:2: RuntimeWarning: invalid value encountered in power
  return (x1*exp(sqrt((x1**2*(x1*tan(x1) + x1 + sin(_a6_*x1/_a7_))**4)**x1)/x1))**x1
<lambdifygenerated-14346>:2: RuntimeWarning: overflow encountered in exp
  return (x1*exp(sqrt((x1**2*(x1*tan(x1) + x1 + sin(_a6_*x1/_a7_))**4)**x1)/x1))**x1
<lambdifygenerated-14346>:2: RuntimeWarning: divide by zero encountered in power
  return (x1*exp(sqrt((x1**2*(x1*tan(x1) + x1 + sin(_a6_*x1/_a7_))**4)**x1)/x1))**x1
<lambdifygenerated-14346>:2: RuntimeWarning: overflow encountered in power
  return (x1*exp(sqrt((x1**2*(x1*tan(x1) + x1 + sin(_a6_*x1/_a7_))**4)**x1)/x1))**x1
<lambdifygenerated-14346>:2: RuntimeWarning: invalid value encountered in power
  return (x1*exp(sqrt((x1**2*(x1*tan(x1) + x1 + sin(_a6_*x1/_a7_))**4)**x1)/x1))**x1
<lambdifygenerated-14347>:2: RuntimeWarning: invalid value encountered in power
  return (x1*exp(sqrt((x1**2*(x1*tan(x1**x1) + x1 + sin(_a6_*x1/_a7_))**4)**x1)/x1))**x1
<lambdifygenerated-14347>:2: RuntimeWarning: overflow encountered in exp
  return (x1*exp(sqrt((x1**2*(x1*tan(x1**x1) + x1 + sin(_a6_*x1/_a7_))**4)**x1)/x1))**x1
<lambdifygenerated-14347>:2: RuntimeWarning: overflow encountered in power
  return (x1*exp(sqrt((x1**2*(x1*tan(x1**x1) + x1 + sin(_a6_*x1/_a7_))**4)**x1)/x1))**x1
<lambdifygenerated-14348>:2: RuntimeWarning: invalid value encountered in power
  return (x1*exp(sqrt((x1**2*(x1*tan(x1**x1) + x1 + sin(_a6_*x1/_a7_))**4)**x1)/x1))**x1
<lambdifygenerated-14348>:2: RuntimeWarning: overflow encountered in exp
  return (x1*exp(sqrt((x1**2*(x1*tan(x1**x1) + x1 + sin(_a6_*x1/_a7_))**4)**x1)/x1))**x1
<lambdifygenerated-14348>:2: RuntimeWarning: overflow encountered in power
  return (x1*exp(sqrt((x1**2*(x1*tan(x1**x1) + x1 + sin(_a6_*x1/_a7_))**4)**x1)/x1))**x1
<lambdifygenerated-14349>:2: RuntimeWarning: overflow encountered in exp
  return (x1*exp(sqrt((x1**2*(x1*tan(_a1_**x1) + x1 + sin(_a6_*x1/_a7_))**4)**x1)/x1))**x1
<lambdifygenerated-14349>:2: RuntimeWarning: divide by zero encountered in power
  return (x1*exp(sqrt((x1**2*(x1*tan(_a1_**x1) + x1 + sin(_a6_*x1/_a7_))**4)**x1)/x1))**x1
<lambdifygenerated-14349>:2: RuntimeWarning: overflow encountered in power
  return (x1*exp(sqrt((x1**2*(x1*tan(_a1_**x1) + x1 + sin(_a6_*x1/_a7_))**4)**x1)/x1))**x1
<lambdifygenerated-14349>:2: RuntimeWarning: invalid value encountered in power
  return (x1*exp(sqrt((x1**2*(x1*tan(_a1_**x1) + x1 + sin(_a6_*x1/_a7_))**4)**x1)/x1))**x1
<lambdifygenerated-14350>:2: RuntimeWarning: overflow encountered in exp
  return (x1*exp(sqrt((x1**2*(x1*tan(_a1_**x1) + x1 + sin(_a6_*x1/_a7_))**4)**x1)/x1))**x1
<lambdifygenerated-14350>:2: RuntimeWarning: divide by zero encountered in power
  return (x1*exp(sqrt((x1**2*(x1*tan(_a1_**x1) + x1 + sin(_a6_*x1/_a7_))**4)**x1)/x1))**x1
<lambdifygenerated-14350>:2: RuntimeWarning: overflow encountered in power
  return (x1*exp(sqrt((x1**2*(x1*tan(_a1_**x1) + x1 + sin(_a6_*x1/_a7_))**4)**x1)/x1))**x1
<lambdifygenerated-14350>:2: RuntimeWarning: invalid value encountered in power
  return (x1*exp(sqrt((x1**2*(x1*tan(_a1_**x1) + x1 + sin(_a6_*x1/_a7_))**4)**x1)/x1))**x1
<lambdifygenerated-14351>:2: RuntimeWarning: overflow encountered in exp
  return (x1*exp(sqrt((x1**2*(x1*tan(_a1_**abs(x1)) + x1 + sin(_a6_*x1/_a7_))**4)**x1)/x1))**x1
<lambdifygenerated-14351>:2: RuntimeWarning: divide by zero encountered in power
  return (x1*exp(sqrt((x1**2*(x1*tan(_a1_**abs(x1)) + x1 + sin(_a6_*x1/_a7_))**4)**x1)/x1))**x1
<lambdifygenerated-14351>:2: RuntimeWarning: overflow encountered in power
  return (x1*exp(sqrt((x1**2*(x1*tan(_a1_**abs(x1)) + x1 + sin(_a6_*x1/_a7_))**4)**x1)/x1))**x1
<lambdifygenerated-14351>:2: RuntimeWarning: invalid value encountered in power
  return (x1*exp(sqrt((x1**2*(x1*tan(_a1_**abs(x1)) + x1 + sin(_a6_*x1/_a7_))**4)**x1)/x1))**x1
<lambdifygenerated-14352>:2: RuntimeWarning: overflow encountered in exp
  return (x1*exp(sqrt((x1**2*(x1*tan(_a1_**abs(x1)) + x1 + sin(_a6_*x1/_a7_))**4)**x1)/x1))**x1
<lambdifygenerated-14352>:2: RuntimeWarning: divide by zero encountered in power
  return (x1*exp(sqrt((x1**2*(x1*tan(_a1_**abs(x1)) + x1 + sin(_a6_*x1/_a7_))**4)**x1)/x1))**x1
<lambdifygenerated-14352>:2: RuntimeWarning: overflow encountered in power
  return (x1*exp(sqrt((x1**2*(x1*tan(_a1_**abs(x1)) + x1 + sin(_a6_*x1/_a7_))**4)**x1)/x1))**x1
<lambdifygenerated-14352>:2: RuntimeWarning: invalid value encountered in power
  return (x1*exp(sqrt((x1**2*(x1*tan(_a1_**abs(x1)) + x1 + sin(_a6_*x1/_a7_))**4)**x1)/x1))**x1
<lambdifygenerated-14353>:2: RuntimeWarning: overflow encountered in exp
  return (x1*exp(sqrt((x1**2*(x1*tan(_a1_**abs(tan(x1))) + x1 + sin(_a6_*x1/_a7_))**4)**x1)/x1))**x1
<lambdifygenerated-14353>:2: RuntimeWarning: divide by zero encountered in power
  return (x1*exp(sqrt((x1**2*(x1*tan(_a1_**abs(tan(x1))) + x1 + sin(_a6_*x1/_a7_))**4)**x1)/x1))**x1
<lambdifygenerated-14353>:2: RuntimeWarning: overflow encountered in power
  return (x1*exp(sqrt((x1**2*(x1*tan(_a1_**abs(tan(x1))) + x1 + sin(_a6_*x1/_a7_))**4)**x1)/x1))**x1
<lambdifygenerated-14353>:2: RuntimeWarning: invalid value encountered in power
  return (x1*exp(sqrt((x1**2*(x1*tan(_a1_**abs(tan(x1))) + x1 + sin(_a6_*x1/_a7_))**4)**x1)/x1))**x1
<lambdifygenerated-14354>:2: RuntimeWarning: overflow encountered in exp
  return (x1*exp(sqrt((x1**2*(x1*tan(_a1_**abs(tan(x1))) + x1 + sin(_a6_*x1/_a7_))**4)**x1)/x1))**x1
<lambdifygenerated-14354>:2: RuntimeWarning: divide by zero encountered in power
  return (x1*exp(sqrt((x1**2*(x1*tan(_a1_**abs(tan(x1))) + x1 + sin(_a6_*x1/_a7_))**4)**x1)/x1))**x1
<lambdifygenerated-14354>:2: RuntimeWarning: overflow encountered in power
  return (x1*exp(sqrt((x1**2*(x1*tan(_a1_**abs(tan(x1))) + x1 + sin(_a6_*x1/_a7_))**4)**x1)/x1))**x1
<lambdifygenerated-14354>:2: RuntimeWarning: invalid value encountered in power
  return (x1*exp(sqrt((x1**2*(x1*tan(_a1_**abs(tan(x1))) + x1 + sin(_a6_*x1/_a7_))**4)**x1)/x1))**x1
<lambdifygenerated-14355>:2: RuntimeWarning: overflow encountered in exp
  return (x1*exp(sqrt((x1**2*(x1*tan(_a1_**abs(tan(2*x1))) + x1 + sin(_a6_*x1/_a7_))**4)**x1)/x1))**x1
<lambdifygenerated-14355>:2: RuntimeWarning: divide by zero encountered in power
  return (x1*exp(sqrt((x1**2*(x1*tan(_a1_**abs(tan(2*x1))) + x1 + sin(_a6_*x1/_a7_))**4)**x1)/x1))**x1
<lambdifygenerated-14355>:2: RuntimeWarning: overflow encountered in power
  return (x1*exp(sqrt((x1**2*(x1*tan(_a1_**abs(tan(2*x1))) + x1 + sin(_a6_*x1/_a7_))**4)**x1)/x1))**x1
<lambdifygenerated-14355>:2: RuntimeWarning: invalid value encountered in power
  return (x1*exp(sqrt((x1**2*(x1*tan(_a1_**abs(tan(2*x1))) + x1 + sin(_a6_*x1/_a7_))**4)**x1)/x1))**x1
<lambdifygenerated-14356>:2: RuntimeWarning: overflow encountered in exp
  return (x1*exp(sqrt((x1**2*(x1*tan(_a1_**abs(tan(2*x1))) + x1 + sin(_a6_*x1/_a7_))**4)**x1)/x1))**x1

interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.661298  4.0  0.658319  0.665745
3746  0.998  0.661485  4.0  0.658527  0.666027
3747  0.998  0.661672  4.0  0.658736  0.666308
3748  0.999  0.661858  4.0  0.658945  0.666591

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.662232  4.0  0.659364  0.667157
3751  1.002  0.662419  4.0  0.659575  0.667442
3752  1.002  0.662605  4.0  0.659785  0.667727
3753  1.003  0.662792  4.0  0.659997  0.668012

3750

/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-14449>:2: RuntimeWarning: overflow encountered in exp
  return -_a3_*(x1*cos(x1) + (_a0_ + _a4_ + exp(_a2_ + x1/_a7_))**2) - 2*x1
<lambdifygenerated-14451>:2: RuntimeWarning: overflow encountered in exp
  return -_a3_*(x1*cos(2*x1) + (_a0_ + _a4_ + exp(_a2_ + x1/_a7_))**2) - 2*x1
<lambdifygenerated-14453>:2: RuntimeWarning: overflow encountered in exp
  return -_a3_*(x1*cos(x1**2 + x1) + (_a0_ + _a4_ + exp(_a2_ + x1/_a7_))**2) - 2*x1
<lambdifygenerated-14455>:2: RuntimeWarning: overflow encountered in exp
  return -_a3_*(x1*cos(_a7_*x1 + x1) + (_a0_ + _a4_ + exp(_a2_ + x1/_a7_))**2) - 2*x1
<lambdifygenerated-14461>:2: RuntimeWarning: overflow encountered in exp
  return -_a3_*(x1*cos(_a6_ + _a7_*x1) + (_a0_ + _a4_ + exp(_a2_ + x1/_a7_))**2) - 3*x1
<lambdifygenerated-14463>:2: RuntimeWarning: overflow encountered in exp
  return -_a3_*(x1*cos(_a6_ + _a7_*x1) + (_a0_ + _a4_ + exp(_a2_ + x1/_a7_))**2) - x1**2 - 2*x1
<lambdifygenerated-14475>:2: RuntimeWarning: overflow encountered in exp
  return -_a2_ - _a3_*(x1*cos(_a6_ + _a7_*x1) + (_a0_ + _a4_ + exp(_a2_ + x1/_a7_))**2) - _a5_*tanh(_a1_ + x1) - x1
<lambdifygenerated-14475>:2: RuntimeWarning: overflow encountered in square
  return -_a2_ - _a3_*(x1*cos(_a6_ + _a7_*x1) + (_a0_ + _a4_ + exp(_a2_ + x1/_a7_))**2) - _a5_*tanh(_a1_ + x1) - x1
<lambdifygenerated-14479>:2: RuntimeWarning: overflow encountered in exp
  return -_a2_ - _a3_*(x1*cos(_a6_ + _a7_*x1) + (_a0_ + _a4_ + exp(_a2_ + x1/_a7_))**2) - _a5_*tanh(_a1_ + x1) - x1**3
<lambdifygenerated-14481>:2: RuntimeWarning: overflow encountered in exp
  return -_a2_ - _a3_*(x1*cos(_a6_ + _a7_*x1) + (_a0_ + _a4_ + exp(_a2_ + x1/_a7_))**2) - _a5_*tanh(_a1_ + x1) - x1**4
<lambdifygenerated-14483>:2: RuntimeWarning: overflow encountered in exp
  return -_a2_ - _a3_*(x1*cos(_a6_ + _a7_*x1) + (_a0_ + _a4_ + exp(_a2_ + x1/_a7_))**2) - _a5_*tanh(_a1_ + x1) - x1**3*cos(x1)
<lambdifygenerated-14487>:2: RuntimeWarning: overflow encountered in exp
  return -_a0_*x1**2*cos(x1) - _a2_ - _a3_*(x1*cos(_a6_ + _a7_*x1) + (_a0_ + _a4_ + exp(_a2_ + x1/_a7_))**2) - _a5_*tanh(_a1_ + x1)
<lambdifygenerated-14487>:2: RuntimeWarning: overflow encountered in square
  return -_a0_*x1**2*cos(x1) - _a2_ - _a3_*(x1*cos(_a6_ + _a7_*x1) + (_a0_ + _a4_ + exp(_a2_ + x1/_a7_))**2) - _a5_*tanh(_a1_ + x1)

interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.956369  5.0  0.953490  0.955221
3746  0.998  0.956259  5.0  0.953317  0.955093
3747  0.998  0.956150  5.0  0.953143  0.954964
3748  0.999  0.956040  5.0  0.952969  0.954836

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.955822  5.0  0.952620  0.954580
3751  1.002  0.955712  5.0  0.952444  0.954452
3752  1.002  0.955603  5.0  0.952269  0.954324
3753  1.003  0.955493  5.0  0.952093  0.954196

3750

<lambdifygenerated-14517>:2: RuntimeWarning: invalid value encountered in power
  return x1*exp(x1**5*x1**(2*x1)) + 2*x1
/usr/local/lib/python3.10/dist-packages/pandas/core/arraylike.py:399: RuntimeWarning: overflow encountered in square
  result = getattr(ufunc, method)(*inputs, **kwargs)
<lambdifygenerated-14518>:2: RuntimeWarning: invalid value encountered in power
  return x1*exp(x1**5*x1**(2*x1)) + 2*x1
<lambdifygenerated-14521>:2: RuntimeWarning: invalid value encountered in power
  return x1*exp(x1**5*(x1**x1/x1)**(2*x1)) + 2*x1
<lambdifygenerated-14522>:2: RuntimeWarning: invalid value encountered in power
  return x1*exp(x1**5*(x1**x1/x1)**(2*x1)) + 2*x1
<lambdifygenerated-14523>:2: RuntimeWarning: invalid value encountered in power
  return x1*exp(x1**5*(_a7_**x1/x1)**(2*x1)) + 2*x1
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-14524>:2: RuntimeWarning: invalid value encountered in power
  return x1*exp(x1**5*(_a7_**x1/x1)**(2*x1)) + 2*x1
<lambdifygenerated-14525>:2: RuntimeWarning: invalid value encountered in power
  return x1*exp(x1**5*(_a7_**_a0_/x1)**(2*x1)) + 2*x1
<lambdifygenerated-14526>:2: RuntimeWarning: invalid value encountered in power
  return x1*exp(x1**5*(_a7_**_a0_/x1)**(2*x1)) + 2*x1
<lambdifygenerated-14527>:2: RuntimeWarning: invalid value encountered in power
  return x1*exp(x1**5*((1/2)*_a7_**_a0_/x1)**(2*x1)) + 2*x1
<lambdifygenerated-14528>:2: RuntimeWarning: invalid value encountered in power
  return x1*exp(x1**5*((1/2)*_a7_**_a0_/x1)**(2*x1)) + 2*x1
<lambdifygenerated-14529>:2: RuntimeWarning: invalid value encountered in power
  return x1*exp(x1**5*(_a7_**_a0_/(_a3_ + x1))**(2*x1)) + 2*x1
<lambdifygenerated-14530>:2: RuntimeWarning: invalid value encountered in power
  return x1*exp(x1**5*(_a7_**_a0_/(_a3_ + x1))**(2*x1)) + 2*x1
<lambdifygenerated-14531>:2: RuntimeWarning: invalid value encountered in scalar power
  return x1*exp(x1**5*((1/2)*_a7_**_a0_/_a3_)**(2*x1)) + 2*x1
<lambdifygenerated-14531>:2: RuntimeWarning: overflow encountered in power
  return x1*exp(x1**5*((1/2)*_a7_**_a0_/_a3_)**(2*x1)) + 2*x1
<lambdifygenerated-14531>:2: RuntimeWarning: overflow encountered in multiply
  return x1*exp(x1**5*((1/2)*_a7_**_a0_/_a3_)**(2*x1)) + 2*x1
<lambdifygenerated-14531>:2: RuntimeWarning: divide by zero encountered in power
  return x1*exp(x1**5*((1/2)*_a7_**_a0_/_a3_)**(2*x1)) + 2*x1
<lambdifygenerated-14532>:2: RuntimeWarning: divide by zero encountered in power
  return x1*exp(x1**5*((1/2)*_a7_**_a0_/_a3_)**(2*x1)) + 2*x1
<lambdifygenerated-14533>:2: RuntimeWarning: divide by zero encountered in power
  return x1*exp(x1**5*((1/2)*_a7_**_a0_/_a3_)**(4*x1)) + 2*x1
<lambdifygenerated-14534>:2: RuntimeWarning: divide by zero encountered in power
  return x1*exp(x1**5*((1/2)*_a7_**_a0_/_a3_)**(4*x1)) + 2*x1
<lambdifygenerated-14535>:2: RuntimeWarning: divide by zero encountered in power
  return x1*exp(x1**5*((1/2)*_a7_**_a0_/_a3_)**(2*x1**2 + 2*x1)) + 2*x1
<lambdifygenerated-14536>:2: RuntimeWarning: divide by zero encountered in power
  return x1*exp(x1**5*((1/2)*_a7_**_a0_/_a3_)**(2*x1**2 + 2*x1)) + 2*x1
<lambdifygenerated-14537>:2: RuntimeWarning: divide by zero encountered in power
  return x1*exp(x1**5*((1/2)*_a7_**_a0_/_a3_)**(2*_a1_*x1 + 2*x1)) + 2*x1
<lambdifygenerated-14538>:2: RuntimeWarning: divide by zero encountered in power
  return x1*exp(x1**5*((1/2)*_a7_**_a0_/_a3_)**(2*_a1_*x1 + 2*x1)) + 2*x1
<lambdifygenerated-14539>:2: RuntimeWarning: divide by zero encountered in power
  return x1*exp(x1**5*((1/2)*_a7_**_a0_/_a3_)**(2*_a1_*x1**2 + 2*x1)) + 2*x1
<lambdifygenerated-14540>:2: RuntimeWarning: divide by zero encountered in power
  return x1*exp(x1**5*((1/2)*_a7_**_a0_/_a3_)**(2*_a1_*x1**2 + 2*x1)) + 2*x1
<lambdifygenerated-14541>:2: RuntimeWarning: divide by zero encountered in power
  return x1*exp(x1**5*((1/2)*_a7_**_a0_/_a3_)**(2*_a1_*_a6_*x1 + 2*x1)) + 2*x1
<lambdifygenerated-14542>:2: RuntimeWarning: divide by zero encountered in power
  return x1*exp(x1**5*((1/2)*_a7_**_a0_/_a3_)**(2*_a1_*_a6_*x1 + 2*x1)) + 2*x1
<lambdifygenerated-14543>:2: RuntimeWarning: divide by zero encountered in power
  return x1*exp(x1**5*((1/2)*_a7_**_a0_/_a3_)**(-2*_a1_*_a6_*x1 + 2*x1)) + 2*x1
<lambdifygenerated-14547>:2: RuntimeWarning: divide by zero encountered in power
  return x1*exp(x1**5*((1/2)*_a7_**_a0_/_a3_)**(-2*_a1_*_a6_*x1 + 2*abs(x1))) + 2*x1
<lambdifygenerated-14551>:2: RuntimeWarning: invalid value encountered in power
  return x1*exp(x1**3*x1**(2*x1)*((1/2)*_a7_**_a0_/_a3_)**(-2*_a1_*_a6_*x1 + 2*abs(x1))) + 2*x1
<lambdifygenerated-14551>:2: RuntimeWarning: divide by zero encountered in power
  return x1*exp(x1**3*x1**(2*x1)*((1/2)*_a7_**_a0_/_a3_)**(-2*_a1_*_a6_*x1 + 2*abs(x1))) + 2*x1
<lambdifygenerated-14552>:2: RuntimeWarning: invalid value encountered in power
  return x1*exp(x1**3*x1**(2*x1)*((1/2)*_a7_**_a0_/_a3_)**(-2*_a1_*_a6_*x1 + 2*abs(x1))) + 2*x1
<lambdifygenerated-14553>:2: RuntimeWarning: divide by zero encountered in power
  return x1*exp(x1**3*((1/2)*_a7_**_a0_/_a3_)**(-2*_a1_*_a6_*x1 + 2*abs(x1))) + 2*x1
<lambdifygenerated-14555>:2: RuntimeWarning: invalid value encountered in power
  return x1*exp(x1**3*x1**(2*x1)*((1/2)*_a7_**_a0_/_a3_)**(-2*_a1_*_a6_*x1 + 2*abs(x1))) + 2*x1
<lambdifygenerated-14555>:2: RuntimeWarning: divide by zero encountered in power
  return x1*exp(x1**3*x1**(2*x1)*((1/2)*_a7_**_a0_/_a3_)**(-2*_a1_*_a6_*x1 + 2*abs(x1))) + 2*x1
<lambdifygenerated-14556>:2: RuntimeWarning: invalid value encountered in power
  return x1*exp(x1**3*x1**(2*x1)*((1/2)*_a7_**_a0_/_a3_)**(-2*_a1_*_a6_*x1 + 2*abs(x1))) + 2*x1
<lambdifygenerated-14557>:2: RuntimeWarning: invalid value encountered in power
  return x1*exp(x1**3*(_a6_**2/x1)**(2*x1)*((1/2)*_a7_**_a0_/_a3_)**(-2*_a1_*_a6_*x1 + 2*abs(x1))) + 2*x1
<lambdifygenerated-14557>:2: RuntimeWarning: divide by zero encountered in power
  return x1*exp(x1**3*(_a6_**2/x1)**(2*x1)*((1/2)*_a7_**_a0_/_a3_)**(-2*_a1_*_a6_*x1 + 2*abs(x1))) + 2*x1
<lambdifygenerated-14558>:2: RuntimeWarning: invalid value encountered in power
  return x1*exp(x1**3*(_a6_**2/x1)**(2*x1)*((1/2)*_a7_**_a0_/_a3_)**(-2*_a1_*_a6_*x1 + 2*abs(x1))) + 2*x1
<lambdifygenerated-14559>:2: RuntimeWarning: invalid value encountered in power
  return x1*exp(x1**3*((1/2)*_a7_**_a0_/_a3_)**(-2*_a1_*_a6_*x1 + 2*abs(x1))*((1/2)*_a6_**2/x1)**(2*x1)) + 2*x1
<lambdifygenerated-14559>:2: RuntimeWarning: divide by zero encountered in power
  return x1*exp(x1**3*((1/2)*_a7_**_a0_/_a3_)**(-2*_a1_*_a6_*x1 + 2*abs(x1))*((1/2)*_a6_**2/x1)**(2*x1)) + 2*x1
<lambdifygenerated-14560>:2: RuntimeWarning: invalid value encountered in power
  return x1*exp(x1**3*((1/2)*_a7_**_a0_/_a3_)**(-2*_a1_*_a6_*x1 + 2*abs(x1))*((1/2)*_a6_**2/x1)**(2*x1)) + 2*x1
<lambdifygenerated-14561>:2: RuntimeWarning: invalid value encountered in power
  return x1*exp(x1**3*((1/3)*_a6_**2/x1)**(2*x1)*((1/2)*_a7_**_a0_/_a3_)**(-2*_a1_*_a6_*x1 + 2*abs(x1))) + 2*x1
<lambdifygenerated-14561>:2: RuntimeWarning: divide by zero encountered in power
  return x1*exp(x1**3*((1/3)*_a6_**2/x1)**(2*x1)*((1/2)*_a7_**_a0_/_a3_)**(-2*_a1_*_a6_*x1 + 2*abs(x1))) + 2*x1
<lambdifygenerated-14562>:2: RuntimeWarning: invalid value encountered in power
  return x1*exp(x1**3*((1/3)*_a6_**2/x1)**(2*x1)*((1/2)*_a7_**_a0_/_a3_)**(-2*_a1_*_a6_*x1 + 2*abs(x1))) + 2*x1
<lambdifygenerated-14563>:2: RuntimeWarning: invalid value encountered in power
  return x1*exp(x1**3*(_a6_**2/(_a4_ + 2*x1))**(2*x1)*((1/2)*_a7_**_a0_/_a3_)**(-2*_a1_*_a6_*x1 + 2*abs(x1))) + 2*x1
<lambdifygenerated-14563>:2: RuntimeWarning: divide by zero encountered in power
  return x1*exp(x1**3*(_a6_**2/(_a4_ + 2*x1))**(2*x1)*((1/2)*_a7_**_a0_/_a3_)**(-2*_a1_*_a6_*x1 + 2*abs(x1))) + 2*x1
<lambdifygenerated-14564>:2: RuntimeWarning: invalid value encountered in power
  return x1*exp(x1**3*(_a6_**2/(_a4_ + 2*x1))**(2*x1)*((1/2)*_a7_**_a0_/_a3_)**(-2*_a1_*_a6_*x1 + 2*abs(x1))) + 2*x1
<lambdifygenerated-14565>:2: RuntimeWarning: invalid value encountered in power
  return x1*exp(x1**3*(_a6_**2/(_a0_ + _a4_ + x1))**(2*x1)*((1/2)*_a7_**_a0_/_a3_)**(-2*_a1_*_a6_*x1 + 2*abs(x1))) + 2*x1
<lambdifygenerated-14565>:2: RuntimeWarning: divide by zero encountered in power
  return x1*exp(x1**3*(_a6_**2/(_a0_ + _a4_ + x1))**(2*x1)*((1/2)*_a7_**_a0_/_a3_)**(-2*_a1_*_a6_*x1 + 2*abs(x1))) + 2*x1
<lambdifygenerated-14566>:2: RuntimeWarning: invalid value encountered in power
  return x1*exp(x1**3*(_a6_**2/(_a0_ + _a4_ + x1))**(2*x1)*((1/2)*_a7_**_a0_/_a3_)**(-2*_a1_*_a6_*x1 + 2*abs(x1))) + 2*x1
<lambdifygenerated-14567>:2: RuntimeWarning: invalid value encountered in power
  return x1*exp(x1**3*(_a6_**2/(_a0_ + _a4_ + x1))**(2*x1)*((1/2)*_a7_**_a0_/_a3_)**(-2*_a1_*_a6_*x1 + 2*abs(x1))) + 2*x1
<lambdifygenerated-14568>:2: RuntimeWarning: invalid value encountered in power
  return x1*exp(x1**3*(_a6_**2/(_a0_ + _a4_ + x1))**(2*x1)*((1/2)*_a7_**_a0_/_a3_)**(-2*_a1_*_a6_*x1 + 2*abs(x1))) + 2*x1
<lambdifygenerated-14569>:2: RuntimeWarning: divide by zero encountered in power
  return x1*exp(x1**3*(_a6_**2/(_a0_ + _a4_ + x1))**(2*_a6_)*((1/2)*_a7_**_a0_/_a3_)**(-2*_a1_*_a6_*x1 + 2*abs(x1))) + 2*x1
<lambdifygenerated-14569>:2: RuntimeWarning: invalid value encountered in power
  return x1*exp(x1**3*(_a6_**2/(_a0_ + _a4_ + x1))**(2*_a6_)*((1/2)*_a7_**_a0_/_a3_)**(-2*_a1_*_a6_*x1 + 2*abs(x1))) + 2*x1
<lambdifygenerated-14573>:2: RuntimeWarning: divide by zero encountered in power
  return x1*exp(_a1_*x1**2*(_a6_**2/(_a0_ + _a4_ + x1))**(2*_a6_)*((1/2)*_a7_**_a0_/_a3_)**(-2*_a1_*_a6_*x1 + 2*abs(x1))) + 2*x1
<lambdifygenerated-14573>:2: RuntimeWarning: invalid value encountered in power
  return x1*exp(_a1_*x1**2*(_a6_**2/(_a0_ + _a4_ + x1))**(2*_a6_)*((1/2)*_a7_**_a0_/_a3_)**(-2*_a1_*_a6_*x1 + 2*abs(x1))) + 2*x1
<lambdifygenerated-14575>:2: RuntimeWarning: divide by zero encountered in power
  return _a7_*exp(_a1_*x1**2*(_a6_**2/(_a0_ + _a4_ + x1))**(2*_a6_)*((1/2)*_a7_**_a0_/_a3_)**(-2*_a1_*_a6_*x1 + 2*abs(x1))) + 2*x1
<lambdifygenerated-14575>:2: RuntimeWarning: invalid value encountered in power
  return _a7_*exp(_a1_*x1**2*(_a6_**2/(_a0_ + _a4_ + x1))**(2*_a6_)*((1/2)*_a7_**_a0_/_a3_)**(-2*_a1_*_a6_*x1 + 2*abs(x1))) + 2*x1
<lambdifygenerated-14577>:2: RuntimeWarning: divide by zero encountered in power
  return _a5_ + _a7_*exp(_a1_*x1**2*(_a6_**2/(_a0_ + _a4_ + x1))**(2*_a6_)*((1/2)*_a7_**_a0_/_a3_)**(-2*_a1_*_a6_*x1 + 2*abs(x1))) + x1
<lambdifygenerated-14577>:2: RuntimeWarning: invalid value encountered in power
  return _a5_ + _a7_*exp(_a1_*x1**2*(_a6_**2/(_a0_ + _a4_ + x1))**(2*_a6_)*((1/2)*_a7_**_a0_/_a3_)**(-2*_a1_*_a6_*x1 + 2*abs(x1))) + x1
<lambdifygenerated-14579>:2: RuntimeWarning: divide by zero encountered in power
  return _a5_ + _a7_*exp(_a1_*x1**2*(_a6_**2/(_a0_ + _a4_ + x1))**(2*_a6_)*((1/2)*_a7_**_a0_/_a3_)**(-2*_a1_*_a6_*x1 + 2*abs(x1))) + x1**2
<lambdifygenerated-14579>:2: RuntimeWarning: invalid value encountered in power
  return _a5_ + _a7_*exp(_a1_*x1**2*(_a6_**2/(_a0_ + _a4_ + x1))**(2*_a6_)*((1/2)*_a7_**_a0_/_a3_)**(-2*_a1_*_a6_*x1 + 2*abs(x1))) + x1**2
<lambdifygenerated-14581>:2: RuntimeWarning: divide by zero encountered in power
  return _a2_*x1 + _a5_ + _a7_*exp(_a1_*x1**2*(_a6_**2/(_a0_ + _a4_ + x1))**(2*_a6_)*((1/2)*_a7_**_a0_/_a3_)**(-2*_a1_*_a6_*x1 + 2*abs(x1)))
<lambdifygenerated-14581>:2: RuntimeWarning: invalid value encountered in power
  return _a2_*x1 + _a5_ + _a7_*exp(_a1_*x1**2*(_a6_**2/(_a0_ + _a4_ + x1))**(2*_a6_)*((1/2)*_a7_**_a0_/_a3_)**(-2*_a1_*_a6_*x1 + 2*abs(x1)))
<lambdifygenerated-14583>:2: RuntimeWarning: divide by zero encountered in power
  return _a2_*x1**2 + _a5_ + _a7_*exp(_a1_*x1**2*(_a6_**2/(_a0_ + _a4_ + x1))**(2*_a6_)*((1/2)*_a7_**_a0_/_a3_)**(-2*_a1_*_a6_*x1 + 2*abs(x1)))
<lambdifygenerated-14583>:2: RuntimeWarning: invalid value encountered in power
  return _a2_*x1**2 + _a5_ + _a7_*exp(_a1_*x1**2*(_a6_**2/(_a0_ + _a4_ + x1))**(2*_a6_)*((1/2)*_a7_**_a0_/_a3_)**(-2*_a1_*_a6_*x1 + 2*abs(x1)))
<lambdifygenerated-14585>:2: RuntimeWarning: divide by zero encountered in power
  return _a2_*x1**3 + _a5_ + _a7_*exp(_a1_*x1**2*(_a6_**2/(_a0_ + _a4_ + x1))**(2*_a6_)*((1/2)*_a7_**_a0_/_a3_)**(-2*_a1_*_a6_*x1 + 2*abs(x1)))
<lambdifygenerated-14585>:2: RuntimeWarning: invalid value encountered in power
  return _a2_*x1**3 + _a5_ + _a7_*exp(_a1_*x1**2*(_a6_**2/(_a0_ + _a4_ + x1))**(2*_a6_)*((1/2)*_a7_**_a0_/_a3_)**(-2*_a1_*_a6_*x1 + 2*abs(x1)))
<lambdifygenerated-14587>:2: RuntimeWarning: divide by zero encountered in power
  return _a2_*_a3_*x1**2 + _a5_ + _a7_*exp(_a1_*x1**2*(_a6_**2/(_a0_ + _a4_ + x1))**(2*_a6_)*((1/2)*_a7_**_a0_/_a3_)**(-2*_a1_*_a6_*x1 + 2*abs(x1)))
<lambdifygenerated-14587>:2: RuntimeWarning: invalid value encountered in power
  return _a2_*_a3_*x1**2 + _a5_ + _a7_*exp(_a1_*x1**2*(_a6_**2/(_a0_ + _a4_ + x1))**(2*_a6_)*((1/2)*_a7_**_a0_/_a3_)**(-2*_a1_*_a6_*x1 + 2*abs(x1)))
<lambdifygenerated-14589>:2: RuntimeWarning: invalid value encountered in power
  return _a2_*_a3_*x1*x1**x1 + _a5_ + _a7_*exp(_a1_*x1**2*(_a6_**2/(_a0_ + _a4_ + x1))**(2*_a6_)*((1/2)*_a7_**_a0_/_a3_)**(-2*_a1_*_a6_*x1 + 2*abs(x1)))
<lambdifygenerated-14589>:2: RuntimeWarning: divide by zero encountered in power
  return _a2_*_a3_*x1*x1**x1 + _a5_ + _a7_*exp(_a1_*x1**2*(_a6_**2/(_a0_ + _a4_ + x1))**(2*_a6_)*((1/2)*_a7_**_a0_/_a3_)**(-2*_a1_*_a6_*x1 + 2*abs(x1)))
<lambdifygenerated-14590>:2: RuntimeWarning: invalid value encountered in power
  return _a2_*_a3_*x1*x1**x1 + _a5_ + _a7_*exp(_a1_*x1**2*(_a6_**2/(_a0_ + _a4_ + x1))**(2*_a6_)*((1/2)*_a7_**_a0_/_a3_)**(-2*_a1_*_a6_*x1 + 2*abs(x1)))
<lambdifygenerated-14591>:2: RuntimeWarning: divide by zero encountered in power
  return _a2_*_a3_*_a3_**x1*x1 + _a5_ + _a7_*exp(_a1_*x1**2*(_a6_**2/(_a0_ + _a4_ + x1))**(2*_a6_)*((1/2)*_a7_**_a0_/_a3_)**(-2*_a1_*_a6_*x1 + 2*abs(x1)))
<lambdifygenerated-14591>:2: RuntimeWarning: invalid value encountered in power
  return _a2_*_a3_*_a3_**x1*x1 + _a5_ + _a7_*exp(_a1_*x1**2*(_a6_**2/(_a0_ + _a4_ + x1))**(2*_a6_)*((1/2)*_a7_**_a0_/_a3_)**(-2*_a1_*_a6_*x1 + 2*abs(x1)))
<lambdifygenerated-14595>:2: RuntimeWarning: divide by zero encountered in power
  return _a2_*_a3_**2*_a3_**x1 + _a5_ + _a7_*exp(_a1_*x1**2*(_a6_**2/(_a0_ + _a4_ + x1))**(2*_a6_)*((1/2)*_a7_**_a0_/_a3_)**(-2*_a1_*_a6_*x1 + 2*abs(x1)))
<lambdifygenerated-14595>:2: RuntimeWarning: invalid value encountered in power
  return _a2_*_a3_**2*_a3_**x1 + _a5_ + _a7_*exp(_a1_*x1**2*(_a6_**2/(_a0_ + _a4_ + x1))**(2*_a6_)*((1/2)*_a7_**_a0_/_a3_)**(-2*_a1_*_a6_*x1 + 2*abs(x1)))
<lambdifygenerated-14599>:2: RuntimeWarning: divide by zero encountered in power
  return _a2_*_a3_**2*_a3_**x1 + _a5_ + _a7_*exp(_a1_*x1**2*(_a6_**2/(_a0_ + _a4_ + x1))**(2*_a6_)*((1/2)*_a7_**_a0_/_a3_)**(-2*_a1_*_a6_*x1 + 2*abs(x1)))
<lambdifygenerated-14599>:2: RuntimeWarning: invalid value encountered in power
  return _a2_*_a3_**2*_a3_**x1 + _a5_ + _a7_*exp(_a1_*x1**2*(_a6_**2/(_a0_ + _a4_ + x1))**(2*_a6_)*((1/2)*_a7_**_a0_/_a3_)**(-2*_a1_*_a6_*x1 + 2*abs(x1)))

interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.428260  6.0  0.429137  0.430017
3746  0.998  0.428367  6.0  0.429271  0.430230
3747  0.998  0.428474  6.0  0.429406  0.430444
3748  0.999  0.428581  6.0  0.429542  0.430662

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.428794  6.0  0.429815  0.431103
3751  1.002  0.428901  6.0  0.429952  0.431327
3752  1.002  0.429008  6.0  0.430090  0.431554
3753  1.003  0.429115  6.0  0.430229  0.431784

3750

<lambdifygenerated-14637>:2: RuntimeWarning: invalid value encountered in power
  return sin(x1*(x1*(_a3_*tanh(_a2_**6*tanh(x1)**3) + x1**x1) + x1))
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-14638>:2: RuntimeWarning: invalid value encountered in power
  return sin(x1*(x1*(_a3_*tanh(_a2_**6*tanh(x1)**3) + x1**x1) + x1))

interpolation

<lambdifygenerated-14659>:2: RuntimeWarning: overflow encountered in power
  return sin(x1*(x1*(_a3_*tanh(_a2_**6*tanh(x1)**3) + (_a6_**2/x1**2)**(_a1_*x1 + _a3_ + _a7_)) + x1))
<lambdifygenerated-14659>:2: RuntimeWarning: invalid value encountered in sin
  return sin(x1*(x1*(_a3_*tanh(_a2_**6*tanh(x1)**3) + (_a6_**2/x1**2)**(_a1_*x1 + _a3_ + _a7_)) + x1))
<lambdifygenerated-14660>:2: RuntimeWarning: overflow encountered in power
  return sin(x1*(x1*(_a3_*tanh(_a2_**6*tanh(x1)**3) + (_a6_**2/x1**2)**(_a1_*x1 + _a3_ + _a7_)) + x1))
<lambdifygenerated-14660>:2: RuntimeWarning: invalid value encountered in sin
  return sin(x1*(x1*(_a3_*tanh(_a2_**6*tanh(x1)**3) + (_a6_**2/x1**2)**(_a1_*x1 + _a3_ + _a7_)) + x1))
<lambdifygenerated-14661>:2: RuntimeWarning: overflow encountered in power
  return sin(x1*(x1*(_a3_*tanh(_a2_**6*tanh(x1)**3) + x1*(_a6_**2/x1**2)**(_a1_*x1 + _a3_ + _a7_)/cos(x1)) + x1))
<lambdifygenerated-14661>:2: RuntimeWarning: invalid value encountered in sin
  return sin(x1*(x1*(_a3_*tanh(_a2_**6*tanh(x1)**3) + x1*(_a6_**2/x1**2)**(_a1_*x1 + _a3_ + _a7_)/cos(x1)) + x1))
<lambdifygenerated-14662>:2: RuntimeWarning: overflow encountered in power
  return sin(x1*(x1*(_a3_*tanh(_a2_**6*tanh(x1)**3) + x1*(_a6_**2/x1**2)**(_a1_*x1 + _a3_ + _a7_)/cos(x1)) + x1))
<lambdifygenerated-14662>:2: RuntimeWarning: invalid value encountered in sin
  return sin(x1*(x1*(_a3_*tanh(_a2_**6*tanh(x1)**3) + x1*(_a6_**2/x1**2)**(_a1_*x1 + _a3_ + _a7_)/cos(x1)) + x1))
<lambdifygenerated-14663>:2: RuntimeWarning: overflow encountered in power
  return sin(x1*(x1*(_a3_*tanh(_a2_**6*tanh(x1)**3) + x1*(_a6_**2/x1**2)**(_a1_*x1 + _a3_ + _a7_)/cos(2*x1)) + x1))
<lambdifygenerated-14663>:2: RuntimeWarning: invalid value encountered in sin
  return sin(x1*(x1*(_a3_*tanh(_a2_**6*tanh(x1)**3) + x1*(_a6_**2/x1**2)**(_a1_*x1 + _a3_ + _a7_)/cos(2*x1)) + x1))
<lambdifygenerated-14664>:2: RuntimeWarning: overflow encountered in power
  return sin(x1*(x1*(_a3_*tanh(_a2_**6*tanh(x1)**3) + x1*(_a6_**2/x1**2)**(_a1_*x1 + _a3_ + _a7_)/cos(2*x1)) + x1))
<lambdifygenerated-14664>:2: RuntimeWarning: invalid value encountered in sin
  return sin(x1*(x1*(_a3_*tanh(_a2_**6*tanh(x1)**3) + x1*(_a6_**2/x1**2)**(_a1_*x1 + _a3_ + _a7_)/cos(2*x1)) + x1))
<lambdifygenerated-14665>:2: RuntimeWarning: overflow encountered in power
  return sin(x1*(x1*(_a3_*tanh(_a2_**6*tanh(x1)**3) + x1*(_a6_**2/x1**2)**(_a1_*x1 + _a3_ + _a7_)/cos(x1 + cos(x1))) + x1))
<lambdifygenerated-14665>:2: RuntimeWarning: invalid value encountered in sin
  return sin(x1*(x1*(_a3_*tanh(_a2_**6*tanh(x1)**3) + x1*(_a6_**2/x1**2)**(_a1_*x1 + _a3_ + _a7_)/cos(x1 + cos(x1))) + x1))
<lambdifygenerated-14666>:2: RuntimeWarning: overflow encountered in power
  return sin(x1*(x1*(_a3_*tanh(_a2_**6*tanh(x1)**3) + x1*(_a6_**2/x1**2)**(_a1_*x1 + _a3_ + _a7_)/cos(x1 + cos(x1))) + x1))
<lambdifygenerated-14666>:2: RuntimeWarning: invalid value encountered in sin
  return sin(x1*(x1*(_a3_*tanh(_a2_**6*tanh(x1)**3) + x1*(_a6_**2/x1**2)**(_a1_*x1 + _a3_ + _a7_)/cos(x1 + cos(x1))) + x1))
<lambdifygenerated-14667>:2: RuntimeWarning: overflow encountered in power
  return sin(x1*(x1*(_a3_*tanh(_a2_**6*tanh(x1)**3) + x1*(_a6_**2/x1**2)**(_a1_*x1 + _a3_ + _a7_)/cos(x1 + cos(2*x1))) + x1))
<lambdifygenerated-14667>:2: RuntimeWarning: invalid value encountered in sin
  return sin(x1*(x1*(_a3_*tanh(_a2_**6*tanh(x1)**3) + x1*(_a6_**2/x1**2)**(_a1_*x1 + _a3_ + _a7_)/cos(x1 + cos(2*x1))) + x1))
<lambdifygenerated-14668>:2: RuntimeWarning: overflow encountered in power
  return sin(x1*(x1*(_a3_*tanh(_a2_**6*tanh(x1)**3) + x1*(_a6_**2/x1**2)**(_a1_*x1 + _a3_ + _a7_)/cos(x1 + cos(2*x1))) + x1))
<lambdifygenerated-14668>:2: RuntimeWarning: invalid value encountered in sin
  return sin(x1*(x1*(_a3_*tanh(_a2_**6*tanh(x1)**3) + x1*(_a6_**2/x1**2)**(_a1_*x1 + _a3_ + _a7_)/cos(x1 + cos(2*x1))) + x1))
<lambdifygenerated-14669>:2: RuntimeWarning: overflow encountered in power
  return sin(x1*(x1*(_a3_*tanh(_a2_**6*tanh(x1)**3) + x1*(_a6_**2/x1**2)**(_a1_*x1 + _a3_ + _a7_)/cos(x1 + cos(2*x1))) + x1))
<lambdifygenerated-14669>:2: RuntimeWarning: invalid value encountered in sin
  return sin(x1*(x1*(_a3_*tanh(_a2_**6*tanh(x1)**3) + x1*(_a6_**2/x1**2)**(_a1_*x1 + _a3_ + _a7_)/cos(x1 + cos(2*x1))) + x1))
<lambdifygenerated-14670>:2: RuntimeWarning: overflow encountered in power
  return sin(x1*(x1*(_a3_*tanh(_a2_**6*tanh(x1)**3) + x1*(_a6_**2/x1**2)**(_a1_*x1 + _a3_ + _a7_)/cos(x1 + cos(2*x1))) + x1))
<lambdifygenerated-14670>:2: RuntimeWarning: invalid value encountered in sin
  return sin(x1*(x1*(_a3_*tanh(_a2_**6*tanh(x1)**3) + x1*(_a6_**2/x1**2)**(_a1_*x1 + _a3_ + _a7_)/cos(x1 + cos(2*x1))) + x1))
<lambdifygenerated-14671>:2: RuntimeWarning: overflow encountered in power
  return sin(x1*(x1*(_a3_*tanh(_a2_**6*tanh(x1)**3) + x1*(_a6_**2/x1**2)**(_a1_*x1 + _a3_ + _a7_)/cos(x1 + cos(_a4_ + x1))) + x1))
<lambdifygenerated-14671>:2: RuntimeWarning: invalid value encountered in sin
  return sin(x1*(x1*(_a3_*tanh(_a2_**6*tanh(x1)**3) + x1*(_a6_**2/x1**2)**(_a1_*x1 + _a3_ + _a7_)/cos(x1 + cos(_a4_ + x1))) + x1))
<lambdifygenerated-14672>:2: RuntimeWarning: overflow encountered in power
  return sin(x1*(x1*(_a3_*tanh(_a2_**6*tanh(x1)**3) + x1*(_a6_**2/x1**2)**(_a1_*x1 + _a3_ + _a7_)/cos(x1 + cos(_a4_ + x1))) + x1))
<lambdifygenerated-14672>:2: RuntimeWarning: invalid value encountered in sin
  return sin(x1*(x1*(_a3_*tanh(_a2_**6*tanh(x1)**3) + x1*(_a6_**2/x1**2)**(_a1_*x1 + _a3_ + _a7_)/cos(x1 + cos(_a4_ + x1))) + x1))
<lambdifygenerated-14673>:2: RuntimeWarning: overflow encountered in power
  return sin(x1*(x1*(_a3_*tanh(_a2_**6*tanh(x1)**3) + x1*(_a6_**2/x1**2)**(_a1_*x1 + _a3_ + _a7_)/cos(_a5_ + cos(_a4_ + x1))) + x1))
<lambdifygenerated-14673>:2: RuntimeWarning: invalid value encountered in sin
  return sin(x1*(x1*(_a3_*tanh(_a2_**6*tanh(x1)**3) + x1*(_a6_**2/x1**2)**(_a1_*x1 + _a3_ + _a7_)/cos(_a5_ + cos(_a4_ + x1))) + x1))
<lambdifygenerated-14674>:2: RuntimeWarning: overflow encountered in power
  return sin(x1*(x1*(_a3_*tanh(_a2_**6*tanh(x1)**3) + x1*(_a6_**2/x1**2)**(_a1_*x1 + _a3_ + _a7_)/cos(_a5_ + cos(_a4_ + x1))) + x1))
<lambdifygenerated-14674>:2: RuntimeWarning: invalid value encountered in sin
  return sin(x1*(x1*(_a3_*tanh(_a2_**6*tanh(x1)**3) + x1*(_a6_**2/x1**2)**(_a1_*x1 + _a3_ + _a7_)/cos(_a5_ + cos(_a4_ + x1))) + x1))
<lambdifygenerated-14675>:2: RuntimeWarning: overflow encountered in power
  return sin(x1*(x1*(_a3_*tanh(_a2_**6*tanh(x1)**3) + x1*(_a6_**2/x1**2)**(_a1_*x1 + _a3_ + _a7_)/cos(_a5_ + cos(_a4_ + x1))) + x1))
<lambdifygenerated-14675>:2: RuntimeWarning: invalid value encountered in sin
  return sin(x1*(x1*(_a3_*tanh(_a2_**6*tanh(x1)**3) + x1*(_a6_**2/x1**2)**(_a1_*x1 + _a3_ + _a7_)/cos(_a5_ + cos(_a4_ + x1))) + x1))
<lambdifygenerated-14676>:2: RuntimeWarning: overflow encountered in power
  return sin(x1*(x1*(_a3_*tanh(_a2_**6*tanh(x1)**3) + x1*(_a6_**2/x1**2)**(_a1_*x1 + _a3_ + _a7_)/cos(_a5_ + cos(_a4_ + x1))) + x1))
<lambdifygenerated-14676>:2: RuntimeWarning: invalid value encountered in sin
  return sin(x1*(x1*(_a3_*tanh(_a2_**6*tanh(x1)**3) + x1*(_a6_**2/x1**2)**(_a1_*x1 + _a3_ + _a7_)/cos(_a5_ + cos(_a4_ + x1))) + x1))
<lambdifygenerated-14677>:2: RuntimeWarning: overflow encountered in power
  return sin(x1*(x1**2*(_a3_*tanh(_a2_**6*tanh(x1)**3) + x1*(_a6_**2/x1**2)**(_a1_*x1 + _a3_ + _a7_)/cos(_a5_ + cos(_a4_ + x1))) + x1))
<lambdifygenerated-14677>:2: RuntimeWarning: invalid value encountered in sin
  return sin(x1*(x1**2*(_a3_*tanh(_a2_**6*tanh(x1)**3) + x1*(_a6_**2/x1**2)**(_a1_*x1 + _a3_ + _a7_)/cos(_a5_ + cos(_a4_ + x1))) + x1))
<lambdifygenerated-14678>:2: RuntimeWarning: overflow encountered in power
  return sin(x1*(x1**2*(_a3_*tanh(_a2_**6*tanh(x1)**3) + x1*(_a6_**2/x1**2)**(_a1_*x1 + _a3_ + _a7_)/cos(_a5_ + cos(_a4_ + x1))) + x1))
<lambdifygenerated-14678>:2: RuntimeWarning: invalid value encountered in sin
  return sin(x1*(x1**2*(_a3_*tanh(_a2_**6*tanh(x1)**3) + x1*(_a6_**2/x1**2)**(_a1_*x1 + _a3_ + _a7_)/cos(_a5_ + cos(_a4_ + x1))) + x1))
<lambdifygenerated-14679>:2: RuntimeWarning: overflow encountered in power
  return sin(x1*(_a3_*x1*(_a3_*tanh(_a2_**6*tanh(x1)**3) + x1*(_a6_**2/x1**2)**(_a1_*x1 + _a3_ + _a7_)/cos(_a5_ + cos(_a4_ + x1))) + x1))
<lambdifygenerated-14679>:2: RuntimeWarning: invalid value encountered in sin
  return sin(x1*(_a3_*x1*(_a3_*tanh(_a2_**6*tanh(x1)**3) + x1*(_a6_**2/x1**2)**(_a1_*x1 + _a3_ + _a7_)/cos(_a5_ + cos(_a4_ + x1))) + x1))
<lambdifygenerated-14680>:2: RuntimeWarning: overflow encountered in power
  return sin(x1*(_a3_*x1*(_a3_*tanh(_a2_**6*tanh(x1)**3) + x1*(_a6_**2/x1**2)**(_a1_*x1 + _a3_ + _a7_)/cos(_a5_ + cos(_a4_ + x1))) + x1))
<lambdifygenerated-14680>:2: RuntimeWarning: invalid value encountered in sin
  return sin(x1*(_a3_*x1*(_a3_*tanh(_a2_**6*tanh(x1)**3) + x1*(_a6_**2/x1**2)**(_a1_*x1 + _a3_ + _a7_)/cos(_a5_ + cos(_a4_ + x1))) + x1))
<lambdifygenerated-14681>:2: RuntimeWarning: overflow encountered in power
  return sin(x1*(2*_a3_*x1*(_a3_*tanh(_a2_**6*tanh(x1)**3) + x1*(_a6_**2/x1**2)**(_a1_*x1 + _a3_ + _a7_)/cos(_a5_ + cos(_a4_ + x1))) + x1))
<lambdifygenerated-14681>:2: RuntimeWarning: invalid value encountered in sin
  return sin(x1*(2*_a3_*x1*(_a3_*tanh(_a2_**6*tanh(x1)**3) + x1*(_a6_**2/x1**2)**(_a1_*x1 + _a3_ + _a7_)/cos(_a5_ + cos(_a4_ + x1))) + x1))
<lambdifygenerated-14682>:2: RuntimeWarning: overflow encountered in power
  return sin(x1*(2*_a3_*x1*(_a3_*tanh(_a2_**6*tanh(x1)**3) + x1*(_a6_**2/x1**2)**(_a1_*x1 + _a3_ + _a7_)/cos(_a5_ + cos(_a4_ + x1))) + x1))
<lambdifygenerated-14682>:2: RuntimeWarning: invalid value encountered in sin
  return sin(x1*(2*_a3_*x1*(_a3_*tanh(_a2_**6*tanh(x1)**3) + x1*(_a6_**2/x1**2)**(_a1_*x1 + _a3_ + _a7_)/cos(_a5_ + cos(_a4_ + x1))) + x1))
<lambdifygenerated-14683>:2: RuntimeWarning: overflow encountered in power
  return sin(x1*(2*_a3_*x1*(_a3_*tanh(_a2_**6*tanh(x1)**3) + x1*(_a6_**2/x1**2)**(_a1_*x1 + _a3_ + _a7_)/cos(_a5_ + cos(_a4_ + x1))) + x1))
<lambdifygenerated-14683>:2: RuntimeWarning: invalid value encountered in sin
  return sin(x1*(2*_a3_*x1*(_a3_*tanh(_a2_**6*tanh(x1)**3) + x1*(_a6_**2/x1**2)**(_a1_*x1 + _a3_ + _a7_)/cos(_a5_ + cos(_a4_ + x1))) + x1))
<lambdifygenerated-14684>:2: RuntimeWarning: overflow encountered in power
  return sin(x1*(2*_a3_*x1*(_a3_*tanh(_a2_**6*tanh(x1)**3) + x1*(_a6_**2/x1**2)**(_a1_*x1 + _a3_ + _a7_)/cos(_a5_ + cos(_a4_ + x1))) + x1))
<lambdifygenerated-14684>:2: RuntimeWarning: invalid value encountered in sin
  return sin(x1*(2*_a3_*x1*(_a3_*tanh(_a2_**6*tanh(x1)**3) + x1*(_a6_**2/x1**2)**(_a1_*x1 + _a3_ + _a7_)/cos(_a5_ + cos(_a4_ + x1))) + x1))
<lambdifygenerated-14685>:2: RuntimeWarning: overflow encountered in power
  return sin(x1*(_a3_*(_a2_ + x1)*(_a3_*tanh(_a2_**6*tanh(x1)**3) + x1*(_a6_**2/x1**2)**(_a1_*x1 + _a3_ + _a7_)/cos(_a5_ + cos(_a4_ + x1))) + x1))
<lambdifygenerated-14685>:2: RuntimeWarning: invalid value encountered in sin
  return sin(x1*(_a3_*(_a2_ + x1)*(_a3_*tanh(_a2_**6*tanh(x1)**3) + x1*(_a6_**2/x1**2)**(_a1_*x1 + _a3_ + _a7_)/cos(_a5_ + cos(_a4_ + x1))) + x1))
<lambdifygenerated-14686>:2: RuntimeWarning: overflow encountered in power
  return sin(x1*(_a3_*(_a2_ + x1)*(_a3_*tanh(_a2_**6*tanh(x1)**3) + x1*(_a6_**2/x1**2)**(_a1_*x1 + _a3_ + _a7_)/cos(_a5_ + cos(_a4_ + x1))) + x1))
<lambdifygenerated-14686>:2: RuntimeWarning: invalid value encountered in sin
  return sin(x1*(_a3_*(_a2_ + x1)*(_a3_*tanh(_a2_**6*tanh(x1)**3) + x1*(_a6_**2/x1**2)**(_a1_*x1 + _a3_ + _a7_)/cos(_a5_ + cos(_a4_ + x1))) + x1))
<lambdifygenerated-14687>:2: RuntimeWarning: overflow encountered in power
  return sin(x1*(_a3_*(_a2_ + x1)*(_a3_*tanh(_a2_**6*tanh(x1)**3) + x1*(_a6_**2/x1**2)**(_a1_*x1 + _a3_ + _a7_)/cos(_a5_ + cos(_a4_ + x1))) + _a5_))
<lambdifygenerated-14687>:2: RuntimeWarning: invalid value encountered in sin
  return sin(x1*(_a3_*(_a2_ + x1)*(_a3_*tanh(_a2_**6*tanh(x1)**3) + x1*(_a6_**2/x1**2)**(_a1_*x1 + _a3_ + _a7_)/cos(_a5_ + cos(_a4_ + x1))) + _a5_))
<lambdifygenerated-14688>:2: RuntimeWarning: overflow encountered in power
  return sin(x1*(_a3_*(_a2_ + x1)*(_a3_*tanh(_a2_**6*tanh(x1)**3) + x1*(_a6_**2/x1**2)**(_a1_*x1 + _a3_ + _a7_)/cos(_a5_ + cos(_a4_ + x1))) + _a5_))
<lambdifygenerated-14688>:2: RuntimeWarning: invalid value encountered in sin
  return sin(x1*(_a3_*(_a2_ + x1)*(_a3_*tanh(_a2_**6*tanh(x1)**3) + x1*(_a6_**2/x1**2)**(_a1_*x1 + _a3_ + _a7_)/cos(_a5_ + cos(_a4_ + x1))) + _a5_))
<lambdifygenerated-14689>:2: RuntimeWarning: overflow encountered in power
  return sin(_a6_*(_a3_*(_a2_ + x1)*(_a3_*tanh(_a2_**6*tanh(x1)**3) + x1*(_a6_**2/x1**2)**(_a1_*x1 + _a3_ + _a7_)/cos(_a5_ + cos(_a4_ + x1))) + _a5_))
<lambdifygenerated-14689>:2: RuntimeWarning: invalid value encountered in sin
  return sin(_a6_*(_a3_*(_a2_ + x1)*(_a3_*tanh(_a2_**6*tanh(x1)**3) + x1*(_a6_**2/x1**2)**(_a1_*x1 + _a3_ + _a7_)/cos(_a5_ + cos(_a4_ + x1))) + _a5_))
<lambdifygenerated-14690>:2: RuntimeWarning: overflow encountered in power
  return sin(_a6_*(_a3_*(_a2_ + x1)*(_a3_*tanh(_a2_**6*tanh(x1)**3) + x1*(_a6_**2/x1**2)**(_a1_*x1 + _a3_ + _a7_)/cos(_a5_ + cos(_a4_ + x1))) + _a5_))
<lambdifygenerated-14690>:2: RuntimeWarning: invalid value encountered in sin
  return sin(_a6_*(_a3_*(_a2_ + x1)*(_a3_*tanh(_a2_**6*tanh(x1)**3) + x1*(_a6_**2/x1**2)**(_a1_*x1 + _a3_ + _a7_)/cos(_a5_ + cos(_a4_ + x1))) + _a5_))
<lambdifygenerated-14691>:2: RuntimeWarning: overflow encountered in power
  return sin(_a6_*(_a3_*(_a2_ + x1)*(_a3_*tanh(_a2_**6*tanh(x1)**3) + x1*(_a6_**2/x1**2)**(_a1_*x1 + _a3_ + _a7_)/cos(_a5_ + cos(_a4_ + x1))) + _a5_))
<lambdifygenerated-14691>:2: RuntimeWarning: invalid value encountered in sin
  return sin(_a6_*(_a3_*(_a2_ + x1)*(_a3_*tanh(_a2_**6*tanh(x1)**3) + x1*(_a6_**2/x1**2)**(_a1_*x1 + _a3_ + _a7_)/cos(_a5_ + cos(_a4_ + x1))) + _a5_))
<lambdifygenerated-14692>:2: RuntimeWarning: overflow encountered in power
  return sin(_a6_*(_a3_*(_a2_ + x1)*(_a3_*tanh(_a2_**6*tanh(x1)**3) + x1*(_a6_**2/x1**2)**(_a1_*x1 + _a3_ + _a7_)/cos(_a5_ + cos(_a4_ + x1))) + _a5_))
<lambdifygenerated-14692>:2: RuntimeWarning: invalid value encountered in sin
  return sin(_a6_*(_a3_*(_a2_ + x1)*(_a3_*tanh(_a2_**6*tanh(x1)**3) + x1*(_a6_**2/x1**2)**(_a1_*x1 + _a3_ + _a7_)/cos(_a5_ + cos(_a4_ + x1))) + _a5_))
<lambdifygenerated-14693>:2: RuntimeWarning: overflow encountered in power
  return sin(_a6_*(_a3_*(_a2_ + x1)*(_a3_*tanh(_a2_**6*tanh(x1)**3) + x1*(_a6_**2/x1**2)**(_a1_*x1 + _a3_ + _a7_)/cos(_a5_ + cos(_a4_ + x1))) + _a5_))
<lambdifygenerated-14693>:2: RuntimeWarning: invalid value encountered in sin
  return sin(_a6_*(_a3_*(_a2_ + x1)*(_a3_*tanh(_a2_**6*tanh(x1)**3) + x1*(_a6_**2/x1**2)**(_a1_*x1 + _a3_ + _a7_)/cos(_a5_ + cos(_a4_ + x1))) + _a5_))
<lambdifygenerated-14694>:2: RuntimeWarning: overflow encountered in power
  return sin(_a6_*(_a3_*(_a2_ + x1)*(_a3_*tanh(_a2_**6*tanh(x1)**3) + x1*(_a6_**2/x1**2)**(_a1_*x1 + _a3_ + _a7_)/cos(_a5_ + cos(_a4_ + x1))) + _a5_))
<lambdifygenerated-14694>:2: RuntimeWarning: invalid value encountered in sin
  return sin(_a6_*(_a3_*(_a2_ + x1)*(_a3_*tanh(_a2_**6*tanh(x1)**3) + x1*(_a6_**2/x1**2)**(_a1_*x1 + _a3_ + _a7_)/cos(_a5_ + cos(_a4_ + x1))) + _a5_))

         x1         y  rep    ymodel      ybms
3745  0.997  0.173654  7.0  0.169591  0.166860
3746  0.998  0.173884  7.0  0.169758  0.166948
3747  0.998  0.174114  7.0  0.169924  0.167036
3748  0.999  0.174344  7.0  0.170090  0.167122

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.174804  7.0  0.170422  0.167291
3751  1.002  0.175034  7.0  0.170587  0.167374
3752  1.002  0.175264  7.0  0.170751  0.167456
3753  1.003  0.175494  7.0  0.170916  0.167537

3750

<lambdifygenerated-14699>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1
<lambdifygenerated-14700>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1
<lambdifygenerated-14711>:2: RuntimeWarning: invalid value encountered in power
  return ((x1 + sin(2*x1 + x1**x1))**2)**x1
<lambdifygenerated-14712>:2: RuntimeWarning: invalid value encountered in power
  return ((x1 + sin(2*x1 + x1**x1))**2)**x1
<lambdifygenerated-14713>:2: RuntimeWarning: invalid value encountered in power
  return ((x1 + sin(2*x1 + sin(x1)**x1))**2)**x1
<lambdifygenerated-14714>:2: RuntimeWarning: invalid value encountered in power
  return ((x1 + sin(2*x1 + sin(x1)**x1))**2)**x1
<lambdifygenerated-14715>:2: RuntimeWarning: invalid value encountered in power
  return ((x1 + sin(2*x1 + sin(x1**x1)**x1))**2)**x1
<lambdifygenerated-14716>:2: RuntimeWarning: invalid value encountered in power
  return ((x1 + sin(2*x1 + sin(x1**x1)**x1))**2)**x1
<lambdifygenerated-14719>:2: RuntimeWarning: invalid value encountered in power
  return ((x1 + sin(2*x1 + sin((_a1_/x1)**x1)**x1))**2)**x1
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-14720>:2: RuntimeWarning: invalid value encountered in power
  return ((x1 + sin(2*x1 + sin((_a1_/x1)**x1)**x1))**2)**x1
<lambdifygenerated-14727>:2: RuntimeWarning: invalid value encountered in power
  return ((x1 + sin(2*x1 + sin((_a1_/_a7_)**(_a5_*x1 + x1))**x1))**2)**x1
<lambdifygenerated-14729>:2: RuntimeWarning: invalid value encountered in power
  return ((x1 + sin(2*x1 + sin((_a1_/_a7_)**(_a5_ + x1))**x1))**2)**x1
<lambdifygenerated-14733>:2: RuntimeWarning: invalid value encountered in power
  return ((x1 + sin(2*x1 + sin((_a1_/_a7_)**(x1 + _a5_*x1/_a0_))**x1))**2)**x1
<lambdifygenerated-14735>:2: RuntimeWarning: invalid value encountered in power
  return ((x1 + sin(2*x1 + sin((_a1_/_a7_)**(tanh(x1) + _a5_*x1/_a0_))**x1))**2)**x1
<lambdifygenerated-14737>:2: RuntimeWarning: invalid value encountered in power
  return ((x1 + sin(2*x1 + sin((_a1_/_a7_)**(tanh(2*x1) + _a5_*x1/_a0_))**x1))**2)**x1
<lambdifygenerated-14739>:2: RuntimeWarning: invalid value encountered in power
  return ((x1 + sin(2*x1 + sin((_a1_/_a7_)**(tanh(x1 + tanh(x1)) + _a5_*x1/_a0_))**x1))**2)**x1
<lambdifygenerated-14741>:2: RuntimeWarning: invalid value encountered in power
  return ((x1 + sin(2*x1 + sin((_a1_/_a7_)**(tanh(x1 + tanh(1)) + _a5_*x1/_a0_))**x1))**2)**x1
<lambdifygenerated-14745>:2: RuntimeWarning: invalid value encountered in power
  return ((x1 + sin(2*x1 + sin((_a1_/_a7_)**(tanh(x1 + tanh(x1/_a0_)) + _a5_*x1/_a0_))**x1))**2)**x1
<lambdifygenerated-14747>:2: RuntimeWarning: invalid value encountered in power
  return ((x1 + sin(2*x1 + sin((_a1_/_a7_)**(tanh(x1**2 + tanh(x1/_a0_)) + _a5_*x1/_a0_))**x1))**2)**x1
<lambdifygenerated-14751>:2: RuntimeWarning: invalid value encountered in power
  return ((x1 + sin(2*x1 + sin((_a1_/_a7_)**(tanh(x1**3 + tanh(x1/_a0_)) + _a5_*x1/_a0_))**x1))**2)**x1
<lambdifygenerated-14753>:2: RuntimeWarning: invalid value encountered in power
  return ((x1 + sin(2*x1 + sin((_a1_/_a7_)**(tanh(x1**4 + tanh(x1/_a0_)) + _a5_*x1/_a0_))**x1))**2)**x1
<lambdifygenerated-14755>:2: RuntimeWarning: invalid value encountered in power
  return ((x1 + sin(2*x1 + sin((_a1_/_a7_)**(tanh(2*x1**4 + tanh(x1/_a0_)) + _a5_*x1/_a0_))**x1))**2)**x1
<lambdifygenerated-14757>:2: RuntimeWarning: invalid value encountered in power
  return ((x1 + sin(2*x1 + sin((_a1_/_a7_)**(tanh(x1**3*(x1**2 + x1) + tanh(x1/_a0_)) + _a5_*x1/_a0_))**x1))**2)**x1
<lambdifygenerated-14759>:2: RuntimeWarning: invalid value encountered in power
  return ((x1 + sin(2*x1 + sin((_a1_/_a7_)**(tanh(x1**3*(_a1_*x1 + x1) + tanh(x1/_a0_)) + _a5_*x1/_a0_))**x1))**2)**x1
<lambdifygenerated-14763>:2: RuntimeWarning: invalid value encountered in power
  return ((x1 + sin(2*x1 + sin((_a1_/_a7_)**(tanh(x1**3*(_a1_*x1 + _a5_) + tanh(x1/_a0_)) + _a5_*x1/_a0_))**x1))**2)**x1
<lambdifygenerated-14765>:2: RuntimeWarning: invalid value encountered in power
  return ((x1 + sin(2*x1 + sin((_a1_/_a7_)**(tanh(_a4_*x1**2*(_a1_*x1 + _a5_) + tanh(x1/_a0_)) + _a5_*x1/_a0_))**x1))**2)**x1
<lambdifygenerated-14769>:2: RuntimeWarning: invalid value encountered in power
  return ((x1 + sin(2*x1 + sin((_a1_/_a7_)**(tanh(_a4_*x1**2*(_a1_*x1 + _a5_) + tanh(x1/_a0_)) + _a5_*x1/_a0_))**(x1**2)))**2)**x1
<lambdifygenerated-14775>:2: RuntimeWarning: overflow encountered in power
  return ((x1 + sin(2*x1 + sin((_a1_/_a7_)**(tanh(_a4_*x1**2*(_a1_*x1 + _a5_) + tanh(x1/_a0_)) + _a5_*x1/_a0_))**(-_a3_*_a7_)))**2)**x1
<lambdifygenerated-14775>:2: RuntimeWarning: invalid value encountered in power
  return ((x1 + sin(2*x1 + sin((_a1_/_a7_)**(tanh(_a4_*x1**2*(_a1_*x1 + _a5_) + tanh(x1/_a0_)) + _a5_*x1/_a0_))**(-_a3_*_a7_)))**2)**x1
<lambdifygenerated-14775>:2: RuntimeWarning: invalid value encountered in sin
  return ((x1 + sin(2*x1 + sin((_a1_/_a7_)**(tanh(_a4_*x1**2*(_a1_*x1 + _a5_) + tanh(x1/_a0_)) + _a5_*x1/_a0_))**(-_a3_*_a7_)))**2)**x1
<lambdifygenerated-14777>:2: RuntimeWarning: invalid value encountered in power
  return ((x1 + sin(_a4_ + x1 + sin((_a1_/_a7_)**(tanh(_a4_*x1**2*(_a1_*x1 + _a5_) + tanh(x1/_a0_)) + _a5_*x1/_a0_))**(-_a3_*_a7_)))**2)**x1
<lambdifygenerated-14779>:2: RuntimeWarning: invalid value encountered in power
  return ((x1 + sin(_a4_ + x1**2 + sin((_a1_/_a7_)**(tanh(_a4_*x1**2*(_a1_*x1 + _a5_) + tanh(x1/_a0_)) + _a5_*x1/_a0_))**(-_a3_*_a7_)))**2)**x1

interpolation

<lambdifygenerated-14787>:2: RuntimeWarning: overflow encountered in power
  return ((_a2_ + sin(_a1_*x1 + _a4_ + sin((_a1_/_a7_)**(tanh(_a4_*x1**2*(_a1_*x1 + _a5_) + tanh(x1/_a0_)) + _a5_*x1/_a0_))**(-_a3_*_a7_)))**2)**_a7_
/usr/local/lib/python3.10/dist-packages/scipy/optimize/_minpack_py.py:1017: RuntimeWarning: overflow encountered in square
  cost = np.sum(infodict['fvec'] ** 2)
/usr/local/lib/python3.10/dist-packages/pandas/core/arraylike.py:399: RuntimeWarning: overflow encountered in square
  result = getattr(ufunc, method)(*inputs, **kwargs)
<lambdifygenerated-14788>:2: RuntimeWarning: overflow encountered in power
  return ((_a2_ + sin(_a1_*x1 + _a4_ + sin((_a1_/_a7_)**(tanh(_a4_*x1**2*(_a1_*x1 + _a5_) + tanh(x1/_a0_)) + _a5_*x1/_a0_))**(-_a3_*_a7_)))**2)**_a7_
<lambdifygenerated-14789>:2: RuntimeWarning: overflow encountered in power
  return ((_a2_ + sin(_a1_*x1 + _a4_ + sin((_a1_/_a7_)**(tanh(_a4_*x1**2*(_a1_*x1 + _a5_) + tanh(x1/_a0_)) + _a5_*x1/_a0_))**(-_a3_*_a7_)))**2)**_a7_
<lambdifygenerated-14790>:2: RuntimeWarning: overflow encountered in power
  return ((_a2_ + sin(_a1_*x1 + _a4_ + sin((_a1_/_a7_)**(tanh(_a4_*x1**2*(_a1_*x1 + _a5_) + tanh(x1/_a0_)) + _a5_*x1/_a0_))**(-_a3_*_a7_)))**2)**_a7_
<lambdifygenerated-14791>:2: RuntimeWarning: overflow encountered in power
  return ((_a2_ + sin(_a1_*x1 + _a4_ + sin((_a1_/_a7_)**(tanh(_a4_*x1**2*(_a1_*x1 + _a5_) + tanh(x1/_a0_)) + _a5_*x1/_a0_))**(-_a3_*_a7_)))**2)**_a7_
<lambdifygenerated-14792>:2: RuntimeWarning: overflow encountered in power
  return ((_a2_ + sin(_a1_*x1 + _a4_ + sin((_a1_/_a7_)**(tanh(_a4_*x1**2*(_a1_*x1 + _a5_) + tanh(x1/_a0_)) + _a5_*x1/_a0_))**(-_a3_*_a7_)))**2)**_a7_

         x1         y  rep    ymodel      ybms
3745  0.997  0.261188  8.0  0.259800  0.264584
3746  0.998  0.261362  8.0  0.260022  0.264841
3747  0.998  0.261535  8.0  0.260243  0.265098
3748  0.999  0.261709  8.0  0.260464  0.265355

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.262056  8.0  0.260906  0.265868
3751  1.002  0.262229  8.0  0.261127  0.266124
3752  1.002  0.262402  8.0  0.261347  0.266380
3753  1.003  0.262576  8.0  0.261567  0.266636

3750

<lambdifygenerated-14797>:2: RuntimeWarning: invalid value encountered in log
  return log(x1)
<lambdifygenerated-14798>:2: RuntimeWarning: invalid value encountered in log
  return log(x1)
<lambdifygenerated-14801>:2: RuntimeWarning: invalid value encountered in power
  return log(x1**x1/x1)
<lambdifygenerated-14802>:2: RuntimeWarning: invalid value encountered in power
  return log(x1**x1/x1)
<lambdifygenerated-14803>:2: RuntimeWarning: invalid value encountered in power
  return log((2*x1)**x1/x1)
<lambdifygenerated-14804>:2: RuntimeWarning: invalid value encountered in power
  return log((2*x1)**x1/x1)
<lambdifygenerated-14805>:2: RuntimeWarning: invalid value encountered in power
  return log((3*x1)**x1/x1)
<lambdifygenerated-14806>:2: RuntimeWarning: invalid value encountered in power
  return log((3*x1)**x1/x1)
<lambdifygenerated-14807>:2: RuntimeWarning: invalid value encountered in power
  return log((2*x1 + x1**x1)**x1/x1)
<lambdifygenerated-14808>:2: RuntimeWarning: invalid value encountered in power
  return log((2*x1 + x1**x1)**x1/x1)
<lambdifygenerated-14809>:2: RuntimeWarning: invalid value encountered in power
  return log((2*x1 + sin(x1)**x1)**x1/x1)
<lambdifygenerated-14810>:2: RuntimeWarning: invalid value encountered in power
  return log((2*x1 + sin(x1)**x1)**x1/x1)
<lambdifygenerated-14811>:2: RuntimeWarning: invalid value encountered in power
  return log((2*x1 + sin(x1**2)**x1)**x1/x1)
<lambdifygenerated-14811>:2: RuntimeWarning: invalid value encountered in log
  return log((2*x1 + sin(x1**2)**x1)**x1/x1)
<lambdifygenerated-14812>:2: RuntimeWarning: invalid value encountered in power
  return log((2*x1 + sin(x1**2)**x1)**x1/x1)
<lambdifygenerated-14812>:2: RuntimeWarning: invalid value encountered in log
  return log((2*x1 + sin(x1**2)**x1)**x1/x1)
<lambdifygenerated-14813>:2: RuntimeWarning: invalid value encountered in power
  return log((2*x1 + sin(x1*x1**x1)**x1)**x1/x1)
<lambdifygenerated-14814>:2: RuntimeWarning: invalid value encountered in power
  return log((2*x1 + sin(x1*x1**x1)**x1)**x1/x1)
<lambdifygenerated-14815>:2: RuntimeWarning: invalid value encountered in power
  return log((2*x1 + sin(x1*cos(x1)**x1)**x1)**x1/x1)
<lambdifygenerated-14815>:2: RuntimeWarning: invalid value encountered in log
  return log((2*x1 + sin(x1*cos(x1)**x1)**x1)**x1/x1)
<lambdifygenerated-14816>:2: RuntimeWarning: invalid value encountered in power
  return log((2*x1 + sin(x1*cos(x1)**x1)**x1)**x1/x1)
<lambdifygenerated-14816>:2: RuntimeWarning: invalid value encountered in log
  return log((2*x1 + sin(x1*cos(x1)**x1)**x1)**x1/x1)
<lambdifygenerated-14817>:2: RuntimeWarning: invalid value encountered in power
  return log((2*x1 + sin(x1*cos(tanh(x1))**x1)**x1)**x1/x1)
<lambdifygenerated-14817>:2: RuntimeWarning: invalid value encountered in log
  return log((2*x1 + sin(x1*cos(tanh(x1))**x1)**x1)**x1/x1)
<lambdifygenerated-14818>:2: RuntimeWarning: invalid value encountered in power
  return log((2*x1 + sin(x1*cos(tanh(x1))**x1)**x1)**x1/x1)
<lambdifygenerated-14818>:2: RuntimeWarning: invalid value encountered in log
  return log((2*x1 + sin(x1*cos(tanh(x1))**x1)**x1)**x1/x1)
<lambdifygenerated-14819>:2: RuntimeWarning: invalid value encountered in power
  return log((2*x1 + sin(x1*cos(tanh(1))**x1)**x1)**x1/x1)
<lambdifygenerated-14819>:2: RuntimeWarning: invalid value encountered in log
  return log((2*x1 + sin(x1*cos(tanh(1))**x1)**x1)**x1/x1)
<lambdifygenerated-14820>:2: RuntimeWarning: invalid value encountered in power
  return log((2*x1 + sin(x1*cos(tanh(1))**x1)**x1)**x1/x1)
<lambdifygenerated-14820>:2: RuntimeWarning: invalid value encountered in log
  return log((2*x1 + sin(x1*cos(tanh(1))**x1)**x1)**x1/x1)
<lambdifygenerated-14821>:2: RuntimeWarning: invalid value encountered in power
  return log((2*x1 + sin(x1*cos(tanh(2))**x1)**x1)**x1/x1)
<lambdifygenerated-14821>:2: RuntimeWarning: invalid value encountered in log
  return log((2*x1 + sin(x1*cos(tanh(2))**x1)**x1)**x1/x1)
<lambdifygenerated-14822>:2: RuntimeWarning: invalid value encountered in power
  return log((2*x1 + sin(x1*cos(tanh(2))**x1)**x1)**x1/x1)
<lambdifygenerated-14822>:2: RuntimeWarning: invalid value encountered in log
  return log((2*x1 + sin(x1*cos(tanh(2))**x1)**x1)**x1/x1)
<lambdifygenerated-14823>:2: RuntimeWarning: invalid value encountered in power
  return log((2*x1 + sin(x1*cos(tanh((x1 + tanh(x1))/x1))**x1)**x1)**x1/x1)
<lambdifygenerated-14823>:2: RuntimeWarning: invalid value encountered in log
  return log((2*x1 + sin(x1*cos(tanh((x1 + tanh(x1))/x1))**x1)**x1)**x1/x1)
<lambdifygenerated-14824>:2: RuntimeWarning: invalid value encountered in power
  return log((2*x1 + sin(x1*cos(tanh((x1 + tanh(x1))/x1))**x1)**x1)**x1/x1)
<lambdifygenerated-14824>:2: RuntimeWarning: invalid value encountered in log
  return log((2*x1 + sin(x1*cos(tanh((x1 + tanh(x1))/x1))**x1)**x1)**x1/x1)
<lambdifygenerated-14825>:2: RuntimeWarning: invalid value encountered in power
  return log((2*x1 + sin(x1*cos(tanh((x1 + tanh(x1**2))/x1))**x1)**x1)**x1/x1)
<lambdifygenerated-14826>:2: RuntimeWarning: invalid value encountered in power
  return log((2*x1 + sin(x1*cos(tanh((x1 + tanh(x1**2))/x1))**x1)**x1)**x1/x1)
<lambdifygenerated-14827>:2: RuntimeWarning: invalid value encountered in power
  return log((2*x1 + sin(x1*cos(tanh((x1 - tanh(x1**2))/x1))**x1)**x1)**x1/x1)
<lambdifygenerated-14827>:2: RuntimeWarning: invalid value encountered in log
  return log((2*x1 + sin(x1*cos(tanh((x1 - tanh(x1**2))/x1))**x1)**x1)**x1/x1)
<lambdifygenerated-14828>:2: RuntimeWarning: invalid value encountered in power
  return log((2*x1 + sin(x1*cos(tanh((x1 - tanh(x1**2))/x1))**x1)**x1)**x1/x1)
<lambdifygenerated-14828>:2: RuntimeWarning: invalid value encountered in log
  return log((2*x1 + sin(x1*cos(tanh((x1 - tanh(x1**2))/x1))**x1)**x1)**x1/x1)
<lambdifygenerated-14829>:2: RuntimeWarning: invalid value encountered in power
  return log((2*x1 + sin(x1*cos(tanh((x1 - tanh(x1**2))/x1))**x1)**x1)**x1/x1)
<lambdifygenerated-14829>:2: RuntimeWarning: invalid value encountered in log
  return log((2*x1 + sin(x1*cos(tanh((x1 - tanh(x1**2))/x1))**x1)**x1)**x1/x1)
<lambdifygenerated-14830>:2: RuntimeWarning: invalid value encountered in power
  return log((2*x1 + sin(x1*cos(tanh((x1 - tanh(x1**2))/x1))**x1)**x1)**x1/x1)
<lambdifygenerated-14830>:2: RuntimeWarning: invalid value encountered in log
  return log((2*x1 + sin(x1*cos(tanh((x1 - tanh(x1**2))/x1))**x1)**x1)**x1/x1)
<lambdifygenerated-14831>:2: RuntimeWarning: invalid value encountered in power
  return log((2*x1 + sin(x1*cos(tanh((x1 - tanh(_a1_*x1))/x1))**x1)**x1)**x1/x1)
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-14832>:2: RuntimeWarning: invalid value encountered in power
  return log((2*x1 + sin(x1*cos(tanh((x1 - tanh(_a1_*x1))/x1))**x1)**x1)**x1/x1)
<lambdifygenerated-14833>:2: RuntimeWarning: invalid value encountered in power
  return log((2*x1 + sin(x1*cos(tanh((_a7_ - tanh(_a1_*x1))/x1))**x1)**x1)**x1/x1)
<lambdifygenerated-14833>:2: RuntimeWarning: invalid value encountered in log
  return log((2*x1 + sin(x1*cos(tanh((_a7_ - tanh(_a1_*x1))/x1))**x1)**x1)**x1/x1)
<lambdifygenerated-14834>:2: RuntimeWarning: invalid value encountered in power
  return log((2*x1 + sin(x1*cos(tanh((_a7_ - tanh(_a1_*x1))/x1))**x1)**x1)**x1/x1)
<lambdifygenerated-14834>:2: RuntimeWarning: invalid value encountered in log
  return log((2*x1 + sin(x1*cos(tanh((_a7_ - tanh(_a1_*x1))/x1))**x1)**x1)**x1/x1)
<lambdifygenerated-14835>:2: RuntimeWarning: invalid value encountered in power
  return log((2*x1 + sin(x1*cos(tanh((_a7_ - tanh(_a1_*x1))/_a6_))**x1)**x1)**x1/x1)
<lambdifygenerated-14835>:2: RuntimeWarning: invalid value encountered in log
  return log((2*x1 + sin(x1*cos(tanh((_a7_ - tanh(_a1_*x1))/_a6_))**x1)**x1)**x1/x1)
<lambdifygenerated-14836>:2: RuntimeWarning: invalid value encountered in power
  return log((2*x1 + sin(x1*cos(tanh((_a7_ - tanh(_a1_*x1))/_a6_))**x1)**x1)**x1/x1)
<lambdifygenerated-14836>:2: RuntimeWarning: invalid value encountered in log
  return log((2*x1 + sin(x1*cos(tanh((_a7_ - tanh(_a1_*x1))/_a6_))**x1)**x1)**x1/x1)
<lambdifygenerated-14837>:2: RuntimeWarning: invalid value encountered in power
  return log((2*x1 + sin(x1*cos(tanh((_a7_ - tanh(_a1_*x1))/_a6_))**(2*x1))**x1)**x1/x1)
<lambdifygenerated-14837>:2: RuntimeWarning: invalid value encountered in log
  return log((2*x1 + sin(x1*cos(tanh((_a7_ - tanh(_a1_*x1))/_a6_))**(2*x1))**x1)**x1/x1)
<lambdifygenerated-14838>:2: RuntimeWarning: invalid value encountered in power
  return log((2*x1 + sin(x1*cos(tanh((_a7_ - tanh(_a1_*x1))/_a6_))**(2*x1))**x1)**x1/x1)
<lambdifygenerated-14838>:2: RuntimeWarning: invalid value encountered in log
  return log((2*x1 + sin(x1*cos(tanh((_a7_ - tanh(_a1_*x1))/_a6_))**(2*x1))**x1)**x1/x1)
<lambdifygenerated-14839>:2: RuntimeWarning: invalid value encountered in power
  return log((2*x1 + sin(x1*cos(tanh((_a7_ - tanh(_a1_*x1))/_a6_))**(x1 + cosh(x1)))**x1)**x1/x1)
<lambdifygenerated-14840>:2: RuntimeWarning: invalid value encountered in power
  return log((2*x1 + sin(x1*cos(tanh((_a7_ - tanh(_a1_*x1))/_a6_))**(x1 + cosh(x1)))**x1)**x1/x1)
<lambdifygenerated-14841>:2: RuntimeWarning: invalid value encountered in power
  return log((2*x1 + sin(x1*cos(tanh((_a7_ - tanh(_a1_*x1))/_a6_))**(x1 + cosh(x1)))**x1)**x1/x1)
<lambdifygenerated-14842>:2: RuntimeWarning: invalid value encountered in power
  return log((2*x1 + sin(x1*cos(tanh((_a7_ - tanh(_a1_*x1))/_a6_))**(x1 + cosh(x1)))**x1)**x1/x1)
<lambdifygenerated-14843>:2: RuntimeWarning: invalid value encountered in power
  return log((2*x1 + sin(x1*cos(tanh((_a7_ - tanh(_a1_*x1))/_a6_))**(_a2_ + cosh(x1)))**x1)**x1/x1)
<lambdifygenerated-14844>:2: RuntimeWarning: invalid value encountered in power
  return log((2*x1 + sin(x1*cos(tanh((_a7_ - tanh(_a1_*x1))/_a6_))**(_a2_ + cosh(x1)))**x1)**x1/x1)
<lambdifygenerated-14845>:2: RuntimeWarning: invalid value encountered in power
  return log((2*x1 + sin(x1**2*cos(tanh((_a7_ - tanh(_a1_*x1))/_a6_))**(_a2_ + cosh(x1)))**x1)**x1/x1)
<lambdifygenerated-14845>:2: RuntimeWarning: invalid value encountered in log
  return log((2*x1 + sin(x1**2*cos(tanh((_a7_ - tanh(_a1_*x1))/_a6_))**(_a2_ + cosh(x1)))**x1)**x1/x1)
<lambdifygenerated-14846>:2: RuntimeWarning: invalid value encountered in power
  return log((2*x1 + sin(x1**2*cos(tanh((_a7_ - tanh(_a1_*x1))/_a6_))**(_a2_ + cosh(x1)))**x1)**x1/x1)
<lambdifygenerated-14846>:2: RuntimeWarning: invalid value encountered in log
  return log((2*x1 + sin(x1**2*cos(tanh((_a7_ - tanh(_a1_*x1))/_a6_))**(_a2_ + cosh(x1)))**x1)**x1/x1)
<lambdifygenerated-14847>:2: RuntimeWarning: invalid value encountered in power
  return log((2*x1 + sin(_a4_*x1*cos(tanh((_a7_ - tanh(_a1_*x1))/_a6_))**(_a2_ + cosh(x1)))**x1)**x1/x1)
<lambdifygenerated-14848>:2: RuntimeWarning: invalid value encountered in power
  return log((2*x1 + sin(_a4_*x1*cos(tanh((_a7_ - tanh(_a1_*x1))/_a6_))**(_a2_ + cosh(x1)))**x1)**x1/x1)
<lambdifygenerated-14849>:2: RuntimeWarning: invalid value encountered in log
  return log((2*x1 + sin(_a4_**2*cos(tanh((_a7_ - tanh(_a1_*x1))/_a6_))**(_a2_ + cosh(x1)))**x1)**x1/x1)
<lambdifygenerated-14850>:2: RuntimeWarning: invalid value encountered in log
  return log((2*x1 + sin(_a4_**2*cos(tanh((_a7_ - tanh(_a1_*x1))/_a6_))**(_a2_ + cosh(x1)))**x1)**x1/x1)
<lambdifygenerated-14851>:2: RuntimeWarning: invalid value encountered in power
  return log((2*x1 + sin(_a4_**2*cos(tanh((_a7_ - tanh(_a1_*x1))/_a6_))**(_a2_ + cosh(x1)))**_a7_)**x1/x1)
<lambdifygenerated-14851>:2: RuntimeWarning: invalid value encountered in log
  return log((2*x1 + sin(_a4_**2*cos(tanh((_a7_ - tanh(_a1_*x1))/_a6_))**(_a2_ + cosh(x1)))**_a7_)**x1/x1)

interpolation

<lambdifygenerated-14852>:2: RuntimeWarning: invalid value encountered in power
  return log((2*x1 + sin(_a4_**2*cos(tanh((_a7_ - tanh(_a1_*x1))/_a6_))**(_a2_ + cosh(x1)))**_a7_)**x1/x1)
<lambdifygenerated-14852>:2: RuntimeWarning: invalid value encountered in log
  return log((2*x1 + sin(_a4_**2*cos(tanh((_a7_ - tanh(_a1_*x1))/_a6_))**(_a2_ + cosh(x1)))**_a7_)**x1/x1)
<lambdifygenerated-14853>:2: RuntimeWarning: invalid value encountered in power
  return log((_a3_ + x1 + sin(_a4_**2*cos(tanh((_a7_ - tanh(_a1_*x1))/_a6_))**(_a2_ + cosh(x1)))**_a7_)**x1/x1)
<lambdifygenerated-14853>:2: RuntimeWarning: invalid value encountered in log
  return log((_a3_ + x1 + sin(_a4_**2*cos(tanh((_a7_ - tanh(_a1_*x1))/_a6_))**(_a2_ + cosh(x1)))**_a7_)**x1/x1)
<lambdifygenerated-14854>:2: RuntimeWarning: invalid value encountered in power
  return log((_a3_ + x1 + sin(_a4_**2*cos(tanh((_a7_ - tanh(_a1_*x1))/_a6_))**(_a2_ + cosh(x1)))**_a7_)**x1/x1)
<lambdifygenerated-14854>:2: RuntimeWarning: invalid value encountered in log
  return log((_a3_ + x1 + sin(_a4_**2*cos(tanh((_a7_ - tanh(_a1_*x1))/_a6_))**(_a2_ + cosh(x1)))**_a7_)**x1/x1)
<lambdifygenerated-14855>:2: RuntimeWarning: invalid value encountered in log
  return log((_a1_ + _a3_ + sin(_a4_**2*cos(tanh((_a7_ - tanh(_a1_*x1))/_a6_))**(_a2_ + cosh(x1)))**_a7_)**x1/x1)
<lambdifygenerated-14856>:2: RuntimeWarning: invalid value encountered in log
  return log((_a1_ + _a3_ + sin(_a4_**2*cos(tanh((_a7_ - tanh(_a1_*x1))/_a6_))**(_a2_ + cosh(x1)))**_a7_)**x1/x1)
<lambdifygenerated-14857>:2: RuntimeWarning: invalid value encountered in log
  return log((_a1_ + _a3_ + sin(_a4_**2*cos(tanh((_a7_ - tanh(_a1_*x1))/_a6_))**(_a2_ + cosh(x1)))**_a7_)**_a6_/x1)
<lambdifygenerated-14858>:2: RuntimeWarning: invalid value encountered in log
  return log((_a1_ + _a3_ + sin(_a4_**2*cos(tanh((_a7_ - tanh(_a1_*x1))/_a6_))**(_a2_ + cosh(x1)))**_a7_)**_a6_/x1)
<lambdifygenerated-14859>:2: RuntimeWarning: invalid value encountered in power
  return log((_a1_ + _a3_ + sin(_a4_**2*cos(tanh((_a7_ - tanh(_a1_*x1))/_a6_))**(_a2_ + cosh(x1)))**_a7_)**_a6_/_a3_)
<lambdifygenerated-14859>:2: RuntimeWarning: invalid value encountered in log
  return log((_a1_ + _a3_ + sin(_a4_**2*cos(tanh((_a7_ - tanh(_a1_*x1))/_a6_))**(_a2_ + cosh(x1)))**_a7_)**_a6_/_a3_)

         x1        y  rep    ymodel      ybms
3745  0.997  0.64259  9.0  0.642304  0.641316
3746  0.998  0.64247  9.0  0.642163  0.641151
3747  0.998  0.64235  9.0  0.642021  0.640987
3748  0.999  0.64223  9.0  0.641880  0.640823

extrapolation

         x1        y  rep    ymodel      ybms
3750  1.001  0.64199  9.0  0.641598  0.640494
3751  1.002  0.64187  9.0  0.641458  0.640329
3752  1.002  0.64175  9.0  0.641317  0.640164
3753  1.003  0.64163  9.0  0.641176  0.639999

3750
interpolation

<lambdifygenerated-14869>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1
<lambdifygenerated-14870>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1
<lambdifygenerated-14871>:2: RuntimeWarning: invalid value encountered in power
  return x1**((1/2)*x1)
<lambdifygenerated-14872>:2: RuntimeWarning: invalid value encountered in power
  return x1**((1/2)*x1)
<lambdifygenerated-14873>:2: RuntimeWarning: invalid value encountered in sqrt
  return (sqrt(2)*sqrt(x1))**x1
<lambdifygenerated-14874>:2: RuntimeWarning: invalid value encountered in sqrt
  return (sqrt(2)*sqrt(x1))**x1
<lambdifygenerated-14875>:2: RuntimeWarning: invalid value encountered in power
  return (x1**2 + x1)**((1/2)*x1)
<lambdifygenerated-14876>:2: RuntimeWarning: invalid value encountered in power
  return (x1**2 + x1)**((1/2)*x1)
<lambdifygenerated-14877>:2: RuntimeWarning: invalid value encountered in power
  return (x1*exp(x1) + x1)**((1/2)*x1)
<lambdifygenerated-14878>:2: RuntimeWarning: invalid value encountered in power
  return (x1*exp(x1) + x1)**((1/2)*x1)
<lambdifygenerated-14879>:2: RuntimeWarning: invalid value encountered in power
  return (x1*exp(x1**2) + x1)**((1/2)*x1)
<lambdifygenerated-14880>:2: RuntimeWarning: invalid value encountered in power
  return (x1*exp(x1**2) + x1)**((1/2)*x1)
<lambdifygenerated-14881>:2: RuntimeWarning: invalid value encountered in power
  return (x1*exp(_a4_*x1) + x1)**((1/2)*x1)
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-14882>:2: RuntimeWarning: invalid value encountered in power
  return (x1*exp(_a4_*x1) + x1)**((1/2)*x1)
<lambdifygenerated-14883>:2: RuntimeWarning: invalid value encountered in power
  return (x1*exp(_a4_*x1) + x1)**((1/2)*x1)
<lambdifygenerated-14884>:2: RuntimeWarning: invalid value encountered in power
  return (x1*exp(_a4_*x1) + x1)**((1/2)*x1)
<lambdifygenerated-14885>:2: RuntimeWarning: invalid value encountered in power
  return (_a2_*exp(_a4_*x1) + x1)**((1/2)*x1)
<lambdifygenerated-14886>:2: RuntimeWarning: invalid value encountered in power
  return (_a2_*exp(_a4_*x1) + x1)**((1/2)*x1)
<lambdifygenerated-14887>:2: RuntimeWarning: invalid value encountered in power
  return (_a2_*exp(_a4_*x1) + x1**2)**((1/2)*x1)
<lambdifygenerated-14889>:2: RuntimeWarning: invalid value encountered in power
  return (_a1_*x1 + _a2_*exp(_a4_*x1))**((1/2)*x1)
<lambdifygenerated-14890>:2: RuntimeWarning: invalid value encountered in power
  return (_a1_*x1 + _a2_*exp(_a4_*x1))**((1/2)*x1)
<lambdifygenerated-14891>:2: RuntimeWarning: invalid value encountered in power
  return (2*_a1_*x1 + _a2_*exp(_a4_*x1))**((1/2)*x1)
<lambdifygenerated-14892>:2: RuntimeWarning: invalid value encountered in power
  return (2*_a1_*x1 + _a2_*exp(_a4_*x1))**((1/2)*x1)
<lambdifygenerated-14893>:2: RuntimeWarning: invalid value encountered in power
  return (2*_a1_*x1 + _a2_*exp(_a4_*x1))**((1/2)*x1)
<lambdifygenerated-14894>:2: RuntimeWarning: invalid value encountered in power
  return (2*_a1_*x1 + _a2_*exp(_a4_*x1))**((1/2)*x1)
<lambdifygenerated-14895>:2: RuntimeWarning: invalid value encountered in power
  return (_a1_*(_a4_ + x1) + _a2_*exp(_a4_*x1))**((1/2)*x1)
<lambdifygenerated-14896>:2: RuntimeWarning: invalid value encountered in power
  return (_a1_*(_a4_ + x1) + _a2_*exp(_a4_*x1))**((1/2)*x1)
<lambdifygenerated-14897>:2: RuntimeWarning: invalid value encountered in power
  return (_a1_*(_a4_ + x1) + _a2_*exp(_a4_*x1))**((1/2)*_a4_)
<lambdifygenerated-14898>:2: RuntimeWarning: invalid value encountered in power
  return (_a1_*(_a4_ + x1) + _a2_*exp(_a4_*x1))**((1/2)*_a4_)
<lambdifygenerated-14899>:2: RuntimeWarning: invalid value encountered in power
  return (_a1_*(_a4_ + x1) + _a2_*exp(_a4_*x1))**((1/2)*_a4_)
<lambdifygenerated-14900>:2: RuntimeWarning: invalid value encountered in power
  return (_a1_*(_a4_ + x1) + _a2_*exp(_a4_*x1))**((1/2)*_a4_)
<lambdifygenerated-14901>:2: RuntimeWarning: invalid value encountered in power
  return (_a1_*(_a4_ + x1) + _a2_*exp(_a4_*x1))**((1/2)*_a4_)
<lambdifygenerated-14902>:2: RuntimeWarning: invalid value encountered in power
  return (_a1_*(_a4_ + x1) + _a2_*exp(_a4_*x1))**((1/2)*_a4_)

         x1         y  rep    ymodel      ybms
3745  0.997  0.360683  0.0  0.362497  0.367268
3746  0.998  0.360826  0.0  0.362636  0.367448
3747  0.998  0.360969  0.0  0.362775  0.367629
3748  0.999  0.361111  0.0  0.362914  0.367810

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.361396  0.0  0.363192  0.368172
3751  1.002  0.361539  0.0  0.363331  0.368353
3752  1.002  0.361681  0.0  0.363470  0.368535
3753  1.003  0.361824  0.0  0.363609  0.368716

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.875844  1.0  0.891025  0.911310
3746  0.998  0.875274  1.0  0.890907  0.911441
3747  0.998  0.874704  1.0  0.890789  0.911573
3748  0.999  0.874135  1.0  0.890671  0.911705

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.872995  1.0  0.890435  0.911973
3751  1.002  0.872426  1.0  0.890317  0.912108
3752  1.002  0.871856  1.0  0.890199  0.912244
3753  1.003  0.871287  1.0  0.890081  0.912380

3750

<lambdifygenerated-14953>:2: RuntimeWarning: invalid value encountered in power
  return sin((2*x1 + exp(x1**x1))/x1)**2
<lambdifygenerated-14954>:2: RuntimeWarning: invalid value encountered in power
  return sin((2*x1 + exp(x1**x1))/x1)**2
<lambdifygenerated-14955>:2: RuntimeWarning: invalid value encountered in power
  return sin((2*x1 + exp(-x1**x1))/x1)**2
<lambdifygenerated-14956>:2: RuntimeWarning: invalid value encountered in power
  return sin((2*x1 + exp(-x1**x1))/x1)**2
<lambdifygenerated-14963>:2: RuntimeWarning: overflow encountered in power
  return sin((2*x1 + exp(-_a6_**(_a0_ + x1)))/x1)**2
/usr/local/lib/python3.10/dist-packages/scipy/optimize/_minpack_py.py:497: RuntimeWarning: overflow encountered in matmul
  cov_x = invR @ invR.T
<lambdifygenerated-14964>:2: RuntimeWarning: overflow encountered in power
  return sin((2*x1 + exp(-_a6_**(_a0_ + x1)))/x1)**2
<lambdifygenerated-14965>:2: RuntimeWarning: overflow encountered in power
  return sin((x1**2 + x1 + exp(-_a6_**(_a0_ + x1)))/x1)**2
<lambdifygenerated-14965>:2: RuntimeWarning: invalid value encountered in power
  return sin((x1**2 + x1 + exp(-_a6_**(_a0_ + x1)))/x1)**2

interpolation

/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-14971>:2: RuntimeWarning: invalid value encountered in sin
  return sin((_a6_ + _a7_*x1 + exp(-_a6_**(_a0_ + x1)))/x1)**2
<lambdifygenerated-14972>:2: RuntimeWarning: invalid value encountered in sin
  return sin((_a6_ + _a7_*x1 + exp(-_a6_**(_a0_ + x1)))/x1)**2
<lambdifygenerated-14973>:2: RuntimeWarning: invalid value encountered in log
  return sin((_a6_ + _a7_*x1 + exp(-_a6_**(_a0_ + x1)))/log(x1))**2
<lambdifygenerated-14973>:2: RuntimeWarning: invalid value encountered in sin
  return sin((_a6_ + _a7_*x1 + exp(-_a6_**(_a0_ + x1)))/log(x1))**2
<lambdifygenerated-14974>:2: RuntimeWarning: invalid value encountered in log
  return sin((_a6_ + _a7_*x1 + exp(-_a6_**(_a0_ + x1)))/log(x1))**2
<lambdifygenerated-14974>:2: RuntimeWarning: invalid value encountered in sin
  return sin((_a6_ + _a7_*x1 + exp(-_a6_**(_a0_ + x1)))/log(x1))**2
<lambdifygenerated-14975>:2: RuntimeWarning: invalid value encountered in divide
  return sin((_a6_ + _a7_*x1 + exp(-_a6_**(_a0_ + x1)))/log(_a6_))**2
<lambdifygenerated-14976>:2: RuntimeWarning: invalid value encountered in divide
  return sin((_a6_ + _a7_*x1 + exp(-_a6_**(_a0_ + x1)))/log(_a6_))**2
<lambdifygenerated-14977>:2: RuntimeWarning: invalid value encountered in divide
  return sin((_a6_ + _a7_*x1 + exp(-_a6_**(_a0_ + x1)))/log(_a6_))**2
<lambdifygenerated-14978>:2: RuntimeWarning: invalid value encountered in divide
  return sin((_a6_ + _a7_*x1 + exp(-_a6_**(_a0_ + x1)))/log(_a6_))**2
<lambdifygenerated-14979>:2: RuntimeWarning: invalid value encountered in divide
  return sin((_a6_ + _a7_*x1 + exp(-_a6_**(_a0_ + x1)))/log(_a6_))**2
<lambdifygenerated-14980>:2: RuntimeWarning: invalid value encountered in divide
  return sin((_a6_ + _a7_*x1 + exp(-_a6_**(_a0_ + x1)))/log(_a6_))**2

         x1         y  rep    ymodel      ybms
3745  0.997  0.997734  2.0  0.998321  0.998200
3746  0.998  0.997761  2.0  0.998324  0.998216
3747  0.998  0.997787  2.0  0.998326  0.998232
3748  0.999  0.997814  2.0  0.998329  0.998248

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.997867  2.0  0.998334  0.998279
3751  1.002  0.997894  2.0  0.998337  0.998295
3752  1.002  0.997921  2.0  0.998339  0.998310
3753  1.003  0.997948  2.0  0.998341  0.998326

3750
interpolation

<lambdifygenerated-14993>:2: RuntimeWarning: invalid value encountered in power
  return x1**2*(x1 + x1**x1)**2 + x1
<lambdifygenerated-14994>:2: RuntimeWarning: invalid value encountered in power
  return x1**2*(x1 + x1**x1)**2 + x1
<lambdifygenerated-14999>:2: RuntimeWarning: invalid value encountered in power
  return x1**2*(_a3_**x1 + 2*x1)**2 + x1

         x1         y  rep    ymodel      ybms
3745  0.997  0.689029  3.0  0.686871  0.694533
3746  0.998  0.688777  3.0  0.686490  0.694363
3747  0.998  0.688525  3.0  0.686109  0.694196
3748  0.999  0.688273  3.0  0.685728  0.694032

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.687768  3.0  0.684966  0.693712
3751  1.002  0.687516  3.0  0.684585  0.693557
3752  1.002  0.687264  3.0  0.684204  0.693404
3753  1.003  0.687012  3.0  0.683823  0.693255

3750

<lambdifygenerated-15029>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (_a1_ + _a4_*x1**x1)**2
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-15030>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (_a1_ + _a4_*x1**x1)**2

interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.661298  4.0  0.656679  0.655562
3746  0.998  0.661485  4.0  0.656867  0.655798
3747  0.998  0.661672  4.0  0.657054  0.656034
3748  0.999  0.661858  4.0  0.657243  0.656271

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.662232  4.0  0.657620  0.656748
3751  1.002  0.662419  4.0  0.657810  0.656988
3752  1.002  0.662605  4.0  0.658000  0.657228
3753  1.003  0.662792  4.0  0.658191  0.657469

3750
interpolation

<lambdifygenerated-15045>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1
<lambdifygenerated-15046>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1

         x1         y  rep    ymodel      ybms
3745  0.997  0.956369  5.0  0.957160  0.942582
3746  0.998  0.956259  5.0  0.957014  0.942282
3747  0.998  0.956150  5.0  0.956867  0.941981
3748  0.999  0.956040  5.0  0.956721  0.941678

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.955822  5.0  0.956426  0.941069
3751  1.002  0.955712  5.0  0.956279  0.940763
3752  1.002  0.955603  5.0  0.956131  0.940456
3753  1.003  0.955493  5.0  0.955982  0.940147

3750

<lambdifygenerated-15083>:2: RuntimeWarning: invalid value encountered in power
  return exp(_a3_*x1*x1**x1 + x1)
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-15084>:2: RuntimeWarning: invalid value encountered in power
  return exp(_a3_*x1*x1**x1 + x1)
<lambdifygenerated-15087>:2: RuntimeWarning: overflow encountered in power
  return exp(_a1_**(2*x1)*_a3_*x1 + x1)
<lambdifygenerated-15087>:2: RuntimeWarning: overflow encountered in multiply
  return exp(_a1_**(2*x1)*_a3_*x1 + x1)
<lambdifygenerated-15087>:2: RuntimeWarning: invalid value encountered in power
  return exp(_a1_**(2*x1)*_a3_*x1 + x1)
<lambdifygenerated-15089>:2: RuntimeWarning: overflow encountered in power
  return exp(_a1_**(x1**2 + x1)*_a3_*x1 + x1)
<lambdifygenerated-15089>:2: RuntimeWarning: overflow encountered in multiply
  return exp(_a1_**(x1**2 + x1)*_a3_*x1 + x1)
<lambdifygenerated-15089>:2: RuntimeWarning: overflow encountered in exp
  return exp(_a1_**(x1**2 + x1)*_a3_*x1 + x1)
/usr/local/lib/python3.10/dist-packages/scipy/optimize/_minpack_py.py:1017: RuntimeWarning: overflow encountered in square
  cost = np.sum(infodict['fvec'] ** 2)
/usr/local/lib/python3.10/dist-packages/pandas/core/arraylike.py:399: RuntimeWarning: overflow encountered in square
  result = getattr(ufunc, method)(*inputs, **kwargs)
<lambdifygenerated-15090>:2: RuntimeWarning: overflow encountered in power
  return exp(_a1_**(x1**2 + x1)*_a3_*x1 + x1)
<lambdifygenerated-15090>:2: RuntimeWarning: overflow encountered in multiply
  return exp(_a1_**(x1**2 + x1)*_a3_*x1 + x1)
<lambdifygenerated-15090>:2: RuntimeWarning: overflow encountered in exp
  return exp(_a1_**(x1**2 + x1)*_a3_*x1 + x1)
<lambdifygenerated-15091>:2: RuntimeWarning: overflow encountered in exp
  return exp(_a1_**(x1 + sin(x1)**2)*_a3_*x1 + x1)
<lambdifygenerated-15091>:2: RuntimeWarning: overflow encountered in multiply
  return exp(_a1_**(x1 + sin(x1)**2)*_a3_*x1 + x1)
<lambdifygenerated-15091>:2: RuntimeWarning: overflow encountered in power
  return exp(_a1_**(x1 + sin(x1)**2)*_a3_*x1 + x1)
/usr/local/lib/python3.10/dist-packages/scipy/optimize/_minpack_py.py:497: RuntimeWarning: overflow encountered in matmul
  cov_x = invR @ invR.T
<lambdifygenerated-15092>:2: RuntimeWarning: overflow encountered in power
  return exp(_a1_**(x1 + sin(x1)**2)*_a3_*x1 + x1)
<lambdifygenerated-15092>:2: RuntimeWarning: overflow encountered in multiply
  return exp(_a1_**(x1 + sin(x1)**2)*_a3_*x1 + x1)
<lambdifygenerated-15093>:2: RuntimeWarning: overflow encountered in power
  return exp(_a1_**(x1 + sin(x1**2)**2)*_a3_*x1 + x1)
<lambdifygenerated-15093>:2: RuntimeWarning: overflow encountered in multiply
  return exp(_a1_**(x1 + sin(x1**2)**2)*_a3_*x1 + x1)
<lambdifygenerated-15093>:2: RuntimeWarning: invalid value encountered in power
  return exp(_a1_**(x1 + sin(x1**2)**2)*_a3_*x1 + x1)
<lambdifygenerated-15094>:2: RuntimeWarning: overflow encountered in power
  return exp(_a1_**(x1 + sin(x1**2)**2)*_a3_*x1 + x1)
<lambdifygenerated-15094>:2: RuntimeWarning: overflow encountered in multiply
  return exp(_a1_**(x1 + sin(x1**2)**2)*_a3_*x1 + x1)
<lambdifygenerated-15095>:2: RuntimeWarning: overflow encountered in power
  return exp(_a1_**(x1 + sin(_a0_*x1)**2)*_a3_*x1 + x1)
<lambdifygenerated-15095>:2: RuntimeWarning: overflow encountered in multiply
  return exp(_a1_**(x1 + sin(_a0_*x1)**2)*_a3_*x1 + x1)
<lambdifygenerated-15095>:2: RuntimeWarning: overflow encountered in exp
  return exp(_a1_**(x1 + sin(_a0_*x1)**2)*_a3_*x1 + x1)
<lambdifygenerated-15096>:2: RuntimeWarning: overflow encountered in power
  return exp(_a1_**(x1 + sin(_a0_*x1)**2)*_a3_*x1 + x1)
<lambdifygenerated-15096>:2: RuntimeWarning: overflow encountered in multiply
  return exp(_a1_**(x1 + sin(_a0_*x1)**2)*_a3_*x1 + x1)
<lambdifygenerated-15097>:2: RuntimeWarning: overflow encountered in power
  return exp(_a1_**(x1 + sin(_a0_*x1)**2)*_a3_*x1 + x1)
<lambdifygenerated-15097>:2: RuntimeWarning: overflow encountered in multiply
  return exp(_a1_**(x1 + sin(_a0_*x1)**2)*_a3_*x1 + x1)
<lambdifygenerated-15098>:2: RuntimeWarning: overflow encountered in power
  return exp(_a1_**(x1 + sin(_a0_*x1)**2)*_a3_*x1 + x1)
<lambdifygenerated-15098>:2: RuntimeWarning: overflow encountered in multiply
  return exp(_a1_**(x1 + sin(_a0_*x1)**2)*_a3_*x1 + x1)
<lambdifygenerated-15099>:2: RuntimeWarning: overflow encountered in power
  return exp(_a1_**(x1 + sin(_a0_*x1)**2)*_a3_*x1 + x1)
<lambdifygenerated-15099>:2: RuntimeWarning: overflow encountered in multiply
  return exp(_a1_**(x1 + sin(_a0_*x1)**2)*_a3_*x1 + x1)
<lambdifygenerated-15100>:2: RuntimeWarning: overflow encountered in power
  return exp(_a1_**(x1 + sin(_a0_*x1)**2)*_a3_*x1 + x1)
<lambdifygenerated-15100>:2: RuntimeWarning: overflow encountered in multiply
  return exp(_a1_**(x1 + sin(_a0_*x1)**2)*_a3_*x1 + x1)
<lambdifygenerated-15101>:2: RuntimeWarning: overflow encountered in power
  return exp(_a0_*_a1_**(x1 + sin(_a0_*x1)**2)*_a3_ + x1)
<lambdifygenerated-15101>:2: RuntimeWarning: invalid value encountered in power
  return exp(_a0_*_a1_**(x1 + sin(_a0_*x1)**2)*_a3_ + x1)

interpolation

<lambdifygenerated-15103>:2: RuntimeWarning: overflow encountered in exp
  return exp(_a0_*_a1_**(x1 + sin(_a0_*x1)**2)*_a3_ + _a6_)
<lambdifygenerated-15107>:2: RuntimeWarning: overflow encountered in exp
  return exp(_a0_*_a1_**(x1 + sin(_a0_*x1)**2)*_a3_ + _a6_)

         x1         y  rep    ymodel      ybms
3745  0.997  0.428260  6.0  0.416007  0.412463
3746  0.998  0.428367  6.0  0.416004  0.412463
3747  0.998  0.428474  6.0  0.416000  0.412463
3748  0.999  0.428581  6.0  0.415997  0.412463

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.428794  6.0  0.415989  0.412463
3751  1.002  0.428901  6.0  0.415986  0.412463
3752  1.002  0.429008  6.0  0.415982  0.412463
3753  1.003  0.429115  6.0  0.415978  0.412463

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.173654  7.0  0.190042  0.184279
3746  0.998  0.173884  7.0  0.190413  0.184540
3747  0.998  0.174114  7.0  0.190784  0.184802
3748  0.999  0.174344  7.0  0.191156  0.185064

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.174804  7.0  0.191902  0.185588
3751  1.002  0.175034  7.0  0.192276  0.185850
3752  1.002  0.175264  7.0  0.192650  0.186113
3753  1.003  0.175494  7.0  0.193025  0.186375

3750
interpolation

/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-15205>:2: RuntimeWarning: invalid value encountered in power
  return abs(_a3_*tanh(_a0_ + _a1_*x1 + _a1_ + _a7_**3*x1**3 + x1**x1) + 2*x1)
<lambdifygenerated-15206>:2: RuntimeWarning: invalid value encountered in power
  return abs(_a3_*tanh(_a0_ + _a1_*x1 + _a1_ + _a7_**3*x1**3 + x1**x1) + 2*x1)

         x1         y  rep    ymodel      ybms
3745  0.997  0.261188  8.0  0.264327  0.269259
3746  0.998  0.261362  8.0  0.264614  0.269574
3747  0.998  0.261535  8.0  0.264901  0.269889
3748  0.999  0.261709  8.0  0.265188  0.270204

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.262056  8.0  0.265762  0.270834
3751  1.002  0.262229  8.0  0.266050  0.271149
3752  1.002  0.262402  8.0  0.266337  0.271464
3753  1.003  0.262576  8.0  0.266624  0.271780

3750

<lambdifygenerated-15245>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1
<lambdifygenerated-15246>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1

interpolation

         x1        y  rep    ymodel      ybms
3745  0.997  0.64259  9.0  0.645574  0.639126
3746  0.998  0.64247  9.0  0.645446  0.638938
3747  0.998  0.64235  9.0  0.645319  0.638750
3748  0.999  0.64223  9.0  0.645191  0.638562

extrapolation

         x1        y  rep    ymodel      ybms
3750  1.001  0.64199  9.0  0.644936  0.638186
3751  1.002  0.64187  9.0  0.644809  0.637997
3752  1.002  0.64175  9.0  0.644681  0.637809
3753  1.003  0.64163  9.0  0.644554  0.637620

3750
interpolation

<lambdifygenerated-15291>:2: RuntimeWarning: invalid value encountered in power
  return _a5_*x1*exp(-x1**x1)
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-15292>:2: RuntimeWarning: invalid value encountered in power
  return _a5_*x1*exp(-x1**x1)
<lambdifygenerated-15301>:2: RuntimeWarning: overflow encountered in power
  return _a5_*x1*exp(-_a5_**(x1 + sinh(_a2_*x1)))
<lambdifygenerated-15301>:2: RuntimeWarning: overflow encountered in sinh
  return _a5_*x1*exp(-_a5_**(x1 + sinh(_a2_*x1)))
<lambdifygenerated-15302>:2: RuntimeWarning: overflow encountered in sinh
  return _a5_*x1*exp(-_a5_**(x1 + sinh(_a2_*x1)))
<lambdifygenerated-15302>:2: RuntimeWarning: overflow encountered in power
  return _a5_*x1*exp(-_a5_**(x1 + sinh(_a2_*x1)))
<lambdifygenerated-15303>:2: RuntimeWarning: overflow encountered in sinh
  return _a5_*x1*exp(-_a5_**(x1 + sinh(_a2_*x1)))
<lambdifygenerated-15303>:2: RuntimeWarning: overflow encountered in power
  return _a5_*x1*exp(-_a5_**(x1 + sinh(_a2_*x1)))
<lambdifygenerated-15304>:2: RuntimeWarning: overflow encountered in sinh
  return _a5_*x1*exp(-_a5_**(x1 + sinh(_a2_*x1)))
<lambdifygenerated-15304>:2: RuntimeWarning: overflow encountered in power
  return _a5_*x1*exp(-_a5_**(x1 + sinh(_a2_*x1)))
<lambdifygenerated-15305>:2: RuntimeWarning: overflow encountered in sinh
  return _a5_*x1*exp(-_a5_**(_a1_ + sinh(_a2_*x1)))
<lambdifygenerated-15305>:2: RuntimeWarning: overflow encountered in power
  return _a5_*x1*exp(-_a5_**(_a1_ + sinh(_a2_*x1)))
<lambdifygenerated-15306>:2: RuntimeWarning: overflow encountered in sinh
  return _a5_*x1*exp(-_a5_**(_a1_ + sinh(_a2_*x1)))
<lambdifygenerated-15306>:2: RuntimeWarning: overflow encountered in power
  return _a5_*x1*exp(-_a5_**(_a1_ + sinh(_a2_*x1)))
<lambdifygenerated-15307>:2: RuntimeWarning: overflow encountered in sinh
  return _a5_**2*exp(-_a5_**(_a1_ + sinh(_a2_*x1)))
<lambdifygenerated-15307>:2: RuntimeWarning: overflow encountered in power
  return _a5_**2*exp(-_a5_**(_a1_ + sinh(_a2_*x1)))
<lambdifygenerated-15308>:2: RuntimeWarning: overflow encountered in sinh
  return _a5_**2*exp(-_a5_**(_a1_ + sinh(_a2_*x1)))
<lambdifygenerated-15309>:2: RuntimeWarning: overflow encountered in sinh
  return _a5_**2*exp(-_a5_**(_a1_ + sinh(_a2_*x1)))
<lambdifygenerated-15310>:2: RuntimeWarning: overflow encountered in sinh
  return _a5_**2*exp(-_a5_**(_a1_ + sinh(_a2_*x1)))
<lambdifygenerated-15311>:2: RuntimeWarning: overflow encountered in sinh
  return _a5_**2*exp(-_a5_**(_a1_ + sinh(_a2_*x1)))
<lambdifygenerated-15312>:2: RuntimeWarning: overflow encountered in sinh
  return _a5_**2*exp(-_a5_**(_a1_ + sinh(_a2_*x1)))

         x1         y  rep    ymodel      ybms
3745  0.997  0.360683  0.0  0.356418  0.358756
3746  0.998  0.360826  0.0  0.356549  0.358879
3747  0.998  0.360969  0.0  0.356680  0.359002
3748  0.999  0.361111  0.0  0.356812  0.359125

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.361396  0.0  0.357074  0.359369
3751  1.002  0.361539  0.0  0.357206  0.359492
3752  1.002  0.361681  0.0  0.357337  0.359614
3753  1.003  0.361824  0.0  0.357468  0.359736

3750

<lambdifygenerated-15317>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1
<lambdifygenerated-15318>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1

interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.875844  1.0  0.895599  0.914077
3746  0.998  0.875274  1.0  0.895488  0.914157
3747  0.998  0.874704  1.0  0.895378  0.914237
3748  0.999  0.874135  1.0  0.895267  0.914318

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.872995  1.0  0.895046  0.914483
3751  1.002  0.872426  1.0  0.894936  0.914566
3752  1.002  0.871856  1.0  0.894825  0.914650
3753  1.003  0.871287  1.0  0.894715  0.914734

3750
interpolation

<lambdifygenerated-15357>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1 + x1**x1) + x1
<lambdifygenerated-15358>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1 + x1**x1) + x1
<lambdifygenerated-15365>:2: RuntimeWarning: invalid value encountered in power
  return x1*(_a3_**tanh(_a0_ + x1) + x1) + x1
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-15375>:2: RuntimeWarning: invalid value encountered in power
  return x1*(_a3_**tanh(_a0_ + _a3_*x1**3) + _a4_) + x1

         x1         y  rep    ymodel      ybms
3745  0.997  0.997734  2.0  0.996411  0.998637
3746  0.998  0.997761  2.0  0.996404  0.998654
3747  0.998  0.997787  2.0  0.996398  0.998672
3748  0.999  0.997814  2.0  0.996391  0.998690

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.997867  2.0  0.996377  0.998726
3751  1.002  0.997894  2.0  0.996370  0.998744
3752  1.002  0.997921  2.0  0.996363  0.998762
3753  1.003  0.997948  2.0  0.996356  0.998780

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.689029  3.0  0.678911  0.678526
3746  0.998  0.688777  3.0  0.678564  0.678237
3747  0.998  0.688525  3.0  0.678218  0.677950
3748  0.999  0.688273  3.0  0.677872  0.677663

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.687768  3.0  0.677180  0.677093
3751  1.002  0.687516  3.0  0.676835  0.676810
3752  1.002  0.687264  3.0  0.676490  0.676529
3753  1.003  0.687012  3.0  0.676145  0.676248

3750

<lambdifygenerated-15435>:2: RuntimeWarning: invalid value encountered in power
  return _a1_*(_a7_ + x1**x1)**2 + _a6_
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-15436>:2: RuntimeWarning: invalid value encountered in power
  return _a1_*(_a7_ + x1**x1)**2 + _a6_

interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.661298  4.0  0.646382  0.653408
3746  0.998  0.661485  4.0  0.646523  0.653632
3747  0.998  0.661672  4.0  0.646664  0.653856
3748  0.999  0.661858  4.0  0.646805  0.654080

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.662232  4.0  0.647088  0.654532
3751  1.002  0.662419  4.0  0.647230  0.654759
3752  1.002  0.662605  4.0  0.647373  0.654987
3753  1.003  0.662792  4.0  0.647515  0.655216

3750
interpolation

<lambdifygenerated-15455>:2: RuntimeWarning: invalid value encountered in power
  return x1*sin(x1**x1) + x1
<lambdifygenerated-15456>:2: RuntimeWarning: invalid value encountered in power
  return x1*sin(x1**x1) + x1
<lambdifygenerated-15457>:2: RuntimeWarning: invalid value encountered in power
  return x1*sin((2*x1)**x1) + x1
<lambdifygenerated-15458>:2: RuntimeWarning: invalid value encountered in power
  return x1*sin((2*x1)**x1) + x1
<lambdifygenerated-15459>:2: RuntimeWarning: invalid value encountered in power
  return x1*sin((2*x1)**x1) + x1
<lambdifygenerated-15460>:2: RuntimeWarning: invalid value encountered in power
  return x1*sin((2*x1)**x1) + x1
<lambdifygenerated-15461>:2: RuntimeWarning: invalid value encountered in power
  return x1*sin((_a2_ + x1)**x1) + x1
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-15462>:2: RuntimeWarning: invalid value encountered in power
  return x1*sin((_a2_ + x1)**x1) + x1
<lambdifygenerated-15463>:2: RuntimeWarning: invalid value encountered in power
  return x1*sin((_a2_ + x1)**x1) + x1
<lambdifygenerated-15464>:2: RuntimeWarning: invalid value encountered in power
  return x1*sin((_a2_ + x1)**x1) + x1
<lambdifygenerated-15465>:2: RuntimeWarning: invalid value encountered in power
  return x1**2*sin((_a2_ + x1)**x1) + x1
<lambdifygenerated-15466>:2: RuntimeWarning: invalid value encountered in power
  return x1**2*sin((_a2_ + x1)**x1) + x1
<lambdifygenerated-15467>:2: RuntimeWarning: invalid value encountered in power
  return _a0_*x1*sin((_a2_ + x1)**x1) + x1
<lambdifygenerated-15468>:2: RuntimeWarning: invalid value encountered in power
  return _a0_*x1*sin((_a2_ + x1)**x1) + x1
<lambdifygenerated-15469>:2: RuntimeWarning: invalid value encountered in power
  return _a0_*x1*sin((_a2_ + x1)**x1) + x1
<lambdifygenerated-15470>:2: RuntimeWarning: invalid value encountered in power
  return _a0_*x1*sin((_a2_ + x1)**x1) + x1
<lambdifygenerated-15471>:2: RuntimeWarning: invalid value encountered in power
  return _a0_*x1*sin((_a2_ + x1)**x1) + _a4_
<lambdifygenerated-15472>:2: RuntimeWarning: invalid value encountered in power
  return _a0_*x1*sin((_a2_ + x1)**x1) + _a4_
<lambdifygenerated-15473>:2: RuntimeWarning: invalid value encountered in power
  return _a0_*x1*sin((_a2_ + x1)**x1) + _a4_
<lambdifygenerated-15474>:2: RuntimeWarning: invalid value encountered in power
  return _a0_*x1*sin((_a2_ + x1)**x1) + _a4_
<lambdifygenerated-15475>:2: RuntimeWarning: invalid value encountered in power
  return _a0_*x1*sin((_a2_ + x1)**x1) + _a4_
<lambdifygenerated-15476>:2: RuntimeWarning: invalid value encountered in power
  return _a0_*x1*sin((_a2_ + x1)**x1) + _a4_

         x1         y  rep    ymodel      ybms
3745  0.997  0.956369  5.0  0.954807  0.960451
3746  0.998  0.956259  5.0  0.954654  0.960403
3747  0.998  0.956150  5.0  0.954502  0.960356
3748  0.999  0.956040  5.0  0.954349  0.960311

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.955822  5.0  0.954042  0.960223
3751  1.002  0.955712  5.0  0.953889  0.960181
3752  1.002  0.955603  5.0  0.953735  0.960140
3753  1.003  0.955493  5.0  0.953581  0.960100

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.428260  6.0  0.429182  0.412593
3746  0.998  0.428367  6.0  0.429289  0.412593
3747  0.998  0.428474  6.0  0.429397  0.412593
3748  0.999  0.428581  6.0  0.429505  0.412593

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.428794  6.0  0.429721  0.412593
3751  1.002  0.428901  6.0  0.429829  0.412593
3752  1.002  0.429008  6.0  0.429938  0.412593
3753  1.003  0.429115  6.0  0.430046  0.412593

3750
interpolation

         x1         y  rep   ymodel      ybms
3745  0.997  0.173654  7.0  0.18156  0.179067
3746  0.998  0.173884  7.0  0.18187  0.179354
3747  0.998  0.174114  7.0  0.18218  0.179641
3748  0.999  0.174344  7.0  0.18249  0.179928

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.174804  7.0  0.183111  0.180503
3751  1.002  0.175034  7.0  0.183422  0.180791
3752  1.002  0.175264  7.0  0.183733  0.181078
3753  1.003  0.175494  7.0  0.184044  0.181366

3750

<lambdifygenerated-15563>:2: RuntimeWarning: invalid value encountered in power
  return x1 + x1**x1/x1
<lambdifygenerated-15564>:2: RuntimeWarning: invalid value encountered in power
  return x1 + x1**x1/x1
<lambdifygenerated-15565>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (2*x1)**x1/x1
<lambdifygenerated-15566>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (2*x1)**x1/x1
<lambdifygenerated-15567>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (_a5_ + x1)**x1/x1
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-15568>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (_a5_ + x1)**x1/x1
<lambdifygenerated-15569>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (_a5_ - x1)**x1/x1
<lambdifygenerated-15570>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (_a5_ - x1)**x1/x1
<lambdifygenerated-15571>:2: RuntimeWarning: divide by zero encountered in power
  return x1 + (_a5_ - 1)**x1/x1
<lambdifygenerated-15572>:2: RuntimeWarning: divide by zero encountered in power
  return x1 + (_a5_ - 1)**x1/x1
<lambdifygenerated-15573>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (_a5_ - x1)**x1/x1
<lambdifygenerated-15574>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (_a5_ - x1)**x1/x1
<lambdifygenerated-15575>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (_a5_ - x1**2)**x1/x1
<lambdifygenerated-15576>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (_a5_ - x1**2)**x1/x1
<lambdifygenerated-15577>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (_a5_ - x1**4)**x1/x1
<lambdifygenerated-15578>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (_a5_ - x1**4)**x1/x1
<lambdifygenerated-15579>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (_a5_ - x1*tanh(x1)**3)**x1/x1
<lambdifygenerated-15580>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (_a5_ - x1*tanh(x1)**3)**x1/x1
<lambdifygenerated-15581>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (_a5_ - x1*tanh(x1**2)**3)**x1/x1
<lambdifygenerated-15582>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (_a5_ - x1*tanh(x1**2)**3)**x1/x1
<lambdifygenerated-15583>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (_a5_ - x1*tanh(_a7_*x1)**3)**x1/x1
<lambdifygenerated-15584>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (_a5_ - x1*tanh(_a7_*x1)**3)**x1/x1
<lambdifygenerated-15585>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (_a5_ - x1*tanh(2*_a7_*x1)**3)**x1/x1
<lambdifygenerated-15586>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (_a5_ - x1*tanh(2*_a7_*x1)**3)**x1/x1
<lambdifygenerated-15587>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (_a5_ - x1*tanh(_a7_*(_a2_ + x1))**3)**x1/x1
<lambdifygenerated-15588>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (_a5_ - x1*tanh(_a7_*(_a2_ + x1))**3)**x1/x1
<lambdifygenerated-15589>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (_a5_ - x1*tanh(_a7_*(_a2_ + x1))**3)**x1/x1
<lambdifygenerated-15590>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (_a5_ - x1*tanh(_a7_*(_a2_ + x1))**3)**x1/x1
<lambdifygenerated-15591>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (-_a2_*tanh(_a7_*(_a2_ + x1))**3 + _a5_)**x1/x1
<lambdifygenerated-15593>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (-_a2_*_a3_*tanh(_a7_*(_a2_ + x1))**3/x1 + _a5_)**x1/x1
<lambdifygenerated-15594>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (-_a2_*_a3_*tanh(_a7_*(_a2_ + x1))**3/x1 + _a5_)**x1/x1
<lambdifygenerated-15595>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (-_a2_*_a3_*exp(-x1)*tanh(_a7_*(_a2_ + x1))**3 + _a5_)**x1/x1
<lambdifygenerated-15596>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (-_a2_*_a3_*exp(-x1)*tanh(_a7_*(_a2_ + x1))**3 + _a5_)**x1/x1
<lambdifygenerated-15597>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (-_a2_*_a3_*exp(-x1)*tanh(_a7_*(_a2_ + x1))**3 + _a5_)**x1/x1
<lambdifygenerated-15598>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (-_a2_*_a3_*exp(-x1)*tanh(_a7_*(_a2_ + x1))**3 + _a5_)**x1/x1
<lambdifygenerated-15599>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (-_a2_*_a3_*exp(-x1)*tanh(_a7_*(_a2_ + x1))**3 + _a5_)**_a0_/x1
<lambdifygenerated-15601>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (-_a2_*_a3_*exp(-x1)*tanh(_a7_*(_a2_ + x1))**3 + _a5_)**_a0_/x1**2
<lambdifygenerated-15603>:2: RuntimeWarning: invalid value encountered in power
  return x1 + x1**(-x1)*(-_a2_*_a3_*exp(-x1)*tanh(_a7_*(_a2_ + x1))**3 + _a5_)**_a0_/x1
<lambdifygenerated-15604>:2: RuntimeWarning: invalid value encountered in power
  return x1 + x1**(-x1)*(-_a2_*_a3_*exp(-x1)*tanh(_a7_*(_a2_ + x1))**3 + _a5_)**_a0_/x1
<lambdifygenerated-15605>:2: RuntimeWarning: invalid value encountered in power
  return x1 + _a1_**(-x1)*(-_a2_*_a3_*exp(-x1)*tanh(_a7_*(_a2_ + x1))**3 + _a5_)**_a0_/x1
<lambdifygenerated-15607>:2: RuntimeWarning: invalid value encountered in power
  return x1 + _a1_**(-x1**2)*(-_a2_*_a3_*exp(-x1)*tanh(_a7_*(_a2_ + x1))**3 + _a5_)**_a0_/x1
<lambdifygenerated-15609>:2: RuntimeWarning: invalid value encountered in power
  return x1 + _a1_**(-_a5_*x1)*(-_a2_*_a3_*exp(-x1)*tanh(_a7_*(_a2_ + x1))**3 + _a5_)**_a0_/x1
<lambdifygenerated-15613>:2: RuntimeWarning: invalid value encountered in power
  return x1 + _a1_**(-_a5_*x1)*(-_a2_*_a3_*exp(-x1)*tanh(_a7_*(_a2_ + x1))**3 + _a5_)**_a0_/_a0_
<lambdifygenerated-15615>:2: RuntimeWarning: invalid value encountered in power
  return _a3_ + _a1_**(-_a5_*x1)*(-_a2_*_a3_*exp(-x1)*tanh(_a7_*(_a2_ + x1))**3 + _a5_)**_a0_/_a0_
<lambdifygenerated-15619>:2: RuntimeWarning: invalid value encountered in power
  return _a3_ + _a1_**(-_a5_*x1)*(-_a2_*_a3_*exp(-x1)*tanh(_a7_*(_a2_ + x1))**3 + _a5_)**_a0_/_a0_

interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.261188  8.0  0.265434  0.271280
3746  0.998  0.261362  8.0  0.265674  0.271571
3747  0.998  0.261535  8.0  0.265915  0.271862
3748  0.999  0.261709  8.0  0.266155  0.272153

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.262056  8.0  0.266634  0.272736
3751  1.002  0.262229  8.0  0.266874  0.273027
3752  1.002  0.262402  8.0  0.267113  0.273318
3753  1.003  0.262576  8.0  0.267353  0.273609

3750

<lambdifygenerated-15627>:2: RuntimeWarning: invalid value encountered in power
  return x1*x1**x1
<lambdifygenerated-15628>:2: RuntimeWarning: invalid value encountered in power
  return x1*x1**x1
<lambdifygenerated-15629>:2: RuntimeWarning: invalid value encountered in power
  return x1*(2*x1)**x1
<lambdifygenerated-15630>:2: RuntimeWarning: invalid value encountered in power
  return x1*(2*x1)**x1
<lambdifygenerated-15631>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1**2 + x1)**x1
<lambdifygenerated-15632>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1**2 + x1)**x1
<lambdifygenerated-15633>:2: RuntimeWarning: invalid value encountered in power
  return x1*(_a3_*x1 + x1)**x1
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-15634>:2: RuntimeWarning: invalid value encountered in power
  return x1*(_a3_*x1 + x1)**x1
<lambdifygenerated-15635>:2: RuntimeWarning: invalid value encountered in power
  return x1*(_a3_*cos(x1) + x1)**x1
<lambdifygenerated-15636>:2: RuntimeWarning: invalid value encountered in power
  return x1*(_a3_*cos(x1) + x1)**x1
<lambdifygenerated-15637>:2: RuntimeWarning: invalid value encountered in power
  return x1*(_a3_*cos(x1) + x1)**x1
<lambdifygenerated-15638>:2: RuntimeWarning: invalid value encountered in power
  return x1*(_a3_*cos(x1) + x1)**x1
<lambdifygenerated-15641>:2: RuntimeWarning: invalid value encountered in power
  return x1*(_a1_ + _a3_*cos(x1))**(x1**2)
<lambdifygenerated-15643>:2: RuntimeWarning: invalid value encountered in power
  return x1*(_a1_ + _a3_*cos(x1))**(2*x1**2)
<lambdifygenerated-15647>:2: RuntimeWarning: invalid value encountered in power
  return x1*(_a1_ + _a3_*cos(x1))**(x1*(_a5_ + x1))
<lambdifygenerated-15649>:2: RuntimeWarning: invalid value encountered in power
  return x1*(_a1_ + _a3_*cos(x1))**(_a6_*(_a5_ + x1))
<lambdifygenerated-15651>:2: RuntimeWarning: invalid value encountered in power
  return _a4_*(_a1_ + _a3_*cos(x1))**(_a6_*(_a5_ + x1))

interpolation

         x1        y  rep    ymodel      ybms
3745  0.997  0.64259  9.0  0.647165  0.652536
3746  0.998  0.64247  9.0  0.647051  0.652444
3747  0.998  0.64235  9.0  0.646936  0.652352
3748  0.999  0.64223  9.0  0.646822  0.652260

extrapolation

         x1        y  rep    ymodel      ybms
3750  1.001  0.64199  9.0  0.646593  0.652077
3751  1.002  0.64187  9.0  0.646480  0.651986
3752  1.002  0.64175  9.0  0.646366  0.651894
3753  1.003  0.64163  9.0  0.646252  0.651803

3750
interpolation

<lambdifygenerated-15665>:2: RuntimeWarning: invalid value encountered in power
  return x1**2*x1**x1
<lambdifygenerated-15666>:2: RuntimeWarning: invalid value encountered in power
  return x1**2*x1**x1
<lambdifygenerated-15669>:2: RuntimeWarning: invalid value encountered in power
  return _a5_**(x1**x1)*x1**2
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-15670>:2: RuntimeWarning: invalid value encountered in power
  return _a5_**(x1**x1)*x1**2
<lambdifygenerated-15671>:2: RuntimeWarning: invalid value encountered in power
  return _a5_**(_a3_**x1)*x1**2

         x1         y  rep    ymodel      ybms
3745  0.997  0.360683  0.0  0.358350  0.366168
3746  0.998  0.360826  0.0  0.358486  0.366362
3747  0.998  0.360969  0.0  0.358621  0.366557
3748  0.999  0.361111  0.0  0.358757  0.366751

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.361396  0.0  0.359028  0.367141
3751  1.002  0.361539  0.0  0.359163  0.367336
3752  1.002  0.361681  0.0  0.359298  0.367531
3753  1.003  0.361824  0.0  0.359434  0.367727

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.875844  1.0  0.886688  0.883360
3746  0.998  0.875274  1.0  0.886569  0.883209
3747  0.998  0.874704  1.0  0.886451  0.883058
3748  0.999  0.874135  1.0  0.886332  0.882907

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.872995  1.0  0.886095  0.882604
3751  1.002  0.872426  1.0  0.885977  0.882453
3752  1.002  0.871856  1.0  0.885859  0.882302
3753  1.003  0.871287  1.0  0.885740  0.882150

3750

<lambdifygenerated-15741>:2: RuntimeWarning: invalid value encountered in power
  return cos(x1*(x1 + sin(_a0_*x1**x1)) + x1)
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-15742>:2: RuntimeWarning: invalid value encountered in power
  return cos(x1*(x1 + sin(_a0_*x1**x1)) + x1)
<lambdifygenerated-15747>:2: RuntimeWarning: invalid value encountered in power
  return cos(x1*(_a7_ + sin(_a0_*_a2_**x1)) + x1)
<lambdifygenerated-15749>:2: RuntimeWarning: invalid value encountered in power
  return cos(_a5_*(_a7_ + sin(_a0_*_a2_**x1)) + x1)
<lambdifygenerated-15751>:2: RuntimeWarning: invalid value encountered in power
  return cos(_a5_*(_a7_ + sin(_a0_*_a2_**x1)) + x1**2)

interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.997734  2.0  0.991987  0.996790
3746  0.998  0.997761  2.0  0.991959  0.996813
3747  0.998  0.997787  2.0  0.991932  0.996836
3748  0.999  0.997814  2.0  0.991904  0.996858

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.997867  2.0  0.991848  0.996904
3751  1.002  0.997894  2.0  0.991820  0.996927
3752  1.002  0.997921  2.0  0.991792  0.996950
3753  1.003  0.997948  2.0  0.991763  0.996973

3750
interpolation

<lambdifygenerated-15771>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1
<lambdifygenerated-15772>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1

         x1         y  rep    ymodel      ybms
3745  0.997  0.689029  3.0  0.687829  0.675107
3746  0.998  0.688777  3.0  0.687522  0.674607
3747  0.998  0.688525  3.0  0.687215  0.674106
3748  0.999  0.688273  3.0  0.686909  0.673605

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.687768  3.0  0.686296  0.672602
3751  1.002  0.687516  3.0  0.685991  0.672099
3752  1.002  0.687264  3.0  0.685686  0.671596
3753  1.003  0.687012  3.0  0.685381  0.671092

3750

<lambdifygenerated-15799>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (x1 + x1**x1/x1)**2
<lambdifygenerated-15800>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (x1 + x1**x1/x1)**2

interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.661298  4.0  0.659993  0.657409
3746  0.998  0.661485  4.0  0.660190  0.657647
3747  0.998  0.661672  4.0  0.660386  0.657885
3748  0.999  0.661858  4.0  0.660583  0.658124

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.662232  4.0  0.660977  0.658605
3751  1.002  0.662419  4.0  0.661174  0.658846
3752  1.002  0.662605  4.0  0.661371  0.659088
3753  1.003  0.662792  4.0  0.661568  0.659331

3750
interpolation

<lambdifygenerated-15829>:2: RuntimeWarning: invalid value encountered in power
  return cos(_a6_ + _a7_*x1**x1)
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-15830>:2: RuntimeWarning: invalid value encountered in power
  return cos(_a6_ + _a7_*x1**x1)
<lambdifygenerated-15831>:2: RuntimeWarning: invalid value encountered in power
  return cos(_a6_ + _a6_**x1*_a7_)
<lambdifygenerated-15832>:2: RuntimeWarning: invalid value encountered in power
  return cos(_a6_ + _a6_**x1*_a7_)
<lambdifygenerated-15833>:2: RuntimeWarning: invalid value encountered in power
  return cos(_a6_ + _a6_**x1*_a7_)
<lambdifygenerated-15834>:2: RuntimeWarning: invalid value encountered in power
  return cos(_a6_ + _a6_**x1*_a7_)
<lambdifygenerated-15835>:2: RuntimeWarning: invalid value encountered in power
  return cos(_a6_ + _a6_**x1*_a7_)
<lambdifygenerated-15836>:2: RuntimeWarning: invalid value encountered in power
  return cos(_a6_ + _a6_**x1*_a7_)
<lambdifygenerated-15837>:2: RuntimeWarning: invalid value encountered in power
  return cos(_a6_ + _a6_**x1*_a7_)
<lambdifygenerated-15838>:2: RuntimeWarning: invalid value encountered in power
  return cos(_a6_ + _a6_**x1*_a7_)

         x1         y  rep    ymodel      ybms
3745  0.997  0.956369  5.0  0.946915  0.941909
3746  0.998  0.956259  5.0  0.946718  0.941629
3747  0.998  0.956150  5.0  0.946520  0.941348
3748  0.999  0.956040  5.0  0.946323  0.941065

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.955822  5.0  0.945926  0.940497
3751  1.002  0.955712  5.0  0.945728  0.940211
3752  1.002  0.955603  5.0  0.945529  0.939925
3753  1.003  0.955493  5.0  0.945330  0.939637

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.428260  6.0  0.424641  0.413179
3746  0.998  0.428367  6.0  0.424701  0.413179
3747  0.998  0.428474  6.0  0.424760  0.413179
3748  0.999  0.428581  6.0  0.424820  0.413179

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.428794  6.0  0.424941  0.413179
3751  1.002  0.428901  6.0  0.425001  0.413179
3752  1.002  0.429008  6.0  0.425062  0.413179
3753  1.003  0.429115  6.0  0.425123  0.413179

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.173654  7.0  0.170939  0.173433
3746  0.998  0.173884  7.0  0.171216  0.173708
3747  0.998  0.174114  7.0  0.171493  0.173984
3748  0.999  0.174344  7.0  0.171769  0.174259

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.174804  7.0  0.172323  0.174811
3751  1.002  0.175034  7.0  0.172600  0.175086
3752  1.002  0.175264  7.0  0.172877  0.175362
3753  1.003  0.175494  7.0  0.173154  0.175638

3750

<lambdifygenerated-15937>:2: RuntimeWarning: invalid value encountered in power
  return x1 + x1**x1
<lambdifygenerated-15938>:2: RuntimeWarning: invalid value encountered in power
  return x1 + x1**x1
<lambdifygenerated-15939>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (2*x1)**x1
<lambdifygenerated-15940>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (2*x1)**x1
<lambdifygenerated-15941>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (x1**3 + x1)**x1
<lambdifygenerated-15942>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (x1**3 + x1)**x1
<lambdifygenerated-15943>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (x1 + 1)**x1
<lambdifygenerated-15944>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (x1 + 1)**x1
<lambdifygenerated-15951>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (x1 + (x1 + sin(x1**2)**3)**3/x1**3)**x1
<lambdifygenerated-15952>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (x1 + (x1 + sin(x1**2)**3)**3/x1**3)**x1
<lambdifygenerated-15953>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (x1 + (x1 + sin(2*x1**2)**3)**3/x1**3)**x1
<lambdifygenerated-15954>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (x1 + (x1 + sin(2*x1**2)**3)**3/x1**3)**x1
<lambdifygenerated-15955>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (x1 + (x1 + sin(x1*(x1 + tanh(x1)))**3)**3/x1**3)**x1
<lambdifygenerated-15956>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (x1 + (x1 + sin(x1*(x1 + tanh(x1)))**3)**3/x1**3)**x1
<lambdifygenerated-15957>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (x1 + (x1 + sin(x1*(x1 + tanh(x1)))**3)**3/x1**3)**x1
<lambdifygenerated-15958>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (x1 + (x1 + sin(x1*(x1 + tanh(x1)))**3)**3/x1**3)**x1
<lambdifygenerated-15959>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (x1 + (x1 + sin(x1*(_a5_ + tanh(x1)))**3)**3/x1**3)**x1
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-15960>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (x1 + (x1 + sin(x1*(_a5_ + tanh(x1)))**3)**3/x1**3)**x1
<lambdifygenerated-15961>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (x1 + (x1 + sin(_a2_*(_a5_ + tanh(x1)))**3)**3/x1**3)**x1
<lambdifygenerated-15962>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (x1 + (x1 + sin(_a2_*(_a5_ + tanh(x1)))**3)**3/x1**3)**x1
<lambdifygenerated-15963>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (x1 + (_a0_ + sin(_a2_*(_a5_ + tanh(x1)))**3)**3/x1**3)**x1
<lambdifygenerated-15964>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (x1 + (_a0_ + sin(_a2_*(_a5_ + tanh(x1)))**3)**3/x1**3)**x1
<lambdifygenerated-15965>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (x1 + (_a0_ + sin(_a2_*(_a5_ + tanh(x1)))**3)**3/_a1_**3)**x1
<lambdifygenerated-15966>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (x1 + (_a0_ + sin(_a2_*(_a5_ + tanh(x1)))**3)**3/_a1_**3)**x1
<lambdifygenerated-15967>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (x1**2 + (_a0_ + sin(_a2_*(_a5_ + tanh(x1)))**3)**3/_a1_**3)**x1

interpolation

<lambdifygenerated-15971>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (x1**2 + (_a0_ + sin(_a2_*(_a5_ + tanh(x1)))**3)**3/_a1_**3)**_a5_
<lambdifygenerated-15973>:2: RuntimeWarning: invalid value encountered in power
  return _a6_ + (x1**2 + (_a0_ + sin(_a2_*(_a5_ + tanh(x1)))**3)**3/_a1_**3)**_a5_

         x1         y  rep    ymodel      ybms
3745  0.997  0.261188  8.0  0.267728  0.245583
3746  0.998  0.261362  8.0  0.267972  0.245730
3747  0.998  0.261535  8.0  0.268216  0.245876
3748  0.999  0.261709  8.0  0.268459  0.246023

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.262056  8.0  0.268945  0.246315
3751  1.002  0.262229  8.0  0.269188  0.246461
3752  1.002  0.262402  8.0  0.269430  0.246607
3753  1.003  0.262576  8.0  0.269672  0.246752

3750
interpolation

<lambdifygenerated-15983>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1
<lambdifygenerated-15984>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1
<lambdifygenerated-15987>:2: RuntimeWarning: invalid value encountered in log
  return (x1*log(x1))**x1
<lambdifygenerated-15987>:2: RuntimeWarning: invalid value encountered in power
  return (x1*log(x1))**x1
<lambdifygenerated-15988>:2: RuntimeWarning: invalid value encountered in log
  return (x1*log(x1))**x1
<lambdifygenerated-15988>:2: RuntimeWarning: invalid value encountered in power
  return (x1*log(x1))**x1
<lambdifygenerated-15989>:2: RuntimeWarning: invalid value encountered in log
  return (x1*log(2*x1))**x1
<lambdifygenerated-15989>:2: RuntimeWarning: invalid value encountered in power
  return (x1*log(2*x1))**x1
<lambdifygenerated-15990>:2: RuntimeWarning: invalid value encountered in log
  return (x1*log(2*x1))**x1
<lambdifygenerated-15990>:2: RuntimeWarning: invalid value encountered in power
  return (x1*log(2*x1))**x1
<lambdifygenerated-15991>:2: RuntimeWarning: invalid value encountered in log
  return (x1*log(2*x1))**x1
<lambdifygenerated-15991>:2: RuntimeWarning: invalid value encountered in power
  return (x1*log(2*x1))**x1
<lambdifygenerated-15992>:2: RuntimeWarning: invalid value encountered in log
  return (x1*log(2*x1))**x1
<lambdifygenerated-15992>:2: RuntimeWarning: invalid value encountered in power
  return (x1*log(2*x1))**x1
<lambdifygenerated-15993>:2: RuntimeWarning: invalid value encountered in log
  return (x1*log(_a3_ + x1))**x1
<lambdifygenerated-15993>:2: RuntimeWarning: invalid value encountered in power
  return (x1*log(_a3_ + x1))**x1
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-15994>:2: RuntimeWarning: invalid value encountered in log
  return (x1*log(_a3_ + x1))**x1
<lambdifygenerated-15995>:2: RuntimeWarning: invalid value encountered in log
  return (_a2_*log(_a3_ + x1))**x1
<lambdifygenerated-15995>:2: RuntimeWarning: invalid value encountered in power
  return (_a2_*log(_a3_ + x1))**x1
<lambdifygenerated-15996>:2: RuntimeWarning: invalid value encountered in log
  return (_a2_*log(_a3_ + x1))**x1
<lambdifygenerated-15996>:2: RuntimeWarning: invalid value encountered in power
  return (_a2_*log(_a3_ + x1))**x1
<lambdifygenerated-15997>:2: RuntimeWarning: invalid value encountered in log
  return (_a2_*log(_a3_ + x1))**(2*x1)
<lambdifygenerated-15997>:2: RuntimeWarning: invalid value encountered in power
  return (_a2_*log(_a3_ + x1))**(2*x1)
<lambdifygenerated-15998>:2: RuntimeWarning: invalid value encountered in log
  return (_a2_*log(_a3_ + x1))**(2*x1)
<lambdifygenerated-15998>:2: RuntimeWarning: invalid value encountered in power
  return (_a2_*log(_a3_ + x1))**(2*x1)
<lambdifygenerated-15999>:2: RuntimeWarning: invalid value encountered in log
  return (_a2_*log(_a3_ + x1))**(x1 + tanh(x1))
<lambdifygenerated-15999>:2: RuntimeWarning: invalid value encountered in power
  return (_a2_*log(_a3_ + x1))**(x1 + tanh(x1))
<lambdifygenerated-16000>:2: RuntimeWarning: invalid value encountered in log
  return (_a2_*log(_a3_ + x1))**(x1 + tanh(x1))
<lambdifygenerated-16000>:2: RuntimeWarning: invalid value encountered in power
  return (_a2_*log(_a3_ + x1))**(x1 + tanh(x1))
<lambdifygenerated-16001>:2: RuntimeWarning: invalid value encountered in log
  return (_a2_*log(_a3_ + x1))**(x1 + tanh(x1**2))
<lambdifygenerated-16001>:2: RuntimeWarning: invalid value encountered in power
  return (_a2_*log(_a3_ + x1))**(x1 + tanh(x1**2))
<lambdifygenerated-16002>:2: RuntimeWarning: invalid value encountered in log
  return (_a2_*log(_a3_ + x1))**(x1 + tanh(x1**2))
<lambdifygenerated-16002>:2: RuntimeWarning: invalid value encountered in power
  return (_a2_*log(_a3_ + x1))**(x1 + tanh(x1**2))
<lambdifygenerated-16003>:2: RuntimeWarning: invalid value encountered in log
  return (_a2_*log(_a3_ + x1))**(x1 + tanh(_a7_*x1))
<lambdifygenerated-16003>:2: RuntimeWarning: invalid value encountered in power
  return (_a2_*log(_a3_ + x1))**(x1 + tanh(_a7_*x1))
<lambdifygenerated-16004>:2: RuntimeWarning: invalid value encountered in log
  return (_a2_*log(_a3_ + x1))**(x1 + tanh(_a7_*x1))
<lambdifygenerated-16004>:2: RuntimeWarning: invalid value encountered in power
  return (_a2_*log(_a3_ + x1))**(x1 + tanh(_a7_*x1))
<lambdifygenerated-16005>:2: RuntimeWarning: invalid value encountered in log
  return (_a2_*log(_a3_ + x1))**(x1 + tanh(_a7_*x1))
<lambdifygenerated-16005>:2: RuntimeWarning: invalid value encountered in power
  return (_a2_*log(_a3_ + x1))**(x1 + tanh(_a7_*x1))
<lambdifygenerated-16006>:2: RuntimeWarning: invalid value encountered in log
  return (_a2_*log(_a3_ + x1))**(x1 + tanh(_a7_*x1))
<lambdifygenerated-16006>:2: RuntimeWarning: invalid value encountered in power
  return (_a2_*log(_a3_ + x1))**(x1 + tanh(_a7_*x1))
<lambdifygenerated-16007>:2: RuntimeWarning: invalid value encountered in log
  return (_a2_*log(_a3_ + x1))**(_a6_ + tanh(_a7_*x1))
<lambdifygenerated-16007>:2: RuntimeWarning: invalid value encountered in power
  return (_a2_*log(_a3_ + x1))**(_a6_ + tanh(_a7_*x1))
<lambdifygenerated-16008>:2: RuntimeWarning: invalid value encountered in log
  return (_a2_*log(_a3_ + x1))**(_a6_ + tanh(_a7_*x1))
<lambdifygenerated-16008>:2: RuntimeWarning: invalid value encountered in power
  return (_a2_*log(_a3_ + x1))**(_a6_ + tanh(_a7_*x1))
<lambdifygenerated-16009>:2: RuntimeWarning: invalid value encountered in log
  return (_a2_*log(_a3_ + x1))**(_a6_ + tanh(_a7_*x1))
<lambdifygenerated-16009>:2: RuntimeWarning: invalid value encountered in power
  return (_a2_*log(_a3_ + x1))**(_a6_ + tanh(_a7_*x1))
<lambdifygenerated-16010>:2: RuntimeWarning: invalid value encountered in log
  return (_a2_*log(_a3_ + x1))**(_a6_ + tanh(_a7_*x1))
<lambdifygenerated-16010>:2: RuntimeWarning: invalid value encountered in power
  return (_a2_*log(_a3_ + x1))**(_a6_ + tanh(_a7_*x1))
<lambdifygenerated-16011>:2: RuntimeWarning: invalid value encountered in log
  return (_a2_*log(_a3_ + x1))**(_a6_ + tanh(_a7_*x1))
<lambdifygenerated-16011>:2: RuntimeWarning: invalid value encountered in power
  return (_a2_*log(_a3_ + x1))**(_a6_ + tanh(_a7_*x1))
<lambdifygenerated-16012>:2: RuntimeWarning: invalid value encountered in log
  return (_a2_*log(_a3_ + x1))**(_a6_ + tanh(_a7_*x1))
<lambdifygenerated-16012>:2: RuntimeWarning: invalid value encountered in power
  return (_a2_*log(_a3_ + x1))**(_a6_ + tanh(_a7_*x1))

         x1        y  rep    ymodel      ybms
3745  0.997  0.64259  9.0  0.644908  0.646139
3746  0.998  0.64247  9.0  0.644804  0.646014
3747  0.998  0.64235  9.0  0.644701  0.645889
3748  0.999  0.64223  9.0  0.644598  0.645763

extrapolation

         x1        y  rep    ymodel      ybms
3750  1.001  0.64199  9.0  0.644393  0.645513
3751  1.002  0.64187  9.0  0.644290  0.645388
3752  1.002  0.64175  9.0  0.644188  0.645263
3753  1.003  0.64163  9.0  0.644087  0.645138

3750

<lambdifygenerated-16021>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1
<lambdifygenerated-16022>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1
<lambdifygenerated-16025>:2: RuntimeWarning: invalid value encountered in power
  return _a7_**exp(x1)
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-16033>:2: RuntimeWarning: invalid value encountered in power
  return _a7_**exp(_a3_*x1)*x1**x1/x1
<lambdifygenerated-16034>:2: RuntimeWarning: invalid value encountered in power
  return _a7_**exp(_a3_*x1)*x1**x1/x1
<lambdifygenerated-16035>:2: RuntimeWarning: invalid value encountered in power
  return _a6_**x1*_a7_**exp(_a3_*x1)/x1
<lambdifygenerated-16035>:2: RuntimeWarning: overflow encountered in exp
  return _a6_**x1*_a7_**exp(_a3_*x1)/x1
<lambdifygenerated-16039>:2: RuntimeWarning: invalid value encountered in power
  return _a6_**x1*_a7_**exp(_a3_*x1)/_a4_

interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.360683  0.0  0.354903  0.365161
3746  0.998  0.360826  0.0  0.355009  0.365322
3747  0.998  0.360969  0.0  0.355114  0.365484
3748  0.999  0.361111  0.0  0.355219  0.365645

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.361396  0.0  0.355430  0.365967
3751  1.002  0.361539  0.0  0.355535  0.366129
3752  1.002  0.361681  0.0  0.355640  0.366290
3753  1.003  0.361824  0.0  0.355745  0.366452

3750
interpolation

<lambdifygenerated-16055>:2: RuntimeWarning: invalid value encountered in power
  return _a2_*x1**x1 + x1
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-16056>:2: RuntimeWarning: invalid value encountered in power
  return _a2_*x1**x1 + x1

         x1         y  rep    ymodel      ybms
3745  0.997  0.875844  1.0  0.900956  0.927800
3746  0.998  0.875274  1.0  0.900872  0.927847
3747  0.998  0.874704  1.0  0.900789  0.927894
3748  0.999  0.874135  1.0  0.900706  0.927941

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.872995  1.0  0.900539  0.928036
3751  1.002  0.872426  1.0  0.900456  0.928084
3752  1.002  0.871856  1.0  0.900373  0.928132
3753  1.003  0.871287  1.0  0.900290  0.928180

3750

<lambdifygenerated-16091>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1 + x1**x1)
<lambdifygenerated-16092>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1 + x1**x1)
<lambdifygenerated-16095>:2: RuntimeWarning: invalid value encountered in power
  return x1*(_a4_**(x1**x1) + x1)
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-16096>:2: RuntimeWarning: invalid value encountered in power
  return x1*(_a4_**(x1**x1) + x1)
<lambdifygenerated-16097>:2: RuntimeWarning: invalid value encountered in power
  return x1*(_a4_**(_a7_**x1) + x1)
<lambdifygenerated-16101>:2: RuntimeWarning: invalid value encountered in power
  return x1*(_a1_ + _a4_**(_a7_**x1))
<lambdifygenerated-16103>:2: RuntimeWarning: overflow encountered in power
  return _a1_*(_a1_ + _a4_**(_a7_**x1))
<lambdifygenerated-16103>:2: RuntimeWarning: invalid value encountered in power
  return _a1_*(_a1_ + _a4_**(_a7_**x1))
<lambdifygenerated-16107>:2: RuntimeWarning: overflow encountered in power
  return _a1_*(_a1_ + _a4_**(_a7_**x1))
<lambdifygenerated-16107>:2: RuntimeWarning: invalid value encountered in power
  return _a1_*(_a1_ + _a4_**(_a7_**x1))

interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.997734  2.0  0.990408  0.998873
3746  0.998  0.997761  2.0  0.990421  0.998901
3747  0.998  0.997787  2.0  0.990433  0.998928
3748  0.999  0.997814  2.0  0.990446  0.998956

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.997867  2.0  0.990471  0.999011
3751  1.002  0.997894  2.0  0.990483  0.999038
3752  1.002  0.997921  2.0  0.990495  0.999066
3753  1.003  0.997948  2.0  0.990508  0.999093

3750
interpolation

<lambdifygenerated-16113>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1
<lambdifygenerated-16114>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1
<lambdifygenerated-16117>:2: RuntimeWarning: invalid value encountered in power
  return _a7_**(x1**x1)
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-16118>:2: RuntimeWarning: invalid value encountered in power
  return _a7_**(x1**x1)

         x1         y  rep    ymodel      ybms
3745  0.997  0.689029  3.0  0.668912  0.664653
3746  0.998  0.688777  3.0  0.668471  0.664127
3747  0.998  0.688525  3.0  0.668030  0.663601
3748  0.999  0.688273  3.0  0.667589  0.663075

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.687768  3.0  0.666705  0.662019
3751  1.002  0.687516  3.0  0.666264  0.661491
3752  1.002  0.687264  3.0  0.665822  0.660962
3753  1.003  0.687012  3.0  0.665379  0.660432

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.661298  4.0  0.623544  0.673171
3746  0.998  0.661485  4.0  0.623537  0.673551
3747  0.998  0.661672  4.0  0.623530  0.673931
3748  0.999  0.661858  4.0  0.623523  0.674313

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.662232  4.0  0.623509  0.675081
3751  1.002  0.662419  4.0  0.623502  0.675467
3752  1.002  0.662605  4.0  0.623494  0.675854
3753  1.003  0.662792  4.0  0.623487  0.676242

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.956369  5.0  0.951686  0.982788
3746  0.998  0.956259  5.0  0.951500  0.982788
3747  0.998  0.956150  5.0  0.951313  0.982788
3748  0.999  0.956040  5.0  0.951127  0.982788

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.955822  5.0  0.950755  0.982788
3751  1.002  0.955712  5.0  0.950568  0.982788
3752  1.002  0.955603  5.0  0.950382  0.982788
3753  1.003  0.955493  5.0  0.950195  0.982788

3750
interpolation

<lambdifygenerated-16173>:2: RuntimeWarning: invalid value encountered in power
  return (x1*x1**x1 + x1)**2
<lambdifygenerated-16174>:2: RuntimeWarning: invalid value encountered in power
  return (x1*x1**x1 + x1)**2

         x1         y  rep    ymodel      ybms
3745  0.997  0.428260  6.0  0.420563  0.420542
3746  0.998  0.428367  6.0  0.420625  0.420550
3747  0.998  0.428474  6.0  0.420688  0.420558
3748  0.999  0.428581  6.0  0.420751  0.420567

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.428794  6.0  0.420878  0.420583
3751  1.002  0.428901  6.0  0.420942  0.420592
3752  1.002  0.429008  6.0  0.421007  0.420600
3753  1.003  0.429115  6.0  0.421072  0.420608

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.173654  7.0  0.175077  0.175262
3746  0.998  0.173884  7.0  0.175287  0.175513
3747  0.998  0.174114  7.0  0.175496  0.175765
3748  0.999  0.174344  7.0  0.175706  0.176017

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.174804  7.0  0.176124  0.176522
3751  1.002  0.175034  7.0  0.176333  0.176774
3752  1.002  0.175264  7.0  0.176542  0.177027
3753  1.003  0.175494  7.0  0.176750  0.177281

3750

<lambdifygenerated-16229>:2: RuntimeWarning: invalid value encountered in power
  return x1*x1**x1
<lambdifygenerated-16230>:2: RuntimeWarning: invalid value encountered in power
  return x1*x1**x1
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-16275>:2: RuntimeWarning: overflow encountered in power
  return _a6_*((_a0_**2*_a2_**2*tanh(_a3_/x1)**2 + _a0_*_a7_)**2)**(_a3_ + _a7_**2*x1**2 + x1)
<lambdifygenerated-16279>:2: RuntimeWarning: overflow encountered in power
  return _a6_*((_a0_**2*_a2_**2*tanh(_a3_/x1)**2 + _a0_*_a7_)**2)**(_a3_ + _a7_**2*x1**2 + x1)

interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.261188  8.0  0.253551  0.267062
3746  0.998  0.261362  8.0  0.253764  0.267375
3747  0.998  0.261535  8.0  0.253976  0.267689
3748  0.999  0.261709  8.0  0.254188  0.268003

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.262056  8.0  0.254611  0.268631
3751  1.002  0.262229  8.0  0.254822  0.268946
3752  1.002  0.262402  8.0  0.255034  0.269260
3753  1.003  0.262576  8.0  0.255245  0.269575

3750
interpolation

<lambdifygenerated-16287>:2: RuntimeWarning: invalid value encountered in power
  return x1*x1**x1
<lambdifygenerated-16288>:2: RuntimeWarning: invalid value encountered in power
  return x1*x1**x1
<lambdifygenerated-16291>:2: RuntimeWarning: invalid value encountered in power
  return x1*(_a1_*x1)**x1
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-16292>:2: RuntimeWarning: invalid value encountered in power
  return x1*(_a1_*x1)**x1
<lambdifygenerated-16293>:2: RuntimeWarning: invalid value encountered in power
  return x1*(_a1_*x1**x1)**x1
<lambdifygenerated-16294>:2: RuntimeWarning: invalid value encountered in power
  return x1*(_a1_*x1**x1)**x1
<lambdifygenerated-16299>:2: RuntimeWarning: invalid value encountered in power
  return x1*(_a0_**x1*_a1_)**(x1**x1)
<lambdifygenerated-16300>:2: RuntimeWarning: invalid value encountered in power
  return x1*(_a0_**x1*_a1_)**(x1**x1)
<lambdifygenerated-16301>:2: RuntimeWarning: invalid value encountered in power
  return x1*(_a0_**x1*_a1_)**(_a2_**x1)
<lambdifygenerated-16303>:2: RuntimeWarning: invalid value encountered in power
  return x1*(_a0_**x1*_a1_)**(_a2_**abs(x1))
<lambdifygenerated-16305>:2: RuntimeWarning: invalid value encountered in power
  return x1*(_a0_**x1*_a1_)**(_a2_**(2*abs(x1)))

         x1        y  rep    ymodel      ybms
3745  0.997  0.64259  9.0  0.647946  0.643029
3746  0.998  0.64247  9.0  0.647857  0.642911
3747  0.998  0.64235  9.0  0.647768  0.642793
3748  0.999  0.64223  9.0  0.647680  0.642675

extrapolation

         x1        y  rep    ymodel      ybms
3750  1.001  0.64199  9.0  0.647503  0.642440
3751  1.002  0.64187  9.0  0.647416  0.642322
3752  1.002  0.64175  9.0  0.647328  0.642204
3753  1.003  0.64163  9.0  0.647240  0.642087

3750
interpolation

<lambdifygenerated-16325>:2: RuntimeWarning: invalid value encountered in power
  return _a3_*x1**x1
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-16326>:2: RuntimeWarning: invalid value encountered in power
  return _a3_*x1**x1
<lambdifygenerated-16329>:2: RuntimeWarning: invalid value encountered in power
  return _a3_*_a4_**(-x1)
<lambdifygenerated-16331>:2: RuntimeWarning: invalid value encountered in power
  return _a3_*_a4_**(-x1**x1)
<lambdifygenerated-16332>:2: RuntimeWarning: invalid value encountered in power
  return _a3_*_a4_**(-x1**x1)
<lambdifygenerated-16337>:2: RuntimeWarning: invalid value encountered in power
  return _a3_*_a4_**(-(cos(x1)**2/x1**2)**x1)

         x1         y  rep    ymodel      ybms
3745  0.997  0.360683  0.0  0.342422  0.342421
3746  0.998  0.360826  0.0  0.342522  0.342501
3747  0.998  0.360969  0.0  0.342621  0.342581
3748  0.999  0.361111  0.0  0.342721  0.342660

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.361396  0.0  0.342921  0.342818
3751  1.002  0.361539  0.0  0.343020  0.342897
3752  1.002  0.361681  0.0  0.343120  0.342976
3753  1.003  0.361824  0.0  0.343219  0.343055

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.875844  1.0  0.901315  0.924358
3746  0.998  0.875274  1.0  0.901225  0.924361
3747  0.998  0.874704  1.0  0.901134  0.924365
3748  0.999  0.874135  1.0  0.901044  0.924368

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.872995  1.0  0.900863  0.924376
3751  1.002  0.872426  1.0  0.900773  0.924380
3752  1.002  0.871856  1.0  0.900683  0.924385
3753  1.003  0.871287  1.0  0.900592  0.924389

3750
interpolation

<lambdifygenerated-16389>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1*(x1 + x1**x1) + x1)
<lambdifygenerated-16390>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1*(x1 + x1**x1) + x1)
<lambdifygenerated-16393>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1*(_a6_**(x1**x1) + x1) + x1)
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-16394>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1*(_a6_**(x1**x1) + x1) + x1)
<lambdifygenerated-16395>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1*(_a6_**((x1**x1)**x1) + x1) + x1)
<lambdifygenerated-16396>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1*(_a6_**((x1**x1)**x1) + x1) + x1)
<lambdifygenerated-16399>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1*(_a6_**((_a3_**(x1**2))**x1) + x1) + x1)
<lambdifygenerated-16405>:2: RuntimeWarning: overflow encountered in power
  return x1*(x1*(_a6_**((_a3_**(x1**2))**x1) + _a7_) + x1)
<lambdifygenerated-16405>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1*(_a6_**((_a3_**(x1**2))**x1) + _a7_) + x1)
<lambdifygenerated-16409>:2: RuntimeWarning: overflow encountered in power
  return x1*(_a3_ + x1*(_a6_**((_a3_**(x1**2))**x1) + _a7_))
<lambdifygenerated-16411>:2: RuntimeWarning: overflow encountered in power
  return _a6_*(_a3_ + x1*(_a6_**((_a3_**(x1**2))**x1) + _a7_))
<lambdifygenerated-16415>:2: RuntimeWarning: overflow encountered in power
  return _a6_*(_a3_ + x1*(_a6_**((_a3_**(x1**2))**x1) + _a7_))

         x1         y  rep    ymodel      ybms
3745  0.997  0.997734  2.0  1.006547  1.009699
3746  0.998  0.997761  2.0  1.006591  1.009773
3747  0.998  0.997787  2.0  1.006634  1.009848
3748  0.999  0.997814  2.0  1.006678  1.009922

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.997867  2.0  1.006766  1.010071
3751  1.002  0.997894  2.0  1.006809  1.010146
3752  1.002  0.997921  2.0  1.006853  1.010220
3753  1.003  0.997948  2.0  1.006897  1.010295

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.689029  3.0  0.695868  0.694677
3746  0.998  0.688777  3.0  0.695502  0.694214
3747  0.998  0.688525  3.0  0.695136  0.693751
3748  0.999  0.688273  3.0  0.694770  0.693288

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.687768  3.0  0.694038  0.692359
3751  1.002  0.687516  3.0  0.693671  0.691893
3752  1.002  0.687264  3.0  0.693305  0.691427
3753  1.003  0.687012  3.0  0.692938  0.690960

3750
interpolation

<lambdifygenerated-16451>:2: RuntimeWarning: invalid value encountered in power
  return _a1_ + (_a6_*x1**x1 + x1)**2
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-16452>:2: RuntimeWarning: invalid value encountered in power
  return _a1_ + (_a6_*x1**x1 + x1)**2
<lambdifygenerated-16457>:2: RuntimeWarning: invalid value encountered in power
  return _a1_ + (_a1_ + _a3_**x1*_a6_)**2

         x1         y  rep    ymodel      ybms
3745  0.997  0.661298  4.0  0.640105  0.653737
3746  0.998  0.661485  4.0  0.640243  0.653984
3747  0.998  0.661672  4.0  0.640381  0.654232
3748  0.999  0.661858  4.0  0.640519  0.654481

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.662232  4.0  0.640796  0.654981
3751  1.002  0.662419  4.0  0.640935  0.655233
3752  1.002  0.662605  4.0  0.641074  0.655485
3753  1.003  0.662792  4.0  0.641214  0.655738

3750
interpolation

<lambdifygenerated-16467>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1
<lambdifygenerated-16468>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1

         x1         y  rep    ymodel      ybms
3745  0.997  0.956369  5.0  0.941342  0.979529
3746  0.998  0.956259  5.0  0.941109  0.979513
3747  0.998  0.956150  5.0  0.940875  0.979497
3748  0.999  0.956040  5.0  0.940641  0.979480

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.955822  5.0  0.940172  0.979448
3751  1.002  0.955712  5.0  0.939937  0.979432
3752  1.002  0.955603  5.0  0.939701  0.979415
3753  1.003  0.955493  5.0  0.939465  0.979399

<lambdifygenerated-16483>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1
<lambdifygenerated-16484>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1

3750

<lambdifygenerated-16487>:2: RuntimeWarning: invalid value encountered in power
  return _a6_**(x1**x1)
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-16488>:2: RuntimeWarning: invalid value encountered in power
  return _a6_**(x1**x1)
<lambdifygenerated-16489>:2: RuntimeWarning: invalid value encountered in power
  return _a6_**(_a3_**x1)
<lambdifygenerated-16491>:2: RuntimeWarning: invalid value encountered in power
  return _a6_**(_a3_**(x1**x1))
<lambdifygenerated-16492>:2: RuntimeWarning: invalid value encountered in power
  return _a6_**(_a3_**(x1**x1))
<lambdifygenerated-16493>:2: RuntimeWarning: invalid value encountered in power
  return _a6_**(_a3_**(_a1_**x1))
<lambdifygenerated-16499>:2: RuntimeWarning: invalid value encountered in power
  return _a6_**(_a3_**(_a1_**x1))

interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.428260  6.0  0.404812  0.420122
3746  0.998  0.428367  6.0  0.404732  0.420130
3747  0.998  0.428474  6.0  0.404652  0.420138
3748  0.999  0.428581  6.0  0.404571  0.420146

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.428794  6.0  0.404410  0.420163
3751  1.002  0.428901  6.0  0.404329  0.420171
3752  1.002  0.429008  6.0  0.404247  0.420179
3753  1.003  0.429115  6.0  0.404166  0.420187

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.173654  7.0  0.168813  0.187437
3746  0.998  0.173884  7.0  0.168976  0.187838
3747  0.998  0.174114  7.0  0.169138  0.188239
3748  0.999  0.174344  7.0  0.169298  0.188641

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.174804  7.0  0.169617  0.189446
3751  1.002  0.175034  7.0  0.169775  0.189850
3752  1.002  0.175264  7.0  0.169932  0.190253
3753  1.003  0.175494  7.0  0.170087  0.190658

3750
interpolation

/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(

         x1         y  rep    ymodel      ybms
3745  0.997  0.261188  8.0  0.242135  0.260968
3746  0.998  0.261362  8.0  0.242293  0.261259
3747  0.998  0.261535  8.0  0.242450  0.261550
3748  0.999  0.261709  8.0  0.242607  0.261841

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.262056  8.0  0.242921  0.262423
3751  1.002  0.262229  8.0  0.243077  0.262714
3752  1.002  0.262402  8.0  0.243233  0.263004
3753  1.003  0.262576  8.0  0.243389  0.263295

3750
interpolation

/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-16619>:2: RuntimeWarning: invalid value encountered in log
  return cos(_a7_*(x1 + log(x1) + tanh(_a5_*x1)))
<lambdifygenerated-16620>:2: RuntimeWarning: invalid value encountered in log
  return cos(_a7_*(x1 + log(x1) + tanh(_a5_*x1)))
<lambdifygenerated-16621>:2: RuntimeWarning: invalid value encountered in log
  return cos(_a7_*(x1 + log(_a5_) + tanh(_a5_*x1)))

         x1        y  rep    ymodel      ybms
3745  0.997  0.64259  9.0  0.649504  0.643438
3746  0.998  0.64247  9.0  0.649383  0.643273
3747  0.998  0.64235  9.0  0.649262  0.643108
3748  0.999  0.64223  9.0  0.649142  0.642943

extrapolation

         x1        y  rep    ymodel      ybms
3750  1.001  0.64199  9.0  0.648901  0.642613
3751  1.002  0.64187  9.0  0.648781  0.642448
3752  1.002  0.64175  9.0  0.648660  0.642283
3753  1.003  0.64163  9.0  0.648540  0.642119

3750
interpolation

<lambdifygenerated-16635>:2: RuntimeWarning: invalid value encountered in power
  return _a0_*x1**x1
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-16636>:2: RuntimeWarning: invalid value encountered in power
  return _a0_*x1**x1
<lambdifygenerated-16639>:2: RuntimeWarning: invalid value encountered in power
  return _a0_*_a2_**(x1**x1)
<lambdifygenerated-16640>:2: RuntimeWarning: invalid value encountered in power
  return _a0_*_a2_**(x1**x1)
<lambdifygenerated-16645>:2: RuntimeWarning: overflow encountered in power
  return _a0_*_a2_**(_a2_**sinh(2*x1))
/usr/local/lib/python3.10/dist-packages/scipy/optimize/_minpack_py.py:1017: RuntimeWarning: overflow encountered in square
  cost = np.sum(infodict['fvec'] ** 2)
/usr/local/lib/python3.10/dist-packages/pandas/core/arraylike.py:399: RuntimeWarning: overflow encountered in square
  result = getattr(ufunc, method)(*inputs, **kwargs)
<lambdifygenerated-16646>:2: RuntimeWarning: overflow encountered in power
  return _a0_*_a2_**(_a2_**sinh(2*x1))
<lambdifygenerated-16647>:2: RuntimeWarning: overflow encountered in power
  return _a0_*_a2_**(_a2_**sinh(2*x1))
<lambdifygenerated-16648>:2: RuntimeWarning: overflow encountered in power
  return _a0_*_a2_**(_a2_**sinh(2*x1))
<lambdifygenerated-16649>:2: RuntimeWarning: overflow encountered in power
  return _a0_*_a2_**(_a2_**sinh(2*x1))
<lambdifygenerated-16650>:2: RuntimeWarning: overflow encountered in power
  return _a0_*_a2_**(_a2_**sinh(2*x1))
<lambdifygenerated-16651>:2: RuntimeWarning: overflow encountered in power
  return _a0_*_a2_**(_a2_**sinh(2*x1))
<lambdifygenerated-16652>:2: RuntimeWarning: overflow encountered in power
  return _a0_*_a2_**(_a2_**sinh(2*x1))
<lambdifygenerated-16653>:2: RuntimeWarning: overflow encountered in power
  return _a0_*_a2_**(_a2_**sinh(2*x1))
<lambdifygenerated-16654>:2: RuntimeWarning: overflow encountered in power
  return _a0_*_a2_**(_a2_**sinh(2*x1))

         x1         y  rep    ymodel      ybms
3745  0.997  0.360683  0.0  0.347770  0.340909
3746  0.998  0.360826  0.0  0.347885  0.340994
3747  0.998  0.360969  0.0  0.348001  0.341078
3748  0.999  0.361111  0.0  0.348116  0.341163

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.361396  0.0  0.348347  0.341332
3751  1.002  0.361539  0.0  0.348463  0.341416
3752  1.002  0.361681  0.0  0.348578  0.341501
3753  1.003  0.361824  0.0  0.348694  0.341585

3750
interpolation

<lambdifygenerated-16659>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1
<lambdifygenerated-16660>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1
<lambdifygenerated-16661>:2: RuntimeWarning: invalid value encountered in power
  return (x1**x1)**x1
<lambdifygenerated-16662>:2: RuntimeWarning: invalid value encountered in power
  return (x1**x1)**x1

         x1         y  rep    ymodel      ybms
3745  0.997  0.875844  1.0  0.905578  0.876874
3746  0.998  0.875274  1.0  0.905496  0.876659
3747  0.998  0.874704  1.0  0.905414  0.876445
3748  0.999  0.874135  1.0  0.905332  0.876231

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.872995  1.0  0.905169  0.875801
3751  1.002  0.872426  1.0  0.905087  0.875586
3752  1.002  0.871856  1.0  0.905006  0.875371
3753  1.003  0.871287  1.0  0.904924  0.875155

3750

<lambdifygenerated-16687>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1 + x1**x1)
<lambdifygenerated-16688>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1 + x1**x1)
<lambdifygenerated-16691>:2: RuntimeWarning: invalid value encountered in power
  return x1*(_a4_**(x1**x1) + x1)
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-16692>:2: RuntimeWarning: invalid value encountered in power
  return x1*(_a4_**(x1**x1) + x1)
<lambdifygenerated-16693>:2: RuntimeWarning: invalid value encountered in power
  return x1*(_a4_**(_a6_**x1) + x1)
<lambdifygenerated-16697>:2: RuntimeWarning: invalid value encountered in power
  return x1*(_a4_**(_a6_**x1) + _a7_)
<lambdifygenerated-16699>:2: RuntimeWarning: overflow encountered in power
  return _a7_*(_a4_**(_a6_**x1) + _a7_)
<lambdifygenerated-16699>:2: RuntimeWarning: invalid value encountered in power
  return _a7_*(_a4_**(_a6_**x1) + _a7_)
<lambdifygenerated-16703>:2: RuntimeWarning: overflow encountered in power
  return _a7_*(_a4_**(_a6_**x1) + _a7_)
<lambdifygenerated-16703>:2: RuntimeWarning: invalid value encountered in power
  return _a7_*(_a4_**(_a6_**x1) + _a7_)

interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.997734  2.0  1.000766  1.000124
3746  0.998  0.997761  2.0  1.000807  1.000152
3747  0.998  0.997787  2.0  1.000848  1.000180
3748  0.999  0.997814  2.0  1.000889  1.000207

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.997867  2.0  1.000970  1.000263
3751  1.002  0.997894  2.0  1.001011  1.000290
3752  1.002  0.997921  2.0  1.001052  1.000318
3753  1.003  0.997948  2.0  1.001093  1.000346

3750
interpolation

<lambdifygenerated-16709>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1
<lambdifygenerated-16710>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1
<lambdifygenerated-16713>:2: RuntimeWarning: invalid value encountered in sqrt
  return _a0_**(sqrt(x1))
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-16714>:2: RuntimeWarning: invalid value encountered in sqrt
  return _a0_**(sqrt(x1))
<lambdifygenerated-16715>:2: RuntimeWarning: invalid value encountered in power
  return _a0_**(sqrt(x1**x1))
<lambdifygenerated-16716>:2: RuntimeWarning: invalid value encountered in power
  return _a0_**(sqrt(x1**x1))

         x1         y  rep    ymodel      ybms
3745  0.997  0.689029  3.0  0.690585  0.670907
3746  0.998  0.688777  3.0  0.690311  0.670419
3747  0.998  0.688525  3.0  0.690038  0.669931
3748  0.999  0.688273  3.0  0.689764  0.669442

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.687768  3.0  0.689218  0.668462
3751  1.002  0.687516  3.0  0.688945  0.667972
3752  1.002  0.687264  3.0  0.688672  0.667481
3753  1.003  0.687012  3.0  0.688400  0.666989

3750

<lambdifygenerated-16743>:2: RuntimeWarning: invalid value encountered in power
  return _a7_*x1**x1*(_a2_ + x1) + x1
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-16744>:2: RuntimeWarning: invalid value encountered in power
  return _a7_*x1**x1*(_a2_ + x1) + x1

interpolation

<lambdifygenerated-16753>:2: RuntimeWarning: invalid value encountered in power
  return _a4_ + _a5_**x1*_a7_*(_a2_ + x1)

         x1         y  rep    ymodel      ybms
3745  0.997  0.661298  4.0  0.683156  0.680542
3746  0.998  0.661485  4.0  0.683506  0.680873
3747  0.998  0.661672  4.0  0.683857  0.681205
3748  0.999  0.661858  4.0  0.684208  0.681537

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.662232  4.0  0.684914  0.682206
3751  1.002  0.662419  4.0  0.685268  0.682542
3752  1.002  0.662605  4.0  0.685624  0.682879
3753  1.003  0.662792  4.0  0.685980  0.683216

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.956369  5.0  0.959904  0.982159
3746  0.998  0.956259  5.0  0.959805  0.982159
3747  0.998  0.956150  5.0  0.959707  0.982159
3748  0.999  0.956040  5.0  0.959609  0.982159

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.955822  5.0  0.959413  0.982159
3751  1.002  0.955712  5.0  0.959315  0.982159
3752  1.002  0.955603  5.0  0.959218  0.982159
3753  1.003  0.955493  5.0  0.959120  0.982159

3750
interpolation

         x1         y  rep    ymodel    ybms
3745  0.997  0.428260  6.0  0.419824  0.4103
3746  0.998  0.428367  6.0  0.419879  0.4103
3747  0.998  0.428474  6.0  0.419934  0.4103
3748  0.999  0.428581  6.0  0.419989  0.4103

extrapolation

         x1         y  rep    ymodel    ybms
3750  1.001  0.428794  6.0  0.420099  0.4103
3751  1.002  0.428901  6.0  0.420154  0.4103
3752  1.002  0.429008  6.0  0.420210  0.4103
3753  1.003  0.429115  6.0  0.420266  0.4103

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.173654  7.0  0.180855  0.180485
3746  0.998  0.173884  7.0  0.181203  0.180811
3747  0.998  0.174114  7.0  0.181551  0.181137
3748  0.999  0.174344  7.0  0.181900  0.181463

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.174804  7.0  0.182597  0.182116
3751  1.002  0.175034  7.0  0.182947  0.182443
3752  1.002  0.175264  7.0  0.183296  0.182770
3753  1.003  0.175494  7.0  0.183646  0.183097

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.261188  8.0  0.266194  0.280095
3746  0.998  0.261362  8.0  0.266440  0.280479
3747  0.998  0.261535  8.0  0.266685  0.280863
3748  0.999  0.261709  8.0  0.266930  0.281248

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.262056  8.0  0.267420  0.282017
3751  1.002  0.262229  8.0  0.267665  0.282402
3752  1.002  0.262402  8.0  0.267909  0.282788
3753  1.003  0.262576  8.0  0.268153  0.283173

3750
interpolation

         x1        y  rep    ymodel      ybms
3745  0.997  0.64259  9.0  0.635774  0.637527
3746  0.998  0.64247  9.0  0.635623  0.637382
3747  0.998  0.64235  9.0  0.635472  0.637237
3748  0.999  0.64223  9.0  0.635322  0.637093

extrapolation

         x1        y  rep    ymodel      ybms
3750  1.001  0.64199  9.0  0.635020  0.636803
3751  1.002  0.64187  9.0  0.634870  0.636658
3752  1.002  0.64175  9.0  0.634720  0.636513
3753  1.003  0.64163  9.0  0.634569  0.636368

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.360683  0.0  0.366702  0.364428
3746  0.998  0.360826  0.0  0.366834  0.364514
3747  0.998  0.360969  0.0  0.366967  0.364600
3748  0.999  0.361111  0.0  0.367099  0.364686

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.361396  0.0  0.367364  0.364857
3751  1.002  0.361539  0.0  0.367497  0.364942
3752  1.002  0.361681  0.0  0.367629  0.365028
3753  1.003  0.361824  0.0  0.367762  0.365113

3750
interpolation

<lambdifygenerated-16937>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1
<lambdifygenerated-16938>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1

         x1         y  rep    ymodel      ybms
3745  0.997  0.875844  1.0  0.889069  0.877012
3746  0.998  0.875274  1.0  0.888955  0.876839
3747  0.998  0.874704  1.0  0.888841  0.876666
3748  0.999  0.874135  1.0  0.888727  0.876492

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.872995  1.0  0.888499  0.876145
3751  1.002  0.872426  1.0  0.888385  0.875971
3752  1.002  0.871856  1.0  0.888271  0.875798
3753  1.003  0.871287  1.0  0.888157  0.875624

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.997734  2.0  0.985878  0.988996
3746  0.998  0.997761  2.0  0.985852  0.988922
3747  0.998  0.997787  2.0  0.985826  0.988848
3748  0.999  0.997814  2.0  0.985800  0.988773

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.997867  2.0  0.985747  0.988622
3751  1.002  0.997894  2.0  0.985721  0.988547
3752  1.002  0.997921  2.0  0.985695  0.988471
3753  1.003  0.997948  2.0  0.985668  0.988394

3750
interpolation

<lambdifygenerated-16995>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1
<lambdifygenerated-16996>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1

         x1         y  rep    ymodel      ybms
3745  0.997  0.689029  3.0  0.690662  0.675859
3746  0.998  0.688777  3.0  0.690300  0.675359
3747  0.998  0.688525  3.0  0.689939  0.674859
3748  0.999  0.688273  3.0  0.689577  0.674358

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.687768  3.0  0.688853  0.673354
3751  1.002  0.687516  3.0  0.688490  0.672851
3752  1.002  0.687264  3.0  0.688128  0.672348
3753  1.003  0.687012  3.0  0.687765  0.671844

3750
interpolation

<lambdifygenerated-17031>:2: RuntimeWarning: overflow encountered in exp
  return _a0_ + (-x1 + exp(_a5_ + x1))**2
<lambdifygenerated-17033>:2: RuntimeWarning: overflow encountered in exp
  return _a0_ + (-_a0_ + exp(_a5_ + x1))**2
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(

         x1         y  rep    ymodel      ybms
3745  0.997  0.661298  4.0  0.674552  0.667698
3746  0.998  0.661485  4.0  0.675011  0.668056
3747  0.998  0.661672  4.0  0.675471  0.668415
3748  0.999  0.661858  4.0  0.675931  0.668775

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.662232  4.0  0.676856  0.669498
3751  1.002  0.662419  4.0  0.677320  0.669862
3752  1.002  0.662605  4.0  0.677785  0.670227
3753  1.003  0.662792  4.0  0.678251  0.670594

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.956369  5.0  0.965111  0.981971
3746  0.998  0.956259  5.0  0.965162  0.981971
3747  0.998  0.956150  5.0  0.965214  0.981971
3748  0.999  0.956040  5.0  0.965267  0.981971

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.955822  5.0  0.965375  0.981971
3751  1.002  0.955712  5.0  0.965431  0.981971
3752  1.002  0.955603  5.0  0.965487  0.981971
3753  1.003  0.955493  5.0  0.965544  0.981971

3750
interpolation

<lambdifygenerated-17059>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1 + x1**x1)**2
<lambdifygenerated-17060>:2: RuntimeWarning: invalid value encountered in power
  return x1*(x1 + x1**x1)**2

         x1         y  rep    ymodel      ybms
3745  0.997  0.428260  6.0  0.402754  0.423663
3746  0.998  0.428367  6.0  0.402657  0.423671
3747  0.998  0.428474  6.0  0.402560  0.423680
3748  0.999  0.428581  6.0  0.402462  0.423689

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.428794  6.0  0.402266  0.423706
3751  1.002  0.428901  6.0  0.402168  0.423714
3752  1.002  0.429008  6.0  0.402069  0.423723
3753  1.003  0.429115  6.0  0.401971  0.423731

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.173654  7.0  0.147954  0.151623
3746  0.998  0.173884  7.0  0.148090  0.151820
3747  0.998  0.174114  7.0  0.148226  0.152018
3748  0.999  0.174344  7.0  0.148363  0.152217

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.174804  7.0  0.148635  0.152614
3751  1.002  0.175034  7.0  0.148770  0.152813
3752  1.002  0.175264  7.0  0.148906  0.153012
3753  1.003  0.175494  7.0  0.149041  0.153212

3750
interpolation

<lambdifygenerated-17113>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1
<lambdifygenerated-17114>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1

         x1         y  rep    ymodel      ybms
3745  0.997  0.261188  8.0  0.279876  0.278539
3746  0.998  0.261362  8.0  0.280414  0.278900
3747  0.998  0.261535  8.0  0.280954  0.279262
3748  0.999  0.261709  8.0  0.281495  0.279624

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.262056  8.0  0.282580  0.280348
3751  1.002  0.262229  8.0  0.283124  0.280710
3752  1.002  0.262402  8.0  0.283669  0.281072
3753  1.003  0.262576  8.0  0.284216  0.281434

3750
interpolation

         x1        y  rep    ymodel      ybms
3745  0.997  0.64259  9.0  0.629704  0.611918
3746  0.998  0.64247  9.0  0.629576  0.611702
3747  0.998  0.64235  9.0  0.629449  0.611486
3748  0.999  0.64223  9.0  0.629322  0.611270

extrapolation

         x1        y  rep    ymodel      ybms
3750  1.001  0.64199  9.0  0.629068  0.610838
3751  1.002  0.64187  9.0  0.628942  0.610621
3752  1.002  0.64175  9.0  0.628817  0.610405
3753  1.003  0.64163  9.0  0.628692  0.610190

3750
interpolation

<lambdifygenerated-17189>:2: RuntimeWarning: invalid value encountered in power
  return _a7_*x1**x1
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-17190>:2: RuntimeWarning: invalid value encountered in power
  return _a7_*x1**x1

         x1         y  rep    ymodel      ybms
3745  0.997  0.360683  0.0  0.354999  0.354472
3746  0.998  0.360826  0.0  0.355091  0.354554
3747  0.998  0.360969  0.0  0.355183  0.354636
3748  0.999  0.361111  0.0  0.355275  0.354718

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.361396  0.0  0.355459  0.354881
3751  1.002  0.361539  0.0  0.355550  0.354963
3752  1.002  0.361681  0.0  0.355642  0.355044
3753  1.003  0.361824  0.0  0.355734  0.355126

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.875844  1.0  0.896456  0.872535
3746  0.998  0.875274  1.0  0.896335  0.872314
3747  0.998  0.874704  1.0  0.896213  0.872092
3748  0.999  0.874135  1.0  0.896091  0.871870

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.872995  1.0  0.895847  0.871425
3751  1.002  0.872426  1.0  0.895725  0.871202
3752  1.002  0.871856  1.0  0.895603  0.870979
3753  1.003  0.871287  1.0  0.895481  0.870756

3750
interpolation

<lambdifygenerated-17243>:2: RuntimeWarning: invalid value encountered in power
  return tanh(x1*x1**x1)
<lambdifygenerated-17244>:2: RuntimeWarning: invalid value encountered in power
  return tanh(x1*x1**x1)
<lambdifygenerated-17245>:2: RuntimeWarning: overflow encountered in multiply
  return tanh(_a0_**x1*x1)
<lambdifygenerated-17245>:2: RuntimeWarning: overflow encountered in power
  return tanh(_a0_**x1*x1)
/usr/local/lib/python3.10/dist-packages/scipy/optimize/_minpack_py.py:497: RuntimeWarning: overflow encountered in matmul
  cov_x = invR @ invR.T
<lambdifygenerated-17246>:2: RuntimeWarning: overflow encountered in power
  return tanh(_a0_**x1*x1)
<lambdifygenerated-17246>:2: RuntimeWarning: overflow encountered in multiply
  return tanh(_a0_**x1*x1)
<lambdifygenerated-17247>:2: RuntimeWarning: overflow encountered in power
  return tanh(_a0_**x1*x1)
<lambdifygenerated-17247>:2: RuntimeWarning: overflow encountered in multiply
  return tanh(_a0_**x1*x1)
<lambdifygenerated-17248>:2: RuntimeWarning: overflow encountered in power
  return tanh(_a0_**x1*x1)
<lambdifygenerated-17248>:2: RuntimeWarning: overflow encountered in multiply
  return tanh(_a0_**x1*x1)
<lambdifygenerated-17249>:2: RuntimeWarning: overflow encountered in power
  return tanh(_a0_**x1*_a1_)
<lambdifygenerated-17249>:2: RuntimeWarning: invalid value encountered in power
  return tanh(_a0_**x1*_a1_)

         x1         y  rep    ymodel      ybms
3745  0.997  0.997734  2.0  1.002351  0.996677
3746  0.998  0.997761  2.0  1.002355  0.996688
3747  0.998  0.997787  2.0  1.002358  0.996698
3748  0.999  0.997814  2.0  1.002361  0.996709

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.997867  2.0  1.002367  0.996731
3751  1.002  0.997894  2.0  1.002369  0.996741
3752  1.002  0.997921  2.0  1.002372  0.996752
3753  1.003  0.997948  2.0  1.002375  0.996762

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.689029  3.0  0.692864  0.693912
3746  0.998  0.688777  3.0  0.692488  0.693449
3747  0.998  0.688525  3.0  0.692112  0.692984
3748  0.999  0.688273  3.0  0.691736  0.692520

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.687768  3.0  0.690984  0.691588
3751  1.002  0.687516  3.0  0.690608  0.691122
3752  1.002  0.687264  3.0  0.690232  0.690654
3753  1.003  0.687012  3.0  0.689856  0.690186

3750
interpolation

<lambdifygenerated-17285>:2: RuntimeWarning: invalid value encountered in power
  return _a0_*sin(x1**x1) + x1
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-17286>:2: RuntimeWarning: invalid value encountered in power
  return _a0_*sin(x1**x1) + x1

         x1         y  rep    ymodel      ybms
3745  0.997  0.661298  4.0  0.661850  0.656117
3746  0.998  0.661485  4.0  0.662031  0.656322
3747  0.998  0.661672  4.0  0.662211  0.656527
3748  0.999  0.661858  4.0  0.662391  0.656734

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.662232  4.0  0.662750  0.657148
3751  1.002  0.662419  4.0  0.662929  0.657357
3752  1.002  0.662605  4.0  0.663108  0.657565
3753  1.003  0.662792  4.0  0.663287  0.657775

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.956369  5.0  0.976998  0.983042
3746  0.998  0.956259  5.0  0.977056  0.983042
3747  0.998  0.956150  5.0  0.977114  0.983042
3748  0.999  0.956040  5.0  0.977172  0.983042

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.955822  5.0  0.977288  0.983042
3751  1.002  0.955712  5.0  0.977347  0.983042
3752  1.002  0.955603  5.0  0.977406  0.983042
3753  1.003  0.955493  5.0  0.977465  0.983042

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.428260  6.0  0.428868  0.423393
3746  0.998  0.428367  6.0  0.428869  0.423399
3747  0.998  0.428474  6.0  0.428870  0.423405
3748  0.999  0.428581  6.0  0.428871  0.423411

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.428794  6.0  0.428872  0.423423
3751  1.002  0.428901  6.0  0.428873  0.423428
3752  1.002  0.429008  6.0  0.428874  0.423434
3753  1.003  0.429115  6.0  0.428874  0.423440

3750
interpolation

/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-17361>:2: RuntimeWarning: overflow encountered in exp
  return _a2_**2*(x1 + exp(2*_a2_ + 2*_a6_ + 2*cos(_a7_*x1)))**2

         x1         y  rep    ymodel      ybms
3745  0.997  0.173654  7.0  0.177066  0.149206
3746  0.998  0.173884  7.0  0.177345  0.149433
3747  0.998  0.174114  7.0  0.177624  0.149660
3748  0.999  0.174344  7.0  0.177903  0.149887

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.174804  7.0  0.178461  0.150343
3751  1.002  0.175034  7.0  0.178739  0.150571
3752  1.002  0.175264  7.0  0.179018  0.150799
3753  1.003  0.175494  7.0  0.179297  0.151027

3750
interpolation

/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(

         x1         y  rep    ymodel      ybms
3745  0.997  0.261188  8.0  0.275705  0.261145
3746  0.998  0.261362  8.0  0.276026  0.261327
3747  0.998  0.261535  8.0  0.276347  0.261509
3748  0.999  0.261709  8.0  0.276669  0.261690

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.262056  8.0  0.277311  0.262052
3751  1.002  0.262229  8.0  0.277632  0.262232
3752  1.002  0.262402  8.0  0.277954  0.262412
3753  1.003  0.262576  8.0  0.278275  0.262591

3750
interpolation

         x1        y  rep    ymodel      ybms
3745  0.997  0.64259  9.0  0.650025  0.617069
3746  0.998  0.64247  9.0  0.649947  0.616916
3747  0.998  0.64235  9.0  0.649870  0.616764
3748  0.999  0.64223  9.0  0.649793  0.616612

extrapolation

         x1        y  rep    ymodel      ybms
3750  1.001  0.64199  9.0  0.649639  0.616308
3751  1.002  0.64187  9.0  0.649562  0.616157
3752  1.002  0.64175  9.0  0.649486  0.616005
3753  1.003  0.64163  9.0  0.649409  0.615854

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.360683  0.0  0.364125  0.353232
3746  0.998  0.360826  0.0  0.364307  0.353314
3747  0.998  0.360969  0.0  0.364489  0.353395
3748  0.999  0.361111  0.0  0.364671  0.353476

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.361396  0.0  0.365035  0.353638
3751  1.002  0.361539  0.0  0.365217  0.353719
3752  1.002  0.361681  0.0  0.365399  0.353800
3753  1.003  0.361824  0.0  0.365582  0.353881

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.875844  1.0  0.907794  0.910610
3746  0.998  0.875274  1.0  0.907744  0.910661
3747  0.998  0.874704  1.0  0.907695  0.910713
3748  0.999  0.874135  1.0  0.907646  0.910766

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.872995  1.0  0.907548  0.910874
3751  1.002  0.872426  1.0  0.907499  0.910929
3752  1.002  0.871856  1.0  0.907450  0.910986
3753  1.003  0.871287  1.0  0.907401  0.911043

3750
interpolation

<lambdifygenerated-17481>:2: RuntimeWarning: invalid value encountered in power
  return _a4_*x1**(-x1) + x1
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-17482>:2: RuntimeWarning: invalid value encountered in power
  return _a4_*x1**(-x1) + x1
<lambdifygenerated-17483>:2: RuntimeWarning: invalid value encountered in power
  return _a4_*(2*x1)**(-x1) + x1
<lambdifygenerated-17484>:2: RuntimeWarning: invalid value encountered in power
  return _a4_*(2*x1)**(-x1) + x1
<lambdifygenerated-17485>:2: RuntimeWarning: invalid value encountered in power
  return _a4_*(_a1_ + x1)**(-x1) + x1
<lambdifygenerated-17486>:2: RuntimeWarning: invalid value encountered in power
  return _a4_*(_a1_ + x1)**(-x1) + x1
<lambdifygenerated-17487>:2: RuntimeWarning: invalid value encountered in power
  return _a4_*(_a1_ + x1)**(-x1) + x1
<lambdifygenerated-17488>:2: RuntimeWarning: invalid value encountered in power
  return _a4_*(_a1_ + x1)**(-x1) + x1
<lambdifygenerated-17489>:2: RuntimeWarning: invalid value encountered in power
  return _a4_*(_a1_ + x1)**(-x1) + x1
<lambdifygenerated-17490>:2: RuntimeWarning: invalid value encountered in power
  return _a4_*(_a1_ + x1)**(-x1) + x1
<lambdifygenerated-17491>:2: RuntimeWarning: invalid value encountered in power
  return _a3_ + _a4_*(_a1_ + x1)**(-x1)
<lambdifygenerated-17492>:2: RuntimeWarning: invalid value encountered in power
  return _a3_ + _a4_*(_a1_ + x1)**(-x1)
<lambdifygenerated-17493>:2: RuntimeWarning: invalid value encountered in power
  return _a3_ + _a4_*(_a1_ + x1)**(-x1)
<lambdifygenerated-17494>:2: RuntimeWarning: invalid value encountered in power
  return _a3_ + _a4_*(_a1_ + x1)**(-x1)
<lambdifygenerated-17495>:2: RuntimeWarning: invalid value encountered in power
  return _a3_ + _a4_*(_a1_ + x1)**(-x1)
<lambdifygenerated-17496>:2: RuntimeWarning: invalid value encountered in power
  return _a3_ + _a4_*(_a1_ + x1)**(-x1)

         x1         y  rep    ymodel      ybms
3745  0.997  0.997734  2.0  0.996225  0.992285
3746  0.998  0.997761  2.0  0.996241  0.992306
3747  0.998  0.997787  2.0  0.996257  0.992326
3748  0.999  0.997814  2.0  0.996272  0.992347

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.997867  2.0  0.996304  0.992388
3751  1.002  0.997894  2.0  0.996319  0.992408
3752  1.002  0.997921  2.0  0.996335  0.992429
3753  1.003  0.997948  2.0  0.996350  0.992449

<lambdifygenerated-17501>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1
<lambdifygenerated-17502>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.689029  3.0  0.686209  0.670228
3746  0.998  0.688777  3.0  0.685910  0.669720
3747  0.998  0.688525  3.0  0.685611  0.669211
3748  0.999  0.688273  3.0  0.685312  0.668701

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.687768  3.0  0.684716  0.667680
3751  1.002  0.687516  3.0  0.684419  0.667169
3752  1.002  0.687264  3.0  0.684121  0.666657
3753  1.003  0.687012  3.0  0.683824  0.666144

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.661298  4.0  0.623852  0.575001
3746  0.998  0.661485  4.0  0.623943  0.574903
3747  0.998  0.661672  4.0  0.624033  0.574805
3748  0.999  0.661858  4.0  0.624124  0.574707

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.662232  4.0  0.624307  0.574511
3751  1.002  0.662419  4.0  0.624398  0.574413
3752  1.002  0.662605  4.0  0.624490  0.574315
3753  1.003  0.662792  4.0  0.624581  0.574217

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.956369  5.0  0.951206  0.981046
3746  0.998  0.956259  5.0  0.951034  0.981046
3747  0.998  0.956150  5.0  0.950863  0.981046
3748  0.999  0.956040  5.0  0.950691  0.981046

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.955822  5.0  0.950347  0.981046
3751  1.002  0.955712  5.0  0.950175  0.981046
3752  1.002  0.955603  5.0  0.950004  0.981046
3753  1.003  0.955493  5.0  0.949832  0.981046

3750
interpolation

<lambdifygenerated-17555>:2: RuntimeWarning: invalid value encountered in power
  return (x1*x1**x1 + x1)**2
<lambdifygenerated-17556>:2: RuntimeWarning: invalid value encountered in power
  return (x1*x1**x1 + x1)**2

         x1         y  rep    ymodel      ybms
3745  0.997  0.428260  6.0  0.430932  0.422203
3746  0.998  0.428367  6.0  0.430880  0.422211
3747  0.998  0.428474  6.0  0.430827  0.422219
3748  0.999  0.428581  6.0  0.430774  0.422226

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.428794  6.0  0.430664  0.422242
3751  1.002  0.428901  6.0  0.430608  0.422250
3752  1.002  0.429008  6.0  0.430552  0.422257
3753  1.003  0.429115  6.0  0.430494  0.422265

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.173654  7.0  0.157187  0.187476
3746  0.998  0.173884  7.0  0.157369  0.187810
3747  0.998  0.174114  7.0  0.157552  0.188145
3748  0.999  0.174344  7.0  0.157735  0.188480

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.174804  7.0  0.158100  0.189151
3751  1.002  0.175034  7.0  0.158283  0.189487
3752  1.002  0.175264  7.0  0.158466  0.189823
3753  1.003  0.175494  7.0  0.158649  0.190159

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.261188  8.0  0.270068  0.262591
3746  0.998  0.261362  8.0  0.270341  0.262743
3747  0.998  0.261535  8.0  0.270614  0.262895
3748  0.999  0.261709  8.0  0.270887  0.263046

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.262056  8.0  0.271433  0.263346
3751  1.002  0.262229  8.0  0.271706  0.263495
3752  1.002  0.262402  8.0  0.271979  0.263643
3753  1.003  0.262576  8.0  0.272251  0.263791

3750
interpolation

         x1        y  rep    ymodel      ybms
3745  0.997  0.64259  9.0  0.640529  0.643446
3746  0.998  0.64247  9.0  0.640349  0.643281
3747  0.998  0.64235  9.0  0.640169  0.643117
3748  0.999  0.64223  9.0  0.639990  0.642952

extrapolation

         x1        y  rep    ymodel      ybms
3750  1.001  0.64199  9.0  0.639629  0.642623
3751  1.002  0.64187  9.0  0.639449  0.642458
3752  1.002  0.64175  9.0  0.639268  0.642293
3753  1.003  0.64163  9.0  0.639088  0.642128

3750
interpolation

<lambdifygenerated-17679>:2: RuntimeWarning: invalid value encountered in power
  return x1*x1**x1
<lambdifygenerated-17680>:2: RuntimeWarning: invalid value encountered in power
  return x1*x1**x1
<lambdifygenerated-17681>:2: RuntimeWarning: invalid value encountered in power
  return x1*sinh(x1)**x1
<lambdifygenerated-17682>:2: RuntimeWarning: invalid value encountered in power
  return x1*sinh(x1)**x1
<lambdifygenerated-17683>:2: RuntimeWarning: invalid value encountered in power
  return x1*sinh(x1**x1)**x1
<lambdifygenerated-17684>:2: RuntimeWarning: invalid value encountered in power
  return x1*sinh(x1**x1)**x1
<lambdifygenerated-17687>:2: RuntimeWarning: invalid value encountered in power
  return x1*sinh((_a4_*x1)**x1)**x1
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-17688>:2: RuntimeWarning: invalid value encountered in power
  return x1*sinh((_a4_*x1)**x1)**x1
<lambdifygenerated-17693>:2: RuntimeWarning: overflow encountered in sinh
  return x1*sinh((_a4_**2)**x1)**_a2_
<lambdifygenerated-17694>:2: RuntimeWarning: overflow encountered in sinh
  return x1*sinh((_a4_**2)**x1)**_a2_
<lambdifygenerated-17695>:2: RuntimeWarning: overflow encountered in sinh
  return _a4_*sinh((_a4_**2)**x1)**_a2_

         x1         y  rep    ymodel      ybms
3745  0.997  0.360683  0.0  0.345279  0.356094
3746  0.998  0.360826  0.0  0.345360  0.356230
3747  0.998  0.360969  0.0  0.345442  0.356366
3748  0.999  0.361111  0.0  0.345523  0.356502

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.361396  0.0  0.345686  0.356774
3751  1.002  0.361539  0.0  0.345767  0.356910
3752  1.002  0.361681  0.0  0.345848  0.357046
3753  1.003  0.361824  0.0  0.345929  0.357182

3750
interpolation

<lambdifygenerated-17717>:2: RuntimeWarning: invalid value encountered in power
  return _a0_*sin(x1)**2 + x1**x1
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-17718>:2: RuntimeWarning: invalid value encountered in power
  return _a0_*sin(x1)**2 + x1**x1

         x1         y  rep    ymodel      ybms
3745  0.997  0.875844  1.0  0.886539  0.884556
3746  0.998  0.875274  1.0  0.886419  0.884444
3747  0.998  0.874704  1.0  0.886298  0.884333
3748  0.999  0.874135  1.0  0.886178  0.884222

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.872995  1.0  0.885938  0.884000
3751  1.002  0.872426  1.0  0.885817  0.883889
3752  1.002  0.871856  1.0  0.885697  0.883778
3753  1.003  0.871287  1.0  0.885576  0.883667

3750
interpolation

<lambdifygenerated-17731>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1
<lambdifygenerated-17732>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1

         x1         y  rep    ymodel      ybms
3745  0.997  0.997734  2.0  0.956476  0.999265
3746  0.998  0.997761  2.0  0.956216  0.999252
3747  0.998  0.997787  2.0  0.955954  0.999238
3748  0.999  0.997814  2.0  0.955693  0.999225

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.997867  2.0  0.955167  0.999197
3751  1.002  0.997894  2.0  0.954903  0.999183
3752  1.002  0.997921  2.0  0.954639  0.999169
3753  1.003  0.997948  2.0  0.954373  0.999154

3750
interpolation

<lambdifygenerated-17753>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1
<lambdifygenerated-17754>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1
<lambdifygenerated-17757>:2: RuntimeWarning: invalid value encountered in power
  return _a5_**(x1**x1)
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-17758>:2: RuntimeWarning: invalid value encountered in power
  return _a5_**(x1**x1)

         x1         y  rep    ymodel      ybms
3745  0.997  0.689029  3.0  0.703224  0.677366
3746  0.998  0.688777  3.0  0.703064  0.676902
3747  0.998  0.688525  3.0  0.702904  0.676436
3748  0.999  0.688273  3.0  0.702745  0.675971

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.687768  3.0  0.702428  0.675037
3751  1.002  0.687516  3.0  0.702270  0.674570
3752  1.002  0.687264  3.0  0.702112  0.674102
3753  1.003  0.687012  3.0  0.701955  0.673634

3750
interpolation

<lambdifygenerated-17779>:2: RuntimeWarning: invalid value encountered in power
  return (_a3_ + sin(x1**x1))/x1
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-17780>:2: RuntimeWarning: invalid value encountered in power
  return (_a3_ + sin(x1**x1))/x1

         x1         y  rep    ymodel      ybms
3745  0.997  0.661298  4.0  0.668367  0.662413
3746  0.998  0.661485  4.0  0.668534  0.662647
3747  0.998  0.661672  4.0  0.668701  0.662883
3748  0.999  0.661858  4.0  0.668868  0.663119

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.662232  4.0  0.669202  0.663593
3751  1.002  0.662419  4.0  0.669369  0.663832
3752  1.002  0.662605  4.0  0.669535  0.664070
3753  1.003  0.662792  4.0  0.669702  0.664310

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.956369  5.0  0.951181  0.987675
3746  0.998  0.956259  5.0  0.951044  0.987675
3747  0.998  0.956150  5.0  0.950907  0.987675
3748  0.999  0.956040  5.0  0.950770  0.987675

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.955822  5.0  0.950496  0.987675
3751  1.002  0.955712  5.0  0.950359  0.987675
3752  1.002  0.955603  5.0  0.950222  0.987675
3753  1.003  0.955493  5.0  0.950085  0.987675

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.428260  6.0  0.404597  0.414443
3746  0.998  0.428367  6.0  0.404647  0.414449
3747  0.998  0.428474  6.0  0.404696  0.414454
3748  0.999  0.428581  6.0  0.404746  0.414460

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.428794  6.0  0.404845  0.414471
3751  1.002  0.428901  6.0  0.404895  0.414476
3752  1.002  0.429008  6.0  0.404944  0.414482
3753  1.003  0.429115  6.0  0.404994  0.414487

3750
interpolation

/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(

         x1         y  rep    ymodel      ybms
3745  0.997  0.173654  7.0  0.141601  0.149610
3746  0.998  0.173884  7.0  0.141760  0.149840
3747  0.998  0.174114  7.0  0.141920  0.150071
3748  0.999  0.174344  7.0  0.142079  0.150302

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.174804  7.0  0.142398  0.150764
3751  1.002  0.175034  7.0  0.142558  0.150995
3752  1.002  0.175264  7.0  0.142718  0.151227
3753  1.003  0.175494  7.0  0.142877  0.151459

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.261188  8.0  0.253006  0.236240
3746  0.998  0.261362  8.0  0.253156  0.236406
3747  0.998  0.261535  8.0  0.253305  0.236571
3748  0.999  0.261709  8.0  0.253455  0.236736

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.262056  8.0  0.253752  0.237066
3751  1.002  0.262229  8.0  0.253900  0.237230
3752  1.002  0.262402  8.0  0.254049  0.237394
3753  1.003  0.262576  8.0  0.254196  0.237559

3750
interpolation

         x1        y  rep    ymodel      ybms
3745  0.997  0.64259  9.0  0.652863  0.623914
3746  0.998  0.64247  9.0  0.652777  0.623837
3747  0.998  0.64235  9.0  0.652690  0.623761
3748  0.999  0.64223  9.0  0.652604  0.623684

extrapolation

         x1        y  rep    ymodel      ybms
3750  1.001  0.64199  9.0  0.652432  0.623533
3751  1.002  0.64187  9.0  0.652346  0.623458
3752  1.002  0.64175  9.0  0.652260  0.623383
3753  1.003  0.64163  9.0  0.652174  0.623309

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.360683  0.0  0.379938  0.358020
3746  0.998  0.360826  0.0  0.380147  0.358104
3747  0.998  0.360969  0.0  0.380356  0.358188
3748  0.999  0.361111  0.0  0.380565  0.358273

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.361396  0.0  0.380984  0.358441
3751  1.002  0.361539  0.0  0.381193  0.358525
3752  1.002  0.361681  0.0  0.381403  0.358609
3753  1.003  0.361824  0.0  0.381612  0.358692

3750
interpolation

/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(

         x1         y  rep    ymodel      ybms
3745  0.997  0.875844  1.0  0.913573  0.908139
3746  0.998  0.875274  1.0  0.913512  0.908198
3747  0.998  0.874704  1.0  0.913451  0.908259
3748  0.999  0.874135  1.0  0.913390  0.908320

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.872995  1.0  0.913269  0.908445
3751  1.002  0.872426  1.0  0.913208  0.908509
3752  1.002  0.871856  1.0  0.913147  0.908574
3753  1.003  0.871287  1.0  0.913086  0.908640

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.997734  2.0  1.020739  0.999958
3746  0.998  0.997761  2.0  1.020787  0.999955
3747  0.998  0.997787  2.0  1.020836  0.999952
3748  0.999  0.997814  2.0  1.020885  0.999949

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.997867  2.0  1.020982  0.999943
3751  1.002  0.997894  2.0  1.021030  0.999939
3752  1.002  0.997921  2.0  1.021079  0.999936
3753  1.003  0.997948  2.0  1.021127  0.999932

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.689029  3.0  0.704227  0.680739
3746  0.998  0.688777  3.0  0.704030  0.680257
3747  0.998  0.688525  3.0  0.703833  0.679774
3748  0.999  0.688273  3.0  0.703636  0.679291

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.687768  3.0  0.703243  0.678322
3751  1.002  0.687516  3.0  0.703047  0.677837
3752  1.002  0.687264  3.0  0.702851  0.677350
3753  1.003  0.687012  3.0  0.702656  0.676864

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.661298  4.0  0.627968  0.663986
3746  0.998  0.661485  4.0  0.628006  0.664329
3747  0.998  0.661672  4.0  0.628043  0.664673
3748  0.999  0.661858  4.0  0.628081  0.665019

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.662232  4.0  0.628156  0.665714
3751  1.002  0.662419  4.0  0.628194  0.666063
3752  1.002  0.662605  4.0  0.628232  0.666413
3753  1.003  0.662792  4.0  0.628269  0.666764

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.956369  5.0  0.955505  0.986805
3746  0.998  0.956259  5.0  0.955414  0.986805
3747  0.998  0.956150  5.0  0.955324  0.986805
3748  0.999  0.956040  5.0  0.955234  0.986805

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.955822  5.0  0.955053  0.986805
3751  1.002  0.955712  5.0  0.954963  0.986805
3752  1.002  0.955603  5.0  0.954872  0.986805
3753  1.003  0.955493  5.0  0.954782  0.986805

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.428260  6.0  0.405537  0.402617
3746  0.998  0.428367  6.0  0.405517  0.402562
3747  0.998  0.428474  6.0  0.405496  0.402507
3748  0.999  0.428581  6.0  0.405476  0.402452

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.428794  6.0  0.405436  0.402341
3751  1.002  0.428901  6.0  0.405416  0.402285
3752  1.002  0.429008  6.0  0.405396  0.402230
3753  1.003  0.429115  6.0  0.405375  0.402174

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.173654  7.0  0.176907  0.166376
3746  0.998  0.173884  7.0  0.177183  0.166642
3747  0.998  0.174114  7.0  0.177459  0.166909
3748  0.999  0.174344  7.0  0.177735  0.167176

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.174804  7.0  0.178287  0.167711
3751  1.002  0.175034  7.0  0.178563  0.167979
3752  1.002  0.175264  7.0  0.178838  0.168247
3753  1.003  0.175494  7.0  0.179114  0.168515

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.261188  8.0  0.249024  0.240770
3746  0.998  0.261362  8.0  0.249187  0.240933
3747  0.998  0.261535  8.0  0.249351  0.241096
3748  0.999  0.261709  8.0  0.249514  0.241259

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.262056  8.0  0.249839  0.241584
3751  1.002  0.262229  8.0  0.250002  0.241747
3752  1.002  0.262402  8.0  0.250164  0.241909
3753  1.003  0.262576  8.0  0.250326  0.242071

3750
interpolation

         x1        y  rep    ymodel      ybms
3745  0.997  0.64259  9.0  0.635764  0.641107
3746  0.998  0.64247  9.0  0.635596  0.640999
3747  0.998  0.64235  9.0  0.635427  0.640891
3748  0.999  0.64223  9.0  0.635259  0.640784

extrapolation

         x1        y  rep    ymodel      ybms
3750  1.001  0.64199  9.0  0.634922  0.640569
3751  1.002  0.64187  9.0  0.634754  0.640462
3752  1.002  0.64175  9.0  0.634586  0.640355
3753  1.003  0.64163  9.0  0.634418  0.640248

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.360683  0.0  0.354008  0.364352
3746  0.998  0.360826  0.0  0.354106  0.364438
3747  0.998  0.360969  0.0  0.354204  0.364524
3748  0.999  0.361111  0.0  0.354301  0.364610

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.361396  0.0  0.354497  0.364781
3751  1.002  0.361539  0.0  0.354594  0.364866
3752  1.002  0.361681  0.0  0.354691  0.364952
3753  1.003  0.361824  0.0  0.354789  0.365037

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.875844  1.0  0.887584  0.866811
3746  0.998  0.875274  1.0  0.887466  0.866563
3747  0.998  0.874704  1.0  0.887348  0.866315
3748  0.999  0.874135  1.0  0.887229  0.866066

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.872995  1.0  0.886993  0.865568
3751  1.002  0.872426  1.0  0.886874  0.865319
3752  1.002  0.871856  1.0  0.886756  0.865070
3753  1.003  0.871287  1.0  0.886637  0.864820

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.997734  2.0  0.997890  0.999759
3746  0.998  0.997761  2.0  0.997905  0.999752
3747  0.998  0.997787  2.0  0.997921  0.999745
3748  0.999  0.997814  2.0  0.997936  0.999738

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.997867  2.0  0.997966  0.999723
3751  1.002  0.997894  2.0  0.997982  0.999716
3752  1.002  0.997921  2.0  0.997997  0.999708
3753  1.003  0.997948  2.0  0.998012  0.999701

3750
interpolation

<lambdifygenerated-18217>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1
<lambdifygenerated-18218>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1
<lambdifygenerated-18221>:2: RuntimeWarning: invalid value encountered in power
  return _a5_**(x1**x1)
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-18222>:2: RuntimeWarning: invalid value encountered in power
  return _a5_**(x1**x1)

         x1         y  rep    ymodel      ybms
3745  0.997  0.689029  3.0  0.688416  0.678913
3746  0.998  0.688777  3.0  0.688055  0.678425
3747  0.998  0.688525  3.0  0.687694  0.677936
3748  0.999  0.688273  3.0  0.687334  0.677447

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.687768  3.0  0.686613  0.676468
3751  1.002  0.687516  3.0  0.686252  0.675977
3752  1.002  0.687264  3.0  0.685892  0.675486
3753  1.003  0.687012  3.0  0.685532  0.674994

3750
interpolation

<lambdifygenerated-18237>:2: RuntimeWarning: invalid value encountered in power
  return x1*x1**x1
<lambdifygenerated-18238>:2: RuntimeWarning: invalid value encountered in power
  return x1*x1**x1

         x1         y  rep    ymodel      ybms
3745  0.997  0.661298  4.0  0.626727  0.595636
3746  0.998  0.661485  4.0  0.626754  0.595563
3747  0.998  0.661672  4.0  0.626781  0.595489
3748  0.999  0.661858  4.0  0.626809  0.595416

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.662232  4.0  0.626864  0.595270
3751  1.002  0.662419  4.0  0.626891  0.595196
3752  1.002  0.662605  4.0  0.626919  0.595123
3753  1.003  0.662792  4.0  0.626947  0.595050

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.956369  5.0  0.971556  0.982056
3746  0.998  0.956259  5.0  0.971562  0.982056
3747  0.998  0.956150  5.0  0.971568  0.982056
3748  0.999  0.956040  5.0  0.971574  0.982056

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.955822  5.0  0.971586  0.982056
3751  1.002  0.955712  5.0  0.971593  0.982056
3752  1.002  0.955603  5.0  0.971599  0.982056
3753  1.003  0.955493  5.0  0.971606  0.982056

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.428260  6.0  0.415399  0.425410
3746  0.998  0.428367  6.0  0.415478  0.425417
3747  0.998  0.428474  6.0  0.415558  0.425424
3748  0.999  0.428581  6.0  0.415638  0.425432

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.428794  6.0  0.415801  0.425446
3751  1.002  0.428901  6.0  0.415884  0.425454
3752  1.002  0.429008  6.0  0.415967  0.425461
3753  1.003  0.429115  6.0  0.416051  0.425468

3750
interpolation

/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(

         x1         y  rep    ymodel      ybms
3745  0.997  0.173654  7.0  0.179092  0.127799
3746  0.998  0.173884  7.0  0.179469  0.127844
3747  0.998  0.174114  7.0  0.179847  0.127889
3748  0.999  0.174344  7.0  0.180225  0.127934

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.174804  7.0  0.180984  0.128024
3751  1.002  0.175034  7.0  0.181365  0.128069
3752  1.002  0.175264  7.0  0.181746  0.128114
3753  1.003  0.175494  7.0  0.182128  0.128159

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.261188  8.0  0.258492  0.239683
3746  0.998  0.261362  8.0  0.259117  0.239850
3747  0.998  0.261535  8.0  0.259744  0.240018
3748  0.999  0.261709  8.0  0.260372  0.240185

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.262056  8.0  0.261634  0.240518
3751  1.002  0.262229  8.0  0.262267  0.240684
3752  1.002  0.262402  8.0  0.262902  0.240851
3753  1.003  0.262576  8.0  0.263539  0.241017

3750
interpolation

<lambdifygenerated-18343>:2: RuntimeWarning: invalid value encountered in power
  return cos(x1 + x1**x1)
<lambdifygenerated-18344>:2: RuntimeWarning: invalid value encountered in power
  return cos(x1 + x1**x1)

         x1        y  rep    ymodel      ybms
3745  0.997  0.64259  9.0  0.711663  0.678400
3746  0.998  0.64247  9.0  0.713018  0.678362
3747  0.998  0.64235  9.0  0.714381  0.678324
3748  0.999  0.64223  9.0  0.715753  0.678285

extrapolation

         x1        y  rep    ymodel      ybms
3750  1.001  0.64199  9.0  0.718523  0.678209
3751  1.002  0.64187  9.0  0.719921  0.678172
3752  1.002  0.64175  9.0  0.721326  0.678134
3753  1.003  0.64163  9.0  0.722740  0.678096

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.360683  0.0  0.337098  0.350384
3746  0.998  0.360826  0.0  0.337152  0.350466
3747  0.998  0.360969  0.0  0.337205  0.350549
3748  0.999  0.361111  0.0  0.337259  0.350631

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.361396  0.0  0.337365  0.350796
3751  1.002  0.361539  0.0  0.337419  0.350878
3752  1.002  0.361681  0.0  0.337472  0.350960
3753  1.003  0.361824  0.0  0.337525  0.351042

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.875844  1.0  0.908039  0.964376
3746  0.998  0.875274  1.0  0.907980  0.964376
3747  0.998  0.874704  1.0  0.907922  0.964376
3748  0.999  0.874135  1.0  0.907863  0.964376

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.872995  1.0  0.907746  0.964376
3751  1.002  0.872426  1.0  0.907688  0.964376
3752  1.002  0.871856  1.0  0.907630  0.964376
3753  1.003  0.871287  1.0  0.907572  0.964376

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.997734  2.0  0.997306  0.999993
3746  0.998  0.997761  2.0  0.997308  0.999994
3747  0.998  0.997787  2.0  0.997310  0.999995
3748  0.999  0.997814  2.0  0.997312  0.999996

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.997867  2.0  0.997315  0.999997
3751  1.002  0.997894  2.0  0.997317  0.999998
3752  1.002  0.997921  2.0  0.997319  0.999999
3753  1.003  0.997948  2.0  0.997320  0.999999

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.689029  3.0  0.692108  0.687428
3746  0.998  0.688777  3.0  0.691791  0.686955
3747  0.998  0.688525  3.0  0.691475  0.686482
3748  0.999  0.688273  3.0  0.691159  0.686008

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.687768  3.0  0.690527  0.685058
3751  1.002  0.687516  3.0  0.690211  0.684582
3752  1.002  0.687264  3.0  0.689896  0.684105
3753  1.003  0.687012  3.0  0.689581  0.683628

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.661298  4.0  0.552930  0.570167
3746  0.998  0.661485  4.0  0.551938  0.570072
3747  0.998  0.661672  4.0  0.550940  0.569977
3748  0.999  0.661858  4.0  0.549937  0.569883

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.662232  4.0  0.547915  0.569693
3751  1.002  0.662419  4.0  0.546895  0.569598
3752  1.002  0.662605  4.0  0.545870  0.569504
3753  1.003  0.662792  4.0  0.544840  0.569409

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.956369  5.0  0.957118  0.982998
3746  0.998  0.956259  5.0  0.956867  0.982998
3747  0.998  0.956150  5.0  0.956613  0.982998
3748  0.999  0.956040  5.0  0.956358  0.982998

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.955822  5.0  0.955841  0.982998
3751  1.002  0.955712  5.0  0.955580  0.982998
3752  1.002  0.955603  5.0  0.955316  0.982998
3753  1.003  0.955493  5.0  0.955051  0.982998

3750

<lambdifygenerated-18465>:2: RuntimeWarning: invalid value encountered in power
  return _a7_*x1**x1
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-18466>:2: RuntimeWarning: invalid value encountered in power
  return _a7_*x1**x1
<lambdifygenerated-18469>:2: RuntimeWarning: invalid value encountered in power
  return _a1_**(x1**x1)*_a7_
<lambdifygenerated-18470>:2: RuntimeWarning: invalid value encountered in power
  return _a1_**(x1**x1)*_a7_

interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.428260  6.0  0.444395  0.419254
3746  0.998  0.428367  6.0  0.444179  0.419259
3747  0.998  0.428474  6.0  0.443958  0.419264
3748  0.999  0.428581  6.0  0.443733  0.419269

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.428794  6.0  0.443270  0.419279
3751  1.002  0.428901  6.0  0.443032  0.419285
3752  1.002  0.429008  6.0  0.442789  0.419290
3753  1.003  0.429115  6.0  0.442542  0.419295

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.173654  7.0  0.158192  0.136353
3746  0.998  0.173884  7.0  0.158180  0.136572
3747  0.998  0.174114  7.0  0.158166  0.136791
3748  0.999  0.174344  7.0  0.158150  0.137011

extrapolation

         x1         y  rep    ymodel     ybms
3750  1.001  0.174804  7.0  0.158112  0.13745
3751  1.002  0.175034  7.0  0.158091  0.13767
3752  1.002  0.175264  7.0  0.158067  0.13789
3753  1.003  0.175494  7.0  0.158042  0.13811

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.261188  8.0  0.289581  0.247902
3746  0.998  0.261362  8.0  0.289771  0.248063
3747  0.998  0.261535  8.0  0.289959  0.248224
3748  0.999  0.261709  8.0  0.290147  0.248385

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.262056  8.0  0.290521  0.248706
3751  1.002  0.262229  8.0  0.290707  0.248867
3752  1.002  0.262402  8.0  0.290892  0.249027
3753  1.003  0.262576  8.0  0.291076  0.249187

3750
interpolation

<lambdifygenerated-18527>:2: RuntimeWarning: invalid value encountered in power
  return sin(_a7_*x1**x1)
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-18528>:2: RuntimeWarning: invalid value encountered in power
  return sin(_a7_*x1**x1)

         x1        y  rep    ymodel      ybms
3745  0.997  0.64259  9.0  0.665864  0.652795
3746  0.998  0.64247  9.0  0.665857  0.652684
3747  0.998  0.64235  9.0  0.665850  0.652574
3748  0.999  0.64223  9.0  0.665843  0.652463

extrapolation

         x1        y  rep    ymodel      ybms
3750  1.001  0.64199  9.0  0.665830  0.652242
3751  1.002  0.64187  9.0  0.665823  0.652132
3752  1.002  0.64175  9.0  0.665817  0.652021
3753  1.003  0.64163  9.0  0.665811  0.651911

3750
interpolation

<lambdifygenerated-18545>:2: RuntimeWarning: invalid value encountered in power
  return x1*x1**x1
<lambdifygenerated-18546>:2: RuntimeWarning: invalid value encountered in power
  return x1*x1**x1
<lambdifygenerated-18549>:2: RuntimeWarning: invalid value encountered in power
  return _a5_**(x1**x1)*x1
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-18550>:2: RuntimeWarning: invalid value encountered in power
  return _a5_**(x1**x1)*x1
<lambdifygenerated-18551>:2: RuntimeWarning: invalid value encountered in power
  return _a5_**(_a7_**x1)*x1
<lambdifygenerated-18555>:2: RuntimeWarning: invalid value encountered in power
  return _a5_*_a5_**(_a7_**x1)

         x1         y  rep    ymodel      ybms
3745  0.997  0.360683  0.0  0.380618  0.350842
3746  0.998  0.360826  0.0  0.380807  0.350923
3747  0.998  0.360969  0.0  0.380995  0.351004
3748  0.999  0.361111  0.0  0.381183  0.351084

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.361396  0.0  0.381559  0.351245
3751  1.002  0.361539  0.0  0.381746  0.351326
3752  1.002  0.361681  0.0  0.381934  0.351406
3753  1.003  0.361824  0.0  0.382122  0.351487

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.875844  1.0  0.915001  0.962676
3746  0.998  0.875274  1.0  0.914945  0.962676
3747  0.998  0.874704  1.0  0.914888  0.962676
3748  0.999  0.874135  1.0  0.914831  0.962676

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.872995  1.0  0.914717  0.962676
3751  1.002  0.872426  1.0  0.914661  0.962676
3752  1.002  0.871856  1.0  0.914604  0.962676
3753  1.003  0.871287  1.0  0.914547  0.962676

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.997734  2.0  1.017596  0.998942
3746  0.998  0.997761  2.0  1.017634  0.998955
3747  0.998  0.997787  2.0  1.017672  0.998968
3748  0.999  0.997814  2.0  1.017710  0.998981

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.997867  2.0  1.017786  0.999007
3751  1.002  0.997894  2.0  1.017824  0.999020
3752  1.002  0.997921  2.0  1.017862  0.999032
3753  1.003  0.997948  2.0  1.017899  0.999045

3750
interpolation

<lambdifygenerated-18595>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1
<lambdifygenerated-18596>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1
<lambdifygenerated-18599>:2: RuntimeWarning: invalid value encountered in power
  return _a7_**(x1**x1)
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-18600>:2: RuntimeWarning: invalid value encountered in power
  return _a7_**(x1**x1)

         x1         y  rep    ymodel      ybms
3745  0.997  0.689029  3.0  0.749903  0.643056
3746  0.998  0.688777  3.0  0.749736  0.642460
3747  0.998  0.688525  3.0  0.749569  0.641864
3748  0.999  0.688273  3.0  0.749402  0.641267

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.687768  3.0  0.749069  0.640072
3751  1.002  0.687516  3.0  0.748903  0.639473
3752  1.002  0.687264  3.0  0.748736  0.638873
3753  1.003  0.687012  3.0  0.748570  0.638273

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.661298  4.0  0.616257  0.579092
3746  0.998  0.661485  4.0  0.616218  0.579000
3747  0.998  0.661672  4.0  0.616180  0.578907
3748  0.999  0.661858  4.0  0.616142  0.578814

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.662232  4.0  0.616065  0.578629
3751  1.002  0.662419  4.0  0.616026  0.578536
3752  1.002  0.662605  4.0  0.615988  0.578443
3753  1.003  0.662792  4.0  0.615949  0.578351

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.956369  5.0  0.936468  0.979983
3746  0.998  0.956259  5.0  0.936263  0.979983
3747  0.998  0.956150  5.0  0.936057  0.979983
3748  0.999  0.956040  5.0  0.935852  0.979983

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.955822  5.0  0.935440  0.979983
3751  1.002  0.955712  5.0  0.935234  0.979983
3752  1.002  0.955603  5.0  0.935028  0.979983
3753  1.003  0.955493  5.0  0.934821  0.979983

3750
interpolation

<lambdifygenerated-18647>:2: RuntimeWarning: invalid value encountered in power
  return (_a6_ + x1**x1)**2
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-18648>:2: RuntimeWarning: invalid value encountered in power
  return (_a6_ + x1**x1)**2

         x1         y  rep    ymodel      ybms
3745  0.997  0.428260  6.0  0.415271  0.406978
3746  0.998  0.428367  6.0  0.415302  0.406978
3747  0.998  0.428474  6.0  0.415332  0.406978
3748  0.999  0.428581  6.0  0.415362  0.406978

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.428794  6.0  0.415422  0.406978
3751  1.002  0.428901  6.0  0.415452  0.406978
3752  1.002  0.429008  6.0  0.415482  0.406978
3753  1.003  0.429115  6.0  0.415512  0.406978

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.173654  7.0  0.122188  0.145151
3746  0.998  0.173884  7.0  0.122262  0.145357
3747  0.998  0.174114  7.0  0.122336  0.145564
3748  0.999  0.174344  7.0  0.122410  0.145770

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.174804  7.0  0.122559  0.146184
3751  1.002  0.175034  7.0  0.122633  0.146391
3752  1.002  0.175264  7.0  0.122707  0.146598
3753  1.003  0.175494  7.0  0.122781  0.146805

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.261188  8.0  0.254134  0.224461
3746  0.998  0.261362  8.0  0.254388  0.224627
3747  0.998  0.261535  8.0  0.254642  0.224792
3748  0.999  0.261709  8.0  0.254896  0.224958

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.262056  8.0  0.255404  0.225289
3751  1.002  0.262229  8.0  0.255657  0.225454
3752  1.002  0.262402  8.0  0.255911  0.225618
3753  1.003  0.262576  8.0  0.256164  0.225783

3750
interpolation

<lambdifygenerated-18709>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1
<lambdifygenerated-18710>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1

         x1        y  rep    ymodel      ybms
3745  0.997  0.64259  9.0  0.640672  0.612299
3746  0.998  0.64247  9.0  0.640549  0.612132
3747  0.998  0.64235  9.0  0.640427  0.611966
3748  0.999  0.64223  9.0  0.640305  0.611799

extrapolation

         x1        y  rep    ymodel      ybms
3750  1.001  0.64199  9.0  0.640061  0.611467
3751  1.002  0.64187  9.0  0.639940  0.611301
3752  1.002  0.64175  9.0  0.639819  0.611135
3753  1.003  0.64163  9.0  0.639697  0.610970

3750
interpolation

<lambdifygenerated-18733>:2: RuntimeWarning: invalid value encountered in power
  return x1 + x1**x1
<lambdifygenerated-18734>:2: RuntimeWarning: invalid value encountered in power
  return x1 + x1**x1

         x1         y  rep    ymodel      ybms
3745  0.997  0.360683  0.0  0.368813  0.346781
3746  0.998  0.360826  0.0  0.369067  0.346911
3747  0.998  0.360969  0.0  0.369321  0.347040
3748  0.999  0.361111  0.0  0.369575  0.347169

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.361396  0.0  0.370084  0.347428
3751  1.002  0.361539  0.0  0.370339  0.347557
3752  1.002  0.361681  0.0  0.370594  0.347687
3753  1.003  0.361824  0.0  0.370850  0.347816

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.875844  1.0  0.899833  0.913713
3746  0.998  0.875274  1.0  0.899745  0.913692
3747  0.998  0.874704  1.0  0.899658  0.913672
3748  0.999  0.874135  1.0  0.899571  0.913651

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.872995  1.0  0.899396  0.913611
3751  1.002  0.872426  1.0  0.899308  0.913591
3752  1.002  0.871856  1.0  0.899220  0.913571
3753  1.003  0.871287  1.0  0.899133  0.913551

3750
interpolation

<lambdifygenerated-18777>:2: RuntimeWarning: invalid value encountered in power
  return _a4_*x1**x1 + x1
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-18778>:2: RuntimeWarning: invalid value encountered in power
  return _a4_*x1**x1 + x1
<lambdifygenerated-18779>:2: RuntimeWarning: invalid value encountered in power
  return _a3_**x1*_a4_ + x1
<lambdifygenerated-18781>:2: RuntimeWarning: invalid value encountered in power
  return _a3_**(x1**x1)*_a4_ + x1
<lambdifygenerated-18782>:2: RuntimeWarning: invalid value encountered in power
  return _a3_**(x1**x1)*_a4_ + x1
<lambdifygenerated-18783>:2: RuntimeWarning: invalid value encountered in power
  return _a3_**(_a5_**x1)*_a4_ + x1
<lambdifygenerated-18787>:2: RuntimeWarning: invalid value encountered in power
  return _a3_**(_a5_**x1)*_a4_ + _a4_

         x1         y  rep    ymodel      ybms
3745  0.997  0.997734  2.0  0.985193  0.969892
3746  0.998  0.997761  2.0  0.985228  0.969905
3747  0.998  0.997787  2.0  0.985262  0.969917
3748  0.999  0.997814  2.0  0.985297  0.969930

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.997867  2.0  0.985366  0.969955
3751  1.002  0.997894  2.0  0.985400  0.969968
3752  1.002  0.997921  2.0  0.985434  0.969980
3753  1.003  0.997948  2.0  0.985468  0.969993

3750
interpolation

<lambdifygenerated-18797>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1
<lambdifygenerated-18798>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1
<lambdifygenerated-18801>:2: RuntimeWarning: invalid value encountered in power
  return _a0_**(x1**x1)
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-18802>:2: RuntimeWarning: invalid value encountered in power
  return _a0_**(x1**x1)

         x1         y  rep    ymodel      ybms
3745  0.997  0.689029  3.0  0.690478  0.699822
3746  0.998  0.688777  3.0  0.690211  0.699417
3747  0.998  0.688525  3.0  0.689944  0.699013
3748  0.999  0.688273  3.0  0.689677  0.698608

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.687768  3.0  0.689145  0.697796
3751  1.002  0.687516  3.0  0.688880  0.697390
3752  1.002  0.687264  3.0  0.688615  0.696983
3753  1.003  0.687012  3.0  0.688350  0.696576

3750
interpolation

<lambdifygenerated-18819>:2: RuntimeWarning: invalid value encountered in power
  return _a7_ + x1**x1
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-18820>:2: RuntimeWarning: invalid value encountered in power
  return _a7_ + x1**x1

         x1         y  rep    ymodel     ybms
3745  0.997  0.661298  4.0  0.642899  0.62169
3746  0.998  0.661485  4.0  0.642941  0.62169
3747  0.998  0.661672  4.0  0.642983  0.62169
3748  0.999  0.661858  4.0  0.643024  0.62169

extrapolation

         x1         y  rep    ymodel     ybms
3750  1.001  0.662232  4.0  0.643107  0.62169
3751  1.002  0.662419  4.0  0.643148  0.62169
3752  1.002  0.662605  4.0  0.643188  0.62169
3753  1.003  0.662792  4.0  0.643229  0.62169

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.956369  5.0  0.974199  0.985803
3746  0.998  0.956259  5.0  0.974116  0.985803
3747  0.998  0.956150  5.0  0.974033  0.985803
3748  0.999  0.956040  5.0  0.973949  0.985803

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.955822  5.0  0.973782  0.985803
3751  1.002  0.955712  5.0  0.973699  0.985803
3752  1.002  0.955603  5.0  0.973615  0.985803
3753  1.003  0.955493  5.0  0.973532  0.985803

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.428260  6.0  0.406496  0.397029
3746  0.998  0.428367  6.0  0.406374  0.396950
3747  0.998  0.428474  6.0  0.406251  0.396870
3748  0.999  0.428581  6.0  0.406129  0.396791

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.428794  6.0  0.405884  0.396632
3751  1.002  0.428901  6.0  0.405761  0.396552
3752  1.002  0.429008  6.0  0.405637  0.396472
3753  1.003  0.429115  6.0  0.405514  0.396392

3750
interpolation

<lambdifygenerated-18871>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1
<lambdifygenerated-18872>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1

         x1         y  rep    ymodel      ybms
3745  0.997  0.173654  7.0  0.119613  0.156643
3746  0.998  0.173884  7.0  0.119567  0.156852
3747  0.998  0.174114  7.0  0.119521  0.157060
3748  0.999  0.174344  7.0  0.119474  0.157269

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.174804  7.0  0.119381  0.157687
3751  1.002  0.175034  7.0  0.119334  0.157896
3752  1.002  0.175264  7.0  0.119286  0.158105
3753  1.003  0.175494  7.0  0.119239  0.158315

3750
interpolation

<lambdifygenerated-18891>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1
<lambdifygenerated-18892>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1
<lambdifygenerated-18895>:2: RuntimeWarning: invalid value encountered in power
  return _a3_**(x1**x1)
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-18896>:2: RuntimeWarning: invalid value encountered in power
  return _a3_**(x1**x1)
<lambdifygenerated-18897>:2: RuntimeWarning: invalid value encountered in power
  return _a3_**(-x1**x1)
<lambdifygenerated-18898>:2: RuntimeWarning: invalid value encountered in power
  return _a3_**(-x1**x1)

         x1         y  rep    ymodel      ybms
3745  0.997  0.261188  8.0  0.243587  0.228526
3746  0.998  0.261362  8.0  0.243636  0.228661
3747  0.998  0.261535  8.0  0.243684  0.228795
3748  0.999  0.261709  8.0  0.243731  0.228929

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.262056  8.0  0.243823  0.229197
3751  1.002  0.262229  8.0  0.243868  0.229330
3752  1.002  0.262402  8.0  0.243912  0.229464
3753  1.003  0.262576  8.0  0.243956  0.229597

3750
interpolation

<lambdifygenerated-18923>:2: RuntimeWarning: invalid value encountered in power
  return sin(_a0_*x1**x1)
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-18924>:2: RuntimeWarning: invalid value encountered in power
  return sin(_a0_*x1**x1)

         x1        y  rep    ymodel      ybms
3745  0.997  0.64259  9.0  0.639650  0.644771
3746  0.998  0.64247  9.0  0.639514  0.644660
3747  0.998  0.64235  9.0  0.639378  0.644549
3748  0.999  0.64223  9.0  0.639242  0.644438

extrapolation

         x1        y  rep    ymodel      ybms
3750  1.001  0.64199  9.0  0.638970  0.644217
3751  1.002  0.64187  9.0  0.638835  0.644106
3752  1.002  0.64175  9.0  0.638699  0.643996
3753  1.003  0.64163  9.0  0.638564  0.643886

3750
interpolation

<lambdifygenerated-18939>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1
<lambdifygenerated-18940>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1
<lambdifygenerated-18943>:2: RuntimeWarning: invalid value encountered in power
  return _a0_**(x1**x1)
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-18944>:2: RuntimeWarning: invalid value encountered in power
  return _a0_**(x1**x1)
<lambdifygenerated-18945>:2: RuntimeWarning: invalid value encountered in power
  return _a0_**(_a6_**x1)

         x1         y  rep    ymodel      ybms
3745  0.997  0.360683  0.0  0.364454  0.384396
3746  0.998  0.360826  0.0  0.364600  0.384560
3747  0.998  0.360969  0.0  0.364745  0.384725
3748  0.999  0.361111  0.0  0.364891  0.384890

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.361396  0.0  0.365181  0.385220
3751  1.002  0.361539  0.0  0.365326  0.385384
3752  1.002  0.361681  0.0  0.365472  0.385549
3753  1.003  0.361824  0.0  0.365617  0.385714

3750
interpolation

         x1         y  rep    ymodel     ybms
3745  0.997  0.875844  1.0  0.898758  0.95458
3746  0.998  0.875274  1.0  0.898671  0.95458
3747  0.998  0.874704  1.0  0.898584  0.95458
3748  0.999  0.874135  1.0  0.898497  0.95458

extrapolation

         x1         y  rep    ymodel     ybms
3750  1.001  0.872995  1.0  0.898323  0.95458
3751  1.002  0.872426  1.0  0.898235  0.95458
3752  1.002  0.871856  1.0  0.898148  0.95458
3753  1.003  0.871287  1.0  0.898061  0.95458

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.997734  2.0  1.007693  0.999994
3746  0.998  0.997761  2.0  1.007738  0.999995
3747  0.998  0.997787  2.0  1.007783  0.999996
3748  0.999  0.997814  2.0  1.007829  0.999997

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.997867  2.0  1.007919  0.999998
3751  1.002  0.997894  2.0  1.007964  0.999999
3752  1.002  0.997921  2.0  1.008009  0.999999
3753  1.003  0.997948  2.0  1.008054  1.000000

3750
interpolation

         x1         y  rep   ymodel      ybms
3745  0.997  0.689029  3.0  0.66050  0.659951
3746  0.998  0.688777  3.0  0.66015  0.659439
3747  0.998  0.688525  3.0  0.65980  0.658927
3748  0.999  0.688273  3.0  0.65945  0.658415

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.687768  3.0  0.658750  0.657387
3751  1.002  0.687516  3.0  0.658401  0.656872
3752  1.002  0.687264  3.0  0.658051  0.656357
3753  1.003  0.687012  3.0  0.657702  0.655840

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.661298  4.0  0.642571  0.582549
3746  0.998  0.661485  4.0  0.642651  0.582456
3747  0.998  0.661672  4.0  0.642731  0.582364
3748  0.999  0.661858  4.0  0.642811  0.582271

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.662232  4.0  0.642971  0.582085
3751  1.002  0.662419  4.0  0.643051  0.581992
3752  1.002  0.662605  4.0  0.643131  0.581899
3753  1.003  0.662792  4.0  0.643210  0.581806

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.956369  5.0  0.925232  0.979091
3746  0.998  0.956259  5.0  0.924819  0.979091
3747  0.998  0.956150  5.0  0.924404  0.979091
3748  0.999  0.956040  5.0  0.923989  0.979091

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.955822  5.0  0.923156  0.979091
3751  1.002  0.955712  5.0  0.922738  0.979091
3752  1.002  0.955603  5.0  0.922320  0.979091
3753  1.003  0.955493  5.0  0.921900  0.979091

3750

<lambdifygenerated-19037>:2: RuntimeWarning: invalid value encountered in power
  return _a1_*x1**x1
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-19038>:2: RuntimeWarning: invalid value encountered in power
  return _a1_*x1**x1
<lambdifygenerated-19041>:2: RuntimeWarning: invalid value encountered in power
  return _a1_*_a7_**(x1**x1)
<lambdifygenerated-19042>:2: RuntimeWarning: invalid value encountered in power
  return _a1_*_a7_**(x1**x1)

interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.428260  6.0  0.374955  0.406828
3746  0.998  0.428367  6.0  0.374662  0.406832
3747  0.998  0.428474  6.0  0.374368  0.406835
3748  0.999  0.428581  6.0  0.374073  0.406838

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.428794  6.0  0.373479  0.406845
3751  1.002  0.428901  6.0  0.373180  0.406848
3752  1.002  0.429008  6.0  0.372880  0.406851
3753  1.003  0.429115  6.0  0.372580  0.406855

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.173654  7.0  0.144245  0.143882
3746  0.998  0.173884  7.0  0.144410  0.144086
3747  0.998  0.174114  7.0  0.144575  0.144291
3748  0.999  0.174344  7.0  0.144740  0.144496

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.174804  7.0  0.145070  0.144907
3751  1.002  0.175034  7.0  0.145236  0.145112
3752  1.002  0.175264  7.0  0.145401  0.145318
3753  1.003  0.175494  7.0  0.145567  0.145523

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.261188  8.0  0.265876  0.240009
3746  0.998  0.261362  8.0  0.265892  0.240167
3747  0.998  0.261535  8.0  0.265906  0.240326
3748  0.999  0.261709  8.0  0.265919  0.240484

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.262056  8.0  0.265941  0.240800
3751  1.002  0.262229  8.0  0.265950  0.240957
3752  1.002  0.262402  8.0  0.265957  0.241115
3753  1.003  0.262576  8.0  0.265964  0.241272

3750
interpolation

         x1        y  rep    ymodel      ybms
3745  0.997  0.64259  9.0  0.640478  0.732996
3746  0.998  0.64247  9.0  0.640242  0.733331
3747  0.998  0.64235  9.0  0.640006  0.733666
3748  0.999  0.64223  9.0  0.639772  0.734002

extrapolation

         x1        y  rep    ymodel      ybms
3750  1.001  0.64199  9.0  0.639304  0.734678
3751  1.002  0.64187  9.0  0.639071  0.735016
3752  1.002  0.64175  9.0  0.638839  0.735356
3753  1.003  0.64163  9.0  0.638608  0.735697

3750
interpolation

<lambdifygenerated-19121>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1
<lambdifygenerated-19122>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1
<lambdifygenerated-19125>:2: RuntimeWarning: invalid value encountered in power
  return _a6_**exp(x1)
<lambdifygenerated-19127>:2: RuntimeWarning: invalid value encountered in power
  return _a6_**exp(x1**x1)
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-19128>:2: RuntimeWarning: invalid value encountered in power
  return _a6_**exp(x1**x1)
<lambdifygenerated-19129>:2: RuntimeWarning: overflow encountered in exp
  return _a6_**exp(_a6_**x1)
<lambdifygenerated-19130>:2: RuntimeWarning: overflow encountered in exp
  return _a6_**exp(_a6_**x1)
<lambdifygenerated-19131>:2: RuntimeWarning: overflow encountered in exp
  return _a6_**exp(_a6_**x1)
<lambdifygenerated-19132>:2: RuntimeWarning: overflow encountered in exp
  return _a6_**exp(_a6_**x1)
<lambdifygenerated-19133>:2: RuntimeWarning: overflow encountered in exp
  return _a6_**exp(_a6_**x1)
<lambdifygenerated-19134>:2: RuntimeWarning: overflow encountered in exp
  return _a6_**exp(_a6_**x1)
<lambdifygenerated-19135>:2: RuntimeWarning: overflow encountered in exp
  return _a6_**exp(_a6_**x1)
<lambdifygenerated-19136>:2: RuntimeWarning: overflow encountered in exp
  return _a6_**exp(_a6_**x1)

         x1         y  rep    ymodel      ybms
3745  0.997  0.360683  0.0  0.365762  0.361057
3746  0.998  0.360826  0.0  0.365920  0.361153
3747  0.998  0.360969  0.0  0.366078  0.361248
3748  0.999  0.361111  0.0  0.366237  0.361344

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.361396  0.0  0.366553  0.361536
3751  1.002  0.361539  0.0  0.366711  0.361631
3752  1.002  0.361681  0.0  0.366870  0.361727
3753  1.003  0.361824  0.0  0.367028  0.361822

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.875844  1.0  0.872874  0.959495
3746  0.998  0.875274  1.0  0.872737  0.959495
3747  0.998  0.874704  1.0  0.872599  0.959495
3748  0.999  0.874135  1.0  0.872461  0.959495

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.872995  1.0  0.872186  0.959495
3751  1.002  0.872426  1.0  0.872049  0.959495
3752  1.002  0.871856  1.0  0.871911  0.959495
3753  1.003  0.871287  1.0  0.871773  0.959495

3750
interpolation

<lambdifygenerated-19151>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1
<lambdifygenerated-19152>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1

         x1         y  rep    ymodel      ybms
3745  0.997  0.997734  2.0  1.028361  0.995214
3746  0.998  0.997761  2.0  1.028407  0.995178
3747  0.998  0.997787  2.0  1.028453  0.995141
3748  0.999  0.997814  2.0  1.028498  0.995104

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.997867  2.0  1.028589  0.995030
3751  1.002  0.997894  2.0  1.028635  0.994993
3752  1.002  0.997921  2.0  1.028680  0.994955
3753  1.003  0.997948  2.0  1.028726  0.994918

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.689029  3.0  0.758879  0.727390
3746  0.998  0.688777  3.0  0.758710  0.726975
3747  0.998  0.688525  3.0  0.758541  0.726559
3748  0.999  0.688273  3.0  0.758372  0.726142

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.687768  3.0  0.758035  0.725307
3751  1.002  0.687516  3.0  0.757866  0.724888
3752  1.002  0.687264  3.0  0.757698  0.724469
3753  1.003  0.687012  3.0  0.757530  0.724049

3750
interpolation

<lambdifygenerated-19193>:2: RuntimeWarning: invalid value encountered in power
  return _a5_*x1**x1
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-19194>:2: RuntimeWarning: invalid value encountered in power
  return _a5_*x1**x1
<lambdifygenerated-19195>:2: RuntimeWarning: invalid value encountered in power
  return _a5_*_a7_**x1

         x1         y  rep    ymodel      ybms
3745  0.997  0.661298  4.0  0.600686  0.592272
3746  0.998  0.661485  4.0  0.600569  0.592197
3747  0.998  0.661672  4.0  0.600451  0.592122
3748  0.999  0.661858  4.0  0.600333  0.592047

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.662232  4.0  0.600096  0.591897
3751  1.002  0.662419  4.0  0.599977  0.591823
3752  1.002  0.662605  4.0  0.599858  0.591748
3753  1.003  0.662792  4.0  0.599738  0.591673

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.956369  5.0  0.947139  0.983685
3746  0.998  0.956259  5.0  0.946933  0.983685
3747  0.998  0.956150  5.0  0.946726  0.983685
3748  0.999  0.956040  5.0  0.946519  0.983685

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.955822  5.0  0.946104  0.983685
3751  1.002  0.955712  5.0  0.945896  0.983685
3752  1.002  0.955603  5.0  0.945687  0.983685
3753  1.003  0.955493  5.0  0.945478  0.983685

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.428260  6.0  0.380573  0.400590
3746  0.998  0.428367  6.0  0.380421  0.400533
3747  0.998  0.428474  6.0  0.380268  0.400476
3748  0.999  0.428581  6.0  0.380115  0.400419

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.428794  6.0  0.379809  0.400305
3751  1.002  0.428901  6.0  0.379655  0.400248
3752  1.002  0.429008  6.0  0.379502  0.400190
3753  1.003  0.429115  6.0  0.379348  0.400133

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.173654  7.0  0.112470  0.152365
3746  0.998  0.173884  7.0  0.112364  0.152556
3747  0.998  0.174114  7.0  0.112259  0.152747
3748  0.999  0.174344  7.0  0.112153  0.152938

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.174804  7.0  0.111939  0.153320
3751  1.002  0.175034  7.0  0.111832  0.153512
3752  1.002  0.175264  7.0  0.111724  0.153704
3753  1.003  0.175494  7.0  0.111616  0.153896

3750
interpolation

<lambdifygenerated-19265>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1/x1
<lambdifygenerated-19266>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1/x1
<lambdifygenerated-19279>:2: RuntimeWarning: overflow encountered in power
  return (x1**2)**((_a2_ + x1)**2/x1)/x1
/usr/local/lib/python3.10/dist-packages/scipy/optimize/_minpack_py.py:1017: RuntimeWarning: overflow encountered in square
  cost = np.sum(infodict['fvec'] ** 2)
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
/usr/local/lib/python3.10/dist-packages/pandas/core/arraylike.py:399: RuntimeWarning: overflow encountered in square
  result = getattr(ufunc, method)(*inputs, **kwargs)
<lambdifygenerated-19280>:2: RuntimeWarning: overflow encountered in power
  return (x1**2)**((_a2_ + x1)**2/x1)/x1
<lambdifygenerated-19281>:2: RuntimeWarning: overflow encountered in power
  return (x1**2)**((_a2_ + x1)**2/x1)/x1
<lambdifygenerated-19282>:2: RuntimeWarning: overflow encountered in power
  return (x1**2)**((_a2_ + x1)**2/x1)/x1
<lambdifygenerated-19285>:2: RuntimeWarning: overflow encountered in power
  return (x1**2)**((_a2_ + x1)**2/_a4_)/_a4_

         x1         y  rep    ymodel      ybms
3745  0.997  0.261188  8.0  0.265180  0.306012
3746  0.998  0.261362  8.0  0.265430  0.306712
3747  0.998  0.261535  8.0  0.265681  0.307414
3748  0.999  0.261709  8.0  0.265932  0.308118

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.262056  8.0  0.266432  0.309533
3751  1.002  0.262229  8.0  0.266683  0.310243
3752  1.002  0.262402  8.0  0.266933  0.310956
3753  1.003  0.262576  8.0  0.267182  0.311671

3750
interpolation

         x1        y  rep    ymodel      ybms
3745  0.997  0.64259  9.0  0.693775  0.599575
3746  0.998  0.64247  9.0  0.693852  0.599370
3747  0.998  0.64235  9.0  0.693929  0.599165
3748  0.999  0.64223  9.0  0.694006  0.598961

extrapolation

         x1        y  rep    ymodel      ybms
3750  1.001  0.64199  9.0  0.694161  0.598553
3751  1.002  0.64187  9.0  0.694238  0.598349
3752  1.002  0.64175  9.0  0.694316  0.598146
3753  1.003  0.64163  9.0  0.694394  0.597943

3750
interpolation

<lambdifygenerated-19321>:2: RuntimeWarning: invalid value encountered in power
  return _a1_*x1**x1
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-19322>:2: RuntimeWarning: invalid value encountered in power
  return _a1_*x1**x1

         x1         y  rep    ymodel      ybms
3745  0.997  0.360683  0.0  0.337427  0.333035
3746  0.998  0.360826  0.0  0.337540  0.333114
3747  0.998  0.360969  0.0  0.337652  0.333193
3748  0.999  0.361111  0.0  0.337765  0.333272

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.361396  0.0  0.337991  0.333429
3751  1.002  0.361539  0.0  0.338104  0.333508
3752  1.002  0.361681  0.0  0.338216  0.333587
3753  1.003  0.361824  0.0  0.338329  0.333665

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.875844  1.0  0.886293  0.961667
3746  0.998  0.875274  1.0  0.886171  0.961667
3747  0.998  0.874704  1.0  0.886048  0.961667
3748  0.999  0.874135  1.0  0.885926  0.961667

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.872995  1.0  0.885681  0.961667
3751  1.002  0.872426  1.0  0.885558  0.961667
3752  1.002  0.871856  1.0  0.885436  0.961667
3753  1.003  0.871287  1.0  0.885313  0.961667

3750
interpolation

<lambdifygenerated-19349>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1
<lambdifygenerated-19350>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1

         x1         y  rep    ymodel      ybms
3745  0.997  0.997734  2.0  0.966750  0.997349
3746  0.998  0.997761  2.0  0.966665  0.997323
3747  0.998  0.997787  2.0  0.966579  0.997296
3748  0.999  0.997814  2.0  0.966493  0.997270

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.997867  2.0  0.966320  0.997216
3751  1.002  0.997894  2.0  0.966234  0.997189
3752  1.002  0.997921  2.0  0.966147  0.997162
3753  1.003  0.997948  2.0  0.966060  0.997135

3750
interpolation

<lambdifygenerated-19369>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1
<lambdifygenerated-19370>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1

         x1         y  rep    ymodel      ybms
3745  0.997  0.689029  3.0  0.709181  0.703340
3746  0.998  0.688777  3.0  0.709040  0.702943
3747  0.998  0.688525  3.0  0.708900  0.702547
3748  0.999  0.688273  3.0  0.708762  0.702150

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.687768  3.0  0.708491  0.701354
3751  1.002  0.687516  3.0  0.708357  0.700956
3752  1.002  0.687264  3.0  0.708226  0.700557
3753  1.003  0.687012  3.0  0.708095  0.700158

3750
interpolation

<lambdifygenerated-19393>:2: RuntimeWarning: invalid value encountered in power
  return _a3_*x1**x1
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-19394>:2: RuntimeWarning: invalid value encountered in power
  return _a3_*x1**x1
<lambdifygenerated-19395>:2: RuntimeWarning: invalid value encountered in power
  return _a3_*_a6_**x1

         x1         y  rep    ymodel      ybms
3745  0.997  0.661298  4.0  0.655810  0.597012
3746  0.998  0.661485  4.0  0.656242  0.596939
3747  0.998  0.661672  4.0  0.656679  0.596867
3748  0.999  0.661858  4.0  0.657121  0.596794

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.662232  4.0  0.658018  0.596649
3751  1.002  0.662419  4.0  0.658472  0.596576
3752  1.002  0.662605  4.0  0.658931  0.596504
3753  1.003  0.662792  4.0  0.659393  0.596431

3750
interpolation

         x1         y  rep    ymodel     ybms
3745  0.997  0.956369  5.0  0.990019  0.97603
3746  0.998  0.956259  5.0  0.989747  0.97603
3747  0.998  0.956150  5.0  0.989449  0.97603
3748  0.999  0.956040  5.0  0.989124  0.97603

extrapolation

         x1         y  rep    ymodel     ybms
3750  1.001  0.955822  5.0  0.988394  0.97603
3751  1.002  0.955712  5.0  0.987988  0.97603
3752  1.002  0.955603  5.0  0.987557  0.97603
3753  1.003  0.955493  5.0  0.987099  0.97603

3750
interpolation

/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(

         x1         y  rep    ymodel      ybms
3745  0.997  0.428260  6.0  0.440833  0.413663
3746  0.998  0.428367  6.0  0.440239  0.413668
3747  0.998  0.428474  6.0  0.439625  0.413673
3748  0.999  0.428581  6.0  0.438993  0.413677

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.428794  6.0  0.437675  0.413686
3751  1.002  0.428901  6.0  0.436990  0.413691
3752  1.002  0.429008  6.0  0.436288  0.413696
3753  1.003  0.429115  6.0  0.435569  0.413700

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.173654  7.0  0.173385  0.133189
3746  0.998  0.173884  7.0  0.174035  0.133403
3747  0.998  0.174114  7.0  0.174560  0.133617
3748  0.999  0.174344  7.0  0.174952  0.133831

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.174804  7.0  0.175304  0.134260
3751  1.002  0.175034  7.0  0.175250  0.134475
3752  1.002  0.175264  7.0  0.175032  0.134690
3753  1.003  0.175494  7.0  0.174646  0.134905

3750
interpolation

<lambdifygenerated-19459>:2: RuntimeWarning: invalid value encountered in power
  return x1*x1**x1
<lambdifygenerated-19460>:2: RuntimeWarning: invalid value encountered in power
  return x1*x1**x1

         x1         y  rep    ymodel      ybms
3745  0.997  0.261188  8.0  0.288043  0.288472
3746  0.998  0.261362  8.0  0.272422  0.288911
3747  0.998  0.261535  8.0  0.255990  0.289351
3748  0.999  0.261709  8.0  0.238854  0.289791

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.262056  8.0  0.202894  0.290673
3751  1.002  0.262229  8.0  0.184271  0.291115
3752  1.002  0.262402  8.0  0.165345  0.291557
3753  1.003  0.262576  8.0  0.146204  0.292000

3750
interpolation

         x1        y  rep    ymodel      ybms
3745  0.997  0.64259  9.0  0.600763  0.607242
3746  0.998  0.64247  9.0  0.584445  0.606938
3747  0.998  0.64235  9.0  0.567120  0.606635
3748  0.999  0.64223  9.0  0.548851  0.606331

extrapolation

         x1        y  rep    ymodel      ybms
3750  1.001  0.64199  9.0  0.509760  0.605723
3751  1.002  0.64187  9.0  0.489088  0.605419
3752  1.002  0.64175  9.0  0.467771  0.605115
3753  1.003  0.64163  9.0  0.445890  0.604811

3750
interpolation

<lambdifygenerated-19507>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1
<lambdifygenerated-19508>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1
<lambdifygenerated-19511>:2: RuntimeWarning: invalid value encountered in power
  return _a3_**(x1**x1)
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-19512>:2: RuntimeWarning: invalid value encountered in power
  return _a3_**(x1**x1)
<lambdifygenerated-19513>:2: RuntimeWarning: invalid value encountered in power
  return _a3_**(_a0_**x1)

         x1         y  rep    ymodel      ybms
3745  0.997  0.360683  0.0  0.449591  0.488993
3746  0.998  0.360826  0.0  0.450116  0.489699
3747  0.998  0.360969  0.0  0.450640  0.490406
3748  0.999  0.361111  0.0  0.451166  0.491114

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.361396  0.0  0.452219  0.492532
3751  1.002  0.361539  0.0  0.452747  0.493241
3752  1.002  0.361681  0.0  0.453275  0.493952
3753  1.003  0.361824  0.0  0.453803  0.494663

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.875844  1.0  0.954992  0.958957
3746  0.998  0.875274  1.0  0.955075  0.958957
3747  0.998  0.874704  1.0  0.955158  0.958957
3748  0.999  0.874135  1.0  0.955242  0.958957

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.872995  1.0  0.955409  0.958957
3751  1.002  0.872426  1.0  0.955493  0.958957
3752  1.002  0.871856  1.0  0.955578  0.958957
3753  1.003  0.871287  1.0  0.955662  0.958957

3750
interpolation

<lambdifygenerated-19537>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1
<lambdifygenerated-19538>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1

         x1         y  rep    ymodel      ybms
3745  0.997  0.997734  2.0  1.004865  0.998562
3746  0.998  0.997761  2.0  1.004899  0.998543
3747  0.998  0.997787  2.0  1.004933  0.998524
3748  0.999  0.997814  2.0  1.004966  0.998505

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.997867  2.0  1.005033  0.998466
3751  1.002  0.997894  2.0  1.005067  0.998446
3752  1.002  0.997921  2.0  1.005100  0.998426
3753  1.003  0.997948  2.0  1.005133  0.998406

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.689029  3.0  0.748080  0.695682
3746  0.998  0.688777  3.0  0.747908  0.695222
3747  0.998  0.688525  3.0  0.747735  0.694760
3748  0.999  0.688273  3.0  0.747563  0.694298

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.687768  3.0  0.747218  0.693371
3751  1.002  0.687516  3.0  0.747046  0.692907
3752  1.002  0.687264  3.0  0.746873  0.692442
3753  1.003  0.687012  3.0  0.746701  0.691977

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.661298  4.0  0.602148  0.585698
3746  0.998  0.661485  4.0  0.602125  0.585605
3747  0.998  0.661672  4.0  0.602102  0.585512
3748  0.999  0.661858  4.0  0.602079  0.585419

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.662232  4.0  0.602033  0.585232
3751  1.002  0.662419  4.0  0.602010  0.585139
3752  1.002  0.662605  4.0  0.601987  0.585046
3753  1.003  0.662792  4.0  0.601964  0.584953

3750
interpolation

         x1         y  rep    ymodel     ybms
3745  0.997  0.956369  5.0  0.994484  0.98644
3746  0.998  0.956259  5.0  0.994472  0.98644
3747  0.998  0.956150  5.0  0.994460  0.98644
3748  0.999  0.956040  5.0  0.994447  0.98644

extrapolation

         x1         y  rep    ymodel     ybms
3750  1.001  0.955822  5.0  0.994423  0.98644
3751  1.002  0.955712  5.0  0.994410  0.98644
3752  1.002  0.955603  5.0  0.994398  0.98644
3753  1.003  0.955493  5.0  0.994386  0.98644

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.428260  6.0  0.415325  0.404208
3746  0.998  0.428367  6.0  0.415322  0.404213
3747  0.998  0.428474  6.0  0.415319  0.404218
3748  0.999  0.428581  6.0  0.415315  0.404222

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.428794  6.0  0.415309  0.404232
3751  1.002  0.428901  6.0  0.415306  0.404237
3752  1.002  0.429008  6.0  0.415302  0.404242
3753  1.003  0.429115  6.0  0.415299  0.404247

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.173654  7.0  0.193215  0.126359
3746  0.998  0.173884  7.0  0.193705  0.126562
3747  0.998  0.174114  7.0  0.194197  0.126765
3748  0.999  0.174344  7.0  0.194689  0.126968

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.174804  7.0  0.195676  0.127375
3751  1.002  0.175034  7.0  0.196170  0.127579
3752  1.002  0.175264  7.0  0.196665  0.127783
3753  1.003  0.175494  7.0  0.197161  0.127987

3750
interpolation

/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(

         x1         y  rep    ymodel      ybms
3745  0.997  0.261188  8.0  0.317514  0.265063
3746  0.998  0.261362  8.0  0.318202  0.265210
3747  0.998  0.261535  8.0  0.318892  0.265356
3748  0.999  0.261709  8.0  0.319585  0.265502

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.262056  8.0  0.320978  0.265793
3751  1.002  0.262229  8.0  0.321678  0.265938
3752  1.002  0.262402  8.0  0.322381  0.266082
3753  1.003  0.262576  8.0  0.323087  0.266226

3750
interpolation

<lambdifygenerated-19665>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1
<lambdifygenerated-19666>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1

         x1        y  rep    ymodel      ybms
3745  0.997  0.64259  9.0  0.668746  0.632232
3746  0.998  0.64247  9.0  0.668666  0.631985
3747  0.998  0.64235  9.0  0.668587  0.631737
3748  0.999  0.64223  9.0  0.668508  0.631490

extrapolation

         x1        y  rep    ymodel      ybms
3750  1.001  0.64199  9.0  0.668352  0.630995
3751  1.002  0.64187  9.0  0.668274  0.630748
3752  1.002  0.64175  9.0  0.668197  0.630500
3753  1.003  0.64163  9.0  0.668119  0.630253

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.360683  0.0  0.363634  0.367823
3746  0.998  0.360826  0.0  0.363751  0.367910
3747  0.998  0.360969  0.0  0.363868  0.367997
3748  0.999  0.361111  0.0  0.363985  0.368083

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.361396  0.0  0.364219  0.368256
3751  1.002  0.361539  0.0  0.364336  0.368342
3752  1.002  0.361681  0.0  0.364453  0.368428
3753  1.003  0.361824  0.0  0.364570  0.368514

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.875844  1.0  0.877186  0.963045
3746  0.998  0.875274  1.0  0.877048  0.963045
3747  0.998  0.874704  1.0  0.876911  0.963045
3748  0.999  0.874135  1.0  0.876773  0.963045

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.872995  1.0  0.876497  0.963045
3751  1.002  0.872426  1.0  0.876359  0.963045
3752  1.002  0.871856  1.0  0.876221  0.963045
3753  1.003  0.871287  1.0  0.876083  0.963045

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.997734  2.0  0.957589  0.986449
3746  0.998  0.997761  2.0  0.957270  0.986385
3747  0.998  0.997787  2.0  0.956951  0.986320
3748  0.999  0.997814  2.0  0.956631  0.986255

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.997867  2.0  0.955987  0.986124
3751  1.002  0.997894  2.0  0.955664  0.986058
3752  1.002  0.997921  2.0  0.955340  0.985992
3753  1.003  0.997948  2.0  0.955015  0.985926

3750
interpolation

<lambdifygenerated-19743>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1
<lambdifygenerated-19744>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1
<lambdifygenerated-19747>:2: RuntimeWarning: invalid value encountered in power
  return _a6_**(x1**x1)
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-19748>:2: RuntimeWarning: invalid value encountered in power
  return _a6_**(x1**x1)

         x1         y  rep    ymodel      ybms
3745  0.997  0.689029  3.0  0.642309  0.635288
3746  0.998  0.688777  3.0  0.641705  0.634621
3747  0.998  0.688525  3.0  0.641100  0.633953
3748  0.999  0.688273  3.0  0.640496  0.633284

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.687768  3.0  0.639285  0.631943
3751  1.002  0.687516  3.0  0.638679  0.631272
3752  1.002  0.687264  3.0  0.638073  0.630600
3753  1.003  0.687012  3.0  0.637466  0.629927

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.661298  4.0  0.656007  0.584577
3746  0.998  0.661485  4.0  0.656192  0.584484
3747  0.998  0.661672  4.0  0.656377  0.584392
3748  0.999  0.661858  4.0  0.656562  0.584300

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.662232  4.0  0.656935  0.584116
3751  1.002  0.662419  4.0  0.657121  0.584023
3752  1.002  0.662605  4.0  0.657308  0.583931
3753  1.003  0.662792  4.0  0.657496  0.583839

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.956369  5.0  0.975183  0.985495
3746  0.998  0.956259  5.0  0.975205  0.985495
3747  0.998  0.956150  5.0  0.975227  0.985495
3748  0.999  0.956040  5.0  0.975250  0.985495

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.955822  5.0  0.975295  0.985495
3751  1.002  0.955712  5.0  0.975318  0.985495
3752  1.002  0.955603  5.0  0.975341  0.985495
3753  1.003  0.955493  5.0  0.975364  0.985495

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.428260  6.0  0.426282  0.416096
3746  0.998  0.428367  6.0  0.426292  0.416101
3747  0.998  0.428474  6.0  0.426303  0.416106
3748  0.999  0.428581  6.0  0.426313  0.416110

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.428794  6.0  0.426334  0.416120
3751  1.002  0.428901  6.0  0.426344  0.416124
3752  1.002  0.429008  6.0  0.426355  0.416129
3753  1.003  0.429115  6.0  0.426365  0.416134

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.173654  7.0  0.115053  0.141354
3746  0.998  0.173884  7.0  0.114655  0.141616
3747  0.998  0.174114  7.0  0.114255  0.141878
3748  0.999  0.174344  7.0  0.113854  0.142141

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.174804  7.0  0.113052  0.142668
3751  1.002  0.175034  7.0  0.112649  0.142933
3752  1.002  0.175264  7.0  0.112246  0.143198
3753  1.003  0.175494  7.0  0.111842  0.143463

3750
interpolation

/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(

         x1         y  rep    ymodel      ybms
3745  0.997  0.261188  8.0  0.190524  0.271128
3746  0.998  0.261362  8.0  0.189920  0.271274
3747  0.998  0.261535  8.0  0.189314  0.271420
3748  0.999  0.261709  8.0  0.188704  0.271565

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.262056  8.0  0.187473  0.271855
3751  1.002  0.262229  8.0  0.186853  0.272000
3752  1.002  0.262402  8.0  0.186229  0.272144
3753  1.003  0.262576  8.0  0.185602  0.272287

3750
interpolation

         x1        y  rep    ymodel      ybms
3745  0.997  0.64259  9.0  0.589236  0.568378
3746  0.998  0.64247  9.0  0.589061  0.568122
3747  0.998  0.64235  9.0  0.588887  0.567867
3748  0.999  0.64223  9.0  0.588713  0.567612

extrapolation

         x1        y  rep    ymodel      ybms
3750  1.001  0.64199  9.0  0.588369  0.567103
3751  1.002  0.64187  9.0  0.588198  0.566849
3752  1.002  0.64175  9.0  0.588029  0.566595
3753  1.003  0.64163  9.0  0.587860  0.566341

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.360683  0.0  0.363643  0.360149
3746  0.998  0.360826  0.0  0.363742  0.360234
3747  0.998  0.360969  0.0  0.363840  0.360319
3748  0.999  0.361111  0.0  0.363938  0.360403

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.361396  0.0  0.364134  0.360573
3751  1.002  0.361539  0.0  0.364232  0.360657
3752  1.002  0.361681  0.0  0.364331  0.360741
3753  1.003  0.361824  0.0  0.364428  0.360826

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.875844  1.0  0.849551  0.965591
3746  0.998  0.875274  1.0  0.849284  0.965591
3747  0.998  0.874704  1.0  0.849018  0.965591
3748  0.999  0.874135  1.0  0.848751  0.965591

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.872995  1.0  0.848216  0.965591
3751  1.002  0.872426  1.0  0.847948  0.965591
3752  1.002  0.871856  1.0  0.847680  0.965591
3753  1.003  0.871287  1.0  0.847411  0.965591

3750
interpolation

<lambdifygenerated-19913>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1
<lambdifygenerated-19914>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1

         x1         y  rep    ymodel      ybms
3745  0.997  0.997734  2.0  1.031530  0.994736
3746  0.998  0.997761  2.0  1.031608  0.994698
3747  0.998  0.997787  2.0  1.031686  0.994659
3748  0.999  0.997814  2.0  1.031764  0.994621

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.997867  2.0  1.031919  0.994543
3751  1.002  0.997894  2.0  1.031997  0.994504
3752  1.002  0.997921  2.0  1.032075  0.994465
3753  1.003  0.997948  2.0  1.032153  0.994426

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.689029  3.0  0.702719  0.684276
3746  0.998  0.688777  3.0  0.702388  0.683799
3747  0.998  0.688525  3.0  0.702056  0.683321
3748  0.999  0.688273  3.0  0.701724  0.682843

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.687768  3.0  0.701060  0.681884
3751  1.002  0.687516  3.0  0.700727  0.681404
3752  1.002  0.687264  3.0  0.700395  0.680923
3753  1.003  0.687012  3.0  0.700062  0.680441

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.661298  4.0  0.645876  0.598561
3746  0.998  0.661485  4.0  0.645911  0.598476
3747  0.998  0.661672  4.0  0.645945  0.598392
3748  0.999  0.661858  4.0  0.645979  0.598307

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.662232  4.0  0.646048  0.598138
3751  1.002  0.662419  4.0  0.646082  0.598054
3752  1.002  0.662605  4.0  0.646117  0.597969
3753  1.003  0.662792  4.0  0.646151  0.597885

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.956369  5.0  0.976577  0.983869
3746  0.998  0.956259  5.0  0.976506  0.983869
3747  0.998  0.956150  5.0  0.976435  0.983869
3748  0.999  0.956040  5.0  0.976364  0.983869

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.955822  5.0  0.976222  0.983869
3751  1.002  0.955712  5.0  0.976151  0.983869
3752  1.002  0.955603  5.0  0.976079  0.983869
3753  1.003  0.955493  5.0  0.976008  0.983869

3750
interpolation

<lambdifygenerated-19981>:2: RuntimeWarning: invalid value encountered in power
  return x1*x1**x1
<lambdifygenerated-19982>:2: RuntimeWarning: invalid value encountered in power
  return x1*x1**x1
<lambdifygenerated-19985>:2: RuntimeWarning: invalid value encountered in power
  return _a5_**(x1**x1)*x1
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-19986>:2: RuntimeWarning: invalid value encountered in power
  return _a5_**(x1**x1)*x1
<lambdifygenerated-19987>:2: RuntimeWarning: invalid value encountered in power
  return _a5_**(_a6_**x1)*x1
<lambdifygenerated-19991>:2: RuntimeWarning: overflow encountered in power
  return _a2_*_a5_**(_a6_**x1)
<lambdifygenerated-19995>:2: RuntimeWarning: overflow encountered in power
  return _a2_*_a5_**(_a6_**x1)

         x1         y  rep    ymodel      ybms
3745  0.997  0.428260  6.0  0.389574  0.404021
3746  0.998  0.428367  6.0  0.389536  0.404023
3747  0.998  0.428474  6.0  0.389497  0.404025
3748  0.999  0.428581  6.0  0.389459  0.404027

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.428794  6.0  0.389383  0.404031
3751  1.002  0.428901  6.0  0.389344  0.404033
3752  1.002  0.429008  6.0  0.389306  0.404035
3753  1.003  0.429115  6.0  0.389268  0.404037

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.173654  7.0  0.172266  0.140199
3746  0.998  0.173884  7.0  0.172484  0.140424
3747  0.998  0.174114  7.0  0.172702  0.140650
3748  0.999  0.174344  7.0  0.172921  0.140875

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.174804  7.0  0.173359  0.141327
3751  1.002  0.175034  7.0  0.173578  0.141553
3752  1.002  0.175264  7.0  0.173797  0.141779
3753  1.003  0.175494  7.0  0.174017  0.142005

3750
interpolation

<lambdifygenerated-20019>:2: RuntimeWarning: invalid value encountered in power
  return x1 + x1**x1
<lambdifygenerated-20020>:2: RuntimeWarning: invalid value encountered in power
  return x1 + x1**x1

         x1         y  rep    ymodel      ybms
3745  0.997  0.261188  8.0  0.249269  0.228768
3746  0.998  0.261362  8.0  0.249369  0.228909
3747  0.998  0.261535  8.0  0.249469  0.229049
3748  0.999  0.261709  8.0  0.249567  0.229189

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.262056  8.0  0.249762  0.229469
3751  1.002  0.262229  8.0  0.249858  0.229609
3752  1.002  0.262402  8.0  0.249953  0.229749
3753  1.003  0.262576  8.0  0.250048  0.229888

3750
interpolation

         x1        y  rep    ymodel      ybms
3745  0.997  0.64259  9.0  0.624298  0.594364
3746  0.998  0.64247  9.0  0.624064  0.594044
3747  0.998  0.64235  9.0  0.623830  0.593723
3748  0.999  0.64223  9.0  0.623597  0.593403

extrapolation

         x1        y  rep    ymodel      ybms
3750  1.001  0.64199  9.0  0.623132  0.592762
3751  1.002  0.64187  9.0  0.622900  0.592441
3752  1.002  0.64175  9.0  0.622669  0.592120
3753  1.003  0.64163  9.0  0.622438  0.591799

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.360683  0.0  0.406818  0.365058
3746  0.998  0.360826  0.0  0.407039  0.365145
3747  0.998  0.360969  0.0  0.407259  0.365231
3748  0.999  0.361111  0.0  0.407479  0.365316

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.361396  0.0  0.407919  0.365488
3751  1.002  0.361539  0.0  0.408139  0.365574
3752  1.002  0.361681  0.0  0.408359  0.365659
3753  1.003  0.361824  0.0  0.408579  0.365745

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.875844  1.0  0.917614  0.960314
3746  0.998  0.875274  1.0  0.917552  0.960314
3747  0.998  0.874704  1.0  0.917489  0.960314
3748  0.999  0.874135  1.0  0.917426  0.960314

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.872995  1.0  0.917301  0.960314
3751  1.002  0.872426  1.0  0.917238  0.960314
3752  1.002  0.871856  1.0  0.917175  0.960314
3753  1.003  0.871287  1.0  0.917112  0.960314

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.997734  2.0  0.977436  0.998146
3746  0.998  0.997761  2.0  0.977446  0.998126
3747  0.998  0.997787  2.0  0.977455  0.998105
3748  0.999  0.997814  2.0  0.977465  0.998085

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.997867  2.0  0.977485  0.998045
3751  1.002  0.997894  2.0  0.977495  0.998024
3752  1.002  0.997921  2.0  0.977505  0.998004
3753  1.003  0.997948  2.0  0.977515  0.997983

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.689029  3.0  0.785538  0.740403
3746  0.998  0.688777  3.0  0.785484  0.740006
3747  0.998  0.688525  3.0  0.785431  0.739609
3748  0.999  0.688273  3.0  0.785378  0.739211

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.687768  3.0  0.785272  0.738414
3751  1.002  0.687516  3.0  0.785220  0.738014
3752  1.002  0.687264  3.0  0.785167  0.737614
3753  1.003  0.687012  3.0  0.785115  0.737213

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.661298  4.0  0.626660  0.596478
3746  0.998  0.661485  4.0  0.626644  0.596388
3747  0.998  0.661672  4.0  0.626628  0.596297
3748  0.999  0.661858  4.0  0.626612  0.596207

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.662232  4.0  0.626581  0.596026
3751  1.002  0.662419  4.0  0.626565  0.595935
3752  1.002  0.662605  4.0  0.626550  0.595845
3753  1.003  0.662792  4.0  0.626534  0.595754

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.956369  5.0  0.954870  0.986834
3746  0.998  0.956259  5.0  0.954848  0.986834
3747  0.998  0.956150  5.0  0.954825  0.986834
3748  0.999  0.956040  5.0  0.954803  0.986834

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.955822  5.0  0.954759  0.986834
3751  1.002  0.955712  5.0  0.954737  0.986834
3752  1.002  0.955603  5.0  0.954715  0.986834
3753  1.003  0.955493  5.0  0.954694  0.986834

3750
interpolation

/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(

         x1         y  rep    ymodel      ybms
3745  0.997  0.428260  6.0  0.438136  0.423793
3746  0.998  0.428367  6.0  0.438370  0.423814
3747  0.998  0.428474  6.0  0.438604  0.423835
3748  0.999  0.428581  6.0  0.438838  0.423856

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.428794  6.0  0.439306  0.423897
3751  1.002  0.428901  6.0  0.439539  0.423918
3752  1.002  0.429008  6.0  0.439773  0.423939
3753  1.003  0.429115  6.0  0.440007  0.423960

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.173654  7.0  0.243184  0.139481
3746  0.998  0.173884  7.0  0.243977  0.139705
3747  0.998  0.174114  7.0  0.244772  0.139929
3748  0.999  0.174344  7.0  0.245567  0.140153

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.174804  7.0  0.247161  0.140602
3751  1.002  0.175034  7.0  0.247959  0.140827
3752  1.002  0.175264  7.0  0.248758  0.141052
3753  1.003  0.175494  7.0  0.249559  0.141277

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.261188  8.0  0.331659  0.261480
3746  0.998  0.261362  8.0  0.332256  0.261632
3747  0.998  0.261535  8.0  0.332853  0.261785
3748  0.999  0.261709  8.0  0.333451  0.261937

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.262056  8.0  0.334649  0.262240
3751  1.002  0.262229  8.0  0.335249  0.262390
3752  1.002  0.262402  8.0  0.335849  0.262541
3753  1.003  0.262576  8.0  0.336450  0.262691

3750
interpolation

         x1        y  rep    ymodel      ybms
3745  0.997  0.64259  9.0  0.692858  0.603877
3746  0.998  0.64247  9.0  0.693081  0.603582
3747  0.998  0.64235  9.0  0.693305  0.603288
3748  0.999  0.64223  9.0  0.693530  0.602993

extrapolation

         x1        y  rep    ymodel      ybms
3750  1.001  0.64199  9.0  0.693980  0.602403
3751  1.002  0.64187  9.0  0.694206  0.602108
3752  1.002  0.64175  9.0  0.694433  0.601813
3753  1.003  0.64163  9.0  0.694660  0.601518

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.360683  0.0  0.344740  0.373392
3746  0.998  0.360826  0.0  0.344767  0.373480
3747  0.998  0.360969  0.0  0.344795  0.373568
3748  0.999  0.361111  0.0  0.344822  0.373656

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.361396  0.0  0.344875  0.373831
3751  1.002  0.361539  0.0  0.344902  0.373919
3752  1.002  0.361681  0.0  0.344929  0.374006
3753  1.003  0.361824  0.0  0.344955  0.374093

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.875844  1.0  0.894627  0.964435
3746  0.998  0.875274  1.0  0.894537  0.964435
3747  0.998  0.874704  1.0  0.894447  0.964435
3748  0.999  0.874135  1.0  0.894358  0.964435

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.872995  1.0  0.894181  0.964435
3751  1.002  0.872426  1.0  0.894093  0.964435
3752  1.002  0.871856  1.0  0.894005  0.964435
3753  1.003  0.871287  1.0  0.893918  0.964435

3750
interpolation

<lambdifygenerated-20273>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1
<lambdifygenerated-20274>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1

         x1         y  rep    ymodel      ybms
3745  0.997  0.997734  2.0  0.989613  0.996449
3746  0.998  0.997761  2.0  0.989670  0.996419
3747  0.998  0.997787  2.0  0.989728  0.996388
3748  0.999  0.997814  2.0  0.989786  0.996357

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.997867  2.0  0.989901  0.996295
3751  1.002  0.997894  2.0  0.989958  0.996264
3752  1.002  0.997921  2.0  0.990016  0.996233
3753  1.003  0.997948  2.0  0.990073  0.996202

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.689029  3.0  0.671165  0.666491
3746  0.998  0.688777  3.0  0.670924  0.665989
3747  0.998  0.688525  3.0  0.670684  0.665486
3748  0.999  0.688273  3.0  0.670444  0.664983

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.687768  3.0  0.669969  0.663974
3751  1.002  0.687516  3.0  0.669733  0.663468
3752  1.002  0.687264  3.0  0.669498  0.662962
3753  1.003  0.687012  3.0  0.669263  0.662455

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.661298  4.0  0.622389  0.588245
3746  0.998  0.661485  4.0  0.622363  0.588159
3747  0.998  0.661672  4.0  0.622338  0.588073
3748  0.999  0.661858  4.0  0.622312  0.587987

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.662232  4.0  0.622262  0.587816
3751  1.002  0.662419  4.0  0.622237  0.587730
3752  1.002  0.662605  4.0  0.622212  0.587644
3753  1.003  0.662792  4.0  0.622187  0.587559

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.956369  5.0  0.954482  0.979174
3746  0.998  0.956259  5.0  0.954494  0.979174
3747  0.998  0.956150  5.0  0.954506  0.979174
3748  0.999  0.956040  5.0  0.954518  0.979174

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.955822  5.0  0.954542  0.979174
3751  1.002  0.955712  5.0  0.954553  0.979174
3752  1.002  0.955603  5.0  0.954565  0.979174
3753  1.003  0.955493  5.0  0.954577  0.979174

3750
interpolation

/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(

         x1         y  rep    ymodel      ybms
3745  0.997  0.428260  6.0  0.444754  0.441047
3746  0.998  0.428367  6.0  0.444828  0.441070
3747  0.998  0.428474  6.0  0.444901  0.441092
3748  0.999  0.428581  6.0  0.444975  0.441115

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.428794  6.0  0.445120  0.441160
3751  1.002  0.428901  6.0  0.445193  0.441182
3752  1.002  0.429008  6.0  0.445265  0.441205
3753  1.003  0.429115  6.0  0.445337  0.441227

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.173654  7.0  0.196763  0.203285
3746  0.998  0.173884  7.0  0.196945  0.203568
3747  0.998  0.174114  7.0  0.197127  0.203851
3748  0.999  0.174344  7.0  0.197309  0.204135

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.174804  7.0  0.197671  0.204702
3751  1.002  0.175034  7.0  0.197852  0.204985
3752  1.002  0.175264  7.0  0.198032  0.205269
3753  1.003  0.175494  7.0  0.198212  0.205554

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.261188  8.0  0.229225  0.246038
3746  0.998  0.261362  8.0  0.229226  0.246228
3747  0.998  0.261535  8.0  0.229227  0.246416
3748  0.999  0.261709  8.0  0.229227  0.246605

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.262056  8.0  0.229229  0.246982
3751  1.002  0.262229  8.0  0.229229  0.247171
3752  1.002  0.262402  8.0  0.229230  0.247359
3753  1.003  0.262576  8.0  0.229231  0.247547

3750
interpolation

         x1        y  rep    ymodel      ybms
3745  0.997  0.64259  9.0  0.662535  0.584682
3746  0.998  0.64247  9.0  0.662535  0.584461
3747  0.998  0.64235  9.0  0.662535  0.584240
3748  0.999  0.64223  9.0  0.662535  0.584019

extrapolation

         x1        y  rep    ymodel      ybms
3750  1.001  0.64199  9.0  0.662535  0.583579
3751  1.002  0.64187  9.0  0.662535  0.583360
3752  1.002  0.64175  9.0  0.662535  0.583140
3753  1.003  0.64163  9.0  0.662536  0.582921

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.360683  0.0  0.339376  0.355487
3746  0.998  0.360826  0.0  0.339450  0.355571
3747  0.998  0.360969  0.0  0.339524  0.355655
3748  0.999  0.361111  0.0  0.339598  0.355739

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.361396  0.0  0.339746  0.355906
3751  1.002  0.361539  0.0  0.339820  0.355989
3752  1.002  0.361681  0.0  0.339894  0.356072
3753  1.003  0.361824  0.0  0.339968  0.356155

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.875844  1.0  0.953535  0.953674
3746  0.998  0.875274  1.0  0.953534  0.953674
3747  0.998  0.874704  1.0  0.953533  0.953674
3748  0.999  0.874135  1.0  0.953532  0.953674

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.872995  1.0  0.953530  0.953674
3751  1.002  0.872426  1.0  0.953530  0.953674
3752  1.002  0.871856  1.0  0.953529  0.953674
3753  1.003  0.871287  1.0  0.953528  0.953674

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.997734  2.0  0.951810  0.999987
3746  0.998  0.997761  2.0  0.951636  0.999985
3747  0.998  0.997787  2.0  0.951463  0.999984
3748  0.999  0.997814  2.0  0.951289  0.999982

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.997867  2.0  0.950939  0.999978
3751  1.002  0.997894  2.0  0.950763  0.999976
3752  1.002  0.997921  2.0  0.950587  0.999974
3753  1.003  0.997948  2.0  0.950411  0.999972

3750
interpolation

<lambdifygenerated-20475>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1
<lambdifygenerated-20476>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1

         x1         y  rep    ymodel      ybms
3745  0.997  0.689029  3.0  0.646988  0.684375
3746  0.998  0.688777  3.0  0.646359  0.683959
3747  0.998  0.688525  3.0  0.645730  0.683543
3748  0.999  0.688273  3.0  0.645100  0.683127

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.687768  3.0  0.643835  0.682293
3751  1.002  0.687516  3.0  0.643201  0.681875
3752  1.002  0.687264  3.0  0.642566  0.681457
3753  1.003  0.687012  3.0  0.641930  0.681039

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.661298  4.0  0.646432  0.578896
3746  0.998  0.661485  4.0  0.646604  0.578803
3747  0.998  0.661672  4.0  0.646777  0.578709
3748  0.999  0.661858  4.0  0.646950  0.578615

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.662232  4.0  0.647297  0.578428
3751  1.002  0.662419  4.0  0.647471  0.578334
3752  1.002  0.662605  4.0  0.647646  0.578240
3753  1.003  0.662792  4.0  0.647821  0.578146

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.956369  5.0  0.933698  0.980944
3746  0.998  0.956259  5.0  0.933502  0.980944
3747  0.998  0.956150  5.0  0.933306  0.980944
3748  0.999  0.956040  5.0  0.933109  0.980944

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.955822  5.0  0.932715  0.980944
3751  1.002  0.955712  5.0  0.932517  0.980944
3752  1.002  0.955603  5.0  0.932319  0.980944
3753  1.003  0.955493  5.0  0.932121  0.980944

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.428260  6.0  0.395057  0.440925
3746  0.998  0.428367  6.0  0.394674  0.440947
3747  0.998  0.428474  6.0  0.394288  0.440969
3748  0.999  0.428581  6.0  0.393901  0.440992

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.428794  6.0  0.393121  0.441036
3751  1.002  0.428901  6.0  0.392729  0.441058
3752  1.002  0.429008  6.0  0.392335  0.441081
3753  1.003  0.429115  6.0  0.391939  0.441103

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.173654  7.0  0.209863  0.134674
3746  0.998  0.173884  7.0  0.209956  0.134891
3747  0.998  0.174114  7.0  0.210048  0.135107
3748  0.999  0.174344  7.0  0.210139  0.135324

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.174804  7.0  0.210316  0.135757
3751  1.002  0.175034  7.0  0.210403  0.135975
3752  1.002  0.175264  7.0  0.210488  0.136192
3753  1.003  0.175494  7.0  0.210572  0.136409

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.261188  8.0  0.342179  0.285861
3746  0.998  0.261362  8.0  0.343057  0.286229
3747  0.998  0.261535  8.0  0.343936  0.286597
3748  0.999  0.261709  8.0  0.344819  0.286966

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.262056  8.0  0.346590  0.287703
3751  1.002  0.262229  8.0  0.347479  0.288072
3752  1.002  0.262402  8.0  0.348371  0.288441
3753  1.003  0.262576  8.0  0.349265  0.288811

3750
interpolation

<lambdifygenerated-20587>:2: RuntimeWarning: invalid value encountered in power
  return sin(x1**x1)
<lambdifygenerated-20588>:2: RuntimeWarning: invalid value encountered in power
  return sin(x1**x1)

         x1        y  rep    ymodel      ybms
3745  0.997  0.64259  9.0  0.670410  0.639971
3746  0.998  0.64247  9.0  0.670389  0.639836
3747  0.998  0.64235  9.0  0.670368  0.639701
3748  0.999  0.64223  9.0  0.670347  0.639567

extrapolation

         x1        y  rep    ymodel      ybms
3750  1.001  0.64199  9.0  0.670307  0.639298
3751  1.002  0.64187  9.0  0.670287  0.639164
3752  1.002  0.64175  9.0  0.670268  0.639030
3753  1.003  0.64163  9.0  0.670249  0.638896

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.360683  0.0  0.364504  0.351982
3746  0.998  0.360826  0.0  0.364694  0.352065
3747  0.998  0.360969  0.0  0.364884  0.352148
3748  0.999  0.361111  0.0  0.365075  0.352231

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.361396  0.0  0.365455  0.352397
3751  1.002  0.361539  0.0  0.365646  0.352479
3752  1.002  0.361681  0.0  0.365836  0.352562
3753  1.003  0.361824  0.0  0.366027  0.352644

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.875844  1.0  0.929353  0.962311
3746  0.998  0.875274  1.0  0.929701  0.962311
3747  0.998  0.874704  1.0  0.930050  0.962311
3748  0.999  0.874135  1.0  0.930402  0.962311

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.872995  1.0  0.931113  0.962311
3751  1.002  0.872426  1.0  0.931471  0.962311
3752  1.002  0.871856  1.0  0.931832  0.962311
3753  1.003  0.871287  1.0  0.932195  0.962311

3750
interpolation

<lambdifygenerated-20637>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1
<lambdifygenerated-20638>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1

         x1         y  rep    ymodel      ybms
3745  0.997  0.997734  2.0  1.013720  0.992258
3746  0.998  0.997761  2.0  1.013966  0.992211
3747  0.998  0.997787  2.0  1.014212  0.992165
3748  0.999  0.997814  2.0  1.014457  0.992119

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.997867  2.0  1.014947  0.992025
3751  1.002  0.997894  2.0  1.015192  0.991978
3752  1.002  0.997921  2.0  1.015436  0.991931
3753  1.003  0.997948  2.0  1.015680  0.991884

3750
interpolation

<lambdifygenerated-20657>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1
<lambdifygenerated-20658>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1

         x1         y  rep    ymodel      ybms
3745  0.997  0.689029  3.0  0.681970  0.733353
3746  0.998  0.688777  3.0  0.681197  0.732989
3747  0.998  0.688525  3.0  0.680423  0.732625
3748  0.999  0.688273  3.0  0.679648  0.732260

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.687768  3.0  0.678097  0.731529
3751  1.002  0.687516  3.0  0.677320  0.731163
3752  1.002  0.687264  3.0  0.676543  0.730796
3753  1.003  0.687012  3.0  0.675765  0.730429

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.661298  4.0  0.625068  0.589766
3746  0.998  0.661485  4.0  0.624711  0.589678
3747  0.998  0.661672  4.0  0.624353  0.589590
3748  0.999  0.661858  4.0  0.623993  0.589503

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.662232  4.0  0.623270  0.589327
3751  1.002  0.662419  4.0  0.622907  0.589239
3752  1.002  0.662605  4.0  0.622542  0.589151
3753  1.003  0.662792  4.0  0.622176  0.589063

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.956369  5.0  0.939862  0.971893
3746  0.998  0.956259  5.0  0.939532  0.971893
3747  0.998  0.956150  5.0  0.939202  0.971893
3748  0.999  0.956040  5.0  0.938875  0.971893

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.955822  5.0  0.938224  0.971893
3751  1.002  0.955712  5.0  0.937901  0.971893
3752  1.002  0.955603  5.0  0.937579  0.971893
3753  1.003  0.955493  5.0  0.937259  0.971893

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.428260  6.0  0.579225  0.430475
3746  0.998  0.428367  6.0  0.582914  0.430481
3747  0.998  0.428474  6.0  0.586630  0.430488
3748  0.999  0.428581  6.0  0.590374  0.430495

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.428794  6.0  0.597941  0.430508
3751  1.002  0.428901  6.0  0.601764  0.430515
3752  1.002  0.429008  6.0  0.605613  0.430521
3753  1.003  0.429115  6.0  0.609488  0.430528

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.173654  7.0  0.200424  0.214011
3746  0.998  0.173884  7.0  0.201356  0.214307
3747  0.998  0.174114  7.0  0.202290  0.214603
3748  0.999  0.174344  7.0  0.203229  0.214900

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.174804  7.0  0.205115  0.215494
3751  1.002  0.175034  7.0  0.206063  0.215791
3752  1.002  0.175264  7.0  0.207014  0.216088
3753  1.003  0.175494  7.0  0.207968  0.216386

3750

<lambdifygenerated-20747>:2: RuntimeWarning: invalid value encountered in power
  return x1**(2*x1)
<lambdifygenerated-20748>:2: RuntimeWarning: invalid value encountered in power
  return x1**(2*x1)
<lambdifygenerated-20751>:2: RuntimeWarning: invalid value encountered in power
  return _a5_**(2*x1**x1)
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-20752>:2: RuntimeWarning: invalid value encountered in power
  return _a5_**(2*x1**x1)
<lambdifygenerated-20755>:2: RuntimeWarning: invalid value encountered in power
  return _a5_**(2*(4*x1**2)**x1)
<lambdifygenerated-20761>:2: RuntimeWarning: invalid value encountered in power
  return _a5_**(2*((_a6_ + x1)**2)**_a6_)

interpolation

<lambdifygenerated-20765>:2: RuntimeWarning: invalid value encountered in power
  return _a5_**(2*((_a6_ + x1)**2)**_a6_)

         x1         y  rep    ymodel      ybms
3745  0.997  0.261188  8.0  0.228881  0.213694
3746  0.998  0.261362  8.0  0.230053  0.213846
3747  0.998  0.261535  8.0  0.231228  0.213997
3748  0.999  0.261709  8.0  0.232406  0.214148

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.262056  8.0  0.234769  0.214451
3751  1.002  0.262229  8.0  0.235954  0.214602
3752  1.002  0.262402  8.0  0.237142  0.214752
3753  1.003  0.262576  8.0  0.238332  0.214903

3750
interpolation

         x1        y  rep    ymodel      ybms
3745  0.997  0.64259  9.0  0.667297  0.598982
3746  0.998  0.64247  9.0  0.667300  0.598684
3747  0.998  0.64235  9.0  0.667304  0.598386
3748  0.999  0.64223  9.0  0.667307  0.598088

extrapolation

         x1        y  rep    ymodel      ybms
3750  1.001  0.64199  9.0  0.667313  0.597491
3751  1.002  0.64187  9.0  0.667316  0.597193
3752  1.002  0.64175  9.0  0.667319  0.596894
3753  1.003  0.64163  9.0  0.667322  0.596596

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.360683  0.0  0.356791  0.355026
3746  0.998  0.360826  0.0  0.356947  0.355110
3747  0.998  0.360969  0.0  0.357103  0.355194
3748  0.999  0.361111  0.0  0.357259  0.355277

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.361396  0.0  0.357571  0.355444
3751  1.002  0.361539  0.0  0.357727  0.355527
3752  1.002  0.361681  0.0  0.357883  0.355611
3753  1.003  0.361824  0.0  0.358040  0.355694

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.875844  1.0  0.973341  0.959878
3746  0.998  0.875274  1.0  0.973579  0.959878
3747  0.998  0.874704  1.0  0.973819  0.959878
3748  0.999  0.874135  1.0  0.974060  0.959878

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.872995  1.0  0.974548  0.959878
3751  1.002  0.872426  1.0  0.974795  0.959878
3752  1.002  0.871856  1.0  0.975043  0.959878
3753  1.003  0.871287  1.0  0.975293  0.959878

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.997734  2.0  0.985370  0.999838
3746  0.998  0.997761  2.0  0.986164  0.999843
3747  0.998  0.997787  2.0  0.986961  0.999848
3748  0.999  0.997814  2.0  0.987763  0.999853

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.997867  2.0  0.989379  0.999863
3751  1.002  0.997894  2.0  0.990193  0.999868
3752  1.002  0.997921  2.0  0.991011  0.999873
3753  1.003  0.997948  2.0  0.991832  0.999877

3750
interpolation

<lambdifygenerated-20841>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1
<lambdifygenerated-20842>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1
<lambdifygenerated-20845>:2: RuntimeWarning: invalid value encountered in power
  return _a3_**(x1**x1)
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-20846>:2: RuntimeWarning: invalid value encountered in power
  return _a3_**(x1**x1)

         x1         y  rep    ymodel      ybms
3745  0.997  0.689029  3.0  0.861072  0.641166
3746  0.998  0.688777  3.0  0.849185  0.640508
3747  0.998  0.688525  3.0  0.834961  0.639849
3748  0.999  0.688273  3.0  0.818427  0.639189

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.687768  3.0  0.778669  0.637867
3751  1.002  0.687516  3.0  0.755630  0.637205
3752  1.002  0.687264  3.0  0.730645  0.636542
3753  1.003  0.687012  3.0  0.703861  0.635878

3750
interpolation

<lambdifygenerated-20861>:2: RuntimeWarning: invalid value encountered in power
  return x1*x1**x1
<lambdifygenerated-20862>:2: RuntimeWarning: invalid value encountered in power
  return x1*x1**x1

         x1         y  rep    ymodel      ybms
3745  0.997  0.661298  4.0  0.738962  0.607352
3746  0.998  0.661485  4.0  0.742071  0.607286
3747  0.998  0.661672  4.0  0.745175  0.607220
3748  0.999  0.661858  4.0  0.748272  0.607154

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.662232  4.0  0.754444  0.607023
3751  1.002  0.662419  4.0  0.757519  0.606957
3752  1.002  0.662605  4.0  0.760584  0.606891
3753  1.003  0.662792  4.0  0.763642  0.606826

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.956369  5.0  0.903928  0.993045
3746  0.998  0.956259  5.0  0.903147  0.993045
3747  0.998  0.956150  5.0  0.902509  0.993045
3748  0.999  0.956040  5.0  0.902009  0.993045

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.955822  5.0  0.901411  0.993045
3751  1.002  0.955712  5.0  0.901304  0.993045
3752  1.002  0.955603  5.0  0.901320  0.993045
3753  1.003  0.955493  5.0  0.901454  0.993045

3750

<lambdifygenerated-20887>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1
<lambdifygenerated-20888>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1
<lambdifygenerated-20895>:2: RuntimeWarning: invalid value encountered in power
  return _a7_**(_a0_ + x1**x1)
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-20896>:2: RuntimeWarning: invalid value encountered in power
  return _a7_**(_a0_ + x1**x1)
<lambdifygenerated-20897>:2: RuntimeWarning: overflow encountered in power
  return _a7_**(_a0_ + _a6_**x1)
/usr/local/lib/python3.10/dist-packages/scipy/optimize/_minpack_py.py:497: RuntimeWarning: overflow encountered in matmul
  cov_x = invR @ invR.T
<lambdifygenerated-20903>:2: RuntimeWarning: overflow encountered in power
  return _a7_**(_a0_ + _a6_**x1)

interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.428260  6.0  0.369956  0.396129
3746  0.998  0.428367  6.0  0.369870  0.396131
3747  0.998  0.428474  6.0  0.369872  0.396132
3748  0.999  0.428581  6.0  0.369959  0.396133

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.428794  6.0  0.370371  0.396135
3751  1.002  0.428901  6.0  0.370689  0.396136
3752  1.002  0.429008  6.0  0.371078  0.396137
3753  1.003  0.429115  6.0  0.371534  0.396139

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.173654  7.0  0.258844  0.134508
3746  0.998  0.173884  7.0  0.260979  0.134724
3747  0.998  0.174114  7.0  0.263024  0.134940
3748  0.999  0.174344  7.0  0.264985  0.135156

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.174804  7.0  0.268668  0.135589
3751  1.002  0.175034  7.0  0.270398  0.135806
3752  1.002  0.175264  7.0  0.272060  0.136023
3753  1.003  0.175494  7.0  0.273657  0.136240

3750

<lambdifygenerated-20927>:2: RuntimeWarning: invalid value encountered in power
  return x1 + x1**x1
<lambdifygenerated-20928>:2: RuntimeWarning: invalid value encountered in power
  return x1 + x1**x1
<lambdifygenerated-20931>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (_a4_/x1)**x1
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-20932>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (_a4_/x1)**x1
<lambdifygenerated-20937>:2: RuntimeWarning: invalid value encountered in power
  return x1 + (_a4_/(_a5_ + x1)**2)**x1

interpolation

<lambdifygenerated-20943>:2: RuntimeWarning: invalid value encountered in power
  return _a5_ + (_a4_/(_a5_ + x1)**2)**_a5_
<lambdifygenerated-20947>:2: RuntimeWarning: invalid value encountered in power
  return _a5_ + (_a4_/(_a5_ + x1)**2)**_a5_

         x1         y  rep    ymodel      ybms
3745  0.997  0.261188  8.0  0.268647  0.225697
3746  0.998  0.261362  8.0  0.259357  0.225840
3747  0.998  0.261535  8.0  0.250279  0.225983
3748  0.999  0.261709  8.0  0.241416  0.226126

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.262056  8.0  0.224329  0.226411
3751  1.002  0.262229  8.0  0.216105  0.226553
3752  1.002  0.262402  8.0  0.208089  0.226696
3753  1.003  0.262576  8.0  0.200280  0.226838

3750
interpolation

<lambdifygenerated-20953>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1
<lambdifygenerated-20954>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1

         x1        y  rep    ymodel      ybms
3745  0.997  0.64259  9.0  0.564552  0.595579
3746  0.998  0.64247  9.0  0.553441  0.595313
3747  0.998  0.64235  9.0  0.542503  0.595047
3748  0.999  0.64223  9.0  0.531749  0.594782

extrapolation

         x1        y  rep    ymodel      ybms
3750  1.001  0.64199  9.0  0.510825  0.594250
3751  1.002  0.64187  9.0  0.500667  0.593984
3752  1.002  0.64175  9.0  0.490718  0.593718
3753  1.003  0.64163  9.0  0.480980  0.593452

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.360683  0.0  0.394133  0.345288
3746  0.998  0.360826  0.0  0.394399  0.345404
3747  0.998  0.360969  0.0  0.394666  0.345519
3748  0.999  0.361111  0.0  0.394933  0.345635

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.361396  0.0  0.395467  0.345866
3751  1.002  0.361539  0.0  0.395734  0.345982
3752  1.002  0.361681  0.0  0.396001  0.346098
3753  1.003  0.361824  0.0  0.396269  0.346214

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.875844  1.0  0.942594  0.967581
3746  0.998  0.875274  1.0  0.942588  0.967581
3747  0.998  0.874704  1.0  0.942582  0.967581
3748  0.999  0.874135  1.0  0.942577  0.967581

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.872995  1.0  0.942566  0.967581
3751  1.002  0.872426  1.0  0.942560  0.967581
3752  1.002  0.871856  1.0  0.942555  0.967581
3753  1.003  0.871287  1.0  0.942550  0.967581

3750
interpolation

<lambdifygenerated-21001>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1
<lambdifygenerated-21002>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1

         x1         y  rep    ymodel      ybms
3745  0.997  0.997734  2.0  0.871005  0.999998
3746  0.998  0.997761  2.0  0.868714  0.999997
3747  0.998  0.997787  2.0  0.866404  0.999996
3748  0.999  0.997814  2.0  0.864075  0.999995

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.997867  2.0  0.859357  0.999992
3751  1.002  0.997894  2.0  0.856968  0.999991
3752  1.002  0.997921  2.0  0.854560  0.999990
3753  1.003  0.997948  2.0  0.852132  0.999988

3750
interpolation

<lambdifygenerated-21021>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1
<lambdifygenerated-21022>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1
<lambdifygenerated-21025>:2: RuntimeWarning: invalid value encountered in power
  return _a1_**(x1**x1)
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-21026>:2: RuntimeWarning: invalid value encountered in power
  return _a1_**(x1**x1)

         x1         y  rep    ymodel      ybms
3745  0.997  0.689029  3.0  0.776519  0.698901
3746  0.998  0.688777  3.0  0.777001  0.698364
3747  0.998  0.688525  3.0  0.777487  0.697827
3748  0.999  0.688273  3.0  0.777976  0.697289

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.687768  3.0  0.778966  0.696211
3751  1.002  0.687516  3.0  0.779466  0.695670
3752  1.002  0.687264  3.0  0.779970  0.695129
3753  1.003  0.687012  3.0  0.780477  0.694588

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.661298  4.0  0.614287  0.558954
3746  0.998  0.661485  4.0  0.614321  0.558853
3747  0.998  0.661672  4.0  0.614354  0.558752
3748  0.999  0.661858  4.0  0.614385  0.558652

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.662232  4.0  0.614445  0.558450
3751  1.002  0.662419  4.0  0.614473  0.558349
3752  1.002  0.662605  4.0  0.614500  0.558249
3753  1.003  0.662792  4.0  0.614526  0.558148

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.956369  5.0  1.006775  0.981199
3746  0.998  0.956259  5.0  1.006997  0.981199
3747  0.998  0.956150  5.0  1.007220  0.981199
3748  0.999  0.956040  5.0  1.007443  0.981199

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.955822  5.0  1.007890  0.981199
3751  1.002  0.955712  5.0  1.008113  0.981199
3752  1.002  0.955603  5.0  1.008336  0.981199
3753  1.003  0.955493  5.0  1.008560  0.981199

3750
interpolation

/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(

         x1         y  rep    ymodel      ybms
3745  0.997  0.428260  6.0  0.419662  0.454553
3746  0.998  0.428367  6.0  0.419766  0.454578
3747  0.998  0.428474  6.0  0.419870  0.454602
3748  0.999  0.428581  6.0  0.419976  0.454626

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.428794  6.0  0.420190  0.454675
3751  1.002  0.428901  6.0  0.420298  0.454699
3752  1.002  0.429008  6.0  0.420407  0.454723
3753  1.003  0.429115  6.0  0.420517  0.454747

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.173654  7.0  0.150033  0.136503
3746  0.998  0.173884  7.0  0.150307  0.136722
3747  0.998  0.174114  7.0  0.150582  0.136942
3748  0.999  0.174344  7.0  0.150856  0.137161

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.174804  7.0  0.151405  0.137601
3751  1.002  0.175034  7.0  0.151679  0.137821
3752  1.002  0.175264  7.0  0.151954  0.138041
3753  1.003  0.175494  7.0  0.152229  0.138261

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.261188  8.0  0.232784  0.240372
3746  0.998  0.261362  8.0  0.232883  0.240572
3747  0.998  0.261535  8.0  0.232981  0.240773
3748  0.999  0.261709  8.0  0.233080  0.240973

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.262056  8.0  0.233279  0.241372
3751  1.002  0.262229  8.0  0.233379  0.241572
3752  1.002  0.262402  8.0  0.233479  0.241771
3753  1.003  0.262576  8.0  0.233580  0.241970

3750
interpolation

<lambdifygenerated-21125>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1
<lambdifygenerated-21126>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1

         x1        y  rep    ymodel      ybms
3745  0.997  0.64259  9.0  0.688802  0.647026
3746  0.998  0.64247  9.0  0.689225  0.646787
3747  0.998  0.64235  9.0  0.689655  0.646547
3748  0.999  0.64223  9.0  0.690092  0.646307

extrapolation

         x1        y  rep    ymodel      ybms
3750  1.001  0.64199  9.0  0.690987  0.645828
3751  1.002  0.64187  9.0  0.691445  0.645588
3752  1.002  0.64175  9.0  0.691909  0.645349
3753  1.003  0.64163  9.0  0.692380  0.645109

3750
interpolation

<lambdifygenerated-21147>:2: RuntimeWarning: invalid value encountered in power
  return x1*x1**x1
<lambdifygenerated-21148>:2: RuntimeWarning: invalid value encountered in power
  return x1*x1**x1
<lambdifygenerated-21151>:2: RuntimeWarning: invalid value encountered in power
  return _a0_**(x1**x1)*x1
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-21152>:2: RuntimeWarning: invalid value encountered in power
  return _a0_**(x1**x1)*x1
<lambdifygenerated-21153>:2: RuntimeWarning: invalid value encountered in power
  return _a0_**((x1**2)**x1)*x1

         x1         y  rep    ymodel      ybms
3745  0.997  0.360683  0.0  0.256727  0.309572
3746  0.998  0.360826  0.0  0.256318  0.309587
3747  0.998  0.360969  0.0  0.255907  0.309602
3748  0.999  0.361111  0.0  0.255497  0.309618

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.361396  0.0  0.254673  0.309648
3751  1.002  0.361539  0.0  0.254260  0.309663
3752  1.002  0.361681  0.0  0.253847  0.309678
3753  1.003  0.361824  0.0  0.253433  0.309693

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.875844  1.0  0.879712  0.960401
3746  0.998  0.875274  1.0  0.879461  0.960401
3747  0.998  0.874704  1.0  0.879210  0.960401
3748  0.999  0.874135  1.0  0.878959  0.960401

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.872995  1.0  0.878456  0.960401
3751  1.002  0.872426  1.0  0.878205  0.960401
3752  1.002  0.871856  1.0  0.877953  0.960401
3753  1.003  0.871287  1.0  0.877700  0.960401

3750
interpolation

<lambdifygenerated-21179>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1
<lambdifygenerated-21180>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1

         x1         y  rep    ymodel      ybms
3745  0.997  0.997734  2.0  1.036108  0.999358
3746  0.998  0.997761  2.0  1.036156  0.999346
3747  0.998  0.997787  2.0  1.036205  0.999333
3748  0.999  0.997814  2.0  1.036252  0.999321

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.997867  2.0  1.036347  0.999295
3751  1.002  0.997894  2.0  1.036394  0.999283
3752  1.002  0.997921  2.0  1.036441  0.999270
3753  1.003  0.997948  2.0  1.036487  0.999256

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.689029  3.0  0.704347  0.673087
3746  0.998  0.688777  3.0  0.704119  0.672594
3747  0.998  0.688525  3.0  0.703891  0.672100
3748  0.999  0.688273  3.0  0.703663  0.671606

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.687768  3.0  0.703208  0.670616
3751  1.002  0.687516  3.0  0.702981  0.670119
3752  1.002  0.687264  3.0  0.702754  0.669622
3753  1.003  0.687012  3.0  0.702527  0.669125

3750
interpolation

<lambdifygenerated-21223>:2: RuntimeWarning: invalid value encountered in power
  return _a4_*x1**x1
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-21224>:2: RuntimeWarning: invalid value encountered in power
  return _a4_*x1**x1
<lambdifygenerated-21225>:2: RuntimeWarning: invalid value encountered in power
  return _a3_**x1*_a4_

         x1         y  rep    ymodel      ybms
3745  0.997  0.661298  4.0  0.654833  0.589453
3746  0.998  0.661485  4.0  0.654848  0.589379
3747  0.998  0.661672  4.0  0.654862  0.589305
3748  0.999  0.661858  4.0  0.654876  0.589231

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.662232  4.0  0.654904  0.589083
3751  1.002  0.662419  4.0  0.654918  0.589009
3752  1.002  0.662605  4.0  0.654931  0.588935
3753  1.003  0.662792  4.0  0.654945  0.588861

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.956369  5.0  0.976246  0.972753
3746  0.998  0.956259  5.0  0.976223  0.972753
3747  0.998  0.956150  5.0  0.976200  0.972753
3748  0.999  0.956040  5.0  0.976177  0.972753

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.955822  5.0  0.976131  0.972753
3751  1.002  0.955712  5.0  0.976109  0.972753
3752  1.002  0.955603  5.0  0.976086  0.972753
3753  1.003  0.955493  5.0  0.976063  0.972753

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.428260  6.0  0.446795  0.408856
3746  0.998  0.428367  6.0  0.446978  0.408861
3747  0.998  0.428474  6.0  0.447162  0.408865
3748  0.999  0.428581  6.0  0.447346  0.408870

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.428794  6.0  0.447714  0.408879
3751  1.002  0.428901  6.0  0.447898  0.408883
3752  1.002  0.429008  6.0  0.448082  0.408888
3753  1.003  0.429115  6.0  0.448267  0.408893

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.173654  7.0  0.217683  0.131440
3746  0.998  0.173884  7.0  0.218175  0.131652
3747  0.998  0.174114  7.0  0.218668  0.131863
3748  0.999  0.174344  7.0  0.219160  0.132074

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.174804  7.0  0.220144  0.132498
3751  1.002  0.175034  7.0  0.220635  0.132709
3752  1.002  0.175264  7.0  0.221127  0.132922
3753  1.003  0.175494  7.0  0.221618  0.133134

3750
interpolation

<lambdifygenerated-21283>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1
<lambdifygenerated-21284>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1

         x1         y  rep    ymodel      ybms
3745  0.997  0.261188  8.0  0.274590  0.229041
3746  0.998  0.261362  8.0  0.275074  0.229185
3747  0.998  0.261535  8.0  0.275559  0.229329
3748  0.999  0.261709  8.0  0.276044  0.229472

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.262056  8.0  0.277018  0.229760
3751  1.002  0.262229  8.0  0.277505  0.229904
3752  1.002  0.262402  8.0  0.277994  0.230047
3753  1.003  0.262576  8.0  0.278483  0.230191

3750
interpolation

         x1        y  rep    ymodel      ybms
3745  0.997  0.64259  9.0  0.578333  0.596680
3746  0.998  0.64247  9.0  0.577875  0.596378
3747  0.998  0.64235  9.0  0.577418  0.596076
3748  0.999  0.64223  9.0  0.576962  0.595774

extrapolation

         x1        y  rep    ymodel      ybms
3750  1.001  0.64199  9.0  0.576053  0.595169
3751  1.002  0.64187  9.0  0.575600  0.594867
3752  1.002  0.64175  9.0  0.575147  0.594565
3753  1.003  0.64163  9.0  0.574696  0.594262

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.360683  0.0  0.359456  0.419499
3746  0.998  0.360826  0.0  0.359600  0.419835
3747  0.998  0.360969  0.0  0.359744  0.420171
3748  0.999  0.361111  0.0  0.359887  0.420507

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.361396  0.0  0.360175  0.421180
3751  1.002  0.361539  0.0  0.360319  0.421517
3752  1.002  0.361681  0.0  0.360463  0.421855
3753  1.003  0.361824  0.0  0.360607  0.422192

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.875844  1.0  0.933419  0.963396
3746  0.998  0.875274  1.0  0.933427  0.963396
3747  0.998  0.874704  1.0  0.933435  0.963396
3748  0.999  0.874135  1.0  0.933443  0.963396

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.872995  1.0  0.933459  0.963396
3751  1.002  0.872426  1.0  0.933467  0.963396
3752  1.002  0.871856  1.0  0.933475  0.963396
3753  1.003  0.871287  1.0  0.933483  0.963396

3750
interpolation

<lambdifygenerated-21361>:2: RuntimeWarning: invalid value encountered in power
  return sin(_a4_*x1**x1)**2
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-21362>:2: RuntimeWarning: invalid value encountered in power
  return sin(_a4_*x1**x1)**2

         x1         y  rep    ymodel      ybms
3745  0.997  0.997734  2.0  0.946819  0.917121
3746  0.998  0.997761  2.0  0.946823  0.916865
3747  0.998  0.997787  2.0  0.946827  0.916608
3748  0.999  0.997814  2.0  0.946831  0.916351

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.997867  2.0  0.946839  0.915836
3751  1.002  0.997894  2.0  0.946843  0.915577
3752  1.002  0.997921  2.0  0.946847  0.915319
3753  1.003  0.997948  2.0  0.946851  0.915059

<lambdifygenerated-21375>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1
<lambdifygenerated-21376>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1
<lambdifygenerated-21379>:2: RuntimeWarning: invalid value encountered in power
  return _a5_**(x1**x1)
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-21380>:2: RuntimeWarning: invalid value encountered in power
  return _a5_**(x1**x1)

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.689029  3.0  0.695481  0.676518
3746  0.998  0.688777  3.0  0.695290  0.676025
3747  0.998  0.688525  3.0  0.695099  0.675532
3748  0.999  0.688273  3.0  0.694908  0.675039

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.687768  3.0  0.694527  0.674050
3751  1.002  0.687516  3.0  0.694336  0.673554
3752  1.002  0.687264  3.0  0.694147  0.673058
3753  1.003  0.687012  3.0  0.693957  0.672562

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.661298  4.0  0.626549  0.567977
3746  0.998  0.661485  4.0  0.626627  0.567882
3747  0.998  0.661672  4.0  0.626707  0.567787
3748  0.999  0.661858  4.0  0.626786  0.567692

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.662232  4.0  0.626945  0.567503
3751  1.002  0.662419  4.0  0.627024  0.567408
3752  1.002  0.662605  4.0  0.627104  0.567314
3753  1.003  0.662792  4.0  0.627183  0.567219

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.956369  5.0  1.003093  0.981124
3746  0.998  0.956259  5.0  1.003161  0.981124
3747  0.998  0.956150  5.0  1.003230  0.981124
3748  0.999  0.956040  5.0  1.003298  0.981124

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.955822  5.0  1.003436  0.981124
3751  1.002  0.955712  5.0  1.003504  0.981124
3752  1.002  0.955603  5.0  1.003573  0.981124
3753  1.003  0.955493  5.0  1.003641  0.981124

3750
interpolation

<lambdifygenerated-21427>:2: RuntimeWarning: invalid value encountered in power
  return _a2_*x1**x1 + x1
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-21428>:2: RuntimeWarning: invalid value encountered in power
  return _a2_*x1**x1 + x1
<lambdifygenerated-21429>:2: RuntimeWarning: invalid value encountered in power
  return _a2_*_a7_**x1 + x1

         x1         y  rep    ymodel      ybms
3745  0.997  0.428260  6.0  0.405589  0.452714
3746  0.998  0.428367  6.0  0.405570  0.452758
3747  0.998  0.428474  6.0  0.405551  0.452803
3748  0.999  0.428581  6.0  0.405532  0.452847

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.428794  6.0  0.405493  0.452935
3751  1.002  0.428901  6.0  0.405474  0.452979
3752  1.002  0.429008  6.0  0.405455  0.453023
3753  1.003  0.429115  6.0  0.405435  0.453067

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.173654  7.0  0.114645  0.137593
3746  0.998  0.173884  7.0  0.114789  0.137814
3747  0.998  0.174114  7.0  0.114932  0.138035
3748  0.999  0.174344  7.0  0.115076  0.138257

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.174804  7.0  0.115362  0.138700
3751  1.002  0.175034  7.0  0.115505  0.138922
3752  1.002  0.175264  7.0  0.115648  0.139144
3753  1.003  0.175494  7.0  0.115791  0.139366

3750

<lambdifygenerated-21459>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1
<lambdifygenerated-21460>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1
<lambdifygenerated-21463>:2: RuntimeWarning: invalid value encountered in power
  return _a0_**(x1**x1)
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/ann_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-21464>:2: RuntimeWarning: invalid value encountered in power
  return _a0_**(x1**x1)
<lambdifygenerated-21467>:2: RuntimeWarning: invalid value encountered in power
  return _a0_**((4*x1**2)**x1)
<lambdifygenerated-21473>:2: RuntimeWarning: invalid value encountered in power
  return _a0_**(((_a2_ + x1)**2)**_a2_)

interpolation

<lambdifygenerated-21477>:2: RuntimeWarning: invalid value encountered in power
  return _a0_**(((_a2_ + x1)**2)**_a2_)

         x1         y  rep    ymodel      ybms
3745  0.997  0.261188  8.0  0.237318  0.219260
3746  0.998  0.261362  8.0  0.237696  0.219403
3747  0.998  0.261535  8.0  0.238074  0.219545
3748  0.999  0.261709  8.0  0.238452  0.219686

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.262056  8.0  0.239208  0.219970
3751  1.002  0.262229  8.0  0.239585  0.220112
3752  1.002  0.262402  8.0  0.239962  0.220253
3753  1.003  0.262576  8.0  0.240338  0.220394

3750
interpolation

         x1        y  rep    ymodel      ybms
3745  0.997  0.64259  9.0  0.692185  0.625695
3746  0.998  0.64247  9.0  0.692187  0.625386
3747  0.998  0.64235  9.0  0.692189  0.625076
3748  0.999  0.64223  9.0  0.692190  0.624767

extrapolation

         x1        y  rep    ymodel      ybms
3750  1.001  0.64199  9.0  0.692194  0.624148
3751  1.002  0.64187  9.0  0.692195  0.623838
3752  1.002  0.64175  9.0  0.692197  0.623528
3753  1.003  0.64163  9.0  0.692199  0.623218

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.360683  0.0  0.386661  0.366665
3746  0.998  0.360826  0.0  0.386833  0.366751
3747  0.998  0.360969  0.0  0.387005  0.366838
3748  0.999  0.361111  0.0  0.387176  0.366924

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.361396  0.0  0.387520  0.367096
3751  1.002  0.361539  0.0  0.387691  0.367182
3752  1.002  0.361681  0.0  0.387863  0.367268
3753  1.003  0.361824  0.0  0.388035  0.367354

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.875844  1.0  0.863385  0.959342
3746  0.998  0.875274  1.0  0.863066  0.959342
3747  0.998  0.874704  1.0  0.862746  0.959342
3748  0.999  0.874135  1.0  0.862426  0.959342

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.872995  1.0  0.861785  0.959342
3751  1.002  0.872426  1.0  0.861464  0.959342
3752  1.002  0.871856  1.0  0.861143  0.959342
3753  1.003  0.871287  1.0  0.860822  0.959342

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.997734  2.0  0.954962  0.996399
3746  0.998  0.997761  2.0  0.954879  0.996370
3747  0.998  0.997787  2.0  0.954795  0.996342
3748  0.999  0.997814  2.0  0.954711  0.996313

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.997867  2.0  0.954542  0.996255
3751  1.002  0.997894  2.0  0.954458  0.996226
3752  1.002  0.997921  2.0  0.954374  0.996197
3753  1.003  0.997948  2.0  0.954289  0.996168

3750
interpolation

<lambdifygenerated-21553>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1
<lambdifygenerated-21554>:2: RuntimeWarning: invalid value encountered in power
  return x1**x1

         x1         y  rep    ymodel      ybms
3745  0.997  0.689029  3.0  0.726713  0.678774
3746  0.998  0.688777  3.0  0.726830  0.678353
3747  0.998  0.688525  3.0  0.726948  0.677931
3748  0.999  0.688273  3.0  0.727066  0.677509

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.687768  3.0  0.727307  0.676664
3751  1.002  0.687516  3.0  0.727428  0.676241
3752  1.002  0.687264  3.0  0.727551  0.675818
3753  1.003  0.687012  3.0  0.727674  0.675394

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.661298  4.0  0.611905  0.593093
3746  0.998  0.661485  4.0  0.611884  0.593009
3747  0.998  0.661672  4.0  0.611862  0.592925
3748  0.999  0.661858  4.0  0.611841  0.592841

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.662232  4.0  0.611798  0.592673
3751  1.002  0.662419  4.0  0.611776  0.592589
3752  1.002  0.662605  4.0  0.611755  0.592505
3753  1.003  0.662792  4.0  0.611734  0.592421

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.956369  5.0  0.973080  0.985853
3746  0.998  0.956259  5.0  0.973042  0.985853
3747  0.998  0.956150  5.0  0.973005  0.985853
3748  0.999  0.956040  5.0  0.972967  0.985853

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.955822  5.0  0.972893  0.985853
3751  1.002  0.955712  5.0  0.972855  0.985853
3752  1.002  0.955603  5.0  0.972818  0.985853
3753  1.003  0.955493  5.0  0.972781  0.985853

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.428260  6.0  0.396199  0.417282
3746  0.998  0.428367  6.0  0.396186  0.417287
3747  0.998  0.428474  6.0  0.396173  0.417292
3748  0.999  0.428581  6.0  0.396160  0.417297

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.428794  6.0  0.396134  0.417307
3751  1.002  0.428901  6.0  0.396121  0.417312
3752  1.002  0.429008  6.0  0.396108  0.417316
3753  1.003  0.429115  6.0  0.396096  0.417321

3750
interpolation

         x1         y  rep    ymodel      ybms
3745  0.997  0.173654  7.0  0.181604  0.283071
3746  0.998  0.173884  7.0  0.181627  0.283396
3747  0.998  0.174114  7.0  0.181650  0.283722
3748  0.999  0.174344  7.0  0.181673  0.284048

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.174804  7.0  0.181718  0.284699
3751  1.002  0.175034  7.0  0.181740  0.285025
3752  1.002  0.175264  7.0  0.181763  0.285350
3753  1.003  0.175494  7.0  0.181785  0.285676

3750
interpolation

<lambdifygenerated-21645>:2: RuntimeWarning: invalid value encountered in power
  return x1*x1**x1
<lambdifygenerated-21646>:2: RuntimeWarning: invalid value encountered in power
  return x1*x1**x1

         x1         y  rep    ymodel      ybms
3745  0.997  0.261188  8.0  0.198622  0.229696
3746  0.998  0.261362  8.0  0.198632  0.229820
3747  0.998  0.261535  8.0  0.198642  0.229944
3748  0.999  0.261709  8.0  0.198652  0.230068

extrapolation

         x1         y  rep    ymodel      ybms
3750  1.001  0.262056  8.0  0.198672  0.230316
3751  1.002  0.262229  8.0  0.198681  0.230440
3752  1.002  0.262402  8.0  0.198691  0.230563
3753  1.003  0.262576  8.0  0.198701  0.230687

3750
interpolation

         x1        y  rep    ymodel      ybms
3745  0.997  0.64259  9.0  0.716926  0.633432
3746  0.998  0.64247  9.0  0.716921  0.633157
3747  0.998  0.64235  9.0  0.716917  0.632883
3748  0.999  0.64223  9.0  0.716913  0.632609

extrapolation

         x1        y  rep    ymodel      ybms
3750  1.001  0.64199  9.0  0.716904  0.632059
3751  1.002  0.64187  9.0  0.716900  0.631785
3752  1.002  0.64175  9.0  0.716896  0.631510
3753  1.003  0.64163  9.0  0.716892  0.631235

,sigma,function,mae_nn_interp.,mae_nn_extrap.,mae_mdl_interp.,mae_mdl_extrap.,rmse_nn_interp.,rmse_nn_extrap.,rmse_mdl_interp.,rmse_mdl_extrap.,n,r
0,0.0,tanh,0.000853,0.013224,0.000273,0.019884,0.001288,0.013445,0.000354,0.025308,0,0
1,0.0,tanh,0.001841,0.010059,0.001976,0.116273,0.002560,0.011410,0.002339,0.152121,1,0
2,0.0,tanh,0.000912,0.050137,0.001519,0.298283,0.001101,0.069633,0.001971,0.335729,2,0
3,0.0,tanh,0.000196,0.023162,0.000119,0.174840,0.000230,0.030903,0.000175,2.283758,3,0
4,0.0,tanh,0.000404,0.017901,0.000060,0.010950,0.000509,0.020898,0.000069,0.013071,4,0
...,...,...,...,...,...,...,...,...,...,...,...,...
655,0.2,leaky_ReLU,0.022261,0.118110,0.009094,0.151337,0.031651,0.138461,0.010507,0.172584,5,2
656,0.2,leaky_ReLU,0.015896,0.099963,0.013044,0.079376,0.024994,0.107615,0.017945,0.089668,6,2
657,0.2,leaky_ReLU,0.038772,0.126559,0.031943,0.141442,0.048350,0.150152,0.041721,0.142647,7,2
658,0.2,leaky_ReLU,0.039122,0.176571,0.030463,0.078499,0.050074,0.189842,0.036354,0.085304,8,2
659,0.2,leaky_ReLU,0.049552,0.158156,0.025762,0.114919,0.065606,0.166579,0.029401,0.130261,9,2