In [1]:
#This script takes every simulation with all points and calculates rmse and mae in each case

In [6]:
import pandas as pd
import numpy as np
import matplotlib
import matplotlib.pyplot as plt

from matplotlib.pyplot import figure
import seaborn as sns
import matplotlib.gridspec as gridspec
import ast
import sys
sys.path.append('../no_degeneracy/')
sys.path.append('../no_degeneracy/Prior/')
from mcmc import *
from parallel import *
from fit_prior import read_prior_par
from sklearn.metrics import mean_squared_error
from sklearn.metrics import root_mean_squared_error
from sklearn.metrics import mean_absolute_error

In [7]:
def clean_index(dataframe):
    dataframe.set_index('Unnamed: 0', inplace=True)
    dataframe.index.name = None
    dataframe= dataframe.reset_index(drop=True)
    return dataframe
#-------------------------------------------------------------------------

#add predictions of bms to the dataframe. Acommodate for 2dimensional functions
def add_bms_pred(dataframe, bms_trace, number_param, dimensions=False):

    if dimensions==True:
         VARS = ['x','y',]
         prior_par = read_prior_par('../no_degeneracy/Prior/final_prior_param_sq.named_equations.nv2.np10.2016-09-09 18:49:42.600380.dat')
    else:
        VARS = ['x',]
        prior_par = read_prior_par('../no_degeneracy/Prior/final_prior_param_sq.named_equations.nv1.np10.2017-10-18 18:07:35.089658.dat')

    try:
        x = dataframe[[c for c in VARS]].copy()
        y=dataframe.z
    except KeyError:
        print("HOLA!")

        
        VARS = ['x1',]
        x = dataframe[[c for c in VARS]].copy()
        y=dataframe.y
    

    #mdl model
    minrow = bms_trace[bms_trace.H == min(bms_trace.H)].iloc[0]
    minH, minexpr, minparvals = minrow.H, minrow.expr, ast.literal_eval(minrow.parvals)

    
    t = Tree(
        variables=list(x.columns),
        parameters=['a%d' % i for i in range(number_param)],
        x=x, y=y,
        prior_par=prior_par,
        max_size=200,
        from_string=minexpr,
    )

    t.set_par_values(deepcopy(minparvals))

    dplot = deepcopy(dataframe)
    dplot['zbms'] = t.predict(x)


    return dplot
#-------------------------------------------------------------------------

#Append indices from the approximation dataset that need to be removed from the interpolation dataset
def rows_to_remove(function_name, index_length,step):
    n0=0 #initial index
    
    if function_name=='10':
        n_points_interpolation=int(np.sqrt(index_length))  #number of rows or columns in the interpolation grid
        n_points_row=int(n_points_interpolation/5)         #number of rows or columns in the approximation grid

        print(n_points_interpolation)
        print(n_points_row)
        
        for i in range(n_points_row):
            print(n0)
            a1=np.arange(n0,n0+n_points_interpolation,step)#Get indices in the interpolation column/row that exist in the approximation
            n0=a1[-1] + n_points_interpolation*4 + 5 #Hop over row/column indices of the interpolation grid that dont exist in the approximation grid
            
            try:
                approximation_indices=np.append(approximation_indices,a1) #append indices to remove from each set of columns/rows
            except NameError:
                approximation_indices=a1 #initialize array

    else:
        approximation_indices=np.arange(n0,n0+n_points_int,step)#Get indices in the interpolation column/row that exist in the approximation

    return approximation_indices

In [5]:
#Read NN and BMS data
functions=['1', '5' , '7', '8', '10']
realizations=2
sigmas=[0.0, 0.02, 0.04,0.06, 0.08, 0.1, 0.12, 0.14, 0.16, 0.18, 0.20]

runid=0
NPAR=10 #10, 20
steps=50000


interpolation_step=5
train_fraction=3/4

rmse_nn_train=[];rmse_nn_test=[]
rmse_mdl_train=[];rmse_mdl_test=[]
mae_nn_train=[];mae_nn_test=[]
mae_mdl_train=[];mae_mdl_test=[]

n_index=[];r_index=[];sigma_index=[];function_index=[]

#Put mae and rmse of each simulation (on nn and bms) in a dataframe
for function in functions:
    for sigma in sigmas:
        for r in range(realizations+1):
            
            #Save indices for dataframe
            r_index.append(r);sigma_index.append(sigma);function_index.append(function)
            
            #Read NN data: original and high resolution
            #------------------------------------------------------------------------------------------
            original_file_path='../../data/nns/nguyen/approximation/'
            model_d='NN_no_overfit_sigma_' + str(sigma) + '_r_' + str(r) + '.csv'
            d=pd.read_csv(original_file_path + model_d)

            hr_file_path='../../data/nns/nguyen/inter_extrapolation/'
            model_dhr='NN_no_overfit_inter_extrapolation_sigma_' + str(sigma) + '_r_' + str(r) + '.csv'
            dhr=pd.read_csv(hr_file_path + model_dhr)
            #------------------------------------------------------------------------------------------

            #High resolution dataset: run over functions
            #-------------------------------------------------------------
            dnhr=dhr[dhr['rep']==int(function)]
            dnhr=clean_index(dnhr)
            #-------------------------------------------------------------

            #Read BMS data
            #-------------------------------------------------------------
            trace_path='../../data/MSTraces/nguyen/'
            filename='BMS_nguyen_n_'+str(function)+'_sigma_'+str(sigma)+ '_r_' + str(r) + '_trace_'+str(steps)+'_prior_'+str(NPAR)+ '.csv'
            trace=pd.read_csv(trace_path + filename, sep=';', header=None, names=['t', 'H', 'expr', 'parvals', 'kk1', 'kk2','kk3'])
            #-------------------------------------------------------------
            
            #Add BMS prediction to high resolution dataframe
            #-------------------------------------------------------------
            #differentiate one and two-variable functions
            if function=='10':
                dinterpolate=add_bms_pred(dnhr, trace, NPAR, dimensions=True)
            else:
                dinterpolate=add_bms_pred(dnhr, trace, NPAR)
            #-------------------------------------------------------------
            
            #Remove points of approximation from the dataset
            #-------------------------------------------------------------
            dn=d[d['rep']==int(function)]
            dn=clean_index(dn)

            #n_points_app=int(len(dn.index))
            n_points_int=int(len(dinterpolate.index))
            approximation_indices=rows_to_remove(function,n_points_int,interpolation_step)

            dinterpolate=dinterpolate.drop(approximation_indices)
            display(dinterpolate)
            #-------------------------------------------------------------
            
            
            #Compute and save Errors to dataframe
            #-----------------------------------------------------------------------------------------------------------------------            
            n_points=int(len(dnhr.index))
            train_size_bms=int(n_points*train_fraction)           
            print(train_size_bms)

            
            #nn errors
            rmse_nn_train_i=root_mean_squared_error(dinterpolate.loc[:train_size_bms-1]['zmodel'],dinterpolate.loc[:train_size_bms -1]['z'])
            rmse_nn_train.append(rmse_nn_train_i)
                
            rmse_nn_test_i=root_mean_squared_error(dinterpolate.loc[train_size_bms-1:]['zmodel'],dinterpolate.loc[train_size_bms -1:]['z'])
            rmse_nn_test.append(rmse_nn_test_i)

            mae_nn_train_i=mean_absolute_error(dinterpolate.loc[:train_size_bms-1]['zmodel'],dinterpolate.loc[:train_size_bms -1]['z'])
            mae_nn_train.append(mae_nn_train_i)
            
            mae_nn_test_i=mean_absolute_error(dinterpolate.loc[train_size_bms-1:]['zmodel'],dinterpolate.loc[train_size_bms -1:]['z'])
            mae_nn_test.append(mae_nn_test_i)
        
            #bms errors
            try:
                rmse_mdl_train_i=root_mean_squared_error(dinterpolate.loc[:train_size_bms-1]['zbms'],dinterpolate.loc[:train_size_bms-1]['z'])
            except ValueError:
                rmse_mdl_train_i=np.inf
            rmse_mdl_train.append(rmse_mdl_train_i)

            try:
                rmse_mdl_test_i=root_mean_squared_error(dinterpolate.loc[train_size_bms-1:]['zbms'],dinterpolate.loc[train_size_bms-1:]['z'])
            except ValueError:
                rmse_mdl_test_i=np.inf
                    
            rmse_mdl_test.append(rmse_mdl_test_i)

            try:
                mae_mdl_train_i=mean_absolute_error(dinterpolate.loc[:train_size_bms-1]['zbms'],dinterpolate.loc[:train_size_bms-1]['z'])
            except ValueError:
                mae_mdl_train_i=np.inf
                    
            mae_mdl_train.append(mae_mdl_train_i)

            try:
                mae_mdl_test_i=mean_absolute_error(dinterpolate.loc[train_size_bms-1:]['zbms'],dinterpolate.loc[train_size_bms-1:]['z'])
            except ValueError:
                mae_mdl_test_i=np.inf
                
            mae_mdl_test.append(mae_mdl_test_i)
            #-----------------------------------------------------------------------------------------------------------------------
            

      
errors_df=pd.DataFrame({'sigma':sigma_index, 'function':function_index, 'mae_nn_interp.':mae_nn_train, 'mae_nn_extrap.':mae_nn_test, 
                        'mae_mdl_interp.':mae_mdl_train, 'mae_mdl_extrap.':mae_mdl_test, 'rmse_nn_interp.':rmse_nn_train, 
                        'rmse_nn_extrap.': rmse_nn_test, 'rmse_mdl_interp.':rmse_mdl_train, 'rmse_mdl_extrap.': rmse_mdl_test, 
                        'r': r_index})
errors_df.to_csv('../../data/all_errors_nguyen_interpolation' + '.csv')
display(errors_df)

         x    y         z  rep    zmodel      zbms
1   -0.995  0.0 -3.011651    1 -2.996476 -3.011651
2   -0.990  0.0 -2.973702    1 -2.961468 -2.973702
3   -0.985  0.0 -2.936150    1 -2.926631 -2.936150
4   -0.980  0.0 -2.898993    1 -2.891973 -2.898993
6   -0.970  0.0 -2.825853    1 -2.823222 -2.825853
..     ...  ...       ...  ...       ...       ...
394  0.970  0.0  6.815269    1  4.414315  6.815269
396  0.980  0.0  6.971089    1  4.450703  6.971089
397  0.985  0.0  7.049904    1  4.468549  7.049904
398  0.990  0.0  7.129326    1  4.486165  7.129326
399  0.995  0.0  7.209357    1  4.503553  7.209357

[320 rows x 6 columns]

300

/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/nguyen_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(

         x    y         z  rep    zmodel      zbms
1   -0.995  0.0 -3.011651    1 -2.998498 -3.011651
2   -0.990  0.0 -2.973702    1 -2.963414 -2.973702
3   -0.985  0.0 -2.936150    1 -2.928490 -2.936150
4   -0.980  0.0 -2.898993    1 -2.893735 -2.898993
6   -0.970  0.0 -2.825853    1 -2.824762 -2.825853
..     ...  ...       ...  ...       ...       ...
394  0.970  0.0  6.815269    1  4.106371  6.815269
396  0.980  0.0  6.971089    1  4.136431  6.971089
397  0.985  0.0  7.049904    1  4.151177  7.049904
398  0.990  0.0  7.129326    1  4.165736  7.129326
399  0.995  0.0  7.209357    1  4.180110  7.209357

[320 rows x 6 columns]

300

         x    y         z  rep    zmodel      zbms
1   -0.995  0.0 -3.011651    1 -3.003757 -3.011651
2   -0.990  0.0 -2.973702    1 -2.967612 -2.973702
3   -0.985  0.0 -2.936150    1 -2.931704 -2.936150
4   -0.980  0.0 -2.898993    1 -2.896036 -2.898993
6   -0.970  0.0 -2.825853    1 -2.825446 -2.825853
..     ...  ...       ...  ...       ...       ...
394  0.970  0.0  6.815269    1  4.423825  6.815269
396  0.980  0.0  6.971089    1  4.463511  6.971089
397  0.985  0.0  7.049904    1  4.483052  7.049904
398  0.990  0.0  7.129326    1  4.502393  7.129326
399  0.995  0.0  7.209357    1  4.521536  7.209357

[320 rows x 6 columns]

300

         x    y         z  rep    zmodel      zbms
1   -0.995  0.0 -3.011651    1 -3.008966 -2.989371
2   -0.990  0.0 -2.973702    1 -2.972773 -2.952690
3   -0.985  0.0 -2.936150    1 -2.936744 -2.916362
4   -0.980  0.0 -2.898993    1 -2.900890 -2.880385
6   -0.970  0.0 -2.825853    1 -2.829749 -2.809477
..     ...  ...       ...  ...       ...       ...
394  0.970  0.0  6.815269    1  4.655834  6.244485
396  0.980  0.0  6.971089    1  4.702091  6.374415
397  0.985  0.0  7.049904    1  4.724862  6.439952
398  0.990  0.0  7.129326    1  4.747395  6.505871
399  0.995  0.0  7.209357    1  4.769691  6.572171

[320 rows x 6 columns]

300

         x    y         z  rep    zmodel      zbms
1   -0.995  0.0 -3.011651    1 -3.002923 -3.007012
2   -0.990  0.0 -2.973702    1 -2.967003 -2.969150
3   -0.985  0.0 -2.936150    1 -2.931293 -2.931684
4   -0.980  0.0 -2.898993    1 -2.895801 -2.894611
6   -0.970  0.0 -2.825853    1 -2.825494 -2.821637
..     ...  ...       ...  ...       ...       ...
394  0.970  0.0  6.815269    1  4.749949  6.785882
396  0.980  0.0  6.971089    1  4.795254  6.941015
397  0.985  0.0  7.049904    1  4.817526  7.019482
398  0.990  0.0  7.129326    1  4.839546  7.098554
399  0.995  0.0  7.209357    1  4.861315  7.178233

[320 rows x 6 columns]

300

         x    y         z  rep    zmodel      zbms
1   -0.995  0.0 -3.011651    1 -2.967661 -3.007014
2   -0.990  0.0 -2.973702    1 -2.935142 -2.969111
3   -0.985  0.0 -2.936150    1 -2.902690 -2.931605
4   -0.980  0.0 -2.898993    1 -2.870312 -2.894494
6   -0.970  0.0 -2.825853    1 -2.805807 -2.821446
..     ...  ...       ...  ...       ...       ...
394  0.970  0.0  6.815269    1  4.434884  6.822644
396  0.980  0.0  6.971089    1  4.479170  6.978616
397  0.985  0.0  7.049904    1  4.501021  7.057508
398  0.990  0.0  7.129326    1  4.522678  7.137008
399  0.995  0.0  7.209357    1  4.544140  7.217117

[320 rows x 6 columns]

300

         x    y         z  rep    zmodel      zbms
1   -0.995  0.0 -3.011651    1 -2.983071 -3.005763
2   -0.990  0.0 -2.973702    1 -2.949675 -2.968333
3   -0.985  0.0 -2.936150    1 -2.916369 -2.931290
4   -0.980  0.0 -2.898993    1 -2.883162 -2.894634
6   -0.970  0.0 -2.825853    1 -2.817079 -2.822467
..     ...  ...       ...  ...       ...       ...
394  0.970  0.0  6.815269    1  4.226639  6.673780
396  0.980  0.0  6.971089    1  4.259671  6.825764
397  0.985  0.0  7.049904    1  4.275855  6.902637
398  0.990  0.0  7.129326    1  4.291820  6.980100
399  0.995  0.0  7.209357    1  4.307569  7.058156

[320 rows x 6 columns]

300

         x    y         z  rep    zmodel      zbms
1   -0.995  0.0 -3.011651    1 -2.984786 -3.012330
2   -0.990  0.0 -2.973702    1 -2.952437 -2.974282
3   -0.985  0.0 -2.936150    1 -2.920113 -2.936631
4   -0.980  0.0 -2.898993    1 -2.887823 -2.899377
6   -0.970  0.0 -2.825853    1 -2.823373 -2.826047
..     ...  ...       ...  ...       ...       ...
394  0.970  0.0  6.815269    1  3.061208  6.799530
396  0.980  0.0  6.971089    1  3.082193  6.955210
397  0.985  0.0  7.049904    1  3.092547  7.033955
398  0.990  0.0  7.129326    1  3.102810  7.113308
399  0.995  0.0  7.209357    1  3.112983  7.193271

[320 rows x 6 columns]

300

         x    y         z  rep    zmodel      zbms
1   -0.995  0.0 -3.011651    1 -2.964789 -3.000337
2   -0.990  0.0 -2.973702    1 -2.931879 -2.962169
3   -0.985  0.0 -2.936150    1 -2.899032 -2.924404
4   -0.980  0.0 -2.898993    1 -2.866257 -2.887040
6   -0.970  0.0 -2.825853    1 -2.800963 -2.813503
..     ...  ...       ...  ...       ...       ...
394  0.970  0.0  6.815269    1  4.113261  6.916968
396  0.980  0.0  6.971089    1  4.146555  7.075549
397  0.985  0.0  7.049904    1  4.162944  7.155762
398  0.990  0.0  7.129326    1  4.179162  7.236594
399  0.995  0.0  7.209357    1  4.195211  7.318047

[320 rows x 6 columns]

300

         x    y         z  rep    zmodel      zbms
1   -0.995  0.0 -3.011651    1 -3.035569 -3.032012
2   -0.990  0.0 -2.973702    1 -2.997408 -2.993118
3   -0.985  0.0 -2.936150    1 -2.959499 -2.954635
4   -0.980  0.0 -2.898993    1 -2.921848 -2.916561
6   -0.970  0.0 -2.825853    1 -2.847353 -2.841628
..     ...  ...       ...  ...       ...       ...
394  0.970  0.0  6.815269    1  4.920485  6.913953
396  0.980  0.0  6.971089    1  4.966614  7.073285
397  0.985  0.0  7.049904    1  4.989250  7.153882
398  0.990  0.0  7.129326    1  5.011603  7.235105
399  0.995  0.0  7.209357    1  5.033673  7.316956

[320 rows x 6 columns]

300

         x    y         z  rep    zmodel      zbms
1   -0.995  0.0 -3.011651    1 -2.937459 -2.955375
2   -0.990  0.0 -2.973702    1 -2.903682 -2.918736
3   -0.985  0.0 -2.936150    1 -2.870063 -2.882479
4   -0.980  0.0 -2.898993    1 -2.836608 -2.846602
6   -0.970  0.0 -2.825853    1 -2.770215 -2.775976
..     ...  ...       ...  ...       ...       ...
394  0.970  0.0  6.815269    1  4.246926  6.779858
396  0.980  0.0  6.971089    1  4.278730  6.933463
397  0.985  0.0  7.049904    1  4.294282  7.011149
398  0.990  0.0  7.129326    1  4.309604  7.089428
399  0.995  0.0  7.209357    1  4.324698  7.168301

[320 rows x 6 columns]

300

         x    y         z  rep    zmodel      zbms
1   -0.995  0.0 -3.011651    1 -2.969984 -3.007007
2   -0.990  0.0 -2.973702    1 -2.936804 -2.968951
3   -0.985  0.0 -2.936150    1 -2.903761 -2.931289
4   -0.980  0.0 -2.898993    1 -2.870859 -2.894021
6   -0.970  0.0 -2.825853    1 -2.805505 -2.820655
..     ...  ...       ...  ...       ...       ...
394  0.970  0.0  6.815269    1  4.129702  6.743673
396  0.980  0.0  6.971089    1  4.166443  6.897161
397  0.985  0.0  7.049904    1  4.184550  6.974798
398  0.990  0.0  7.129326    1  4.202483  7.053034
399  0.995  0.0  7.209357    1  4.220241  7.131870

[320 rows x 6 columns]

300

         x    y         z  rep    zmodel      zbms
1   -0.995  0.0 -3.011651    1 -3.030441 -3.039380
2   -0.990  0.0 -2.973702    1 -2.994885 -2.999803
3   -0.985  0.0 -2.936150    1 -2.959433 -2.960648
4   -0.980  0.0 -2.898993    1 -2.924098 -2.921914
6   -0.970  0.0 -2.825853    1 -2.853816 -2.845695
..     ...  ...       ...  ...       ...       ...
394  0.970  0.0  6.815269    1  4.161574  7.061477
396  0.980  0.0  6.971089    1  4.194027  7.225067
397  0.985  0.0  7.049904    1  4.209976  7.307823
398  0.990  0.0  7.129326    1  4.225742  7.391223
399  0.995  0.0  7.209357    1  4.241327  7.475271

[320 rows x 6 columns]

300

         x    y         z  rep    zmodel      zbms
1   -0.995  0.0 -3.011651    1 -2.984486 -2.981578
2   -0.990  0.0 -2.973702    1 -2.949702 -2.943048
3   -0.985  0.0 -2.936150    1 -2.915077 -2.905018
4   -0.980  0.0 -2.898993    1 -2.880618 -2.867483
6   -0.970  0.0 -2.825853    1 -2.812230 -2.793872
..     ...  ...       ...  ...       ...       ...
394  0.970  0.0  6.815269    1  3.821266  8.029594
396  0.980  0.0  6.971089    1  3.847300  8.257279
397  0.985  0.0  7.049904    1  3.860042  8.373145
398  0.990  0.0  7.129326    1  3.872605  8.490377
399  0.995  0.0  7.209357    1  3.884990  8.608989

[320 rows x 6 columns]

300

<lambdifygenerated-4347>:2: RuntimeWarning: invalid value encountered in power
  return x*x**x
<lambdifygenerated-4348>:2: RuntimeWarning: invalid value encountered in power
  return x*x**x
<lambdifygenerated-4349>:2: RuntimeWarning: invalid value encountered in power
  return x*(2*x)**x
<lambdifygenerated-4350>:2: RuntimeWarning: invalid value encountered in power
  return x*(2*x)**x
<lambdifygenerated-4351>:2: RuntimeWarning: divide by zero encountered in power
  return x*(_a1_ + x)**x
/usr/local/lib/python3.10/dist-packages/scipy/optimize/_minpack_py.py:1055: RuntimeWarning: invalid value encountered in multiply
  pcov = pcov * s_sq
<lambdifygenerated-4352>:2: RuntimeWarning: divide by zero encountered in power
  return x*(_a1_ + x)**x
<lambdifygenerated-4357>:2: RuntimeWarning: invalid value encountered in power
  return x*(_a1_ + (_a3_ + x)**2)**x

         x    y         z  rep    zmodel       zbms
1   -0.995  0.0 -3.011651    1 -2.977176  -3.005309
2   -0.990  0.0 -2.973702    1 -2.938702  -2.962981
3   -0.985  0.0 -2.936150    1 -2.900486  -2.921260
4   -0.980  0.0 -2.898993    1 -2.862538  -2.880139
6   -0.970  0.0 -2.825853    1 -2.787477  -2.799662
..     ...  ...       ...  ...       ...        ...
394  0.970  0.0  6.815269    1  4.633408   9.549575
396  0.980  0.0  6.971089    1  4.677294   9.843174
397  0.985  0.0  7.049904    1  4.698871   9.992851
398  0.990  0.0  7.129326    1  4.720205  10.144475
399  0.995  0.0  7.209357    1  4.741298  10.298067

[320 rows x 6 columns]

300

         x    y         z  rep    zmodel      zbms
1   -0.995  0.0 -3.011651    1 -2.964580 -3.000467
2   -0.990  0.0 -2.973702    1 -2.932368 -2.963310
3   -0.985  0.0 -2.936150    1 -2.900188 -2.926530
4   -0.980  0.0 -2.898993    1 -2.868049 -2.890124
6   -0.970  0.0 -2.825853    1 -2.803933 -2.818427
..     ...  ...       ...  ...       ...       ...
394  0.970  0.0  6.815269    1  3.189742  6.256078
396  0.980  0.0  6.971089    1  3.216189  6.398110
397  0.985  0.0  7.049904    1  3.229255  6.469953
398  0.990  0.0  7.129326    1  3.242215  6.542351
399  0.995  0.0  7.209357    1  3.255070  6.615306

[320 rows x 6 columns]

300

         x    y         z  rep    zmodel      zbms
1   -0.995  0.0 -3.011651    1 -3.074213 -3.074598
2   -0.990  0.0 -2.973702    1 -3.036291 -3.036027
3   -0.985  0.0 -2.936150    1 -2.998628 -2.997855
4   -0.980  0.0 -2.898993    1 -2.961231 -2.960080
6   -0.970  0.0 -2.825853    1 -2.887257 -2.885709
..     ...  ...       ...  ...       ...       ...
394  0.970  0.0  6.815269    1  4.592635  6.649309
396  0.980  0.0  6.971089    1  4.625301  6.801680
397  0.985  0.0  7.049904    1  4.641225  6.878755
398  0.990  0.0  7.129326    1  4.656881  6.956427
399  0.995  0.0  7.209357    1  4.672271  7.034698

[320 rows x 6 columns]

300

         x    y         z  rep    zmodel      zbms
1   -0.995  0.0 -3.011651    1 -2.965062 -3.006573
2   -0.990  0.0 -2.973702    1 -2.931788 -2.969578
3   -0.985  0.0 -2.936150    1 -2.898613 -2.932963
4   -0.980  0.0 -2.898993    1 -2.865547 -2.896727
6   -0.970  0.0 -2.825853    1 -2.799779 -2.825377
..     ...  ...       ...  ...       ...       ...
394  0.970  0.0  6.815269    1  3.122349  6.588977
396  0.980  0.0  6.971089    1  3.144989  6.738327
397  0.985  0.0  7.049904    1  3.156149  6.813863
398  0.990  0.0  7.129326    1  3.167203  6.889978
399  0.995  0.0  7.209357    1  3.178151  6.966673

[320 rows x 6 columns]

300

         x    y         z  rep    zmodel      zbms
1   -0.995  0.0 -3.011651    1 -3.071819 -3.016297
2   -0.990  0.0 -2.973702    1 -3.030848 -2.978847
3   -0.985  0.0 -2.936150    1 -2.990292 -2.941783
4   -0.980  0.0 -2.898993    1 -2.950156 -2.905103
6   -0.970  0.0 -2.825853    1 -2.871167 -2.832886
..     ...  ...       ...  ...       ...       ...
394  0.970  0.0  6.815269    1  3.723605  6.596486
396  0.980  0.0  6.971089    1  3.749064  6.746703
397  0.985  0.0  7.049904    1  3.761526  6.822683
398  0.990  0.0  7.129326    1  3.773813  6.899247
399  0.995  0.0  7.209357    1  3.785927  6.976397

[320 rows x 6 columns]

300

         x    y         z  rep    zmodel      zbms
1   -0.995  0.0 -3.011651    1 -2.990920 -2.982360
2   -0.990  0.0 -2.973702    1 -2.954237 -2.945867
3   -0.985  0.0 -2.936150    1 -2.917888 -2.909754
4   -0.980  0.0 -2.898993    1 -2.881877 -2.874018
6   -0.970  0.0 -2.825853    1 -2.810876 -2.803666
..     ...  ...       ...  ...       ...       ...
394  0.970  0.0  6.815269    1  3.932957  6.926529
396  0.980  0.0  6.971089    1  3.958085  7.082327
397  0.985  0.0  7.049904    1  3.970382  7.161115
398  0.990  0.0  7.129326    1  3.982504  7.240499
399  0.995  0.0  7.209357    1  3.994454  7.320481

[320 rows x 6 columns]

300

/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/nguyen_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(

         x    y         z  rep    zmodel      zbms
1   -0.995  0.0 -3.011651    1 -2.894743 -2.931107
2   -0.990  0.0 -2.973702    1 -2.862025 -2.894681
3   -0.985  0.0 -2.936150    1 -2.829433 -2.858634
4   -0.980  0.0 -2.898993    1 -2.796971 -2.822961
6   -0.970  0.0 -2.825853    1 -2.732464 -2.752731
..     ...  ...       ...  ...       ...       ...
394  0.970  0.0  6.815269    1  3.064108  6.516331
396  0.980  0.0  6.971089    1  3.079204  6.664561
397  0.985  0.0  7.049904    1  3.086606  6.739534
398  0.990  0.0  7.129326    1  3.093912  6.815081
399  0.995  0.0  7.209357    1  3.101123  6.891207

[320 rows x 6 columns]

300

         x    y         z  rep    zmodel      zbms
1   -0.995  0.0 -3.011651    1 -2.857402 -2.946062
2   -0.990  0.0 -2.973702    1 -2.826114 -2.907971
3   -0.985  0.0 -2.936150    1 -2.795008 -2.870376
4   -0.980  0.0 -2.898993    1 -2.764086 -2.833270
6   -0.970  0.0 -2.825853    1 -2.702816 -2.760504
..     ...  ...       ...  ...       ...       ...
394  0.970  0.0  6.815269    1  3.172069  8.048976
396  0.980  0.0  6.971089    1  3.206586  8.277435
397  0.985  0.0  7.049904    1  3.223790  8.393696
398  0.990  0.0  7.129326    1  3.240957  8.511328
399  0.995  0.0  7.209357    1  3.258086  8.630344

[320 rows x 6 columns]

300

         x    y         z  rep    zmodel      zbms
1   -0.995  0.0 -3.011651    1 -3.021069 -3.035888
2   -0.990  0.0 -2.973702    1 -2.991192 -3.008808
3   -0.985  0.0 -2.936150    1 -2.961283 -2.981509
4   -0.980  0.0 -2.898993    1 -2.931348 -2.953999
6   -0.970  0.0 -2.825853    1 -2.871429 -2.898394
..     ...  ...       ...  ...       ...       ...
394  0.970  0.0  6.815269    1  3.275921  1.427555
396  0.980  0.0  6.971089    1  3.297955  1.416547
397  0.985  0.0  7.049904    1  3.308780  1.411336
398  0.990  0.0  7.129326    1  3.319478  1.406335
399  0.995  0.0  7.209357    1  3.330051  1.401554

[320 rows x 6 columns]

300

         x    y         z  rep    zmodel      zbms
1   -0.995  0.0 -3.011651    1 -2.965405 -3.289431
2   -0.990  0.0 -2.973702    1 -2.930271 -3.231266
3   -0.985  0.0 -2.936150    1 -2.895366 -3.174279
4   -0.980  0.0 -2.898993    1 -2.860698 -3.118445
6   -0.970  0.0 -2.825853    1 -2.792099 -3.010146
..     ...  ...       ...  ...       ...       ...
394  0.970  0.0  6.815269    1  2.548379  6.677629
396  0.980  0.0  6.971089    1  2.569915  6.861936
397  0.985  0.0  7.049904    1  2.580608  6.956066
398  0.990  0.0  7.129326    1  2.591252  7.051544
399  0.995  0.0  7.209357    1  2.601846  7.148396

[320 rows x 6 columns]

300

         x    y         z  rep    zmodel      zbms
1   -0.995  0.0 -3.011651    1 -2.902615 -3.084285
2   -0.990  0.0 -2.973702    1 -2.869689 -3.043996
3   -0.985  0.0 -2.936150    1 -2.836982 -3.004141
4   -0.980  0.0 -2.898993    1 -2.804501 -2.964719
6   -0.970  0.0 -2.825853    1 -2.740230 -2.887159
..     ...  ...       ...  ...       ...       ...
394  0.970  0.0  6.815269    1  4.299238  7.460724
396  0.980  0.0  6.971089    1  4.340437  7.633070
397  0.985  0.0  7.049904    1  4.360762  7.720251
398  0.990  0.0  7.129326    1  4.380903  7.808106
399  0.995  0.0  7.209357    1  4.400861  7.896640

[320 rows x 6 columns]

300

         x    y         z  rep    zmodel      zbms
1   -0.995  0.0 -3.011651    1 -2.911057 -2.994947
2   -0.990  0.0 -2.973702    1 -2.877213 -2.956919
3   -0.985  0.0 -2.936150    1 -2.843630 -2.919327
4   -0.980  0.0 -2.898993    1 -2.810312 -2.882167
6   -0.970  0.0 -2.825853    1 -2.744484 -2.809124
..     ...  ...       ...  ...       ...       ...
394  0.970  0.0  6.815269    1  4.380138  4.749124
396  0.980  0.0  6.971089    1  4.424569  4.842167
397  0.985  0.0  7.049904    1  4.446511  4.889327
398  0.990  0.0  7.129326    1  4.468271  4.936919
399  0.995  0.0  7.209357    1  4.489847  4.984947

[320 rows x 6 columns]

300

         x    y         z  rep    zmodel      zbms
1   -0.995  0.0 -3.011651    1 -2.908552 -2.835211
2   -0.990  0.0 -2.973702    1 -2.881592 -2.804218
3   -0.985  0.0 -2.936150    1 -2.854551 -2.773516
4   -0.980  0.0 -2.898993    1 -2.827433 -2.743104
6   -0.970  0.0 -2.825853    1 -2.772996 -2.683143
..     ...  ...       ...  ...       ...       ...
394  0.970  0.0  6.815269    1  3.633636  7.274753
396  0.980  0.0  6.971089    1  3.653186  7.444243
397  0.985  0.0  7.049904    1  3.662757  7.530072
398  0.990  0.0  7.129326    1  3.672194  7.616629
399  0.995  0.0  7.209357    1  3.681500  7.703920

[320 rows x 6 columns]

300

         x    y         z  rep    zmodel      zbms
1   -0.995  0.0 -3.011651    1 -3.102496 -3.094069
2   -0.990  0.0 -2.973702    1 -3.067788 -3.054536
3   -0.985  0.0 -2.936150    1 -3.033059 -3.015461
4   -0.980  0.0 -2.898993    1 -2.998324 -2.976838
6   -0.970  0.0 -2.825853    1 -2.928882 -2.900929
..     ...  ...       ...  ...       ...       ...
394  0.970  0.0  6.815269    1  3.774676  4.840929
396  0.980  0.0  6.971089    1  3.801047  4.936838
397  0.985  0.0  7.049904    1  3.814019  4.985461
398  0.990  0.0  7.129326    1  3.826851  5.034536
399  0.995  0.0  7.209357    1  3.839543  5.084069

[320 rows x 6 columns]

300

         x    y         z  rep    zmodel      zbms
1   -0.995  0.0 -3.011651    1 -3.190579 -3.125063
2   -0.990  0.0 -2.973702    1 -3.142837 -3.082537
3   -0.985  0.0 -2.936150    1 -3.095647 -3.040481
4   -0.980  0.0 -2.898993    1 -3.049015 -2.998893
6   -0.970  0.0 -2.825853    1 -2.957452 -2.917109
..     ...  ...       ...  ...       ...       ...
394  0.970  0.0  6.815269    1  4.020255  7.878798
396  0.980  0.0  6.971089    1  4.058582  8.063412
397  0.985  0.0  7.049904    1  4.077507  8.156811
398  0.990  0.0  7.129326    1  4.096274  8.250941
399  0.995  0.0  7.209357    1  4.114882  8.345805

[320 rows x 6 columns]

300

         x    y         z  rep    zmodel      zbms
1   -0.995  0.0 -3.011651    1 -3.148277 -3.145859
2   -0.990  0.0 -2.973702    1 -3.105936 -3.104427
3   -0.985  0.0 -2.936150    1 -3.063885 -3.063418
4   -0.980  0.0 -2.898993    1 -3.022137 -3.022828
6   -0.970  0.0 -2.825853    1 -2.939591 -2.942901
..     ...  ...       ...  ...       ...       ...
394  0.970  0.0  6.815269    1  4.667938  7.264540
396  0.980  0.0  6.971089    1  4.711053  7.418723
397  0.985  0.0  7.049904    1  4.732266  7.496503
398  0.990  0.0  7.129326    1  4.753252  7.574740
399  0.995  0.0  7.209357    1  4.774010  7.653436

[320 rows x 6 columns]

300

         x    y         z  rep    zmodel      zbms
1   -0.995  0.0 -3.011651    1 -2.895723 -3.012649
2   -0.990  0.0 -2.973702    1 -2.864918 -2.976159
3   -0.985  0.0 -2.936150    1 -2.834191 -2.940041
4   -0.980  0.0 -2.898993    1 -2.803550 -2.904293
6   -0.970  0.0 -2.825853    1 -2.742554 -2.833897
..     ...  ...       ...  ...       ...       ...
394  0.970  0.0  6.815269    1  3.908849  6.597497
396  0.980  0.0  6.971089    1  3.937755  6.745893
397  0.985  0.0  7.049904    1  3.951979  6.820941
398  0.990  0.0  7.129326    1  3.966053  6.896559
399  0.995  0.0  7.209357    1  3.979978  6.972749

[320 rows x 6 columns]

300

<lambdifygenerated-4807>:2: RuntimeWarning: invalid value encountered in power
  return x*x**x
<lambdifygenerated-4808>:2: RuntimeWarning: invalid value encountered in power
  return x*x**x
<lambdifygenerated-4811>:2: RuntimeWarning: invalid value encountered in power
  return x*(_a6_*x)**x
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/nguyen_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-4812>:2: RuntimeWarning: invalid value encountered in power
  return x*(_a6_*x)**x
<lambdifygenerated-4819>:2: RuntimeWarning: divide by zero encountered in power
  return x*(_a6_*(_a1_ + x)**2)**x
<lambdifygenerated-4820>:2: RuntimeWarning: divide by zero encountered in power
  return x*(_a6_*(_a1_ + x)**2)**x
<lambdifygenerated-4821>:2: RuntimeWarning: invalid value encountered in power
  return x*(_a6_*(_a1_ + x)**2)**_a5_
<lambdifygenerated-4827>:2: RuntimeWarning: invalid value encountered in power
  return x*(_a6_*(_a1_ + x)**2)**_a5_

         x    y         z  rep    zmodel      zbms
1   -0.995  0.0 -3.011651    1 -2.823338 -2.707482
2   -0.990  0.0 -2.973702    1 -2.795950 -2.686676
3   -0.985  0.0 -2.936150    1 -2.768621 -2.665898
4   -0.980  0.0 -2.898993    1 -2.741353 -2.645149
6   -0.970  0.0 -2.825853    1 -2.687015 -2.603736
..     ...  ...       ...  ...       ...       ...
394  0.970  0.0  6.815269    1  2.395702  3.464901
396  0.980  0.0  6.971089    1  2.408236  3.508210
397  0.985  0.0  7.049904    1  2.414439  3.529909
398  0.990  0.0  7.129326    1  2.420598  3.551637
399  0.995  0.0  7.209357    1  2.426715  3.573393

[320 rows x 6 columns]

300

         x    y         z  rep    zmodel      zbms
1   -0.995  0.0 -3.011651    1 -2.689011 -2.873196
2   -0.990  0.0 -2.973702    1 -2.662221 -2.843064
3   -0.985  0.0 -2.936150    1 -2.635555 -2.812915
4   -0.980  0.0 -2.898993    1 -2.609017 -2.782758
6   -0.970  0.0 -2.825853    1 -2.556336 -2.722448
..     ...  ...       ...  ...       ...       ...
394  0.970  0.0  6.815269    1  3.460826  1.849426
396  0.980  0.0  6.971089    1  3.496300  1.836249
397  0.985  0.0  7.049904    1  3.513909  1.829657
398  0.990  0.0  7.129326    1  3.531431  1.823075
399  0.995  0.0  7.209357    1  3.548866  1.816510

[320 rows x 6 columns]

300

<lambdifygenerated-4889>:2: RuntimeWarning: invalid value encountered in power
  return x*(x + x**x + cos(_a1_*_a4_*cos(_a1_*x)/_a3_)/_a6_)
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/nguyen_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-4890>:2: RuntimeWarning: invalid value encountered in power
  return x*(x + x**x + cos(_a1_*_a4_*cos(_a1_*x)/_a3_)/_a6_)
<lambdifygenerated-4901>:2: RuntimeWarning: overflow encountered in exp
  return x*(x + exp((_a3_*x**2 + x)**2)**x + cos(_a1_*_a4_*cos(_a1_*x)/_a3_)/_a6_)
<lambdifygenerated-4902>:2: RuntimeWarning: overflow encountered in exp
  return x*(x + exp((_a3_*x**2 + x)**2)**x + cos(_a1_*_a4_*cos(_a1_*x)/_a3_)/_a6_)
<lambdifygenerated-4903>:2: RuntimeWarning: overflow encountered in exp
  return x*(x + exp((_a3_*x**2 + x)**2)**x + cos(_a1_*_a4_*cos(_a1_*x)/_a3_)/_a6_)
<lambdifygenerated-4904>:2: RuntimeWarning: overflow encountered in exp
  return x*(x + exp((_a3_*x**2 + x)**2)**x + cos(_a1_*_a4_*cos(_a1_*x)/_a3_)/_a6_)
<lambdifygenerated-4905>:2: RuntimeWarning: overflow encountered in exp
  return x*(x + exp((_a0_*_a3_*x + x)**2)**x + cos(_a1_*_a4_*cos(_a1_*x)/_a3_)/_a6_)
<lambdifygenerated-4906>:2: RuntimeWarning: overflow encountered in exp
  return x*(x + exp((_a0_*_a3_*x + x)**2)**x + cos(_a1_*_a4_*cos(_a1_*x)/_a3_)/_a6_)
<lambdifygenerated-4907>:2: RuntimeWarning: overflow encountered in exp
  return x*(x + exp((_a0_*_a3_*x + sin(x))**2)**x + cos(_a1_*_a4_*cos(_a1_*x)/_a3_)/_a6_)
<lambdifygenerated-4908>:2: RuntimeWarning: overflow encountered in exp
  return x*(x + exp((_a0_*_a3_*x + sin(x))**2)**x + cos(_a1_*_a4_*cos(_a1_*x)/_a3_)/_a6_)
<lambdifygenerated-4909>:2: RuntimeWarning: overflow encountered in exp
  return x*(x + exp((_a0_*_a3_*x + sin(x**2))**2)**x + cos(_a1_*_a4_*cos(_a1_*x)/_a3_)/_a6_)
<lambdifygenerated-4910>:2: RuntimeWarning: overflow encountered in exp
  return x*(x + exp((_a0_*_a3_*x + sin(x**2))**2)**x + cos(_a1_*_a4_*cos(_a1_*x)/_a3_)/_a6_)
<lambdifygenerated-4911>:2: RuntimeWarning: overflow encountered in exp
  return x*(x + exp((_a0_*_a3_*x + sin(_a7_*x))**2)**x + cos(_a1_*_a4_*cos(_a1_*x)/_a3_)/_a6_)
<lambdifygenerated-4912>:2: RuntimeWarning: overflow encountered in exp
  return x*(x + exp((_a0_*_a3_*x + sin(_a7_*x))**2)**x + cos(_a1_*_a4_*cos(_a1_*x)/_a3_)/_a6_)
<lambdifygenerated-4913>:2: RuntimeWarning: overflow encountered in exp
  return x*(x + exp((_a0_*_a3_*x + sin(_a7_))**2)**x + cos(_a1_*_a4_*cos(_a1_*x)/_a3_)/_a6_)
<lambdifygenerated-4914>:2: RuntimeWarning: overflow encountered in exp
  return x*(x + exp((_a0_*_a3_*x + sin(_a7_))**2)**x + cos(_a1_*_a4_*cos(_a1_*x)/_a3_)/_a6_)
<lambdifygenerated-4915>:2: RuntimeWarning: overflow encountered in exp
  return x*(x + exp((_a0_*_a3_*x + sin(_a7_))**2)**x + cos(_a1_*_a4_*cos(_a1_*x)/_a3_)/_a6_)
<lambdifygenerated-4916>:2: RuntimeWarning: overflow encountered in exp
  return x*(x + exp((_a0_*_a3_*x + sin(_a7_))**2)**x + cos(_a1_*_a4_*cos(_a1_*x)/_a3_)/_a6_)
<lambdifygenerated-4917>:2: RuntimeWarning: overflow encountered in exp
  return x*(x + exp((_a0_*_a3_*x + sin(_a7_/x))**2)**x + cos(_a1_*_a4_*cos(_a1_*x)/_a3_)/_a6_)
<lambdifygenerated-4918>:2: RuntimeWarning: overflow encountered in exp
  return x*(x + exp((_a0_*_a3_*x + sin(_a7_/x))**2)**x + cos(_a1_*_a4_*cos(_a1_*x)/_a3_)/_a6_)
<lambdifygenerated-4919>:2: RuntimeWarning: overflow encountered in exp
  return x*(x + exp((_a0_*_a3_*x + sin(_a7_/_a3_))**2)**x + cos(_a1_*_a4_*cos(_a1_*x)/_a3_)/_a6_)
<lambdifygenerated-4920>:2: RuntimeWarning: overflow encountered in exp
  return x*(x + exp((_a0_*_a3_*x + sin(_a7_/_a3_))**2)**x + cos(_a1_*_a4_*cos(_a1_*x)/_a3_)/_a6_)
<lambdifygenerated-4921>:2: RuntimeWarning: overflow encountered in exp
  return x*(x + exp((_a0_*_a3_*x + sin((1/2)*_a7_/_a3_))**2)**x + cos(_a1_*_a4_*cos(_a1_*x)/_a3_)/_a6_)
<lambdifygenerated-4922>:2: RuntimeWarning: overflow encountered in exp
  return x*(x + exp((_a0_*_a3_*x + sin((1/2)*_a7_/_a3_))**2)**x + cos(_a1_*_a4_*cos(_a1_*x)/_a3_)/_a6_)
<lambdifygenerated-4923>:2: RuntimeWarning: overflow encountered in exp
  return x*(x + exp((_a0_*_a3_*x + sin((1/3)*_a7_/_a3_))**2)**x + cos(_a1_*_a4_*cos(_a1_*x)/_a3_)/_a6_)
<lambdifygenerated-4924>:2: RuntimeWarning: overflow encountered in exp
  return x*(x + exp((_a0_*_a3_*x + sin((1/3)*_a7_/_a3_))**2)**x + cos(_a1_*_a4_*cos(_a1_*x)/_a3_)/_a6_)
<lambdifygenerated-4925>:2: RuntimeWarning: overflow encountered in exp
  return x*(x + exp((_a0_*_a3_*x + sin(_a7_/_a3_))**2)**x + cos(_a1_*_a4_*cos(_a1_*x)/_a3_)/_a6_)
<lambdifygenerated-4926>:2: RuntimeWarning: overflow encountered in exp
  return x*(x + exp((_a0_*_a3_*x + sin(_a7_/_a3_))**2)**x + cos(_a1_*_a4_*cos(_a1_*x)/_a3_)/_a6_)
<lambdifygenerated-4927>:2: RuntimeWarning: overflow encountered in exp
  return x*(x + exp((_a0_*_a3_*x + sin(_a7_*x/(_a3_*(-_a6_ + 2*x))))**2)**x + cos(_a1_*_a4_*cos(_a1_*x)/_a3_)/_a6_)
<lambdifygenerated-4928>:2: RuntimeWarning: overflow encountered in exp
  return x*(x + exp((_a0_*_a3_*x + sin(_a7_*x/(_a3_*(-_a6_ + 2*x))))**2)**x + cos(_a1_*_a4_*cos(_a1_*x)/_a3_)/_a6_)
<lambdifygenerated-4929>:2: RuntimeWarning: overflow encountered in exp
  return x*(x + exp((_a0_*_a3_*x + sin(_a7_*x/(_a3_*(_a0_ - _a6_ + x))))**2)**x + cos(_a1_*_a4_*cos(_a1_*x)/_a3_)/_a6_)
<lambdifygenerated-4930>:2: RuntimeWarning: overflow encountered in exp
  return x*(x + exp((_a0_*_a3_*x + sin(_a7_*x/(_a3_*(_a0_ - _a6_ + x))))**2)**x + cos(_a1_*_a4_*cos(_a1_*x)/_a3_)/_a6_)
<lambdifygenerated-4931>:2: RuntimeWarning: overflow encountered in exp
  return x*(x + exp((_a0_*_a3_*x + sin(_a7_*x/(_a3_*(_a0_ + _a2_ - _a6_))))**2)**x + cos(_a1_*_a4_*cos(_a1_*x)/_a3_)/_a6_)
<lambdifygenerated-4932>:2: RuntimeWarning: overflow encountered in exp
  return x*(x + exp((_a0_*_a3_*x + sin(_a7_*x/(_a3_*(_a0_ + _a2_ - _a6_))))**2)**x + cos(_a1_*_a4_*cos(_a1_*x)/_a3_)/_a6_)
<lambdifygenerated-4933>:2: RuntimeWarning: overflow encountered in exp
  return x*(x + exp((_a0_*_a3_*x + sin(_a7_*x/(_a3_*(_a0_ + _a2_ - _a6_))))**2)**_a4_ + cos(_a1_*_a4_*cos(_a1_*x)/_a3_)/_a6_)
<lambdifygenerated-4933>:2: RuntimeWarning: overflow encountered in power
  return x*(x + exp((_a0_*_a3_*x + sin(_a7_*x/(_a3_*(_a0_ + _a2_ - _a6_))))**2)**_a4_ + cos(_a1_*_a4_*cos(_a1_*x)/_a3_)/_a6_)
<lambdifygenerated-4934>:2: RuntimeWarning: overflow encountered in exp
  return x*(x + exp((_a0_*_a3_*x + sin(_a7_*x/(_a3_*(_a0_ + _a2_ - _a6_))))**2)**_a4_ + cos(_a1_*_a4_*cos(_a1_*x)/_a3_)/_a6_)
<lambdifygenerated-4934>:2: RuntimeWarning: overflow encountered in power
  return x*(x + exp((_a0_*_a3_*x + sin(_a7_*x/(_a3_*(_a0_ + _a2_ - _a6_))))**2)**_a4_ + cos(_a1_*_a4_*cos(_a1_*x)/_a3_)/_a6_)
<lambdifygenerated-4935>:2: RuntimeWarning: overflow encountered in exp
  return x*(_a5_ + exp((_a0_*_a3_*x + sin(_a7_*x/(_a3_*(_a0_ + _a2_ - _a6_))))**2)**_a4_ + cos(_a1_*_a4_*cos(_a1_*x)/_a3_)/_a6_)
<lambdifygenerated-4935>:2: RuntimeWarning: overflow encountered in power
  return x*(_a5_ + exp((_a0_*_a3_*x + sin(_a7_*x/(_a3_*(_a0_ + _a2_ - _a6_))))**2)**_a4_ + cos(_a1_*_a4_*cos(_a1_*x)/_a3_)/_a6_)
<lambdifygenerated-4936>:2: RuntimeWarning: overflow encountered in exp
  return x*(_a5_ + exp((_a0_*_a3_*x + sin(_a7_*x/(_a3_*(_a0_ + _a2_ - _a6_))))**2)**_a4_ + cos(_a1_*_a4_*cos(_a1_*x)/_a3_)/_a6_)
<lambdifygenerated-4936>:2: RuntimeWarning: overflow encountered in power
  return x*(_a5_ + exp((_a0_*_a3_*x + sin(_a7_*x/(_a3_*(_a0_ + _a2_ - _a6_))))**2)**_a4_ + cos(_a1_*_a4_*cos(_a1_*x)/_a3_)/_a6_)
<lambdifygenerated-4937>:2: RuntimeWarning: overflow encountered in exp
  return _a2_*(_a5_ + exp((_a0_*_a3_*x + sin(_a7_*x/(_a3_*(_a0_ + _a2_ - _a6_))))**2)**_a4_ + cos(_a1_*_a4_*cos(_a1_*x)/_a3_)/_a6_)
<lambdifygenerated-4937>:2: RuntimeWarning: overflow encountered in power
  return _a2_*(_a5_ + exp((_a0_*_a3_*x + sin(_a7_*x/(_a3_*(_a0_ + _a2_ - _a6_))))**2)**_a4_ + cos(_a1_*_a4_*cos(_a1_*x)/_a3_)/_a6_)
<lambdifygenerated-4938>:2: RuntimeWarning: overflow encountered in exp
  return _a2_*(_a5_ + exp((_a0_*_a3_*x + sin(_a7_*x/(_a3_*(_a0_ + _a2_ - _a6_))))**2)**_a4_ + cos(_a1_*_a4_*cos(_a1_*x)/_a3_)/_a6_)
<lambdifygenerated-4938>:2: RuntimeWarning: overflow encountered in power
  return _a2_*(_a5_ + exp((_a0_*_a3_*x + sin(_a7_*x/(_a3_*(_a0_ + _a2_ - _a6_))))**2)**_a4_ + cos(_a1_*_a4_*cos(_a1_*x)/_a3_)/_a6_)
<lambdifygenerated-4939>:2: RuntimeWarning: overflow encountered in exp
  return _a2_*(_a5_ + exp((_a0_*_a3_*x + sin(_a7_*x/(_a3_*(_a0_ + _a2_ - _a6_))))**2)**_a4_ + cos(_a1_*_a4_*cos(_a1_*x)/_a3_)/_a6_)
<lambdifygenerated-4939>:2: RuntimeWarning: overflow encountered in power
  return _a2_*(_a5_ + exp((_a0_*_a3_*x + sin(_a7_*x/(_a3_*(_a0_ + _a2_ - _a6_))))**2)**_a4_ + cos(_a1_*_a4_*cos(_a1_*x)/_a3_)/_a6_)
<lambdifygenerated-4940>:2: RuntimeWarning: overflow encountered in exp
  return _a2_*(_a5_ + exp((_a0_*_a3_*x + sin(_a7_*x/(_a3_*(_a0_ + _a2_ - _a6_))))**2)**_a4_ + cos(_a1_*_a4_*cos(_a1_*x)/_a3_)/_a6_)
<lambdifygenerated-4940>:2: RuntimeWarning: overflow encountered in power
  return _a2_*(_a5_ + exp((_a0_*_a3_*x + sin(_a7_*x/(_a3_*(_a0_ + _a2_ - _a6_))))**2)**_a4_ + cos(_a1_*_a4_*cos(_a1_*x)/_a3_)/_a6_)
<lambdifygenerated-4941>:2: RuntimeWarning: overflow encountered in exp
  return _a2_*(_a5_ + exp((_a0_*_a3_*x + sin(_a7_*x/(_a3_*(_a0_ + _a2_ - _a6_))))**2)**_a4_ + cos(_a1_*_a4_*cos(_a1_*x)/_a3_)/_a6_)
<lambdifygenerated-4941>:2: RuntimeWarning: overflow encountered in power
  return _a2_*(_a5_ + exp((_a0_*_a3_*x + sin(_a7_*x/(_a3_*(_a0_ + _a2_ - _a6_))))**2)**_a4_ + cos(_a1_*_a4_*cos(_a1_*x)/_a3_)/_a6_)
<lambdifygenerated-4942>:2: RuntimeWarning: overflow encountered in exp
  return _a2_*(_a5_ + exp((_a0_*_a3_*x + sin(_a7_*x/(_a3_*(_a0_ + _a2_ - _a6_))))**2)**_a4_ + cos(_a1_*_a4_*cos(_a1_*x)/_a3_)/_a6_)
<lambdifygenerated-4942>:2: RuntimeWarning: overflow encountered in power
  return _a2_*(_a5_ + exp((_a0_*_a3_*x + sin(_a7_*x/(_a3_*(_a0_ + _a2_ - _a6_))))**2)**_a4_ + cos(_a1_*_a4_*cos(_a1_*x)/_a3_)/_a6_)

         x    y         z  rep    zmodel      zbms
1   -0.995  0.0 -0.294774    5 -0.275970 -0.294774
2   -0.990  0.0 -0.294284    5 -0.277346 -0.294284
3   -0.985  0.0 -0.293881    5 -0.278741 -0.293881
4   -0.980  0.0 -0.293564    5 -0.280156 -0.293564
6   -0.970  0.0 -0.293188    5 -0.283047 -0.293188
..     ...  ...       ...  ...       ...       ...
394  0.970  0.0 -0.293188    5 -0.303439 -0.293188
396  0.980  0.0 -0.293564    5 -0.299482 -0.293564
397  0.985  0.0 -0.293881    5 -0.297522 -0.293881
398  0.990  0.0 -0.294284    5 -0.295574 -0.294284
399  0.995  0.0 -0.294774    5 -0.293639 -0.294774

[320 rows x 6 columns]

<lambdifygenerated-4957>:2: RuntimeWarning: invalid value encountered in power
  return x*cos(x**x/x) + 2*x
<lambdifygenerated-4958>:2: RuntimeWarning: invalid value encountered in power
  return x*cos(x**x/x) + 2*x
<lambdifygenerated-4961>:2: RuntimeWarning: invalid value encountered in power
  return x*cos((x*cosh(x))**x/x) + 2*x
<lambdifygenerated-4962>:2: RuntimeWarning: invalid value encountered in power
  return x*cos((x*cosh(x))**x/x) + 2*x
<lambdifygenerated-4963>:2: RuntimeWarning: invalid value encountered in power
  return x*cos((x*cosh(x**2))**x/x) + 2*x
<lambdifygenerated-4964>:2: RuntimeWarning: invalid value encountered in power
  return x*cos((x*cosh(x**2))**x/x) + 2*x
<lambdifygenerated-4965>:2: RuntimeWarning: invalid value encountered in power
  return x*cos((x*cosh(x**3))**x/x) + 2*x
<lambdifygenerated-4966>:2: RuntimeWarning: invalid value encountered in power
  return x*cos((x*cosh(x**3))**x/x) + 2*x
<lambdifygenerated-4967>:2: RuntimeWarning: invalid value encountered in power
  return x*cos((x*cosh(_a6_*x**2))**x/x) + 2*x
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/nguyen_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-4968>:2: RuntimeWarning: invalid value encountered in power
  return x*cos((x*cosh(_a6_*x**2))**x/x) + 2*x
<lambdifygenerated-4969>:2: RuntimeWarning: invalid value encountered in power
  return x*cos((x*cosh(_a6_*x**2))**x/x) + 2*x
<lambdifygenerated-4970>:2: RuntimeWarning: invalid value encountered in power
  return x*cos((x*cosh(_a6_*x**2))**x/x) + 2*x
<lambdifygenerated-4971>:2: RuntimeWarning: invalid value encountered in power
  return x*cos((x*cosh(_a4_*_a6_*x))**x/x) + 2*x
<lambdifygenerated-4972>:2: RuntimeWarning: invalid value encountered in power
  return x*cos((x*cosh(_a4_*_a6_*x))**x/x) + 2*x
<lambdifygenerated-4973>:2: RuntimeWarning: overflow encountered in cosh
  return x*cos((_a1_*cosh(_a4_*_a6_*x))**x/x) + 2*x
<lambdifygenerated-4973>:2: RuntimeWarning: invalid value encountered in cos
  return x*cos((_a1_*cosh(_a4_*_a6_*x))**x/x) + 2*x
<lambdifygenerated-4975>:2: RuntimeWarning: overflow encountered in cosh
  return x*cos((_a1_*cosh(_a4_*_a6_*x))**(2*x)/x) + 2*x
<lambdifygenerated-4975>:2: RuntimeWarning: invalid value encountered in cos
  return x*cos((_a1_*cosh(_a4_*_a6_*x))**(2*x)/x) + 2*x
<lambdifygenerated-4977>:2: RuntimeWarning: overflow encountered in cosh
  return x*cos((_a1_*cosh(_a4_*_a6_*x))**(x**2 + x)/x) + 2*x
<lambdifygenerated-4977>:2: RuntimeWarning: invalid value encountered in cos
  return x*cos((_a1_*cosh(_a4_*_a6_*x))**(x**2 + x)/x) + 2*x
<lambdifygenerated-4981>:2: RuntimeWarning: overflow encountered in cosh
  return x*cos((_a1_*cosh(_a4_*_a6_*x))**(x**3 + x)/x) + 2*x
<lambdifygenerated-4981>:2: RuntimeWarning: invalid value encountered in cos
  return x*cos((_a1_*cosh(_a4_*_a6_*x))**(x**3 + x)/x) + 2*x
<lambdifygenerated-4985>:2: RuntimeWarning: overflow encountered in cosh
  return x*cos((_a1_*cosh(_a4_*_a6_*x))**(_a0_*x**2 + x)/x) + 2*x
<lambdifygenerated-4985>:2: RuntimeWarning: invalid value encountered in cos
  return x*cos((_a1_*cosh(_a4_*_a6_*x))**(_a0_*x**2 + x)/x) + 2*x
<lambdifygenerated-4985>:2: RuntimeWarning: overflow encountered in power
  return x*cos((_a1_*cosh(_a4_*_a6_*x))**(_a0_*x**2 + x)/x) + 2*x
<lambdifygenerated-4987>:2: RuntimeWarning: overflow encountered in cosh
  return x*cos((_a1_*cosh(_a4_*_a6_*x))**(_a0_*x**2 + _a3_)/x) + 2*x
<lambdifygenerated-4987>:2: RuntimeWarning: overflow encountered in power
  return x*cos((_a1_*cosh(_a4_*_a6_*x))**(_a0_*x**2 + _a3_)/x) + 2*x
<lambdifygenerated-4987>:2: RuntimeWarning: invalid value encountered in cos
  return x*cos((_a1_*cosh(_a4_*_a6_*x))**(_a0_*x**2 + _a3_)/x) + 2*x

300

<lambdifygenerated-4989>:2: RuntimeWarning: overflow encountered in cosh
  return x*cos((_a1_*cosh(_a4_*_a6_*x))**(_a0_*x**2 + _a3_)/x**2) + 2*x
<lambdifygenerated-4989>:2: RuntimeWarning: invalid value encountered in cos
  return x*cos((_a1_*cosh(_a4_*_a6_*x))**(_a0_*x**2 + _a3_)/x**2) + 2*x
<lambdifygenerated-4991>:2: RuntimeWarning: invalid value encountered in power
  return x*cos((_a1_*cosh(_a4_*_a6_*x))**(_a0_*x**2 + _a3_)/_a5_**2) + 2*x
<lambdifygenerated-4993>:2: RuntimeWarning: invalid value encountered in power
  return _a4_*cos((_a1_*cosh(_a4_*_a6_*x))**(_a0_*x**2 + _a3_)/_a5_**2) + 2*x
<lambdifygenerated-4995>:2: RuntimeWarning: invalid value encountered in power
  return _a2_ + _a4_*cos((_a1_*cosh(_a4_*_a6_*x))**(_a0_*x**2 + _a3_)/_a5_**2) + x
<lambdifygenerated-4997>:2: RuntimeWarning: overflow encountered in power
  return _a2_ + _a4_*cos((_a1_*cosh(_a4_*_a6_*x))**(_a0_*x**2 + _a3_)/_a5_**2) + x**2
<lambdifygenerated-4997>:2: RuntimeWarning: invalid value encountered in cos
  return _a2_ + _a4_*cos((_a1_*cosh(_a4_*_a6_*x))**(_a0_*x**2 + _a3_)/_a5_**2) + x**2
<lambdifygenerated-4997>:2: RuntimeWarning: invalid value encountered in power
  return _a2_ + _a4_*cos((_a1_*cosh(_a4_*_a6_*x))**(_a0_*x**2 + _a3_)/_a5_**2) + x**2
<lambdifygenerated-4999>:2: RuntimeWarning: invalid value encountered in power
  return _a2_ + _a4_*cos((_a1_*cosh(_a4_*_a6_*x))**(_a0_*x**2 + _a3_)/_a5_**2) + x*cosh(x)
<lambdifygenerated-5001>:2: RuntimeWarning: invalid value encountered in power
  return _a2_ + _a4_*cos((_a1_*cosh(_a4_*_a6_*x))**(_a0_*x**2 + _a3_)/_a5_**2) + x*cosh(x**2)
<lambdifygenerated-5003>:2: RuntimeWarning: invalid value encountered in power
  return _a2_ + _a4_*cos((_a1_*cosh(_a4_*_a6_*x))**(_a0_*x**2 + _a3_)/_a5_**2) + x*cosh(_a5_*x)
<lambdifygenerated-5007>:2: RuntimeWarning: invalid value encountered in power
  return _a2_ + _a4_*cos((_a1_*cosh(_a4_*_a6_*x))**(_a0_*x**2 + _a3_)/_a5_**2) + _a7_*cosh(_a5_*x)
<lambdifygenerated-5011>:2: RuntimeWarning: invalid value encountered in power
  return _a2_ + _a4_*cos((_a1_*cosh(_a4_*_a6_*x))**(_a0_*x**2 + _a3_)/_a5_**2) + _a7_*cosh(_a5_*x)

         x    y         z  rep    zmodel      zbms
1   -0.995  0.0 -0.294774    5 -0.275688 -0.294774
2   -0.990  0.0 -0.294284    5 -0.277106 -0.294284
3   -0.985  0.0 -0.293881    5 -0.278542 -0.293881
4   -0.980  0.0 -0.293564    5 -0.279997 -0.293564
6   -0.970  0.0 -0.293188    5 -0.282962 -0.293188
..     ...  ...       ...  ...       ...       ...
394  0.970  0.0 -0.293188    5 -0.291397 -0.293188
396  0.980  0.0 -0.293564    5 -0.287017 -0.293564
397  0.985  0.0 -0.293881    5 -0.284844 -0.293881
398  0.990  0.0 -0.294284    5 -0.282684 -0.294284
399  0.995  0.0 -0.294774    5 -0.280536 -0.294774

[320 rows x 6 columns]

/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/nguyen_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-5049>:2: RuntimeWarning: invalid value encountered in power
  return (x + (_a7_ - cos(_a3_*_a4_*x))*abs(_a1_ + x**x))/x
<lambdifygenerated-5050>:2: RuntimeWarning: invalid value encountered in power
  return (x + (_a7_ - cos(_a3_*_a4_*x))*abs(_a1_ + x**x))/x
<lambdifygenerated-5051>:2: RuntimeWarning: invalid value encountered in power
  return (x + (_a7_ - cos(_a3_*_a4_*x))*abs(_a1_ + _a5_**x))/x
<lambdifygenerated-5061>:2: RuntimeWarning: invalid value encountered in power
  return (_a6_ + (_a7_ - cos(_a3_*_a4_*x))*abs(_a1_ + _a5_**cos(_a0_*x)))/x
<lambdifygenerated-5063>:2: RuntimeWarning: invalid value encountered in power
  return (_a6_ + (_a7_ - cos(_a3_*_a4_*x))*abs(_a1_ + _a5_**cos(_a0_*x)))/_a4_

300

         x    y         z  rep    zmodel      zbms
1   -0.995  0.0 -0.294774    5 -0.275582 -0.294774
2   -0.990  0.0 -0.294284    5 -0.277000 -0.294284
3   -0.985  0.0 -0.293881    5 -0.278437 -0.293881
4   -0.980  0.0 -0.293564    5 -0.279892 -0.293564
6   -0.970  0.0 -0.293188    5 -0.282859 -0.293188
..     ...  ...       ...  ...       ...       ...
394  0.970  0.0 -0.293188    5 -0.269684 -0.293188
396  0.980  0.0 -0.293564    5 -0.264700 -0.293564
397  0.985  0.0 -0.293881    5 -0.262225 -0.293881
398  0.990  0.0 -0.294284    5 -0.259760 -0.294284
399  0.995  0.0 -0.294774    5 -0.257307 -0.294774

[320 rows x 6 columns]

300

         x    y         z  rep    zmodel      zbms
1   -0.995  0.0 -0.294774    5 -0.287402 -0.275564
2   -0.990  0.0 -0.294284    5 -0.288280 -0.276122
3   -0.985  0.0 -0.293881    5 -0.289175 -0.276734
4   -0.980  0.0 -0.293564    5 -0.290089 -0.277399
6   -0.970  0.0 -0.293188    5 -0.291971 -0.278890
..     ...  ...       ...  ...       ...       ...
394  0.970  0.0 -0.293188    5 -0.491590 -0.278890
396  0.980  0.0 -0.293564    5 -0.490218 -0.277399
397  0.985  0.0 -0.293881    5 -0.489540 -0.276734
398  0.990  0.0 -0.294284    5 -0.488869 -0.276122
399  0.995  0.0 -0.294774    5 -0.488203 -0.275564

[320 rows x 6 columns]

300

         x    y         z  rep    zmodel      zbms
1   -0.995  0.0 -0.294774    5 -0.277882 -0.270691
2   -0.990  0.0 -0.294284    5 -0.279072 -0.271750
3   -0.985  0.0 -0.293881    5 -0.280282 -0.272855
4   -0.980  0.0 -0.293564    5 -0.281513 -0.274007
6   -0.970  0.0 -0.293188    5 -0.284036 -0.276448
..     ...  ...       ...  ...       ...       ...
394  0.970  0.0 -0.293188    5 -0.495698 -0.276448
396  0.980  0.0 -0.293564    5 -0.494136 -0.274007
397  0.985  0.0 -0.293881    5 -0.493362 -0.272855
398  0.990  0.0 -0.294284    5 -0.492592 -0.271750
399  0.995  0.0 -0.294774    5 -0.491827 -0.270691

[320 rows x 6 columns]

300

         x    y         z  rep    zmodel      zbms
1   -0.995  0.0 -0.294774    5 -0.271060 -0.276722
2   -0.990  0.0 -0.294284    5 -0.272697 -0.277795
3   -0.985  0.0 -0.293881    5 -0.274353 -0.278914
4   -0.980  0.0 -0.293564    5 -0.276027 -0.280079
6   -0.970  0.0 -0.293188    5 -0.279431 -0.282546
..     ...  ...       ...  ...       ...       ...
394  0.970  0.0 -0.293188    5 -0.408498 -0.282546
396  0.980  0.0 -0.293564    5 -0.405717 -0.280079
397  0.985  0.0 -0.293881    5 -0.404340 -0.278914
398  0.990  0.0 -0.294284    5 -0.402972 -0.277795
399  0.995  0.0 -0.294774    5 -0.401612 -0.276722

[320 rows x 6 columns]

300

/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/nguyen_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(

         x    y         z  rep    zmodel      zbms
1   -0.995  0.0 -0.294774    5 -0.270654 -0.259614
2   -0.990  0.0 -0.294284    5 -0.272395 -0.261742
3   -0.985  0.0 -0.293881    5 -0.274155 -0.263886
4   -0.980  0.0 -0.293564    5 -0.275932 -0.266044
6   -0.970  0.0 -0.293188    5 -0.279543 -0.270407
..     ...  ...       ...  ...       ...       ...
394  0.970  0.0 -0.293188    5 -0.332050 -0.270407
396  0.980  0.0 -0.293564    5 -0.328510 -0.266044
397  0.985  0.0 -0.293881    5 -0.326758 -0.263886
398  0.990  0.0 -0.294284    5 -0.325017 -0.261742
399  0.995  0.0 -0.294774    5 -0.323289 -0.259614

[320 rows x 6 columns]

300

<lambdifygenerated-5169>:2: RuntimeWarning: invalid value encountered in power
  return _a2_*x**x
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/nguyen_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-5170>:2: RuntimeWarning: invalid value encountered in power
  return _a2_*x**x

         x    y         z  rep    zmodel      zbms
1   -0.995  0.0 -0.294774    5 -0.276598 -0.229697
2   -0.990  0.0 -0.294284    5 -0.278005 -0.232195
3   -0.985  0.0 -0.293881    5 -0.279429 -0.234712
4   -0.980  0.0 -0.293564    5 -0.280872 -0.237248
6   -0.970  0.0 -0.293188    5 -0.283810 -0.242375
..     ...  ...       ...  ...       ...       ...
394  0.970  0.0 -0.293188    5 -0.380173 -0.242375
396  0.980  0.0 -0.293564    5 -0.377313 -0.237248
397  0.985  0.0 -0.293881    5 -0.375899 -0.234712
398  0.990  0.0 -0.294284    5 -0.374495 -0.232195
399  0.995  0.0 -0.294774    5 -0.373102 -0.229697

[320 rows x 6 columns]

300

<lambdifygenerated-5187>:2: RuntimeWarning: invalid value encountered in power
  return x*x**x
<lambdifygenerated-5188>:2: RuntimeWarning: invalid value encountered in power
  return x*x**x
<lambdifygenerated-5191>:2: RuntimeWarning: invalid value encountered in power
  return _a1_**(x**2)*x
<lambdifygenerated-5195>:2: RuntimeWarning: invalid value encountered in power
  return _a1_**(x**2)*_a5_

         x    y         z  rep    zmodel      zbms
1   -0.995  0.0 -0.294774    5 -0.262021 -0.223612
2   -0.990  0.0 -0.294284    5 -0.263745 -0.226302
3   -0.985  0.0 -0.293881    5 -0.265491 -0.229011
4   -0.980  0.0 -0.293564    5 -0.267257 -0.231738
6   -0.970  0.0 -0.293188    5 -0.270852 -0.237247
..     ...  ...       ...  ...       ...       ...
394  0.970  0.0 -0.293188    5 -0.459163 -0.237247
396  0.980  0.0 -0.293564    5 -0.457122 -0.231738
397  0.985  0.0 -0.293881    5 -0.456112 -0.229011
398  0.990  0.0 -0.294284    5 -0.455108 -0.226302
399  0.995  0.0 -0.294774    5 -0.454111 -0.223612

[320 rows x 6 columns]

<lambdifygenerated-5211>:2: RuntimeWarning: divide by zero encountered in divide
  return _a2_/(_a4_ + x)
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/nguyen_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-5212>:2: RuntimeWarning: divide by zero encountered in divide
  return _a2_/(_a4_ + x)

300

         x    y         z  rep    zmodel      zbms
1   -0.995  0.0 -0.294774    5 -0.254989 -0.264530
2   -0.990  0.0 -0.294284    5 -0.256537 -0.266278
3   -0.985  0.0 -0.293881    5 -0.258112 -0.268041
4   -0.980  0.0 -0.293564    5 -0.259715 -0.269817
6   -0.970  0.0 -0.293188    5 -0.263003 -0.273414
..     ...  ...       ...  ...       ...       ...
394  0.970  0.0 -0.293188    5 -0.164346 -0.273414
396  0.980  0.0 -0.293564    5 -0.156930 -0.269817
397  0.985  0.0 -0.293881    5 -0.153241 -0.268041
398  0.990  0.0 -0.294284    5 -0.149565 -0.266278
399  0.995  0.0 -0.294774    5 -0.145903 -0.264530

[320 rows x 6 columns]

300

<lambdifygenerated-5227>:2: RuntimeWarning: invalid value encountered in power
  return x*x**x
<lambdifygenerated-5228>:2: RuntimeWarning: invalid value encountered in power
  return x*x**x
<lambdifygenerated-5231>:2: RuntimeWarning: invalid value encountered in power
  return _a7_**(x**2)*x
<lambdifygenerated-5237>:2: RuntimeWarning: invalid value encountered in power
  return _a0_*_a7_**(x**2)

         x    y         z  rep    zmodel      zbms
1   -0.995  0.0 -0.294774    5 -0.278900 -0.230395
2   -0.990  0.0 -0.294284    5 -0.280764 -0.233108
3   -0.985  0.0 -0.293881    5 -0.282639 -0.235838
4   -0.980  0.0 -0.293564    5 -0.284525 -0.238587
6   -0.970  0.0 -0.293188    5 -0.288330 -0.244137
..     ...  ...       ...  ...       ...       ...
394  0.970  0.0 -0.293188    5 -0.084408 -0.244137
396  0.980  0.0 -0.293564    5 -0.077146 -0.238587
397  0.985  0.0 -0.293881    5 -0.073554 -0.235838
398  0.990  0.0 -0.294284    5 -0.069989 -0.233108
399  0.995  0.0 -0.294774    5 -0.066451 -0.230395

[320 rows x 6 columns]

<lambdifygenerated-5253>:2: RuntimeWarning: divide by zero encountered in divide
  return _a4_/(_a3_ + x)

300

/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/nguyen_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-5254>:2: RuntimeWarning: divide by zero encountered in divide
  return _a4_/(_a3_ + x)

         x    y         z  rep    zmodel      zbms
1   -0.995  0.0 -0.294774    5 -0.288444 -0.282525
2   -0.990  0.0 -0.294284    5 -0.289954 -0.284315
3   -0.985  0.0 -0.293881    5 -0.291481 -0.286120
4   -0.980  0.0 -0.293564    5 -0.293025 -0.287938
6   -0.970  0.0 -0.293188    5 -0.296164 -0.291616
..     ...  ...       ...  ...       ...       ...
394  0.970  0.0 -0.293188    5 -0.372292 -0.291616
396  0.980  0.0 -0.293564    5 -0.369657 -0.287938
397  0.985  0.0 -0.293881    5 -0.368353 -0.286120
398  0.990  0.0 -0.294284    5 -0.367057 -0.284315
399  0.995  0.0 -0.294774    5 -0.365770 -0.282525

[320 rows x 6 columns]

300

         x    y         z  rep    zmodel      zbms
1   -0.995  0.0 -0.294774    5 -0.259003 -0.220688
2   -0.990  0.0 -0.294284    5 -0.262003 -0.224095
3   -0.985  0.0 -0.293881    5 -0.265011 -0.227517
4   -0.980  0.0 -0.293564    5 -0.268029 -0.230953
6   -0.970  0.0 -0.293188    5 -0.274091 -0.237868
..     ...  ...       ...  ...       ...       ...
394  0.970  0.0 -0.293188    5 -0.193925 -0.237868
396  0.980  0.0 -0.293564    5 -0.187099 -0.230953
397  0.985  0.0 -0.293881    5 -0.183726 -0.227517
398  0.990  0.0 -0.294284    5 -0.180379 -0.224095
399  0.995  0.0 -0.294774    5 -0.177059 -0.220688

[320 rows x 6 columns]

300

<lambdifygenerated-5291>:2: RuntimeWarning: divide by zero encountered in divide
  return _a2_/(_a1_ + x)
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/nguyen_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-5292>:2: RuntimeWarning: divide by zero encountered in divide
  return _a2_/(_a1_ + x)

         x    y         z  rep    zmodel      zbms
1   -0.995  0.0 -0.294774    5 -0.268750 -0.267196
2   -0.990  0.0 -0.294284    5 -0.269903 -0.268945
3   -0.985  0.0 -0.293881    5 -0.271079 -0.270709
4   -0.980  0.0 -0.293564    5 -0.272278 -0.272486
6   -0.970  0.0 -0.293188    5 -0.274748 -0.276084
..     ...  ...       ...  ...       ...       ...
394  0.970  0.0 -0.293188    5 -0.366006 -0.276084
396  0.980  0.0 -0.293564    5 -0.361464 -0.272486
397  0.985  0.0 -0.293881    5 -0.359207 -0.270709
398  0.990  0.0 -0.294284    5 -0.356958 -0.268945
399  0.995  0.0 -0.294774    5 -0.354719 -0.267196

[320 rows x 6 columns]

300

<lambdifygenerated-5311>:2: RuntimeWarning: invalid value encountered in power
  return _a7_*x**x
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/nguyen_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-5312>:2: RuntimeWarning: invalid value encountered in power
  return _a7_*x**x

         x    y         z  rep    zmodel      zbms
1   -0.995  0.0 -0.294774    5 -0.271187 -0.238892
2   -0.990  0.0 -0.294284    5 -0.272546 -0.241373
3   -0.985  0.0 -0.293881    5 -0.273921 -0.243872
4   -0.980  0.0 -0.293564    5 -0.275313 -0.246389
6   -0.970  0.0 -0.293188    5 -0.278149 -0.251474
..     ...  ...       ...  ...       ...       ...
394  0.970  0.0 -0.293188    5 -0.447780 -0.251474
396  0.980  0.0 -0.293564    5 -0.444990 -0.246389
397  0.985  0.0 -0.293881    5 -0.443604 -0.243872
398  0.990  0.0 -0.294284    5 -0.442226 -0.241373
399  0.995  0.0 -0.294774    5 -0.440854 -0.238892

[320 rows x 6 columns]

300

         x    y         z  rep    zmodel      zbms
1   -0.995  0.0 -0.294774    5 -0.254096 -0.209438
2   -0.990  0.0 -0.294284    5 -0.254926 -0.212671
3   -0.985  0.0 -0.293881    5 -0.255776 -0.215918
4   -0.980  0.0 -0.293564    5 -0.256647 -0.219179
6   -0.970  0.0 -0.293188    5 -0.258453 -0.225742
..     ...  ...       ...  ...       ...       ...
394  0.970  0.0 -0.293188    5 -0.460627 -0.225742
396  0.980  0.0 -0.293564    5 -0.457883 -0.219179
397  0.985  0.0 -0.293881    5 -0.456516 -0.215918
398  0.990  0.0 -0.294284    5 -0.455153 -0.212671
399  0.995  0.0 -0.294774    5 -0.453793 -0.209438

[320 rows x 6 columns]

300

/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/nguyen_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(

         x    y         z  rep    zmodel      zbms
1   -0.995  0.0 -0.294774    5 -0.237513 -0.203856
2   -0.990  0.0 -0.294284    5 -0.240076 -0.209098
3   -0.985  0.0 -0.293881    5 -0.242655 -0.214313
4   -0.980  0.0 -0.293564    5 -0.245249 -0.219502
6   -0.970  0.0 -0.293188    5 -0.250486 -0.229801
..     ...  ...       ...  ...       ...       ...
394  0.970  0.0 -0.293188    5 -0.517695 -0.229801
396  0.980  0.0 -0.293564    5 -0.515497 -0.219502
397  0.985  0.0 -0.293881    5 -0.514405 -0.214313
398  0.990  0.0 -0.294284    5 -0.513317 -0.209098
399  0.995  0.0 -0.294774    5 -0.512233 -0.203856

[320 rows x 6 columns]

300

         x    y         z  rep    zmodel      zbms
1   -0.995  0.0 -0.294774    5 -0.280948 -0.213207
2   -0.990  0.0 -0.294284    5 -0.282573 -0.216499
3   -0.985  0.0 -0.293881    5 -0.284213 -0.219804
4   -0.980  0.0 -0.293564    5 -0.285870 -0.223124
6   -0.970  0.0 -0.293188    5 -0.289234 -0.229804
..     ...  ...       ...  ...       ...       ...
394  0.970  0.0 -0.293188    5 -0.054346 -0.229804
396  0.980  0.0 -0.293564    5 -0.046889 -0.223124
397  0.985  0.0 -0.293881    5 -0.043197 -0.219804
398  0.990  0.0 -0.294284    5 -0.039530 -0.216499
399  0.995  0.0 -0.294774    5 -0.035888 -0.213207

[320 rows x 6 columns]

300

         x    y         z  rep    zmodel      zbms
1   -0.995  0.0 -0.294774    5 -0.265428 -0.220975
2   -0.990  0.0 -0.294284    5 -0.267749 -0.224387
3   -0.985  0.0 -0.293881    5 -0.270085 -0.227813
4   -0.980  0.0 -0.293564    5 -0.272439 -0.231254
6   -0.970  0.0 -0.293188    5 -0.277196 -0.238177
..     ...  ...       ...  ...       ...       ...
394  0.970  0.0 -0.293188    5 -0.385923 -0.238177
396  0.980  0.0 -0.293564    5 -0.382545 -0.231254
397  0.985  0.0 -0.293881    5 -0.380870 -0.227813
398  0.990  0.0 -0.294284    5 -0.379205 -0.224387
399  0.995  0.0 -0.294774    5 -0.377549 -0.220975

[320 rows x 6 columns]

300

         x    y         z  rep    zmodel      zbms
1   -0.995  0.0 -0.294774    5 -0.365227 -0.312136
2   -0.990  0.0 -0.294284    5 -0.366243 -0.314486
3   -0.985  0.0 -0.293881    5 -0.367271 -0.316835
4   -0.980  0.0 -0.293564    5 -0.368312 -0.319185
6   -0.970  0.0 -0.293188    5 -0.370428 -0.323883
..     ...  ...       ...  ...       ...       ...
394  0.970  0.0 -0.293188    5 -0.235330 -0.323883
396  0.980  0.0 -0.293564    5 -0.231233 -0.319185
397  0.985  0.0 -0.293881    5 -0.229208 -0.316835
398  0.990  0.0 -0.294284    5 -0.227200 -0.314486
399  0.995  0.0 -0.294774    5 -0.225206 -0.312136

[320 rows x 6 columns]

300

         x    y         z  rep    zmodel      zbms
1   -0.995  0.0 -0.294774    5 -0.254862 -0.213986
2   -0.990  0.0 -0.294284    5 -0.256906 -0.217289
3   -0.985  0.0 -0.293881    5 -0.258965 -0.220607
4   -0.980  0.0 -0.293564    5 -0.261039 -0.223939
6   -0.970  0.0 -0.293188    5 -0.265233 -0.230644
..     ...  ...       ...  ...       ...       ...
394  0.970  0.0 -0.293188    5 -0.519265 -0.230644
396  0.980  0.0 -0.293564    5 -0.517553 -0.223939
397  0.985  0.0 -0.293881    5 -0.516704 -0.220607
398  0.990  0.0 -0.294284    5 -0.515859 -0.217289
399  0.995  0.0 -0.294774    5 -0.515018 -0.213986

[320 rows x 6 columns]

300

         x    y         z  rep    zmodel      zbms
1   -0.995  0.0 -0.294774    5 -0.259241 -0.346976
2   -0.990  0.0 -0.294284    5 -0.262407 -0.349644
3   -0.985  0.0 -0.293881    5 -0.265585 -0.352303
4   -0.980  0.0 -0.293564    5 -0.268774 -0.354954
6   -0.970  0.0 -0.293188    5 -0.275184 -0.360228
..     ...  ...       ...  ...       ...       ...
394  0.970  0.0 -0.293188    5  0.638690 -0.360228
396  0.980  0.0 -0.293564    5  0.644140 -0.354954
397  0.985  0.0 -0.293881    5  0.646729 -0.352303
398  0.990  0.0 -0.294284    5  0.649232 -0.349644
399  0.995  0.0 -0.294774    5  0.651652 -0.346976

[320 rows x 6 columns]

300

/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/nguyen_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(

         x    y         z  rep    zmodel      zbms
1   -0.995  0.0 -0.294774    5 -0.291293 -0.213776
2   -0.990  0.0 -0.294284    5 -0.292511 -0.218679
3   -0.985  0.0 -0.293881    5 -0.293740 -0.223558
4   -0.980  0.0 -0.293564    5 -0.294978 -0.228411
6   -0.970  0.0 -0.293188    5 -0.297486 -0.238045
..     ...  ...       ...  ...       ...       ...
394  0.970  0.0 -0.293188    5 -0.562182 -0.238045
396  0.980  0.0 -0.293564    5 -0.561658 -0.228411
397  0.985  0.0 -0.293881    5 -0.561400 -0.223558
398  0.990  0.0 -0.294284    5 -0.561144 -0.218679
399  0.995  0.0 -0.294774    5 -0.560891 -0.213776

[320 rows x 6 columns]

300

         x    y         z  rep    zmodel      zbms
1   -0.995  0.0 -0.294774    5 -0.267958 -0.217685
2   -0.990  0.0 -0.294284    5 -0.270340 -0.221046
3   -0.985  0.0 -0.293881    5 -0.272737 -0.224421
4   -0.980  0.0 -0.293564    5 -0.275149 -0.227810
6   -0.970  0.0 -0.293188    5 -0.280016 -0.234631
..     ...  ...       ...  ...       ...       ...
394  0.970  0.0 -0.293188    5 -0.618548 -0.234631
396  0.980  0.0 -0.293564    5 -0.617186 -0.227810
397  0.985  0.0 -0.293881    5 -0.616509 -0.224421
398  0.990  0.0 -0.294284    5 -0.615835 -0.221046
399  0.995  0.0 -0.294774    5 -0.615162 -0.217685

[320 rows x 6 columns]

300

<lambdifygenerated-5497>:2: RuntimeWarning: invalid value encountered in power
  return _a7_*x**x
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/nguyen_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-5498>:2: RuntimeWarning: invalid value encountered in power
  return _a7_*x**x
<lambdifygenerated-5501>:2: RuntimeWarning: invalid value encountered in power
  return _a1_**abs(x)*_a7_

         x    y         z  rep    zmodel      zbms
1   -0.995  0.0 -0.294774    5 -0.325512 -0.308461
2   -0.990  0.0 -0.294284    5 -0.326611 -0.310089
3   -0.985  0.0 -0.293881    5 -0.327724 -0.311726
4   -0.980  0.0 -0.293564    5 -0.328849 -0.313372
6   -0.970  0.0 -0.293188    5 -0.331138 -0.316690
..     ...  ...       ...  ...       ...       ...
394  0.970  0.0 -0.293188    5  0.275738 -0.316690
396  0.980  0.0 -0.293564    5  0.284599 -0.313372
397  0.985  0.0 -0.293881    5  0.288934 -0.311726
398  0.990  0.0 -0.294284    5  0.293207 -0.310089
399  0.995  0.0 -0.294774    5  0.297417 -0.308461

[320 rows x 6 columns]

300

         x    y         z  rep    zmodel      zbms
1   -0.995  0.0 -0.294774    5 -0.321196 -0.356178
2   -0.990  0.0 -0.294284    5 -0.322428 -0.358916
3   -0.985  0.0 -0.293881    5 -0.323672 -0.361646
4   -0.980  0.0 -0.293564    5 -0.324929 -0.364367
6   -0.970  0.0 -0.293188    5 -0.327480 -0.369781
..     ...  ...       ...  ...       ...       ...
394  0.970  0.0 -0.293188    5  0.966393 -0.369781
396  0.980  0.0 -0.293564    5  0.980502 -0.364367
397  0.985  0.0 -0.293881    5  0.987345 -0.361646
398  0.990  0.0 -0.294284    5  0.994052 -0.358916
399  0.995  0.0 -0.294774    5  1.000625 -0.356178

[320 rows x 6 columns]

300

<lambdifygenerated-5535>:2: RuntimeWarning: divide by zero encountered in divide
  return _a3_/(_a5_ + x)
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/nguyen_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-5536>:2: RuntimeWarning: divide by zero encountered in divide
  return _a3_/(_a5_ + x)

         x    y         z  rep    zmodel      zbms
1   -0.995  0.0 -0.294774    5 -0.299699 -0.267147
2   -0.990  0.0 -0.294284    5 -0.300804 -0.268939
3   -0.985  0.0 -0.293881    5 -0.301929 -0.270747
4   -0.980  0.0 -0.293564    5 -0.303076 -0.272570
6   -0.970  0.0 -0.293188    5 -0.305433 -0.276261
..     ...  ...       ...  ...       ...       ...
394  0.970  0.0 -0.293188    5 -0.628887 -0.276261
396  0.980  0.0 -0.293564    5 -0.627800 -0.272570
397  0.985  0.0 -0.293881    5 -0.627260 -0.270747
398  0.990  0.0 -0.294284    5 -0.626723 -0.268939
399  0.995  0.0 -0.294774    5 -0.626190 -0.267147

[320 rows x 6 columns]

300

         x    y         z  rep    zmodel      zbms
1   -0.995  0.0 -0.294774    5 -0.239325 -0.141666
2   -0.990  0.0 -0.294284    5 -0.241578 -0.147485
3   -0.985  0.0 -0.293881    5 -0.243837 -0.153265
4   -0.980  0.0 -0.293564    5 -0.246103 -0.159007
6   -0.970  0.0 -0.293188    5 -0.250653 -0.170377
..     ...  ...       ...  ...       ...       ...
394  0.970  0.0 -0.293188    5 -0.734622 -0.170377
396  0.980  0.0 -0.293564    5 -0.734453 -0.159007
397  0.985  0.0 -0.293881    5 -0.734365 -0.153265
398  0.990  0.0 -0.294284    5 -0.734276 -0.147485
399  0.995  0.0 -0.294774    5 -0.734185 -0.141666

[320 rows x 6 columns]

300

         x    y         z  rep    zmodel      zbms
1   -0.995  0.0 -0.294774    5 -0.414613 -0.203773
2   -0.990  0.0 -0.294284    5 -0.412625 -0.206919
3   -0.985  0.0 -0.293881    5 -0.410633 -0.210078
4   -0.980  0.0 -0.293564    5 -0.408639 -0.213251
6   -0.970  0.0 -0.293188    5 -0.404648 -0.219636
..     ...  ...       ...  ...       ...       ...
394  0.970  0.0 -0.293188    5 -0.634191 -0.219636
396  0.980  0.0 -0.293564    5 -0.633741 -0.213251
397  0.985  0.0 -0.293881    5 -0.633518 -0.210078
398  0.990  0.0 -0.294284    5 -0.633295 -0.206919
399  0.995  0.0 -0.294774    5 -0.633074 -0.203773

[320 rows x 6 columns]

300

         x    y         z  rep    zmodel      zbms
1   -0.995  0.0 -0.294774    5 -0.292821 -0.225823
2   -0.990  0.0 -0.294284    5 -0.294975 -0.229310
3   -0.985  0.0 -0.293881    5 -0.297142 -0.232811
4   -0.980  0.0 -0.293564    5 -0.299322 -0.236327
6   -0.970  0.0 -0.293188    5 -0.303720 -0.243403
..     ...  ...       ...  ...       ...       ...
394  0.970  0.0 -0.293188    5 -0.502880 -0.243403
396  0.980  0.0 -0.293564    5 -0.501383 -0.236327
397  0.985  0.0 -0.293881    5 -0.500643 -0.232811
398  0.990  0.0 -0.294284    5 -0.499910 -0.229310
399  0.995  0.0 -0.294774    5 -0.499183 -0.225823

[320 rows x 6 columns]

300

         x    y         z  rep    zmodel      zbms
1   -0.995  0.0 -0.294774    5 -0.453855 -0.612687
2   -0.990  0.0 -0.294284    5 -0.454827 -0.612687
3   -0.985  0.0 -0.293881    5 -0.455802 -0.612687
4   -0.980  0.0 -0.293564    5 -0.456780 -0.612687
6   -0.970  0.0 -0.293188    5 -0.458744 -0.612687
..     ...  ...       ...  ...       ...       ...
394  0.970  0.0 -0.293188    5 -0.805779 -0.612687
396  0.980  0.0 -0.293564    5 -0.806478 -0.612687
397  0.985  0.0 -0.293881    5 -0.806823 -0.612687
398  0.990  0.0 -0.294284    5 -0.807166 -0.612687
399  0.995  0.0 -0.294774    5 -0.807507 -0.612687

[320 rows x 6 columns]

300

         x    y         z  rep    zmodel      zbms
1   -0.995  0.0 -0.294774    5 -0.251181 -0.583323
2   -0.990  0.0 -0.294284    5 -0.253410 -0.583323
3   -0.985  0.0 -0.293881    5 -0.255651 -0.583323
4   -0.980  0.0 -0.293564    5 -0.257907 -0.583323
6   -0.970  0.0 -0.293188    5 -0.262457 -0.583323
..     ...  ...       ...  ...       ...       ...
394  0.970  0.0 -0.293188    5 -0.470953 -0.583323
396  0.980  0.0 -0.293564    5 -0.469122 -0.583323
397  0.985  0.0 -0.293881    5 -0.468212 -0.583323
398  0.990  0.0 -0.294284    5 -0.467306 -0.583323
399  0.995  0.0 -0.294774    5 -0.466404 -0.583323

[320 rows x 6 columns]

300

         x    y         z  rep    zmodel      zbms
1   -0.995  0.0 -0.294774    5 -0.463484 -0.629823
2   -0.990  0.0 -0.294284    5 -0.463823 -0.629823
3   -0.985  0.0 -0.293881    5 -0.464163 -0.629823
4   -0.980  0.0 -0.293564    5 -0.464502 -0.629823
6   -0.970  0.0 -0.293188    5 -0.465183 -0.629823
..     ...  ...       ...  ...       ...       ...
394  0.970  0.0 -0.293188    5 -0.600975 -0.629823
396  0.980  0.0 -0.293564    5 -0.601565 -0.629823
397  0.985  0.0 -0.293881    5 -0.601860 -0.629823
398  0.990  0.0 -0.294284    5 -0.602153 -0.629823
399  0.995  0.0 -0.294774    5 -0.602447 -0.629823

[320 rows x 6 columns]

300

<lambdifygenerated-5631>:2: RuntimeWarning: divide by zero encountered in log
  return log(x)
<lambdifygenerated-5632>:2: RuntimeWarning: divide by zero encountered in log
  return log(x)
<lambdifygenerated-5637>:2: RuntimeWarning: invalid value encountered in divide
  return log((x**3 + x)/x)
<lambdifygenerated-5638>:2: RuntimeWarning: invalid value encountered in divide
  return log((x**3 + x)/x)
<lambdifygenerated-5639>:2: RuntimeWarning: invalid value encountered in divide
  return log((8*x**3 + x)/x)
<lambdifygenerated-5640>:2: RuntimeWarning: invalid value encountered in divide
  return log((8*x**3 + x)/x)
<lambdifygenerated-5641>:2: RuntimeWarning: divide by zero encountered in divide
  return log((x + (_a3_ + x)**3)/x)
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/nguyen_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-5642>:2: RuntimeWarning: divide by zero encountered in divide
  return log((x + (_a3_ + x)**3)/x)
<lambdifygenerated-5643>:2: RuntimeWarning: divide by zero encountered in divide
  return log((x + (_a3_ + x)**3)/x)
<lambdifygenerated-5644>:2: RuntimeWarning: divide by zero encountered in divide
  return log((x + (_a3_ + x)**3)/x)
<lambdifygenerated-5645>:2: RuntimeWarning: divide by zero encountered in divide
  return log((2*x + (_a3_ + x)**3)/x)
<lambdifygenerated-5646>:2: RuntimeWarning: divide by zero encountered in divide
  return log((2*x + (_a3_ + x)**3)/x)
<lambdifygenerated-5647>:2: RuntimeWarning: divide by zero encountered in divide
  return log((_a1_ + x + (_a3_ + x)**3)/x)
<lambdifygenerated-5648>:2: RuntimeWarning: divide by zero encountered in divide
  return log((_a1_ + x + (_a3_ + x)**3)/x)
<lambdifygenerated-5649>:2: RuntimeWarning: divide by zero encountered in divide
  return log((_a1_ + x**2 + (_a3_ + x)**3)/x)
<lambdifygenerated-5650>:2: RuntimeWarning: divide by zero encountered in divide
  return log((_a1_ + x**2 + (_a3_ + x)**3)/x)
<lambdifygenerated-5651>:2: RuntimeWarning: divide by zero encountered in divide
  return log((_a1_ + _a6_*x + (_a3_ + x)**3)/x)
<lambdifygenerated-5652>:2: RuntimeWarning: divide by zero encountered in divide
  return log((_a1_ + _a6_*x + (_a3_ + x)**3)/x)
<lambdifygenerated-5653>:2: RuntimeWarning: divide by zero encountered in divide
  return log((_a1_ + _a6_*x + (_a3_ + x)**3)/x)
<lambdifygenerated-5654>:2: RuntimeWarning: divide by zero encountered in divide
  return log((_a1_ + _a6_*x + (_a3_ + x)**3)/x)
<lambdifygenerated-5657>:2: RuntimeWarning: divide by zero encountered in log
  return log(x*(_a1_ + _a6_*x + (_a3_ + x)**3)/_a4_)
<lambdifygenerated-5658>:2: RuntimeWarning: divide by zero encountered in log
  return log(x*(_a1_ + _a6_*x + (_a3_ + x)**3)/_a4_)

         x    y         z  rep    zmodel      zbms
1    0.005  0.0  0.602421    7  0.588255  0.602421
2    0.010  0.0  0.606031    7  0.592541  0.606031
3    0.015  0.0  0.609667    7  0.596842  0.609667
4    0.020  0.0  0.613329    7  0.601158  0.613329
6    0.030  0.0  0.620731    7  0.609835  0.620731
..     ...  ...       ...  ...       ...       ...
394  1.970  0.0  2.859892    7  2.821948  2.859892
396  1.980  0.0  2.870450    7  2.830845  2.870450
397  1.985  0.0  2.875718    7  2.835269  2.875718
398  1.990  0.0  2.880980    7  2.839677  2.880980
399  1.995  0.0  2.886235    7  2.844069  2.886235

[320 rows x 6 columns]

300

<lambdifygenerated-5671>:2: RuntimeWarning: divide by zero encountered in log
  return x*log(x)
<lambdifygenerated-5671>:2: RuntimeWarning: invalid value encountered in multiply
  return x*log(x)
<lambdifygenerated-5672>:2: RuntimeWarning: divide by zero encountered in log
  return x*log(x)
<lambdifygenerated-5672>:2: RuntimeWarning: invalid value encountered in multiply
  return x*log(x)
<lambdifygenerated-5673>:2: RuntimeWarning: divide by zero encountered in log
  return x*log(x**2)
<lambdifygenerated-5673>:2: RuntimeWarning: invalid value encountered in multiply
  return x*log(x**2)
<lambdifygenerated-5674>:2: RuntimeWarning: divide by zero encountered in log
  return x*log(x**2)
<lambdifygenerated-5674>:2: RuntimeWarning: invalid value encountered in multiply
  return x*log(x**2)
<lambdifygenerated-5675>:2: RuntimeWarning: divide by zero encountered in log
  return x*log(x**4)
<lambdifygenerated-5675>:2: RuntimeWarning: invalid value encountered in multiply
  return x*log(x**4)
<lambdifygenerated-5676>:2: RuntimeWarning: divide by zero encountered in log
  return x*log(x**4)
<lambdifygenerated-5676>:2: RuntimeWarning: invalid value encountered in multiply
  return x*log(x**4)
<lambdifygenerated-5677>:2: RuntimeWarning: divide by zero encountered in log
  return x*log(4*x**4)
<lambdifygenerated-5677>:2: RuntimeWarning: invalid value encountered in multiply
  return x*log(4*x**4)
<lambdifygenerated-5678>:2: RuntimeWarning: divide by zero encountered in log
  return x*log(4*x**4)
<lambdifygenerated-5678>:2: RuntimeWarning: invalid value encountered in multiply
  return x*log(4*x**4)
<lambdifygenerated-5679>:2: RuntimeWarning: divide by zero encountered in log
  return x*log(x**2*(x + 1)**2)
<lambdifygenerated-5679>:2: RuntimeWarning: invalid value encountered in multiply
  return x*log(x**2*(x + 1)**2)
<lambdifygenerated-5680>:2: RuntimeWarning: divide by zero encountered in log
  return x*log(x**2*(x + 1)**2)
<lambdifygenerated-5680>:2: RuntimeWarning: invalid value encountered in multiply
  return x*log(x**2*(x + 1)**2)
<lambdifygenerated-5681>:2: RuntimeWarning: divide by zero encountered in log
  return x*log(4*x**4)
<lambdifygenerated-5681>:2: RuntimeWarning: invalid value encountered in multiply
  return x*log(4*x**4)
<lambdifygenerated-5682>:2: RuntimeWarning: divide by zero encountered in log
  return x*log(4*x**4)
<lambdifygenerated-5682>:2: RuntimeWarning: invalid value encountered in multiply
  return x*log(4*x**4)
<lambdifygenerated-5683>:2: RuntimeWarning: divide by zero encountered in log
  return x*log(x**2*(x**2 + x)**2)
<lambdifygenerated-5683>:2: RuntimeWarning: invalid value encountered in multiply
  return x*log(x**2*(x**2 + x)**2)
<lambdifygenerated-5684>:2: RuntimeWarning: divide by zero encountered in log
  return x*log(x**2*(x**2 + x)**2)
<lambdifygenerated-5684>:2: RuntimeWarning: invalid value encountered in multiply
  return x*log(x**2*(x**2 + x)**2)
<lambdifygenerated-5685>:2: RuntimeWarning: divide by zero encountered in log
  return x*log(x**2*(x**2 + x)**2)
<lambdifygenerated-5685>:2: RuntimeWarning: invalid value encountered in multiply
  return x*log(x**2*(x**2 + x)**2)
<lambdifygenerated-5686>:2: RuntimeWarning: divide by zero encountered in log
  return x*log(x**2*(x**2 + x)**2)
<lambdifygenerated-5686>:2: RuntimeWarning: invalid value encountered in multiply
  return x*log(x**2*(x**2 + x)**2)
<lambdifygenerated-5687>:2: RuntimeWarning: divide by zero encountered in log
  return x*log(x**2*(2*x**2 + x)**2)
<lambdifygenerated-5687>:2: RuntimeWarning: invalid value encountered in multiply
  return x*log(x**2*(2*x**2 + x)**2)
<lambdifygenerated-5688>:2: RuntimeWarning: divide by zero encountered in log
  return x*log(x**2*(2*x**2 + x)**2)
<lambdifygenerated-5688>:2: RuntimeWarning: invalid value encountered in multiply
  return x*log(x**2*(2*x**2 + x)**2)
<lambdifygenerated-5689>:2: RuntimeWarning: divide by zero encountered in log
  return x*log(x**2*(x*(_a7_ + x) + x)**2)
<lambdifygenerated-5689>:2: RuntimeWarning: invalid value encountered in multiply
  return x*log(x**2*(x*(_a7_ + x) + x)**2)
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/nguyen_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-5690>:2: RuntimeWarning: divide by zero encountered in log
  return x*log(x**2*(x*(_a7_ + x) + x)**2)
<lambdifygenerated-5690>:2: RuntimeWarning: invalid value encountered in multiply
  return x*log(x**2*(x*(_a7_ + x) + x)**2)
<lambdifygenerated-5691>:2: RuntimeWarning: divide by zero encountered in log
  return x*log(x**2*(x*(_a7_ + 1) + x)**2)
<lambdifygenerated-5691>:2: RuntimeWarning: invalid value encountered in multiply
  return x*log(x**2*(x*(_a7_ + 1) + x)**2)
<lambdifygenerated-5692>:2: RuntimeWarning: divide by zero encountered in log
  return x*log(x**2*(x*(_a7_ + 1) + x)**2)
<lambdifygenerated-5692>:2: RuntimeWarning: invalid value encountered in multiply
  return x*log(x**2*(x*(_a7_ + 1) + x)**2)
<lambdifygenerated-5693>:2: RuntimeWarning: divide by zero encountered in log
  return x*log(x**2*(x*(_a7_ + 1) + x)**2)
<lambdifygenerated-5693>:2: RuntimeWarning: invalid value encountered in multiply
  return x*log(x**2*(x*(_a7_ + 1) + x)**2)
<lambdifygenerated-5694>:2: RuntimeWarning: divide by zero encountered in log
  return x*log(x**2*(x*(_a7_ + 1) + x)**2)
<lambdifygenerated-5694>:2: RuntimeWarning: invalid value encountered in multiply
  return x*log(x**2*(x*(_a7_ + 1) + x)**2)
<lambdifygenerated-5695>:2: RuntimeWarning: divide by zero encountered in log
  return x*log(x**2*(x*(_a7_ + x/_a6_) + x)**2)
<lambdifygenerated-5695>:2: RuntimeWarning: invalid value encountered in multiply
  return x*log(x**2*(x*(_a7_ + x/_a6_) + x)**2)
<lambdifygenerated-5696>:2: RuntimeWarning: divide by zero encountered in log
  return x*log(x**2*(x*(_a7_ + x/_a6_) + x)**2)
<lambdifygenerated-5696>:2: RuntimeWarning: invalid value encountered in multiply
  return x*log(x**2*(x*(_a7_ + x/_a6_) + x)**2)
<lambdifygenerated-5697>:2: RuntimeWarning: divide by zero encountered in log
  return x*log(x**2*(x + x**2*(_a7_ + x/_a6_)/_a0_)**2)
<lambdifygenerated-5697>:2: RuntimeWarning: invalid value encountered in multiply
  return x*log(x**2*(x + x**2*(_a7_ + x/_a6_)/_a0_)**2)
<lambdifygenerated-5698>:2: RuntimeWarning: divide by zero encountered in log
  return x*log(x**2*(x + x**2*(_a7_ + x/_a6_)/_a0_)**2)
<lambdifygenerated-5698>:2: RuntimeWarning: invalid value encountered in multiply
  return x*log(x**2*(x + x**2*(_a7_ + x/_a6_)/_a0_)**2)
<lambdifygenerated-5699>:2: RuntimeWarning: divide by zero encountered in log
  return x*log(x**2*(2*x + x**2*(_a7_ + x/_a6_)/_a0_)**2)
<lambdifygenerated-5699>:2: RuntimeWarning: invalid value encountered in multiply
  return x*log(x**2*(2*x + x**2*(_a7_ + x/_a6_)/_a0_)**2)
<lambdifygenerated-5700>:2: RuntimeWarning: divide by zero encountered in log
  return x*log(x**2*(2*x + x**2*(_a7_ + x/_a6_)/_a0_)**2)
<lambdifygenerated-5700>:2: RuntimeWarning: invalid value encountered in multiply
  return x*log(x**2*(2*x + x**2*(_a7_ + x/_a6_)/_a0_)**2)
<lambdifygenerated-5701>:2: RuntimeWarning: divide by zero encountered in log
  return x*log(x**2*(_a7_ + x + x**2*(_a7_ + x/_a6_)/_a0_)**2)
<lambdifygenerated-5701>:2: RuntimeWarning: invalid value encountered in multiply
  return x*log(x**2*(_a7_ + x + x**2*(_a7_ + x/_a6_)/_a0_)**2)
<lambdifygenerated-5702>:2: RuntimeWarning: divide by zero encountered in log
  return x*log(x**2*(_a7_ + x + x**2*(_a7_ + x/_a6_)/_a0_)**2)
<lambdifygenerated-5702>:2: RuntimeWarning: invalid value encountered in multiply
  return x*log(x**2*(_a7_ + x + x**2*(_a7_ + x/_a6_)/_a0_)**2)
<lambdifygenerated-5703>:2: RuntimeWarning: divide by zero encountered in log
  return x*log(x**2*(_a7_ + 2*x + x**2*(_a7_ + x/_a6_)/_a0_)**2)
<lambdifygenerated-5703>:2: RuntimeWarning: invalid value encountered in multiply
  return x*log(x**2*(_a7_ + 2*x + x**2*(_a7_ + x/_a6_)/_a0_)**2)
<lambdifygenerated-5704>:2: RuntimeWarning: divide by zero encountered in log
  return x*log(x**2*(_a7_ + 2*x + x**2*(_a7_ + x/_a6_)/_a0_)**2)
<lambdifygenerated-5704>:2: RuntimeWarning: invalid value encountered in multiply
  return x*log(x**2*(_a7_ + 2*x + x**2*(_a7_ + x/_a6_)/_a0_)**2)
<lambdifygenerated-5705>:2: RuntimeWarning: divide by zero encountered in log
  return x*log(x**2*(_a7_ + 2*x + x**2*(_a7_ + x/_a6_)/_a0_)**2)
<lambdifygenerated-5705>:2: RuntimeWarning: invalid value encountered in multiply
  return x*log(x**2*(_a7_ + 2*x + x**2*(_a7_ + x/_a6_)/_a0_)**2)
<lambdifygenerated-5706>:2: RuntimeWarning: divide by zero encountered in log
  return x*log(x**2*(_a7_ + 2*x + x**2*(_a7_ + x/_a6_)/_a0_)**2)
<lambdifygenerated-5706>:2: RuntimeWarning: invalid value encountered in multiply
  return x*log(x**2*(_a7_ + 2*x + x**2*(_a7_ + x/_a6_)/_a0_)**2)
<lambdifygenerated-5707>:2: RuntimeWarning: divide by zero encountered in log
  return x*log(x**2*(_a7_ + x**2 + x + x**2*(_a7_ + x/_a6_)/_a0_)**2)
<lambdifygenerated-5707>:2: RuntimeWarning: invalid value encountered in multiply
  return x*log(x**2*(_a7_ + x**2 + x + x**2*(_a7_ + x/_a6_)/_a0_)**2)
<lambdifygenerated-5708>:2: RuntimeWarning: divide by zero encountered in log
  return x*log(x**2*(_a7_ + x**2 + x + x**2*(_a7_ + x/_a6_)/_a0_)**2)
<lambdifygenerated-5708>:2: RuntimeWarning: invalid value encountered in multiply
  return x*log(x**2*(_a7_ + x**2 + x + x**2*(_a7_ + x/_a6_)/_a0_)**2)
<lambdifygenerated-5709>:2: RuntimeWarning: divide by zero encountered in log
  return x*log(x**2*(_a7_ + x**2 + x + x**2*(_a7_ + x/_a6_)/_a0_)**2)
<lambdifygenerated-5709>:2: RuntimeWarning: invalid value encountered in multiply
  return x*log(x**2*(_a7_ + x**2 + x + x**2*(_a7_ + x/_a6_)/_a0_)**2)
<lambdifygenerated-5710>:2: RuntimeWarning: divide by zero encountered in log
  return x*log(x**2*(_a7_ + x**2 + x + x**2*(_a7_ + x/_a6_)/_a0_)**2)
<lambdifygenerated-5710>:2: RuntimeWarning: invalid value encountered in multiply
  return x*log(x**2*(_a7_ + x**2 + x + x**2*(_a7_ + x/_a6_)/_a0_)**2)
<lambdifygenerated-5711>:2: RuntimeWarning: divide by zero encountered in log
  return x*log(x**2*(_a2_*x + _a7_ + x + x**2*(_a7_ + x/_a6_)/_a0_)**2)
<lambdifygenerated-5711>:2: RuntimeWarning: invalid value encountered in multiply
  return x*log(x**2*(_a2_*x + _a7_ + x + x**2*(_a7_ + x/_a6_)/_a0_)**2)
<lambdifygenerated-5712>:2: RuntimeWarning: divide by zero encountered in log
  return x*log(x**2*(_a2_*x + _a7_ + x + x**2*(_a7_ + x/_a6_)/_a0_)**2)
<lambdifygenerated-5712>:2: RuntimeWarning: invalid value encountered in multiply
  return x*log(x**2*(_a2_*x + _a7_ + x + x**2*(_a7_ + x/_a6_)/_a0_)**2)
<lambdifygenerated-5713>:2: RuntimeWarning: divide by zero encountered in log
  return x*log(x**4*(_a2_*x + _a7_ + x + x**2*(_a7_ + x/_a6_)/_a0_)**2)
<lambdifygenerated-5713>:2: RuntimeWarning: invalid value encountered in multiply
  return x*log(x**4*(_a2_*x + _a7_ + x + x**2*(_a7_ + x/_a6_)/_a0_)**2)
<lambdifygenerated-5714>:2: RuntimeWarning: divide by zero encountered in log
  return x*log(x**4*(_a2_*x + _a7_ + x + x**2*(_a7_ + x/_a6_)/_a0_)**2)
<lambdifygenerated-5714>:2: RuntimeWarning: invalid value encountered in multiply
  return x*log(x**4*(_a2_*x + _a7_ + x + x**2*(_a7_ + x/_a6_)/_a0_)**2)
<lambdifygenerated-5715>:2: RuntimeWarning: divide by zero encountered in log
  return x*log(x**6*(_a2_*x + _a7_ + x + x**2*(_a7_ + x/_a6_)/_a0_)**2)
<lambdifygenerated-5715>:2: RuntimeWarning: invalid value encountered in multiply
  return x*log(x**6*(_a2_*x + _a7_ + x + x**2*(_a7_ + x/_a6_)/_a0_)**2)
<lambdifygenerated-5716>:2: RuntimeWarning: divide by zero encountered in log
  return x*log(x**6*(_a2_*x + _a7_ + x + x**2*(_a7_ + x/_a6_)/_a0_)**2)
<lambdifygenerated-5716>:2: RuntimeWarning: invalid value encountered in multiply
  return x*log(x**6*(_a2_*x + _a7_ + x + x**2*(_a7_ + x/_a6_)/_a0_)**2)
<lambdifygenerated-5717>:2: RuntimeWarning: divide by zero encountered in log
  return x*log(_a4_**2*x**4*(_a2_*x + _a7_ + x + x**2*(_a7_ + x/_a6_)/_a0_)**2)
<lambdifygenerated-5717>:2: RuntimeWarning: invalid value encountered in multiply
  return x*log(_a4_**2*x**4*(_a2_*x + _a7_ + x + x**2*(_a7_ + x/_a6_)/_a0_)**2)
<lambdifygenerated-5718>:2: RuntimeWarning: divide by zero encountered in log
  return x*log(_a4_**2*x**4*(_a2_*x + _a7_ + x + x**2*(_a7_ + x/_a6_)/_a0_)**2)
<lambdifygenerated-5718>:2: RuntimeWarning: invalid value encountered in multiply
  return x*log(_a4_**2*x**4*(_a2_*x + _a7_ + x + x**2*(_a7_ + x/_a6_)/_a0_)**2)
<lambdifygenerated-5719>:2: RuntimeWarning: divide by zero encountered in log
  return x*log(_a2_**2*_a4_**2*x**2*(_a2_*x + _a7_ + x + x**2*(_a7_ + x/_a6_)/_a0_)**2)
<lambdifygenerated-5719>:2: RuntimeWarning: invalid value encountered in multiply
  return x*log(_a2_**2*_a4_**2*x**2*(_a2_*x + _a7_ + x + x**2*(_a7_ + x/_a6_)/_a0_)**2)
<lambdifygenerated-5720>:2: RuntimeWarning: divide by zero encountered in log
  return x*log(_a2_**2*_a4_**2*x**2*(_a2_*x + _a7_ + x + x**2*(_a7_ + x/_a6_)/_a0_)**2)
<lambdifygenerated-5720>:2: RuntimeWarning: invalid value encountered in multiply
  return x*log(_a2_**2*_a4_**2*x**2*(_a2_*x + _a7_ + x + x**2*(_a7_ + x/_a6_)/_a0_)**2)

         x    y         z  rep    zmodel      zbms
1    0.005  0.0  0.602421    7  0.594366  0.602421
2    0.010  0.0  0.606031    7  0.598439  0.606031
3    0.015  0.0  0.609667    7  0.602529  0.609667
4    0.020  0.0  0.613329    7  0.606636  0.613329
6    0.030  0.0  0.620731    7  0.614901  0.620731
..     ...  ...       ...  ...       ...       ...
394  1.970  0.0  2.859892    7  2.782007  2.859892
396  1.980  0.0  2.870450    7  2.790117  2.870450
397  1.985  0.0  2.875718    7  2.794147  2.875718
398  1.990  0.0  2.880980    7  2.798162  2.880980
399  1.995  0.0  2.886235    7  2.802160  2.886235

[320 rows x 6 columns]

300

<lambdifygenerated-5739>:2: RuntimeWarning: divide by zero encountered in log
  return x + (x + log(x))/x
<lambdifygenerated-5740>:2: RuntimeWarning: divide by zero encountered in log
  return x + (x + log(x))/x
<lambdifygenerated-5741>:2: RuntimeWarning: divide by zero encountered in log
  return x + (x + log(x**3))/x
<lambdifygenerated-5742>:2: RuntimeWarning: divide by zero encountered in log
  return x + (x + log(x**3))/x
<lambdifygenerated-5743>:2: RuntimeWarning: divide by zero encountered in log
  return x + (x + log(x**6))/x
<lambdifygenerated-5744>:2: RuntimeWarning: divide by zero encountered in log
  return x + (x + log(x**6))/x
<lambdifygenerated-5745>:2: RuntimeWarning: divide by zero encountered in log
  return x + (x + log(x**9))/x
<lambdifygenerated-5746>:2: RuntimeWarning: divide by zero encountered in log
  return x + (x + log(x**9))/x
<lambdifygenerated-5747>:2: RuntimeWarning: divide by zero encountered in log
  return x + (x + log(8*x**9))/x
<lambdifygenerated-5748>:2: RuntimeWarning: divide by zero encountered in log
  return x + (x + log(8*x**9))/x
<lambdifygenerated-5749>:2: RuntimeWarning: divide by zero encountered in log
  return x + (x + log(27*x**9))/x
<lambdifygenerated-5750>:2: RuntimeWarning: divide by zero encountered in log
  return x + (x + log(27*x**9))/x
<lambdifygenerated-5751>:2: RuntimeWarning: divide by zero encountered in log
  return x + (x + log(x**6*(2*x + x**x)**3))/x
<lambdifygenerated-5752>:2: RuntimeWarning: divide by zero encountered in log
  return x + (x + log(x**6*(2*x + x**x)**3))/x
<lambdifygenerated-5753>:2: RuntimeWarning: divide by zero encountered in log
  return x + (x + log(x**6*(2*x + exp(x)**x)**3))/x
<lambdifygenerated-5754>:2: RuntimeWarning: divide by zero encountered in log
  return x + (x + log(x**6*(2*x + exp(x)**x)**3))/x
<lambdifygenerated-5755>:2: RuntimeWarning: divide by zero encountered in log
  return x + (x + log(x**6*(2*x + exp(-x)**x)**3))/x
<lambdifygenerated-5756>:2: RuntimeWarning: divide by zero encountered in log
  return x + (x + log(x**6*(2*x + exp(-x)**x)**3))/x
<lambdifygenerated-5757>:2: RuntimeWarning: divide by zero encountered in log
  return x + (x + log(x**6*(2*x + exp(-x))**3))/x
<lambdifygenerated-5758>:2: RuntimeWarning: divide by zero encountered in log
  return x + (x + log(x**6*(2*x + exp(-x))**3))/x
<lambdifygenerated-5759>:2: RuntimeWarning: divide by zero encountered in log
  return x + (x + log(x**6*(2*x + exp(x))**3))/x
<lambdifygenerated-5760>:2: RuntimeWarning: divide by zero encountered in log
  return x + (x + log(x**6*(2*x + exp(x))**3))/x
<lambdifygenerated-5761>:2: RuntimeWarning: divide by zero encountered in divide
  return x + (x + log(x**6*(2*x + exp(_a4_/x)**x)**3))/x
<lambdifygenerated-5761>:2: RuntimeWarning: divide by zero encountered in log
  return x + (x + log(x**6*(2*x + exp(_a4_/x)**x)**3))/x
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/nguyen_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-5762>:2: RuntimeWarning: divide by zero encountered in divide
  return x + (x + log(x**6*(2*x + exp(_a4_/x)**x)**3))/x
<lambdifygenerated-5762>:2: RuntimeWarning: divide by zero encountered in log
  return x + (x + log(x**6*(2*x + exp(_a4_/x)**x)**3))/x
<lambdifygenerated-5763>:2: RuntimeWarning: divide by zero encountered in log
  return x + (x + log(x**6*(2*x + exp(_a4_)**x)**3))/x
<lambdifygenerated-5764>:2: RuntimeWarning: divide by zero encountered in log
  return x + (x + log(x**6*(2*x + exp(_a4_)**x)**3))/x
<lambdifygenerated-5765>:2: RuntimeWarning: divide by zero encountered in log
  return x + (x + log(x**6*(2*x + exp(_a4_*x/_a0_)**x)**3))/x
<lambdifygenerated-5766>:2: RuntimeWarning: divide by zero encountered in log
  return x + (x + log(x**6*(2*x + exp(_a4_*x/_a0_)**x)**3))/x
<lambdifygenerated-5767>:2: RuntimeWarning: divide by zero encountered in log
  return x + (x + log(x**6*(2*x + exp(_a4_*cos(x)/_a0_)**x)**3))/x
<lambdifygenerated-5768>:2: RuntimeWarning: divide by zero encountered in log
  return x + (x + log(x**6*(2*x + exp(_a4_*cos(x)/_a0_)**x)**3))/x
<lambdifygenerated-5769>:2: RuntimeWarning: divide by zero encountered in log
  return x + (x + log(x**6*(2*x + exp(_a4_*cos(_a5_)/_a0_)**x)**3))/x
<lambdifygenerated-5770>:2: RuntimeWarning: divide by zero encountered in log
  return x + (x + log(x**6*(2*x + exp(_a4_*cos(_a5_)/_a0_)**x)**3))/x
<lambdifygenerated-5771>:2: RuntimeWarning: divide by zero encountered in log
  return x + (x + log(x**6*(2*x + exp(_a4_*cos(_a5_)/_a0_)**x)**3))/x
<lambdifygenerated-5772>:2: RuntimeWarning: divide by zero encountered in log
  return x + (x + log(x**6*(2*x + exp(_a4_*cos(_a5_)/_a0_)**x)**3))/x
<lambdifygenerated-5773>:2: RuntimeWarning: divide by zero encountered in log
  return x + (x + log(x**6*(_a6_ + x + exp(_a4_*cos(_a5_)/_a0_)**x)**3))/x
<lambdifygenerated-5774>:2: RuntimeWarning: divide by zero encountered in log
  return x + (x + log(x**6*(_a6_ + x + exp(_a4_*cos(_a5_)/_a0_)**x)**3))/x
<lambdifygenerated-5775>:2: RuntimeWarning: divide by zero encountered in log
  return x + (x + log(x**6*(_a6_ + x**x + exp(_a4_*cos(_a5_)/_a0_)**x)**3))/x
<lambdifygenerated-5776>:2: RuntimeWarning: divide by zero encountered in log
  return x + (x + log(x**6*(_a6_ + x**x + exp(_a4_*cos(_a5_)/_a0_)**x)**3))/x
<lambdifygenerated-5777>:2: RuntimeWarning: divide by zero encountered in log
  return x + (x + log(x**6*(_a6_ + (x**2)**x + exp(_a4_*cos(_a5_)/_a0_)**x)**3))/x
<lambdifygenerated-5778>:2: RuntimeWarning: divide by zero encountered in log
  return x + (x + log(x**6*(_a6_ + (x**2)**x + exp(_a4_*cos(_a5_)/_a0_)**x)**3))/x
<lambdifygenerated-5779>:2: RuntimeWarning: divide by zero encountered in log
  return x + (x + log(x**6*(_a6_ + (x**2)**x + exp(_a4_*cos(_a5_)/_a0_)**x)**3))/x
<lambdifygenerated-5780>:2: RuntimeWarning: divide by zero encountered in log
  return x + (x + log(x**6*(_a6_ + (x**2)**x + exp(_a4_*cos(_a5_)/_a0_)**x)**3))/x
<lambdifygenerated-5781>:2: RuntimeWarning: divide by zero encountered in log
  return x + (x + log(x**6*(_a6_ + (_a1_*x)**x + exp(_a4_*cos(_a5_)/_a0_)**x)**3))/x
<lambdifygenerated-5782>:2: RuntimeWarning: divide by zero encountered in log
  return x + (x + log(x**6*(_a6_ + (_a1_*x)**x + exp(_a4_*cos(_a5_)/_a0_)**x)**3))/x
<lambdifygenerated-5783>:2: RuntimeWarning: divide by zero encountered in log
  return x + (x + log(x**6*(_a6_ + (_a1_*x)**(2*x) + exp(_a4_*cos(_a5_)/_a0_)**x)**3))/x
<lambdifygenerated-5784>:2: RuntimeWarning: divide by zero encountered in log
  return x + (x + log(x**6*(_a6_ + (_a1_*x)**(2*x) + exp(_a4_*cos(_a5_)/_a0_)**x)**3))/x
<lambdifygenerated-5785>:2: RuntimeWarning: divide by zero encountered in log
  return x + (x + log(x**6*(_a6_ + (_a1_*x)**(_a7_ + x) + exp(_a4_*cos(_a5_)/_a0_)**x)**3))/x
<lambdifygenerated-5786>:2: RuntimeWarning: divide by zero encountered in log
  return x + (x + log(x**6*(_a6_ + (_a1_*x)**(_a7_ + x) + exp(_a4_*cos(_a5_)/_a0_)**x)**3))/x
<lambdifygenerated-5787>:2: RuntimeWarning: divide by zero encountered in log
  return x + (x + log(x**6*(_a6_ + (_a1_*x)**(_a3_ + _a7_) + exp(_a4_*cos(_a5_)/_a0_)**x)**3))/x
<lambdifygenerated-5788>:2: RuntimeWarning: divide by zero encountered in log
  return x + (x + log(x**6*(_a6_ + (_a1_*x)**(_a3_ + _a7_) + exp(_a4_*cos(_a5_)/_a0_)**x)**3))/x
<lambdifygenerated-5789>:2: RuntimeWarning: divide by zero encountered in log
  return x + (x + log(_a2_**3*x**3*(_a6_ + (_a1_*x)**(_a3_ + _a7_) + exp(_a4_*cos(_a5_)/_a0_)**x)**3))/x
<lambdifygenerated-5790>:2: RuntimeWarning: divide by zero encountered in log
  return x + (x + log(_a2_**3*x**3*(_a6_ + (_a1_*x)**(_a3_ + _a7_) + exp(_a4_*cos(_a5_)/_a0_)**x)**3))/x
<lambdifygenerated-5791>:2: RuntimeWarning: invalid value encountered in log
  return x + (x + log(_a2_**3*(_a6_ + (_a1_*x)**(_a3_ + _a7_) + exp(_a4_*cos(_a5_)/_a0_)**x)**3*cos(x)**3))/x
<lambdifygenerated-5791>:2: RuntimeWarning: divide by zero encountered in divide
  return x + (x + log(_a2_**3*(_a6_ + (_a1_*x)**(_a3_ + _a7_) + exp(_a4_*cos(_a5_)/_a0_)**x)**3*cos(x)**3))/x
<lambdifygenerated-5792>:2: RuntimeWarning: invalid value encountered in log
  return x + (x + log(_a2_**3*(_a6_ + (_a1_*x)**(_a3_ + _a7_) + exp(_a4_*cos(_a5_)/_a0_)**x)**3*cos(x)**3))/x
<lambdifygenerated-5792>:2: RuntimeWarning: divide by zero encountered in divide
  return x + (x + log(_a2_**3*(_a6_ + (_a1_*x)**(_a3_ + _a7_) + exp(_a4_*cos(_a5_)/_a0_)**x)**3*cos(x)**3))/x
<lambdifygenerated-5793>:2: RuntimeWarning: divide by zero encountered in divide
  return x + (x + log(_a2_**3*(_a6_ + (_a1_*x)**(_a3_ + _a7_) + exp(_a4_*cos(_a5_)/_a0_)**x)**3*cos(1)**3))/x
<lambdifygenerated-5794>:2: RuntimeWarning: divide by zero encountered in divide
  return x + (x + log(_a2_**3*(_a6_ + (_a1_*x)**(_a3_ + _a7_) + exp(_a4_*cos(_a5_)/_a0_)**x)**3*cos(1)**3))/x
<lambdifygenerated-5795>:2: RuntimeWarning: divide by zero encountered in divide
  return x + (x + log(_a2_**3*(_a6_ + (_a1_*x)**(_a3_ + _a7_) + exp(_a4_*cos(_a5_)/_a0_)**x)**3*cos(x**x/x)**3))/x
<lambdifygenerated-5795>:2: RuntimeWarning: invalid value encountered in cos
  return x + (x + log(_a2_**3*(_a6_ + (_a1_*x)**(_a3_ + _a7_) + exp(_a4_*cos(_a5_)/_a0_)**x)**3*cos(x**x/x)**3))/x
<lambdifygenerated-5795>:2: RuntimeWarning: invalid value encountered in log
  return x + (x + log(_a2_**3*(_a6_ + (_a1_*x)**(_a3_ + _a7_) + exp(_a4_*cos(_a5_)/_a0_)**x)**3*cos(x**x/x)**3))/x
<lambdifygenerated-5796>:2: RuntimeWarning: divide by zero encountered in divide
  return x + (x + log(_a2_**3*(_a6_ + (_a1_*x)**(_a3_ + _a7_) + exp(_a4_*cos(_a5_)/_a0_)**x)**3*cos(x**x/x)**3))/x
<lambdifygenerated-5796>:2: RuntimeWarning: invalid value encountered in cos
  return x + (x + log(_a2_**3*(_a6_ + (_a1_*x)**(_a3_ + _a7_) + exp(_a4_*cos(_a5_)/_a0_)**x)**3*cos(x**x/x)**3))/x
<lambdifygenerated-5796>:2: RuntimeWarning: invalid value encountered in log
  return x + (x + log(_a2_**3*(_a6_ + (_a1_*x)**(_a3_ + _a7_) + exp(_a4_*cos(_a5_)/_a0_)**x)**3*cos(x**x/x)**3))/x
<lambdifygenerated-5797>:2: RuntimeWarning: divide by zero encountered in divide
  return x + (x + log(_a2_**3*(_a6_ + (_a1_*x)**(_a3_ + _a7_) + exp(_a4_*cos(_a5_)/_a0_)**x)**3*cos(x**x/x)**3))/x
<lambdifygenerated-5797>:2: RuntimeWarning: invalid value encountered in cos
  return x + (x + log(_a2_**3*(_a6_ + (_a1_*x)**(_a3_ + _a7_) + exp(_a4_*cos(_a5_)/_a0_)**x)**3*cos(x**x/x)**3))/x
<lambdifygenerated-5797>:2: RuntimeWarning: invalid value encountered in log
  return x + (x + log(_a2_**3*(_a6_ + (_a1_*x)**(_a3_ + _a7_) + exp(_a4_*cos(_a5_)/_a0_)**x)**3*cos(x**x/x)**3))/x
<lambdifygenerated-5798>:2: RuntimeWarning: divide by zero encountered in divide
  return x + (x + log(_a2_**3*(_a6_ + (_a1_*x)**(_a3_ + _a7_) + exp(_a4_*cos(_a5_)/_a0_)**x)**3*cos(x**x/x)**3))/x
<lambdifygenerated-5798>:2: RuntimeWarning: invalid value encountered in cos
  return x + (x + log(_a2_**3*(_a6_ + (_a1_*x)**(_a3_ + _a7_) + exp(_a4_*cos(_a5_)/_a0_)**x)**3*cos(x**x/x)**3))/x
<lambdifygenerated-5798>:2: RuntimeWarning: invalid value encountered in log
  return x + (x + log(_a2_**3*(_a6_ + (_a1_*x)**(_a3_ + _a7_) + exp(_a4_*cos(_a5_)/_a0_)**x)**3*cos(x**x/x)**3))/x
<lambdifygenerated-5799>:2: RuntimeWarning: divide by zero encountered in divide
  return x + (x + log(_a2_**3*(_a6_ + (_a1_*x)**(_a3_ + _a7_) + exp(_a4_*cos(_a5_)/_a0_)**x)**3*cos((x**x)**x/x)**3))/x
<lambdifygenerated-5799>:2: RuntimeWarning: invalid value encountered in cos
  return x + (x + log(_a2_**3*(_a6_ + (_a1_*x)**(_a3_ + _a7_) + exp(_a4_*cos(_a5_)/_a0_)**x)**3*cos((x**x)**x/x)**3))/x
<lambdifygenerated-5799>:2: RuntimeWarning: invalid value encountered in log
  return x + (x + log(_a2_**3*(_a6_ + (_a1_*x)**(_a3_ + _a7_) + exp(_a4_*cos(_a5_)/_a0_)**x)**3*cos((x**x)**x/x)**3))/x
<lambdifygenerated-5800>:2: RuntimeWarning: divide by zero encountered in divide
  return x + (x + log(_a2_**3*(_a6_ + (_a1_*x)**(_a3_ + _a7_) + exp(_a4_*cos(_a5_)/_a0_)**x)**3*cos((x**x)**x/x)**3))/x
<lambdifygenerated-5800>:2: RuntimeWarning: invalid value encountered in cos
  return x + (x + log(_a2_**3*(_a6_ + (_a1_*x)**(_a3_ + _a7_) + exp(_a4_*cos(_a5_)/_a0_)**x)**3*cos((x**x)**x/x)**3))/x
<lambdifygenerated-5800>:2: RuntimeWarning: invalid value encountered in log
  return x + (x + log(_a2_**3*(_a6_ + (_a1_*x)**(_a3_ + _a7_) + exp(_a4_*cos(_a5_)/_a0_)**x)**3*cos((x**x)**x/x)**3))/x
<lambdifygenerated-5801>:2: RuntimeWarning: divide by zero encountered in divide
  return x + (x + log(_a2_**3*(_a6_ + (_a1_*x)**(_a3_ + _a7_) + exp(_a4_*cos(_a5_)/_a0_)**x)**3*cos(((x**x)**x)**x/x)**3))/x
<lambdifygenerated-5801>:2: RuntimeWarning: invalid value encountered in cos
  return x + (x + log(_a2_**3*(_a6_ + (_a1_*x)**(_a3_ + _a7_) + exp(_a4_*cos(_a5_)/_a0_)**x)**3*cos(((x**x)**x)**x/x)**3))/x
<lambdifygenerated-5801>:2: RuntimeWarning: invalid value encountered in log
  return x + (x + log(_a2_**3*(_a6_ + (_a1_*x)**(_a3_ + _a7_) + exp(_a4_*cos(_a5_)/_a0_)**x)**3*cos(((x**x)**x)**x/x)**3))/x
<lambdifygenerated-5802>:2: RuntimeWarning: divide by zero encountered in divide
  return x + (x + log(_a2_**3*(_a6_ + (_a1_*x)**(_a3_ + _a7_) + exp(_a4_*cos(_a5_)/_a0_)**x)**3*cos(((x**x)**x)**x/x)**3))/x
<lambdifygenerated-5802>:2: RuntimeWarning: invalid value encountered in cos
  return x + (x + log(_a2_**3*(_a6_ + (_a1_*x)**(_a3_ + _a7_) + exp(_a4_*cos(_a5_)/_a0_)**x)**3*cos(((x**x)**x)**x/x)**3))/x
<lambdifygenerated-5802>:2: RuntimeWarning: invalid value encountered in log
  return x + (x + log(_a2_**3*(_a6_ + (_a1_*x)**(_a3_ + _a7_) + exp(_a4_*cos(_a5_)/_a0_)**x)**3*cos(((x**x)**x)**x/x)**3))/x
<lambdifygenerated-5803>:2: RuntimeWarning: divide by zero encountered in divide
  return x + (x + log(_a2_**3*(_a6_ + (_a1_*x)**(_a3_ + _a7_) + exp(_a4_*cos(_a5_)/_a0_)**x)**3*cos((((x**3)**x)**x)**x/x)**3))/x
<lambdifygenerated-5803>:2: RuntimeWarning: invalid value encountered in cos
  return x + (x + log(_a2_**3*(_a6_ + (_a1_*x)**(_a3_ + _a7_) + exp(_a4_*cos(_a5_)/_a0_)**x)**3*cos((((x**3)**x)**x)**x/x)**3))/x
<lambdifygenerated-5803>:2: RuntimeWarning: invalid value encountered in log
  return x + (x + log(_a2_**3*(_a6_ + (_a1_*x)**(_a3_ + _a7_) + exp(_a4_*cos(_a5_)/_a0_)**x)**3*cos((((x**3)**x)**x)**x/x)**3))/x
<lambdifygenerated-5804>:2: RuntimeWarning: divide by zero encountered in divide
  return x + (x + log(_a2_**3*(_a6_ + (_a1_*x)**(_a3_ + _a7_) + exp(_a4_*cos(_a5_)/_a0_)**x)**3*cos((((x**3)**x)**x)**x/x)**3))/x
<lambdifygenerated-5804>:2: RuntimeWarning: invalid value encountered in cos
  return x + (x + log(_a2_**3*(_a6_ + (_a1_*x)**(_a3_ + _a7_) + exp(_a4_*cos(_a5_)/_a0_)**x)**3*cos((((x**3)**x)**x)**x/x)**3))/x
<lambdifygenerated-5804>:2: RuntimeWarning: invalid value encountered in log
  return x + (x + log(_a2_**3*(_a6_ + (_a1_*x)**(_a3_ + _a7_) + exp(_a4_*cos(_a5_)/_a0_)**x)**3*cos((((x**3)**x)**x)**x/x)**3))/x
<lambdifygenerated-5805>:2: RuntimeWarning: divide by zero encountered in divide
  return x + (x + log(_a2_**3*(_a6_ + (_a1_*x)**(_a3_ + _a7_) + exp(_a4_*cos(_a5_)/_a0_)**x)**3*cos((((_a3_**3)**x)**x)**x/x)**3))/x
<lambdifygenerated-5805>:2: RuntimeWarning: invalid value encountered in cos
  return x + (x + log(_a2_**3*(_a6_ + (_a1_*x)**(_a3_ + _a7_) + exp(_a4_*cos(_a5_)/_a0_)**x)**3*cos((((_a3_**3)**x)**x)**x/x)**3))/x
<lambdifygenerated-5805>:2: RuntimeWarning: invalid value encountered in log
  return x + (x + log(_a2_**3*(_a6_ + (_a1_*x)**(_a3_ + _a7_) + exp(_a4_*cos(_a5_)/_a0_)**x)**3*cos((((_a3_**3)**x)**x)**x/x)**3))/x
<lambdifygenerated-5806>:2: RuntimeWarning: divide by zero encountered in divide
  return x + (x + log(_a2_**3*(_a6_ + (_a1_*x)**(_a3_ + _a7_) + exp(_a4_*cos(_a5_)/_a0_)**x)**3*cos((((_a3_**3)**x)**x)**x/x)**3))/x
<lambdifygenerated-5806>:2: RuntimeWarning: invalid value encountered in cos
  return x + (x + log(_a2_**3*(_a6_ + (_a1_*x)**(_a3_ + _a7_) + exp(_a4_*cos(_a5_)/_a0_)**x)**3*cos((((_a3_**3)**x)**x)**x/x)**3))/x
<lambdifygenerated-5806>:2: RuntimeWarning: invalid value encountered in log
  return x + (x + log(_a2_**3*(_a6_ + (_a1_*x)**(_a3_ + _a7_) + exp(_a4_*cos(_a5_)/_a0_)**x)**3*cos((((_a3_**3)**x)**x)**x/x)**3))/x
<lambdifygenerated-5807>:2: RuntimeWarning: divide by zero encountered in divide
  return x + (x + log(_a2_**3*(_a6_ + (_a1_*x)**(_a3_ + _a7_) + exp(_a4_*cos(_a5_)/_a0_)**x)**3*cos((((_a3_**3)**(x**x))**x)**x/x)**3))/x
<lambdifygenerated-5807>:2: RuntimeWarning: invalid value encountered in cos
  return x + (x + log(_a2_**3*(_a6_ + (_a1_*x)**(_a3_ + _a7_) + exp(_a4_*cos(_a5_)/_a0_)**x)**3*cos((((_a3_**3)**(x**x))**x)**x/x)**3))/x
<lambdifygenerated-5807>:2: RuntimeWarning: invalid value encountered in log
  return x + (x + log(_a2_**3*(_a6_ + (_a1_*x)**(_a3_ + _a7_) + exp(_a4_*cos(_a5_)/_a0_)**x)**3*cos((((_a3_**3)**(x**x))**x)**x/x)**3))/x
<lambdifygenerated-5808>:2: RuntimeWarning: divide by zero encountered in divide
  return x + (x + log(_a2_**3*(_a6_ + (_a1_*x)**(_a3_ + _a7_) + exp(_a4_*cos(_a5_)/_a0_)**x)**3*cos((((_a3_**3)**(x**x))**x)**x/x)**3))/x
<lambdifygenerated-5808>:2: RuntimeWarning: invalid value encountered in cos
  return x + (x + log(_a2_**3*(_a6_ + (_a1_*x)**(_a3_ + _a7_) + exp(_a4_*cos(_a5_)/_a0_)**x)**3*cos((((_a3_**3)**(x**x))**x)**x/x)**3))/x
<lambdifygenerated-5808>:2: RuntimeWarning: invalid value encountered in log
  return x + (x + log(_a2_**3*(_a6_ + (_a1_*x)**(_a3_ + _a7_) + exp(_a4_*cos(_a5_)/_a0_)**x)**3*cos((((_a3_**3)**(x**x))**x)**x/x)**3))/x
<lambdifygenerated-5809>:2: RuntimeWarning: divide by zero encountered in divide
  return x + (x + log(_a2_**3*(_a6_ + (_a1_*x)**(_a3_ + _a7_) + exp(_a4_*cos(_a5_)/_a0_)**x)**3*cos((((_a3_**3)**(_a6_**x))**x)**x/x)**3))/x
<lambdifygenerated-5809>:2: RuntimeWarning: invalid value encountered in cos
  return x + (x + log(_a2_**3*(_a6_ + (_a1_*x)**(_a3_ + _a7_) + exp(_a4_*cos(_a5_)/_a0_)**x)**3*cos((((_a3_**3)**(_a6_**x))**x)**x/x)**3))/x
<lambdifygenerated-5809>:2: RuntimeWarning: invalid value encountered in log
  return x + (x + log(_a2_**3*(_a6_ + (_a1_*x)**(_a3_ + _a7_) + exp(_a4_*cos(_a5_)/_a0_)**x)**3*cos((((_a3_**3)**(_a6_**x))**x)**x/x)**3))/x
<lambdifygenerated-5810>:2: RuntimeWarning: divide by zero encountered in divide
  return x + (x + log(_a2_**3*(_a6_ + (_a1_*x)**(_a3_ + _a7_) + exp(_a4_*cos(_a5_)/_a0_)**x)**3*cos((((_a3_**3)**(_a6_**x))**x)**x/x)**3))/x
<lambdifygenerated-5810>:2: RuntimeWarning: invalid value encountered in cos
  return x + (x + log(_a2_**3*(_a6_ + (_a1_*x)**(_a3_ + _a7_) + exp(_a4_*cos(_a5_)/_a0_)**x)**3*cos((((_a3_**3)**(_a6_**x))**x)**x/x)**3))/x
<lambdifygenerated-5810>:2: RuntimeWarning: invalid value encountered in log
  return x + (x + log(_a2_**3*(_a6_ + (_a1_*x)**(_a3_ + _a7_) + exp(_a4_*cos(_a5_)/_a0_)**x)**3*cos((((_a3_**3)**(_a6_**x))**x)**x/x)**3))/x
<lambdifygenerated-5811>:2: RuntimeWarning: divide by zero encountered in divide
  return x + (x + log(_a2_**3*(_a6_ + (_a1_*x)**(_a3_ + _a7_) + exp(_a4_*cos(_a5_)/_a0_)**x)**3*cos((((_a3_**3)**(_a6_**x))**x)**x/x)**3))/x
<lambdifygenerated-5811>:2: RuntimeWarning: invalid value encountered in cos
  return x + (x + log(_a2_**3*(_a6_ + (_a1_*x)**(_a3_ + _a7_) + exp(_a4_*cos(_a5_)/_a0_)**x)**3*cos((((_a3_**3)**(_a6_**x))**x)**x/x)**3))/x
<lambdifygenerated-5811>:2: RuntimeWarning: invalid value encountered in log
  return x + (x + log(_a2_**3*(_a6_ + (_a1_*x)**(_a3_ + _a7_) + exp(_a4_*cos(_a5_)/_a0_)**x)**3*cos((((_a3_**3)**(_a6_**x))**x)**x/x)**3))/x
<lambdifygenerated-5812>:2: RuntimeWarning: divide by zero encountered in divide
  return x + (x + log(_a2_**3*(_a6_ + (_a1_*x)**(_a3_ + _a7_) + exp(_a4_*cos(_a5_)/_a0_)**x)**3*cos((((_a3_**3)**(_a6_**x))**x)**x/x)**3))/x
<lambdifygenerated-5812>:2: RuntimeWarning: invalid value encountered in cos
  return x + (x + log(_a2_**3*(_a6_ + (_a1_*x)**(_a3_ + _a7_) + exp(_a4_*cos(_a5_)/_a0_)**x)**3*cos((((_a3_**3)**(_a6_**x))**x)**x/x)**3))/x
<lambdifygenerated-5812>:2: RuntimeWarning: invalid value encountered in log

         x    y         z  rep    zmodel      zbms
1    0.005  0.0  0.602421    7  0.593360  0.602421
2    0.010  0.0  0.606031    7  0.597488  0.606031
3    0.015  0.0  0.609667    7  0.601631  0.609667
4    0.020  0.0  0.613329    7  0.605790  0.613329
6    0.030  0.0  0.620731    7  0.614157  0.620731
..     ...  ...       ...  ...       ...       ...
394  1.970  0.0  2.859892    7  2.764097  2.859892
396  1.980  0.0  2.870450    7  2.771651  2.870450
397  1.985  0.0  2.875718    7  2.775401  2.875718
398  1.990  0.0  2.880980    7  2.779133  2.880980
399  1.995  0.0  2.886235    7  2.782848  2.886235

[320 rows x 6 columns]

300

<lambdifygenerated-5847>:2: RuntimeWarning: divide by zero encountered in power
  return _a1_*x**_a7_ + x

         x    y         z  rep    zmodel      zbms
1    0.005  0.0  0.602421    7  0.596043  0.606473
2    0.010  0.0  0.606031    7  0.600223  0.609503
3    0.015  0.0  0.609667    7  0.604420  0.612778
4    0.020  0.0  0.613329    7  0.608635  0.616224
6    0.030  0.0  0.620731    7  0.617116  0.623488
..     ...  ...       ...  ...       ...       ...
394  1.970  0.0  2.859892    7  2.691398  2.994923
396  1.980  0.0  2.870450    7  2.698182  3.008875
397  1.985  0.0  2.875718    7  2.701550  3.015855
398  1.990  0.0  2.880980    7  2.704902  3.022838
399  1.995  0.0  2.886235    7  2.708240  3.029824

[320 rows x 6 columns]

300

         x    y         z  rep    zmodel      zbms
1    0.005  0.0  0.602421    7  0.586414  0.588594
2    0.010  0.0  0.606031    7  0.590672  0.592582
3    0.015  0.0  0.609667    7  0.594946  0.596595
4    0.020  0.0  0.613329    7  0.599238  0.600634
6    0.030  0.0  0.620731    7  0.607871  0.608785
..     ...  ...       ...  ...       ...       ...
394  1.970  0.0  2.859892    7  2.727093  2.721750
396  1.980  0.0  2.870450    7  2.734174  2.727973
397  1.985  0.0  2.875718    7  2.737689  2.731042
398  1.990  0.0  2.880980    7  2.741188  2.734083
399  1.995  0.0  2.886235    7  2.744670  2.737095

[320 rows x 6 columns]

300

<lambdifygenerated-5885>:2: RuntimeWarning: divide by zero encountered in divide
  return _a6_/x
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/nguyen_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-5886>:2: RuntimeWarning: divide by zero encountered in divide
  return _a6_/x
<lambdifygenerated-5887>:2: RuntimeWarning: divide by zero encountered in divide
  return (1/2)*_a6_/x
<lambdifygenerated-5888>:2: RuntimeWarning: divide by zero encountered in divide
  return (1/2)*_a6_/x
<lambdifygenerated-5893>:2: RuntimeWarning: invalid value encountered in power
  return _a6_/(_a3_ + _a3_**x)

         x    y         z  rep    zmodel      zbms
1    0.005  0.0  0.602421    7  0.604379  0.603070
2    0.010  0.0  0.606031    7  0.608255  0.606905
3    0.015  0.0  0.609667    7  0.612149  0.610760
4    0.020  0.0  0.613329    7  0.616060  0.614634
6    0.030  0.0  0.620731    7  0.623937  0.622439
..     ...  ...       ...  ...       ...       ...
394  1.970  0.0  2.859892    7  2.778840  2.778678
396  1.980  0.0  2.870450    7  2.786751  2.786483
397  1.985  0.0  2.875718    7  2.790681  2.790357
398  1.990  0.0  2.880980    7  2.794592  2.794211
399  1.995  0.0  2.886235    7  2.798486  2.798047

[320 rows x 6 columns]

300

<lambdifygenerated-5913>:2: RuntimeWarning: divide by zero encountered in power
  return x*x**_a1_ + x
<lambdifygenerated-5913>:2: RuntimeWarning: invalid value encountered in multiply
  return x*x**_a1_ + x

         x    y         z  rep    zmodel      zbms
1    0.005  0.0  0.602421    7  0.575957  0.577528
2    0.010  0.0  0.606031    7  0.580495  0.580877
3    0.015  0.0  0.609667    7  0.585046  0.584464
4    0.020  0.0  0.613329    7  0.589610  0.588217
6    0.030  0.0  0.620731    7  0.598776  0.596081
..     ...  ...       ...  ...       ...       ...
394  1.970  0.0  2.859892    7  2.887911  3.014624
396  1.980  0.0  2.870450    7  2.897970  3.028652
397  1.985  0.0  2.875718    7  2.902978  3.035670
398  1.990  0.0  2.880980    7  2.907972  3.042690
399  1.995  0.0  2.886235    7  2.912951  3.049712

[320 rows x 6 columns]

300

<lambdifygenerated-5937>:2: RuntimeWarning: divide by zero encountered in power
  return x*(_a6_ + x**_a3_)
<lambdifygenerated-5937>:2: RuntimeWarning: invalid value encountered in multiply
  return x*(_a6_ + x**_a3_)

         x    y         z  rep    zmodel      zbms
1    0.005  0.0  0.602421    7  0.562368  0.578846
2    0.010  0.0  0.606031    7  0.566758  0.582148
3    0.015  0.0  0.609667    7  0.571167  0.585695
4    0.020  0.0  0.613329    7  0.575597  0.589410
6    0.030  0.0  0.620731    7  0.584516  0.597208
..     ...  ...       ...  ...       ...       ...
394  1.970  0.0  2.859892    7  2.669369  3.032711
396  1.980  0.0  2.870450    7  2.675580  3.046890
397  1.985  0.0  2.875718    7  2.678662  3.053984
398  1.990  0.0  2.880980    7  2.681729  3.061079
399  1.995  0.0  2.886235    7  2.684781  3.068178

[320 rows x 6 columns]

300

         x    y         z  rep    zmodel      zbms
1    0.005  0.0  0.602421    7  0.627329  0.619691
2    0.010  0.0  0.606031    7  0.630853  0.623725
3    0.015  0.0  0.609667    7  0.634395  0.627771
4    0.020  0.0  0.613329    7  0.637954  0.631831
6    0.030  0.0  0.620731    7  0.645128  0.639989
..     ...  ...       ...  ...       ...       ...
394  1.970  0.0  2.859892    7  2.792211  3.212710
396  1.980  0.0  2.870450    7  2.799791  3.231075
397  1.985  0.0  2.875718    7  2.803554  3.240277
398  1.990  0.0  2.880980    7  2.807297  3.249491
399  1.995  0.0  2.886235    7  2.811022  3.258719

[320 rows x 6 columns]

300

<lambdifygenerated-5979>:2: RuntimeWarning: divide by zero encountered in power
  return x*(_a2_ + x**_a5_)
<lambdifygenerated-5979>:2: RuntimeWarning: invalid value encountered in multiply
  return x*(_a2_ + x**_a5_)

         x    y         z  rep    zmodel      zbms
1    0.005  0.0  0.602421    7  0.595608  0.572127
2    0.010  0.0  0.606031    7  0.599572  0.575455
3    0.015  0.0  0.609667    7  0.603552  0.579025
4    0.020  0.0  0.613329    7  0.607549  0.582762
6    0.030  0.0  0.620731    7  0.615595  0.590598
..     ...  ...       ...  ...       ...       ...
394  1.970  0.0  2.859892    7  2.818654  3.016361
396  1.980  0.0  2.870450    7  2.826810  3.030453
397  1.985  0.0  2.875718    7  2.830859  3.037503
398  1.990  0.0  2.880980    7  2.834889  3.044555
399  1.995  0.0  2.886235    7  2.838900  3.051610

[320 rows x 6 columns]

300

         x    y         z  rep    zmodel      zbms
1    0.005  0.0  0.602421    7  0.574360  0.535978
2    0.010  0.0  0.606031    7  0.578550  0.541328
3    0.015  0.0  0.609667    7  0.582759  0.546687
4    0.020  0.0  0.613329    7  0.586985  0.552053
6    0.030  0.0  0.620731    7  0.595492  0.562809
..     ...  ...       ...  ...       ...       ...
394  1.970  0.0  2.859892    7  2.808708  2.997828
396  1.980  0.0  2.870450    7  2.816731  3.011595
397  1.985  0.0  2.875718    7  2.820716  3.018482
398  1.990  0.0  2.880980    7  2.824684  3.025372
399  1.995  0.0  2.886235    7  2.828634  3.032263

[320 rows x 6 columns]

300

         x    y         z  rep    zmodel      zbms
1    0.005  0.0  0.602421    7  0.552408  0.537389
2    0.010  0.0  0.606031    7  0.557170  0.542729
3    0.015  0.0  0.609667    7  0.561946  0.548077
4    0.020  0.0  0.613329    7  0.566736  0.553433
6    0.030  0.0  0.620731    7  0.576360  0.564166
..     ...  ...       ...  ...       ...       ...
394  1.970  0.0  2.859892    7  2.785286  2.981744
396  1.980  0.0  2.870450    7  2.793577  2.995372
397  1.985  0.0  2.875718    7  2.797700  3.002190
398  1.990  0.0  2.880980    7  2.801808  3.009009
399  1.995  0.0  2.886235    7  2.805900  3.015831

[320 rows x 6 columns]

300

         x    y         z  rep    zmodel      zbms
1    0.005  0.0  0.602421    7  0.563158  0.514720
2    0.010  0.0  0.606031    7  0.567536  0.520731
3    0.015  0.0  0.609667    7  0.571932  0.526742
4    0.020  0.0  0.613329    7  0.576347  0.532754
6    0.030  0.0  0.620731    7  0.585231  0.544776
..     ...  ...       ...  ...       ...       ...
394  1.970  0.0  2.859892    7  2.562189  2.877113
396  1.980  0.0  2.870450    7  2.567184  2.889135
397  1.985  0.0  2.875718    7  2.569659  2.895147
398  1.990  0.0  2.880980    7  2.572120  2.901158
399  1.995  0.0  2.886235    7  2.574567  2.907169

[320 rows x 6 columns]

300

         x    y         z  rep    zmodel      zbms
1    0.005  0.0  0.602421    7  0.525578  0.487971
2    0.010  0.0  0.606031    7  0.530649  0.494081
3    0.015  0.0  0.609667    7  0.535730  0.500190
4    0.020  0.0  0.613329    7  0.540819  0.506300
6    0.030  0.0  0.620731    7  0.551023  0.518519
..     ...  ...       ...  ...       ...       ...
394  1.970  0.0  2.859892    7  2.934561  2.889060
396  1.980  0.0  2.870450    7  2.946145  2.901279
397  1.985  0.0  2.875718    7  2.951921  2.907389
398  1.990  0.0  2.880980    7  2.957686  2.913499
399  1.995  0.0  2.886235    7  2.963441  2.919608

[320 rows x 6 columns]

300

         x    y         z  rep    zmodel      zbms
1    0.005  0.0  0.602421    7  0.588350  0.532647
2    0.010  0.0  0.606031    7  0.591754  0.538009
3    0.015  0.0  0.609667    7  0.595186  0.543379
4    0.020  0.0  0.613329    7  0.598648  0.548757
6    0.030  0.0  0.620731    7  0.605659  0.559538
..     ...  ...       ...  ...       ...       ...
394  1.970  0.0  2.859892    7  2.624127  3.017727
396  1.980  0.0  2.870450    7  2.628840  3.031682
397  1.985  0.0  2.875718    7  2.631171  3.038663
398  1.990  0.0  2.880980    7  2.633486  3.045646
399  1.995  0.0  2.886235    7  2.635785  3.052632

[320 rows x 6 columns]

300

         x    y         z  rep    zmodel      zbms
1    0.005  0.0  0.602421    7  0.528850  0.512357
2    0.010  0.0  0.606031    7  0.533805  0.518443
3    0.015  0.0  0.609667    7  0.538778  0.524529
4    0.020  0.0  0.613329    7  0.543771  0.530615
6    0.030  0.0  0.620731    7  0.553812  0.542787
..     ...  ...       ...  ...       ...       ...
394  1.970  0.0  2.859892    7  2.632821  2.904170
396  1.980  0.0  2.870450    7  2.638827  2.916342
397  1.985  0.0  2.875718    7  2.641810  2.922428
398  1.990  0.0  2.880980    7  2.644779  2.928514
399  1.995  0.0  2.886235    7  2.647734  2.934600

[320 rows x 6 columns]

300

         x    y         z  rep    zmodel      zbms
1    0.005  0.0  0.602421    7  0.583749  0.512351
2    0.010  0.0  0.606031    7  0.587991  0.518395
3    0.015  0.0  0.609667    7  0.592251  0.524439
4    0.020  0.0  0.613329    7  0.596529  0.530483
6    0.030  0.0  0.620731    7  0.605137  0.542571
..     ...  ...       ...  ...       ...       ...
394  1.970  0.0  2.859892    7  2.726559  2.887681
396  1.980  0.0  2.870450    7  2.733301  2.899769
397  1.985  0.0  2.875718    7  2.736646  2.905813
398  1.990  0.0  2.880980    7  2.739973  2.911857
399  1.995  0.0  2.886235    7  2.743282  2.917901

[320 rows x 6 columns]

300

         x    y         z  rep    zmodel      zbms
1    0.005  0.0  0.602421    7  0.620540  0.551782
2    0.010  0.0  0.606031    7  0.624817  0.557093
3    0.015  0.0  0.609667    7  0.629107  0.562411
4    0.020  0.0  0.613329    7  0.633409  0.567735
6    0.030  0.0  0.620731    7  0.642049  0.578403
..     ...  ...       ...  ...       ...       ...
394  1.970  0.0  2.859892    7  2.843783  2.931761
396  1.980  0.0  2.870450    7  2.853524  2.944871
397  1.985  0.0  2.875718    7  2.858372  2.951429
398  1.990  0.0  2.880980    7  2.863204  2.957989
399  1.995  0.0  2.886235    7  2.868022  2.964551

[320 rows x 6 columns]

300

         x    y         z  rep    zmodel      zbms
1    0.005  0.0  0.602421    7  0.584128  0.683950
2    0.010  0.0  0.606031    7  0.589686  0.685788
3    0.015  0.0  0.609667    7  0.595250  0.687881
4    0.020  0.0  0.613329    7  0.600819  0.690158
6    0.030  0.0  0.620731    7  0.611974  0.695134
..     ...  ...       ...  ...       ...       ...
394  1.970  0.0  2.859892    7  2.594555  3.015306
396  1.980  0.0  2.870450    7  2.601518  3.030108
397  1.985  0.0  2.875718    7  2.604984  3.037516
398  1.990  0.0  2.880980    7  2.608440  3.044928
399  1.995  0.0  2.886235    7  2.611885  3.052345

[320 rows x 6 columns]

300

         x    y         z  rep    zmodel      zbms
1    0.005  0.0  0.602421    7  0.690283  0.655767
2    0.010  0.0  0.606031    7  0.692736  0.660767
3    0.015  0.0  0.609667    7  0.695210  0.665767
4    0.020  0.0  0.613329    7  0.697705  0.670767
6    0.030  0.0  0.620731    7  0.702763  0.680767
..     ...  ...       ...  ...       ...       ...
394  1.970  0.0  2.859892    7  2.439929  2.620767
396  1.980  0.0  2.870450    7  2.442896  2.630767
397  1.985  0.0  2.875718    7  2.444359  2.635767
398  1.990  0.0  2.880980    7  2.445808  2.640767
399  1.995  0.0  2.886235    7  2.447244  2.645767

[320 rows x 6 columns]

300

         x    y         z  rep    zmodel      zbms
1    0.005  0.0  0.602421    7  0.540796  0.536999
2    0.010  0.0  0.606031    7  0.546199  0.542851
3    0.015  0.0  0.609667    7  0.551611  0.548703
4    0.020  0.0  0.613329    7  0.557034  0.554556
6    0.030  0.0  0.620731    7  0.567912  0.566260
..     ...  ...       ...  ...       ...       ...
394  1.970  0.0  2.859892    7  2.604207  2.836951
396  1.980  0.0  2.870450    7  2.610725  2.848655
397  1.985  0.0  2.875718    7  2.613964  2.854507
398  1.990  0.0  2.880980    7  2.617189  2.860360
399  1.995  0.0  2.886235    7  2.620402  2.866212

[320 rows x 6 columns]

300

         x    y         z  rep    zmodel      zbms
1    0.005  0.0  0.602421    7  0.475326  0.472486
2    0.010  0.0  0.606031    7  0.480744  0.478653
3    0.015  0.0  0.609667    7  0.486174  0.484820
4    0.020  0.0  0.613329    7  0.491613  0.490987
6    0.030  0.0  0.620731    7  0.502522  0.503321
..     ...  ...       ...  ...       ...       ...
394  1.970  0.0  2.859892    7  2.811294  2.896071
396  1.980  0.0  2.870450    7  2.820838  2.908404
397  1.985  0.0  2.875718    7  2.825593  2.914571
398  1.990  0.0  2.880980    7  2.830335  2.920738
399  1.995  0.0  2.886235    7  2.835066  2.926905

[320 rows x 6 columns]

300

         x    y         z  rep    zmodel      zbms
1    0.005  0.0  0.602421    7  0.588060  0.675345
2    0.010  0.0  0.606031    7  0.593006  0.680345
3    0.015  0.0  0.609667    7  0.597964  0.685345
4    0.020  0.0  0.613329    7  0.602933  0.690345
6    0.030  0.0  0.620731    7  0.612908  0.700345
..     ...  ...       ...  ...       ...       ...
394  1.970  0.0  2.859892    7  2.602984  2.640345
396  1.980  0.0  2.870450    7  2.609603  2.650345
397  1.985  0.0  2.875718    7  2.612893  2.655345
398  1.990  0.0  2.880980    7  2.616170  2.660345
399  1.995  0.0  2.886235    7  2.619434  2.665345

[320 rows x 6 columns]

300

         x    y         z  rep    zmodel      zbms
1    0.005  0.0  0.602421    7  0.642130  0.623610
2    0.010  0.0  0.606031    7  0.645327  0.627705
3    0.015  0.0  0.609667    7  0.648541  0.631813
4    0.020  0.0  0.613329    7  0.651774  0.635934
6    0.030  0.0  0.620731    7  0.658293  0.644217
..     ...  ...       ...  ...       ...       ...
394  1.970  0.0  2.859892    7  2.876898  3.264739
396  1.980  0.0  2.870450    7  2.884019  3.283472
397  1.985  0.0  2.875718    7  2.887538  3.292859
398  1.990  0.0  2.880980    7  2.891029  3.302259
399  1.995  0.0  2.886235    7  2.894491  3.311672

[320 rows x 6 columns]

300

         x    y         z  rep    zmodel      zbms
1    0.005  0.0  0.602421    7  0.507948  0.471372
2    0.010  0.0  0.606031    7  0.513139  0.477668
3    0.015  0.0  0.609667    7  0.518347  0.483963
4    0.020  0.0  0.613329    7  0.523570  0.490259
6    0.030  0.0  0.620731    7  0.534064  0.502850
..     ...  ...       ...  ...       ...       ...
394  1.970  0.0  2.859892    7  2.490064  2.945485
396  1.980  0.0  2.870450    7  2.495231  2.958076
397  1.985  0.0  2.875718    7  2.497795  2.964371
398  1.990  0.0  2.880980    7  2.500347  2.970667
399  1.995  0.0  2.886235    7  2.502885  2.976962

[320 rows x 6 columns]

300

         x    y         z  rep    zmodel      zbms
1    0.005  0.0  0.602421    7  0.536444  0.510468
2    0.010  0.0  0.606031    7  0.541509  0.516566
3    0.015  0.0  0.609667    7  0.546586  0.522663
4    0.020  0.0  0.613329    7  0.551674  0.528761
6    0.030  0.0  0.620731    7  0.561884  0.540956
..     ...  ...       ...  ...       ...       ...
394  1.970  0.0  2.859892    7  2.598047  2.906777
396  1.980  0.0  2.870450    7  2.604873  2.918972
397  1.985  0.0  2.875718    7  2.608266  2.925069
398  1.990  0.0  2.880980    7  2.611647  2.931167
399  1.995  0.0  2.886235    7  2.615014  2.937264

[320 rows x 6 columns]

300

         x    y         z  rep    zmodel      zbms
1    0.005  0.0  0.602421    7  0.521185  0.509644
2    0.010  0.0  0.606031    7  0.526226  0.515768
3    0.015  0.0  0.609667    7  0.531286  0.521892
4    0.020  0.0  0.613329    7  0.536365  0.528016
6    0.030  0.0  0.620731    7  0.546579  0.540264
..     ...  ...       ...  ...       ...       ...
394  1.970  0.0  2.859892    7  2.659376  2.916382
396  1.980  0.0  2.870450    7  2.665540  2.928631
397  1.985  0.0  2.875718    7  2.668601  2.934755
398  1.990  0.0  2.880980    7  2.671648  2.940879
399  1.995  0.0  2.886235    7  2.674682  2.947003

[320 rows x 6 columns]

300

         x    y         z  rep    zmodel      zbms
1    0.005  0.0  0.602421    7  0.568408  0.508056
2    0.010  0.0  0.606031    7  0.573308  0.514149
3    0.015  0.0  0.609667    7  0.578222  0.520242
4    0.020  0.0  0.613329    7  0.583149  0.526336
6    0.030  0.0  0.620731    7  0.593046  0.538523
..     ...  ...       ...  ...       ...       ...
394  1.970  0.0  2.859892    7  2.750239  2.902772
396  1.980  0.0  2.870450    7  2.758337  2.914959
397  1.985  0.0  2.875718    7  2.762366  2.921052
398  1.990  0.0  2.880980    7  2.766382  2.927146
399  1.995  0.0  2.886235    7  2.770385  2.933239

[320 rows x 6 columns]

300

         x    y         z  rep    zmodel      zbms
1    0.005  0.0  0.602421    7  0.477838  0.472187
2    0.010  0.0  0.606031    7  0.483012  0.478473
3    0.015  0.0  0.609667    7  0.488203  0.484760
4    0.020  0.0  0.613329    7  0.493410  0.491046
6    0.030  0.0  0.620731    7  0.503871  0.503618
..     ...  ...       ...  ...       ...       ...
394  1.970  0.0  2.859892    7  2.688004  2.942656
396  1.980  0.0  2.870450    7  2.693816  2.955229
397  1.985  0.0  2.875718    7  2.696697  2.961515
398  1.990  0.0  2.880980    7  2.699561  2.967801
399  1.995  0.0  2.886235    7  2.702408  2.974087

[320 rows x 6 columns]

300

         x    y         z  rep    zmodel      zbms
1    0.005  0.0  0.602421    7  0.445186  0.661408
2    0.010  0.0  0.606031    7  0.452431  0.666408
3    0.015  0.0  0.609667    7  0.459676  0.671408
4    0.020  0.0  0.613329    7  0.466921  0.676408
6    0.030  0.0  0.620731    7  0.481410  0.686408
..     ...  ...       ...  ...       ...       ...
394  1.970  0.0  2.859892    7  2.481104  2.626408
396  1.980  0.0  2.870450    7  2.486329  2.636408
397  1.985  0.0  2.875718    7  2.488926  2.641408
398  1.990  0.0  2.880980    7  2.491513  2.646408
399  1.995  0.0  2.886235    7  2.494091  2.651408

[320 rows x 6 columns]

300

         x    y         z  rep    zmodel      zbms
1    0.005  0.0  0.602421    7  0.550776  0.629527
2    0.010  0.0  0.606031    7  0.555357  0.634527
3    0.015  0.0  0.609667    7  0.559949  0.639527
4    0.020  0.0  0.613329    7  0.564552  0.644527
6    0.030  0.0  0.620731    7  0.573795  0.654527
..     ...  ...       ...  ...       ...       ...
394  1.970  0.0  2.859892    7  2.862271  2.594527
396  1.980  0.0  2.870450    7  2.872847  2.604527
397  1.985  0.0  2.875718    7  2.878117  2.609527
398  1.990  0.0  2.880980    7  2.883373  2.614527
399  1.995  0.0  2.886235    7  2.888618  2.619527

[320 rows x 6 columns]

300

         x    y         z  rep    zmodel      zbms
1    0.005  0.0  0.602421    7  0.406727  0.482577
2    0.010  0.0  0.606031    7  0.413464  0.488973
3    0.015  0.0  0.609667    7  0.420221  0.495369
4    0.020  0.0  0.613329    7  0.426997  0.501765
6    0.030  0.0  0.620731    7  0.440607  0.514557
..     ...  ...       ...  ...       ...       ...
394  1.970  0.0  2.859892    7  2.460585  2.996222
396  1.980  0.0  2.870450    7  2.463809  3.009014
397  1.985  0.0  2.875718    7  2.465404  3.015410
398  1.990  0.0  2.880980    7  2.466988  3.021806
399  1.995  0.0  2.886235    7  2.468560  3.028202

[320 rows x 6 columns]

300

         x    y         z  rep    zmodel      zbms
1    0.005  0.0  0.602421    7  0.601359  0.673532
2    0.010  0.0  0.606031    7  0.605760  0.678532
3    0.015  0.0  0.609667    7  0.610174  0.683532
4    0.020  0.0  0.613329    7  0.614601  0.688532
6    0.030  0.0  0.620731    7  0.623494  0.698532
..     ...  ...       ...  ...       ...       ...
394  1.970  0.0  2.859892    7  2.844022  2.638532
396  1.980  0.0  2.870450    7  2.853918  2.648532
397  1.985  0.0  2.875718    7  2.858847  2.653532
398  1.990  0.0  2.880980    7  2.863763  2.658532
399  1.995  0.0  2.886235    7  2.868667  2.663532

[320 rows x 6 columns]

300

        x    y         z  rep    zmodel      zbms
1    0.01  0.0  0.110905    8  0.128526  0.110905
2    0.02  0.0  0.156844    8  0.149902  0.156844
3    0.03  0.0  0.192094    8  0.170844  0.192094
4    0.04  0.0  0.221811    8  0.191358  0.221811
6    0.06  0.0  0.271662    8  0.231133  0.271662
..    ...  ...       ...  ...       ...       ...
394  3.94  0.0  2.201409    8  2.151293  2.201409
396  3.96  0.0  2.206989    8  2.155277  2.206989
397  3.97  0.0  2.209774    8  2.157256  2.209774
398  3.98  0.0  2.212555    8  2.159226  2.212555
399  3.99  0.0  2.215333    8  2.161187  2.215333

[320 rows x 6 columns]

300

        x    y         z  rep    zmodel      zbms
1    0.01  0.0  0.110905    8  0.235474  0.110905
2    0.02  0.0  0.156844    8  0.247389  0.156844
3    0.03  0.0  0.192094    8  0.259232  0.192094
4    0.04  0.0  0.221811    8  0.271004  0.221811
6    0.06  0.0  0.271662    8  0.294333  0.271662
..    ...  ...       ...  ...       ...       ...
394  3.94  0.0  2.201409    8  2.038411  2.201409
396  3.96  0.0  2.206989    8  2.041352  2.206989
397  3.97  0.0  2.209774    8  2.042814  2.209774
398  3.98  0.0  2.212555    8  2.044271  2.212555
399  3.99  0.0  2.215333    8  2.045722  2.215333

[320 rows x 6 columns]

300

        x    y         z  rep    zmodel      zbms
1    0.01  0.0  0.110905    8  0.136458  0.110905
2    0.02  0.0  0.156844    8  0.156473  0.156844
3    0.03  0.0  0.192094    8  0.176177  0.192094
4    0.04  0.0  0.221811    8  0.195571  0.221811
6    0.06  0.0  0.271662    8  0.233427  0.271662
..    ...  ...       ...  ...       ...       ...
394  3.94  0.0  2.201409    8  2.124198  2.201409
396  3.96  0.0  2.206989    8  2.127703  2.206989
397  3.97  0.0  2.209774    8  2.129442  2.209774
398  3.98  0.0  2.212555    8  2.131173  2.212555
399  3.99  0.0  2.215333    8  2.132895  2.215333

[320 rows x 6 columns]

300

        x    y         z  rep    zmodel      zbms
1    0.01  0.0  0.110905    8  0.189647  0.110905
2    0.02  0.0  0.156844    8  0.205226  0.156843
3    0.03  0.0  0.192094    8  0.220623  0.192093
4    0.04  0.0  0.221811    8  0.235839  0.221810
6    0.06  0.0  0.271662    8  0.265736  0.271661
..    ...  ...       ...  ...       ...       ...
394  3.94  0.0  2.201409    8  2.152584  2.201403
396  3.96  0.0  2.206989    8  2.157155  2.206983
397  3.97  0.0  2.209774    8  2.159431  2.209768
398  3.98  0.0  2.212555    8  2.161699  2.212549
399  3.99  0.0  2.215333    8  2.163960  2.215327

[320 rows x 6 columns]

300

        x    y         z  rep    zmodel      zbms
1    0.01  0.0  0.110905    8  0.222098  0.110368
2    0.02  0.0  0.156844    8  0.234706  0.156083
3    0.03  0.0  0.192094    8  0.247220  0.191162
4    0.04  0.0  0.221811    8  0.259641  0.220735
6    0.06  0.0  0.271662    8  0.284204  0.270345
..    ...  ...       ...  ...       ...       ...
394  3.94  0.0  2.201409    8  2.086272  2.190736
396  3.96  0.0  2.206989    8  2.090158  2.196289
397  3.97  0.0  2.209774    8  2.092093  2.199060
398  3.98  0.0  2.212555    8  2.094024  2.201828
399  3.99  0.0  2.215333    8  2.095949  2.204593

[320 rows x 6 columns]

300

        x    y         z  rep    zmodel      zbms
1    0.01  0.0  0.110905    8  0.140179  0.110750
2    0.02  0.0  0.156844    8  0.159248  0.156624
3    0.03  0.0  0.192094    8  0.177999  0.191824
4    0.04  0.0  0.221811    8  0.196438  0.221499
6    0.06  0.0  0.271662    8  0.232394  0.271280
..    ...  ...       ...  ...       ...       ...
394  3.94  0.0  2.201409    8  2.224623  2.198320
396  3.96  0.0  2.206989    8  2.230198  2.203892
397  3.97  0.0  2.209774    8  2.232974  2.206673
398  3.98  0.0  2.212555    8  2.235743  2.209450
399  3.99  0.0  2.215333    8  2.238505  2.212224

[320 rows x 6 columns]

300

        x    y         z  rep    zmodel      zbms
1    0.01  0.0  0.110905    8  0.183252  0.111419
2    0.02  0.0  0.156844    8  0.198145  0.157571
3    0.03  0.0  0.192094    8  0.212893  0.192984
4    0.04  0.0  0.221811    8  0.227497  0.222839
6    0.06  0.0  0.271662    8  0.256277  0.272921
..    ...  ...       ...  ...       ...       ...
394  3.94  0.0  2.201409    8  2.186598  2.211612
396  3.96  0.0  2.206989    8  2.191927  2.217218
397  3.97  0.0  2.209774    8  2.194585  2.220016
398  3.98  0.0  2.212555    8  2.197239  2.222810
399  3.99  0.0  2.215333    8  2.199889  2.225601

[320 rows x 6 columns]

300

        x    y         z  rep    zmodel      zbms
1    0.01  0.0  0.110905    8  0.084194  0.111119
2    0.02  0.0  0.156844    8  0.107411  0.157146
3    0.03  0.0  0.192094    8  0.130194  0.192464
4    0.04  0.0  0.221811    8  0.152546  0.222238
6    0.06  0.0  0.271662    8  0.195972  0.272185
..    ...  ...       ...  ...       ...       ...
394  3.94  0.0  2.201409    8  2.199695  2.205653
396  3.96  0.0  2.206989    8  2.204447  2.211244
397  3.97  0.0  2.209774    8  2.206809  2.214034
398  3.98  0.0  2.212555    8  2.209161  2.216821
399  3.99  0.0  2.215333    8  2.211505  2.219604

[320 rows x 6 columns]

300

        x    y         z  rep    zmodel      zbms
1    0.01  0.0  0.110905    8  0.163408  0.110611
2    0.02  0.0  0.156844    8  0.179208  0.156427
3    0.03  0.0  0.192094    8  0.194822  0.191584
4    0.04  0.0  0.221811    8  0.210252  0.221222
6    0.06  0.0  0.271662    8  0.240567  0.270940
..    ...  ...       ...  ...       ...       ...
394  3.94  0.0  2.201409    8  2.168178  2.195564
396  3.96  0.0  2.206989    8  2.172741  2.201129
397  3.97  0.0  2.209774    8  2.175011  2.203907
398  3.98  0.0  2.212555    8  2.177272  2.206681
399  3.99  0.0  2.215333    8  2.179526  2.209451

[320 rows x 6 columns]

300

        x    y         z  rep    zmodel      zbms
1    0.01  0.0  0.110905    8  0.241322  0.111011
2    0.02  0.0  0.156844    8  0.253711  0.156993
3    0.03  0.0  0.192094    8  0.266011  0.192277
4    0.04  0.0  0.221811    8  0.278223  0.222022
6    0.06  0.0  0.271662    8  0.302382  0.271921
..    ...  ...       ...  ...       ...       ...
394  3.94  0.0  2.201409    8  2.061263  2.203508
396  3.96  0.0  2.206989    8  2.064543  2.209093
397  3.97  0.0  2.209774    8  2.066173  2.211881
398  3.98  0.0  2.212555    8  2.067798  2.214665
399  3.99  0.0  2.215333    8  2.069416  2.217445

[320 rows x 6 columns]

300

        x    y         z  rep    zmodel      zbms
1    0.01  0.0  0.110905    8  0.259956  0.111095
2    0.02  0.0  0.156844    8  0.271778  0.157113
3    0.03  0.0  0.192094    8  0.283521  0.192423
4    0.04  0.0  0.221811    8  0.295185  0.222191
6    0.06  0.0  0.271662    8  0.318279  0.272127
..    ...  ...       ...  ...       ...       ...
394  3.94  0.0  2.201409    8  2.065043  2.205181
396  3.96  0.0  2.206989    8  2.068321  2.210770
397  3.97  0.0  2.209774    8  2.069950  2.213560
398  3.98  0.0  2.212555    8  2.071574  2.216346
399  3.99  0.0  2.215333    8  2.073191  2.219129

[320 rows x 6 columns]

300

        x    y         z  rep    zmodel      zbms
1    0.01  0.0  0.110905    8  0.235896  0.111303
2    0.02  0.0  0.156844    8  0.248800  0.157406
3    0.03  0.0  0.192094    8  0.261594  0.192782
4    0.04  0.0  0.221811    8  0.274279  0.222606
6    0.06  0.0  0.271662    8  0.299322  0.272635
..    ...  ...       ...  ...       ...       ...
394  3.94  0.0  2.201409    8  2.095500  2.209297
396  3.96  0.0  2.206989    8  2.099182  2.214897
397  3.97  0.0  2.209774    8  2.101014  2.217692
398  3.98  0.0  2.212555    8  2.102840  2.220484
399  3.99  0.0  2.215333    8  2.104660  2.223271

[320 rows x 6 columns]

300

        x    y         z  rep    zmodel      zbms
1    0.01  0.0  0.110905    8  0.216992  0.110649
2    0.02  0.0  0.156844    8  0.229925  0.156481
3    0.03  0.0  0.192094    8  0.242746  0.191650
4    0.04  0.0  0.221811    8  0.255454  0.221298
6    0.06  0.0  0.271662    8  0.280540  0.271034
..    ...  ...       ...  ...       ...       ...
394  3.94  0.0  2.201409    8  2.157108  2.196320
396  3.96  0.0  2.206989    8  2.161836  2.201888
397  3.97  0.0  2.209774    8  2.164193  2.204666
398  3.98  0.0  2.212555    8  2.166546  2.207441
399  3.99  0.0  2.215333    8  2.168893  2.210212

[320 rows x 6 columns]

300

        x    y         z  rep    zmodel      zbms
1    0.01  0.0  0.110905    8  0.386688  0.110207
2    0.02  0.0  0.156844    8  0.393167  0.155856
3    0.03  0.0  0.192094    8  0.399650  0.190884
4    0.04  0.0  0.221811    8  0.406136  0.220414
6    0.06  0.0  0.271662    8  0.419117  0.269951
..    ...  ...       ...  ...       ...       ...
394  3.94  0.0  2.201409    8  2.177762  2.187545
396  3.96  0.0  2.206989    8  2.181665  2.193090
397  3.97  0.0  2.209774    8  2.183602  2.195858
398  3.98  0.0  2.212555    8  2.185530  2.198621
399  3.99  0.0  2.215333    8  2.187449  2.201382

[320 rows x 6 columns]

300

        x    y         z  rep    zmodel      zbms
1    0.01  0.0  0.110905    8  0.253309  0.111026
2    0.02  0.0  0.156844    8  0.264938  0.157015
3    0.03  0.0  0.192094    8  0.276500  0.192303
4    0.04  0.0  0.221811    8  0.287994  0.222052
6    0.06  0.0  0.271662    8  0.310781  0.271957
..    ...  ...       ...  ...       ...       ...
394  3.94  0.0  2.201409    8  2.030457  2.203805
396  3.96  0.0  2.206989    8  2.033490  2.209391
397  3.97  0.0  2.209774    8  2.034998  2.212179
398  3.98  0.0  2.212555    8  2.036502  2.214963
399  3.99  0.0  2.215333    8  2.038000  2.217744

[320 rows x 6 columns]

300

        x    y         z  rep    zmodel      zbms
1    0.01  0.0  0.110905    8  0.268569  0.111041
2    0.02  0.0  0.156844    8  0.277863  0.157035
3    0.03  0.0  0.192094    8  0.287147  0.192328
4    0.04  0.0  0.221811    8  0.296422  0.222082
6    0.06  0.0  0.271662    8  0.314940  0.271993
..    ...  ...       ...  ...       ...       ...
394  3.94  0.0  2.201409    8  1.977782  2.204096
396  3.96  0.0  2.206989    8  1.979723  2.209683
397  3.97  0.0  2.209774    8  1.980684  2.212472
398  3.98  0.0  2.212555    8  1.981639  2.215256
399  3.99  0.0  2.215333    8  1.982588  2.218038

[320 rows x 6 columns]

300

        x    y         z  rep    zmodel      zbms
1    0.01  0.0  0.110905    8  0.469711  0.110999
2    0.02  0.0  0.156844    8  0.475337  0.156976
3    0.03  0.0  0.192094    8  0.480977  0.192256
4    0.04  0.0  0.221811    8  0.486631  0.221998
6    0.06  0.0  0.271662    8  0.497979  0.271891
..    ...  ...       ...  ...       ...       ...
394  3.94  0.0  2.201409    8  2.131994  2.203266
396  3.96  0.0  2.206989    8  2.135085  2.208851
397  3.97  0.0  2.209774    8  2.136618  2.211638
398  3.98  0.0  2.212555    8  2.138142  2.214421
399  3.99  0.0  2.215333    8  2.139657  2.217202

[320 rows x 6 columns]

300

        x    y         z  rep    zmodel      zbms
1    0.01  0.0  0.110905    8  0.407255  0.111751
2    0.02  0.0  0.156844    8  0.413919  0.158039
3    0.03  0.0  0.192094    8  0.420591  0.193558
4    0.04  0.0  0.221811    8  0.427273  0.223501
6    0.06  0.0  0.271662    8  0.440661  0.273732
..    ...  ...       ...  ...       ...       ...
394  3.94  0.0  2.201409    8  2.153217  2.218188
396  3.96  0.0  2.206989    8  2.156548  2.223811
397  3.97  0.0  2.209774    8  2.158201  2.226617
398  3.98  0.0  2.212555    8  2.159846  2.229419
399  3.99  0.0  2.215333    8  2.161483  2.232218

[320 rows x 6 columns]

300

        x    y         z  rep    zmodel      zbms
1    0.01  0.0  0.110905    8  0.194083  0.109436
2    0.02  0.0  0.156844    8  0.205037  0.154766
3    0.03  0.0  0.192094    8  0.215969  0.189548
4    0.04  0.0  0.221811    8  0.226876  0.218872
6    0.06  0.0  0.271662    8  0.248618  0.268062
..    ...  ...       ...  ...       ...       ...
394  3.94  0.0  2.201409    8  1.936665  2.172239
396  3.96  0.0  2.206989    8  1.938356  2.177745
397  3.97  0.0  2.209774    8  1.939194  2.180493
398  3.98  0.0  2.212555    8  1.940027  2.183238
399  3.99  0.0  2.215333    8  1.940854  2.185979

[320 rows x 6 columns]

300

        x    y         z  rep    zmodel      zbms
1    0.01  0.0  0.110905    8  0.307283  0.110657
2    0.02  0.0  0.156844    8  0.318026  0.156492
3    0.03  0.0  0.192094    8  0.328699  0.191663
4    0.04  0.0  0.221811    8  0.339301  0.221314
6    0.06  0.0  0.271662    8  0.360298  0.271053
..    ...  ...       ...  ...       ...       ...
394  3.94  0.0  2.201409    8  2.129469  2.196475
396  3.96  0.0  2.206989    8  2.133650  2.202043
397  3.97  0.0  2.209774    8  2.135730  2.204821
398  3.98  0.0  2.212555    8  2.137804  2.207596
399  3.99  0.0  2.215333    8  2.139871  2.210368

[320 rows x 6 columns]

300

        x    y         z  rep    zmodel      zbms
1    0.01  0.0  0.110905    8  0.452060  0.108967
2    0.02  0.0  0.156844    8  0.457722  0.154103
3    0.03  0.0  0.192094    8  0.463391  0.188737
4    0.04  0.0  0.221811    8  0.469069  0.217935
6    0.06  0.0  0.271662    8  0.480446  0.266914
..    ...  ...       ...  ...       ...       ...
394  3.94  0.0  2.201409    8  2.150580  2.162939
396  3.96  0.0  2.206989    8  2.154419  2.168422
397  3.97  0.0  2.209774    8  2.156325  2.171158
398  3.98  0.0  2.212555    8  2.158222  2.173891
399  3.99  0.0  2.215333    8  2.160110  2.176620

[320 rows x 6 columns]

300

        x    y         z  rep    zmodel      zbms
1    0.01  0.0  0.110905    8  0.191596  0.112584
2    0.02  0.0  0.156844    8  0.205078  0.159218
3    0.03  0.0  0.192094    8  0.218442  0.195002
4    0.04  0.0  0.221811    8  0.231691  0.225169
6    0.06  0.0  0.271662    8  0.257841  0.275774
..    ...  ...       ...  ...       ...       ...
394  3.94  0.0  2.201409    8  2.323163  2.234735
396  3.96  0.0  2.206989    8  2.329609  2.240400
397  3.97  0.0  2.209774    8  2.332825  2.243227
398  3.98  0.0  2.212555    8  2.336035  2.246050
399  3.99  0.0  2.215333    8  2.339240  2.248870

[320 rows x 6 columns]

300

        x    y         z  rep    zmodel      zbms
1    0.01  0.0  0.110905    8  0.175477  0.109357
2    0.02  0.0  0.156844    8  0.192730  0.154654
3    0.03  0.0  0.192094    8  0.209746  0.189412
4    0.04  0.0  0.221811    8  0.226524  0.218714
6    0.06  0.0  0.271662    8  0.259368  0.267869
..    ...  ...       ...  ...       ...       ...
394  3.94  0.0  2.201409    8  2.453611  2.170672
396  3.96  0.0  2.206989    8  2.462393  2.176175
397  3.97  0.0  2.209774    8  2.466759  2.178921
398  3.98  0.0  2.212555    8  2.471107  2.181663
399  3.99  0.0  2.215333    8  2.475438  2.184402

[320 rows x 6 columns]

300

        x    y         z  rep    zmodel      zbms
1    0.01  0.0  0.110905    8  0.277637  0.110850
2    0.02  0.0  0.156844    8  0.286407  0.156765
3    0.03  0.0  0.192094    8  0.295168  0.191997
4    0.04  0.0  0.221811    8  0.303918  0.221699
6    0.06  0.0  0.271662    8  0.321384  0.271525
..    ...  ...       ...  ...       ...       ...
394  3.94  0.0  2.201409    8  2.135108  2.200301
396  3.96  0.0  2.206989    8  2.138711  2.205878
397  3.97  0.0  2.209774    8  2.140501  2.208662
398  3.98  0.0  2.212555    8  2.142283  2.211442
399  3.99  0.0  2.215333    8  2.144058  2.214218

[320 rows x 6 columns]

300

        x    y         z  rep    zmodel      zbms
1    0.01  0.0  0.110905    8  0.366190  0.111936
2    0.02  0.0  0.156844    8  0.374998  0.158301
3    0.03  0.0  0.192094    8  0.383774  0.193878
4    0.04  0.0  0.221811    8  0.392518  0.223872
6    0.06  0.0  0.271662    8  0.409911  0.274186
..    ...  ...       ...  ...       ...       ...
394  3.94  0.0  2.201409    8  2.016944  2.221862
396  3.96  0.0  2.206989    8  2.020147  2.227494
397  3.97  0.0  2.209774    8  2.021738  2.230305
398  3.98  0.0  2.212555    8  2.023323  2.233112
399  3.99  0.0  2.215333    8  2.024902  2.235916

[320 rows x 6 columns]

300

        x    y         z  rep    zmodel      zbms
1    0.01  0.0  0.110905    8  0.363447  0.110302
2    0.02  0.0  0.156844    8  0.372379  0.155990
3    0.03  0.0  0.192094    8  0.381277  0.191048
4    0.04  0.0  0.221811    8  0.390139  0.220603
6    0.06  0.0  0.271662    8  0.407758  0.270183
..    ...  ...       ...  ...       ...       ...
394  3.94  0.0  2.201409    8  2.022105  2.189426
396  3.96  0.0  2.206989    8  2.025472  2.194976
397  3.97  0.0  2.209774    8  2.027146  2.197746
398  3.98  0.0  2.212555    8  2.028815  2.200512
399  3.99  0.0  2.215333    8  2.030478  2.203275

[320 rows x 6 columns]

300

        x    y         z  rep    zmodel      zbms
1    0.01  0.0  0.110905    8  0.530401  0.111307
2    0.02  0.0  0.156844    8  0.535771  0.157412
3    0.03  0.0  0.192094    8  0.541151  0.192790
4    0.04  0.0  0.221811    8  0.546542  0.222615
6    0.06  0.0  0.271662    8  0.557356  0.272646
..    ...  ...       ...  ...       ...       ...
394  3.94  0.0  2.201409    8  2.093569  2.209386
396  3.96  0.0  2.206989    8  2.096568  2.214987
397  3.97  0.0  2.209774    8  2.098056  2.217782
398  3.98  0.0  2.212555    8  2.099535  2.220573
399  3.99  0.0  2.215333    8  2.101007  2.223361

[320 rows x 6 columns]

300

        x    y         z  rep    zmodel      zbms
1    0.01  0.0  0.110905    8  0.367831  0.112387
2    0.02  0.0  0.156844    8  0.375303  0.158939
3    0.03  0.0  0.192094    8  0.382772  0.194659
4    0.04  0.0  0.221811    8  0.390239  0.224773
6    0.06  0.0  0.271662    8  0.405164  0.275290
..    ...  ...       ...  ...       ...       ...
394  3.94  0.0  2.201409    8  2.189636  2.230809
396  3.96  0.0  2.206989    8  2.193091  2.236463
397  3.97  0.0  2.209774    8  2.194805  2.239285
398  3.98  0.0  2.212555    8  2.196511  2.242104
399  3.99  0.0  2.215333    8  2.198207  2.244919

[320 rows x 6 columns]

300

        x    y         z  rep    zmodel      zbms
1    0.01  0.0  0.110905    8  0.374506  0.112423
2    0.02  0.0  0.156844    8  0.383855  0.158991
3    0.03  0.0  0.192094    8  0.393162  0.194723
4    0.04  0.0  0.221811    8  0.402428  0.224847
6    0.06  0.0  0.271662    8  0.420833  0.275380
..    ...  ...       ...  ...       ...       ...
394  3.94  0.0  2.201409    8  2.166033  2.231543
396  3.96  0.0  2.206989    8  2.170371  2.237199
397  3.97  0.0  2.209774    8  2.172532  2.240022
398  3.98  0.0  2.212555    8  2.174687  2.242842
399  3.99  0.0  2.215333    8  2.176837  2.245658

[320 rows x 6 columns]

300

        x    y         z  rep    zmodel      zbms
1    0.01  0.0  0.110905    8  0.384471  0.060478
2    0.02  0.0  0.156844    8  0.391712  0.092254
3    0.03  0.0  0.192094    8  0.398951  0.118102
4    0.04  0.0  0.221811    8  0.406187  0.140725
6    0.06  0.0  0.271662    8  0.420649  0.180155
..    ...  ...       ...  ...       ...       ...
394  3.94  0.0  2.201409    8  2.132838  2.305568
396  3.96  0.0  2.206989    8  2.136419  2.312691
397  3.97  0.0  2.209774    8  2.138198  2.316247
398  3.98  0.0  2.212555    8  2.139968  2.319799
399  3.99  0.0  2.215333    8  2.141731  2.323348

[320 rows x 6 columns]

300

        x    y         z  rep    zmodel      zbms
1    0.01  0.0  0.110905    8  0.450459  0.056056
2    0.02  0.0  0.156844    8  0.455619  0.086492
3    0.03  0.0  0.192094    8  0.460789  0.111468
4    0.04  0.0  0.221811    8  0.465971  0.133452
6    0.06  0.0  0.271662    8  0.476369  0.171990
..    ...  ...       ...  ...       ...       ...
394  3.94  0.0  2.201409    8  2.310180  2.358280
396  3.96  0.0  2.206989    8  2.315164  2.365763
397  3.97  0.0  2.209774    8  2.317639  2.369499
398  3.98  0.0  2.212555    8  2.320101  2.373232
399  3.99  0.0  2.215333    8  2.322553  2.376961

[320 rows x 6 columns]

300

        x    y         z  rep    zmodel      zbms
1    0.01  0.0  0.110905    8  0.458041  0.058063
2    0.02  0.0  0.156844    8  0.464192  0.089116
3    0.03  0.0  0.192094    8  0.470352  0.114495
4    0.04  0.0  0.221811    8  0.476522  0.136774
6    0.06  0.0  0.271662    8  0.488886  0.175727
..    ...  ...       ...  ...       ...       ...
394  3.94  0.0  2.201409    8  2.227734  2.333703
396  3.96  0.0  2.206989    8  2.231600  2.341018
397  3.97  0.0  2.209774    8  2.233519  2.344670
398  3.98  0.0  2.212555    8  2.235429  2.348318
399  3.99  0.0  2.215333    8  2.237330  2.351963

[320 rows x 6 columns]

300

        x    y         z  rep    zmodel      zbms
1    0.01  0.0  0.110905    8  0.297626  0.111105
2    0.02  0.0  0.156844    8  0.309073  0.157126
3    0.03  0.0  0.192094    8  0.320451  0.192439
4    0.04  0.0  0.221811    8  0.331760  0.222210
6    0.06  0.0  0.271662    8  0.354172  0.272150
..    ...  ...       ...  ...       ...       ...
394  3.94  0.0  2.201409    8  1.979098  2.205368
396  3.96  0.0  2.206989    8  1.981447  2.210958
397  3.97  0.0  2.209774    8  1.982613  2.213748
398  3.98  0.0  2.212555    8  1.983774  2.216534
399  3.99  0.0  2.215333    8  1.984929  2.219317

[320 rows x 6 columns]

300
400
80
0
2000
4000
6000
8000
10000
12000
14000
16000
18000
20000
22000
24000
26000
28000
30000
32000
34000
36000
38000
40000
42000
44000
46000
48000
50000
52000
54000
56000
58000
60000
62000
64000
66000
68000
70000
72000
74000
76000
78000
80000
82000
84000
86000
88000
90000
92000
94000
96000
98000
100000
102000
104000
106000
108000
110000
112000
114000
116000
118000
120000
122000
124000
126000
128000
130000
132000
134000
136000
138000
140000
142000
144000
146000
148000
150000
152000
154000
156000
158000

             x       y         z  rep    zmodel      zbms
1       0.0000  0.0025  0.000000   10  0.000962  0.000000
2       0.0000  0.0050  0.000000   10  0.000968  0.000000
3       0.0000  0.0075  0.000000   10  0.000975  0.000000
4       0.0000  0.0100  0.000000   10  0.000981  0.000000
6       0.0000  0.0150  0.000000   10  0.000994  0.000000
...        ...     ...       ...  ...       ...       ...
159995  0.9975  0.9875  0.878116   10  0.920837  0.878116
159996  0.9975  0.9900  0.877525   10  0.920335  0.877525
159997  0.9975  0.9925  0.876932   10  0.919833  0.876932
159998  0.9975  0.9950  0.876338   10  0.919329  0.876338
159999  0.9975  0.9975  0.875742   10  0.918826  0.875742

[153600 rows x 6 columns]

120000

<lambdifygenerated-6963>:2: RuntimeWarning: divide by zero encountered in reciprocal
  return x + (x*x**(-_a5_))**x
<lambdifygenerated-6963>:2: RuntimeWarning: invalid value encountered in multiply
  return x + (x*x**(-_a5_))**x
<lambdifygenerated-6963>:2: RuntimeWarning: divide by zero encountered in power
  return x + (x*x**(-_a5_))**x
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/nguyen_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-6981>:2: RuntimeWarning: divide by zero encountered in power
  return x*(x**_a0_ + (x*x**(-_a5_)*cos(_a6_))**_a3_)
<lambdifygenerated-6981>:2: RuntimeWarning: invalid value encountered in multiply
  return x*(x**_a0_ + (x*x**(-_a5_)*cos(_a6_))**_a3_)
<lambdifygenerated-6991>:2: RuntimeWarning: divide by zero encountered in power
  return (x**_a0_ + (x*x**(-_a5_)*cos(_a6_))**_a3_)*cos(x*y/_a5_)
<lambdifygenerated-6991>:2: RuntimeWarning: overflow encountered in power
  return (x**_a0_ + (x*x**(-_a5_)*cos(_a6_))**_a3_)*cos(x*y/_a5_)
<lambdifygenerated-6991>:2: RuntimeWarning: invalid value encountered in multiply
  return (x**_a0_ + (x*x**(-_a5_)*cos(_a6_))**_a3_)*cos(x*y/_a5_)
<lambdifygenerated-7001>:2: RuntimeWarning: invalid value encountered in divide
  return (-2*x - cos(x))*(x**_a0_ + (x*x**(-_a5_)*cos(_a6_))**_a3_)*cos(_a3_*y/_a5_)/x
<lambdifygenerated-7002>:2: RuntimeWarning: invalid value encountered in divide
  return (-2*x - cos(x))*(x**_a0_ + (x*x**(-_a5_)*cos(_a6_))**_a3_)*cos(_a3_*y/_a5_)/x
<lambdifygenerated-7003>:2: RuntimeWarning: invalid value encountered in divide
  return (-2*x - cos(x**2))*(x**_a0_ + (x*x**(-_a5_)*cos(_a6_))**_a3_)*cos(_a3_*y/_a5_)/x
<lambdifygenerated-7004>:2: RuntimeWarning: invalid value encountered in divide
  return (-2*x - cos(x**2))*(x**_a0_ + (x*x**(-_a5_)*cos(_a6_))**_a3_)*cos(_a3_*y/_a5_)/x
<lambdifygenerated-7005>:2: RuntimeWarning: invalid value encountered in divide
  return (-2*x - cos(x**2))*(x**_a0_ + (x*x**(-_a5_)*cos(_a6_))**_a3_)*cos(_a3_*y/_a5_)/x
<lambdifygenerated-7006>:2: RuntimeWarning: invalid value encountered in divide
  return (-2*x - cos(x**2))*(x**_a0_ + (x*x**(-_a5_)*cos(_a6_))**_a3_)*cos(_a3_*y/_a5_)/x
<lambdifygenerated-7007>:2: RuntimeWarning: invalid value encountered in divide
  return (-2*x - cos(_a3_*x))*(x**_a0_ + (x*x**(-_a5_)*cos(_a6_))**_a3_)*cos(_a3_*y/_a5_)/x
<lambdifygenerated-7008>:2: RuntimeWarning: invalid value encountered in divide
  return (-2*x - cos(_a3_*x))*(x**_a0_ + (x*x**(-_a5_)*cos(_a6_))**_a3_)*cos(_a3_*y/_a5_)/x
<lambdifygenerated-7009>:2: RuntimeWarning: invalid value encountered in divide
  return (x**_a0_ + (x*x**(-_a5_)*cos(_a6_))**_a3_)*(-x - cos(_a3_*x) - 1)*cos(_a3_*y/_a5_)/x
<lambdifygenerated-7010>:2: RuntimeWarning: invalid value encountered in divide
  return (x**_a0_ + (x*x**(-_a5_)*cos(_a6_))**_a3_)*(-x - cos(_a3_*x) - 1)*cos(_a3_*y/_a5_)/x
<lambdifygenerated-7011>:2: RuntimeWarning: invalid value encountered in divide
  return (-2*x - cos(_a3_*x))*(x**_a0_ + (x*x**(-_a5_)*cos(_a6_))**_a3_)*cos(_a3_*y/_a5_)/x
<lambdifygenerated-7012>:2: RuntimeWarning: invalid value encountered in divide
  return (-2*x - cos(_a3_*x))*(x**_a0_ + (x*x**(-_a5_)*cos(_a6_))**_a3_)*cos(_a3_*y/_a5_)/x
<lambdifygenerated-7013>:2: RuntimeWarning: invalid value encountered in divide
  return (x**_a0_ + (x*x**(-_a5_)*cos(_a6_))**_a3_)*(-_a6_ - x - cos(_a3_*x))*cos(_a3_*y/_a5_)/x
<lambdifygenerated-7014>:2: RuntimeWarning: invalid value encountered in divide
  return (x**_a0_ + (x*x**(-_a5_)*cos(_a6_))**_a3_)*(-_a6_ - x - cos(_a3_*x))*cos(_a3_*y/_a5_)/x
<lambdifygenerated-7015>:2: RuntimeWarning: divide by zero encountered in divide
  return (x**_a0_ + (x*x**(-_a5_)*cos(_a6_))**_a3_)*(-_a6_*cos(x)/x - x - cos(_a3_*x))*cos(_a3_*y/_a5_)/x
<lambdifygenerated-7015>:2: RuntimeWarning: invalid value encountered in multiply
  return (x**_a0_ + (x*x**(-_a5_)*cos(_a6_))**_a3_)*(-_a6_*cos(x)/x - x - cos(_a3_*x))*cos(_a3_*y/_a5_)/x
<lambdifygenerated-7016>:2: RuntimeWarning: divide by zero encountered in divide
  return (x**_a0_ + (x*x**(-_a5_)*cos(_a6_))**_a3_)*(-_a6_*cos(x)/x - x - cos(_a3_*x))*cos(_a3_*y/_a5_)/x
<lambdifygenerated-7016>:2: RuntimeWarning: invalid value encountered in multiply
  return (x**_a0_ + (x*x**(-_a5_)*cos(_a6_))**_a3_)*(-_a6_*cos(x)/x - x - cos(_a3_*x))*cos(_a3_*y/_a5_)/x
<lambdifygenerated-7017>:2: RuntimeWarning: divide by zero encountered in divide
  return (x**_a0_ + (x*x**(-_a5_)*cos(_a6_))**_a3_)*(-_a6_*cos(x**2)/x - x - cos(_a3_*x))*cos(_a3_*y/_a5_)/x
<lambdifygenerated-7017>:2: RuntimeWarning: invalid value encountered in multiply
  return (x**_a0_ + (x*x**(-_a5_)*cos(_a6_))**_a3_)*(-_a6_*cos(x**2)/x - x - cos(_a3_*x))*cos(_a3_*y/_a5_)/x
<lambdifygenerated-7018>:2: RuntimeWarning: divide by zero encountered in divide
  return (x**_a0_ + (x*x**(-_a5_)*cos(_a6_))**_a3_)*(-_a6_*cos(x**2)/x - x - cos(_a3_*x))*cos(_a3_*y/_a5_)/x
<lambdifygenerated-7018>:2: RuntimeWarning: invalid value encountered in multiply
  return (x**_a0_ + (x*x**(-_a5_)*cos(_a6_))**_a3_)*(-_a6_*cos(x**2)/x - x - cos(_a3_*x))*cos(_a3_*y/_a5_)/x
<lambdifygenerated-7019>:2: RuntimeWarning: divide by zero encountered in divide
  return (x**_a0_ + (x*x**(-_a5_)*cos(_a6_))**_a3_)*(-_a6_*cos(_a7_*x)/x - x - cos(_a3_*x))*cos(_a3_*y/_a5_)/x
<lambdifygenerated-7019>:2: RuntimeWarning: invalid value encountered in multiply
  return (x**_a0_ + (x*x**(-_a5_)*cos(_a6_))**_a3_)*(-_a6_*cos(_a7_*x)/x - x - cos(_a3_*x))*cos(_a3_*y/_a5_)/x
<lambdifygenerated-7020>:2: RuntimeWarning: divide by zero encountered in divide
  return (x**_a0_ + (x*x**(-_a5_)*cos(_a6_))**_a3_)*(-_a6_*cos(_a7_*x)/x - x - cos(_a3_*x))*cos(_a3_*y/_a5_)/x
<lambdifygenerated-7020>:2: RuntimeWarning: invalid value encountered in multiply
  return (x**_a0_ + (x*x**(-_a5_)*cos(_a6_))**_a3_)*(-_a6_*cos(_a7_*x)/x - x - cos(_a3_*x))*cos(_a3_*y/_a5_)/x
<lambdifygenerated-7021>:2: RuntimeWarning: divide by zero encountered in divide
  return (x**_a0_ + (x*x**(-_a5_)*cos(_a6_))**_a3_)*(-_a6_*cos(_a7_*x**2)/x - x - cos(_a3_*x))*cos(_a3_*y/_a5_)/x
<lambdifygenerated-7021>:2: RuntimeWarning: invalid value encountered in multiply
  return (x**_a0_ + (x*x**(-_a5_)*cos(_a6_))**_a3_)*(-_a6_*cos(_a7_*x**2)/x - x - cos(_a3_*x))*cos(_a3_*y/_a5_)/x
<lambdifygenerated-7022>:2: RuntimeWarning: divide by zero encountered in divide
  return (x**_a0_ + (x*x**(-_a5_)*cos(_a6_))**_a3_)*(-_a6_*cos(_a7_*x**2)/x - x - cos(_a3_*x))*cos(_a3_*y/_a5_)/x
<lambdifygenerated-7022>:2: RuntimeWarning: invalid value encountered in multiply
  return (x**_a0_ + (x*x**(-_a5_)*cos(_a6_))**_a3_)*(-_a6_*cos(_a7_*x**2)/x - x - cos(_a3_*x))*cos(_a3_*y/_a5_)/x
<lambdifygenerated-7023>:2: RuntimeWarning: divide by zero encountered in divide
  return (x**_a0_ + (x*x**(-_a5_)*cos(_a6_))**_a3_)*(-_a6_*cos(_a7_**2*x)/x - x - cos(_a3_*x))*cos(_a3_*y/_a5_)/x
<lambdifygenerated-7023>:2: RuntimeWarning: invalid value encountered in multiply
  return (x**_a0_ + (x*x**(-_a5_)*cos(_a6_))**_a3_)*(-_a6_*cos(_a7_**2*x)/x - x - cos(_a3_*x))*cos(_a3_*y/_a5_)/x
<lambdifygenerated-7024>:2: RuntimeWarning: divide by zero encountered in divide
  return (x**_a0_ + (x*x**(-_a5_)*cos(_a6_))**_a3_)*(-_a6_*cos(_a7_**2*x)/x - x - cos(_a3_*x))*cos(_a3_*y/_a5_)/x
<lambdifygenerated-7024>:2: RuntimeWarning: invalid value encountered in multiply
  return (x**_a0_ + (x*x**(-_a5_)*cos(_a6_))**_a3_)*(-_a6_*cos(_a7_**2*x)/x - x - cos(_a3_*x))*cos(_a3_*y/_a5_)/x
<lambdifygenerated-7025>:2: RuntimeWarning: divide by zero encountered in divide
  return (x**_a0_ + (x*x**(-_a5_)*cos(_a6_))**_a3_)*(-_a6_*cos(_a7_**2*x**2)/x - x - cos(_a3_*x))*cos(_a3_*y/_a5_)/x
<lambdifygenerated-7025>:2: RuntimeWarning: invalid value encountered in multiply
  return (x**_a0_ + (x*x**(-_a5_)*cos(_a6_))**_a3_)*(-_a6_*cos(_a7_**2*x**2)/x - x - cos(_a3_*x))*cos(_a3_*y/_a5_)/x
<lambdifygenerated-7026>:2: RuntimeWarning: divide by zero encountered in divide
  return (x**_a0_ + (x*x**(-_a5_)*cos(_a6_))**_a3_)*(-_a6_*cos(_a7_**2*x**2)/x - x - cos(_a3_*x))*cos(_a3_*y/_a5_)/x
<lambdifygenerated-7026>:2: RuntimeWarning: invalid value encountered in multiply
  return (x**_a0_ + (x*x**(-_a5_)*cos(_a6_))**_a3_)*(-_a6_*cos(_a7_**2*x**2)/x - x - cos(_a3_*x))*cos(_a3_*y/_a5_)/x
<lambdifygenerated-7027>:2: RuntimeWarning: divide by zero encountered in divide
  return (x**_a0_ + (x*x**(-_a5_)*cos(_a6_))**_a3_)*(-_a6_*cos(_a7_**2*x**3)/x - x - cos(_a3_*x))*cos(_a3_*y/_a5_)/x
<lambdifygenerated-7027>:2: RuntimeWarning: invalid value encountered in multiply
  return (x**_a0_ + (x*x**(-_a5_)*cos(_a6_))**_a3_)*(-_a6_*cos(_a7_**2*x**3)/x - x - cos(_a3_*x))*cos(_a3_*y/_a5_)/x
<lambdifygenerated-7028>:2: RuntimeWarning: divide by zero encountered in divide
  return (x**_a0_ + (x*x**(-_a5_)*cos(_a6_))**_a3_)*(-_a6_*cos(_a7_**2*x**3)/x - x - cos(_a3_*x))*cos(_a3_*y/_a5_)/x
<lambdifygenerated-7028>:2: RuntimeWarning: invalid value encountered in multiply
  return (x**_a0_ + (x*x**(-_a5_)*cos(_a6_))**_a3_)*(-_a6_*cos(_a7_**2*x**3)/x - x - cos(_a3_*x))*cos(_a3_*y/_a5_)/x
<lambdifygenerated-7029>:2: RuntimeWarning: divide by zero encountered in divide
  return (x**_a0_ + (x*x**(-_a5_)*cos(_a6_))**_a3_)*(-_a6_*cos(_a7_**2*x**3)/x - x - cos(_a3_*x))*cos(_a3_*y/_a5_)/x
<lambdifygenerated-7029>:2: RuntimeWarning: invalid value encountered in multiply
  return (x**_a0_ + (x*x**(-_a5_)*cos(_a6_))**_a3_)*(-_a6_*cos(_a7_**2*x**3)/x - x - cos(_a3_*x))*cos(_a3_*y/_a5_)/x
<lambdifygenerated-7030>:2: RuntimeWarning: divide by zero encountered in divide
  return (x**_a0_ + (x*x**(-_a5_)*cos(_a6_))**_a3_)*(-_a6_*cos(_a7_**2*x**3)/x - x - cos(_a3_*x))*cos(_a3_*y/_a5_)/x
<lambdifygenerated-7030>:2: RuntimeWarning: invalid value encountered in multiply
  return (x**_a0_ + (x*x**(-_a5_)*cos(_a6_))**_a3_)*(-_a6_*cos(_a7_**2*x**3)/x - x - cos(_a3_*x))*cos(_a3_*y/_a5_)/x
<lambdifygenerated-7031>:2: RuntimeWarning: divide by zero encountered in divide
  return (x**_a0_ + (x*x**(-_a5_)*cos(_a6_))**_a3_)*(-_a6_*cos(_a2_*_a7_**2*x**2)/x - x - cos(_a3_*x))*cos(_a3_*y/_a5_)/x
<lambdifygenerated-7031>:2: RuntimeWarning: invalid value encountered in multiply
  return (x**_a0_ + (x*x**(-_a5_)*cos(_a6_))**_a3_)*(-_a6_*cos(_a2_*_a7_**2*x**2)/x - x - cos(_a3_*x))*cos(_a3_*y/_a5_)/x
<lambdifygenerated-7032>:2: RuntimeWarning: divide by zero encountered in divide
  return (x**_a0_ + (x*x**(-_a5_)*cos(_a6_))**_a3_)*(-_a6_*cos(_a2_*_a7_**2*x**2)/x - x - cos(_a3_*x))*cos(_a3_*y/_a5_)/x
<lambdifygenerated-7032>:2: RuntimeWarning: invalid value encountered in multiply
  return (x**_a0_ + (x*x**(-_a5_)*cos(_a6_))**_a3_)*(-_a6_*cos(_a2_*_a7_**2*x**2)/x - x - cos(_a3_*x))*cos(_a3_*y/_a5_)/x
<lambdifygenerated-7033>:2: RuntimeWarning: divide by zero encountered in divide
  return (x**_a0_ + (x*x**(-_a5_)*cos(_a6_))**_a3_)*(-1/2*_a6_*cos(_a2_*_a7_**2*x**2)/x - x - cos(_a3_*x))*cos(_a3_*y/_a5_)/x
<lambdifygenerated-7033>:2: RuntimeWarning: invalid value encountered in multiply
  return (x**_a0_ + (x*x**(-_a5_)*cos(_a6_))**_a3_)*(-1/2*_a6_*cos(_a2_*_a7_**2*x**2)/x - x - cos(_a3_*x))*cos(_a3_*y/_a5_)/x
<lambdifygenerated-7034>:2: RuntimeWarning: divide by zero encountered in divide
  return (x**_a0_ + (x*x**(-_a5_)*cos(_a6_))**_a3_)*(-1/2*_a6_*cos(_a2_*_a7_**2*x**2)/x - x - cos(_a3_*x))*cos(_a3_*y/_a5_)/x
<lambdifygenerated-7034>:2: RuntimeWarning: invalid value encountered in multiply
  return (x**_a0_ + (x*x**(-_a5_)*cos(_a6_))**_a3_)*(-1/2*_a6_*cos(_a2_*_a7_**2*x**2)/x - x - cos(_a3_*x))*cos(_a3_*y/_a5_)/x
<lambdifygenerated-7035>:2: RuntimeWarning: invalid value encountered in divide
  return (x**_a0_ + (x*x**(-_a5_)*cos(_a6_))**_a3_)*(-_a6_*cos(_a2_*_a7_**2*x**2)/(_a0_ + x) - x - cos(_a3_*x))*cos(_a3_*y/_a5_)/x
<lambdifygenerated-7036>:2: RuntimeWarning: invalid value encountered in divide
  return (x**_a0_ + (x*x**(-_a5_)*cos(_a6_))**_a3_)*(-_a6_*cos(_a2_*_a7_**2*x**2)/(_a0_ + x) - x - cos(_a3_*x))*cos(_a3_*y/_a5_)/x
<lambdifygenerated-7037>:2: RuntimeWarning: invalid value encountered in divide
  return (x**_a0_ + (x*x**(-_a5_)*cos(_a6_))**_a3_)*(-_a6_*cos(_a2_*_a7_**2*x**2)/(_a0_ + _a1_) - x - cos(_a3_*x))*cos(_a3_*y/_a5_)/x
<lambdifygenerated-7038>:2: RuntimeWarning: invalid value encountered in divide
  return (x**_a0_ + (x*x**(-_a5_)*cos(_a6_))**_a3_)*(-_a6_*cos(_a2_*_a7_**2*x**2)/(_a0_ + _a1_) - x - cos(_a3_*x))*cos(_a3_*y/_a5_)/x
<lambdifygenerated-7039>:2: RuntimeWarning: invalid value encountered in divide
  return (x**_a0_ + (x*x**(-_a5_)*cos(_a6_))**_a3_)*(-_a6_*cos(_a2_*_a7_**2*x**2)/(_a0_ + _a1_) - _a7_ - cos(_a3_*x))*cos(_a3_*y/_a5_)/x
<lambdifygenerated-7040>:2: RuntimeWarning: invalid value encountered in divide
  return (x**_a0_ + (x*x**(-_a5_)*cos(_a6_))**_a3_)*(-_a6_*cos(_a2_*_a7_**2*x**2)/(_a0_ + _a1_) - _a7_ - cos(_a3_*x))*cos(_a3_*y/_a5_)/x

400
80
0
2000
4000
6000
8000
10000
12000
14000
16000
18000
20000
22000
24000
26000
28000
30000
32000
34000
36000
38000
40000
42000
44000
46000
48000
50000
52000
54000
56000
58000
60000
62000
64000
66000
68000
70000
72000
74000
76000
78000
80000
82000
84000
86000
88000
90000
92000
94000
96000
98000
100000
102000
104000
106000
108000
110000
112000
114000
116000
118000
120000
122000
124000
126000
128000
130000
132000
134000
136000
138000
140000
142000
144000
146000
148000
150000
152000
154000
156000
158000

             x       y         z  rep    zmodel      zbms
1       0.0000  0.0025  0.000000   10  0.003559  0.000000
2       0.0000  0.0050  0.000000   10  0.003515  0.000000
3       0.0000  0.0075  0.000000   10  0.003472  0.000000
4       0.0000  0.0100  0.000000   10  0.003429  0.000000
6       0.0000  0.0150  0.000000   10  0.003344  0.000000
...        ...     ...       ...  ...       ...       ...
159995  0.9975  0.9875  0.878116   10  0.923910  0.878116
159996  0.9975  0.9900  0.877525   10  0.923427  0.877525
159997  0.9975  0.9925  0.876932   10  0.922944  0.876932
159998  0.9975  0.9950  0.876338   10  0.922460  0.876338
159999  0.9975  0.9975  0.875742   10  0.921976  0.875742

[153600 rows x 6 columns]

120000
400
80
0
2000
4000
6000
8000
10000
12000
14000
16000
18000
20000
22000
24000
26000
28000
30000
32000
34000
36000
38000
40000
42000
44000
46000
48000
50000
52000
54000
56000
58000
60000
62000
64000
66000
68000
70000
72000
74000
76000
78000
80000
82000
84000
86000
88000
90000
92000
94000
96000
98000
100000
102000
104000
106000
108000
110000
112000
114000
116000
118000
120000
122000
124000
126000
128000
130000
132000
134000
136000
138000
140000
142000
144000
146000
148000
150000
152000
154000
156000
158000

             x       y         z  rep    zmodel      zbms
1       0.0000  0.0025  0.000000   10  0.002166  0.000000
2       0.0000  0.0050  0.000000   10  0.002134  0.000000
3       0.0000  0.0075  0.000000   10  0.002103  0.000000
4       0.0000  0.0100  0.000000   10  0.002072  0.000000
6       0.0000  0.0150  0.000000   10  0.002010  0.000000
...        ...     ...       ...  ...       ...       ...
159995  0.9975  0.9875  0.878116   10  0.919736  0.878116
159996  0.9975  0.9900  0.877525   10  0.919263  0.877525
159997  0.9975  0.9925  0.876932   10  0.918790  0.876932
159998  0.9975  0.9950  0.876338   10  0.918317  0.876338
159999  0.9975  0.9975  0.875742   10  0.917843  0.875742

[153600 rows x 6 columns]

120000
400
80
0
2000
4000
6000
8000
10000
12000
14000
16000
18000
20000
22000
24000
26000
28000
30000
32000
34000
36000
38000
40000
42000
44000
46000
48000
50000
52000
54000
56000
58000
60000
62000
64000
66000
68000
70000
72000
74000
76000
78000
80000
82000
84000
86000
88000
90000
92000
94000
96000
98000
100000
102000
104000
106000
108000
110000
112000
114000
116000
118000
120000
122000
124000
126000
128000
130000
132000
134000
136000
138000
140000
142000
144000
146000
148000
150000
152000
154000
156000
158000

             x       y         z  rep    zmodel      zbms
1       0.0000  0.0025  0.000000   10  0.007893  0.000000
2       0.0000  0.0050  0.000000   10  0.007810  0.000000
3       0.0000  0.0075  0.000000   10  0.007727  0.000000
4       0.0000  0.0100  0.000000   10  0.007645  0.000000
6       0.0000  0.0150  0.000000   10  0.007482  0.000000
...        ...     ...       ...  ...       ...       ...
159995  0.9975  0.9875  0.878116   10  0.905890  0.877966
159996  0.9975  0.9900  0.877525   10  0.905414  0.877399
159997  0.9975  0.9925  0.876932   10  0.904937  0.876831
159998  0.9975  0.9950  0.876338   10  0.904460  0.876262
159999  0.9975  0.9975  0.875742   10  0.903982  0.875691

[153600 rows x 6 columns]

120000
400
80
0
2000
4000
6000
8000
10000
12000
14000
16000
18000
20000
22000
24000
26000
28000
30000
32000
34000
36000
38000
40000
42000
44000
46000
48000
50000
52000
54000
56000
58000
60000
62000
64000
66000
68000
70000
72000
74000
76000
78000
80000
82000
84000
86000
88000
90000
92000
94000
96000
98000
100000
102000
104000
106000
108000
110000
112000
114000
116000
118000
120000
122000
124000
126000
128000
130000
132000
134000
136000
138000
140000
142000
144000
146000
148000
150000
152000
154000
156000
158000

             x       y         z  rep    zmodel      zbms
1       0.0000  0.0025  0.000000   10  0.002328  0.000000
2       0.0000  0.0050  0.000000   10  0.002283  0.000000
3       0.0000  0.0075  0.000000   10  0.002239  0.000000
4       0.0000  0.0100  0.000000   10  0.002195  0.000000
6       0.0000  0.0150  0.000000   10  0.002108  0.000000
...        ...     ...       ...  ...       ...       ...
159995  0.9975  0.9875  0.878116   10  0.928253  0.875855
159996  0.9975  0.9900  0.877525   10  0.927750  0.875278
159997  0.9975  0.9925  0.876932   10  0.927245  0.874700
159998  0.9975  0.9950  0.876338   10  0.926740  0.874121
159999  0.9975  0.9975  0.875742   10  0.926234  0.873541

[153600 rows x 6 columns]

120000

<lambdifygenerated-7149>:2: RuntimeWarning: invalid value encountered in divide
  return sin(x)/x
<lambdifygenerated-7150>:2: RuntimeWarning: invalid value encountered in divide
  return sin(x)/x
<lambdifygenerated-7151>:2: RuntimeWarning: invalid value encountered in divide
  return sin(x**2)/x
<lambdifygenerated-7152>:2: RuntimeWarning: invalid value encountered in divide
  return sin(x**2)/x
<lambdifygenerated-7153>:2: RuntimeWarning: invalid value encountered in divide
  return sin(x**2)/x
<lambdifygenerated-7154>:2: RuntimeWarning: invalid value encountered in divide
  return sin(x**2)/x
<lambdifygenerated-7155>:2: RuntimeWarning: invalid value encountered in divide
  return sin(_a4_*x)/x
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/nguyen_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-7156>:2: RuntimeWarning: invalid value encountered in divide
  return sin(_a4_*x)/x

400
80
0
2000
4000
6000
8000
10000
12000
14000
16000
18000
20000
22000
24000
26000
28000
30000
32000
34000
36000
38000
40000
42000
44000
46000
48000
50000
52000
54000
56000
58000
60000
62000
64000
66000
68000
70000
72000
74000
76000
78000
80000
82000
84000
86000
88000
90000
92000
94000
96000
98000
100000
102000
104000
106000
108000
110000
112000
114000
116000
118000
120000
122000
124000
126000
128000
130000
132000
134000
136000
138000
140000
142000
144000
146000
148000
150000
152000
154000
156000
158000

             x       y         z  rep    zmodel      zbms
1       0.0000  0.0025  0.000000   10  0.007778  0.000000
2       0.0000  0.0050  0.000000   10  0.007723  0.000000
3       0.0000  0.0075  0.000000   10  0.007669  0.000000
4       0.0000  0.0100  0.000000   10  0.007614  0.000000
6       0.0000  0.0150  0.000000   10  0.007506  0.000000
...        ...     ...       ...  ...       ...       ...
159995  0.9975  0.9875  0.878116   10  0.940372  0.877757
159996  0.9975  0.9900  0.877525   10  0.939908  0.877189
159997  0.9975  0.9925  0.876932   10  0.939443  0.876620
159998  0.9975  0.9950  0.876338   10  0.938979  0.876049
159999  0.9975  0.9975  0.875742   10  0.938513  0.875478

[153600 rows x 6 columns]

120000
400
80
0
2000
4000
6000
8000
10000
12000
14000
16000
18000
20000
22000
24000
26000
28000
30000
32000
34000
36000
38000
40000
42000
44000
46000
48000
50000
52000
54000
56000
58000
60000
62000
64000
66000
68000
70000
72000
74000
76000
78000
80000
82000
84000
86000
88000
90000
92000
94000
96000
98000
100000
102000
104000
106000
108000
110000
112000
114000
116000
118000
120000
122000
124000
126000
128000
130000
132000
134000
136000
138000
140000
142000
144000
146000
148000
150000
152000
154000
156000
158000

             x       y         z  rep    zmodel      zbms
1       0.0000  0.0025  0.000000   10 -0.004949  0.000000
2       0.0000  0.0050  0.000000   10 -0.004972  0.000000
3       0.0000  0.0075  0.000000   10 -0.004994  0.000000
4       0.0000  0.0100  0.000000   10 -0.005015  0.000000
6       0.0000  0.0150  0.000000   10 -0.005053  0.000000
...        ...     ...       ...  ...       ...       ...
159995  0.9975  0.9875  0.878116   10  0.964586  0.879739
159996  0.9975  0.9900  0.877525   10  0.964224  0.879157
159997  0.9975  0.9925  0.876932   10  0.963862  0.878573
159998  0.9975  0.9950  0.876338   10  0.963500  0.877989
159999  0.9975  0.9975  0.875742   10  0.963137  0.877403

[153600 rows x 6 columns]

120000
400
80
0
2000
4000
6000
8000
10000
12000
14000
16000
18000
20000
22000
24000
26000
28000
30000
32000
34000
36000
38000
40000
42000
44000
46000
48000
50000
52000
54000
56000
58000
60000
62000
64000
66000
68000
70000
72000
74000
76000
78000
80000
82000
84000
86000
88000
90000
92000
94000
96000
98000
100000
102000
104000
106000
108000
110000
112000
114000
116000
118000
120000
122000
124000
126000
128000
130000
132000
134000
136000
138000
140000
142000
144000
146000
148000
150000
152000
154000
156000
158000

             x       y         z  rep    zmodel      zbms
1       0.0000  0.0025  0.000000   10 -0.002427  0.000000
2       0.0000  0.0050  0.000000   10 -0.002296  0.000000
3       0.0000  0.0075  0.000000   10 -0.002168  0.000000
4       0.0000  0.0100  0.000000   10 -0.002042  0.000000
6       0.0000  0.0150  0.000000   10 -0.001797  0.000000
...        ...     ...       ...  ...       ...       ...
159995  0.9975  0.9875  0.878116   10  0.926104  0.879364
159996  0.9975  0.9900  0.877525   10  0.925596  0.878802
159997  0.9975  0.9925  0.876932   10  0.925088  0.878240
159998  0.9975  0.9950  0.876338   10  0.924578  0.877677
159999  0.9975  0.9975  0.875742   10  0.924066  0.877113

[153600 rows x 6 columns]

120000
400
80
0
2000
4000
6000
8000
10000
12000
14000
16000
18000
20000
22000
24000
26000
28000
30000
32000
34000
36000
38000
40000
42000
44000
46000
48000
50000
52000
54000
56000
58000
60000
62000
64000
66000
68000
70000
72000
74000
76000
78000
80000
82000
84000
86000
88000
90000
92000
94000
96000
98000
100000
102000
104000
106000
108000
110000
112000
114000
116000
118000
120000
122000
124000
126000
128000
130000
132000
134000
136000
138000
140000
142000
144000
146000
148000
150000
152000
154000
156000
158000

             x       y         z  rep    zmodel      zbms
1       0.0000  0.0025  0.000000   10 -0.003661  0.000000
2       0.0000  0.0050  0.000000   10 -0.003604  0.000000
3       0.0000  0.0075  0.000000   10 -0.003547  0.000000
4       0.0000  0.0100  0.000000   10 -0.003490  0.000000
6       0.0000  0.0150  0.000000   10 -0.003377  0.000000
...        ...     ...       ...  ...       ...       ...
159995  0.9975  0.9875  0.878116   10  0.955413  0.879412
159996  0.9975  0.9900  0.877525   10  0.955035  0.878826
159997  0.9975  0.9925  0.876932   10  0.954656  0.878238
159998  0.9975  0.9950  0.876338   10  0.954276  0.877650
159999  0.9975  0.9975  0.875742   10  0.953895  0.877060

[153600 rows x 6 columns]

120000
400
80
0
2000
4000
6000
8000
10000
12000
14000
16000
18000
20000
22000
24000
26000
28000
30000
32000
34000
36000
38000
40000
42000
44000
46000
48000
50000
52000
54000
56000
58000
60000
62000
64000
66000
68000
70000
72000
74000
76000
78000
80000
82000
84000
86000
88000
90000
92000
94000
96000
98000
100000
102000
104000
106000
108000
110000
112000
114000
116000
118000
120000
122000
124000
126000
128000
130000
132000
134000
136000
138000
140000
142000
144000
146000
148000
150000
152000
154000
156000
158000

             x       y         z  rep    zmodel      zbms
1       0.0000  0.0025  0.000000   10 -0.005836  0.000000
2       0.0000  0.0050  0.000000   10 -0.005739  0.000000
3       0.0000  0.0075  0.000000   10 -0.005644  0.000000
4       0.0000  0.0100  0.000000   10 -0.005549  0.000000
6       0.0000  0.0150  0.000000   10 -0.005362  0.000000
...        ...     ...       ...  ...       ...       ...
159995  0.9975  0.9875  0.878116   10  0.870010  0.876203
159996  0.9975  0.9900  0.877525   10  0.869290  0.875628
159997  0.9975  0.9925  0.876932   10  0.868570  0.875052
159998  0.9975  0.9950  0.876338   10  0.867849  0.874475
159999  0.9975  0.9975  0.875742   10  0.867128  0.873897

[153600 rows x 6 columns]

120000

<lambdifygenerated-7287>:2: RuntimeWarning: invalid value encountered in divide
  return tanh(x)/x
<lambdifygenerated-7288>:2: RuntimeWarning: invalid value encountered in divide
  return tanh(x)/x
<lambdifygenerated-7289>:2: RuntimeWarning: divide by zero encountered in divide
  return tanh(1)/x
<lambdifygenerated-7290>:2: RuntimeWarning: divide by zero encountered in divide
  return tanh(1)/x
<lambdifygenerated-7291>:2: RuntimeWarning: divide by zero encountered in divide
  return tanh(1)/x
<lambdifygenerated-7292>:2: RuntimeWarning: divide by zero encountered in divide
  return tanh(1)/x
<lambdifygenerated-7293>:2: RuntimeWarning: invalid value encountered in divide
  return tanh(x/_a3_)/x
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/nguyen_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-7294>:2: RuntimeWarning: invalid value encountered in divide
  return tanh(x/_a3_)/x
<lambdifygenerated-7295>:2: RuntimeWarning: invalid value encountered in divide
  return (1/2)*tanh(x/_a3_)/x
<lambdifygenerated-7296>:2: RuntimeWarning: invalid value encountered in divide
  return (1/2)*tanh(x/_a3_)/x

400
80
0
2000
4000
6000
8000
10000
12000
14000
16000
18000
20000
22000
24000
26000
28000
30000
32000
34000
36000
38000
40000
42000
44000
46000
48000
50000
52000
54000
56000
58000
60000
62000
64000
66000
68000
70000
72000
74000
76000
78000
80000
82000
84000
86000
88000
90000
92000
94000
96000
98000
100000
102000
104000
106000
108000
110000
112000
114000
116000
118000
120000
122000
124000
126000
128000
130000
132000
134000
136000
138000
140000
142000
144000
146000
148000
150000
152000
154000
156000
158000

             x       y         z  rep    zmodel      zbms
1       0.0000  0.0025  0.000000   10  0.016960  0.000000
2       0.0000  0.0050  0.000000   10  0.016822  0.000000
3       0.0000  0.0075  0.000000   10  0.016684  0.000000
4       0.0000  0.0100  0.000000   10  0.016547  0.000000
6       0.0000  0.0150  0.000000   10  0.016275  0.000000
...        ...     ...       ...  ...       ...       ...
159995  0.9975  0.9875  0.878116   10  0.909463  0.918709
159996  0.9975  0.9900  0.877525   10  0.908993  0.918137
159997  0.9975  0.9925  0.876932   10  0.908521  0.917565
159998  0.9975  0.9950  0.876338   10  0.908049  0.916992
159999  0.9975  0.9975  0.875742   10  0.907576  0.916418

[153600 rows x 6 columns]

120000
400
80
0
2000
4000
6000
8000
10000
12000
14000
16000
18000
20000
22000
24000
26000
28000
30000
32000
34000
36000
38000
40000
42000
44000
46000
48000
50000
52000
54000
56000
58000
60000
62000
64000
66000
68000
70000
72000
74000
76000
78000
80000
82000
84000
86000
88000
90000
92000
94000
96000
98000
100000
102000
104000
106000
108000
110000
112000
114000
116000
118000
120000
122000
124000
126000
128000
130000
132000
134000
136000
138000
140000
142000
144000
146000
148000
150000
152000
154000
156000
158000

             x       y         z  rep    zmodel      zbms
1       0.0000  0.0025  0.000000   10  0.011413  0.000000
2       0.0000  0.0050  0.000000   10  0.011378  0.000000
3       0.0000  0.0075  0.000000   10  0.011342  0.000000
4       0.0000  0.0100  0.000000   10  0.011306  0.000000
6       0.0000  0.0150  0.000000   10  0.011234  0.000000
...        ...     ...       ...  ...       ...       ...
159995  0.9975  0.9875  0.878116   10  0.940249  0.886037
159996  0.9975  0.9900  0.877525   10  0.939819  0.885509
159997  0.9975  0.9925  0.876932   10  0.939388  0.884979
159998  0.9975  0.9950  0.876338   10  0.938957  0.884449
159999  0.9975  0.9975  0.875742   10  0.938526  0.883918

[153600 rows x 6 columns]

120000

<lambdifygenerated-7345>:2: RuntimeWarning: invalid value encountered in divide
  return sin(x)/x
<lambdifygenerated-7346>:2: RuntimeWarning: invalid value encountered in divide
  return sin(x)/x
<lambdifygenerated-7347>:2: RuntimeWarning: invalid value encountered in divide
  return sin(x**2)/x
<lambdifygenerated-7348>:2: RuntimeWarning: invalid value encountered in divide
  return sin(x**2)/x
<lambdifygenerated-7349>:2: RuntimeWarning: invalid value encountered in divide
  return sin(x**2)/x
<lambdifygenerated-7350>:2: RuntimeWarning: invalid value encountered in divide
  return sin(x**2)/x
<lambdifygenerated-7351>:2: RuntimeWarning: invalid value encountered in divide
  return sin(_a0_*x)/x
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/nguyen_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-7352>:2: RuntimeWarning: invalid value encountered in divide
  return sin(_a0_*x)/x

400
80
0
2000
4000
6000
8000
10000
12000
14000
16000
18000
20000
22000
24000
26000
28000
30000
32000
34000
36000
38000
40000
42000
44000
46000
48000
50000
52000
54000
56000
58000
60000
62000
64000
66000
68000
70000
72000
74000
76000
78000
80000
82000
84000
86000
88000
90000
92000
94000
96000
98000
100000
102000
104000
106000
108000
110000
112000
114000
116000
118000
120000
122000
124000
126000
128000
130000
132000
134000
136000
138000
140000
142000
144000
146000
148000
150000
152000
154000
156000
158000

             x       y         z  rep    zmodel      zbms
1       0.0000  0.0025  0.000000   10 -0.016075  0.000000
2       0.0000  0.0050  0.000000   10 -0.015943  0.000000
3       0.0000  0.0075  0.000000   10 -0.015812  0.000000
4       0.0000  0.0100  0.000000   10 -0.015682  0.000000
6       0.0000  0.0150  0.000000   10 -0.015422  0.000000
...        ...     ...       ...  ...       ...       ...
159995  0.9975  0.9875  0.878116   10  0.941845  0.879721
159996  0.9975  0.9900  0.877525   10  0.941469  0.879163
159997  0.9975  0.9925  0.876932   10  0.941092  0.878603
159998  0.9975  0.9950  0.876338   10  0.940714  0.878043
159999  0.9975  0.9975  0.875742   10  0.940336  0.877481

[153600 rows x 6 columns]

120000
400
80
0
2000
4000
6000
8000
10000
12000
14000
16000
18000
20000
22000
24000
26000
28000
30000
32000
34000
36000
38000
40000
42000
44000
46000
48000
50000
52000
54000
56000
58000
60000
62000
64000
66000
68000
70000
72000
74000
76000
78000
80000
82000
84000
86000
88000
90000
92000
94000
96000
98000
100000
102000
104000
106000
108000
110000
112000
114000
116000
118000
120000
122000
124000
126000
128000
130000
132000
134000
136000
138000
140000
142000
144000
146000
148000
150000
152000
154000
156000
158000

             x       y         z  rep    zmodel      zbms
1       0.0000  0.0025  0.000000   10 -0.000134  0.000000
2       0.0000  0.0050  0.000000   10 -0.000305  0.000000
3       0.0000  0.0075  0.000000   10 -0.000475  0.000000
4       0.0000  0.0100  0.000000   10 -0.000643  0.000000
6       0.0000  0.0150  0.000000   10 -0.000975  0.000000
...        ...     ...       ...  ...       ...       ...
159995  0.9975  0.9875  0.878116   10  0.883833  0.885679
159996  0.9975  0.9900  0.877525   10  0.883646  0.885127
159997  0.9975  0.9925  0.876932   10  0.883459  0.884574
159998  0.9975  0.9950  0.876338   10  0.883271  0.884019
159999  0.9975  0.9975  0.875742   10  0.883084  0.883463

[153600 rows x 6 columns]

120000
400
80
0
2000
4000
6000
8000
10000
12000
14000
16000
18000
20000
22000
24000
26000
28000
30000
32000
34000
36000
38000
40000
42000
44000
46000
48000
50000
52000
54000
56000
58000
60000
62000
64000
66000
68000
70000
72000
74000
76000
78000
80000
82000
84000
86000
88000
90000
92000
94000
96000
98000
100000
102000
104000
106000
108000
110000
112000
114000
116000
118000
120000
122000
124000
126000
128000
130000
132000
134000
136000
138000
140000
142000
144000
146000
148000
150000
152000
154000
156000
158000

<lambdifygenerated-7409>:2: RuntimeWarning: divide by zero encountered in divide
  return sin(_a6_*x)*cos(y/x)
<lambdifygenerated-7409>:2: RuntimeWarning: invalid value encountered in divide
  return sin(_a6_*x)*cos(y/x)
<lambdifygenerated-7409>:2: RuntimeWarning: invalid value encountered in cos
  return sin(_a6_*x)*cos(y/x)
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/nguyen_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-7410>:2: RuntimeWarning: divide by zero encountered in divide
  return sin(_a6_*x)*cos(y/x)
<lambdifygenerated-7410>:2: RuntimeWarning: invalid value encountered in divide
  return sin(_a6_*x)*cos(y/x)
<lambdifygenerated-7410>:2: RuntimeWarning: invalid value encountered in cos
  return sin(_a6_*x)*cos(y/x)

             x       y         z  rep    zmodel      zbms
1       0.0000  0.0025  0.000000   10 -0.018969  0.000000
2       0.0000  0.0050  0.000000   10 -0.019028  0.000000
3       0.0000  0.0075  0.000000   10 -0.019085  0.000000
4       0.0000  0.0100  0.000000   10 -0.019141  0.000000
6       0.0000  0.0150  0.000000   10 -0.019251  0.000000
...        ...     ...       ...  ...       ...       ...
159995  0.9975  0.9875  0.878116   10  0.852556  0.888547
159996  0.9975  0.9900  0.877525   10  0.851435  0.888007
159997  0.9975  0.9925  0.876932   10  0.850312  0.887466
159998  0.9975  0.9950  0.876338   10  0.849187  0.886923
159999  0.9975  0.9975  0.875742   10  0.848059  0.886380

[153600 rows x 6 columns]

120000
400
80
0
2000
4000
6000
8000
10000
12000
14000
16000
18000
20000
22000
24000
26000
28000
30000
32000
34000
36000
38000
40000
42000
44000
46000
48000
50000
52000
54000
56000
58000
60000
62000
64000
66000
68000
70000
72000
74000
76000
78000
80000
82000
84000
86000
88000
90000
92000
94000
96000
98000
100000
102000
104000
106000
108000
110000
112000
114000
116000
118000
120000
122000
124000
126000
128000
130000
132000
134000
136000
138000
140000
142000
144000
146000
148000
150000
152000
154000
156000
158000

<lambdifygenerated-7433>:2: RuntimeWarning: invalid value encountered in divide
  return sin(_a0_*x/(x**2 + x))
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/nguyen_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-7434>:2: RuntimeWarning: invalid value encountered in divide
  return sin(_a0_*x/(x**2 + x))
<lambdifygenerated-7435>:2: RuntimeWarning: invalid value encountered in divide
  return sin(_a0_*x/(x + y**2))
<lambdifygenerated-7436>:2: RuntimeWarning: invalid value encountered in divide
  return sin(_a0_*x/(x + y**2))

             x       y         z  rep    zmodel      zbms
1       0.0000  0.0025  0.000000   10 -0.023262  0.000000
2       0.0000  0.0050  0.000000   10 -0.023148  0.000000
3       0.0000  0.0075  0.000000   10 -0.023032  0.000000
4       0.0000  0.0100  0.000000   10 -0.022917  0.000000
6       0.0000  0.0150  0.000000   10 -0.022683  0.000000
...        ...     ...       ...  ...       ...       ...
159995  0.9975  0.9875  0.878116   10  1.002224  0.954769
159996  0.9975  0.9900  0.877525   10  1.001756  0.954479
159997  0.9975  0.9925  0.876932   10  1.001283  0.954188
159998  0.9975  0.9950  0.876338   10  1.000805  0.953896
159999  0.9975  0.9975  0.875742   10  1.000322  0.953603

[153600 rows x 6 columns]

120000
400
80
0
2000
4000
6000
8000
10000
12000
14000
16000
18000
20000
22000
24000
26000
28000
30000
32000
34000
36000
38000
40000
42000
44000
46000
48000
50000
52000
54000
56000
58000
60000
62000
64000
66000
68000
70000
72000
74000
76000
78000
80000
82000
84000
86000
88000
90000
92000
94000
96000
98000
100000
102000
104000
106000
108000
110000
112000
114000
116000
118000
120000
122000
124000
126000
128000
130000
132000
134000
136000
138000
140000
142000
144000
146000
148000
150000
152000
154000
156000
158000

             x       y         z  rep    zmodel      zbms
1       0.0000  0.0025  0.000000   10 -0.008985  0.000000
2       0.0000  0.0050  0.000000   10 -0.008861  0.000000
3       0.0000  0.0075  0.000000   10 -0.008737  0.000000
4       0.0000  0.0100  0.000000   10 -0.008614  0.000000
6       0.0000  0.0150  0.000000   10 -0.008369  0.000000
...        ...     ...       ...  ...       ...       ...
159995  0.9975  0.9875  0.878116   10  0.955496  0.955270
159996  0.9975  0.9900  0.877525   10  0.954994  0.954937
159997  0.9975  0.9925  0.876932   10  0.954491  0.954602
159998  0.9975  0.9950  0.876338   10  0.953987  0.954266
159999  0.9975  0.9975  0.875742   10  0.953482  0.953927

[153600 rows x 6 columns]

120000

<lambdifygenerated-7475>:2: RuntimeWarning: invalid value encountered in divide
  return sin(x)/x
<lambdifygenerated-7476>:2: RuntimeWarning: invalid value encountered in divide
  return sin(x)/x
<lambdifygenerated-7477>:2: RuntimeWarning: invalid value encountered in divide
  return sin(x**2)/x
<lambdifygenerated-7478>:2: RuntimeWarning: invalid value encountered in divide
  return sin(x**2)/x
<lambdifygenerated-7479>:2: RuntimeWarning: invalid value encountered in divide
  return sin(_a3_*x)/x
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/nguyen_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(
<lambdifygenerated-7480>:2: RuntimeWarning: invalid value encountered in divide
  return sin(_a3_*x)/x
<lambdifygenerated-7481>:2: RuntimeWarning: invalid value encountered in divide
  return sin(_a3_*x)/x
<lambdifygenerated-7482>:2: RuntimeWarning: invalid value encountered in divide
  return sin(_a3_*x)/x

400
80
0
2000
4000
6000
8000
10000
12000
14000
16000
18000
20000
22000
24000
26000
28000
30000
32000
34000
36000
38000
40000
42000
44000
46000
48000
50000
52000
54000
56000
58000
60000
62000
64000
66000
68000
70000
72000
74000
76000
78000
80000
82000
84000
86000
88000
90000
92000
94000
96000
98000
100000
102000
104000
106000
108000
110000
112000
114000
116000
118000
120000
122000
124000
126000
128000
130000
132000
134000
136000
138000
140000
142000
144000
146000
148000
150000
152000
154000
156000
158000

             x       y         z  rep    zmodel      zbms
1       0.0000  0.0025  0.000000   10 -0.014356  0.000000
2       0.0000  0.0050  0.000000   10 -0.014276  0.000000
3       0.0000  0.0075  0.000000   10 -0.014197  0.000000
4       0.0000  0.0100  0.000000   10 -0.014117  0.000000
6       0.0000  0.0150  0.000000   10 -0.013957  0.000000
...        ...     ...       ...  ...       ...       ...
159995  0.9975  0.9875  0.878116   10  0.952966  0.887248
159996  0.9975  0.9900  0.877525   10  0.952477  0.886726
159997  0.9975  0.9925  0.876932   10  0.951987  0.886203
159998  0.9975  0.9950  0.876338   10  0.951496  0.885679
159999  0.9975  0.9975  0.875742   10  0.951003  0.885154

[153600 rows x 6 columns]

120000
400
80
0
2000
4000
6000
8000
10000
12000
14000
16000
18000
20000
22000
24000
26000
28000
30000
32000
34000
36000
38000
40000
42000
44000
46000
48000
50000
52000
54000
56000
58000
60000
62000
64000
66000
68000
70000
72000
74000
76000
78000
80000
82000
84000
86000
88000
90000
92000
94000
96000
98000
100000
102000
104000
106000
108000
110000
112000
114000
116000
118000
120000
122000
124000
126000
128000
130000
132000
134000
136000
138000
140000
142000
144000
146000
148000
150000
152000
154000
156000
158000

             x       y         z  rep    zmodel      zbms
1       0.0000  0.0025  0.000000   10 -0.009541  0.000000
2       0.0000  0.0050  0.000000   10 -0.009565  0.000000
3       0.0000  0.0075  0.000000   10 -0.009587  0.000000
4       0.0000  0.0100  0.000000   10 -0.009610  0.000000
6       0.0000  0.0150  0.000000   10 -0.009653  0.000000
...        ...     ...       ...  ...       ...       ...
159995  0.9975  0.9875  0.878116   10  0.963240  0.956388
159996  0.9975  0.9900  0.877525   10  0.962949  0.956081
159997  0.9975  0.9925  0.876932   10  0.962657  0.955772
159998  0.9975  0.9950  0.876338   10  0.962365  0.955462
159999  0.9975  0.9975  0.875742   10  0.962072  0.955150

[153600 rows x 6 columns]

120000
400
80
0
2000
4000
6000
8000
10000
12000
14000
16000
18000
20000
22000
24000
26000
28000
30000
32000
34000
36000
38000
40000
42000
44000
46000
48000
50000
52000
54000
56000
58000
60000
62000
64000
66000
68000
70000
72000
74000
76000
78000
80000
82000
84000
86000
88000
90000
92000
94000
96000
98000
100000
102000
104000
106000
108000
110000
112000
114000
116000
118000
120000
122000
124000
126000
128000
130000
132000
134000
136000
138000
140000
142000
144000
146000
148000
150000
152000
154000
156000
158000

             x       y         z  rep    zmodel      zbms
1       0.0000  0.0025  0.000000   10 -0.005096  0.000000
2       0.0000  0.0050  0.000000   10 -0.005247  0.000000
3       0.0000  0.0075  0.000000   10 -0.005397  0.000000
4       0.0000  0.0100  0.000000   10 -0.005544  0.000000
6       0.0000  0.0150  0.000000   10 -0.005833  0.000000
...        ...     ...       ...  ...       ...       ...
159995  0.9975  0.9875  0.878116   10  0.965809  0.966501
159996  0.9975  0.9900  0.877525   10  0.965477  0.966355
159997  0.9975  0.9925  0.876932   10  0.965144  0.966208
159998  0.9975  0.9950  0.876338   10  0.964812  0.966061
159999  0.9975  0.9975  0.875742   10  0.964479  0.965913

[153600 rows x 6 columns]

120000
400
80
0
2000
4000
6000
8000
10000
12000
14000
16000
18000
20000
22000
24000
26000
28000
30000
32000
34000
36000
38000
40000
42000
44000
46000
48000
50000
52000
54000
56000
58000
60000
62000
64000
66000
68000
70000
72000
74000
76000
78000
80000
82000
84000
86000
88000
90000
92000
94000
96000
98000
100000
102000
104000
106000
108000
110000
112000
114000
116000
118000
120000
122000
124000
126000
128000
130000
132000
134000
136000
138000
140000
142000
144000
146000
148000
150000
152000
154000
156000
158000

<lambdifygenerated-7563>:2: RuntimeWarning: invalid value encountered in divide
  return sin(x + x/(x**2 + x))
<lambdifygenerated-7564>:2: RuntimeWarning: invalid value encountered in divide
  return sin(x + x/(x**2 + x))
<lambdifygenerated-7565>:2: RuntimeWarning: invalid value encountered in divide
  return sin(x + x/(x + y**2))
<lambdifygenerated-7566>:2: RuntimeWarning: invalid value encountered in divide
  return sin(x + x/(x + y**2))

             x       y         z  rep    zmodel      zbms
1       0.0000  0.0025  0.000000   10 -0.041502  0.000000
2       0.0000  0.0050  0.000000   10 -0.041095  0.000000
3       0.0000  0.0075  0.000000   10 -0.040693  0.000000
4       0.0000  0.0100  0.000000   10 -0.040295  0.000000
6       0.0000  0.0150  0.000000   10 -0.039512  0.000000
...        ...     ...       ...  ...       ...       ...
159995  0.9975  0.9875  0.878116   10  0.941112  0.970062
159996  0.9975  0.9900  0.877525   10  0.940626  0.969932
159997  0.9975  0.9925  0.876932   10  0.940140  0.969803
159998  0.9975  0.9950  0.876338   10  0.939652  0.969673
159999  0.9975  0.9975  0.875742   10  0.939165  0.969543

[153600 rows x 6 columns]

120000
400
80
0
2000
4000
6000
8000
10000
12000
14000
16000
18000
20000
22000
24000
26000
28000
30000
32000
34000
36000
38000
40000
42000
44000
46000
48000
50000
52000
54000
56000
58000
60000
62000
64000
66000
68000
70000
72000
74000
76000
78000
80000
82000
84000
86000
88000
90000
92000
94000
96000
98000
100000
102000
104000
106000
108000
110000
112000
114000
116000
118000
120000
122000
124000
126000
128000
130000
132000
134000
136000
138000
140000
142000
144000
146000
148000
150000
152000
154000
156000
158000

             x       y         z  rep    zmodel      zbms
1       0.0000  0.0025  0.000000   10  0.008239  0.000000
2       0.0000  0.0050  0.000000   10  0.008106  0.000000
3       0.0000  0.0075  0.000000   10  0.007973  0.000000
4       0.0000  0.0100  0.000000   10  0.007841  0.000000
6       0.0000  0.0150  0.000000   10  0.007578  0.000000
...        ...     ...       ...  ...       ...       ...
159995  0.9975  0.9875  0.878116   10  0.942604  0.884674
159996  0.9975  0.9900  0.877525   10  0.942144  0.884401
159997  0.9975  0.9925  0.876932   10  0.941684  0.884129
159998  0.9975  0.9950  0.876338   10  0.941222  0.883856
159999  0.9975  0.9975  0.875742   10  0.940759  0.883584

[153600 rows x 6 columns]

120000
400
80
0
2000
4000
6000
8000
10000
12000
14000
16000
18000
20000
22000
24000
26000
28000
30000
32000
34000
36000
38000
40000
42000
44000
46000
48000
50000
52000
54000
56000
58000
60000
62000
64000
66000
68000
70000
72000
74000
76000
78000
80000
82000
84000
86000
88000
90000
92000
94000
96000
98000
100000
102000
104000
106000
108000
110000
112000
114000
116000
118000
120000
122000
124000
126000
128000
130000
132000
134000
136000
138000
140000
142000
144000
146000
148000
150000
152000
154000
156000
158000

             x       y         z  rep    zmodel      zbms
1       0.0000  0.0025  0.000000   10  0.022094  0.000000
2       0.0000  0.0050  0.000000   10  0.022085  0.000000
3       0.0000  0.0075  0.000000   10  0.022075  0.000000
4       0.0000  0.0100  0.000000   10  0.022066  0.000000
6       0.0000  0.0150  0.000000   10  0.022046  0.000000
...        ...     ...       ...  ...       ...       ...
159995  0.9975  0.9875  0.878116   10  0.956605  0.956009
159996  0.9975  0.9900  0.877525   10  0.956266  0.955701
159997  0.9975  0.9925  0.876932   10  0.955927  0.955393
159998  0.9975  0.9950  0.876338   10  0.955588  0.955083
159999  0.9975  0.9975  0.875742   10  0.955248  0.954771

[153600 rows x 6 columns]

120000
400
80
0
2000
4000
6000
8000
10000
12000
14000
16000
18000
20000
22000
24000
26000
28000
30000
32000
34000
36000
38000
40000
42000
44000
46000
48000
50000
52000
54000
56000
58000
60000
62000
64000
66000
68000
70000
72000
74000
76000
78000
80000
82000
84000
86000
88000
90000
92000
94000
96000
98000
100000
102000
104000
106000
108000
110000
112000
114000
116000
118000
120000
122000
124000
126000
128000
130000
132000
134000
136000
138000
140000
142000
144000
146000
148000
150000
152000
154000
156000
158000

             x       y         z  rep    zmodel      zbms
1       0.0000  0.0025  0.000000   10 -0.005979  0.000000
2       0.0000  0.0050  0.000000   10 -0.006063  0.000000
3       0.0000  0.0075  0.000000   10 -0.006144  0.000000
4       0.0000  0.0100  0.000000   10 -0.006225  0.000000
6       0.0000  0.0150  0.000000   10 -0.006382  0.000000
...        ...     ...       ...  ...       ...       ...
159995  0.9975  0.9875  0.878116   10  0.793299  0.849516
159996  0.9975  0.9900  0.877525   10  0.792569  0.848419
159997  0.9975  0.9925  0.876932   10  0.791850  0.847318
159998  0.9975  0.9950  0.876338   10  0.791141  0.846210
159999  0.9975  0.9975  0.875742   10  0.790443  0.845098

[153600 rows x 6 columns]

120000
400
80
0
2000
4000
6000
8000
10000
12000
14000
16000
18000
20000
22000
24000
26000
28000
30000
32000
34000
36000
38000
40000
42000
44000
46000
48000
50000
52000
54000
56000
58000
60000
62000
64000
66000
68000
70000
72000
74000
76000
78000
80000
82000
84000
86000
88000
90000
92000
94000
96000
98000
100000
102000
104000
106000
108000
110000
112000
114000
116000
118000
120000
122000
124000
126000
128000
130000
132000
134000
136000
138000
140000
142000
144000
146000
148000
150000
152000
154000
156000
158000

             x       y         z  rep    zmodel      zbms
1       0.0000  0.0025  0.000000   10 -0.015526  0.000000
2       0.0000  0.0050  0.000000   10 -0.015395  0.000000
3       0.0000  0.0075  0.000000   10 -0.015264  0.000000
4       0.0000  0.0100  0.000000   10 -0.015133  0.000000
6       0.0000  0.0150  0.000000   10 -0.014874  0.000000
...        ...     ...       ...  ...       ...       ...
159995  0.9975  0.9875  0.878116   10  0.946240  0.957898
159996  0.9975  0.9900  0.877525   10  0.945820  0.957591
159997  0.9975  0.9925  0.876932   10  0.945399  0.957281
159998  0.9975  0.9950  0.876338   10  0.944977  0.956970
159999  0.9975  0.9975  0.875742   10  0.944555  0.956658

[153600 rows x 6 columns]

120000
400
80
0
2000
4000
6000
8000
10000
12000
14000
16000
18000
20000
22000
24000
26000
28000
30000
32000
34000
36000
38000
40000
42000
44000
46000
48000
50000
52000
54000
56000
58000
60000
62000
64000
66000
68000
70000
72000
74000
76000
78000
80000
82000
84000
86000
88000
90000
92000
94000
96000
98000
100000
102000
104000
106000
108000
110000
112000
114000
116000
118000
120000
122000
124000
126000
128000
130000
132000
134000
136000
138000
140000
142000
144000
146000
148000
150000
152000
154000
156000
158000

             x       y         z  rep    zmodel      zbms
1       0.0000  0.0025  0.000000   10 -0.025653  0.000000
2       0.0000  0.0050  0.000000   10 -0.025332  0.000000
3       0.0000  0.0075  0.000000   10 -0.025014  0.000000
4       0.0000  0.0100  0.000000   10 -0.024697  0.000000
6       0.0000  0.0150  0.000000   10 -0.024071  0.000000
...        ...     ...       ...  ...       ...       ...
159995  0.9975  0.9875  0.878116   10  0.958705  0.950914
159996  0.9975  0.9900  0.877525   10  0.958314  0.950574
159997  0.9975  0.9925  0.876932   10  0.957923  0.950232
159998  0.9975  0.9950  0.876338   10  0.957531  0.949889
159999  0.9975  0.9975  0.875742   10  0.957139  0.949545

[153600 rows x 6 columns]

120000

<lambdifygenerated-7705>:2: RuntimeWarning: divide by zero encountered in log
  return sin(y*log(y))
<lambdifygenerated-7705>:2: RuntimeWarning: invalid value encountered in multiply
  return sin(y*log(y))
<lambdifygenerated-7706>:2: RuntimeWarning: divide by zero encountered in log
  return sin(y*log(y))
<lambdifygenerated-7706>:2: RuntimeWarning: invalid value encountered in multiply
  return sin(y*log(y))
<lambdifygenerated-7707>:2: RuntimeWarning: divide by zero encountered in log
  return sin(y*log(2*y))
<lambdifygenerated-7707>:2: RuntimeWarning: invalid value encountered in multiply
  return sin(y*log(2*y))
<lambdifygenerated-7708>:2: RuntimeWarning: divide by zero encountered in log
  return sin(y*log(2*y))
<lambdifygenerated-7708>:2: RuntimeWarning: invalid value encountered in multiply
  return sin(y*log(2*y))

400
80
0
2000
4000
6000
8000
10000
12000
14000
16000
18000
20000
22000
24000
26000
28000
30000
32000
34000
36000
38000
40000
42000
44000
46000
48000
50000
52000
54000
56000
58000
60000
62000
64000
66000
68000
70000
72000
74000
76000
78000
80000
82000
84000
86000
88000
90000
92000
94000
96000
98000
100000
102000
104000
106000
108000
110000
112000
114000
116000
118000
120000
122000
124000
126000
128000
130000
132000
134000
136000
138000
140000
142000
144000
146000
148000
150000
152000
154000
156000
158000

             x       y         z  rep    zmodel      zbms
1       0.0000  0.0025  0.000000   10 -0.030196  0.000000
2       0.0000  0.0050  0.000000   10 -0.030035  0.000000
3       0.0000  0.0075  0.000000   10 -0.029873  0.000000
4       0.0000  0.0100  0.000000   10 -0.029712  0.000000
6       0.0000  0.0150  0.000000   10 -0.029388  0.000000
...        ...     ...       ...  ...       ...       ...
159995  0.9975  0.9875  0.878116   10  0.959993  0.950642
159996  0.9975  0.9900  0.877525   10  0.959578  0.950206
159997  0.9975  0.9925  0.876932   10  0.959163  0.949767
159998  0.9975  0.9950  0.876338   10  0.958747  0.949324
159999  0.9975  0.9975  0.875742   10  0.958329  0.948877

[153600 rows x 6 columns]

120000

<lambdifygenerated-7737>:2: RuntimeWarning: invalid value encountered in divide
  return x*(x + x/(x + y))
<lambdifygenerated-7738>:2: RuntimeWarning: invalid value encountered in divide
  return x*(x + x/(x + y))
/export/home/shared/Projects/ANN/Sergio/BMS_approximator/bin/nguyen_functions/../no_degeneracy/mcmc.py:654: OptimizeWarning: Covariance of the parameters could not be estimated
  res = curve_fit(

400
80
0
2000
4000
6000
8000
10000
12000
14000
16000
18000
20000
22000
24000
26000
28000
30000
32000
34000
36000
38000
40000
42000
44000
46000
48000
50000
52000
54000
56000
58000
60000
62000
64000
66000
68000
70000
72000
74000
76000
78000
80000
82000
84000
86000
88000
90000
92000
94000
96000
98000
100000
102000
104000
106000
108000
110000
112000
114000
116000
118000
120000
122000
124000
126000
128000
130000
132000
134000
136000
138000
140000
142000
144000
146000
148000
150000
152000
154000
156000
158000

             x       y         z  rep    zmodel      zbms
1       0.0000  0.0025  0.000000   10  0.005907  0.000000
2       0.0000  0.0050  0.000000   10  0.005869  0.000000
3       0.0000  0.0075  0.000000   10  0.005833  0.000000
4       0.0000  0.0100  0.000000   10  0.005799  0.000000
6       0.0000  0.0150  0.000000   10  0.005734  0.000000
...        ...     ...       ...  ...       ...       ...
159995  0.9975  0.9875  0.878116   10  1.055050  0.888792
159996  0.9975  0.9900  0.877525   10  1.054257  0.887678
159997  0.9975  0.9925  0.876932   10  1.053463  0.886559
159998  0.9975  0.9950  0.876338   10  1.052669  0.885438
159999  0.9975  0.9975  0.875742   10  1.051874  0.884312

[153600 rows x 6 columns]

120000
400
80
0
2000
4000
6000
8000
10000
12000
14000
16000
18000
20000
22000
24000
26000
28000
30000
32000
34000
36000
38000
40000
42000
44000
46000
48000
50000
52000
54000
56000
58000
60000
62000
64000
66000
68000
70000
72000
74000
76000
78000
80000
82000
84000
86000
88000
90000
92000
94000
96000
98000
100000
102000
104000
106000
108000
110000
112000
114000
116000
118000
120000
122000
124000
126000
128000
130000
132000
134000
136000
138000
140000
142000
144000
146000
148000
150000
152000
154000
156000
158000

             x       y         z  rep    zmodel      zbms
1       0.0000  0.0025  0.000000   10  0.013865  0.000000
2       0.0000  0.0050  0.000000   10  0.013874  0.000000
3       0.0000  0.0075  0.000000   10  0.013882  0.000000
4       0.0000  0.0100  0.000000   10  0.013891  0.000000
6       0.0000  0.0150  0.000000   10  0.013908  0.000000
...        ...     ...       ...  ...       ...       ...
159995  0.9975  0.9875  0.878116   10  0.927710  0.973935
159996  0.9975  0.9900  0.877525   10  0.927428  0.973867
159997  0.9975  0.9925  0.876932   10  0.927147  0.973800
159998  0.9975  0.9950  0.876338   10  0.926866  0.973733
159999  0.9975  0.9975  0.875742   10  0.926584  0.973665

[153600 rows x 6 columns]

120000
400
80
0
2000
4000
6000
8000
10000
12000
14000
16000
18000
20000
22000
24000
26000
28000
30000
32000
34000
36000
38000
40000
42000
44000
46000
48000
50000
52000
54000
56000
58000
60000
62000
64000
66000
68000
70000
72000
74000
76000
78000
80000
82000
84000
86000
88000
90000
92000
94000
96000
98000
100000
102000
104000
106000
108000
110000
112000
114000
116000
118000
120000
122000
124000
126000
128000
130000
132000
134000
136000
138000
140000
142000
144000
146000
148000
150000
152000
154000
156000
158000

             x       y         z  rep    zmodel      zbms
1       0.0000  0.0025  0.000000   10 -0.042756  0.000000
2       0.0000  0.0050  0.000000   10 -0.042657  0.000000
3       0.0000  0.0075  0.000000   10 -0.042556  0.000000
4       0.0000  0.0100  0.000000   10 -0.042455  0.000000
6       0.0000  0.0150  0.000000   10 -0.042251  0.000000
...        ...     ...       ...  ...       ...       ...
159995  0.9975  0.9875  0.878116   10  1.037785  0.947368
159996  0.9975  0.9900  0.877525   10  1.037475  0.947032
159997  0.9975  0.9925  0.876932   10  1.037162  0.946696
159998  0.9975  0.9950  0.876338   10  1.036846  0.946358
159999  0.9975  0.9975  0.875742   10  1.036528  0.946019

[153600 rows x 6 columns]

120000
400
80
0
2000
4000
6000
8000
10000
12000
14000
16000
18000
20000
22000
24000
26000
28000
30000
32000
34000
36000
38000
40000
42000
44000
46000
48000
50000
52000
54000
56000
58000
60000
62000
64000
66000
68000
70000
72000
74000
76000
78000
80000
82000
84000
86000
88000
90000
92000
94000
96000
98000
100000
102000
104000
106000
108000
110000
112000
114000
116000
118000
120000
122000
124000
126000
128000
130000
132000
134000
136000
138000
140000
142000
144000
146000
148000
150000
152000
154000
156000
158000

             x       y         z  rep    zmodel      zbms
1       0.0000  0.0025  0.000000   10 -0.007017  0.000000
2       0.0000  0.0050  0.000000   10 -0.007000  0.000000
3       0.0000  0.0075  0.000000   10 -0.006983  0.000000
4       0.0000  0.0100  0.000000   10 -0.006965  0.000000
6       0.0000  0.0150  0.000000   10 -0.006925  0.000000
...        ...     ...       ...  ...       ...       ...
159995  0.9975  0.9875  0.878116   10  0.961597  0.952449
159996  0.9975  0.9900  0.877525   10  0.961242  0.952107
159997  0.9975  0.9925  0.876932   10  0.960887  0.951763
159998  0.9975  0.9950  0.876338   10  0.960530  0.951418
159999  0.9975  0.9975  0.875742   10  0.960173  0.951072

[153600 rows x 6 columns]

120000
400
80
0
2000
4000
6000
8000
10000
12000
14000
16000
18000
20000
22000
24000
26000
28000
30000
32000
34000
36000
38000
40000
42000
44000
46000
48000
50000
52000
54000
56000
58000
60000
62000
64000
66000
68000
70000
72000
74000
76000
78000
80000
82000
84000
86000
88000
90000
92000
94000
96000
98000
100000
102000
104000
106000
108000
110000
112000
114000
116000
118000
120000
122000
124000
126000
128000
130000
132000
134000
136000
138000
140000
142000
144000
146000
148000
150000
152000
154000
156000
158000

             x       y         z  rep    zmodel      zbms
1       0.0000  0.0025  0.000000   10 -0.003326  0.000000
2       0.0000  0.0050  0.000000   10 -0.003359  0.000000
3       0.0000  0.0075  0.000000   10 -0.003392  0.000000
4       0.0000  0.0100  0.000000   10 -0.003424  0.000000
6       0.0000  0.0150  0.000000   10 -0.003489  0.000000
...        ...     ...       ...  ...       ...       ...
159995  0.9975  0.9875  0.878116   10  0.988273  0.968467
159996  0.9975  0.9900  0.877525   10  0.987788  0.968337
159997  0.9975  0.9925  0.876932   10  0.987303  0.968206
159998  0.9975  0.9950  0.876338   10  0.986816  0.968076
159999  0.9975  0.9975  0.875742   10  0.986329  0.967945

[153600 rows x 6 columns]

120000
400
80
0
2000
4000
6000
8000
10000
12000
14000
16000
18000
20000
22000
24000
26000
28000
30000
32000
34000
36000
38000
40000
42000
44000
46000
48000
50000
52000
54000
56000
58000
60000
62000
64000
66000
68000
70000
72000
74000
76000
78000
80000
82000
84000
86000
88000
90000
92000
94000
96000
98000
100000
102000
104000
106000
108000
110000
112000
114000
116000
118000
120000
122000
124000
126000
128000
130000
132000
134000
136000
138000
140000
142000
144000
146000
148000
150000
152000
154000
156000
158000

             x       y         z  rep    zmodel      zbms
1       0.0000  0.0025  0.000000   10 -0.025479  0.000000
2       0.0000  0.0050  0.000000   10 -0.025157  0.000000
3       0.0000  0.0075  0.000000   10 -0.024839  0.000000
4       0.0000  0.0100  0.000000   10 -0.024525  0.000000
6       0.0000  0.0150  0.000000   10 -0.023910  0.000000
...        ...     ...       ...  ...       ...       ...
159995  0.9975  0.9875  0.878116   10  0.984484  0.952571
159996  0.9975  0.9900  0.877525   10  0.984299  0.952266
159997  0.9975  0.9925  0.876932   10  0.984115  0.951959
159998  0.9975  0.9950  0.876338   10  0.983931  0.951651
159999  0.9975  0.9975  0.875742   10  0.983747  0.951342

[153600 rows x 6 columns]

120000

,sigma,function,mae_nn_interp.,mae_nn_extrap.,mae_mdl_interp.,mae_mdl_extrap.,rmse_nn_interp.,rmse_nn_extrap.,rmse_mdl_interp.,rmse_mdl_extrap.,r
0,0.00,1,0.003155,0.852872,1.233750e-16,6.661338e-16,0.004471,1.167822,1.968682e-16,8.514391e-16,0
1,0.00,1,0.003693,0.998788,1.183226e-16,4.797260e-16,0.004808,1.342675,2.084592e-16,7.405598e-16,1
2,0.00,1,0.002434,0.865053,1.411848e-16,8.662481e-16,0.003358,1.172886,2.380712e-16,1.114327e-15,2
3,0.02,1,0.010924,0.783363,3.273081e-03,2.350146e-01,0.013970,1.052788,6.553932e-03,2.940264e-01,0
4,0.02,1,0.004217,0.704566,1.770215e-03,1.752805e-02,0.005219,0.984614,2.444490e-03,1.886998e-02,1
...,...,...,...,...,...,...,...,...,...,...,...
160,0.18,10,0.004011,0.008843,6.389056e-03,2.007255e-02,0.005232,0.011983,9.177947e-03,3.037298e-02,1
161,0.18,10,0.008255,0.046167,5.506491e-03,1.378513e-02,0.010680,0.058829,7.237618e-03,2.012844e-02,2
162,0.20,10,0.007934,0.025464,5.719325e-03,2.097733e-02,0.010095,0.030987,6.870082e-03,2.536005e-02,0
163,0.20,10,0.003555,0.052856,4.559083e-03,1.973315e-02,0.004999,0.058217,6.785228e-03,2.852211e-02,1
164,0.20,10,0.007064,0.036017,5.978311e-03,1.565584e-02,0.008656,0.043592,6.713104e-03,2.230475e-02,2